Edwin - Added user classes to weekly summary report
OneCommunityGlobal/HighestGoodNetworkApp pull request #1042
Opened 2023-07-25 19:10 UTC by EdwinLauM

# Description

<img width="516" alt="Screen Shot 2023-07-25 at 12 04 08 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/42288987/9c2d188a-3b51-4357-a483-ae204e7f6991">

## Related PRS (if any):

This frontend PR is related to the BE PR [PR #458](https://github.com/OneCommunityGlobal/HGNRest/pull/458)

## Main changes explained:

- Made code changes to show the user class in the weekly summary report
- Added check to not display 'Volunteer' role
- Made slight changes to backend for weekly summary request to now include the users role

## How to test:

1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as any user that has the view weekly summary permission (Owner/Admin)
4. Dashboard -> Reports -> Weekly Summaries Report
5. Check that the user class for every user is shown on the right of the google docs icon
6. Users whose class is Volunteer, should not show since that is the default 

## Videos/Screenshots of changes:

<img width="813" alt="Screen Shot 2023-07-25 at 12 08 47 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/42288987/7a51ea3e-ffaf-42a5-9387-08ccbb60c7df">

2023-07-25 19:56 UTC, sxiong5 approved these changes
Hey, the feature worked as expected! Great job on the code style.

![Screenshot 2023-07-25 at 15 52 11](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/1e437c7c-51c3-416d-8e84-8cea5fbace77)

2023-07-25 23:22 UTC, BaileyM96 approved these changes
Hello @EdwinLauM I reviewed your PR and followed your directions, and everything works and looks great, great work!

## Screenshots

![PR #1042 user classes to weekly summary report](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/7c7f1a7f-7ca3-4838-ae53-773ad124d09b)

2023-07-26 01:11 UTC, veronicacheng2 approved these changes
Hi @EdwinLauM, I tested the PR and everything works as expected

Role Listing for roles other than Volunteer:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/5bb8d468-445a-4fc6-b4e3-852ed348c6e4)

2023-07-26 01:18 UTC, winghojackyli approved these changes
Hi @EdwinLauM , I tested your PR and it works great. Using admin account, I can see the roles of users near the google icon except for volunteer. 

![1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/ac71cb3b-a7b0-44d9-bb19-d5d23f58435b)

2023-07-26 10:51 UTC, beblicarl commented
This functionality works as expected but the dev environment lags way too much. I am sure it's a general problem

![issue #1042](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/4e50b2ca-0e33-4ed6-b3c4-1fe88065f6d8)

2023-07-26 18:04 UTC, Shreyj14 commented
Hi @EdwinLauM everything worked great!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/020d90f2-4653-42b0-9f6b-d2cdd0cabbaa

2023-07-26 18:05 UTC, Shreyj14 approved these changes

2023-07-26 19:26 UTC, iTvX commented
I have tested your PR, and everything looks good. Great job!
<img width="732" alt="CleanShot 2023-07-26 at 12 25 49@2x" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/06b556cf-c15c-4511-85c0-a16648e1adb6">

2023-07-26 19:30 UTC, eduvarjaor approved these changes
This feature works as intended. Great job!
![Screenshot_1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/c4961cee-5f27-4112-8b02-45392c37c20c)

2023-07-26 22:19 UTC, igorrochadasilva approved these changes
Hi @EdwinLauM !
I hope you are well =D 
I tested your PR and everything works correcty, congratulations and great job!
![1042_01_weekly-summary-report class showed](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/2a91d9ae-963e-489a-88d0-e12755e7f480)

2023-07-26 23:11 UTC, DavidC0126 approved these changes
Hi @EdwinLauM ,
I tested your PR and it works as intended. Nice job!
<img width="1674" alt="user_classes" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/662e6ef5-b913-40a0-b7bb-30fd8dd3ad7a">

2023-07-27 06:20 UTC, mounica-dingari-by commented
Hi @EdwinLauM , I've tested this PR and it works as expected. Great Job!

![Screenshot from 2023-07-26 23-18-54](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49270410/0be601a6-db24-4404-a5d7-628bbde15bf7)

2023-07-27 14:06 UTC, xaanders approved these changes
Hi @EdwinLauM ! I've tested it and it works good! All the classes are shown. Good job.
![1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/7d20c5da-a56e-4c63-b90e-45ea973f76a7)

2023-07-27 22:14 UTC, AnishPandita commented
Hi @EdwinLauM, tested the feature and it works well.
<img width="1156" alt="Screenshot 2023-07-27 at 3 13 35 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/385f72d9-c773-44f1-8af7-10491f6b11e3">

2023-07-28 13:34 UTC, vemanamadhu approved these changes
Everything looks good and works as expected. Good job.
![PR_1042](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13665284/36f99202-abca-47d1-a6c1-9da32eea9a00)

I had one question though:
1. Why isn't there a separate field called role. Wouldnt that be more readable? Because when I first opened the page I had to look for some time for changes that were made.

Let me know what you think @EdwinLauM and @one-community

2023-07-28 15:51 UTC, yaow62023 reviewed
I tested your PR, and most of the features work fine. However, there is one issue where the position is not being displayed within the parentheses. Strangely, some reviews show the role inside the parentheses, while others do not. Check the screen shoot I provided. 

<img width="1404" alt="Screenshot 2023-07-28 at 11 46 29 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/3575a663-46e6-4419-b6d1-b78f0fe9971d">

2023-07-28 16:09 UTC, iTvX commented on src/components/WeeklySummariesReport/FormattedReport.jsx
> +                <b>&nbsp;&nbsp;{summary.role !== 'Volunteer' && `(${summary.role})`}</b>
Maybe use CSS will better than using &nbsp;&nbsp. For example, classname the code google, and write the css below:
`.google {
  margin-left: 10px;
}`

2023-07-28 22:34 UTC, mahamakhan approved these changes
Works as mentioned.
<img width="368" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/c6480871-e1f9-4293-a307-ad019cd1ff25">

2023-07-28 22:51 UTC, zuhang2000 commented
Hi Edwin @EdwinLauM ! I tested your PR following the instructions on both backend and frontend. Everything works as expected! I am able to see different roles beside people's names.
<img width="1502" alt="Screen Shot 2023-07-28 at 3 06 00 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/af4af451-68b1-498c-a4de-9642442ba4e6">

2023-07-28 22:55 UTC, zuhang2000 approved these changes
Everything work as expected! I test both the front-end and back-end. The roles are shown properly.
<img width="1502" alt="Screen Shot 2023-07-28 at 3 06 00 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/8fb80fcb-327c-4f00-bdc6-83f44923e98f">

2023-07-29 00:19 UTC, shiva2096 approved these changes
Hi @EdwinLauM 

Great work! Functionality is working as expected.

![Screenshot 2023-07-28 at 8 18 19 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/9254d4df-ea3b-40e8-8951-6eed8d1ef18a)

2023-07-29 05:22 UTC, ramyaram2092 requested changes
Hello @EdwinLauM  i see  some glitch . Its unable to fetch the  class name . Could you take a look at this 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/81664904-4f73-45fa-b236-d0872833d5da)

2023-07-29 05:22 UTC, Lucas-E commented
Thank you everyone! Moving this one to final review!

2023-07-29 07:58 UTC, merged

2023-07-29 18:41 UTC, EdwinLauM commented
> Hello @EdwinLauM i see some glitch . Its unable to fetch the class name . Could you take a look at this ![image](https://user-images.githubusercontent.com/89441435/256965407-81664904-4f73-45fa-b236-d0872833d5da.png)

Hey @ramyaram2092, are you running this frontend with its respective backend PR?