update user permission management
OneCommunityGlobal/HighestGoodNetworkApp pull request #1074
Opened 2023-07-30 07:35 UTC by juneluo

# Description
7. (PRIORITY MEDIUM) Oleksandr/Jae: Make Manage User Permissions modal window show existing
If the user chosen is an Admin or other class with permissions, those permissions should show.
Changing that person's permissions should save the person as having custom permissions.
If the person's role is then changed though, it should reset that person's permissions to whatever their new role is

## Main changes explained:
- Show the permissions (from the role itself) in the list of the 'Manage User Permissions' modal, if the permission is not included in the role, an Owner can add/remove (customize) the frontPermissions to a specific user without changing the rules for the whole group of this role.
- Reset all the permissions to default if a person's role is changed (remove the customized frontPermissions)
- add key to the option in the list to avoid the warning

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as Owner user (only owner role can edit)
4. go to dashboard→ Other Links -› Permissions Management -› 'Manage User Permissions' Button
5. select any user to see its permission list

## Screenshots or videos of changes:
go to dashboard→ Other Links -› Permissions Management -› click the 'Manager' to view its default permission:
<img width="474" alt="2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/9314962/d12ecd3a-3db2-4512-ac1d-874287ace065">
Permissions Management -› 'Manage User Permissions' Button ->select a user who is a manager:
<img width="500" alt="1" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/9314962/856cf69c-1efd-4c5c-858a-c4639c84ee7e">
As the screen shot above shows: it will show the default permissions as well as the permissions that can be edit. The changes (add/remove) saved in this component will not affect the whole manager group but just this user.

However, if a user who has some customized permissions changes its role in the user profile page, for example from manager to volunteer, the front permissions saved before will be all removed and the user will have default permissions as a volunteer.
<img width="598" alt="3" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/9314962/74fc0287-30b5-48b1-a0a2-e027d76aa03d">

2023-07-30 12:31 UTC, beblicarl commented
This functionality works and the code looks great as well.

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.07.30-11_47_00.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/f0313edd-470e-436b-9014-4a6d924c7645)

2023-07-31 14:52 UTC, sxiong5 submitted a review, later dismissed
Hey @juneluo, I have tested this PR, and it worked well!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/701bebc2-925c-4c9a-98b5-06ea0c784460

2023-07-31 15:24 UTC, yurisokolovicz requested changes
Dear,

The new functionality is working fine for me. I checked the video before and after and also tried changing the user permissions for different admin users. I just think the code could be optimized to make it more readable and secure, as requested below.

In the following code: 
By using let, you allow the permissions variable to be reassigned to a new value, which is unnecessary in this case. Since the value of permissions is only set once within the conditional block and is not reassigned later, using const is more appropriate and makes the code more readable and secure.

useEffect(() => {
    getAllUsers();
    if (actualUserProfile?.role && roles) {
      const roleIndex = roles?.findIndex(({ roleName }) => roleName === actualUserProfile?.role);
      let permissions = [];
      if (roleIndex !== -1) {
        permissions = roles[roleIndex].permissions;
      }
      setActualUserRolePermission(permissions);
    }
  }, [actualUserProfile]);

Good job

Before

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/1c6f3a7b-3efe-4f18-a885-5c04f7a5cb74

After 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/5b3c0d0c-129f-449a-8bfa-9410392f989f


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/d00559b7-52b5-4e67-93ef-e29e80781ffa

2023-07-31 19:51 UTC, veronicacheng2 approved these changes
Hi @juneluo, I have tested the PR and everything works as intended.

Testing points: 
1. Changing the permission of a specific role will not affect the permission of the entire role group
2. After changing the role of the user and resetting it back, the previously assigned permission will be lost and reset to the default permission associated with the role group

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/d1dbdd37-6166-4d19-9ef0-9d3c6b1ae075

2023-07-31 20:41 UTC, juneluo commented on src/components/PermissionsManagement/UserPermissionsPopUp.jsx
> +    }
Thank you very much for the detailed review. The code has been updated as suggested.

2023-07-31 21:00 UTC, winghojackyli approved these changes
Hi @juneluo , I've tested the PR and it works great. 

Changing individual user's permisson does not change the role's permission. 
Changing individual user's role resets the permission of that role. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/7c5c743e-4534-405c-b88c-4c3f96184c0f

2023-07-31 21:24 UTC, DavidC0126 approved these changes
I have tested the PR and it works as described.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/12983404-4e2d-4038-8741-964efdfabb4e

2023-08-01 00:10 UTC, yurisokolovicz approved these changes
Perfect!

2023-08-01 18:18 UTC, sxiong5 approved these changes

2023-08-02 00:33 UTC, joyceiphone approved these changes
LGTM. 
<img width="661" alt="Screen Shot 2023-08-01 at 8 30 01 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60331390/2294bb30-8599-4317-bc5e-a4556864d010">

2023-08-02 16:09 UTC, eduvarjaor approved these changes
Everything working as intended. Great job @juneluo ! 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/144a44d7-3035-49c9-be52-caa2e52ab786

2023-08-03 05:22 UTC, n0vay reviewed
Tested the changes, works as intended. Good Job!
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85691749/048720f5-44af-4f04-9b1a-ddc3a702ba7a)
I am also getting a memory leak in console but I dont know if this PR is causing that.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85691749/b577fa5f-ef4f-4f38-af3c-7198b57ab7bc)

2023-08-05 00:05 UTC, TheDescendant39 approved these changes
Hi @juneluo, I performed the test based on the following steps and everything worked well. Well done.

1. Checked the Manager Default permissions
2. Verified that user "Vansh Manager" had the same permissions. 
3. Added permission only to "Vansh Manager" and verified that it did not change the default manager permissions.
4. Added permission to the manager role and verified that it reflected in the "Vansh Manager" user as well.
5. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/a5a44a36-0b26-4f4a-b47a-975f2ce466ac

6. Changed the role for "Vansh Manager" to "Volunteer" and verified that the default permissions for Volunteer matched the newly changed user. 
7. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/90491e25-c316-4b30-9388-90be8b955379

2023-08-05 21:29 UTC, zuhang2000 requested changes
Hi I've tested your PR. However if I log in as a Volunteer account, it's reporting error whenever going to the dashboard page. Please check on this problem. Although this PR is for Owner role, Volunteer account should operate without a problem. 
<img width="1512" alt="Screen Shot 2023-08-05 at 2 23 58 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/eb15ca94-ffa7-451b-91dd-8a761075588e">

2023-08-05 22:36 UTC, ramyaram2092 approved these changes
Works as expected. Good Job 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/71728878-a735-4143-b08a-fea13b761f7b

2023-08-06 02:13 UTC, EdwinLauM approved these changes
Hey @juneluo! The changes work as expected! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/b1a27368-d423-4b11-a79d-d32e8004c510

2023-08-06 16:23 UTC, one-community commented
Thank you all, merging!

2023-08-06 16:23 UTC, merged

2023-08-06 16:35 UTC, one-community commented
Merged this to Dev and am seeing this... is anyone else seeing this? 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/18335122/4f7c4884-4516-409d-b747-bdf75160e8ed)

2023-08-06 16:44 UTC, one-community commented
I should be able to still remove permissions from a person… it should just be auto-populated with whatever their role assigned them… then, if they edit anything, their permissions should be saved as custom permissions separate from their role. If they then change roles (rare), it should reset their permissions to whatever their new role is. Does this make sense?

2023-08-07 00:12 UTC, juneluo commented
> I should be able to still remove permissions from a person… it should just be auto-populated with whatever their role assigned them… then, if they edit anything, their permissions should be saved as custom permissions separate from their role. If they then change roles (rare), it should reset their permissions to whatever their new role is. Does this make sense?

The pop up 'manage user permission' component is designed for frontend/customized permission, which is completely different from the permissions brought by the role itself (which can be modified by changing the rules for the role). Therefore, when we click the button, we can see permissions given by the role without editing buttons, then we can add/remove customized permissions to the rest.
For example, the reason why most of the buttons are gone in your screenshot is that the user you select is an owner, who by default has most of the permissions and those permissions should not be removed by others. If you check other users who are volunteer or manager, most of the permissions will show the add/remove button that are open to edit.
Also, changing the roles on the user profile page will erase all the front permissions given to the user and they will only have the default permissions given by the new role.