create PR
OneCommunityGlobal/HighestGoodNetworkApp pull request #1173
Opened 2023-08-25 02:40 UTC by Lin1404

# Description
(PRIORITY HIGH) Jae: Make tasks list only suggest active members(WIP Haohui)
Other Links -> Projects -> WBS -> Pick any -> Add Task -> Resources
Reminder a person has to be a member of the Project (can be added on Profile Page, Projects Management, or during setup) to be added to a task within the Project
This list used to show only active team members. Please help restore this limitation, no need to see inactive members in this list, it slows the selection process. 
Anyone taking this should be able to finish it this week. If not, I'll have Xiao W do it next week. It'll take him less than a couple hours.

## Main changes explained:
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin/owner user
4. go to Other Links -> Projects -> WBS -> Pick any -> Add Task -> Resources…

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2023-08-26 22:46 UTC, Lin1404 commented
**Videos of changes:**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/9b4df178-3277-4232-9f51-036eca8de8af

2023-08-27 00:52 UTC, veronicacheng2 submitted a review, later dismissed
Hi @Lin1404, I have tested the PR and the function works as intended. After I set the member to inactive, I am not able to see that member in the task list suggestion anymore.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/ad698b5e-b817-4b4d-b27e-0a809e6bed13

2023-08-28 22:43 UTC, tsunami776 submitted a review, later dismissed
I have tested the PR with an owner account. The member suggestion functionality works as intended, and the task list now only suggests active members of the team. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/1f909341-3db9-4264-bbff-8a6b3df35a3c

2023-08-29 22:00 UTC, GaryB93 requested changes
The intended functionality works for adding tasks but not for editing preexisting tasks. When you set a team member to inactive you can still see that team member in the task resources list when editing a preexisting task.

Also, just something to think about. It seems like it would be more intuitive to have the task resource list be  a dropdown menu vs typing in it to see the list. I know this was how it functioned before but every time I go to add resources to a task my first thought is to click on the input field to select from a dropdown but then I have to type in the input field to be able to see the list.

![Screenshot 2023-08-29 at 4 45 42 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/3109c4d6-3a12-4a98-a0de-0374f9f69729)

![Screenshot 2023-08-29 at 4 47 09 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/30276111-52cd-46be-b284-6216f7a58471)

![Screenshot 2023-08-29 at 4 50 39 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/f628a10c-7900-4c0c-a45d-1b68cd058c3a)

2023-08-30 00:54 UTC, one-community commented
> It seems like it would be more intuitive to have the task resource list be a dropdown menu vs typing in it to see the list.

Typing as it is is my preference. A dropdown list is too huge.

2023-08-30 05:04 UTC, DavidC0126 reviewed
Hi @Lin1404 I tested your PR and it works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/ca0b9d56-5f65-4168-9901-232ee6dca990

2023-08-30 06:33 UTC, Haoj1 submitted a review, later dismissed
@Lin1404 Add task list successfully has inactive users disappeared. Great job! But it is wired that in current BE dev there is no "add WBS" in project page. I switch to the previous BE branch which works for me 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/f5b22804-1369-4a87-b87b-12fa66e361d2

2023-08-30 20:19 UTC, Jiyuanxia commented
Hello, @Lin1404. I have reviewed your pull request and conducted some tests. It appears that there are a few issues that you should address in your branch. These might not be problems directly related to your code itself. I am unable to deactivate my account when using the volunteer and owner roles. Consequently, I can only test the admin role to determine its functionality. It does indeed work; upon deactivating my account, it no longer appears in the list. You've done well in this regard.
However, I've noticed that in this branch, when I log in with the owner role, I am unable to see the tabs for other links.

Before inactive
![Screenshot 2023-08-30 161017](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/87cfb891-2902-4985-bb7e-b7a2f72295e5)
After inactive
![Screenshot 2023-08-30 161141](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/6e5c76f5-8003-4892-a633-3ef143256530)

2023-08-31 14:04 UTC, Lin1404 commented
> The intended functionality works for adding tasks but not for editing preexisting tasks. When you set a team member to inactive you can still see that team member in the task resources list when editing a preexisting task.
> 
> Also, just something to think about. It seems like it would be more intuitive to have the task resource list be a dropdown menu vs typing in it to see the list. I know this was how it functioned before but every time I go to add resources to a task my first thought is to click on the input field to select from a dropdown but then I have to type in the input field to be able to see the list.
> 
> ![Screenshot 2023-08-29 at 4 45 42 PM](https://user-images.githubusercontent.com/108501006/264170278-3109c4d6-3a12-4a98-a0de-0374f9f69729.png)
> 
> ![Screenshot 2023-08-29 at 4 47 09 PM](https://user-images.githubusercontent.com/108501006/264170329-30276111-52cd-46be-b284-6216f7a58471.png)
> 
> ![Screenshot 2023-08-29 at 4 50 39 PM](https://user-images.githubusercontent.com/108501006/264170368-f628a10c-7900-4c0c-a45d-1b68cd058c3a.png)

Hi Gary,

Thanks for the edge case report. This problem should be fixed right now.

2023-08-31 14:09 UTC, Lin1404 commented
> Hello, @Lin1404. I have reviewed your pull request and conducted some tests. It appears that there are a few issues that you should address in your branch. These might not be problems directly related to your code itself. I am unable to deactivate my account when using the volunteer and owner roles. Consequently, I can only test the admin role to determine its functionality. It does indeed work; upon deactivating my account, it no longer appears in the list. You've done well in this regard. However, I've noticed that in this branch, when I log in with the owner role, I am unable to see the tabs for other links.
> 
> Before inactive ![Screenshot 2023-08-30 161017](https://user-images.githubusercontent.com/92963742/264463530-87cfb891-2902-4985-bb7e-b7a2f72295e5.png) After inactive ![Screenshot 2023-08-30 161141](https://user-images.githubusercontent.com/92963742/264463531-6e5c76f5-8003-4892-a633-3ef143256530.png)

Hi @Jiyuanxia , thanks for the review comment. I think the reason is because your owner account downgrade to volunteer role. Jae has mentioned this in coding-problem channel in slack. You can DM him to ask help to upgrade it again.

2023-08-31 20:25 UTC, tsunami776 approved these changes
I tested the latest code, and the edge case found by @GaryB93 is now fixed. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/fe1df1ff-c0b0-4f57-98fd-f19130cc2843

2023-09-01 19:26 UTC, harshidad reviewed
I tested the PR with an Admin account. I folllow the steps as mentioned in PR and functionality works as intended. The task list now only shows the  active members of the team.

Only thing I additionally observed is the older task, still shows the inactive users. So is it intended? Please see the attched video. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/a59e833e-5d59-43e6-8649-b4af4f9dc95b

2023-09-02 03:49 UTC, EdwinLauM approved these changes
Hey @Lin1404! I have tested your PR and works as expected! Code changes look good as well!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/0c57901a-e548-4b5d-a7c6-2650065af521

2023-09-05 03:48 UTC, one-community commented
Thank you everyone, merging!

2023-09-05 03:48 UTC, merged