Zuhang fix team management alert if user already exists
OneCommunityGlobal/HighestGoodNetworkApp pull request #1185
Opened 2023-08-27 03:58 UTC by zuhang2000

# Description
(PRIORITY MEDIUM) Jae: Fix Team Management alert if user already exists
a. Other Links -> Teams -> Choose Team → Members → Add Existing
b. If you try to add an existing member, it says “Please choose a valid user.” It should say, “Member is already a part of this team.”

## Main changes explained:
- Address a bug in file src/components/Teams/MembersAutoComplete.jsx.
- Update file src/components/Teams/TeamMembersPopup.jsx. Adding a new state called "duplicateUserAlert" to detect duplicate member.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user
4. go to dashboard→ Other Links→ Teams→Members
5. Add new members or existing members

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/4cb27aa9-2b9d-48d5-82af-8c5e3047c396

2023-08-27 04:08 UTC, winghojackyli submitted a review, later dismissed
Hi @zuhang2000 , I've tested this PR and it works as intended. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/d998a80e-28e0-4218-a4f3-d464fdcbfbd8

2023-08-28 00:06 UTC, Arsamat commented
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67019552/e8634d71-0673-4191-a389-e6062fe56b55

@zuhang2000 Tested the functionality. Works as expected!

2023-08-28 04:07 UTC, luisarevalo21 commented
Hello @zuhang2000 
I tried to test your branch but I am missing the links in the Navbar. 
This was a bug that started last Monday, any suggestions on fixing it?
When it happened to my branch, I had to reset my entire development environment. 


<img width="1603" alt="Screenshot 2023-08-27 at 9 06 20 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/49635de7-c381-4b4a-9f5e-55db0f998780">

2023-08-28 18:41 UTC, tsunami776 commented
I had the same issue as @luisarevalo21. The links in the navigation are missing for me, and FE dev branch has those links. 

![PR Review #1185](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/76cf802f-32cb-4a09-9b8e-e18e90ed080e)

2023-08-28 19:14 UTC, harshidad submitted a review, later dismissed
Changes looks Good!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/b118dc71-9746-4954-b7eb-e2b501674164

2023-08-28 23:25 UTC, yurisokolovicz reviewed
Dear @zuhang2000 

I am also experiencing the issue reported in the error section regarding the absence of "other links". I have tried clearing the cache and following the normal procedures, but it still is not working.


![Screenshot 2023-08-28 232155](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/1f118f98-f42e-4263-9a60-8776e6b3287c)

2023-08-29 05:13 UTC, luisarevalo21 commented
> I had the same issue as @luisarevalo21. The links in the navigation are missing for me, and FE dev branch has those links.
> 
> UPDATE: I made it work by checkout an old commit with detached HEAD on dd8809c for BE. The features work as described in the PR.
> 
> ![PR Review #1185](https://user-images.githubusercontent.com/43768723/263796548-76cf802f-32cb-4a09-9b8e-e18e90ed080e.png)
> 
>  PR.Review.1185.mp4

Hello can you explain exactly, how you resolved the missing links in the navbar?

2023-08-29 05:41 UTC, tsunami776 commented
@luisarevalo21 First of all, I do not think my method is a fix to this. It only made it work to test it. And here is how I did it through GitHub Desktop as shown in the screenshot. I just checkout an old back end commit from 10 days ago. That was all I did.

<img width="883" alt="Screenshot 2023-08-29" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/db3837d2-2b15-4ea7-a695-b0df7f64582a">

2023-08-29 06:00 UTC, navneeeth submitted a review, later dismissed
LGTM! Initially faced the issue with 'Other Links' not showing up. Removing the cache and reloading the page did not help. Followed @tsunami776 's steps to checkout to the 'dd8809c' commit for the BE and it worked as a fix.

The PR works as intended. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/58464e18-bf12-4972-9861-c7cd3052619e

2023-08-30 00:50 UTC, AnishPandita commented
Hey, the PR works well. Tried adding new user and already existing user.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/5d4c66e6-a4b8-4d1e-8d64-9e3eb6aaa4d1

2023-08-30 01:29 UTC, DavidC0126 approved these changes, later dismissed
Hi @zuhang2000 I tested your PR and it works as intended.

<img width="1664" alt="already_exist_alert" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/2e718ce3-540b-41ed-9094-7fd7e85610b4">

2023-08-30 02:53 UTC, Haoj1 submitted a review, later dismissed
@zuhang2000 Good job! Alert when add existing members. Refresh did not fix the other link disappeared issues. I try @tsunami776 solutions and switch to previous BE commit works for me. Perhaps some bugs are merged into current BE dev.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/56e4a1dc-9965-4ae0-8e23-c3fd40f44b18

2023-08-30 17:32 UTC, vinaykumarh reviewed
I have reviewed the PR.
As mentioned by earlier reviewers the nav links are missing along with logout button on profile page. I can see conflicts in the branch, please resolve it.
As for the PR it is working as expected. One thing I observed is the username is getting cleared in new fix whereas it is persist in search bar in old functionality. I believe keeping it in the search bar will be useful.
Attached screenshot!

Before:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92617693/37659880-7957-413b-be6d-e554abeadbf0)

After:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92617693/e38c37c0-6a55-49d0-821f-e205e7d2b7a4)

Nav missing:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92617693/8b89e7ec-dcfb-4bf9-800e-21d67c34a880)

2023-08-30 18:44 UTC, Indujaks submitted a review, later dismissed
Tested your PR, it works as expected, I tried adding a existing team member and the error is shown!
<img width="1324" alt="Screenshot 2023-08-30 at 11 40 28 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/11251850/8a5e2c8b-971c-4cb8-bb22-b4526ef87da1">

2023-08-30 20:05 UTC, yurisokolovicz requested changes, later dismissed
Dear @zuhang2000 

I'm also encountering the problem mentioned in the error section, where the "other links" are missing. I attempted to clear the cache (using "Empty Cache and Hard Reload") and followed the usual steps, but the issue persists. Even creating another owner account didn't fix the problem (this approach worked for other PRs). As a result, we must be cautious before merging this into the development branch.


![Screenshot 2023-08-30 195524](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/ae8ff556-87db-4567-a2b9-d4d8a58babb0)

2023-08-30 21:30 UTC, Jiyuanxia commented
Hi, @zuhang2000 , I met the same issue that the tab for other links is missing.

![Screenshot 2023-08-30 172845](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/cbb7b020-33c1-4ffb-ac03-32a59e234611)

2023-09-01 08:27 UTC, Chuehleo submitted a review, later dismissed
Everything works as expected, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/32e868ac-05d9-4c65-8e92-9b989de7c686

2023-09-01 13:07 UTC, gabi-lima approved these changes, later dismissed
Well done.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74115277/08136846-01e5-49c0-8a17-d358f5cde96d)

2023-09-01 19:04 UTC, zuhang2000 commented
> Dear @zuhang2000
> 
> I'm also encountering the problem mentioned in the error section, where the "other links" are missing. I attempted to clear the cache (using "Empty Cache and Hard Reload") and followed the usual steps, but the issue persists. Even creating another owner account didn't fix the problem (this approach worked for other PRs).
> 
> ![Screenshot 2023-08-30 195524](https://user-images.githubusercontent.com/121908988/264458151-ae8ff556-87db-4567-a2b9-d4d8a58babb0.png)

I would it say it's probably the problem with the most recent back-end development branch. I also encounter similar issue when reviewing other PRs. Could you please test with older back-end? I believe this problem is not related to this PR.

2023-09-03 01:42 UTC, ramyaram2092 approved these changes, later dismissed
Works as expected . Good job 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/5f48c25c-bac3-4611-8ea2-6def047fbcb8

2023-09-07 21:05 UTC, GaryB93 requested changes
I too am unable to access the Other Links to test this PR. I know this has been fixed so merging current development branch to this branch should fix this issue.

![Screenshot 2023-09-07 at 3 55 02 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/1b8c8f62-221d-4496-a259-2b990b03b1fd)

![Screenshot 2023-09-07 at 4 02 26 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/257a1102-f715-4eaf-9b74-baf1d22a802c)

2023-09-13 20:53 UTC, zuhang2000 commented
> I too am unable to access the Other Links to test this PR. I know this has been fixed so merging current development branch to this branch should fix this issue.
> 
> ![Screenshot 2023-09-07 at 3 55 02 PM](https://user-images.githubusercontent.com/108501006/266441323-1b8c8f62-221d-4496-a259-2b990b03b1fd.png)
> 
> ![Screenshot 2023-09-07 at 4 02 26 PM](https://user-images.githubusercontent.com/108501006/266441357-257a1102-f715-4eaf-9b74-baf1d22a802c.png)

I have solved merge conflicts. And I have merged current dev branch. The problem is now fixed. Please check on that! Thank you so much!

2023-09-14 18:04 UTC, GaryB93 submitted a review, later dismissed
Hi @zuhang2000, great work on implementing the error message upon trying to add a member to a team they are already a member of. I tested this under an Admin and Owner role and it works flawlessly.
![Screenshot 2023-09-14 at 12 54 43 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/75086755-b8ba-4dbd-9996-fb586d538876)

2023-09-16 02:53 UTC, Shubhu0 commented
Tested PR, error messages being displayed correctly.

2023-09-16 21:11 UTC, Sssky-18 approved these changes
Hi @zuhang2000 , just tested this PR and the feature worked fine for me. I tried to add an existing member, and the warning text displayed correctly. 
<img width="831" alt="PR#1185" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/7a192728-566d-406a-801d-e7e787f920d0">

2023-09-29 22:01 UTC, Shubhu0 commented
Hi @zuhang2000 reviewed the PR and it is working as intended. 

Created and added a new member
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/8475037a-d02e-43f0-87f7-f9b9ec589eea)

Tested for adding and already added member
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/7dc0a59d-997a-4714-981e-23c1e8ff251b)

2023-09-30 23:20 UTC, RheaWu1212 commented
works really well except my network was slowwww

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/7a012c78-d347-49f5-833a-9cc7ae1d4df5

2023-10-03 05:03 UTC, Bhagyashree444 approved these changes
Works as expected. Good job!

![Screenshot (195)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/41186831/1b4e8b11-64b4-4b10-af29-cefe14dadaba)

![Screenshot (194)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/41186831/6f72ad89-1182-4afe-9d7f-d0998ef3ac01)

2023-10-07 16:29 UTC, JeffLi117 approved these changes, later dismissed
Changes work as expected, good job!

Added initial user JEFFTESTCAPS Li:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/acd69c99-e586-412b-a487-4dac31281114)

Attempting to add same user again:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/b6c34025-ee99-400f-9bf3-0fb328714702)

The error message:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/1530b186-c8a1-49fb-b368-c5d9392db91a)

2023-10-11 21:14 UTC, yi-lin-1234 submitted a review, later dismissed
Hello, I tested your PR and works as intended. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/79b6544f-31b1-4c4a-bb77-cb87d8b866db

2023-10-14 01:10 UTC, Lin1404 commented
Hi @zuhang2000 tested the PR and it is working as intended.
![PR1185](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/38200fee-ddf3-4649-acf3-e943330a2171)

2023-10-14 01:12 UTC, Lin1404 submitted a review, later dismissed

2023-10-21 08:42 UTC, StrawberryCalpico submitted a review, later dismissed
I reviewed your PR, it works as the description. Good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/7ab05a89-b4e7-46b1-9dac-e8086a18b420

2023-10-27 00:29 UTC, kavya151 commented
I have examined the PR, and it functions correctly when a team member's name is chosen from the dropdown. However, when I type the full member name, it displays "Please choose a valid user" instead of "The member is already part of this team."
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/6b649f7e-5f4a-4616-988f-e708e6be13bd

2023-11-07 15:45 UTC, cvtqx requested changes
I've faced the same issue as @kavya151 . When choosing a name from the dropown, the new message appears as described. However if we  type the full name of an existing team member manually, the message is different:

<img width="954" alt="Screen Shot 2023-11-07 at 10 40 27 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/32e79f1f-3817-4476-af08-98cadb9b63a8">

Here is a video of testing:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/e5ca1180-77d5-4a5b-93ee-dcceb40b60dd

2024-01-11 15:36 UTC, cvtqx commented on src/components/Teams/TeamMembersPopup.jsx
>    const [isValidUser, onValidation] = useState(true);
Can these 2 state update functions (lines 16 and 17) names be updated to follow the convention? The convention for naming the state update functions is to use a prefix like "set" followed by the state variable name.

2024-01-17 15:31 UTC, cvtqx approved these changes
Thanks for updating the code to follow the convention. As for my previous comment, I think it should be addressed in a new PR, I will let Jae know.

2024-01-18 02:07 UTC, one-community commented
Thank you all, merging!

2024-01-18 02:08 UTC, merged