aaron linting for PermissionsManagement component
OneCommunityGlobal/HighestGoodNetworkApp pull request #1190
Opened 2023-08-28 06:42 UTC by AaronPersaud

# Description
Fix linting for the `PermissionsManagement` component

## Related PRS (if any):
N/A

## Main changes explained:
- removed the PermissionsManagement component directory from `.eslintignore` and `.prettierignore`

## How to test:
1. check into current branch
2. do `npm install` and `npm run lint` to make sure you get no lint errors
3. run `npm run start:local` and start the backend as usual
4. go to Other Links -> Permissions Management and make sure everything is working (please do not add/remove any permissions).
5. run `npm run test` to make sure the tests are passing (see below image)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/8a934975-4cc6-460e-a342-5e2baad311d2)

## Note:
- the failing tests are also on dev branch, I am looking into that
- there were no lint errors, so I haven't really changed any of the component's code so nothing should be breaking

2023-08-28 16:23 UTC, Arsamat commented
Hello @AaronPersaud I tested your code and the changes seem to be working correctly.
![Снимок экрана (256)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67019552/a6558617-5917-4918-b408-b9bc0b36959d)
![Снимок экрана (257)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67019552/5bc6e833-7f81-4123-8ca1-4f1074cf8a07)
![Снимок экрана (254)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67019552/ea969bef-dcf8-497d-b2b0-d699b0981470)

2023-08-28 16:26 UTC, Arsamat approved these changes
Tested and changes worked as expected

2023-08-28 18:59 UTC, Haoj1 approved these changes, later dismissed
@AaronPersaud Good job! All tests passed and no lint error

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/ae362466-29e9-483c-8ca0-f565973d5441

<img width="666" alt="1190 2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/565a686d-03a4-451f-95ab-4e732c6c723a">

2023-08-28 19:18 UTC, sxiong5 requested changes
Hey, `npm run test` doesn't use eslint and prettier to check the code.
All the `jsx` file have issues that need to be solved.
Please check them one by one to solve it.

**Tips: `npx eslint --fix [path]` can help solve the issues automatically.**
<img width="1512" alt="Screenshot 2023-08-28 at 15 15 42" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/9a3185b4-13c6-4522-8a54-b63b97481756">

2023-08-28 19:36 UTC, AaronPersaud commented
Hey @sxiong5, thanks for reviewing!

I'm not receiving those errors on my VS Code.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/c5c46c1d-499e-431d-bba4-2663b2081b5e)

I'm guessing it's because I'm missing a plugin? I have prettier plugin installed, do I need eslint too? I assumed that all the eslint would be checked with `npm run lint`. Please let me know. Thank you.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/0c90417c-0903-46b3-844f-ad6578608945)

2023-08-28 21:40 UTC, sxiong5 commented
> Hey @sxiong5, thanks for reviewing!
> 
> I'm not receiving those errors on my VS Code.
> 
> ![image](https://user-images.githubusercontent.com/10265513/263814475-c5c46c1d-499e-431d-bba4-2663b2081b5e.png)
> 
> I'm guessing it's because I'm missing a plugin? I have prettier plugin installed, do I need eslint too? I assumed that all the eslint would be checked with `npm run lint`. Please let me know. Thank you.
> 
> ![image](https://user-images.githubusercontent.com/10265513/263814311-0c90417c-0903-46b3-844f-ad6578608945.png)

Hey @AaronPersaud, you still need ESLint in your vscode. And the command `npm run lint` will only check the `index.js` on the folder if that exists. Otherwise, it won't display any errors. So what you need to do is use `npx lint [path]` to check the file one by one.

2023-09-16 19:10 UTC, ramyaram2092 reviewed
Hello @AaronPersaud  Good work on the fix . However I still see the following warnings. 
![Screenshot (4)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/9be2b713-1f05-4f7d-bc84-979d1f59e64b)
![Screenshot (5)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/1869d529-001e-4ef8-80b0-e37fcb69247b)

![Screenshot (6)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/9f57ec3e-60dd-4e2d-a546-911df5ea0bf8)
![Screenshot (7)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/1334695b-02ba-4dda-8daa-a3e9ce38f9b9)

2023-09-17 00:06 UTC, AaronPersaud commented
@ramyaram2092, thanks for reviewing. However, I'm not getting the errors that you're getting.

<img width="958" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/ddf2c97c-7fda-44a0-916d-408322892628">

I'm going to further look into this, I'm not really sure why there's a discrepancy. If you have any ideas, feel free to let me know.

2023-09-18 19:12 UTC, AaronPersaud commented
@ramyaram2092 I fixed all the errors, I realized there's something wrong with my VS Code and some of these errors don't show up. As for the errors in the test file, the linter is setup to ignore those.

<img width="959" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/b8a7e744-9470-498c-b958-231e20cfb552">

Please see if all the errors have cleared for you. Thank you.

2023-09-20 23:20 UTC, ramyaram2092 reviewed
Hello @AaronPersaud now i dont see the issues I mentioned before .
however I just see "unable to resolve path" warning in all the files.  if that's fixed we are good to go 


![Screenshot (12)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/d5bfd2f0-f32b-4a7d-9bb7-cf309c161612)

2023-09-23 03:35 UTC, EvianTan requested changes

2023-09-23 07:24 UTC, AaronPersaud commented on src/components/PermissionsManagement/NewRolePopUp.jsx
> +import { permissionLabel } from './RolePermissions';
So before my change, `UserRoleTab` imports the entire component `RolePermissions` and then `RolePermissions` was importing the `permissionLabel` constant from `UserRoleTab` which was causing a circular dependency. I moved `permissionLabel` to `RolePermissions` so then `RolePermissions` doesn't have to import it from `UserRoleTab`, and it breaks the circle.

2024-05-05 03:55 UTC, EvianTan commented
I'm taking over this PR and I'll work on it soon. Need to pull in the latest changes from development and fix all the eslint/prettier issues. And also make sure the builds won't fail.

2024-05-19 05:17 UTC, EvianTan commented
Closed this PR for now because I raised another PR #2269 instead.

2024-05-19 05:17 UTC, closed without merging