Shihao - Lint Fix Header
OneCommunityGlobal/HighestGoodNetworkApp pull request #1202
Opened 2023-08-30 19:07 UTC by sxiong5

# Description
Lint Fix `src/component/Header/**`

## Main changes explained:
- Change the code style according to ESLint and Prettier

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as any user
4. go to dashboard
5. check the app works as normal (specific the `Header`)
6. set up ESLint and Prettier in VSCode
7. check all files in `src/component/WeeklySummary/**` doesn't have errors

## Screenshots or videos of changes:
![Screenshot 2023-08-30 at 15 06 17 (2)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/0d7ae809-9132-4118-8a9d-0f4a14ded6f2)

2023-08-30 23:40 UTC, iTvX commented
I have tested your pr and followed your instructions. I don't find any error.

<img width="1960" alt="CleanShot 2023-08-30 at 16 39 20@2x" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/25bb9477-02c5-4aec-ab72-7176a6efea72">

2023-08-31 00:14 UTC, DavidC0126 reviewed
I tested it and it works as intended.
<img width="1664" alt="PR1202" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/3e2fd2e6-ce16-4e0f-ac46-bd9b1d603277">

2023-08-31 01:17 UTC, Jiyuanxia commented
Works perfectly!
![Screenshot 2023-08-30 211636](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/2db3e34e-aa2e-4b25-8ad5-469bdcdc4b45)

2023-08-31 20:05 UTC, GaryB93 approved these changes
Great work in cleaning up the codebase by destructuring props object! No lint errors found in Header component and functionality has not been affected. Header component removed from .eslintignore & .prettierignore files.

![Screenshot 2023-08-31 at 2 56 27 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/43b79390-5001-4088-8a86-441d7a4a48ec)

2023-08-31 20:15 UTC, gabi-lima commented
Shouldn't the username appear in the header? Right after Welcome, 'user...'

2023-08-31 23:53 UTC, AnishPandita commented
Hey, followed the instructions and didn't see any errors due to the PR. The code looks nice as well.
<img width="1440" alt="Screenshot 2023-08-31 at 4 51 20 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/c62f7bff-73d9-4806-989b-3f05124703bb">

2023-09-01 04:22 UTC, sxiong5 commented
> Shouldn't the username appear in the header? Right after Welcome, 'user...'

Hey @gabi-lima, it should display the name like "Welcome, xxx". But this is a backend issue since the first name in the data is empty.

<img width="816" alt="Screenshot 2023-09-01 at 00 20 02" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/be49b18a-c85e-4508-bd6c-4fd70a6d9eb3">

2023-09-01 05:46 UTC, ramyaram2092 requested changes
Hello @shihao firstly good job 
The code looks clean. The header looks error free. 
However I do think the name is not getting populated near Welcome ..
I checked the development branch . I can see the name there 
So could you recheck the fix you did especially for this field

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/6f3e1173-bfa7-4770-86d2-3b4189b5ad23)

2023-09-01 22:25 UTC, yaow62023 reviewed
PR tested, No error show up. However, there is no first name after word "Welcome, ". Check the picture below for details. 

<img width="1512" alt="1202" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/0d9a7058-732c-44fc-a596-7474747967fc">

2023-09-02 03:40 UTC, luisarevalo21 submitted a review, later dismissed
Hello @sxiong5 ,

I tested your PR and works as intended. Great work. 
The application works as intended. 
As others mentioned the header is missing the name, but since you pointed out it is a backend issue, it is unrelated to this PR.

Great work. 
<img width="1291" alt="Screenshot 2023-09-01 at 8 39 40 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/af1090db-2cf2-43a8-b727-12a6825d2cd3">

2023-09-02 18:13 UTC, Shreyj14 commented
Hi @sxiong5 , as mentioned by others above. Please check for the user name. Apart from that it looks good.

<img width="1440" alt="Screenshot 2023-09-02 at 2 13 10 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/4c7f3acc-1464-4fac-be79-a49045929a08">

2023-09-04 23:53 UTC, vikrambadhan approved these changes
Hi, I reviewed the header code and tested your PR. Everything works perfectly!

![Week2- PR2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/de9302f4-4ada-46c8-a1ee-98dac25c9392)

2023-09-13 20:58 UTC, Sssky-18 submitted a review, later dismissed
Hi @sxiong5, I checked this code and there was no errors. When running the dashboard, I can see the header correctly and my name was shown behind the "Welcome," so I think your recent fix worked as expected.

<img width="1437" alt="PR#1202" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/cb9ccaa8-c8d6-4b2d-b26c-1b2cac79fdbe">

2023-09-15 01:01 UTC, dah00 submitted a review, later dismissed
hey @sxiong5, I tested your PR, I don't see any errors and everything is displayed as expected. Also, my name appears after the Welcome. Good work!
![PR1202](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61763829/96fd4bfc-0ad4-4610-ba40-3e7b3d2bf730)

2023-09-16 02:53 UTC, Shubhu0 commented
Tested the PR, did not notice any errors.

2023-09-17 05:44 UTC, zuhang2000 submitted a review, later dismissed
Hi I've tested your PR and everything works as expected!

1. The header on dashboard all good. The "missing name" error that they previously mentioned is gone.
<img width="1511" alt="Screen Shot 2023-09-17 at 1 42 15 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/4d792f97-3322-4cd9-9c89-26b0b68b2616">

2. No error in the files from header component. Good job!
<img width="1102" alt="Screen Shot 2023-09-17 at 1 42 26 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/fa8c59c3-21cb-4c56-a1a3-968ed47c586d">
<img width="545" alt="Screen Shot 2023-09-17 at 1 42 32 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/3bdcf922-47d5-4005-b173-d1dfba963ef9">

2023-09-20 00:20 UTC, Shiwani99 approved these changes
Hi, 
I tested your PR. It works as intended. There are no errors in files under Header. I also checked if Header folder path was removed from eslintignore and prettierignore. 

<img width="1432" alt="Screenshot 2023-09-19 at 8 15 42 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/fbf65ba6-79e0-4768-83dc-51332369a1d5">

<img width="1435" alt="Screenshot 2023-09-19 at 8 16 20 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/5dbb69e8-7828-4d22-937a-e795568caa2b">

2023-09-20 22:35 UTC, ramyaram2092 requested changes
Looks good  Shihao. However I still see some warnings like unusued import, unused variable names
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/8287a9bc-c704-4b72-b06d-0fea706ff881)

![Screenshot (9)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/4c1fed7c-1c98-467b-a7b4-86742de05871)


![Screenshot (10)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/79b99670-bffd-4709-9878-fd17739f74d5)


![Screenshot (11)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/b9490c39-6f08-4343-bb3b-510b00ec5db1)

2023-09-20 22:59 UTC, EvianTan commented on .gitattributes
> +# * text eol=lf
See the same comment I left on your #1203 PR.

2023-09-20 23:03 UTC, EvianTan requested changes

2023-09-20 23:03 UTC, EvianTan commented on src/components/Reports/PeopleTableDetails.css
> -.wrapper.container-fluid {
can you help me understand what are the exactly changes in this `.css` file?

2023-09-29 22:26 UTC, Shubhu0 commented
Hey @sxiong5 I tested your PR, I don't see any errors and everything is displayed as expected. The name appears are it should and the PR is working correctly with no errors.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/30e1efc4-a19e-4b7d-ae93-be685ea17d2e)

2023-10-22 02:08 UTC, palakgosalia commented
Hey, I have checked for errors in the header folder and didn't find any. The App runs as expected. Thank you

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/d60571bb-803b-4297-82aa-eb3f873e540e)

2023-10-29 06:43 UTC, savio-henrique submitted a review, later dismissed
Hi @sxiong5 , I've tested your PR, the Header seems to be working as expected, no console errors, and the name seems to be back at the Header after 'Welcome,'. Also no errors on my IDE on Linting the files as shown by the screenshots below.

# Screenshots

![working!](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83360232/0dec74b6-9227-47d0-a66c-44759211f925)

![No problems](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83360232/66cf6225-98d6-4304-83af-4b42d2cb9bfa)

2023-10-31 03:53 UTC, EvianTan approved these changes

2023-11-02 04:02 UTC, EvianTan approved these changes

2023-11-02 04:02 UTC, merged