Navneeth Make adding a Project save the category selected
OneCommunityGlobal/HighestGoodNetworkApp pull request #1226
Opened 2023-09-02 21:39 UTC by navneeeth

# Description
![bug I am working on](https://github.com/OneCommunityGlobal/HGNRest/assets/44264834/7206d7fa-d01d-4621-af80-5f787365aad6)

## Related PRS (if any):
This frontend PR is related to the [#490 backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/490).
To test this frontend PR, you need to checkout the above backend PR.

## Main changes explained:
- Fixed a bug in `Project.jsx` where a related state was not being updated after the project category was updated

## How to test:
1. check into the current branch (also in the [#490 backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/490)).
2. do `npm install` and `npm run start:local` to run this PR locally.
3. login as admin/owner user
4. go to Other Links -> Projects
5. Add a new project with an unique name and remember its category
6. Refresh the page or leave the Projects page and come back to it
7. Scroll down to your newly created project and check if its category is the same as the category set when it was created
8. Change the newly created project's category from the dropdown and see if the update works for all types of categories

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/f9ba417f-5939-4eca-906c-c241b8438563

2023-09-02 23:32 UTC, AuroraLovesWhales commented
Hi @navneeeth. I have tested your PR and it is working as intended. Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/58fd30d2-fd8e-4e79-afd2-32d29806beef

2023-09-02 23:32 UTC, AuroraLovesWhales approved these changes

2023-09-03 02:41 UTC, robertoooc approved these changes
Hi @navneeeth, I reviewed your branch and everything worked well. Projects can be created and updated just well.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/6f45c6ae-84df-4ebf-bcaa-09303574dd13

2023-09-03 05:00 UTC, EdwinLauM reviewed
Hey @navneeeth! I have tested your changes, however, whenever I create a new project the category doesn't save after the refresh. Changing the categories of the project does work though. I have checked out both the frontend and backend branches

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/32b13c43-aa07-42ea-b99a-bcf293ec46cb

2023-09-03 05:06 UTC, veronicacheng2 approved these changes
Hi @navneeeth, I have tested the PR and everything works as intended.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/8f3b75dc-251c-4b01-a687-ff5c04af1bc0

2023-09-03 05:07 UTC, winghojackyli approved these changes
Hi @navneeeth , I've tested the PR and it works as intended. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/0d8474dd-f6a6-433a-9391-2172981b78ea

2023-09-03 21:25 UTC, GaryB93 approved these changes
Newly created projects now save their categories and when changing an existing projects category you are able to select from the entire menu. Great work!

![PR1226+490](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/9c30d4e6-f317-4eff-8247-12266e0ff638)

2023-09-04 03:14 UTC, luisarevalo21 commented
Hello @navneeeth 

I tested your PR but unfortunately it does not work for me. Even though 6 other developers confirmed its working. 
When creating the new project, the category is saved. However, once I refresh the category resets to unspecified. 

If I edit the category and refresh it works. 
I've attached videos below. I checked into your Front end branch and backend branch. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/a1793e43-9c66-4645-918d-e986b1153292


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/c196abc3-92c8-40e5-9e58-e88638fd6538

2023-09-04 18:25 UTC, belagaam approved these changes
I tested the PR as per the instructions. Everything works as intended.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/5ae47165-5887-42cf-96bc-d3e7fd530238

2023-09-05 04:46 UTC, DavidC0126 approved these changes
Hi @navneeeth I tested your PR and it works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/496d3505-f26a-42ce-bbe7-e6198d7e4513

2023-09-05 06:25 UTC, Haoj1 approved these changes
@navneeeth Great job! Category is successfully saved after creating  projects and looks good after refreshing.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/419a2638-dcee-470f-b9d6-33ac8f609c2e

2023-09-05 18:59 UTC, navneeeth commented
> Hello @navneeeth
> 
> I tested your PR but unfortunately it does not work for me. Even though 6 other developers confirmed its working. When creating the new project, the category is saved. However, once I refresh the category resets to unspecified.
> 
> If I edit the category and refresh it works. I've attached videos below. I checked into your Front end branch and backend branch.
> 
>  Screen.Recording.2023-09-03.at.8.11.11.PM.mov 
>  Screen.Recording.2023-09-03.at.8.12.44.PM.mov

Hello, @luisarevalo21! Thank you for your comment. The issue that you are facing in specific was fixed in the backend so I'd suggest doing  a `npm install` `npm run build` and `npm run start` on the backend again and hopefully, it should fix any caching-related errors. Please try again and let me know if the issue persists. The fact that you can edit the category and refresh it confirms that the frontend PR is working as intended and only the backend PR needs to be rechecked. Thank you!

2023-09-05 19:03 UTC, navneeeth commented
> Hey @navneeeth! I have tested your changes, however, whenever I create a new project the category doesn't save after the refresh. Changing the categories of the project does work though. I have checked out both the frontend and backend branches
> 
>  Screen.Recording.2023-09-02.at.9.53.59.PM.mov

Hello, @EdwinLauM! Thank you for your comment. The issue that you are facing in specific was fixed in the backend so I'd suggest doing a npm install npm run build and npm run start on the backend again and hopefully, it should fix any caching-related errors. Please try again and let me know if the issue persists. The fact that you can edit the category and refresh it confirms that the frontend PR is working as intended and only the backend PR needs to be rechecked. Thank you!

2023-09-06 04:58 UTC, vikrambadhan approved these changes
Hi, I followed the instruction to check the PR the and it is working as intended. Great Work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/0b017ff3-4a9d-422a-b6e4-3958f7543bf5

2023-09-06 19:49 UTC, harshidad requested changes
As mentioned in PR I took the branch from both frontend and backend. 
When I Add new project with an unique name and its category -> category display
But when I refresh the page -> selected category not display.

Also I observed this happens only first time. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/dcb663b1-d536-4938-ad1a-16ce91bfdd53

2023-09-07 19:05 UTC, GaryB93 commented
Wanted to confirm the functionality of this PR as @harshidad seemed to be having issues with the refresh. I performed the same steps as in adding a new project and refreshing the page. The category was saved and is displaying correctly.

2023-09-08 00:13 UTC, tsunami776 approved these changes
I tested the PR with an Admin account, and it works as described. Now newly created project will have its category set. The project's category can also be changed to any other category in the dropdown list.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/2db593df-647d-45a7-a338-c6d5dd5eac9b

2023-09-08 03:37 UTC, ss23046 approved these changes
Hi @navneeeth 
Tested your PR, works perfectly, good job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99052235/c5219592-a99c-4a7b-ab34-2ad5b045c7af

2023-09-13 17:50 UTC, navneeeth commented
> Hi @navneeeth ,
> 
> I've checked the feature and it works as intended. The project is saved in the right category. However, when clicking the delete button, it selects a different project (you can see in the video)
> 
>  PR1226.mp4

Hey @Chris33871! Thank you for your review. That's a good bug you found. I tested it and it's a bug related to the delete modal where 'Ramya-lint-test' is shown as the default name when deleting any project. When you confirm deletion though, the project you selected itself is deleted. I believe that this bug you found out can be posted separately on the Bugs Doc as it is not related to this PR which is to fix the issue with saving the category of the newly created project. Thank you again!

2023-09-13 18:24 UTC, Chris33871 commented
> > Hi @navneeeth ,
> > I've checked the feature and it works as intended. The project is saved in the right category. However, when clicking the delete button, it selects a different project (you can see in the video)
> > PR1226.mp4
> 
> Hey @Chris33871! Thank you for your review. That's a good bug you found. I tested it and it's a bug related to the delete modal where 'Ramya-lint-test' is shown as the default name when deleting any project. When you confirm deletion though, the project you selected itself is deleted. I believe that this bug you found out can be posted separately on the Bugs Doc as it is not related to this PR which is to fix the issue with saving the category of the newly created project. Thank you again!

Okay cool, I updated the bug sheet with a new entry in the Projects/Teams/Tasks/WBS component section. Please let me know if I should make any changes to the reporting.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68507104/d29652bf-c614-4724-a4c1-f608a0787dba)

2023-09-13 20:22 UTC, navneeeth commented
> > > Hi @navneeeth ,
> > > I've checked the feature and it works as intended. The project is saved in the right category. However, when clicking the delete button, it selects a different project (you can see in the video)
> > > PR1226.mp4
> > 
> > 
> > Hey @Chris33871! Thank you for your review. That's a good bug you found. I tested it and it's a bug related to the delete modal where 'Ramya-lint-test' is shown as the default name when deleting any project. When you confirm deletion though, the project you selected itself is deleted. I believe that this bug you found out can be posted separately on the Bugs Doc as it is not related to this PR which is to fix the issue with saving the category of the newly created project. Thank you again!
> 
> Okay cool, I updated the bug sheet with a new entry in the Projects/Teams/Tasks/WBS component section. Please let me know if I should make any changes to the reporting.
> 
> ![image](https://user-images.githubusercontent.com/68507104/267752794-d29652bf-c614-4724-a4c1-f608a0787dba.png)

Hey, @Chris33871! It looks good to me. And, Jae has approved your bug report as well. Good find!

2023-09-14 07:22 UTC, Shiwani99 approved these changes
Hi,
Great work. I tested your PR and it works as expected when I refreshed the same page and came back to the same page from another page to test if the category selected is getting saved.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/ba5cf5d8-8a6b-4fa0-82fa-e85c35b7e6c3

2023-09-14 07:52 UTC, Chris33871 approved these changes

2023-09-15 17:58 UTC, Jiyuanxia approved these changes
Hi @navneeeth , I have reviewed your pull request and tested it. It works as you intended. Good job!
![Screenshot 2023-09-15 135658](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/fdd5267c-9d74-42a4-8419-7f2989b46500)
![Screenshot 2023-09-15 135727](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/3ad2263d-273d-4218-bb21-f679ad832dc2)

2023-09-15 23:35 UTC, one-community commented
Thank you everyone, moved to final review!

2023-09-16 01:09 UTC, wantingxu7 commented
Hi,
the PR works nearly as expected except for one thing: when I created the project and specified the category as "food", it is shown in the project list, but after refreshing, the category becomes "unspecified".  After this, changing category and refreshing all works well.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/9b5764e2-9450-4819-b2e6-30647e2df17c

2023-09-16 02:59 UTC, Shubhu0 commented
Tested the PR, working as intended. Good job!

2023-09-16 23:02 UTC, EdwinLauM approved these changes
Hey @navneeeth, thanks for addressing my comment. Last time I tested, I missed pulling the changes/commits you made to the BE branch. Works as intended, good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/1e653c15-ebbf-4030-acab-c690899c2011

2023-09-18 06:01 UTC, one-community commented
Thank you everyone, merging!

2023-09-18 06:03 UTC, merged