Shihao - Fix Weekly Summaries Report Loading Issue & ESLint Errors
OneCommunityGlobal/HighestGoodNetworkApp pull request #1264
Opened 2023-09-05 18:25 UTC by sxiong5

# Description
Fix the issue of failing to load the weekly summaries report page and related eslint errors.

## Related PRS (if any):
This PR is to fix all the issues caused by #1172 and #1242 

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to dashboard→ Report → Weekly Summaires Report
5. Make sure the page can load normally and fast
6. Set up ESLint and Prettier in VSCode
7. Check all the files contain no errors in `src/component/WeeklySummariesReport/**`

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/7c68d455-3294-4fc5-8fd3-2da4bd194cc2

2023-09-05 19:59 UTC, navneeeth submitted a review, later dismissed
Hello, @sxiong5! I tested your changes and they LGTM! There is no lag in the Weekly Summaries Report loading.

Here's a comparison:
*Before the fix*:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/5826d52f-f634-402b-8dfd-e21740912e32

*After checking out this branch*:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/7d0e7cdf-dbe6-43cc-8c1e-c52d845ad4bf

There were no issues in the files under `src/components/WeeklySummariesReport` as observed in the second video. I believe it is my browser's issue why it still takes 2-3 seconds to load as the reduction in loading time is clearly seen in the second video with respect to the *Before the fix* video.

Good implementation!

2023-09-05 21:39 UTC, Haoj1 submitted a review, later dismissed
@sxiong5 Weekly summary report page looks good to me. And there is no error in src/components/WeeklySummariesReport. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/a4eb645a-9e55-411d-a0dd-d647b8e58060

2023-09-06 20:23 UTC, robertoooc approved these changes
Hi @sxiong5, I tested your branch and your changes drastically cut down the loading time for the weekly summary report page. Nicely done, the files also worked well under eslint and had no formatting issues. 

Your Branch:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/2a75ca9a-5738-443c-b8b5-e541df33ae2d


Development Branch: 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/dbbd07ea-924d-413e-8fc3-27577cc73bac

2023-09-06 21:43 UTC, wang9hu requested changes

2023-09-07 07:11 UTC, iTvX submitted a review, later dismissed
I have tested your pr, and I didn't see any error. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/8d8c7392-f0fc-4c35-ac74-23c89057bea6

2023-09-07 19:12 UTC, sxiong5 commented on src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
> +export default connect(mapStateToProps)(WeeklySummariesReport);
But they are already imported. Can you be more specific about why we should do that since I noticed that so many components did like this.

2023-09-07 19:41 UTC, wang9hu commented on src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
> +export default connect(mapStateToProps)(WeeklySummariesReport);
That is redux-thunk, a middleware for adding asynchronous request to redux, here is the link that has more info: https://redux.js.org/usage/writing-logic-thunks#thunk-overview

2023-09-07 22:35 UTC, GaryB93 approved these changes
In testing this pull request, the Weekly Summaries Report page now loads much quicker. In reviewing the code, there are no lint errors but I can create lint errors by modifying the code, ensuring that eslint is indeed working.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/1c0cb23e-4b5a-4804-9e5f-340cd674330c

2023-09-10 05:04 UTC, gabi-lima approved these changes
Well done! Working as intended, it is much faster than the dev branch.

2023-09-13 18:26 UTC, GaryB93 submitted a review, later dismissed
Good work! A load badges button has been added and correctly toggles whether the user can see badges on the Weekly Summaries Report page. I tested the eslint and prettier functionalities on the codebase and was able to introduce errors so it is working correctly.

![Screenshot 2023-09-13 at 1 04 21 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/eedf8c1a-a2ad-45be-a94d-49c41f228216)
![Screenshot 2023-09-13 at 1 21 11 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/bb5d5b2a-3eea-40d9-8510-dfd82a43cb5a)

2023-09-15 17:46 UTC, Jiyuanxia approved these changes
Hi @sxiong5 , I have reviewed your pull request and tested it. It works as you intended. Well done!
Load Badge
![Screenshot 2023-09-15 134331](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/848696af-6e28-48b5-ac75-416174829181)

Hide Badge
![Screenshot 2023-09-15 134346](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/141dc8e9-90d6-4258-9bd7-f73a2977e773)

2023-09-15 18:53 UTC, dah00 commented
Hey, the badges are showing as intended. Good job!
![PR1264](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61763829/a095441d-5b36-48bc-a422-5e5f9a2a8640)

2023-09-15 23:52 UTC, one-community commented
Thank you all, moving to final review

2023-09-18 13:14 UTC, beblicarl commented
This functionality works as intended also there are no errors in all the files in the weeklySummariesReport folder

[screencast-localhost_3000-2023.09.18-13_11_36.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/c91380a1-a2e6-4b3e-996f-57427eff7f15)

2023-09-18 13:17 UTC, beblicarl approved these changes

2023-09-18 20:37 UTC, merged