Edwin - Add See User Management Tab (ONLY create users) permission
OneCommunityGlobal/HighestGoodNetworkApp pull request #1281
Opened 2023-09-07 23:52 UTC by EdwinLauM

# Description

<img width="1168" alt="Screen Shot 2023-09-07 at 4 45 07 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/fb58d3ec-3ed4-475b-be43-919c59e60063">

## Main changes explained:

- Implemented the See User Management Tab (ONLY create users) permission
- Disabled buttons if the full functionality permission is not given
- Made changes to the protected route to include this new permission

## How to test:

1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Log in as Owner
4. Dashboard -> Other Links -> Permission Management -> Manage User Permissions -> Choose a volunteer account and give them "See User Management Tab (ONLY create Users)" permission 
5. Log into that account and you should be able to see the Other Links tab now -> User Management -> all buttons should be disabled except the create user button. Users should not be able to delete or edit user profiles.

## Videos/Screenshots of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/84d2864b-1010-41a3-8d19-5b3fa498fd32

2023-09-09 23:20 UTC, robertoooc requested changes
Hi @EdwinLauM, I tested your branch and I encountered an issue when trying to submit the form to actually create the new user. The permissions update did allow me to see the user management page on a volunteer account but I received an unauthorized access response once I tried to submit the create user modal.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/346ff65a-7617-4cb8-afd5-e7b01c082a75

2023-09-11 19:35 UTC, GaryB93 requested changes
Upon updating a volunteer's permission to only create users I was able to access the Create New User modal with that account. However, I ran into an issue trying to create a new user and the logged errors can be seen in the video. Seems like a prop error if that's what's preventing the user from being created.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/150b4a38-a4ff-4c46-b2de-9caef5089fb0

2023-09-16 18:44 UTC, ramyaram2092 reviewed
Hello @EdwinLauM 
I couldnt start the front end server as the test cases are failing . Could you confirm if you are in the middle of making changes in this branch ?
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/e7e2afb7-dc3a-4018-95e0-4e471d47f12b)

2023-09-17 05:24 UTC, Haoj1 requested changes
@EdwinLauM When I assign the permission to a volunteer. Other link is available but forbidden to create a user

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/7171acb5-d24e-4947-838d-8cfbd6eacb74

2023-09-19 16:22 UTC, Shiwani99 requested changes
Hi,
I tested your PR. I had issues with creating a user, but when I gave the permission it did block delete and updating user access. I'm attaching a screen recording of how it looks in my end.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/e57ef1c0-9a78-4477-baae-bb4e8db10044

2023-09-22 16:27 UTC, closed without merging