Masasa_onlycreatebadge_permission
OneCommunityGlobal/HighestGoodNetworkApp pull request #1287
Opened 2023-09-10 04:51 UTC by ThapeloMasasa

# Description
This PR creates a new Permission that restrict the badge management to capability to creating badges only. Below are pictures that show the task
<img width="748" alt="Screenshot 2023-09-09 at 9 25 22 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/312846d4-d360-448a-99ea-a40dd96cfceb">
<img width="1384" alt="Screenshot 2023-09-09 at 9 29 45 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/9f6c0848-c8ea-4a49-b107-cfc40ac36629">

## Related PRS (if any):
This frontend PR is related to no backend PR.. so please use the development branch
…

## Main changes explained:
- Created the permision in RolesTab.jsx and named it seeBadgeManagementTab …
- In order to have  to display its info icon description I added the permission in permissionList in Rolepermissions…
-  Then used the hasPermission function in badgemanagement to determine what to display between having the both the assign and develop badge tabs…
- The same function, hasPermission was also used in badgedevelopmentTable to disable the ability to edit or delete badges
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as owner.. this way you can assign and unassign the permission to you designated user...
4. go to otherlinks→ Permissions Management→ manage User permisssions→ Select user…
5. assign a user you can log into the permission 'See Badge Management Tab (ONLY create Badges)'
6. log out of owner and log in as that user 
7. go to otherlinks→ Badge Management

Expect to see this if the permission has been granted succesfully.. 
<img width="1440" alt="Screenshot 2023-09-09 at 9 43 44 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/5fc16ffb-f544-4668-a888-f1d91b2ef532">

 repeat and log in as owner and remove the permission and expect to see this in the badge management tab:

<img width="1346" alt="Screenshot 2023-09-09 at 9 48 54 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/b47b70c1-4a6e-4f65-a9d1-5d5a071cd58b">

## Note:
Include the information the reviewers need to know.
Do not test with an owner account because the owner always has all permissions

2023-09-10 04:58 UTC, gabi-lima reviewed
Hello! Even after saving the permission change, the other links tab does not appear in the account that I allowed viewing/editing.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74115277/454541f8-2fc6-40ad-ad76-df553e73a51d)
![Captura de tela 2023-09-10 015539](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74115277/e253739e-833a-457e-b1c7-0f25245ca8e8)

2023-09-11 18:48 UTC, Haoj1 reviewed
@ThapeloMasasa I have the same issue as @gabi-lima that I cannot see "other link" after giving the volunteer permission

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/f150a8c9-b240-4fa3-9430-f6e7f4f1b389

2023-09-12 18:35 UTC, GaryB93 requested changes, later dismissed
I'm also having the issue of not being able to see the Other Links tab for the user I assigned the permission to.
![Screenshot 2023-09-12 at 1 34 20 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/8c1faa87-274d-4dc1-97df-bc6a414573b6)

2023-09-12 19:14 UTC, ThapeloMasasa commented
> I'm also having the issue of not being able to see the Other Links tab for the user I assigned the permission to. ![Screenshot 2023-09-12 at 1 34 20 PM](https://user-images.githubusercontent.com/108501006/267427649-8c1faa87-274d-4dc1-97df-bc6a414573b6.png)

Hi @GaryB93 , I have added the backend code necessary. checkout into that branch. and it should work properly now..

2023-09-12 21:40 UTC, navneeeth submitted a review, later dismissed
Hello, @ThapeloMasasa! I tested your PR and it works as expected. I logged in as an owner account and navigated to Other Links->Permission Management->Manage User Permissions->Select User and selected an user account that I can log into. To this user account, I added the 'See Badge Management Tab (ONLY create Badges)' permission and got the popup with the success message. Then after logging out of the owner account and logging in as the above user, I can see the 'Create New Badge' functionality available in Other Links->Badge Management. Good implementation!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/18c9b39d-7817-4375-a399-37cd59a897f1

2023-09-13 05:18 UTC, DavidC0126 commented
Hi @ThapeloMasasa, I tested your PR and here is what I found.
1. When I gave an Admin role permission to create badges, I was able to see the button and edit the badge.
2. If I gave a volunteer the permission, I cannot find other link to access the badge management page.

<img width="1679" alt="admin_with" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/0bf09ce9-3e81-4d22-b446-833f5927fee2">
<img width="1679" alt="admin_without" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/8cfe97ff-ec86-48a9-9f0c-d372c2f6eb90">
<img width="1679" alt="volunteer_with_per" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/7346173d-e4b0-4337-a99e-ef4297bf7517">

2023-09-13 18:37 UTC, ThapeloMasasa commented
> Hi @ThapeloMasasa, I tested your PR and here is what I found.
> 
> 1. When I gave an Admin role permission to create badges, I was able to see the button and edit the badge.
> 2. If I gave a volunteer the permission, I cannot find other link to access the badge management page.
> 
> <img alt="admin_with" width="1679" src="https://user-images.githubusercontent.com/74082492/267543221-0bf09ce9-3e81-4d22-b446-833f5927fee2.png"> <img alt="admin_without" width="1679" src="https://user-images.githubusercontent.com/74082492/267543226-8cfe97ff-ec86-48a9-9f0c-d372c2f6eb90.png"> <img alt="volunteer_with_per" width="1679" src="https://user-images.githubusercontent.com/74082492/267543230-7346173d-e4b0-4337-a99e-ef4297bf7517.png">

hi @DavidC0126 Please watch the demo video below.. also make sure you checkout out into the right backend branch and make sure to run npm install.. Thank you..


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/853e6d84-e9df-4073-8511-8ef7bf0b6c7c

2023-09-13 18:51 UTC, Shiwani99 requested changes, later dismissed
Hi @ThapeloMasasa,
I tested your PR and I'm having the same issue as mentioned previously, that is when I get when I give the same badge permission to administrator, I'm able to get the same page as yours where I'm not able to edit or delete. When I set the same permission for a manager, I'm not able to find other links. I'm attaching a video of what I tested.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/e8b9feec-b0a4-4562-bf6e-2c766ec3dfb3

2023-09-13 19:07 UTC, GaryB93 commented
Hi @ThapeloMasasa, I pulled down the current backend and frontend for these PRs and was still unable to see the Other Links tab in the navigation. See video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/b4ed5716-2586-4c59-b160-3d511b537599

2023-09-13 21:21 UTC, vikrambadhan approved these changes, later dismissed
Hi, I tested your PR and works as intended! Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/c41091eb-d283-443a-80fc-b34758d3ab09

2023-09-14 02:46 UTC, wantingxu7 commented
Hi, I tested the PR and after being assigned permission, I can see the badge management. But after removing the permission, I cannot find "other link" tab, neither badge management.
![FE#1287 BE#534_after](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/28a5dd7f-63ea-4e62-a6dc-c9bbcd300510)
![FE#1287 BE#534_before](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/bbff9c60-4919-4f95-aa41-20e6ab0b22b1)

2023-09-14 19:46 UTC, TuanDinh140194 commented
Hi ! I have tested the PR and evverything look good for the role Admin as well as the role Manager. But I also don't see other link tab as Volunteer role like anyone else. However, I have found that if you change permission for volunteer role with create Badges enable. You can test it the same with other roles.  

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/9299733d-08f4-4a1d-930d-25d83581e201

](url)

2023-09-14 19:48 UTC, TuanDinh140194 commented
Here is the PR test for Volunteer Role

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/f79d59e2-ba3e-4250-a8dd-5d755cbf38b3

2023-09-14 19:57 UTC, TuanDinh140194 commented
Here is the test for Volunteer 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/f8975da5-42a4-423a-86a5-e037b3b76a47

Role

2023-09-14 22:11 UTC, robertoooc approved these changes, later dismissed
Hi @ThapeloMasasa, I tested your branch and like most people after giving the create badge permission to a volunteer role I was not able to see the other links tab to lead to the badge management. I did however find a workaround by using the url route and confirmed that it does give the correct permission. I did create a new badge to confirm that this works and removing the permission does also restrict access to visiting the url route. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/2473179c-5a37-4df4-b07c-4a5feaf8cf52

2023-09-16 02:13 UTC, TuanDinh140194 approved these changes, later dismissed

2023-09-19 11:32 UTC, Chris33871 reviewed
Hi @ThapeloMasasa ,

I reviewed the code and it works well but only for users who already have access to the other links option. When giving permission to a volunteer account, I do not have access to the other links option.
![Screenshot 2023-09-19 122647](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68507104/a54bb2d6-4b28-44a3-baab-4a61e00646cf)
![Screenshot 2023-09-19 122342](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68507104/cb5d6cbb-17ad-44f5-b630-552d15516956)

2023-09-19 19:01 UTC, GaryB93 submitted a review, later dismissed
Hi @ThapeloMasasa, I went ahead and reviewed this PR again trying to test any edge cases to see if I could access the Other Links tab. After giving both a Volunteer role and a Manager role the desired permission, I was still unable to access the Other Links tab.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/189c09f1-a2d8-4123-95b5-9e8dadd9f568

2023-09-20 21:09 UTC, iTvX reviewed
I followed all your instructions, but I cannot see the other link than in my other account after adding permission. That's so weird.

2023-10-14 03:37 UTC, StrawberryCalpico approved these changes
I tested your PR. It works as intended! good implementation! 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/92b8ecc2-4d1c-4f9e-a640-e132b99993e8

2023-10-14 07:32 UTC, malikjahanzaib approved these changes
Hi @ThapeloMasasa, I have reviewed this PR and the implemented functionality works as intended. Here is my test recording below. Great job!!!

Test rec:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/7f4f8aaa-9e30-403d-8eeb-ca28892f7e05

2023-10-15 00:23 UTC, RheaWu1212 commented
Hi I'm testing your PR, it's able to assign 'create badge' and the button showed up but no existing list below:

<img width="1257" alt="Screen Shot 2023-10-14 at 20 15 39" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/630fe033-9936-4b2f-97d8-76845c4515ff">
<img width="1283" alt="Screen Shot 2023-10-14 at 20 21 22" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/49408ad9-7d30-4bac-9f68-98de49340f52">

2023-10-25 00:17 UTC, ThapeloMasasa commented
> Hi I'm testing your PR, it's able to assign 'create badge' and the button showed up but no existing list below:
> 
> <img alt="Screen Shot 2023-10-14 at 20 15 39" width="1257" src="https://user-images.githubusercontent.com/109626741/275294371-630fe033-9936-4b2f-97d8-76845c4515ff.png"> <img alt="Screen Shot 2023-10-14 at 20 21 22" width="1283" src="https://user-images.githubusercontent.com/109626741/275294376-49408ad9-7d30-4bac-9f68-98de49340f52.png">

Hi @RheaWu1212, I am not sure I understand what probelm you are exeperiencing here.. please clarify so that we can know if it is related to this PR.

2023-10-25 01:40 UTC, ThapeloMasasa commented
> Hi @ThapeloMasasa, I pulled down the current backend and frontend for these PRs and was still unable to see the Other Links tab in the navigation. See video below.
> 
>  Screen.Recording.2023-09-13.at.2.02.33.PM.mov

Hi @GaryB93, please  check the demo below.. that is how a volunteer behaves without  and  with the permsission. 

Uploading Screen Recording 2023-10-24 at 5.44.50 PM.mov…

2023-10-27 22:36 UTC, nathanah requested changes

2023-10-27 22:36 UTC, nathanah commented on src/components/Header/Header.jsx
> +  console.log('canOnlyCreateBadges', canOnlyCreateBadges)
```suggestion
```

2023-11-05 00:12 UTC, shubhankarval approved these changes
Hey @ThapeloMasasa, the PR works as intended, great job!

When user has access to the Badge Management Tab:
![Screenshot 2023-11-04 171038](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59073366/829cfe97-dadc-4b37-a795-29b2fec1418e)

When user does not have access to the Badge Management Tab:
![Screenshot 2023-11-04 171300](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59073366/37bcea70-ae22-4b27-8995-843ad52fb3ab)

2023-12-13 07:14 UTC, Alforoan approved these changes
It works. Nice!
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/704e065c-140b-4f74-82d1-64d11ddd2252

2024-02-08 02:22 UTC, Pandani07 submitted a review, later dismissed
Tested this PR and the backend PR, the functionality works as intended. I added the permission for my volunteer account and I could see badge management under 'other links'.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/a0e62373-b7f7-4b18-a950-b1fcca3871ad

2024-02-29 04:06 UTC, skaush21 reviewed
Tested createbadge permission

* logged in as owner
* when signed in received a bunch of error 400's (might not be related to PR)
* navigated to user permissions -> user -> added create badge permission
* logged out
* logged in as volunteer user
* verified that user is able to see badges
* logged out
* logged in as owner, removed user permission
* logged out and back into volunteer account
* volunteer is no longer able to see bages.
feature works great


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/8fb7c014-68c5-4ad5-8dae-5c343b62d0f8

2024-06-05 01:55 UTC, closed without merging