Lintfixes for Badge Component
OneCommunityGlobal/HighestGoodNetworkApp pull request #1296
Opened 2023-09-13 20:49 UTC by mounica-dingari-by

# Description
Lint fixes for Badge Component

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to Other Links→ Badge Management
5. set up ESLint and Prettier in VSCode
6. Check if the files in src/component/Badge/** doesn't have any errors

## Note:
Please let me know, if something needs to be modified, or can be optimized

2023-09-14 17:17 UTC, robertoooc requested changes
Hi @mounica-dingari-by, I took a look at your pr and noticed that you didn't remove the `src/components/Badge/**` line out of the `.eslintignore` file or the `.prettierignore` file either. When I browsed through the files I removed these myself which led to finding many eslint warnings across most of the files in the Badge folder. I would suggest removing those lines out of the ignore files to complete this pr. 
<img width="1891" alt="Screenshot 2023-09-14 at 9 34 08 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/deacc30f-32a4-4bde-931b-cc987d587b64">

2023-09-17 04:44 UTC, Haoj1 reviewed
@mounica-dingari-by When I remove the line src/components/Badge/** in ignore, there is still some error in  src/components/Badge/**.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/6d88b2d6-60a3-4598-8ef5-0db6d5980236

2023-09-19 00:19 UTC, Shiwani99 requested changes
Hi,
I tested your PR. There are still errors in the files under badges folder. Please do add that the folder path needs to be commented in both eslint and prettier ignore files for the changes to be seen.

<img width="1296" alt="Screenshot 2023-09-18 at 8 16 00 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/8e896d53-368e-4d87-abc6-2c2827b2c3d4">

2023-09-20 21:21 UTC, iTvX commented
Hi, I tested your pr and used IntelliJ IDEA to see if it has any errors. Luckily, I saw no significant error, just some duplicate functions or variables.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/b83cd60c-5e99-42ed-a23b-154199d4aa47

2023-09-24 00:05 UTC, zuhang2000 reviewed
Hi I've tested your PR following your instructions. When I remove "#src/components/Badge/**" in both .eslintignore and .prettierignore file, the badge component is reporting many errors. Please check on this issue.
<img width="1459" alt="Screenshot 2023-09-23 at 8 04 19 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/b6a1a9a9-90f7-497b-ae3c-2a915c1448d5">

2023-12-14 05:22 UTC, Alforoan approved these changes
It doesn't seem to have any errors. Nice!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/dbe6ef77-491d-4bd8-bf67-082f0686426e

2025-03-02 00:40 UTC, closed without merging