Haohui - add new user permissions role
OneCommunityGlobal/HighestGoodNetworkApp pull request #1307
Opened 2023-09-15 05:27 UTC by Lin1404

# Description
Please include the exact bug/functionality description and a summary of the changes/ related issues. Please also include any other relevant motivation and context:
Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to dashboard→ Tasks→ task→…
5. verify function “A” (feel free to include screenshot here)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2023-09-24 21:01 UTC, wantingxu7 submitted a review, later dismissed
Hi, I followed the directions and assigned permission to a volunteer role and that volunteer can create a new role. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/fc423a78-051c-4bfd-b63a-a9e8eb3407e8

2023-09-26 01:21 UTC, JYXiao-2021 approved these changes
Hi, I test this pr and it works as expected. Well done!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49748716/32f543be-1eb4-45fd-9b34-81d260f3bc78

2023-09-27 20:37 UTC, navneeeth submitted a review, later dismissed
Hello, @Lin1404! I tested your changes and they work as intended. Logged in as an Owner user and navigated to `Dashboard-> Other Links-> Permissions Management-> Manage User Permissions` and added the "Add New user Permissions Role" to a Volunteer user. Then logged in as the above Volunteer user and navigated to `Dashboard-> Other Links-> Permissions Management-> Add New Role` and created a new test role,  added some permissions, and then hit Submit. The newly created role shows up as intended in the `User Roles` tab. Good implementation!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/433cd846-7d4e-4abd-a5ab-708b77660ea9


By the way, it will be helpful for reviewers if you can link the backend PR to the text that mentions it in the 'Related PRs' section in the Description. Thanks.

2023-09-28 07:06 UTC, vikrambadhan approved these changes
Hi, I tested your PR and it works perfectly! Great Job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/45b79c36-f055-489a-89cf-b40daf34c3de

2023-09-29 21:42 UTC, Shiwani99 approved these changes
Hi,
Great work. I test your PR. It works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/5425547a-e90c-4532-8003-8a7d054224ac

2023-09-30 04:48 UTC, Bhagyashree444 requested changes
From owners account I was able to add "Add New User Permissions Role" for Manager but when logged in as manager and was while trying to add "Add New Role", the application crashed.
![Screenshot (140)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/41186831/9910fe8c-d5ad-479e-8f46-9101179997f4)
![Screenshot (142)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/41186831/b19fcc4a-8b00-41a2-9ca1-f03b79098666)
![Screenshot (143)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/41186831/b2cc02a1-881d-40a4-b42e-327216721cd9)

2023-09-30 22:57 UTC, Lin1404 commented
> From owners account I was able to add "Add New User Permissions Role" for Manager but when logged in as manager and was while trying to add "Add New Role", the application crashed. ![Screenshot (140)](https://user-images.githubusercontent.com/41186831/271754277-9910fe8c-d5ad-479e-8f46-9101179997f4.png) ![Screenshot (142)](https://user-images.githubusercontent.com/41186831/271754284-b19fcc4a-8b00-41a2-9ca1-f03b79098666.png) ![Screenshot (143)](https://user-images.githubusercontent.com/41186831/271754285-b2cc02a1-881d-40a4-b42e-327216721cd9.png)

Hi @Bhagyashree444 , 

Thank you for the edge case report. I have located this bug is not from my change, but I have fixed it now. Please check the row 46,47 in 'src/components/PermissionsManagement/PermissionsManagement.jsx' file.

Thanks for the edge case report again.

2023-10-01 03:31 UTC, Bhagyashree444 approved these changes
Thanks for making the changes. It Works as expected.

2023-10-09 19:04 UTC, StrawberryCalpico requested changes
Hi! I just reviewed your PR, it seems like there's a conflict with the current branch, so that I can't find the add new user permission role.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/d0f59139-a7c6-4114-ab9d-70ad1afdca4b

2023-10-10 22:44 UTC, nathanah commented on src/components/Header/Header.jsx
> +                    {((canPutRole || canManageUser) || canPostRole) && (
```suggestion
                    {(canPutRole || canManageUser || canPostRole) && (
```
Extra () unneeded.

2023-10-11 02:47 UTC, malikjahanzaib requested changes
Hi @Lin1404, it seems this branch has some conflicts. I have checked out both FE and BE branches. When I try to go to "dashboard→ Other Links→ Permissions Management→ Manage User Permissions" from an owner account, I search for the user to assign the permission but there appears no “Add New User Permissions Role”. Below is the test recording.

Test rec:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/fb9cd6a6-499b-4d71-90fb-d151b0e47c3e

2023-10-22 00:03 UTC, Cloid requested changes
Hi there.

I tried enabling the "Add New User Permissions Role" but I couldn't find it within the User Profile permission management setting for a volunteer user:
![Screenshot 2023-10-21 153352](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/14044314/9c048e2f-bcd1-4d3d-9adb-dcbb58cdab77)

2023-10-27 02:45 UTC, ChirayuRai requested changes
Hey! I ran this PR on my local machine, and it seems there is no option to add new user permissions role. I have a video attached to show what I mean


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15188751/bb025d9b-d7d7-456e-9ad0-24d8479f067a

2023-10-27 21:24 UTC, nathanah requested changes
Should use hasPermission instead of custom logic.

2023-10-27 21:24 UTC, nathanah commented on src/components/PermissionsManagement/PermissionsManagement.jsx
> +      userProfile?.permissions?.frontPermissions.some(permission => permission === 'postRole')) &&
Shouldn't have logic based on hard-coded roles. More than just owners can create roles.

```suggestion
      {props.hasPermission('postRole') &&
```

2023-10-27 21:24 UTC, nathanah commented on src/components/PermissionsManagement/PermissionsManagement.jsx
> +            ) &&
```suggestion
            {props.hasPermission('postRole') &&
```

2023-10-27 21:24 UTC, nathanah commented on src/components/PermissionsManagement/PermissionsManagement.jsx
Import hasPermission and add it to mapDispatchToProps.

2023-10-29 01:53 UTC, palakgosalia commented
Hey, I reviewed your code and tried to test it out but I couldn't see the permission in the permissions tab. Please let me know if I need to do anything else. Thankyou. 
Attaching a video of the manage user permissions page

 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/2ccb4168-7d71-4bdc-b16e-f15d556b3f1a

2023-12-23 07:01 UTC, Alforoan requested changes
As you can see by the video, I was not able to find the specific role.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/1ed2f441-3dcc-413d-ae41-58fca24a008f

2024-02-05 01:55 UTC, closed without merging

2025-04-17 23:13 UTC, KH07 reviewed
I checked out the current branch, ran npm install, and started the app locally. Logging in as owner User A, in Other Links -> Permission Management -> Manager User Permissions, selected User B but was not able to find the ‘Add New User Permission Role’ option.
<img width="1558" alt="PR#1307" src="https://github.com/user-attachments/assets/e04efb9f-c941-44d4-83ed-59d604a3717b" />