Zijie lint fix for reports component Phase 6
OneCommunityGlobal/HighestGoodNetworkApp pull request #1361
Opened 2023-10-01 01:19 UTC by iTvX

# Description
Lint fix for Reports component, this is phase 3.

## Files changed
All js/jsx file in /src/components/Reports/TasksTable

eslint test:
<img width="1490" alt="CleanShot 2023-09-30 at 18 19 16@2x" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/facc863b-c474-458b-b7c6-516cfc532d35">

# How to Test

To test this pull request:

- Check out the current branch
- Run `npm install` and `npm run start:local` to run this PR locally  
- Log in as an admin user
- Check all the functionality of the report is the same as before, and see if any bugs have appeared. (Please record a video)

(Optional)
- Set up ESLint in VSCode/ IntelliJ IDEA, I personally use IntelliJ IDEA
- Delete .eslintignore file in the root: `rm .eslintignore`
- `npx eslint --fix '/src/components/Reports/TasksTable/*.{js,jsx}'`
- `git restore .`

I have complete confidence that **the code will pass the ESLint tests.** Therefore, I kindly request that you **focus on testing the frontend**. Specifically, please ensure that the **report functionality remains consistent** with how it operated previously. Thank you for your time and effort!

2023-10-03 02:59 UTC, luisarevalo21 requested changes
Hello @iTvX 
I tested your PR, however, running the npx eslint displays an error, also the eslintignore file doesn't exist. see screenshot. 
<img width="913" alt="Screenshot 2023-10-02 at 7 58 32 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/edb3cd02-9721-4b2d-af55-ded5dbd16103">

2023-10-03 07:44 UTC, iTvX commented
> Hello @iTvX I tested your PR, however, running the npx eslint displays an error, also the eslintignore file doesn't exist. see screenshot. <img alt="Screenshot 2023-10-02 at 7 58 32 PM" width="913" src="https://user-images.githubusercontent.com/22454953/272135473-edb3cd02-9721-4b2d-af55-ded5dbd16103.png">

Hi @luisarevalo21 ,
Because you are not in the root directory of HighestGoodNetworkApp, the instructions I gave you are for a relative path. You should navigate into the HighestGoodNetworkApp folder.

As I mentioned earlier, I have complete confidence that the code will pass the ESLint tests. This PR is primarily aimed at ensuring the frontend behaves as expected.

2023-10-04 07:03 UTC, DavidC0126 commented
Hi @iTvX, 

I tested the PR and I found when I clicked a project, I will be directed to a blank page. Other two buttons work as described.
<img width="639" alt="Screenshot 2023-10-04 at 12 00 07 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/96579344-8d18-42aa-9a3b-34f5f29bcfc4">
<img width="639" alt="Screenshot 2023-10-04 at 12 00 14 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/a3314a49-7c73-48b4-8d71-98f098eb5202">
<img width="639" alt="Screenshot 2023-10-04 at 12 00 25 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/76daf5c0-a9eb-467c-b272-75c82d6903dc">


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/63c2dfcb-8cc3-4c3d-b4c8-44ebdd961eb1

2023-10-05 03:33 UTC, luisarevalo21 commented
> > Hello @iTvX I tested your PR, however, running the npx eslint displays an error, also the eslintignore file doesn't exist. see screenshot. <img alt="Screenshot 2023-10-02 at 7 58 32 PM" width="913" src="https://user-images.githubusercontent.com/22454953/272135473-edb3cd02-9721-4b2d-af55-ded5dbd16103.png">
> 
> Hi @luisarevalo21 , Because you are not in the root directory of HighestGoodNetworkApp, the instructions I gave you are for a relative path. You should navigate into the HighestGoodNetworkApp folder.
> 
> I suggest you use `pwd` to determine your current location. The .eslintignore file is a default file; if you can't find it, that means you're in **the wrong directory**.
> 
> As I mentioned earlier, I have complete confidence that the code will pass the ESLint tests. This PR is primarily aimed at ensuring the frontend behaves as expected. Thank you for testing this PR.

@iTvX 

I revised, my testing of this PR and can confirm the eslint works when running. 
<img width="1115" alt="Screenshot 2023-10-04 at 8 29 03 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/0464f0cb-4f22-4171-a1fc-29c2cfe31da8">


However, when testing the project, I am to view the reports section and select, "people" and "teams" as normal but when I select projects, and select a project the app crashes. 
See video for reference. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/56371957-804d-45d2-95e8-8b4379b7bc2b

2023-10-09 17:48 UTC, iTvX commented
Hi @luisarevalo21 @DavidC0126 ,

I redo the eslint, those issues should be fixed, could you please double check again? Please let me know your result.

2023-10-13 22:35 UTC, Shubhu0 submitted a review, later dismissed
Hi @iTvX Reviewed the PR and it is working as intended. No issues or errors in the ESLint as well!

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/dfd4ebb6-3e64-45c8-bfd0-4f97aaef6898)

2023-10-14 16:33 UTC, savio-henrique submitted a review, later dismissed
Hi @iTvX , I've tested as the video below, and it was working as intended. Also the ESLint linted with no problems!
![terminal](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83360232/ba49997e-12e0-42d5-aca8-7234cd75a612)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83360232/71a04d3e-03a9-400a-85f5-5fdda36b64ee

2023-10-22 20:38 UTC, yi-lin-1234 approved these changes
Hello, functionality of the TasksTable pages is the same as before. And, the eslint fix worked as expected. Great work!

<img width="782" alt="Screenshot 2023-10-22 at 4 38 04 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/d9de5d73-150e-4d4a-a307-411ff3cb9386">

2023-11-07 04:31 UTC, EvianTan commented on src/components/Reports/TasksTable/TasksTable.jsx
> +// eslint-disable-next-line no-unused-vars
Same comment as [here](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1356/files#r1384348686)

2023-11-07 04:31 UTC, EvianTan commented on src/components/Reports/TasksTable/TasksTable.jsx
> +  // eslint-disable-next-line camelcase
Same as above.

2023-11-07 04:31 UTC, EvianTan commented on src/components/Reports/TasksTable/TasksTable.jsx
> +        /* eslint-disable-next-line camelcase */
Same as above.

2023-11-07 04:31 UTC, EvianTan commented on src/components/Reports/TasksTable/index.js
> +// eslint-disable-next-line import/prefer-default-export
Same as above.

2023-11-07 04:31 UTC, EvianTan commented on src/components/Reports/TasksTable/selectors.js
> +// eslint-disable-next-line camelcase
Same as above.

2023-11-07 04:32 UTC, EvianTan commented on src/components/Reports/TasksTable/selectors.js
> +  // eslint-disable-next-line camelcase
Same as above.

2023-11-10 06:17 UTC, iTvX commented on src/components/Reports/TasksTable/selectors.js
> +  // eslint-disable-next-line camelcase
fixed

2023-11-10 06:17 UTC, iTvX commented on src/components/Reports/TasksTable/selectors.js
> +// eslint-disable-next-line camelcase
fixed

2023-11-10 06:17 UTC, iTvX commented on src/components/Reports/TasksTable/index.js
> +// eslint-disable-next-line import/prefer-default-export
fixed

2023-11-10 06:17 UTC, iTvX commented on src/components/Reports/TasksTable/TasksTable.jsx
> +        /* eslint-disable-next-line camelcase */
fixed

2023-11-10 06:17 UTC, iTvX commented on src/components/Reports/TasksTable/TasksTable.jsx
> +  // eslint-disable-next-line camelcase
fixed

2023-11-10 06:18 UTC, iTvX commented on src/components/Reports/TasksTable/TasksTable.jsx
> +// eslint-disable-next-line no-unused-vars
fixed

2023-11-14 04:43 UTC, EvianTan commented
Just tried with the latest backend and this branch, got below error.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/5071040/78c40bf3-8243-4a24-bfbb-a5b4a1500b28)
And tried on the incognito window, cannot login from there.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/5071040/08c3ffd1-eab0-46a1-b18b-2cc7479db418)

2023-11-14 04:44 UTC, EvianTan commented on src/components/Reports/TasksTable/TasksTable.jsx
> +          {/* eslint-disable-next-line camelcase */}
Looks like you already got the camelcase errors fixed, please also delete line 77/80/88/95

2023-11-14 04:45 UTC, EvianTan commented
Merged your other PR, so you'd need to resolve the conflicts here as well.

2023-11-14 04:55 UTC, EvianTan commented
Same as this [comment](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1356/files#r1391983106)

2023-12-09 08:29 UTC, closed without merging