Jiyuan-Fixed-Assign-Badges-permission-function
OneCommunityGlobal/HighestGoodNetworkApp pull request #1387
Opened 2023-10-06 20:48 UTC by Jiyuanxia

# Description
![Screenshot 2023-10-06 162922](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/c5563db0-ed3c-4c5e-89c3-c1f9e6632457)

## Related PRS (if any):
This frontend PR is related to the [#547](https://github.com/OneCommunityGlobal/HGNRest/pull/547) backend PR.

## Main changes explained:
- Add a new check condition when assign a badge
## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as owner user
4. go to dashboard→ Other Links→ Permissions Management→ Manage User Permissions
5. type in another account name of yours which is not owner nor admin in User name→ find Assign Badges and click the Add button→ scroll down and click Submit
6. use the account you gave badge assignment permission to log in
7. click anyone's name to see if you can see the Assign Badges button on his profile page

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/7ccd6df7-5e70-4307-86f6-b0c4a62db85b

## Note:
If you click the Assign Badges button and see 403 error and there is nothing on Assign Badges page, it is ok because it is caused by lack of seeBadges permission.

2023-10-07 02:39 UTC, luisarevalo21 approved these changes
Hello @Jiyuanxia,

I tested your PR and works as intended. Great work! 
Logging in as an owner and adding the assigning the badge permission to my volunteer account. 
I then logged into the volunteer account and was able to assign badges to accounts.

Great work! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/96fc7485-995a-4c3f-b417-ec8373d4b457

2023-10-07 05:08 UTC, JYXiao-2021 approved these changes
Hi, I test this pr and it works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49748716/3d2139ed-3b7b-46ea-bd52-8ef63d877dbd

2023-10-07 14:56 UTC, Shreyj14 commented
Hi @Jiyuanxia I tested this branch and the code work as intended. I am able to assign badges from my volunteer account.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/50af5bf3-d80b-4c48-8090-806fac38951d

2023-10-07 17:10 UTC, wantingxu7 approved these changes
Hi,
the PR LGTM, before being given the "assign badge" permission, the volunteer cannot see the "assign badges" button. After being given the permission, the button shows up. Good work! 
But the assign badge function seems not working for now from my local test.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/c0e70881-2507-4750-a11c-e51ded317646

2023-10-07 19:27 UTC, TuanDinh140194 approved these changes
Hi! I have test this PR and it worked as expected. I have logged in as admin and assign add badget to my volunteer account. After logged in my volunteer account, I have see the assign badget button in my profile. Very good job !

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/aae07620-dfa7-44f3-a624-0cafb624614b

2023-10-09 08:44 UTC, StrawberryCalpico approved these changes
Hi! I just checked your PR, it worked perfectly! The badge assign button show up after updating the permission! Great job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/47b4017d-01a4-4ad2-b503-f2cd56535796

2023-10-09 19:30 UTC, navneeeth requested changes
Hi @Jiyuanxia! Tested your changes and the frontend fixes look good to me. But, I believe that a fix for this issue also requires a backend fix as the user will be unable to view all the badges and assign new badges to the user which is the purpose of this permission fix. 
### Testing video: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/7b05c736-158a-408b-ac20-0e66d56ac45b

### The error:
![badges not loading](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/1f455eb9-d2e5-4e7b-8414-67d7f6995c3d)

### Two areas in `src/controllers/badgeController.js` that need to be fixed in the backend
![backend suggested changes](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/3bb4c95a-41fa-4411-9032-d3421d9ccbb2)

If you follow the convention in this [frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1336) and its [backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/545), you should be able to fix the issue. I see that you have mentioned in the Note that 'there is nothing on Assign Badges page' but this PR should also require that functionality to work to be considered a fix. Thank you!

2023-10-09 19:40 UTC, lacnoskillz reviewed
Hi Jiyuan
I have pulled both the front end and back end changes you made but am having trouble assigning the badges permission to a user
Below I log in as my Owner account and attempt to give my volunteer account the assign badges permission but get a error in the console and unable to successfully assign badges on the volunteer account

[Untitled_ Oct 9, 2023 2_31 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/30c77788-7926-4935-a3ad-93437824204b)

2023-10-11 00:53 UTC, DavidC0126 commented
Hi @Jiyuanxia I also pulled FE + BE branches to test out the functionalities, however, it turned out I cannot see the badges on the list (But I can see the assign badges button after modified the permission as an Owner).
<img width="1658" alt="cannot_see_badges" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/86bec67e-3399-4530-8d8b-f879e0605d5d">

2023-10-12 20:31 UTC, Jiyuanxia commented
> Hi @Jiyuanxia! Tested your changes and the frontend fixes look good to me. But, I believe that a fix for this issue also requires a backend fix as the user will be unable to view all the badges and assign new badges to the user which is the purpose of this permission fix.
> 
> ### Testing video:
>  1387.mp4 
> ### The error:
> ![badges not loading](https://user-images.githubusercontent.com/44264834/273679168-1f455eb9-d2e5-4e7b-8414-67d7f6995c3d.png)
> 
> ### Two areas in `src/controllers/badgeController.js` that need to be fixed in the backend
> ![backend suggested changes](https://user-images.githubusercontent.com/44264834/273679350-3bb4c95a-41fa-4411-9032-d3421d9ccbb2.png)
> 
> If you follow the convention in this [frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1336) and its [backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/545), you should be able to fix the issue. I see that you have mentioned in the Note that 'there is nothing on Assign Badges page' but this PR should also require that functionality to work to be considered a fix. Thank you!

Hi @navneeeth , Thank you for reviewing my PR. The reason why user can not see Assign badges page is because lacking of "seeBadges" permission which is not provided in the permissions management system. Only admin and owner role has this permission by default. I have added it to the volunteer role and tested and it works well. So the issue is when "assignBadges" permission is assigned to a user, the "seeBadge" permission is not assigned accordingly so 403 error appears. I can submit another PR by adding "seeBadges" permission to default but it can not solve this issue totally. What we need to do is to make "seeBadges" permission either avalible in the system or when we assign a user "assignBadges" permission, assign them "seeBadges" permission too.

2023-10-12 20:35 UTC, Jiyuanxia commented
> Hi Jiyuan I have pulled both the front end and back end changes you made but am having trouble assigning the badges permission to a user Below I log in as my Owner account and attempt to give my volunteer account the assign badges permission but get a error in the console and unable to successfully assign badges on the volunteer account
> 
>  Untitled_.Oct.9.2023.2_31.PM.webm

Hi @

2023-10-13 15:27 UTC, vikrambadhan submitted a review, later dismissed
Hi, I followed the instructions given in your PR and I was unable to view the badges. I think a backend fix is required to solve this issue.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/538daf4a-42fa-48bd-ac95-901e1705db4d

2023-10-13 22:25 UTC, JeffLi117 approved these changes
Hi @Jiyuanxia, the code works all the way up until I try to assign another user a badge. The steps I took are as follows:

Logged in as Owner→ dashboard→ Other Links→ Permissions Management→ Manage User Permissions→ select my Volunteer account→ add "Assign Badges"→ Submit

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/76d371a5-68c4-42f8-a6fe-c8fedaf976fe)

Logged into said account→ looked into another user's account and was able to see "Assign Badges":
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/eb685300-0aac-4ae3-805a-51181b1b7be6)

However, when I try to see if that newly granted permission is usable for my Volunteer account, I get the following result: 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/666801f0-b9f7-4258-875a-3943b48af0fc)

I tried searching for a few common badge names, but got no result. I saw your conversation with @navneeeth on "seeBadges" permission -- as this seems to need another PR to address (or to completely overhaul it into a new PR), I am approving it because you have added the ability for another user to "Assign Badges", they just can't see them.

2023-10-14 15:38 UTC, RheaWu1212 commented
Hi I'm testing your PR, I'm able to 'assign badges' from my account but after I click 'search badges' it came out nothing. Other than that, it works as expected. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/cb43e8e7-e6d3-4481-a374-b17027e92661

2023-10-14 19:29 UTC, navneeeth commented
> > Hi @Jiyuanxia! Tested your changes and the frontend fixes look good to me. But, I believe that a fix for this issue also requires a backend fix as the user will be unable to view all the badges and assign new badges to the user which is the purpose of this permission fix.
> > ### Testing video:
> > 1387.mp4
> > ### The error:
> > ![badges not loading](https://user-images.githubusercontent.com/44264834/273679168-1f455eb9-d2e5-4e7b-8414-67d7f6995c3d.png)
> > ### Two areas in `src/controllers/badgeController.js` that need to be fixed in the backend
> > ![backend suggested changes](https://user-images.githubusercontent.com/44264834/273679350-3bb4c95a-41fa-4411-9032-d3421d9ccbb2.png)
> > If you follow the convention in this [frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1336) and its [backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/545), you should be able to fix the issue. I see that you have mentioned in the Note that 'there is nothing on Assign Badges page' but this PR should also require that functionality to work to be considered a fix. Thank you!
> 
> Hi @navneeeth , Thank you for reviewing my PR. The reason why user can not see Assign badges page is because lacking of "seeBadges" permission which is not provided in the permissions management system. Only admin and owner role has this permission by default. I have added it to the volunteer role and tested and it works well. So the issue is when "assignBadges" permission is assigned to a user, the "seeBadge" permission is not assigned accordingly so 403 error appears. I can submit another PR by adding "seeBadges" permission to default but it can not solve this issue totally. What we need to do is to make "seeBadges" permission either avalible in the system or when we assign a user "assignBadges" permission, assign them "seeBadges" permission too. ![Screenshot 2023-10-12 162108](https://user-images.githubusercontent.com/92963742/274729081-2f202fec-4c03-4ddc-b6a4-718739fc572a.png)

Hi @Jiyuanxia! Thank you for addressing my review. Yes, such a permission does not exist in the system and that is why it needs to be created for this permission to work as expected in the frontend. I will approve this PR now since it only aims to fix the button's visibility in the UI. If you will be working next on a full fix on the permission in a new FE + BE PR set, please follow the conventions in the frontend and backend links I shared above and also the rules in the Permissions Management Fixes spreadsheet (You can find the link on the Bugs document by searching for the same title). Thank you!

2023-10-14 19:30 UTC, navneeeth approved these changes

2023-10-15 03:59 UTC, John-Flavian commented
Hi @Jiyuanxia, Nicely done;

I believe that there is a need for modifications and upgrade of the backend permisions for fetching badges.

2023-10-19 20:10 UTC, sxiong5 requested changes
Hey @Jiyuanxia, I have pulled your changes and tested the PR, but I cannot see the badge list because of the error code 403. I think the issue comes from the backend, and it needs to be fixed.

![Screenshot 2023-10-19 at 16 07 49](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/f1ca2d60-ac0d-4694-87b3-b1e800d9ef55)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/aad7ec33-b469-4c9b-87ab-0e4209fc77f4

2023-10-21 18:29 UTC, Cloid approved these changes
Hi there.

I tested this case by following the instructions in PR. While the Assign badge functionality doesn't work, the visibility of the button does work. If this is the correct functionality of this PR then it works fine.

Attached are screenshots for me to test this.
![Screenshot 2023-10-21 110602](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/14044314/a0dd8a1b-6f92-446a-b68c-f6a90ab54dd6)
![Screenshot 2023-10-21 110749](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/14044314/a44e6942-ce6a-42c0-ac4e-43d94597897f)

2023-12-14 05:22 UTC, Alforoan approved these changes
I see the assign badge button. Nice!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/29e2b83d-b16f-4b9c-9867-65f5e291c069

2024-01-16 19:56 UTC, Jiyuanxia commented
> > > Hi @Jiyuanxia! Tested your changes and the frontend fixes look good to me. But, I believe that a fix for this issue also requires a backend fix as the user will be unable to view all the badges and assign new badges to the user which is the purpose of this permission fix.
> > > ### Testing video:
> > > 1387.mp4
> > > ### The error:
> > > ![badges not loading](https://user-images.githubusercontent.com/44264834/273679168-1f455eb9-d2e5-4e7b-8414-67d7f6995c3d.png)
> > > ### Two areas in `src/controllers/badgeController.js` that need to be fixed in the backend
> > > ![backend suggested changes](https://user-images.githubusercontent.com/44264834/273679350-3bb4c95a-41fa-4411-9032-d3421d9ccbb2.png)
> > > If you follow the convention in this [frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1336) and its [backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/545), you should be able to fix the issue. I see that you have mentioned in the Note that 'there is nothing on Assign Badges page' but this PR should also require that functionality to work to be considered a fix. Thank you!
> > 
> > 
> > Hi @navneeeth , Thank you for reviewing my PR. The reason why user can not see Assign badges page is because lacking of "seeBadges" permission which is not provided in the permissions management system. Only admin and owner role has this permission by default. I have added it to the volunteer role and tested and it works well. So the issue is when "assignBadges" permission is assigned to a user, the "seeBadge" permission is not assigned accordingly so 403 error appears. I can submit another PR by adding "seeBadges" permission to default but it can not solve this issue totally. What we need to do is to make "seeBadges" permission either avalible in the system or when we assign a user "assignBadges" permission, assign them "seeBadges" permission too. ![Screenshot 2023-10-12 162108](https://user-images.githubusercontent.com/92963742/274729081-2f202fec-4c03-4ddc-b6a4-718739fc572a.png)
> 
> Hi @Jiyuanxia! Thank you for addressing my review. Yes, such a permission does not exist in the system and that is why it needs to be created for this permission to work as expected in the frontend. I will approve this PR now since it only aims to fix the button's visibility in the UI. If you will be working next on a full fix on the permission in a new FE + BE PR set, please follow the conventions in the frontend and backend links I shared above and also the rules in the Permissions Management Fixes spreadsheet (You can find the link on the Bugs document by searching for the same title). Thank you!

Hi @sxiong5 and @vikrambadhan , thank you for reviewing. This pull request is intended to address the UI problem, and it has successfully fixed it. I have also identified the backend issue you mentioned. You can review the conversation between Naeneeeth and me above. Now, I am requesting you to re-review this.

2024-01-23 01:29 UTC, one-community commented
Thank you all, moving to final review.

2024-01-23 13:48 UTC, merged