Zijie fix report lint phase14
OneCommunityGlobal/HighestGoodNetworkApp pull request #1395
Opened 2023-10-09 07:22 UTC by iTvX

# Description
Lint fix for Reports component, this is phase 14（Last Phase）.

## Files changed
src/components/Reports/PeopleReport/PeopleReport.jsx

eslint test:
![CleanShot 2023-10-09 at 00 20 59@2x](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/debe58d7-2213-4c54-a963-13b4f0742f0c)

# How to Test

To test this pull request:

- Check out the current branch
- Run `npm install` and `npm run start:local` to run this PR locally  
- Log in as an admin user
- Check all the functionality of the report is the same as before, and see if any bugs have appeared. (Please record a video)

(Optional)
- Set up ESLint in VSCode/ IntelliJ IDEA, I personally use IntelliJ IDEA
- Delete .eslintignore file in the root: `rm .eslintignore`
- `npx eslint src/components/Reports/Reports.jsx`
- `git restore .`

2023-10-10 18:20 UTC, olenadanykh commented
Hi @iTvX. I've tested your PR, and it works as intended. I didn't encounter any ESLint errors, and all the functionality on the Reports page is working smoothly. Great work!

<img width="1250" alt="PR1395" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/ad75368f-c3ed-41fa-ae4a-1de751e5caea">


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/41383eb2-be02-458d-af1b-2b69d036b0c2

2023-10-11 03:25 UTC, lacnoskillz reviewed
Hello Zijie
I pulled your changes and ran them locally
At first it ran fine except some loading times for Show Total Team Report
look below
Also note the People category is 0

[Untitled_ Oct 10, 2023 9_47 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/383e4d83-9bef-4af1-ac4f-693d47965e8c)

 I noticed after clearing cache/site data and restarting server I don't get any category data at all 
this is me testing after clearing site data:

[Untitled_ Oct 10 2023 10_20 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/004211ee-242f-4562-8b72-008f486b26f6)

2023-10-12 10:53 UTC, iTvX commented
> Hello Zijie I pulled your changes and ran them locally At first it ran fine except some loading times for Show Total Team Report look below Also note the People category is 0
> 
>  Untitled_.Oct.10.2023.9_47.PM.webm 
> 
> I noticed after clearing cache/site data and restarting server I don't get any category data at all this is me testing after clearing site data:
> 
>  Untitled_.Oct.10.2023.10_20.PM.webm

Hi @lacnoskillz , thank your for the review. However, I can not see your video, could you please using another format or dropbox link?

2023-10-13 15:02 UTC, Iris-Song approved these changes
Hi @iTvX. I've tested your PR, and it works as expect.Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/fc641d32-56ac-40c7-920d-5fa4304fdf01

2023-10-14 16:03 UTC, RheaWu1212 commented
Hi I'm testing your PR and came across the same issue as @lacnoskillz, take a look at the video attached:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/01f8fc91-20ba-4306-921c-a1a7ea378505

2023-10-22 06:49 UTC, savio-henrique requested changes
Hi @iTvX !

I've tested your PR and, as the video below shows, things are not working as intended! The filtering is not working, the "People" counter is set to 0 and show no members. The "total reports" are working, but, as usual, taking long to be loaded, specially the 'Total Team Reports' .
 
Although, the ESLint showed no problems during linting, as shown in the screenshot below.

---

## Video and screenshot
 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83360232/ac2fcb2e-4f5c-46bc-9cb8-e09be0003ba6

![terminal](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83360232/d8c89e20-a8eb-4bbb-89d2-6c5c1a2bb11d)

2023-11-04 06:52 UTC, malikjahanzaib requested changes
Hi @iTvX, I ran this PR locally an there are no lint errors. But I encountered some bugs like the peoples tab is "0", which I think is not correct. Also there are some delays when clicking the users or loading the reports which also causes console errors but I guess that isn't related to this PR. Refer to my test recording.

Screenshots:

<img width="478" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/25b8bfa6-f141-44f1-9107-0a80b5d509f0">

Test rec:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/876319f6-0986-4c90-a6c9-96612163acca

2023-11-07 04:39 UTC, EvianTan commented on src/components/Reports/Reports.jsx
> +// eslint-disable-next-line no-unused-vars
Same comment as [here](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1356/files#r1384348686)

2023-11-07 04:40 UTC, EvianTan commented on src/components/Reports/Reports.jsx
> +      // teamMembersPopupOpen: false,
If the codes are unused, just delete them instead of commenting them.

2023-12-14 05:22 UTC, Alforoan requested changes
I did not get any lint errors, but the number of people was 0 for some reason.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/91656e1a-bf6f-4cfc-b5c3-1a76df5fa668

2025-03-02 00:40 UTC, closed without merging