Create a Weekly Summaries Reports recipient button for Owners
OneCommunityGlobal/HighestGoodNetworkApp pull request #1400
Opened 2023-10-11 06:52 UTC by mounica-dingari-by

# Description
Show and editable list of who is currently receiving the Weekly summary report and
it's password protected with the test account 
[mounica_test20@gmail.com]
Password@1234

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/49270410/e287dd82-e5a0-4920-99e7-5f7e145ad4f6)

## Related PRS (if any):
To test this frontend PR you need to checkout the #XXX backend PR.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to Reports→ Weekly Summaries Reports →  Weekly Summaries Reports button
5. Enter the password and if the user is Authorized, a popup shows up, with list of Weekly Summary recipients
6. Test if you're able to add/delete the Weekly Summary recipients.
7. The weekly summaries will be sent to the recipients through email. In order to test this, add yourself to the recipients and to send/receive email using Gmail API, using OAuth2 and nodemailer, kindly follow the below video and setup up a test mail id.
https://www.youtube.com/watch?v=-rcRf7yswfM&t=10s&ab_channel=MafiaCodes

Fill below variable values from the above setup in the .env file of the backend.
REACT_APP_EMAIL =
REACT_APP_EMAIL_CLIENT_ID =
REACT_APP_EMAIL_CLIENT_SECRET =
REACT_APP_EMAIL_REFRESH_TOKEN =
REACT_APP_EMAIL_CLIENT_REDIRECT_URI = https://developers.google.com/oauthplayground
sendEmail = TRUE

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/49270410/19ef1602-fa6c-4ea2-b923-b78b2527735c

![Screenshot from 2023-10-10 13-57-37](https://github.com/OneCommunityGlobal/HGNRest/assets/49270410/3ea7cc36-ca8f-415d-87ee-4a83a888be03)

## Note:
Include the information the reviewers need to know.

2023-10-12 17:56 UTC, lacnoskillz reviewed
Hi @mounica-dingari-by 
I pulled your changes for both frontend and backend #566
But its unclear what password to enter after pressing the Weekly Summary Report Recipients button and need it to test further
thank you!

2023-10-12 22:04 UTC, mounica-dingari-by commented
> Hi @mounica-dingari-by I pulled your changes for both frontend and backend #566 But its unclear what password to enter after pressing the Weekly Summary Report Recipients button and need it to test further thank you!

2023-10-14 00:03 UTC, StrawberryCalpico requested changes
Hi I tested your PR, the add and delete function works, great job, but can you add more details about setting up the email functionality? I followed the youtube video and successfully get the key and changed the cron job so it would execute every 10 secs however, it didn't work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/bbf19ff8-b3a4-4887-bc77-2df48dbf7dac

2023-10-15 04:09 UTC, John-Flavian commented
Hi @mounica-dingari-by , nice upgrade.

However, can you modify the initial authorization modal to close immediately after a authorization?

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46160341/3427f812-dedb-45f4-891e-079f433fa586)

Both buttons can handle the modal close function; then a snackbar can prompt the user about their authorization status.

Good job.

2023-10-19 00:54 UTC, malikjahanzaib requested changes
Hi @mounica-dingari-by, I have checkout both the FE and BE branches but I am facing this error consistently while running the app locally:

Error: Cannot find module '../utilities/nodemailer'
Require stack:
- C:\Users\JZ\Desktop\Reuse\HGNRest\dist\helpers\userHelper.js
- C:\Users\JZ\Desktop\Reuse\HGNRest\dist\cronjobs\userProfileJobs.js
- ...

I also tried installing "nodemailer" using npm but same issue persists. 

Is there anything that I might be doing wrong ?

<img width="956" alt="Screenshot 2023-10-18 174513" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/8f0768c6-22a8-44aa-96b3-003d93819a77">

2023-10-28 10:59 UTC, Bali2Mohit reviewed
I am facing error while trying to authorize password. 
I am logged in as test user: "mounica_test20@gmail.com" and password : Password@1234
Can you help with what i am doing wrong here
<img width="1427" alt="Screenshot 2023-10-28 at 11 57 09" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94716419/1e13755e-7cf1-43ba-9991-6536675d6406">

2023-11-14 06:04 UTC, wanglu1207 commented
Hi @mounica-dingari-by, I am facing the same issue as the Bali. It shows the password is wrong. Let me know if I am doing incorrectly or you fixed the bugs.
![Uploading Screen Shot 2023-11-13 at 10.02.41 PM.png…]()

2023-11-17 18:04 UTC, Changhao3220K commented
the error in backend is blocking me from properly setup frontend services, please check out the commend on frontend, Thank you!
<img width="1297" alt="Screenshot 2023-11-17 at 1 03 59 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104778270/6fcb95e3-3d9b-42bc-8a50-c2a102b0e728">

2023-11-17 18:18 UTC, Changhao3220K reviewed
Hi @mounica-dingari-by 
the backend code is not able to run build properly on my local environment, and the frontend will bring me error notifications.
<img width="1297" alt="Screenshot 2023-11-17 at 1 03 59 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104778270/122bfd05-d897-45d2-a8af-c6ab2d7383fd">

2023-11-17 21:06 UTC, Shuhua-L requested changes
Details are left in the [BE review](https://github.com/OneCommunityGlobal/HGNRest/pull/566#pullrequestreview-1737925755). 

I successfully compiled the backend but ran into issues getting it running. Let me know if you address this issue, and I'll be more than happy to review again.

2023-11-18 15:27 UTC, kavya151 commented
Hi @mounica-dingari-by, I am facing this error while trying to run BE locally. Please help me out.
<img width="1036" alt="Screenshot 2023-11-18 at 8 27 02 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/8eeff213-5c2a-450e-be7e-7621ab3fa4a2">

2023-11-18 16:21 UTC, ptrpengdev commented
Hi @mounica-dingari-by, the application failed to start due to a missing file nodemailer.js in the utilities folder. 
<img width="841" alt="bugModuleNotFound_BEPR566" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/9067d4a5-c620-46a0-847e-5e5fd2e9c6cb">

2023-11-18 22:04 UTC, palakgosalia commented
Hey, I tried testing out the PR but I wasn't able to run the backend because I was facing the following issue. Attaching a screenshot of it. Thank you

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/62a3c3a3-1888-4c6b-9e75-4bae6a00b17d)

2023-12-02 05:44 UTC, Alforoan requested changes
I keep getting a password error. Please look into it. Thanks.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/f9d162c3-b1f3-4482-88ef-79a38e4bac43

2023-12-07 17:00 UTC, DragonSlayer2401 commented
I tested this PR using the related backend. The backend was unable to be started. Please see the video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/f568c392-03a7-485e-9119-428a9398aaa0

2023-12-07 19:57 UTC, DragonSlayer2401 commented
Also please fix your #566 link it goes to the wrong backend

2023-12-09 01:07 UTC, sucheta90 reviewed
Hello @mounica-dingari-by , I was able to start the application after setting up the backend environment variables and by changing the path in the dist folder locally. However, even though I logged in with credentials provided in the description, I got an authorization error while trying to pull the editable list of recipients. Please refer to the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/994f4325-a8b6-4d31-a22d-c42ca0318fa5

2023-12-13 04:43 UTC, pika-chu11 reviewed
Hi @mounica-dingari-by , I have tested your PR. Thank you for your effort!
I ran into the issue as **sucheta90** did.
I followed your instruction:
1. Log in using [mounica_test20@gmail.com] and [Password@1234].
2. I do see a button labeled 'Weekly Summary Report Recipients'.
3. When clicked on it, there is a popup where need to fill in the 'Password to Authorise User'.
4. I have tried to enter [Password@1234] as the password, but it shows that "Incorrect password". So I was able to test whether if the email notification sending is functional.

> I have also tried to use my account to login and use the password you provided to get access of sending recipients email. Same issues as above: wrong password.

Please refer to the video for more detail:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/fa2da6b4-d9bb-4bb5-83b3-da894fd0d0af

2024-02-18 02:08 UTC, brandta-1 requested changes
# Review
Unable to test on locally with back end branch ```mounica_weekly_summary_reports_button_backend``` due to a missing ```/dist``` utility as cited by others. Link to [back end review](https://github.com/OneCommunityGlobal/HGNRest/pull/566#pullrequestreview-1887065653)

2024-08-13 22:40 UTC, Gmon-k commented
I have checked the result and it is working fine. Below is the screenshot for it

<img width="1024" alt="3" src="https://github.com/user-attachments/assets/7c68d230-d005-4f79-8a29-b3e91a534048">

2025-03-13 02:31 UTC, sri0606 commented
@one-community , this can be closed. Re-implemented in this already [merged PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2006)

2025-03-14 20:11 UTC, closed without merging