Tim add Materials List page
OneCommunityGlobal/HighestGoodNetworkApp pull request #1401
Opened 2023-10-11 20:18 UTC by tdkent

# Description
Add the Materials List page (Phase 2), a table of all purchased materials being used by the organization in their building projects.
- [Docs](https://docs.google.com/document/d/1WONWQW_56pXlyZpdQFibddFuT3iMxFjho-wfGwbHFV8/edit#bookmark=id.shlm4iwupd4s)
- [Wireframes](https://www.figma.com/file/kpwXZP2pLtOJ1Fn2u7Sivn/HGN-PII?node-id=505%3A5786)

## Related PRS (if any):
To test this PR you need to checkout [backend PR #567](https://github.com/OneCommunityGlobal/HGNRest/pull/567)

## Main changes explained:
- Adds route “bmdashboard/materials-list”
- Adds **bmdashboard** subdirectory to the actions, components, and reducers folders with related JS, JSX, and CSS files.
- On page load, an API request is sent to the backend to fetch the data (see backend PR for more). The response (either an error or the data) is added to Redux state and mapped to `props`.
- Based on the fetch result, the page will display either the error, the data, or a zero results page if there is no data.
   - Note: data values are arbitrary
- Data can be sorted by project
- Each data entry contains additional Usage, Updates, and Purchase info accessible via a button that opens a modal. There are also edit icons that currently return null but will eventually access Edit forms.

## How to test:
- Follow steps to test backend PR 567
- `git checkout Tim_bm_materials_list_index`
- `npm install`
- `npm run start:local`
- Log into HGN as a volunteer
- Verify your credentials at “/bmdashboard”, then navigate to “/bmdashboard/materials-list”
   - Note: you will need to manually enter this into your URL bar as there are currently no nav links
- The Materials List page should display a table with about 25 rows of dummy data by default
- Test the Projects filter properly filters the results by project
- Test the “View” buttons for various rows to test that a modal with new data is displayed
- Test modal overflow: in row Tim Test Project 1 > River Sand (default first row), open the Usage, Updates, and Records modals. Each have enough data rows added to ensure the modal will overflow the results. Try scrolling the modal to test overflow is working properly.
- Test the page and modals are adaptive to page width.
   - Modal widths are reactstrap defaults (I cannot figure out how to change this) and not very good. I added overflow styling so the modals should be able to handle x-axis overflow at narrower screen widths.
   - Main page styling is also mostly reactstrap defaults, but the table should also handle x-axis overflow at narrower screen widths.
- Test error state: if the fetch attempt returns an error, the page will display the error information with a button to reload the page and try again.
   - Easy way to test client-side error: open the file **actions/bmdashboard/materialsAction.js**. In the **fetchAllMaterials** function, edit the `ENDPOINTS.BM_MATERIALS_LIST` string so the request is sent to an incorrect endpoint (404 error)
   - Easy to way to test server-side error: deactivate the backend so that no response object is included in the error object (503 error)
- Test ‘no results’ state: if no data is returned from the database, table layout will be replaced with “No materials data” text and the Project filter will be disabled
   - How to test: in fetchAllMaterials func, change dispatch(setMaterials(res.data)) to dispatch(setMaterials([]))
   - Note: you made need to refresh the page twice

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/bba52a8a-b180-4206-9d0e-18c65ee5377f

2023-10-11 22:07 UTC, ChirayuRai commented
Great work on implementing everything! It looks quite nice, and it's also responsive. Scrolling works on the table all throughout, and the code seems to all be in order. Error handling also properly shows error toasts. 

I have noticed that if there's a 503 error, then 7 toasts pop up on the page with different timings for all of them. I also cannot close them by pressing the "x" in the top right corner sometimes. I have also noticed that all the buttons on screen seem to stop working when the error messages pop up, and after they are gone as well. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15188751/9b316090-8867-4304-b857-bb46c5d77c21

Also, it seems there is nothing that occurs when the edit button is pressed. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15188751/1bb8e89f-99b7-49a2-9614-7f264d37665e

2023-10-11 22:23 UTC, ChirayuRai reviewed
Great work on implementing everything! It looks quite nice, and it's also responsive. Scrolling works on the table all throughout, and the code seems to all be in order. Error handling also properly shows error toasts.

I have noticed that if there's a 503 error, then 7 toasts pop up on the page with different timings for all of them. I also cannot close them by pressing the "x" in the top right corner sometimes. I have also noticed that all the buttons on screen seem to stop working when the error messages pop up, and after they are gone as well.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15188751/48539401-3006-4126-ae05-b37f944a263d




Also, it seems there is nothing that occurs when the edit button is pressed.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15188751/8bf10e0e-c754-4c6f-94dd-6452f6de3e88

2023-10-11 23:43 UTC, tdkent commented
> Great work on implementing everything! It looks quite nice, and it's also responsive. Scrolling works on the table all throughout, and the code seems to all be in order. Error handling also properly shows error toasts.
> 
> I have noticed that if there's a 503 error, then 7 toasts pop up on the page with different timings for all of them. I also cannot close them by pressing the "x" in the top right corner sometimes. I have also noticed that all the buttons on screen seem to stop working when the error messages pop up, and after they are gone as well.
> 
>  Screen.Recording.2023-10-11.at.3.05.26.PM.mov 
> Also, it seems there is nothing that occurs when the edit button is pressed.
> 
>  Screen.Recording.2023-10-11.at.2.49.16.PM.mov

Thanks for your comment. The error toasts are the result of other error handling in the app. The edit buttons are currently not hooked up to anything and return null for now. I've updated the PR description to make this more clear.

2023-10-12 08:29 UTC, DavidC0126 approved these changes
Hi @tdkent I tested your PR and it works as intended.

1. Display row data normally, and filter the result properly by project.
<img width="1652" alt="Screenshot 2023-10-12 at 1 10 32 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/86f4a70b-8a75-421f-9812-257fdd4bd0aa">

2. "View" buttons and overflow data work as described


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/4cccdc55-de8d-47d1-964b-bfdc58fa3501



<img width="1634" alt="Screenshot 2023-10-12 at 1 11 32 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/4176ced9-68ee-4944-bcbb-1bfb2b4d5ac7">
<img width="1634" alt="Screenshot 2023-10-12 at 1 11 52 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/9a07bfc7-f44f-4a72-8eab-233d79635267">

3. Error state and no data state are shown as described in the test.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/73a2bfb9-3336-48bf-8fa8-f12bd2335f08

2023-10-12 17:14 UTC, olenadanykh commented
hi @tdkent. I've tested your PR, and it appears to be working as intended. The table displays properly, the row data is shown correctly, and the filtering by project works as expected. Also "View" and "Tim Admin" buttons works as described.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/b417024a-0753-407f-953a-e4d51496637a

2023-10-12 18:55 UTC, lacnoskillz approved these changes
hello @tdkent 
I pulled your backend #567 and front end code
After messing with it for longer than id like to admit and realizing I forgot to run build in the backend I got your changes to work! ha-ha
Everything is working as described!

[Untitled_ Oct 12, 2023 1_43 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/1b96e0f2-ddca-498a-b424-22d227381ee8)


I would note in galaxy fold view port the projects dropdown is a little off center but no big deal
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/7c573446-cac1-4bf1-8678-0052710d1abd)


tested no materials data
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/c6821c5c-4492-4c78-a3ad-a70ecac43df7)


Nice work!

2023-10-12 20:43 UTC, emunkh404 commented
I attempted to test it, and it displayed this: http://localhost:3000/dashboard/bmdashboard. However, when I tried various methods, it didn't display anything similar to http://localhost:3000/bmdashboard/materials-list.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/5ea55eda-f852-4b1b-aeae-0f337759381b)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/ff74d332-6926-42ff-9d94-2c407b056cc4)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/56a652a6-6da6-456c-83ee-f7359b0ab2d0)

2023-10-12 21:13 UTC, tdkent commented
> I attempted to test it, and it displayed this: http://localhost:3000/dashboard/bmdashboard. However, when I tried various methods, it didn't display anything similar to http://localhost:3000/bmdashboard/materials-list.
> 
> ![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/5ea55eda-f852-4b1b-aeae-0f337759381b)
> 
> ![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/ff74d332-6926-42ff-9d94-2c407b056cc4)
> 
> ![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/56a652a6-6da6-456c-83ee-f7359b0ab2d0)
> 
> 

Did you check out and build the backend PR? What errors displayed in your console? Please provide more info so it's  possible to debug the issue you are having.

2023-10-13 01:43 UTC, tsunami776 approved these changes
Hi @tdkent, I followed the steps in your PR and tested locally with the BE PR using a volunteer account. 
The functionalities mentioned in the PR work as described. After logging into /bmdashboard, user can access material list page. I tested Modal overflow by shrinking x-axis, and the content will adjust accordingly. For error states, I followed your test instructions, and error states are handled correctly. Great work!



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/a0d54c31-1ba8-437c-8424-1cdf5336d43c

2023-10-13 02:14 UTC, StrawberryCalpico approved these changes
Hi I test your PR. Worked as expected, great job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/e653063d-39ff-428c-8244-58b3c8644592

2023-10-13 14:54 UTC, Iris-Song commented
Hi, when I test login in as volunteer, I got a 404 page. Does it mean I don't have credentials or something wrong?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/ec8c8808-b45e-4dd5-bdb4-eb77998c4590

![Screenshot 2023-10-13 at 10 51 25](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/f8ddba3d-5596-47e4-adde-f502f6acdc3c)

2023-10-13 20:14 UTC, JeffLi117 submitted a review, later dismissed
Changes work as intended. Good job!

Initial view of "/bmdashboard/materials-list” after verifying credentials at "/bmdashboard":
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/70b107a5-6113-4e27-b438-1debe18d76e1)

Filtering by projects works; here is one view: 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/d41564d8-8e08-4382-a514-d5a4478a2a6a)

Testing the "View" buttons, modal overflow, and different screen width:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/d4b210c9-355e-4471-9ce1-c838a4b98eca)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/6cc57f28-c807-4779-b64e-e9dbde4a4194)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/086f2bb3-d00b-4e37-b46e-283ef2009c77)

Client-side error: 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/e8801ee2-dbd7-497a-a3e3-9dcdc44dbb52)

Server-side error: 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/e03a95bf-dbfc-497d-a039-e29b8391d937)

No results state:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/0755ea08-7be4-45aa-90ff-6cf56094df93)

Great job!

2023-10-14 00:54 UTC, malikjahanzaib submitted a review, later dismissed
Hi @tdkent, I tested this PR locally and all the features implemented work as described including error states. Below are my Test recordings. Great Job!!!
P.S. The only issue is that the FE gets "Compiled with warnings". I saw the same error in your recording as well so I assume you are aware of that.

Test Rec:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/bbf45ebe-116b-4359-b615-0dd69626bec3

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/bbe2dafc-35ee-4732-9311-7d455d29393b

2023-10-14 14:53 UTC, RheaWu1212 commented
Hi, I'm testing your PR, however, I didn't get anything expected. I've tried to 'git checkout Tim_bm_materials_list_index' and latest branch, but it keeps giving me 404. I've cleaned cache several times and manually put the link, result shows like this:
<img width="1271" alt="Screen Shot 2023-10-14 at 10 44 33" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/03c4799b-074a-48a2-b5b7-14284a5b341e">

2023-10-14 15:43 UTC, yurisokolovicz requested changes
Hi Tim,

Minimal adjustments are required to match it exactly with the Figma. Check below:

2023-10-14 15:43 UTC, yurisokolovicz commented on src/routes.js
> +      <BMProtectedRoute path="/bmdashboard/materials-list" component={MaterialsList} />
Hi Tim, while checking Figma, in order for the path in the navbar header component to match with this, it should be "/bmdashboard/material-list," right?

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/d66bf120-cc52-4ed0-a925-9f0409c9a6be)

2023-10-14 15:55 UTC, TuanDinh140194 submitted a review, later dismissed
Hi Tim! I have tested your PR with the following instruction: 
First, I have logged in as volunteer, and go to the  “localhost:3000/bmdashboard/materials-list” and the lists have display as expected with 25 rows of data and I can scroll down to see the overflow data.
Next, the filter of project is work great with filter the result of data/
I also have open the Usage, Updates, and Record modal and everything is responsive.
The page wildths is also work. I have test with the smaller screen and it can scroll horizontal to see the over flow data.
Next, for the test error, I have change the ENDPOINTS.BM_MATERIALS_LIST string on the code, and it only show the red modal with the unexpected error. Is it need to be show the incorrect endpoint (404 error)?
Finally, I have remove the res.data in function dispatch(setMaterials(res.data)) and it show “No materials data” . Below is my video of testing

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/60fc7676-8969-4825-bd55-b2c4ab61e22b

2023-10-14 22:43 UTC, tdkent commented
> Hi Tim,
> 
> Minimal adjustments are required to match it exactly with the Figma. Check below:

There is no requirement to exactly match the wireframes.

2023-10-14 23:12 UTC, yurisokolovicz commented
> > Hi Tim,
> > Minimal adjustments are required to match it exactly with the Figma. Check below:
> 
> There is no requirement to exactly match the wireframes.

Yes, no problem. It needs to match the navbar link URL address, so I will update it in the header to "/bmdashboard/materials-list" instead of "/bmdashboard/material-list.

2023-10-14 23:13 UTC, yurisokolovicz approved these changes

2023-10-17 16:50 UTC, one-community commented
Thank you all, moving to final review!

2023-10-18 12:17 UTC, beblicarl submitted a review, later dismissed

2023-10-18 16:49 UTC, KurtisIvey requested changes
Great job on this. Everything looks really good. The functionality is 100% there and it's fully responsive:
![pr1401 functioning](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/20855340-155c-44a1-9964-21feb5edc826)

Your error handling within the page works flawlessly as you described in the instructions as well:
![pr1401 handles bad url fetch](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/533adef6-c76c-4efe-99f0-3b0c38766b02)
![pr1401 error page works when no materials](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/e93561ed-3bc2-40fb-b73b-1fc1bdfaab43)



I just had some small fixes to suggest and some things I'd like to clarify.

This one isn't related to my request for changes, but it's something that I noticed while checking out your PR. The back to top button seems to be malfunctioning and showing while at the top of the page. (Note: not pr1401 that caused this but the back to top button).
![pr1401 non failing issue with back to top](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/70b593f6-8894-426d-b64a-a1275dc196cf)


I noticed you were using index as the key in the props. Not sure why linting isn't catching this, but it's generally considered bad practice to do so. If you need to, you could create a unique key through the use of combining the date timestamp & createdBy._id.
![pr1401 shouldn't use I as the key in prod version](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/fda461c6-d28a-456f-9162-29e5ca093bb0)
![pr1401 shouldn't use I in the key](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/7d15a2ba-b844-4e3b-a9c3-df2ab6523638)
![pr1401 dont want to use i as key](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/4e16d9a4-42db-4e2d-847d-d676364380db)


I was also wondering your thoughts on implementing a sorting algorithm to sort these by date on the following modals as the date is not sorted chronologically. This could be implemented directly within the mongodb query on the backend:
![pr1401 does this sort via the usage date](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/a7fe1683-81fa-4bb6-865a-2fdf3abbd7f5)
![pr1401 need to confirm if purchases sorted via date](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/0c91ad8f-bd75-43db-b9b8-23432386e09e)
![pr1401 does updates sort via date](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/0ea1ca7a-9e7d-40b7-9d0e-15a1a3b51889)


The only other thing I noticed was a css warning due to use of "end" instead of "flex-end"
![pr1401 fix materialsList css](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/58c6be2e-cf82-407b-8a7f-6b8715be365f)


Other than those small things, it's all pretty stellar. 

List of my requested changes:
 - fix the use of "i" as the key
 - implement chronological sorting in mongodb query
 - fix css use of "align-items: end" to "align-items: flex-end" so the warning goes away

2023-10-18 19:45 UTC, tdkent commented
@KurtisIvey Thanks for your comments. I pretty much agree with your suggestions!

1. I'm aware that using the array index as a key is not recommended. However in this case the data being displayed is entirely dummy data, most of it duplicated, so combining props as you suggest may result in duplicated key errors, so I used the index as a temporary workaround. (Btw, the linter did pick up the error but I disabled that lint rule for this). For now I will change the key as you suggest and remove the lint exception. Once we can manually create new materials on the frontend (in progress) I will need to revisit anyway.
2. I fully intend that sorting and advanced filtering should be available for the data, however I decided it was unnecessary to implement that at this time and more important to get this already large update up and running. I should have been more clear about my intentions in the description though!
3. Thanks for the catch on flex-end. I glazed over the error but have fixed it now.

2023-10-19 18:22 UTC, KurtisIvey approved these changes
Everything checks out. Great job. The error handling still works without issue as well after the recent changes. 

Just like you mentioned, the keys caused a duplicate error. However, it's not important since this was something you said you'd address later. Thanks for taking the time to explain things to me about how a lot of this is still in development

2023-10-19 20:14 UTC, merged