Aaron add message to popup management when there are no popups
OneCommunityGlobal/HighestGoodNetworkApp pull request #1417
Opened 2023-10-15 05:26 UTC by AaronPersaud

# Description
Currently, whenever an admin/owner goes to the Popup Management page, no content is loaded if there aren't any popups. I've added a message that appears when no popups exist. I've also renamed the route to /popupmanagement, since the link currently reroutes to /admin which is confusing.

## Related PRS (if any):
N/A

## Main changes explained:
- added text to the Popup Management page when no popups exist
- renamed route for Popup Management for /admin to /popupmanagement

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin/owner user
4. go to dashboard→ Other Links → Popup Management
5. verify you are taken to /popupmanagement instead of /admin
6. if there are no popups, verify that you can see the message below 

## Screenshots or videos of changes:

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/8653e09a-a3d4-4afb-a131-b602f9d0bfdd)

2023-10-15 05:59 UTC, ChirayuRai submitted a review, later dismissed
I just tested your PR! It seems that clicking on the popup management tab in the "other links" dropdown DOES take me to /popupmanagement, however I see a different screen than what was posted in the screenshot. 

![Screen Shot 2023-10-14 at 10 58 27 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15188751/ca7b93b2-a225-4483-8093-b377cea91110)

2023-10-15 06:03 UTC, AaronPersaud commented
Hi @ChirayuRai, thank you for reviewing. Since your account has popup messages, you're not going to see that message. Please see step 6 in my instructions.

2023-10-15 20:29 UTC, yi-lin-1234 approved these changes
Hello, I tested your PR and works as intended. Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/fc4ac873-cc9d-42b0-ac1d-c9c86a1d8e38

2023-10-16 14:22 UTC, RheaWu1212 commented
Hi, it works as expected!
<img width="1318" alt="Screen Shot 2023-10-16 at 10 21 28" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/a4a86b2b-4a74-4367-9c32-4f8d2a909aa9">

2023-10-17 19:11 UTC, Sssky-18 approved these changes
Hi @AaronPersaud, I tested your PR, and the feature worked as expected. The popup management displayed great with the correct text on it. Thank you for your work! 

<img width="1108" alt="PR#1417" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/1b1670e0-0ada-474d-a212-98e982fad506">

2023-10-18 00:57 UTC, lacnoskillz approved these changes
Hello @AaronPersaud 
After pulling and testing your code it appears to work as expected and I am now getting the new message when I have no popups!
Nice work

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/715e9934-7170-44e5-9ec2-39c28324c2a4)

2023-10-18 07:04 UTC, DavidC0126 approved these changes
Hi @AaronPersaud I tested the PR and it works as described!

<img width="839" alt="popup" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/f2236537-7ccd-43f5-b444-c825ab8625aa">

2023-10-18 20:21 UTC, dah00 approved these changes
Hey @AaronPersaud, I tested your PR and everything works as expected. It is taking me to /popupmanagement and the no popups message is displayed. Great Job!
![PR1417_check](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61763829/0f8bdd9b-27ee-4c6e-9311-47e8b840fd7a)

2023-10-19 20:30 UTC, emunkh404 commented
Hello @AaronPersaud, I've reviewed your pull request, and I'm happy to report that everything functions as anticipated. It successfully directs me to /popupmanagement, and the message indicating no popups is displayed. Excellent work!
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/94ba01e8-cbfc-4a51-9bed-6447296263ad)

2023-10-19 21:35 UTC, Chuehleo approved these changes
Everthing work as intended, great job!
![Screenshot 2023-10-19 143413](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/2c3f9f1e-99e5-4bf5-9017-9f89a98a2d17)

2023-10-19 22:48 UTC, tsunami776 approved these changes
Hi @AaronPersaud, I tested your PR and it works as described. Now if there is no popup, there will be a message showing. The route rename also makes sense. Nice work!

![1417](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/cf5ea531-c45a-4d9d-b727-f568ed057edb)

![1417-2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/bca35dbc-e5ac-4537-a2de-bc9d3afef04b)

2023-10-20 01:22 UTC, Jiyuanxia approved these changes
Hi @AaronPersaud , I have reviewed your pull request and tested it. It works as you intended. Good job!
![Screenshot 2023-10-19 212124](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/81c12fe0-7bc6-4526-8980-14447dd191de)

2023-10-21 04:44 UTC, one-community commented
Thank you all, moving this to final review!

2023-10-21 04:46 UTC, Shubhu0 approved these changes
Hi @AaronPersaud Tested the PR and it is working as intended. I did get the popup button for both accounts, admin and owner and it did redirect me to the required page as well!

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/c5309a3e-345a-4518-9aae-a7e7d5639092)

2023-10-21 06:09 UTC, StrawberryCalpico approved these changes
Hi, I tested your PR. It works as expected. Good work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/338080f3-9a52-47a3-b9e1-48d71ea6ed9a

2023-10-21 12:37 UTC, Iris-Song approved these changes
It works as intended when I log in as admin. Good job.
<img width="923" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/7ca6b762-1535-4a5c-9d6e-3570f76fcd9e">

2023-10-21 19:49 UTC, shubhankarval approved these changes
Hey @AaronPersaud, I tested this PR and everything works as expected, good job. 
![PR 1417](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59073366/9f3ad158-79af-4ca5-afa2-7e755acaf7d2)

2023-10-21 20:47 UTC, vikrambadhan requested changes
Hi, I tested your PR ! However, the /popupmanagement screen is different from the one that shows up in the posted screenshot.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/b753ca46-e718-4638-984a-34d82ebc97f0

2023-10-21 21:48 UTC, TheDescendant39 reviewed
Hi @AaronPersaud , your changes work as intended. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/fcb6f4b5-19b2-4384-8187-809418952fec

2023-10-22 04:55 UTC, zuhang2000 reviewed
Hi I've tested your PR following your instructions. However, I don't have the popup message as others show in their test. Please check the screenshot below.

<img width="1353" alt="Screenshot 2023-10-22 at 12 55 02 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/c2d11e81-2fd9-4206-af39-e48f08953f60">

2023-10-23 20:19 UTC, KurtisIvey approved these changes
Works as intended. Good idea to add something like this to handle no popups.

Due to my owner account having popups, I did have to change the condition to !== 0 instead of the original === 0.

<img width="1283" alt="Screenshot 2023-10-23 at 3 08 00 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/c62d8172-9b41-4084-8721-88dc3a65518d">

2023-10-23 20:20 UTC, KurtisIvey commented
> Hi I've tested your PR following your instructions. However, I don't have the popup message as others show in their test. Please check the screenshot below.
> 
> <img alt="Screenshot 2023-10-22 at 12 55 02 AM" width="1353" src="https://user-images.githubusercontent.com/123051008/277146033-c2d11e81-2fd9-4206-af39-e48f08953f60.png">

change the condition from === 0 to !== 0 in the admin.jsx file

2023-10-23 21:36 UTC, merged