Update FormattedReport.jsx
OneCommunityGlobal/HighestGoodNetworkApp pull request #1418
Opened 2023-10-15 07:46 UTC by Jiangwei-shi

# Description
Please include the exact bug/functionality description and a summary of the changes/ related issues. Please also include any other relevant motivation and context:
Fixes # (URGENT) Jae: Fix committed hours not showing correctly on the Weekly Summaries page

## Main changes explained:
- fixed the hours logged in Weekly Summaries Reports
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin/owner user
4. Create a new user and set Weekly Committed Hours
5. Go to Weekly Summaries Reports page and under "This week" tab. check the new user's Hours logged shows correctly.

## Screenshots or videos of changes:
![屏幕截图 2023-10-15 034608](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/5267f6dc-24c5-44f4-bc36-4e51f7be31a7)

## Note:
Include the information the reviewers need to know.

2023-10-16 06:33 UTC, AaronPersaud requested changes
Hi @Jiangwei-shi, I reviewed the PR but it seems new accounts are still having the committed hours showed incorrectly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/2ec2b7e1-f2d8-47e1-a470-17df50d4cd8c

I have a feeling the error is not coming from the `FormattedReport.jsx` page, but it's how the `promisedHoursByWeek` array is being populated.

2023-10-16 14:12 UTC, RheaWu1212 commented
Hi, I'm testing your PR and had same issue Aaron mentioned before:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/e3fb47bb-1590-48a0-830d-4a070b94e343

2023-10-16 23:40 UTC, yi-lin-1234 reviewed
Hi, I'm testing your PR and had same issue above, the hours display 0.00 / 0

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/c0e59385-a5c6-445b-bf4e-e94700caf066

2023-10-17 17:23 UTC, beblicarl commented
Unfortunately, the weekly hours do not reflect 

[screencast-hgnapplication_react_beta.surge.sh-2023.10.17-17_21_19.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/cc2a6416-688a-4f6d-8e2d-b390d79926df)

2023-10-17 18:07 UTC, sxiong5 commented
Hey @AaronPersaud, @RheaWu1212, @beblicarl, @yi-lin-1234. I noticed that all of you guys were checking the committed time in the **Last Week** tab. But actually, you should check in the **This Week** tab since you created the new user, and it makes sense it shows as 0 in the "Last Week"

2023-10-17 19:52 UTC, wantingxu7 approved these changes
Hi @Jiangwei-shi 
the function LGTM, please find the recording. Good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/bcd7ce4f-6992-4cca-aea7-2e8947a4a68e

2023-10-17 21:13 UTC, Sssky-18 approved these changes
Hi @Jiangwei-shi, I tested your PR, and the logged hours are displayed correctly. I created a test account for this PR with 50 weekly hours. Then when I checked it on the weekly summary report page, the hour number was shown for this account properly. Thank you for your contribution! 


<img width="596" alt="PR#1418" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/19e9cb76-650a-4052-a016-aed2fad87fc0">

2023-10-17 22:48 UTC, StrawberryCalpico approved these changes
I tested your PR, it works as intended! I can see correct time under "this week".

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/0867d8c9-81fa-4ffd-9429-34ba3b9c1716

2023-10-17 22:53 UTC, nathanah approved these changes
The code looks like it's nearly logically equivalent. I don't think it actually solves the bug that it intends to fix, nor is the suggested means of testing adequate, but it does improve code quality independent from fixing that bug.

2023-10-18 01:25 UTC, DavidC0126 approved these changes
Hi @Jiangwei-shi I tested the PR and it works as intended.
<img width="1657" alt="timeCheck" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/65d4fabb-bd45-4f78-b17b-c620e98e460c">

2023-10-18 02:09 UTC, AaronPersaud approved these changes
Hi @Jiangwei-shi, as per Shihao's comment I realized I was looking at the wrong tab. Sorry about that! It works great and I am approving the PR.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/8a26dead-2257-43fd-9740-66633850ef32

2023-10-18 17:04 UTC, lacnoskillz approved these changes
Hello @Jiangwei-shi 
It appears that your code is working as intended. Nice work!
However I noticed that it was already working in the development branch
But even with your changes it still works as you intended the hours in 'This Week' tab matches.

Video with your changes:

[Untitled_ Oct 18, 2023 11_59 AM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/d3b81088-3675-452a-afa9-00b08cd413f8)

heres a screen shot of me on development making a new user with 11 hours:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/28874866-f829-4110-9959-763c039a22ae)

2023-10-18 18:31 UTC, eduhorta approved these changes
Hey @Jiangwei-shi!
I've tested your PR and the logged hours are displaying correctly.
Great job! 👍 

<img width="865" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/222407a6-2808-4519-a801-3107dfe8041e">

2023-10-19 00:25 UTC, emunkh404 commented
Hi @Jiangwei-shi, I have tested the PR, It appears that your code is working as intended

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/ba3181ed-5ae7-4733-91f1-6636fb2d6596

2023-10-19 00:39 UTC, one-community commented
Thank you all, moving to final review. If @beblicarl approves this, I'll merge it!

2023-10-19 14:20 UTC, beblicarl commented
This functionality works as intended @one-community 

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/c30db4ea-1c9f-44cb-b0da-4c299f60804c)

2023-10-19 14:20 UTC, beblicarl approved these changes

2023-10-19 14:24 UTC, merged