Ramya teams limit see all
OneCommunityGlobal/HighestGoodNetworkApp pull request #1425
Opened 2023-10-18 06:35 UTC by ramyaram2092

# Description of the feature

- A “Limit See-All” option for teams 

-  Other Links ->Teams

- When this option is turned on for a team member,  the team member  shouldn't  be able to see  other members of the team in their dashboard 

- The member however should be able to see team members of other teams  they are part of 

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
-  Added a column ‘See all’ in the "Team Menber " popup
-  A tool tip beside See All
-  Added a Toggle Switch in Add/Edit Teams pop-up beside every row 
-  Renderd the toggle switch with apprpriate choice.
-  When the user makes the choice,  make a call to   action function 
-  The  action fiunction  makes a post call to the backend 
-  Make a dispatch call to the reducer to update the redux store. 

## How to test:
1.  check into current branch
2.  do `npm install` and `...` to run this PR locally
3.  log as admin user
4.  Go to Other Links ->Teams
5.  Create two Teams , lets say Team A and Team B (you can use any existing Team as well)
6.  Add  the same  team member to Team A and Team B
7.  Enable the toggle switch in Team A for this member
8.  Login to the user's profile and verify if the user is only able  to see  the team members of the  team B and not Team A

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2023-10-19 06:30 UTC, DavidC0126 submitted a review, later dismissed
Hi @ramyaram2092 I tested this PR with BE [PR#576](https://github.com/OneCommunityGlobal/HGNRest/pull/576) and it works as intended! Good job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/86a87d53-874c-4eca-9f46-64ee0e3cf303

2023-10-19 16:15 UTC, shubhankarval requested changes
Hey @ramyaram2092, I would like to request 3 changes. 

1. Please change the text in the popup, its kind of confusing. Does enabling the option mean 'allowing the user to see all team members'?
![pr](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59073366/3ee96756-bb2d-43e3-9679-24a46d8a6386)

2.  The state of the toggle is not preserved. 
After enabling the toggle:
![pr1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59073366/c91d8924-276d-475d-a52c-088d888dec2d)
After closing and reopening the members popup:    
![pr2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59073366/d820809b-f22c-4de6-b12c-1e33fc0e5948)

3. If possible, can you make the toggle open to the right and not to the left, as that is the commonly used pattern. This would mean the toggle would be disabled (gray) on the left side, and enabled (blue) on the right side.

2023-10-21 00:30 UTC, StrawberryCalpico requested changes
The functionality to let user unsee their team members work, great job! but the state of the toggle will be reset if i close the pop up window. Since the toggle is reset every time, there is currently no way to make the user able to see their team members again.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/0334f792-6141-4738-8641-90d221fb645e

2023-10-21 02:25 UTC, ChirayuRai requested changes
Hey! It seems that setting the toggle sets the value to false, and I think that doesn't preserve the state for being able to view other members. I think that's also why that option doesn't persist when closing the popup.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15188751/b3be4ae0-2679-46b6-8b03-95c1e5f2e92a

2023-10-21 02:48 UTC, ramyaram2092 commented
I am investigating the bug/ feedbacks received so far. Marking the PR to "do not review " for now on the same account

2023-11-11 08:40 UTC, ramyaram2092 commented
Hello @ChirayuRai  @shubhankarval @StrawberryCalpico I have addressed your feedbacks. Could you  re-test and let me know your observation?

2023-12-15 06:43 UTC, Alforoan submitted a review, later dismissed
It works as intended. Nice!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/79e3c2f8-1b69-4a2b-aa87-4a2b4d4c273e

2023-12-23 02:24 UTC, keyunhuangg commented
I added the same members of both team a and team b. And disable the button for in team a for keyun(testing) huang. the teams in profiles do not show team a. and there is no member in the leaderboard.

<img width="841" alt="Screenshot 2023-12-23 at 10 17 39 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/584ad033-c1b0-4574-8b48-f393b90a0f66">
<img width="829" alt="Screenshot 2023-12-23 at 10 20 18 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/68eda0bc-7699-415c-aebd-b835ca85efd9">
<img width="902" alt="Screenshot 2023-12-23 at 10 17 44 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/6969908d-cd96-413e-bfa9-a970766500e7">
<img width="629" alt="Screenshot 2023-12-23 at 10 24 18 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/2172d703-f151-403d-8359-28c71ba12069">

2023-12-23 23:40 UTC, sucheta90 reviewed
Hi @ramyaram2092 , I've successfully conducted testing on this PR. I logged in as an Administrator and created two teams containing identical members. Subsequently, I disabled visibility for one team member. Upon logging in as the specified user, the expected outcome was observed: I couldn't view the team members.
<img width="1552" alt="Screenshot 2023-12-23 at 6 33 44 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/5dd30ac5-dc06-4c02-b9ce-5f5db1e4055d">
<img width="1532" alt="Screenshot 2023-12-23 at 6 32 56 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/afd02ce1-7160-4961-973f-1f21b290bec6">

2023-12-24 01:13 UTC, ljrirene requested changes
Hi Ramya, I tested your PR and I found something which is unexpected. 
1. The toggle switch is not preserved, like other people mentioned under this PR. It is hard to make sure if it is set successfully.
2. I logged in as a manager user, but when I checked the team members, I can still see the volunteer user and they are under team a and team b. Could you please explain more  about how to test this PR?
Thank you! Here is my test video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/8d096cff-f01f-4a56-a555-817c194824f9

2024-01-06 22:39 UTC, mianmiantea2019 commented
Hi Ramya, 

I tested your PR, here is what I've found.

1. Same as like other people mentioned under this PR. The toggle switch is not preserved.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/c306b4f8-ec39-4726-b291-f3688c7cf03e


2. I  can see the all team members on the dashboard.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/b59b3178-a8ed-4d52-8778-0ad13c8d92e6)

2024-01-15 20:31 UTC, X1aoZhang99 reviewed
Hi Ramya,

I've reviewed your PR and the functionalities work as intended. 

The toggle switch status is now preserved.  

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/0e783bd6-bdf7-4d6e-9f5f-6732bedb8ac0

2024-01-15 21:05 UTC, X1aoZhang99 approved these changes

2024-01-16 23:21 UTC, yuhuimin1996 commented
Hi Ramya,
I've tested this FE pr along with the BE pr#576. I could toggle the switcher of my test role under the admin account, while I didn't find where is the team member will show on the dashboard or in the profile. Please see more details in the video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108281570/9a3f7451-5eda-4cef-8780-d19dffb52b24

2024-01-19 06:08 UTC, pshereen reviewed
Tasks are not loading in the dashboard after I check into the "ramya-teams-limit-see-all" branch.
Everything is working fine in the development branch.

2024-01-19 16:07 UTC, rusalshrestha98 commented on src/components/UserProfile/UserProfileEdit/ToggleSwitch/ToggleSwitch.jsx
> +  const[visiblity,setVisiblity]=useState(choice);
Nitpick but the spacing on this line could probably be improved.
`const [visiblity, setVisiblity] = useState(choice);`

2024-01-19 16:14 UTC, rusalshrestha98 commented on src/components/Teams/TeamMembersPopup.jsx
> +  TabContent,
Don't see `TabContent` being used anywhere in this component, should it be removed?

2024-01-19 16:18 UTC, rusalshrestha98 commented on src/components/Teams/TeamMembersPopup.jsx
> +    setSortOrder(0);
`setSortOrder(0)` is being used before it is defined so I would recommend moving the `closePopup()` function below line 35 after the declared states. 

You typically want to declared all the variables and then the functions of the component.

2024-01-19 16:20 UTC, rusalshrestha98 commented on src/components/Teams/TeamMembersPopup.jsx
> +  }, [props.teamData]);
Nitpick: add a line break after this `useEffect()` to improve code readability and consistency of spacing.

2024-01-19 16:22 UTC, rusalshrestha98 requested changes
Please see comments above.

2024-01-20 08:23 UTC, Renanluizssx reviewed
Hi @ramyaram2092 , i don't know if i did something wrong, but when i add a team member on the team a and b, the team members didn't save, you can look my review below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/f4139ec8-d12a-428d-bf75-17d378d5e88f

2024-01-20 08:28 UTC, ramyaram2092 commented
Hi all thanks for your detailed feedback . I am looking into your feedback and  addressing them, marking the PR  do not review on the same note

2024-02-01 23:54 UTC, ramyaram2092 commented
Addressed all the issue in [1905] (https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1905). Closing the PR on the same note

2024-02-01 23:54 UTC, closed without merging