Wanting make 5 letter codes editable only by admin&owner
OneCommunityGlobal/HighestGoodNetworkApp pull request #1434
Opened 2023-10-20 20:48 UTC by wantingxu7

# Description
<img width="882" alt="截屏2023-10-20 下午1 03 00" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/bef20af5-5117-4735-9348-6189d81cffb6">

## Related PRS (if any):
…

## Main changes explained:
- Update WeeklySummariesReport.jsx file for Owner/Admin/whoever is given "edit team code" permission to edit 5-letter team code in 'Weekly Summaries Report page'
- Update UserProfile.jsx file for Owner/Admin/whoever is given "edit team code" permission to edit 5-letter team code in profile's teams tab
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin/owner user
        a. go to Reports -> Weekly Summaries Report
        b. verify that the 5-letter team code is editable
        c. go to User Profile -> Teams tab
        d. verify that the 5-letter team code is editable
4. log as any role EXCEPT admin/owner(like volunteer, manager, mentor, etc.)
        a. go to Reports -> Weekly Summaries Report
        b. verify that the 5-letter team code is NOT editable
        c. go to User Profile -> Teams tab
        d. verify that the 5-letter team code is NOT editable
5. log as owner
6. go to Other Likes -> Permission Management -> Manage User Permissions -> enter the previously logged user in step 4 -> scroll to the end and add "Edit Team 4-Digit Codes" permission to that user -> click "Submit"
7. login with the user given permission in step 6
8. verify that the user can edit team code in "Weekly Summaries Report" and Profile "Teams" tab

## Screenshots or videos of changes:
**editable team code example:**
![截屏2023-10-20 下午1 11 24](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/e594c116-42a4-4e8f-b9d1-7914b831fe6d)

![截屏2023-10-20 下午1 45 17](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/10a1ff4d-5f99-4853-b033-03b710626976)

**uneditable team code example:**
![截屏2023-10-20 下午1 17 32](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/eb455ec6-05f4-4859-a67f-c4d45c443c33)

![截屏2023-10-20 下午1 21 32](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/4a4e3de3-9958-41d2-82a9-ac63af0d85bc)

2023-10-20 21:24 UTC, Iris-Song commented
Hi, when I log in as an administrator and try to update 5-letter team code, an alert show that below: 
<img width="741" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/67fe2374-8292-4b39-9bbe-162a849d7823">
<img width="536" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/dc41d63e-89cf-4526-ba3f-04719422215c">

2023-10-21 01:55 UTC, StrawberryCalpico requested changes
Hi, I tested your PR. When I login as Admin, all team code boxes are blank. I can't see the code. When I login in as Volunteer, there's no team code box. I think there may be some issues with loading team code to the page?
Here is when I login as admin:
<img width="451" alt="Screenshot 2023-10-20 at 9 52 20 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/937b4bfe-a6d2-40c5-b24c-a91bf3d1a0e8">
here is the view as volunteer role who has no right to edit team code.
<img width="285" alt="Screenshot 2023-10-20 at 9 53 21 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/090e40b7-df77-48fd-9c70-7d734e913fb0">

2023-10-21 02:26 UTC, Cloid requested changes
Hi there.

I tested with the Admin and Volunteer edge cases provided.
Changing team code as Admin gives an error that @Iris-Song  talked about in their screenshot.

With the Volunteer profile, I tried accessing the Weekly Report summary via the dashboard dropdown and page URL. I just get redirected back to the main home screen which I assume is the intended behavior since you shouldn't have those permissions by default.

I gained access to an owner account and adjusted the permission sets to edit team code enabled the following options:
- “See Only Weekly Summary Reports Tab” 
- "Edit Team 4-Digit Codes" 

Logging back into the Volunteer page, I tried to change the team code and got the following error:
![Screenshot 2023-10-20 181255](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/14044314/2e4a3bd3-2499-4541-8264-447fc0dffe44)

Options I enabled for Volunteer profile:
![Screenshot 2023-10-20 181333](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/14044314/7a722f99-8dcb-4802-aa0a-c5d8cf5c867b)
![Screenshot 2023-10-20 181337](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/14044314/3ba4c954-ce46-47db-abb9-8afaf641988d)

2023-10-21 02:46 UTC, Shubhu0 requested changes
Hi @wantingxu7  I tested your PR and it is working but i noticed a few things

the codes are editable as admin and owner, but some teams do not have any codes whatsoever. Dont know if that was a loading issue or it is as it is. But everything else was working as intended.


![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/4e0e5d19-2866-4590-bd53-be17f85ff6a9)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/e7328839-a48e-4681-aedd-e48101a21478)

2023-10-21 03:35 UTC, mounica-dingari-by commented
Hi @wantingxu7 , I've tested your PR and for an Admin/Owner, I can't see any code for Weekly summaries Reports tab, but it's editable and same with the Profile->Teams tab. But when I login as volunteer, the Reports is not visible in the Nav bar and in the Teams tab, the code text box is not visible, which is fine. But , even when logged in as Owner/Admin, I'm unable to find any code for any of the users. Is there any particular branch that I can test from?

![Screenshot from 2023-10-20 20-28-42](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49270410/fa0797fa-2360-4435-9e66-ad01ce0af978)

![Screenshot from 2023-10-20 20-22-06](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49270410/f3050097-017f-4a4d-936f-16375bf083fd)
![Screenshot from 2023-10-20 20-24-00](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49270410/6097cf26-4116-4771-9831-eb5461df7fcb)
![Screenshot from 2023-10-20 20-28-37](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49270410/8f59d7da-22e0-446e-a236-7f6b72192aff)

2023-10-21 23:11 UTC, RheaWu1212 commented
Hi I tested your PR, log in as Owner --> able to edit codes, log in as volunteer --> popup message, not able to edit code.
<img width="385" alt="Screen Shot 2023-10-21 at 19 05 17" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/342889e7-f890-4ad6-8ac5-2fd30ca477dd">
<img width="754" alt="Screen Shot 2023-10-21 at 19 08 26" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/5fefa087-ad20-4391-bdf0-163d13c15980">

2023-10-21 23:47 UTC, wantingxu7 commented
figuring out the mentioned bugs, labeling it "do not review"

2023-10-29 01:07 UTC, cvtqx requested changes
Hi @wantingxu7!
When I log in as admin I can see and edit the codes however, the changes are not being saved.

In  reports -> weekly summaries :
![1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/e3464a67-0b97-40d7-9c2d-2462571d4594)

In profile -> teams:
![2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/04b29542-3dcc-40d8-9464-801f17f92713)

When I log in as other than admin/owner, the codes are not editable:

![Screen Shot 2023-10-28 at 9 00 05 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/02854035-3fd7-474c-b5d1-5473621bf1d5)

![Screen Shot 2023-10-28 at 9 00 28 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/525c2514-ae45-4231-b28c-68e8118cd782)

Also volunteers are not be able to see reports tab, so perhaps you need to remove volunteer role from your  'how to test' description so noone gets confused.

2023-10-29 03:13 UTC, John-Flavian commented on src/components/UserProfile/UserProfile.jsx
>      const compare =
Duplicated work.

2023-10-29 03:13 UTC, John-Flavian commented on src/components/UserProfile/UserProfile.jsx
>      const compare =
There is no need to have repeated work; you can refactor into a function or variable.

2023-10-29 06:15 UTC, savio-henrique requested changes
Hi @wantingxu7 , I've tested this PR, I couldn't edit the team codes as I was getting an 403 error, even in the profile page I couldn't find the code that I tried to edit into my team.

# Screenshots

403 error:
![ERROR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83360232/1d5d00f5-9e82-486a-a822-4d2ee8a3519d)

Team code not showing up, as it was not edited:
![no-team](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83360232/91bc5036-f6b5-4b6c-9d7c-c5d31713e15e)

2023-10-31 21:01 UTC, closed without merging