Zijie lint fix root files
OneCommunityGlobal/HighestGoodNetworkApp pull request #1460
Opened 2023-10-26 07:42 UTC by iTvX

# Description
lint fix for the files below:
![CleanShot 2023-10-26 at 00 39 09@2x](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/41e72af4-788a-46f3-bab5-edf4af3f451b)

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user
4. **Record a video to ensure all functions are operating normally.**

No need to test the eslint, I have tested, below is the screenshot.

![CleanShot 2023-10-26 at 00 41 58@2x](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/aa27b135-eef0-4f40-9415-d20345289167)

2023-10-26 22:18 UTC, emunkh404 approved these changes

2023-10-26 22:18 UTC, emunkh404 commented
I've tested your PR #1460, and I'm pleased to report that there are no issues; all functions are operating normally.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/401fa1c0-de80-4f99-8edb-1df554fdb943

2023-10-27 00:21 UTC, DavidC0126 approved these changes
Hi @iTvX I tested the PR and it works as intended. 

![npxES](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/1189e2ff-2adf-41ff-b4e8-ab0a888d65b8)

Uploading testFunc.mov…

2023-10-27 12:47 UTC, beblicarl commented
The app works perfectly. Great work

[screencast-localhost_3000-2023.10.27-12_45_58.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/2b574686-ad72-4905-b7ce-90bfd1041d5a)

2023-10-27 12:48 UTC, beblicarl submitted a review, later dismissed

2023-10-27 22:06 UTC, wantingxu7 submitted a review, later dismissed
Hi @iTvX , I logged as admin and tested the timer, weekly summary, weekly summaries report, user profile. All works well. Good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/29ebfd09-de20-4b48-b778-443658efdda4

2023-10-28 14:34 UTC, Iris-Song reviewed
I've tested your PR,  all functions are operating normally. But the loading time seems too long.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/20da8bc7-0337-4417-9511-7f0244ec660a

2023-10-28 22:00 UTC, Shubhu0 approved these changes
Hi @iTvX Reviewed and tested your repository! Everything is working as intended, Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/ca1d2827-5b69-4ba9-bb37-b6794448eb2a

2023-10-28 23:52 UTC, yaow62023 submitted a review, later dismissed
I have tested your PR, all the functions are work. Good Job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/ff63e48a-9282-4f47-8539-2eadaa602bd2

2023-10-29 01:35 UTC, yangfan2001 approved these changes
Hi, I have tested your PR and everything functions normally. Great Job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/75376251/e7b2b38b-c792-47cd-b188-1388eeb802fd

2023-10-29 03:35 UTC, zuhang2000 approved these changes
Hi, I've tested the functionality of the APP. Everything is working as expected. All the features are working without a problem. I tested weekly summary, weekly reports, teams, user management, user profile, etc.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/6c2bde5e-eb6f-4c3d-8349-e6d2494fb17a

2023-10-29 05:39 UTC, savio-henrique submitted a review, later dismissed
Hi @iTvX , I've tested this PR, everything working as intended, excepting some slow loading of the functions but this is not this PR's fault, as showed in the video below!

Great job! :+1: 

# Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83360232/c0d9b4b8-6cf8-4dba-b001-dee00bbbbad4

2023-10-31 04:17 UTC, EvianTan commented on src/setupTests.js
> +// eslint-disable-next-line import/no-extraneous-dependencies
Please fix lint errors in this fix with answers [here](https://stackoverflow.com/questions/44939304/eslint-should-be-listed-in-the-projects-dependencies-not-devdependencies)

2023-10-31 04:18 UTC, EvianTan requested changes
Need to actually fix the lint errors in `setupTests.js`.

2023-10-31 07:24 UTC, iTvX commented
> Need to actually fix the lint errors in `setupTests.js`.

Hi @EvianTan , this issue has been addressed.

2023-11-01 21:12 UTC, yi-lin-1234 reviewed
hello, I've tested your PR, all functions are operating normally. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/7721ad0d-4f68-4213-a851-ae721cc86c04

2023-11-02 04:38 UTC, EvianTan approved these changes

2023-11-02 04:38 UTC, merged