Anny fix reports view of team name
OneCommunityGlobal/HighestGoodNetworkApp pull request #1464
Opened 2023-10-27 03:21 UTC by astrjc0326

# Description
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98345990/0c94159f-fb66-40c8-b9d1-8338bad095b0)

## Main changes explained:
-Render only 5 teams detail once to speed up the loading time

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to Other Links → Reports → Reports → Teams
5. open any team on the right in a new tab, check if it render properly
6. select another team name from the list, test if it displays the new selected team

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98345990/c0e40d21-cdb7-4930-9c82-edf75c131f5c

## Note:
Although the loading time is faster than before, but it still take some time to load.

2023-10-27 04:01 UTC, malikjahanzaib approved these changes, later dismissed
Hi @astrjc0326, I have tested this PR locally and it seems to work as intended. Teams are getting displayed and rendered correctly in both the new tab as well as the original tab, although there is some delay but you have already acknowledged it. Great work!!!

Test rec:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/5f863a01-d071-47e8-ae23-217a30716d32

2023-10-27 04:05 UTC, ChirayuRai requested changes
Hey I checked out your PR and it seems to work on both admin and owner accounts. 

It looks like if you access DIFFERENT teams, it isn't too bad at loading things in. However, when you access the second team while a tab containing the first team's information is already open, fetching the data for the second team takes much longer. 

Also, it seems that opening two (or more) tabs for the SAME team exponentially increases load times for tabs 2 and onward. For instance, I opened [A test team mounica2] and in the first tab, it took anywhere from 1-8 seconds to load in. When I opened the second tab, it took too long to load (over 40 seconds, I gave up on timing it when it hit 40). I think that may need to be investigated, or at the very least there could be a loading spinner added?


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15188751/512c525b-728c-4e34-b10f-7b92a4ec06bd

2023-10-28 04:08 UTC, Iris-Song approved these changes, later dismissed
Hi, I have tested this PR locally and it seems to work as intended. Teams are getting displayed and rendered correctly in both the new tab as well as the original tab, although there is some delay but you have already acknowledged it. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/b9b7a46c-b061-450a-9cfe-53f08f92a35c

2023-10-28 21:41 UTC, AnishPandita commented
Hey, I tested the PR and the visual changes look good. The new tab for teams opens correctly and all the elements are rendered correctly.
<img width="1440" alt="Screenshot 2023-10-28 at 2 38 11 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/5252c629-dedc-4e28-a260-caf6a8af8451">
<img width="1440" alt="Screenshot 2023-10-28 at 2 38 21 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/27629e67-9de5-4b0d-a42a-b557df41ff44">

2023-10-28 21:57 UTC, kavya151 commented
Hello @astrjc0326, I've successfully tested the PR, and it's performing as expected. I opened a new team in a new tab and experimented with opening other teams, both in the same tab and new tabs. However, the previously accessed team consistently reopens. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/75b2df82-87b8-4bed-a962-c16268a8b3ee

2023-10-28 22:08 UTC, Bali2Mohit reviewed
Hi @astrjc0326, I tested the PR, and the fix is not working for me. I am still seeing the previous team in both scenarios.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94716419/8289a7d9-0389-48e4-ac4d-495485b64fc5

2023-10-28 23:26 UTC, vikrambadhan reviewed
I've successfully tested the PR, and it's performing as expected. I opened a new team in a new tab and experimented with opening other teams, both in the same tab and new tabs. However, the previously accessed team consistently reopens.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/e8217671-558e-491a-8de9-07ced9cff8b3

2023-10-29 02:37 UTC, Shubhu0 approved these changes, later dismissed
Hi @astrjc0326 Tested the Pr and it is working as intended

Uploading HGN APP — Mozilla Firefox 2023-10-21 00-31-12.mp4…

2023-10-29 02:42 UTC, palakgosalia commented
Hey, I reviewed your code and tested the changes. It works as intended. Thank you


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/ae50f8c8-f279-47fa-8828-35ca2cb3d781

2023-10-29 03:02 UTC, zuhang2000 reviewed
Hi, I've tested your PR reviews following your instructions. However, I do encounter several errors when I do the testing.
Firstly, the page crashes and pops up a lot of "Unexpected Error" messages. This happens when the page is enduring lots of delays when interacting with.
Secondly, the new team page that I opens in the new tab are not the team that I clicked. I in fact find it so strange that after clicking several teams, this undefined behaviors would happen.
Please find the details in the following recording.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/6b97d007-201a-4e77-baff-5511d71aaecf

2023-10-29 03:23 UTC, John-Flavian reviewed
Nice.

2023-10-29 03:23 UTC, John-Flavian commented on src/components/Reports/TeamReport/TeamReport.jsx
> +    return () => {
Nice job.

The unmount function was definitely neccesary.

2023-10-31 02:48 UTC, luisarevalo21 commented
Hello @astrjc0326 ,

I tested your PR and loads much faster. Great work! 
However, as others have noted, when clicking on another team, the previous team is loaded instead. 
When i open a new tab the older user is dispalyed as well. 

I also noticed a console.log which displays 200 elements, I don't think its related to your PR but logs shouldn't be rendered on production. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/f05ad9bc-6f99-4546-bbd8-85be8e8b036f

2023-11-02 18:19 UTC, Jiyuanxia commented
Hi @astrjc0326 , I have reviewed your pull request and tested it. It seems like there is some issues. When I choose a team and open it on the new tab, it does render me the right page. But after that when I left click a team, it renders me another team page I have ever accesed to.
![Screenshot 2023-11-02 141118](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/7f85e37f-8b8e-4561-afbc-f93ec6577f7c)
![Screenshot 2023-11-02 141122](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/136e45bc-ef85-4794-810c-da308dc93619)
![Screenshot 2023-11-02 141353](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/2facf4c0-74bf-48a4-8998-d57127b5488b)
![Screenshot 2023-11-02 141435](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/0439be97-f526-4621-acdc-305d6048d617)

2023-11-03 07:24 UTC, Chuehleo approved these changes, later dismissed
Everything works as expected, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/1ab9b100-ab31-458c-b21e-c1262237d142

2023-11-11 20:02 UTC, wanglu1207 commented
Hi, @astrjc0326. It works as intended! Good job!
![Uploading anny_fix_reports_view_of_team_name.png…]()

2023-12-15 06:43 UTC, Alforoan submitted a review, later dismissed
It seems to work as intended. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/0c356c6d-6629-4b03-9a52-4c9c70f7d122

2024-04-20 20:33 UTC, closed without merging