Obeda lint fix Common component
OneCommunityGlobal/HighestGoodNetworkApp pull request #1480
Opened 2023-11-02 19:49 UTC by dah00

# Description
Lint Fix for Common Component `src/components/common/**`

## Main changes explained:
- Executed the link checker
- Fixed changes manually apart from fix done by lint--fix
- Removed the component from .prettierignore and .eslintignore

## How to test:

1. check into current branch
2. Run `npm install` and `npx eslint src/components/common/*` to make sure there is no lint errors
3. Run `npm run test` to make sure that all tests pass
4. Run `npm run start:local`
5. log as any user
6. Verify that common components such as checkbox, form, dropdown, etc work properly 

## Screenshots or videos of changes:
![successful lint fix common component](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61763829/c0931cf9-94c0-46c0-9426-80eb232b7fc1)

2023-11-11 06:34 UTC, wanglu1207 commented
<img width="403" alt="Obeda_lint_fix_common_component" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67501735/7e64f577-0ed8-49d2-9159-ad5e4b47c50d">
Good job! It works for me!

2023-11-11 15:27 UTC, yi-lin-1234 approved these changes, later dismissed
Hello, I tested your PR and works as intended. Great work!

<img width="355" alt="Screenshot 2023-11-11 at 10 24 25 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/35b74a87-2cd7-4906-a982-31df807bc22a">

2023-11-11 16:37 UTC, Hemsharavanan reviewed
All tests passed. Great work!

![Obeda lint fix Common component #1480](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/28252459/14cf4e32-34f2-44db-b25a-af1f6755b592)

2023-12-06 05:12 UTC, EvianTan commented
Hey @dah00 , I was trying to review your branch but got this when building.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/5071040/61c93b52-4534-49f3-a753-b2fc7eae77e4)

Can you just revert all changes in /Report? We already get @iTvX to work on this component for a long time.

Once you fix that, please let me know, I'll do a further review.

2023-12-07 19:02 UTC, ZichanYang324 submitted a review, later dismissed
All the cases have passed, well done
![Screenshot 2023-12-07 at 14 00 36](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86720318/993a8d7e-19bc-4eae-9fed-39958f6d9d53)

2023-12-07 20:31 UTC, DragonSlayer2401 commented
I tested your PR the tests all ran correctly. However, the app itself is completely unresponsive. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/6ffb1777-b6bf-47bb-bb53-5649b366ded6

2023-12-08 00:09 UTC, sucheta90 requested changes
Please Note: running command `npx eslint src/components/common/*`, throws an error saying the path is invalid - `npx eslint src/components/common/Clipboard `, so I tried to  
`npx eslint src/components/common/Clipboard/*` - command and every other folders separately.
<img width="923" alt="PR1480_eslint_report" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/0921b608-4150-425e-8c53-98a2dd7e7a28">

Here's the TEST result
<img width="923" alt="PR1480_test_result" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/feb2e268-75f5-4220-b141-d10e63abaaf1">

On starting the local branch, I got an `export` error
![PR1480_export_error](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/e2821e14-2f4d-404c-9a88-efb12eea27aa)
Here's what fixes this error
<img width="1440" alt="PR1480_fix_exportError" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/9ad12b99-ea2a-4f48-8dc7-675112a5eb3d">

Here's a screen recording showing there may be some issues with the app itself.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/1977ac3e-6615-49d1-8fe9-ec2ba8fb8790

2023-12-09 23:21 UTC, pika-chu11 reviewed
Hi @dah00 , I have tested your PR.

- The `npx eslint src/components/common/*` seems not work as intended.  The massage shows: "No files matching the pattern "src/components/common/Clipboard" were found.
Please check for typing mistakes in the pattern." Here is the picture according to the erorr:
![PR 1480-1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/05ec4903-4590-420b-96c6-943e92c8a03b)

- I also did the `npm run test`, it seems the tests are all passed, but there are several warnings and error on the output stream. Details are in the video below.

- I have checked whether the app is running correctly after doing the test but it seems that the app is frozen and unresponsive. For details, please check the video:
I have recorded the whole process I got through

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/adaba1d6-fea1-439e-97e5-188e2c4d6453

2023-12-16 05:18 UTC, Alforoan reviewed
As can be seen by my images and my video, I do get an issue in my terminal when I run it and the app is not responsive at all.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/78ca4588-e314-47cb-a8b0-ade87061b97d)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/4079e4d3-cbf5-46af-b51b-cda82ea151b9)


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/514a45ab-035a-4130-b693-01f96c5ab349

2023-12-22 05:06 UTC, keyunhuangg commented
All the test has passed but when i run npm run start:local, there seems to be compile error
<img width="375" alt="Screenshot 2023-12-22 at 1 03 16 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/a068052f-a418-4978-8898-cb5f7656801d">
<img width="765" alt="Screenshot 2023-12-22 at 1 05 04 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/aec0eb9e-0bc0-452c-8d06-fd72dc9843e3">

2023-12-24 05:29 UTC, ljrirene reviewed
Hi Obeda, I got this error when I was trying to run "npx eslint src/components/common/*"
![1480FE](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/2179e0e9-e508-46e5-943d-520c30f20b04)

2023-12-30 05:42 UTC, mianmiantea2019 commented
When I ran npm run test, it seems the tests are all passed, but there are several concole.error
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/116e189d-73f5-4a28-8d60-1cb4b1767a28)

I ran the command 'npm run start:local' on my terminal, after waiting a bit for it to load, the app successfully launched.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/a5ea344f-2167-455d-8e27-3d89f83a793b)

2024-01-10 21:56 UTC, Haoxiang310 commented
After I ran npm run test, it seems like some of the tests cannot pass:
![PR3-#1480-fe](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/135764868/14ca5831-d68a-47e7-9045-0df6c61fb5a1)

2024-01-12 03:07 UTC, yuhuimin1996 commented
Hi @dah00,
I've tested this PR with admin user account. After running `npx eslint src/components/common/*`, something went wrong like this:
<img width="864" alt="Snipaste_2024-01-11_19-04-55" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108281570/de4e85c7-a0d1-4946-9435-61bbce76dd80">
And 1 test was failed:
<img width="1027" alt="Snipaste_2024-01-11_18-59-39" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108281570/516d2004-daa9-42aa-8c98-932270452048">
After I logged into the site as an admin user, it seems that all the basic functions like dropdown, checkbox are working well:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108281570/420bd8c2-8eea-41e1-854d-83d16d8f6043

2024-01-16 18:43 UTC, X1aoZhang99 requested changes
Hi, I have tested your PR. When I run `npx eslint src/components/common/*`, an error appears as shown in the following image. It says `No files matching the pattern "src/components/common/Clipboard" were found.`
![Screenshot 2024-01-16 at 13 32 19](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/b5d2d37a-e5f4-4333-b798-0602b5520101)


Additionally, when I run `npm run test`, one test fails.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/8baec94b-9c65-47c0-a9ad-c6d3ae8cc86e

2024-01-18 03:02 UTC, pshereen requested changes
I tested the PR.
1 test suit is failed.
And 5 Tests are failed.

<img width="831" alt="Screenshot 2024-01-17 190101" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/abd4a1e5-ae21-4282-b30f-c504b9fc3b75">

2024-01-19 18:51 UTC, rusalshrestha98 commented on src/components/Reports/PeopleReport/PeopleReport.jsx
> +import  {Checkbox} from '../../common/Checkbox';
I believe this change is not needed and should stay as: `import { Checkbox } from '../../common/Checkbox';`

I would try installing ESLint and Prettier extensions in your IDE if you are using VS Code.

2024-01-19 18:56 UTC, rusalshrestha98 commented on src/components/Reports/PeopleReport/components/PeopleTasksPieChart.jsx
> +import NewModal from '../../../common/NewModal';
Typically a space is kept for destructured module imports, so it should be fine to keep it the original way:
import { Checkbox } from '../../common/Checkbox';

I would try installing ESLint and Prettier extensions in your IDE if you are using VS Code.

2024-01-19 18:57 UTC, rusalshrestha98 commented on src/components/Reports/PeopleTableDetails.jsx
> -import { NewModal } from '../common/NewModal';
Same thing

2024-01-19 18:58 UTC, rusalshrestha98 commented on src/components/Reports/TasksTable/TasksTable.jsx
> +import {Checkbox} from 'components/common/Checkbox';
Same thing

2024-01-19 19:00 UTC, rusalshrestha98 commented on src/components/Reports/ProjectMemberTable/ProjectMemberTable.jsx
>  import React, { useEffect, useState } from 'react';
```suggestion
import { useEffect, useState } from 'react';
```
Doesn't seem like `React` is being used

2024-01-19 19:03 UTC, rusalshrestha98 requested changes
Please see comments above and feel free to let me know if you have any questions or concerns 👍

2024-01-20 06:05 UTC, Renanluizssx requested changes
Hi @dah00, i tested, and gives me some errors
![pullrequest](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/12a94835-957b-49a2-80d8-078c217f7e50)

i tested components in your application and it´s running very nice.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/cc9f66b2-2b36-40c4-a833-45b9534bb192

2024-01-20 23:58 UTC, galgalinidhi commented
Hi @dah00, npx eslint src/components/common/* was throwing an error so I ran this command for each component under the common folder. I did get lint errors for the following folders- Clipboard, Input, Modal, Paging, Piechart, Radio and SkeletonLoading. 

<img width="1436" alt="lint_error" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/68ad304d-1e2a-4560-baa3-82e12cc58852">


<img width="1436" alt="Screenshot 2024-01-20 at 3 08 46 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/22a3e373-642f-4483-818c-cb11e69c086c">




for npm run test- I had one test suite failing

<img width="1436" alt="run_tests" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/d52408d3-6380-4e81-a7ea-ad20795876e1">

I logged in as Volunteer as well as admin and the components seem to be working fine.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/e8be8ccc-7883-4c5a-9691-b380111865d6

2024-01-21 01:28 UTC, xmyoot commented
When running the "npm run test": i get the following, various tests appear to have been skipped
<img width="359" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15240538/70a71b95-7096-4840-8f92-909ad2bc0e30">
Additionally when running the tests on the common components my environment was unable to find the 'testing-library' plugin not exactly sure why this occured reference image below:
<img width="718" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15240538/53300426-1f41-4a1c-833d-46a7deec01d6">

2024-01-22 05:42 UTC, 666saofeng requested changes
Hi, when I run npm run test, 1 test fails. Details are as follows.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/106a58d6-5eb4-4ae5-bb96-caab216919fe

2024-01-24 08:03 UTC, Sophie-lei requested changes
Hey! I just tested this PR. After I do" npx eslint src/components/common/*".  it shows an error like this.
<img width="729" alt="Screenshot 2024-01-24 at 15 45 32" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/4edc85ad-19e2-4887-bf51-181218bb203d">
then I started the test. it didn't pass all the tests as shown below. and have error like this
<img width="861" alt="Screenshot 2024-01-24 at 15 47 37" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/c2005c20-6c94-41c0-bc32-90502ada4919">
then I logged in as an owner role. I found that after I clicked "the other link" in the dashboard. the dropdown box looks weird, especially for the "project". There should be "team" after "project "but also not shown. Please view the video for more details.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/3c28986e-b9a5-454a-86cc-1c73aeb804de

2024-01-25 00:12 UTC, KevHnh requested changes
Appears that some tests failed. While I was able to access the platform, certain menus seem different than what I normally see. Regardless still functional and didn't encounter any noticeable issues. Nonetheless, I think the few failed test cases need to be reviewed.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/7ff69906-1621-4b74-ae53-96d0b3288386)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/69b45900-1be4-4d3e-85eb-1de8e9a00d72)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/b64d5f68-7c93-4c21-8f00-39a741672796)

2024-01-28 02:11 UTC, yvonnep165 reviewed
Hi @dah00 ,

I ran the code following the instruction but get errors about failing to find the files as below. There're also several test cases failed:
<img width="463" alt="Screenshot 2024-01-27 at 6 01 54 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/07dcb712-07a4-4cf4-b414-82d46540df10">
<img width="700" alt="Screenshot 2024-01-27 at 6 00 46 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/169663f3-31a0-4c2f-810a-aeb112b044c4">

2024-01-30 16:10 UTC, SRamen1999 requested changes
After running npx eslint src/components/common/*, I got an error.

<img width="1019" alt="Screen Shot 2024-01-30 at 11 01 12 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/d3d2f6e0-baed-4b2d-b4fa-d4b08eb541ad">

When running npm run test. 1 test was failed:

<img width="1692" alt="Screen Shot 2024-01-30 at 11 00 39 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/293d5ca4-d798-4bc4-b560-d6ffbc8f012d">

When logging in as an admin, menus seem different than what I normally see.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/7dbf6650-acdf-475f-972d-7688076614e5

2024-02-08 07:35 UTC, SaiDeepak-NEU requested changes
I checked into the current branch and tested the steps and here are my results:
1. When i ran the npx eslint src/components/common/* command in the bash terminal it resulted in an error which said
![Screenshot (73)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114311909/ac9c0630-c951-4969-8468-19a1ce6a93b7)
But later when i ran the same command in the powershell terminal it executed without any errors:
![Screenshot (74)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114311909/c53adb1b-1523-4c9d-a2b4-8e3afebb62c1)
and finally when i ran npm run test, the results were as follows with some test cases failing.
![Screenshot (75)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114311909/fb5ccc59-f40a-499c-b666-82ed05a8fc4a)

2024-02-08 18:32 UTC, TapanPathak requested changes
Hi, I ran the code following the steps but got errors in npx eslint src/components/common/* :

<img width="569" alt="Screenshot 2024-02-08 at 10 22 50 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/23dcdefa-33e7-448d-bde8-9d77082cd6cb">

Also, 1 test fails - 

<img width="430" alt="Screenshot 2024-02-08 at 10 22 07 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/f77cdf45-c269-417d-ad51-639996bfe7ee">


Then I logged in as admin and seems all the functionalities works fine. Just one small difference - When clicking "Other Links" we need to scroll down to see all the items in dropdown menu which is not the case in original version. 

<img width="1448" alt="Screenshot 2024-02-08 at 10 16 23 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/3930d78d-29cc-4a57-be5a-6525a2f9b2ae">


Original - 
<img width="350" alt="Screenshot 2024-02-08 at 10 30 41 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/e612384d-3c74-471b-a335-1db9ced6d4df">

2024-02-14 21:21 UTC, XiaohanMeng reviewed
Hi, I've tested this PR and encountered the same error as reported by many other reviewers. 
![PR1480_bug](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/44bb86df-686d-4564-a3e4-6d3fbb96a9b4)

When I attempted to start the test, numerous errors occurred, which are detailed in the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/6da0986c-0afb-4883-babe-9af49ed88658

2024-02-18 06:39 UTC, nnamdixobi commented
Hey, I tested your code like you stated in the instructions and ran the tests after checking into the current branch and I happened to get some errors that I will show here 
<img width="957" alt="Screenshot 2024-02-18 003738" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/80783443/e6c82e2f-720a-47d5-84c7-49d265aca2c2">
<img width="957" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/80783443/7b66e894-4469-400e-ad5f-8bdc1efe7389">

2024-02-21 19:26 UTC, psharma1984 requested changes
Hi. I checked with the listed steps. npx eslint src/components/common/* gave errors. i was able to run it for every directory inside common
![Screenshot from 2024-02-21 11-02-06](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/ac57573e-a097-4f6e-a13c-2459fae9fdf6)
The test case summary is as under  
![Screenshot from 2024-02-21 11-11-23](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/6735f474-7819-4281-a8dd-b559e342b527)
The app seems to be frozen for me for some functions. Drop downs and forms are working though
![Screenshot from 2024-02-21 11-24-30](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/ca812401-1e3d-4123-8e6b-6c3bfc74ca47)

2024-02-21 19:27 UTC, psharma1984 reviewed
Hi. I checked with the listed steps. npx eslint src/components/common/* gave errors. i was able to run it for every directory inside common
![Screenshot from 2024-02-21 11-02-06](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/ac57573e-a097-4f6e-a13c-2459fae9fdf6)
The test case summary is as under  
![Screenshot from 2024-02-21 11-11-23](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/6735f474-7819-4281-a8dd-b559e342b527)
The app seems to be frozen for me for some functions. Drop downs and forms are working though
![Screenshot from 2024-02-21 11-24-30](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/ca812401-1e3d-4123-8e6b-6c3bfc74ca47)

2024-02-23 07:37 UTC, chrischenlixing requested changes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114450390/c02c9040-bf75-428f-8e10-51c2fa326d6a)
Hello, nice job and I think the format looks a lot nicer. I wasn't able to run the bypass linting line, without that, most tests passed, but still there is an error.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114450390/7342c2dd-785d-49f7-940d-7a9f8755d2ab)

2024-02-24 09:24 UTC, skaush21 requested changes
when I do npx eslint src/components/common/* I get this error:
<img width="541" alt="Screen Shot 2024-02-24 at 12 26 48 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/3fc28e69-19d7-47ce-99b1-ba332a3743c5">

when I run the npm run test I didnt pass all the tests:
<img width="350" alt="Screen Shot 2024-02-24 at 12 28 18 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/9e15b45b-01b2-4ada-aef6-739d527a1b3d">

I checked a few features locally and they all seemed to work

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/8272982d-77c1-4857-9420-1d46e4d09ef9

2024-02-26 22:18 UTC, MALAV1308 requested changes
Hello , I have tested your PR. It has some errors in </stub> component. I have attached the screenshots. Please look at it and solve it. Apart from this, components are working great.
![#1480-1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61341363/7de2ec31-5ef8-4fd4-86e0-8df810cb5881)
![#1480-2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61341363/f40e17c0-91ec-438e-930b-6e2e8511f4ee)
![#1480-3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61341363/aa1fd0b2-2794-44a5-b2a8-ed7263860ef4)

2024-03-02 08:31 UTC, ClemarNunes requested changes
I tested your PR and got some errors.
![error123](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/1da3beb4-6a2d-4e65-a908-6e8aaa03d729)

the components are performing excellently.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/bd426de1-9b48-4a18-bfb7-b0ac90cd3d34

2024-03-07 14:37 UTC, Gugor99 requested changes
### Report 
Hi Obeda, 
I tested your functionality and got a couple errors in the terminal. Except for that, I tried to log in as owner and I encountered no issues. All pages and buttons were working as expected. Please see screenshot for error's reference
### Screenshot
![Cattura1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/9b9b69f6-0b1f-47b8-8207-599b83c675c2)

2024-03-08 12:14 UTC, Gugor99 approved these changes, later dismissed

2024-03-23 15:21 UTC, Coops023 reviewed
Hi Obeda, i have tested this PR and when running 'npm run test' i receive some errors, i will attach a screen shot, the components however are working as intended. 

<img width="517" alt="Screenshot 2024-03-23 at 16 16 31" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81972263/cf68b589-9946-436c-ae7f-9fe355e1e2c2">

2024-03-24 20:49 UTC, kylepham requested changes
Good work @dah00. All tests and functionalities of common components work well, except for the Stub component. Looks like there is a problem with import statement in Stub's test suit. Fixing the import statement of Stub component should fix the issue and make all tests passed.
<img width="666" alt="Screenshot 2024-03-24 at 3 49 07 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/a7d85e0a-2fbd-486d-8059-4f3f7c619e28">

2024-03-27 20:12 UTC, hetvi11110 reviewed
I have tested this PR as explained here. I found some errors while running the command npm run test. Here is the screenshot I attached for reference.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/704bc43a-1781-4355-a75c-3fa08e95ec77)
Here is the reference video for verified common components.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/d7db7e4d-9cbb-466e-9d5e-c5415a142e36

2024-03-29 19:13 UTC, Jaiwin-4998 approved these changes
HI, I just tested you PR and it is working fine with all the functionalities.
<img width="595" alt="Screenshot 2024-03-29 at 10 48 47 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62836815/27bbe502-10c3-4458-954d-85f00f84054a">

2024-03-30 11:56 UTC, Sarthak32 reviewed
Hey I tested your PR this what I am getting : 
![Screenshot 2024-03-30 172501](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/c8f02641-574b-41f7-9feb-d5e3879d55b3)

2025-03-02 00:41 UTC, closed without merging