Roberto- Fixes Ukraine Location Problem
OneCommunityGlobal/HighestGoodNetworkApp pull request #1486
Opened 2023-11-04 01:42 UTC by robertoooc

# Description
<img width="819" alt="Screenshot 2023-11-03 at 6 27 36 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/8ea5e45a-251b-459a-92c4-2f3e1593088b">
Ukraine was previously not an optional location to choose when editing a user's profile information. Selecting Ukraine would crash the page.

## Related PRS (if any):
Test with backend development

## Main changes explained:
- Adds if statement if Ukraine is selected, the api timezone gives you `Europe/Kyiv` which is the correct timezone name but built in javascript function spells it wrong. They spell it `Europe/Kiev`. So if statement just fixes the typo which prevents future functions from not crashing.

## Sign up for API KEY
1. Go to `https://opencagedata.com/users/sign_up` and sign up for an account its free
2. Once in dashboard press on geocoding API or `https://opencagedata.com/dashboard#geocoding`
3. Scroll down to api keys and press create another api key. You will see a error warning saying ‘Error adding API key’ above but it’s wrong, return to geocoding API.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. In `src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx` go to line 284. Comment it out and replace it with `const key = ‘your api key’ `
4. Log into any account that has permission to edit user's account information. Suggested: Admin
5. Select any User's profile in user management and edit their location with Ukraine or any city in Ukraine, then press the get time zone button
6. Confirm that the page doesn't crash and that the timezone does change to `Europe/Kiev`

## Screenshots or videos of changes:
Before: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/23b8adc0-c905-4f6d-b0df-5ace3c742e34

After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/a49669b7-affc-4d3d-9d0a-600d6f4d80e9

2023-11-04 03:37 UTC, malikjahanzaib requested changes
Hi @robertoooc, Upon reviewing the PR, it operates as expected for the most part. However, I encountered a bug when attempting to save updates to the time zone. For further details, please refer to the recording provided below. Aside from that, the functionality is great. Great effort!

Test rec:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/8b45299e-4664-45e8-89cb-ac03f8b0ccd1

2023-11-04 06:03 UTC, robertoooc commented
> Hi @robertoooc, Upon reviewing the PR, it operates as expected for the most part. However, I encountered a bug when attempting to save updates to the time zone. For further details, please refer to the recording provided below. Aside from that, the functionality is great. Great effort!
> 
> Test rec:
> 
>  03.11.2023_20.33.06_REC.mp4

Hi @malikjahanzaib, I can't seem to replicate this issue. Could you open the response tab and see if there's a more clear error message there, it looks like it could be related to CORS but I am not sure.

2023-11-04 16:03 UTC, Bali2Mohit approved these changes
Hi @robertoooc , Tested your PR. Works perfectly. Well done!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94716419/5bd2cf2e-2079-48fd-9530-fc3634afdf3a

2023-11-04 21:24 UTC, kavya151 approved these changes
Hi @robertoooc , I have tested this PR locally and it works as expected. Good Job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/e9200ee7-5818-48ef-89d2-967fbb14b5a5

2023-11-05 02:49 UTC, pika-chu11 approved these changes
Hi @robertoooc , you did a good job on fixing this. It actaully work on my end!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/e9a9685b-3f64-41a0-b0ce-eb9662d1b27e

2023-11-08 20:33 UTC, wantingxu7 commented
Hi @robertoooc , I tested the PR and the "Get Time Zone" function works as expected. But the time zone remains unchanged after clicking "Save Changes" and refreshing the page. I've included my testing details below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/2979c657-3bed-4b05-a9e6-102b5ecc26da

2023-11-11 02:51 UTC, Iris-Song approved these changes
Hi @robertoooc , I have tested this PR locally and it works as expected. time zone kiev can be changed and saved. Good Job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/434fc485-95ed-4acf-9182-5f3730bfb97a

2023-11-15 23:04 UTC, malikjahanzaib commented
> 1. https://opencagedata.com/users/sign_up

Hi @robertoooc, I think there was some issue with my local environment setup so I did a clean install and re-tested this PR and it works perfectly fine as intended and I was able to save the changes as well. Approving now. Sorry about the delay. Here's my test screenshot:

<img width="960" alt="Screenshot 2023-11-15 150023" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/4f9ef0e5-f09e-47a4-beb9-681dea6a78a3">

2023-11-15 23:04 UTC, malikjahanzaib approved these changes

2023-11-16 00:19 UTC, one-community commented
Thank you all, merging!

2023-11-16 00:19 UTC, merged