add additional condition to fix bug
OneCommunityGlobal/HighestGoodNetworkApp pull request #1526
Opened 2023-11-12 03:44 UTC by StrawberryCalpico

# Description
<img width="735" alt="Screen Shot 2023-11-11 at 10 34 55 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/cc81353c-e6e6-4adb-9bd6-88084d9815e9">

## Related PRS (if any):
N/A

## Main changes explained:
Add additional condition to ignore tasks that is not assigned or not active.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log in as admin or owner
4. assign task to a volunteer
5. log out and log in as volunteer
6. make sure the default tab is tasks for volunteer right now
7. log out and log in as admin or owner again
8. set the task to be unassigned
9. log out and log in as volunteer
10. make sure the default tab is Current Week Timelog

## Screenshots or videos of changes:
Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/8d0b3fc6-b5c8-423e-8972-47264b675832

2023-12-01 04:29 UTC, Alforoan requested changes
Hi, it doesn't seem like it's working as intended. As per the video, once I assign a task, the volunteer's tab should be on tasks, but it is not.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/543b822c-1ac1-452e-8ee2-f8042d316759

2023-12-01 20:13 UTC, sucheta90 reviewed
Tested in local branch as volunteer, however got an error in the console due to which the "Task" - board did not show. Please refer to the video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/b9ce9ab9-cd9b-4c5c-95d2-da2f096dee9d

2023-12-01 23:32 UTC, sucheta90 commented
@StrawberryCalpico My apologies, I figured I had a problem in my local environment. I would will make sure to review this PR one more time and make sure everything works.

2023-12-02 00:50 UTC, sucheta90 requested changes
@StrawberryCalpico Here's my finding upon the 2nd review. I first logged in as Admin and was able to assign task to a volunteer. Then I logged in as a Volunteer to see if the default tag was "TASK". Looked like it still was "Current Week". Also, for some reason the assigned task list was not visible in the "Task" tab.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/f99f8ef9-affa-4180-9703-24ddf9223e78

2023-12-02 06:02 UTC, this-journey commented
I was able to assign task as admin, then logged back in as volunteer and although the default tab was task, the task itself didn't display.  

![Screenshot 2023-12-01 at 9 56 32 PM (2)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/c6544844-ada6-4504-9475-a2de69fae6f6)


I logged in as admin, unassigned the task, re-logged in as volunteer and the default tab correctly moved to current week time log.

![Screenshot 2023-12-01 at 9 58 18 PM (2)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/490a1487-54f7-41a6-b803-a15153021d64)

2023-12-03 00:19 UTC, ptrpengdev commented
Hi @StrawberryCalpico , I tested this PR and failed to verify the feature - make sure the default tab is 'Tasks' for the volunteer after assigning a task to the account. The current default tab for the volunteer role is still 'Current Week Timelog.' I have included the account for your verification in the Dev environment.

Account: testtesterpp@gmail.com
Pass: Hgn@dev2023
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/3a0627fd-f0cb-42fc-a454-9f2c0d60728b)

Step to reproduce:
- Create task with Admin role
![1701562417639](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/dbdc0bcc-ea7f-4791-8e7c-957156828ab6)
- Verify task creation and assignment.
![1701562473752](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/16c39086-a067-4e72-b82a-c394e9be633b)
- Login in as Volunteer role
![1701562515426](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/208c3c06-07f3-44bd-bd7a-46c5c6409671)

2023-12-07 17:26 UTC, DragonSlayer2401 commented
I have tested your PR, and it does not seem to be working correctly. After assigning a task to a volunteer user, it still defaults to the timelog. There also appears to be a console error which may be causing the task not to appear under the Task tab. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/ebb15d98-8e18-4bdf-b416-2b2a356f4946

2023-12-22 04:42 UTC, keyunhuangg requested changes
1) started by assigning the task to volunteer
<img width="497" alt="Screenshot 2023-12-22 at 12 36 52 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/3988beb2-fb40-49d1-82f6-73dcbb042764">
2) logged in and see the default tab is 'Current Week Timelog' instead of 'task.' But the task is correctly display under the 'task' tab
<img width="798" alt="Screenshot 2023-12-22 at 12 37 28 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/c79a86ff-dbf8-43d8-884f-7a4c248a94d6">
<img width="755" alt="Screenshot 2023-12-22 at 12 37 34 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/36c470c0-31c2-41da-aebb-82739edf7a9e">
3) Logged back as owner and and un-assign the task
<img width="488" alt="Screenshot 2023-12-22 at 12 38 35 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/70c88976-acac-4b32-8714-2a45bc21a863">
4) The default task is 'Current Week Timelog' but the task does not appear in the 'task' tab
<img width="776" alt="Screenshot 2023-12-22 at 12 38 58 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/99ec4010-18ac-49f4-9062-3ff33e67009a">

2025-04-17 22:49 UTC, closed without merging