Haoji fetch images from team page and multiple profile images selection for individuals
OneCommunityGlobal/HighestGoodNetworkApp pull request #1531
Opened 2023-11-12 07:31 UTC by Haoj1

# Description
<img width="664" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/84737f22-f684-46f7-abbd-0661ff8352b4">

## Related PRS (if any):
This frontend PR is related to the [#608](https://github.com/OneCommunityGlobal/HGNRest/pull/608) backend PR.
…

## Main changes explained:
- Update src/actions/userManagement.js and add a new column for owners to manage the profile pictures
- Create src/actions/userManagement.js for admin to select proper profile picture that matches the user
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. See backend how to setup [#608](https://github.com/OneCommunityGlobal/HGNRest/pull/608), change the cronjob period 
4. log in as owner user
5. go to other link→ user management → Profile Image →…
6. Create a new user according to the name on [https://www.onecommunityglobal.org/team/](https://www.onecommunityglobal.org/team/). If you cannot see your name on the site, feel free to create a new user with the following cases. Then wait for the cronjob execution 
7. Case 1: If the user already has a profile picture or the user is inactive, the cronjob will skip and not overwrite the original picture. (You can paste an image URL into the "Profile Image" and click "add". Wait and see if cronjob will overwrite the picture)
8. Case 2: If the user name is unique in the team page and there is no profile picture, the cronjob automatically assigns one
9. Case 3: If the user name matches multiple images on the sites. For example, there is a person named Yifan Wang and another named Yi Wang, cronjob may not be able to tell the belongings of pictures. Owners in that case, could select the proper one from all possible pictures. 
10. And this user who matches multiple images on the sites would receive an email for notification about the case, and could select a proper one in their own profile page.

## Screenshots or videos of changes:

Case1 & 2: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/ba908164-f8a0-43e2-87eb-7d2b0d6f56d0

Case 3:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/61aae8c2-c16f-4357-a435-b0d3bda612a4

Email sender:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/9a679a89-9f94-47d9-8917-9ed9bfdebdd9

## Note:
URL is currently valid and available for the profile picture
Setup email sender in backend before testing

2024-01-24 10:02 UTC, Sophie-lei requested changes
Hey! I just tested this PR and I meet problems in cases 1 &2.
I found that after I created a new user who has a photo on the team website. The backend said that the profile is updated successfully. but I can not see any change in the photo. Please view the video for more details.
<img width="691" alt="Screenshot 2024-01-24 at 16 50 44" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/6037c55f-3c4e-41f7-9f80-66841d3dfea8">

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/9b4c75fb-a798-4296-8cc1-3d784a9763ee

I also test for case 3. I chose the name that has the same last name as the team number. but the select photo is not working. Please view the video. 
<img width="499" alt="Screenshot 2024-01-24 at 17 02 34" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/13c939b3-512b-4718-9c52-22cc96f0909d">

<img width="1416" alt="Screenshot 2024-01-24 at 17 03 07" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/6182b085-8da4-4246-a968-38fcc4ee6eac">

2024-02-02 18:47 UTC, Pandani07 requested changes
Hello, I tested this PR and followed your steps, when I create a new user with the same name as one that exists on the website, the backend console says 'update picture' and nothing happens. The photo is not updated, please check the video. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/88ebf005-cb04-4b83-ac1e-09f2577bf861

2024-02-15 21:07 UTC, XiaohanMeng requested changes
Hi, I tested this PR and encountered a problem at the very beginning. I followed your steps to change the first name in userHelper.js, but the code is underlined in red, possibly indicating a problem with JSON parsing. After creating the new user, there was no response on my backend terminal and no photo showing in the new user profile. For detailed information, please see my video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/82c90463-27f8-46c0-be22-55f227b65067

2024-02-18 05:27 UTC, nnamdixobi commented
I reviewed it and found out that it does not reflect photo updates for new users on the website and does not update the photo for duplicate user names. I also got the same JSON parsing error when modifying the first name in userHelper.js.

2024-02-19 22:23 UTC, XiaohanMeng commented
Hi Haoji,
I retested this PR following your guidance on Slack. Now, the "update picture" function works in my backend terminal, but the picture does not update in the profile on the frontend page. Please see the video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/0267dbb0-4916-4c05-9cd7-65a7c93ef702

2024-03-01 19:26 UTC, DiegoSalas27 commented
I have made an inline comment in the userHelper.js file suggesting a code change to prevent non active users profile images being updated. Overall, great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26840798/09c67d09-d4d0-4a46-8cc7-f1d59cd11d89

2024-03-07 23:45 UTC, XiaohanMeng requested changes
Hi, I retested this PR and noticed some improvements from before. In Case 1, when I created a new user with a unique name, the picture was displayed correctly (Video 1). Then, I tried to create a user with a duplicate name, and while the picture was still displayed, there was an error shown in the backend terminal (Video 2). In Case 3, I followed your guidance in the video with name: "Haoji Wang", but there was no option for picture selection on my screen (Video 3). 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/d6434f1b-212d-4615-b788-06222b2160fb


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/4818326c-a718-4903-9639-e1786666ddc0



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/a478ba2c-061c-4ec1-ac07-4dabacd6c7c2

2024-03-26 20:25 UTC, kylepham requested changes
I tested case 2 where I created a new user with a unique first and last name ("Marcus Nguyen") that I found on the team page, but it fetched multiple images of other users with the same last name "Nguyen". Please see the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/c535f480-36e9-438e-a7d5-a1ad13b81f7b

2024-03-27 00:40 UTC, hetvi11110 reviewed
I have reviewed this PR, as mentioned, and encountered a few bugs while testing. They are as follows:

1. The user 'Hetvi Owner' has the last name 'Owner,' yet it fetched and assigned the image of Aly Shannon.
2. I created a user named 'Falgun Patel' with the last name 'Patel.' Although there are four team members listed on the team page, only three user images were fetched, and Falgun's image was missing. However, when I tested the same case with another user with the last name 'Feng,' it worked perfectly.
3. After assigning an image to the user, I still found the option to add an image to the same user by clicking the 'add' button.

I was also unsure how to test users with more than two words in their names. Additionally, in case three, I integrated the SMTP variables but still didn't receive any mail. I have attached a reference video here for the review.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/17b8c911-3c5a-475b-a53d-6ab223ebc75f


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/fd9c4be4-10a8-4b53-bcb7-c1588e5ee151


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/5b7bb877-7249-4849-b2ea-6937274484b6

2024-04-17 20:53 UTC, kylepham requested changes
Hi @Haoj1, I retested your PR in all 3 cases.
- Case 1: inactive user doesn't get updated. Worked as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/fba04d21-bfa0-4162-8e73-bc13cfca7d3a

- Case 2: active and unique user gets updated. I'm not sure if there was an issue with caching, but I used the same user as case 1, just switch the status from inactive to active, and it failed to update the profile picture.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/d45a5e3a-a809-4bd6-a909-079d11fbaaeb

However, after terminating the backend and spinning up again, it successfully updated the picture.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/9374b909-cdc0-47ba-a510-ef2130219094

- Case 3: multiple active users with both first and last name, or just last name. I tested with the name "Haoji Lu" since I found multiple people with "Lu" in their names, but it only returned a single picture of yours. If I misunderstood, please let me know.

 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/09f22dd9-c754-4a7e-9d40-9e458f4827bf

2024-04-17 22:15 UTC, hetvi11110 approved these changes

2024-04-26 14:55 UTC, XiaohanMeng reviewed
Hi Haoji, the feature about adding pic now is great(Video1). But in case 3, I notice that the banner still appear when I refresh the screen after I close them(Video2).

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/4748ac37-6120-40bb-9612-6eb69f17cc09


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/628f6f5d-e1dc-483f-8acf-f0bf96d18a10

2024-05-05 19:20 UTC, kylepham approved these changes

2024-06-15 13:43 UTC, TXMO-dev approved these changes
fetch images from team page and multiple profile images selection for individuals, works as expected with no issues. Approved!

2025-01-25 00:11 UTC, closed without merging