TuanDinh_UserLoginPrevileges_UnitTest
OneCommunityGlobal/HighestGoodNetworkApp pull request #1567
Opened 2023-11-19 02:41 UTC by TuanDinh140194

# Description
Create the unit test for UserLoginPrivileges component

## Main changes explained:
- Add new file UserLoginPrevileges.test.js
- In UserLoginPrevileges.test.js, I added 7 test case to test the UserLoginPrevileges.jsx component.
- First, test if UserLoginPrivileges component renders without crashing, test if the component renders team name and team report logs corectly, renders selected teams and corresponding charts, test if the coponent displays correct data in team report logs, check if correct data in the second team report logs. Next I test if the component have certain styles applied and styles are applied correctly for pie charts with data.
…

## How to test:
1. check into current branch
2. do `npm install`
3. do `npm test UserLoginPrevileges.test.js ` to run the test
4. Verify that all 7 tests have passed

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/4fd2bb17-545e-4877-ae73-e54d8975c0ca

## Note:
Include the information the reviewers need to know.

2023-11-19 18:23 UTC, sahilpatel18 approved these changes
Hi @TuanDinh140194, all test cases have passed successfully. However, I noticed a small typo in the test file name mentioned in the description. It's currently 'UserLoginPrevileges.test.js', but it should be 'UserLoginPrivileges.test.js', as 'Privileges' is misspelled. Great work nonetheless!

![Screenshot 2023-11-19 at 1 20 17 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/24741818/86ed50d0-a136-4c67-847b-bd1a2049d620)

2023-11-24 02:33 UTC, vikrambadhan requested changes
Hi, I tested your PR and the test cases did not pass! Please check the attached screenshot.

![Week 13 - PR4](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/2a5acc26-8994-4165-8434-1203091fc9ec)

2023-11-24 06:59 UTC, TuanDinh140194 commented
> Hi @TuanDinh140194, all test cases have passed successfully. However, I noticed a small typo in the test file name mentioned in the description. It's currently 'UserLoginPrevileges.test.js', but it should be 'UserLoginPrivileges.test.js', as 'Privileges' is misspelled. Great work nonetheless!
> 
> ![Screenshot 2023-11-19 at 1 20 17 PM](https://user-images.githubusercontent.com/24741818/284081464-86ed50d0-a136-4c67-847b-bd1a2049d620.png)



> I keep getting this error, not sure why
> 
> ![image](https://user-images.githubusercontent.com/68056104/284575069-76abdebb-2625-4a54-8af1-4c1987d2ab36.png)

2023-11-24 07:01 UTC, TuanDinh140194 commented
> Hi @TuanDinh140194, all test cases have passed successfully. However, I noticed a small typo in the test file name mentioned in the description. It's currently 'UserLoginPrevileges.test.js', but it should be 'UserLoginPrivileges.test.js', as 'Privileges' is misspelled. Great work nonetheless!
> 
> ![Screenshot 2023-11-19 at 1 20 17 PM](https://user-images.githubusercontent.com/24741818/284081464-86ed50d0-a136-4c67-847b-bd1a2049d620.png)

Hi! Thank you for comment. I have fixed the misspelled component. It should be npm test UserLoginPrivileges.test.js

2023-11-24 07:03 UTC, TuanDinh140194 commented
> Hi, I tested your PR and the test cases did not pass! Please check the attached screenshot.
> 
> ![Week 13 - PR4](https://user-images.githubusercontent.com/85417946/285342084-2a5acc26-8994-4165-8434-1203091fc9ec.png)

Hi! It should be npm test UserLoginPrivileges.test.js

> I keep getting this error, not sure why
> 
> ![image](https://user-images.githubusercontent.com/68056104/284575069-76abdebb-2625-4a54-8af1-4c1987d2ab36.png)

Hi! It should be npm test UserLoginPrivileges.test.js

2023-11-28 00:49 UTC, DavidC0126 approved these changes
Hi @TuanDinh140194 I tested the PR and it works as intended. Good job!

![Screenshot 2023-11-27 at 4 48 47 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/d2c10c31-ff03-4e5f-9b45-604aeabe0831)

2023-12-04 08:00 UTC, Alforoan approved these changes
They all passed. Nice!

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/47b005e3-d233-446d-ad09-b07a4f71fb7e)

2024-01-10 20:31 UTC, ChengyanOo approved these changes
Hi @TuanDinh140194 

All tests were successful!

<img width="752" alt="Screenshot 2024-01-10 at 15 29 38" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69735000/f3d066e1-06ca-4af1-8698-f478e556d8e7">

2024-02-04 02:46 UTC, 666saofeng reviewed
All tests passed, but there seems to be a console error. Please refer to the screenshot for details.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/c945156b-0a98-4b74-b9cb-94a26de0aca4)

2024-02-04 02:47 UTC, 666saofeng commented
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/b4013f8a-c518-467f-9a51-f1dd61572a75)

2024-02-12 21:53 UTC, XiaohanMeng reviewed
All cases passed, but there's a warning as shown below.

![PR1567 UnitTest result 1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/8c9964f8-6c76-409c-805f-ab139605c61f)
![PR1567 UnitTest result 2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/8c1644a6-86cf-48f7-b0a7-b40fdefa5cd5)

2024-02-24 09:46 UTC, skaush21 reviewed
ran the specified test, all 7 tests pass.
However there is a console error, not sure if that is related to your code
<img width="455" alt="Screen Shot 2024-02-24 at 1 42 33 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/02d7cef4-c9d4-46f1-b7b6-a4a1f809e9f7">
<img width="524" alt="Screen Shot 2024-02-24 at 1 43 43 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/ee8d85da-11a4-4dc0-a190-c8eddac4e87f">

2024-04-26 06:04 UTC, yvonnep165 reviewed
Hi @TuanDinh140194 I checked the test cases and ran the tests. All tests passed but there's an error as what previous comment has mentioned. Please refer to the screenshot below:
<img width="748" alt="Screenshot 2024-04-25 at 11 02 05 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/ef3e0343-fd33-43cb-a511-719bd2b9e49d">

<img width="616" alt="Screenshot 2024-04-25 at 11 02 11 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/18f33396-b13c-494d-9100-5103e9d2ea0b">

2024-05-17 10:47 UTC, KaushikMreddy commented
Hi, 
All the test cases passed with 1 warning. Good work!
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/abb48206-1cc8-4ab6-93d4-d017cf39da77)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/5df19c7b-0239-4947-9aa8-676928a60065)

2024-06-02 01:29 UTC, Sandhya1236 approved these changes
I have successfully tested the unit tests for the UserLoginPrivileges component. The main changes involved adding a new file, UserLoginPrivileges.test.js, which includes 7 test cases. These tests ensure that the UserLoginPrivileges component renders without crashing, correctly renders team names and team report logs, displays selected teams and corresponding charts, and verifies that the correct data is displayed in the team report logs. Additionally, the tests check that certain styles are applied correctly, including styles for pie charts with data. After checking into the current branch, running npm install, and executing npm test UserLoginPrivileges.test.js, I verified that all 7 tests passed successfully, confirming the proper functionality and styling of the UserLoginPrivileges component.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/ae8118b7-ca06-4747-b29e-4ada131c121b)

2024-08-09 23:47 UTC, Gmon-k commented
Test cases has passed and below is the screenshot for it

<img width="1024" alt="4" src="https://github.com/user-attachments/assets/1bbf4fa1-2844-4501-a953-26708d1f2486">

2024-09-13 00:41 UTC, ishangoel17 reviewed
All test cases are passing. Below is the screenshot for reference:
![Capture1567](https://github.com/user-attachments/assets/fa8c56ec-b0d2-4410-a8a4-b2ba006840fc)

2024-10-24 19:32 UTC, slidracoon72 approved these changes
#1567 
@TuanDinh140194 
I have tested this PR and it passes all test cases.

<img width="636" alt="Screenshot 2024-10-24 at 3 30 58 PM" src="https://github.com/user-attachments/assets/4b054801-28a4-4938-bc69-10d67dbfae6a">

2024-12-19 23:23 UTC, nikhilpittala16 approved these changes
I have tested the PR and all the test cases have passed.
![Screenshot (271)](https://github.com/user-attachments/assets/391393e1-86bc-4fd5-a73c-2ec335cf3ee9)

2025-01-12 00:59 UTC, vishavk1992 approved these changes
All test cases passed successfully!!

2025-01-15 03:14 UTC, vishavk1992 approved these changes
I have reviewed this PR and have found the testcases to be worked correctly

2025-03-14 00:23 UTC, sri0606 commented
@one-community , this PR has been open for a while. The test file is still not in the dev branch and I've checked that all test cases ran fine.

2026-07-24 20:14 UTC, closed without merging