Ruike_filter_active_user
OneCommunityGlobal/HighestGoodNetworkApp pull request #1589
Opened 2023-11-26 01:33 UTC by StrawberryCalpico

# Description
<img width="678" alt="Screenshot 2023-11-25 at 8 26 33 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/4cf790da-b5c9-43e3-829e-e6a8ce353898">

## Related PRS (if any):
N/A

## Main changes explained:
- Update inputref to autofocus when user enter this page
- filter the user array to ignore inactive user

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin/owner user who has permission management permission
4. set an existing user(or create a new one) to be inactive
5. go to permission management 
6. make sure when you enter, the cursor is auto focus on the input field
7. and there's a placeholder to indicate only shows active user unless you type in characters
8. search for the user that you set inactive and make sure can't find it

## Screenshots or videos of changes:
<img width="693" alt="Screenshot 2023-11-25 at 8 32 40 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/69186ea2-9bc7-4eda-a6ad-a079899be4f1">

2023-11-26 04:44 UTC, palakgosalia commented
Hey, I reviewed your code and tested the changes. It works as intended. Details in the video. Thank you

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/12705799-e423-429d-8e0a-cd0dd5612ed1

2023-11-29 00:53 UTC, ptrpengdev commented
Hi @StrawberryCalpico , I tested both the Admin and Owner roles for this PR. The owner account has no issues. However, with the admin account, I didn't see the 'manage user permission' button. In the 'How To Test' section, it is listed as 'log in as an admin/owner user with permission management permission.' I would like to confirm that the Admin account should have permission to manage user permissions. Thanks.


**Admin**:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/7b8ab6e0-7748-44de-9b02-3a824b7b87e9)


**Owner**:

<img width="767" alt="1701218813795" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/7254a2f3-6776-4e36-a029-d7b854a4e28c">

![1701219099102](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/1f085003-daba-4060-be92-138cd9a87c9b)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/91163eb1-c346-4ba0-a1db-236936e0b40e)

2023-11-30 18:30 UTC, keyunhuangg approved these changes
Checkout of this branch and using the inactive user and did not see it in the search results. Seem like everything is working.
<img width="470" alt="Screenshot 2023-11-30 at 1 25 11 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/b1e8b356-5760-4d98-bc8e-0debd90fc3d3">
<img width="679" alt="Screenshot 2023-11-30 at 1 25 22 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/3b10b0e3-b7b2-484a-b2ac-f22d74ec6fa7">

2023-11-30 21:51 UTC, sucheta90 requested changes
Hi @StrawberryCalpico , I only had admin access, hence, I tried testing with the role - ADMIN, did not have an option to "Add New Role". Please refer to the recording.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/c7fab787-f79f-44f1-891d-d6cb486fce75

2023-12-01 06:55 UTC, StrawberryCalpico commented
Hi all, according to jae's description for this bug, I think admin should have the permission to edit the permission, it seems like someone might edit the permission for ADMIN when they tested some other features, which will cause the admin can't access this page

2023-12-01 19:36 UTC, ZichanYang324 approved these changes
I login as the owner and set it to inactive, all the features in the  **manage user permission** matched the expectations in the following:
(1) No result shows when I set my account as inactive.
(2) The placeholder did indicate the **Shows only ACTIVE** users before I typed in.

Good Job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86720318/39848f3e-0343-48f7-bd2f-030f70171508

2023-12-01 19:46 UTC, this-journey commented
Everything works as intended for the Owner role, however, not for the admin role as others have mentioned.  Video attached for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/7f0632c6-10c0-428c-8588-d4f22b3d192c

2023-12-02 04:29 UTC, ljrirene reviewed
Hi Ruike,
Here is an issue: When I log in as an admin, it doesn't show 'Manage User Permissions' after I click on 'Permissions Management'. It looks like the following picture:
![no-menu](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/1dc7c0d1-f607-4a5f-bc2e-ad7aa9d8f76c)

2023-12-02 04:57 UTC, ljrirene requested changes
Admin test didn't pass:https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1589#pullrequestreview-1760776534

Owner test passed:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/82b58ba5-0a71-413e-8b7f-b96663761994

2023-12-02 04:59 UTC, ljrirene requested changes
Admin test didn't pass:https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1589#pullrequestreview-1760776534

Owner test passed:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/ec15a5ce-1fae-4985-92c6-dc5930779f17

2023-12-02 06:44 UTC, wanglu1207 commented
<img width="1415" alt="Screen Shot 2023-12-01 at 10 42 59 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67501735/1a7ddfbc-7b04-435e-b1b2-6fb62a149d06">
Hi @StrawberryCalpico, after the user has been inactive, the page does not have the button.

2023-12-02 19:04 UTC, pika-chu11 approved these changes
Hi @StrawberryCalpico , the function works as intended! Once the user is inactive, it won't show on the assigning permission page anymore. Great Job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/90030d02-12fc-4a7d-897f-330b9d35cd51

2023-12-02 20:08 UTC, one-community commented
Admins shouldn't have that access. Thank you all, merging!

2023-12-02 20:09 UTC, merged