Jiyuan added scheduled-on date to scheduled blue square reason
OneCommunityGlobal/HighestGoodNetworkApp pull request #1641
Opened 2023-12-06 02:04 UTC by Jiyuanxia

# Description
![Screenshot 2023-11-29 153713](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/37306e7b-3789-44df-8aba-9eff76cba0e4)
![Screenshot 2023-11-29 153739](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/dc81fac0-c8b9-48bd-b171-1c90ad644498)

## Related PRS (if any):
This frontend PR is related to the [#640](https://github.com/OneCommunityGlobal/HGNRest/pull/640) backend PR.
To test this backend PR you need to checkout the [#640](https://github.com/OneCommunityGlobal/HGNRest/pull/640) backend PR.

## How to test:
1. check into current branch
2. `npm install`
3. `npm run start:local`
4. log in as admin
5. go to anyone's profile page
6. add a blue square to this person by clicking `+`
7. check if the new blue square contains the created date before the summary with right format(month/day) by hovering it
8. click this new blue square
9. check if  **created date** appears 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/2ead345b-2013-4f42-aeef-d8dbf69ca07b

## Note:
Old blue squares do not have **created date**

2023-12-07 18:54 UTC, Cavein254 commented
Hi @Jiyuanxia, reviewed your pr and everything works as expected :fire: 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/cd66b179-9fa7-4f66-ac2f-90bcc2b43b24

2023-12-07 20:54 UTC, this-journey submitted a review, later dismissed
Hello! I reviewed your PR and everything seems to be working perfectly.  I know this may be outside of the scope of your PR, however, may I suggest making the blue squares section a little bit bigger. In comparison to the "Schedule Blue Square Reson" button it's extremely small and difficult to find if you don't know exactly what you're looking for.  Great job! I've attached a video for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/16b6c075-ae26-4418-b549-21ae3921ab48

2023-12-08 07:07 UTC, Alforoan submitted a review, later dismissed
Assining blue square and hovering both worked. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/036b59f3-7dad-453e-ab45-5aef0dc29d59

2023-12-09 21:48 UTC, DragonSlayer2401 commented
I tested your PR and everything works as intended. I created the square, updated the square, and deleted the square on top of testing for the created date and hovering over it. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/2ad5520b-ee60-46b0-99dd-fbe1500d4542

2023-12-14 05:55 UTC, keyunhuangg approved these changes, later dismissed
Hello!

Things I tested for:
1) Verified that the "+" button is present
2) Added two date and it did create two blue squares and 
3) Clicked on the blue square that was created and it showed created date 
<img width="442" alt="Screenshot 2023-12-14 at 1 51 39 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/08b81fe9-8360-42e1-8ba2-ff8b96948e4d">
<img width="496" alt="Screenshot 2023-12-14 at 1 52 52 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/2ece4c0c-37fa-4bb1-a3ff-688be829dacd">
<img width="417" alt="Screenshot 2023-12-14 at 1 51 43 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/b6139966-3470-4d9b-912f-31e03210f0aa">

2024-01-16 02:48 UTC, yuhuimin1996 commented
Hi Jiyuan,
I've tested this FE pr also with the BE pr #640. Everything works well as you described. After adding a blue square, by hovering on it, the create date will show up. And after clicking on this blue square, the created date will appear beside ‘Created Date:'. Nice job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108281570/b431ad50-8a52-46f6-bfa1-98e5b846b6e4

2024-01-16 04:00 UTC, Sophie-lei approved these changes, later dismissed
hey! I just tested this PR, and everything works well. I tasted as admin role. After created 
 the blue square for other user with date and summary, the other user's blue square create date was shown as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/0f234876-8405-41f6-a105-3df01f711b0f

2024-01-17 06:41 UTC, pshereen submitted a review, later dismissed
I tested the PR as a admin user.

It works as per the requirement. 

Created date appears before the blue square description.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/5ea55f8a-6773-4222-b627-1fb06cfa1c25

2024-01-17 08:02 UTC, Renanluizssx approved these changes, later dismissed
Hi @Jiyuanxia, I tested your application, and it's working very well. I navigated to the leaderboard, clicked on an admin user named Aaron, pressed the plus button to add a blue square, entered the date, and then submitted. It showed me the date when I hovered over the mouse and it show me a date 
 when i clicked on the blue square button.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/253631b9-0cea-43d6-85ab-2835592e58ad

2024-01-17 20:58 UTC, X1aoZhang99 submitted a review, later dismissed
Hi Jiyuan, 

I've just tested this pull request, and everything is functioning correctly. I tested it in the admin role. After creating a blue square for another user with a date and summary, the creation date of the other user's blue square was displayed as anticipated.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/98cde0e8-014e-43b2-b033-33c9be226349

2024-01-18 10:13 UTC, Renanluizssx submitted a review, later dismissed

2024-01-19 00:36 UTC, Vishala09 commented
Works as intended! The created date appears now after creating a new blue square. But for some reason , I am getting a different date. Can you please let me know if this is expected?


[Untitled_ Jan 18,2024 4_31 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/e9a355a6-b881-4a59-b994-8ed42e0a4363)

Before with no created date:
<img width="960" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/cb28a0fe-c1b0-4f59-9816-cff51ffa78fd">

After with created date:
<img width="959" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/63e50962-aae0-4ba8-b90d-ea9442a38ac7">

2024-01-19 00:40 UTC, Vishala09 submitted a review, later dismissed
Please check my previous comment for the issue.

2024-01-20 23:12 UTC, xmyoot commented
Reviewed this PR and assigning blue squares functioned as expected, reference video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15240538/aba637fb-f139-4055-adf5-afe5a8de7b2c

2024-01-21 03:10 UTC, rusalshrestha98 commented on src/components/UserProfile/BlueSquares/BlueSquare.jsx
>                </div>
I think you may have an extra `</div` closing tag on line 61 that is causing the build to fail.

2024-01-21 03:13 UTC, rusalshrestha98 commented on src/components/UserProfile/BlueSquares/BlueSquare.jsx
> +
Might be better to remove this empty line space on line 18

2024-01-21 03:15 UTC, rusalshrestha98 commented on src/components/UserProfile/BlueSquares/BlueSquare.jsx
> +                  </div>
```suggestion
                  <div className="report" data-testid="report">
                    <div className="title">{formatDate(blueSquare.date)}</div>

                    {blueSquare.description !== undefined && (
                      <div className="summary">
                        {blueSquare.createdDate !== undefined
                          ? formatCreatedDate(BlueSquare.createdDate) + ':'
                          : null}

                        {formatDateFromDescriptionString(blueSquare.description)}
                      </div>
                    )}
                  </div>
```

2024-01-21 03:16 UTC, rusalshrestha98 commented on src/components/UserProfile/BlueSquares/BlueSquare.jsx
> +                  </div>
Try using Prettier extension in VS code to easily make your code look cleaner

2024-01-21 03:16 UTC, rusalshrestha98 requested changes, later dismissed
Please review above comments and resolve conflict in `formatDate.js`

2024-01-21 04:09 UTC, galgalinidhi commented
Hi @Jiyuanxia, the FrontEnd doesn't compile because of the following error-

<img width="1436" alt="Screenshot 2024-01-20 at 7 44 33 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/6e887014-67ec-4508-bf9a-104b0110c006">

I commented out the extra <div> tag. After that, the code compiles, but I notice that the page is not responsive.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/cb68157d-6847-48ee-a831-f79642ce3415

2024-01-21 19:16 UTC, 666saofeng requested changes
Hi, there is an extra <div> tag in BlueSquares.jsx. After I commented it out, the dashboard page became unresponsive.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/f837f07a-ee9c-4f07-82c8-708222e33351

2024-01-22 06:36 UTC, Jiyuanxia commented
Hi @rusalshrestha98 and @Vishala09 ala09, thank you for your previous review on my pull request. Unfortunately, I encountered some challenges while resolving conflicts, leading to a mistake. As a result, I've reverted the changes to a working version. Please review again. Thank you for understanding.

2024-01-22 16:07 UTC, peterson337 requested changes
I created the blue square, updated it, but the creation date is not displayed below the date entry.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/85061512-2109-4417-9e0d-c38cc9a0dcfc

2024-01-22 18:51 UTC, Jiyuanxia commented
> I created the blue square, updated it, but the creation date is not displayed below the date entry.
> 
>  Desktop.2024.01.22.-.12.28.40.04.mp4

Hi @peterson337 , the problem you mentioned should not happen. Check if you get the latest version and switch to the accourding backend PR.

2024-01-22 23:33 UTC, peterson337 commented
> > Criei o quadrado azul, atualizei-o, mas a data de criação não aparece abaixo da entrada de data.
> > Desktop.2024.01.22.-.12.28.40.04.mp4
> 
> Oi@peterson337, o problema que você mencionou não deveria acontecer. Verifique se você obteve a versão mais recente e mude para o PR de back-end correspondente.

[@Jiyuanxia](https://github.com/Jiyuanxia), Which branch are you on?

2024-01-23 14:47 UTC, peterson337 commented
> > I created the blue square, updated it, but the creation date is not displayed below the date entry.
> > Desktop.2024.01.22.-.12.28.40.04.mp4
> 
> Hi @peterson337 , the problem you mentioned should not happen. Check if you get the latest version and switch to the accourding backend PR.

Hi [@Jiyuanxia](https://github.com/Jiyuanxia), The changes you made have not been merged into the development branch. Which branch are you on?

2024-01-23 18:01 UTC, peterson337 commented
> > I created the blue square, updated it, but the creation date is not displayed below the date entry.
> > Desktop.2024.01.22.-.12.28.40.04.mp4
> 
> Hi @peterson337 , the problem you mentioned should not happen. Check if you get the latest version and switch to the accourding backend PR.
[@Jiyuanxia](https://github.com/Jiyuanxia), I was able to use your branch to test this PR, and it worked.

2024-01-23 18:13 UTC, peterson337 approved these changes, later dismissed
I tested it, and everything works as expected.

![one comunnity](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/ad29d160-826d-4eb0-9d38-cd2086ee178f)

2024-01-26 16:54 UTC, SRamen1999 submitted a review, later dismissed
I've just tested this PR, and everything is functioning correctly. Both the admin and owner roles can create, edit, and delete blue squares. The date and summary is displayed without any issues.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/e73dde86-1299-443c-8729-53d7e068ee08

2024-01-27 03:58 UTC, KevHnh approved these changes, later dismissed
Nice job, everything works as intended!

Using an owner account I was able to create, update, and delete a blue square. Everything functioned as planned and no issues were seen.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/5f641241-24a6-4e06-9492-0506ea52bcfb

2024-01-28 05:28 UTC, xmyoot commented
Hello, great work on this component, I'm getting this error on the front end, I've checked out to the corresponding branches on both front end and back end, npm installed and ensured node 14 was being used but I keep getting this error please reference the photo for more details: 
<img width="1353" alt="PR#640+1641" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15240538/5fb2eaca-5bcf-4876-a72e-13680cc0cb0b">

2024-02-03 18:34 UTC, Pandani07 approved these changes
Tested this PR and the related backend PR, everything works as expected. I could add a new blue square for a user. I could also check the created date for a blue square and update the description of an existing blue square.  The **created date** inside the blue square modal can be styled better but everything else is great!

2024-02-04 16:55 UTC, merged