Nathan make editing roles permission-based
OneCommunityGlobal/HighestGoodNetworkApp pull request #1659
Opened 2023-12-09 00:09 UTC by nathanah

# Description
This PR replaces the role-based logic for determining front-end permission to edit roles to match the permission-based logic on the back end.

## Main changes explained:
- Use standardized `hasPermisison()` logic for checking if users can edit or delete roles
- Add a check to make sure nobody can edit their own or the Owner role except for Owners

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other LInks→ Permission Management→ any testing role
6. verify you can edit, save, and delete permissions and presets
7. verify you can create a new role and delete it
8. verify that you can't edit admin or owner as an admin, but can edit both as an owner

2023-12-09 02:04 UTC, Alforoan requested changes, later dismissed
Everything seems to work except when I try to delete a role as an amin.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/bb5e6435-fce8-48b4-8add-dcd5d2328d5f

2023-12-09 04:25 UTC, nathanah commented
> Everything seems to work except when I try to delete a role as an amin.
> 
>  pr.review.1659.mp4

Admins don't have permission to add or delete roles. I swapped the logic to use permissions, but forgot only Owners should still be able to do that. Thank you for reminding me. I updated the instructions.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/23086054/7adf83a6-39fb-4b48-a128-454ddbfbb6eb)

2023-12-09 05:38 UTC, this-journey approved these changes
Everything works beautifully including the ability to delete a role as an owner.  I've attached a video for reference.  Great job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/21d6455a-bb92-4f57-a187-31879be1df66

2023-12-09 21:28 UTC, DragonSlayer2401 commented
I tested your PR it works as intended. I used both the Admin and Owner account as requested. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/4f72e616-0070-4670-8e69-2e692309d863

2023-12-17 01:13 UTC, pika-chu11 approved these changes
Hi @nathanah , I have tested you PR and you did a great job!

- Log in as Admin
    - Under Other Link -> Permission Management
        - I was able to edit, save and delete permissions and presets but I was unable to edit permissions of both Admin and Owner as expected

- Log in as Owner
    - I was able to edit, save, and delete permissions and presets of any roles.
    
 Please watch the video for workflow:
 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/8db3f0e9-46a1-4f3a-ad0c-5100c9272392

2023-12-21 00:13 UTC, one-community commented
Thank you all, merging!

2023-12-21 00:13 UTC, merged