Jiangwei ceate unit test for TableFilter
OneCommunityGlobal/HighestGoodNetworkApp pull request #1675
Opened 2023-12-10 04:21 UTC by Jiangwei-shi

# Description
Create unit tests for the TableFilter component to confirm whether it working as intended.

## Main changes explained:
- Create file TableFilter.test.js  to do the unit tests

## How to test:
1. check into the current branch
2. do npm install and run this PR locally
3. open file src → __tests__ → TableFilter.test.js
4. run `npm run test src/__tests__/TableFilter.test.js`

## Screenshots or videos of changes:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/8acddb6b-2a02-461f-86dd-3558cf2b2b0f)

## Note:
If all tests passed, everything worked as intended.

2023-12-10 05:44 UTC, Alforoan submitted a review, later dismissed
All tests passed. Nice!

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/2a258a98-f204-4bf1-9ecc-77a83490e27a)

2023-12-15 18:41 UTC, this-journey approved these changes, later dismissed
Hello @Jiangwei-shi !  I reviewed your PR and all tests passed.  Great job!
![Screenshot 2023-12-15 at 10 41 29 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/c4cfa5c0-0a7a-4ed3-a121-2805eaf71cf6)

2024-01-14 05:48 UTC, bienzguoa reviewed
All test cases passed. It seems the build process failed when running npm test, please look into that to resolve it.
<img width="873" alt="Screenshot 2024-01-13 at 11 47 28 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/9a398d5d-de51-460e-be21-32e6a2c8137e">

2024-01-18 08:34 UTC, beblicarl requested changes
In the unit testing channel, they suggested that we please follow the convention outlined there for saving your tests in a relevant folder: src/components/Component/__tests__     Please do NOT store them in the src/__tests__

2024-01-19 01:29 UTC, ramyaram2092 requested changes
Hi @Jiangwei, I think we can enhance the validations further. I suggest ensuring that each object within the component has at least one validation. Here are some specific test cases:

1. A test case to assess the functionality of InputWithCalendarIcon.
2. Additional unit test cases for TextSearchBoxes, DropDownSearchBoxes, and DatePicker.
3. A test case to validate the Checkbox and its default values.
4. A test case to verify the default date range.

2024-02-01 00:06 UTC, ramyaram2092 requested changes
Good job on the test cases. I beleive unit test cases for date picker and DropDownSearchBox can also be added.  Kindly correct me if the validations have already been added

2024-02-01 00:06 UTC, ramyaram2092 commented on src/components/Reports/TableFilter/__tests__/TableFilter.test.js
> +    fireEvent.change(startDateInput, { target: { value: '01/01/2020' } });
What is the validation here ?

2024-02-10 20:35 UTC, DragonSlayer2401 commented
The tests appear to have a few errors preventing them from running please watch my video to see the errors

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/11e83d96-ec0f-4c87-b299-7d9b71389ae6

2024-05-25 17:15 UTC, meetpadhiar4 approved these changes
Hi, I tested your PR and it passed all the test cases. Please refer the screenshot attached.
<img width="1028" alt="PR 1675" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/e2069007-9eda-40ae-b87d-4339988e2144">

2024-08-09 23:41 UTC, Gmon-k commented
Test cases has passed and Below is the screenshot for it.

<img width="1024" alt="2" src="https://github.com/user-attachments/assets/cba31f6f-6f22-4a83-9b53-bfabd53e209d">

2024-08-13 03:19 UTC, Gmon-k commented
I am getting below error and test cases has failed

<img width="1024" alt="1" src="https://github.com/user-attachments/assets/d9806a34-2368-486d-ba5a-d78780955724">

2025-03-14 00:29 UTC, sri0606 commented
@one-community , Test file for TableFilter already exist in the dev branch. This PR can be closed.

2025-03-14 00:57 UTC, closed without merging