Shrey WeeklySummaries unit tests
OneCommunityGlobal/HighestGoodNetworkApp pull request #1704
Opened 2023-12-15 18:18 UTC by Shreyj14

# Description
Unit tests for WeeklySummaries component

## How to test:
1. check into current branch
2. do `npm install` 
3. npm test WeeklySummaries.test.js
4. verify that all tests pass

## Screenshots or videos of changes:
<img width="928" alt="Screenshot 2023-12-15 at 11 48 18 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/e56167ec-5e60-44fd-8105-a1ccbfa4f4e7">

2023-12-15 18:34 UTC, this-journey approved these changes
Hello @Shreyj14!  I reviewed you PR and all tests passed.  Great job.

![Screenshot 2023-12-15 at 10 34 07 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/6e4d69bc-be84-478b-954c-623208dbde0d)

2023-12-15 21:01 UTC, sxiong5 approved these changes
Hey @Shreyj14, all the tests were passed, nice job!
<img width="687" alt="Screenshot 2023-12-15 at 16 00 29" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/f5bd8eab-35b5-4f8f-bc1e-f233981fb482">

2023-12-16 05:29 UTC, sahilpatel18 approved these changes
All test cases passed successfully. Great work! 

<img width="620" alt="Screenshot 2023-12-16 at 12 29 23 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/24741818/5df17f29-1475-41e2-8ff2-20ed1c863dfa">

2023-12-16 06:21 UTC, wanglu1207 commented
<img width="413" alt="Screen Shot 2023-12-15 at 10 21 35 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67501735/4cfb8497-f533-494a-b788-241a11e137cd">
All the test cases were successful. Excellent job!

2023-12-16 20:48 UTC, DragonSlayer2401 commented
I tested your PR all of the tests passed as expected. Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/84eaca8b-7d7e-42e8-a0fd-6db1f0f8786e

2023-12-16 21:52 UTC, Lin1404 commented
I tested your PR, all the tests were passed, nice job!

![Screenshot 2023-12-16 at 4 52 07 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/1a34dd3c-054b-42d5-b12e-b69b7ee6a40d)

2023-12-16 21:53 UTC, Lin1404 approved these changes

2023-12-17 07:52 UTC, ljrirene approved these changes
All the tests passed here. Thanks!
![6](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/619869a8-c17b-4096-b8d1-f3453435af8c)

2023-12-19 07:03 UTC, Alforoan submitted a review, later dismissed
Tests all pass, but some suggestions I can make: 
1. Instead of "renders no summaries message when there are no summaries," maybe "should display 'No weekly summaries available' message when there are no summaries." would be slightly better.
2. Maybe consider adding a test case for when user object is missing. 


![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/50a66b4d-d601-445e-93a7-a0775b4f34e6)

2023-12-29 17:05 UTC, sahilpatel18 approved these changes
All test cases passed successfully. Great work! 
<img width="529" alt="Screenshot 2023-12-29 at 12 04 59 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/24741818/a219c038-5087-435f-9d68-67c014cdbe61">

2023-12-30 07:29 UTC, vikrambadhan approved these changes
Hi, I tested your PR and all the test cases passed!

![Week 18 - PR4](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/3ca59dfb-55df-4016-a0b7-865be1c439de)

2024-01-04 20:57 UTC, Shreyj14 commented
> Tests all pass, but some suggestions I can make:
> 
> 1. Instead of "renders no summaries message when there are no summaries," maybe "should display 'No weekly summaries available' message when there are no summaries." would be slightly better.
> 2. Maybe consider adding a test case for when user object is missing.
> 
> ![image](https://private-user-images.githubusercontent.com/118868270/291460112-50a66b4d-d601-445e-93a7-a0775b4f34e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDIwODAsIm5iZiI6MTcwNDQwMTc4MCwicGF0aCI6Ii8xMTg4NjgyNzAvMjkxNDYwMTEyLTUwYTY2YjRkLWQ2MDEtNDQ1ZS05M2E3LWEwNzc1YjRmMzRlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQyMDU2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWY1NGNkYWY3OGZhNGE4OWI5MTBjYTViYmUzMWM2ZjVjMzg2YTM5ZTc5MmIwMjNmM2Y4YTZhNTZkNTdlNjA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j1Chxt9EAxWNMwbnGhdmHE0UATaoa10IbQjTlTvjsOI)

Hi @Alforoan the code covers 100% of the line.

2024-01-05 22:07 UTC, Shreyj14 commented
@Alforoan the code has 100% line coverage and take cares of all the lines. Please approve.

2024-01-06 18:19 UTC, BaileyM96 approved these changes
Hello @Shreyj14 I ran your test and all tests were passed and cover 100% of the lines are covered in the test. Great work!

## Screenshots

<img width="579" alt="Screenshot 2024-01-06 at 10 17 37 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/5716602e-cfd6-47cb-870d-596c4932b3a6">

2024-01-06 19:46 UTC, KurtisIvey requested changes
<a>https://docs.google.com/document/d/1-SMFLeoBoJhn8FUas5oLkofYoLTRM-Tz1HfjZ0gbBuk/edit</a>

Great job on everything. Just one small thing. Please fix the location of the test file to follow the current standard set forth in the codebase rules and conventions. I know this incorrect location has already been established(incorrectly lol). However, we'd like to minimize this going forward to create a more intuitive folder structure.

2024-01-14 06:56 UTC, bienzguoa reviewed
Good job! Test cases all passed, please fix the file location as Kurtis mentioned above.
<img width="764" alt="Screenshot 2024-01-14 at 12 56 10 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/58a4dea5-ce1d-4a6f-be06-95eeb9a4c57e">

2024-01-20 18:51 UTC, KurtisIvey commented
Hey Shreyj14, just checking in on this. Would love to go ahead and get this ready for merge once it's moved to the correct location as you've done great work here.

2024-01-28 03:43 UTC, 666saofeng approved these changes
Hi, All tests passed!
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/af9b156f-5c45-4860-b671-c30bb17f5704)

2024-03-23 22:52 UTC, Tiantian-C approved these changes
All the tests have been passed.Good job!
<img width="681" alt="Screenshot 2024-03-23 at 3 51 41 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/b4be200e-a4c1-451f-ac1d-0a41a84f453d">

2024-03-25 04:10 UTC, one-community commented
Shrey seems to have abandoned this one and 1582. I've followed up on Slack and by email. Can someone else help finish these?

2024-10-26 01:07 UTC, geetamatkar commented
Tested this PR and all the test cases have passed.

<img width="769" alt="Screenshot 2024-10-25 at 8 07 29 PM" src="https://github.com/user-attachments/assets/0159877d-7645-4140-b55b-e831d9a8afe7">

2025-03-17 21:32 UTC, sri0606 commented
Updated [PR here](#3284). Closing this.

2025-03-17 21:32 UTC, closed without merging