added new unit tests for NewUserPopup
OneCommunityGlobal/HighestGoodNetworkApp pull request #1733
Opened 2023-12-20 17:40 UTC by Changhao3220K

# Description
new unit tests for NewUserPopup.jsx

## How to test:
1. check into current branch
2. do `npm install` and `npm test NewUserPopup.test.js` to run this PR locally
3. verify all 8 tests are passed

## Screenshots:
<img width="681" alt="Screenshot 2023-12-20 at 12 36 28 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104778270/112a8b79-5f34-4906-9cb0-bb845a6437ef">

## Note:
please ignore the error caused by `EditableInfoModal`

2023-12-21 07:58 UTC, Alforoan approved these changes
All tests pass, but you could be a little more descriptive with your test description, such as 'should render the new user popup with close buttons and heading'. 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/3146a7ad-41c9-419d-9aa5-bbb479398a79)

2023-12-21 21:23 UTC, this-journey approved these changes
Hello @Changhao3220K !  I reviewed your PR and all tests passed.  Great job!
![Screenshot 2023-12-21 at 1 22 21 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/ed02e3ea-9dcf-4bd8-a0c3-d326d4cdb7e5)

2023-12-26 22:22 UTC, ilyaflaks requested changes
When I checkout this branch and run "npm test NewUserPopup.test.js" I get a number of errors printed to my console, mostly by information.js try/catch block (line 14). I spliced them together to save space here: 
<img width="1199" alt="PR1733-errors" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/11a744dd-1a77-47d9-8545-5f6c5bd68d35">
In the middle of all that text I can see that the unit tests are actually passing: 
<img width="1201" alt="PR1733-pass" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/1a01685e-a289-4bf2-b80a-c5e75dd74d34">

I don't know how to resolve these errors, but I can tell you that they were also present in the old version of NewUserPopup.test.js that is currently on the development branch. 

One minor unrelated suggestion is to update the description on line 34: " it('should render User Profile', () => {...", to something more specific like "should render AddNewUserProfile component"

2023-12-29 17:03 UTC, sahilpatel18 reviewed
Test cases did not pass; instead, I was presented with a long list of errors in my console. This will require further examination.

2023-12-30 07:25 UTC, vikrambadhan approved these changes
hi, I tested your PR and none of the test cases passed and also I got a couple of errors too.

![Week 18 - PR3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/a8ab3ffa-e2c5-4a73-aa71-e533a28b9c0c)

2023-12-30 13:15 UTC, bienzguoa reviewed
Got many warnings and console errors here, codes should be adjusted for the prop type "loading". 
<img width="914" alt="Screenshot 2023-12-30 at 5 13 33 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/3817bd4e-4c79-493a-9ffe-ba715b9aa9b9">

2024-01-09 20:01 UTC, ChengyanOo requested changes
@Changhao3220K,

I've conducted tests on the recent changes you implemented. During testing, an error was encountered. For your reference, I've attached the log file which contains the console output. This should provide more details about the issue. Looking forward to your insights on this.

<img width="1440" alt="Screenshot 2024-01-09 at 14 59 35" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69735000/6e1ab950-7020-4215-8a85-e6403cb438e0">

[HGNServer.log](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/files/13878436/HGNServer.log)

2024-02-06 03:03 UTC, 666saofeng reviewed
Hi, all tests passed. However, there was a console error. Please refer to the video for details.

Uploading Badge.jsx - HighestGoodNetworkApp - Visual Studio Code 2024-02-05 21-56-50.mp4…

2024-02-06 03:05 UTC, 666saofeng reviewed
Hi, all tests passed. However, there was a console error. Please refer to the video for details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/b553451c-0d1f-4337-ad95-70c813cb9f74

2024-02-14 18:06 UTC, peterson337 approved these changes
HI Changhao, All tests passed and were unaffected by the error that appeared in the console.

![a](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/8c04af40-737b-43ce-afb8-d9f4ff27f723)

2024-02-20 11:46 UTC, ShengjieMao reviewed
The unit test file can't run properly. Got long list of console errors. The majority is caused by a prop called "loading". May refer to it in "editableInfoModal" to check for causes. 
<img width="808" alt="PR_1733" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/3d240258-6307-4a5b-97dd-1140b50fc43c">

2024-03-01 22:58 UTC, XiaohanMeng reviewed
Hi, all test cases passed but with error.
![PR1733_result](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/8fb7318c-b52f-4ab6-9108-744be572d45e)

2024-05-17 10:17 UTC, KaushikMreddy commented
Hi, 
all the test cases have passed but with error
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/7739e916-02aa-4a79-8515-e7f1c70ebaa0)
A lot of these errors have popped up
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/d8001b01-86d0-4be6-b083-2c3163e60ad0)

2024-05-20 20:11 UTC, dkn6 reviewed
When I ran the tests in my environment, multiple errors occurred. I have attached a screenshot for your reference.

<img width="946" alt="test" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/168319518/2ebedfad-c176-4ca8-b9e6-737c64aef813">

2024-08-09 23:38 UTC, Gmon-k commented
Test cases didn't passed and I could still see axios error from my side. Below is the screenshot for it.

<img width="1024" alt="1" src="https://github.com/user-attachments/assets/e5091c02-eff6-41c2-8152-7cfea29958a8">

2024-09-07 02:23 UTC, Saniya98 approved these changes
All test cases passed, but I am getting an console error
![image](https://github.com/user-attachments/assets/cc9f97f0-d12b-4922-bedd-f50e0c03eb47)

2024-09-13 04:07 UTC, ishangoel17 reviewed
All test cases are passing. Below is the screenshot for reference:
![Capture1733](https://github.com/user-attachments/assets/91597f9f-a572-40e8-bc07-eaf5defe8c2b)

2024-10-17 14:39 UTC, beblicarl commented
@Changhao3220K , can you please change the location of this test

2024-12-04 23:19 UTC, sri0606 commented
This PR seems like a duplicate of [this PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1835). I have already fixed the errors and merge conflicts for the latter in a [new PR here](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2901).

2025-01-27 03:02 UTC, closed without merging