unit test case for SetUpFinalDayPopUp
OneCommunityGlobal/HighestGoodNetworkApp pull request #1739
Opened 2023-12-22 21:18 UTC by belagaam

# Description

Unit test case for SetUpFinalDayPopUp

## How to test:

1.     check into current branch
2.     do npm install
3.     npm test TangibleInfoModal.test.js
4.     verify that all tests pass

## Screenshots or videos of changes:

<img width="1012" alt="Screenshot 2023-12-22 at 4 17 37 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/f43e9904-87df-499a-825d-e97de8a84cd4">

2023-12-23 07:00 UTC, Alforoan requested changes
Your test name is wrong. It's supposed to be SetUpFinalDayPopUp and not Tangible... (that's your pr #1737). Also even with a name change, I get this error.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/cb487760-551d-4106-bea4-dcd8557ba0fb)

2023-12-23 19:31 UTC, belagaam commented
> Your test name is wrong. It's supposed to be SetUpFinalDayPopUp and not Tangible... (that's your pr #1737). Also even with a name change, I get this error.
> 
> ![image](https://private-user-images.githubusercontent.com/118868270/292612150-cb487760-551d-4106-bea4-dcd8557ba0fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNjAwNDMsIm5iZiI6MTcwMzM1OTc0MywicGF0aCI6Ii8xMTg4NjgyNzAvMjkyNjEyMTUwLWNiNDg3NzYwLTU1MWQtNDEwNi1iZWE0LWRjZDg1NTdiYTBmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxOTI5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzM2ODhiZjkzODUyMWM2MDNkZjFkN2YwMWU4ZmNhZGNjMzYxODZlODI2NjIzZDA4N2VlNmE2NDhiY2QyZDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YqXU5kI0nilWC4K2APoOq4BpG1SJHcWOzYQqaiwjhqE)

Thanks for pointing that out. I have fixed that.

When you are testing use this command "npm test SetUpFinalDayPopUp.js"

2023-12-30 07:18 UTC, vikrambadhan approved these changes
Hi, I tested you PR and all the test cases passed!

![Week 18 - PR2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/3f668da1-4b77-4603-8cb6-8aa30ef9545e)

2023-12-30 20:50 UTC, Lin1404 commented
Hi, I tested you PR and all the test cases passed. Good Job!
![PR1739_1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/a5e23833-4f58-42a4-b52a-0df69147e1e3)

2024-01-07 05:29 UTC, bienzguoa approved these changes
All test cases passed! Good job.
<img width="893" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/8d821e7e-db58-4457-8145-b7467be55a5d">

2024-01-09 17:40 UTC, bajajtushar094 approved these changes
All test cases passed. Thanks 
![Screenshot 2024-01-09 at 23 10 10](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/67af9dcd-80e5-4771-9591-391df9389b20)

2024-01-27 11:27 UTC, ShengjieMao approved these changes
All tests passed. Great
<img width="655" alt="PR_1739" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/c3d6521b-ebf0-4ab7-8a88-8aa8e66ffe45">

2024-01-28 03:50 UTC, 666saofeng approved these changes
All tested passed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/c39d99d4-121d-41ea-9a13-1ce3536c9c75)

2024-03-01 22:59 UTC, XiaohanMeng approved these changes
Hi, all test cases passed. Great job!
![PR1739_result](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/cb9b3532-3b3d-47a1-9237-bbee1acc4ad1)

2024-04-26 20:47 UTC, yvonnep165 submitted a review, later dismissed
Hi @belagaam I have checked the test cases and ran the tests. They all passed. Please refer to the screenshot below:

<img width="716" alt="Screenshot 2024-04-26 at 1 44 01 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/49b88ceb-2052-45ff-b168-11c1a520d810">

2024-04-28 01:26 UTC, KurtisIvey requested changes
Tests have just the right coverage for what's going on with the component. The date format is restricted by default, so you're spot on by not having to test for any additional inputs. 

My only suggestion and criteria for approval is relocating the test to the proper location per HGN standards to keep things organized.

refer to this for correct folder structure:
https://docs.google.com/document/d/1-SMFLeoBoJhn8FUas5oLkofYoLTRM-Tz1HfjZ0gbBuk/edit#heading=h.m9b033294wic

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/6c924cb8-e77a-4bb7-a97a-2f6e34c0ee08)

2024-05-20 19:40 UTC, dkn6 approved these changes
Thank you for your great work! All test cases are working as expected.

<img width="789" alt="test" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/168319518/5a31839d-99f1-42cd-a26c-7ef12b686c62">

2024-06-22 23:17 UTC, belagaam commented
> Tests have just the right coverage for what's going on with the component. The date format is restricted by default, so you're spot on by not having to test for any additional inputs. Great job on the tests.
> 
> My only suggestion and criteria for approval is relocating the test to the proper location per HGN standards to keep things organized.
> 
> refer to this for correct folder structure: https://docs.google.com/document/d/1-SMFLeoBoJhn8FUas5oLkofYoLTRM-Tz1HfjZ0gbBuk/edit#heading=h.m9b033294wic
> 
> ![image](https://private-user-images.githubusercontent.com/19482363/326222320-6c924cb8-e77a-4bb7-a97a-2f6e34c0ee08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwOTg1MzcsIm5iZiI6MTcxOTA5ODIzNywicGF0aCI6Ii8xOTQ4MjM2My8zMjYyMjIzMjAtNmM5MjRjYjgtZTc3YS00YmI3LWE5N2EtMmY2ZTM0YzBlZTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDIzMTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMTBkMzExNmQyMDRhYzNjOTA1OGI1MTRmNjcwNjQ3MDc4YTAyOWIwMGYxZTZmNTRkNzEzMWE5YjdjMWMxNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dbi1NoA8MxYnk3iZ88_0GwqVrKIWvKMbPSZpW32bsxQ)

Moved the file to the correct folder. can you review it again?

2025-05-07 13:29 UTC, closed without merging