Haohui - fix permission for edit tasks
OneCommunityGlobal/HighestGoodNetworkApp pull request #1742
Opened 2023-12-23 06:14 UTC by Lin1404

# Description
Please include the exact bug/functionality description and a summary of the changes/ related issues. Please also include any other relevant motivation and context:
Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ task→…
6. verify function “A” (feel free to include screenshot here)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2023-12-23 18:08 UTC, AriaYu927 approved these changes
Hi @Lin1404 , I've tested your PR and everything works as expected.

For individual who is assigned the permission:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/cc55499e-312b-421e-a881-e3b2bf075096


For Manger user:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/cfbb9872-753f-476a-b345-6734752482f0

2023-12-24 00:32 UTC, ljrirene requested changes
Hi Haohui, I logged in as a volunteer user and a manager user. 
Everything works as expected when I logged in as a volunteer user:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/84018ee4-f57c-4f11-9472-533b9f7e78b9

However, when I logged in as a manager user, I can't unselect the edit button here:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/84546b76-3ab9-449d-9e78-068f1f0fdc44

2023-12-24 01:44 UTC, mianmiantea2019 commented
Hi @Lin1404 , 

I tested with different user roles: an owner user, a manager user, and a volunteer user. Everything operated smoothly without any issues.

For Manger user:

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/e295706a-1915-401e-a5d9-6a4dee73dce9)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/a8a0cf71-ea0b-440c-85ef-a7d3f61c3137)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/1ad6dd72-5db3-4e8b-9663-ecf0e62c63ac)

For Owner user:

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/3460f2c2-e377-45c5-8bc5-6ce74fa70e81)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/1a7c08a2-d2f2-41c8-9da3-eede72bb6d75)

For individual who is assigned the permission:

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/458ab90e-7d44-44ff-9acb-f06a2dc87937)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/39c14e13-16b1-4ea3-87ae-43f3d5b737a6)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/6a9dbde6-3a03-4543-ae94-d717f61fa6a0)

2023-12-24 05:07 UTC, Lin1404 commented
> Hi Haohui, I logged in as a volunteer user and a manager user. Everything works as expected when I logged in as a volunteer user:
> 
>  Screen.Recording.2023-12-23.at.16.28.45.mov 
> However, when I logged in as a manager user, I can't unselect the edit button here:
> 
>  Screen.Recording.2023-12-23.at.16.20.20.mov

Hi @ljrirene , we don't want to remove this for manager user. It is a default ability for manager account.

2023-12-26 19:54 UTC, ilyaflaks requested changes
I tested this PR and my finding are essentially the same as those of @ljrirene 
1) checked out this branch, ran npm run build and npm run start, cleared cash. Logged in as owner. Owner can "Add" the Edit Task permission to a Volunteer account: 
<img width="990" alt="PR1742-owner-to-volunt" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/22cf7234-9355-4c47-8389-b65f5f65f025">
2) Logged out, logged back in as the Volunteer who just got permissions updated. Was able to edit projects and save: 
<img width="870" alt="PR1742-volunt-edit-proj" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/0eed5f8f-88dd-4183-bdb9-2689fc014c4e">
<img width="1002" alt="PR1742-volunt-save-proj" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/69e5cc81-1c79-48f7-a864-012136b83c61">

3) Logged out, then back in as Owner again, selected a manager account. Clicked "Reset to Default": 
<img width="872" alt="PR1742-owner-edit-manager" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/d3d952a5-f73e-4ce6-8619-781df5a0d767">
4) This is where things diverge. Your test instructions say "15. scroll down and click submit button (double check "Edit Task" is unselected)" but "Edit Task" is enabled and the "delete" is disabled even for an Owner
<img width="944" alt="PR1742-owner-can-not-disable" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/a1fb6658-35a7-446b-a2b2-fc20ac8157c0">
5) Manager can edit and save a task:
<img width="1158" alt="PR1742-manager-edited-task" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/d4fa1d94-7116-475c-a7b8-82cadd6e79f1">

Since the last line in your instructions is "18. make some change of the task then submit.", could it be you did not mean to disable the edit feature for the Manager account? If it was unselected and then saved, a Manager would not be able to edit the task. 
If this is the intended behavior, please comment and I'll give my approval. 
Also, this is possibly outside of the scope of this PR, but I'd like to suggest a UI change: when one clicks "Reset to Default", nothing noticeable happens. A user might think it didn't work. Perhaps add another "toast" or disable the button after it performed it's function.

2023-12-28 04:54 UTC, Alforoan requested changes
As you can see the volunteer user permission change worked, but the manager's edit permission is disabled.



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/e9a583fe-284b-414f-b0e1-356982cc2300

2023-12-28 20:31 UTC, Lin1404 commented
> Since the last line in your instructions is "18. make some change of the task then submit.", could it be you did not mean to disable the edit feature for the Manager account? If it was unselected and then saved, a Manager would not be able to edit the task. If this is the intended behavior, please comment and I'll give my approval. Also, this is possibly outside of the scope of this PR, but I'd like to suggest a UI change: when one clicks "Reset to Default", nothing noticeable happens. A user might think it didn't work. Perhaps add another "toast" or disable the button after it performed it's function.

@ilyaflaks Thank you for the review. Yes, since "edit task" is a default ability for manager account, so we want to keep it in all manager account. And thanks for the "disable button" advice, I will talk with Jae about this.

2023-12-28 20:36 UTC, Lin1404 commented
> As you can see the volunteer user permission change worked, but the manager's edit permission is disabled.
> 
>  pr.review.1742.mp4

Thank you for the review. We don't want to remove this for manager user. It is a default ability for manager account.

2023-12-28 21:36 UTC, ilyaflaks approved these changes

2023-12-28 21:37 UTC, ilyaflaks commented
Changing my review to an approval because Haohui clarified that the "bug" I pointed out is intentional

2023-12-30 22:39 UTC, GKD890 approved these changes
It works as intended, I can't load Dashboard, thus I used WBS url to test. The Manager role should by default has `Edit` ability to the task. The volunteer account before I give the permission can only `suggest` to certain task.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/57503876/88868c91-1a44-471f-8a6f-6a7d9c9bd6db

2024-01-06 19:01 UTC, Haoxiang310 commented
I've tested through owner role, volunteer role and manager role. 
For owner editing a volunteer's permission, it works as expected:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/135764868/d88cc335-27b4-42c7-a7d8-59ebabdd67b9
For manager, most of the functions works as expected, but the edit task button is disabled:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/135764868/36507d43-0787-473a-996a-09e6760584d5

2024-01-11 20:16 UTC, DragonSlayer2401 commented
Everything is working as intended. Please watch the overview video below for more details;


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/e160665b-820c-4629-a869-c30bc1600689

2024-01-13 02:45 UTC, Sophie-lei approved these changes
I just tasted this PR with the user and manager role. Both of them can edit the task and reload with the correct update. I believe it working as expected. Here is the video to check.
For owner role change the user role permission

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/5d37abc8-57a1-4c4b-b675-aa91ebccc6a8

For owner role change  manager role task permission 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/ea8dc6eb-eb30-49d0-a10f-de0d8d965665

2024-01-14 05:06 UTC, Lin1404 commented
> I've tested through owner role, volunteer role and manager role. For owner editing a volunteer's permission, it works as expected:
> 
>  PR6-.1742.permission.mov 
> For manager, most of the functions works as expected, but the edit task button is disabled:
> 
>  PR6-.1742.manager.mov

Hi @Haoxiang310 Thank you for the review. We don't want to remove this for manager user. It is a default ability for manager account.

2024-01-19 03:58 UTC, pshereen approved these changes
Hi Haohui,
I logged in as an owner user and enabled the permission to edit task for a volunteer user.

<img width="890" alt="Screenshot 2024-01-18 194350" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/2ff981be-e2e5-4802-b5c0-8b2189aec77e">

Then I logged in as a volunteer user and was able to edit the task.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/cd82d03d-8e08-40d7-9792-333b8c1f4372

Later I logged in as an owner user and set the permissions of manager user to default by clicking "Reset to Default" button. 

<img width="896" alt="Screenshot 2024-01-18 194512" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/85030dfa-c567-43cf-a959-d739c5b649f4">

Then I logged in as the manager user and was able to edit the task.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/2e6240e2-4433-474a-ab3c-66f203c3aeb3

However, I have one suggestion. After clicking "Reset to Default" in manage permissions page, there is no way to let the user know that permissions are set to default. It will be good if a pop-up message is shown like the one showing after clicking submit button. I had to click two times to make sure the button was clicked, and it reset the permissions.

2024-01-20 22:15 UTC, xmyoot commented
Logged in a Admin and set new role for test user, added permissions to edit tasks and delete tasks. Logged in as Test User with elevated permissions and was able to successfully perform both operations, please see video for more details

Uploading Screen Recording 2024-01-20 at 2.11.48 PM.mov…

2024-01-21 01:22 UTC, KevHnh approved these changes
Tested with an owner account and works as expected. Only suggestion which is unrelated to the functionality is that the permissions list could be collapsible (you can see me struggle to look for the right permission in the recording). Again, unrelated so great work on the fix. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/90e13db6-71b3-4ad0-97a7-d6b2108a105b

2024-01-21 06:59 UTC, galgalinidhi commented
Hi @Lin1404, I tested the PR for both Volunteer as well as Manager accounts. It works as expected!

For Volunteer-


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/5e57fbb3-37de-41f2-b00c-2c646e6ab407

For Manager-


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/187ee395-3cc1-49c5-a0ad-f46eb1cd48c8

2024-01-22 18:21 UTC, X1aoZhang99 approved these changes
Hi Haohui,

I've tested this PR with the volunteer role and the manager role, and they both worked as expected. 

Volunteer: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/227d3d52-e428-40ad-870f-1af8afabc76b

Manager: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/646a1a2a-fe30-4d96-8864-e62f085d4213

2024-01-23 00:57 UTC, Renanluizssx approved these changes
Hi @Lin1404, i tested your application both manager and volunteer, and they are working very good.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/c3ff544e-284e-46b2-bacb-f1348af91650

2024-01-24 22:08 UTC, SRamen1999 approved these changes
This PR works as intended. I used an owner account to give a volunteer account permission to edit tasks for projects. One improvement I suggest is to make the permission list collapsible so it is easier and cleaner to find certain permissions. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/1b4ae46d-be49-4275-ab5f-3f9397093461

2024-01-27 01:46 UTC, nathanah requested changes

2024-01-27 01:46 UTC, nathanah commented on src/components/Header/Header.jsx
> +  const canUpdateTask = props.hasPermission('updateTask') || props.auth.user?.permissions?.frontPermissions.includes('updateTask');
```suggestion
  const canUpdateTask = props.hasPermission('updateTask');
```
Invividual permissions are checked through `props.hasPermission()` in addition to role permissions.

2024-01-27 03:33 UTC, one-community commented
Thank you all, moving to final review.

2024-01-28 17:39 UTC, navneeeth approved these changes
Hello, @Lin1404!

I reviewed your PR for Volunteer and Manager roles and the implementation works as expected. I appreciate that you have maintained the 'Edit User' permission set to default for a Manager role. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/b6d6f868-6e15-478f-94af-b14128b57866


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/0adc0ea1-a150-4799-9575-c2baf1f338d3



I am approving this PR as it is ready to commit once you address @nathanah's requested change in the canUpdateTask permission check. Thank you!

2024-02-02 22:23 UTC, merged