Xiaow TimeEntryForm refactor
OneCommunityGlobal/HighestGoodNetworkApp pull request #1744
Opened 2023-12-23 11:11 UTC by wang9hu

# Description
Please include the exact bug/functionality description and a summary of the changes/ related issues. Please also include any other relevant motivation and context:
Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ task→…
6. verify function “A” (feel free to include screenshot here)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2023-12-28 16:52 UTC, ChengyanOo commented
> # Description
> This is the refactor of TimeEntryForm, TimeLog and TimeEntry along with related files.
> 
> ## Related PRS (if any):
> To test this frontend PR you need to checkout the #[668](https://github.com/OneCommunityGlobal/HGNRest/pull/668#issue-2054757181) backend PR. …
> 
> ## Main changes explained:
> * Restructure format of files, favoring destructure assignment, redux state management, and code categorization arranged in a centralized manner
> * Add WBS and task names in the project/task selection for both TimeEntryForm and TimeLog
> * Add wbs in state.userProject reducer for better data handling
> * Add wbsId and taskId to timeentry data for better data displaying
> * Refactor event handler logic
> * Disable outdated test files of these component, will overhaul those in the future
>   …
> 
> ## How to test:
> 1. check into current branch
> 2. check into #[668](https://github.com/OneCommunityGlobal/HGNRest/pull/668#issue-2054757181) backend PR.
> 3. do `npm install` and `npm run start:local` to run this PR locally
> 4. Clear site data/cache
> 5. log as admin/vol user
> 6. Test the five use cases of TimeEntryForm below, try to break it.
> 
> ## Screenshots or videos of changes:
> ## Note:
> * userProfile, userProjects and userTask reducers are solely for storing data displaying on page (not logged in user, this is important).
> * There are five use cases of TimeEntryForm component
> 
> 1. Account Owner (not owner account) user logs new time entry from Timer to Account Owner: edit is false, fromTimer is true, isTangible is true;
> 2. Account Owner adds time entry from 'Add Intangible Time Entry' button to Account Owner: edit is false, fromTimer is false, isTangible depends;
> 3. Account Owner with permission adds time entry from 'Add Intangible Time Entry for XXX' button to XXX user: edit is false, fromTimer is false, isTangible depends;
> 4. Account Owner edits same day time entry of Account user: edit is true, fromTimer is false, isTangble depends;
> 5. Account Owner with permission edits existing time entry of other user: edit is true, fromTimer is false, isTangble depends;

Hi @wang9hu,

I'm in the process of testing the feature and would appreciate some additional guidance. Could you clarify the meaning of "edit is false, fromTimer is true, isTangible is true"? Specifically, I need to understand how these boolean values impact the feature's functionality. Also, could you advise on the best method for verifying these values? For instance, is inserting console logs in the TimeEntry.jsx file the recommended approach, or is there another preferred method for this verification?

2023-12-28 21:01 UTC, wang9hu commented
> I'm in the process of testing the feature and would appreciate some additional guidance. Could you clarify the meaning of "edit is false, fromTimer is true, isTangible is true"? Specifically, I need to understand how these boolean values impact the feature's functionality. Also, could you advise on the best method for verifying these values? For instance, is inserting console logs in the TimeEntry.jsx file the recommended approach, or is there another preferred method for this verification?

Hi @ChengyanOo, thank you for your suggestions on this! I updated the description a little and hopefully that will clear up some confusions. I removed the `isTangble` since it is less impactable comparing to the other two boolean values.

2023-12-28 21:10 UTC, ChengyanOo commented
> > I'm in the process of testing the feature and would appreciate some additional guidance. Could you clarify the meaning of "edit is false, fromTimer is true, isTangible is true"? Specifically, I need to understand how these boolean values impact the feature's functionality. Also, could you advise on the best method for verifying these values? For instance, is inserting console logs in the TimeEntry.jsx file the recommended approach, or is there another preferred method for this verification?
> 
> Hi @ChengyanOo, thank you for your suggestions on this! I updated the description a little and hopefully that will clear up some confusions. I removed the `isTangble` since it is less impactable comparing to the other two boolean values.

@wang9hu 
Thank you for your explanation!

2023-12-29 01:56 UTC, Alforoan requested changes
Everything works as intended except for editing (both when volunteer tries to edit and when the owner tries to edit the volunteer's.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/47655158-418d-4896-b750-dab50dcb2c0a

2023-12-29 17:24 UTC, ChengyanOo commented
@Alforoan 

Sorry that I accidentally re-requested a review for your PR review, didn't meant to do it

2023-12-29 17:29 UTC, ChengyanOo commented on src/actions/userProfile.js
Is it missing error handling near line 31-34?

2023-12-29 17:31 UTC, ChengyanOo commented on src/actions/index.js
Hi there! I noticed there's a section of code that's been commented out. Could you please add a brief comment explaining the reason for this? This would really help other developers understand the context behind this change. Also, if you're confident that this code won't be needed in the future, consider removing it to keep our codebase clean and tidy. Thanks!

2023-12-29 17:32 UTC, ChengyanOo commented on src/actions/userProjects.js
Is it missing error handling near line 23?

2023-12-29 17:40 UTC, ChengyanOo requested changes
Hi @wang9hu,

Great job on the refactoring of multiple React components! I've conducted tests on the features you implemented, specifically in the scenarios involving volunteer and admin roles, as you suggested. However, I encountered the same issue as @Alforoan.

Below, I've attached my complete server log and a video walkthrough of these features for your reference:

- **Video Walkthrough**: [Feature Test Video](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69735000/7f778581-d4d3-48dc-8a5c-d51f1dec2051)
- **Log File**: [HGNRest_pullReq_668_Dec29.log](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/files/13795234/HGNRest_pullReq_668_Dec29.log)

2023-12-30 08:55 UTC, bienzguoa reviewed
There is something wrong with the "Edit" function( for both volunteers and admins). Others work as intended!
Logged as vol:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/c14c34bb-d8b4-4a1f-b485-d8366792e420
Logged as admin:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/42ded897-7ead-4902-a491-cdcbbb863664

2023-12-31 05:30 UTC, wang9hu commented
Thank you all for the prompt feedbacks, @Alforoan @ChengyanOo and @bienzguoa!

I have fixed the issue and made some changes according to those feedbacks. Please take another look at it and let me know if there is more bugs.

2023-12-31 05:31 UTC, wang9hu commented on src/actions/userProfile.js
Error handling added in the latest commit.

2023-12-31 05:31 UTC, wang9hu commented on src/actions/userProjects.js
Error handling added in the latest commit.

2023-12-31 05:37 UTC, wang9hu commented on src/actions/index.js
That action creator is for one reducer that is not included in our current store. It is only connected to one file that has only one reducer, which is not being used anywhere else, either.  Also it hasn't been changed in 4 years. So I think it is safe to just delete them and if we need similar functionality, it won't be hard to add it later.

2024-01-03 04:32 UTC, one-community commented
Thank you all, merging!

2024-01-03 04:32 UTC, merged