Read-only HOC make non-editable task view obvious
OneCommunityGlobal/HighestGoodNetworkApp pull request #1745
Opened 2023-12-24 03:32 UTC by GKD890

# Description
<img width="714" alt="Frontend_Task143_PR_description" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/57503876/bec062f8-9fb6-4faf-b33a-97aa3d7c4dcd">

Fixes 16 in **PROJECTS/TASKS/WBS COMPONENT** (medium)

## Related PRS (if any):
This frontend PR solves the problem the same as in #860. However, I chose a better solution for better review experience and remove unnecessary refactoring.

## Main changes explained:

1. Created a HOC(Higher Order Component) to wrap sections in `TaskEditModal` and determine Now in Task View, users who only have **view** permission (e.g. Volunteer user) can only see the contents rather than some inputs .
2. Make the fields in `EditTaskModal` in the Wrapper as much as possible, or disable the input to make the style obviously non-editable for those who only has **view** permission.
3. Add a **disable** to the props of **TagsSearch** component to disable the input.

## How to test:

- check into current branch
- do `npm install` and `npm run start:local` to run this PR locally
- You need to login as a role that **DOES NOT** have either **suggest** or **edit** permission (not volunteer). You can do this by creating a new role.

- go to dashboard→ Click any task in **Task** tab -> click **View** button to see the details of each task.
The fields that user can't edit should be obvious. Clicking any button won't make changes to the filed.

Also log as **admin** or **manager** , they have either **edit** or **suggest** permission, so the fields can be edited and has `update` button. Also try if **Add Task** button can show the Modal properly.

## Screenshots or videos of changes:
<img width="1023" alt="Screenshot 2023-12-23 at 22 27 57" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/57503876/7d1d2a09-3e73-4038-b423-e478ff0721c6">

## Note:
### 2. If you don't have an Owner account, see below.
- you can modify the file `src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx` to remove permission
**! I don't recommend to do so though**
<img width="487" alt="Screenshot 2023-12-23 at 22 16 08" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/57503876/35792035-a73a-4e8a-802e-516456b79de5">

2023-12-24 06:03 UTC, Alforoan submitted a review, later dismissed
I tested using a core member account and admin account and everything works as intended. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/08106b1f-6d57-4c5d-b809-b34ee66107a6

2023-12-27 21:41 UTC, ilyaflaks approved these changes, later dismissed
I tested this PR and found that it works as described and looks very good too!
I confirmed that in "development" branch the fields are editable and there is no UI that would suggest that they are not. 
I assigned one of my test accounts a role "PR1475Tester" (Thank you to whoever created it and named it so clearly), opened an arbitrary task (id 60287d1ffcd5d10017d08833 pictured below) and pressed "View"
<img width="1259" alt="PR1745-grayed" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/0455172f-f705-4a0e-96be-93d03ce0db91">
I think it would be obvious to most web users that the gray fields are not editable. 
I double checked that the fields are editable from the owner account: 
<img width="1256" alt="PR1745-editable-by-owner" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/75a8b982-3980-428f-99da-d5ca2e5a01b0">
Also, there were "update" and "cancel" buttons available for the owner, but that was there before this PR. 
Great work! Very elegant solution with the ReadOnlySectionWrapper and the "editable" state for the input components. The only line of code I disagree with (or don't understand) is this one: 
<img width="1352" alt="PR1745-value" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/a294c76f-8b07-4740-8f2e-4ced15188084">
As far as I know, the state variable that is being set by the onChange function should be assigned to the "value" property. In this case it's "assigned". That way the React state is the source of the truth. This only gets buggy on text input components and not "radio" buttons, so not a big deal.

2023-12-27 23:24 UTC, ChengyanOo requested changes
Hello @GKD890,

Excellent work on the implementation of the Higher-Order Component (HOC). I've certainly gained new insights from reviewing your code. I conducted tests using various roles including testRole, Admin, Volunteer, and Manager. I'm pleased to report that the feature has been implemented effectively and functions smoothly across these different roles. For a more detailed walkthrough, please refer to the attached video.

**I did notice a couple of minor points that might be typos. Could you please take a moment to review them?** 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69735000/8b0a0fe6-ccc2-4c2b-aec6-d92f33f1dd58

2023-12-27 23:24 UTC, ChengyanOo commented on src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
Should line 21 be deleted?

Plus line 59 was a nice refactoring!

2023-12-27 23:24 UTC, ChengyanOo commented on src/components/Projects/WBS/WBSDetail/EditTask/ReadOnlySectionWrapper.jsx
line 15-19 is a great implementation!

2023-12-28 15:52 UTC, GKD890 commented on src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
<img width="836" alt="Screenshot 2023-12-28 at 10 27 02" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/57503876/4b83cd8e-9f5c-4cf6-a019-13cce883ce16">

I commented out ESLint and Prettier when editing the file, it seems this is auto fixed by ESLint shown in screenshot, please check new commit ( only 2 lines are changed, thus if you can approve based on that, it would be helpful)
Thank you for pointing that out, including other typos (some are fixed by ESLint)

2023-12-28 15:57 UTC, GKD890 commented
# Update
Fixed some style issue ( 2 lines), see new [commits](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1745/commits/77eb7406d53f5c7b9b590acf8c65f7f91dd0bbad), it shouldn't affect functionality.

2023-12-28 16:22 UTC, ChengyanOo approved these changes, later dismissed

2023-12-28 16:23 UTC, ChengyanOo commented
> # Update
> Fixed some style issue ( 2 lines), see new [commits](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1745/commits/77eb7406d53f5c7b9b590acf8c65f7f91dd0bbad), it shouldn't affect functionality.

@GKD890,

Excellent work on the implementation of the new feature, and I appreciate your diligent updates!

2023-12-28 16:37 UTC, GKD890 commented
> > # Update
> > Fixed some style issue ( 2 lines), see new [commits](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1745/commits/77eb7406d53f5c7b9b590acf8c65f7f91dd0bbad), it shouldn't affect functionality.
> 
> @GKD890,
> 
> Excellent work on the implementation of the new feature, and I appreciate your diligent updates!

Thank you so much for quick response and approval

2023-12-30 14:25 UTC, mianmiantea2019 commented
Hello @GKD890,
I've tested this PR, and everything appears to be working as expected.

-  a user role without suggest or edit permissions

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/cad3d7a2-2920-446f-be93-2aa6e7340d1a

- a user role with suggest or edit permissions

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/4ae733e6-de4b-4be5-9c25-677bf12bb27e

2024-01-06 20:51 UTC, Haoxiang310 commented
I've tested the pr through a new role without edit or suggest permission, and owner role with edit and suggest permission. Everything seems to work as expected. 
For the new role without edit or suggest permission:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/135764868/3cc27138-98b8-4815-8781-aee0ff126996

For owner role:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/135764868/5a41f2c3-a51e-4199-b1cc-b023d50ff887

2024-01-13 01:46 UTC, Sophie-lei approved these changes
I have tested the PR in both the user role, without update permission, and the admin role. In the user role, the edit button has disappeared, and there is no way for the user role to make changes. So the PR is working as expected.
but there is a notification that the update was successfully changed. I think this is confusing because the change cannot actually be completed. Please view the video for details. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/b6c7bdaf-f352-4115-8521-f0c435808960

For the admin role, the user can update the task as expected, and it can refresh the page with reloaded information. Please check the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/19396b92-378d-40cf-9440-150050a156ce

2024-01-15 03:57 UTC, pshereen approved these changes, later dismissed
I tested the changes

2024-01-15 05:05 UTC, one-community commented
Thank you all, moving to final review.

2024-01-15 05:14 UTC, one-community commented
Please make these just numbers instead of boxes that look like they are waiting for inputs. Then I’ll move this to final review.  
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/18335122/ae772244-0ac2-4a25-9265-9d05a3719cd4)

This one too, remove input box: 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/18335122/e3ebd08c-c7fd-4993-86c6-7bc482a83415)

Same with these, they shouldn't look editable: 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/18335122/93c6994d-e13e-40b4-aa44-0d0b1f14d7ad)

2024-01-18 19:53 UTC, keyunhuangg submitted a review, later dismissed
Created a new user role and verified that with all selected rows cannot be edited.
<img width="1188" alt="Screenshot 2024-01-18 at 12 30 14 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/fa8a6193-3d1f-4d44-996f-4db597ec6a02">

2024-01-19 21:40 UTC, Renanluizssx approved these changes, later dismissed
Hi @GKD890, i tested your application and it´s correct.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/19a0671b-b936-472b-9179-ef1dc43a1a16

2024-01-19 22:52 UTC, KevHnh approved these changes, later dismissed
I tested this PR and everything functions as expected, however, with a minor performance issue. I tested with an owner account and then made a new user with the role "PR1475Tester", and both function as described.

As seen in my recording, there is a noticeable delay when I click "Edit" on the owner account. It occurred occasionally during my testing (sometimes the edit window pops up instantly sometimes the delay occurs). I managed to figure out that after clearing my cache and local storage, the delay does not occur. Clicking view from a non-owner or admin account works smoothly. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/2b07e22c-88fe-4be0-9ab9-0e0c4bc51633

2024-01-20 06:06 UTC, Sophie-lei approved these changes, later dismissed
I reviewed this PR again because I could still see the edit button problem before. It turns out is because of the permission problem. I created an account with neither edit nor suggestion permission to test. it worked as expected. plz view the video for more detail.  I also test for admin roles and the sheet can be edited as expected as well.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/68281a54-ebfc-4c3a-a294-49934414d09e

2024-01-20 20:23 UTC, 666saofeng approved these changes
I tested with different roles. It works as expected.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/f22b21a6-4027-4ad0-811a-048d5bb0a470

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/4b0c39d5-1d1b-4285-8a1c-47f6f03ae309

2024-01-20 21:24 UTC, rusalshrestha98 approved these changes, later dismissed
Confirmed the following:
- Users with role "TestRole" could view the task
- Users with role "Manager" could view + edit the task
- Users with role "Admin" could view + edit the task
- Users with role "Volunteer" could view + provide suggestions to the task

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/48131438/264ccd3f-4b5c-47a5-bbb4-3a638236b05f

2024-01-20 22:00 UTC, xmyoot commented
Confirmed and tested by creating some Tasks and assigned them to Volunteer role, here the process of editing tasks as Admin role:
<img width="246" alt="Screenshot 2024-01-20 at 1 58 14 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15240538/b62597b6-9571-42be-9961-6cb12fb37647">

<img width="734" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15240538/42cf65e5-c0ab-438b-91c3-b2066d92d765">

2024-01-21 03:11 UTC, galgalinidhi commented
Hi @GKD890, I tested this PR for the PR1475Tester and Admin roles and it works! I could see a View button for the PR1475Tester account with no update button. The Admin account had an edit button as well as an Update button. 

<img width="1436" alt="1745testrole" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/36894eae-901c-47f1-942c-d715d622727d">

<img width="1436" alt="1745adminrole" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/ec8dd7c1-3aec-4c65-b927-8341d1d43294">

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/003026df-0c07-4207-b095-05394c1a7cdf

2024-01-22 17:57 UTC, X1aoZhang99 submitted a review, later dismissed
Hi Yubo,

I successfully tested the PR for both the PR1475Tester and Admin roles, and it functioned as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/1a6a88e7-e00e-4a6e-96ec-155eb4ab1e10

2024-01-22 18:45 UTC, SRamen1999 approved these changes, later dismissed
I tested this PR and everything functions as expected, The Admin role can view and edit the task. The manager Role can view and edit the task. The Volunteer role can view and provide a suggestion. The TestRole can only view the role. 

One thing I noticed is that the Admin role is the only account that has direct access to the projects with other links tab. All other roles do not.

You can see the Volunteer suggestion on the manager and admin accounts.
<img width="1717" alt="Screen Shot 2024-01-22 at 1 37 27 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/6130096d-edc0-4654-ba09-6b73cfc6f3e1">


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/10d8c72b-9c92-420e-92bd-2faaaa57d37d

2024-01-24 21:49 UTC, BaileyM96 approved these changes
Hello @GKD890 I tested your PR after the changes of the modal being more noticable that you cant edit it. Great work

## Videos


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/370b5f74-3017-4b41-9d6e-03d2e7121d22


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/28757a02-2758-4090-ab9a-c71c6bff2976


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/47c143d0-2043-40e5-8e33-a1d55215db89


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/070f28fd-51f1-4347-a195-6e5b92354466

2024-01-25 16:19 UTC, one-community commented
Thank you all, merging!

2024-01-25 16:19 UTC, merged