Cheng-Yun Members.jsx Unit Test
OneCommunityGlobal/HighestGoodNetworkApp pull request #1750
Opened 2023-12-28 06:10 UTC by DavidC0126

# Description
Implementation unit test fuctions for Members.jsx

## Related PRS (if any):
None

## Main changes explained:

- Create Members.test.jsx file for testing Members.jsx components 

## How to test:
1. check into current branch
2. do `npm install` and `npm test src/component/Projects/Members/Members.test.jsx` to run this PR locally
3. Clear site data/cache

## Screenshots or videos of changes:

![Screenshot 2023-12-27 at 10 10 12 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/0e109626-78c2-49f1-b7a1-d4c586da2818)

## Note:

2023-12-28 17:06 UTC, ChengyanOo commented
> 2\. `npm test src/component/Projects/Members/Members.test.jsx`

For anyone who will be reviewing this PR:

Please note that the correct command to run the test script for this PR is "npm test src/component/Projects/Members/Members.test.jsx". There was a minor typo in the previously provided command.

2023-12-28 17:45 UTC, ChengyanOo requested changes
@DavidC0126 

Great job on implementing the tests,  here's a picture of your triumphant tests:

![test successful](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69735000/36d5cbdb-2396-43c9-888e-5bdeac44bbff)

I must also commend you on the clarity and organization of your code – it's impressive!

_**While reviewing, I thought of a few additional test scenarios that could further enhance our coverage:**_

1. Member Deletion: It would be beneficial to include tests that simulate the deletion of a member. This can help us ensure that the deletion process works smoothly and the UI updates accordingly.

2. Toggle Button Functionality: Testing the functionality of the "Active" and "All" buttons could be really valuable. Specifically, observe how the UI and elements change when these buttons are toggled. This ensures our toggle feature is robust and user-friendly.

3. Edge Case Handling: Adding tests for edge cases like submitting a member with empty names or IDs could be a great addition. This can help us identify and handle any errors or unusual behaviors in the UI, enhancing the application's stability and user experience.

2023-12-29 01:56 UTC, Alforoan requested changes
I get this error in the screenshot.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/7734f77f-c06e-42b8-ae25-4691d4aad11c)

2023-12-29 01:59 UTC, ChengyanOo commented
> > 2\. `npm test src/component/Projects/Members/Members.test.jsx`
> 
> 
> 
> For anyone who will be reviewing this PR:
> 
> 
> 
> Please note that the correct command to run the test script for this PR is "npm test src/component/Projects/Members/Members.test.jsx". There was a minor typo in the previously provided command.

@Alforoan 

There was a typo in the path, please check out my comments.

2023-12-29 02:10 UTC, Alforoan commented
> > > 2. `npm test src/component/Projects/Members/Members.test.jsx`
> > 
> > 
> > For anyone who will be reviewing this PR:
> > Please note that the correct command to run the test script for this PR is "npm test src/component/Projects/Members/Members.test.jsx". There was a minor typo in the previously provided command.
> 
> @Alforoan
> 
> There was a typo in the path, please check out my comments.

Is that not what I typed in the terminal?
npm test src/component/Projects/Members/Members.test.jsx

2023-12-29 02:11 UTC, ChengyanOo commented
src/componenets

2023-12-29 02:13 UTC, ChengyanOo commented
> @Alforoan 
> src/componenets

Oops just noticed that I also used the wrong path, my bad.

2023-12-29 16:54 UTC, sahilpatel18 approved these changes
All test cases passed successfully. Great work! 
<img width="608" alt="Screenshot 2023-12-29 at 11 54 34 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/24741818/7a56d21d-810d-4494-8712-02b127904f9c">

2023-12-30 07:14 UTC, vikrambadhan reviewed
Hi, I tested your PR and all the test cases passed however, I got a few errors too

![Week 18 - PR1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/330eb456-b449-44be-9ebb-d95e47f5ab0d)
.

2023-12-30 07:31 UTC, Alforoan submitted a review, later dismissed
All tests passed. Nice!

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/13ae65e3-0475-4682-abc5-da154d61c984)

2023-12-31 00:00 UTC, ramyaram2092 requested changes
Hello @DavidC0126  Good job on the test cases 
1. Kindly move the test files under __tests__ folder as suggested in the unit testing slack channel 
2. Comma is missing at line 29,43,55  
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/d5e3e150-eccb-441a-9710-f0dfbdc2a777)
3. kindly remove  comments  that are not needed

2024-01-07 01:02 UTC, bienzguoa reviewed
Hi, all test cases passed, but i got these errors related to network and environment. 
<img width="1087" alt="Screenshot 2024-01-06 at 5 00 39 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/42030181-aea7-4d6b-9778-553c922e4edc">

2024-01-09 17:16 UTC, bajajtushar094 submitted a review, later dismissed
All test cases passed. Thanks 
![Screenshot 2024-01-09 at 22 45 38](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/a1ccff11-ea66-43bb-b33b-558ee883d1cd)

2024-01-13 03:15 UTC, sahilpatel18 submitted a review, later dismissed
All test cases passed successfully. Great work! 

![Screenshot 2024-01-12 at 10 15 32 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/24741818/3ee0b6ed-0441-4889-aac5-b5c980bb0f58)

2024-01-13 16:21 UTC, beblicarl commented
This test has errors in the console

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/602fccaf-96cd-4881-8fba-3a5816059ec3)

2024-02-06 02:52 UTC, 666saofeng approved these changes
Hi, I tested, and there were two tests that failed. Please refer to the image for details.[image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/c05441ee-0cc6-4055-bf3f-e19b200693b1)

2024-02-06 02:54 UTC, 666saofeng requested changes
Hi, I tested, and there were two tests that failed. Please refer to the image for details.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/102347e6-5259-4e00-a2e0-761a0be46fec)

2024-05-17 05:57 UTC, KaushikMreddy commented
Hi, 

Some of the test cases have failed. I've pasted the errors below.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/feab3a1d-51bf-4b4a-b483-d30b084c990b)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/98a27ecd-eef4-48bb-8a34-678ecb91a7d9)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/2241c53f-89dc-41f5-85c6-f7ac6458efa1)

2024-06-01 22:34 UTC, Sandhya1236 requested changes
I attempted to test the unit test cases for the TimelogNavbar component and the Members component. While the TimelogNavbar tests were successful, the Members component encountered issues. The test for toggling the showActiveMembersOnly state failed because the expected length of members was incorrect, with an expected value of 1 and a received value of 2. Additionally, the test for triggering the assignProject function for all found users failed because the function was not called, with an expected number of calls being greater than or equal to 1 but receiving 0. These issues need to be addressed to ensure the correct functionality of the Members component. The remaining tests were successful, confirming the functionality of other components under various scenarios.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/9e66c3e9-9593-46c1-885b-040309a41259)

2024-08-16 02:43 UTC, SatyashanthiT approved these changes
I reviewed PR 1750 by checking out the current branch, installing dependencies, and running the unit tests for Members.jsx. The Members.test.jsx file correctly tests the component, and all tests passed successfully. 
<img width="956" alt="image" src="https://github.com/user-attachments/assets/2bce74dd-1687-4dcc-ad10-295e6a17c41e">

2024-08-17 23:44 UTC, adityasure9 approved these changes
I have reviewed the PR by checking out the current branch, installing dependencies, and running the unit tests for Members.jsx. The Members.test.jsx file is correctly set up, and all tests passed successfully. The implementation is solid, and I encountered no issues during testing. Great work on this! Thank you.

![image](https://github.com/user-attachments/assets/6c77e8d9-ff52-40d5-a271-e2dfd9c1a4ef)

2024-08-25 04:22 UTC, oliviahyw approved these changes
I have tested this PR and all test cases were passed. Great job!
<img width="902" alt="PR1750" src="https://github.com/user-attachments/assets/ccd8358e-583f-4cee-9a5f-d87bc8b83e50">

2024-11-02 03:10 UTC, VMD281 commented
Hi! I have tested this PR and all test cases were passed. 
<img width="1049" alt="#PR1750_1" src="https://github.com/user-attachments/assets/b3d7233f-df25-4cf9-a1df-9d7961abd548">
<img width="1049" alt="#PR1750_2" src="https://github.com/user-attachments/assets/5ec53d9b-47ca-495c-a56b-a16097ad5d58">

2025-05-16 02:53 UTC, closed without merging