Shantanu Unit Test for Setup Final Day Popup
OneCommunityGlobal/HighestGoodNetworkApp pull request #1762
Opened 2023-12-30 22:35 UTC by n0vay

# Description
Unit test cases for Setup Final Day Pop-Up Component

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3.  run `npm test SetUpFinalDayPopUp.test.jsx`
4. Check if all test cases pass

## Screenshots or videos of changes:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85691749/4ff04259-bcd5-4232-b7b0-966a209112ad)

## Note:
Include the information the reviewers need to know.

2023-12-30 23:10 UTC, KurtisIvey requested changes
1. Please restructure the component to follow file structure convention standards. 
   it will need to be within its own component folder <a>https://docs.google.com/document/d/1-SMFLeoBoJhn8FUas5oLkofYoLTRM-Tz1HfjZ0gbBuk/edit#heading=h.m9b033294wic</a>
   
   Though I know it's not your fault for the component not being within its own folder, it will be necessary for approval.
   
2. create a test to ensure ModalHeader is rendering properly
3. create additional tests to handle bad date input such as empty string, invalid date format
4. create a test to ensure nothing happens when props.open is false
5. add test for onClose to ensure close is functioning

2023-12-31 00:52 UTC, bienzguoa reviewed
All tests passed and rendering correct. Please add additional tests for handling bad data input and other props like Kurtis mentioned above.
<img width="752" alt="Screenshot 2023-12-30 at 4 50 48 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/163ffda3-ef8b-4671-a037-9bf03a77dd7a">

2023-12-31 01:56 UTC, Alforoan approved these changes
All passed. Nice!

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/8a873444-4707-4af3-bf93-06ae3dab8b0f)

2023-12-31 03:26 UTC, AaronPersaud approved these changes
Hi Shantanu (@n0vay), I have tested and all of the tests have passed. Well done.

<img width="840" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/d0788183-defd-4c71-a070-0eba02fb74b8">

I believe Kurtis made some good suggestions, so it wouldn't hurt to add those as well.

2023-12-31 06:07 UTC, ramyaram2092 reviewed
hello @Shantanu good job on the unit test cases . 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/54069fd9-290a-409d-842b-fe809c4743a8)

2024-01-07 07:27 UTC, vikrambadhan reviewed
Hi, I tested your and encountered these errors.

![Week 19 - PR6](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/2a258663-eec6-4964-b676-1bcf7029478a)

2024-01-10 19:15 UTC, ChengyanOo requested changes
Hi @n0vay,

I noticed that one of your tests failed during the execution. I've attached a screenshot to illustrate the specific issue. Let's work together to identify and resolve the cause of this failure.

<img width="904" alt="Screenshot 2024-01-10 at 14 12 59" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69735000/addfe576-50a8-4296-829e-797e8ac296b9">

2024-01-13 03:12 UTC, sahilpatel18 approved these changes
Unfortunately, the passing of one of the test cases has failed.

![Screenshot 2024-01-12 at 10 09 36 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/24741818/f1f536d9-26bb-43a3-bba8-127928afa7bf)

2024-01-28 03:49 UTC, 666saofeng approved these changes
All tests passed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/1445cd0e-3695-4902-9624-88456dc2b5dd)

2024-01-28 03:55 UTC, 666saofeng requested changes
1 test failed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/4463c6c2-0e02-4459-8d8c-c48f160505ed)

2024-02-07 17:46 UTC, X1aoZhang99 requested changes
Hi Shantanu,

There is an error, and the test failed. Please refer to the image. 

![Screenshot 2024-02-07 at 12 43 11](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/1ea96137-82e6-4c8f-b823-676056f39c85)

2024-02-14 17:39 UTC, peterson337 requested changes
One of your tests failed and four passed.

![a](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/3d31386c-203e-435f-8307-663c53b6fb8d)

2024-03-01 05:47 UTC, XiaohanMeng requested changes
Hi, there’s one test case not passed and others passed.
![PR1762-result](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/408c118c-e594-4802-8464-299a4164a98f)

2024-03-02 03:19 UTC, FyisFe requested changes
One test failed.

<img width="800" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59299011/f266f67e-4529-4d73-a126-eeeff836c9df">

2024-03-02 03:19 UTC, FyisFe commented on src/components/UserManagement/SetUpFinalDayPopUp.test.jsx
> +    fireEvent.change(screen.getByTestId('date-input'), { target: { value: '2023-12-31' } });
This test failed because `2023-12-31` is not a future date now, you'd better use date like 2100-01-01 instead of a close date.

2024-03-06 03:28 UTC, Pandani07 requested changes
One test failed

![Screenshot 2024-03-05 at 7 28 03 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/54635893-70ca-4a9e-99a3-d8d4c9be5eee)

2024-04-28 03:11 UTC, aaryaneil requested changes
Tested the PR and 1 of the test cases failed.
![Screenshot 2024-04-27 at 10 09 53 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/fff3d3fa-91fe-4ed4-957e-8634d23b7b19)

2024-05-17 05:48 UTC, KaushikMreddy commented
Hi, 

There are errors in your test, 1 test case has failed, please check
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/d17398ec-daed-4502-87cd-1d16cad80ae5)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/fea1f1b0-8c6b-4a0c-bee6-dd92c1f09c6a)

2024-05-19 17:29 UTC, closed without merging

2024-05-19 17:48 UTC, dkn6 requested changes
I have encountered an error and have attached a screenshot for your reference.

<img width="919" alt="test" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/168319518/c6d6f9a3-ea0c-4e52-84d8-8d7d0f9afc96">