Shivansh adds permissions rechecks
OneCommunityGlobal/HighestGoodNetworkApp pull request #1765
Opened 2023-12-31 05:44 UTC by shiva2096

# Description
![Screenshot 2023-12-30 at 9 10 37 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/a47fcc6e-72c5-4949-bb1e-e7599615fda0)

## Related PRS (if any):
N/A

## Main changes explained:
- **Added permission check in DeleteTeamPopup.jsx**
Authorized and Unauthorized User DeleteTeamPopup preview:
<img width="350" alt="Screenshot 2023-12-30 at 9 02 45 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/1f79b701-d498-45c0-8ea7-3854ef3759fc">

<img width="350" alt="Screenshot 2023-12-30 at 9 01 59 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/a3a71db3-a511-449e-8a3f-3dc772326875">

- **Added permission check in DeleteUserPopup.jsx**
Authorized and Unauthorized User DeleteUserPopup preview:

<img width="350" alt="Screenshot 2023-12-30 at 9 00 50 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/214a39db-0c5a-471e-a8d8-3b90ff5541b9">

<img width="350" alt="Screenshot 2023-12-30 at 9 00 11 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/d8b15bd8-239a-486b-af2b-ba5c07005717">

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally 
3. log as admin user
4. **Check User Delete functionality**
4.1 Create a new user 
4.2 Now check if you are able to delete this user
4.3 If you are able to delete the user without any issues, this functionality is working as expected.
5. **Check Team Delete functionality**
5.1 Create a new team 
5.2 Now check if you are able to delete this team
5.3 If you are able to delete the team without any issues, this functionality is working as expected.

## Screenshots or videos of changes:

Changes explained above

2024-01-02 05:02 UTC, Alforoan requested changes
As you can see by my video, creating and deleting user works as intended, but not for the team.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/7881e5db-8c6a-4d7a-b597-8566424e23b7

2024-01-05 16:49 UTC, ChengyanOo requested changes
Hey @shiva2096,

I've just tested the new feature you implemented. While the user deletion function seems to be working fine, there appears to be an issue with the team deletion functionality – similar to what @Alforoan experienced.

I've included a video here that demonstrates the bug in more detail for your reference. Please have a look when you get a chance.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69735000/df22be9f-e01a-4439-8d82-b8ad7193e844

2024-01-07 07:44 UTC, bienzguoa requested changes
Hi, it works for users. But it doesn't work when creating teams.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/0d9c97a5-fefe-4fdd-9982-3ce5d4ca1c16

2024-01-08 02:24 UTC, shiva2096 commented
@one-community 
Hi Jae,
A new bug has been identified through this PR, **we are not able to created a new team**, even from the development branch.

2024-01-13 07:18 UTC, one-community commented
> @one-community Hi Jae, A new bug has been identified through this PR, **we are not able to created a new team**, even from the development branch.

This has been fixed. Please re-review this.

2024-01-15 06:51 UTC, Hemsharavanan approved these changes
I am able to create and delete both users and teams successfully. Check the below video. Functionality works as expected. Great work!

Delete User:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/28252459/9b124544-3bb8-4c15-823a-34d08ab3b441

Delete Team:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/28252459/60403be3-0fdf-472d-9768-96fd5f3f44ee

2024-01-16 01:24 UTC, Chuehleo requested changes
The delete user works perfect, but I was unable to create a new team and delete it
Delete user:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/0307e09a-9cb9-491f-87ee-323682e32dc7

Delete Team:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/f7826c75-8834-4fbe-9edf-2ffb89271320

2024-02-07 19:20 UTC, X1aoZhang99 requested changes
Hi Shivansh,

I have tested the PR with the admin user, I can create and delete the new user, but I can't create as well as delete a new team. Please refer to the video. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/3fe73b6c-0cce-47ca-9542-970df4ecc919

2024-02-17 02:22 UTC, XiaohanMeng requested changes
Hi, I tested this PR. Using my admin account, I was able to add and delete users smoothly. However, I encountered issues with team management. After creating a new team, the team could not be found and disappeared after reloading the page. Please refer to the attached video for details. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/e5db0366-500b-4aec-97dc-d53743d5391f

2024-02-17 06:09 UTC, Jingyii800 requested changes
Hi @shiva2096, I successfully created and deleted a new user. But I was not able to create and delete a new team. Please check more details in my video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/a4e8501a-d09d-4fcf-b642-83982e78a01e

2024-02-17 22:25 UTC, brandta-1 requested changes
# Review
I was able to successfully create and delete a user. However I was not able to immediately create and delete a team. I would recommend updating the branch (pull latest from development). From there the team creation should work. Team deletion worked after manually creating a team on this branch (screenshots below).

# Videos

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/01c07b36-38d2-4cec-ba12-d4c4dd68b6e9

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/3c2422ad-9d29-4b17-a923-eec738b2bd2e

![response](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/40279732-1cdc-4a6c-96e9-0e02f80e4db2)

![console_log](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/b1e6fd97-27dc-43e1-a3cb-f379e6dcc65e)

![status undefined](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/16b542d2-f975-491c-adc0-eb5a235c5efc)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/12bb1998-685f-480e-8a1f-0d5580665c80

2024-02-22 00:17 UTC, skaush21 requested changes
- logged into owners account -> other links -> user management 
- created a new user account, deleted the newly created account - feature works
- then went to other links-> teams, attempted to create new team, got notification of team created, could not find created team. 
- deleted a team (created from an unrelated PR)
There is a problem with creating teams, new teams do not appear in the list of teams.
However, users can delete existing teams.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/42fc6e50-43a4-45a1-885b-416b55823400

2024-02-23 23:31 UTC, Weiyao-Li commented
So users portion works fine. But I cannot search to find the team I created, leading to that I cannot delete a team that i cannot search.


<img width="1728" alt="Screenshot 2024-02-23 at 18 27 43" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/9ad915bc-1d82-4294-8c56-59a5cdea2efa">
<img width="1728" alt="Screenshot 2024-02-23 at 18 30 36" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/dfd1633f-ee1d-4228-bd87-c15773ed5195">
<img width="1728" alt="Screenshot 2024-02-23 at 18 27 26" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/12a828b4-d901-46c6-afb1-60f4039e6105">
<img width="1728" alt="Screenshot 2024-02-23 at 18 27 18" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/cef6cb24-da44-4b0c-bc6e-eb6ee22d8182">
<img width="1728" alt="Screenshot 2024-02-23 at 18 27 15" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/17412623-b4be-4257-9efe-08da066d0dc8">

2024-02-24 06:22 UTC, shiva2096 commented
Because there have been a lot of changes since this PR was created, I had no other option that to recreate a new PR with new changes. Please perform the testing on the following PR:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1989

 @ChengyanOo @Weiyao-Li @skaush21 @brandta-1 @Jingyii800 @XiaohanMeng 
 
 I apologize for the inconvenience.

2024-02-24 21:18 UTC, shiva2096 commented
This PR has become old and causing issues while testing. So I am closing this.
New PR created : https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1989

2024-02-24 21:18 UTC, closed without merging