Jay - Modify Badge Amount Permission
OneCommunityGlobal/HighestGoodNetworkApp pull request #1793
Opened 2024-01-08 23:06 UTC by Alforoan

# Description
This PR enables the user with the Modify Badge Amount Permission to be able to edit other users' badge counts on their profile pages. 

## Related PRS (if any):
This frontend PR is related to the [#]() backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Added a new permission lable for Modify Badge Amount.
- Added conditional logic so that delete and Featured checkbox are disabled for users with only the modify badge count permission.
- Added conditional logic so that the user is not able to lower the badge count below 1 so that he/she is not able to delete a badge on accident.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to Other Links -> Permissions Management -> Manage User Permissions -> Choose a user without badge management permissions such as volunteer or core team -> add Modify Badge Amount 
6. verify that user is now able to see featured button and is able to manipulate the badge count.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/99edf90e-b437-4c28-bd02-28e9fb71c1f7

## Note:
**Unmute the video**

2024-01-27 04:49 UTC, nathanah commented on src/components/UserProfile/Badges.jsx
> +              {(props.canEdit || props.role == 'Owner' || props.role == 'Administrator' || canModifyBadgeAmount) && (
```suggestion
              {(props.canEdit || canModifyBadgeAmount) && (
```
I'd would make it so admins/owners have the relevant permissions, but that's just me.

2024-02-06 21:32 UTC, X1aoZhang99 requested changes
Hi Jay

I tested your PR with owner and volunteer. All functionalities worked as intended. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/97e4db40-2051-4713-aca6-df7db5dc04b4

However, every time I logged in as the owner, then an error message was displayed in the console. For more details, please see the image provided below. 
### Image
<img width="1352" alt="Screenshot 2024-02-06 at 16 27 34" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/84a37029-b892-40e5-bb6b-19e4e7c3516a">

2024-02-18 05:54 UTC, mohabbasd approved these changes
Hello, I tested your PR and it works as instructed. Here are some screenshots for your reference.
<img width="1440" alt="Screenshot 2024-02-18 at 12 52 09 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/e4c9d3f7-b8a7-4b23-a399-3c83b8fbdff0">
<img width="1440" alt="Screenshot 2024-02-18 at 12 52 54 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/98099e5d-0240-4892-b107-b50a7d4617a4">
<img width="1440" alt="Screenshot 2024-02-18 at 12 53 05 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/574706ed-38b1-4cdb-9986-4874b0fec2aa">

2024-02-22 01:32 UTC, XiaohanMeng requested changes
Hi, I tested this PR using the owner and volunteer accounts, following your guidance, and it worked as intended. Here are my steps:
* The owner account granted permissions to the volunteer account.
* The volunteer account was able to see and click the ‘select ‘feature.
* The badge amount was successfully edited.
However, an error appeared in the backend terminal, as shown in the image. 
<img width="990" alt="PR1793+690_error" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/9371eda4-e93c-4f7d-a72f-8e2a8afef41f">

Please see the reference video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/50f9577c-b41b-415f-b30d-189f73983bff

2024-02-23 05:02 UTC, Jingyii800 submitted a review, later dismissed
Hi @Alforoan. The function works well; the owner role can permit other users to modify the number of their badges. However, I encountered error messages in the backend. It should be considered, though it didn't influence the function. 
<img width="518" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/cb9ee28c-dda3-4fc3-a240-517353b996e0">

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/a785bf85-2705-48e3-bac6-067dfbf517e8

2024-02-23 23:20 UTC, Weiyao-Li commented
Great work. I followed exactly of your steps. It works by being able to add or decrease number of badges and then save changes. Thanks. Please see my screenshots for more info
<img width="1728" alt="Screenshot 2024-02-23 at 18 19 44" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/b00a3706-2b3a-4d12-ab98-0fa367d97b51">
<img width="1728" alt="Screenshot 2024-02-23 at 18 18 48" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/e7aa1b55-b139-43ed-a2ad-318b4c8bae56">
<img width="1728" alt="Screenshot 2024-02-23 at 18 15 56" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/343459fc-2ebf-46bb-a7ec-f272d076d9a1">

2024-02-25 05:45 UTC, ClemarNunes requested changes
I tested your PR and it worked as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/628b624a-6f72-4c85-a918-52bb8f988571

however, an error message appeared in the backend.
![error](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/546a0530-12fa-44d9-9fbb-90555b08aace)

2024-02-26 15:58 UTC, Gugor99 requested changes
### Report
Hello Jay, 
I checked out your implementation and I had some issues. My steps were: log in as owner, change permissions to my volunteer account, log out and back in as volunteer and check on my testRole profile if I could edit the badge amount. Good news is I was able to see and interact with all the buttons and modal as expected, bad news is that the changes I tried to make wouldn't get saved. I was able to increase the number of badges from the modal, but once saved I had no icon displaying the amount of the badges and as I reopened the modal the badge's count was still at 0. Please see screenshots for reference.
### Screenshots
![Cattura3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/cdea1517-7d94-43dc-8fcd-d23e62fd07d7)
![Cattura5](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/8e8f8c98-e4c3-4491-afc8-3e98c2bb0f4d)
![Cattura6](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/37c2e487-b4de-4623-a4cb-956eac9b7acd)

2024-02-27 21:35 UTC, psharma1984 approved these changes
Hi @Alforoan The code works as intended. I was able to chnage the badge count for the volunteer account and could sea the Featured button. Awesome !!!
![a](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/7e36baa1-1133-40e4-b8f6-6516b2c7ac6c)

![a](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/39f2cfc1-4099-4977-9113-952bc760ed60)
![b](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/c2ebffc2-20f9-435d-a53f-9bd448d25791)
![c](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/a51bd444-2000-4b59-9b65-b3331355dd10)

2024-03-01 16:58 UTC, skaush21 approved these changes
Modify badge amount
* logged in as owner, assigned permission ‘modify badge amount’
* logged in as volunteer, viewed profile, increased count for badges, saved changes
* count increased

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/393602da-b1cc-419f-addd-0fcd2eea886f

2024-03-02 17:09 UTC, MALAV1308 requested changes
Hello , I have tested your PR and it's working fine. But I got some error in console at backend. Please look into it and resolve it. Thank you.
![#690](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61341363/06719d4e-2b99-4178-adf5-1e3909fe1aff)
![#1793](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61341363/781317c4-1301-4d1e-80ad-2dfb13e9eb5f)
![#1793-1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61341363/8e7f897f-1263-41f5-960a-d8086d6fa4bc)

2024-03-07 06:34 UTC, Tiantian-C reviewed
Although the backend has some error, the frontend works well!
<img width="1437" alt="Screenshot 2024-03-06 at 10 32 15 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/e4bb3ad6-893b-4d73-83f9-c15012819412">

2024-03-08 01:03 UTC, SRamen1999 reviewed
I tested this PR using the owner and volunteer accounts, everything works as intended Using owner account I granted permissions to the volunteer account to change badge amount. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/794965f0-5bf7-431c-a2f8-7acc03e597d3

However I am getting an error on the backend. 

<img width="1467" alt="Screen Shot 2024-03-07 at 7 59 43 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/7b0f7dec-81a4-43e4-842f-153b01f34c61">

2024-03-16 11:53 UTC, Sarthak32 commented
It works as expected . I have tested your PR and it's working fine on the Frontend :
![Screenshot 2024-03-16 170221](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/e8395674-f2f4-42ea-bc1a-a424fa4847d5)
![Screenshot 2024-03-16 170541](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/eaba6370-c0eb-4a20-9149-4833c03a9017)
![Screenshot 2024-03-16 170604](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/e177b56f-4d6c-4245-9e73-7151c59be2dc)

2024-03-16 11:54 UTC, Sarthak32 reviewed
It works as expected . I have tested your PR and it's working fine on the Frontend :
![Screenshot 2024-03-16 170221](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/e8395674-f2f4-42ea-bc1a-a424fa4847d5)
![Screenshot 2024-03-16 170541](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/eaba6370-c0eb-4a20-9149-4833c03a9017)
![Screenshot 2024-03-16 170604](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/e177b56f-4d6c-4245-9e73-7151c59be2dc)

2024-03-21 06:37 UTC, hetvi11110 reviewed
As mentioned, I have reviewed the PR, and the Modify Badge Amount is working fine. However, the Edit Badge gives the same permission as the Modify Badge Amount. Here is the reference video to check it.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/73937908-caf9-4830-8442-32e519941537

Furthermore, I am also getting an error on the backend.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/d436d068-8947-479e-bee8-2fe92fceaafe)

2024-03-29 06:09 UTC, iven-yao approved these changes
Hi Jay, I just reviewed this pull request, following are the screenshots before and after granting the needed permission on a volunteer account. after granting the permission, the user could modify the amount of badges on other's user profile page as stated in the request. looks good.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/0eed7782-4875-43d0-94cc-50be4e8baf00)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/3dde5cc9-47dc-4e5a-a4a0-5a00750b8c3e)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/c5894653-141e-494a-a7d1-11ce1f8d249e)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/da760f97-b8b4-4bd0-aa8c-f3cb59927bba)

2024-04-03 21:12 UTC, kylepham requested changes
PR worked as intended. However, there are errors on the backend. Please see my [review](https://github.com/OneCommunityGlobal/HGNRest/pull/690#pullrequestreview-1978051604) for reference. 
![Screenshot 2024-04-03 at 4 01 45 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/03f0f53a-a740-46c0-943f-85b1c0333c7d)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/b8155e84-9b07-4620-930f-c3de4465dd82

2024-09-05 22:21 UTC, AJAYINAVOLU submitted a review, later dismissed
Changes are working as expected.

<img width="948" alt="PR 1793" src="https://github.com/user-attachments/assets/74b64d7c-ee97-47b0-83fe-99e327e61655">
<img width="947" alt="PR 1793_1" src="https://github.com/user-attachments/assets/4bbe5cda-58ac-4a1f-9842-04d9f12fc137">


Thank You

2025-06-28 17:11 UTC, boppanapraveen approved these changes
Thank you for the detailed guidance. I followed your steps exactly, and everything is working perfectly now. I'm able to add or remove badges and save the changes successfully. I've attached some screenshots for your reference.
![image](https://github.com/user-attachments/assets/66d64ea3-75e6-4e47-948d-10d97e6f463a)

2025-07-04 02:11 UTC, marcusyi1 requested changes
Made a test user and confirmed that user is now able to see featured button and modify badge amount. However, there are problems with the backend, please refer to the backend PR #690 for context
<img width="598" alt="image" src="https://github.com/user-attachments/assets/36f13a38-eb18-4009-8a69-0786732239df" />
<img width="530" alt="image" src="https://github.com/user-attachments/assets/1a2e4426-d5f0-4276-9932-a735faf96e6d" />

2025-07-05 07:43 UTC, shashank-madan reviewed
Good job, changes work as expected. Backend terminal encounters unintented errors. 


https://github.com/user-attachments/assets/f23c0147-3fe9-4b90-9c7f-a020618b8a3e

2025-07-10 00:05 UTC, saikrishnaraoyadagiri reviewed
Hi, After changing the permissions, saving is not working correctly as the call is in pending status in the network tab and seeing errors in the backend code.
![image](https://github.com/user-attachments/assets/7a17c584-3a4f-4dca-9dd7-ee439be66103)
for users with enabled badge count we are able to increase the count but the featured column is also enabled.
![image](https://github.com/user-attachments/assets/4347f5eb-df03-46fd-9358-de79de5d00aa)
backend errors 

![image](https://github.com/user-attachments/assets/7b3a8504-5a92-40f3-8c2a-f414527708ca)

2025-07-11 16:36 UTC, sphurthy reviewed
I was able to add Modify Badge Amount for a volunteer user. 
<img width="1322" height="628" alt="image" src="https://github.com/user-attachments/assets/91df1f20-fb29-42dd-9d61-a748c313ec8e" />
And as the user, I am also able to see the featured checkbox and modify the count.
<img width="1314" height="616" alt="image" src="https://github.com/user-attachments/assets/8363ee27-9bcd-4325-bd03-f49e83973aa5" />
Good work!

2025-07-14 20:32 UTC, Teja-Sri-Surya commented
✅ Successfully tested the Modify Badge Amount permission:

User with this permission can update badge count (minimum 1).

Cannot delete badges or toggle the “Featured” checkbox.

UI elements behave correctly based on permission.

Implementation aligns with the intended logic and provides a good safeguard against accidental deletions.
Well done! 👍
<img width="1724" height="867" alt="Screenshot 2025-07-14 152920" src="https://github.com/user-attachments/assets/2d2707bd-8a03-44fd-a477-7c9ebbc9a3dd" />
<img width="1895" height="878" alt="Screenshot 2025-07-14 152848" src="https://github.com/user-attachments/assets/0c047fb9-50fa-4626-90b0-8dcea86de3de" />

2025-07-19 03:02 UTC, Babu-kota approved these changes
The implementation of the Modify Badge Amount permission works well. I appreciate the safeguard to prevent badge counts from being reduced below 1 smart call to avoid accidental deletions. The conditional logic around disabling delete and featured options for users with limited permissions is also functioning as expected.

https://github.com/user-attachments/assets/6cfee896-0f35-4946-9ff8-4d7baee55b5b

2025-07-19 19:24 UTC, vamsidharpanithi requested changes
Tested the frontend functionality for the "Modify Badge Amount" permission. The assigned permission does not take effect, as the submit button in the Permissions Management page is not working, and the user is unable to access the badge count controls. This appears to be related to a backend issue preventing the permission from being saved or applied correctly. Please revisit this once the backend is fixed to ensure that the assigned permissions are properly stored and reflected in the user session.

<img width="625" height="308" alt="image" src="https://github.com/user-attachments/assets/c4aaddf8-d33b-4759-88d9-f47bdbc0a953" />

<img width="626" height="315" alt="image" src="https://github.com/user-attachments/assets/fe8c7a77-054c-4b15-a872-df8fad52f5ef" />

2025-08-21 05:04 UTC, sohamsharma08 reviewed
Logged in as an Owner and was able to change badge permissions successfully. Changes the permission of an account such that the badge permission is now available. Screenshots of the same as provided below:

<img width="1440" height="900" alt="PR 1793+690 (1)" src="https://github.com/user-attachments/assets/d7126016-4ee7-48da-b4f7-e54046cf2075" />
<img width="1440" height="900" alt="PR 1793+690 (2)" src="https://github.com/user-attachments/assets/a79e4723-5152-4226-8a53-e463c4f45c57" />
<img width="1299" height="709" alt="PR 1793+690 (3)" src="https://github.com/user-attachments/assets/36d726e2-d589-40d4-9cbe-65cf15c7e9be" />
<img width="1297" height="707" alt="PR 1793+690 (4)" src="https://github.com/user-attachments/assets/6121e41f-3ee7-4496-a276-2a128c8073cb" />

2025-08-21 05:04 UTC, sohamsharma08 approved these changes

2025-09-03 17:51 UTC, anirudhsk2107 commented
I have fixed the "canManageAdminLinks is not defined" error. Please review again.
@harshavarma29 @Venk-rgb @vamsidharpanithi @saikrishnaraoyadagiri @marcusyi1 @jaydeep138

2025-09-05 02:29 UTC, one-community commented
Thank you all, merging!

2025-09-05 02:29 UTC, merged