create a no records state for both purchase records and update record…
OneCommunityGlobal/HighestGoodNetworkApp pull request #1801
Opened 2024-01-09 23:49 UTC by this-journey

…s modal

# Description
Please include the exact bug/functionality description and a summary of the changes/ related issues. Please also include any other relevant motivation and context:
Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Related PRS (if any):
none

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. git pull
2. check into current branch
3. do npm install and npm run start:local to run this PR locally
4. Clear site data/cache in local storage
5. log in as any user
6. go to http://localhost:3000/bmdashboard/login to confirm your login credentials
7. go to http://localhost:3000/bmdashboard/materials
8. select "View" under "Purchases"
9. Verify that if no records are present modal reads "There are no purchase records"
10. select "View" under "Updates"
11. Verify that if no records are present modal reads "There are no updates to display"

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/fee3d265-9535-43bf-a575-60fc5dd54db5

## Note:
Use development branch for back end.

2024-01-20 20:47 UTC, keyunhuangg approved these changes
Check all 3 rows shown under updates and purchases that if no item is present then 'There are no purchase records.' under purchase record and 'There are no updates for this item.' under update records.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/938e25a4-5d80-4a70-a847-aa9fb3bfac11

2024-02-03 20:23 UTC, swathyjayaseelan commented
Works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/d9c975de-2568-4202-b56c-deb0bbe36c46

2024-02-04 02:18 UTC, 666saofeng approved these changes
It worked as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/1c96488e-b5a0-41a8-9c7d-21e16ca0c5d4

2024-02-06 00:38 UTC, X1aoZhang99 submitted a review, later dismissed
Hi Demi,

I tested the PR with the admin role, I can see both "There are no purchase records" and "There are no updates to display." Nice work! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/d1edffb1-8d69-48ab-8035-62eb6755a7e4

2024-02-13 16:19 UTC, peterson337 submitted a review, later dismissed
I tested your application, and everything worked as expected. Good job!

![one comunnity](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/a83096a1-4bb4-4275-9ea0-c0a1248e2bff)

2024-02-17 05:27 UTC, ClemarNunes submitted a review, later dismissed
I tested your PR and worked as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/9019a432-67c3-446b-bbba-dd3c85e46867

2024-02-18 04:14 UTC, mohabbasd submitted a review, later dismissed
Hello, I tested you PR and it works as intended, although I could see some updates done under someone else's name but purchase was empty. 
<img width="1440" alt="Screenshot 2024-02-17 at 11 13 27 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/27664ac1-7eaf-431d-a5e7-c6b0b1dce2e1">
<img width="1440" alt="Screenshot 2024-02-17 at 11 13 19 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/8a0879ec-67cb-46ab-af71-cedbb513f3e6">

2024-02-24 07:04 UTC, skaush21 reviewed
* logged in as admin user, went to bmdashboard
* logged in again, went to bmdashboard/materials
* clicked on each of the views for update and purchase
* all button display correct output.
* for updates, when clicking on the 'view' for the ones that have items, a warning appears in console. "Warning: Encountered two children with the same key"


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/56a4c594-4d3e-4898-9b11-b87f7b7e2b11

2024-02-28 23:49 UTC, XiaohanMeng approved these changes
Hi, the buttons worked as intended!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/4a569a7a-ad74-459d-af10-62080b9c37aa

2024-03-01 17:48 UTC, tdkent requested changes
The functionality works as expected. However, there are a couple issues: 

1. The Purchase Record "no records" text is not center-aligned. On line 104 of **RecordsModal.jsx** the `colspan` of the `<td>` element should be changed from `4` to `6` (see my inline comment).

<img width="666" alt="purch-rec-modal" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/a9474403-b5b0-4e89-8de9-c84fb49a6377"> 

2. Your version of **RecordsModal.jsx** is also based off an older version of the file that needs to be merged with the current version of the file in `development`. This is why the duplicate key prop error is appearing in the console when the modals are used (see my inline comment), an issue you already fixed in #1813.

2024-03-01 17:48 UTC, tdkent commented on src/components/BMDashboard/MaterialsList/RecordsModal.jsx
> +              <td colSpan={4} style={{ fontWeight: 'bold' }}>
This should be changed to `colSpan={6}` so the text can correctly center align.

2024-03-01 17:48 UTC, tdkent commented on src/components/BMDashboard/MaterialsList/RecordsModal.jsx
> +                <tr key={data.date.toString() + data.createdBy._id}>
This key prop should be using the `_id` field to remove the dupe key prop error

2024-03-01 17:48 UTC, tdkent commented on src/components/BMDashboard/MaterialsList/RecordsModal.jsx
> +                <tr key={date + requestedBy._id}>
This key prop should be using the _id field to remove the dupe key prop error

2024-06-25 06:14 UTC, one-community commented
Thank you all, merging!

2024-06-25 06:14 UTC, merged