Check Types Modal
OneCommunityGlobal/HighestGoodNetworkApp pull request #1802
Opened 2024-01-10 01:37 UTC by Vishala09

# Description
This PR implements a Modal to display the list of requested Types in the db such as Material , Equipment , Consumable , Reusable , Tool , and All. 
Or Implements # (WBS) 5.1.4

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.

## Main changes explained:
- Implemented component

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. Go to http://localhost:3000/bmdashboard/equipment/add
6. Test the Check Types button to see if it displays equipment data accurately. 

## Screenshots or videos of changes:

https://www.loom.com/share/2628f969342f4b1b90c2a3a6f7945eca

2024-01-10 04:54 UTC, tdkent requested changes
Off to a great start. A couple requests for the view:

- it's fine to also put the types list into a view in addition to a modal, but I think the URL path should be "/inventory", i.e. "/bmdashboard/inventory", and the types list itself "/bmdashboard/inventory/types".
- The view should have a header such as "Inventory: Types" or something similar.
- Change the modal header and/or add a snippet of text to make it clear the user is seeing a list of existing inventory types of a specific category.

2024-01-10 18:55 UTC, ChengyanOo submitted a review, later dismissed
Hi @Vishala09,

I've thoroughly reviewed and tested your implementation. It functions exactly as expected. For your reference, I've attached a video demonstrating the feature in action. Great work on this!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69735000/42101c17-498a-417e-8055-31037fe0ccb1

2024-01-10 20:42 UTC, Vishala09 commented
> Off to a great start. A few requests:
> 
Worked on the changes mentioned. Please find the video recording of latest changes here.
https://www.loom.com/share/c340a68734474d5b923b693258e8453f

2024-01-19 00:39 UTC, tdkent approved these changes

2024-01-19 19:21 UTC, merged