Jacob fix badge development checkbox
OneCommunityGlobal/HighestGoodNetworkApp pull request #1810
Opened 2024-01-11 17:57 UTC by DragonSlayer2401

# Description
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/43267ea4-d820-4ca5-b2a1-018c54b52cc8)

## Related PRS (if any):
N/A

## Main changes explained:
- Center checkbox
- Fix badge toggle 
- Remove the badge confirmation message

## How to test:
1. check into the current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log in as an admin or owner user
5. go to Other Links → Badge Management → Badge Development
6. verify the checkbox is horizontally centered
7. verify the confirmation message when toggling badges is gone
8. toggle off or on a badge
9. go to Reports → Weekly Summaries Report → Load Badges
10. verify only the toggled-on badges show

## Screenshots or videos of changes:
Before:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/d7712b0f-ee1f-46d5-94f3-4ff4495339c6

After:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/d37f28a9-276a-416f-b303-c2f06c9a267f

2024-01-20 11:17 UTC, Cavein254 commented
@DragonSlayer2401 
Tested this pr as admin and everything works as intended

- [x] verify the checkbox is horizontally centered
- [x] verify the confirmation message when toggling badges is gone
- [x] verify only the toggled-on badges show

![Screenshot from 2024-01-20 14-11-47](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/742d8a43-5e87-4181-91ef-9d4b0eb9310b)


![Screenshot from 2024-01-20 14-11-12](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/d2447d8d-588f-48be-b91c-1c398fcd494c)

2024-01-20 20:38 UTC, keyunhuangg approved these changes
The checkbox is centered, without message showing and all the badges are correctly displayed under weekly summaries report!
![Screenshot 2024-01-20 at 3 35 22 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/febb4d6a-2850-48ef-8810-bfda0184ae88)
![Screenshot 2024-01-20 at 3 36 42 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/b36db14a-8dad-487a-9013-3652b6ddc616)
![Screenshot 2024-01-20 at 3 37 05 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/eee0e469-dae9-4ccf-9372-561e70f55e61)

2024-01-23 22:39 UTC, Nahiyan-16 approved these changes, later dismissed
## Great work on this Jacob!
The checkbox is correctly centered.
The confirmation message box does not show anymore when toggling.
Badges display accordingly in the Weekly Summaries Report page.
Code is very well written but did leave a comment suggesting using a more descriptive variable name.

![Screenshot 2024-01-23 172340](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/1cd2cc77-ab4d-4a48-acb0-51e7419b0391)
![Screenshot 2024-01-23 172025](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/0dedadf4-43b8-420e-958f-02917f275b90)
![Screenshot 2024-01-23 171939](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/e4864921-3407-4ab0-8f3f-a8c5ccd49814)

2024-01-23 22:39 UTC, Nahiyan-16 commented on src/components/WeeklySummariesReport/FormattedReport.jsx
> +            {value && value.imageUrl && value._id && (
Awesome work on this but would it be better to use a more descriptive name in place for "value"

2024-02-01 00:14 UTC, X1aoZhang99 approved these changes, later dismissed
Hi Jacob,

I have tested your PR with owner user. The checkbox is properly aligned in the center. The toggle no longer triggers a confirmation message box. In the Weekly Summaries Report page, badges are displayed as expected. Please refer to the video. Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/204d1173-747b-4b3e-b46c-e068eb848718

2024-02-08 05:20 UTC, swathyjayaseelan commented
The checkbox is centered in normal screen size but when the screen size is reduced and becomes scrollable the checkbox position does not change with the container, as shown in the video below. The enclosing scrollable container should be given a style of "position: relative", so that the checkbox moves with it

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/0acf60a8-2dbb-4d74-8777-d44165be2815

2024-02-08 11:38 UTC, ShengjieMao approved these changes, later dismissed
Tested as admin user, all functions worked as expected:
no more confirmation message appear when toggling badges, 
checkboxes are horizontally centered,
toggling badges worked correctly,
and only toggled-on badges showed in the summaries report page

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/38944a23-24bb-41ee-a967-fd87b442fc83

2024-02-10 18:22 UTC, Pandani07 submitted a review, later dismissed
Tested this PR with my owner account and all the features work. When toggling badges the confirmation message does not appear, the checkboxes are horizontally centered , toggling badges and showing the badges in the summary report worked as well

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/3237e512-90dc-48b2-b254-42506432a51a

2024-02-11 06:11 UTC, galgalinidhi commented
Hi @DragonSlayer2401, I tested your PR and verified that the checkbox is horizontally centered, only the toggled-on badges are shown and the confirmation message for the checkbox doesn't appear. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/43a5d790-e2f5-4ec2-beea-bd5c5522bd61

2024-02-17 03:37 UTC, ClemarNunes approved these changes, later dismissed
I tested your PR and worked as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/0dff1fc5-853c-461b-a6e3-d55617e3c031

2024-02-17 07:11 UTC, mohabbasd requested changes, later dismissed
Hello, I tested your PR using the development branch as the backend, but the only thing which was working for me was the horizontally centered check box, I did not get any confirmation nor could I see the badges whether hidden or not.
<img width="1440" alt="Screenshot 2024-02-17 at 2 03 50 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/9c23c3c8-35b3-4dad-816f-dc7190b82531">
<img width="1440" alt="Screenshot 2024-02-17 at 2 05 08 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/788
<img width="1440" alt="Screenshot 2024-02-17 at 2 07 28 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/a04cd92d-de17-4ebb-8a8d-2ef4831046af">
c9635-c1f0-41a9-a39c-1d76dfd78c70">

2024-02-17 07:22 UTC, mohabbasd submitted a review, later dismissed
Hello, I tested you PR other than the pop up not showing up after checking or unchecking the box, everything works. Good Job.
<img width="1440" alt="Screenshot 2024-02-17 at 2 17 20 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/634d8108-31ab-4453-ae9a-1b3a323ea979">
<img width="1440" alt="Screenshot 2024-02-17 at 2 17 56 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/d8b7835b-499f-4395-99a2-5123b052c890">
<img width="1440" alt="Screenshot 2024-02-17 at 2 18 09 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/f16f01e9-d6b3-40e8-ae61-0b063e438a4c">
<img width="1440" alt="Screenshot 2024-02-17 at 2 21 18 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/2fe4e513-b989-4315-8297-e110425bb805">

2024-02-17 17:15 UTC, 666saofeng approved these changes
I tested with an admin account. The checkbox is horizontally centered, and there isn't a confirmation message when toggling badges. Only the badges toggled on show in the weekly report summary. LGTM. 
Please refer to the video for details.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/f8b48fb0-589e-4b59-83b2-feebaa1cc264

2024-02-17 20:34 UTC, XiaohanMeng submitted a review, later dismissed
Hi, I tested this pull request, and it worked as intended. The following aspects were verified successfully:
* The checkbox is confirmed to be aligned in the center horizontally.
* It is ensured that the notification message does not appear when toggling badges on or off.
* It is verified that only the badges that have been activated are displayed.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/6df5fd7a-294b-47bc-b7ed-2442e674ffa5

2024-02-18 01:25 UTC, one-community commented
Thank you all, moving this to final review!

2024-02-27 16:55 UTC, cvtqx requested changes
All the fixes work as described:

    Center checkbox - WORKS (but on large screen only)
    Fix badge toggle - WORKS
    Remove the badge confirmation message - WORKS

Badges before toggling some of them:

![Screen Shot 2024-02-27 at 11 42 37 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/7d26d3a9-c8d0-47fc-8f22-aad8217f3b26)

Same user after toggling some of the badges:

![Screen Shot 2024-02-27 at 11 43 55 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/cfafd8ec-e378-42c6-a6c2-cff16f5cf3e7)

However, the check box is not centered when the screen is smaller as mentioned by one of the previous reviewers. Please see video for details of testing and the issue.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/a4c4d5f8-2090-47f5-8435-6591dba39600

2024-02-28 21:10 UTC, one-community commented
Thank you all, merging!  Logged issues as a new request on the bugs doc.

2024-02-28 21:10 UTC, merged