Unit test for delete badge pop up
OneCommunityGlobal/HighestGoodNetworkApp pull request #1828
Opened 2024-01-13 21:42 UTC by belagaam

# Description

Unit tests for src/components/Badge/DeleteBadgePopup

## Main changes explained:

    New file
        DeleteBadgePopup.test.js : unit test cases

Test Case

<img width="977" alt="Unit test - DeleteBadgePopup - Test suit" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/321994e1-a004-421f-821a-94a88a78da04">

…

## How to test:

    check into current branch
    do npm test DeleteBadgePopup.test.js
    check if all the test cases pass

## Screenshots or videos of changes:

<img width="977" alt="Unit test - DeleteBadgePopup" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/b68e2a68-26c6-41c7-a9ab-8125e77c42e2">

## Note:
Kindly take a look at the test cases and suggest if more validations can be added

2024-01-13 22:56 UTC, Cavein254 commented
@belagaam, hi I am not finding this commit. I have tried `git pull` but your commit is not showing up
![Screenshot from 2024-01-14 01-53-57](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/dd14c4df-a51b-4850-99a9-7f52f5467af1)

2024-01-14 01:25 UTC, bienzguoa requested changes
It is well-structured and covers the essential functionalities. Suggestion: add test for behavior of the component with edge cases like null or undefined badgeId or badgeName props. Thanks!
<img width="765" alt="Screenshot 2024-01-13 at 7 21 19 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/d5e49733-ecef-486b-b1e1-4f104318cfe8">

2024-01-14 03:45 UTC, n0vay reviewed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85691749/9151b81e-78e0-4fb7-9d12-16befd6c9018)

2024-01-14 03:50 UTC, mianmiantea2019 commented
All tests passed.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/ccd5b293-bb75-41b2-9d3d-364c96aa5812)

2024-01-14 06:57 UTC, AaronPersaud approved these changes
Hi @belagaam, I've tested and everything passed! Well done.

<img width="833" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/e7400ef8-df0e-4607-ab18-8c47d5840fc1">

2024-01-15 06:29 UTC, bajajtushar094 approved these changes
Hi @belagaam, checked your PR and every test case passes. 
![Screenshot 2024-01-15 at 11 58 29](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/83524e19-002d-4b9b-b80a-1d96d0505d37)

2024-01-26 23:48 UTC, Lin1404 commented
Hi @belagaam , I have tested your PR and all cases passed.

<img width="761" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/49888408-988c-48b5-a002-aad3cba10ea8">

2024-01-26 23:48 UTC, Lin1404 approved these changes

2024-01-26 23:50 UTC, Lin1404 commented
Hi @belagaam  I have tested your PR and all cases passed.

<img width="768" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/ed246d94-ed4a-4735-b07e-c0b641a39365">

2024-01-30 19:48 UTC, 666saofeng approved these changes
All tests passed.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/5dc9787f-cc0a-40d7-a72d-1b7584747a46)

2024-01-31 13:14 UTC, X1aoZhang99 approved these changes
Hi Anirudh,

All tests passed. Nice work!

![Screenshot 2024-01-31 at 08 13 58](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/59ba3ce6-2cf5-403d-a04a-704806cfa7de)

2024-02-03 22:28 UTC, DragonSlayer2401 commented
I tested your PR and all of the tests passed as intended. Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/0b0dd05d-0b25-409d-ba67-d2f0ef8fbc90

2024-02-08 17:54 UTC, Pandani07 approved these changes
All tests passed. Did additional bug checking and explored features of the app, everything worked great.
![Screenshot 2024-02-08 at 12 53 15 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/18a0da0c-b2c6-41ba-aa18-33ac0f9860bb)

2024-02-13 05:16 UTC, mohabbasd approved these changes
Hello, I tested your PR and all the test cases have passed. Great job!
<img width="768" alt="Screenshot 2024-02-13 at 12 16 02 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/7995d831-787a-4c6b-badc-b37b71a50b1f">

2024-02-14 17:14 UTC, peterson337 approved these changes
Hi belagaam, all Tests passed. Good job!

![Capturar](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/419b653e-b2ac-4361-9f52-dccbf2ce8440)

2024-02-15 12:33 UTC, ShengjieMao approved these changes
All tests passed. Can find checks for all functions and buttons, etc. Great work
<img width="497" alt="PR_1828" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/fadc0449-c611-4f88-93b0-7e558885ae65">

2024-02-17 23:35 UTC, ClemarNunes approved these changes
I tested your PR and worked as expected.

![Captura de tela 2024-02-17 233308](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/db4236c6-7ac9-4250-8550-6fa62f37f6ac)

2024-02-19 19:05 UTC, dhairya-mehta commented
Hey, I reviewed your PR , all test cases passed!
<img width="1018" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56514777/1805c856-c989-4731-9e1f-dd7afed88c98">

2024-02-29 04:00 UTC, XiaohanMeng approved these changes
Hi, all test cases passed!
![1828_result](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/234877eb-7e77-4e91-b714-2ba04f9324ff)

2024-03-30 05:35 UTC, ramyaram2092 approved these changes
Looks good ! Good job on the test cases
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/bbe30386-b132-4e09-82f5-80a308b300a0)

2024-03-30 05:39 UTC, ramyaram2092 requested changes
Could you clarify on why the changes of Image.test.jsx file included with this PR? 
Also Kindly  cross check suggestions_icon.png file as well. I see that included in this branch

2024-03-31 13:57 UTC, one-community commented
> Could you clarify on why the changes of Image.test.jsx file included with this PR? Also Kindly cross check suggestions_icon.png file as well. I see that included in this branch

Good catch! Icons and images are frequently being broken by unrelated PR merges and I think this is an example of that. Xiao W has helped me fix them at least 5 times now.

2024-05-17 20:36 UTC, dkn6 approved these changes
All test cases are working as expected! LGTM

<img width="707" alt="test" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/168319518/8c59be5e-72de-4b90-b25b-ac11e901c7b1">

2024-09-06 22:08 UTC, Saniya98 approved these changes
All test cases passed successfully
![image](https://github.com/user-attachments/assets/6d3a2713-8b21-467b-b2ed-7393ecba406d)

2024-10-26 01:19 UTC, geetamatkar commented
Tested this PR and all test cases have passed.

<img width="768" alt="Screenshot 2024-10-25 at 8 19 17 PM" src="https://github.com/user-attachments/assets/104dee9f-803f-496e-87cd-4d36fc80724c">

2025-01-07 02:24 UTC, vishavk1992 approved these changes
I have tested this PR and all test cases passed successfully!!

2025-03-14 01:06 UTC, sri0606 commented
@one-community , An updated PR exists. this can be closed.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2615

2025-03-14 01:06 UTC, closed without merging