Jay - Toggle Request Bio Permission
OneCommunityGlobal/HighestGoodNetworkApp pull request #1831
Opened 2024-01-14 19:13 UTC by Alforoan

# Description
This PR enables the user with the Toggle Request Bio Permission to be able to access and toggle the bio switch.

## Related PRS (if any):
N/A

…

## Main changes explained:
- Added a new permission label for toggle request bio.
- Added conditional logic so that the user with the permission can view and toggle the switch.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to Other Links -> Permissions Management -> Manage User Permissions -> Choose a user without Toggle Request Bio under Reports -> click on Add  -> Scroll down then submit
6. verify that the user who was given the permission is now able to see the toggle on Reports -> Weekly Summarizes Report and toggle successfully.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/326bd5ab-ac0e-4329-969f-88dac8d316af

## Note:
**Unmute the video**

2024-01-18 20:10 UTC, keyunhuangg approved these changes
Verified that everything is showing and working correctly given with the 'Toggle Request Bio' permission added for a user
<img width="648" alt="Screenshot 2024-01-18 at 3 07 41 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/f1c387f5-26bb-4390-9d6c-261068bfd2de">
<img width="665" alt="Screenshot 2024-01-18 at 3 08 36 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/3daa5784-b6c3-4849-904b-7937ab174300">

2024-01-24 20:32 UTC, Nahiyan-16 submitted a review, later dismissed
## Works fine
Attempted to give a volunteer-level user permission to request bio using an owner account. 
Volunteer-level user was able to access the Reports dropdown and the Weekly Summaries Report page where they can toggle bio announcements for other users. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/9caa61e5-2e10-41cf-bf54-2b7a30ea4439

2024-01-27 00:21 UTC, nathanah requested changes

2024-01-27 00:21 UTC, nathanah commented on src/components/WeeklySummariesReport/FormattedReport.jsx
> +  return bioCanEdit || canRequestBio ? <BioSwitch {...props} /> : <BioLabel {...props} />;
This should be replacing bioCanEdit instead of adding to it.

2024-01-27 00:21 UTC, nathanah commented on src/components/WeeklySummariesReport/FormattedReport.jsx
> +  return bioCanEdit || canRequestBio ? <BioSwitch {...props} /> : <BioLabel {...props} />;
And `bioCanEdit` (which is based on the previous `putUserProfileImportantInfo` I think) should be removed.

2024-01-30 05:04 UTC, X1aoZhang99 reviewed
Hi Jay,

I tested this PR with BE #707, and all functionalities worked as intended. I'll approve this PR as long as the small issue above is fixed. Nice work!

2024-02-01 16:19 UTC, Renanluizssx requested changes
Hi @Alforoan, i reviewed your application but i'm having a issue, there is an error when i submit the Toggle Request Bio rule, please review my request:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/4b15882d-97f0-40cc-be82-088f3264b47e

2024-02-10 02:17 UTC, Pandani07 requested changes
Tested this PR with the related backend and got the following error
![Screenshot 2024-02-09 at 9 16 34 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/5c9927e8-970c-44a2-ba77-8ab1feec5645)
![Screenshot 2024-02-09 at 9 16 53 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/e65ce68b-2a23-4005-93fe-60c571882f63)
![Uploading Screenshot 2024-02-09 at 9.17.05 PM.png…]()

2024-02-11 05:10 UTC, galgalinidhi commented
Hi @Alforoan, I tested this PR by granting permission to an Admin account. I am able to see the toggle switch and it works as expected!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/900e58a2-70b6-4763-9fd0-7152759a3f78

2024-02-12 05:37 UTC, mohabbasd requested changes
Hello, I tested your PR and logged in to my owner account but when I add the bio option and press submit I get an error pop-up onto the top right corner of my screen. It is not working properly.
<img width="1440" alt="Screenshot 2024-02-12 at 12 33 21 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/47c9c54b-bc69-4ed5-a91c-4ee4b40c9708">
<img width="1440" alt="Screenshot 2024-02-12 at 12 33 34 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/8acb2690-a8dc-4b0d-b531-59a751d89313">
<img width="1440" alt="Screenshot 2024-02-12 at 12 34 26 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/173fd216-95e6-4b20-923e-75a394c96b24">

2024-02-15 22:20 UTC, XiaohanMeng requested changes
Hi, I tested this PR using both owner and volunteer accounts. In the owner account, I couldn't click the "Toggle Request Bio" as it appears to have been fixed. However, when I attempted to reset permissions to default, an error occurred. Upon checking my manager account, I found that "Toggle Request Bio" was not fixed, and I also encountered an error when trying to grant permissions. Below is a screenshot of the error that appeared in the backend terminal. 
![1831-error-BE](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/537d9a78-d010-4c68-a389-e06b177fb303)


As for the volunteer account, with "Toggle Request Bio" permissions, worked perfectly. I was able to switch the bio announcement to different statuses.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/d6f4067c-aa04-4100-8539-be31c45bedc3

2024-02-21 02:47 UTC, skaush21 reviewed
I tested the implemented features and they do indeed work. In the owner account, I am able to go to permission and assign 'toggle request bio' to a role. When choosing volunteer role can see the toggle button. when it is off. volunteers can see only whats been selected. However, I noticed that in the console when clicking on 'manage permissions' I get console warnings about memory leaks. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/3bf0233f-bf8f-4b45-a292-599b4361de46

<img width="700" alt="screen shot of warnings" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/d03a63f8-86a8-4f80-839e-6d4a7085ff9b">

2024-02-23 02:24 UTC, Jingyii800 requested changes
Hi @Alforoan, I tested this feature but encountered one issue in saving the change of "toggle bio" add button. Please check the screenshot and the video.
<img width="476" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/1b13142f-aa2b-495d-918a-fb574c709e0b">

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/c9550669-d977-401b-b1ca-f354d1a0c10e

2024-02-24 03:45 UTC, chrischenlixing submitted a review, later dismissed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114450390/bd273e04-5c46-41dd-8a62-f26b42c2dbba)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114450390/6b26928f-4dab-4178-839a-f1542941d667)
The permission change works as intended and the toggle button also works

2024-02-24 06:00 UTC, ClemarNunes requested changes
test your PR and got the following issues
![erro1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/75327bca-0d6b-482d-b241-fd174a3b8bae)

![erro2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/f4117ebf-928f-48c8-9f45-86c8360c327f)

2024-02-26 11:58 UTC, Gugor99 approved these changes, later dismissed
### Report
Hi Jay,
I reviewed your implementation and it seems to be working correctly. I logged in as owner to change my volunteer's profile permission on the toggle's bio, and then logged back in with my volunteer's profile. I was then able to switch the bio permission in others weekly summaries, well done!
### Screenshots
![Cattura1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/99e07c49-4327-437a-9f78-2de9afdfacf6)
![Cattura2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/157f6762-0ad1-46c7-97f4-f12800cfeb7b)
![Cattura3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/6369e9b9-f7b4-46e6-839d-238722812dd8)

2024-03-02 03:56 UTC, MALAV1308 requested changes
Hello, I have reviewed your PR but I got some error. Please look into it and solve it. Thank you.
![#704](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61341363/35788b73-f2c4-4885-ae0d-b7fe27043db5)
![#1831](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61341363/4e92f814-0b23-4d22-9dfe-e7853de74c3c)

2024-03-03 04:11 UTC, brandta-1 requested changes
# Review
Successfully able to edit another volunteer user's permissions. Successfully able to view and activate the Bio announcement toggle as a volunteer user. However this does not actually change the bio announcement and the ```PUT``` request returns a ```403```

```
Uncaught (in promise) Error: Request failed with status code 403
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.onloadend (xhr.js:54:1)
```

```
Failed to load resource: the server responded with a status of 403 (Forbidden)
```
The endpoint is ```http://localhost:4500/api/userprofile/<id of the toggled user>```

There is not a 403 popup on the web app.

# Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/df729f21-9220-474b-a3b8-3743dc00a986

2024-03-09 22:39 UTC, YHX6 approved these changes, later dismissed
The page toggle is added as described.
before:
<img width="1512" alt="Screenshot 2024-03-09 at 5 16 00 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113729159/4fca2aa7-e785-46ef-80dc-521003d14289">
after：
<img width="1512" alt="Screenshot 2024-03-09 at 5 37 25 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113729159/9cdde421-78b5-4658-9ae2-af630caed140">

2024-03-09 22:44 UTC, YHX6 requested changes
I added permission to a volunteer and an admin account. The toggle is not working as expected (not showing the switch toggle).
<img width="1512" alt="Screenshot 2024-03-09 at 5 43 05 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113729159/53806d5c-9dd4-4ced-bce3-bffb234ac26f">

2024-03-15 07:23 UTC, psharma1984 approved these changes
Hi @Alforoan Everything is working as expected. I can toggle the user 

[screen-capture (3).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/88c1a2f4-988d-45a6-bd9e-3be14f236b96)

2024-03-22 23:29 UTC, Coops023 commented
Hi i have left my comments in the backend PR

2024-03-27 17:10 UTC, SRamen1999 reviewed
I am unable to test this PR because the related backend #704 is giving an error when running npm run build.

<img width="1728" alt="Screen Shot 2024-03-27 at 12 59 43 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/18d750b5-b3c2-49f3-912a-0e0e786875f4">

2024-03-27 23:18 UTC, Gayathr-2012 commented
Hi "I've reviewed your backend, and there seems to be an issue. It's not retrieving my user profile.
<img width="1274" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/9c3c9e12-1d7b-4c4e-b11b-1d0ad0a2f028">

2024-04-02 21:11 UTC, kylepham requested changes
Frontend changes worked as expected. I was able to grant a volunteer account toggle request bio permission and the toggle appeared.
<img width="1800" alt="Screenshot 2024-04-02 at 3 43 19 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/343ed16d-d30c-473a-9f3c-2a9fe7c2e106">



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/64f1e761-0e97-41cf-abd2-8c7e8891fc55

However, there is a syntax error on the backend side that prevented me from starting up the server. Please see my [review](https://github.com/OneCommunityGlobal/HGNRest/pull/704#pullrequestreview-1975032604) for reference.

<img width="1800" alt="Screenshot 2024-04-02 at 4 01 50 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/e7faa5ba-60a8-4ada-841e-7af70d169f57">

2024-06-06 02:21 UTC, Kavil-Jain-514 requested changes
Facing errors when building the backend application PR 704
Steps: Checkout to the branch -> npm install -> npm run build 
Error:
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/112303944/84b7862f-631f-44ab-8aae-ba04dd39c449)

2024-06-06 21:02 UTC, JatinAgrawal94 requested changes
I am unable to run "npm run build" while starting backend. Kindly consider the screenshot for the error at hand.
<img width="1040" alt="1831" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/5ed6fd29-e3cf-48b1-ac31-ae213245be2c">

2024-06-14 21:06 UTC, TXMO-dev approved these changes
Checkout into the backend PR #704 to run together with this PR #1831 and the toggle request bio permission works accordingly. Approved!

2024-07-26 17:48 UTC, Shadhrush5 requested changes
Hi, I reviewed the PR #1831 with PR #704. Seems like I ran into an issue while building the current branch of the backend. I have attached a screenshot as well in the backend PR.

2024-08-04 06:13 UTC, souravwalke commented
Hi, I tried reviewing this PR with the mentioned backend PR and there seems to be a build issue in the backend code. I have attached a screenshot as well in the backend PR.

2024-09-08 04:30 UTC, yashwanth170 approved these changes
Everything is working as expected. I am able to toggle bio permission after giving permission
![toogle_bio](https://github.com/user-attachments/assets/3d93ad51-3059-4994-9478-bd977fc77f48)

2024-09-13 14:52 UTC, swaroop-2007 requested changes
I tried reviewing this PR along with the associated backend PR, but experienced an issue while building the backend server. I have added my review to the PR #704. 

Thanks.

2024-09-17 18:27 UTC, SFA23SCM35V approved these changes
"I checked out the current branch and ran the application locally using npm install and npm run start:local. After clearing the site data and cache, I logged in as the owner user and navigated to Other Links -> Permissions Management -> Manage User Permissions. I selected a user without the 'Toggle Request Bio' permission under Reports, added the permission, and submitted the form. I then verified that the user could now see the toggle under Reports -> Weekly Summaries Report and confirmed that the toggle worked as expected."
![1](https://github.com/user-attachments/assets/e779977a-d430-4d59-80c1-a4a7126b35b9)
![2](https://github.com/user-attachments/assets/2212bb4f-7ff8-4f2e-bbfd-e589f76a93f6)
![3](https://github.com/user-attachments/assets/6057c8d5-ebb5-4bd1-a9a9-f8153669b15e)
![4](https://github.com/user-attachments/assets/29cafe16-cbd4-4b06-ae30-cd0475800da1)

2024-09-20 12:50 UTC, neeharikakoniki requested changes
reviewed at https://github.com/OneCommunityGlobal/HGNRest/pull/704#pullrequestreview-2318190197

![image](https://github.com/user-attachments/assets/b6d4372c-854f-414e-bd77-1333e2b71883)

2024-09-21 20:45 UTC, Muzammil603 reviewed
I have reviewed this in Backend PR#704

2024-09-29 02:28 UTC, khushijain03 approved these changes
Followed the following: 
Other Links -> Permissions Management -> Manage User Permissions -> Choose a user without Toggle Request Bio under Reports -> click on Add -> Scroll down then submit.

I verified that the user who was given the permission is now able to see the toggle on Reports -> Weekly Summaries Report and toggle successfully.

<img width="1226" alt="Screenshot 2024-09-28 at 10 20 53 PM" src="https://github.com/user-attachments/assets/0612e9b3-c123-4d8b-8240-d42ae10e5eaa">

2024-10-01 21:37 UTC, mrinalini-raghavendran19 requested changes
Reviewed in associated backend PR 704

2024-10-20 02:54 UTC, navya9989 commented
Hi, I have tested this PR locally and toggle request is updated as expected. Good Work!
![PR# 1831](https://github.com/user-attachments/assets/8ec373c0-2c0e-45b5-ac4a-3d0d22cc8f8c)

2024-10-20 23:40 UTC, navya9989 reviewed
toggle request is updated as expected

2024-11-09 18:24 UTC, SupriyaSudini requested changes
Experiencing issues with running "npm run build" when starting the backend.

![image](https://github.com/user-attachments/assets/d5b02705-9113-433d-aaf3-0e4eaf656f3e)

2025-08-02 03:19 UTC, BenithaSri approved these changes
Reviewed the changes and found everything working as expected.

<img width="928" height="374" alt="Screenshot 2025-08-01 at 11 17 11 PM" src="https://github.com/user-attachments/assets/7940ae23-00fa-4397-afd2-f84931f7d163" />
<img width="2637" height="1709" alt="Screenshot 2025-08-01 at 11 15 32 PM" src="https://github.com/user-attachments/assets/fa5326d0-7174-4699-ae7e-8d8084e29d1a" />

2025-10-25 14:48 UTC, closed without merging