more unit tests for activeinactiveconfirmationpopup.jsx
OneCommunityGlobal/HighestGoodNetworkApp pull request #1833
Opened 2024-01-15 02:15 UTC by Changhao3220K

# Description
more unit tests for activeinactiveconfirmationpopup.jsx

## How to test:
1. check into current branch
2. do `npm install` and `npm test ActiveInactiveConfirmationPopup.test.js` to run this PR locally
3. verify all 11 tests passed

## Screenshots:
<img width="800" alt="Screenshot 2023-12-14 at 11 47 37 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104778270/d8484d9b-468a-4640-94f0-81ed35d8fcbd">

2024-01-15 21:17 UTC, sahilpatel18 approved these changes
All test cases passed successfully. Great work! 

<img width="683" alt="Screenshot 2024-01-15 at 4 16 46 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/24741818/8147e754-6d11-4994-899d-3ead0a604420">

2024-01-20 23:39 UTC, DragonSlayer2401 commented
I tested your PR and all of the tests passed as intended. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/48a9588f-f244-41b4-8287-06e7daac5865

2024-01-21 00:31 UTC, vikrambadhan submitted a review, later dismissed
Hi, I tested your PR and all the test cases passed!

![Week 21 - PR5](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/9f5441c9-7cf1-45ab-86e1-2a3324c508e8)

2024-01-23 19:32 UTC, Nahiyan-16 submitted a review, later dismissed
## Well done!
This unit test is concise, well-organized, and effectively tracks function calls using Jest mocks. Assertions confirm non-invocation of 'onClose' and 'setActiveInactive' under specific conditions. Overall, it's a compact and comprehensive test.

![Screenshot 2024-01-23 142430](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/965794a5-7bf3-49f9-b2d8-14bf7ad80980)

2024-01-25 01:48 UTC, X1aoZhang99 submitted a review, later dismissed
Hi Changhao,

All tests passed, congrats! 

![Screenshot 2024-01-24 at 17 11 02](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/d45978a8-8eb8-44fd-9bc9-f94bce14678d)

2024-01-31 15:17 UTC, peterson337 submitted a review, later dismissed
All tests passed

![a](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/df9c0541-f339-4e2b-9db0-8f5eb3d5c588)

2024-02-01 12:40 UTC, Renanluizssx approved these changes, later dismissed
Hi @Changhao3220K, i tested your unit test and it's running correct:
![Screenshot 2024-02-01 093908](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/61369cca-343f-43ca-9529-f84ea13cc16c)

2024-02-03 22:02 UTC, 666saofeng approved these changes
All tests passed and everthing worked as intended.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/6245c760-907b-48d0-808c-49358bbc90f5)

2024-02-08 22:58 UTC, Pandani07 approved these changes, later dismissed
All the test cases passed! 
![Screenshot 2024-02-08 at 5 52 59 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/b1f67f5e-2c0c-464c-94a4-46cc8d765268)
However, when I tried to run this frontend branch with the latest development backend, I got a white screen and could not use the app. I don't know if that issue is related to this frontend branch, but just mentioning it.

2024-02-08 23:30 UTC, prnvjn approved these changes, later dismissed
Ran the PR, cleared all 11 Test
![#1833 Changhao - more unit tests for activeinactiveconfirmationpopup](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/3525231/b06d626a-91dc-4c8d-a82d-bb38d0ec73df)

2024-02-12 05:07 UTC, mohabbasd submitted a review, later dismissed
Hello, I tested your PR and it is working perfectly.
<img width="887" alt="Screenshot 2024-02-12 at 12 07 08 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/bef78794-1fb2-47e8-ab3c-3ccbbca418b5">

2024-02-17 01:57 UTC, ramyaram2092 requested changes
The test cases are detailed. Good job!
Kindly move the test case to the __ tests __ folder. 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/4befe531-2395-496d-a683-7ccdb8ac1e7c)

2024-02-17 05:45 UTC, ClemarNunes approved these changes
I tested your PR and worked as expected.

![TestFoto](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/3425f03d-8797-4b09-a657-4912c84857ff)

2024-03-23 22:25 UTC, Tiantian-C reviewed
All the tests have passed!
<img width="513" alt="Screenshot 2024-03-23 at 3 24 35 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/37a4e315-290c-47fd-8ef6-d828a384925a">

2024-05-11 18:55 UTC, dkn6 approved these changes
All test cases are working as expected.
Thank you for the great work!

<img width="633" alt="#1833" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/168319518/63862ba7-cade-468f-8e81-22e8d762c754">

2024-08-16 02:33 UTC, SatyashanthiT approved these changes
I tested PR 1833 by checking out the current branch, installing dependencies, and running the unit tests. All 11 tests for ActiveInactiveConfirmationPopup.jsx passed successfully, confirming that the component functions as expected. 
<img width="950" alt="image" src="https://github.com/user-attachments/assets/35ecb394-6081-4511-8d8d-f86b415d35f9">

2024-10-17 14:47 UTC, beblicarl commented
@Changhao3220K can you please work on the merge conflicts

2024-10-17 14:48 UTC, beblicarl commented
All tests passed successfully

![image](https://github.com/user-attachments/assets/cde711b6-b100-4528-809c-9f65924e509a)

2024-10-19 07:21 UTC, beblicarl approved these changes

2024-10-26 01:05 UTC, geetamatkar commented
Tested this PR and all the test cases have passed.

<img width="843" alt="Screenshot 2024-10-25 at 8 05 19 PM" src="https://github.com/user-attachments/assets/14ca517d-e428-4ea9-9c1a-6a9ec2ae9bf1">

2024-12-04 23:33 UTC, sri0606 commented
The unit tests that were added in this PR were already merged and exist in the latest branch. This PR can be closed.

2025-01-27 03:02 UTC, closed without merging