Leo fix user id workaround bug for dashboard display
OneCommunityGlobal/HighestGoodNetworkApp pull request #1839
Opened 2024-01-16 00:33 UTC by Chuehleo

# Description
![螢幕擷取畫面 2024-01-15 171036](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/341c9130-1538-4190-96a3-d4ee6ac84ba4)

## Related PRS (if any):
N/A
…

## Main changes explained:
- Fixed the Add Time Entry button on the Dashboard to display correct user id when clicked the dashboard button to navigate back to owners dashboard while viewing other users dashboard. Made adjustments in useEffect hooks and state management for accurate data loading.
-Corrected an issue where the wrong badges and leaderboard data were displayed for a user in dashboard. Modified useEffect dependencies for accurate badge updates based on user selection.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Leaderboard→ Select a user to view his/her dashboard…
6. click the dashboard button on the nav bar
7. check if the Add Time Entry button changes back to green with correct text
8. check if the badges and leaderboard are showing the correct user data

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/d6bb8f5e-cfb5-48d5-b9a8-fd1c6b18f609

2024-01-16 10:49 UTC, beblicarl requested changes
I got this error in the console which prevented me from logging in

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/d416c9ea-bb87-4766-beb8-5b6c0f5bc311)

2024-01-18 03:49 UTC, pshereen requested changes
Not able to log in.
Getting this error in the terminal.

<img width="911" alt="Screenshot 2024-01-17 194843" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/94c141ea-c3cd-49ac-a549-3e77793158d4">

2024-01-18 07:52 UTC, Renanluizssx approved these changes
it´s very nice @Chuehleo, look my review below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/64ef2774-704d-4740-bb4d-fa305d8a2ec4

2024-01-20 07:31 UTC, bajajtushar094 approved these changes
@Chuehleo I tested your PR and works as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/d595a9d1-5df5-4a10-a323-14a89e735143

2024-01-28 02:17 UTC, ShengjieMao approved these changes
The app works as expected. No errors found when testing.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/b3c25d3b-f224-4b29-9076-0451f250919e

2024-01-29 22:31 UTC, X1aoZhang99 requested changes
Hi Leo,

I tested your PR with the admin role, and an unexpected issue occurred. After I clicked to view another user's dashboard, a new window popuped and I was not able to see the dashboard within a second. Please refer to the video. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/1dbe57fe-b7b7-40e1-8ccc-72444d703b41

2024-01-30 19:59 UTC, peterson337 approved these changes
I tested it and it worked as advertised.

![one comunnity](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/241a6399-52fb-4d71-ab01-03efb48851cd)

2024-02-03 21:35 UTC, 666saofeng requested changes
Hi, I conducted a test on your pull request using the admin account when an unforeseen problem arose. Clicking to access a different user's dashboard triggered a new window to open, preventing the dashboard from being visible immediately. Kindly consult the video for more details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/556cc29a-dcc4-4376-a20f-06cd0f310ed4

2024-02-08 17:31 UTC, Pandani07 requested changes
I cannot click anything on the screen and I get this error in the backend console. Im using the latest Development branch

![Screenshot 2024-02-08 at 12 31 18 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/e2739875-6a8d-4bdc-b34b-fec688aacf43)

2024-02-17 02:24 UTC, XiaohanMeng requested changes
Hi, I tested this PR and encountered an issue where the screen remains clickable when the team member tasks are not loaded. However, once the team member tasks have finished loading, I am unable to click anywhere on the page when attempting to access the user dashboard. Please see my video for more details.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/4a0a4299-3747-43a5-9d87-02c6ad5199a1

2024-02-17 03:54 UTC, TapanPathak requested changes
Hi, I tested your PR and using latest development branch. I'm not able to perform the functionality. Getting following error on backend - 

 
<img width="773" alt="Screenshot 2024-02-16 at 7 49 14 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/c9cd612d-b62d-40aa-8c31-2d83ee62d1e4">

2024-02-17 06:54 UTC, mohabbasd requested changes
Hello, I tested your PR using the development branch for the backend but I cannot click on anything like the others have mentioned. There are some screenshots for your reference.
<img width="1440" alt="Screenshot 2024-02-17 at 1 52 55 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/e2784cde-4507-4472-a103-5700bfdc4f07">
<img width="992" alt="Screenshot 2024-02-17 at 1 52 38 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/673ada0a-c566-4430-8108-6f1ac94cac52">

2024-02-17 20:20 UTC, swathyjayaseelan requested changes
The name in the dashboard page is updated based on the user but I can see some errors in the console and the "Tasks and Timelog" box overlays on the dashboard header 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/9ef9625d-873f-49b0-8c37-672644567815

2025-04-17 22:50 UTC, closed without merging