Jay - Modify Task X on Dashboard Permission
OneCommunityGlobal/HighestGoodNetworkApp pull request #1850
Opened 2024-01-18 21:54 UTC by Alforoan

# Description
This PR enables the user with the View and Interact with Task “X” on Dashboards Permission to be able to access the X button on dashboard under task name and update the user.

## Related PRS (if any):
This frontend PR is related to the [#704](https://github.com/OneCommunityGlobal/HGNRest/pull/704) backend PR.

…

## Main changes explained:
- Added a new permission label for View and Interact with Task “X” on Dashboards.
- Added conditional logic so that the user with the permission can view the X button and update the user.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to Other Links -> Permissions Management -> Manage User Permissions -> Choose a user without View and Interact with Task "X" on Dashboards under Project Management, Work Breakdown Structures, Tasks -> click on Add  -> Scroll down then submit
6. verify that the user who was given the permission is now able to see the the X button on dashboard under each task.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/164a5615-5ef9-4de8-9abd-4c4179ca96b1

## Note:
**Unmute the video**

2024-01-23 00:48 UTC, X1aoZhang99 submitted a review, later dismissed
Hi Jay,


I've just reviewed your Pull Request; everything is functioning as expected. 

Permission Grant:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/bf0ed932-4667-4e74-b946-ee048a06c8f6

Modify Task:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/f65c3493-0080-4cb7-9db4-b2b32b445f9d

2024-01-24 19:32 UTC, Nahiyan-16 approved these changes
## Works great
Using an owner account, I was able to change permission of a volunteer-level user to be able to View and Interact with the "X" on tasks. I was fully able to delete the task from using the volunteer-level account. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/f552be2a-3958-4985-91c8-ccbf6160f51f

2024-01-31 14:22 UTC, Renanluizssx reviewed
Hi @Alforoan, i tested your application and i didn't get to see the team members, it gave me a block, see my review

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/abb40918-3a08-461a-a6a3-853681f83616

2024-02-05 16:15 UTC, Pandani07 requested changes
Hello, I tested this PR and I encountered a bug. I am using the latest development backend. After I add the Task X permission to my volunteer user, when I log into the volunteer account, the dashboard is just a white screen. I can see the user profile and team locations pages when I manually modify the URL. However, I
![Screenshot 2024-02-05 at 11 13 30 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/f4fe9990-f372-438c-bfe5-5a69d80fc285)
![Screenshot 2024-02-05 at 11 13 42 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/078a1043-bb29-4958-b618-c9e0c8b11853)
 cannot see the dashboard.

2024-02-16 07:17 UTC, mohabbasd submitted a review, later dismissed
Hello, I tested you PR and it works as instructed. Nice Work.
<img width="1440" alt="Screenshot 2024-02-16 at 2 13 10 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/0d0aa8cc-751c-4bc7-9d86-449c98ffe644">

2024-02-21 21:22 UTC, XiaohanMeng reviewed
Hi, I tested this PR using the owner and volunteer accounts, following your guidance, and it worked as intended. Here are my steps:
* The owner account granted permissions to the volunteer account.
* The volunteer account was able to see and click the 'X'.
* The task was successfully deleted.
However, an error appeared in the backend terminal, as shown in the image. 
<img width="977" alt="PR1850+707_error" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/6e328899-d386-4151-a595-233cb047b221">
Please see the reference video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/a09ec6e0-be64-4301-a883-5b52f742f45c

2024-02-21 23:15 UTC, skaush21 reviewed
Unable to view task 'X'
I first go to 'other links' -> 'permission management' -> 'volunteer' -> Choose a user without View and Interact with Task "X" on Dashboards under Project Management, Work Breakdown Structures, Tasks -> click on Add -> Scroll up and save.

I then go to projects -> wbs -> add tasks

i first check 'team members tasks' on owner account, I am unable to see my own created tasks (i do see other members tasks though)
I click on members name and there is no tasks, even though I had created a few.

I then logout and sign in to volunteer account, i can see no tasks and when clicking on the name and going to the projects tab, i see no tasks.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/eb4a10a5-2b10-4d45-8ef8-50f20d5ab2bf

2024-02-21 23:16 UTC, skaush21 requested changes
Unable to view task 'X'
I first go to 'other links' -> 'permission management' -> 'volunteer' -> Choose a user without View and Interact with Task "X" on Dashboards under Project Management, Work Breakdown Structures, Tasks -> click on Add -> Scroll up and save.

I then go to projects -> wbs -> add tasks

i first check 'team members tasks' on owner account, I am unable to see my own created tasks (i do see other members tasks though)
I click on members name and there is no tasks, even though I had created a few.

I then logout and sign in to volunteer account, i can see no tasks and when clicking on the name and going to the projects tab, i see no tasks.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/eb4a10a5-2b10-4d45-8ef8-50f20d5ab2bf

2024-02-23 05:35 UTC, chrischenlixing reviewed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114450390/916d7165-4e99-48d3-a028-dd7ebf1e7bb8)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114450390/13c08504-1b7a-4572-b251-fab94f48c52e)
It might not be directly related to this pr, but when I try to hit save after editing the permission management, it's throwing this error to me on my backend. And I am not able to save it. Just want to raise it to concern.

2024-02-25 03:38 UTC, ClemarNunes requested changes
I tested your PR and it worked as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/b8eebfa0-dabb-45ac-ab1a-36fec611b0a6

however, I got an issue on the backend
![erroN](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/740a65b8-6000-4e64-a1dc-8c54383ae850)

2024-03-03 12:35 UTC, PratimaSingh02 reviewed
Tested the PR and I can't see the delete task icon even after permission is granted.
![Screenshot (43)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/48998232/b909d678-fbc8-4c8b-8472-a33b33efee3d)


X button still not visible
![Screenshot (42)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/48998232/192e6275-b258-4b40-8f98-8267616a9f45)

2024-03-03 12:44 UTC, PratimaSingh02 reviewed
Tested the PR and I can't see the delete task icon even after permission is granted.
![Screenshot (43)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/48998232/b909d678-fbc8-4c8b-8472-a33b33efee3d)


Remove button still not visible
![Screenshot (42)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/48998232/192e6275-b258-4b40-8f98-8267616a9f45)

I tried to print the value of canDeleteTask constant on page TeamMemberTask and it prints only false. Which means

2024-03-03 12:44 UTC, PratimaSingh02 commented on src/components/TeamMemberTasks/TeamMemberTask.jsx
> +                            {canUpdateTask || canDeleteTask && (
I can see the delete icon only after removing canDeleteTask constant here on line 191, which means either the database is not getting updated when assigning the permission or the value is not handled properly at the frontend.
Please find the screenshot below that prints the value of canDeleteTask on console. 
PS: This component shouldn't be loading more than once as it uses React.memo hook. But as we can see, it re-renders 1169 times. This issue could have been caused by a state/prop change in a parent component that this component uses.
![Screenshot (44)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/48998232/9fb4cff1-9c35-4923-b7a2-c8fb2fc5143d)

2024-03-08 02:16 UTC, nathanah requested changes

2024-03-08 02:16 UTC, nathanah commented on src/components/TeamMemberTasks/TeamMemberTasks.jsx
> +                      userPermission={props?.auth?.user?.permissions?.frontPermissions?.includes('putReviewStatus')}
This is unrelated to this PR. 
Also, it should be removed in general to remove prop drilling. Call `hasPermission()` in the component where you actually need this permission instead. `hasPermission()` will also check for role permissions in addition to user permissions.

2024-03-08 02:16 UTC, nathanah commented on src/components/TeamMemberTasks/TeamMemberTasks.jsx
> +                      userPermission={props?.auth?.user?.permissions?.frontPermissions?.includes('putReviewStatus')}
```suggestion
```
Remove to reduce prop drilling

2024-03-08 02:16 UTC, nathanah commented on src/components/TeamMemberTasks/TeamMemberTask.jsx
> +                              userPermission={userPermission}
```suggestion
```
Remove to reduce prop drilling

2024-03-08 02:16 UTC, nathanah commented on src/components/TeamMemberTasks/TeamMemberTask.jsx
> +    userPermission
```suggestion
```
Remove to reduce prop drilling

2024-03-08 02:16 UTC, nathanah commented on src/components/TeamMemberTasks/ReviewButton.jsx
> +  userPermission
```suggestion
```
Remove to reduce prop drilling

2024-03-08 02:16 UTC, nathanah commented on src/components/TeamMemberTasks/ReviewButton.jsx
> +      if (myRole == "Owner" ||myRole == "Administrator" || myRole == "Mentor" || myRole == "Manager" || userPermission) {
```suggestion
      const canPutReviewStatus = props.hasPermission('putReviewStatus')
      if (canPutReviewStatus) {
```
This is unrelated to this PR and should be either added to the description/testing instructions or removed/remade in its own PR.

Wherever you choose to add the `putReviewStatus` permission, it should replace any role logic with standardized permission logic.
Import and connect `hasPermission()` when you're implementing this.

2024-03-08 02:16 UTC, nathanah commented on src/components/PermissionsManagement/PermissionsConst.js
> +              },
Adding this permission is not pointed out in the PR description.

2024-03-09 14:39 UTC, DiegoSalas27 commented
Hi Jay, your PR is working as expected. Great job.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26840798/be11272e-a649-4953-8db4-08224581d433

2024-03-09 14:40 UTC, DiegoSalas27 submitted a review, later dismissed

2024-03-13 04:35 UTC, Tiantian-C reviewed
I have tried your code.I gave permission to my admin account, but nothing changed.Maybe need a change,thank you!
<img width="696" alt="#1850-1" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/9febc280-17de-44f8-b2d1-1101a5028a34">
<img width="831" alt="#1850-2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/c826819a-f556-4755-a978-e1790e0890e4">

2024-03-15 07:15 UTC, psharma1984 reviewed
Hi @Alforoan With latest dev branch i'm unable to see 'X' for team members task

[screen-capture (2).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/aad9128c-28a8-4208-9010-d4b725a5c1ce)

2024-03-15 19:14 UTC, SRamen1999 reviewed
After testing this PR everything is functioning as expected. I used an Owner account to give permission to view and interact with task "X" on a volunteer account.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/ab6ec4d1-3564-4ccd-b693-ce3ee90fd39a

2024-03-16 20:06 UTC, Sarthak32 requested changes
Hi, I have tested it as you have mentioned using volunteer account.
I was able to click on 'X' but the Task wasn't removed from the list.Here are screenshots : 
![Screenshot 2024-03-16 180923](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/89b23d65-6680-4c74-a769-4645982
![Screenshot 2024-03-16 180938](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/0c63ae21-2715-47a2-96de-0daca42ff9ea)
01264)
![Screenshot 2024-03-16 181040](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/5761b07f-758d-40a7-b213-0913953b6195)

![Screenshot 2024-03-16 181059](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/8e6ff13a-f7f9-462d-9292-49442c48eaac)

2024-03-19 16:34 UTC, rajnada commented
Hi Functionality is working as expected, user can able to remove the task. However, I can see "View and Interact with Task “X” on Dashboards" permission is set by default it should be manual. So I request you if you can set it to manual.

Here is the preview

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25640436/0ec01b85-a6a9-4240-9531-82eaf7c17c89

2024-03-21 23:59 UTC, iven-yao approved these changes
following screenshots show before and after granting the permission on a test role account, the user could interact with the task with the X on dashboard, and remove task with X correctly.

here's the steps I reproduce the test
1. login as owner
2. assigned tasks to test role
3. add permission to test role
4. login as test role
5. the X of tasks will show on user's dashboard
6. click X, the task will be removed

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/b668ec7b-130c-4880-b454-789036e455be)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/425ca18d-04a0-4147-a404-4cdd7ff390b8)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/54a9bb01-fcc1-4170-8949-11014215fa76)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/0cebfaae-0d7e-4ac3-93a5-a960aa1ce732)

2024-03-22 01:33 UTC, hetvi11110 reviewed
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/66b7e486-f485-4a01-820e-7b86ff7bb82e

As mentioned, I have reviewed the PR, and the Modify Task X on Dashboard Permission is working fine. However, Modifying Task X on Dashboard Permission will not work if I enable Edit Task permission. Here is the reference video.

2024-04-02 02:47 UTC, kylepham requested changes
PR worked as intended. Volunteer account with the new permission could remove themselves from an assigned task.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/340a32f0-3e6d-4f13-bc2e-0029b68d6a4f

There are some code in the PR that need to improve to enhance code quality (like renaming permission name, using `hasPermission` instead of passing props) that others have pointed out above.

2024-09-05 22:08 UTC, AJAYINAVOLU submitted a review, later dismissed
Changes are working as expected.

<img width="932" alt="image" src="https://github.com/user-attachments/assets/ba5bf73a-0072-461f-b477-8f19cba0d29b">

Thank You

2024-09-14 18:52 UTC, Saniya98 reviewed
Reviewed this PR, but unable to see "X"
![image](https://github.com/user-attachments/assets/221794c4-257c-43e2-bb31-94e711627e1f)
![image](https://github.com/user-attachments/assets/de4b50be-89cc-4ca8-a195-d5a4b38fdee3)

2025-06-28 16:23 UTC, boppanapraveen submitted a review, later dismissed
Check by adding  a new permission label for View and Interact with Task and also tried by adding conditional logic so that the user with the permission can view, Its working fine.
![image](https://github.com/user-attachments/assets/10f18c8d-8325-4d74-a62d-1494cfb9a7fb)

2025-06-30 06:27 UTC, one-community commented
Thank you all, merging!

2025-06-30 06:28 UTC, merged

2025-07-05 07:18 UTC, shashank-madan reviewed
Changes work as expected. Able to view and interact with 'x' button on task dashboard after updated permissions. 

https://github.com/user-attachments/assets/c2e0d52e-106a-4030-b8dc-f426b24b40a2

2025-07-09 22:46 UTC, sphurthy commented
The changes work as expected, I was able to edit the permissions of a particular Volunteer level user to be able to View and Interact with Task "X" on Dashboards, as an Admin user.
![image](https://github.com/user-attachments/assets/89958857-c94c-4cac-98bf-a7b55bdeb559)
I am also able to view and interact with the "X" when logged in as the Volunteer user.
![image](https://github.com/user-attachments/assets/fdbe1321-7322-4a03-b696-8e6a28f0d985)
Good work!

2025-07-14 19:55 UTC, Teja-Sri-Surya commented
Successfully tested the "View and Interact with Task 'X' on Dashboards" permission.
The X button now properly appears under each task for users with the granted permission.
Feature behaves as expected — permission logic works and dashboard interaction is smooth.
Good job! Just ensure wording consistency ("the the X button" → "the X button") in UI/tooltips if any. 👍
<img width="1902" height="918" alt="Screenshot 2025-07-14 144600" src="https://github.com/user-attachments/assets/0842eaa1-2135-43e0-aa74-d24ba04130ca" />

2025-07-18 23:41 UTC, vamsidharpanithi reviewed
Tested the permission-based access to the “X” button on the dashboard under task names. After assigning the "View and Interact with Task X on Dashboards" permission to a user, the user was able to see and use the X button as expected. Everything appears to be functioning as intended.
<img width="625" height="340" alt="image" src="https://github.com/user-attachments/assets/004029a5-ad46-4d30-a850-9a7ae74c4cab" />


<img width="635" height="293" alt="image" src="https://github.com/user-attachments/assets/51c04531-daf2-45f1-92b8-2cbd6561981f" />

<img width="638" height="340" alt="image" src="https://github.com/user-attachments/assets/ad053468-3e31-4daa-bedf-b538c12afb20" />


<img width="656" height="342" alt="image" src="https://github.com/user-attachments/assets/d802a717-5519-4f92-97c1-f061f4d57226" />

<img width="644" height="341" alt="image" src="https://github.com/user-attachments/assets/64f0f400-28dc-4575-85f9-9c905c2fc715" />

2025-07-19 04:11 UTC, Babu-kota reviewed
The new permission for interacting with the Task “X” button on dashboards is working as expected. I tested the full flow from assigning the permission to verifying the visibility and functionality of the “X” button and everything behaves correctly. 

https://github.com/user-attachments/assets/6713870e-890f-42a3-b653-e2a4a35e31c9