Masasa_fix_the_end_dates_issue
OneCommunityGlobal/HighestGoodNetworkApp pull request #1852
Opened 2024-01-19 03:57 UTC by ThapeloMasasa

# Description
![Screenshot 2024-01-18 at 7 47 04 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/06198907-8617-4a8b-9b0f-607c0671cacd)

## Related PRS (if any):
This PR is only frontend so it runs the back end on development branch

## Main changes explained:
- Added a check in case the person object has no end date and in which case the end date would be 'N/A'

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Reports→ Reports→ People
6. verify that the end dates for each user is either a valid date that is not current date or is N/A

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/69ea9668-2e0d-4dda-9767-0acb7fc5383e

2024-01-23 15:57 UTC, Nahiyan-16 requested changes
## Hi there!
I believe you may have accidentally deleted the package-lock.json file which is crucial.
Assuming you didn't add any other dependencies, I tested your changes on the development package-lock.json file and your changes work accordingly.
Unavailable end dates show up as "N/A" while the correct end dates show for available ones.  

![Screenshot 2024-01-23 104708](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/9d6a4e4d-5310-446c-84e7-ff265e96a7b7)

2024-01-23 15:57 UTC, Nahiyan-16 commented on package-lock.json
Noticed the deletion of package-lock.json. It's a crucial file for dependency management.

2024-01-29 17:23 UTC, peterson337 approved these changes, later dismissed
The dates for users are either validated or marked as N/A.

![a](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/46517351-8b55-4c79-89cb-10ede28f3e61)

2024-01-30 03:00 UTC, 666saofeng approved these changes
Hi, I tested with admin account and it worked as intended. Congrats!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/8775b9be-62d8-43c4-83ae-f9f7247c4ed3

2024-01-30 03:31 UTC, pshereen submitted a review, later dismissed
Tested the PR and the implemented feature is working as per the requirement.

Logged in as Admin user.
End dates for each user is either a valid date that is not current date or is N/A.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/c79b7157-b603-4d15-a229-65a3e37c69ac

2024-01-30 16:27 UTC, SRamen1999 submitted a review, later dismissed
Tested the PR everything works as expected

Logged in as Admin user. End dates for each user is either a valid date that is not current date or is N/A. Everything is also updated accordingly when adding and deleting end dates.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/20251a0c-d914-4d77-ac2c-f41f2dabc80f

2024-01-31 02:17 UTC, Renanluizssx submitted a review, later dismissed
Hi @ThapeloMasasa, i tested your application and it's correct, nice

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/b4145fca-f2bd-4039-952e-120ff090fd8d

2024-01-31 02:23 UTC, SaiDeepak-NEU submitted a review, later dismissed
I have logged in as an admin and checked the people tab under reports and the end dates are looking fine according to the description given. 
It is not showing the current date and showing the proper dates and displaying N/A for invalid fields.
![Screenshot (27)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114311909/962da53a-10d5-4812-8429-cbe6bdf53b34)
![Screenshot (26)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114311909/ef696263-8aaa-4653-b4a0-e98fa0c90aae)

2024-01-31 13:42 UTC, Sophie-lei submitted a review, later dismissed
Hey, I just reviewed this PR.  I logged as an admin role and everything works as expected. The End Date has either the valid date or N/A. The User permission page also works well. Please check the video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/34785624-c66c-4b80-bab8-ad66ca66ec16

A small problem would be looks like some end dates are easier than the start date. It may causes confusion. Is it better to limit the end date after the start date? like this 
<img width="590" alt="Screenshot 2024-01-31 at 21 38 54" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/d45e8699-f0f5-4b67-86af-e93e6e749eac">

2024-02-02 03:41 UTC, KevHnh submitted a review, later dismissed
I tested using an owner account and the changes are working as expected. The end dates are either "N/A" or displaying a valid date. 

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/758188d4-9aae-429d-9d50-2e2f42badbfb)

2024-02-03 06:38 UTC, galgalinidhi commented
Hi @ThapeloMasasa , I tested the PR and it works as expected! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/8555c2ea-c917-4ace-8a77-2662c2016b2a

2024-02-03 16:20 UTC, ShengjieMao approved these changes, later dismissed
Hi, all dates seems to be fine and they have the same format.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/f3ab178b-be89-408e-8170-af7ba982d5b0

2024-02-03 18:40 UTC, one-community commented
Thank you all, moving to final review.

2024-02-05 14:57 UTC, Renanluizssx submitted a review, later dismissed

2024-02-09 02:31 UTC, Aishwaryak01 commented
@ThapeloMasasa I can see that the checks have failed for this PR. Can you check?

2024-04-20 19:09 UTC, closed without merging