Jay - Edit Time Entry Description Permission
OneCommunityGlobal/HighestGoodNetworkApp pull request #1859
Opened 2024-01-20 20:17 UTC by Alforoan

# Description
This PR enables the user with the Edit Time Entry Description permission to be able to access any user's time entry description and edit it and update successfully.

## Related PRS (if any):
This frontend PR is related to the [#707](https://github.com/OneCommunityGlobal/HGNRest/pull/707) backend PR.

…

## Main changes explained:
- Added a new permission label for Edit Time Entry Description permission.
- Added conditional logic so that the user with the permission can view the edit button and edit the time log description.

## How to test (please watch the video):
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log in with an owner account
5. go to Other Links -> Permissions Management -> Manage User Permissions -> Choose a user without Edit Time Entry Description permission under Timelog Management, Edit Time Entries, Edit Timelog Description -> click on Add  -> Scroll down then submit
6. verify that the user who was given the permission is now able to see the the edit button on another user's dashboard for time log entries.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/3dc44aab-1f81-4f26-8c97-09f82afe301c

## Note:
**Unmute the video**

2024-01-23 18:26 UTC, X1aoZhang99 approved these changes, later dismissed
Hi Jay,

I've tested your PR, and all functionalities worked as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/1daf8267-d581-4899-a49f-dc14460fef72

2024-01-28 01:03 UTC, abdel-lall approved these changes, later dismissed
Works as described. Good job!
![Screenshot 2024-01-27 185905](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/1d880400-bb84-4c5a-a906-4f06e0978b41)
![Screenshot 2024-01-27 190018](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/2c8372fd-66aa-4f75-bee7-bf2f8f8c0972)

![Screenshot 2024-01-27 185940](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/3872255b-5075-4aac-b012-403fd0534f3d)

2024-01-31 01:52 UTC, Renanluizssx approved these changes, later dismissed
Hi @Alforoan, i tested your application and it's correct, see my review below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/5297c326-6afb-4c31-b87c-2ba38ea16b42

2024-02-01 22:22 UTC, Nahiyan-16 submitted a review, later dismissed
## Works fine
Hi Jay, just tested your PR and everything seems to work fine. I logged in as an owner and updated permission of another account to be able to edit the description. I made sure that when it was toggled off you weren't able to edit it and when you toggle it on that you are able to. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/82539da9-e7d5-49ce-9c8a-2f5404aac5cd

2024-02-03 17:56 UTC, Pandani07 submitted a review, later dismissed
Tested this PR and everything works as intended. I added the edit time entry permission for my admin account and I verified if I could change the time log description. The edited description is saved after the update as well. Nice work

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/f7767035-df98-4d3a-838f-98678f7e5283

2024-02-09 22:29 UTC, nathanah requested changes

2024-02-09 22:29 UTC, nathanah commented on src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
> +                  disabled={(!canEditTimeEntry && !initialIsTangible || canEditTimeEntryDescription)}
```suggestion
                  disabled={(!canEditTimeEntry && !initialIsTangible && !canEditTimeEntryDescription)}
```
Does this need to be inversed?

2024-02-09 22:29 UTC, nathanah commented on src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
> +    const isUserAuthorized = (canEditTimeEntry && canPutUserProfileImportantInfo) || canEditTimeEntryDescription || !edit || today.diff(date, 'days') === 0
```suggestion
    const isUserAuthorized = (canEditTimeEntry && canPutUserProfileImportantInfo) || !edit || today.diff(date, 'days') === 0
```
isUserAuthorized looks like it's only about changing dates of time entries, not descriptions?

2024-02-09 22:29 UTC, nathanah commented on src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
> +                disabled={!(canEditTimeEntry || canEditTimeEntryDescription) }
```suggestion
                disabled={!canEditTimeEntryDescription}
```
`editTimeEntry` should be replaced by more granular permissions (`editTimeEntryDescription` in this case)

2024-02-16 06:23 UTC, mohabbasd reviewed
Hello, I tested your PR and I added the permission to my test account from the owner account but unfortunately I cannot see any other user other than myself and even if I get other user's information I am not able to see the time entry.

<img width="1440" alt="Screenshot 2024-02-16 at 1 14 32 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/5ca806b6-8621-45ac-9b29-20fcfa5700ec">
<img width="1440" alt="Screenshot 2024-02-16 at 1 19 06 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/d79c4d1e-92d5-4046-bd03-ee78330b93e5">

2024-02-21 03:02 UTC, XiaohanMeng submitted a review, later dismissed
Hi, I tested this PR using the owner, volunteer, and admin roles, and everything worked as intended! After the owner granted permissions, volunteers could edit their own Time Entry Descriptions, while admins were able to edit the Time Entry Descriptions of other users. Please see the reference video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/1ae91b78-765d-4bba-9619-a9c6141293a5

2024-02-21 22:09 UTC, Coops023 approved these changes, later dismissed
Hi Jay,

i reviewed your PR and tested functionality of giving permission to a user without time entry editing permission and it is working as described by your instructions. well done!

<img width="834" alt="PR-1859-edited" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81972263/256ce20d-8833-45b3-8f05-c3c5bb33c11e">

<img width="507" alt="PR-1859-editform" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81972263/2489d2c0-69a8-41d4-9733-8852fc1af98b">

2024-02-22 04:43 UTC, Jingyii800 approved these changes, later dismissed
Hi, I have tested this feature, and it worked well. As an owner role, I can give one user permission to let it change the others' time log description. Please check this video for more details. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/de472d98-ac43-4623-9b4d-cad1097fdc8a

2024-02-22 05:52 UTC, ClemarNunes submitted a review, later dismissed
I tested your PR and worked as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/7d0ed21f-1b41-4257-be28-07d48732aebc

2024-02-23 22:03 UTC, Weiyao-Li commented
I've tested this feature, and it performed well. As the owner, I added the time log edition permission to volunteer. And volunteer can be 
<img width="1728" alt="Screenshot 2024-02-23 at 16 42 33" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/d4f2b037-18d8-4947-b0aa-992802c76232">
<img width="1728" alt="Screenshot 2024-02-23 at 16 39 24" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/33d0e3cd-6a07-4e79-9074-ae3e98339dad">
<img width="1728" alt="Screenshot 2024-02-23 at 16 39 17" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/d78b455a-3834-4292-af8d-f5c3bb921815">
<img width="1728" alt="Screenshot 2024-02-23 at 16 23 35" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/56914205-3ac6-482f-8fa2-f6aa0cd17e8c">
able to see and edit its own time log.

2024-03-08 02:34 UTC, SRamen1999 reviewed
All functionalities worked as intended. Used owner account and gave volunteer account timelog description permission and was able to edit past timelog descriptions.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/2a4e17d8-962c-4753-81fc-dd93de635d97

2024-03-19 17:10 UTC, rajnada commented
Hii,
I have followed the steps and review the functionality it's working fine for me.

Give permission to User
<img width="1400" alt="1859B" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25640436/d29b023f-a46f-46c2-8583-a941bfa99caf">

Initial Time Entry
<img width="1335" alt="1859B2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25640436/8d655515-595f-4f17-9da5-f8efa3d0e2a0">

Edit Time Entry
<img width="1300" alt="1859A" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25640436/54413bd9-de1b-4232-915e-da92787d2cdd">

2024-03-25 21:08 UTC, hetvi11110 requested changes
I attempted to log in as indicated here, but I'm facing a white screen on the user dashboard page. Here's a screenshot of the console error.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/7c51b80d-e540-497e-8ac4-2d403e3dbeb2)

2024-03-29 18:12 UTC, iven-yao requested changes
without the permission, users cannot even log in their own time entries, project/task drop down selection and notes input area are both disabled. 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/37cff07b-3030-4eb7-ac9a-0a28113de584)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/42c33c7e-6df0-4e5a-80fc-f286891bb1f6)

2024-04-01 20:07 UTC, kylepham requested changes
There is an error of undefined variable `fromTimer` that caused the app to display blank screen on startup. 
![Screenshot 2024-04-01 at 3 05 55 PM (2)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/a257eeae-1bb2-4e66-b731-21f1804463c3)


I temporarily put `const fromTimer = false` in the modal component and everything worked as intended.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/16fbe89d-7c09-4e07-a9f0-a744a64c560c

2024-04-01 20:07 UTC, kylepham commented on src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
> +                    disabled={!((canEditTimeEntry && !fromTimer) || canChangeTime)}
`fromTimer` is not previously defined.

2024-05-02 22:24 UTC, closed without merging