Luis add warnings component to dashboard
OneCommunityGlobal/HighestGoodNetworkApp pull request #1873
Opened 2024-01-24 05:13 UTC by luisarevalo21

# Description
<img width="863" alt="Screenshot 2024-01-23 at 8 49 55 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/7dae6db3-a541-4c6f-82d7-527493393a25">

The main functions I created was: 
A way to track warnings issued by an Admin or Owner account. 
8 Icons are displayed and can be selected assigning a warning
After 2 warnings assigend a modal will appear to provide options.
Issuing a warning will change the color to yellow (Future PR will send an email currently only an alert is issued)
Issuing a blue square will change the color to red (Future PR will create and assign a blue square)
Selecting a colored icon will delete it, a modal will appear to confirm the deletion. 

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
Created a warnings component inside of components
All notable files related to the component are inside of warnings. 
`Warnings.jsx` is the main file and maps over the user's warnings received from the backend.
The warnings are also filtered by blue yellow red then by date. 

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Login as an admin account.
4. Once the dashboard loads, you'll see a toggle button underneath every user
5. click the toggle button to view the users' warnings
6. Click an icon to assign a warning to the user' corresponding to the description. 
7. Once they receive more than 2 a modal will appear. 
8. 4 options are given issue warning, log warning only, cancel and issue blue square
9. log warning only will color the icon blue like normal
10. issue warning will color the icon yellow an alert will appear saying an email was sent (Future PR)
11. Issuing a blue square will color red and an alert will appear saying blue square was sent (Future PR)
12. Selecting a colored allows you to delete it.
13. You may toggle the button to remove the warnings component and will appear one you click it again. 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/ff425741-6b7f-4472-a5cb-cec7f3e2d56e

## Note:
This is the basis for the warnings component. 
I'll create other PR to add more warning descriptions, send emails, and issue blue square in the future. I just wanted to lay out a basis first then add to it. 
the following warnings appear and are unrelated to the PR 
<img width="349" alt="Screenshot 2024-01-23 at 8 20 35 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/274faedf-b48b-4f06-831d-fdeb6fdf6ce0">

2024-01-25 04:00 UTC, KevHnh requested changes
Appears that a specific backend must be used to review this PR. I get an error message when clicking on the "Tracking" button. I will review again when I get an update. 

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/3619ac72-f878-4fe3-a6c0-cd9755624332)

2024-01-25 04:02 UTC, luisarevalo21 commented
> Appears that a specific backend must be used to review this PR. I get an error message when clicking on the "Tracking" button. I will review again when I get an update.
> 
> ![image](https://private-user-images.githubusercontent.com/83934825/299533029-3619ac72-f878-4fe3-a6c0-cd9755624332.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNTU1NzQsIm5iZiI6MTcwNjE1NTI3NCwicGF0aCI6Ii84MzkzNDgyNS8yOTk1MzMwMjktMzYxOWFjNzItZjg3OC00ZmUzLWE2YzAtY2Q5NzU1NjI0MzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA0MDExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlODMxOTNhZjI4YmJmNDJlOWY4YmE5YzNiY2MzZDEyZjYzNTQyMTdjMWE1NGZjYmM0NWFiZjI0MDc2Nzg2NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XT-4L93hxcJHO_KIc_nAI8n-F9xrUF1-dbWWUn-iiM0)

@KevHnh 
Yes you must check into the backend the PR is https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/718

Please check in and follow the steps.

2024-01-25 15:42 UTC, Renanluizssx reviewed
Hi @luisarevalo21, i tested your application and i didn't get to see the team members tasks, look my review please:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/6846a641-4592-4fa8-bcc7-675d27482f3c

2024-01-26 11:37 UTC, Cavein254 commented
@luisarevalo21 Tested the pr and failed to receive the results as explained. The functionality fails with status code `404`


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/1a1c4fd0-5406-4d2b-83af-a2b48a21c53a

2024-01-26 15:37 UTC, SRamen1999 requested changes
After testing this PR I came across some problems. When using the backend PR https://github.com/OneCommunityGlobal/HGNRest/pull/718 the team members tasks would not load. 

<img width="1725" alt="Screen Shot 2024-01-25 at 7 32 13 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/356f1b43-b1b8-4782-816d-67e5eea187a8">

However when using the current development backend it would load the team members task but the functionality fails with status code 404

<img width="1724" alt="Screen Shot 2024-01-25 at 7 34 26 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/18d40371-d5a8-4ffd-b242-b58dedd1fa56">

2024-01-27 03:31 UTC, KevHnh submitted a review, later dismissed
Hi Luis, thanks for getting back to me with the backend issue. Everything works as intended. Excellent work on updating the UI only after the request is successful.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/1b634371-f86e-405d-ba0d-fb433f7f6a43

2024-01-27 04:44 UTC, luisarevalo21 commented
> Hi @luisarevalo21, i tested your application and i didn't get to see the team members tasks, look my review please:
> 
>  2024-01-25-13-09-33.mov

Hello 
Please make sure you are checking into the corresponding backend and running `npm run build && npm run start` 
when checking into the branch. then run the frontend with `npm run start:local`
Feel free to reach out via slack for further assistance. 
Thanks

2024-01-27 04:44 UTC, luisarevalo21 commented
> After testing this PR I came across some problems. When using the backend PR [OneCommunityGlobal/HGNRest#718](https://github.com/OneCommunityGlobal/HGNRest/pull/718) the team members tasks would not load.
> 
> <img alt="Screen Shot 2024-01-25 at 7 32 13 PM" width="1725" src="https://private-user-images.githubusercontent.com/56932664/300030821-356f1b43-b1b8-4782-816d-67e5eea187a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzA4NDMsIm5iZiI6MTcwNjMzMDU0MywicGF0aCI6Ii81NjkzMjY2NC8zMDAwMzA4MjEtMzU2ZjFiNDMtYjFiOC00NzgyLTgxNmQtNjdlNWVlYTE4N2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDA0NDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZTUwMWYwMjA4N2JmNGM0OTFlZTZkM2U0ODEwZmQ3NmFkNjM2MWE5NWUzNzdlYWQ1Y2UzYjI2OTRkOTkyNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n1EvikxoKW1oI7liRhXy8RMbF9eFEX21JOjlyg1xt5A">
> However when using the current development backend it would load the team members task but the functionality fails with status code 404
> 
> <img alt="Screen Shot 2024-01-25 at 7 34 26 PM" width="1724" src="https://private-user-images.githubusercontent.com/56932664/300031332-18d40371-d5a8-4ffd-b242-b58dedd1fa56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzA4NDMsIm5iZiI6MTcwNjMzMDU0MywicGF0aCI6Ii81NjkzMjY2NC8zMDAwMzEzMzItMThkNDAzNzEtZDVhOC00ZmZkLWIyNDItYjU4ZGVkZDFmYTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDA0NDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYTRkNzgyNDdiMjIwYjcxM2MzMjU4ZDQwMDMyY2E0Mzc3YWUxMTVmYjgwNzE5YWJmNjE1YTM5N2FlZmNkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FvhH6fderYH141djNpnwO1VWTxr3gAMapn-MkhAWiUQ">


Hello 
Please make sure you are checking into the corresponding backend and running `npm run build && npm run start` 
when checking into the branch. then run the frontend with `npm run start:local`
Feel free to reach out via slack for further assistance. 
Thanks

2024-01-27 04:45 UTC, luisarevalo21 commented
> After testing this PR I came across some problems. When using the backend PR [OneCommunityGlobal/HGNRest#718](https://github.com/OneCommunityGlobal/HGNRest/pull/718) the team members tasks would not load.
> 
> <img alt="Screen Shot 2024-01-25 at 7 32 13 PM" width="1725" src="https://private-user-images.githubusercontent.com/56932664/300030821-356f1b43-b1b8-4782-816d-67e5eea187a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzEwMDksIm5iZiI6MTcwNjMzMDcwOSwicGF0aCI6Ii81NjkzMjY2NC8zMDAwMzA4MjEtMzU2ZjFiNDMtYjFiOC00NzgyLTgxNmQtNjdlNWVlYTE4N2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDA0NDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZDE4NmZkMjNmMGJlYjM5NWIyNWMxZGRmYjRhNTZjNjFiMWRlZjI2MDY2MTg2YmMzYWNjOTAzZWQwZDBhMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ra9GjPWYowx8FrRX-R_3H779tBZ2ADKh0g0VgMidmsE">
> However when using the current development backend it would load the team members task but the functionality fails with status code 404
> 
> <img alt="Screen Shot 2024-01-25 at 7 34 26 PM" width="1724" src="https://private-user-images.githubusercontent.com/56932664/300031332-18d40371-d5a8-4ffd-b242-b58dedd1fa56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzEwMDksIm5iZiI6MTcwNjMzMDcwOSwicGF0aCI6Ii81NjkzMjY2NC8zMDAwMzEzMzItMThkNDAzNzEtZDVhOC00ZmZkLWIyNDItYjU4ZGVkZDFmYTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDA0NDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNzhiNGMwZDIxNGMyOWZlODg4ZTMyMDJkZjQ0NWQyMTQ0ZDZmNmUyZTYxZmYwMDc3Njg5Njc2Nzc5ZThjYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M_Ucgi8BBSSNR8f1ZsF0b-vPNiswfQfQyWcjsBt6IoA">

Hello 
Please make sure you are checking into the corresponding backend and running `npm run build && npm run start` 
when checking into the branch. then run the frontend with `npm run start:local`
Feel free to reach out via slack for further assistance. 
Thanks

2024-01-27 07:21 UTC, Sophie-lei approved these changes, later dismissed
Hey! I just tasted this PR. I think the most of parts are working as expected. The warning page pops up and the alert notification is working. However, the Style of the warning button looks different from the video you are sharing. it may need adjusted.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/4b80268e-3c81-4a7b-81cd-81905f1fa50f

2024-01-27 17:06 UTC, SRamen1999 submitted a review, later dismissed
Hi Luis, thanks for getting back to me. Everything works as intended.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/99db859f-a740-4aa0-8a5b-a24e29065d69

2024-01-27 19:41 UTC, xmyoot commented
Hi Luis, awesome work on this PR. I checked out to the two necessary branches and tested #1783 and #718, backend logging correctly but for some reason when I click the same warning multiple times, the state freezes and then I can’t add any more warnings to any users, also I wasn't able to see that modal after the second warning. Please reference the video: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15240538/fc662ef6-1adb-411b-929f-ae50b1f6bd4d

2024-01-27 22:34 UTC, 666saofeng approved these changes
Hi, I tested PR and  it worked as intended. Congrats!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/0b4929da-b524-4fd3-a004-b805b90a13ac

2024-01-28 01:35 UTC, BaileyM96 approved these changes
Good evening @luisarevalo21 I reviewed your PR and everything looks and works great I am excited to see how this feature will work for everyone.

## Videos


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/80c4ed21-d006-4ad3-a4c9-8cff5da0cda9

2024-01-28 02:04 UTC, galgalinidhi commented
Hi @luisarevalo21, I tested the PR and I don't see all the options under Tracking and the Tasks and Timelog component overlaps the Timer.
<img width="1379" alt="Screenshot 2024-01-27 at 6 01 20 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/6e46de15-49d5-418f-9bf6-9a69b081da27">

<img width="1379" alt="Screenshot 2024-01-27 at 5 56 04 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/3fb9acb8-00b7-43e9-afa9-8752ca792eeb">

Also, I see that some of the circles are already selected when I click on Tracking.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/78acd3ca-83c6-4a84-a24b-628e1e7c6934

2024-01-28 21:51 UTC, peterson337 submitted a review, later dismissed
Hi, I am testing and everything is working as intended.

![one comunnity](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/71933a81-2847-446c-8e96-5c52121ef162)

2024-01-29 00:07 UTC, X1aoZhang99 approved these changes, later dismissed
Hi Luis,

I test you PR with FE #1873, and I logged in as admin. All functionalities worked as intended, nice work! Please refer to the video. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/b9a3c73e-452b-4329-bbec-6b78a5e9cede

2024-01-29 03:29 UTC, luisarevalo21 commented
> Hi Luis, awesome work on this PR. I checked out to the two necessary branches and tested #1783 and #718, backend logging correctly but for some reason when I click the same warning multiple times, the state freezes and then I can’t add any more warnings to any users, also I wasn't able to see that modal after the second warning. Please reference the video:
> 
>  PR.1783+.718.mov

Hello 
Please make sure you are checking into the correct backend.
You linked a different Backend hence the errors.

here is the correct backend 
https://github.com/OneCommunityGlobal/HGNRest/pull/718
Once checked in, run the following comand `npm run build && npm run start`
Feel to reach out on slack if you have any further questions.

2024-01-29 03:33 UTC, luisarevalo21 commented
> Hi @luisarevalo21, I tested the PR and I don't see all the options under Tracking and the Tasks and Timelog component overlaps the Timer. <img alt="Screenshot 2024-01-27 at 6 01 20 PM" width="1379" src="https://private-user-images.githubusercontent.com/44816413/300229511-6e46de15-49d5-418f-9bf6-9a69b081da27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTkzNDgsIm5iZiI6MTcwNjQ5OTA0OCwicGF0aCI6Ii80NDgxNjQxMy8zMDAyMjk1MTEtNmU0NmRlMTUtNDlkNS00MThmLTliZjYtOWE2OWIwODFkYTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAzMzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzkxNDEyODNhMmFjZjVjMzhhMzk2YmMyODBjYzFiODYzNmVjZDUxM2EwMjBiODYyOTExYjAyNzc1YjNhZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1YYnHVCT-Nm7ljGp3RcW3MFIGWbnj3rM3ZwS_n-ohgY">
> 
> <img alt="Screenshot 2024-01-27 at 5 56 04 PM" width="1379" src="https://private-user-images.githubusercontent.com/44816413/300229517-3fb9acb8-00b7-43e9-afa9-8752ca792eeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTkzNDgsIm5iZiI6MTcwNjQ5OTA0OCwicGF0aCI6Ii80NDgxNjQxMy8zMDAyMjk1MTctM2ZiOWFjYjgtMDBiNy00M2U5LWFmYTktODc1MmNhNzkyZWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAzMzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTRiODAxZjBlNDI2ZDA3OGI5ZmM2OWUwYWU2MDAxMjc2ZWZlMmMxNzFjNWFjMTMwY2FmYTk2ZmIxNjZkMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CGoqECK8PPPYinkslm_nsFr239lCAdlllWbA2icoXxQ">
> Also, I see that some of the circles are already selected when I click on Tracking.
> 
>  Screen.Recording.2024-01-27.at.5.58.13.PM.mov

Hello
It seems you've checked into a previous version of my branch. 
Please fetch from this PR then run ` git pull` then ` npm run install` 

Feel to reach out on slack if you have any further questions.

2024-01-30 01:48 UTC, pshereen approved these changes, later dismissed
Tested the PR and all the newly implemented features are working as expected.
Logged in as admin user.

Click the toggle button to view the users' warnings - Working
Click an icon to assign a warning to the user' corresponding to the description. - Working
Once they receive more than 2 a modal will appear. - Working
log warning only will color the icon blue like normal - Working
issue warning will color the icon yellow an alert will appear saying an email was sent (Future PR) - Working
Issuing a blue square will color red and an alert will appear saying blue square was sent (Future PR) - Working
Selecting a colored allows you to delete it. - Working
You may toggle the button to remove the warnings component and will appear one you click it again. - Working

Video below shows the working of the features.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/95c9bd31-07e0-46e2-b5af-a7aaecc5d407

2024-01-30 20:09 UTC, Pandani07 approved these changes, later dismissed
Tested the PR and implemented features are working as expected.
Logged in as admin user

View warnings by clicking the toggle button - works
Assign respective warning to the user by clicking none colored circle - works
Delete warning by clicking colored circle - works
Modal appears when more than 2 warnings have been given
Scroll-bar in the warnings component works
Warnings hidden after toggle button is clicked - works

Clicking on any circle will not make that particular circle colored, it will increase the number of warnings issues, works as expected

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/c4404fb6-973d-42c7-8810-8fa77fd58c63



Additional web responsiveness checked

2024-02-01 18:35 UTC, Nahiyan-16 submitted a review, later dismissed
## Great work!
Hi Luis, I tested your PR and I have to say that you did a wonderful job. I logged in as an admin and was able to see the tracking toggle button underneath all users. I was able to access and issue warnings to each row. After issuing two warnings, a pop-up box appears with the correct options and each option works fine. Deleting warnings also works fine. I do have a suggestion for this pop-up box: 
![Screenshot 2024-02-01 132122](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/ba92bb19-eb9e-4092-bd18-c02ee98223a4)
As you can see there is a text where you are telling the user what the color of the circle will be but it doesn't change at all.  An option could be to update the word or even use a visual object to notify the user upon hovering over an option. 

Otherwise, this feature works as intended:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/c286e7a4-d7f9-4dbd-9f13-b8b83d4504d2

2024-02-01 23:30 UTC, ClemarNunes submitted a review, later dismissed
I tested your PR and logged in as an administrator. All features worked as intended.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/9a83690d-33a7-4dde-950f-3cbc218c9071

2024-02-01 23:58 UTC, yvonnep165 approved these changes, later dismissed
Hi @luisarevalo21 ,
I have tested the PR and the implemented features are working as expected. Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/a1ed9380-d2e3-48e2-9cc0-f8673c6ff1c7

2024-02-04 01:13 UTC, sucheta90 approved these changes, later dismissed
Hello @luisarevalo21 , I tested this PR as an owner, and was able to issue warnings to another profile. It works as intended. Great work! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/e10a1aee-3f8a-4984-a340-79f7b1df9f4f

2024-02-04 03:53 UTC, mohabbasd commented
Hello,
So I had a few issues first and after reading the comment I was able to get the PR review done exactly as intended.
This is the video in which this PR was executed successfully.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/50291908-95f3-492b-9807-b2d69b63e8ac

2024-02-04 04:08 UTC, mohabbasd submitted a review, later dismissed
Hello,
So I had a few issues first and after reading the comment I was able to get the PR review done exactly as intended.
This is the video in which this PR was executed successfully.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/2c7d8f57-d1e1-4757-aba3-94e62f258939

2024-02-13 19:12 UTC, Coops023 reviewed
When logged as an admin user, i was able to toggle between being able to showing and not showing warnings, add and remove warnings, log or issue warnings and blue squares. All functionality tests went well, great job implementing this feature. 
<img width="1440" alt="Screenshot 2024-02-13 at 19 45 36" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81972263/8f7bf83d-2f51-4ca3-86ba-bb5502757806">
![Uploading Screenshot 2024-02-13 at 19.46.04.png…]()

2024-02-13 19:12 UTC, Coops023 commented on src/components/Warnings/WarningItem.jsx
> +  const [warning, setWarning] = useState(null);
Perhaps grouping these in a state object could be an improvement as they all deal with the warning state?
`const [warningState, setWarningState] = useState({
  warning: null,
  deleteWarning: false,
  warningId: null,
});`

2024-02-13 19:54 UTC, XiaohanMeng reviewed
The admin account testing confirms the application works as intended with the following functionalities:

- Ability to toggle visibility of warnings.
- Assigning warnings is functional.
- Log warnings are correctly displayed in blue.
- Issuing a warning colors the icon yellow, and an alert appears indicating an email was sent.
- Issuing a blue square turns the icon red, and an alert appears indicating a blue square was sent.
- Warnings can be deleted, and the sequence of warnings remains correct even if they are not deleted in order.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/b62b12b1-3be4-4f3b-86ae-c85e382b0f05

2024-02-13 20:05 UTC, Coops023 approved these changes

2024-02-14 05:12 UTC, Jingyii800 commented
Hi @luisarevalo21, good job!  I tested the warning functions, it works well to 

- Open the "track" toggle button to see the warnings for each volunteer
- Delete the warning 
- Add warnings
- When there are more than 2 warnings, a window will pop up to choose the detailed warning issues
- Hide warnings by clicking on the "hide" button

I only encountered one issue. When I tried to delete one warning but accidentally clicked twice by mistake, there was a warning showing "error occurred when posting". Then I **MUST REFRESH** the whole page to continue working. Please consider adding a feature to partly refresh one volunteer's warning issues instead of refreshing the whole page manually.

Please refer to more details in my video.  

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/f150ed26-c505-4a44-a712-39aea7d1bed4

2024-02-14 05:18 UTC, Jingyii800 approved these changes, later dismissed

2024-02-14 08:41 UTC, XiaohanMeng submitted a review, later dismissed

2024-02-15 00:43 UTC, one-community commented
Thank you all, moving to final review!

2024-02-15 17:47 UTC, cvtqx approved these changes, later dismissed
Tested this PR and everything works as described, warnings can be issued and deleted and the changes are reflected in the UI accordingly. Excellent job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/18cc7e4e-200d-4ace-a676-6100a42aeb51

2024-02-16 06:11 UTC, one-community commented
Thank you all, merging!

2024-02-16 06:11 UTC, merged