Nathan permissions unit test utility
OneCommunityGlobal/HighestGoodNetworkApp pull request #1889
Opened 2024-01-27 05:24 UTC by nathanah

# Description
Creates a utility for creating auth objects with and without specified permissions to enable easier testing of specific permissions.

## Main changes explained:
- Created `getAllPermissionKeys()` in `PermissionsConst.js` for creating a flat list of every permission.
- Created `createAuthMocks()` in `mockStates.js` for creating test auth objects with only relevant permissions and with every permission except those.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. create a unit test using `createAuthMocks()` to test a permission or add it to an existing unit test

2024-02-13 03:49 UTC, nnamdixobi commented
Changes look good, the use of a comprehensive list of permission keys and the ability to create test auth objects with specified permissions or without specific permissions adds flexibility to the testing process. You might need to work on the testing for this though

2024-02-14 05:48 UTC, Jingyii800 approved these changes, later dismissed
I tested the createAuthMocks() function by adding a unit test for it. You worked great and passed the test! Please refer to the radio to see more details. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/e4917cdb-7935-464e-a85a-30e4404ab2c2

2024-02-15 17:34 UTC, DiegoSalas27 commented
Great work. I have also tested the utility file and it works as @Jingyii800 has already shown. Consider reviewing my suggested changes, and add the unit test as suggested by @nnamdixobi.

2024-02-15 23:08 UTC, DiegoSalas27 requested changes
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26840798/ab8bd48b-24be-48a9-9593-934ad8871b7c

I am attaching a video making to delve deeper into my comments

2024-02-16 03:02 UTC, nathanah commented on src/__tests__/mockStates.js
> +  const onlyPermissions = {...authTemplate, permissions: {frontPermissions: [...permissions]}};
good catch

2024-02-16 03:40 UTC, DiegoSalas27 submitted a review, later dismissed
Nicely done, Nathan.

2024-02-17 12:35 UTC, Sarthak32 commented
The code appears to be well-structured and commented. However, you may want to ensure that comments are clear, especially for complex logic like getAllSubpermissionKeys().
Also Consider adding error handling in case of invalid inputs to the utility functions, such as createAuthMocks().

2024-02-19 12:56 UTC, Coops023 submitted a review, later dismissed
Hi Nathan, 
I tested the createAuthMocks() function by adding a unit test. All of the tests passed i will attatch a screenshot of the tests. Good job!

<img width="1440" alt="PR-1889" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81972263/650ae742-59e0-4146-af8c-583de6b5cbef">

2024-03-25 16:44 UTC, kylepham submitted a review, later dismissed
All changes work well. I only have one nitpick, which is the redundant spread operator on line 1258 next to `allPermissionsExcept()`. Overall, great work.
<img width="1800" alt="Screenshot 2024-03-25 at 11 40 22 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/1d8b33df-3033-4b02-b721-06bf6e1d3034">

2024-03-25 16:44 UTC, kylepham commented on src/__tests__/mockStates.js
> +  const allOtherPermissions = {...authTemplate, permissions: {frontPermissions: [...allPermissionsExcept(permissions)]}};
Redundant spread operator on line 1258 next to `allPermissionsExcept()`. Removing it can improve the performance a little bit.

2024-03-30 11:45 UTC, Sarthak32 reviewed
Hi, I tested your PR the createAuthMocks() function by adding a unit test.

![Uploading Screenshot 2024-03-30 171347.png…]()

2024-03-30 23:11 UTC, anandsesha commented
Hi, I have written a unit test for the `createAuthMocks()` utility function. Specifically, I added two test cases:
- To verify the correct inclusion of specified permissions in the generated auth object.
- To verify the exclusion of specified permissions in the generated auth object.

The functionality works as expected.

https://www.loom.com/share/c5153903a0a8497fa1f3c7f0d358d947?sid=e1418368-3b8d-4f7e-a871-1bc2db75d658

![unit tests](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/98b652af-6ca6-478d-9577-9d298ace4810)

2024-04-12 02:26 UTC, merged