olena fixed issues in olena_likes_func  for reverted PR 1854
OneCommunityGlobal/HighestGoodNetworkApp pull request #1909
Opened 2024-02-02 15:12 UTC by olenadanykh

# Description

## Related PRS (if any):
This PR is the copy of reverted PR 1854 (https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1854) with corresponded change made in Lessons.css
-the only one change was made here to the file  Lessons.css:

Before:
<img width="926" alt="nav-unset" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/7e917043-b45f-4b02-bcf7-a5e9eb14db81">

After:
<img width="734" alt="nav-flex" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/f03e68d9-ee29-4b81-b2cc-077d434f73e3">

The problem was in Dashboard:
Before:

<img width="815" alt="dashboardbefore" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/1a861860-6269-462e-a525-591e9475635d">

After:

<img width="831" alt="dashboard after" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/19db3ed5-f19e-4c98-b364-892788126262">

2024-02-03 07:19 UTC, Sophie-lei approved these changes, later dismissed
Hey, I tested this PR as the owner role and admin role. the CSS style has been changed successfully.
<img width="1438" alt="Screenshot 2024-02-03 at 15 17 04" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/57ad50b0-e171-4716-834e-dcd578aa6619">
<img width="1440" alt="Screenshot 2024-02-03 at 15 17 44" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/d836e4fc-d0a9-4727-93ee-93d92dcdfab9">

2024-02-03 07:27 UTC, Sophie-lei reviewed
Hey, I tested this PR with the CSS style. It worked as expected. The "current week log " font size looks bigger than other tasks. Not sure whether it is on purpose to be like this.
<img width="692" alt="Screenshot 2024-02-03 at 15 24 43" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/4ee58fa9-db1a-46d4-a5be-ea5cadc5896b">

2024-02-03 15:50 UTC, ShengjieMao approved these changes, later dismissed
The layout now seems right with the sections. But also noticed the difference in the font size. the page looks like this:
<img width="983" alt="PR_1909" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/03ce2f32-7011-4f28-8747-889889246315">

2024-02-05 00:55 UTC, X1aoZhang99 requested changes
Hi Olena,

I've tested the PR, and there is a small issue. The font size appears to be unusually small across all tabs, with the exception of the "current week time log" tab. 

![Screenshot 2024-02-04 at 19 51 22](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/d382e206-cf0e-4a3a-9921-ef301848c24a)

2024-02-09 18:29 UTC, 666saofeng approved these changes
Hi, I tested this PR and the font size looks good on my side.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/0662b86c-ab3e-45ce-9d3c-9ce5ec3401ab)

2024-02-09 23:29 UTC, Pandani07 approved these changes
Looks good!
![Screenshot 2024-02-09 at 6 28 33 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/3336cee4-62d0-4c2d-9a02-0b71c7535027)

2024-02-10 18:51 UTC, TareqMia approved these changes
Hi @olenadanykh, tested the PR and everything looked good to me. Good job 👍 
<img width="1504" alt="Screenshot 2024-02-10 at 1 49 40 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/6e828e8f-4b72-4fc9-bef7-159ef3f057e2">
<img width="574" alt="Screenshot 2024-02-10 at 1 50 10 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/ca7b8fb1-08f0-4ba1-b162-a08ee57a5988">

2024-02-10 22:29 UTC, prnvjn approved these changes
Looks Good and responsive!

![Screenshot 2024-02-10 at 4 26 50 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/3525231/1912d8f8-a17a-4ca7-861f-c34e4c1907af)

2024-02-20 05:37 UTC, XiaohanMeng approved these changes
Hi, I tested this PR. Everything looks great! The font is fine, and the layout appears very comfortable.
![1909_result](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/8a6f7291-322e-4086-81d9-89fb5f9ef2ef)

2025-01-12 01:01 UTC, vishavk1992 approved these changes
I have tested this PR everything works as expected.

2025-04-17 22:50 UTC, closed without merging