Anirudh -  AddTeamsAutoComplete unit test
OneCommunityGlobal/HighestGoodNetworkApp pull request #1914
Opened 2024-02-03 01:01 UTC by belagaam

# Description

Unit tests for src/components/UserProfile/TeamsAndProjects/AddTeamsAutoComplete.jsx

## Main changes explained:

New File
- AddTeamsAutoComplete.test.js : Unit test case file

Test Cases:

![Screenshot 2024-02-02 at 8 01 24 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/e2bf6e67-2500-4883-83e0-2af8d443613e)

## How to test:
check into current branch
do npm test AddTeamsAutoComplete.test.js 
check if all the test cases pass

## Screenshots or videos of changes:

![AddTeamsAutoComplete - UnitTest working](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/46c3f8aa-0c39-49ad-9506-b3c98c4a0032)

## Note:
Include the information the reviewers need to know.

2024-02-03 14:38 UTC, ShengjieMao approved these changes
All tests passed.
<img width="448" alt="PR_1914" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/0a9f4eda-a1ed-4328-be6f-9fb3fc7c24fb">


Also got console error. Please check the image for detail.
<img width="678" alt="PR_1914(2)" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/51053e73-fea7-4551-8e0c-e7aea1dea4bb">

2024-02-03 16:40 UTC, 666saofeng approved these changes
All tests passed.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/f1989067-1c3c-4d78-a1c1-36c1fd4cbcc0)

2024-02-03 21:54 UTC, vikrambadhan approved these changes
Hi, I tested your PR and all the test cases passed!

![Week 23 - PR3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/cc82b610-9578-4933-aea8-8c596edb9ef4)

2024-02-04 01:21 UTC, iTvX commented
Passed, but your gihub npm test failed, please fix that.

![CleanShot 2024-02-03 at 17 21 29@2x](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/58f414cf-e255-402e-a9ae-7382666ca4ac)

Your unit test
![CleanShot 2024-02-03 at 17 20 11@2x](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/f37d0ef2-1650-40ec-8e86-2a64420ef9ce)

2024-02-04 02:26 UTC, xmyoot commented
Hello, 
Checked your test it passed successfully, please reference the photo: 

<img width="1268" alt="PR#1914" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15240538/b8714ed2-01c1-479d-9752-052ced1c9064">

2024-02-04 04:50 UTC, n0vay submitted a review, later dismissed
All test cases Passed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85691749/7842b277-f463-4c6d-82dd-b1bafb0ab75e)

2024-02-04 06:49 UTC, AaronPersaud approved these changes
Hi @belagaam, I've tested and everything passed! Good job.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/efaef433-21ee-40a3-8259-a6c136082d6d)

Please note you'll have to fix the `npm test` failing for github actions before it will be able to merge.

2024-02-06 19:30 UTC, Cloid commented
Sorry about that put the label in the wrong PR. Keep up the good work!

2024-02-08 14:41 UTC, beblicarl commented
All tests passed successfully

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/bbc406db-9fc3-4734-a6ac-d91ee2955d5e)

2024-02-08 14:42 UTC, beblicarl approved these changes, later dismissed

2024-02-09 02:12 UTC, prnvjn approved these changes
Hey, it clears all 6 tests, also you're missing to pass the key prop on line 45 on the map function. 


![Screenshot 2024-02-08 at 8 10 20 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/3525231/00b404f8-ec90-4233-88b4-de45fed869d7)

2024-02-10 16:02 UTC, KurtisIvey commented
Would love to get this moved to final review once the node build check is addressed as you've done great work here :D

2024-02-10 16:04 UTC, KurtisIvey commented
Would love to get this moved to final review once the node build check is addressed as you've done great work here :D

Please refer to the build logs as it looks to detail it pretty well.

2024-02-11 06:18 UTC, mohabbasd approved these changes, later dismissed
Hello, Tested this PR and all the test cases have passed.

2024-02-22 23:35 UTC, ChengyanOo submitted a review, later dismissed
All tests passed!
<img width="1195" alt="Screenshot 2024-02-22 at 18 35 15" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69735000/f4fe1c44-88cf-4832-be9a-56a2af5b440b">

2024-02-27 04:35 UTC, iTvX requested changes
The unit test should be placed in the folder named "tests." Please create a "test" folder and place the unit test under this folder.

Please fix the file location: src/components/common/Image/Image.test.jsx

2024-09-07 18:12 UTC, mohangadde1 approved these changes, later dismissed
![image](https://github.com/user-attachments/assets/87c82eac-ca48-4136-96af-397864d4be7b)
All test cases are passed.

2024-11-09 02:10 UTC, SatyashanthiT commented
I reviewed and tested this PR for the AddTeamsAutoComplete unit tests. All test cases are passing as expected, and the functionality is working well.
<img width="458" alt="image" src="https://github.com/user-attachments/assets/b5a1d84c-b4f5-47d4-9bf3-43d25ee77489">

2025-03-14 01:10 UTC, closed without merging

2025-03-14 01:10 UTC, sri0606 commented
@one-community , updated PR exists. This can be closed.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2646