Leo Add more specific link validation for GDoc links
OneCommunityGlobal/HighestGoodNetworkApp pull request #1915
Opened 2024-02-03 01:39 UTC by Chuehleo

# Description
![1706923423396](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/f11948df-8503-4a7b-8c0c-49c43cdb440d)

## Main changes explained:
- Updated EditLinkModal component to include validation for Google Doc URLs using isValidGoogleDocsUrl.
- Modified validation logic to accept any valid URL for the Media Folder input field.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to nav bar→ Welcome, XXX→View Profile→Edit(Under the Profile pic)
6. enter various URLs in the Google Doc link to test if only google doc links are allowed
7. verify that any valid URL can be entered in the Media Folder link

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/79f7152b-8259-49e6-9aad-92bc81ba3aaa

2024-02-03 06:50 UTC, Sophie-lei submitted a review, later dismissed
Hey, I tested this PR, and everything works as expected. I logged in as an owner role, it can be added Google Doc button with only the Google Doc link. and any URL can be used in the Media Folder link.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/72a87752-45a4-4dfa-8472-6007654813a5

2024-02-03 14:30 UTC, ShengjieMao approved these changes, later dismissed
The two functions worked as expected. Tested different input types and both text fields worked great based on criteria

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/a48a9ade-216e-4aa4-a6fe-ba8a4edcb3aa

2024-02-03 19:14 UTC, n0vay submitted a review, later dismissed
looks Good to me
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85691749/518e323e-8ca3-47e3-ab9d-311e2d085c6d)

2024-02-03 19:39 UTC, Pandani07 approved these changes, later dismissed
I tested this frontend PR with the latest development backend and the feature works as intended. I could only add google-doc links to the google doc links prompt. I could add other links to the media folder prompt and the links were saved.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/0b57fa80-a7d9-4399-990f-7080ea4d1235

2024-02-03 20:07 UTC, swathyjayaseelan commented
Works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/96c3bf59-be95-4eaf-b5f5-8b3aa9544cd7

2024-02-04 02:38 UTC, prnvjn approved these changes, later dismissed
Hey Leo, tested your PR and the functionality works as described. Tested it using the admin role. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/3525231/b866ae42-13f2-48f9-bbfc-41bef72f1d0e

2024-02-04 03:14 UTC, ClemarNunes submitted a review, later dismissed
I tested this PR and it is working as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/f42cdc85-c64c-442b-ba6d-5f1504996de6

2024-02-04 23:23 UTC, X1aoZhang99 approved these changes, later dismissed
Hi Leo,

I've tested your PR, and all functionalities worked as intended. Please refer to the video.  Nice work! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/b9247a5a-8497-46a7-bd11-a9fc62741a27

2024-02-05 16:10 UTC, 666saofeng approved these changes
Hi, I tested with the admin account and it worked as intended. Great work! Please refer to the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/5632e50d-60b2-4a2f-87f4-cdcbed12cb9d

2024-02-05 20:15 UTC, peterson337 submitted a review, later dismissed
Chuehleo, I tested your application, and everything worked as expected. Good job!

![one comunnity](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/754b1da0-af6b-4c0f-a649-e503752bdacb)

2024-02-10 06:45 UTC, yaow62023 approved these changes, later dismissed
I have test your PR, only specify google docs can be added to there. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/cfda269e-a3eb-47ad-9ce8-15f8e8629ccc

2024-02-12 04:35 UTC, navneeeth commented on src/components/UserProfile/UserProfileModal/EditLinkModal.jsx
> +    // This is a placeholder. You should define what constitutes a valid media URL for your application.
This ChatGPT-generated comment needs to be removed

2024-02-12 04:35 UTC, navneeeth commented on src/components/UserProfile/UserProfileModal/EditLinkModal.jsx
> +      handleSubmit(); // If you have additional logic to handle after submitting the form
This ChatGPT-generated comment needs to be removed

2024-02-12 04:49 UTC, navneeeth commented on src/components/UserProfile/UserProfileModal/EditLinkModal.jsx
> +      if (!isMediaFolderLinkChanged && !isWarningPopupOpen) { // Fisrt time media folder link is changed
Fix the typographical error in the comment: 'Fisrt'

2024-02-12 05:14 UTC, navneeeth requested changes
Hello, @Chuehleo! I tested your PR and the functionality works nearly as expected. Please address the changes that I have requested in the Observations and I will approve the PR. Thank you. 

## Observations
- The RegEx to update the Google Doc link works strictly and does not allow regular URLs to be entered as the Google Doc Link.
- The RegEx for the Media Folder allows a good range of permissible URLs in its RegEx design.
- The Google Doc link, however, does not accept 'http' or 'www' as the start of the Google document link which needs to be updated in the RegEx check. Please update the RegEx check to allow links that begin with 'http' and 'www'.
![http](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/b21810c9-5994-4521-8777-cc0dbf9257b8)
![www](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/1cbe0ebf-08db-4f27-9fda-da761479b901)

- The above error message: `Please ensure each link has a unique and not empty, and enter valid URLs.` is not grammatically correct. Please update it as: `Please enter valid URLs for each link.` in the paragraph tag in line 382: 
```javascript
<p className='invalid-help-context' data-testid='invalid-url-warning' >
                  Please ensure each link has a unique and not empty, and enter valid URLs.
                </p>
```
- In line 17, we are importing the following functions:
```javascript
import { isValidGoogleDocsUrl, isValidMediaUrl } from 'utils/checkValidURL';
```
For maintaining best practices, please update your implementation of the isValidGoogleDocsUrl and isValidMediaUrl functions directly in `src/utils/checkValidURL.js` instead of defining them again in the `src/components/UserProfileModal/EditLinkModal.jsx` file. Please also move the following implementation of `isValidUrl` into the `src/utils/checkValidURL.js` file while also including it in the import:
```javascript
const isValidUrl = url => {
    try {
      const pattern = /^(?:https?:\/\/)?[\w.-]+\.[a-zA-Z]{2,}(?:\/\S*)?$/;
      return pattern.test(url);
    } catch (err) {
      console.log(err);
      return false;
    }
  };
```
- The code needs to be proofread as it contains 2 AI-generated comments and a typographical error which need to be removed. I have highlighted them in my review with single-line comments.

### Testing Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/8facf55a-341c-40d8-95c2-cb84742893a2

2024-03-06 17:30 UTC, Weiyao-Li commented
Check 1, invalid url:
<img width="1716" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/0463ad16-1d2b-4cb4-9611-9113ba6ba7a4">

<img width="1728" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/af284a40-2df2-432e-a44c-a4d2161ba2db">


Check2, with the correct google doc link:
<img width="1728" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/f39330c0-0d1d-40a8-b110-764a551f9cf1">

Check3: invalid integer:
<img width="1728" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/2d8a434f-3d7a-4352-b553-8ca2f27ad0d3">

2024-03-06 17:35 UTC, Weiyao-Li reviewed
Reviewed

2024-03-06 17:36 UTC, Weiyao-Li approved these changes, later dismissed
Looks good, more detailed review in the comment

2024-03-13 05:38 UTC, Tiantian-C reviewed
Hi, I have tested this, it works well!
<img width="1438" alt="Screenshot 2024-03-12 at 10 36 18 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/81e23868-a653-4178-a0e9-f501e1933a28">
<img width="1439" alt="Screenshot 2024-03-12 at 10 36 45 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/3c337d7e-601e-4970-96f8-5142099a919a">

2024-03-30 18:47 UTC, rajnada commented
Hi,
I have checked the functionality. It works as mentioned. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25640436/4e0d9970-8e9d-4bad-80fa-2b53d07e4558

2024-04-11 17:03 UTC, one-community commented
Thank you all, merging!

2024-04-11 17:04 UTC, merged