Jay - Toggle Invisibility Self Others
OneCommunityGlobal/HighestGoodNetworkApp pull request #1922
Opened 2024-02-04 07:09 UTC by Alforoan

# Description
This PR enables the user with toggle Invisibility permission to manipulate the visible invisible toggle on the visibility column.

## Related PRS (if any):
This frontend PR is related to the [#688](https://github.com/OneCommunityGlobal/HGNRest/pull/688)  backend PR.

…

## Main changes explained:
- Added conditional logic so that the user with the permission is able to view it on his/her profile page and on other users' profile pages.
…

## How to test (watch video for step by step testing):
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to Other Links -> Permissions Management -> Manage User Permissions -> Choose a user without user management permissions such as volunteer or core team -> add Toggle Invisibility Permission Self and Others under User Management -> scroll down then submit
6. log into the account who was just granted the permission and go to its own profile page, click on teams tab, and verify visibility column is visible and toggling the switch works as well as saving (do the same on a different user's profile page)

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/af6b8f52-b066-4901-bf67-eedb58700017

## Note:
**Unmute the video.**

2024-02-06 16:54 UTC, TareqMia requested changes
Hi Jay, I tested this PR with backend PR #735 and everything worked as expected. I logged in using an Owner account and gave the permission to a volunteer account. I then logged in as a volunteer to verify that the visibility column was there. I also checked out another profile to make sure that the column was in the other profile as well. Really good work on implementing this.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/2d01c431-6b3d-4e6c-bb25-a64818662b98



#### Note: 
There was an issue with the tests failing when trying to run the app. Turns out there was a missing ```{``` in one of the files (I left a comment on the specific line) which was causing the error. Everything worked after that fix.

2024-02-06 16:54 UTC, TareqMia commented on src/components/PermissionsManagement/PermissionsConst.js
>          label: 'Manage Time Off Requests',
Missing opening `{`, causing tests to fail.

2024-02-13 03:17 UTC, nnamdixobi commented
Changes align with the backend and everything works as expected. Consider adding comments for the complex parts like the "fullCodeRegex" part and the "toggleToolTip"

2024-02-19 12:26 UTC, DiegoSalas27 commented
Hi, Jay. I have tested your PR and works as expected. I have attached a video with some questions regarding the invisibility functionality to learn what are the intended behaviors. In addition I have made a comment in the source code to request minor changes. Good work.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26840798/03e5de53-56c5-4d93-9e00-999b3a0b1406

2024-02-19 13:51 UTC, Coops023 requested changes
Hi Jay,
I have reviewed this PR and i am having some issues, first issue which had been stated by others in reviews was an error being thrown regarding a missing opening "{" i will leave a comment on the line that needs this. 

Secondly i am unable to toggle invisibility permissions of volunteer accounts when logged as an owner. however i am able to do this to core team accounts. i will attach screen shots showing this

<img width="1389" alt="PR-1922-volunteer" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81972263/f2d8bd2f-df7a-4273-a34c-1097f0f8c0a4">

<img width="912" alt="PR-1922-core-ex" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81972263/354ae52d-0bee-480f-8724-9f40637ad7e4">

2024-02-19 13:52 UTC, Coops023 commented on src/components/PermissionsManagement/PermissionsConst.js
>          label: 'Manage Time Off Requests',
Missing opening `{` causes error

2024-02-19 22:25 UTC, XiaohanMeng requested changes
Hi, I tested this PR and initially encountered a compilation failure. Adding a left brace resolved the issue, allowing the program to run successfully. 
![1922+735_error](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/a27c3b2c-4c32-473d-94e0-36457b385b50)

I then attempted to assign permissions to both the core team and volunteers using the owner account. The process worked as intended for the core team account. However, when assigning permissions to the volunteer account, the button remained fixed, preventing the assignment of permissions. Please refer to the attached video for further details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/66a2400e-c92f-491f-a7e9-c42f36d0b9a4

2024-02-22 01:13 UTC, skaush21 requested changes
- did npm install got a message in terminal stating that there is a missing syntax.
- went to components/PermissionsManagement/PermissionsConst.js and added the missing open brace at line 67.
- saved changes, ran it again, cleared data/cache
- logged in as owner user
- went to Other Links -> Permissions Management -> Manage User Permissions -> volunteer -> add 'toggle invisibility permission self and others' under user management,
then hit save.
- signed out, logged in as volunteer user, went to profile page, clicked teams tab, verified visibility column is visible and toggling switch and save feature work. tested different users page by opening their profile page. feature works.

<img width="582" alt="PR 1922" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/6628a15c-fb21-4527-abb7-daf9095c6913">

<img width="607" alt="PR 1922" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/414bb5e7-465d-4bea-bff7-ddfde98047a5">


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/5b31c42f-b31a-43f1-8de0-da9bda5df1c0

2024-02-22 06:37 UTC, Jingyii800 requested changes
Hi, a left open brace "{" is missing in the PermissionsConst.js, which causes the compile to fail while running the webpage.
After modifying it, the feature works well; the user given the permission can select the visible/invisible state under the profile.
<img width="556" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/68286471-3714-4de9-8fde-5e61611c7b71">

<img width="556" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/a8ec538c-0457-4073-9bea-9c7332650c44">

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/bc48874b-93a4-4bab-a922-1046852629f6

2024-02-23 11:06 UTC, Gugor99 requested changes
### Report
Hey Jay,
As mentioned from others I found a typo in the PermissionsConst.js file. Once corrected it, the implementation worked perfectly on my machine.
Logged in as volunteer to check I didn't have permissions to interact with the invisibility toggle. I then logged in as owner to change the permission. Once back on my volunteer account I was able to toggle the visibility of both mine and others profiles. Good job!
### Screenshots
![Cattura1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/2f7bfa50-c874-4f88-8dae-b602259f7432)
![Cattura2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/08364804-24db-458a-a388-d1ba816e78a4)
![Cattura3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/f62219ef-c409-4b80-b094-e49b780fac81)

2024-02-24 00:20 UTC, Weiyao-Li commented
When i run npm run start:local, this happened. I think there are unexpected tokens

<img width="1342" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/126a480f-3d46-4a63-a77c-b79b5c43108c">

2024-02-24 18:24 UTC, PratimaSingh02 requested changes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/48998232/664a6898-4af6-422e-9e9d-697d07b1f9ee)
Please add an opening curly braces on line 67 in PermissionsConst.js file

2024-02-24 19:14 UTC, PratimaSingh02 reviewed
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/48998232/8e7f8d78-caa8-44f6-afde-236920c13ff0


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/48998232/c3a3ba62-b8c5-47c0-ae77-10b4f618f016

Working as expected.

2024-02-24 21:17 UTC, ClemarNunes requested changes
As others have pointed out, I came across a typo in the PermissionsConst.js file. Once corrected, the implementation worked flawlessly on my machine.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/003c9bf3-35a8-4f88-a68b-b656f2842be2

2024-03-01 13:15 UTC, Sarthak32 commented
As people have already suggested, there was a typo in the PermissionsConst.js file. I corrected that, and it worked fine.
![Screenshot 2024-03-01 184441](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/a2e36181-2123-46d5-a0bb-165b644f83b7)
![Screenshot 2024-03-01 184441](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/de20dda1-f781-47f0-ab01-9e7138bb106b)

2024-03-02 23:21 UTC, brandta-1 requested changes
# Review
As others have mentioned, a typo must be fixed for the app to run, once fixed, visibility toggling is fully functional.

![00_missing_brace](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/b459dbe8-60a4-46e2-8cf4-036ddd007912)

# Video


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/25333126-5642-4ad5-ac53-0c5ffe3a5dd4

![02_visible_teams](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/3a6fcdf1-140d-499d-9752-dcf7550725a4)

2024-03-03 22:53 UTC, psharma1984 requested changes
Hi @Alforoan After fixing the typo error the functionality works as expected. Please see the screenshots below for the error and a working functionality thereafter
![a](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/f9e4c56c-c24e-4c9a-856d-5575d183da76)
![b](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/fd3c8bfd-0987-4f44-a355-c3e785fc421b)
![c](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/90ff45b6-4f6e-4fbb-a232-5829b8e5383d)
![d](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/e7ea36c8-eb00-4058-9a32-308e45f05b6e)

2024-03-14 15:14 UTC, nathanah requested changes

2024-03-14 15:14 UTC, nathanah commented on src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
> +          {(props.canEditVisibility || canToggleInvisibility) && (
```suggestion
          {(canToggleInvisibility) && (
```
Should replace/remove `canEditVisibility` from props and include logic in `canToggleInvisibility`

2024-03-14 15:14 UTC, nathanah commented on src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
> +          {(props.canEditVisibility || canToggleInvisibility) && (
Should also replace at line 147.

2024-03-14 15:14 UTC, nathanah commented on src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
> +  const canToggleInvisibility = props.hasPermission(('toggleInvisibility'));
```suggestion
  const canToggleInvisibility = props.hasPermission(('toggleInvisibility')) && targetIsEditable;
```
include logic for `canEditVisibility`

2024-03-14 15:14 UTC, nathanah commented on src/components/UserProfile/UserProfile.jsx
> +  );
```suggestion
  const canToggleInvisibility = props.hasPermission('toggleInvisibility');
```

2024-03-14 15:14 UTC, nathanah commented on src/components/UserProfile/UserProfile.jsx
> +                      {(canEdit || canToggleInvisibility) && (activeTab == '1' || canPutUserProfile) && (
Should be replacing logic instead of adding to it.

2024-03-14 15:14 UTC, nathanah commented on src/components/UserProfile/UserProfile.jsx
> +
Should be replacing logic instead of adding to it.

2024-03-14 15:14 UTC, nathanah commented on src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
> +    this.canToggleRequestBio = hasPermission('requestBio');
```suggestion
    this.canToggleRequestBio = props.hasPermission('requestBio');
```
this is for another PR... should rebase your commits relevant to this PR onto dev.

2024-03-15 19:59 UTC, SRamen1999 reviewed
After fixing the typo the PR works as intended.

Here is the typo location and solution

<img width="1728" alt="Screen Shot 2024-03-15 at 3 54 47 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/9db16ad8-821b-4a55-be50-48557f55bedd">

<img width="1728" alt="Screen Shot 2024-03-15 at 3 55 35 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/0a86c0ba-f23a-4971-a9e2-9f758738f3df">

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/142fbc0a-e736-4c89-be38-5f30660c9178

2024-03-19 22:27 UTC, iven-yao requested changes
One error in PermissionsConst.js line 67, missing a  `{`
After fixing this, it works as expected.
1. Log in as owner
2. add permission to a volunteer role `Toggle Invisibility Permission Self and Others` and submit
3. Log in as the volunteer role
4. the visibility column is shown as expected.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/94bdae6e-8d60-48c8-aaee-c287398280de)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/9bb5bad2-0ac4-4fae-b367-21bcfd331d3d)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/b86dfe08-3c97-4f71-8ce6-67d04046d243)

2024-03-27 21:10 UTC, hetvi11110 requested changes
I have tested this PR as mentioned, but after adding "{" on line 67 in the PermissionConst.js file, it compiled without any errors. Here is the reference image:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/84485419-aee1-4a68-84e3-f61e360c7b53)
The Toggle Invisibility Self Others permission is working as expected. Here is the reference video:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/323ac1a2-64d0-4190-8e2f-790c5644eb43

2024-03-28 20:48 UTC, kylepham requested changes
Invisibility button showed up as I granted my Core Team account this permission from the Owner account.
![Screenshot 2024-03-28 at 3 45 18 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/926639c4-6b95-4020-bd99-c0b4487c4181)
And as everyone else pointed out, there is a syntax error in `PermissionsConst.js`.

2024-03-29 02:22 UTC, MQChen211 requested changes

2024-03-29 02:22 UTC, MQChen211 commented on src/components/PermissionsManagement/PermissionsConst.js
Hi Jay, I tested this PR. While the login page loads as expected, I encountered issues with the sign-in functionality. Specifically, I was unable to sign in using either the owner or admin credentials. Although the buttons are correctly positioned, there is a problem with entering information into the input fields and triggering the submit action.
<img width="1139" alt="PR#1922" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/61409fee-d30f-4e69-b925-04f2d7b0f87c">

2024-04-06 21:46 UTC, Tiantian-C reviewed
Hi Jay,
When I tried to run the frontend, it has some errors.
<img width="978" alt="Screenshot 2024-04-06 at 2 45 36 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/b64651d3-d7ad-439a-aee7-f708565ffa9b">

2024-05-08 03:21 UTC, closed without merging