Ilya consumables add page
OneCommunityGlobal/HighestGoodNetworkApp pull request #1926
Opened 2024-02-07 20:01 UTC by ilyaflaks

# Description
<img width="754" alt="consumables-add" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/a75e41b6-91e3-491d-a36c-cf2aece3c21a">

Adds functionality for the user to navigate to /consumables/add, enter the required information (consumable name, description, measurement units, size) and create a new consumable type in the system.

The front end validates the input to have a name that is at least 4 characters long and a description that is at least 10 characters long. The back end checks if a consumable under the same name already exists.

## Related PRS (if any):
This frontend PR is related to the [back end PR#737](https://github.com/OneCommunityGlobal/HGNRest/pull/737)
To test this front end PR you need to checkout the #737 back end PR, branch **ilya_consumables_add_page**
…

## Main changes explained:
- /consumables/add route added to the front end router
- AddConsumables component includes a form with validation that makes a POST request to the backend
- The new component is styled to accommodate smaller screens 
- Necessary Redux actions and Reducers created
- Existing files formatted with ESLint and Prettier

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to [http://localhost:3000/bmdashboard ](http://localhost:3000/bmdashboard) and log in again
6. go to [http://localhost:3000/bmdashboard/consumables/add](http://localhost:3000/bmdashboard/consumables/add), enter some dummy data, press "Add Consumable" when the button is enabled
7. A success message should appear if everything is acceptable or a warning message if not (such as a duplicate value)
<img width="1127" alt="consumables-fe" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/0f6334ab-6c81-49cc-82bf-3a99fbd787a2">
8. In MongoDB Compass open hgnData_dev.buildingInventoryTypes collection. Press "Find", scroll all the way to the bottom or search by name and verify that the entered information is saved in the database
<img width="1419" alt="compass" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/08034d00-5c9e-4aeb-8232-f7d6037cd935">

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/a5600668-ccf6-4e3b-b5e7-b52be3e7cb7f

## Note:
Examples of construction consumables can include nails, screws, batteries, lumber, etc.

2024-02-08 02:11 UTC, Pandani07 approved these changes, later dismissed
Tested this PR and i could add a new consumable. I got a screen success message after I added a new entry.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/62e1f610-5885-4f35-b94d-779a7436a798

2024-02-08 17:20 UTC, meetpadhiar4 commented
I have tested this PR and all the changes and functionalities are working properly. Please see the attached video for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/62424d0a-d0ec-437b-94fc-5de71f04f2e6

2024-02-08 17:25 UTC, meetpadhiar4 approved these changes, later dismissed
I have tested this PR and all the changes and functionalities are working properly. Please see the attached video for reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/dda6cc1e-6225-4bd0-a7fc-afaf5fb2316b

2024-02-09 01:25 UTC, ClemarNunes approved these changes, later dismissed
I tested your PR and everything worked as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/2e0b8748-e2ea-4d88-bda3-fc816f40fc74

2024-02-09 06:55 UTC, ShengjieMao approved these changes, later dismissed
No problem with either the front/backend. Function worked as expected, and the check for inputs also considered the different cases. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/c34ce231-35fb-43d9-8ffd-17f20ef49033

2024-02-09 18:10 UTC, n0vay approved these changes, later dismissed
Looks Good to me
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85691749/bece3850-6d7f-4e85-b1ee-23d5210b7d88)

2024-02-10 00:55 UTC, Renanluizssx requested changes
Hi @ilyaflaks 
, i followed your steps but in my case, the message appear an error, look my review please:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/8789db30-0f50-400b-9b0e-8e8d425ac0e2

2024-02-10 01:09 UTC, Renanluizssx approved these changes, later dismissed
Hi @ilyaflaks, i made a mistake, now i added in correct branch, see my review:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/f7719a1e-abd0-4e54-aae3-f1d2f6ce0fed

2024-02-10 03:50 UTC, SaiDeepak-NEU requested changes
Hello Ilya,
I have tested the changes mentioned in the PR and found one issue.

When I am entering an empty object in the consumable name by just entering space 4 times, it is still considering it as an accepted value.
The same goes with description and size. The button is getting enabled and I am able to create a record for empty values . Please see the attached screen shot.
![Screenshot (86)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114311909/26f34049-9984-4b41-a805-7ea96e3e8368)
Rest everything worked fine. successful popup on correct record creation and warning message on duplicate record creation.
![Screenshot (85)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114311909/8a68aeff-ddbf-4c6f-b6ff-9a24fbeb830a)
![Screenshot (84)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114311909/06fd85b5-f898-46a7-b903-88eed8d9b2e2)

2024-02-11 01:01 UTC, TareqMia commented
Hi @ilyaflaks, I tested your PR with the associated backend PR and everything worked as expected. However, adding on to what Sai mentioned above, the Consumable Name, Description, and Size fields can all be submitted using the minimum number of required characters (ex. 4 for name). Other than that, great job on this 👍 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/de595939-43a7-4c27-8b44-347618179771

<img width="1624" alt="Screenshot 2024-02-10 at 7 56 40 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/a0d18e83-22ce-451b-816e-0c4fd98e8412">

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/3031077b-ff03-4f94-b49e-8acd544c6dc6

2024-02-11 22:05 UTC, 666saofeng approved these changes
Hi, I tested with admin account and it worked as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/c9d4c590-aa29-4ea7-a63a-0daa07c641b4


![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/6afcdb18-9a48-4fbd-88b8-a41038b7554d)

2024-02-12 18:32 UTC, ilyaflaks commented
> Hello Ilya, I have tested the changes mentioned in the PR and found one issue.
> 
> When I am entering an empty object in the consumable name by just entering space 4 times, it is still considering it as an accepted value. The same goes with description and size. The button is getting enabled and I am able to create a record for empty values . Please see the attached screen shot. ![Screenshot (86)](https://private-user-images.githubusercontent.com/114311909/303812495-26f34049-9984-4b41-a805-7ea96e3e8368.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NjIyMDUsIm5iZiI6MTcwNzc2MTkwNSwicGF0aCI6Ii8xMTQzMTE5MDkvMzAzODEyNDk1LTI2ZjM0MDQ5LTk5ODQtNGI0MS1hODA1LTdlYTk2ZTNlODM2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxODE4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDJiMmE2NDc5ZDYxZWJlNzdmYjc3ZDAzYTExMzJjYjU5NDllYmQzYTUwYjU4MmM0ZDY1YmJiNWFhYTY1Y2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G-Urhf33SQyl0x6AY3ckhg6pZzTclqvuRvERa5CKWv4) Rest everything worked fine. successful popup on correct record creation and warning message on duplicate record creation. ![Screenshot (85)](https://private-user-images.githubusercontent.com/114311909/303812532-8a68aeff-ddbf-4c6f-b6ff-9a24fbeb830a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NjIyMDUsIm5iZiI6MTcwNzc2MTkwNSwicGF0aCI6Ii8xMTQzMTE5MDkvMzAzODEyNTMyLThhNjhhZWZmLWRkYmYtNGM2Zi1iNmZmLTlhMjRmYmViODMwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxODE4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjU2MDhmYjc4OTA0OGRlMDBhZWRlYzA4MGZiMTIyZDMxNjMwMzBkMGY2NWM4MjM0M2FhNmViMzhkNGIxNWViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xZz8R2ZsyMaXwvFgcVxov_92PNv2B85bqJPMNs1YNQ0) ![Screenshot (84)](https://private-user-images.githubusercontent.com/114311909/303812534-06fd85b5-f898-46a7-b903-88eed8d9b2e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NjIyMDUsIm5iZiI6MTcwNzc2MTkwNSwicGF0aCI6Ii8xMTQzMTE5MDkvMzAzODEyNTM0LTA2ZmQ4NWI1LWY4OTgtNDZhNy1iOTAzLTg4ZWVkOGQ5YjJlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxODE4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGI5ODI5ZGUyYmY2YzMzZmM5NzYyMzc2MTBjMmZiYWE5ZjkzOWJkNWIyZGVhM2U0ODY0Y2I5YTM0MTUwZmYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hd5e78HK4xU7QjQksfan4QUPm7VlATOkzg_jBbTkbz8)

@SaiDeepak-NEU and @TareqMia Thank you for catching that! I added non-white space validation on the front end to "name", "description" and "size" fields. Please review when you have a chance

2024-02-13 21:21 UTC, mianmiantea2019 commented
I have tested this PR and some edge cases, functionalities are working properly. Good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/e47b37f6-dca1-452a-bf23-02cdf6372505

2024-02-15 16:28 UTC, peterson337 submitted a review, later dismissed
Hi ilyaflaks, I tested your application, and everything worked as expected. Good job!

![one comunnity](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/abbd2e77-0188-4606-9459-f2069233e36c)

2024-02-15 21:21 UTC, Jingyii800 submitted a review, later dismissed
Hi @ilyaflaks, I have tested this feature with the backend PR, and it works as expected. Great work! I only have one concern, when I enter digits and special characters into "consumable name", it could also be recognized as value. I am wondering if you designed to accept this. Please check more details from my video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/600f0b4a-4873-41e0-b37c-e23a0de660e4

2024-02-18 03:47 UTC, brandta-1 approved these changes, later dismissed
# Review
Tested functionality using MongoDB and front end web application. Successfully logged into the building management dashboard and created a consumable. When the consumable was created, the application logged ```! vali err```. However the document was successfully created in MongoDB. Referenced this review on the [back end](https://github.com/OneCommunityGlobal/HGNRest/pull/737#pullrequestreview-1887074584).

# Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/1de9ac3d-d6c3-4744-a3f4-054a3ba944f0


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/ec8d6e6a-05ae-482e-807e-d6302ac8a437

2024-02-19 17:54 UTC, ilyaflaks commented
@Jingyii800 Thanks for bringing up the issue of entering digits and special characters in the name. I have discussed this with the team manager and we agreed that the validation needs to allow these characters. We can not predict all of the possible scenarios but some consumables might have those characters in the name. For example, WD-40 has both a number and a character. 

@brandta-1 Looks like I forgot to delete a console log! Thanks for catching that, I'll remove it shortly

2024-02-24 00:03 UTC, XiaohanMeng submitted a review, later dismissed
Hi, I tested this PR and found that it functions excellently—well done! I verified the following:
* Successfully added a consumable and received a confirmation prompt upon submission.
* Attempted to add a consumable with the same name and received a duplication warning.
* Confirmed that only the successfully added consumables are visible in MongoDB Compass.
Please refer attached video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/0e91b37d-6598-40e5-8c5a-539e1d808e3a

2024-03-16 16:53 UTC, 20chen-7 submitted a review, later dismissed
Everything looks good, and I could find the created inventory type in the MongoDB.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/447596b9-615a-4183-9d4f-a577c27771ff

duplicated name
<img width="952" alt="Screenshot 2024-03-17 at 12 31 37 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/e88ca110-67af-41e7-a20e-f247c94147c3">
<img width="752" alt="Screenshot 2024-03-17 at 12 48 23 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/3722671c-6cb6-4b4e-8d2a-2f9ee40452ba">

2024-03-26 22:06 UTC, ilyaflaks commented
@one-community can you please merge this PR into "development"? All of the changes requested have been addressed and I resolved the merge conflicts. Let's close this before more merge conflicts arise. Thanks

2024-03-28 18:40 UTC, MQChen211 approved these changes

2024-03-28 18:40 UTC, MQChen211 commented on src/actions/bmdashboard/invTypeActions.js
Hi Ilya, I tested the PR and successfully added a new consumable and got a message. Here's the screenshot.

<img width="1474" alt="#1926" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/3bc34fab-6999-47a1-9788-ac94ee5afe67">

2024-04-01 19:12 UTC, merged