Equipment_List_View_Frontend
OneCommunityGlobal/HighestGoodNetworkApp pull request #1937
Opened 2024-02-11 00:37 UTC by Aishwaryak01

Description
This PR is about the EquipmentsList View from Phase 2 with Sorting based on project name and item name, Filtering based on selected values of the project and equipment, and Modal implementation for viewing update and purchase history.
Implements # (WBS) 9.1.1

Related PRS (if any):
This frontend PR is related to the # backend PR.

Main changes explained:
Created components for Equipments

How to test:
1. check into the current branch
2. do npm install and npm run start: local to run this PR locally
3. Clear site data/cache
4. log as an admin user
5. verify all the table functionalities like open/close modals, sorting, and filtering for equipments view

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91091456/d95be2de-5a58-4ccb-9b62-30a6c3716964)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91091456/1b4e8fee-50f7-4182-ada6-fc95ca994297)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91091456/e217fd4a-80c0-4247-92cf-172c69875606)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91091456/4b957248-f50e-4fba-897a-0ea2cd63d774)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91091456/53363a82-d74f-438f-9220-e5df3a700d3e)

2024-02-11 16:19 UTC, 666saofeng requested changes
Hi @Aishwaryak01, It seems that the equipment's page cannot be rendered on my side. Please refer to the video for the details

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/08e5ff33-082a-4ca3-b6f9-b6a34b2d968a

2024-02-13 17:54 UTC, peterson337 approved these changes, later dismissed
HI Aishwaryak01, I tested your application, and everything worked as expected. Good job!

![one comunnity](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/2fcbd09b-6723-42df-a68d-9b29a0046f6d)

![one comunnity](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/7575f01e-7d67-4a48-9816-2432982bea18)

2024-02-13 20:28 UTC, mianmiantea2019 commented
Hi @Aishwaryak01. The equipment page cannot be rendered on my side, the 'equimentslist' is undefined.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/6d39895f-a252-4384-8fb4-4e4928d737a5

2024-02-14 13:04 UTC, ShengjieMao reviewed
Hi, I also met errors when loading the equipments page. The page doesn't rendered properly, and received error messages in console saying missing properties. Most of these properties are suggested to be in the equipmentslist file. The error message looks like:
<img width="460" alt="PR_1937" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/95ff16d4-993a-45ef-a14e-f909ce83a507">

2024-02-14 17:55 UTC, meetpadhiar4 requested changes
Hi, I reviewed your PR and it is giving errors while rendering the equipments page. Please refer the video attached for your reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/b59fe352-3cd5-474c-8652-e5b7c6fd8dc7

2024-02-16 00:24 UTC, Aishwaryak01 commented
@mianmiantea2019 @ShengjieMao @666saofeng @meetpadhiar4  Can you check now? I have made the necessary changes.

2024-02-17 19:28 UTC, swathyjayaseelan commented on src/actions/bmdashboard/equipmentActions.js
> +        console.log("Equipment is", res);
Please comment out or remove the log statement.

2024-02-17 19:33 UTC, swathyjayaseelan approved these changes, later dismissed
The changes look good.
 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/c35801b0-a15b-4765-90e1-e7d67521f34a

2024-02-18 02:48 UTC, TareqMia commented
Hi @Aishwaryak01, I tested out this PR and the equipment table looks good and everything functions as it is supposed to (sorting, modals). However, I did notice that when I try to view the purchase modal for:
<img width="778" alt="Screenshot 2024-02-17 at 9 46 10 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/c3f062b0-2fdb-4626-a0af-b951dc090f73"> 

the app crashed. I think it might have something to do with the actual dummy data being faulty. Just wanted to bring that to your attention. Other than that, everything else looks good 👍 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/b7a7e154-5216-42da-b0db-3d1b03bc6be6

2024-02-23 00:28 UTC, Aishwaryak01 commented
@TareqMia : I cross-checked the PR again and as you said found out that there was some issue in the collection. So no changes are required in the code

2024-02-23 00:52 UTC, XiaohanMeng reviewed
Hi, I tested this PR with an admin account and encountered the same issue TareqMia mentioned. I verified all functionalities for the equipment view, including modals, sorting, and filtering. However, when clicking the purchase button on the second row, the same error occurred. Please see the attached video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/4df6cafc-2f2c-496d-beb3-b330c795e062

2024-02-24 00:24 UTC, Aishwaryak01 commented
Can you check now as I have fixed the issue in the collection?

2024-02-24 06:05 UTC, skaush21 approved these changes, later dismissed
- logged in to admin account, navigated to bmdashboard
- logged in again, navigated to equipments
- tested project/name tabs, clicked on each view button, tested the drop down menus
- all features work
- the issue mentioned in the previous comment has been fixed


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/610ffcc3-8fd3-473f-8b0c-3bfe720a38a0

2024-02-24 22:50 UTC, brandta-1 approved these changes, later dismissed
# Review
Tested all sorting arrows, dropdown menus, and view buttons. All components were functioning correctly.

# Video


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/d8d11385-8586-4d6a-a9b3-4dd38cbfea41

2024-02-26 17:46 UTC, meetpadhiar4 submitted a review, later dismissed
Hi, I reviewed the PR again and the code now works correctly. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/ed8d135d-3276-4f3b-b0bc-c4d79a19cc36

2024-02-27 01:16 UTC, XiaohanMeng requested changes, later dismissed
Hi @Aishwaryak01, I retested this PR, and all the previously mentioned issues have been resolved. Great job!
However, I've encountered some minor issues related to sorting:
* Initially, when I enter the page, the arrow next to 'Project' points upwards, indicating that the projects are sorted in ascending order. However, after clicking the 'Name' column's arrow a few times and then returning to click the 'Project' column's arrow, the 'Project' arrow points downwards while still sorting the content in ascending order. A similar issue occurs with the 'Name' column.
* The filters for 'project' and 'name' work well initially, displaying data correctly. But, when I click the sorting arrows for 'Name' or 'Project', all data appears, ignoring the applied filters. I'm not sure if this is intentional.
Please refer to the attached video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/92a3c44e-6931-418a-b1f8-9e6db24229ee

2024-03-06 17:22 UTC, Weiyao-Li commented
Hi, while reviewing your pr, I encountered sever side error. Please have a check. I have attached relevant screenshots about the situation.

<img width="1209" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/5d7df20d-838c-4e12-8003-fe93c6f9d0ba">
<img width="1728" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/04488e33-589e-4c6e-876a-c18b45b58bb5">
<img width="1700" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/0e14559c-5cc6-4711-ad2a-b9dc06caf3f0">

2024-03-06 17:25 UTC, DiegoSalas27 commented
Great work. Everything works as expected and your PR is clean and contains only the changes regarding your functionality. I attached a video showcasing how everything works:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26840798/1c7361f4-26b0-4dfb-91cd-0b568daa8e69

2024-03-06 17:26 UTC, DiegoSalas27 approved these changes, later dismissed

2024-03-06 17:43 UTC, Weiyao-Li submitted a review, later dismissed
Hi, while reviewing your pr, I encountered sever side error. Please have a check. I have attached relevant screenshots about the situation.

2024-03-08 02:10 UTC, SRamen1999 reviewed
While reviewing this PR, I encountered sever side error. Also when I am in the http://localhost:3000/bmdashboard/equipments route no data is being loaded because I
 am getting a 404 error.

<img width="1706" alt="Screen Shot 2024-03-07 at 9 06 28 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/b20e6098-30aa-47ef-9c8a-f39d15208a4f">

<img width="927" alt="Screen Shot 2024-03-07 at 9 06 57 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/def56c37-e008-4696-8597-cac433d27e8f">

2024-03-08 12:32 UTC, Gugor99 reviewed
### Report
Hi,
I tried to review your PR but compilation failed and I got an error message in the console. Please see screenshot for reference.
### Screenshot
![Cattura1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/128ebd7e-f1c4-43b9-84e6-26319ba54053)

2024-03-08 17:18 UTC, rajnada commented
Hi Aishwariya,

Great Job! All the functionality that you mentioned is working fine.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25640436/efff3b18-5aff-4921-bdff-42d8346de800

2024-03-08 19:53 UTC, Coops023 submitted a review, later dismissed
Hi, i have reviewed the functionality of this PR and all seems to work well. 

<img width="1375" alt="Screenshot 2024-03-08 at 20 51 14" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81972263/107f14f2-148f-44b0-871c-7401b7c57427">

2024-03-09 00:37 UTC, Aishwaryak01 commented
@Gugor99 @Weiyao-Li @SRamen1999 : I re-tested and the page is rendered successfully on my side. I think it is an intermittent issue as others can view it without any issue.

2024-03-09 00:44 UTC, SanketKaware commented
Followed all the mentioned steps and the changes look good to me.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/185284be-b752-4446-a222-5630d57f0972

2024-03-09 08:02 UTC, Sarthak32 reviewed
I am not able to see  the projects in the  equipments page:
![Screenshot 2024-03-09 133030](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/0d9c614d-64f9-4881-be49-c723f8f6694c)
![Screenshot 2024-03-09 133103](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/b9769a1b-bc19-4118-971a-5bf47ba6d717)

2024-03-09 19:31 UTC, bhuvan-dv submitted a review, later dismissed
Followed all the mentioned steps and the changes look good to me.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67942070/8bd8715d-4a76-4b0a-ad23-9eb84d5dc5ab

2024-03-09 20:46 UTC, YHX6 submitted a review, later dismissed
It works correctly.
<img width="1512" alt="Screenshot 2024-03-09 at 3 43 44 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113729159/704af1cc-8e53-49a1-b3b4-a2064fbc1199">

2024-03-10 09:33 UTC, psharma1984 approved these changes
Hi @Aishwaryak01 Everything works as expected. Approving !!!
![a](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/eca76206-c4a5-4822-af9c-4601d61b5310)
![c](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/cf0c621d-bcf7-4218-87fd-1642700a22ec)
![d](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/5fbfe750-daa2-4204-9144-d32d731632c9)
![Screenshot 2024-03-10 012904](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/f619d5b4-2930-490a-899e-8da9ae0afe8f)

2024-03-13 03:00 UTC, sameersdeshpande requested changes, later dismissed
Hello Aishwarya!
I tested the dashboard on my end. It is working fine as expected.
But I want to check that when I sort project and equipment, and then click on ascending or descending. It lists all the items. Should not it be listing only the itmes of the sorted list.
May I know if this is the thing to be considered? Uploading the video here.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/87390339/52da09ea-f178-4875-8263-6630ec9a2c83


Thanks

2024-03-16 16:16 UTC, 20chen-7 reviewed
Every function looks great. just one thing, npm start for the frontend will cause test error
<img width="601" alt="Screenshot 2024-03-17 at 12 09 36 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/c5ccdab3-9ed6-47ac-b484-eb5fa3843c7d">
<img width="955" alt="Screenshot 2024-03-17 at 12 07 23 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/42ab8a09-1fde-4aa9-b864-04d58be0f209">
<img width="921" alt="Screenshot 2024-03-17 at 12 07 55 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/6a6ce368-8725-44d5-a571-2308652aefdc">
<img width="920" alt="Screenshot 2024-03-17 at 12 08 04 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/be9e250f-3f9d-4a68-82ff-facdb631c701">
<img width="915" alt="Screenshot 2024-03-17 at 12 08 18 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/b63e3002-bdc0-4bd6-ab17-7a7dd3ed7395">

<img width="847" alt="Screenshot 2024-03-17 at 12 09 03 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/b5c3363
<img width="778" alt="Screenshot 2024-03-17 at 12 09 12 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/9239226d-24ab-48c3-9035-542c7e38fd00">
3-0353-4e9d-8593-5d6894907596">

2024-03-16 23:16 UTC, iven-yao submitted a review, later dismissed
- [x] open edit/update/purchase modal correctly
- [x] close edit/update/purchase modal correctly
- [x] sorting on project/ name works correctly
- [x] filtering on project/ equipment works correctly  

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/34927ad5-5bc0-4d7f-8a85-371021e4f5d0

2024-03-20 02:47 UTC, hetvi11110 approved these changes, later dismissed
I have looked over and tested this PR as it was mentioned. It is working perfectly on my local server. Here is a reference video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/70e404c2-0741-4589-a7ed-eed38894f588

2024-03-22 05:03 UTC, ImzIssa submitted a review, later dismissed
Hey, I've tested your PR and all your changes work as expected. 

![Screenshot (86)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/87269725/77c612d1-7616-4e8a-9918-11f1e3624340)
![Screenshot (85)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/87269725/e74e3b62-4457-48b6-9f92-f5eecbece540)

2024-03-26 02:14 UTC, kylepham submitted a review, later dismissed
Functionalities work as expected. Here is the testing video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/150333a8-894b-4374-b7ad-51f64d7e11dc

However, I noticed that the first click on either "Project" or "Name" doesn't yield any changes. I think it was because the data was already sorted that way. 2 things that I want to point out:
- If the initial data is not sorted, I think there shouldn't be any sorting direction indicators next to column names. They should be there once the user triggers.
- Plus, there should be only one column being sorted at a time. I've found [an example](https://www.w3.org/WAI/ARIA/apg/patterns/table/examples/sortable-table/), you can check it out.

These improvements should improve UX, imo. Overall, great work 👍🏻

2024-03-26 20:11 UTC, Gayathr-2012 commented
Hi, 
I have tested your PR. I followed the steps you mentioned, and it works as expected.  Good job.
<img width="1238" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/070f36dc-e181-4a8d-862e-ab307ef995c3">


<img width="1235" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/14a752fd-b0ae-49c2-a6ec-a9b3bba64e56">

<img width="1238" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/01e0393d-1c55-4b13-8b6b-b6adda088154">

<img width="1214" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/25cc6872-f96e-4052-af74-fb9826106fb5">

2024-03-31 00:44 UTC, Jaiwin-4998 approved these changes, later dismissed
Hi I just reviewed you PR and all the features are working as intended. I am attaching the video file for the reference. Please let me know if I missed something to check.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62836815/082aea22-d912-4223-af9e-85d48f1cd415

2024-04-07 05:40 UTC, Parth-tech approved these changes, later dismissed
Hey Aishwarya,

Everything works correctly. Great job done. I have just one feedback. 

`Feedback:`
- When you click on the column name to sort i.e `Name` or `Project` column, and if you do not move your cursor the tooltip still displays the same message. This is very confusing. Better if you solve this. 
- Meaning if the above statement is ambiguous: You hover on `Name` Column. The tooltip displays `sort name asc`. Once you click on it then the `Name` column will be sorted in ascending order. Now if you do not move your cursor the tooltip still continues to display `sort name asc`. Hence, after the click we can simply get rid of the tool tip and display when we re-hover over it


<img width="1440" alt="Screenshot 2024-04-06 at 7 35 10 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/180455bf-ff05-4cd6-96d1-3058934c324a">
<img width="1440" alt="Screenshot 2024-04-06 at 7 34 35 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/94582f38-d8d4-4002-aebd-c7be3d5c83f2">
<img width="1440" alt="Screenshot 2024-04-06 at 7 34 45 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/bb92432d-cd98-41b7-a77e-913cd8169213">

<img width="1440" alt="Screenshot 2024-04-06 at 7 34 55 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/9ea81150-44aa-49de-923f-fd4f176ac13e">

2024-04-09 18:50 UTC, MQChen211 commented
Hi, I tested your PR and it works as expected.
<img width="1517" alt="截屏2024-04-09 14 03 31" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/10f63ecc-0b17-448d-a3f1-b93a51f3d312">
<img width="1520" alt="截屏2024-04-09 14 48 09" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/c74708df-7a0f-41a6-a9f0-d4b632f43325">
<img width="1515" alt="截屏2024-04-09 14 48 17" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/0a642558-9c24-41fc-b5aa-0f1cdea38e56">
<img width="1517" alt="截屏2024-04-09 14 04 05" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/16ae156f-281b-4be8-ae1e-e96fac5cf3
<img width="1513" alt="截屏2024-04-09 14 04 18" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/eb0d1ba2-1f70-467c-a8cc-5d13157d3fd5">
3d">

2024-04-14 03:38 UTC, j-corp-25 reviewed
Hi @Aishwaryak01 ,

I tested as instructed but im not seeing a list of items. I checked the endpoint and its returning ok. But I still dont see the items as listed on your pictures

Please see below:

![TestingEquipment](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95154804/ee666683-40e3-4142-b946-b756c8996cd2)

2024-04-19 19:53 UTC, cvtqx submitted a review, later dismissed
I've tested this PR from an admin account and all features work as described. There is a little delay happening when a tooltip is displayed on hover and it is not disappearing once the arrow is clicked (someone has mentioned this already). this should probably be addressed in a different PR as it seems just a tiny cosmetic defect. Overall great job!
See video of testing:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/9518c286-21c4-44d7-bfc5-ed5b181895cd

2024-05-14 13:47 UTC, kaushikMreddy293 commented
Hi, 
I tried to test this PR but, the data is not showing up in the table for me, can anyone share the URL or update if I've missed something in the implementation

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42844448/14e65673-7cb7-4c36-b051-f99982212a3d)

2024-05-15 14:35 UTC, KaushikMreddy commented
Hi, 
I tried to test this PR but, the data is not showing up in the table for me, can anyone share the URL or update if I've missed something in the implementation

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42844448/14e65673-7cb7-4c36-b051-f99982212a3d)

2024-05-22 01:43 UTC, one-community commented
Thank you all, merging!

2024-05-25 17:45 UTC, one-community commented
Thank you all, merging!

2024-05-25 17:45 UTC, merged