Nahiyan_Added padding to the projects and teams report container
OneCommunityGlobal/HighestGoodNetworkApp pull request #1967
Opened 2024-02-20 19:13 UTC by Nahiyan-16

# Description
The projects report page and the teams' report page needed some padding.

## Related PRS (if any):
Use dev backend

## Main changes explained:
Just added some padding vertically and horizontally in the Report Page container

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→Reports-> Reports -> Projects/Teams -> Click on any project/team
6. Verify that there is padding and that elements are not touching the edge

## Screenshots or videos of changes:
Before:
![Screenshot 2024-02-20 140941](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/6d8dea02-dcd5-4a2d-ae19-36936a6b4705)
![Screenshot 2024-02-20 141009](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/348aa735-4b04-417c-80f9-c6a22a36bc06)

After:
![Screenshot 2024-02-20 140902](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/038461bd-230d-4328-ae7e-b2b85a4f6ed9)
![Screenshot 2024-02-20 140830](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/d1011d0e-0274-4976-9e64-53f1a1565707)

2024-02-21 00:27 UTC, dhairya-mehta commented
Hey, I verified the padding shown in the image below!
<img width="1255" alt="PR 1967" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56514777/86cae56d-8c03-4ac2-868a-461211097788">

2024-02-21 17:41 UTC, meetpadhiar4 approved these changes
Hi, I reviewed your PR and the padding is visible in projects and teams pages. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/bc7fadb7-70ab-4767-a2ba-8f4a4e639366

2024-02-22 01:34 UTC, XiaohanMeng approved these changes
Hi, I have verified the padding settings in both the teams and projects. Please refer to the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/be07c8f9-2679-461b-8da5-b9f39ac84186

2024-02-22 09:58 UTC, ShengjieMao approved these changes
The layout looks great and the padding works as expected. Great work.
<img width="1280" alt="PR_1967a" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/471183f5-8c19-4932-9df8-99effe312968">
<img width="1917" alt="PR_1967b" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/abcd0eb1-477d-4e0f-befd-ec49f631e07b">

2024-02-23 02:36 UTC, Jingyii800 approved these changes
HI, I have tested this frontend change! It looks good! Great job.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/fda75bb8-cacc-442e-9cd9-228057d740d6

2024-02-24 06:45 UTC, swathyjayaseelan requested changes
The padding is applied to the reports page. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/ce5becb5-164d-4fbc-829b-e2b89d68c4ad

2024-03-01 00:40 UTC, skaush21 approved these changes
Verified that there is paddings on the team and projects pages, looks good. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/e0a4c4cd-a5a4-49bd-ae64-88de789382f9

2024-03-02 02:57 UTC, ramyaram2092 approved these changes
Looks good !

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/5db8e4c3-7a1f-4d8d-8b91-f10a17fa8488

2024-03-02 05:07 UTC, one-community commented
Thank you all, merging!

2024-03-02 05:08 UTC, merged