Shuhua - All Inventory Types page functionalities
OneCommunityGlobal/HighestGoodNetworkApp pull request #1984
Opened 2024-02-23 06:03 UTC by Shuhua-L

# Description

Implement the functionalities of the All Inventory Types page, which the UI was implemented in this [PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1868)

## Related PRS (if any):

This frontend PR is related to the [#765](https://github.com/OneCommunityGlobal/HGNRest/pull/765) backend PR.

## Main changes explained:

- added actions and reduces for updating/deleting inventory types, along with corresponding toast notifications
- added actions and reduces for adding/deleting units of measurement, along with corresponding toast notifications
- added click event handlers for all **Add**, **Edit**, **Delete** buttons

## How to test:

1. check into current branch
2. do `npm run start:local` to run this PR locally
3. Clear site data/cache or use Incognito mode
4. log in as any user, direct to `http://localhost:3000/bmdashboard`, log in again, and navigate to `http://localhost:3000/bmdashboard/inventorytypes`
5. (optional) add new inventory types for testing, check out the note below for adding multiple types at once
6. Verify editing and deleting inventory types
    1. choose any category, then a type
    2. click “**Edit**”, update either name or description, confirm changes and toasts
    3. click “**Delete**”, confirm changes and toasts
7. Verify adding and removing inventory units
    1. click “**Unit of Measurement**”, then “**Add**” to create a new unit, or “**Delete**” to remove it 
    2. confirm changes and toasts
8. Other buttons
    1. "**Add**" buttons under categories open new pages, but right now, only “Add Material” page and “Add Equipment” page are fully functional, the “Add Tool” page is implemented but not connected with the backend
    2. "**Back to previous list page**" does nothing at this point since the target page is not implemented yet

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/049c15ab-21ed-44be-b330-50874ab7d033

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/506709d0-ae7d-4d87-b3c2-903e30cbb0cf

## Note:

1. You can use MongoDB Compass to quickly create a new type for each category. Here’s the [JSON](https://drive.google.com/file/d/1Bw4eTm6-1VodeuHHxYUV-RPnVPTwAUAx/view) in case you want to try it out. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/fbced6e1-498d-4872-8fee-0289b72a4bfa

2. These potential errors are unrelated
<img width="1310" alt="potential errors" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/1fcfd9d3-3139-4a64-b04f-83e83453b0fd">

2024-02-24 22:17 UTC, skaush21 requested changes
* blank screen when navigating to http://localhost:3000/bmdashboard/inventorytypes
* there are a couple of console errors:
<img width="535" alt="Screen Shot 2024-02-24 at 2 13 34 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/e7608e55-8085-497d-ac75-50ed63867575">

<img width="541" alt="Screen Shot 2024-02-24 at 2 13 47 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/3f9be60f-1a4d-4568-bebf-8804244213c6">

2024-02-25 00:53 UTC, brandta-1 requested changes
# Review
Unable to navigate to ```http://localhost:3000/bmdashboard/inventorytypes``` as an admin user after Hard Reload and Clear Cache.

# Error
From Chrome developer console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'error')
    at invUnitsTable.jsx:28:1
    at commitHookEffectListMount (react-dom.development.js:19731:1)
    at commitPassiveHookEffects (react-dom.development.js:19769:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at HTMLUnknownElement.sentryWrapped (helpers.ts:77:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at flushPassiveEffectsImpl (react-dom.development.js:22853:1)
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at flushPassiveEffects (react-dom.development.js:22820:1)
    at performSyncWorkOnRoot (react-dom.development.js:21737:1)
    at react-dom.development.js:11089:1
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084:1)
    at workLoop (scheduler.development.js:597:1)
    at flushWork (scheduler.development.js:552:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:164:1)
```

```
The above error occurred in the <UnitsTable> component:
    in UnitsTable (created by Connect(UnitsTable))
    in Connect(UnitsTable) (at InventoryTypesList.jsx:90)
    in div (created by CardBody)
    in CardBody (at InventoryTypesList.jsx:89)
    in div (created by AccordionCollapse)
    in Transition (created by ForwardRef)
    in ForwardRef (created by AccordionCollapse)
    in AccordionCollapse (at InventoryTypesList.jsx:88)
    in div (created by Card)
    in Card (at InventoryTypesList.jsx:84)
    in div (created by Accordion)
    in Accordion (at InventoryTypesList.jsx:68)
    in div (at InventoryTypesList.jsx:52)
    in InventoryTypesList (created by Connect(InventoryTypesList))
    in Connect(InventoryTypesList) (at BMProtectedRoute.jsx:16)
    in Suspense (at BMProtectedRoute.jsx:16)
    in Route (at BMProtectedRoute.jsx:7)
    in BMProtectedRoute (created by Connect(BMProtectedRoute))
    in Connect(BMProtectedRoute) (at routes.js:229)
    in Switch (at routes.js:98)
    in Switch (at routes.js:89)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.jsx:54)
    in PersistGate (at App.jsx:53)
    in Provider (at App.jsx:52)
    in App (at src/index.js:11)
```
# System
Chrome 121.0.0
Windows 10

2024-02-25 01:41 UTC, Shuhua-L commented
@skaush21 @brandta-1 
Please clear the cache or use Incognito mode before logging in. I have changed the Redux store state, which heavily relies on cache.

2024-02-25 02:40 UTC, Shuhua-L commented
@brandta-1 @skaush21 Please clear the cache or use Incognito mode before logging in. I have changed the Redux store state, which heavily relies on cache.

2024-02-26 21:02 UTC, skaush21 submitted a review, later dismissed
Tested this PR using Incognito mode.

* logged in with owner account
* navigated to bmdashboard, logged in again
* navigated to bmdashboard/inventorytypes
* tested the edit and delete buttons
* tested the add buttons for "unit of Measurment", "Add Material", and "Add Equipment".
All features implemented work.

The previous issue I mentioned is not an issue when using incognito mode. However clearing cache does not seem to do anything when not using the private browser.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/6de06531-a39f-4ef7-9675-b2bf78fa9951

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/8d150ed4-3be9-4d5b-b924-8329dab62211

2024-02-27 22:09 UTC, XiaohanMeng approved these changes
Hi, I tested this PR in incognito mode, and it worked as intended. All category items can be updated and deleted, and the add button opens a new page. Well done!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/29b1dfc7-8958-45f4-999f-0360d3dcdfe8

2024-02-29 03:58 UTC, nnamdixobi commented
Hey there I tested it as instructed it looks good but the add functionality does not work as expected. As you can see in the video where I will attach the link below you can see how the add button does not function when I try to use it
Video: https://www.loom.com/share/a30513aff4544e0495f38427b1481685

2024-02-29 19:53 UTC, Shuhua-L commented
> Hey there I tested it as instructed it looks good but the add functionality does not work as expected. As you can see in the video where I will attach the link below you can see how the add button does not function when I try to use it
> 
> Video: https://www.loom.com/share/a30513aff4544e0495f38427b1481685

Thanks for reviewing! Did any errors pop up in the console when you clicked Add?

2024-03-01 10:08 UTC, ShengjieMao approved these changes
Buttons and features in the page worked as expected in incognito mode. Available buttons all functioned well as described in the instructions. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/b537286a-fafd-4e9b-9228-66b704aefa65

2024-03-03 01:55 UTC, ClemarNunes approved these changes
I tested your PR and worked as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/831c001c-9762-4243-bff7-784a0fdb0917

2024-03-06 03:19 UTC, Pandani07 submitted a review, later dismissed
Tested this PR in incognito mode and everything works as expected. I could edit/delete and also add a new unit of measurement

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/418df4c9-ddd6-4806-b453-3687363eabfc

2024-03-18 05:15 UTC, 20chen-7 commented
left review on the backend

2024-03-18 05:31 UTC, 20chen-7 commented
Overall, each looks good. left review at the backend

2024-03-18 05:36 UTC, 20chen-7 approved these changes
Every function expected and looks great!

2024-04-12 07:23 UTC, yvonnep165 submitted a review, later dismissed
Hi @Shuhua-L , I tested this PR in incognito mode and it worked as intended. I logged in as an Admin account and saw all the pages. I verified the editing and deleting inventory types and added and removed inventory units. Nice work! Please refer to the video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/7d72a48d-a729-4cd8-9dfe-1ae2018ada80

2024-06-30 18:51 UTC, peter6866 submitted a review, later dismissed

2024-07-06 23:21 UTC, Vigneshwar-Muriki approved these changes
Tested this PR and all edit and delete buttons in collapsible dropdowns work as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/78b779c1-fdee-4d6b-805d-d2bd9b6ff511

2024-07-17 23:23 UTC, SaiLavanya1 approved these changes
I've tested the PR #1984 in incognito mode as well, but some features did not work as expected. Please review it.
https://www.loom.com/share/289499020d8c4d179144afe44ef9d208

2024-07-19 01:48 UTC, kabraambika requested changes
### Changes requested due to compile time error in frontend

Followed the below steps to verify the PR:

_In backend repository_
- git checkout  Shuhua-Types_List_Page_Edit_Delete
- npm install
- npm run build
- npm start

_In frontend repository_
- git checkout into Shuhua-Types_List_Page_Edit_Delete
- npm install
- npm run start:local

**Unable to start the frontend, Build is showing compile time error as shown below:**
<img width="1275" alt="image" src="https://github.com/user-attachments/assets/3dc41e1f-0316-468d-a948-8f52e3d104a9">

2024-07-26 00:16 UTC, ReinaT5678 requested changes
I also am getting the same error. I renamed the "roleInfoModal.jsx" to "RoleInfoModal.jsx" to get the HGN site to load.

<img width="1004" alt="Screenshot 2024-07-25 at 5 02 09 PM" src="https://github.com/user-attachments/assets/924d3376-0022-407e-baa7-34480b355cab">

After fixing the file issue, I couldn't load the content in http://localhost:3000/bmdashboard/inventorytypes

<img width="1317" alt="Screenshot 2024-07-25 at 5 16 11 PM" src="https://github.com/user-attachments/assets/0ed6b031-8bd8-4020-bbe2-82501687a583">

2024-07-28 00:54 UTC, souravwalke commented
Tried testing the contents of the PR but was unable to deploy and run the frontend due to the below issue.

<img width="678" alt="Screenshot 2024-07-27 at 5 53 27 PM" src="https://github.com/user-attachments/assets/3a8eee7b-110a-4701-97f0-0505d102fbdf">

2024-08-02 16:39 UTC, Pranay-ai requested changes
Hey @Shuhua-L 

I have tested the PR but when i was redirecting yo inventory page i ran into some issued and found some errors in the console
I have attached a log file
[inventory-log.log](https://github.com/user-attachments/files/16473025/inventory-log.log)
Thank You.

2024-08-09 02:21 UTC, varunreddy03 requested changes
Hi I have tried running this PR but the frontend branch failed to load in local host because of errors. I have attached screenshots of them.

![PR 1984_1](https://github.com/user-attachments/assets/b669f988-a037-4b72-b0fe-7609160b255f)

2024-08-11 06:58 UTC, adityasure9 requested changes
Hi @Shuhua-L,

I tested the PR according to the instructions, and I encountered the following issues:

After editing and saving changes on the Inventory Types page, the entire page becomes unresponsive and gets stuck. This issue prevents further interaction with the page, making it difficult to proceed with other actions like adding or deleting items.
I noticed similar errors as mentioned by other reviewers, particularly related to the frontend not loading properly due to compile-time errors.
Given these issues, it seems there are some bugs that need to be addressed before this can be merged. Please let me know if you need any further details or testing on my end.

https://github.com/user-attachments/assets/72fc1a43-98ac-4965-8f6c-740425133d37

Thanks for your efforts on this!

2024-08-17 08:01 UTC, SMitta11 requested changes
I followed the given steps but while running frontend I got this issue of RoleInfoModal.jsx file:
![Screen Shot 1](https://github.com/user-attachments/assets/dbe30074-7948-4343-8851-3204dbe5fb2e)

I changed the filename and ran it again and it is opening bmdashboard
![Screen Shot 3](https://github.com/user-attachments/assets/bc1fb8c0-4c39-4694-b56f-be89d2318067)


but when I try to open http://localhost:3000/bmdashboard/inventorytypes, it is giving a blank page:
![Screen Shot 4](https://github.com/user-attachments/assets/a2a26fe5-cdfb-4c2f-97e3-09dea42dedfd)

2024-08-31 00:47 UTC, oliviahyw requested changes
Hi @Shuhua-L I have tested this PR and I can successfully access http://localhost:3000/bmdashboard. But http://localhost:3000/bmdashboard/inventorytypes is blank. Please check the attached screenshots.
<img width="1376" alt="Screenshot 2024-08-30 at 7 47 18 PM" src="https://github.com/user-attachments/assets/87bb05d0-13e0-476d-a0cb-994dc377d0c6">
<img width="1365" alt="Screenshot 2024-08-30 at 7 47 31 PM" src="https://github.com/user-attachments/assets/256117c5-1f3d-464e-9f94-77588510dbf5">

2024-09-07 06:57 UTC, Shreyav2000 requested changes
Hi,

It looks like there are several case sensitivity issues causing compilation errors. The imports for files such as 'RoleInfoModal.jsx' do not match the corresponding file names on disk. Please review the following imports for case mismatches or missing files:

'RoleInfoModal.jsx'
Other components imported from 'EditableModal' and similar directories.
To resolve the issue, please ensure that the import paths and file names match exactly, as this is likely due to case sensitivity in the environment.

Thanks!
<img width="1728" alt="Screenshot 2024-09-07 at 1 52 28 AM" src="https://github.com/user-attachments/assets/50652ca4-2e5a-46a1-b5f4-0cb118780a06">

2024-09-14 07:28 UTC, Parth-tech requested changes
Hi Jiayu,
I am experiencing encountering error when I navigate to `bmdashboard/inventorytypes` route.

https://github.com/user-attachments/assets/29a80094-f933-4eed-bfe5-21b62276f0be

2024-09-14 15:15 UTC, sud306 commented
Hello,
I tried to test PR1984 with PR765 but it gave error on frontend.
PFA the screenshots.

![7 PR765_PR1984_1](https://github.com/user-attachments/assets/5d4c610f-be48-410c-ab7c-1266ee09b0b4)
![7 PR765_PR1984_2](https://github.com/user-attachments/assets/396887ab-4513-4b06-95e7-d63e7fa0a6af)

2024-09-15 00:40 UTC, Muzammil603 requested changes
![image](https://github.com/user-attachments/assets/b5b77e57-49c0-4e37-baab-5f566bec399d)
![image](https://github.com/user-attachments/assets/f98c714f-2370-495d-8a65-0683311cd675)

I have tested it showing me this error on front end

2024-09-17 19:22 UTC, SFA23SCM35V requested changes
A blank screen is displayed when attempting to run the application locally
![1](https://github.com/user-attachments/assets/112b84c3-7696-4f8e-b7b9-9007d700037e)
![2](https://github.com/user-attachments/assets/a67241e9-e8ef-462b-9158-163b8260645f)
![3](https://github.com/user-attachments/assets/58c14402-f798-4a39-a6c6-d844f6517a3c)
.

2024-09-26 07:06 UTC, neeharikakoniki requested changes
Failed to Complie
![image](https://github.com/user-attachments/assets/15b1e192-88a4-4239-9fe0-b6a55915c540)

2024-10-03 17:53 UTC, mrinalini-raghavendran19 approved these changes
Looks good to me!

This PR works mostly as expected. 

For anyone facing errors setting up locally -

There is a compile time error initially - this is due to case sensitivity with `roleInfoModal.jsx`, you can change this yourself to `RoleInfoModal.jsx` under `src/components/UserProfile/EditableModal/RoleInfoModal.jsx`. This will resolve any compile time errors

![image](https://github.com/user-attachments/assets/cf5cdfd3-0a40-418d-aaa7-5f9974e3cd01)

After this, either try clearing cache for this page or test on incognito.

Find below a screen recording of this feature being tested locally. 

I have used an `Owner` account for the same and have a couple of suggestions. 

When I click on `Edit` to edit an existing inventory, I can edit it and it toasts successfully however, all buttons become irresponsive without refreshing the page. 

The `Delete` and `Add` button work as expected, but once a new material is added to the inventory it doesn't take the form back to the inventory page - which may not be within the scope of this PR.

https://github.com/user-attachments/assets/d3d3baa0-42e5-46ed-a90d-21e6abf05f71

Great work!

2024-10-27 00:27 UTC, sheetalmangate commented
Unable to test this PR locally. It is showing "Failed to compile"

![PR1984_error_editor](https://github.com/user-attachments/assets/4123ba68-e7e7-442f-ad71-9eb6dc0dae08)
![PR1984_error](https://github.com/user-attachments/assets/4e07b74b-d474-4c7e-b5a1-3f2437e794a1)

2024-10-27 02:55 UTC, zhiminV requested changes
I have checkout into the related backend and then turn on the frontend, but try many time it still have the following error
![Screenshot 2024-10-26 at 7 54 26 PM](https://github.com/user-attachments/assets/16f11619-108a-4ad7-b2e5-6f569d1bd4e5)

2024-10-31 18:59 UTC, humera314 commented
I tried running the code locally, but I encountered some issues.

![image](https://github.com/user-attachments/assets/6ba91320-a665-4ea6-9fed-15b637277d4e)

2024-11-05 15:22 UTC, AshritaCherlapally requested changes
While testing the frontend PR, i got the below error, for which I have changed the FileName RoleInfoModal.jsx. Later I was able to login and navigate to bmdashboard page, but then when i route to inventorytypes page, the page is blank and the console has the attached log. This PR have case sensitivity issues, please check into them before merging.

<img width="1440" alt="PR#1984_1" src="https://github.com/user-attachments/assets/bb66cb50-4125-4ed2-83d1-6d8f22a03a10">

<img width="1440" alt="PR#1984_2" src="https://github.com/user-attachments/assets/3f924060-0a86-419f-9773-29c468d3fdfc">

2024-11-09 03:33 UTC, SupriyaSudini requested changes
I tested this PR and initially encountered an error that resulted in a blank page, which I have documented here. After renaming the file to RoleInfoModal.jsx, the output appeared correctly, and all functionalities—including editing, deleting, adding, and removing inventory types—worked as required. Please change the file name to ensure everything is correct before proceeding with the merge.

![image](https://github.com/user-attachments/assets/af55c5b0-31f7-42af-a2b2-51633d7349e7)

![image](https://github.com/user-attachments/assets/97c9d646-30b9-45f6-9bbd-bb5f750acd1d)

![image](https://github.com/user-attachments/assets/136aa34b-8941-45e1-8163-9d412a4c194b)

![image](https://github.com/user-attachments/assets/d97d43ce-d282-4b4e-b636-20e740e3b332)

![image](https://github.com/user-attachments/assets/4383ef5d-8237-49b3-873f-260aaf024209)

![image](https://github.com/user-attachments/assets/4db87a81-ebf9-4c04-8c74-bbda70e57a93)

2024-11-23 09:29 UTC, ppsahu commented
I was trying to run the the current benach, however I got the error during compilation. Below are the screenshot for reference.
![Screenshot 2024-11-23 at 12 57 08 AM](https://github.com/user-attachments/assets/81d34119-0b46-4b75-929e-c10205474846)

2025-01-15 21:37 UTC, honglinchen0524 requested changes
## Build Issues
- Initially encountered a compilation error:
  - Original: `./src/components/UserProfile/EditableModal/roleInfoModal.jsx`
  - Fixed: `./src/components/UserProfile/EditableModal/RoleInfoModal.jsx`
![image](https://github.com/user-attachments/assets/5686c4d3-1285-4a8a-bf2e-64e99d068f88)

After changing the file name, the frontend was able to display successfully. 
## Functionality Testing (after I changed the file name)
### Working Features
- Add operation functions as expected
- Delete operation functions as expected

### Issues Found
- 'Edit' Button State Update Delay
   - Changes to edited content are not immediately reflected in the UI, updates only become visible after page refresh
- Also there is noticable lagging during edit operations

https://github.com/user-attachments/assets/9977834b-9eca-43ee-a263-6a5d1ef1fa66

2025-01-22 21:02 UTC, jeyanthi-sm commented
While executing the command npm run start:local, an error occurred after a few seconds: "Failed to compile."

The error message is as follows: 
./src/routes.js
Cannot find file: 'RoleInfoModal.jsx' does not match the corresponding name on disk: '.\src\components\UserProfile\EditableModal\roleInfoModal.jsx'.

Please refer to the attached video for more details.

Uploading PR-1984-compile-error-small.mp4…

2025-02-23 04:43 UTC, SSP24SCM16G reviewed
After integrating the related backend, the frontend failed to start due to an npm test failure, causing the prestart script to exit. To resolve this, try running npm test -- --watchAll=false to check failing test cases, or start the frontend manually using npm start. If the issue persists, clear dependencies (rm -rf node_modules package-lock.json && npm install --legacy-peer-deps) and ensure .env has the correct backend URL (REACT_APP_API_URL=http://localhost:4500).

<img width="1470" alt="Screenshot 2025-02-22 at 22 40 30" src="https://github.com/user-attachments/assets/19914d60-deca-4618-a08e-4973c03381fc" />

2025-02-23 05:02 UTC, rohith1667 requested changes
I am getting an error stating file did not exist.
<img width="1440" alt="Screenshot 2025-02-22 at 10 51 41 PM" src="https://github.com/user-attachments/assets/fc82890b-9a8c-4032-b650-299d005780db" />
Changed the file name. the page is loading but the buttons are not working properly and also there is an error. refer to the screenshot for error

https://github.com/user-attachments/assets/ddda1c70-9177-4872-88d1-1008cdae9ec3
error :-
<img width="669" alt="Screenshot 2025-02-22 at 11 02 23 PM" src="https://github.com/user-attachments/assets/9f2121f4-fced-42c7-a906-f65609e7be64" />

2025-03-01 21:59 UTC, puchakayalasaisaketh reviewed
intially getting the error

<img width="468" alt="image" src="https://github.com/user-attachments/assets/84895d1b-270e-4c60-a97e-1d268364cf96" />

Changed the file name in location /src/components/UserProfile/EditableModal from roleInfoModal.jsx to RoleInfoModal.jsx
 
After making the changes, the frontend functioned correctly. Below are the features demonstrated in the screen recording.

https://drive.google.com/file/d/1BeY31PH_Olq_UNtSD2NkFJiX41gz6YGv/view?usp=sharing

the add item is working properly
delete item is not working properly
update item is not working properly
 
below are the errors encountering in backend

<img width="468" alt="image" src="https://github.com/user-attachments/assets/c871c5e7-5775-4d3a-87f9-e14f37a74c94" />

2025-03-08 19:55 UTC, HSP24SCM69K approved these changes
Reviewed Frontend PR #1984 and confirmed that all the requested functionalities have been implemented successfully. The UI behavior aligns with the expected functionalities, and all features—adding, editing, and deleting inventory types and units—are working as intended.

Additionally, validation mechanisms are in place, ensuring smooth user interaction, and toast notifications provide proper feedback for user actions. API requests are correctly sent and handled as expected, with no issues observed during testing.

I have already provided a backend review for the related PR #765, along with supporting screenshots. You can find them here:[Backend PR #765 Review & Screenshots](https://github.com/OneCommunityGlobal/HGNRest/pull/765)

2025-03-10 20:26 UTC, rishwa344 requested changes
I reviewed this PR and verified that adding, editing, and deleting inventory types are working as expected. However, after editing an inventory type, the page becomes unresponsive and throws a console error. The issue resolves only after refreshing the page. Other functionalities, including adding and deleting inventory units, are working fine.

<img width="1303" alt="Screenshot 2025-03-10 at 1 19 33 PM" src="https://github.com/user-attachments/assets/a47d961d-b207-46e6-ad4d-a08851727668" />
<img width="1433" alt="Screenshot 2025-03-10 at 1 18 41 PM" src="https://github.com/user-attachments/assets/786ab0c8-7129-4147-a10a-170e60bb499b" />

2025-03-12 20:54 UTC, sri0606 commented
> I reviewed this PR and verified that adding, editing, and deleting inventory types are working as expected. However, after editing an inventory type, the page becomes unresponsive and throws a console error. The issue resolves only after refreshing the page. Other functionalities, including adding and deleting inventory units, are working fine.
> <img alt="Screenshot 2025-03-10 at 1 19 33 PM" width="1303" src="https://private-user-images.githubusercontent.com/128539084/421078002-a47d961d-b207-46e6-ad4d-a08851727668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE4MDg1MjEsIm5iZiI6MTc0MTgwODIyMSwicGF0aCI6Ii8xMjg1MzkwODQvNDIxMDc4MDAyLWE0N2Q5NjFkLWIyMDctNDZlNi1hZDRkLWEwODg1MTcyNzY2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMxMlQxOTM3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTY4NDY0ZDMyYjViOGJhODQxMjg3NGJhODg1NGU0YTQzMDk4YTIwMmE1Y2E0NTIwZmVhNjEzZTljY2IxNzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yIGwQmSuJjnUbZAb_zkZijQSZb4cTL-iFDbSPjaIcRM"> <img alt="Screenshot 2025-03-10 at 1 18 41 PM" width="1433" src="https://private-user-images.githubusercontent.com/128539084/421078017-786ab0c8-7129-4147-a10a-170e60bb499b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE4MDg1MjEsIm5iZiI6MTc0MTgwODIyMSwicGF0aCI6Ii8xMjg1MzkwODQvNDIxMDc4MDE3LTc4NmFiMGM4LTcxMjktNDE0Ny1hMTBhLTE3MGU2MGJiNDk5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMxMlQxOTM3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTM5ZTAxZjBhYjRmMGUwMTFlMTc3MmFjMzY1ZjA3NmMxOTM4MzI0ZTNjNWE1YmVjMTcxNjBiNGQxYjAxMDUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.86z2FSj4_AbWnrdCaEsjGJy7dKYVqt4l_1oRUxnoGiE">

@rishwa344 , should be fixed now

2025-03-29 02:48 UTC, humemah commented
UI updates for adding, editing, and deleting inventory types work smoothly.
Toast notifications appear correctly for all actions. Button click events function as expected.
Everything looks good on the frontend.
![image](https://github.com/user-attachments/assets/1d8c149a-700d-462d-8798-1f833c11503e)
![image](https://github.com/user-attachments/assets/9a69c1b4-7024-4809-9c17-a9766b766b33)
![image](https://github.com/user-attachments/assets/f2e19f1b-d010-4d1b-b509-93926a0f6288)

2025-05-17 01:48 UTC, closed without merging