SaiDeepak project summary alignment BMDashboard
OneCommunityGlobal/HighestGoodNetworkApp pull request #1986
Opened 2024-02-23 07:38 UTC by SaiDeepak-NEU

# Description
This PR is regarding the alignment of the project summary list which is off in the bmdashboard of Phase 2 and also making the project summary page responsive.

## Related PRS (if any):
This is only a frontend PR and can be tested using the development branch in the backend
…

## Main changes explained:
- Modified the ProjectSummary.jsx file
- Added some styling in BMDashboard.css
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin or owner user
5. navigate to /bmdashboard and login again
6. verify that the alignment of the content in the project summaries is in place and is not looking off like before. Please input any suggestions for any particular layout or design changes which would make the list and info look appealing.
7. Also, please verify the responsiveness of the table data by inspecting the page and verify alignment for different screen sizes.

## Screenshots or videos of changes:
Before Pic: 
![Screenshot (103)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114311909/939b2b98-9043-408d-af70-9d84edf71198)
After alignment correction:
![Screenshot (102)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114311909/393c847b-4b50-4e9f-8fe1-fd908a30a713)

## Note:
To test the responsiveness, right click and then click on inspect and then select mobile view and select different screen sizes and check alignment.

2024-02-23 16:04 UTC, meetpadhiar4 approved these changes, later dismissed
Hi, I reviewed your PR and all the changes work as intended. I also tested the responsiveness with different screen sizes. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/8b0be46d-d677-4cf9-91f8-e99dc80115ee

2024-02-23 21:58 UTC, skaush21 reviewed
* logged in as admin user
* navigated to /bmdashboard, logged in again
* verified alignment
* alignment of the table looks good on most devices except the galaxy fold, its more compacted and the text overlaps. 
* when switching from desktop/ipad to mobile the style/layout of the summary changes to a longer form. if that can be resized to appear like it does on the desktop that would be great. if not the current layout works just fine.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/a715834f-aade-4980-97ed-5b654f775c3e

2024-02-24 04:14 UTC, chrischenlixing approved these changes, later dismissed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114450390/2f0c6296-5c29-4049-b915-b844a8ba14dc)
Hi this looks like it works as intended. Even when I try to shrink the window.

2024-02-24 05:40 UTC, swathyjayaseelan submitted a review, later dismissed
The changes look good. The alignment of the page is responsive at all screen sizes.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/7fdf33bf-ec52-4240-b9b0-184254fbac2e

2024-02-24 08:01 UTC, ShengjieMao submitted a review, later dismissed
The responsive page looks great in alignment. Toggling page doesn't affect the appearance. Great work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/d656b24e-7fef-4b9c-98fc-3a707bbb18c1

2024-02-25 03:00 UTC, FyisFe requested changes
Tested with mobile and desktop view, the alignments looks great. However, there are still some bugs need to be fixed.

<img width="761" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59299011/5092214c-d3d1-4ddd-8806-e058edb7577b">

<img width="277" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59299011/7d690386-9312-4f11-b5d4-5d2ca66ffadd">

2024-02-25 03:02 UTC, FyisFe commented on src/components/BMDashboard/Projects/ProjectSummary.jsx
> +        <Col xs={window.innerWidth < 700 ? '6' : '4'}>
A bug here is directly accessing `window.innerWidth` in the JSX, which does not respond to window resizing after the initial render, use the `useState` and `useEffect` hooks from React to create a responsive layout that reacts to window size changes.

You can navigate to this tag, and when resizing window, it doesn't change from `col-6` to `col-4` and vice versa
<img width="556" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59299011/d3af2cb5-bac2-47c0-9107-55917a7e0520">

2024-02-27 01:20 UTC, XiaohanMeng submitted a review, later dismissed
Hi, I reviewed the PR and everything is functioning correctly. The responsiveness and alignment look great. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/71ffdb0b-5bad-417d-9c7c-c49d384cb053

2024-02-28 02:17 UTC, SaiDeepak-NEU commented on src/components/BMDashboard/Projects/ProjectSummary.jsx
> +        <Col xs={window.innerWidth < 700 ? '6' : '4'}>
Thank you for checking the code and suggesting appropriate changes. I appreciate your comment and I certainly agree that the change you suggested is a better approach. I will make the changes and will incorporate them as soon as possible.

2024-03-01 00:18 UTC, FyisFe approved these changes, later dismissed
LGTM! Thanks for your contribution.

2024-03-01 10:35 UTC, Gugor99 approved these changes
### Report 
Hi SaiDeepak,
I checked out your implementation and it seems to be working as intended! Here are the steps I took: I logged in as admin, then navigated to /bmdashboard and logged in again. The layout was looking nicely both with phone and big screen size screens, well done! Please see screenshots for reference
### Screenshots
![Cattura1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/90fbe765-384c-41c9-a9dc-e2a2486865f7)
![Cattura2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/20a1b9be-afd9-4dc2-b69e-874f460d95d4)
![Cattura3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/769a06ca-efb9-469c-badb-cb90938671e5)

2024-03-02 18:04 UTC, ClemarNunes approved these changes, later dismissed
I tested your PR and worked as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/3bd8e954-e00d-4a03-9119-a80739b48625

2024-03-03 17:55 UTC, tdkent requested changes
The page alignment and overall page layout looks good at standard desktop sizes. As other reviewers have pointed out, the layout is less readable for mobile views. This is mainly due to the left padding constricting the summary container. I played around with the styling for a few minutes and found that adding a rule such as `padding: 0` to `.projects-list` in **BMDashboard.css** eliminates most of the excess padding of the container itself. The container should also be centered.

There is padding inside the container pushing the text inwards that I think can be toned down/removed for mobile views.

Example of suggested improved mobile layout: 

<img width="383" alt="Screenshot 2024-03-03 at 9 47 44 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/858c2759-9b77-4856-b446-9a1f66c229f6">

This is just a quick example, and its causing some new issues with the text formatting, but I think it's closer to how the inner padding should be formatted. Note that I had to add a padding rule to each `<Col>` tag in **ProjectSummary.jsx** to make this work.

<img width="826" alt="Screenshot 2024-03-03 at 9 52 17 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/72f613ff-4adc-4f7a-a698-d61bfd5127ad">

2024-03-22 22:22 UTC, SanketKaware approved these changes, later dismissed
This change looks good to me.  /bmdashboard page alignment is correct.

I verified alignment for different screen sizes. 

Approving this change, **but my suggestion is** to check the alignment of "Select a project" and "Go to project dashboard" which are not aligned at the center.


<img width="870" alt="Screenshot 2024-03-22 at 6 15 55 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/e59c65f5-e4c3-4a19-a8fa-286d9753808a">

<img width="476" alt="Screenshot 2024-03-22 at 6 19 23 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/efe7f1ec-9bd8-448d-94c5-42af739dc399">



**Please see my video review for reference**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/9c67fa16-d5f7-4d3d-86c2-4cdb664068b0

2024-04-13 16:02 UTC, tdkent approved these changes
Update to padding improves mobile view.

2024-04-14 01:05 UTC, one-community commented
Thank you all, merging!

2024-04-14 01:05 UTC, merged