Yixiao protectedroute unittest
OneCommunityGlobal/HighestGoodNetworkApp pull request #1993
Opened 2024-02-25 01:29 UTC by JYXiao-2021

# Description
Create the unit test for the ProtectedRoute component to confirm whether it working as intended.

## Main changes explained:
- Create file ProtectedRoute.test.js to do the unit test.

## How to test:
1.check into current branch
2.do npm install to run this PR locally
3.run npm test ProtectedRoute.test.js

## Screenshots or videos of changes:

2024-02-25 05:42 UTC, AaronPersaud approved these changes, later dismissed
Hi @JYXiao-2021, I've tested and all the tests have passed! Good job.

<img width="832" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/93e322f7-88af-47e7-a7a7-c8338e14c507">

2024-02-25 09:52 UTC, iTvX commented
It passed the test. Good job!

![CleanShot 2024-02-25 at 01 52 16@2x](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/57789cce-1fef-4cbe-bcdf-15d07f1bdf3f)

2024-02-26 18:34 UTC, meetpadhiar4 approved these changes, later dismissed
Hi, I tested your PR and it passed all the test cases. Please refer the screenshot attached.

<img width="1202" alt="PR 1993" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/3fc19b35-ad3c-4970-85f2-6665e5c584a9">

2024-02-26 22:21 UTC, ChengyanOo submitted a review, later dismissed
All test passed, great work!
![Screenshot 2024-02-26 at 17 20 06](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69735000/44d7c5c7-4d7e-4be8-a4f3-07f592e81d6b)

2024-02-27 04:15 UTC, iTvX requested changes
The unit test should be placed in the folder named "__tests__." Please create a "__test__" folder and place the unit test under this folder.

2024-02-27 08:33 UTC, ShengjieMao submitted a review, later dismissed
All tests passed and the components and props are comprehensively considered. As others have indicated, it might be better to organize the
<img width="635" alt="1993" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/2ea5dc51-ca92-49b0-bf50-94688464172b">
 files under a test dir.

2024-02-29 03:59 UTC, XiaohanMeng approved these changes, later dismissed
Hi, all 6 test cases passed! Great job! 
![1993_result](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/9dffdf40-d7df-4479-9db6-c65b6be2e10d)

2024-02-29 04:21 UTC, skaush21 approved these changes
Ran npm test, all tests passed.
<img width="627" alt="Screen Shot 2024-02-28 at 8 19 08 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/9e79ed6f-7cdd-40c4-8d0d-ef3b9252a019">

2024-03-01 03:28 UTC, FyisFe approved these changes, later dismissed
All tests passed. 

<img width="779" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59299011/3d4e7b7e-b3f5-4cb7-a63d-77aca750a1a4">

2024-03-01 03:28 UTC, FyisFe commented on src/components/common/ProtectedRoute/ProtectedRoute.test.js
> +const DashboardComponent = () => <div>Dashboard Page</div>;
Those two components are declared but not used.

2024-03-02 03:25 UTC, dhairya-mehta commented
Hey verified the Pull Request, good job!
<img width="1224" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56514777/3f8fd641-e463-40ca-a3fb-3d2d029534ab">

2024-03-03 04:41 UTC, ramyaram2092 requested changes
Good job on the test cases. Kindly update the path 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/cbd6fffe-4e60-42b1-98a7-f293016fca6e)

2024-03-05 21:06 UTC, Pandani07 submitted a review, later dismissed
All the test cases passed! Great work

2024-03-09 06:25 UTC, JYXiao-2021 commented
> Good job on the test cases. Kindly update the path ![image](https://private-user-images.githubusercontent.com/89441435/309524391-cbd6fffe-4e60-42b1-98a7-f293016fca6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NDEyMjYsIm5iZiI6MTcwOTQ0MDkyNiwicGF0aCI6Ii84OTQ0MTQzNS8zMDk1MjQzOTEtY2JkNmZmZmUtNGU2MC00MmIxLTk4YTctZjI5MzAxNmZjYTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA0NDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYTc3MjY3YjZlMzM0OGU2ZjkwNjA3N2NmZmZiMTYwZjMxYmZmYjdhNGU5MzU1YzUxNGYwOTA3MzUwYTlmM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FoePpIhoeSUM65NaShXf8J7N6hsdMsSsE0SainB4vrE)

update the path, please review

2024-03-09 07:31 UTC, iTvX approved these changes

2024-03-09 16:28 UTC, vikrambadhan approved these changes
Hi, I tested your PR and all the test cases passed!

![Week 28 - PR3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/76508023-0b0a-448e-bd8f-c8d40f761577)

2024-03-10 06:32 UTC, ramyaram2092 approved these changes
Looks good !

2024-03-11 22:14 UTC, merged