Handled the scroll issue
OneCommunityGlobal/HighestGoodNetworkApp pull request #2002
Opened 2024-02-28 02:18 UTC by ThapeloMasasa

# Description
This PR handles the issue of scrolling along the horizontal axis on the teams page:
<img width="749" alt="Screenshot 2024-02-27 at 5 56 04 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/629a6b15-a084-490d-b67e-4516022e7686">

## Related PRS (if any):
This frontend PR is related  No backend PR so use development for backend

…

## Main changes explained:
- Made the table to be responsive…
…

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/4f26295e-91e4-4e23-a634-8ecdb8af7bc1

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other links→ Teams→…
6. verif that there is a horizontal scroll bar at the bottom of the table when the window is shrunk

2024-02-28 04:44 UTC, ShengjieMao approved these changes
The scroll bar functioned properly as described in the instruction. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/1590838c-b286-45cc-a910-33db765abf14

2024-02-28 19:01 UTC, meetpadhiar4 approved these changes
Hi, I tested your PR and it is working correctly. The layout of the table is responsive and it is rendering without any errors. Please refer the attached video.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/802fb448-dff7-442e-b190-7a49f9deefdc

2024-02-28 22:08 UTC, FyisFe approved these changes
I tested your PR and it is working correctly.
The video is attached 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59299011/e03f54d8-8a9f-4a29-808e-502ea1365ee9

2024-02-28 23:46 UTC, XiaohanMeng approved these changes
Hi, I tested this PR and it worked as intended. The scroll bar functioned correctly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/665c2b23-3f9e-44b9-8567-71b36e24e41f

2024-03-01 09:46 UTC, Gugor99 requested changes
### Report
Hey Masasa, 
I tried your implementation but unfortunately I had some issues, here are the steps I followed: I logged in as admin and navigated to the teams page, there I shrank the window but unfortunately I couldn't see the horizontal scroll bar. I then tired to log in with another user but I had the same issue. I think it may be caused by my browser Firefox, which in general drops a few style declarations. Anyway my keyboard arrows were working just fine to move on the page horizontally and vertically! Please see screenshots for reference.
### Screenshots
![Cattura1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/4762d9ca-524d-4745-b91f-8dab3f09b608)
![Cattura2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/0e2a191d-a961-42f6-a7c4-aab9d165c2f7)

2024-03-01 17:44 UTC, navyasrim approved these changes
Hi Manasa,
Tested your  code, scroll is working horizontally when resized...but I can only see the scroll bar when I move all the way down (but without seeing the scroll bar if I drag with my mouse or key pad the scroll is moving) if this is the functionality ..it is working as expected ..Attached video for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/77515207/b3387d4a-6849-4cc1-a8a8-42e3845428cb

![PR-2002-Approve](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/77515207/a001d78d-1fbd-45b5-9b07-f0ddadb7c0d0)

2024-03-01 19:36 UTC, merged