Yi - User Profile: Remove inactive accounts from summary intro
OneCommunityGlobal/HighestGoodNetworkApp pull request #2024
Opened 2024-03-04 23:25 UTC by FyisFe

# Description

When clicking `Generate Summary Intro` button on the user profile, it generates an intro for the weekly summary to state who on their team submitted summaries. Now, inactive users are ignored when generating the summary.

<img width="813" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59299011/3a7a3382-bb5a-44d4-8e69-982a23b971f7">

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
- Ignore inactive users when generating summary intro.
- Add error handling.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as a user that is in any team
5. go to dashboard → `View Profile` -> Click `Generate Summary Intro` button
6. verify if inactive users in the team are ignored in the report.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59299011/4dfd7d66-2a48-498a-ba63-6507cd6565e2

2024-03-05 13:30 UTC, Gugor99 approved these changes
### Report
Hi Yi,
I tried your implementation and it seems to be working as intended! To test your changes I followed these steps: I logged in as admin, I submitted my summary and then checked on my own account with the "generate summary intro" button. As expected I was the only one of my three members team that submitted and all the team's names were mentioned. I then modified my testrole account and put it inactive, did the check a second time and the inactive account wasn't included in the summary. The app works smoothly, well done!
### Screenshots
![Cattura1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/9fe18f81-ea16-44a9-b805-f2f1a270646d)
![Cattura2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/0ea69414-1cae-4943-8f04-d1474d6a4b7e)
![Cattura3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/4b12a9f8-1625-49d1-a27f-2f6bfbed47c0)
![Cattura5](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121721730/47a76d96-54ac-4e43-8c81-c5942f7ce775)

2024-03-05 16:41 UTC, meetpadhiar4 reviewed
Hi, I tried testing your PR but when I go to the view profile section, the entire page becomes unresponsive and I am unable to click any buttons. I am checked out to the latest dev backend branch and have cleared my browser data as well. Please refer the video attached.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/ada8aa98-9650-4987-b673-5ab28f0c2071

2024-03-05 17:42 UTC, Weiyao-Li commented
Hi, I also noticed the issue that when I logged in and clicked view profile, the entire page becomes unresponsive. I must hard refresh so that I can continue the testing.

<img width="2012" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/96925606/1f7d5a47-97fa-40df-82ed-38eca388b2be">

2024-03-05 19:20 UTC, psharma1984 reviewed
Hi @FyisFe I noticed the screen becomes unresponsive after i logged in and accessed the View Profile link. Please see the video below

[screen-capture (1).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/72b1e1a0-80aa-4224-8a2e-e730e67fb8f1)

2024-03-05 20:44 UTC, DiegoSalas27 commented
Hi Yi,

I tested your PR, but it doesn't comply with the description. We only list the team members who have not completed their weekly summary report, instead of the ones who actually did complete their weekly report. 

In addition, I was struggling to test your PR since the web page was being unresponsive for a long periord of time. Maybe the database was being bombarded at that time. Still I found many issues with HTTP requests being made to the backend. This is a separate issue which I debugged and I am attaching a video not only testing your PR, but also exposing these errors, which should be addressed.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26840798/f4033186-f604-438c-9b9a-9b536b133350

2024-03-05 21:45 UTC, Coops023 requested changes
Hi Yi, i have reviewed this PR and when i view the user profile page, it seems to be unresponsive and i cannot generate the summary info. because of this i am unable to approve this PR.

2024-03-05 22:13 UTC, FyisFe commented
Hi guys, thank you for your comments. 

Since I'm unable to replicate the unresponsive bug you've mentioned, could you please switch to the dev branch and confirm if the issue persists there? If it does, I'll include it in the bug report and address it.

2024-03-06 10:19 UTC, Tiantian-C reviewed
Hi,
I have just tested it but I can't see the Generate Summary Intro button. 
<img width="1428" alt="Screenshot 2024-03-06 at 2 19 16 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/d12a7d6e-3fe4-4c6c-ba62-a77cb2c97d8c">

2024-03-06 16:57 UTC, PratimaSingh02 requested changes
Hi,
As mentioned by other devs, View Profile page does become unresponsive. I see the major reason could be react-error-overlay which makes your page unresponsive, when a runtime error is encountered. One of the plausible reasons could be Reference Error that is our env variable isn't getting picked/read because the plugins weren't configured properly in webpack.config.js or so. (We might need to upgrade the react-scripts dependency)
Also I can see there is an 404 error being thrown for the api/reason/:id endpoint.
![2024 Yi - User Profile Remove inactive accounts from summary intro](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/48998232/3e3a2594-706e-4e55-992c-06202fd473e0)

2024-03-06 17:01 UTC, PratimaSingh02 commented
> Hi guys, thank you for your comments.
> 
> Since I'm unable to replicate the unresponsive bug you've mentioned, could you please switch to the dev branch and confirm if the issue persists there? If it does, I'll include it in the bug report and address it.

This issue doesnt persist for me in the dev branch

2024-03-06 23:41 UTC, hetvi11110 approved these changes
I tested the code as a manager role user and followed the process as mentioned. It is working fine on my local environment. Here is the reference video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/985c4362-0cef-44d2-a62c-437d50b1017e



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/2e369c90-d45d-47e3-a898-e8d66486da42

2024-03-07 20:15 UTC, navyasrim approved these changes
Hi,
Tested the  changes, the first summary is with active users and after than I made the DevMNav user inactive..then again generated the summary and this time
 inactive users are ignored when generating the summary ..
![PR-2024-2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/77515207/68ce1f1f-b6a0-48bb-b1c8-0adf0b291df2)

2024-03-07 21:48 UTC, rajnada commented
Hii,

It's working completely fine I have tested as you mentioned the steps.
Thanks

Here is the preview of the test

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25640436/39a9894d-4f6e-49bc-b4ae-6485774e23e6

2024-03-08 00:41 UTC, nathanah approved these changes
Looks good to me

2024-03-08 02:51 UTC, one-community commented
Thank you all, merging!

2024-03-08 02:51 UTC, merged