Project Title, Sorting task button, and Spaces between back button and return title
OneCommunityGlobal/HighestGoodNetworkApp pull request #2062
Opened 2024-03-15 02:48 UTC by mohabbasd

# Description
Add title and sort functions to Projects WBS Pages:
Fixes # (PRIORITY MEDIUM)

## Related PRS (if any):
To test this PR check into current branch for Frontend and for backend use the development branch.
…

## Main changes explained:
- Added title of the project for WBS
- Added a button named as "Name" for sorting the tasks under the WBS of each project
- Added spaces between the back button and added new text saying "Return to..." to make it look clean
- Added the name of the task at the top
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links → Projects → WBS Icon
6. Explained everything in the video below.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/cfce3363-7739-4b48-9040-1b67a636635d

2024-03-15 04:08 UTC, Abi-Liu submitted a review, later dismissed
Hey I reviewed the PR and it works as expected. I think the current design of the name button having 3 functionalities is a bit unintuitive and it is also not very clear what that button does to begin with.  When first looking at the page, I thought the name button would also add a new WBS task but in reality, it's just used for sorting.

I think it would be better if we broke it up into more meaningful ways, for example we could move the sorting button/functionality inside the `name` cell in the table. We could break it up furhter by either having two buttons either having `Sort Ascending` or Up/down arrows. We could also have a drop down menu where users can click and choose how they want to sort, but it's your decision on how you want to implement it.

2024-03-15 18:28 UTC, meetpadhiar4 submitted a review, later dismissed
Hi, I reviewed your PR and it is working as intended. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/aa262d07-af72-40c7-8672-2ba4fb059504

2024-03-28 19:17 UTC, MQChen211 submitted a review, later dismissed

2024-03-28 19:44 UTC, kylepham requested changes
Texts are displayed correctly. The only concern that I have is the button "Name" that you added. Having it displayed next to the input field without any indications whether it's for sorting purposes makes it unintuitive. I wouldn't know it's for sorting until I read your description or try it out.

2024-03-28 19:44 UTC, kylepham commented on src/components/Projects/WBS/wbs.jsx
> +  };
I don't think implementing toggleSort by keeping track of click counts is a good approach. The more useState we put into the component, the worse the performance will be.

2024-03-28 19:44 UTC, kylepham commented on src/components/Projects/WBS/wbs.jsx
> +        <AddWBS projectId={projectId} toggleSort={toggleSort} />
`toggleSort` doesn't align with the purpose of the `<AddWBS />` component. There should be a component dedicated to toggle sorting status. Leaving it this way would be unintuitive to further develop.

2024-03-28 20:20 UTC, hetvi11110 approved these changes
I have reviewed PR as explained, and it is working as expected. Here is the reference video attached to review.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/1f8a8c77-e2cb-4c65-901d-b6dd150e81ea

2024-03-29 01:03 UTC, iven-yao submitted a review, later dismissed
just reviewed this pr, and checked all the following feature mentioned in the video
- [x] centered project name
- [x] the return to Project/ return to WBSs string display as expected
- [x] Name button will sort the wbss in asc/desc orders
- [x] after adding a new task in one wbs, the wbs will be on top of the list

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/7a7a107b-7953-4e07-8ebe-0145ae2475f1)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/437d3ae0-1bb9-4bd4-8ff3-d77dd5a8a298)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/c2e38f9c-83ac-4a4e-9676-23c65c3fd7ea)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/d7cc8295-c121-4451-8216-363274ece2cf)

2024-03-29 15:43 UTC, ImzIssa submitted a review, later dismissed
Hey, I've tested your PR and everything works however consider renaming the "name" button to something that can be understood easily like "sort". Also I noticed that input is not cleared when a new task is created and the add button also still show unless the input is manually cleared.

![PR 2062](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/87269725/c5e8cdc7-103d-4fc0-9cff-ddc7a1560284)
![PR 2062 (2)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/87269725/22ce8121-00ee-4358-a9a3-81c4676ceb9e)

2024-03-29 19:04 UTC, SRamen1999 submitted a review, later dismissed
After reviewing this PR everything works as expected. They only thing I would change is the sorting button called "name". I feel like the name is misleading as it is used to sort tasks. 

The name of the project is shown correctly at the top 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/df446662-ab43-415a-a75b-7a5fc9e7fea9


The sorting functionality works as intended. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/a0ed704a-c89d-4751-860b-02398f0de9eb


The tasks name is shown on top and the two buttons to go back to projects and to wbs work correctly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/e014b1d6-13dd-4e80-8d65-ff7860e44c1f

2024-03-31 01:20 UTC, anandsesha commented
Hi, I have tested this PR and all functions work as described in the video.


- The chosen project name is center-aligned
![a](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/c576b9d8-587f-4550-9cf4-3ed73d9bd262)

- WBS -> added a task -> any edit made hence its sorted at the top 
![b1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/bf78be24-f94a-457c-b623-eef8ab01e02c)
![b2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/e638ce7a-357a-44f9-b506-ad48df04be69)

- Name button to sort tasks – 1st click asc, 2nd  desc and 3rd to default
![c1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/7a91a539-b76b-4d90-ba87-7ad412ad9bc8)
![c2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/29069c3a-583b-49f3-a189-d9ea7234c7e1)

- Space between back button and Return text + vertically aligned
![d](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/c4ec62a3-c142-4a12-8c8f-c640e47cacf2)

- Individual task centered and shown in task page 
![e](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/c180048a-d52b-40b1-97bb-6a72eb13fb4b)

Kindly rename the "name" button to "sort" for clarity and input clears on new task creation as mentioned by @ImzIssa.

2024-04-02 00:00 UTC, one-community commented
> Hey I reviewed the PR and it works as expected. I think the current design of the name button having 3 functionalities is a bit unintuitive and it is also not very clear what that button does to begin with. When first looking at the page, I thought the name button would also add a new WBS task but in reality, it's just used for sorting.
> 
> I think it would be better if we broke it up into more meaningful ways, for example we could move the sorting button/functionality inside the `name` cell in the table. We could break it up furhter by either having two buttons either having `Sort Ascending` or Up/down arrows. We could also have a drop down menu where users can click and choose how they want to sort, but it's your decision on how you want to implement it.

Yes, I agree. Please do this.

2024-04-02 01:04 UTC, Parth-tech commented
Hey,
Everything works as intended. I have attached a video as well.

- [ ] Return to Projects/Return to WBS
- [ ] Name of Project/ Task Center Aligned
- [ ] Recently edited WBS appears at Top
- [ ] Sort works in Ascending/Descending/Natural Order

Suggestions:

- `Name` is confusing and I wouldn't have clicked on it to sort unless I saw your video. Maybe you can offer a drop down with 3 values, Ascending, Descending
- After writing `WBS Name` I clicked on `Add New WBS` thinking it is a button, but I realized I had to click on `+` to add a new WBS. Maybe we can discuss this with others and understand whether or not they were confused.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/a17c208d-8326-4feb-ad1e-db67c9e58834

2024-04-02 23:17 UTC, Parth-tech approved these changes

2024-04-03 04:39 UTC, Gayathr-2012 commented
Hi 
 I reviewed these steps it works as expected. Good job
 centered project name
 the return to Project/ return to WBSs string display as expected
 Name button will sort the wbss in asc/desc orders
 after adding a new task in one wbs will be on top of the list

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/41faccaf-4c39-4afb-84e6-4c54ebcad7b9)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/abb74849-930e-4b28-9bed-61e6335c779a)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/bf6e0ce3-9d9b-4c60-a760-fc33207ed899)

2024-04-03 15:18 UTC, Jaiwin-4998 submitted a review, later dismissed
HI Mohammad, I just checked your PR and it working as you mentioned in the video.
Here are the images of the testing.
<img width="1440" alt="Screenshot 2024-04-03 at 11 09 59 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62836815/3351d425-7c4f-4ee0-87f1-372574fc06c5">
<img width="1440" alt="Screenshot 2024-04-03 at 11 07 16 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62836815/87b23c84-5ac4-4b76-a531-89f86f9d3139">
<img width="1440" alt="Screenshot 2024-04-03 at 11 07 05 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62836815/b73ae05c-9479-4c93-9d57-992aad133443">

2024-04-03 19:54 UTC, bhuvaneswarignanasekar reviewed
I have reviewed the PR. Renaming the button from 'name' to something like 'sort', and/or moving the button below the text box and above the table might be clearer. Additionally, having an arrow in the button could specify its sorting function.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59138503/316442c8-d4c9-4e50-b26a-fed6243f666a

2024-04-05 01:25 UTC, SushmithaPrathap requested changes
Hey, I've gone through this PR and followed the steps provided. Everything looks good, and the texts are displayed correctly. My only concern is about the "Name" button you added next to the input field. Without any clear indications, it's not immediately obvious that it's intended for sorting. I wouldn't have guessed its purpose without reading your description. 
Maybe adding a tooltip or a small icon could help clarify its function at a glance?
The name is Name button unintuitive, having a more explicit button for sorting will be better.

here are two screen recordings and screenshots:
<img width="1469" alt="Screenshot 2024-04-04 at 9 16 32 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/b9bde456-bf58-4734-891f-2f5e00832633">

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/37b4fdb7-2c08-4b5f-bbaf-46ff237e006f

2024-04-05 20:26 UTC, hiralsonip commented
I've reviewed the changes, and everything seems to be working well. I do have one suggestion though. The button labelled "Name" is a bit confusing because it's responsible for sorting. So, its name doesn't match what it does.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66827672/0fc6c49d-3ea4-40ac-afce-e56cdea65baa

2024-04-12 14:58 UTC, MohdShahzil29 approved these changes
Working perfectly

https://www.loom.com/share/7db807f6946744b5b605d44716c353cd

2024-04-20 23:26 UTC, Tiantian-C submitted a review, later dismissed
Hi, I have reviewed your PR, and it works as intended!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/152c67e7-4eb5-432d-ac07-e957b11a3e4e

2024-04-21 05:47 UTC, aaryaneil submitted a review, later dismissed
Tested the PR and all the changes work as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/8e741d16-62db-4b52-be34-7829b5f7430d

2024-05-11 17:47 UTC, KaushikMreddy requested changes
Hi @mohabbasd , 

I reviewed your changes, Your intended idea looks good but sorting is ambiguous. 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/6577050b-590f-42d6-baa3-10b11267fb22)

The up and down buttons are sorting, the sorting is not occurring properly. 

- The button with the "up arrow", sorts both ways ( making the "down button" useless). 
- Please update the PR's description with the change of the button from name to the arrows
- I suggest to add a button that says "sort" or use an icon that looks like this to show sorting by alphabetical order : 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/5b984c87-a60a-4e34-a3ff-e6cf32d7fb40)

Apart from that, 
The return button looks great, the spacing looks clean and the task name and project titles are appearing as expected. Good work!
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/f17cb2c0-8c3d-4fda-b6b3-c20833766b1a)

2024-05-23 21:08 UTC, mohabbasd commented
> Hi @mohabbasd ,
> 
> I reviewed your changes, Your intended idea looks good but sorting is ambiguous. ![image](https://private-user-images.githubusercontent.com/144624017/329804052-6577050b-590f-42d6-baa3-10b11267fb22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTg2NzgsIm5iZiI6MTcxNjQ5ODM3OCwicGF0aCI6Ii8xNDQ2MjQwMTcvMzI5ODA0MDUyLTY1NzcwNTBiLTU5MGYtNDJkNi1iYWEzLTEwYjExMjY3ZmIyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QyMTA2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjE4MzI4ZmQ4NjM0MmM2MzhhNzFkNTU4OGIyNGE5Y2RmYjM2MDZmYmYzNmFkMjQ2M2U0NzgwMTllYTQ2NTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lZsuMBGQHHnwkldDmU9xNvk1nNzLlHvpmMDxClehRyc)
> 
> The up and down buttons are sorting, the sorting is not occurring properly.
> 
> * The button with the "up arrow", sorts both ways ( making the "down button" useless).
> * Please update the PR's description with the change of the button from name to the arrows
> * I suggest to add a button that says "sort" or use an icon that looks like this to show sorting by alphabetical order :
>   ![image](https://private-user-images.githubusercontent.com/144624017/329804281-5b984c87-a60a-4e34-a3ff-e6cf32d7fb40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTg2NzgsIm5iZiI6MTcxNjQ5ODM3OCwicGF0aCI6Ii8xNDQ2MjQwMTcvMzI5ODA0MjgxLTViOTg0Yzg3LWE2MGEtNGUzNC1hM2ZmLWU2Y2YzMmQ3ZmI0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QyMTA2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGQ1ZjNhNDYwMTQ2MmI0ZGRjNjg1NWFiYTIyZDg5OGRhZWRjNjQzMWFmZDJkODUyZGNmODMyZThkOGNkZWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2I7c3EZ_vDva-HBkr1pvm5yXtk8C2cY6Y3mFZJRLU1s)
> 
> Apart from that, The return button looks great, the spacing looks clean and the task name and project titles are appearing as expected. Good work! ![image](https://private-user-images.githubusercontent.com/144624017/329804031-f17cb2c0-8c3d-4fda-b6b3-c20833766b1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTg2NzgsIm5iZiI6MTcxNjQ5ODM3OCwicGF0aCI6Ii8xNDQ2MjQwMTcvMzI5ODA0MDMxLWYxN2NiMmMwLThjM2QtNGZkYS1iNmIzLWMyMDgzMzc2NmIxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QyMTA2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWIyNDkxMzNjMzA2OTQwYTM4MTM5NzBmMGNkYjhjZmMyODM1OGU3MjM0YWYwYzFlYWVlMzI5MDc0MWUzMjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NKMbgDUs1ESNhQbkoGClfJlOKM2BwmzzlVULhLL-bak)

2024-05-23 21:13 UTC, mohabbasd commented
@KaushikMreddy 
Hello, Thank you for this suggestion, I will be implementing it shortly so that it is more clear.

2024-05-26 05:57 UTC, Sandhya1236 submitted a review, later dismissed
I checked out the current branch, ran npm install and the necessary commands to run the PR locally, and cleared the site data/cache. I logged in as an owner or admin, navigated to the dashboard → Other Links → Projects → WBS Icon. I verified the following updates: the project title was added for WBS, a button named "Name" was added for sorting tasks under the WBS of each project, spaces were added around the back button with new text "Return to..." for a cleaner look, and the task name was displayed at the top. All steps were followed successfully, confirming the updates were implemented and functioned correctly.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/22365b2a-233c-403b-8f49-02e51b8de0a6)

2024-05-27 03:46 UTC, nishithaShetty commented
HI Mohammad, Nice work!
The functionalities work as expected.
<img width="922" alt="PR#2062_1" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/84f8b15f-5736-48bf-a829-bf1febafde4e">
<img width="956" alt="PR#2062_2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/8d9d3364-fb7f-4df5-bed3-dac2340a62a6">

2024-06-06 02:52 UTC, Kavil-Jain-514 commented on src/components/Projects/WBS/wbs.jsx
A </div> closing tag is missing in line 132.

2024-06-06 03:00 UTC, Kavil-Jain-514 reviewed
The functionality works as expected. All the changes mentioned in the video work very well. There is a missing closing </div> in the wbs. js file.

The video has a review of the PR

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/e7f9bc47-a4d8-4501-91cc-52e89a2de5dd

2024-06-06 20:09 UTC, JatinAgrawal94 submitted a review, later dismissed
I was unable to click the "Other links" button due to the errors in code.
Please consider the video and screenshot to get a better idea of the errors.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/33450b2d-7cb6-4116-bf6c-50dfc590bd76

![Screenshot 2024-06-06 at 1 06 08 PM (2)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/09deafa8-542c-45fe-9f5f-a3d4dab72084)

2024-06-15 13:55 UTC, TXMO-dev approved these changes
Having reviewed this PR, everything works as expected and nothing breaks.

2024-07-11 20:54 UTC, Vigneshwar-Muriki approved these changes
Tested this PR as mentioned in the video and changes work as expected.

https://github.com/user-attachments/assets/9910158b-c4e7-4331-8fff-c20e34e7280b

2024-08-01 04:06 UTC, Pranay-ai submitted a review, later dismissed
Hey @mohabbasd 
I was reviewing your PR i had ran into some issues with the code
![image](https://github.com/user-attachments/assets/88628e9b-335b-43af-a1a9-b2e9ae5cdf3b)

Thank You

2024-09-09 02:18 UTC, one-community requested changes
Yes, please change this to two buttons. A plus on the left for adding a new WBS and this on the right for sorting A-Z (1 click) or Z-A (2 clicks). Default view should still show them in the order a WBS was edited, so the most recently edited one is always on top. 

Please make the title font **bold** too
![image](https://github.com/user-attachments/assets/551d0799-89c1-4bc6-9ef3-90d871085611)

Please change this to a centered delete button on large screens: 
![image](https://github.com/user-attachments/assets/413b2f75-64b1-4dca-8ae0-2a577010dad3)

To match this style: 
![image](https://github.com/user-attachments/assets/de3b97d0-140f-48bf-b507-c8410d6481e0)

Keep it a minus/- when on small screens

2024-09-13 14:29 UTC, swaroop-2007 requested changes
Hi @mohabbasd,
I was reviewing this PR and when I clicked on the WBS link I got this error. 
![Screenshot (397)](https://github.com/user-attachments/assets/9e39d8cf-0e7f-4cc8-ab8f-f8dc633953e0)
![Screenshot (398)](https://github.com/user-attachments/assets/877c8433-040b-42fe-b9b8-6db2865bf104)

2024-09-21 22:48 UTC, saurabhshetty29 commented
I tested this PR as demonstrated in the video, and the changes function as expected.

https://github.com/user-attachments/assets/68ebec46-12e8-4874-b442-f54b6c669a4c

2024-09-29 04:46 UTC, lcohen730 requested changes
Wasn't able to progress past clicking WBS icon in testing - next screen was blank page with five errors/warnings in console:

- Uncaught TypeError: Cannot read properties of undefined (reading 'projectName')
- Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
    in App (at src/index.js:10)
- Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
- Uncaught ReferenceError: process is not defined
- Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

![Screenshot 2024-09-29 at 00 42 28](https://github.com/user-attachments/assets/f493689a-f81b-4347-a70a-8de94e608c71)
![Screenshot 2024-09-29 at 00 42 35](https://github.com/user-attachments/assets/3967a8bc-91f7-40f7-90f5-2ff184592d7e)

2024-10-03 22:00 UTC, mrinalini-raghavendran19 requested changes
Hello,

I get an error when I click on the WBS icon - to be more specific, the projectId being passed in the props and params is undefined.

This error is being generated from wbs.jsx:

<img width="1470" alt="Screenshot 2024-10-03 at 2 58 02 PM" src="https://github.com/user-attachments/assets/5e98da50-8856-4cbc-af8e-58b2b1871245">

Don't know if this is an error with the latest version of development - backend code causing this issue. 

Let me know if there's something I'm missing to proceed with testing.

2024-10-06 03:52 UTC, khushijain03 requested changes
I couldn't go past the WBS icon in the tests; the blank page with errors and warnings in the console appeared on the following screen:

https://github.com/user-attachments/assets/32f8ea90-ed59-48a8-8020-255345428874

2025-04-17 05:50 UTC, closed without merging