Yi - Add Overview Report page's  sub tabs placeholders
OneCommunityGlobal/HighestGoodNetworkApp pull request #2071
Opened 2024-03-17 05:43 UTC by FyisFe

# Description
<img width="746" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59299011/6d0c1ca9-1965-450b-a62e-86b465c2ada5">

This PR is built on top of #2070 

## Related PRS (if any):
This frontend PR is related to the dev backend PR.

## Main changes explained:
- Add `'This Week', 'Last Week', 'Week Before Last', 'Three Weeks Ago` subtabs
- Add buttons to be used to show different stats

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as an user with `getOverviewReport` permission
5. go to dashboard→ Reports → OverviewReport
6. verify the UI

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59299011/8af32a52-2724-400d-93aa-083fd536e4f6

2024-03-17 21:14 UTC, Abi-Liu reviewed
Changes look good and the page renders as expected. However, on my screen the 5 buttons are not all on the same line even at max width. Not a huge deal but it might be worth looking into having them all aligned on a single line at max width.

You could maybe try using grid instead of flex for this. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59585815/6b8e0ad8-819c-4b29-bb79-6517ba1c75ab

2024-03-18 18:10 UTC, meetpadhiar4 requested changes
Hi, I tested your PR the overview page is rendering properly but the buttons are misaligned. Please refer the video attached.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/4e2dcd30-9522-4000-aeed-f454c34231ac

2024-03-19 05:41 UTC, dhairya-mehta commented
Hey, I verified the 4 tabs of this week, last week, week before last and three weeks ago but the alignment seems misplaced as others have pointed out!
<img width="1054" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56514777/4c475117-6796-47b7-8c24-8f912cb67ba3">

2024-03-20 11:54 UTC, ImzIssa submitted a review, later dismissed
Hello, I've tested your PR. I can view the page and the tabs are working fine.

![PR#2071](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/87269725/afd13094-77b5-4c44-acef-da0e69f26771)

2024-03-20 21:16 UTC, Pandani07 submitted a review, later dismissed
The button style is a bit off, but everything works as intended. It is responsive as well

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/42c16b13-4a2c-4220-9902-94712a584934

2024-03-31 01:33 UTC, mohabbasd submitted a review, later dismissed
Hello, I tested you PR and the UI looks good. Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/ed951f8d-9210-4364-90ec-438076ab1437

2026-08-14 16:38 UTC, closed without merging