Navneeth handle UI for resolveTask permission
OneCommunityGlobal/HighestGoodNetworkApp pull request #2074
Opened 2024-03-18 23:23 UTC by navneeeth

# Description
Please include the exact bug/functionality description and a summary of the changes/ related issues. Please also include any other relevant motivation and context:
Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ task→…
6. verify function “A” (feel free to include screenshot here)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2024-03-20 04:20 UTC, Abi-Liu requested changes
Overall it works as expected. I followed the testing instructions to allow my admin account to resolve tasks and I can now see and click on the green checkmarks to resolve tasks.

There are some areas where the code can be cleaned up, unused state variables, commented out useEffects, etc.

Some more areas that can be cleaned up outside of the comments I have left are the `handeUpdateTask` function inside of `src/components/TeamMemberTasks/TeamMemberTask.jsx` and `src/components/Timelog/Timelog.jsx`

That function is just setting the `shouldFetchData` state to true but that piece of state is not being used anywhere so it's just causing unnecessary rerenders.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59585815/d43e88fc-1350-49da-9bc9-0d176de51bd7

2024-03-20 04:20 UTC, Abi-Liu commented on src/components/Timelog/Timelog.jsx
> +  const [shouldFetchData, setShouldFetchData] = useState(false);
Remove this state as it's not being used anywhere.

2024-03-20 04:20 UTC, Abi-Liu commented on src/components/Timelog/Timelog.jsx
>    // useEffect(() => {
Remove excess code.

2024-03-20 17:53 UTC, navneeeth commented
> Overall it works as expected. I followed the testing instructions to allow my admin account to resolve tasks and I can now see and click on the green checkmarks to resolve tasks.
> 
> There are some areas where the code can be cleaned up, unused state variables, commented out useEffects, etc.
> 
> Some more areas that can be cleaned up outside of the comments I have left are the `handeUpdateTask` function inside of `src/components/TeamMemberTasks/TeamMemberTask.jsx` and `src/components/Timelog/Timelog.jsx`
> 
> That function is just setting the `shouldFetchData` state to true but that piece of state is not being used anywhere so it's just causing unnecessary rerenders.
> 
>  video1942620258.mp4

Hello, @Abi-Liu! Thanks for your thorough review. I have removed the ununsed state variable and some additional comments. Requesting you to review the PR again. Thanks!

2024-03-20 19:02 UTC, Abi-Liu approved these changes
Looks good!

2024-03-20 20:09 UTC, Pandani07 approved these changes
PR works as expected. I added the permission to my admin account and I could see the green tick mark to resolve tasks

2024-03-20 22:34 UTC, Coops023 approved these changes
Hi Navneeth, I tested this PR and after granting resolve task permission to my admin account i was able to resolve tasks on that account. Well done! 

<img width="769" alt="PR2074" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81972263/74e37ba0-40cf-4f81-bf50-3f2eac1fb4b4">

2024-03-22 00:17 UTC, hetvi11110 approved these changes
As mentioned here, I have reviewed this PR, and it is working as expected. Here is a reference video to look at.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/1e063628-037c-46ac-b3d0-34e6f4d68f53

2024-03-22 03:19 UTC, one-community commented
Thank you all, moving to final review.

2024-03-22 06:25 UTC, mohabbasd requested changes, later dismissed
Hello, I tested you PR and I faced an issue, since I don't have an admin account I tried to do it with a volunteer test account to add the project, task etc. I tried to add the permissions and the permission did not change whether it was owner or volunteer account, and when I try to go back to the dashboard everything goes blank. I tried it multiple times but the same issue keeps happening. Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/5f21a912-86bb-45a7-b2c6-6dfdda8cfad7

2024-03-22 08:08 UTC, navneeeth commented
> Hello, I tested you PR and I faced an issue, since I don't have an admin account I tried to do it with a volunteer test account to add the project, task etc. I tried to add the permissions and the permission did not change whether it was owner or volunteer account, and when I try to go back to the dashboard everything goes blank. I tried it multiple times but the same issue keeps happening. Below is a video for your reference.
> 
>  Screen.Recording.2024-03-22.at.2.21.52.AM.mov

Hello, @mohabbasd! Thanks for your review. I notice that in the video you shared, you have granted the wrong permission: Change the Bio Announcement Status. This implementation is for 'Resolve Tasks'. I also observe that your list of permissions in the shared video seem to be outdated. Please use the latest branch on the FE and the latest development branch on the BE to test this.

This implementation is one of many implementations for the list of permissions in the Permissions Management Fixes spreadsheet. It's not meant to be tested on a Volunteer account as a number of the other permissions as listed in the sheet, to be able to view the tasks in the dashboard, and a few others, are yet to be implemented and can lead to troubles testing on a Volunteer account. So, you can test it on an Admin account (by following the steps that I have shared) where the other permissions need not be implemented in order to test this specific implementation.  

Thank you!

2024-03-22 14:03 UTC, SRamen1999 reviewed
PR works as expected. I added the permission to admin account and I could see the green tick mark to resolve tasks.

Here I changed the code as specified 
<img width="1728" alt="Screen Shot 2024-03-22 at 9 42 43 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/abf695b3-0938-4b86-a9b9-7368b7389544">

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/7c8a851e-b5b2-4251-8e31-374efe8b0156

2024-03-22 20:40 UTC, rajnada commented
Hii,

I have changed the code as you mentioned in the instructions. And it's working well. Good Job!

Provide permission to Admin Account

<img width="1421" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25640436/70aedc0a-1045-4720-b7d4-2e88547f033b">

Here is the task that assigned :

<img width="1439" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25640436/2467c5b4-58ec-445a-abcf-4e0afed79e7d">

<img width="1436" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25640436/ebf30861-ec62-4472-b3c6-c6ee24262078">

Thanks

2024-03-22 22:00 UTC, iven-yao submitted a review, later dismissed
Hi I just review this request.

I login as an admin without resolve task permission, but I can still see green ticks, and able to mark it as done.

following screenshots show that with or without the permission, the task layout is just the same, if I misunderstood this request, please let me know. thank you.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/3e1c041b-baa6-40a4-9e7a-2445354bbd3d)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/82c441d0-2a99-433e-abe4-cc4e376f22e4)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/3556fbe8-c21d-4883-adca-4c88d5cf8452)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/654e7ceb-f330-4e76-b228-c53fe8bc952f)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/97d25527-c1ed-4b68-adb6-d84ee945eff9)

2024-03-23 14:36 UTC, yaow62023 approved these changes
Hi, i have test your PR fellowing the steps, all the functions work as intended. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/2543a94a-dc94-4152-92ca-91fb4699359b

<img width="638" alt="2074_2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/f67c9fac-e002-46c7-b4d4-c1f0843497dd">

2024-03-23 17:05 UTC, psharma1984 approved these changes
hi @navneeeth Clicking the green tick mark the task as resolved!!. Approving

[screen-capture.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/3b1584f2-f8f9-48f3-ae11-de66bbf3300a)

[screen-capture (1).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/445ed817-6339-41e7-87ca-92089f75a1d7)

2024-03-23 20:51 UTC, navneeeth commented
> Hi I just review this request.
> 
> I login as an admin without resolve task permission, but I can still see green ticks, and able to mark it as done.
> 
> following screenshots show that with or without the permission, the task layout is just the same, if I misunderstood this request, please let me know. thank you. ![image](https://private-user-images.githubusercontent.com/25358966/316176762-3e1c041b-baa6-40a4-9e7a-2445354bbd3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzY3NjItM2UxYzA0MWItYmFhNi00MGE0LTllN2EtMjQ0NTM1NGJiZDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNTUxNGYwYWUwNTk3ODMyZDQ3NzIxZjM4YWQ3NzE2MzhkYjkxZWE5MzM4YjI4M2MyM2E1OWQ3MTI5N2U0NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Sz2rh0YCrELkYXrI0DVLX1k3HYd6wrD9fpvQwcTHOA) ![image](https://private-user-images.githubusercontent.com/25358966/316176973-82c441d0-2a99-433e-abe4-cc4e376f22e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzY5NzMtODJjNDQxZDAtMmE5OS00MzNlLWFiZTQtY2M0ZTM3NmYyMmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MGRhYTc0YWU2ODBmZmIzMzE3YTIzYjkwMTUzNGYzZWFmOGZlZjMyYjgyNjhkNGE5MDg1NGZiODNlZWYyZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GfHaKVYO6Mdvx7iW7Qt0w2C81sr7tKd-M2VLHLoHiJs) ![image](https://private-user-images.githubusercontent.com/25358966/316178177-3556fbe8-c21d-4883-adca-4c88d5cf8452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzgxNzctMzU1NmZiZTgtYzIxZC00ODgzLWFkY2EtNGM4OGQ1Y2Y4NDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNDhjZjI5MmM2YjA5ZjNmYTNhOGIzMDViZDg1MDYyNGIxMDc0YjRhYjU3OThkYTgyZTIxYTFkNDk2NTkzMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9pe35MdbdJsJxvXaqEEdj17Z_ZSQD9RVN3OuN-VIfQU) ![image](https://private-user-images.githubusercontent.com/25358966/316177734-654e7ceb-f330-4e76-b228-c53fe8bc952f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzc3MzQtNjU0ZTdjZWItZjMzMC00ZTc2LWIyMjgtYzUzZmU4YmM5NTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMjgwNWRiZGJjOTk4ZmI5YmU1ZTcyNzMxNmIwNDNhN2ExNTRlZmI4YWU5OTlmODk2MTFjZDE5NGU4ZWRlZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rc9JXkeuitc1w34uObIYUnUBhu6shgk5PVP-qL88miE) ![image](https://private-user-images.githubusercontent.com/25358966/316177659-97d25527-c1ed-4b68-adb6-d84ee945eff9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzc2NTktOTdkMjU1MjctYzFlZC00YjY4LWFkYjYtZDg0ZWU5NDVlZmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliN2E5NWEwYjlhMzg5NTUyYTFhZjI4NWI3YThmZDhhY2RkM2M3ZTcyZmY3NTYyYzFiYjc3MDE0NGNkN2EzMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fzR5dejFv7UQzXl9xivscUw2uHQ293h1qYpuvZgTjS4)

Hello, @iven-yao! Yes, admins have this permission available by default--which is why I have provided a code update in the instructions to remove this default case. Please update line 65 as per the instructions and they should not be able to see the green tick (as long as they do not have this permission granted to them). Please try again. Thank you!

2024-03-23 21:27 UTC, iven-yao commented
> > Hi I just review this request.
> > I login as an admin without resolve task permission, but I can still see green ticks, and able to mark it as done.
> > following screenshots show that with or without the permission, the task layout is just the same, if I misunderstood this request, please let me know. thank you. ![image](https://private-user-images.githubusercontent.com/25358966/316176762-3e1c041b-baa6-40a4-9e7a-2445354bbd3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzY3NjItM2UxYzA0MWItYmFhNi00MGE0LTllN2EtMjQ0NTM1NGJiZDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNTUxNGYwYWUwNTk3ODMyZDQ3NzIxZjM4YWQ3NzE2MzhkYjkxZWE5MzM4YjI4M2MyM2E1OWQ3MTI5N2U0NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Sz2rh0YCrELkYXrI0DVLX1k3HYd6wrD9fpvQwcTHOA) ![image](https://private-user-images.githubusercontent.com/25358966/316176973-82c441d0-2a99-433e-abe4-cc4e376f22e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzY5NzMtODJjNDQxZDAtMmE5OS00MzNlLWFiZTQtY2M0ZTM3NmYyMmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MGRhYTc0YWU2ODBmZmIzMzE3YTIzYjkwMTUzNGYzZWFmOGZlZjMyYjgyNjhkNGE5MDg1NGZiODNlZWYyZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GfHaKVYO6Mdvx7iW7Qt0w2C81sr7tKd-M2VLHLoHiJs) ![image](https://private-user-images.githubusercontent.com/25358966/316178177-3556fbe8-c21d-4883-adca-4c88d5cf8452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzgxNzctMzU1NmZiZTgtYzIxZC00ODgzLWFkY2EtNGM4OGQ1Y2Y4NDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNDhjZjI5MmM2YjA5ZjNmYTNhOGIzMDViZDg1MDYyNGIxMDc0YjRhYjU3OThkYTgyZTIxYTFkNDk2NTkzMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9pe35MdbdJsJxvXaqEEdj17Z_ZSQD9RVN3OuN-VIfQU) ![image](https://private-user-images.githubusercontent.com/25358966/316177734-654e7ceb-f330-4e76-b228-c53fe8bc952f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzc3MzQtNjU0ZTdjZWItZjMzMC00ZTc2LWIyMjgtYzUzZmU4YmM5NTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMjgwNWRiZGJjOTk4ZmI5YmU1ZTcyNzMxNmIwNDNhN2ExNTRlZmI4YWU5OTlmODk2MTFjZDE5NGU4ZWRlZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rc9JXkeuitc1w34uObIYUnUBhu6shgk5PVP-qL88miE) ![image](https://private-user-images.githubusercontent.com/25358966/316177659-97d25527-c1ed-4b68-adb6-d84ee945eff9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzc2NTktOTdkMjU1MjctYzFlZC00YjY4LWFkYjYtZDg0ZWU5NDVlZmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliN2E5NWEwYjlhMzg5NTUyYTFhZjI4NWI3YThmZDhhY2RkM2M3ZTcyZmY3NTYyYzFiYjc3MDE0NGNkN2EzMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fzR5dejFv7UQzXl9xivscUw2uHQ293h1qYpuvZgTjS4)
> 
> Hello, @iven-yao! Yes, admins have this permission available by default--which is why I have provided a code update in the instructions to remove this default case. Please update line 65 as per the instructions and they should not be able to see the green tick (as long as they do not have this permission granted to them). Please try again. Thank you!

Thank you for pointing out, I tried again and it works perfect as expected.

2024-03-23 21:28 UTC, iven-yao approved these changes
> > Hi I just review this request.
> > I login as an admin without resolve task permission, but I can still see green ticks, and able to mark it as done.
> > following screenshots show that with or without the permission, the task layout is just the same, if I misunderstood this request, please let me know. thank you. ![image](https://private-user-images.githubusercontent.com/25358966/316176762-3e1c041b-baa6-40a4-9e7a-2445354bbd3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzY3NjItM2UxYzA0MWItYmFhNi00MGE0LTllN2EtMjQ0NTM1NGJiZDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNTUxNGYwYWUwNTk3ODMyZDQ3NzIxZjM4YWQ3NzE2MzhkYjkxZWE5MzM4YjI4M2MyM2E1OWQ3MTI5N2U0NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Sz2rh0YCrELkYXrI0DVLX1k3HYd6wrD9fpvQwcTHOA) ![image](https://private-user-images.githubusercontent.com/25358966/316176973-82c441d0-2a99-433e-abe4-cc4e376f22e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzY5NzMtODJjNDQxZDAtMmE5OS00MzNlLWFiZTQtY2M0ZTM3NmYyMmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MGRhYTc0YWU2ODBmZmIzMzE3YTIzYjkwMTUzNGYzZWFmOGZlZjMyYjgyNjhkNGE5MDg1NGZiODNlZWYyZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GfHaKVYO6Mdvx7iW7Qt0w2C81sr7tKd-M2VLHLoHiJs) ![image](https://private-user-images.githubusercontent.com/25358966/316178177-3556fbe8-c21d-4883-adca-4c88d5cf8452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzgxNzctMzU1NmZiZTgtYzIxZC00ODgzLWFkY2EtNGM4OGQ1Y2Y4NDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNDhjZjI5MmM2YjA5ZjNmYTNhOGIzMDViZDg1MDYyNGIxMDc0YjRhYjU3OThkYTgyZTIxYTFkNDk2NTkzMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9pe35MdbdJsJxvXaqEEdj17Z_ZSQD9RVN3OuN-VIfQU) ![image](https://private-user-images.githubusercontent.com/25358966/316177734-654e7ceb-f330-4e76-b228-c53fe8bc952f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzc3MzQtNjU0ZTdjZWItZjMzMC00ZTc2LWIyMjgtYzUzZmU4YmM5NTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMjgwNWRiZGJjOTk4ZmI5YmU1ZTcyNzMxNmIwNDNhN2ExNTRlZmI4YWU5OTlmODk2MTFjZDE5NGU4ZWRlZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rc9JXkeuitc1w34uObIYUnUBhu6shgk5PVP-qL88miE) ![image](https://private-user-images.githubusercontent.com/25358966/316177659-97d25527-c1ed-4b68-adb6-d84ee945eff9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjcyNTQsIm5iZiI6MTcxMTIyNjk1NCwicGF0aCI6Ii8yNTM1ODk2Ni8zMTYxNzc2NTktOTdkMjU1MjctYzFlZC00YjY4LWFkYjYtZDg0ZWU5NDVlZmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIwNDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliN2E5NWEwYjlhMzg5NTUyYTFhZjI4NWI3YThmZDhhY2RkM2M3ZTcyZmY3NTYyYzFiYjc3MDE0NGNkN2EzMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fzR5dejFv7UQzXl9xivscUw2uHQ293h1qYpuvZgTjS4)
> 
> Hello, @iven-yao! Yes, admins have this permission available by default--which is why I have provided a code update in the instructions to remove this default case. Please update line 65 as per the instructions and they should not be able to see the green tick (as long as they do not have this permission granted to them). Please try again. Thank you!

Thank you for pointing out, I tried again and it works perfect as expected.

2024-03-24 04:00 UTC, Sarthak32 approved these changes
Hi I tested this PR as you asked It works well!
![Screenshot 2024-03-24 092534](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/2b8e3e26-4e4c-4beb-a7b1-f66f00fe29c2)
![Screenshot 2024-03-24 092546](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/a383f3f2-18dc-4050-b869-8e86af87afd2)

2024-03-25 02:10 UTC, Tiantian-C approved these changes
The function works as intended. Well done!
<img width="990" alt="Screenshot 2024-03-24 at 7 09 38 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/74a8a2d5-85fe-4ee1-971f-a8519d2483f5">

2024-03-27 03:06 UTC, kylepham approved these changes
Functionality works as expected. Users with 'Admin' role can resolve their tasks. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/63a06717-98a9-4417-86cb-975c8ef09304

I have a question: does this mean to work only for owner and admin roles? I tried granting a volunteer account the "resolve task" permission but failed to resolve because of unauthorized request. The task agenda doesn't seem to specify this case.

2024-03-27 21:02 UTC, Gayathr-2012 commented
Hi ,
I reviewed your PR. It works as expected. Good Job.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/770a4d2b-9b59-48eb-88c0-5fed786a6c8c)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/99ea1f98-9b78-468c-9d3b-03ddc3688744)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/60f26435-ef6e-4116-9132-2eb4441afc23)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/0653d226-be80-403b-a76c-f5f55e49caa4)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/9c3756c4-5c06-4b8a-b1f7-8a55fb18be73)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/98d7aeac-a1be-4f89-b6b0-8dc0c141ea6c)

2024-03-27 23:49 UTC, SanketKaware approved these changes
I have followed the mentioned steps to test this functionality and it works as expected.

After adding the permission to the Admin account, I was able to see the ‘green tick’ icon and resolved the task as well.

Please find my below video reviews for reference

**Before**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/1b42eb1c-d627-44a5-bed6-b75fc4ccc7ad



**Add Permission**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/f77f1ec7-f5ff-44b3-92e2-61cec2cc022c


**After**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/333ab896-53d7-476e-981b-12cc1d3fe7b0

2024-03-29 23:16 UTC, merged