Peterson impl feature finish my team filter or tasks tab
OneCommunityGlobal/HighestGoodNetworkApp pull request #2078
Opened 2024-03-21 14:33 UTC by peterson337

# Description
The filter was created for administrators, core team members, and owners. These users require the filter as they oversee all users listed in the Leaderboard and the Team Member Tasks tables, rendering all tools for reviewing user work useless.

## Related PRS (if any):
None
…

## Main changes explained:
The components 'Team Members' and 'Leaderboard' were modified to implement the filter.

…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally   
3. The filter is exclusively visible to administrators, owners, and core team members; other users will not see the filter.
4.  Log in as an administrator, owner, or core team member to verify the visibility of the filter. Log in as any other user to confirm its invisibility.
5. to test this PR you need of two or more teams.
6.  If you need to create a team, click on 'Other Links' and select 'Teams.' Then, click on 'Create New Team' and enter the team name. Next, click the button within the 'Members' column to add yourself and other users.
![b](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/b486bff5-fe63-4239-a9ea-4905601f0eb1)
7. go to dashboard→ Tasks 
8. Click on the filter and select any team, then click on the "My Team" button.
9. After the table displays the team members, the button text will change to "View All." Clicking it again will reveal all users of the HGN software.
10. Verify the functionality of the filter with buttons for 1 day, 2 days, 3 days, and so forth.

## Screenshots or videos of changes:
![a](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/6b9b64cc-5cef-4a71-ae5d-332cb2f0769f)

## Note:
Before deleting a team, ensure all members are removed. If the team is deleted first, it may still appear in the filter.

2024-03-22 00:08 UTC, SanketKaware submitted a review, later dismissed
I have followed your steps as mentioned. Overall looks good.

It works as expected. 
1. When there was no team, I was unable to click on "My Team" on the dashboard.
2. After adding the team and its members, I was able to select the team and switch between "My Team" and "View All".
3. Worked for 1 day, 2 days, 3 days, and so forth.

Here is my video review for reference - 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/d34f1074-f90a-4ea8-be56-afa613e165d5

2024-03-22 16:27 UTC, meetpadhiar4 approved these changes, later dismissed
Hi, I tested your PR and it is working as intended. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/f73ccafb-fb88-4978-9def-22368ac557c3

2024-03-22 20:16 UTC, Abi-Liu submitted a review, later dismissed
Overall the changes work as expected! I can toggle to view between my individual teams vs all users inside the leaderboard and Team member tasks section.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59585815/a5a6b244-8cfd-4e1f-a63d-f70a59212c36

2024-03-23 02:49 UTC, abdel-lall reviewed
I've encountered an issue with the filter functionality—it's not functioning as expected. Please refer to the images below.

Before selecting a team:
![Screenshot 2024-03-22 213244](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/deafd5a8-3e0a-4d13-968f-9277cfe49a26)

After selecting a team:
![Screenshot 2024-03-22 213308](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/e4dbb5d4-c9d6-4ad4-b6f4-efae9a263351)

Additionally, the styling of the button below doesn't seem to be as it was before.
Before:
![Screenshot 2024-03-22 213357](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/3f1dba87-9207-45a8-b090-079a89b8bb5d)
After:
![Screenshot 2024-03-22 213340](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/332084ce-232b-433c-a706-190bea49e47b)

2024-04-04 16:17 UTC, SushmithaPrathap requested changes
Hey,
Just reviewed your PR and tested it following the steps provided.Here are my observations:

- The filter clearly indicates to create a team when none exist, which is helpful.
- Suggestion: Adding a "Create Team" button right there could streamline the process, leading users directly to the team creation page rather than navigating through the menu.
- It's great that the filter doesn't work for teams without members
- The toggle between "My Team" and "View All" feels a bit clunky
- Placing "View All" inside the dropdown is somewhat confusing. It might be more intuitive to have it separate from the team selection.
- The "My Team" blue button seems unnecessary since selecting a team from the dropdown already initiates the filter by that team. It could be more useful to repurpose this button for a "View All" functionality, simplifying the UI.
- The dashboard is going out of the view. Have to scroll horizontally

I've attached a screen recording to illustrate these points more clearly. Hope this feedback is helpful!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/cccdbc5c-bdcc-41e6-8258-2590a9b39a08


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/dd3d9ad5-1c64-426c-a19b-83bfd80b0540

2024-04-04 17:20 UTC, MQChen211 commented
Hello, I've reviewed and tested your pull request, and everything functions as anticipated. Utilizing an Owner account, I was able to create teams, assign members to those teams, and verify that this information accurately displays on the dashboard. Additionally, when accessing the system with a Volunteer account, the filter appropriately remained hidden, aligning with the expected behavior.

Tested with a Volunteer account:
<img width="1161" alt="截屏2024-04-04 13 13 16" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/6e4b850d-16f3-4ff5-918a-0e8df4af0b45">

Tested with an Owner account:
<img width="1069" alt="截屏2024-04-04 13 06 19" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/4e4ee8b7-c6ad-4070-b121-3e886318b875">

<img width="1030" alt="截屏2024-04-04 13 08 10" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/4bf14ad6-0d76-45af-9045-e90ba5fb6629">

<img width="1076" alt="截屏2024-04-04 13 09 47" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/118e9f20-6151-4ab4-8dbe-cefa9bf8fe74">

<img width="1162" alt="截屏2024-04-04 13 12 24" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/08f30c18-9b28-45b3-b099-0b613e2a9c19">

<img width="1149" alt="截屏2024-04-04 13 12 34" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/5090b23f-ed73-49aa-a137-eb29fd9e6aaa">

2024-04-04 17:28 UTC, MQChen211 submitted a review, later dismissed

2024-04-05 13:07 UTC, SRamen1999 submitted a review, later dismissed
Everything works as expected. I can toggle to view between my individual teams vs all users inside the leaderboard and Team member tasks section. Also there are safe checks in place when a user does not have a team or did not select a team.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/f9ca85b2-e9e0-4a62-9355-8a7e0f7b423a

2024-04-05 16:18 UTC, hiralsonip commented
I've reviewed the PR, and it looks good. However, I have a couple of suggestions:

1. Instead of having multiple dropdowns, we could simplify by having just one dropdown. Within this dropdown, we can include a "View All" button for ease of navigation.
2. If a user doesn't have a team, rather than displaying the text "Please create a team," we can make the "My Team" button functional. It could allow users to create a team directly.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66827672/eb316d55-4f5a-4e3d-a36d-80af9b5b20bf

2024-04-05 22:16 UTC, anandsesha requested changes

2024-04-05 22:16 UTC, anandsesha commented on src/components/LeaderBoard/Leaderboard.jsx
> +                        {team.teamName}
Hi, I've tested this feature and my observations are as below:
What works:
- Without adding team, the 'My Team' was not selectable as expected.
- Able to add team, add members, filter based on 'My Team' and 'View All' in dashboard.
- functionality of  filter with buttons for 1 day, 2 days and so forth works.
- Other users like CoreTeam/Volunteer can't see Team filter as expected.

**Issue**:
- When a team name with large characters is added, the same is reflected in the dashboard which disrupts the team selection view. (Refer Issue screenshots below at the end)

**Suggestion**: On line 270, recommend using `${team.teamName.substring(0, 10)}...` in the DropdownItem in the Leaderboard and under Team member task in dashboard page.

Other observations:
- After filtering based on a team in the leaderboard, when we hit refresh the list shows all users of the HGN software, even though a particular team is selected. (Please confirm if this is the expected functionality, screenshot attached)


![1 Created Team](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/51e083f5-cfc8-4547-b752-5f2e8636d024)
![2 assigned team members](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/84b8fad2-5e44-4912-8f95-b5bd827a49ea)
![3 Team filtered in dashboard](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/c61458bc-c1df-4d3d-96d7-08b20edf317b)
![4 viewAll expands  team](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/458840c3-80d9-4a41-b2bf-2e4f74b13d27)
![5 CoreTeam](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/f3c982c4-d5e6-468d-b974-25db1fd33f31)


**Issue screenshots:**
![Issue - Team length 2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/b0f83ccc-88dd-489f-af57-550ce2828f26)
![Issue - team length 3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/7393528a-fb15-437b-91d1-c13a298be57f)
![Issue - Team length](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/ccdc5d74-a292-407a-bfb1-bf8bbeeb568a)


Observation on leaderboard refresh:
![Observ - leaderboard update with team selection](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/9420dbc9-5d87-4dd6-8aab-ba9132b765dc)

2024-04-05 22:22 UTC, anandsesha requested changes
Hi, I've tested this feature and my observations are as below:
What works:
- Without adding team, the 'My Team' was not selectable as expected.
- Able to add team, add members, filter based on 'My Team' and 'View All' in dashboard.
- functionality of  filter with buttons for 1 day, 2 days and so forth works.
- Other users like CoreTeam/Volunteer can't see Team filter as expected.

**Issue**:
- When a team name with large characters is added, the same is reflected in the dashboard which disrupts the team selection view. (Refer Issue screenshots below at the end)

**Suggestion**: On line 270, recommend using `${team.teamName.substring(0, 10)}...` in the DropdownItem in the Leaderboard and under Team member task in dashboard page.

Other observations:
- After filtering based on a team in the leaderboard, when we hit refresh in the leaderboard, the list shows all users of the HGN software, even though a particular team is selected. (Please confirm if this is the expected functionality, screenshot attached)


![1 Created Team](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/51e083f5-cfc8-4547-b752-5f2e8636d024)
![2 assigned team members](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/84b8fad2-5e44-4912-8f95-b5bd827a49ea)
![3 Team filtered in dashboard](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/c61458bc-c1df-4d3d-96d7-08b20edf317b)
![4 viewAll expands  team](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/458840c3-80d9-4a41-b2bf-2e4f74b13d27)
![5 CoreTeam](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/f3c982c4-d5e6-468d-b974-25db1fd33f31)


**Issue screenshots:**
![Issue - Team length 2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/b0f83ccc-88dd-489f-af57-550ce2828f26)
![Issue - team length 3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/7393528a-fb15-437b-91d1-c13a298be57f)
![Issue - Team length](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/ccdc5d74-a292-407a-bfb1-bf8bbeeb568a)


Observation on leaderboard refresh:
![Observ - leaderboard update with team selection](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/9420dbc9-5d87-4dd6-8aab-ba9132b765dc)

2024-04-06 08:38 UTC, j-corp-25 approved these changes, later dismissed
Hi @peterson337 

I tested the feature based on the instructions and its working as expected. 
I tested with multiple buttons as well.

Below is the video;

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95154804/d5424a4d-3bbe-4dee-9df5-ad05fafc4545

2024-04-06 12:47 UTC, ImzIssa approved these changes, later dismissed
Hello, I've reviewed this PR and overall everything works as expected. Nice work.
![PR 2078](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/87269725/6e1bd73d-4e36-4bc6-a9ef-8b028ea86e34)
![PR 2078 (2)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/87269725/506b4e3c-3902-41ec-bc4b-0b8be8a1969a)

For improvements consider suggestions made by @SushmithaPrathap.

2024-04-07 01:26 UTC, p-suram reviewed
Works as expected. I have tried options in "Team Member Tasks" as well. 
**Suggestions:**
1. Parallelly write unit test cases as we keep adding new features
2.  `const TeamSelected = team => {
    const teamName = `${team.teamName.substring(0, 15)}...`;
    setSelectedTeamName(team.teamName.length >= 15 ? teamName : team.teamName);
    setUsersSelectedTeam(team);
    setTextButton('My Team');
  };`
  Extract above logic into a util function so that it can be reused in other places if required. (It can be a function which takes 2 input params, title: string, length: number and return text accordingly).

Rest all looks great. Please find the recording below

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/157307140/c3a81f92-cc92-49d7-b970-a150e0dd2bd4

2024-04-08 15:49 UTC, peterson337 commented
> * When a team name with large characters is added, the same is reflected in the dashboard which disrupts the team selection view. (Refer Issue screenshots below at the end)
> 
> **Suggestion**: On line 270, recommend using `${team.teamName.substring(0, 10)}...` in the DropdownItem in the Leaderboard and under Team member task in dashboard page.
>
> 
> * After filtering based on a team in the leaderboard, when we hit refresh in the leaderboard, the list shows all users of the HGN software, even though a particular team is selected. (Please confirm if this is the expected functionality, screenshot attached)
>
>

[@anandsesha](https://github.com/anandsesha),  I fixed the bugs in your comment. Please, refer to my GIF for further reference: 
![b](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/07e835ea-4caa-4c70-a9db-2912d3c7e259)

2024-04-09 00:14 UTC, Parth-tech approved these changes, later dismissed
Hi Peterson,
I have checked you PR and everything looks perfect. Great job!

Checks performed:

- [x] Button visible only to admins & owners
- [ ] `My Team` display the selected team
- [ ] `View All` allows to view everyone
- [ ] Test Leaderboard
- [ ] Test for `different days` under `Tasks Tab`

<img width="608" alt="Screenshot 2024-04-08 at 4 49 09 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/372d1540-5b16-4391-b92e-70553b04e7a5">

<img width="1440" alt="Screenshot 2024-04-08 at 4 47 16 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/09bcf821-fe79-41e4-ab8b-f932159e968a">

<img width="662" alt="Screenshot 2024-04-08 at 4 49 01 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/159311ed-9717-4525-9907-4fa18aee280a">

<img width="814" alt="Screenshot 2024-04-08 at 4 48 19 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/bd2e4473-0674-4ad7-9667-7800796ed4db">

<img width="824" alt="Screenshot 2024-04-08 at 4 48 10 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/1d76cf83-1c00-4cfb-9c10-bee12578bc36">

<img width="1440" alt="Screenshot 2024-04-08 at 4 49 31 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/2ebaa271-fb54-4b0a-b9eb-9c0254c35917">

I have a suggestion (for improving user experience, feel free to ignore as well):

1. Prefer hiding `My Team` button until the user has selected his team.
2. Whenever `selects a team` from the `dropdown` directly update the view automatically to display details about the team member (this is more intuitive); instead of user having to select a team from the drop down and then also click on the `My Team`

2024-04-11 22:36 UTC, anandsesha approved these changes, later dismissed
Hi, I tested this PR again and the Issue I reported earlier is fixed now. 

- Team name with large characters is displayed correctly in Team selection view om dashboard
- Refresh leaderboard doesn't load all HGN team members and works as expected 

Great Work!

Screenshots of change attached.
![Screenshot (777)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/8dd080aa-ee07-43fa-b79b-49366d1ad64a)
![Screenshot (778)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/e4ba5187-5393-443d-a261-6fd8439f3044)
![Screenshot (779)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/adef23c8-8ae6-460e-936b-0505d0bfc99b)
![Screenshot (780)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/8c9255fe-9ed3-4ba3-b2f4-81867e48ff97)
![Screenshot (781)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/fb695937-6c9d-4664-87b2-ebe71f33ff73)

After Leaderboard refresh in a team view:
![Screenshot (782)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/92387473-9354-4d4c-b556-abfc6abd7afc)

2024-04-13 02:11 UTC, SushmithaPrathap submitted a review, later dismissed
Hey, After reviewing the recent adjustments made to this PR, everything now works as expected. The issues previously highlighted have been effectively addressed, and the functionality aligns well with the requirements.

Here are the screenshots:

<img width="1469" alt="PR 2078 - 1" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/9fab985a-0dd9-4fa5-97fe-ed0b13a5f5e2">
<img width="1469" alt="PR 2078 - 2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/c30d1dd9-02b0-4b25-ada5-51b7f30eeab0">

2024-04-13 17:10 UTC, j-corp-25 submitted a review, later dismissed
Hi @peterson337 

I tested based on the instructions and the filter is working correctly. 

I have two teams under Admin and I can filter through them. I filter is also hidden from different roles. I also tested deleting a team and it doesnt show on the filter after I do this.

Screenshots and videos below:

- Admin View with Filter

![AdminView](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95154804/7f3db0ee-0979-4b80-9f90-3cad1ac99242)


- Volunteer view with no filter view

![VolunteerView](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95154804/367fbe99-e6c3-4572-8a66-7f81b5b84da1)

- Video following testing filter before and after deletion of teams


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95154804/a568ad52-4fde-4cdd-a87b-4f2631a15726

2024-04-13 19:58 UTC, p-suram reviewed
Changes look good working as expected. Filter is only visible for Admin, Owner users but not for Volunteer user. I have 2 minor suggestions:
1. Lines 224-225 of Leaderboard.jsx can be extracted into separate util function as this logic is being repeated quite a number of times.
2. I see team name as `Pooja_test_team...` even though team name is `Pooja_test_team`. Please find video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/157307140/14614f4f-5609-434b-84d8-dee46ffec51a

2024-04-13 22:11 UTC, metaphor987 reviewed
Hi Peterson,

I've tested the changes, and the main functionalities all work well. The team filter is only visible to admin accounts and not volunteer accounts, which works as expected.

The only issue I encountered is that when clicking on the "Tracking" button for a team member in "Team Member Tasks" on the left side (regardless of whether the member belongs to the admin's team or not), the "Leaderboard" on the right side automatically changes to show all members' info, even though we are still in "My team" mode. I'm not sure if this action is expected. Thank you!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/83e345a2-0e55-4ca9-bad0-d8c9c6ba6978

2024-04-14 00:45 UTC, Tiantian-C reviewed
I have tested it and it works as intended.
<img width="1420" alt="Screenshot 2024-04-13 at 5 44 15 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/1faf5d81-e8b0-4671-bf2f-4e96db92402e">
<img width="1425" alt="Screenshot 2024-04-13 at 5 44 44 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/b7631922-46e0-4a9c-9194-c1b729d82adb">

2024-04-15 20:16 UTC, p-suram requested changes
Changes look good working as expected. Filter is only visible for Admin, Owner users but not for Volunteer user. I have 2 minor suggestions:
1. Lines 224-225 of Leaderboard.jsx can be extracted into separate util function as this logic is being repeated quite a number of times.
2. I see team name as `Pooja_test_team...` even though team name is `Pooja_test_team`. Please find video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/157307140/14614f4f-5609-434b-84d8-dee46ffec51a

2024-04-17 12:39 UTC, peterson337 commented
> Hi Peterson,
> 
> I've tested the changes, and the main functionalities all work well. The team filter is only visible to admin accounts and not volunteer accounts, which works as expected.
> 
> The only issue I encountered is that when clicking on the "Tracking" button for a team member in "Team Member Tasks" on the left side (regardless of whether the member belongs to the admin's team or not), the "Leaderboard" on the right side automatically changes to show all members' info, even though we are still in "My team" mode. I'm not sure if this action is expected. Thank you!
> 
Hello [@metaphor987](https://github.com/[metaphor987](https://github.com/metaphor987)), I fixed the bug in your comment. Please, refer to my GIF for further reference:  

![17](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/e0728425-43dd-4ef0-be91-09f2875089eb)

2024-04-20 04:52 UTC, metaphor987 submitted a review, later dismissed
Hi Peterson,

Thank you for the updates! The GIF you have attached is really clear. I've tested the changes on my side and everything looks great. Here's a screen recording showing that the previous bug has been fixed.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/28d4868a-249b-480b-8c57-6bae10035099


Thank you!

2024-04-22 16:40 UTC, p-suram approved these changes, later dismissed
Hey Peterson, Thank you addressing the comments. Code changes look good and working as expected. Please find attached video that shoes that previous issue has been resolved.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/157307140/f0b3273e-d437-4252-90d8-b0c05583c844

Great Work!

2024-04-30 02:33 UTC, Abi-Liu submitted a review, later dismissed
Hey Peterson! The changes work as expected. I'm able to toggle between teams only on an admin/owner account.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59585815/9b88958b-64b4-4e61-8738-bf1ba6dc8051

2024-05-01 21:55 UTC, meetpadhiar4 approved these changes, later dismissed
Hi, i tested your PR and it is working as intended.

2024-05-04 18:53 UTC, abdel-lall reviewed
Hello, @peterson337. I wanted to bring to your attention that the filter on the task board is still not displaying the tasks and their progress, which is crucial for the task board's functionality. Additionally, it seems that the style of the time-off button is still not quite right. Everything else looks good.
![Screenshot 2024-05-04 135046](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/1d847d6f-337e-49b5-aabe-fb490186a31e)
![Screenshot 2024-05-04 135056](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/46357527-2daa-42fd-9ab1-1d07d4159508)

2024-05-04 20:17 UTC, peterson337 commented
> Hello, @peterson337. I wanted to bring to your attention that the filter on the task board is still not displaying the tasks and their progress, which is crucial for the task board's functionality. Additionally, it seems that the style of the time-off button is still not quite right. Everything else looks good. ![Screenshot 2024-05-04 135046](https://private-user-images.githubusercontent.com/49083865/327968932-1d847d6f-337e-49b5-aabe-fb490186a31e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTQwODIsIm5iZiI6MTcxNDg1Mzc4MiwicGF0aCI6Ii80OTA4Mzg2NS8zMjc5Njg5MzItMWQ4NDdkNmYtMzM3ZS00OWI1LWFhYmUtZmI0OTAxODZhMzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIwMTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1OGU1NjAwNDkxNDliOGQ4NjgwNDk0ZDNjZmFlMmY2YzJjMThiNjdlYjk1MmYyYzNkZTA0Y2UyMjE4M2VhMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hLExHIB4ruPmiC5AGOTcRuiac7Ty0X67Bez0fn7qowA) ![Screenshot 2024-05-04 135056](https://private-user-images.githubusercontent.com/49083865/327968933-46357527-2daa-42fd-9ab1-1d07d4159508.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTQwODIsIm5iZiI6MTcxNDg1Mzc4MiwicGF0aCI6Ii80OTA4Mzg2NS8zMjc5Njg5MzMtNDYzNTc1MjctMmRhYS00MmZkLTlhYjEtMWQwN2Q0MTU5NTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIwMTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2OGYzYzY1ZTRmZTc3NjI0ZjAxZDQyYmMwYzkyNmZlZGY0YWJiYWFlMGZiZGUwMjQ1YWVmNzJmOTNkMDc0ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J_k3f2AsktqWFLWO43ho_Q2YKsGrN8QN3TaTCm4eTVw)

Hello [abdel-lall](https://github.com/abdel-lall), I noticed that you're testing the old version of my pull request. The filter that displays the user's tasks.  
![x](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/9644aaa5-9dd2-4519-92eb-39f1f3d92a89)
If you test my pull request again, please use 'git pull' in your terminal.

2024-05-06 19:24 UTC, cgomezhub requested changes
Good job! It seems like you're doing very well, almost everything is alright, However, check the time recording feature, it is not showing correctly on the dashboard.

![Screenshot 2024-05-06 144346](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/45723b83-d5ab-47c6-9f38-a3cf75f56f70)
![Screenshot 2024-05-06 144837](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/d730a5de-8f1f-46c9-ac54-7109d5fbc3aa)
![Screenshot 2024-05-06 151506](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/8fdbef4b-d6bd-4d8b-ae8c-71a8671a455b)
![Screenshot 2024-05-06 151811](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/1d4b27e1-0657-4495-9979-764f1d9c72f3)

2024-05-07 16:30 UTC, SRamen1999 submitted a review, later dismissed

2024-05-10 15:22 UTC, ImzIssa submitted a review, later dismissed
Hello, I've tested your PR and the filter works as expected. Great Work.

Filter Invisible when logged in as Volunteer
![PR2078](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/87269725/0384c39b-d09f-4c53-ab52-94375c577f85)

Filter works on Tasks and Leaderboard when logged in as Admin
![PR2078 (2)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/87269725/d279265e-d47b-4db3-9db5-cb853187c105)

2024-05-11 17:29 UTC, abdel-lall submitted a review, later dismissed
LGTM. Good job!
![Screenshot 2024-05-11 122827](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/540350ad-9016-4b26-8d13-55a95b6ea727)

2024-05-11 18:51 UTC, one-community commented
> Good job! It seems like you're doing very well, almost everything is alright, However, check the time recording feature, it is not showing correctly on the dashboard.
> 
> ![Screenshot 2024-05-06 144346](https://private-user-images.githubusercontent.com/55204862/328293715-45723b83-d5ab-47c6-9f38-a3cf75f56f70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTM3MjksIm5iZiI6MTcxNTQ1MzQyOSwicGF0aCI6Ii81NTIwNDg2Mi8zMjgyOTM3MTUtNDU3MjNiODMtZDVhYi00N2M2LTlmMzgtYTNjZjc1ZjU2ZjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE4NTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZDc3NDc4ZmM4M2I2NjU4NzY3ZWY1ZGNiMjZlYTc1NjZjMTJlMDcwMTM5MTBjMzliNjVlZTVlZTBjMWI3ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7aQUnxmrNTdkq4jJ1RDQKbYcqOjWYB_QhsJxs3hkano) ![Screenshot 2024-05-06 144837](https://private-user-images.githubusercontent.com/55204862/328293719-d730a5de-8f1f-46c9-ac54-7109d5fbc3aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTM3MjksIm5iZiI6MTcxNTQ1MzQyOSwicGF0aCI6Ii81NTIwNDg2Mi8zMjgyOTM3MTktZDczMGE1ZGUtOGYxZi00NmM5LWFjNTQtNzEwOWQ1ZmJjM2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE4NTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZDE0NWIwMDQ4ODZlNjM3ZWFhZTUwOGE4YzI2OTY0OWY1NTI5NzE0ZjcwNmRjZDc3MjZhM2JiNmJkYTNmYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._it3yfL4jqk6bd7diJ0PEzjM0VHFovLG0Kp_EqZcRLc) ![Screenshot 2024-05-06 151506](https://private-user-images.githubusercontent.com/55204862/328293720-8fdbef4b-d6bd-4d8b-ae8c-71a8671a455b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTM3MjksIm5iZiI6MTcxNTQ1MzQyOSwicGF0aCI6Ii81NTIwNDg2Mi8zMjgyOTM3MjAtOGZkYmVmNGItZDZiZC00ZDhiLWFlOGMtNzFhODY3MWE0NTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE4NTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MWUyMzIxYWMzOGYzMmNjZDE5Y2U0NjRlM2NiNmY2NDdlNzZmZGQxYzU1Y2JiZDQ1NWQ0YmNhM2JiZTQ0OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yqOUKpmlRyRU_uX2ig1Qukft4fZrJU4LICFbAJlUkSU) ![Screenshot 2024-05-06 151811](https://private-user-images.githubusercontent.com/55204862/328293721-1d4b27e1-0657-4495-9979-764f1d9c72f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTM3MjksIm5iZiI6MTcxNTQ1MzQyOSwicGF0aCI6Ii81NTIwNDg2Mi8zMjgyOTM3MjEtMWQ0YjI3ZTEtMDY1Ny00NDk1LTk5NzktNzY0ZjFkOWM3MmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE4NTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMWM2Y2I0YTRhYjU0ODU3YjZiOGY4MWMyYjhjMzYwNTBhZTdmMzA0YzA1MjkyZmYxN2I1MWVjMjY3OTcxNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-2uRMM7CGu-TxkcZcDRsdaCtnAVkv67cSea_gywvn3A)

This looks correct to me, what are you seeing that is wrong?

2024-05-13 15:47 UTC, cgomezhub submitted a review, later dismissed
I had some issues with charging but the functionality works as expected

https://www.loom.com/share/49dd2825adcb4241a273610d33996bd5

2024-05-16 13:45 UTC, nathcarnevalli submitted a review, later dismissed
The functionality worked as expected for different type of accounts.

![Screenshot 2024-05-16 104136](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/61f77203-c236-44fe-8abb-d0e68fcccc25)

2024-05-18 16:07 UTC, nishithaShetty commented
Hey Peterson, nice work. The functionality works as expected.
It's not related to the functionality but the inactive button in the delete team section, does not work as expected.

<img width="424" alt="PR#2078" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/99f60349-f60b-4816-980d-2f9e11a2b95b">
<img width="518" alt="PR#2078_1" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/d7435a98-12ad-4d56-baaf-8bd1be77d549">

2024-05-26 05:44 UTC, Sandhya1236 approved these changes, later dismissed
I checked out the current branch, ran npm install and the necessary commands to run the PR locally. I verified that the filter is exclusively visible to administrators and owners by logging in as an administrator and owner, confirming the filter's visibility. I also logged in as a regular user to ensure the filter was not visible. To test with two or more teams, I created new teams by navigating to 'Other Links' → 'Teams', then clicked 'Create New Team', entered the team name, and added members including myself. All steps were followed successfully, confirming the filter visibility works as intended based on user roles.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/04243220-faef-405f-aa45-be1fa95177a6)

2024-05-30 22:03 UTC, one-community commented
Thank you all, moving to final review.

2024-05-31 17:31 UTC, ZhangPeizhou commented
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/4370426b-e407-4c6f-97ee-41a76fac649e

Work as expected, well done!

2024-07-12 20:52 UTC, vishavk1992 approved these changes
I have tested this PR by following the instructions and it works as intended . 
After adding the team and its members, I was able to select the team and switch between "My Team" and "View All".
Worked for 1 day, 2 days, 3 days, and so forth.


https://github.com/user-attachments/assets/0e405c5c-e47a-4f6e-8037-8ca84d6787b0

2024-07-17 05:26 UTC, one-community commented
Thank you all, merging!

2024-07-17 05:26 UTC, merged