Malav delete time entry own
OneCommunityGlobal/HighestGoodNetworkApp pull request #2087
Opened 2024-03-24 01:45 UTC by MALAV1308

# Description
This PR enables the user with the Delete Time Entry (Own) permission to be able to delete it's own any time entry  via their dashboard.

## Related PRS (if any):
This frontend PR is related to the dev backend PR.

## Main changes explained:
- Added conditional logic so that the user with the permission can delete the any time entry of it's own.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Other Links -> Permissions Management -> Manage User Permissions -> Choose a USER without Delete Time Entry (Own) permission under Timelog Management -> click on Add -> Scroll down then submit
6. verify that the user who was given the permission is now able to see  delete button in any of time entry log on  dashboard and able delete it.

## Screenshots or videos of changes:
![1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61341363/b3efe5cd-adf4-42f0-ba5b-16d4baaa686e)
![2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61341363/db6fd5ac-c4a6-4b88-8559-dd95d4e9eacc)
![3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61341363/cde10146-84c9-4be6-b750-7806c3fb2826)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61341363/6eb67fc0-9e6f-4d8c-886b-b6ce6d526e64

## Note:

2024-03-25 16:08 UTC, linkhanthtel approved these changes
Looks good! I can see delete button in time entry log on dashboard and I can delete it.

<img width="1434" alt="#2087" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/aa09dc16-9476-4eee-abe1-5aa9df2bfd03">

2024-03-25 18:18 UTC, meetpadhiar4 approved these changes
Hi, I reviewed your PR and it works as intended. I was able to delete my own time entries when the permission was granted. Please refer the reference video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/e2c4bf1d-cc34-47df-8b55-efdfcadf01e7

2024-03-26 10:04 UTC, m-khalaf commented
Looks good to me as well. Was able to change the permission of the volunteer role to allow them to delete their time entries.
<img width="1005" alt="PR-2097 -1" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107087873/5f9d7ff7-1566-4a79-b753-1619ca6db1d7">
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107087873/a41e320e-5a4b-4c57-972a-6a154bc91f65)

2024-03-26 10:14 UTC, m-khalaf approved these changes
Looks good to me as well. Was able to change the permission of the volunteer role to allow them to delete their time entries.
<img width="1005" alt="PR-2097 -1" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107087873/cde53a52-9c2e-4a2f-afe9-eb9b64247015">
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107087873/23be2f7d-3778-441b-9921-2d046ac38b43)

2024-03-27 14:03 UTC, SanketKaware approved these changes
I have tested the functionality and it works as expected. During my testing, I used both "Administrator" and "Owner" role accounts and didn't encounter any issues.

My only suggestion is in How to test steps. In step 5, please update to log in with an "Owner" account to make the changes.

For reference, please take a look at my video review.
**Before**


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/54329584-f7cf-4016-823a-618a6d69a65d

**After**


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/bd74c07a-3442-4347-81b7-8d0db02b6f05

2024-03-29 23:29 UTC, iven-yao requested changes
Hi, I just tested this pull request and faced some issue,
I checked my Test Role without Delete Time Entry(Own) permission, but this role could still delete any entry on its own dashboard. Please let me know if I misunderstood this test case.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/5d7b6d84-267c-4cb0-8697-16c5adca6b89)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/0802834a-b15e-475e-b67a-7799f1dabfe7)

2024-03-30 09:25 UTC, hbodgal requested changes
I can see Delete button and it event deletes the Time Entry. But, even if I revoke the permission from user still it allows user to Delete its own Time Entry.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/eff01fa7-7bf8-42d2-a51b-78d53beccb7e)

2024-03-30 23:21 UTC, MALAV1308 commented
> I can see Delete button and it event deletes the Time Entry. But, even if I revoke the permission from user still it allows user to Delete its own Time Entry.
> 
> ![image](https://private-user-images.githubusercontent.com/145157488/318183500-eff01fa7-7bf8-42d2-a51b-78d53beccb7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NDA5MTMsIm5iZiI6MTcxMTg0MDYxMywicGF0aCI6Ii8xNDUxNTc0ODgvMzE4MTgzNTAwLWVmZjAxZmE3LTdiZjgtNDJkMi1hNTFiLTc4ZDUzYmVjY2I3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQyMzE2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDVhOGRjZjhkYmM4MGVjZmVhMTc4N2FhMTViMDliODI4ZmViODJlMzc1OTA4N2E2NGRkOGFmMTc3MTQ0YzY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ylel06yQJBXv6BolyfmD9NeecAJISq2prcOutYm9gSA)

This is because of a bug in delete_time_Entry_Others features which allows users to delete any time entry and I think your user had a perrmision to delete_time_entry_Others. I would like to request you to disable the permission of Delete_Time_Entry_Others and then try this feature. Thank You.

2024-03-30 23:21 UTC, MALAV1308 commented
> Hi, I just tested this pull request and faced some issue, I checked my Test Role without Delete Time Entry(Own) permission, but this role could still delete any entry on its own dashboard. Please let me know if I misunderstood this test case. ![image](https://private-user-images.githubusercontent.com/25358966/318150910-5d7b6d84-267c-4cb0-8697-16c5adca6b89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NDA5MTMsIm5iZiI6MTcxMTg0MDYxMywicGF0aCI6Ii8yNTM1ODk2Ni8zMTgxNTA5MTAtNWQ3YjZkODQtMjY3Yy00Y2IwLTg2OTctMTZjNWFkY2E2Yjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDIzMTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOGYzNDg5MzQzZWFhMjlhZTI4Mjc2NGU4YzBjNmFkYmFlMWI4Y2I2ODNjYTQwMTM4MzRkZWQyZjdjNTlmYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DaLmbhZl7gBCRWnRpAlDstPyZDffwGhUwycWbmTMa9c) ![image](https://private-user-images.githubusercontent.com/25358966/318150920-0802834a-b15e-475e-b67a-7799f1dabfe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NDA5MTMsIm5iZiI6MTcxMTg0MDYxMywicGF0aCI6Ii8yNTM1ODk2Ni8zMTgxNTA5MjAtMDgwMjgzNGEtYjE1ZS00NzVlLWI2N2EtNzc5OWYxZGFiZmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDIzMTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMWFjMjZmNzZjNGE0OTg4YTliZjMwYTNmNzczYjNiZjI0OTZmZmM1MTY0Y2YyOWQ3MWYyOGM1ZTJlMDIxMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-VTOpghsk43ljnfH5QQBfaL5PpApMBqe1II2nftWcAU)

This is because of a bug in delete_time_Entry_Others features which allows users to delete any time entry and I think your user had a perrmision to delete_time_entry_Others. I would like to request you to disable the permission of Delete_Time_Entry_Others and then try this feature. Thank You.

2024-04-06 09:39 UTC, aaryaneil requested changes
I am getting a bug for this change, even when the edit timelog change permissions are disabled the user is able to delete the timelog.
<img width="1440" alt="Screenshot 2024-04-06 at 4 36 55 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/7cc8b652-1e91-46e7-a96a-ced178b120cf">
<img width="1440" alt="Screenshot 2024-04-06 at 4 37 28 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/0296988e-c803-42b8-b2eb-24caee947b65">

2024-06-02 03:07 UTC, Sandhya1236 approved these changes
I have successfully tested the new functionality that allows users with the "Delete Time Entry (Own)" permission to delete their own time entries via their dashboard. The main changes included adding conditional logic to enable this functionality. After checking into the current branch, running npm install, and starting the application locally, I cleared the site data and cache. Logging in as an admin user, I navigated to Other Links -> Permissions Management -> Manage User Permissions, selected a user without the "Delete Time Entry (Own)" permission under Timelog Management, clicked on Add, scrolled down, and submitted the changes. I ensured the user did not have the "DELETE_TIME_ENTRY_OTHERS" permission. I verified that the user with the new permission could see the delete button in their time entry logs on the dashboard and successfully delete their entries. All tests confirmed that the functionality worked as intended.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/36359c19-5f67-4a8c-b16b-034d4c01ea94)

2024-08-02 04:09 UTC, Pranay-ai approved these changes
Hey @MALAV1308 
The PR is working as expected here is the screenshot  for reference
![image](https://github.com/user-attachments/assets/76f78c6a-d447-48f8-aea7-295ad08243de)

2025-01-10 20:56 UTC, closed without merging