Yixiao header unittest
OneCommunityGlobal/HighestGoodNetworkApp pull request #2098
Opened 2024-03-29 20:36 UTC by JYXiao-2021

# Description
Create the unit test for the Header component to confirm whether it working as intended.

## Main changes explained:
- Create file Header.test.js to do the unit test.

## How to test:
1.check into current branch
2.do npm install to run this PR locally
3.run npm test src/components/Header/`__tests__`/Header.test.js

## Screenshots or videos of changes:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49748716/5f45386c-4274-4885-a250-4787e032a818)

2024-03-29 21:21 UTC, mianmiantea2019 requested changes
Hi Yixiao. All the tests have passed! There was just one minor issue: I noticed the mockStore declaration was duplicated, but overall, great work! 

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/83850a1d-4a39-4b54-8e4c-7c77bfbfcece)

2024-03-29 21:21 UTC, mianmiantea2019 commented on src/components/Header/__tests__/Header.test.js
> +  const mockStore = configureMockStore([]);
'mockStore' is already declared in the upper scope on line 10

2024-03-29 23:51 UTC, aaryaneil requested changes
mockStore declared twice otherwise looks good to me.
<img width="1098" alt="Screenshot 2024-03-29 at 6 50 19 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/5b7811aa-5731-496c-894c-16148f152882">

2024-03-30 06:38 UTC, linkhanthtel submitted a review, later dismissed
I reviewed your PR and all tests passed! 

<img width="932" alt="#2098" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/2802711d-b6a9-48e0-903c-de68067e1f96">

2024-03-30 06:40 UTC, linkhanthtel reviewed
One thing, 'mockStore' is declared twice in line 10 and 14

<img width="573" alt="Screenshot 2024-03-30 at 2 34 03 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/3828478d-91a2-4d7d-93e8-7966f1cc691a">

2024-03-31 04:35 UTC, JYXiao-2021 commented
@aaryaneil @mianmiantea2019 I did remove the duplicate code, please review again. Thank you.

2024-03-31 05:06 UTC, ramyaram2092 requested changes
Hello @JYXiao-2021 Good job on the existing test cases.  However I believe more test cases and validations can be added

2024-04-07 04:02 UTC, vikrambadhan submitted a review, later dismissed
Hi, I tested your PR and all the test cases passed!

![Week 31 - PR4](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/1eec9e17-1c35-4978-b50e-7dcd7446ab6f)

2024-04-10 01:20 UTC, bhuvaneswarignanasekar submitted a review, later dismissed
I have reviewed your PR. Works as intented. 
All test cases passed. 
<img width="1027" alt="Screenshot 2024-04-09 at 8 17 53 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59138503/1c5d30ad-18f1-4a50-9b83-61e84833ae41">

2024-04-24 20:20 UTC, mianmiantea2019 commented on src/components/Header/__tests__/Header.test.js
> +  const mockStore = configureMockStore([]);
Good work and all tests passed!

2024-04-24 20:20 UTC, mianmiantea2019 submitted a review, later dismissed
Good work and all tests passed!

2024-04-25 04:25 UTC, jennZhang93 submitted a review, later dismissed
All unit test passed. good work!
<img width="621" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/2c9cefb1-c199-4aff-bc9f-dc8043930635">

2024-04-27 00:08 UTC, yvonnep165 submitted a review, later dismissed
Hi @JYXiao-2021 , I checked all test cases and ran the tests. All tests passed. Nice work! Please refer to the screenshot below:
<img width="696" alt="Screenshot 2024-04-26 at 5 07 05 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/0c20febb-4c01-4c3a-b542-9635101293aa">

2024-04-28 01:45 UTC, Tiantian-C approved these changes, later dismissed
All tests have been passed!
<img width="529" alt="Screenshot 2024-04-27 at 6 45 31 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/f92be617-ef0c-45b8-aa72-c955059e9e76">

2024-05-03 18:29 UTC, one-community commented
Thank you all, merging!

2024-05-03 18:29 UTC, merged