Ramya unit test : Reports/PeopleTableDetails
OneCommunityGlobal/HighestGoodNetworkApp pull request #2102
Opened 2024-03-31 04:51 UTC by ramyaram2092

# Description
Unit test for src/components/Reports/PeopleTableDetails

## Main changes explained:
-  New file
      - **PeopleTableDetails.test.js** : unit test cases 

####  Test cases 
To be filled

## How to test:
1. check into current branch
2. do npm test PeopleTableDetails.test.js
3. check if all the test cases pass

## Screenshots or videos of changes:

To be filled

## Note : 
Kindly take a look at the test cases and  suggest if more validations can be added

2024-04-20 12:25 UTC, aaryaneil requested changes
Reviewed your PR and all the test cases passed but there were a lot of warnings generated, please look into it. Good work.
<img width="1335" alt="Screenshot 2024-04-20 at 7 24 09 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/03a4d05f-c282-473d-9c29-2eb2777d0b25">
<img width="1291" alt="Screenshot 2024-04-20 at 7 24 22 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/44074364-68c3-497c-8baa-8e3c04860fb1">

2024-04-20 17:01 UTC, ramyaram2092 commented
> Reviewed your PR and all the test cases passed but there were a lot of warnings generated, please look into it. Good work. <img alt="Screenshot 2024-04-20 at 7 24 09 AM" width="1335" src="https://private-user-images.githubusercontent.com/39597927/324177109-03a4d05f-c282-473d-9c29-2eb2777d0b25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTYzOTgsIm5iZiI6MTcxMzYxNjA5OCwicGF0aCI6Ii8zOTU5NzkyNy8zMjQxNzcxMDktMDNhNGQwNWYtYzI4Mi00NzNkLTljMjktMmViMjc3N2QwYjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDEyMjgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MGFjYTY1ZDczMTNhOTdiMTJlOGY4ZDI3ZWRjYzRmMDFmZGRhZTYxMDU2YzJjZGM0NjRjOWYyYmYzNDllNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-OY3VzrkWjkEnfmpM-Ssua-O6PudxNZ4VKEeoVxAeQY"> <img alt="Screenshot 2024-04-20 at 7 24 22 AM" width="1291" src="https://private-user-images.githubusercontent.com/39597927/324177112-44074364-68c3-497c-8baa-8e3c04860fb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTYzOTgsIm5iZiI6MTcxMzYxNjA5OCwicGF0aCI6Ii8zOTU5NzkyNy8zMjQxNzcxMTItNDQwNzQzNjQtNjhjMy00OTdjLThiYWEtOGUzYzA0ODYwZmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDEyMjgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZTAzZjczODlhOGZiNmVhM2IzZDg3OTA4YTkxMzI3NGIwYjQ2NjdjOTY4ZDdlNDhkY2UwNzk1MzFjNTZjYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VTrQrtWCao0oyfnKGW-vhdK5Jh9eIIGTmCO8xjw2Ivk">

The warning stems from the component's code design  so that is not something I can address in the unit test

2024-04-20 23:06 UTC, Tiantian-C reviewed
All the tests have passed.
<img width="809" alt="Screenshot 2024-04-20 at 4 05 37 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/f91474c0-22ad-457e-80db-9ff77a9bf6c6">

2024-04-21 02:25 UTC, metaphor987 requested changes
Hi Ramya, all tests have passed on my side but there are some warnings, and it would be best to check them. Here is the screenshot showing that all tests have passed:
<img width="894" alt="Screenshot 2024-04-20 at 10 21 09 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/84cb4f6e-989d-4523-b1bc-3e8c8a7cb5bd">

and here are screenshots showing some of the warnings:
<img width="965" alt="Screenshot 2024-04-20 at 10 19 44 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/3d49181d-d4bb-44c4-9cba-4edc7b0f91aa">
<img width="1193" alt="Screenshot 2024-04-20 at 10 20 44 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/25b932b5-de84-479b-aadb-662ca8dad5cd">

Thank you!

2024-04-21 03:21 UTC, jennZhang93 reviewed
Testcases passed but here are some console log error that showed up.

<img width="1680" alt="Screenshot 2024-04-20 at 11 18 38 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/a06bed05-6fbb-4683-aeea-66fe4d025668">
<img width="1680" alt="Screenshot 2024-04-20 at 11 18 47 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/1a894881-9f2e-45ae-9f21-3ad03bd9cc89">
<img width="1173" alt="Screenshot 2024-04-20 at 11 19 00 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/87dfa2b8-5734-4268-b95d-c8cdbaa18071">
<img width="1144" alt="Screenshot 2024-04-20 at 11 19 08 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/ec08af08-4785-44b2-aa8a-801a05848beb">
<img width="1178" alt="Screenshot 2024-04-20 at 11 19 15 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/4bbf120e-c408-4a53-a109-56c4c61ba898">
<img width="1039" alt="Screenshot 2024-04-20 at 11 19 22 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/84459d15-5ee3-48d8-a606-e688edff19f7">

2024-04-21 06:31 UTC, ramyaram2092 commented
@metaphor987 @aaryaneil  I have fixed the console warnings. Now you shouldn't see any warnings except for  warning due to the main component logic

2024-05-06 18:04 UTC, cgomezhub requested changes
All test has passed but to avoid warning in file  221  you need to add l key={value._id}  :   <NewModal key={value._id} header="Task info" trigger={() => renderFilteredTask(value)}>

do it and please let me know.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/316460ff-7c2e-4690-941c-e0942f2f1426)

2024-05-11 16:57 UTC, KaushikMreddy requested changes
Hi Ramya, 

All test cases have passed with 1 warning, pasting that warning here
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/ed647fe5-762e-4970-99ee-3c575dd811a0)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/ce86d641-1727-46a9-a297-f211f2861fc3)

Good work!

2024-05-13 17:48 UTC, dkn6 reviewed
As others have already mentioned in their comments, there is a warning to add a unique ID. Thank you for your great work!

<img width="991" alt="2102" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/168319518/fd2ada13-eee4-47ec-928a-ea0d67ca7823">

2024-05-13 17:49 UTC, dkn6 requested changes
As others have already mentioned in their comments, there is a warning to add a unique ID. Thank you for your great work!

<img width="991" alt="2102" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/168319518/fa19afbb-6571-4184-98c4-bc9599b83de3">

2024-05-14 02:06 UTC, ZhangPeizhou commented
![RR#2102 Review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/e76699df-9a04-4d16-b82e-bea469b36c1f)
Pass all tests, nice work!

2024-05-19 05:14 UTC, ramyaram2092 commented
@ZhangPeizhou @cgomezhub @dkn6 my understanding is the warning stems from the main component logic. I am not really sure if i can make that changes as part of this PR . I beleive it should be addressed in a separate PR altogether  as the component needs to functionally tested after making any changes. Let me know your thoughts

2024-05-19 11:36 UTC, dkn6 approved these changes

2024-05-19 11:36 UTC, dkn6 commented on src/components/Reports/PeopleTableDetails.jsx
>          {filteredTasks.map(value => (
@ramyaram2092 
From my understanding, simply assigning a unique key to the list of items here should be enough, and I don't think this change will have any negative impact. Whether to handle this in a separate PR is up to you, so I approve this PR. Thank you for your great work!

2024-05-26 05:32 UTC, Sandhya1236 approved these changes
I checked out the current branch, ran npm test PeopleTableDetails.test.js, and verified that all the test cases passed. All steps were followed successfully, confirming that the functionality covered by the PeopleTableDetails.test.js file is working as intended.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/0436a505-d84d-4f6d-88fc-4c5f6f95c085)

2024-05-29 23:06 UTC, Kavil-Jain-514 requested changes
All test cases have passed, however there is warning for a unique key. each element in an array rendered by map needs to have a unique key prop. 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/1ec38063-ccf6-450c-b901-6fc2611b7257)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/fbeefd7c-96be-43c4-b6da-9ee2fdf5ca7d)



You can replace the line number 221 to 229 in the PeopleTableDetails.jsx with this code:
{filteredTasks.map(value => (
          <NewModal key={value._id} header="Task info" trigger={() => renderFilteredTask(value)}>
            <div>Why This Task is important</div>
            <textarea className="rectangle" type="text" value={value.whyInfo} readOnly />
            <div>Design Intent</div>
            <textarea className="rectangle" type="text" value={value.intentInfo} readOnly />
            <div>End State</div>
            <textarea className="rectangle" type="text" value={value.endstateInfo} readOnly />
          </NewModal>
        ))}
        
        
Also you can make your code better by removing extra stuffs like.
Line no. 61, remove const simple = [ ] as it is never used.
Line no. 64 to 72, instead of a if and return true, just use return.

2024-06-05 18:57 UTC, JatinAgrawal94 requested changes
All the tests pass, but with a warning.
The NewModal Component doesn't have a key prop on line 221 in PeopleTableDetails.jsx. Rest everything works fine.
Good Job.
![2102](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/45ac1a68-6eaf-418a-87f3-41c4c0aa3a4b)

2024-06-07 00:43 UTC, akshit0211 commented
All test cases passed but with warning. I saw your previous comment so I'm approving this.

<img width="799" alt="test cases passed" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/b2db04a1-cd7a-4fbb-84ae-e0179951d346">

2024-06-07 00:45 UTC, akshit0211 approved these changes

2024-06-10 06:02 UTC, ramyaram2092 commented
> the warning stems from the main component logic. I am not really sure if i can make that changes as part of this PR . I beleive it should be addressed in a separate PR a

the warning stems from the main component logic . I beleive it is better to make the changes as a seperate PR. Let me know your thoughts @JatinAgrawal94 @Kavil-Jain-514

2024-06-10 20:23 UTC, JatinAgrawal94 approved these changes

2024-06-16 05:23 UTC, deepthikannan approved these changes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83337914/8cefbcc8-7d79-4b3b-ac9f-5b48c4d01b92)
All test cases passed.

2024-07-11 01:09 UTC, Vigneshwar-Muriki approved these changes
Tested this PR as mentioned in the instructions and its working as intended. All test cases have passed.
![Frontend PR #2102](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/4bcb1f70-3d05-46ae-9a0f-2a817e9f9288)

2024-07-13 16:57 UTC, AnujVakil approved these changes
I have tested this PR and all test cases are passed
![Uploading PR #2102_1.png…]()

2024-07-14 03:24 UTC, ZhangPeizhou commented
all tests are passed, well done!
![PR#2102](https://github.com/user-attachments/assets/4c252b71-ba2a-4121-becb-3256e9e11c37)

2024-07-14 16:18 UTC, Shadhrush5 approved these changes
Hi, I have reviewed PR 2102. I followed the steps as mentioned and see that all the test cases execute and is working as expected. Thank you for the great work.

<img width="638" alt="Screenshot 2024-07-14 at 8 08 29 AM" src="https://github.com/user-attachments/assets/f0a3e72a-2b93-4742-b4e1-58ca3152c37f">

2024-07-25 23:24 UTC, vamshik2024 approved these changes
Reviewed the PR, test cases passed but could see couple of warnings related to keys while rendering PeopleTableDetails

![image](https://github.com/user-attachments/assets/a6829a8f-2a2f-4151-86c7-56805f2bfd15)


Good work!

2024-07-28 01:09 UTC, souravwalke commented
I have reviewed PR 2102 and all the test cases executed without any fail.

<img width="664" alt="Screenshot 2024-07-27 at 6 07 31 PM" src="https://github.com/user-attachments/assets/baf6d44c-87d7-40a7-95a1-e74855125fa5">

2024-08-07 22:23 UTC, Gmon-k commented
I have tested from my side and all the test cases has passed. It looks fine.
<img width="1024" alt="2" src="https://github.com/user-attachments/assets/5f81b3d0-e0b6-4c4e-a4a8-ef26ab0bfa2e">

2024-10-19 06:03 UTC, navya9989 commented
Hi, I have tested this PR and all test suits have passed, Good worl!
@
![PR # 2102](https://github.com/user-attachments/assets/21aef6da-afd3-4fe8-952a-51ebf2095e23)

2024-10-20 23:10 UTC, navya9989 approved these changes

2024-10-24 21:57 UTC, SatyashanthiT commented
I reviewed and tested PR for the Reports/PeopleTableDetails unit tests. Verified that all test cases outlined in PeopleTableDetails.test.js passed, confirming the expected behavior for the component.
<img width="459" alt="image" src="https://github.com/user-attachments/assets/92fc196d-599d-415b-a26d-e77d05835048">

2024-10-26 01:09 UTC, geetamatkar commented
Tested this PR and all the test cases have passed.

<img width="918" alt="Screenshot 2024-10-25 at 8 09 32 PM" src="https://github.com/user-attachments/assets/77bea6e7-150e-40f4-a350-2a20a2dc6e63">

2026-04-21 04:26 UTC, closed without merging

2026-04-21 04:27 UTC, saisandeepkoritala commented
Created new PR to resolve errors. Please find the https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/5176