Jiarong rewrite weeklysummaries class component
OneCommunityGlobal/HighestGoodNetworkApp pull request #2115
Opened 2024-04-04 16:50 UTC by ljrirene

# Description
<img width="743" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/6a4d3b14-faf8-41e5-a8d0-6087b8107846">

## Related PRS:
This frontend PR is not related to a backend PR.

## Main changes explained:
- Change the whole class component to a functional component:
  - Change class state for hook state 
  - Update all lines of code that use this.setState()
  - Remove the props constructor and fix props to work with a function component
  - Remove class component functions like componentDidMount, componentDidUpdate, and change them to hooks 
  - Remove all calls to render() and relocate code inside of a return()
  - Update any and all other code related to class components

- Merged and Refactor the related test files from an unmerged branch, changhao_weeklysummariesreport_unit_test: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1907
- Fixed related warnings, log bugs, and memory leak bugs.

## How to test:
1. check into current branch
2. do `npm install` and `npm test WeeklySummariesReport.test.js` to run this PR locally
3. Verify all 10 unit tests are passed:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/d538e32b-b39d-4f52-a422-1987076a657b)
4. do `npm run start:local` to run this PR locally
5. Clear site data/cache
6. log as **Owner** or **Administrator** user
7. go to Main Page→ Reports→ Weekly Summaries Report
8. Make sure data is loaded and rendered.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/afd30b44-c74e-46de-b303-9141a1e67084)
9. Make sure you can change the Time, Select Team Code, Select Color, Change the filters, and Open PDF. (Nothing will happen when you click hide badges and load trophies)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/39064c66-e8cb-477c-8d63-adbf1cba9aa9)
10. Check into the **dev** branch to see if each part works the same as the dev.
## Videos:

## Note:
This is a refactoring task, so no functionality changes here. The refactoring code is based on the latest version of dev from commit https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/0ee3519e54a2e5ef65f399c55c44198161bcc209. The test is to make sure this component can work as the former version.

2024-04-06 12:13 UTC, ImzIssa requested changes
Hello, the test cases in WeeklySummariesReport.test.js are not passing.
![PR  2115](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/87269725/84500071-720c-4aa2-9a4c-e0126d586b9a)

2024-04-06 15:54 UTC, ljrirene commented
@ImzIssa Hi Imzlssa, this PR is just open to review. The last version is a draft. Please review this again, thanks!

2024-04-07 07:09 UTC, hbodgal submitted a review, later dismissed
I was able to pass all the test cases and even use different components. It takes little extra time to load the results but I think it will work well on Production.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/76d78369-5990-48ba-8099-f5482cd64c0c)

2024-04-08 23:22 UTC, bhuvaneswarignanasekar submitted a review, later dismissed
I have reviewed your PR. All test cases pased and functionality works as it should. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59138503/4a1f3b44-2184-4ca9-b17c-2fd420515860

<img width="974" alt="Screenshot 2024-04-08 at 6 22 32 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59138503/84e23e51-b4e3-43a6-bf20-80f81aeaa06d">

2024-04-13 20:45 UTC, aaryaneil submitted a review, later dismissed
The test cases were passed and the UI works as expected, however there is a delay.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/921124d7-987b-46b3-9db2-4304c9d9e421
![Screenshot 2024-04-13 at 1 03 45 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/e8789b76-a29a-4c0a-a33f-0397ba28d35e)

2024-05-16 15:56 UTC, nathcarnevalli requested changes
I have now tested the functionality as shown below. It worked as expected, but you can see in my video that the switch buttons under the Select Color field still appear when the drop-down menu appears.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/9c314d97-2af9-45bc-8650-61f3c312e411

2024-05-26 05:25 UTC, Sandhya1236 submitted a review, later dismissed
I checked out the current branch, ran npm install and npm test WeeklySummariesReport.test.js to run the PR locally, and verified that all 10 unit tests passed. I then ran npm run start:local, cleared site data/cache, and logged in as an Owner or Administrator user. Navigating to Main Page → Reports → Weekly Summaries Report, I ensured that the data was loaded and rendered correctly. All steps were followed successfully, confirming the proper functionality of the Weekly Summaries Report.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/3b6c61f2-14bf-4a3f-877f-8710bf11fd71)

2024-05-31 16:04 UTC, ZhangPeizhou commented
![PR#2115](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/eb0a5f74-a2de-4f53-b8e2-d4988d62e776)
Pass all tests

2024-06-02 01:13 UTC, peter6866 submitted a review, later dismissed
Changes work as expected.
- All tests passed successfully.
- Weekly summaries reports are displayed as expected.
<img width="563" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/5e942e37-c169-4ef6-b30a-f893b5eb2b12">
<img width="819" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/1575679f-9ea6-4ba2-85d5-6e8a23934f6d">

2024-06-05 18:40 UTC, JatinAgrawal94 submitted a review, later dismissed
All test cases pass and functionality works as expected.
![2115](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/0964ff96-7864-4f31-b2df-203ad2290f48)
![2115-1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/3902fa1d-53ed-4fd4-97ef-6a87dc147fea)

2024-06-06 03:26 UTC, Kavil-Jain-514 submitted a review, later dismissed
All functionalities work as the PR instructed.
The video shows the review of the PR

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/ae0610f6-46f8-4a3d-88fd-67fc741d340c

2024-06-12 01:14 UTC, akshit0211 commented
It is working as expected and all the test cases passed. Good work!

<img width="774" alt="All test cases passed" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/fd655c09-adb7-43e3-ba25-9b30d688d391">
<img width="774" alt="reports page" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/cfc76778-b828-4e88-8182-e85270775c0a">

2024-06-12 01:14 UTC, akshit0211 submitted a review, later dismissed

2024-06-13 15:36 UTC, TXMO-dev approved these changes
Jiarong rewrite weeklysummaries class component works as expected! Great Job.

2024-06-27 19:40 UTC, vishavk1992 submitted a review, later dismissed
Changes work as expected.
All tests passed successfully.
Weekly summaries reports are displayed as expected.

![PR-2115-1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/dc8535e6-95a3-4961-806e-2239019badfb)
![PR-2115](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/b3e8f441-43d3-4d64-b564-d5d7b9143d36)

2024-06-28 18:52 UTC, Sarath-3119 approved these changes
Tested this pr and compared the changes with the dev site, the pr runs as expected and is same in the dev site as well. 
Approving the changes,  Good work!


![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/156833266/969dd79d-7443-4d8c-90aa-cb6be5480cad)


![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/156833266/b9eac2c9-2ea2-4fcf-a393-09b32a59dfdc)

2024-07-01 17:05 UTC, ljrirene commented
> I have now tested the functionality as shown below. It worked as expected, but you can see in my video that the switch buttons under the Select Color field still appear when the drop-down menu appears.
> 
>  HGN.APP.Mozilla.Firefox.2024-05-16.11-59-55.mp4

Hi, nathcarnevalli, Thanks for pointing this out! I tested the bug you mentioned and turns out it is a bug from the development branch. I've already fixed it. Please review this again. Thanks!

2024-07-07 00:07 UTC, Vigneshwar-Muriki approved these changes
All test cases have passed and weekly summaries report functionality is working as expected but there is a light delay initially.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/c0a45441-78e2-48c1-b9ca-a51a34520799

![Screenshot 2024-07-06 195523](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/6a3a3918-b096-4983-a7ff-5a03170efb84)

2024-07-12 19:30 UTC, Shadhrush5 approved these changes
Hi, I have reviewed PR #2115 as mentioned in the below steps
Checkout the branch mentioned
Ran the test cases which passed as expected.

<img width="682" alt="Screenshot 2024-07-12 at 12 19 58 PM" src="https://github.com/user-attachments/assets/2868ec75-db5e-4a04-9292-31ea563b0a7e">

I logged in as an Admin and went to the weekly summary reports page.

Everything worked as expected and the data populated as well.

<img width="1728" alt="Screenshot 2024-07-12 at 12 24 13 PM" src="https://github.com/user-attachments/assets/75d26998-e17c-4528-b659-1e4aaa5f50d9">

But I do see a lag which I have recorded in the video below.

https://github.com/user-attachments/assets/fcebf1db-e65a-403f-9a84-e6208f55b59b

Thank you for the great work.

2024-07-13 06:04 UTC, AnujVakil approved these changes
I have tested this PR and functionality working as expected.

<img width="1440" alt="PR #2115_1" src="https://github.com/user-attachments/assets/21e1968b-a7d4-42cc-bebf-d370b8e856d5">

<img width="1434" alt="PR #2115_2" src="https://github.com/user-attachments/assets/ae453ee5-b579-4958-b475-2b433601207e">

2025-04-28 04:01 UTC, closed without merging