Swathy user teams table unit test
OneCommunityGlobal/HighestGoodNetworkApp pull request #2120
Opened 2024-04-06 01:48 UTC by swathyjayaseelan

# Description
Unit testing of User Teams Table component under User Profile.

## Main changes explained:
- Create a unit test file for User Teams Table Component under User Profile --> Teams and Projects --> ```__tests__```

## How to test:
1. check into current branch
2. run ```"npm test src/components/UserProfile/TeamsAndProjects/__tests__/UserTeamsTable.test.js"```

## Screenshots or videos of changes:
You should be able to see 6 successful tests
<img width="1285" alt="Screenshot 2024-04-05 at 6 48 07 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/d7a2e4f3-1b24-41c2-80c3-e95d9af35c6e">

## Note:
Include the information the reviewers need to know.

2024-04-06 08:59 UTC, linkhanthtel submitted a review, later dismissed
Looks good! All 6 tests are passed!

<img width="1184" alt="#2120" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/115c7cc7-a9b1-49a1-bc20-085920acfe3e">

2024-04-06 20:57 UTC, aaryaneil approved these changes, later dismissed
All the test cases were passed. Looks good to me.
<img width="1020" alt="Screenshot 2024-04-06 at 3 56 19 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/a824cae0-54c3-4d21-a8d8-d16b769727f3">

2024-04-07 03:54 UTC, vikrambadhan submitted a review, later dismissed
Hi, I tested your PR and all the test cases passed!

![Week 31 - PR2(#2120)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/f153da2b-7822-47f4-b992-846cc0ab9d24)

2024-04-07 06:44 UTC, hbodgal submitted a review, later dismissed
It passed all the tests.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/4b620ee7-cecc-427b-a2b5-fdd6bf9ad06c)

2024-04-08 21:20 UTC, bhuvaneswarignanasekar approved these changes, later dismissed
Hi Swathy, I have reviewed your PR. All test cases passed. 
<img width="1100" alt="Screenshot 2024-04-08 at 4 19 45 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59138503/9191698f-04e7-43e8-8e9b-f30f3271d380">

2024-04-19 19:24 UTC, gowthamdongari submitted a review, later dismissed
test cases working successfully
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/27274513/c34d65db-9475-44ae-b80d-ade096715ef8)

2024-04-27 02:54 UTC, yvonnep165 submitted a review, later dismissed
Hi @swathyjayaseelan I checked the test cases and ran the tests, but one test failed. Please refer to the screenshot below:
<img width="701" alt="Screenshot 2024-04-26 at 7 52 31 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/90650758-ca95-4690-9321-23a6246c0a5d">

2024-05-04 13:58 UTC, dkn6 requested changes, later dismissed
FYI: The same error as yvonnep165 occurred in my environment.

<img width="1060" alt="Swathy_UserTeamsTable_Unit_Test" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/168319518/2d36001b-0633-429f-bea4-1b5861728d66">

2024-05-17 05:10 UTC, KaushikMreddy commented
Hi, 
5/6 test cases have passed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/304ea480-104f-4974-8e0d-5612ada33f4f)
There seems to be an Id that's missing, please check

2024-05-28 05:50 UTC, swathyjayaseelan commented
The tests have been fixed. 

![Uploading Screenshot 2024-05-27 at 10.42.56 PM.png…]()

2024-06-14 16:18 UTC, shradac approved these changes
All tests passed. The tests cover all specified scenarios. Good Work!

<img width="1009" alt="4" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56028645/f15624bf-b09e-49de-aafb-5a4294f9f4ba">

2024-07-16 23:34 UTC, nikhilpittala16 approved these changes, later dismissed
I have tested the PR and all the test cases have passed.
![Screenshot (103)](https://github.com/user-attachments/assets/e93d49e5-3c1a-4510-a7cb-71212a128727)

2024-09-13 04:18 UTC, ishangoel17 reviewed
All test cases are passing. Below is the screenshot for reference:
![Capture2120](https://github.com/user-attachments/assets/ac2fecfd-0c65-4da6-8d00-b8bc04e92481)

2024-10-19 21:16 UTC, geetamatkar commented
Tested this PR and all test cases have passed.

<img width="1008" alt="Screenshot 2024-10-19 at 4 16 21 PM" src="https://github.com/user-attachments/assets/b81a9f9e-d55f-4750-b26c-449081a67db8">

2024-10-23 02:31 UTC, SatyashanthiT commented
All test cases passed successfully. Everything is functioning as expected.
<img width="806" alt="image" src="https://github.com/user-attachments/assets/51489649-b8fd-41a9-a819-1074715a20ba">

2025-01-09 02:59 UTC, vishavk1992 approved these changes, later dismissed
I have tested this PR and everything working as expected.

2025-01-18 01:38 UTC, vishavk1992 reviewed
Hi Swathy, I have reviewed your PR. All test cases passed.

2025-07-24 14:25 UTC, Rishitha1810 commented
I reviewed this PR all the test cases were working good 
<img width="1454" height="956" alt="Screenshot 2025-07-24 at 10 24 45 AM" src="https://github.com/user-attachments/assets/bf2cf68e-e8cf-4ac3-9b5a-0f79b6f2f279" />

2026-01-16 04:04 UTC, Anusha-Gali requested changes
Hi Anirudh,

I tried reviewing the PR but unable to do so since it is in node version: {"node":">=14.0.0 <15"} whereas the actual: requirement is:  {"npm":"8.19.4","node":"v22.21.1"}
<img width="1278" height="756" alt="Screenshot 2026-01-15 at 11 02 29 PM" src="https://github.com/user-attachments/assets/bf22c54f-f76f-4dd3-a7b3-de1ad599c2f7" />

2026-02-06 05:19 UTC, rohanrastogi311 requested changes
Hi Anirudh,


Launch Error due to incorrect node version. 14 instead of 20. 

<img width="1728" height="346" alt="Image" src="https://github.com/user-attachments/assets/07227ed8-6971-4ca5-b8a8-f9abc4b039e5" />

2026-04-05 04:24 UTC, one-community commented
Completed with this PR: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/4975

2026-04-05 04:24 UTC, closed without merging