Sucheta - Adds user's ability to check entered password to reveal the weeklySummaryRecipient for Authorized users only
OneCommunityGlobal/HighestGoodNetworkApp pull request #2124
Opened 2024-04-07 00:17 UTC by sucheta90

# Description
The feature implemented in this PR reveals the user password in the `weeklySummaryRecepients` table for the convenience of the user only if the user is an authorized user.

## Related PRS (if any):
This frontend PR is related to the [#861](https://github.com/OneCommunityGlobal/HGNRest/pull/861) backend PR.

…

## Main changes explained:
- Adds infoCircle icon to the Modal Header on `WeeklySummaryRececipentsPopup.jsx`
- `Onclick`  reveals and hides the user password , only in case of an authorized user.

…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Include the user password on `WeeklySummaryReport.jxs` 
<img width="795" alt="Screenshot 2024-04-07 at 5 41 10 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/f3fb0af1-e8ba-40ae-8eff-7c889f6a7b93">
5. log as OWNER user
6. go to Reports→ WeeklySummaryReports
7. Check if the `WeeklySummaryRecepients` button renders
8. Enter your user account password
9. Once authenticated, the user should now see an info icon , on click reveals or hides user password

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/59be5109-45ff-4628-8ee6-de5b8cb34fae

## Note:
Please note this feature can only be accessed by authorized users, hence please include the email that has OWNER rights both in the Frontend and Backend code .

2024-04-07 05:16 UTC, hbodgal approved these changes
It works well as required. I was able to see and hide password when I pressed "Reveal" button.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/139f649a-dca8-44cb-8164-292431c8b5db)

2024-04-07 06:29 UTC, Parth-tech reviewed
Hi Sucheta,
I tried to test the PR. 
I did the setup as required. I entered my owner account's email in frontend and backend. I logged in as owner and when I enter the same password it says `incorrect password! unauthorized user.`. It was the same password that I used to log in and which was successful.

Could you help me resolve this?

2024-04-09 02:41 UTC, Parth-tech requested changes
Hey Sucheta,
I have encountered 2 problems, please correct me if I did something wrong.

1. I have added my owner account's email address in both `WeeklySummariesReport.jsx` & in `userProfileController.js`. When I try to use the account password to see the `Report` an error: `Incorrect Password! Unauthorized User!`
2. After this error response the Modal freezes and I just cannot close the modal. But when I scroll the webpage in the background does scrolls.

Kindly let me know if there were any other steps other than adding email Id. 
Thank you for helping out!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/02e51bad-7a95-4c1e-ae55-0334fb7c1070

2024-04-09 04:37 UTC, merged

2024-04-09 04:50 UTC, sucheta90 commented
Hello @Parth-tech, thank you so much for taking to review this PR. I took a look at it, and changed my email, it did work for me. I would be happy to answer related to this PR if you have any.

2024-04-09 05:01 UTC, Parth-tech commented
> Hello @Parth-tech, thank you so much for taking to review this PR. I took a look at it, and changed my email, it did work for me. I would be happy to answer related to this PR if you have any.

Hey @sucheta90,
Thanks for helping. So here's what I am doing:

FileName: *WeeklySummariesReports.jsx*
`const authorizedUser2 = 'prjangid27_owner_1@gmail.com'; // To test please include your email here`

FileName: *userProfileController.js*
`const authorizedUserSara = `prjangid27_owner_1@gmail.com`; // To test this code please include your email here`

Once the local server is up and running, I login and use the same password but it shows `Incorrect Password!`. Am I making a mistake?