Hoang fix hours inputs in task modal
OneCommunityGlobal/HighestGoodNetworkApp pull request #2135
Opened 2024-04-10 03:18 UTC by kylepham

# Description
The validation text alignments problem was encountered in https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2075#pullrequestreview-1964909284. 

<img width="743" alt="Screenshot 2024-04-09 at 10 02 54 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/fc77e775-4542-468e-a108-30fd57b884e7">

## Related PRS (if any):
Latest backend's development branch.
…

## Main changes explained:
- Group each label and corresponding input field inside a `div` tag and place validation text next to it.
- Remove "Hours - " prefixes for clarity.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user, or any other role that has permission to view/add projects.
5. go to dashboard→ Project→ pick a project→ WBS -> select a WBS
6. click "Add task"
  6.1. Enter any number that is greater than "Best case" input in the "Most-case" input.
  6.2. Verify that the validation text appears below the label-input group for each hour type on both desktop and mobile view.
7. pick a task and click "Edit"→"Edit"
  7.1. Follow the same procedure in 6.1 and 6.2 and verify.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/81fb8b16-572b-45e4-82ae-532f2dd75bcd

## Note:
N/A

2024-04-11 20:31 UTC, aaryaneil requested changes
The functionality works as expected for new tasks, but for editing old tasks no warning sign showed up. Please make the necessary changes.
![Screenshot 2024-04-11 at 3 23 05 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/92f263ff-a390-4bc3-839d-ca7646c5f325)

![Screenshot 2024-04-11 at 3 23 39 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/6afc5631-5994-41f1-b72d-5ba6fd271676)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/afcffc4f-9508-4ce3-8f19-7ab57d56695e

2024-04-12 19:52 UTC, kylepham commented
> The functionality works as expected for new tasks, but for editing old tasks no warning sign showed up. Please make the necessary changes. ![Screenshot 2024-04-11 at 3 23 05 PM](https://private-user-images.githubusercontent.com/39597927/321777627-92f263ff-a390-4bc3-839d-ca7646c5f325.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTEzNTUsIm5iZiI6MTcxMjk1MTA1NSwicGF0aCI6Ii8zOTU5NzkyNy8zMjE3Nzc2MjctOTJmMjYzZmYtYTM5MC00YmMzLTgzOWQtY2E3NjQ2YzVmMzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDE5NDQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMzg2OWQwMzI3ODI1ZTNkMDk2OTg5OWYzMWZhZTQyZjQ1MTdmNWRkZWU0ODFiMjI3ZTI0MzlmMTUzOTkxMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EhBVU5QXMwQ4oJPh4MUIgRNE0ZTy92fqBtYHSjTpq8w)
> 
> ![Screenshot 2024-04-11 at 3 23 39 PM](https://private-user-images.githubusercontent.com/39597927/321777675-6afc5631-5994-41f1-b72d-5ba6fd271676.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTEzNTUsIm5iZiI6MTcxMjk1MTA1NSwicGF0aCI6Ii8zOTU5NzkyNy8zMjE3Nzc2NzUtNmFmYzU2MzEtNTk5NC00MWYxLWI3MmQtNWJhNmZkMjcxNjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDE5NDQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NGVhN2U3NDAwZGZiMDA0NGVlMmI5YzU0YjdkNjAyYmJiZWI4ZGJiODFhYWQwNTQ5Y2QzMDQ3NTMwNDJkZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eV0M7MoHaZmHFLmOvykEPc8ZLs2IY9kWI5XqntjviP4)
> 
>  Screen.Recording.2024-04-11.at.3.29.18.PM.mov

Hi @aaryaneil, I believe changing value in an input field will trigger calculation of all input fields underneath when being unfocused (i.e. clicking outside of the text input). That's why at the very end of your demo video, every other values changed when you modified best-case value, so there was no validation error.

2024-04-14 06:22 UTC, hbodgal requested changes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/0f72820a-d611-4336-8605-dd5d14068507)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/76cb603d-8962-4ff2-a2c6-e71f65741fa6)


I used chrome inspect tools and chosed device size for mobile and I was not able to see options when I click Edit button (in mobile screen). (Refer SS 1)

What you have worked looks fine. Both in mobile and Desktop.

2024-04-14 20:12 UTC, kylepham commented
> ![image](https://private-user-images.githubusercontent.com/145157488/322251404-0f72820a-d611-4336-8605-dd5d14068507.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMjQ5NzcsIm5iZiI6MTcxMzEyNDY3NywicGF0aCI6Ii8xNDUxNTc0ODgvMzIyMjUxNDA0LTBmNzI4MjBhLWQ2MTEtNDMzNi04NjA1LWRkNWQxNDA2ODUwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQxOTU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjQ3MjYxYzA0NjhjNTM2Y2IxYTBhZmIxMjMzNDk0YTk5N2Y5MTNhMThiY2UyYjA1Y2I1YWJkMWE5YjdmMDllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2R1q2yT2O3sCzYum0z3mxhbVN-Pu769tAqq3BIdT6Ak)
> 
> ![image](https://private-user-images.githubusercontent.com/145157488/322251501-76cb603d-8962-4ff2-a2c6-e71f65741fa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMjQ5NzcsIm5iZiI6MTcxMzEyNDY3NywicGF0aCI6Ii8xNDUxNTc0ODgvMzIyMjUxNTAxLTc2Y2I2MDNkLTg5NjItNGZmMi1hMmM2LWU3MWY2NTc0MWZhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQxOTU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODljZTMyZjk0NzdiYWQ0OWZlMWUzM2Y3M2FiYjk1ODU2ZmQyNDAzMWIwMDEyYWUyZjZkZGNkZDMzZWVlZWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8IXTMJxFZiipfZFvQH8PRwkW3MsKL1YbgviVuk3jap8)
> 
> I used chrome inspect tools and chosed device size for mobile and I was not able to see options when I click Edit button (in mobile screen). (Refer SS 1)
> 
> What you have worked looks fine. Both in mobile and Desktop.

Hi @hbodgal, thank you for your review. The bug you spotted out appeared to be out of scope for this PR. But what I found out was that the component which is responsible for rendering the action items when clicking "Edit" is working on a desktop-view only. There is a CSS property that forces it not to display on mobile view.

<img width="1622" alt="Screenshot 2024-04-14 at 3 10 42 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/208f6523-1a06-42b1-8523-5e6e5d52d425">

2024-06-02 02:29 UTC, peter6866 submitted a review, later dismissed
Great work on resolving the validation text alignment issue described in #2075. The grouping of labels and inputs, along with removing the unnecessary "Hours -" prefixes, improves the overall clarity and usability.

<img width="509" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/ec4f52c5-8294-40cd-9374-6cb65a470270">
<img width="508" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/b93312ed-9c2d-4281-b0d7-9886e37e8280">

2024-06-21 02:03 UTC, merged