Unit test for UserProfileEdit components - SaveButton, ToggleSwitch and  TriStateToggleSwitch
OneCommunityGlobal/HighestGoodNetworkApp pull request #2148
Opened 2024-04-12 00:37 UTC by bhuvan-dv

## Main changes explained:

Added Five new files names 
1. [SaveButton.test.js](src/components/UserProfile/UserProfileEdit/__test__/SaveButton.test.js)
2. [ToggleSwitch.test.js](src/components/UserProfile/UserProfileEdit/__test__/ToggleSwitch.test.js)
3. [TriStateToggleSwitch.test.js](src/components/UserProfile/UserProfileEdit/__test__/TriStateToggleSwitch.test.js)

## How to test:
1. check into current branch 
 ```bash
   git checkout bhuvan-table
```
2. do `npm install` and `...` to run this PR locally
you can choose to run the files individually or as whole (jump to step 7)
3. run this command 
```bash 
npm run test:coverage D:/HGN/HighestGoodNetworkApp/src/components/UserProfile/UserProfileEdit/__test__/SaveButton.test.js
```
4. run this command 
```bash 
npm run test:coverage D:/HGN/HighestGoodNetworkApp/src/components/UserProfile/UserProfileEdit/__test__/ToggleSwitch.test.js
```
5. run this command 
```bash 
npm run test:coverage D:/HGN/HighestGoodNetworkApp/src/components/UserProfile/UserProfileEdit/__test__/TriStateToggleSwitch.test.js
```
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67942070/be3d4eca-d924-42bf-b7fd-d3b75fca681d)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67942070/9c62378e-dd78-4549-bdc6-16ec7bdb3286)

2024-04-12 08:26 UTC, hbodgal requested changes
Everything works fine. One error occurs when i run the test for SaveButton. Please refer the video.  If thats not a concern let me know on the slack I'll approve the PR.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/9a71bae7-8767-4cba-ad33-9cb8facf02ba

2024-04-12 16:16 UTC, alla0810 commented
All 3 files passed the test successfully.
While [ToggleSwitch.test.js](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/src/components/UserProfile/UserProfileEdit/__test__/ToggleSwitch.test.js) and [TriStateToggleSwitch.test.js](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/src/components/UserProfile/UserProfileEdit/__test__/TriStateToggleSwitch.test.js) passed without errors, [SaveButton.test.js](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/src/components/UserProfile/UserProfileEdit/__test__/SaveButton.test.js) generated some console errors.  
test log file for SaveButton.test.js is attached.

![1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/7ac1044f-c716-49f3-9f93-29d417327e31)
![2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/008e66b2-764d-4714-a9d5-66f030a4dae5)
![3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/72de7371-6cd7-4b4a-bcf6-f399acdfd921)
[saveButton logs.txt](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/files/14961095/saveButton.logs.txt)

2024-04-12 21:32 UTC, aaryaneil submitted a review, later dismissed
All the test cases passed. Good work.
![Screenshot 2024-04-12 at 4 24 17 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/336b7f75-4e9a-4de6-b528-f0e5caf5f7fc)
![Screenshot 2024-04-12 at 4 24 54 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/d6ab4086-4c85-450e-8a3e-5861407316e7)
![Screenshot 2024-04-12 at 4 30 12 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/6a100570-a79c-4d8b-8db4-76ac964fc918)

2024-04-13 05:13 UTC, linkhanthtel approved these changes, later dismissed
All test cases passed! Only one thing, it shows some errors in SaveButton.test.js file.

<img width="1189" alt="#2148 (Toogle Switch)" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/7aed7b54-5e95-411c-8cef-155977bd4d96">
<img width="1188" alt="#2148 (SaveButton)" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/77b2c385-843e-486f-bfe7-765300185882">
<img width="1184" alt="#2148 (Tri)" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/4069cc7b-d736-4e4a-872d-985dbead5ad7">

2024-04-17 06:42 UTC, Pandani07 approved these changes, later dismissed
PR works as intended but got some console errors for saveButton
![Screenshot 2024-04-16 at 11 36 37 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/9077efee-8ce4-4aa1-ab91-8bfbf6043e45)
![Screenshot 2024-04-16 at 11 38 45 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/493fec68-52d5-49b0-a27c-3eb4aa66c643)

ToggleSwitch
![Screenshot 2024-04-16 at 11 37 45 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/56385806-1986-434a-ba8c-f881e08cac1c)

TriStateToggleSwitch
![Screenshot 2024-04-16 at 11 41 44 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/1e103f3d-7526-4c05-8314-16dc6b08cad6)

2024-05-02 11:09 UTC, cgomezhub approved these changes, later dismissed
Well done!, These three files:
SaveButton.test.js
ToggleSwitch.test.js
TriStateToggleSwitch.test.js
have passed the tests

![Screenshot 2024-05-02 064719](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/ab70caaf-da94-423f-89df-1896c301f4d2)
![Screenshot 2024-05-02 064931](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/77561c3a-2d59-4d48-bb3f-b1ad9d56078b)
![Screenshot 2024-05-02 065107](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/2bb2019d-93ad-45b9-bb37-7665feac21bc)

2024-05-17 04:50 UTC, KaushikMreddy commented
Hi Bhuvan, 
1. All test cases have passed with warnings for saveButton
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/05bb4c1a-d9f8-4d4e-8243-9faccaa008ef)

2. All test cases have passed for toggleSwitch
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/a9ffb9f0-26eb-4539-9020-c0d140895db7)

3. All test cases have passed for TriStateToggleSwitch
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/a6682f22-d43d-4345-9152-a6202ad6d305)

There is a lot of redundant code in #1, which is why there is a warning, please check that before you merge.

2024-06-02 01:19 UTC, peter6866 approved these changes, later dismissed
All tests passed as expected.

<img width="621" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/af87bf69-464c-4ef8-970a-dcf7f01d9be7">
<img width="596" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/80422237-8bbf-4633-9e56-62ce4f377d22">
<img width="676" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/61612c67-505d-4e37-85fe-b6d931ae2298">

2024-06-16 04:04 UTC, deepthikannan approved these changes, later dismissed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83337914/bea76351-3f25-46c1-b450-11f801a53281)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83337914/fc567966-1467-4824-976e-cf3dbe12297d)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83337914/9c421496-e920-4749-adb5-4ebef58b84a9)
All test cases passed for all the unit tests.

2024-07-10 00:10 UTC, nikhilpittala16 approved these changes, later dismissed
I have tested the PR and all the test cases passed. Great Work!
![Screenshot (52)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/142841075/719c9132-f322-4404-a2e8-c928250f34c2)

2024-07-10 21:21 UTC, Vigneshwar-Muriki submitted a review, later dismissed
Tested this PR as mentioned in the instructions. All test cases have passed but I ran into issues when testing SaveButton.js file
![#2148_1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/beaf252c-f1ed-4b54-bb81-06a644fdc0dd)
![#2148_2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/0aa51e7d-fe44-41fa-bbfc-0c2693b4e03e)
![#2148_3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/34cae136-996d-4866-b10e-4e9e56ea3f58)

2024-07-15 04:45 UTC, one-community commented
Thank you all, moving this to final review!

2024-08-26 07:47 UTC, beblicarl requested changes
I found errors in the console for the SaveButton tests

![image](https://github.com/user-attachments/assets/405d16aa-60cb-46e4-a390-d9b1e14f8cf4)

The ToggleSwitch test works perfectly

![image](https://github.com/user-attachments/assets/a7ab43d7-5d15-4205-93b3-87b32409064b)

The TriStateToggleSwitch test works perfectly as well

![image](https://github.com/user-attachments/assets/c4e2939e-e749-475f-913a-8b15887ac2db)

2026-08-14 16:41 UTC, closed without merging