Chris update equipment frontend
OneCommunityGlobal/HighestGoodNetworkApp pull request #2160
Opened 2024-04-15 03:23 UTC by chrischenlixing

# Description
Implemented the update equipment page in the bmdashboard as part of the phase 2 development.
<img width="771" alt="Screenshot 2024-04-14 at 8 23 28 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114450390/f45f34be-102f-4289-8c46-3b9e33a9323c">

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
Created UpdateEquipment.jsx and UpdateEquipment.css
Added routing for update equipment
Added the url and added pages like equipmentactions, equipmentreducers, equipmentconstants etc
…

## How to test:
1. check into current branch
2. do npm install and ... to run this PR locally(npm start)
3. Clear site data/cache
4. log as any user eg: volunteer, owner or admin
5. go to http://localhost:3000/bmdashboard and login again
6. Navigate to http://localhost:3000/bmdashboard/tools/65c16ef325834114ac9427e0/update
7. Verify the design from the figma template https://www.figma.com/file/kpwXZP2pLtOJ1Fn2u7Sivn/HGN-PII?type=design&node-id=404-6751&mode=design&t=WKyVjVeztidxL1Y9-0
8. Verify the details of the page from the database from buildingInventoryItems collection.
9. Feel free to change the id in the url to any other id in the database (the type has to be equipment) and verify the webpage data.

## Screenshots or videos of changes:
![Screenshot 2024-04-14 at 8 20 15 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114450390/d3cd11e4-88a5-4da1-b036-6914446446c3)
![Screenshot 2024-04-14 at 8 20 54 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114450390/2bf4ee91-ec3f-4c66-9f5e-1e8d05163a4e)

## Note:
The scope of this pr is just limited to the design of retrieving the equipment data related to its picture, name, number, class, project, current status, ownership, rental end date, and days left. All the other data that need to be updated are not working because there isn't fields in the database to update those data to, once we are done with creating those fields, we can actually update the information into the database

2024-04-16 14:24 UTC, alla0810 commented
could access http://localhost:3000/bmdashboard successfully, but when tried to access http://localhost:3000/bmdashboard/tools/65c16ef325834114ac9427e0/update, I had a lot of console errors, and the screen was white without any rendering.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/2f7ff6cf-5259-4700-9210-e75a712935c9)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/62adffe6-4a67-4fc8-adb5-96056ed2de89

2024-04-16 14:27 UTC, alla0810 requested changes
could access http://localhost:3000/bmdashboard successfully, but when tried to access http://localhost:3000/bmdashboard/tools/65c16ef325834114ac9427e0/update, I had a lot of console errors, and the screen was white without any rendering. Please see the screenshot and video.

![322880815-2f7ff6cf-5259-4700-9210-e75a712935c9](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/5c59e4c7-85ea-420a-b3f9-4d069d38ae22)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/0825c27c-750e-4197-8f4d-c286fe9c8f67


cannot access http://localhost:3000/bmdashboard/tools either.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/6e270b71-d49f-4c64-8bab-aa38d21a05b7)

2024-04-17 13:54 UTC, alla0810 requested changes
tested newly committed branch.
http://localhost:3000/bmdashboard/tools/65c16ef325834114ac9427e0/update is still crashing when being loaded.

![crash](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/0ed2e0b7-a7dc-4f60-9e84-79221ff0e41c)


http://localhost:3000/bmdashboard/tools/65c16ef325834114ac9427e0/ loaded successfully, but looks like a lot of items are missing such as Class, Name, Number, Ownership, Add Date, Rental Duration.  Please check the screenshot.

![2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/246f38db-f3bf-453b-ab9b-7ace1784f2ee)

2024-04-17 14:10 UTC, chrischenlixing commented
Hi Alla, thank you for your review, I think you are using a wrong url without /update at the end. Could you please test the one with correct url to check if it still crashes?

2024-04-17 14:18 UTC, alla0810 commented
> Hi Alla, thank you for your review, I think you are using a wrong url without /update at the end. Could you please test the one with correct url to check if it still crashes?

Hi, Chris.
The url that had crashing was 
http://localhost:3000/bmdashboard/tools/65c16ef325834114ac9427e0/update

Do you suggest another url?

2024-04-17 16:35 UTC, chrischenlixing commented
> > Hi Alla, thank you for your review, I think you are using a wrong url without /update at the end. Could you please test the one with correct url to check if it still crashes?
> 
> Hi, Chris. The url that had crashing was http://localhost:3000/bmdashboard/tools/65c16ef325834114ac9427e0/update
> 
> Do you suggest another url?

Hi Alla, thank you so much for your review! It's working perfectly on my end and I could not reproduce your error...So I cannot try to fix it. I totally understand sometimes it happens, hopefully someone else can try to review it soon to see if there is actually an error.

2024-04-17 17:53 UTC, alla0810 commented
> > > Hi Alla, thank you for your review, I think you are using a wrong url without /update at the end. Could you please test the one with correct url to check if it still crashes?
> > 
> > 
> > Hi, Chris. The url that had crashing was http://localhost:3000/bmdashboard/tools/65c16ef325834114ac9427e0/update
> > Do you suggest another url?
> 
> Hi Alla, thank you so much for your review! It's working perfectly on my end and I could not reproduce your error...So I cannot try to fix it. I totally understand sometimes it happens, hopefully someone else can try to review it soon to see if there is actually an error.

I agree.

2024-04-28 01:29 UTC, jennZhang93 requested changes
tested with owner account. When trying to access http://localhost:3000/bmdashboard/tools/65c16ef325834114ac9427e0/update, I can only see a blank page with some console errors. Looks like it's about `equipmentDetails.itemType.name` that the `name` attribute is unidentified.

 <img width="1680" alt="Screenshot 2024-04-27 at 8 28 04 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/7f390cf5-b3ff-4b84-886b-a4ec8e29d5bf">

2024-04-29 14:56 UTC, closed without merging