Hoang add copy functionality and fix project report table
OneCommunityGlobal/HighestGoodNetworkApp pull request #2163
Opened 2024-04-15 18:34 UTC by kylepham

# Description
![Screenshot 2024-04-15 at 1 27 31 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/44f093c6-1995-4547-b1ae-b8e67d7bdd67)

## Related PRS (if any):
Latest backend development branch
…

## Main changes explained:
- Add ID copy functionality on WBS and Members table in Reports → Reports → Projects 
- Fix styling to display ellipses at the end of ID string when text overflows
- Wrap text in Name column when text overflows
- Fix paging component overlapping with table content

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to Reports → Reports → Projects → AAA USE THIS PROJECT
6. verify that copy functionality works as expected
7. verify that texts in WBS and Members table display with text wrap and ellipses
8. verify that paging component doesn't overlap with table content on small screen sizes

## Screenshots or videos of changes:

## Note:
None.

2024-04-17 15:27 UTC, alla0810 commented
Hi, [kylepham](https://github.com/kylepham).
Great job for improving the appearance of the project report page.
I've checked one by one if all the intended improvements have been fulfilled.

1. Add ID copy functionality on WBS : works great.  I can successfully copy the ID to the clipboard and paste it somewhere else.
2. Fix styling to display ellipses at the end of ID string when text overflows: works good.  I can see the ellipses appear when the space for the ID is not enough.  
3. Wrap text in Name column when text overflows: works good.  Wrapped Names are aligned in the center.
4. Fix paging component overlapping with table content: Works good.  Page component is not overlapping with table content any more.  My little suggestion for this is that, looks like this page component stays in the left side of the table content.  I wonder if this page component can be move to the center of the table component.

![paging component](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/9a48d385-3301-41ca-a3af-1cefbf2363a7)

2024-04-17 18:42 UTC, kylepham commented
> Hi, [kylepham](https://github.com/kylepham). Great job for improving the appearance of the project report page. I've checked one by one if all the intended improvements have been fulfilled.
> 
> 1. Add ID copy functionality on WBS : works great.  I can successfully copy the ID to the clipboard and paste it somewhere else.
> 2. Fix styling to display ellipses at the end of ID string when text overflows: works good.  I can see the ellipses appear when the space for the ID is not enough.
> 3. Wrap text in Name column when text overflows: works good.  Wrapped Names are aligned in the center.
> 4. Fix paging component overlapping with table content: Works good.  Page component is not overlapping with table content any more.  My little suggestion for this is that, looks like this page component stays in the left side of the table content.  I wonder if this page component can be moved to the center of the table component.
> 
> ![paging component](https://private-user-images.githubusercontent.com/131193110/323284849-9a48d385-3301-41ca-a3af-1cefbf2363a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzk1NzksIm5iZiI6MTcxMzM3OTI3OSwicGF0aCI6Ii8xMzExOTMxMTAvMzIzMjg0ODQ5LTlhNDhkMzg1LTMzMDEtNDFjYS1hM2FmLTFjZWZiZjIzNjNhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxODQxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDM5M2I5ZDM5MzU0ZDNmYjBlOWNkYWJmZTE4NTE4ZWRmM2UxMmM2MWJiNDhjNjMyZGM1MjM4ZTdhZGQ5NjMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s5sbPfAh30VLFQiDvEwfrLlSyCYC5LVh5YKn_SPyYBU)

Thank you @alla0810 for your review and suggestions. I'll make updates as soon as I can.

2024-04-18 00:37 UTC, one-community requested changes
Checked and Sarthak finished some related formatting here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2155

Please check his code and take anything that's can benefit your PR. Let me know once you have, then I'll close his and put a “High Priority - Please Review First” tag on yours

2024-04-18 14:16 UTC, linkhanthtel approved these changes, later dismissed
I reviewed your PR and copied functionality works. Also paging component does not overlap with table content in smaller screen sizes. Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/fe3c6000-c7a9-4558-b4ff-5b3331b07f12

2024-04-20 12:09 UTC, aaryaneil approved these changes, later dismissed
The copy functionality works well and the styling looks good too and the changes for smaller screen work as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/d7043f23-1579-49fc-8bc5-203e6661368b

2024-04-20 22:37 UTC, Tiantian-C reviewed
I have tested it and it works very well!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/5ff18c89-fb9e-4a98-8103-0660f0fbd006

2024-04-21 01:41 UTC, metaphor987 submitted a review, later dismissed
Hi Hoang, I've tested the changes using admin and owner accounts, and all the main updates are working well. This includes the ID copy functionality, ellipses when text overflows, wrapped text in the Name column, and no component overlapping. Here’s a recording of the tests. Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/e1724b36-5831-4da6-8418-f93f737658bd

2024-04-23 15:43 UTC, jennZhang93 approved these changes, later dismissed
Tested with owner account and all expected features are working. Good work!

Some details that I found:
- upon loading the project page (first few seconds in the video), it took ~5sec for the member's panel to display all entries
- when the screen is set as a fairly small size, (0:32 in the video) the Tasks panel which has a table header row displayed, the texts are squeezed together and overlapping. Consider making each header into 2 lines with a small screensize might help.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/207ccf09-65c0-4d32-b8d1-99ab5fc24e37

2024-05-01 14:48 UTC, cgomezhub requested changes
Good job! I see that most of the requested changes are complete, however there are some details to consider:

1. Add ID copy functionality in WBS and Members table:
       - well done

2. Fix style to show ellipsis at end of ID string when text overflows:

on screens less than 533 pixels (see images)
- ellipsis in WBS table not working
- task table needs general adjustments
-  borders of all tables are not showed

3. Wrap the text in the Name column when the text overflows:
It works very well!

Additionally, I would like the description to appear centered and left-aligned as shown below:
                 7672 hours committed
                 131 active members
                 145 total contributors

4. Fix pagination component overlapping table content.
made!

5. Correct the texts of the tables so that they are aligned to the left.
made!

![PR#903 (2)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/79b5e48f-2b66-466b-bacc-ba99bb972375)
![PR#903 (3)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/cc9ec71e-b16e-45b8-9098-7bf2ab196ff9)
![PR#903](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/0bbeac7c-6573-4974-af39-51a0fe366bc3)

2024-05-04 23:14 UTC, mSharifHub commented
Hello, I highly believe that we should maintain consistency on the UI here. The functionality works as expected. Mostly, we should adhere to the UI since the UI presented in this pr seems off alignment with the main app UI

2024-05-04 23:15 UTC, mSharifHub requested changes
As I commented in the comments, the UI in this functionality seems to be running off from the main application UI. Overall, the logic works as expected.

2024-05-15 17:58 UTC, nathcarnevalli requested changes
Hi Hoang, you did a really good job. However, as you can see with my video there're some alignment issues especially for smaller screen sizes and the ellipses are not working for WBS table. Also I didn't understand why we have different components for tables with similar designs. 

Uploading HGN APP — Mozilla Firefox 2024-05-15 14-45-09.mp4…

2024-05-16 23:32 UTC, kylepham commented
Hi @nathcarnevalli, I understand your confusion that there are two separate designs for similar table. I tried my best to implement the ellipsis styling on both table and keep everything else intact to match the goal of PR, unless there is a need to change the overall UI.

2024-05-17 13:02 UTC, nathcarnevalli commented
> Hi @nathcarnevalli, I understand your confusion that there are two separate designs for similar table. I tried my best to implement the ellipsis styling on both table and keep everything else intact to match the goal of PR, unless there is a need to change the overall UI.

I really liked the way you did everything. The only issues are with the ellipses and the alignment on small screen sizes. Creating two components with a similar design is not a problem at all :)

2024-05-18 16:42 UTC, nishithaShetty commented
Hi Kylepham, Great Work.
The copy functionality works as expected. The texts are correctly left aligned. On small screens the paging components do not overlap. Texts in WBS ID displays with ellipses on small screen sizes.

<img width="812" alt="PR#2163" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/042fd917-1232-4e90-b866-1bafb1ad0785">
<img width="641" alt="PR#2163_2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/7a443666-77b0-4fc5-b86b-10e58ff05d20">
<img width="434" alt="PR#2163_mobile" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/03fe3d70-9e4e-4d2e-9c1d-426580222367">
<img width="416" alt="PR#2163_mobile_2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/2e2ea991-1258-42c4-aca9-b953e7593661">

2024-05-19 04:29 UTC, MinSun0814 submitted a review, later dismissed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/f9a4fc7d-d954-4716-a783-890f1220ca05)
Hello, I checked your PR and tested the id copy paste and it seems like everything is working fine.

2024-05-21 20:49 UTC, peter6866 approved these changes, later dismissed
Hi, I have checked into your branch and verified these changes work as expected.
<img width="740" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/4445c761-a01e-478c-bf02-194e3511d391">

2024-05-24 01:24 UTC, Sandhya1236 approved these changes, later dismissed
Great job improving the appearance of the project report page. I verified that all the intended improvements have been successfully implemented:

Add ID copy functionality on WBS: Works great. I can successfully copy the ID to the clipboard and paste it elsewhere.
Fix styling to display ellipses at the end of the ID string when text overflows: Works well. Ellipses appear when the ID text exceeds the available space.
Wrap text in the Name column when text overflows: Works well. Wrapped names are aligned in the center.
Fix paging component overlapping with table content: Works well. The paging component no longer overlaps with the table content.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/30300b67-039a-4f1d-b4c4-912551c006f5

2024-05-31 16:29 UTC, ZhangPeizhou commented
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/b762a87f-3233-4058-aa4b-845f1be7303d

Work as expected. Well done!

2024-06-05 07:44 UTC, JatinAgrawal94 requested changes
The page looks great!
1) ID can be copied and pasted from the copy button.
2) Texts in WBS ID displays with ellipses on small screen sizes.
3) Paging component doesn't overlap with table content on small screen sizes.
4) Text are left aligned on both tables.

Issues:
1) On some page sizes the table showing tasks break down, which is the table seems to be too big for the page due to which only a part of it is visible.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/2bd03366-e6a7-41c7-a6b0-628dd0aaac43

2024-06-12 00:29 UTC, akshit0211 commented
It works as expected. Good work!

<img src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/803001ea-08c9-41d3-b796-4968ad56094c" alt="copy">
<img src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/e142ee61-42bd-46fd-acb5-38bd19734bb4" alt="size1">
<img src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/9e3e7d6d-9178-45a8-9671-5c44a0caff8e" alt="size2">
<img src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/f4723c94-74a7-41c7-aeea-f0cca8c8d4e2" alt="size3">
<img src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/e62a5f38-82ef-4dad-b2a6-f0d185e1bc43" alt="size4">

2024-06-12 00:29 UTC, akshit0211 approved these changes, later dismissed

2024-06-21 18:18 UTC, Sudershhh approved these changes, later dismissed
Hi Hoang,

The changes look good. I am able to copy the text id and paste it elsewhere. Good job on the responsiveness for the tables as well.

![PR 2163](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59435391/dbeda763-7509-4039-a2b7-7123933cbd5c)

2024-07-02 19:37 UTC, merged