Sanket - Create way to see 6 months & yearly anniversaries
OneCommunityGlobal/HighestGoodNetworkApp pull request #2171
Opened 2024-04-19 15:00 UTC by SanketKaware

# Description
This PR is about adding a trophy icon for 6M, 1Y, 2Y, 3Y, etc. work anniversaries to the Leaderboard and Weekly Summaries Report.
![Screenshot 2024-04-19 at 9 35 52 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/9ebb55fb-c9c2-473c-996c-718c09e85a98)

The PRs FE[#1603](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1603) BE[#627](https://github.com/OneCommunityGlobal/HGNRest/pull/627) created earlier may cause issues if merged due to significant advancements in both backend and frontend. Moreover, there were some other issues with these PRs which were pointed out in the comments section. In this new PR, I have resolved those.

## Related PRs (if any):

## Main changes explained:
Created Trophy icon for 6M, 1Y, 2Y, 3Y, etc. work anniversaries to the Leaderboard and Weekly Summaries Report

## How to test:

1. Check into the current branch
2. Do `npm run start: local` to run this PR locallyLog in as owner/admin/core/mentor/manager user. As a Volunteer, you won't be able to review this PR.
3. Go to Leaderboard, and verify if you can see a trophy icon with 6M, 1Y, ..., 10Y right of a person's name to check whose anniversary this week.
4. If it's a Red trophy, it means it's not followed up. To check the follow-up feature → Click on the  Red trophy icon → Confirm the button, and verify if the trophy icon then turns Yellow. (This process may take some time) (For some reason - this follow-up feature not working for "0Eduardo Mentor0". I am checking on that, so check the rest of the person's trophies)
5. Go to Reports → Weekly Summaries Reports Page → This Week, verify if you can see the trophy icon right of a person's name.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/576a9b58-8f89-42c1-b3f7-df50e0b18819

2024-04-23 13:55 UTC, alla0810 commented
Hi, [SanketKaware](https://github.com/SanketKaware).
I've checked that trophies are placed on the right side of the names, with 6M and 1Y marks on the bottom of the trophies.
I've also checked the color of the trophies turned yellow from red if confirmed by the administrator.
On Report>Weekly Summaries Report>This Week, I've also found black trophies on the right side of the Name and the team this account belongs to.
Everything works as intended, except some performance issues I believe out of this PR's criteria.
When I tried to load Report>Weekly Summaries Report>This Week from Dashboard, it took me around 10secs or more, and there were a lot of console errors.

![1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/3e2fd0f4-6e41-4c1e-8d26-7e5409f4ccc8)
![2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/02bd9ff6-29c9-43ca-a9e5-a957b494af21)
![3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/2d05aa16-9f76-4de1-aa8a-d45448538669)
![4](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/0c4fffc3-61c1-444a-99cf-e98e9031afcd)

2024-04-24 14:02 UTC, alla0810 approved these changes
Works as expected.  Good work!

2024-04-26 01:26 UTC, jennZhang93 approved these changes
Tested with owner account. Besides that changing the trophy's color did take quite some time, all described features are working. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/252e504c-f5a2-40ef-88ef-a9655552e510

2024-04-28 00:52 UTC, Tiantian-C reviewed
All the functions work well,but it took a very long time to load the weekly summaries report page which is not that user-friendly.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/91ebb2dc-0db1-4095-9b38-87c3744fba81

2024-04-30 23:02 UTC, cgomezhub requested changes
Inconsistency in Trophy Display:

I've identified an issue where the trophy color transition from red to yellow  is functioning correctly, but the trophies themselves aren't displaying consistently across the leaderboard and weekly summary for some users.

Here's a breakdown of the observed behavior:

Missing Trophies on Leaderboard: Users like "Aron Aaron BlueSquare" and "Aaron BadgePersonalMax" have trophies visible in the weekly summary but not on the leaderboard.
Missing Trophies on Weekly Summary: Conversely, "0Nicolle VLT" has a trophy on the leaderboard but not in the weekly summary.

Next Steps:

To investigate this inconsistency further, we can:

Examine the data: Review the user data and trophy logic to identify why trophies are appearing in one location but not the other.
Test scenarios: Simulate different user interactions and trophy states to pinpoint potential bugs in the display logic.
Verify user roles: Ensure users have the necessary permissions to see trophies in both sections.

![Screenshot 2024-04-30 165908](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/a6f5acff-bfdd-4f79-b2bb-6cf36149cfa2)
![Screenshot 2024-04-30 170232](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/5af18761-23d4-43ae-816d-4575360e0396)
![Screenshot 2024-04-30 183146](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/218f761f-dd07-460e-8b53-e93c88dd658a)
![Screenshot 2024-04-30 183520](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/e91a7a39-d711-4142-abd3-785ad7e931b7)

2024-05-03 17:28 UTC, mSharifHub commented
I followed the comments from peers and I can confirm that it does take time to load the dashboard and the error `breadcrumbs.ts:103 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Timelog (created by Connect(Timelog))
    in Connect(Timelog) (at Dashboard.jsx:109)
    in div (at Dashboard.jsx:108)
    in div (created by Col)
    in Col (at Dashboard.jsx:94)
    in div (created by Row)
    in Row (at Dashboard.jsx:86)
    in div (created by Container)
    in Container (at Dashboard.jsx:54)
    in Dashboard (created by Connect(Dashboard))
    in Connect(Dashboard) (at ProtectedRoute.jsx:49)`

could be fixed by reviewing the TimeLog.jsx and using a flag to know whether or not a component unmounted

One of the suggestions for the file function is
`const loadAsyncData = async userId => {
  **let isMounted = true;**
  setTimeLogState({ ...timeLogState, isTimeEntriesLoading: true });
  try {
    await Promise.all([
      props.getUserProfile(userId),
      props.getTimeEntriesForWeek(userId, 0),
      props.getTimeEntriesForWeek(userId, 1),
      props.getTimeEntriesForWeek(userId, 2),
      props.getTimeEntriesForPeriod(userId, timeLogState.fromDate, timeLogState.toDate),
      props.getAllRoles(),
      props.getUserProjects(userId),
      props.getUserWBSs(userId),
      props.getUserTasks(userId),
    ]);
    if (isMounted) {
      setTimeLogState({ ...timeLogState, isTimeEntriesLoading: false });
      const defaultTabValue = defaultTab();
      setInitialTab(defaultTabValue);
    }
  } catch (e) {
    console.log(e);
  } finally {
    if (!isMounted) {

    }
  }
  return () => { isMounted = false; };
};
`
Besides that the PR itself is not related to the performance issue. I would put my best guess that related files must be refractored. The throphy functionality works as expected.

2024-05-03 17:36 UTC, mSharifHub reviewed
There are some performance issues that may not be directly related to this functionality but I recommend adding error handling with try and catch blocks

2024-05-03 17:36 UTC, mSharifHub commented on src/actions/leaderBoardData.js
Error handling will be good choice to help debug

```suggestion
export const getLeaderboardData = userId => async dispatch => {
  try {
    const url = ENDPOINTS.LEADER_BOARD(userId);
    const response = await httpService.get(url);
    dispatch(getLeaderboardDataActionCreator(response.data));
  } catch (error) {
    console.error('Failed to fetch leaderboard data:', error);
  }
};

```

2024-05-03 17:36 UTC, mSharifHub commented on src/actions/leaderBoardData.js
>    return async dispatch => {
Error handling to debug 

```suggestion
export const postLeaderboardData = (userId, trophyFollowedUp, userProfile) => async dispatch => {
  try {
    const url = ENDPOINTS.TROPHY_ICON(userId, trophyFollowedUp);
    const response = await httpService.post(url, userProfile);
    dispatch(postLeaderboardDataActionCreator(userProfile));
  } catch (error) {
    console.error('Failed to post leaderboard data:', error);
  }
};
```

2024-05-04 00:25 UTC, Parth-tech approved these changes
Hey Sanket,
Everything looks good. The functionality works as intended. I can see red colored trophy and after I confirm on the modal it turns yellow as well. 
I can also see the black colored trophy in weekly summaries section. At my end it did not take that long to load weekly summary.
Although unrelated the screen UI dashboard UI was off. I will attach an image for that. 


<img width="1440" alt="haohuimanager in red" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/4f9a6471-dfed-4302-8750-fd2bd85d5d7e">
<img width="1440" alt="changing red to yellow" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/9c39cb63-6195-4a71-8119-68defee151e4">
<img width="1411" alt="haohuimanager in yellow" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/2c9085cc-c86a-4a61-88e3-24a9afa50b2d">
<img width="1440" alt="Weekly sumarries report - 2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/0b93e5cd-142d-4f7e-949f-35dbf6d832a7">
<img width="1440" alt="WeeklySummaries Report - 1 " src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/4b29a86b-f402-430e-a59b-a52e5278c365">

Issue:
<img width="1440" alt="UI Issue" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/9d754a28-f0ba-49eb-bd92-e0fcfb17b048">

2024-05-14 14:29 UTC, kaushikMreddy293 commented
Hi, 

The functionality operates as expected. On the leaderboard, Upon confirmation in the modal, the red trophy transitions to yellow, as intended. Additionally, the black trophy is visible in the weekly summaries section.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42844448/885036a4-67fd-4c92-bb69-ea96f1fa8cec)

2024-05-14 17:52 UTC, nathcarnevalli reviewed
Worked as expected. However there're some performance issues for me too, but I believe they're not related to the task.  You can see it takes a lot of time to receive a response from the server as I've shown on the video below.

![Screenshot 2024-05-14 144717](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/c3550ecd-acf3-4a37-9c12-b452e2cf3906)
![Screenshot 2024-05-14 144738](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/26a62e65-7e42-4a61-b6e3-4d3b9911b7b1)


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/a4e435b4-7adc-4b5c-991f-9ae30b04506c

2024-05-15 14:40 UTC, KaushikMreddy commented
Hi, 

The functionality operates as expected. On the leaderboard, Upon confirmation in the modal, the red trophy transitions to yellow, as intended. Additionally, the black trophy is visible in the weekly summaries section.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42844448/885036a4-67fd-4c92-bb69-ea96f1fa8cec)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42844448/c812de92-ae9c-4ce3-bd7d-8df36a24a75a)

2024-05-18 20:20 UTC, nishithaShetty commented
Hi Sanket,
Good work! the functionalities look good.  
1. The trophies are rendered after the names in the leadership board, with the year below the trophies.
2. The red trophy turns yellow after following up.
3.The black summary is correctly rendered after names, icons and designation in the weekly summaries report
<img width="893" alt="PR#2171_1" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/0ba38a1b-a18b-4cf4-9416-ca21984ef5f1">
<img width="913" alt="PR#2171_2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/92bec47c-b2af-4109-8022-501058d44b84">
<img width="890" alt="PR#2171_3" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/ddf6a7dd-af3c-4b2e-96e5-aa35e3e565c6">
<img width="776" alt="PR#2171_4" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/df2d7828-5cbd-4e7b-ba2c-b914b599bed6">
.
4. It does take some time to load the weekly summaries report.

2024-05-29 19:57 UTC, peter6866 approved these changes
Excellent work on implementing the trophy icon feature for work anniversaries in the Leaderboard and Weekly Summaries Report! 
Here's the review based on the provided testing steps:

✅ Trophy Icon Implementation:
   - Verified that the trophy icon for work anniversaries is successfully added to the Leaderboard and Weekly Summaries Report.
   - Confirmed that the trophy icons are displayed correctly next to the person's name, indicating their work anniversary for the current week.

✅ Trophy Icon Colors and Follow-up:
   - Tested the color-coding of the trophy icons, where red indicates an unfollowed anniversary and yellow represents a followed-up anniversary.
   - Confirmed that clicking on the red trophy icon and confirming the action changes the trophy color to yellow, signifying the completion of the follow-up process.

✅ Weekly Summaries Reports Integration:
   - Verified that the trophy icons are correctly displayed in the "This Week" section of the Weekly Summaries Reports page.
   - Confirmed that the icons appear next to the person's name, maintaining consistency with the Leaderboard implementation.

✅ User Role Considerations:
   - Verified that the testing instructions clearly state the user roles (owner, admin, core, mentor, manager) that can review this PR, while volunteers are excluded.
   - Ensured that the appropriate user roles are considered during the testing process.
  
https://www.loom.com/share/72e533af955a42f49d65b1ea815feb01?sid=a8571ada-dc7d-4d25-9cb9-2ed6be44e49c

2024-05-29 23:42 UTC, Kavil-Jain-514 requested changes
The trophies are visible against the names on the leaderboard. The red color changes to yellow upon confirming the follow-up prompt. 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/9e656972-3296-4024-a196-796b268ec311)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/a81c12cf-f701-4d7a-94ed-0c2bf3683088)


But the trophies symbol is not reflected in the Weekly summary report.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/07194f33-e06e-450e-9f8c-4f8cb91f4210)

2025-04-17 22:51 UTC, closed without merging