Imran toggle invisibility permission self and others
OneCommunityGlobal/HighestGoodNetworkApp pull request #2183
Opened 2024-04-20 20:30 UTC by ImzIssa

# Description
![Desc](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/87269725/7969de79-525b-402e-900f-9c5641fc3414)

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
5. see video below on the rest of steps 

## Screenshots or videos of changes:

Uploading Toggle Inv PR_Trim.mp4…

2024-04-24 07:41 UTC, ImzIssa commented
> Hi, [ImzIssa](https://github.com/ImzIssa). I've tried to follow your video. At first, I've created my team, namely `KyoTestTeam`, and assigned 3 members, `KyoTest Admin`, `KyoTest Volunteer`, `KyoTest2 Volunteer`.
> 
> ![KyoTestTeam](https://private-user-images.githubusercontent.com/131193110/324943942-d2e5389c-1bcc-492d-a00f-895512d112e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDQyODYsIm5iZiI6MTcxMzk0Mzk4NiwicGF0aCI6Ii8xMzExOTMxMTAvMzI0OTQzOTQyLWQyZTUzODljLTFiY2MtNDkyZC1hMDBmLTg5NTUxMmQxMTJlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwNzMzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNmJiY2VkZTBjMzU4NTc3YmVmOWZmNjE2ZGI1ZTM2MzM2ZDQ4ODZkYjVhZjcyMzRlYjgxNTNlZjViMzA0YWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tiO9bsw1ogdowXCjH5DcM7FTdiZUX4RHqAhkZEJyVAQ)
> 
> As expected, when logged in as `KyoTest Admin`, I could see the `visible/invisible` toggle button, and when logged in as `KyoTest Volunteer` and `KyoTest2 volunteer`, I could not. I've logged in as `KyoTest Admin` and could successfully give permission for `Toggle Invisibility Permission Self and Others` to `KyoTest Volunteer` and `KyoTest2 Volunteer`, which is good until now.
> 
> I've made both `KyoTest Volunteer` and `KyoTest2 Volunteer` invisible by setting the toggling button to `invisible`, when I logged in as `KyoTest Volunteer` and `KyoTest2 Volunteer` separately.
> 
> ![KyoTest made invisible](https://private-user-images.githubusercontent.com/131193110/324944612-7da0e7c3-fcb8-4bda-9510-7525072f0ca6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDQyODYsIm5iZiI6MTcxMzk0Mzk4NiwicGF0aCI6Ii8xMzExOTMxMTAvMzI0OTQ0NjEyLTdkYTBlN2MzLWZjYjgtNGJkYS05NTEwLTc1MjUwNzJmMGNhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwNzMzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDk3MzM3ZTNkYzQ4ZjRiZmNiNmFjY2I5MDdhZWJkOWUyNTUyOTBlYjIzMzkyODMxNjQyZWM1YzFiNjQ5YWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BNApEP2XGusP05J8FccFzrMG4VVlHPsS3pVAR8ZBgM4) ![KyoTest2 made invisible](https://private-user-images.githubusercontent.com/131193110/324944642-ec6b0266-344e-4b17-b873-d90b7a4e456e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDQyODYsIm5iZiI6MTcxMzk0Mzk4NiwicGF0aCI6Ii8xMzExOTMxMTAvMzI0OTQ0NjQyLWVjNmIwMjY2LTM0NGUtNGIxNy1iODczLWQ5MGI3YTRlNDU2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwNzMzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGUyNTFhODM0Yzc2NzRhNDlkZmZjZTc2M2FkOTljYzRhODA3ZjMyM2U0OTYwOWVkZmMwNmRhNGU1OWQ2NThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KvIyADxY-MLMYNJ6Sbck5l_QKD2vh8P-hcrD0USjWh4)
> 
> I've also made `KyoTest Admin` invisible.
> 
> ![KyoTest Admin invisible](https://private-user-images.githubusercontent.com/131193110/324945337-7b5e5a1e-3ed2-4b6e-a8b5-b676e2ecd8fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDQyODYsIm5iZiI6MTcxMzk0Mzk4NiwicGF0aCI6Ii8xMzExOTMxMTAvMzI0OTQ1MzM3LTdiNWU1YTFlLTNlZDItNGI2ZS1hOGI1LWI2NzZlMmVjZDhmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwNzMzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjFiNjg1OTkxOTAxNGYxMjMyMzQ5Y2FlMjQyZDc3YzFkODE0YTQyNjNkNTRjOTVkMmQwMzgzNDA4Y2U5MGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XBsyivy9-zfprlCJexUNa_HC0Z88U-HlGQq9Wft9TI8)
> 
> Now, we expect the team members cannot see each other.
> 
> But what I have now is, I can see all members from the Dashboard no matter what account I logged in with.
> 
> When logged in as `KyoTest Admin`, I could see `KyoTest Volunteer` and `KyoTest2 Volunteer`, which could be thought as acceptable because I logged in as an administrator.
> 
> ![visiable logged in as admin](https://private-user-images.githubusercontent.com/131193110/324947023-aad7fbb8-0304-45f5-ac5d-1da238ce6ae7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDQyODYsIm5iZiI6MTcxMzk0Mzk4NiwicGF0aCI6Ii8xMzExOTMxMTAvMzI0OTQ3MDIzLWFhZDdmYmI4LTAzMDQtNDVmNS1hYzVkLTFkYTIzOGNlNmFlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwNzMzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmUzNWMxZWU3YmUwYzA1NDJiOGY4NThmZGNjZWRkMzQwZGE2YzM5ZTIwZjYyZmFhMzQ1MDBjMzA1MGI0MjE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OdkDN6urOC6QbbNblT94SUx1PoWBA0mDKlAZU2YDYY0)
> 
> But when logged in as `KyoTest Volunteer`, I could also see all of the members from Dashboard, who were all set INVISIBLE.
> 
> ![all users visible](https://private-user-images.githubusercontent.com/131193110/324947323-c59cb7b1-d628-42f0-b6d7-2a76fd4e80be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDQyODYsIm5iZiI6MTcxMzk0Mzk4NiwicGF0aCI6Ii8xMzExOTMxMTAvMzI0OTQ3MzIzLWM1OWNiN2IxLWQ2MjgtNDJmMC1iNmQ3LTJhNzZmZDRlODBiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwNzMzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjI3NDIxYzVhMzEwYmQyNmZmMTc3YjI1ZGJjOGUxNjA5YTQ2OThiNTFhYjBkOTRlNjI2YmRjZTU2ZmU4ZjI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ocEgNfnCWWdCAm0dpbGNERgzcPhF94uH0bF1rupaRGE)
> 
> I've logged in as `KyoTest2 Volunteer`, and also could see all members belonging the the same team including the one who has the administrator status.
> 
> ![all users visible](https://private-user-images.githubusercontent.com/131193110/324947694-70f9123f-01b8-4fbf-b96a-4febfb9d3065.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDQyODYsIm5iZiI6MTcxMzk0Mzk4NiwicGF0aCI6Ii8xMzExOTMxMTAvMzI0OTQ3Njk0LTcwZjkxMjNmLTAxYjgtNGZiZi1iOTZhLTRmZWJmYjlkMzA2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwNzMzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjdlNzQ5Yjk0NzVjMGRkZjk4Mjg4MzkzNWY0NGU4MjNjYjExMGE2YTc2MzZmMTRiYWY1ODAwNGM0ZjMyZjVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U4TKBkPENyG8Wsr4QsSpSs93v1vQZJx_6TEO-rAoJ44)
> 
> I've logged in and out many times and went back and forth from pages to pages, and the localhost ended up with crashing, which I think from backend database error.
> 
> ![crash](https://private-user-images.githubusercontent.com/131193110/324948079-47790168-100a-407a-8134-3e10d3c11721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDQyODYsIm5iZiI6MTcxMzk0Mzk4NiwicGF0aCI6Ii8xMzExOTMxMTAvMzI0OTQ4MDc5LTQ3NzkwMTY4LTEwMGEtNDA3YS04MTM0LTNlMTBkM2MxMTcyMS5wbmc_WC1BbXo [...]

2024-04-29 18:50 UTC, cgomezhub reviewed
Toggle Function Issue - Admin vs. Volunteer User

During testing, we encountered an inconsistency with the toggle function:

Admin User: The toggle function works as expected, allowing admins to successfully set the volunteer user's status.

Volunteer User: However, the toggle function is not functional for volunteer users. They are unable to:

Activate the "closed eyed" option.
Change their status to "inactive."

![Screenshot 2024-04-29 121317](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/4a0068c9-0d44-4b6b-b948-efefa18bd39f)
![Screenshot 2024-04-29 143911](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/4507a0f0-ce39-41cd-b800-dac9221bf288)
![Screenshot 2024-04-29 143935](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/24779071-e3fa-4ff5-a661-7922aaff8662)
![Screenshot 2024-04-29 144353](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/47725d0a-04f5-4738-bc49-a730e9a566c0)

2024-04-30 17:37 UTC, mSharifHub requested changes
After reviewing your code I noticed that you not accounting for failure due to network. In addition, on userManagement.js
`export const deleteUser = (user, option) => {
  const requestData = { option, userId: user._id };
  const deleteProfilePromise = axios.delete(ENDPOINTS.USER_PROFILE(user._id), {
    data: requestData,
  });
  return async dispatch => {
    deleteProfilePromise
      .then(res => {
        dispatch(userProfileDeleteAction(user));
      })
      .catch(err => {
        dispatch(userProfileDeleteAction(user));
      });
  };
};`

 the function dispatched the same action (userProfileDeleteAction) whether succeeds or fails. This may not allow the UI to respond appropriately.

2024-04-30 17:37 UTC, mSharifHub commented on src/actions/userManagement.js
> +    toggleVisibilityPromise.then(res => {
the code is missing error handling. You are only handling success cases of axios.patch requests. However, it does not account for situations where the request may fail due to network issues, server errors, or other reasons. 
```suggestion
   .catch((err)=>{
   console.error("failed to toggle visibility:',error):
   dispatch(userProfileErrorAction(error));
   }
   }
   ........
```

2024-05-09 22:11 UTC, KaushikMreddy reviewed
Hi, 
I've reviewed your changes, and it works for myself ( Owner Account ) and I tried to set it for someone else as well.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/a7b6fcf8-80c9-4779-b789-b24590a53a52)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/6c0c2752-5912-4c2f-a8c3-5d00d8359eef)


I encountered an error with a value called count while opening another user account from the homepage. I'm not sure if this is related to this feature, but please take a look if possible

Click on the underlined user
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/c3f0f961-61be-4f31-8167-3f6793f9622b)

Got this error
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/5f12c252-f23f-4ae9-9e05-477e15f2705b)

Please note that this error is only occurring for the the user: 0Eduardo Volunteer

2024-05-10 14:43 UTC, ImzIssa commented
@cgomezhub Thank you for testing. The Leaderboard was not part of the scope for this PR

2024-05-10 14:45 UTC, ImzIssa commented
It's not ralated but did you try clearing the cache?

2024-05-14 17:08 UTC, nathcarnevalli reviewed
I've got an error SyntaxError as shown below

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/4777e157-f549-4984-87f3-42168ac5f02a)

2024-05-15 04:10 UTC, ImzIssa commented
@nathcarnevalli Fixed. Please Test again

2024-05-16 03:58 UTC, ImzIssa commented
@nathcarnevalli this PR does not cover the dashboard but did you try a hard reload of the page

2024-05-16 12:29 UTC, nathcarnevalli commented
> @nathcarnevalli this PR does not cover the dashboard but did you try a hard reload of the page

Yes, but I tested now on Google Chrome and it worked. I'll approve your PR.

2024-05-16 12:29 UTC, nathcarnevalli approved these changes

2024-05-18 02:15 UTC, jayyy-s submitted a review, later dismissed
Appears to be working correctly. The position automatically exists for an owner level user, and I was able use the toggle/confirm modal. I am able to assign the permission to a volunteer user and this video also shows that a mentor role does not automatically have the permission. It appears to address everything that was in scope, so I'm approving.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71467346/cc9bacaa-2531-4838-85fa-477380181671

2024-05-18 19:11 UTC, nishithaShetty commented
Hi, I've reviewed your changes, and it works for Admin and volunteer user.
I encountered this error, loading follow up data when I log into any account
<img width="930" alt="PR#2183_1" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/858a824f-9474-4225-b63f-cd1abdb138ba">
<img width="869" alt="PR#2183_2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/045ed615-d25a-4a59-a0cc-56734c23a66c">
<img width="406" alt="PR#2183_3" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/ce1ddecb-51c3-4d83-b4ec-3586f15f0353">
<img width="385" alt="PR#2183_4" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/cdbcb027-eb06-4e46-b757-e6f0ebcf3db4">
<img width="956" alt="PR#2183_error" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/ee06fbf1-b03d-4b7d-b4b4-d0cf58d15ef9">
<img width="946" alt="PR#2183_error_followup_data" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/daaa515c-9cfa-4484-9383-d95a14ee2492">

2024-05-22 03:22 UTC, Sandhya1236 commented
> Member
> ###
> <img alt="@ImzIssa" width="24" height="24" src="https://avatars.githubusercontent.com/u/87269725?s=48&amp;v=4"> ** [ImzIssa](/ImzIssa) **
I'm unable to play the video nor download it for testing. Can u help me?

2024-06-01 00:05 UTC, Infinite-Turkey requested changes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122322808/53469ced-4876-4a67-a9ff-cf9759a8b367)
I have followed your video, but met 1 errors: 1. Loading follow up data when I logged into my account

2024-06-05 02:46 UTC, Kavil-Jain-514 approved these changes
The functionality works as expected.
The test user doesn't have the visibility toggle before permission
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/6b7cb302-7ca3-41c7-a037-c8cad99dbe78)
Setting the permission
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/e5daf88f-d018-434a-b910-63e82cbe6f33)
Toggle option is visible
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/8598ae79-5449-4a7a-abbf-96f86004b9a4)
User is able to hide his visibility
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/6f7d611a-a937-4c18-aaf0-de4a6f5e4253)


Great work!!

2024-06-05 06:36 UTC, JatinAgrawal94 submitted a review, later dismissed
Functionality works as described. Consider a couple of warnings being shown in the console. Rest everything works fine.
Good job!

![2183](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/540e9ad3-39ea-4427-9577-970ad87c16ad)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/8f64082d-d073-4bb8-9675-e2fd33885ebc

2024-06-08 21:29 UTC, akshit0211 commented
Hi Imran, after granting permission to a volunteer user, I can successfully toggle their invisibility or visibility.

<img src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/57f225dd-26e5-4229-900d-a95b807a7148" alt="admin user" />
<img src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/34b6449d-e53a-4dc3-b791-070040e39f13" alt="volunteer user" />
<img src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/1861ed86-4cea-4113-acdb-0177677f3bb6" alt="Permission" />
<img src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/c092bcc4-0563-456d-a448-7f3a4f0e00d8" alt="Volunteer with permission" />

2024-06-08 21:29 UTC, akshit0211 submitted a review, later dismissed

2024-06-26 05:45 UTC, DiyaWadhwani requested changes
Hi Imran,
Tried testing this as per your instructions but I'm unable to view the user profile. Reloading the browser displays the user profile for a second and the entire UI becomes blank again. 
There are around 3 API calls on the backend throwing a 404 error and my assumption is that the other API calls are dependent on either of them. (I'm guessing it's this one 
http://localhost:4500/api/notification/unread/user/66725af292f78117649bdc5b)
I have attached a video of the issue I'm facing while testing. Kindly review this.

Thank you

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54880903/7fd0cea3-c0d1-4777-aee3-431bf2f635d4

2024-06-27 19:07 UTC, vishavk1992 requested changes
I am unable to start localhost:3000 due to errors and failed test suites. I have followed the steps you mentioned, but I'm still encountering issues. Additionally, I am unable to review this PR alongside the backend PR 906.

![PR-2183](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/2c3de501-39ed-423d-a8c7-4b8da3af0d22)

2024-07-12 01:59 UTC, nyelmela reviewed
I am unable to start `localhost:3000` due to errors and failed test suites. Despite following the steps mentioned, I am still encountering issues. Additionally, I am unable to review this PR alongside the backend PR #906. Thank you.

<img width="960" alt="image" src="https://github.com/user-attachments/assets/2f8e1618-cf33-471e-a09d-1e0602f4bc79">

![image](https://github.com/user-attachments/assets/887bca95-ce77-40a0-a136-8e8d4b0d68d0)

2024-08-02 16:14 UTC, Pranay-ai requested changes
Hey @ImzIssa 
I have tried testing the PR but i ran into few errors on the console here is the LOG file.
[localhost-1722615277507.log](https://github.com/user-attachments/files/16472831/localhost-1722615277507.log)

2024-08-16 01:23 UTC, Parth-tech commented
Hey Imran,
After the dashboard loads up it goes blank. 

`Error:`
<img width="634" alt="Screenshot 2024-08-15 at 6 22 19 PM" src="https://github.com/user-attachments/assets/4682b369-f157-4ef4-a336-b1aa05a277bd">
<img width="644" alt="Screenshot 2024-08-15 at 6 22 27 PM" src="https://github.com/user-attachments/assets/e435853f-30ea-4811-9064-c7f05879ffdb">
<img width="1440" alt="Screenshot 2024-08-15 at 12 00 04 AM" src="https://github.com/user-attachments/assets/4e223605-bcd4-487f-b69d-388f96c8bd44">

2024-08-16 01:24 UTC, Parth-tech commented on src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
> +import { boxStyle } from 'styles';
You need to remove this line.

2024-08-17 06:20 UTC, SMitta11 requested changes
I ran this as per given instructions but on running frontend code getting error as boxStyle is imported twice, need to remove one import statement.
Screenshot:
![Screen Shot 2024-08-17 at 1 11 51 AM](https://github.com/user-attachments/assets/453d6b58-a649-40b1-9299-0703a71ece27)
So I commented one of the import statement and ran again, there was no error this time but the app is showing unexpected results. It first gives the error and then page is blank if I refresh:
![Screen Shot 2024-08-17 at 1 17 31 AM](https://github.com/user-attachments/assets/dbce4336-f96a-4a6a-8064-a9e55c30ac1b)
![Screen Shot 2024-08-17 at 1 19 40 AM](https://github.com/user-attachments/assets/918619ce-8b9d-4591-8f0f-568b76b89f0d)

2024-08-17 21:56 UTC, adityasure9 approved these changes
I have tested the PR according to the provided instructions, and everything works as expected. The toggle functionality for invisibility permissions is functioning correctly, and I encountered no issues during testing. Great job on implementing these changes! Thank you!

![image](https://github.com/user-attachments/assets/a5645de1-eafc-438e-b7c2-5a3274555a96)

2024-08-31 00:41 UTC, oliviahyw requested changes
Hi @ImzIssa I tested this PR and I encountered this issue: if I logged in as an Admin/Owner, my profile page is blank. But if I logged in as a Volunteer, I can see my profile page. Please check the attached screenshot.
<img width="1237" alt="Screenshot 2024-08-30 at 7 40 13 PM" src="https://github.com/user-attachments/assets/ab3bbef0-42fd-45fe-9326-fc3af29e9538">
<img width="1309" alt="Screenshot 2024-08-30 at 7 40 39 PM" src="https://github.com/user-attachments/assets/6b1f7ffc-0d84-4179-a9cc-bff8be25a9b1">

2024-08-31 23:11 UTC, ishangoel17 reviewed
Verified the PR with the given branch code and observing blank screen issue while trying to navigate to the user profile page. Below are the screenshots for reference:
![PR_Review_2183](https://github.com/user-attachments/assets/af388cc5-e24e-4ab7-a1bf-246d64964f46)

2024-09-07 08:26 UTC, Shreyav2000 requested changes
Hi,

I followed the steps in your video, but when I log in as an Admin/Owner and navigate to any user profile (e.g., my test or volunteer user account) to assign a team, the page goes blank. I also tried viewing my own profile on the Admin page, and the console threw some errors.

Please refer to the video I'm uploading that shows the issue. Could you review and make the necessary changes?

Thanks!

https://github.com/user-attachments/assets/c5dbfc0c-4982-4a85-9b30-b74434f36d47

2024-09-07 15:01 UTC, sam19981 requested changes
Hi @ImzIssa 

Tried To test the changes but the website crashed as soon i tried to open the profile page for the admin and found the following errors.

<img width="1440" alt="Profile page crashes" src="https://github.com/user-attachments/assets/4279aa26-7919-4516-a17b-c4ca7cea5459">

so checked the code from the look of it you import is missing for the toggle switch in the 
[UserTeamsTable](src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx).

2024-09-10 20:34 UTC, vedantg24 requested changes
Tested the PR, and faced some issues. When I login as Admin/Owner and go to my user profile or go to any other user's profile, the page goes blank, with errors in the console. However, if I log in as a volunteer, I can view my user profile. Attaching screenshots for the same.
![Screenshot 2024-09-10](https://github.com/user-attachments/assets/97054dd1-b4cb-498f-8770-509502199887)
![Screenshot 2024-09-10](https://github.com/user-attachments/assets/43ed6479-8250-4ee8-b3d1-2f3b7d52cac3)
![Screenshot 2024-09-10](https://github.com/user-attachments/assets/c0aa6b8b-4d47-4d56-9841-06d74929959f)

2024-09-12 15:20 UTC, swaroop-2007 requested changes
@ImzIssa,
I reviewed your PR and checked the code as well, but there seems to be an error with the functionality. Please refer to the below screenshots.
![Screenshot (395)](https://github.com/user-attachments/assets/692752bb-9404-493d-bc90-4191a0516da8)
![Screenshot (396)](https://github.com/user-attachments/assets/7fcbb791-95a6-4c41-b61a-c51d122d0c05)

I guess there is some rendering issue. You may need to re-check the code. 
Thanks.

2024-12-31 03:41 UTC, closed without merging