Add validation for required review link and implement link checking
OneCommunityGlobal/HighestGoodNetworkApp pull request #2185
Opened 2024-04-20 23:37 UTC by anandsesha

# Description
![Description](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/29ed21a1-c9b6-4fb5-bfba-be676bbb5577)

## Related PRS (if any):
This frontend PR is related to the dev backend
…

## Main changes explained:
- Updated the input field to be 'required' and show an error message when an invalid or empty URL is entered during review submission.
- Modified `handleLink` to set the appropriate error message depending on whether the URL is empty or invalid, clearing the error when a valid URL is entered.
- Implemented logic to clear linkError when the review modal is closed to prevent error messages from persisting on re-opening.
…

## How to test:
1. Check into current branch
2. Do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. Log as any user with task assigned
5. Go to dashboard→ Task Tab→ Submit For Review.
6. Click 'Submit for Review' and the Change Review Status model pops up
- The model should display → Please add link to related work: (required)
- Check if you are able to Submit review without entering any link. Appropriate error message should be shown.
- Test using other invalid links/shortcuts/without https:// to see if it accepts such links. 
- When an error message is shown, click 'Cancel' and re-open the Change Review Status modal by clicking on Submit for Review. The earlier error should not be persisted when the popup is reopened. 

## Screenshots or videos of changes:
![Screenshot (858)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/4d58a7f2-a11d-4b19-8520-d7de3ae5711a)
![Screenshot (862)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/3da28526-3fb5-45c1-8397-f90bd1527f8d)
https://www.loom.com/share/f627bb2b70c247cab222c2fff4d68365?sid=e5251dee-98cd-4dec-a1f9-60a81f1f823e

## Note:
N/A

2024-04-24 19:53 UTC, alla0810 commented
Hi, [anandsesha](https://github.com/anandsesha).
Can I ask a question?
I've tried to find `Submit for Review` from the Task tab, but I don't know how to add this `Submit for Review` under a user's Task.
Can you please explain how I can add `Submit for Review` to test this PR?

2024-04-24 22:15 UTC, anandsesha commented
> Hi, [anandsesha](https://github.com/anandsesha). Can I ask a question? I've tried to find `Submit for Review` from the Task tab, but I don't know how to add this `Submit for Review` under a user's Task. Can you please explain how I can add `Submit for Review` to test this PR?

Hi @alla0810 you can follow the below video link which explains how to add a task and assign yourself to it. Once you do, it will show up on the Dashboard under the Task tab.
https://www.loom.com/share/8bc672c323b64955aac4bce46c3794aa?sid=b05f5604-87cb-4ca1-80b8-49bd823893ee

2024-04-27 16:54 UTC, alla0810 submitted a review, later dismissed
Hi, [anandsesha](https://github.com/anandsesha).
To tell the scope of this PR, looks good working.

When logged in `DevAdmin`, I could assign a task to `KyoTest Admin`, and when logged in as `KyoTest Admin`, I could see `Submit for Review` button.
As expected by this PR, I had to add an appropriate link related to this task.
I've tested 3 invalid cases, one empty link and two incomplete links, and checked these linked were successfully declined.

![4-good](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/e7976c05-ba15-4906-b312-411db21c44a6)
![5-good](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/93ff781b-e002-4923-9b5e-324be0ad39e9)
![6-good](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/2e01feb3-a617-4a7f-a580-c53a985df852)

When I input an appropriate link, the `Submit for Review` was approved and the button turn into `Ready for Review` state, which is a normal state transition.

![7-good](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/eb8039bf-1e4d-412e-9612-ebc97f8e2696)

Apart from the requirement of this PR, this branch seems very unstable, sometimes made my all of the chrome browsers `Not Responding`, or sometimes I had to reboot my computer.
I've also noticed some errors repeatedly coming up including `GET` method error.
Please see the screenshots of DevTools, network side error messages, bash windows error messages, and console log file attached.

![1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/229cd170-a01e-4aed-8df2-3ba6a901c7c5)
![2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/ecbb7552-2d82-42a0-a955-d85230e23179)
![3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/566e8536-ee96-42fa-8521-d7ac84830100)

[console log.log](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/files/15139023/console.log.log)

2024-05-03 19:08 UTC, Ramaruva approved these changes, later dismissed
I have verified changes in my local url checking is working as expected

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/78db930f-29a6-4e31-90ed-d9c60161e011

2024-05-25 03:24 UTC, peter6866 submitted a review, later dismissed
Changes work as expected with invalid links.
<img width="469" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/4f8c2994-ebbc-4c37-a28e-7214c6d28517">

2024-05-28 10:20 UTC, nishithaShetty commented
Hi Anand, Great work.
It works as expected. I see the error message when we submit without a link, and when we click the submit review button again, the error message does not reappear. I also tried submitting the URL without https://, and an error is correctly thrown.
<img width="957" alt="PR#2185_1" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/91718b99-f58c-4b2d-a851-584aaf4e0a19">
<img width="947" alt="PR#2185_2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/58e2a1c2-5eff-44d4-99bd-76d013636dfd">

2024-06-06 18:25 UTC, JatinAgrawal94 submitted a review, later dismissed
Feature works as expected.
Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/cb3aff10-f990-4a3a-8dd3-a8ccec9af2ab

2024-06-06 18:26 UTC, JatinAgrawal94 commented
> Feature works as expected. Great work!
> 
>  PR.2185.mp4

2024-06-07 22:53 UTC, CloudyZ524 approved these changes
Hi Anand, 
The function of adding valid URL for "Submit for Review" works as expected. 
I've been able to assign a new task to a user and tested from the user's task tab. Also, it is impossible to submit an invalid URL. Well done!

<img width="654" alt="Screenshot 2024-06-07 at 15 49 51" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124476559/b2add101-d6da-4e62-a628-7c5b2336231d">

2024-06-11 18:31 UTC, TXMO-dev requested changes

2024-06-11 18:31 UTC, TXMO-dev commented on src/components/TeamMemberTasks/ReviewButton.jsx
> +              e.preventDefault();
If this can be put in a seperate class for reusability and maintainability please.

2024-06-11 23:21 UTC, akshit0211 commented
Hi Anand, the changes are working as expected. Good work!

<img src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/ceb93e49-e444-4b75-aad2-2154ffc8929e" alt="err1">
<img src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/e3f88e25-02ff-4af3-8c21-330483a7b786" alt="err2">
<img src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/820121a5-80fa-4f5c-af1c-e00f5dd6fc05" alt="err3">

2024-06-11 23:21 UTC, akshit0211 approved these changes, later dismissed

2024-06-13 15:27 UTC, TXMO-dev approved these changes
URL validation check works perfectly fine and meets all requirements. Great Job. Approved!

2024-06-21 01:37 UTC, suaniii submitted a review, later dismissed
The functionality works as expected: an error message appears when submitting without an appropriate link, and it does not reappear upon clicking the submit review button again. I tested an empty link and incomplete links, and confirmed that these links were not accepted.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113208952/910a3689-76f8-479b-b9e5-ee005f677be5

2024-07-03 23:38 UTC, nyelmela submitted a review, later dismissed
I have tested the functionality in this PR by running the application locally, clearing site data, and performing the steps to submit a task for review. The "Change Review Status" modal correctly prompts for a link to related work and shows appropriate error messages for invalid or missing links. Errors do not persist when reopening the modal. Everything is functioning as expected. 
<img width="945" alt="2185 Anand_required_review_link_on_task_submission" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/aaefefb7-7eb8-42aa-8b06-b4ab2d915775">
<img width="945" alt="2185(1)" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/9f5a43a1-755e-4e08-b548-2c54731f8a86">
<img width="947" alt="2185(2)" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/db01a250-dee1-45ad-b327-e337f71f33ec">

2024-07-06 01:59 UTC, Vigneshwar-Muriki approved these changes, later dismissed
Tested this PR using admin account. Firstly, I have created a task for the admin and then refreshed it so that I could see the task in the tasks section. Then I clicked submit review button and a dialog box appears to enter a valid URL. I have tried all possible cases and it works well for all scenarios. Also, I clicked cancel too see if the error persists after clicking submit review button button and it hasn't.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/3532063e-1705-4dbf-bc12-856b111f48c9

2024-07-11 19:52 UTC, Shadhrush5 submitted a review, later dismissed
Hi, I have tested PR 2185, the changes on the current branch by following the steps provided: performed npm install and ran the PR locally, cleared site data/cache, logged in as an user with a task assigned, navigated to the dashboard -> tasks ->Submit review.  The pop up appears as expected and works as expected. The link checks are working fine as well.
<img width="1728" alt="Screenshot 2024-07-11 at 12 45 05 PM" src="https://github.com/user-attachments/assets/2b5d99ba-333c-4e73-97be-2c1490907850">
<img width="1728" alt="Screenshot 2024-07-11 at 12 45 20 PM" src="https://github.com/user-attachments/assets/4c7b1f66-265d-42f8-9d90-2121c07d9ec2">
<img width="1728" alt="Screenshot 2024-07-11 at 12 46 04 PM" src="https://github.com/user-attachments/assets/95e0d7f4-a61b-4aca-8454-77ec2a335384">
<img width="1728" alt="Screenshot 2024-07-11 at 12 46 17 PM" src="https://github.com/user-attachments/assets/3e8266a4-d6e8-4f10-882d-9190cde6ec6f">

I have approved the same. Great work.

2024-07-13 07:19 UTC, AnujVakil submitted a review, later dismissed
I have tested this PR and It is working correctly as expected.
<img width="1430" alt="PR #2185_1" src="https://github.com/user-attachments/assets/6a912335-d75a-494b-97fc-a10451bb841d">
<img width="1440" alt="PR #2185_2" src="https://github.com/user-attachments/assets/b2c66842-5436-47d3-88b8-f3cc8a556614">
<img width="1435" alt="PR #2185_3" src="https://github.com/user-attachments/assets/0eaf23f0-2462-4942-af71-6af86534383b">

2024-07-13 16:52 UTC, KurtisIvey commented
I noticed there was a merge conflict on this pull request. Would you be able to clear it up please when you get a chance? Looks to be a high quality pull request as you've got all approvals, so we'd like to get this moved to final review and merged 😁

2024-07-17 00:31 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.
![Screenshot (105)](https://github.com/user-attachments/assets/948b0701-58e5-4d67-b764-330a8fe8d89b)
![Screenshot (106)](https://github.com/user-attachments/assets/1bb3cddf-4697-46b1-8621-17eee2dc0a56)
![Screenshot (107)](https://github.com/user-attachments/assets/8cf97dd6-7837-445c-a8e5-89fbaf7de624)
![Screenshot (108)](https://github.com/user-attachments/assets/58d55b35-0769-41c3-b571-3ec03a43150f)

2024-07-26 18:42 UTC, Shadhrush5 requested changes
Hi, I tried reviewing the PR #2185. I ran into some trouble trying to build the front end on the current branch. I have attached a screenshot of the same.

<img width="682" alt="Screenshot 2024-07-26 at 11 32 56 AM" src="https://github.com/user-attachments/assets/4f968420-201a-413f-92ee-674f3467e8d1">

2024-07-26 19:56 UTC, souravwalke commented
Tried reviewing the PR but the local deployment failed with the following error in the console.

<img width="1315" alt="Sc

<img width="685" alt="Screenshot 2024-07-26 at 12 54 04 PM" src="https://github.com/user-attachments/assets/f4352823-fe43-4f68-858b-f3d05af8f955">

<img width="685" alt="Screenshot 2024-07-26 at 12 54 04 PM" src="https://github.com/user-attachments/assets/6c14edb6-2347-40ce-a223-51b0665a3fca">

2024-08-11 01:03 UTC, varunreddy03 requested changes
Hi I have tried to test this PR but the frontend of the PR has Failed to compile and it is giving  an error. I have attached screenshot for your reference.

![Screenshot 2024-08-10 200158](https://github.com/user-attachments/assets/3e24c51f-030a-4c31-b1c9-e14cfdcf31e9)

2024-08-14 07:18 UTC, Lemonnycodes commented
Hi Anand,

I verified the PR and it works as mentioned in the description 

1.  Attempted to submit without a link, and the appropriate error message was displayed.
2. Tested various invalid links (e.g., without https://, incomplete URLs, non-URLs) and confirmed that they were correctly rejected.
3.  Confirmed that after closing and reopening the modal, previous errors were not persisted, and the modal worked as expected.
![Screenshot 2024-08-13 235740](https://github.com/user-attachments/assets/fbf9b816-e071-4e18-a93b-fb9fdcb83954)
![Screenshot 2024-08-13 235802](https://github.com/user-attachments/assets/8852ac36-0542-4447-b26c-e498ed5ddd56)
![Screenshot 2024-08-14 000401](https://github.com/user-attachments/assets/ff8e8187-e2b0-423f-b1c5-8ba93b9b269a)

 Encountered an issue where the project failed to compile due to a file naming mismatch: RoleInfoModal.jsx was expected, but the file was named 'roleInfoModal.jsx' on disk. Resolved the issue by renaming the file to 'RoleInfoModal.jsx' to match the expected casing. After addressing the file naming issue, the PR works as intended.
 
![error](https://github.com/user-attachments/assets/5204ed52-4831-425a-bd0f-a60e49652ca2)

2024-08-18 00:09 UTC, adityasure9 approved these changes
This PR effectively implements the required link validation and handles all edge cases as expected. 

![image](https://github.com/user-attachments/assets/06ace4a6-cbf8-4bd9-8d25-f9aed7c00568)

2024-08-19 05:22 UTC, Lemonnycodes approved these changes

2024-08-25 04:13 UTC, oliviahyw requested changes
Hi @anandsesha I have tested this PR and I got this error. Please check the screenshot attached.
<img width="951" alt="PR2185" src="https://github.com/user-attachments/assets/504d5f87-4e2c-473b-aa71-35506365ae27">

2024-09-06 17:21 UTC, FayeLV commented
Hi,
Great job, all tests have passed, but I found a small issue when I first opened the project and a compilation error occurred. I changed **roleInfoModal**.jsx to **RoleInfoModal**.jsx, and the project ran successfully. Other team members have also reported this issue, and the error still persists.
**Without entering a link:** The system correctly shows an error message stating that a link is required.
**Invalid links:** The system rejects links that are missing a protocol, incomplete, lacking a top-level domain, or containing spaces, special characters, or an incorrect protocol. Appropriate error messages are displayed.
**Valid links:** The system successfully accepts and submits links with https://  protocols.
**Error message persistence check:** After closing the modal, the error message does not persist when reopening it, and the modal resets correctly.
![Snipaste_2024-09-06_12-14-06](https://github.com/user-attachments/assets/27c00ab0-7cb0-4533-ac1d-8600b5acb372)
![1](https://github.com/user-attachments/assets/1cd5cd47-6695-44a7-a53b-8aea96ee9eb7)
![Snipaste_2024-09-06_12-09-31](https://github.com/user-attachments/assets/9c63caf8-2ebc-4c83-b553-8cbf13a7dd1d)
![Snipaste_2024-09-06_12-09-42](https://github.com/user-attachments/assets/91c2225f-9b69-4b6c-8cd0-0f2fbc0f99f2)
![Snipaste_2024-09-06_12-09-56](https://github.com/user-attachments/assets/4f1a8efd-bd67-4cba-8e3e-25e56202fa93)
![Snipaste_2024-09-06_12-10-07](https://github.com/user-attachments/assets/05d3ab3b-1df5-4ba7-a444-d120543167a6)
![Snipaste_2024-09-06_12-10-19](https://github.com/user-attachments/assets/b5a8e209-3254-4963-a7db-3094f43a3e71)
![Snipaste_2024-09-06_12-10-38](https://github.com/user-attachments/assets/f3d41ec8-a52a-494d-9f63-1437f2ec921c)
![Snipaste_2024-09-06_12-11-22](https://github.com/user-attachments/assets/3d962434-005e-465b-843e-a7136dde543f)

2024-11-11 00:19 UTC, closed without merging