Gayathri users enddate moreaccurate
OneCommunityGlobal/HighestGoodNetworkApp pull request #2196
Opened 2024-04-26 05:21 UTC by Gayathr-2012

# Description
Make a user’s end date more accurate  
If a person stops working without notice, or is activated and deactivated at some point in the future, their end date is the day I deactivate them. This is not accurate. A person’s end date should be the last week they contributed hours. 
Making a person inactive should have the software check for the last week they contributed hours and set the last day of that week as their end date. 
This should be reflected in these 3 areas:
Profile Page
Reports → Reports → People → Their report page
Other Links → User Management page
I’d also like Owners/Admins to be able to edit a person’s last day from their Profile page

## Related PRS (if any):
To test this backend PR you need to checkout latest branch frontend PR.
…

## Main changes explained:
Implemented accurate end date calculation functionality in the Frontend and integrate it into the User Management and profile pages, as well as the People report's page. Thoroughly test the accuracy of the implementation..

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/ owner user
5. go to Other Links→ User Management Page 
6. Profile Pag
7. Reports → Reports → People → Their report page

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/bf9d619a-724d-44de-921e-7912caecb254

![dateAccurate-2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/f8f65b16-47d8-45a6-9995-06509282a10a)
![dateAccurate-3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/ac8bd65b-8444-453d-8701-4a8c6fa83a5a)
![dateAccurate-4](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/ed4da6a4-d726-402d-969f-9d6c660617ee)
![dateAccurate-5](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/442559a1-f7a2-4c3f-bbbc-b0c56954d37e)

## Note:
Include the information the reviewers need to know.
If the person has tasks assigned, you can see their end date; otherwise, you will see "N/A". The end date displays as Saturday of that week. You need to ensure that the user has both Tasks and Time Logs entries.

2024-04-26 18:49 UTC, cgomezhub commented
Hi,
I have been checking it. I can see the user inactive in the report but not in the other links

![Screenshot 2024-04-26 100651](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/6baa167e-d796-464d-b936-ad3394e8634a)
![Screenshot 2024-04-26 143324](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/a10225b7-f158-438e-9a02-7a8eec002ed7)
![Screenshot 2024-04-26 144002](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/29cf8c7a-1e2f-41e4-8624-6fb1c46131e0)
![Screenshot 2024-04-26 144023](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/f22ee4c8-c309-4d08-ac29-0e2000150440)
![Screenshot 2024-04-26 144207](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/215546d7-32ea-4b51-aab8-fa5a141975e6)

2024-04-26 19:21 UTC, Gayathr-2012 commented
Hi Carlos Gomez,
First, you need to add a Time log for your account, then only you can see your end date. (Tasks and Timelogs) I have added it for you and included a screenshot for your clarification. If the person does not have a last contributed time entry, it won't show the End Date.
Click clock image 
<img width="1223" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/0d5e0ed7-9064-4cf9-b6ee-3184c1a15a6e">

<img width="1182" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/9003a0fa-bc43-4d7d-b497-679c8d4ccf81">

<img width="934" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/d0c17717-5a79-4c0f-826e-168871842921">

<img width="1280" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/6ccbc934-70f9-404f-ad28-6e291df83883">
<img width="1229" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/a97ca580-de0e-4668-a0a8-5c022199c345">
<img width="1174" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/14cf0236-da33-4440-a28f-e87b9983f7b0">

<img width="1244" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/e41eb417-81d7-4699-880f-1cb9be930bad">

2024-04-26 22:45 UTC, hbodgal approved these changes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/084f0aa8-124d-457e-85b8-a37e7573c9cd)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/0209ff03-a1e1-4bd9-86e6-0ee4fd9fb28d)

Everythins looks great. Funtionality works as intended.

2024-04-27 06:40 UTC, aaryaneil approved these changes
There are some issues with this PR:
1. The end date isn't showing up as today's date when the user has been deactivated.
2.  The end date is off by a date in the profile section
![Screenshot 2024-04-27 at 1 25 09 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/bc6e6fff-1b77-45d8-95da-df7e489c673c)
![Screenshot 2024-04-27 at 1 25 31 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/4e052e7c-9f7b-4222-8686-cc41764ffe2e)
![Screenshot 2024-04-27 at 1 25 49 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/598aefae-4a12-4e64-ac2e-bfcac58b8981)
![Screenshot 2024-04-27 at 1 28 00 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/10dbae94-363e-4c81-a6f1-0e1a67256244)

2024-04-27 06:42 UTC, aaryaneil requested changes
There are some issues with this PR:

The end date isn't showing up as today's date when the user has been deactivated.
The end date is off by a date in the profile section

![Screenshot 2024-04-27 at 1 25 09 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/0bd16e80-c71f-4ef6-8815-7c0e5f533b0a)
![Uploading Screenshot 2024-04-27 at 1.25.31 AM.png…]()

2024-04-27 17:54 UTC, cgomezhub reviewed
The PR is working, but  I've identified an inconsistency in the end date displayed across different pages. Here's a breakdown of the discrepancies:

User manager page: Shows end date: 19/04/24
Report page: Shows end date: 19/04
Profile page: Shows end date: 19/04 at the beginning and 20/04 in the middle

It would be great to have just one end date.
![Screenshot 2024-04-27 130859](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/bbf7bf5f-a85f-4472-8c2b-d2899bb053c5)
![Screenshot 2024-04-27 131014](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/5c679bd2-ec4e-46d3-b57b-41f6e4c63980)
![Screenshot 2024-04-27 131054](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55204862/51c03bef-9288-4500-ac92-81349443690e)

2024-05-16 13:18 UTC, nathcarnevalli approved these changes
Worked as expected for me and I didn't find any error. Nice job :)
![Screenshot 2024-05-16 095344](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/21bae814-a479-46ad-82a1-56e58cb772f0)
![Screenshot 2024-05-16 095403](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/3f07ea94-7e3d-4c05-8ebf-183491f3ff86)
![Screenshot 2024-05-16 095435](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/c09e9e68-7a99-44e6-9a28-1a827c4b29d7)
![Screenshot 2024-05-16 095744](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/1db9fbac-f799-49e9-8cee-2af1dd2cd8fd)
![Screenshot 2024-05-16 095923](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/a4c3eeeb-2c74-4975-b703-cd3c6bda254b)

2024-05-25 02:50 UTC, peter6866 requested changes
The end date is still N/A even if I have added a time entry in the timelogs, and the end date in the reports page is still the day of deactivation. 
<img width="1105" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/1ea024a9-c6ad-417b-a7bd-8d311815c08f">
<img width="1879" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/112b7cca-0f40-4eb6-92dd-7453d86d0179">
<img width="571" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/bf3f0fa0-3db8-4103-99bd-1a2403768858">

2024-05-26 02:54 UTC, Sandhya1236 approved these changes
I checked out the current branch, ran npm install and npm run start:local to set up the PR locally, and cleared the site data/cache. I logged in as an admin/owner user and navigated to Other Links → User Management Page, Profile Page, and Reports → Reports → People → Their Report Page. I verified the implementation of the accurate end date calculation functionality in the Frontend and confirmed its integration into the User Management, profile pages, and People report's page. After thorough testing, I confirmed the accuracy of the end date calculations. All steps were followed successfully, confirming that the new feature works as intended.



![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/e8d1cac2-e02d-47fb-b3ef-a79293fddf18)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/31fa4859-3028-4b84-913c-30f614474393)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/5ae48443-1445-4b43-b8ac-bec6d7390da5)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/9d81219a-709d-4b9a-9c9a-8a35b8ecfaa2)

2024-05-30 21:59 UTC, KyreneAF requested changes
- There is some unexpected behavior when using the status pause button on the profile page. It causes you to add a end date and after selecting one whenever inactivating a user it will save that date.
- It also does not change to inactive on the reports > reports page. It will change after reset.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/129882345/52f91a4a-1998-4be8-ab2a-2185f68ceb66

2024-06-01 06:49 UTC, Kavil-Jain-514 requested changes
I am facing many issues while reviewing this PR.
So when I made a user inactive, the end date and start date are different in different places in the user management and reports page it shows correct date but in user profile page the start date and end date is changed.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/d8be4188-688a-44ab-ab91-d1db4136e356)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/22326587-f9f8-4b77-9b55-d1045f78370b)

Wrong dates in the user page
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/ed378a84-6914-4244-8d17-0872d30d2bb9)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/f6b8279c-a7a8-412a-9e64-c437b01c5562)


I tested with different account and I faced a new issue. The end date is not reflected in the user profile page but the details are perfect in user management page.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/23ac46ee-3f53-41ce-b8fd-76e4b4fd6b5d)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/babbfd97-0b83-4aa3-84e4-c43688f3d377)
And in the reports page the dates are displayed wrong
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/896dd853-dcfa-4f21-a8ea-2a151b25a29d)

2024-06-06 18:00 UTC, JatinAgrawal94 requested changes
A user has time logged in already in the current week, still the end date shows to be "N/A". Consider the video for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/a2cae3b3-83d7-4d51-8577-26bf509230ed

2024-06-06 23:45 UTC, nishithaShetty commented
HI Gayatri, Nice job! The PR works as expected.
- I added a time entry and was able to deactivate the user.
- I was able to see the end date on the list page, the profile page (in the Volunteering and Basic Information tabs).
- I was also able to see the end date in the Reports tab
I have added the screenshot below
<img width="515" alt="PR#2196_1" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/06f83aaf-6488-4bf2-af31-1dd66c8d1000">
<img width="923" alt="PR#2196_2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/1661f456-3d36-4768-8bb5-1060804e9343">
<img width="934" alt="Pr#2196_3" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/545aaf85-523e-4c46-bef5-1bd0d0d39945">
<img width="942" alt="PR#2196_4" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/52f59f79-beef-48ad-9f92-bdb18e9312e4">
<img width="949" alt="PR#2196_5" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/d8d34963-267a-47eb-b913-d4c6d6f29f37">
<img width="519" alt="PR#2196_6" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/3ca33942-14c8-4239-9a07-9e2fc8be452e">

2024-06-12 21:28 UTC, KyreneAF approved these changes

2024-06-13 15:20 UTC, TXMO-dev approved these changes
Using the moment plugin, the users enddate has become more accurate after running this branch locally, great implementation.

2024-06-18 03:41 UTC, Sudershhh requested changes
The Inactive end User functionality is not working.
I made a volunteer user inactive. The status was not reflected in the User Management page and their profile page.

![PR 2196 - 2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59435391/110c8815-68b7-45d7-af94-3b6812a45ae2)

![PR 2196](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59435391/86b29151-1282-48b9-a951-8ad0143dcdaa)

2024-07-06 00:44 UTC, IchinnorovTuguldur commented
Hello Gayathri,

looks like you have already fixed the issues mentioned above. It works as expected now.
<img width="1211" alt="Screenshot 2024-07-05 at 5 43 30 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54337205/8fe63aef-0e0d-4915-9a3f-9de19eba91b2">

2024-07-10 20:21 UTC, Shadhrush5 approved these changes
Hi, I reviewd PR 2196 and I followed the below steps:
I checked out the branch "Gayathri_users_enddate_moreaccurate", ran npm install and npm run start:local to set up the PR locally, and cleared the site data/cache. I logged in as an admin user and navigated to Other Links → User Management Page, Profile Page, and Reports → Reports → People → Their Report Page. 

<img width="1728" alt="Screenshot 2024-07-10 at 1 13 08 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/119898772/cbed5fb7-1b66-4d0c-8e0a-9e3377c10779">
<img width="1728" alt="Screenshot 2024-07-10 at 1 13 35 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/119898772/3f8e9aac-8de8-494f-aa5b-d5d19a8d1aee">
<img width="1557" alt="Screenshot 2024-07-10 at 1 15 06 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/119898772/8f8eab1b-4f8a-4b83-aaa5-9d5feaf87332">
<img width="1557" alt="Screenshot 2024-07-10 at 1 17 12 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/119898772/32b06dde-e22e-4dc6-af92-1ec043b66727">

I verified the accurate end date calculation functionality in the frontend and confirmed its integration into the User Management, profile pages, and People report page. After thorough testing, I confirmed the end date calculations were accurate. All steps were completed successfully, confirming that the new feature works as intended.

2024-07-11 19:45 UTC, vishavk1992 approved these changes
I have tested this PR and it works as expected. i also attached a video for your reference


https://github.com/user-attachments/assets/0821f96b-aebf-4ec1-bd3a-9f89ae195866

2024-07-13 21:22 UTC, AnujVakil approved these changes
I have tested this PR and working as expected.
<img width="1435" alt="PR #2196_1" src="https://github.com/user-attachments/assets/239f2c0a-062e-4938-b7f3-761efcf9aa6b">
<img width="1436" alt="PR #2196_2" src="https://github.com/user-attachments/assets/9c92fbce-e0b4-4e54-bd17-3716d0169f11">
<img width="1432" alt="PR #2196_3" src="https://github.com/user-attachments/assets/d1177429-3225-40ce-8344-9b47bfbc6fa5">
<img width="1430" alt="PR #2196_4" src="https://github.com/user-attachments/assets/81d8ebad-dcc4-432a-ba6c-d5360922373a">

2024-07-14 02:18 UTC, DiyaWadhwani requested changes
Hi Gayathri,
I tried testing out your PR and as per your notes, created a new task and assigned it to a few users. The end date still shows as N/A in this case. I tried logging in time but none of the projects/tasks are loading for me to log time.
I have attached screenshots below. Kindly review this and make the necessary changes or let me know if there is something else I must be doing to test this PR.
Thank you

![2196](https://github.com/user-attachments/assets/1a71a0f6-d202-477e-bfbd-d6860de06415)

2025-11-12 04:21 UTC, closed without merging