Nahiyan_Fixed Header UI
OneCommunityGlobal/HighestGoodNetworkApp pull request #2212
Opened 2024-04-28 16:05 UTC by Nahiyan-16

# Description
Fixed header UI by centering timer and hiding elements based on screen width

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
- Centered timer
- Font size decrease for timer
- Hiding clock icon when under 530px width
- Hiding owner message when between 1400px and 1700px

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard
6. verify that header UI is working properly from all viewports (300px and up)
7. Make sure there are no overlaps or items going out of view

## Screenshots or videos of changes:
Before: 
<img width="228" alt="Screenshot 2024-04-28 at 12 00 47 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/a9df73a7-9c8d-4838-b2b7-b23e71075a84">
<img width="768" alt="Screenshot 2024-04-28 at 12 01 38 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/f3a197b3-2efd-4121-b5ed-1bb5d854ab14">
<img width="234" alt="Screenshot 2024-04-28 at 12 02 22 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/b7964131-d935-44bf-a9b1-f953d9e92fda">

2024-04-29 12:56 UTC, linkhanthtel submitted a review, later dismissed
New UI looks good to me! Clock icon is hidden under 530px and no components are overlapped! Nice work!

<img width="1440" alt="#2212 (2)" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/85d53ae8-99ee-4cae-9347-c5d0fddf65e8">
 

<img width="1440" alt="#2212" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/fcd8ac1b-b3c7-495e-adcc-521de4443997">

2024-04-29 14:33 UTC, MinSun0814 approved these changes, later dismissed
New UI looks clean! Text is successfully hidden when resizing the window and clock icon is hidden.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/938dee67-d533-4c2e-b76f-72df07578a8c)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/7f011f42-81f5-4389-9952-bbe56a47c7de)

2024-05-04 03:27 UTC, hbodgal approved these changes, later dismissed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/c206b35b-f86f-41fd-88f0-c737f3d79c4f)

Everything works fine at different viewports.

2024-05-04 06:13 UTC, dkn6 requested changes

2024-05-04 06:13 UTC, dkn6 commented on src/components/Timer/Timer.module.css
> +  .btnDiv{
Thank you for the excellent work! 
Nits: Have you run Prettier?

2024-05-11 19:16 UTC, dkn6 reviewed
@Nahiyan-16
I think the update has not been pushed yet.
Could you please check it?

2024-05-15 15:28 UTC, Nahiyan-16 commented
> @Nahiyan-16 I think the update has not been pushed yet. Could you please check it?

I'm not too sure what changes you are requesting. Can you please clarify?

2024-05-16 20:02 UTC, dkn6 commented on src/components/Timer/Timer.module.css
> +}
> > @Nahiyan-16 I think the update has not been pushed yet. Could you please check it?
> 
> I'm not too sure what changes you are requesting. Can you please clarify?

Sure! If Prettier has been successfully executed, the code would look like this.
```suggestion
@media (max-width: 530px) {
  .btnDiv {
    display: none;
  }
}
```

2024-05-17 19:09 UTC, dkn6 approved these changes

2024-05-21 17:06 UTC, one-community commented
Thank you all, merging!

2024-05-21 17:08 UTC, merged