Nahiyan_Dark mode on all modal in User Management
OneCommunityGlobal/HighestGoodNetworkApp pull request #2238
Opened 2024-05-08 17:01 UTC by Nahiyan-16

# Description
All modals are now fully integrated with dark mode on the user management page

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- All modals have dark mode

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other Links -> User Management
6. verify all modals are working properly. 

## Screenshots or videos of changes:
![Screenshot 2024-05-08 130011](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/e6586f50-6539-4bbe-94c6-ca967ce0b102)
![Screenshot 2024-05-08 130034](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/498b1a22-9716-4a90-a6a4-e32954e3c99b)

2024-05-08 23:37 UTC, Ramaruva requested changes
Hi @Nahiyan-16  I have checked all modal in user management page all modals are in dark mode except for the change password modal I am not sure whether the change password have darkmode or not?
![image]

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/eaca57f3-f149-4d96-88e5-0031fa0874fa

(https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/b92c80de-c84e-47ff-8fdd-d8496c6b2ce2)

and also I have one suggestion that can we make this icon "X" has white in dark mode instead of black because as a user I feel I am unable to see properly  "X" icon in dark mode

2024-05-09 05:16 UTC, MinSun0814 submitted a review, later dismissed
The updated dark mode looks fantastic and aligns with the aesthetic of the application. Nice work!
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/b7b873dd-c8a8-4fd3-a9b5-b24e276a11e7)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/7f33d52e-4ab8-48b5-9ed2-b6d72dc89bfa)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/06594fec-d017-4c2c-b365-8ba38d267666)

2024-05-09 14:55 UTC, linkhanthtel submitted a review, later dismissed
I reviewed your PR and all modals are working properly. Nice work! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/e314b610-75b3-4ae1-93e7-6bcb2df94751

2024-05-09 17:09 UTC, Nahiyan-16 commented
> Hi @Nahiyan-16 I have checked all modal in user management page all modals are in dark mode except for the change password modal I am not sure whether the change password have darkmode or not? ![image](https://private-user-images.githubusercontent.com/64008831/329082258-af999cc6-a9a6-4652-aa3d-336de85dae75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzQ3NDgsIm5iZiI6MTcxNTI3NDQ0OCwicGF0aCI6Ii82NDAwODgzMS8zMjkwODIyNTgtYWY5OTljYzYtYTlhNi00NjUyLWFhM2QtMzM2ZGU4NWRhZTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE3MDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZDQyZWI5NTU2MGE4Y2E4N2ZiZmRmNTZjZWVjNTc4NzdmODMwMzZlOGVmMDYxNDc1MzY2YTM2Mzg5Zjc0MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G7rFdqjtg6KBq-Mzvc1rZlutLJcRMDKvxEIYLkorce0)
> 
>  usermodel.mp4 
> (https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/b92c80de-c84e-47ff-8fdd-d8496c6b2ce2)
> 
> and also I have one suggestion that can we make this icon "X" has white in dark mode instead of black because as a user I feel I am unable to see properly "X" icon in dark mode

Fixed the issue regarding dark mode on password modal and added new custom header with the X mark being able to toggle from light to dark

2024-05-09 22:31 UTC, Ramaruva commented
> > Hi @Nahiyan-16 I have checked all modal in user management page all modals are in dark mode except for the change password modal I am not sure whether the change password have darkmode or not? ![image](https://private-user-images.githubusercontent.com/64008831/329082258-af999cc6-a9a6-4652-aa3d-336de85dae75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzQ3NDgsIm5iZiI6MTcxNTI3NDQ0OCwicGF0aCI6Ii82NDAwODgzMS8zMjkwODIyNTgtYWY5OTljYzYtYTlhNi00NjUyLWFhM2QtMzM2ZGU4NWRhZTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE3MDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZDQyZWI5NTU2MGE4Y2E4N2ZiZmRmNTZjZWVjNTc4NzdmODMwMzZlOGVmMDYxNDc1MzY2YTM2Mzg5Zjc0MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G7rFdqjtg6KBq-Mzvc1rZlutLJcRMDKvxEIYLkorce0)
> > usermodel.mp4
> > (https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/b92c80de-c84e-47ff-8fdd-d8496c6b2ce2)
> > and also I have one suggestion that can we make this icon "X" has white in dark mode instead of black because as a user I feel I am unable to see properly "X" icon in dark mode
> 
> Fixed the issue regarding dark mode on password modal and added new custom header with the X mark being able to toggle from light to dark

Hi I verified the latest changes now I am able to see dark mode for reset password modal great work on the X  mark also
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/b0d05074-cf0d-4dbc-a5e7-1474c2633269)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/4a2d2ba8-3b65-44aa-bbe9-c77d20b6acd3)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/63fb05cc-7de9-47e0-9d00-72a44ff255c5)

2024-05-09 22:31 UTC, Ramaruva submitted a review, later dismissed
latest changes are working

2024-05-10 20:14 UTC, ZhangPeizhou commented
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/6575370a-00c2-4c08-9a93-783035d1f292

Everything works as expected, nice work!

2024-05-10 20:17 UTC, ZhangPeizhou commented
I want to mention that when I click to view a user profile, it automatically switches to light mode, and I have to switch it back manually. I am not sure if it needs to be fixed here or not, just let you know.

2024-05-11 04:30 UTC, nathcarnevalli approved these changes, later dismissed
The Dark mode worked as expected in User Management

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/01cebc5a-6119-4b66-8781-2fb0dc7f555a

2024-05-11 06:40 UTC, hbodgal submitted a review, later dismissed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/dd4e534d-8e9d-44ea-b482-ade9c846ce43)

it works well.

2024-05-12 04:09 UTC, abdel-lall commented on src/components/UserManagement/logTimeOffPopUp.jsx
> -  ModalHeader,
This error was caused by the deletion of this import.
![Screenshot 2024-05-11 230729](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/404311cd-b438-41e7-9622-e330181a2707)

2024-05-12 04:11 UTC, abdel-lall requested changes
The Edit time-off request modal do not change color in dark mode.

![Screenshot 2024-05-11 230639](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/c3cc69ed-c0b3-43c7-8747-70df652f1866)

2024-05-14 20:01 UTC, cgomezhub approved these changes
well done!
All the popups works in dark mode.

https://www.loom.com/share/e8e1cd66176143be8c7f11b8f7a63e19?sid=467ac1c1-95ef-4bdb-afb6-f5f7c9a34f57

2024-05-18 18:34 UTC, sucheta90 reviewed
Hello @Nahiyan-16,

After reviewing this PR, I see the feature works as expected. Please refer to the video. However, I noticed that refreshing the page resets the dark mode back to light mode. Is this the intended behavior?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/75114daa-5e92-4c02-9300-98ab39f53659

2024-05-20 15:01 UTC, Nahiyan-16 commented
> Hello @Nahiyan-16,
> 
> After reviewing this PR, I see the feature works as expected. Please refer to the video. However, I noticed that refreshing the page resets the dark mode back to light mode. Is this the intended behavior?
> 
>  PR2238_review.mov

No this is not the intended behavior and will be dealt with in another PR.

2024-05-21 14:20 UTC, peter6866 approved these changes
All modals in user management work great in dark modal. 
<img width="716" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/6eebc98f-0d57-4ba7-8d89-bbce205122bc">
<img width="719" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/d3e4f096-0a28-48ed-88ca-76f977b04949">
<img width="445" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/129b7b2e-d318-434f-a471-82e846a29de5">
<img width="448" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/0f0f188e-984f-4264-8927-cb27935a2905">
<img width="448" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/f98a285c-23c7-4d18-82e4-060e0ec3552c">

2024-05-21 17:07 UTC, one-community commented
Thank you all, merging!

2024-05-21 17:07 UTC, merged