Sucheta - Improved Add_New_Task Modal Format
OneCommunityGlobal/HighestGoodNetworkApp pull request #2244
Opened 2024-05-10 19:36 UTC by sucheta90

# Description
(PRIORITY HIGH) Jae: Improve “Add New Task” modal format
- Make Task Name box bigger
- Fix Status Section so everything fits on 2 lines
- Fix hours input width so up to a 4-digit number will show
- [Video clarification](https://www.loom.com/share/80b70f2750ad4f00abee0d6fdeeca4f9?sid=8f6037a8-169b-4b97-bf79-39051f93fea3)

## Related PRS (if any):
None

## Main changes explained:
- Changed html tags in `AddTaskModal.jsx` , from `<tr>` to `<div>` and `<td>` to `<span>` for the form labels and input fields
- Adds css classes to the style the `<div>` and `<span>` elements.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Projects → WBS -> Tasks -> Add Task
6. The input fields now take more space than the labels.

## Screenshots or videos of changes:
Before the change: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/2482fa39-6d7c-4078-ab7f-b2fab529aa2c

After the change: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/91fc9ee0-bc4a-40bc-8eeb-cc519e70eaef

## Note:
Extended version of
- [PR2167](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2167)
This PR resolved a bug , please refer to the picture below:
<img width="416" alt="Screenshot 2024-04-26 at 1 36 24 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/4b423b82-68db-4fae-8008-9c5499534a05">
- [PR2198](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2198), implemented style classes as suggested in the code reviews.
PLEASE NOTE: This PR does not change or debug any functionality issues related to this modal. This PR only fixes the css format.

2024-05-11 03:11 UTC, hbodgal approved these changes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/c82f5f81-f9ec-4da9-bebc-3c9436c99ee7)

Yes. labels are shorter than Input size as needed.

2024-05-11 03:33 UTC, nathcarnevalli reviewed
I wasn't able to get into the task as Admin or Owner. What's the problem?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/419cac5e-dc4f-4c61-ad6f-6610e9fdc8ef

2024-05-11 17:42 UTC, abdel-lall approved these changes
LGTM. Nice job!

2024-05-11 18:40 UTC, MinSun0814 approved these changes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/cef4a9ba-827b-4ce6-bb73-c1184073cdae)
New UI looks clean even when I try to resize the window. Nice work!

2024-05-11 21:24 UTC, sucheta90 commented
> I wasn't able to get into the task as Admin or Owner. What's the problem?
> 
>  HGN.APP.-.Google.Chrome.2024-05-11.00-21-50.mp4

Hello  @nathcarnevalli , please refer to the After Change video. This should reflect the recent changes.

2024-05-11 21:36 UTC, KaushikMreddy requested changes
Hi @sucheta90 , 

The Add New Task Modal looks great now, much better alignments and look, just needs a small fix.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/7e1f0cf1-38c2-4d91-a58c-0254918a5ec5)

The status box, the "Complete radio button" is not aligned with the one above it, if that can be added it'd be great. Thanks

2024-05-13 11:52 UTC, nathcarnevalli approved these changes
Now it worked :)

2024-05-14 20:31 UTC, cgomezhub requested changes
For some reason when I click on the task the app redirects me to /dashboard, please check it and let me know.

https://www.loom.com/share/3197f4d5d670483f81c041a889cdc1c8?sid=87703286-0db1-4387-824e-7cbe55573609

2024-05-15 01:48 UTC, nishithaShetty commented
Nice job, Works as expected.
<img width="358" alt="PR_2244_Status" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/f2141a47-faba-4c7a-8737-871f0ad2ec2d">
<img width="368" alt="PR_2244_Task_name" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/b4b654e1-3bc3-4387-b2f9-3bdfea37284f">
<img width="364" alt="PR_2244_time_width" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/45bb81bd-e758-4979-96b5-6ad96607b56b">

2024-05-16 04:03 UTC, Sandhya1236 commented
Failed to compile.

Module not found: Error: Package path ./dist/d3.min is not exported from package D:\HighestGoodNetworkApp\node_modules\d3 (see exports field in D:\HighestGoodNetworkApp\node_modules\d3\package.json)
ERROR in ./src/components/Reports/InfringementsViz.jsx 6:0-37
Module not found: Error: Package path ./dist/d3.min is not exported from package D:\HighestGoodNetworkApp\node_modules\d3 (see exports field in D:\HighestGoodNetworkApp\node_modules\d3\package.json)

ERROR in ./src/components/Reports/TeamReport/components/TeamReportCharts.jsx 8:0-37
Module not found: Error: Package path ./dist/d3.min is not exported from package D:\HighestGoodNetworkApp\node_modules\d3 (see exports field in D:\HighestGoodNetworkApp\node_modules\d3\package.json)

ERROR in ./src/components/Reports/TeamReport/components/TeamsReportCharts.jsx 8:0-37
Module not found: Error: Package path ./dist/d3.min is not exported from package D:\HighestGoodNetworkApp\node_modules\d3 (see exports field in D:\HighestGoodNetworkApp\node_modules\d3\package.json)

ERROR in ./src/components/Reports/TimeEntriesViz.jsx 6:0-37
Module not found: Error: Package path ./dist/d3.min is not exported from package D:\HighestGoodNetworkApp\node_modules\d3 (see exports field in D:\HighestGoodNetworkApp\node_modules\d3\package.json)

ERROR in ./src/components/Reports/TotalReport/TotalReportBarGraph.jsx 6:0-37
Module not found: Error: Package path ./dist/d3.min is not exported from package D:\HighestGoodNetworkApp\node_modules\d3 (see exports field in D:\HighestGoodNetworkApp\node_modules\d3\package.json)

ERROR in ./src/components/SetupProfile/SetupProfileUserEntry.jsx 512:31-39
Should not import the named export 'tokenKey' (imported as 'tokenKey') from default-exporting module (only default export is available soon)

ERROR in ./src/components/common/PieChart/PieChart.jsx 7:0-37
Module not found: Error: Package path ./dist/d3.min is not exported from package D:\HighestGoodNetworkApp\node_modules\d3 (see exports field in D:\HighestGoodNetworkApp\node_modules\d3\package.json)

ERROR in ./node_modules/hoek/lib/index.js 4:15-32
Module not found: Error: Can't resolve 'assert' in 'D:\HighestGoodNetworkApp\node_modules\hoek\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }

ERROR in ./node_modules/hoek/lib/index.js 5:15-32
Module not found: Error: Can't resolve 'crypto' in 'D:\HighestGoodNetworkApp\node_modules\hoek\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }

ERROR in ./node_modules/hoek/lib/index.js 6:13-28
Module not found: Error: Can't resolve 'path' in 'D:\HighestGoodNetworkApp\node_modules\hoek\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

ERROR in ./node_modules/isemail/lib/index.js 5:13-28
Module not found: Error: Can't resolve 'util' in 'D:\HighestGoodNetworkApp\node_modules\isemail\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }

ERROR in ./node_modules/joi/lib/types/string/index.js 4:12-26
Module not found: Error: Can't resolve 'net' in 'D:\HighestGoodNetworkApp\node_modules\joi\lib\types\string'

ERROR in ./node_modules/joi/lib/types/symbol/index.js 4:13-28
Module not found: Error: Can't resolve 'util' in 'D:\HighestGoodNetworkApp\node_modules\joi\lib\types\symbol'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }

ERROR in ./node_modules/react-html-parser/node_modules/htmlparser2/lib/WritableStream.js 5:13-37
Module not found: Error: Can't resolve 'buffer' in 'D:\HighestGoodNetworkApp\node_modules\react-html-parser\node_modules\htmlparser2\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
        - install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "buffer": false }

ERROR in ./node_modules/safe-buffer/index.js 3:13-30
Module not found: Error: Can't resolve 'buffer' in 'D:\HighestGoodNetworkApp\node_modules\safe-buffer'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
        - install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "buffer": false }

webpack compiled with 15 errors




Can anyone help me with these errors


![Screenshot (685)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/094bf194-74a6-4319-afef-119b7e3b6ef3)

2024-05-18 11:36 UTC, sucheta90 commented
> For some reason when I click on the task the app redirects me to /dashboard, please check it and let me know.
> 
> https://www.loom.com/share/3197f4d5d670483f81c041a889cdc1c8?sid=87703286-0db1-4387-824e-7cbe55573609

Hello @cgomezhub , I just checked out to this branch on my local, however could not recreate the bug. Can you specify if this happens with a specific role? I tried with Owner's and Volunteer's role.

2024-05-18 11:42 UTC, sucheta90 commented
> Failed to compile.
> 
> Module not found: Error: Package path ./dist/d3.min is not exported from package D:\HighestGoodNetworkApp\node_modules\d3 (see exports field in D:\HighestGoodNetworkApp\node_modules\d3\package.json) ERROR in ./src/components/Reports/InfringementsViz.jsx 6:0-37 Module not found: Error: Package path ./dist/d3.min is not exported from package D:\HighestGoodNetworkApp\node_modules\d3 (see exports field in D:\HighestGoodNetworkApp\node_modules\d3\package.json)
> 
> ERROR in ./src/components/Reports/TeamReport/components/TeamReportCharts.jsx 8:0-37 Module not found: Error: Package path ./dist/d3.min is not exported from package D:\HighestGoodNetworkApp\node_modules\d3 (see exports field in D:\HighestGoodNetworkApp\node_modules\d3\package.json)
> 
> ERROR in ./src/components/Reports/TeamReport/components/TeamsReportCharts.jsx 8:0-37 Module not found: Error: Package path ./dist/d3.min is not exported from package D:\HighestGoodNetworkApp\node_modules\d3 (see exports field in D:\HighestGoodNetworkApp\node_modules\d3\package.json)
> 
> ERROR in ./src/components/Reports/TimeEntriesViz.jsx 6:0-37 Module not found: Error: Package path ./dist/d3.min is not exported from package D:\HighestGoodNetworkApp\node_modules\d3 (see exports field in D:\HighestGoodNetworkApp\node_modules\d3\package.json)
> 
> ERROR in ./src/components/Reports/TotalReport/TotalReportBarGraph.jsx 6:0-37 Module not found: Error: Package path ./dist/d3.min is not exported from package D:\HighestGoodNetworkApp\node_modules\d3 (see exports field in D:\HighestGoodNetworkApp\node_modules\d3\package.json)
> 
> ERROR in ./src/components/SetupProfile/SetupProfileUserEntry.jsx 512:31-39 Should not import the named export 'tokenKey' (imported as 'tokenKey') from default-exporting module (only default export is available soon)
> 
> ERROR in ./src/components/common/PieChart/PieChart.jsx 7:0-37 Module not found: Error: Package path ./dist/d3.min is not exported from package D:\HighestGoodNetworkApp\node_modules\d3 (see exports field in D:\HighestGoodNetworkApp\node_modules\d3\package.json)
> 
> ERROR in ./node_modules/hoek/lib/index.js 4:15-32 Module not found: Error: Can't resolve 'assert' in 'D:\HighestGoodNetworkApp\node_modules\hoek\lib'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to: - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }' - install 'assert' If you don't want to include a polyfill, you can use an empty module like this: resolve.fallback: { "assert": false }
> 
> ERROR in ./node_modules/hoek/lib/index.js 5:15-32 Module not found: Error: Can't resolve 'crypto' in 'D:\HighestGoodNetworkApp\node_modules\hoek\lib'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to: - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }' - install 'crypto-browserify' If you don't want to include a polyfill, you can use an empty module like this: resolve.fallback: { "crypto": false }
> 
> ERROR in ./node_modules/hoek/lib/index.js 6:13-28 Module not found: Error: Can't resolve 'path' in 'D:\HighestGoodNetworkApp\node_modules\hoek\lib'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to: - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }' - install 'path-browserify' If you don't want to include a polyfill, you can use an empty module like this: resolve.fallback: { "path": false }
> 
> ERROR in ./node_modules/isemail/lib/index.js 5:13-28 Module not found: Error: Can't resolve 'util' in 'D:\HighestGoodNetworkApp\node_modules\isemail\lib'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to: - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }' - install 'util' If you don't want to include a polyfill, you can use an empty module like this: resolve.fallback: { "util": false }
> 
> ERROR in ./node_modules/joi/lib/types/string/index.js 4:12-26 Module not found: Error: Can't resolve 'net' in 'D:\HighestGoodNetworkApp\node_modules\joi\lib\types\string'
> 
> ERROR in ./node_modules/joi/lib/types/symbol/index.js 4:13-28 Module not found: Error: Can't resolve 'util' in 'D:\HighestGoodNetworkApp\node_modules\joi\lib\types\symbol'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to: - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }' - install 'util' If you don't want to include a polyfill, you can use an empty module like this: resolve.fallback: { "util": false }
> 
> ERROR in ./node_modules/react-html-parser/node_modules/htmlparser2/lib/WritableStream.js 5:13-37 Module not found: Error: Can't resolve 'buffer' in 'D:\HighestGoodNetworkApp\node_modules\react-html-parser\node_modules\htmlparser2\lib'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to: - add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }' - install 'buffer' If you don't want to include a polyfill, you can use an empty module like this: resolve.fallback: { "buffer": false }
> 
> ERROR in ./node_modules/safe-buffer/index.js 3:13-30 Module not found: Error: Can't resolve 'buffer' in 'D:\HighestGoodNetworkApp\node_modules\safe-buffer'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to: - add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }' - install 'buffer' If you don't want to include a polyfill, you can use an empty module like this: resolve.fallback: { "buffer": false }
> 
> webpack compiled with 15 errors
> 
> Can anyone help me with these errors while trying to test these changes
> 
> ![Screenshot (685)](https://private-user-images.githubusercontent.com/79351059/331044389-094bf194-74a6-4319-afef-119b7e3b6ef3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMzAzMjEsIm5iZiI6MTcxNjAzMDAyMSwicGF0aCI6Ii83OTM1MTA1OS8zMzEwNDQzODktMDk0YmYxOTQtNzRhNi00MzE5LWFmZWYtMTE5YjdlM2I2ZWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDExMDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZGNiZTNiODQ1YzEwYzA4MmI1YjAwODA5ZjBhMGI4MGIyNWY2NTk1Yzc1ZTNlN2VjNjVjNTc2YzZhYjQ5NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CjilydfJ6x_LGpFR0og1ZdkLHVMLyPeXSQ5AcByfBeY)

Hello @Sandhya1236, this error seems unrelated to the PR. Please follow the steps to run the local environment. You may want to refer to slack [message](https://highest-good.slack.com/archives/CSCN20FA5/p1715975051791669?thread_ts=1715832605.573119&cid=CSCN20FA5)

2024-05-20 17:32 UTC, peter6866 commented
> For some reason when I click on the task the app redirects me to /dashboard, please check it and let me know.
> 
> https://www.loom.com/share/3197f4d5d670483f81c041a889cdc1c8?sid=87703286-0db1-4387-824e-7cbe55573609

Hi @sucheta90 , I have the same issue here with the admin role.

2024-05-23 23:52 UTC, closed without merging

2024-05-23 23:52 UTC, sucheta90 commented
This PR indeed had an error , due to which the project page did not work as intended. To make is work new changes have been made and a [new PR ](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2284)has been created.