initalscroollbar
OneCommunityGlobal/HighestGoodNetworkApp pull request #2249
Opened 2024-05-11 23:23 UTC by Gayathr-2012

# Description
(PRIORITY LOW) Sushmitha: Fix the design of the Projects/People/Teams page on the narrow screens (WIP Gayathridevi)
Right now, users might not realize results have appeared without scrolling down. Make it more obvious that the search has produced results.
	A. go to Reports→ Reports → Projects/People/Teams
	B. Narrow the screen
C. Type any letter in the search bar
Do not change how it works on large screens

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout latest Backend.
…

## Main changes explained:
- Reports.jsx functionality added.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin /owner user
5. go to Reports→ Reports → Projects/People/Teams	
6. B. Narrow the screen
7.Type any letter in the search bar)  ( When you click  Projects/People/Teams scroll down to the result page)

## Screenshots or videos of changes:
Before changes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/fd1fccad-7fd8-4ffb-ac3f-83b96c4ec07c)
After changes:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/c53461f4-219b-4564-9298-eede3374f51b)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/5df41772-f74f-4b3a-8d15-a0cd64141a6b)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/163784958/216e9210-7dee-4ec3-99b4-78d9f7de9a6e

## Note:
When it is narrow screen it will automatically scroll down

2024-05-14 13:30 UTC, nathcarnevalli approved these changes
Worked as expected :)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/39cccc49-205d-4246-962f-a4b156b85c84

2024-05-18 23:32 UTC, hbodgal approved these changes
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/8a8b9984-78a7-425a-96e2-dfb67ff567f6

It works well. When I clciked on Project/people/teams it scrolls down to make results visible.

2024-05-29 04:30 UTC, Sandhya1236 approved these changes
Upon reviewing the PR for fixing the design of the Projects/People/Teams page on narrow screens, I followed the testing instructions. I checked into the current branch, ran npm install, cleared the site data/cache, and logged in as an admin/owner user. I navigated to Reports → Reports → Projects/People/Teams, narrowed the screen, and typed a letter in the search bar. The changes ensure that users can now easily see that search results have appeared without needing to scroll down. The functionality remains unchanged on larger screens. All tests were successful, confirming the improvements in the user interface for narrow screens.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/7e0f2711-5af0-4509-9778-14ce793cc83b


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/a7d90229-3fda-43f7-a9d5-f9f37f590175

2024-06-07 05:33 UTC, JatinAgrawal94 requested changes
The feature works only in specific screen sizes. Consider the video where the page has similar arrangement, but the page doesn't move down on selecting project and other selections.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/1255dd35-5dc3-4130-b591-6b4a709338bb

2024-06-20 03:51 UTC, Sudershhh reviewed
The Scroll bar navigates to the list of users. Works as expected. The only thing that would be better is if it (the scroll bar navigation) is consistent across all screen sizes relative to the viewport size.

![PR 2249](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59435391/ce23bc3b-74f2-4b1d-902a-a26b1adba9c5)

2024-08-05 01:05 UTC, manikittu810 approved these changes
Hello @Gayathr-2012 
Everything is working good and as mentioned above. It is also working for any case, word search implementation is good.

https://github.com/user-attachments/assets/c63c26bd-366d-4372-817e-85773397cd2b

Thankyou.

2025-04-02 02:34 UTC, closed without merging