Dark mode on modal intagible time
OneCommunityGlobal/HighestGoodNetworkApp pull request #2267
Opened 2024-05-19 01:15 UTC by DaveB4r

# Description
Implemented dark mode on Add/Edit Intangible time modal.

## Related PRS (if any):
This frontend PR isn't related to any backend PR.
…

## Main changes explained:
- Dark mode on Add/Edit Intangible time modal.
- 
## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard…
6. Click on button Add Intangible Time Entry

## Screenshots or videos of changes:
![dark mode add intangible time](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117042123/cb85a777-79ed-4725-a60f-469a5d1b6a5a)
![dark mode edit intangible time](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117042123/5248caa4-d37b-401f-a0bd-b3dd6abe0510)

2024-05-19 02:03 UTC, MinSun0814 commented
I think other dark mode changes have white background for textbox I am not sure if you should align with that. Other than that it looks nice.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/f2128b64-56f2-4ba2-b787-93902c0575b1)

2024-05-19 03:43 UTC, aaryaneil reviewed
The changes look good and the text entry box look great.
<img width="960" alt="Screenshot 2024-05-18 at 10 42 40 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/4b2f2b4b-b98a-4b26-9088-f5f91946d431">

2024-05-19 07:49 UTC, hbodgal approved these changes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/7e177b1f-a61f-4a46-b7e2-22295e93674e)

looks good!

2024-05-19 12:22 UTC, dkn6 approved these changes
Thank you for your great work! LGTM

<img width="601" alt="add" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/168319518/5d4c679f-1f8d-4d68-a988-cd49470d9771">

<img width="558" alt="edit" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/168319518/e60df63d-fbd6-4abd-8a8f-4fe74afbd89a">

2024-05-21 06:56 UTC, cecilia-uu approved these changes
It looks good! 
<img width="1275" alt="截屏2024-05-21 下午2 55 41" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117628326/f6226ef9-d980-48da-9d5d-0bdb7949f0b7">

2024-05-21 13:00 UTC, linkhanthtel approved these changes
Nice work! It looks good to me! It would be much better if the text box is also light color in light theme.

<img width="1437" alt="Screenshot 2024-05-21 at 8 53 02 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/090a9adb-857a-4032-910f-b93f4753c8e5">


<img width="1438" alt="Screenshot 2024-05-21 at 8 51 35 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/bf2be6a5-6a86-4e49-96d1-ea88aee1a53d">

2024-05-22 01:04 UTC, peter6866 requested changes
Hi, there are some issues I found with the dark mode.
1. The requirement prompt text is hard to see due to the text color.
2. When changing back to light mode, the text field will remain in dark mode. 
<img width="457" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/7e7dd3c3-7c00-4a73-9b95-909cc1ac52ca">
<img width="453" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/72c4ec46-dfe1-494d-8bfa-a235f490ce7c">
<img width="441" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/b9d5626b-ca58-49d1-92e5-f506a710a73c">

2024-05-23 02:08 UTC, Sandhya1236 requested changes
Everything on the Add/Edit Intangible Time modal looks good in dark mode. However, when switched to light mode, the description box remains in dark mode, which looks a bit odd. Please check and address this issue if possible. I posted screenshots for you reference.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/d3b8d71d-d826-45e7-b2ae-871b52d23c15)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/3439ff26-f868-4f58-89fa-0e20eb6cb44a)

2024-05-23 09:21 UTC, beblicarl requested changes
This functionality works as intended in dark mode. However, it looks weird in light mode.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/3cffa4a8-a138-438b-bed2-bd0c2c61938a)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/24a64054-48ff-4a69-b8bd-0784cc4d74a7)

2024-05-24 09:21 UTC, Wenboooooo approved these changes
![1716542437771](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114895283/52c52369-4ed1-4686-b6e7-55b214ce5b1d)
Looks good to me, the functionality works.

2024-05-24 19:46 UTC, nathcarnevalli requested changes
It's not working properly when switching back to light mode.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/bfe1bd8f-5b42-40fd-beca-f34da5735947)

2024-05-25 08:28 UTC, Kavil-Jain-514 requested changes
Good work !! However, there are two changes that could make this feature more attractive.

In Light mode, the notes section is intially white but when the mode is switched to dark and again to light then the notes section still remains on dark mode.
Before:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/d1f643ee-d64c-4ae3-b662-206124ef8483)

After:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/cf9e513f-91af-4d1a-b1c3-057a164b7307)


Also, one suggestion
in the dark mode when Tangible check box is clicked the heading text of the Modal "Add Tangible Time Entry ", the color of the text Tangible is similar to dark mode color. Use a lighter color for the text to make it contrast.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/5596ddcf-653e-4644-a5bd-d2198911d8a2)
 "cyan" looks good.

2024-05-25 10:32 UTC, KaushikMreddy requested changes
Hi, your changes are working with 1 error and one change is needed

1. Please change the color of "Tangible", in dark mode it's not visible
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/cceb75af-edc0-429e-8332-d71eb4cdfc1c)
2. After changing the mode back to light after changing it to dark, this error appears. The text field remains dark.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/b4461f3c-5366-4de8-b420-1033199fd0ac)

2024-05-25 16:56 UTC, meetpadhiar4 requested changes
Hi, I reviewed your PR and it works as intended. But the placeholder text in the textbox is not readable in dark mode. Please refer the screenshot attached.
<img width="1440" alt="PR 2267" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/25edd87b-76b9-4520-8a67-ffdb0c7c03c3">

2024-05-25 23:21 UTC, deepthikannan approved these changes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83337914/3f50b9b0-4ee1-4e7d-b3fa-c108b7a7282f)
Functionality works for the Add intangible time in dark mode.

2024-05-26 01:00 UTC, jennZhang93 approved these changes
Everything looks good! 

Possible UI improvements: 
1. the placeholder text in Notes section has black color which is not readable with the dark mode. Consider making it white can be better. 
2. The info modal of the Time Entry is still white background. Not sure if this is intended.

<img width="630" alt="Screenshot 2024-05-25 at 8 56 27 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/5e4c481c-cbdc-4db1-a28d-bf403d290103">
<img width="773" alt="Screenshot 2024-05-25 at 8 56 42 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/a505983c-3bd0-4eaa-b248-60b7d5bcc46d">

2024-05-26 01:50 UTC, mohabbasd approved these changes
Hello, I tested your PR and it works perfectly as intended. Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/5eca9a8b-23fb-40a3-9efe-54db1a03b06c

2024-05-26 14:54 UTC, dikshitakejriwal commented
The changes work as expected and look good to me. The only suggestion I have here is to change both the info boxes shown in the picture to dark mode to make everything look consistent. 

<img width="1610" alt="Screenshot 2024-05-26 at 7 51 38 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62951992/e1bfd722-9adb-4f3a-a217-b9ff40084981">
<img width="1435" alt="Screenshot 2024-05-26 at 7 52 02 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62951992/dffb06a4-d0d3-4afe-a03c-3f53f00f04df">

2024-05-26 15:06 UTC, dikshitakejriwal approved these changes
The changes work as expected and look good to me. The only suggestion I have here is to change both the info boxes shown in the picture to dark mode to make everything look consistent. 

<img width="1610" alt="Screenshot 2024-05-26 at 7 51 38 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62951992/e1bfd722-9adb-4f3a-a217-b9ff40084981">


<img width="1435" alt="Screenshot 2024-05-26 at 7 52 02 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62951992/dffb06a4-d0d3-4afe-a03c-3f53f00f04df">

2024-05-30 02:15 UTC, closed without merging