Chris_spinning_wheel_date_change_reports
OneCommunityGlobal/HighestGoodNetworkApp pull request #2298
Opened 2024-05-30 06:04 UTC by chrischenlixing

# Description
The issue with the original pr is that when the date is changed, there isn't an indicator to show that the data is retrieved or not. With the spinning wheels added, it's going to spin until the newest data is ready and graph is rerendered.

## Related PRS (if any):
This pr is the minor patch for the functionality implemented on pr#2268
No backend pr related, for the backend just check-in to the development branch 

## Main changes explained:
- Added the state for "dataReady" and "setDataReady" for the spinning wheel of the total people report
- Added the state for "dataReady" and "setDataReady" for the spinning wheel of the total project report

## How to test:
1. check into current branch
2. do npm install and ... to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Reports →Reports → Projects/People/Teams
6. Click on ‘Show Total Project Report’, ‘Show Total People Report’, and ‘Show Total Team Report’ one by one
7. Change the end date to last year or any date you would want to test, see if there is a spinning wheel on there before the new report is shown for the new date

## Screenshots or videos of changes:
Before, when changing the date for People Report and Project Report to a different date, the date would be refreshed to the new date but the new graph is lagged to render.
<img width="1391" alt="Screenshot 2024-05-29 at 11 58 00 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114450390/32f76528-0e43-4b0f-a6e3-e52035df8b7a">
With the new spinning wheel, it's not going to show the graph until the new graph is ready with the updated date.
<img width="1391" alt="Screenshot 2024-05-29 at 11 42 30 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114450390/bd4e34f6-baa8-4db4-8664-cb586bc3f98b">

2024-05-31 04:02 UTC, Vijeth-V commented
This works perfectly. The report would be displayed with the new date.

<img width="1512" alt="Screenshot 2024-05-30 at 11 01 08 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/72465725/9af40245-58d4-4b64-8402-de7d0806dde7">

2024-06-01 03:46 UTC, mohabbasd submitted a review, later dismissed
Hello, I tested you PR and I can see the spinning wheel, it's just that for some reason I am unable to access the database in this particular page other wise everything works. Below is a video for your reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/92d7a4ca-5f68-4af6-b522-782af0f48c2f

2024-06-01 05:10 UTC, Sandhya1236 requested changes
While testing the recent updates that add spinning wheels to indicate data loading status when the date is changed, I encountered several issues. This PR is a minor patch for the functionality implemented in PR #2268, with no related backend PR. The main changes involved adding states for dataReady and setDataReady to handle the spinning wheels for the total people report, total project report, and total team report.

After checking into the current branch and running npm install, I cleared the site data and cache. I logged in as an admin user and navigated to Reports → Reports → Projects/People/Teams. I clicked on 'Show Total Project Report', 'Show Total People Report', and 'Show Total Team Report' one by one. When changing the end date to test different dates, the spinning wheel appeared as expected before the new report was shown.

However, I was unable to access the database on this particular page, which prevented me from fully verifying the functionality of the spinning wheel and data retrieval. Despite the spinning wheel displaying correctly, the inability to access the database means I couldn't confirm if the data was being retrieved and the graph was being re-rendered accurately. This issue needs to be resolved to ensure that the data loading indicator and data retrieval processes are functioning correctly.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/99e0b077-69f7-45b6-9fc7-6daaebead7c6

2024-06-01 05:41 UTC, chrischenlixing commented
> While testing the recent updates that add spinning wheels to indicate data loading status when the date is changed, I encountered several issues. This PR is a minor patch for the functionality implemented in PR #2268, with no related backend PR. The main changes involved adding states for dataReady and setDataReady to handle the spinning wheels for the total people report, total project report, and total team report.
> 
> After checking into the current branch and running npm install, I cleared the site data and cache. I logged in as an admin user and navigated to Reports → Reports → Projects/People/Teams. I clicked on 'Show Total Project Report', 'Show Total People Report', and 'Show Total Team Report' one by one. When changing the end date to test different dates, the spinning wheel appeared as expected before the new report was shown.
> 
> However, I was unable to access the database on this particular page, which prevented me from fully verifying the functionality of the spinning wheel and data retrieval. Despite the spinning wheel displaying correctly, the inability to access the database means I couldn't confirm if the data was being retrieved and the graph was being re-rendered accurately. This issue needs to be resolved to ensure that the data loading indicator and data retrieval processes are functioning correctly.
> 
>  HGN.APP.-.Google.Chrome.2024-05-31.21-57-24.mp4

Hi Sandhya, it is not loading because you have to wait longer for it to load. It's a large report to retrieve (even though it comes up on my end in 3 seconds), also try the Total People Report and Total Team Report and be patient on loading. Thanks!

2024-06-02 02:14 UTC, peter6866 approved these changes, later dismissed
Great work on effectively addressing the lack of user feedback after changing report dates. The addition of loading spinners is a great improvement to the user experience.

https://www.loom.com/share/ba3cc185193d40d483fb8f2893f5bb9a?sid=e000794a-2567-49e9-ade4-20cb04291f17

2024-06-02 03:00 UTC, tianyangL11 submitted a review, later dismissed
It works perfectly.    Please see the attached screenshots
![4aa23e5280a4b9beac03d25b31672e8](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144981416/603dc710-d98c-42c3-8bb5-12ef52ca45f1)

2024-06-05 00:04 UTC, JatinAgrawal94 approved these changes, later dismissed
Feature works as expected. Great Work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/17e5abb6-326d-49af-835a-35adcec3775e

2024-06-06 00:34 UTC, nishithaShetty commented
Hi Chris, Nice work!
It works as expected. It functions properly for Projects, People, and Teams. During loading and when changing the dates for the given modules, the spinning wheel is rendered.

<img width="514" alt="PR#2298_1" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/0f3ec03f-af08-46ed-8970-57afada87940">
<img width="509" alt="PR#2298_2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/55b6786f-affd-4d0d-ba1d-7c8f39e8a8e5">
<img width="509" alt="PR#2298_3" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/ffe4e7a6-b8ac-4fbd-815a-73d6bbadbf5a">
<img width="509" alt="PR#2298_4" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/45133470/39a3445b-2acb-4c54-9b6c-55edd68329ab">

2024-06-06 07:12 UTC, CloudyZ524 submitted a review, later dismissed
Hi Chris, 
The spinning wheel updated in this pull request works well and the date were updated correctly when I reset the date ‘Show Total Project Report’, ‘Show Total People Report’, and ‘Show Total Team Report’ one by one. Good job!

<img width="1041" alt="Screenshot 2024-06-06 at 00 04 15" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124476559/a473f04c-f1b6-44f7-a818-4058f8ac7a84">


One suggestion about the content display is that I noticed the date format from the textbox of date selection and the date format on the report is different, which might cause some confusion to users. It would be more clear to unify the date format in the same page. 

<img width="1334" alt="Screenshot 2024-06-06 at 00 03 15" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124476559/1abcd6e9-53d3-432d-8b7a-b5a890bdc6d7">

2024-06-06 14:04 UTC, akshit0211 commented
Hi Chris, great work for adding this spinning wheel functionality. It is working as expected for all three reports.

<img width="1250" alt="Spinning Wheel" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/8da15c6e-3479-44ce-92a6-90eff4b86a75">
![Total project report](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/64b80fce-0416-4311-a4c2-fbea30e2df91)
![Total people report](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/6fffa691-fc9e-4c9d-ae5b-0c2c0d50fcb9)
![Total team report](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/33cca913-abf8-4487-9bdd-3978cf9e54ce)

2024-06-06 14:11 UTC, akshit0211 approved these changes, later dismissed

2024-06-07 14:01 UTC, Wenboooooo submitted a review, later dismissed
Hello, I have tested the functionality using the admin account, the spinning wheel displayed as expected, great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114895283/66100698-7e3e-400c-af79-d05a603b820e

2024-06-07 15:48 UTC, PabloWang commented
Hi Chris, good work! It works as expected
<img width="1103" alt="Screenshot 2024-06-07 at 11 45 38 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/132537437/cb707eb4-c65c-4daf-bd9b-916f6dfa558c">
<img width="1430" alt="Screenshot 2024-06-07 at 11 45 08 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/132537437/5357336e-63f3-48df-a79d-0ac1988a5df1">

2024-06-07 16:01 UTC, PabloWang approved these changes, later dismissed
Hi Chris, good work! It works as expected

<img width="1103" alt="Screenshot 2024-06-07 at 11 45 38 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/132537437/9a85d25b-d6b1-4a0d-b284-4c929ba1b38f">
<img width="1430" alt="Screenshot 2024-06-07 at 11 45 08 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/132537437/3a7c96a3-4ee1-4fc8-a89b-24cde8cc381a">

2024-06-07 22:21 UTC, Sudershhh requested changes
Hi Chris,
The feature works as expected. 
![PR1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59435391/90cfd6f0-f518-4d4c-ae5b-f2fbdee91bed)

With this in mind, here are 2 more code changes that could be done to significantly enhance user experience.

1. Renaming the dataReady state variable.
2. Vertically aligning the loading spinner.

2024-06-07 22:21 UTC, Sudershhh commented on src/components/Reports/TotalReport/TotalProjectReport.jsx
>          <Loading align="center" darkMode={darkMode}/>
The Loading animation can be centered Vertically around the mid area point of the div bar. It works correctly around the X-axis.

2024-06-08 00:53 UTC, jennZhang93 approved these changes, later dismissed
Tested with owner account, I was able to see spinning wheels when graph isn't ready to load. One improvement suggestion is to alert user on the date range that the date selector can handle. Or block off the dates that shouldn't be selected. In the video below, I was trying to set the start date to 2004, but it keeps jumping back to 2014. I was confused for a minute until I realized that 2004 was too early.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/a8fce736-2518-4690-bc7c-942af8de6f4f

2024-06-11 20:47 UTC, Sudershhh approved these changes
Thanks for updating the requested changes. The new variables look good and more meaningful.

2024-06-12 19:29 UTC, Jingyii800 approved these changes
Hi Chris, I tested this feature with admin account. the wheel looks good while waiting for the chart generating.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/b9e651e4-d603-48bc-a575-a38d534f3323

2024-06-13 15:06 UTC, TXMO-dev approved these changes
I checked out the branch, and it worked as desired. Everything functions correctly. Approved!

2024-06-14 02:34 UTC, suaniii approved these changes
Hi, I've tested your PR, and it works well. I clicked into the reports page, then clicked on ‘Show Total Project Report’, ‘Show Total People Report’, and ‘Show Total Team Report’ one by one, and there was a spinning wheel displayed. Then, I changed the start date and end date, and the spinning wheels also displayed when the data was being retrieved. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113208952/61e3cdb8-8a75-4dc4-9c4f-06e5fd96d98c

2024-06-14 06:25 UTC, Sandhya1236 approved these changes
The original PR had an issue where changing the date did not provide any indication if data retrieval was in progress or completed. This PR addresses the problem by adding spinning wheels to indicate data loading until the newest data is ready and the graph is re-rendered. It is a minor patch for the functionality implemented in PR #2268 and does not require any backend PR; for the backend, just check in to the development branch. The main changes include adding state variables dataReady and setDataReady for the spinning wheels in the total people and total project reports. To test, check into the current branch, run npm install and necessary commands to run this PR locally, clear site data/cache, log in as an admin user, navigate to Reports → Reports → Projects/People/Teams, and click on ‘Show Total Project Report’, ‘Show Total People Report’, and ‘Show Total Team Report’ one by one. Change the end date to last year or any other date you want to test, and verify if the spinning wheel appears before the new report is shown for the new date. The functionality was successfully tested, and everything is working fine.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/ca83a7c5-a363-457e-89c7-90f772a2dace

2024-06-14 20:31 UTC, Trip2310 commented
The functionality was tested by following the given steps. It works perfectly. Some screenshots attached
<img width="863" alt="Screenshot 2024-06-14 132704" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113469900/7f4cc688-ac10-4cbb-8ef5-b14bc712977b">
<img width="876" alt="Screenshot 2024-06-14 132923" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113469900/f151920c-6b3f-421f-a049-3459863e1e94">
<img width="824" alt="Screenshot 2024-06-14 132825" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113469900/6caa936a-a10c-4a0d-a657-f7f4608e7fce">

2024-06-14 20:36 UTC, Trip2310 approved these changes
I've tested this PR, and it works well. Following given testing steps one by one, and there is a spinning wheel displayed after that, I changed the date and year, and the spinning wheels displayed and shows all data smoothly. I approve
Working well

2024-06-14 21:23 UTC, Kavil-Jain-514 approved these changes
The spinning wheel appears every time there is a load time when displaying the reports and changing dates.
The PR works well.  

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/aba52655-5b21-4e73-9c21-4cc74cf40012

2024-06-14 21:28 UTC, peter6866 approved these changes

2024-06-14 21:29 UTC, sahithidhulipala9 commented
Hi Chris, I have checked your PR and it is working perfectly. I have followed the steps you mentioned to check the functionality. Spinning wheel is working as it should be while loading the data. I have also checked changing the start and end dates and tried for all 3 i.e. for Show Total Reports, Hide Total People Report, Show Total Team Report. 

https://www.loom.com/share/0e359bb9163f4869990bed9b7a1acba0?sid=e7b6018f-6f8c-4e03-96db-659e98302db2

2024-06-14 21:31 UTC, sahithidhulipala9 approved these changes

2024-06-22 09:26 UTC, ImzIssa approved these changes
The changes look good. Nice work.

![Screenshot (405)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/87269725/e14ed205-bbfb-46d4-aec3-9addf85619e3)

2024-06-24 20:40 UTC, vishavk1992 approved these changes
Hi chris , Tested this PR for  for the spinning wheel of the total people report and project report. it works great and spinning wheel looks good. 

![PR-2298](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/b41ad320-58ac-499e-891c-40cf5e0122f7)
![PR--2298](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/35141db4-08cc-4953-a987-f71612ddff95)

2024-06-29 01:16 UTC, one-community commented
Thank you all, merging!

2024-06-29 01:17 UTC, merged