Peizhou_fix the Save Changes button hover issue
OneCommunityGlobal/HighestGoodNetworkApp pull request #2318
Opened 2024-06-05 16:35 UTC by ZhangPeizhou

# Description
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/7f741409-9377-4d92-b163-5941fc0eb9b2)

## Related PRS (if any):
This frontend PR is not related to any backend PR, please just check in to the development branch.

## Main changes explained:
- Fix the bug of the mouse hovering on the "Save Changes" button and the text disappears.

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in as an admin / owner user
5. go to dashboard→ Profile→ Teams
6. in order to test this change, you need to be in at least one team. If you are not on any team, use the "Assign Team" button to join a team
7. click the "Delete" button to remove yourself from a team
8. move the mouse over the "Save Changes" button, verify the text does not disappear and the hover effect works correctly

## Screenshots and videos of changes:
screenshot:
![my_PR_1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/e135a859-3116-4c02-a31f-bbd807e31c1b)
video:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/9c2b8f43-897d-4f7f-a544-28f2f03bc68b

2024-06-07 04:57 UTC, JatinAgrawal94 requested changes
I cannot pull this branch.
It says: "Remote branch ZhangPeizhou:peizhou_fix_savechanges_button_hover not found in upstream origin"
Please fix that.

2024-06-09 02:08 UTC, shradac requested changes
Cannot checkout to this branch. 
"error: pathspec 'ZhangPeizhou:peizhou_fix_savechanges_button_hover' did not match any file(s) known to git"

2024-06-10 21:53 UTC, ZhangPeizhou commented
> I cannot pull this branch. It says: "Remote branch ZhangPeizhou:peizhou_fix_savechanges_button_hover not found in upstream origin" Please fix that.



> Cannot checkout to this branch. "error: pathspec 'ZhangPeizhou:peizhou_fix_savechanges_button_hover' did not match any file(s) known to git"

The branch name is incorrect for some reason, please use this one instead: "peizhou_fix_savechanges_button_hover"

2024-06-10 22:07 UTC, ZhangPeizhou commented
> I cannot pull this branch. It says: "Remote branch ZhangPeizhou:peizhou_fix_savechanges_button_hover not found in upstream origin" Please fix that.



> Cannot checkout to this branch. "error: pathspec 'ZhangPeizhou:peizhou_fix_savechanges_button_hover' did not match any file(s) known to git"

The branch name is incorrect for some reason, please checkout with this branch name: "peizhou_fix_savechanges_button_hover"
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/d89a9305-40a4-47ed-a7f0-82a1241ffa53)

2024-06-12 12:18 UTC, KaushikMreddy requested changes
Hi, 

The change you've fixed is working. On hover, it turns blue and the text is clearly seen as well.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/9269b151-0537-4c32-9520-332e536359e5)

_Before I approve this, could you please make these changes in a branch of the main repository instead of a forked repository. I don't think workflows can be run on a forked repository._ 
Please do this ASAP.

2024-06-13 15:08 UTC, closed without merging

2024-06-13 20:45 UTC, ZhangPeizhou commented
This PR is replaced by PR#2351: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2351