Nathalia remove note from editable modals
OneCommunityGlobal/HighestGoodNetworkApp pull request #2348
Opened 2024-06-12 13:05 UTC by nathcarnevalli

# Description
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/503d74f0-73ac-445a-bacb-3c8dc862d8c4)

## Related PRS (if any):
This frontend PR is related to the dev backend PR.

## Main changes explained:
- Deleted the condition related to showing the note.

## How to test:
1. Check into current branch.
2. Do `npm install` and `npm run start:local` to run this PR locally.
3. Clear site data/cache.
4. Log as owner user.
5. Verify that all editable info modals on all pages do not display the following message at the bottom: “(Note: Only works on Permissions Management Page)."

## Screenshots or videos of changes:
Before:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/6f180513-f7e1-429c-9c70-2fe459beabdb

After:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/e761cca3-6f01-409d-a75a-fbfafee38f7e

## Note:
...

2024-06-12 16:08 UTC, Logeshwari-Renu approved these changes
I have tested the PR as owner and the message "(Note: Only works on Permissions Management Page)" is removed in all the editable info modals on all pages.
I have verified in the code as well.!  Great work.!

2024-06-12 16:13 UTC, Kavil-Jain-514 approved these changes
I have checked all the modals, and the message doesn't appear anymore.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/225e167a-af24-4742-bc54-6992b0301070)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/ee0498b3-2ad0-44d2-b362-ee04a050652c)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/50b82a3d-0608-4e81-a55f-84227c6851b9)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/f715192f-9da2-4562-bf1a-8303744e223f)

2024-06-13 04:42 UTC, Vijeth-V commented
I have reviewed the PR and checked all the info, and that message does not appear anywhere.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/72465725/be6db031-5026-4034-9e70-6d5472f1d268

2024-06-13 16:16 UTC, cgomezhub requested changes, later dismissed
I had fetching issues:

https://www.loom.com/share/e629a46e840e4d2cbc20bd6c23babdcb?sid=1a2404fb-3d17-4fb1-96e0-d8597ac2fc32

2024-06-13 19:22 UTC, Trip2310 commented
I have verified the PR and could not find message  "(Note: Only works on Permissions Management Page)"
Greatwork/

Uploading Recording 2024-06-13 121627.mp4…

2024-06-13 19:38 UTC, Trip2310 approved these changes
I have review the code and they are well organise. we can write reusable code for better readability or maintainability.

2024-06-14 18:45 UTC, nathcarnevalli commented
> I had fetching issues:
> 
> https://www.loom.com/share/e629a46e840e4d2cbc20bd6c23babdcb?sid=1a2404fb-3d17-4fb1-96e0-d8597ac2fc32

Hi @cgomezhub, thank you for your review! I've tested my branch again and tried to find the same issue but couldn't. I believe this issue is not related to my task.

2024-06-15 00:16 UTC, akshit0211 commented
Hi, the message doesn't appear on any pages. Good work!

<img width="1000" alt="img1" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/f6677f62-6089-46b0-9348-27889a94a893">
<img width="856" alt="img2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/8c8fd2af-796d-4b80-8e03-23a94629302b">
<img width="886" alt="img3" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/07813181-8c9e-456a-95bb-87dd299a96ae">
<img width="908" alt="img4" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/d10618f8-ba36-4c9d-8c3c-99e66cac473b">
<img width="895" alt="img5" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/59c1b772-3372-49fc-9220-9e42cb98c93d">

2024-06-15 00:17 UTC, akshit0211 approved these changes

2024-06-15 19:35 UTC, aaryaneil approved these changes
Tested the PR and the changes work as expected.
<img width="960" alt="Screenshot 2024-06-15 at 2 33 41 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/42f1cb5a-1eb5-492a-bda5-01a1a54ee008">
<img width="960" alt="Screenshot 2024-06-15 at 2 33 57 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/b6fd805d-1881-4319-a76d-a443bfb10ee3">
<img width="960" alt="Screenshot 2024-06-15 at 2 34 05 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/9531b3e8-2af0-4adc-ba93-80483a9817b4">
<img width="960" alt="Screenshot 2024-06-15 at 2 34 59 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/c469bc5a-0f96-403d-9996-eb59af3b4c4a">

2024-06-17 22:11 UTC, sahithidhulipala9 commented
Verified all the editable models, not able to see the message - "Only works on Permissions Management Page", Great Work!
![PR 2348-4](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60340387/9d5436f6-d1c1-4625-bc85-75c4ed2b8bcb)
![PR 2348- 2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60340387/3632a0a7-5913-435d-b6a5-1f3be9cdedca)
![PR 2348-1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60340387/66cbea31-e52a-4fa6-8f57-8c7564a9f62b)
![PR 2348-3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60340387/b032ee9d-d48b-4700-931e-c1b00df1d12e)

2024-06-17 22:21 UTC, sahithidhulipala9 approved these changes

2024-06-20 01:51 UTC, Sudershhh approved these changes
The message “(Note: Only works on Permissions Management Page)." is NOT being displayed on all the mentioned places. 

Good Work.

![PR 2348 - 2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59435391/76a7765e-62cc-4d4d-9cf3-ad5ed4689117)
![PR 2348 - 3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59435391/9a9836c2-13ff-449e-9d9b-36b9b8ee5ed7)
![PR 2348 - 4](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59435391/af4d4780-7ed6-4b6b-854a-a5115b664608)
![PR 2348](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59435391/42a797b1-7d4c-4976-a763-4b9560cf13f2)

2024-06-23 00:47 UTC, jinxyou approved these changes
The note has been removed from all editable info modals. Great work!
![Screenshot 2024-06-22 184638](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13797542/e9b608a8-95b4-4d65-a88b-5667d772e78d)
![Screenshot 2024-06-22 184645](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13797542/db185e62-ba4d-41f4-8706-bbe65b889933)

2024-06-27 19:25 UTC, JatinAgrawal94 approved these changes
Changes work as expected. Great Work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/12863896-1f34-4f85-9548-f6ceeca306c6

2024-06-28 18:51 UTC, vishavk1992 approved these changes
I have tested this PR and the note successfully deleted from all modals.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/cb071767-3252-4836-96c2-69ad29f4636b

2024-07-06 23:44 UTC, one-community commented
Thank you all, merging!

2024-07-06 23:44 UTC, merged