Unit test volunteering time tab
OneCommunityGlobal/HighestGoodNetworkApp pull request #2355
Opened 2024-06-14 06:58 UTC by aaryaneil

# Description
Unit test for `src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx`

## Related PRS (if any):
Updated PR from #2291

## Main changes explained:
Main changes explained:
- StartDate component should correctly validate and display a success style if the start date is before the end date
- StartDate component should handle the case when the start date is null or undefined
- StartDate component should correctly validate and display an error style if the start date is after the end date
- WeeklyCommittedHours component should handle the case when the entered value is equal to the defined maximum
- WeeklyCommittedHours component should prevent users from entering hours beyond the defined maximum or below the minimum
- MissedHours component should handle the case when userProfile.missedHours is null or undefined
- MissedHours component should display the missed hours if the user cannot edit
- MissedHours component should only allow non-negative values for additional make-up hours
- ViewTab component and all child components should render correctly
- ViewTab component and all child components should render correctly in dark mode

## How to test:
1. check into current branch
2. do `npm test VolunteeringTimeTab.test.js`

## Note:
Please ignore the errors because they are from network issues that this PR isn't testing.

2024-06-15 04:01 UTC, Vijeth-V commented
Hello,
Their is a console log error.
Cannot log after tests are done. Did you forget to wait for something async in your test?
Attempted to log "Request failed with status code 401".

<img width="1624" alt="Screenshot 2024-06-14 at 10 59 35 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/72465725/09206c13-fdd4-4a6a-819b-0e56d2729b08">

2024-06-15 06:30 UTC, deepthikannan reviewed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83337914/b3432348-d909-4c97-96ab-4363a91033af)
The test cases passed but with console errors.

2024-06-15 23:32 UTC, jinxyou submitted a review, later dismissed
I did the test and except for the network errors that should be ignored, everything works fine. Great work!
![Screenshot 2024-06-15 183124](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13797542/ef087a3a-a4d2-4d00-a6f6-4e79e2d8c5d2)

2024-06-28 03:18 UTC, jennZhang93 submitted a review, later dismissed
Except for the mentioned network error that should be ignored, all parts passed test. Good work!
<img width="1182" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/cf047a95-0d00-4b6e-8c33-7f7487731357">
<img width="1211" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/9a293781-565b-409e-9939-0b535ed33c47">
<img width="930" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/100d2ec3-42fd-4f46-971e-88e16c6341a8">

2024-07-22 21:34 UTC, Gauravmg6 requested changes
Your tests have passed successfully, but you are seeing warnings about logging after tests are completed. This typically happens when asynchronous code (like API calls) attempts to log errors after the Jest test runner has finished executing tests. In your case, it's logging Request failed with status code 401. To address this, you need to ensure that all asynchronous operations are properly awaited and that there are no pending promises or logs when the test completes.

![Screenshot 2024-07-22 173229](https://github.com/user-attachments/assets/84abcee8-b0e7-4f0b-b59e-9f73426d0ae2)

2024-09-11 00:41 UTC, ishangoel17 reviewed
All test cases are not passing. Below is the screenshot for reference:
![Capture2355](https://github.com/user-attachments/assets/883f19a8-c5f7-42cf-9b27-df44c18ca8d2)

2024-10-11 20:02 UTC, geetamatkar commented
Hi,
I tested this PR and all test cases are not passing.

<img width="943" alt="PR2355" src="https://github.com/user-attachments/assets/b3081ee3-523d-4b19-b562-33aaf3191c26">

2024-10-24 22:09 UTC, SatyashanthiT commented
need changes for this pr
<img width="453" alt="image" src="https://github.com/user-attachments/assets/7c270313-9911-421a-90ca-4ca7dc5ab04a">

2025-04-03 05:40 UTC, closed without merging