Jay fix people report badges
OneCommunityGlobal/HighestGoodNetworkApp pull request #2358
Opened 2024-06-14 22:56 UTC by jayyy-s

# Description
High priority bug issue to make presentation of badges on people reports match profile (also fixed some other places badges are used such as dashboard and Select Featured on profile page)
![bug ticket](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71467346/55bf494f-e1fc-4564-957d-79b836c9b22b)

## Related PRS (if any):
Unrelated to backend PRs, use latest development branch of HGNRest

## Main changes explained:
- Refactor the following files to use the `BadgeImage` component instead of copy/pasting code:
  - `src/components/Badge/BadgeReport.jsx`
  - `src/components/Reports/BadgeSummaryPreview.jsx`
  - `src/components/Reports/BadgeSummaryViz.jsx`
- Add variable css classes to `src/components/Badge/BadgeImage.jsx` to account for variable positioning on different pages
- Add new css to the following file for all badge count classes:
  - `src/components/Badge/BadgeReport.css`
  - `src/components/Reports/BadgeSummaryPreview.css`
  - `src/components/Reports/BadgeSummaryViz.css`
- Add `personalBestMaxHrs` to child components in the following files:
  - `src/components/Reports/PeopleReport/PeopleReport.jsx`
  - `src/components/UserProfile/Badges.jsx`

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Open up MongoDB Compass and connect to dev DB (auth variables should be in your .env file)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71467346/4f573121-ee17-4f76-acca-9c049dacfc96)
4. Open `userProfiles` collection and query document for your own account.
5. Update `personalBestMaxHrs` to something greater than 0
6. log as admin user
7. go to dashboard→ View Profile→ Assign Badge→ give yourself a Max Personal award
8. go to dashboard→ Reports→ People Reports and search for your account and navigate to it
9. Verify that when you click open _both_ badge modals, it correctly shows the max hours on top of the badge
10. Also verify that this is true for on the dashboard (bottom of the page where badges are displayed) and Select Featured on the profile page

## Screenshots or videos of changes:
![changes made](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71467346/44768cf6-00c3-4d32-8a94-c6d5f54d2ce4)

2024-06-19 21:18 UTC, Logeshwari-Renu approved these changes
I have tested the PR and after assigning "New Max - Personal Record Award" to user, it correctly displays the correct Badge hours that was modified in the "personalBestMaxHrs" field of "userProfiles" collection in MongoDB!
Also I have verified in the Dashboard and Reports Page. Great Work!
![2358_2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/166590596/ea63b154-2dc2-46d5-97a1-81929cda25a6)
![2358_1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/166590596/2d4437c5-51ca-4be6-a5aa-68fa0d9d8799)
![2358_3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/166590596/0a87ff56-9885-4782-a3a2-3284a9850a7f)

2024-07-12 06:00 UTC, angelalalacheng submitted a review, later dismissed
I use frontend branch `Jay_fix_People_Report_badges` and latest backend development branch to test. They all show the maxHour as expect.

`MongoDB`
<img width="815" alt="Screenshot 2024-07-11 at 10 54 55 PM" src="https://github.com/user-attachments/assets/233add7f-fc2e-4d4e-8639-0f66fa70fafc">

`Reports`
<img width="787" alt="Screenshot 2024-07-11 at 10 55 21 PM" src="https://github.com/user-attachments/assets/80bf8c0c-fe4e-4093-9823-93a8b70e5dde">
<img width="822" alt="Screenshot 2024-07-11 at 10 55 28 PM" src="https://github.com/user-attachments/assets/a6115104-2694-445b-a771-24dd7e1984f7">

`DashBoard`
<img width="632" alt="Screenshot 2024-07-11 at 10 56 35 PM" src="https://github.com/user-attachments/assets/f463b379-047a-4596-bcd2-63b781cdba1a">

2024-07-12 06:02 UTC, angelalalacheng approved these changes

2024-07-13 02:20 UTC, JatinAgrawal94 approved these changes
Changes work as expected. I tried assigning a user a badge and it works good.
Good work.

https://github.com/user-attachments/assets/795a08ab-7188-4bb9-aa85-2376dc9172af

2024-07-28 03:31 UTC, varunreddy03 requested changes
@jayyy-s 
I have reviewed and verified the PR by following the given steps and adding a few more badges, the number on the badge is appearing as modified in the MongoDB, and other badge numbers are also consistent across the profile page and the reports and users page, I have attached screenshots for the same.


![PR 2358_1](https://github.com/user-attachments/assets/32ef2ada-b6d6-492d-81bb-ac694fbea068)
![PR 2358_2](https://github.com/user-attachments/assets/7d28e811-f18d-45b5-980c-5fc1547a94aa)
![PR 2358_3](https://github.com/user-attachments/assets/2f5c43dd-0a57-4a0d-bbf9-8343238e8d64)

But I have Tried to open _**"Select Featured"**_ option in the profile tab and I have come across a bug that the page is not loading when I click on the "Select Featured" Button, Below is the Video of the issue.


https://github.com/user-attachments/assets/251226d9-adcc-40d1-8b67-33d8e29dcff1

2024-08-03 02:25 UTC, ReinaT5678 submitted a review, later dismissed
The changes work as expected! I changed the Max Hours in a user as seen below: 

<img width="213" alt="Screenshot 2024-08-02 at 7 23 22 PM" src="https://github.com/user-attachments/assets/942f629b-a3bc-4e0b-bf91-306da84ae9ff">

Then I assigned badges to the user, and it shows the correct number of hours in the New Max badge under Featured Badges.

<img width="816" alt="Screenshot 2024-08-02 at 7 23 40 PM" src="https://github.com/user-attachments/assets/18c9573c-b6f6-47da-b27e-5ba99895a826">

The hours are also visible under Reports > People Reports and Badge Summary:
<img width="777" alt="Screenshot 2024-08-02 at 7 25 19 PM" src="https://github.com/user-attachments/assets/b6376a64-f9c8-4280-b827-93b6619ba686">

2024-08-30 19:09 UTC, sri0606 submitted a review, later dismissed
Hello @jayyy-s , Great job! I've tested the changes and everythin works seamlessly. I have updated the `personalBestMaxHrs` in database and this is updated on the badge.

![Screenshot 2024-08-30 120128](https://github.com/user-attachments/assets/7c403f6d-f140-43f1-a8ff-ca662f975f44)
![Screenshot 2024-08-30 120642](https://github.com/user-attachments/assets/3e2adde5-4380-49cf-a698-7c9ed92c5d39)
![Screenshot 2024-08-30 120659](https://github.com/user-attachments/assets/365e8a29-a330-4ccd-a980-b55c9c4f8ce7)

2024-09-04 02:35 UTC, Shreyav2000 approved these changes
The issue with the presentation of badges on people reports matching the profile has been successfully resolved. I've verified the changes across the various places where badges are used, including the dashboard and the 'Select Featured' section on the profile page. Everything looks great, and the fixes ensure a consistent user experience.
<img width="719" alt="Screenshot 2024-09-03 at 9 29 24 PM" src="https://github.com/user-attachments/assets/3fa4d8bc-26bf-4a52-9a09-e34935c155b9">
<img width="982" alt="Screenshot 2024-09-03 at 9 32 46 PM" src="https://github.com/user-attachments/assets/b0763562-f4cb-4410-9753-00111611a5e0">

2024-09-05 23:45 UTC, FayeLV commented
Hi,

I have tested single and multiple gauges. Everything works well. Good job!
![Snipaste_2024-09-05_18-00-22](https://github.com/user-attachments/assets/77c773bd-764f-43ca-a320-c4616107f246)
![Snipaste_2024-09-05_18-03-26](https://github.com/user-attachments/assets/dce3cc44-5275-459d-89f9-ed0643030ce0)
![Snipaste_2024-09-05_18-03-34](https://github.com/user-attachments/assets/6001d62e-411a-4d0c-a4b9-d317a9419756)
![Snipaste_2024-09-05_18-05-14](https://github.com/user-attachments/assets/cb6a5793-633e-414c-a8bb-6214948550bf)

2024-09-05 23:47 UTC, FayeLV approved these changes

2024-09-06 07:58 UTC, sud306 commented
Hi,
I reviewed the PR and everything is working as expected.
Attaching the step-by-step screenshots.

![4  PR2358_1](https://github.com/user-attachments/assets/c6712450-2ab6-4516-a202-242a872d2496)
![4  PR2358_2](https://github.com/user-attachments/assets/ade76adc-0647-459d-b61d-6989ce1b81b0)
![4  PR2358_3](https://github.com/user-attachments/assets/0da21272-14fa-46a7-9550-5b9d29441eb0)
![4  PR2358_4](https://github.com/user-attachments/assets/7ae6ce33-23c2-422d-a7ad-9ae3a0d0e999)
![4  PR2358_5](https://github.com/user-attachments/assets/dd45247b-99d6-426b-b5ac-f0c54675410d)

2024-09-06 16:28 UTC, sam19981 approved these changes
FrontEnd - [Jay_fix_People_Report_badges](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/tree/Jay_fix_People_Report_badges)
BackEnd - Development branch

Scenario 1:
- Updated the personalBestMaxHrs for a volunteer account.
- Assigned a badge to the volunteer from the admin account.
- Checked the report for badge view and summary.

<img width="1440" alt="backend:Frontend-branch" src="https://github.com/user-attachments/assets/e90b381c-0f71-42f0-a607-3a06d6476518">

<img width="1173" alt="Updating_personal_maxhrs" src="https://github.com/user-attachments/assets/ddd10483-ca1a-471a-959d-6d7666bf63b4">

![assign_badge_to_volunteer](https://github.com/user-attachments/assets/f9267b87-42a5-413a-8fb9-6ba8c62d5bb3)

<img width="1436" alt="badge_summary_preview" src="https://github.com/user-attachments/assets/c8b18938-f6ba-41f8-8754-2382a281e610">

<img width="1435" alt="Badge_summary" src="https://github.com/user-attachments/assets/632e70d2-a261-4083-a287-2baef6fd2818">

Scenario 2:
-Tried assigning the badge to the admin account.
-Checked if it was updated in the reports.

![assigned_badge_to_admin_account](https://github.com/user-attachments/assets/c8304dd7-cf2d-493a-94d3-7cfc677b8ad3)

<img width="1417" alt="report_view_for_admin_account_badge_preview" src="https://github.com/user-attachments/assets/c83d9ef6-ef4e-498a-b9e5-da62353acd44">


<img width="1440" alt="report_view_for_admin_account_badge_summary" src="https://github.com/user-attachments/assets/87505866-30ac-4215-9407-028013400fe8">

The functionality is working as expected.

2024-09-13 00:31 UTC, crystallow1168 approved these changes
<img width="363" alt="image" src="https://github.com/user-attachments/assets/6525c648-9047-4eca-af75-7a5586c6c0a3">

✅  Personal Best Hours is set to 11 hours

<img width="532" alt="image" src="https://github.com/user-attachments/assets/fbe04827-c254-4643-89a9-146f46a44fec">

✅ Number of hours is shown on both badge modals

<img width="472" alt="image" src="https://github.com/user-attachments/assets/3fa233f9-5b7e-4c16-b4d7-9956d3a6df49">

✅ Badge section on dashboard is showing number of hours
❗️ Page crashed when opening Select Featured on the profile page

2024-09-26 20:06 UTC, mrinalini-raghavendran19 submitted a review, later dismissed
Looks good to me!

Good job, the changes in the PR work as expected. Attached are screenshots to show the changes I made and their reflection on the various places I can view badges including in the profile sections - 'select featured' modal.

<img width="1470" alt="Screenshot 2024-09-26 at 12 52 45 PM" src="https://github.com/user-attachments/assets/3e8ebb46-b5b0-4ccd-83ef-9622489c885a">

<img width="543" alt="Screenshot 2024-09-26 at 12 53 33 PM" src="https://github.com/user-attachments/assets/b45f9254-46d7-42a7-9d95-4284160ebdb6">

<img width="1470" alt="Screenshot 2024-09-26 at 12 52 30 PM" src="https://github.com/user-attachments/assets/c236d0e2-16df-4dfa-9de5-ee0b5bb47768">

<img width="744" alt="Screenshot 2024-09-26 at 12 54 15 PM" src="https://github.com/user-attachments/assets/12e2bc73-6f64-487f-972a-b6229d50cdd5">

<img width="744" alt="Screenshot 2024-09-26 at 1 05 50 PM" src="https://github.com/user-attachments/assets/4d4dfce6-3372-4d85-8616-9ac9a718e04b">

2024-09-27 01:50 UTC, nevatiarishabh approved these changes
Everything is working as expected. Looks good to me.

<img width="1440" alt="Screenshot 2024-09-26 at 6 49 17 PM" src="https://github.com/user-attachments/assets/b9eb8b55-82bb-4a86-aa22-030dead0cf8b">
<img width="1440" alt="Screenshot 2024-09-26 at 6 49 57 PM" src="https://github.com/user-attachments/assets/fbe30f69-9c73-489b-8623-3bd18e6ba700">

2024-10-27 02:37 UTC, zhiminV approved these changes
I have checked the function work as expected.



https://github.com/user-attachments/assets/e03b06ad-2ca8-48c7-b56d-4486ca8a4a9e

2025-02-18 04:12 UTC, one-community commented
Thank you all, merging!

2025-02-18 04:12 UTC, merged