Remove dead space in user profile section
OneCommunityGlobal/HighestGoodNetworkApp pull request #2387
Opened 2024-06-25 23:09 UTC by KyreneAF

…w 2 inside userProfile

# Description
<img width="800" alt="Screenshot 2024-06-25 at 5 59 01 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/129882345/3e9bac36-e657-4445-aa53-fa6d258f5997">
s # (WBS) 
This bug was only on an owner account

## Related PRS (if any):
No related PRS

## Main changes explained:
Added a height to a div to remove dead space.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ View profile → Click on each tab ie(Basic information, Teams, Projects)→
6. verify Update Password, Save Changes and cancel button is right under the content rendered with no dead space.
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:
![Screenshot 2024-06-25 at 3 56 41 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/129882345/2709b12b-a162-4269-a813-88089625ba49)
![Screenshot 2024-06-25 at 3 56 18 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/129882345/0ea08c24-32da-403c-8eed-ba61e96cddfb)
![Screenshot 2024-06-25 at 3 55 53 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/129882345/cb8430ce-a7ee-4161-b4c8-bcc0f02a4
![Screenshot 2024-06-25 at 3 58 15 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/129882345/a09ad621-0cdd-4890-8fef-c11c67b4b1f7)
f24)

## Note:
Include the information the reviewers need to know.

2024-06-26 02:06 UTC, kdaga81 requested changes
<img width="600" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60085629/084c6bbd-4522-4ee7-af45-308471d34699">

<img width="609" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60085629/b91de03c-a22e-4e75-9b4d-8ce42d3d6d2a">
Can we have "Cancel", "Pause", "Set Final Day" to filled color initially rather than getting highlighted while hovering to make it more intuitive during dark mode?

<img width="617" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60085629/47650a8d-0f68-4137-a6a9-0991918d78cd">

Can we have some margin between the last textfield and the buttons in "Volunteer Teams" tab as it looks bit overlapping.

2024-06-26 09:12 UTC, DiyaWadhwani requested changes
Hi Kyrene,
I checked out the changes and the spacing on the teams and projects sub-parts is fine.

![teams+projectsview](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54880903/491e21c2-f05f-4cf3-b5b3-301bec3da597)

However, the volunteering times section could use a little more margin around the text areas as well as the buttons. The UI looks manageable in light mode but super crammed up in the dark mode.
I would suggest changing the colour of the buttons on the dark mode as well instead of the change in colour when a user hovers over it.

![volunteerTimesDark+Light](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54880903/c00d2bf4-987c-4fb5-a395-0fec1fd01d72)

Kindly review this. Thanks

2024-06-26 18:30 UTC, Jingyii800 approved these changes, later dismissed
I have tested this PR, the space between the content and the button looks good now in light mode. But the "save changes" button not so obvious in the dark mode.
![Screenshot 2024-06-26 142746](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/74db063f-4142-45dc-a65c-3deada7b83ce)
![Screenshot 2024-06-26 142825](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/4ea7f2c9-a73b-4dbd-843a-0183daa11122)
![Screenshot 2024-06-26 142816](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/f8792999-e5f6-4599-8275-186bc60b3b50)
![Screenshot 2024-06-26 142800](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/c18eb01f-490c-4179-964f-41d749f376ba)

2024-06-26 20:29 UTC, Logeshwari-Renu submitted a review, later dismissed
I have tested the PR as owner and the dead space is removed for each tab in Profile page. The update, save and cancel button were placed at bottom after some space for the "Team" and "Edit History Tab" due to less data but it did not cause any trouble in navigation.

![2387_1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/166590596/aef7ce02-22a7-467f-ac9e-d71c4a3e1efd)
![2387_2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/166590596/a28597d3-6ede-42ae-90e9-de4795633620)
![2387_3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/166590596/774b7d41-326b-4340-ab06-2bee99f4cb17)

2024-06-26 21:34 UTC, Trip2310 submitted a review, later dismissed
Hi Kyrene, I have tested this PR by following given steps, it looks good in dark and light mode. Suggestion: Labels looks very occupied to right
It is working perfectly.
Good work
<img width="979" alt="PR#2387B" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113469900/a3ad13d9-a045-4dc4-961b-534175680a5e">

2024-06-26 23:06 UTC, HowieMiao requested changes
Deadspace has been removed and looks good, I also agree with a lot of the proposed changes above, regarding margins for Volunteering Times tab, as well as filled buttons for dark mode.

On top of this, I believe there should be a margin addition between the Save Changes and Cancel button to match the space between Update Password and Save changes, marked in small red indicator at the bottom of the screenshot provided

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73614967/2e092ffd-0636-4b68-b9e9-6a95f1a522e4)

2024-06-27 05:59 UTC, KaushikMreddy requested changes
Hi, 

May I know what the changes you've made are? I still see the dead space between the tables and the buttons. Please highlight the changes using a marker in the images. 

- Edit History Tab
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/b1f93461-a4af-4c52-8c22-0cd35f23a11c)
- Projects Tab
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/939cbeb5-66f3-4527-9401-b189ab426d79)

2024-06-27 15:27 UTC, Sarath-3119 approved these changes
The changes said in this PR are reflected as expected in the view profile section. There are no dead spaces between updatepassword, save changes and cancel buttons in all the mentioned sub sections.
![unnamed (1)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/156833266/8d504d8a-a0f3-42e1-8531-abb776af4156)
![unnamed (2)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/156833266/375ec194-6432-4456-a074-b870fbe8e326)
![unnamed (3)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/156833266/2daba0d1-aeff-4c42-9f3a-b26e77095730)
![unnamed (4)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/156833266/0e3d2e44-735f-43c4-9370-c6f275d14c92)
![unnamed](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/156833266/9580d0ab-6ef7-4ae5-96bb-c328b7442d59)

2024-06-27 18:13 UTC, JatinAgrawal94 requested changes
The sections for teams and edit history still have dead spaces. Rest everything is fine.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/717406d5-3da8-49dc-8916-f2fa4c0169cf

2024-06-28 17:39 UTC, KyreneAF commented
> <img alt="image" width="600" src="https://private-user-images.githubusercontent.com/60085629/342982525-084c6bbd-4522-4ee7-af45-308471d34699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1OTY2MDAsIm5iZiI6MTcxOTU5NjMwMCwicGF0aCI6Ii82MDA4NTYyOS8zNDI5ODI1MjUtMDg0YzZiYmQtNDUyMi00ZWU3LWFmNDUtMzA4NDcxZDM0Njk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDE3MzgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExOTMyNTRlNzlkOTZmMWY0ZDg1YjYxODc1NDJjMGFmYzY5MzNmMDIzM2E0ZDVlZTU2NmFkZjgxMmY3YzRkNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z7ysbAPiNs9I1LULgXx-yLn5OS5C5wJZvy0Keqmct3s"> <img alt="image" width="609" src="https://private-user-images.githubusercontent.com/60085629/342982473-b91de03c-a22e-4e75-9b4d-8ce42d3d6d2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1OTY2MDAsIm5iZiI6MTcxOTU5NjMwMCwicGF0aCI6Ii82MDA4NTYyOS8zNDI5ODI0NzMtYjkxZGUwM2MtYTIyZS00ZTc1LTliNGQtOGNlNDJkM2Q2ZDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDE3MzgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNzc5ZGVmZjgwNzI5ZDU5ZTYyZTFkZGZjZDQyMGM1YWNhODQ1MDQ4ZTJlYjI3NTAxMzNkYjlmOTNmZWNmZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4lav_Vj31B4HmDRr-CeHyKR3H0OcyspnE_Yrd9_5L5U">
> Can we have "Cancel", "Pause", "Set Final Day" to filled color initially rather than getting highlighted while hovering to make it more intuitive during dark mode?
> 
> <img alt="image" width="617" src="https://private-user-images.githubusercontent.com/60085629/342982877-47650a8d-0f68-4137-a6a9-0991918d78cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1OTY2MDAsIm5iZiI6MTcxOTU5NjMwMCwicGF0aCI6Ii82MDA4NTYyOS8zNDI5ODI4NzctNDc2NTBhOGQtMGY2OC00MTM3LWE2YTktMDk5MTkxOGQ3OGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDE3MzgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YThhN2RmZjI3MmEyZDExODUyYmIyZDcyODNmM2RkYjA5OWVjNWVkNWMxMGY1YWEzZDg2ZTVlNDljNzkzYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oRYRoruA3WHjkJEYBq-x4Mbfv5sS-ZiXTVmXqG82Q7I">
> Can we have some margin between the last textfield and the buttons in "Volunteer Teams" tab as it looks bit overlapping.

-I have made the margin changes please review and approve :)

2024-06-28 17:43 UTC, KyreneAF commented
@kdaga81 @DiyaWadhwani  I have updated the changes that you have requested. Please review again and approve if you feel they are met :)

2024-06-28 18:09 UTC, pavanswaroopl requested changes
Hello,

Everything looks good, but small changes can make the website look better.
1. A little bit of padding between buttons.
2. The save changes button doesn't look obvious in dark mode even when changes are made.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/e0e3f862-a89a-48f3-a509-2fa3c310faf0

<img width="710" alt="Screenshot 2024-06-28 at 2 02 45 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/56e38f27-49e7-495f-adb5-868cefab739e">

2024-06-28 21:32 UTC, Parth-tech commented on src/components/UserProfile/UserProfile.scss
> +
Hi @KyreneAF,
I was trying to find a reference to `.profileEditButtonContainer` that has been created above. Could you help me locate the use of this css. 
Thanks for helping out!

2024-06-28 21:39 UTC, Parth-tech commented
Hi @KyreneAF,
Below I have attached 2 screenshots where I see abit of dead space between the content and the buttons. So I believe that dead space has to be eliminated. Kindly correct me if I have got it wrong. 

Currently a grid/table (i.e rows and columns based) layout is being used hence that leads to the dead space between the table content above and the buttons. Again if I have interpreted incorrectly kindly correct me. 
Thanks.

`Image Reference`
<img width="819" alt="Screenshot 2024-06-28 at 2 33 05 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/eb371be0-b414-4325-8b2e-47204e78edda">
<img width="796" alt="Screenshot 2024-06-28 at 2 33 12 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/9951c7e0-cc5b-4bbc-8b18-56d5258a3e4c">

2024-06-29 01:31 UTC, IchinnorovTuguldur commented
Hello Kyrene, 

I think spacing looks good to me. nice job on that!!  But under basic information tab there is "pause button". Isn't it supposed to be aligned with set final day button? Looks bit off. 

![Screenshot 2024-06-28 at 6 28 55 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54337205/cb7c1cf3-034f-4801-ac7b-f64478843585)

2024-06-29 03:46 UTC, nyelmela submitted a review, later dismissed
I checked the PR as an owner and verified that there is no dead space in each tab. The Update Password, Save Changes, and Cancel buttons were exactly under the content, except for Teams, and Edit History, which had less content. Everything else appears to be fine.
<img width="507" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/097501b7-278a-4a38-be6d-9682a2f4ee21">
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/5a51fbb2-26da-44da-a90d-c2bc611d8b0b)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/a0088014-c3f5-432e-aea5-fd92452f640d)

2024-06-29 05:17 UTC, wang9hu commented
Hi KyreneAF,

I reviewed the request and your changes, and it seems that this extra space is caused by the right tabs sections height trying to match to the left, and the buttons below are outside of these div elements. So my suggestion for this is to include the buttons in the tab sections.
<img width="1270" alt="Screenshot 2024-06-28 at 10 11 23 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/77769556/e8e50d2d-0dd9-42af-bf27-becf67e29918">
<img width="1307" alt="Screenshot 2024-06-28 at 10 11 17 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/77769556/67a0a403-979e-46a3-91a6-e9c96ba0edf6">
<img width="1365" alt="Screenshot 2024-06-28 at 10 11 40 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/77769556/e1478451-8d33-458c-a91f-e0715bff770a">

2024-06-29 21:25 UTC, wang9hu commented
The dead spaces are removed as originally requested. Good work.

<img width="1241" alt="Screenshot 2024-06-29 at 2 21 21 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/77769556/c3732649-bb5c-428f-bd8f-9178b8bb7a43">

2024-06-30 00:51 UTC, one-community commented
Thank you all, merging!

2024-06-30 00:51 UTC, merged