Shrada Reports UI fix buttons and graph
OneCommunityGlobal/HighestGoodNetworkApp pull request #2396
Opened 2024-06-29 01:11 UTC by shradac

# Description
<img width="680" alt="Screenshot 2024-06-28 at 8 56 32 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56028645/234ddaca-4c17-403f-9c3c-fdb348068bb2">

## Related PRS (if any):
This frontend PR is related to the development backend.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Repots
6. verify the six buttons at the bottom appear in a square shape between 1100px and 1350px.
7. verify the increased top margin to the Projects/People/Teams table when 1350px and below.
8. verify the total project/people/team report graph goes out of view when 550px and below.

## Screenshots or videos of changes:
<img width="478" alt="Screenshot 2024-06-28 at 1 29 49 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56028645/cd8f7606-94b3-4d40-a89d-9872dc02e430">
<img width="515" alt="Screenshot 2024-06-28 at 9 07 15 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56028645/0fc0ce1f-e512-43e1-9109-9ccf943bfab8">
<img width="515" alt="Screenshot 2024-06-28 at 9 08 36 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56028645/6a9e051f-8fa0-4b5a-8e3a-13b70a59369c">

2024-06-29 05:01 UTC, Vijeth-V commented
The buttons and the graph look perfectly well on my screen when checked with 1101px and 1350px, But it is not working well with 1100 px. Can you please check and update the code.

1100px and 1350px
<img width="729" alt="Screenshot 2024-06-28 at 11 59 01 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/72465725/ac919061-ef25-41fd-84be-2670f658907c">

1101px and 1350px
<img width="729" alt="Screenshot 2024-06-28 at 11 59 14 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/72465725/56850904-244e-4778-b8a3-d2ed26952f08">

2024-06-29 06:16 UTC, kdaga81 requested changes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60085629/5e15df99-f715-45f0-9559-d86f7212ac04)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60085629/ece2c15f-a93d-4b29-9a89-3d120457930d)


Working fine for 1100px but not for 1100px

2024-06-30 01:52 UTC, jinxyou approved these changes
All adjusted layout seems good! Great work!
![Screenshot 2024-06-29 195021](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13797542/f6da2ecb-39bc-4149-a7ab-2de68df241d3)
![Screenshot 2024-06-29 195143](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13797542/686a6a99-ed74-4ba3-a5b1-3670d8ce42bc)
![Screenshot 2024-06-29 195152](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13797542/c26938db-b7ec-4ed0-b4fd-fecb163f4a6d)

2024-06-30 05:52 UTC, aaryaneil approved these changes
The UI changes work as expected and they look good. Good work.
<img width="1440" alt="Screenshot 2024-06-30 at 12 51 12 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/f21bbada-a47a-460a-841f-e9653adea270">
<img width="1440" alt="Screenshot 2024-06-30 at 12 51 40 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/76f155dc-6676-4abc-a38d-81bf4606489c">

2024-07-04 17:25 UTC, vijay10pk requested changes
The changes are working between 1100px to 1350px as expected and also alignment is also looks good.
<img width="965" alt="Screenshot 2024-07-04 at 1 18 06 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/5ff8058b-3912-49c2-9b2b-e95892455efc">
<img width="965" alt="Screenshot 2024-07-04 at 1 18 17 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/46b24127-f4e9-4d41-b8fe-f591f33a8b40">

I have a suggestion that if you could make the button width in filter component same and also the width of graph component and select a catergory and select a filter component same.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/df29379c-be7b-4c5e-ae4e-8816c2b50be4)

2024-07-04 20:48 UTC, vijay10pk approved these changes

2024-07-05 04:38 UTC, KaushikMreddy approved these changes
Hi Shrada, 

Your changes are working well,
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/149dc354-3e93-47c4-b1f9-c2a085ae85c3)

The margin makes the page look neater;
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/6ff662ab-234c-4c2d-b269-7b5d67bc89e4)

I do not have an admin account, but I can approve these changes.

2024-07-05 17:16 UTC, kdaga81 approved these changes
The changes are working as expected

2024-07-06 00:52 UTC, IchinnorovTuguldur commented
Buttons look as described above. Great job!!
<img width="581" alt="Screenshot 2024-07-05 at 5 51 36 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54337205/8280f2ac-363a-4995-ab07-d5cdc2b4fb75">
<img width="633" alt="Screenshot 2024-07-05 at 5 51 46 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54337205/6b7f90be-9b28-4b30-adb9-bffd7d2cfd20">

2024-07-06 00:52 UTC, merged