Nahiyan_Added dark mode to editor and user profile modals
OneCommunityGlobal/HighestGoodNetworkApp pull request #2411
Opened 2024-07-03 15:46 UTC by Nahiyan-16

# Description
This PR adds a new feature that makes the `send emails` page editor toggle with dark mode.
Also added dark mode on two new modals on the user profile.

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
- Added dark mode to  `send emails` page editor
- Added dark mode to `Blue Square Emails BCCs` (User Profile)
- Added dark mode to Blue Square table's `EditableInfoModal` (User Profile)

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other Links -> Send Emails
6. verify that editor is toggling themes along with dark mode
7. verify that `Blue Square Emails BCCs` (User Profile) toggles to dark mode
8. verify that the Blue Square table's `EditableInfoModal` (User Profile) toggles to dark mode

## Screenshots or videos of changes:

Uploading Recording 2024-07-03 114234.mp4…

2024-07-03 20:42 UTC, HowieMiao approved these changes
Couldn't get myself set up with BCC email tab, but Blue squares and send email both look great in light and dark mode. 

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73614967/cafeb522-3d70-4fb4-89e2-1fb9d67d1382)

2024-07-04 00:06 UTC, kdaga81 requested changes
Dark mode is working as expected for email. However, it's not showing as expected for Profile page.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60085629/3404dea8-ccc1-4175-8a39-4a80dd11e43c)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60085629/b791f35d-3af4-472e-8abc-7e266556becb)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60085629/cfcd968e-9bc7-4f41-8efe-5e9cc1cbf626)

2024-07-04 00:14 UTC, Nahiyan-16 commented
> Dark mode is working as expected for email. However, it's not showing as expected for Profile page. ![image](https://private-user-images.githubusercontent.com/60085629/345650235-3404dea8-ccc1-4175-8a39-4a80dd11e43c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTIyODQsIm5iZiI6MTcyMDA1MTk4NCwicGF0aCI6Ii82MDA4NTYyOS8zNDU2NTAyMzUtMzQwNGRlYTgtY2NjMS00MTc1LThhMzktNGE4MGRkMTFlNDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAwMTMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZjgyMTgxMDExYmE5ZGZjMTcxZjMyYzUzYmY2ODA4MzI0OTJlY2YwYjkzZjdlMmNhOTZkOWIyMmEzMTZlZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PVi7C5Ocnuxg7s7woLCWfFMVrxI3nA1bntF_t1_tUXk) ![image](https://private-user-images.githubusercontent.com/60085629/345650635-b791f35d-3af4-472e-8abc-7e266556becb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTIyODQsIm5iZiI6MTcyMDA1MTk4NCwicGF0aCI6Ii82MDA4NTYyOS8zNDU2NTA2MzUtYjc5MWYzNWQtM2FmNC00NzJlLThhYmMtN2UyNjY1NTZiZWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAwMTMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNjRiMzE4ZjNlNTlkMTEwODllZDFlODlhMGI3ZjQzOGYzNjA5MWQyNjYwOTc5NTQ0Y2RiNDhlZTQ5ZGVhNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4mrpbw0_9kw_qZrWwfQcFemkK-aLfl0DM1sDSeVsq2Q)
> 
> ![image](https://private-user-images.githubusercontent.com/60085629/345650850-cfcd968e-9bc7-4f41-8efe-5e9cc1cbf626.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTIyODQsIm5iZiI6MTcyMDA1MTk4NCwicGF0aCI6Ii82MDA4NTYyOS8zNDU2NTA4NTAtY2ZjZDk2OGUtOWJjNy00ZjQxLThlZmUtNWU5Y2MxY2JmNjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAwMTMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NjdjNWMxZTRiOGI0MjFkNGM1NmUzMTgyYzllMmExMjkwM2MzYTA4YWI0ZjcxYmNmNDZmYWI3OTM0NGU5NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.giXBxv4NvcxvMoM3ohlcnZH7NWOATD1G1-kCBrNbUiI)

Please test this again. It seems like you weren't able to switch to this branch.

2024-07-04 00:59 UTC, kdaga81 approved these changes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60085629/9b537c0b-a478-4db3-8372-e461c6f2914b)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60085629/bc0849fd-e64c-4b2f-8e42-e1d6b72b7b7d)


The changes are working as expected. Sorry for the inconvenience

2024-07-05 02:25 UTC, vijay10pk approved these changes
All the changes are working as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/376d6c02-3b83-4663-b697-fcd7f2cec949

2024-07-06 01:38 UTC, merged