Hoang prevent overriding task edit suggestion's approval/rejection
OneCommunityGlobal/HighestGoodNetworkApp pull request #2413
Opened 2024-07-03 18:02 UTC by kylepham

# Description
<img width="706" alt="Screenshot 2024-07-03 at 11 49 21 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/f30bb9c7-bc60-4bf4-8c82-dd51af9a7b1a">

Issue videos: 
- https://drive.google.com/file/d/10EGb6LMg6LxpAYdRhUZoHlaZgMe1xHFE/view
- https://drive.google.com/file/d/1WyJIv5byGLI0UcwV01nnxkF4Tpz525bY/view
- https://drive.google.com/file/d/1atldiRx1NMd2dkuzjo-agL9sm_N_cerg/view *(have to reload to get the suggestions data)*.

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ task→…
6. verify function “A” (feel free to include screenshot here)
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2024-07-06 23:22 UTC, vijay10pk approved these changes
All the changes works as expected in both light and dark mode. Looks good to me
<img width="1411" alt="Screenshot 2024-07-06 at 7 12 22 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/e3765e86-2897-4539-b309-9aebe5c78008">
<img width="1422" alt="Screenshot 2024-07-06 at 7 11 55 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/d0571746-39b1-4513-b658-661b2badb3f6">
![Screenshot 2024-07-06 at 7 13 51 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/2c3bcdf9-f210-40c8-b635-da6e83a9f1d3)
![Screenshot 2024-07-06 at 7 14 03 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/b3653ca5-8d77-47ec-99ae-33a31d3e11a0)
<img width="1425" alt="Screenshot 2024-07-06 at 7 15 07 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/6ee8e9f8-15eb-4a7f-b02c-53cb9ba7dc21">
<img width="1428" alt="Screenshot 2024-07-06 at 7 15 18 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/908bd663-cfb9-43e4-b8d6-9657819a3fef">
![Screenshot 2024-07-06 at 7 15 32 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/29483409-7e5f-4f49-abf9-80d94d31e708)
<img width="1409" alt="Screenshot 2024-07-06 at 7 17 33 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/0851d37d-78e0-47ea-a723-dc2ef26b3997">
<img width="1428" alt="Screenshot 2024-07-06 at 7 17 45 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/dbab4ce2-67ea-4fc4-b60d-72d09257d6a2">
![Screenshot 2024-07-06 at 7 18 18 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/8fd69c8c-fe02-48a6-8f35-4f118230892d)

2024-07-10 04:21 UTC, nikhilpittala16 approved these changes
I have tested PR  and everything works as expected.
![Screenshot (54)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/142841075/4f3372f8-fd49-498f-89fb-3b613c894834)
![Screenshot (55)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/142841075/9ec4dce7-1b2d-44ee-baf0-da4178864819)
![Screenshot (56)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/142841075/60b80dcf-c17b-4456-ad11-b503fbee7c6c)
![Screenshot (57)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/142841075/d51ec759-ae68-4b2f-8784-b35ac678beff)

2024-07-12 19:07 UTC, Vigneshwar-Muriki approved these changes
I checked out the current branch and ran `npm install` followed by `npm run start:local` to run the PR locally. I verified that when a person suggests a change, their number of suggestions is updated immediately on their header. Additionally, the other person’s suggestion list is updated automatically when navigating to `/taskeditsuggestions` by clicking on the red circle on the header. Everything worked as expected.
![#2413_1 (1)](https://github.com/user-attachments/assets/f920ce41-f854-43aa-ad64-d62695dda8e7)
![#2413_2](https://github.com/user-attachments/assets/fe31456c-13a5-4502-aeb3-5acf28a7404e)
![#2413_3](https://github.com/user-attachments/assets/d5cb35e4-36c5-46b3-bd87-c767789c231b)

2024-07-13 13:59 UTC, rmcgummadi reviewed
The #PR2413 is functioning properly in both light and dark modes. When an admin adds a task to a specific user, the user's number of suggestions is immediately updated in their header (Red Button). The user can accept or reject the suggestion.
<img width="1512" alt="Screenshot 2024-07-13 at 12 33 53 AM" src="https://github.com/user-attachments/assets/9144c648-0f47-449b-841c-cf99109c66e0">
<img width="1506" alt="Screenshot 2024-07-13 at 12 33 36 AM" src="https://github.com/user-attachments/assets/d716402b-402e-49f5-ba24-0be3f36076c0">
<img width="1512" alt="Screenshot 2024-07-13 at 12 09 13 AM" src="https://github.com/user-attachments/assets/fa56a0d3-4b69-49d1-bf29-a701d958d991">

2024-07-15 18:52 UTC, SaiLavanya1 approved these changes
Hi
Below are the screenshots of running the PR - 2413.
All the changes worked as expected and looked good.
<img width="724" alt="Screenshot 2024-07-14 at 2 14 53 PM" src="https://github.com/user-attachments/assets/869f502f-5bfa-4e15-b015-6ddf2095edd2">
<img width="725" alt="Screenshot 2024-07-14 at 2 14 59 PM" src="https://github.com/user-attachments/assets/eb0bc6f3-7feb-497c-bfcc-d5dfe8562844">
<img width="717" alt="Screenshot 2024-07-14 at 2 15 06 PM" src="https://github.com/user-attachments/assets/ee99cd14-5530-477b-8c12-9212c4788111">
<img width="718" alt="Screenshot 2024-07-14 at 2 15 17 PM" src="https://github.com/user-attachments/assets/f2256072-9ee1-4782-82cc-1c143adb0d14">

2024-07-17 22:08 UTC, JatinAgrawal94 approved these changes
Changes work as expected.

https://github.com/user-attachments/assets/10925e4b-b968-4f12-b731-5728dbf7ff53

2024-07-19 17:12 UTC, kabraambika requested changes
I have followed the below steps to test the PR

_In frontend repository_
- git checkout Hoang_fix_approve_and_apply_suggested_changes_on_a_task
- npm install
- npm run start:local

_In backend repository_
- git checkout Hoang_fix_approve_and_apply_suggested_changes_on_a_task
- npm install
- npm run build
- npm start

On logging as dev admin or owner, Dashboard is not loading and there are backend errors as shown below: 
![image](https://github.com/user-attachments/assets/0e9234e2-7749-40cd-a9ac-fb67245c7b7f)

<img width="765" alt="image" src="https://github.com/user-attachments/assets/bbe13940-a779-4934-9cc3-3bd6762be61c">

**Error in processTicksAndRejections as shown below**
<img width="877" alt="image" src="https://github.com/user-attachments/assets/9305da48-c905-48f6-ba3d-7656d17cb5ba">

2024-07-19 20:05 UTC, kylepham commented
> I have followed the below steps to test the PR
> 
> _In frontend repository_
> 
> * git checkout Hoang_fix_approve_and_apply_suggested_changes_on_a_task
> * npm install
> * npm run start:local
> 
> _In backend repository_
> 
> * git checkout Hoang_fix_approve_and_apply_suggested_changes_on_a_task
> * npm install
> * npm run build
> * npm start
> 
> On logging as dev admin or owner, Dashboard is not loading and there are backend errors as shown below: ![image](https://private-user-images.githubusercontent.com/90600253/350496527-0e9234e2-7749-40cd-a9ac-fb67245c7b7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTk3NTIsIm5iZiI6MTcyMTQxOTQ1MiwicGF0aCI6Ii85MDYwMDI1My8zNTA0OTY1MjctMGU5MjM0ZTItNzc0OS00MGNkLWE5YWMtZmI2NzI0NWM3YjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDIwMDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYzY4MDI1OWFhZDNhOTE1NGU0YzkxZWE4ZmE1OGQ0YTQ3NWU5YzdkMGMwNjA3ZDhhMDAzNjU4MTM0YTFlYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GS7jO5XuaiY3IbszDZs-CN7dZ7xadn6zWi-lZBFWVd0)
> 
> <img alt="image" width="765" src="https://private-user-images.githubusercontent.com/90600253/350496690-bbe13940-a779-4934-9cc3-3bd6762be61c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTk3NTIsIm5iZiI6MTcyMTQxOTQ1MiwicGF0aCI6Ii85MDYwMDI1My8zNTA0OTY2OTAtYmJlMTM5NDAtYTc3OS00OTM0LTljYzMtM2JkNjc2MmJlNjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDIwMDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZjNmOWExODFmNmUwNzM4ZmE0ZDc0MmIwY2E0Mzg4NWE5MDk1MjMwYjRlMjBlNjVjM2FiNWQ4ZGQxYzQ5MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8CU1SRuJ1oLoO8oDikWP8yMMOkQNzu43Nh9x6BsBx3I">
> **Error in processTicksAndRejections as shown below** <img alt="image" width="877" src="https://private-user-images.githubusercontent.com/90600253/350497147-9305da48-c905-48f6-ba3d-7656d17cb5ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTk3NTIsIm5iZiI6MTcyMTQxOTQ1MiwicGF0aCI6Ii85MDYwMDI1My8zNTA0OTcxNDctOTMwNWRhNDgtYzkwNS00OGY2LWJhM2QtNzY1NmQxN2NiNWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDIwMDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZjU3YzcwM2YxNWFmZTRiYmRlYzc3M2MxNzM2MDdkMjg5ZDM1NWQxMTY2NWM5YmUxOGQ1NDAxMjE0ZmE3ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MlLkvAdDkF4VIbBVW2y8jCs7HcXhI9c-95-ZfMYGsXY">

Hi @kabraambika, this is unrelated to my PR. I have merged the latest commits on development branch. Please do a `git pull --rebase` to apply the changes and test from there. Thank you.

2024-07-19 20:08 UTC, kabraambika commented
Thanks for the quick response @kylepham, I will apply the changes and test again.

2024-07-19 20:51 UTC, kabraambika approved these changes
After the rebase, I reviewed the frontend PR and the related backend PR. The feature is working as intended for both the devAdmin and Owner roles, as demonstrated in the attached video.

https://github.com/user-attachments/assets/3ef08cd5-3967-485a-bc6e-73546874c34d

2024-07-21 00:55 UTC, pavanswaroopl approved these changes
Great execution,

Reviewed everything perfectly works fine.

https://github.com/user-attachments/assets/709815ad-15fa-43d2-9740-25ad2d497ec9

<img width="1440" alt="Screenshot 2024-07-20 at 7 48 45 PM" src="https://github.com/user-attachments/assets/10cb9fa4-c6b6-4130-bd4b-78fc7a121037">
<img width="1440" alt="Screenshot 2024-07-20 at 7 50 20 PM" src="https://github.com/user-attachments/assets/18f05116-35b5-4739-9efd-5d2c218905fb">

2024-07-21 12:21 UTC, aaryaneil approved these changes
Tested the PR and all the cases were working as expected.

https://github.com/user-attachments/assets/7902fc38-3727-42c3-9bb7-0727edb0dca9


https://github.com/user-attachments/assets/a7dc411f-ec96-4789-a048-a0445be8c8f2


https://github.com/user-attachments/assets/9ed8fc9b-60fb-4e7e-afea-40dc37383660

2024-07-25 02:30 UTC, one-community commented
Thank you all, merging!

2024-07-25 02:30 UTC, merged