Jay Force new password for new users
OneCommunityGlobal/HighestGoodNetworkApp pull request #2417
Opened 2024-07-04 20:53 UTC by jayyy-s

# Description
High priority issue to force a new password for new users. Previously, users could choose the same default password as their new one
![345946161-48d890ff-e9ca-44fa-84fc-452a321b18f0](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71467346/e3db9782-f2df-45ae-b318-9025efc35aed)

## Related PRS (if any):
This frontend PR is related to the #1020 backend PR.

## Main changes explained:
- Update `components/ForcePasswordUpdate/ForcePasswordUpdate.jsx` to show same password feedback if receiving a 400 error

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links→ User Management→Create New User
6. create a new user (any role)
7. log out 
8. log into new user account with default password
9. when prompted to make a new password, attempt to use the default password `123Welcome!`

## Screenshots or videos of changes:
See backend PR

2024-07-04 23:18 UTC, nyelmela approved these changes
The PR 2417 has been tested and works as intended. Checked into the current branch, ran npm install and npm run start:local to run the PR locally, and cleared site data/cache. Logged in as an admin user, navigated to Dashboard → Other Links → User Management → Create New User, and created a new user with any role. Logged out and logged into the new user account with the default password. When prompted to create a new password, attempted to use the default password 123Welcome! and received an error indicating that the "new password cannot be the default password", as intended. Everything works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/0ff0f947-dd22-4d63-8bdf-80842a348593

2024-07-05 18:00 UTC, vijay10pk approved these changes
Changes are working as expected.

**Creted a new user using admin account**
<img width="1398" alt="Screenshot 2024-07-05 at 1 50 20 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/273bd3a8-a2bd-4345-8056-f5dc67b9e226">

**Attempt to use the default password**
<img width="733" alt="Screenshot 2024-07-05 at 1 52 26 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/c66a4220-aba8-4be0-aef3-e53eb893491b">

**Allows only a different password other than default password**
<img width="1423" alt="Screenshot 2024-07-05 at 1 56 54 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/ecea45d5-9023-42a8-b6e7-18a695f16517">

2024-07-05 20:15 UTC, nikhilpittala16 submitted a review, later dismissed
I tested the PR with the given instructions. it works perfectly fine and screenshots below are a proof of that.
creating new user
![Screenshot (21)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/142841075/847d4762-a3d7-487a-803c-2b1d2707884f)
Trying to use default password as new password and it doesn't allow 
![Screenshot (22)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/142841075/edc323de-3b22-4db0-a80a-927d5b09a7f3)
it works for any other  passwords.
![Screenshot (23)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/142841075/5f5f985a-a49d-49da-a7cf-498628bffc64)

2024-07-05 23:58 UTC, sahithidhulipala9 approved these changes
When attempted to create using the default password, pop up appeared that can't use the default password, tried with another worked successfully.
![Screenshot (104)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60340387/bcd9a96b-8c5f-48a2-9e0f-ff5c072fc69e)
![Screenshot (105)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60340387/face0957-6023-4a7b-81e8-c4b9855aedc2)

2024-07-06 22:48 UTC, JatinAgrawal94 submitted a review, later dismissed
Changes work as expected. Good Work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/a779e4ae-151e-405a-a669-ddaf43f5b098

2024-07-06 23:33 UTC, jinxyou approved these changes
I tried to create a new user, and use the default password to log in. All the functions seem to work nicely. Great work! 
![Screenshot 2024-07-06 173107](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13797542/f6a72960-0972-4fef-8d62-1d2604ae07f1)
![Screenshot 2024-07-06 173136](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13797542/ffc62725-5e1b-42cb-b775-fe3cef5c4d06)
![Screenshot 2024-07-06 173151](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13797542/fd454ef8-62ce-4fa3-8288-60ad1221962d)
![Screenshot 2024-07-06 173157](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13797542/4eee64e1-366b-4a30-9185-d1b43dee27de)
![Screenshot 2024-07-06 173216](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13797542/349192f8-2b2b-46b7-9a78-23fe49a46e0b)

2024-07-14 09:43 UTC, aaryaneil approved these changes
Tested the PR and the changes work as expected. Good work.

https://github.com/user-attachments/assets/a2936c38-3bb6-4188-ae2f-bc4a32b57f55

2024-07-22 21:24 UTC, Gauravmg6 approved these changes
Using the new credentials with the default password will redirect to setup a new password and the same password being used will continue the loop of setting a new password. Ideally, I didn't see an alert stating not to use the default password but indirectly the functionality works fine.

![Screenshot 2024-07-22 171842](https://github.com/user-attachments/assets/0a715833-c1a5-4969-a6fb-d2fdcf763184)
![Screenshot 2024-07-22 171924](https://github.com/user-attachments/assets/8ea15920-544a-4568-9776-65994a627d4b)

2024-07-26 18:45 UTC, Pranay-ai requested changes
Hey @jayyy-s 
The Password doesnt Change But when the user Tries to keep the 123Welcome!password 
![image](https://github.com/user-attachments/assets/f888cfa3-8db0-4a44-b503-f954b6434963)
It show that Password has been changed
It would be Better we Do not allow the user to enter the password 123Welcome! in first place an throw an error when updating.
Thank You

2024-07-31 13:29 UTC, Annezhang673 submitted a review, later dismissed
Works as expected. I created a new user account and use default password when asked to set a new password, an error occurred. I tried to change to a non default password, it is allowed by the system. Works as expected. Good job.
<img width="1348" alt="PR2417_1" src="https://github.com/user-attachments/assets/9f031d16-cd4c-4f98-a83f-ca5f86b4336e">
<img width="1431" alt="PR2417_2" src="https://github.com/user-attachments/assets/a3ee6277-340c-4041-a5a6-8e57cf0ba7d4">

2024-08-05 01:39 UTC, one-community commented
Thank you all. Address the 1 requested change Jay and I'll merge this one.

2024-09-05 17:33 UTC, AJAYINAVOLU requested changes
Changes are not working as expected. When I create a new user and use the default password: 123Welcome!, it redirects the page to create a new password. On the change password page, when I use the default password: 123Welcome!, it redirects back to the login without any error. 

New User created -> Login Page -> Change Password -> Login Page -> Change Password

This infinite cycle is created when I use the default password: 123Welcome! and the error message is not displayed.

<img width="955" alt="PR 2417" src="https://github.com/user-attachments/assets/43361239-c1d1-40f4-ae61-c0aa52a1cf85">

2024-09-07 02:09 UTC, sri0606 requested changes
@jayyy-s , I have reviewed the changes you made and found issues:

* I created a new user and tried to log in.
* I tried to set `123Welcome!` as new password and it was successful.
* It redirected me to login page and when I use those credentials, it redirects back to `New password` page.

Please fix this. I suggest you to check the initial password and new password to compare if they are same, if so throw an error on that page itself.


https://github.com/user-attachments/assets/e03fbabe-5b26-49ae-966e-5848ee051e5a

2025-02-13 03:42 UTC, sri0606 approved these changes

2025-02-13 03:45 UTC, sri0606 commented
@AJAYINAVOLU , can you check if the issue you mentioned still persists on your end? If it doesn't, please approve, so that PR can be ready to be merged. I had the same issue, but not anymore.

2025-02-28 19:24 UTC, saishekhar10 approved these changes
The changes work as expected, I'm getting an error code 400 on the console when I try to input the default password as the new password. 

https://github.com/user-attachments/assets/5ddd96df-8953-4a8a-adff-fb6519a7522f

2025-05-02 04:42 UTC, one-community commented
Thank you all, merging!

2025-05-02 04:43 UTC, merged