Logeshwari - Fix Role “i” icons dialogue error message in Permissions Management
OneCommunityGlobal/HighestGoodNetworkApp pull request #2420
Opened 2024-07-06 00:46 UTC by Logeshwari-Renu

# Description
![Error Msg 1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/166590596/b46ccf00-2ed7-493f-b647-9336e6b2efa1)
![Error Msg 2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/166590596/7c9fb458-2b7e-4a77-8ef6-2b7229bfebea)

## Related PRS (if any):
To test this backend PR you need to checkout the backend development PR.

## Main changes explained:
Made changes in the PermissionsManagement component to fix the "handleModalOpen is not defined" error. 

## How to test:
1. Check into current branch.
2. Do `npm install` and `npm run start:local` to run this PR locally.
3. Clear site data/cache.
4. Log as owner user.
5. Go to the Dashboard → Other Links → Permission Management. 
6. Select any Role.
7. Check if dialog box is displayed on selecting the "i" icon next to Save and Delete Option.
8. Verify "handleModalOpen is not defined" error is not in console.

## Screenshots or videos of changes:

Before Changes

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/166590596/c24201c2-46bb-4dec-b98a-1ab4a9a3a84a

After Changes

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/166590596/def36d5c-35df-4178-8e53-e259563545d0

2024-07-07 04:46 UTC, JatinAgrawal94 requested changes
Page comes out blank with errors in console.
<img width="1506" alt="Screenshot 2024-07-06 at 9 45 41 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/bdfed4bf-268e-477a-9683-65917ae6234c">

2024-07-08 22:37 UTC, Logeshwari-Renu commented
> Page comes out blank with errors in console. <img alt="Screenshot 2024-07-06 at 9 45 41 PM" width="1506" src="https://private-user-images.githubusercontent.com/47699187/346311851-bdfed4bf-268e-477a-9683-65917ae6234c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NzgzMTEsIm5iZiI6MTcyMDQ3ODAxMSwicGF0aCI6Ii80NzY5OTE4Ny8zNDYzMTE4NTEtYmRmZWQ0YmYtMjY4ZS00NzdhLTk2ODMtNjU5MTdhZTYyMzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDIyMzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZDYzODEzOGNjNzRjMDdkNWZiOTQ1YTljMjZkZmYzZTNkYTg2YzBhMWU3M2E4NTZkYzJkYzVhYThlMDUwYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uPViDRd_gL9JQLJSVFexgc1KRZkelpO2viU-rL8OO2E">

Hi, can you review again

2024-07-11 03:48 UTC, vijay10pk approved these changes
Changes works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/def18977-2956-4021-8ecd-e5aeb1ed4654

2024-07-14 07:54 UTC, aaryaneil approved these changes
Tested the PR and the changes work as expected.
<img width="1552" alt="Screenshot 2024-07-14 at 2 54 00 AM" src="https://github.com/user-attachments/assets/0da0fb00-9f32-4abf-b6b7-9c3d4243f585">
<img width="1552" alt="Screenshot 2024-07-14 at 2 54 04 AM" src="https://github.com/user-attachments/assets/e816d381-d5ad-4e23-bc07-0dc657a88ed2">

2024-08-22 23:40 UTC, SnelPatare approved these changes
Tested PR. Works fine

![image](https://github.com/user-attachments/assets/e83639ad-6392-4ed1-adc0-51f80bacc4d8)

![image](https://github.com/user-attachments/assets/a9d88274-9c74-447e-8578-95d096d1fc5b)

2024-09-01 01:04 UTC, sri0606 requested changes
Hello, I've tested the changes you made and found some issues. Even though the pop-up is supposed to only work for Owner account,  I tried this with an Admin account and got some errors and it kind of bugs out and any click doesn't work unless I refresh the page.


https://github.com/user-attachments/assets/aba8baef-3c97-4c5c-a806-aa523af01a28


![image](https://github.com/user-attachments/assets/f5677e61-ac6d-4b5b-88cb-fde30fec453a)

2024-09-06 05:19 UTC, vedantg24 requested changes
Tested the PR, but I got an error. It failed to compile due to naming mismatch. I have attached the screenshots for the same:
![Screenshot 2024-09-05](https://github.com/user-attachments/assets/fc15808f-e69f-46f4-90fd-5a92078f4097)
![Screenshot 2024-09-05_1](https://github.com/user-attachments/assets/8faef34f-65d2-4c5c-9145-50ec8fc3c873)

2024-09-06 08:13 UTC, sud306 commented
Hello,
I tried to checkout with the mentioned branch but facing issue.
Attached is the screenshot.

![5  PR2420_1](https://github.com/user-attachments/assets/b2ae9852-e69a-4868-b8b5-e0ca48e9afb8)
![5  PR2420_2](https://github.com/user-attachments/assets/033b8ad6-5e27-4fe1-8110-deda7505235d)

2024-09-10 07:23 UTC, ashayk9 requested changes
I tested the PR, but encountered a compilation error due to a naming mismatch. I’ve attached screenshots illustrating the issue.
![Screenshot 2024-09-10 at 12 19 15 AM](https://github.com/user-attachments/assets/85301c24-d4ed-4cf4-bfe0-0bfa266956cb)
![Screenshot 2024-09-10 at 12 19 34 AM](https://github.com/user-attachments/assets/367a8c3f-675a-4240-9969-a81d1ff6ea31)

2024-09-14 19:56 UTC, crystallow1168 requested changes
Hi @Logeshwari-Renu,

I was having issues running the app due to the mismatch file name 'roleInfoModal' under src/UserProfile/EditableModal/roleInfoModal. After changing the file name to RoleInfoModal, I was able to test the changes. Below are my findings:

https://github.com/user-attachments/assets/7ab9a0db-8016-4cc7-94f1-665fef58c2b9



✅ When clicked on the "i" icon, dialog box is displayed

![image](https://github.com/user-attachments/assets/840d59fa-1bba-4e8c-a88e-8dde4ca5b502)

❗️The text in the dialog box are not clearly visible when in dark mode

2024-09-15 01:54 UTC, Shreyav2000 requested changes
While testing this PR, I encountered the following errors:

The app failed to compile due to a missing file: RoleInfoModal.jsx. It seems the file name on disk does not match the one referenced in src/routes.js.
The console showed errors related to unhandled processes, which could potentially be affecting the system behavior.
I have attached screenshots for your reference. Please review and let me know if there are any steps I missed or if further changes are required.
<img width="1727" alt="Screenshot 2024-09-14 at 8 52 21 PM" src="https://github.com/user-attachments/assets/2796c643-446f-49a0-8082-6ca1eaad0a11">
<img width="1728" alt="Screenshot 2024-09-14 at 8 52 33 PM" src="https://github.com/user-attachments/assets/47e7519b-842e-4f2c-bd5f-9c8c13c256b1">

2024-09-15 03:52 UTC, nishitag5 requested changes
Blank screen appears with errors in console.
![image](https://github.com/user-attachments/assets/6fb49e35-8b85-4025-a43f-03851653d594)

2024-09-17 03:44 UTC, SFA23SCM35V requested changes
Upon running 
![1](https://github.com/user-attachments/assets/1f85b4f2-1270-4cf8-a18e-07683e5eb8be)
![2](https://github.com/user-attachments/assets/1e7dd997-e588-4da9-bb5c-6c71ac9dc1d6)
the application locally, only a black screen was displayed.

2024-09-18 21:01 UTC, geetamatkar commented
Hi @Logeshwari-Renu ,
Tested this PR but getting this error.

<img width="1106" alt="PR2420" src="https://github.com/user-attachments/assets/c4b6a5e9-cfde-4763-9fdc-378b28d0a863">

2024-09-20 06:11 UTC, neeharikakoniki requested changes
The page appears blank, and errors are displayed in the console.

![image](https://github.com/user-attachments/assets/3c98d39a-e857-46f2-a102-702c69617320)

2024-09-21 21:50 UTC, saurabhshetty29 commented
There is some issue, not able to load. Please find the screenshot with console log.
<img width="1410" alt="Screenshot 2024-09-21 at 2 49 03 PM" src="https://github.com/user-attachments/assets/11fa772c-0cda-4b1a-af02-cc2d0ff65973">

2024-09-22 00:34 UTC, nevatiarishabh requested changes
I tested the PR. However, the PR has some issues. The application cannot find file: 'RoleInfoModal.jsx' as it does not match the corresponding name on disk.

<img width="1440" alt="Screenshot 2024-09-21 at 5 31 59 PM" src="https://github.com/user-attachments/assets/4ec6472b-6e91-4b8e-b21d-fb336c4dcedb">
<img width="1048" alt="Screenshot 2024-09-21 at 5 32 18 PM" src="https://github.com/user-attachments/assets/b7ae6df7-3012-4eb3-840f-dec6e8c000ac">

2024-09-28 18:44 UTC, lcohen730 requested changes
Loading blank page with multiple errors in the console:

- Uncaught Error: Cannot find module 'components/UserProfile/EditableModal/RoleInfoModal'
- index.js:1 ./src/routes.js
Cannot find file: 'RoleInfoModal.jsx' does not match the corresponding name on disk: './src/components/UserProfile/EditableModal/roleInfoModal.jsx'.
- ./src/components/WeeklySummariesReport/FormattedReport.jsx
Cannot find file: 'RoleInfoModal.jsx' does not match the corresponding name on disk: './src/components/UserProfile/EditableModal/roleInfoModal.jsx'.
- Uncaught ReferenceError: process is not defined

See attached screenshot for more details.

![Screenshot 2024-09-28 at 14 39 38](https://github.com/user-attachments/assets/5f8c03c3-2537-43e5-91b9-f618ae68d8fc)


And the one error I am getting in the terminal that is failing the app to compile is the Cannot find file: 'RoleInfoModal.jsx' does not match the corresponding name on disk: './src/components/UserProfile/EditableModal/roleInfoModal.jsx'. It looks like the routes.js file is referencing a file RoleInfoModal, but the file is actually named roleInfoModal. Just a capitalization difference with the r in role. R should be capital to match other files and fit React component naming conventions.

![Screenshot 2024-09-28 at 14 41 42](https://github.com/user-attachments/assets/d10771f1-f8a0-4efb-8888-bbdc23f24e00)

2024-10-02 19:09 UTC, mrinalini-raghavendran19 requested changes
Looks good to me, however I have a few changes to suggest. 

I have tested the following functionality by logging in as an `Owner`, I navigated to the `Permissions Management` section, selected a role and tested the modals by clicking the `i` and no errors appeared. Find below a screen recording of the same:

https://github.com/user-attachments/assets/478e7deb-fa7a-475d-9006-494742edef91

Suggestions to PR reviewers and dev:

1) There is a compile time error initially - this is due to case sensitivity with `roleInfoModal.jsx`, you can change this yourself to `RoleInfoModal.jsx` under `src/components/UserProfile/EditableModal/RoleInfoModal.jsx`. This will resolve any compile time errors

<img width="1470" alt="Screenshot 2024-10-02 at 11 50 00 AM" src="https://github.com/user-attachments/assets/f302d211-b4b6-4c3d-bfe5-948307c3cb2b">

2) For anyone facing any future errors after fixing above error - try clearing page data or test on incognito

3) In dark mode, the text in the modals is not clearly visible.

<img width="1470" alt="Screenshot 2024-10-02 at 12 08 51 PM" src="https://github.com/user-attachments/assets/73bd845a-3269-4a1f-978c-c131f1f5cf02">

Cheers!

2024-11-03 03:32 UTC, Rupa2400 approved these changes
PR #2420 I tested the PR review and is working as expected.

<img width="959" alt="PR_2420" src="https://github.com/user-attachments/assets/7866a2cb-e1c5-48ce-9d87-e95eedcf2cac">
<img width="959" alt="PR_2420_2" src="https://github.com/user-attachments/assets/bc065978-5bdf-4403-bf04-f558178caec5">

2024-11-06 19:19 UTC, AshritaCherlapally approved these changes
This code works as expected. When clicked on "i" icon in Permissions management tab, it perfectly displays the message in the dialog box. However, initially when i tried to start the server, I have got the error message saying RoleInfoModal.jsx does not match with roleInfoModal.jsx this can be changed by updating the file name. Apart from this everything works fine. Great job!

https://github.com/user-attachments/assets/456a854c-8d43-47f1-adbe-753d6908d95a

2024-11-09 07:01 UTC, audreydieuanh requested changes
There are compile errors due to the inconsistency between the file name when importing and the actual file name.

<img width="1512" alt="Screenshot 2024-11-09 at 12 57 49 AM" src="https://github.com/user-attachments/assets/59fe7fce-2d8d-4be8-885f-b284ee25dc4f">

2024-11-09 19:49 UTC, SupriyaSudini requested changes
I have encountered an error that was resolved by changing the file name from roleInfoModal.jsx to RoleInfoModal.jsx. After making this change, I tested the PR and found that everything is working as expected. The file name just needs to be updated.

![image](https://github.com/user-attachments/assets/449a1b23-52ef-4f23-b3cd-aa5dcead8dd3)

![image](https://github.com/user-attachments/assets/59b465af-2a0a-4a22-a4d2-7b5daa2868ae)

![image](https://github.com/user-attachments/assets/ecb8ecd4-a322-4b67-9ae0-e5004adf7862)

![image](https://github.com/user-attachments/assets/548d7555-0961-45e2-90f6-faa78c2d5621)

2024-12-07 01:17 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/16fdfd99-58af-467c-806e-9e74f9575f9a

2025-02-05 20:29 UTC, mikelambo7 approved these changes
Verified that dialog box is displayed on selecting "i". "handleModalOpen is not defined" error is not in console.
<img width="665" alt="Screenshot 2025-02-05 at 3 27 56 PM" src="https://github.com/user-attachments/assets/b12ad265-2f6e-4d60-a194-2ac655ae4c2d" />
<img width="564" alt="Screenshot 2025-02-05 at 3 28 14 PM" src="https://github.com/user-attachments/assets/a9669e8c-c788-4272-b767-16d54fb3f66e" />

2025-03-24 20:20 UTC, closed without merging