Fix: Responsive design for SEND EMAILS page
OneCommunityGlobal/HighestGoodNetworkApp pull request #2426
Opened 2024-07-06 22:45 UTC by deepthikannan

# Description
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83337914/d0863232-a9cd-4e43-9b49-d0a29ea29831)
…

## Main changes explained:
Updated Announcements.css: Added media queries to adjust the layout for various screen widths, ensuring that elements stack vertically around 800px and below.
Modified index.jsx: Adjusted component structure and styles to work with the new responsive design changes.
Verified the design: Ensured the layout works as expected at multiple breakpoints including 800px, 600px, 480px, and 375px.
…

## How to test:
1. check into current branch: git checkout deepthikannan-fix-email-ui
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other links→ Send email …
6. Verify the functionality of the SEND EMAILS page:
Ensure the editor and form elements stack vertically around 800px and below.
Test the page at various screen widths around 800px to ensure responsiveness.

## Screenshots or videos of changes:
![localhost_3000_announcements (2)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83337914/fde240c6-ade7-451a-9427-a7f575421417)

2024-07-06 23:30 UTC, nyelmela approved these changes
I have tested PR 2426 the changes on the current branch by following the steps provided: performed `npm install` and ran the PR locally, cleared site data/cache, logged in as an admin user, navigated to the dashboard, accessed Other Links, and then Send Email. I verified the functionality of the SEND EMAILS page, ensuring that the editor and form elements stack vertically around 800px and below. I also tested the page at various screen widths around 800px to ensure responsiveness. Everything works perfectly fine. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/90f60e71-1c7b-4e89-aeac-7640df7625bc

2024-07-07 01:58 UTC, sahithidhulipala9 approved these changes
Reviewed the PR 2426, responsiveness of the page is good at different screen widths. Working perfect.
![Screenshot 2024-07-06 215057](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60340387/db3da280-0512-4593-8b7b-6439ab68ca7a)
![Screenshot 2024-07-06 215141](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60340387/77040cfb-39ed-40a4-98d4-47ec503de9d2)

2024-07-08 18:52 UTC, vijay10pk approved these changes
Changes works as expected.
<img width="622" alt="Screenshot 2024-07-08 at 2 51 18 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/44ad996e-e632-4009-b706-6eccfd808455">
<img width="543" alt="Screenshot 2024-07-08 at 2 51 28 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/499086ee-575d-43ea-a978-3d05c0b93603">
<img width="522" alt="Screenshot 2024-07-08 at 2 51 43 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/ab432054-a4d4-4dfc-be8c-f192b530cafb">

2024-07-09 01:52 UTC, kdaga81 requested changes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60085629/5e4fbc69-e3d7-4a22-ae6b-c0b4869fdc18)

Can we add some margin for labels, buttons and textfield to make it more user friendly.

2024-07-09 17:16 UTC, Nahiyan-16 submitted a review, later dismissed
Hi @deepthikannan, great work on the collapsing feature for the form but I have some suggestions, please add some padding to the inputs and buttons. No element should be that close to the border. 

![Screenshot 2024-07-09 131644](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/1290bfd5-a03d-420c-8dc2-26d0fb7e6c1a)

2024-07-11 19:34 UTC, nikethaanand commented
The changes are working as expected, the alignment changes according to the screen size.

https://github.com/user-attachments/assets/9e9219ca-7743-4d40-ba0f-508e2762664a

2024-07-14 07:32 UTC, aaryaneil requested changes
Tested the PR and the changes work as expected but I feel the input fields need a little padding.
<img width="1552" alt="Screenshot 2024-07-14 at 2 31 28 AM" src="https://github.com/user-attachments/assets/37ec874b-c8fe-487d-a41b-19bc6837a2ed">

2024-07-16 23:45 UTC, JatinAgrawal94 submitted a review, later dismissed
Changes work as expected.

https://github.com/user-attachments/assets/9f4ca1fc-c307-4bdf-802d-d08086961408

2024-07-19 04:40 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.
![Screenshot (138)](https://github.com/user-attachments/assets/0a60af79-be52-48ab-86c2-a0526ffd18ee)
![Screenshot (139)](https://github.com/user-attachments/assets/ca3eb968-66f3-4af6-b394-144a9356da4e)
![Screenshot (140)](https://github.com/user-attachments/assets/79fddc3a-a798-4249-a661-42eac5cb0c0a)
![Screenshot (141)](https://github.com/user-attachments/assets/a56adcc6-670f-4def-a30a-dce000224874)

2024-07-21 04:33 UTC, Chetan0606 submitted a review, later dismissed
Followed the steps and verified. Everything looks fine. Here's a video of my observation

https://github.com/user-attachments/assets/f5f539a5-4015-4b48-8453-0ae80de4aaa8

2024-07-22 20:55 UTC, Gauravmg6 approved these changes
![Screenshot 2024-07-22 165302](https://github.com/user-attachments/assets/ae5245c4-d1f2-4f29-9eb0-913bab92329a)
![Screenshot 2024-07-22 165328](https://github.com/user-attachments/assets/251f37d8-2a70-486d-b3ee-c7889d3915f5)

Everything works fine.

2024-08-02 03:10 UTC, SatyashanthiT submitted a review, later dismissed
I tested PR 2426 by following the provided steps, ensuring the SEND EMAILS page is responsive. The layout transitions smoothly at various breakpoints (800px, 600px, 480px, 375px), with no overlapping issues. All elements are functional and user-friendly, and permissions for different roles are correct.  I recommend approving the PR as the changes work perfectly fine, and the responsiveness is well-implemented.


<img width="650" alt="ss-1" src="https://github.com/user-attachments/assets/3147e763-5422-4159-9f67-383c3494afe0">
<img width="290" alt="ss2" src="https://github.com/user-attachments/assets/c92166f0-acfa-4ceb-bf57-8201bfc4cece">
<img width="902" alt="ss-3" src="https://github.com/user-attachments/assets/a3f9d537-60a4-482d-959b-3ba8d2b46b3d">
<img width="905" alt="ss-4" src="https://github.com/user-attachments/assets/661c342f-b108-449b-a714-2f694b010991">

2024-08-02 18:58 UTC, Pranay-ai requested changes
Hey @deepthikannan 
I have reviewed the PR it's working as expected but i would suggest some changes in the component below
![image](https://github.com/user-attachments/assets/10e2eac2-5b8e-4ded-a42f-ab1d65899ed8)

It would improve the user experience if the buttons and input fields are smaller and their is some padding between them.
Thank You.

2024-08-17 23:18 UTC, deepthikannan commented
Hi, thank you for the feedback! I’ve added padding to the inputs and buttons as suggested to improve the spacing. Kindly please review again.
@Nahiyan-16 @Pranay-ai @aaryaneil @kdaga81 

![localhost_3000_announcements (4)](https://github.com/user-attachments/assets/6eb69c93-e460-410b-822d-44817009aa34)

2024-09-10 20:07 UTC, AJAYINAVOLU approved these changes
Changes are working as expected.

<img width="626" alt="image" src="https://github.com/user-attachments/assets/5115da14-28e3-4530-83b1-8a4e08bf3b00">

Thank You

2024-10-19 06:50 UTC, navya9989 commented
HI @deepthikannan I have tested this PR and checked the email functionality in different dimentions  I works good as expected. Here are the screenshots for Reference.
![PR 2426](https://github.com/user-attachments/assets/02854a51-8b74-43ce-940e-d16d5fd12fee)
![PR# 2426](https://github.com/user-attachments/assets/2d0e1026-58f9-420a-a4b5-80ad2ec53258)

2024-10-20 23:29 UTC, navya9989 reviewed
I works good as expected.

2024-11-06 03:40 UTC, deepthikannan commented
Hi @Pranay-ai @Nahiyan-16 @aaryaneil @kdaga81 , I have made the necessary changes could you kindly please review the PR again to get it merged!

2024-11-06 03:41 UTC, deepthikannan commented
> ![image](https://private-user-images.githubusercontent.com/60085629/346769721-5e4fbc69-e3d7-4a22-ae6b-c0b4869fdc18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NjQ1MTMsIm5iZiI6MTczMDg2NDIxMywicGF0aCI6Ii82MDA4NTYyOS8zNDY3Njk3MjEtNWU0ZmJjNjktZTNkNy00YTIyLWFlNmItYzBiNDg2OWZkYzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAzMzY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MjcwOWZmZjE2ZjExMWYzYjA2YTBlMTAwZjE4NTM4MGZlZjBjMzFlNDVjZjRhMWEzMjAzOGY2MzU5ZmUyYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NGMg50b2vPAsKZVpUISL11Lh1f16xDX6dR3OnHyFbII)
> 
> Can we add some margin for labels, buttons and textfield to make it more user friendly.

Hi I have made the changes could you kindly review it again to get it merged.  Thank you !!

2024-11-06 03:41 UTC, deepthikannan commented
> Tested the PR and the changes work as expected but I feel the input fields need a little padding. <img alt="Screenshot 2024-07-14 at 2 31 28 AM" width="1552" src="https://private-user-images.githubusercontent.com/39597927/348522003-37ec874b-c8fe-487d-a41b-19bc6837a2ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NjQ1MTMsIm5iZiI6MTczMDg2NDIxMywicGF0aCI6Ii8zOTU5NzkyNy8zNDg1MjIwMDMtMzdlYzg3NGItYzhmZS00ODdkLWE0MWItMTliYzY4MzdhMmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAzMzY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MmNlZDI4NDE4ZjgwYjg4ZmE0NDEwNzBlMTQ0OTVkMDE5NGI1ZThjOGQ1OWMyNTRjYjQ3MzhjMWJlYjVhZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w7Tv4SCCr1fCHc_LsJQwKoJdNCb6APYvqk4knRjjHRk">

Hi I have made the changes could you kindly review it again to get it merged.  Thank you !!

2024-11-06 03:42 UTC, deepthikannan commented
> Hi @deepthikannan, great work on the collapsing feature for the form but I have some suggestions, please add some padding to the inputs and buttons. No element should be that close to the border.
> 
> ![Screenshot 2024-07-09 131644](https://private-user-images.githubusercontent.com/71025942/347054091-1290bfd5-a03d-420c-8dc2-26d0fb7e6c1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NjQ1MTMsIm5iZiI6MTczMDg2NDIxMywicGF0aCI6Ii83MTAyNTk0Mi8zNDcwNTQwOTEtMTI5MGJmZDUtYTAzZC00MjBjLThkYzItMjZkMGZiN2U2YzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAzMzY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNDAxNTA0OWY3YWYwMTFjZTNmNTg5YWZmNjAzODEyMGQ0Yjc0Njk3MTA1ZTNjODRkNGVlODViMDhiZDZlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DUKfuTFpS6AYHu6j2Pa1rLpeJzUJzTWwcJ62ncu6WVk)

Hi I have made the changes could you kindly review it again to get it merged.  Thank you !!

2024-11-06 03:42 UTC, deepthikannan commented
> Hey @deepthikannan I have reviewed the PR it's working as expected but i would suggest some changes in the component below ![image](https://private-user-images.githubusercontent.com/65746692/354697020-10e2eac2-5b8e-4ded-a42f-ab1d65899ed8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NjQ1MTMsIm5iZiI6MTczMDg2NDIxMywicGF0aCI6Ii82NTc0NjY5Mi8zNTQ2OTcwMjAtMTBlMmVhYzItNWI4ZS00ZGVkLWE0MmYtYWIxZDY1ODk5ZWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAzMzY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYzdhMDI1NjZjNDUzMmIxY2M3MTYwZThlNjg2OTFmNzE2NWNhNmJkY2FiZjE0ODMxNjI2MzFiMDJhM2Y1NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BJ0arXwAmj9aYEcmq2HbQZPdYXAmoacSQv7rVtKCT9A)
> 
> It would improve the user experience if the buttons and input fields are smaller and their is some padding between them. Thank You.

Hi I have made the changes could you kindly review it again to get it merged.  Thank you !!

2025-01-17 19:26 UTC, honglinchen0524 approved these changes
Great work! The functionality of the SEND EMAILS page works perfectly. The editor and form elements stack accordingly. The TinyMCEs email editor box width also adjusts as intended. 


https://github.com/user-attachments/assets/42e130cd-1151-4110-ba93-667af7d1b68d

2025-03-11 07:18 UTC, koushi1906 commented
I have tested the PR, and the page renders responsively. One suggestion I have is to enhance the alignment of buttons and links in the header at 769px, as they appear slightly misaligned. Adjusting this would improve the overall layout.

<img width="1370" alt="Screenshot 2025-03-11 at 2 15 47 AM" src="https://github.com/user-attachments/assets/dbc6dc91-a53c-4544-9bfa-f736a38f343e" />

2025-03-28 00:05 UTC, smohansatyaram approved these changes
Layout adjusts correctly at all breakpoints (800px, 600px, 480px, 375px).

No overlapping elements; editor and form stack vertically as needed.

All UI components remain functional and user-friendly.


![Screenshot 2025-03-27 190502](https://github.com/user-attachments/assets/4cbc0b1b-da13-404b-9dd4-a2d70003ac74)
![Screenshot 2025-03-27 190453](https://github.com/user-attachments/assets/e57b9239-1d8f-48db-b9d6-b61109b40e95)
![Screenshot 2025-03-27 190414](https://github.com/user-attachments/assets/734f655c-020c-4ebd-a01a-c1d9380c559e)
![Screenshot 2025-03-27 190400](https://github.com/user-attachments/assets/30b6c8e4-8d6b-42d1-8463-ae23d6363b2b)

2025-05-07 03:05 UTC, one-community commented
Thank you all, merging!

2025-05-07 03:05 UTC, merged

2025-05-09 00:27 UTC, rahulprasad2823 reviewed
I checked out the branch and ran npm install to set up the project locally. After clearing the site data and cache, I logged in as an admin user and navigated to Dashboard → Other links → Send email. I verified the functionality of the SEND EMAILS page and confirmed that the editor and form elements stack vertically as expected when the screen width is around 800px and below. I also tested the page across various screen widths near 800px to ensure the layout remains responsive and behaves correctly.
![Screenshot 2025-05-08 202443](https://github.com/user-attachments/assets/10224347-168f-48df-a337-2111d12dd2e0)