Leo make it so i can delete and then add a team without saving
OneCommunityGlobal/HighestGoodNetworkApp pull request #2436
Opened 2024-07-09 00:16 UTC by Chuehleo

# Description
![1720481133004](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/ae9da09a-fb4c-4f47-8335-6f5f690942a6)

## Related PRS (if any):
…

## Main changes explained:
- Update UserTeamsTable.jsx: Modified the component to ensure the "Assign Team" and "Delete" buttons work immediately upon being clicked, without requiring a save
- Remove Save Button in UserProfile.jsx: Removed the save button in the Teams tab since changes are now saved directly
- Enable the Assign team and delete button in every condition
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ User→ View Profile→…
6. verify function the "Assign Team" and "Delete" button works immediately when clicked
7. verify toast notifications appear when a team is successfully assigned or deleted
8. verify the save changes button was not showing in the teams tab

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/43b38ebb-03c6-42a9-8e18-58d61655fa0a

## Note:

2024-07-09 02:01 UTC, vijay10pk approved these changes
All the changes works as expected.
<img width="1419" alt="Screenshot 2024-07-08 at 9 58 22 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/c9f5fb99-429c-40a7-87cb-517a0d2deee6">
<img width="1428" alt="Screenshot 2024-07-08 at 9 58 37 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/a55327f1-617c-4b21-841c-b32b07f9463a">

2024-07-11 19:07 UTC, nikethaanand commented
All the changes work correctly, able to assign team and remove team for a user.

https://github.com/user-attachments/assets/37d311ff-e755-4ae7-959c-7f0ebae3d9a1

2024-07-12 03:45 UTC, sahithidhulipala9 approved these changes
PR working as expected. Toast messages appearing when team is created, assigned and deleted. 
![Screenshot (110)](https://github.com/user-attachments/assets/191406f3-bf4b-4bd7-8346-461ea1976db6)
![Screenshot (111)](https://github.com/user-attachments/assets/90caefb1-0dc1-4170-a696-486b8237f276)

2024-07-13 00:30 UTC, JatinAgrawal94 requested changes
When I try to add a profile to multiple teams, It asks me to save changes. Which it shouldn't. Please fix that.


https://github.com/user-attachments/assets/00a21a94-dab1-439a-8648-008f5449d10c

2024-07-14 02:22 UTC, aaryaneil approved these changes
Tested the PR and I was able to add teams and remove them and the results were updated quickly.
<img width="1552" alt="Screenshot 2024-07-13 at 9 20 07 PM" src="https://github.com/user-attachments/assets/23c360cb-7754-49ab-825a-94d630dfddb9">
<img width="1552" alt="Screenshot 2024-07-13 at 9 20 12 PM" src="https://github.com/user-attachments/assets/6e8a5296-8a22-4941-a73b-7c17163b9752">
<img width="1552" alt="Screenshot 2024-07-13 at 9 20 18 PM" src="https://github.com/user-attachments/assets/cbe7f36c-b78f-45e0-aa15-6f7341dccb0e">
<img width="1552" alt="Screenshot 2024-07-13 at 9 20 20 PM" src="https://github.com/user-attachments/assets/a2a7b321-04bd-4c57-9d81-d061db3568d4">

2024-07-16 01:40 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected. Teams are getting assigned and deleted with popups and save changes button is not showing in teams tab.
![Screenshot (93)](https://github.com/user-attachments/assets/2e2037c5-91a0-46d5-82a6-8fdfb5bdfd8e)
![Screenshot (94)](https://github.com/user-attachments/assets/ccef76f3-84b9-49ab-b91e-31d421be1c72)
![Screenshot (95)](https://github.com/user-attachments/assets/7141bbe7-de69-449f-b4c2-a4d8ef04290a)

2024-07-25 19:01 UTC, Pranay-ai requested changes
Hey @Chuehleo 
 I was Testing Out the PR i ended up getting a compile error
Failed to compile.

./src/routes.js
Cannot find file: 'RoleInfoModal.jsx' does not match the corresponding name on disk: '.\src\components\UserProfile\EditableModal\roleInfoModal.jsx'.

2024-07-25 21:00 UTC, Pranay-ai reviewed
Hey @Chuehleo,

The functionality works well in desktop view, but when I tested it in mobile view, the "Save Changes" button still appears in the team modal. Additionally, when switching between desktop and mobile views, I'm prompted to save changes, and the same issue occurs in the reverse scenario.

2024-08-24 00:03 UTC, closed without merging