Changes to display specific error
OneCommunityGlobal/HighestGoodNetworkApp pull request #2440
Opened 2024-07-09 05:36 UTC by DiyaWadhwani

# Description
Updating the Last Name on the User Profile to an initial throws a 400 error with a localhost webpage error saying "An error occurred while attempting to save this profile"

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.

## Main changes explained:
- Displaying the error returned from backend

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. View Profile > Change the last name to an initial
6. Verify the localhost:3000 shows the error 'Path 'lastname' ('[_your entered initial_]') is shorter than the minimum allowed length (2).

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54880903/1b4edeac-f9d4-4cf5-a17d-e7404f50988e

2024-07-10 02:54 UTC, vijay10pk approved these changes
All the changes work as expected. Tried to change the lastname from "Admin" to "A" and error message popped up as expected.

<img width="1428" alt="Screenshot 2024-07-09 at 7 49 39 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/4315c63e-f365-4dc5-96ea-52c1d000fc67">

<img width="1428" alt="Screenshot 2024-07-09 at 10 51 34 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/46b3ae86-0765-43a4-8b61-2c248d2e8a07">

2024-07-10 22:47 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.
![Screenshot (69)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/142841075/5370e5ee-dea8-4167-85a7-5275c4ef6cc5)

2024-07-10 23:12 UTC, nyelmela requested changes
I encountered an issue while testing this PR: the application failed to compile due to a case sensitivity error with the import statement for `RoleInfoModal`. The file on disk is named `roleInfoModal.jsx`, but the import statement in `routes.js` is using a different casing. I updated the import statement in `routes.js` to match the exact case of the file name on disk (`import RoleInfoCollections from '/components/UserProfile/EditableModal/roleInfoModal'`), but I still encountered the same issue. 

Before:
<img width="960" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/d7b893c5-2c80-4d37-b7f0-99abab110a14">

After:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/181ea97c-9d01-44df-9a65-a84356b83408)

2024-07-11 18:48 UTC, nikethaanand commented
All changes worked as expected. On Editing the username and setting the last name to a size less than two, an error pops up as mentioned above with a warming.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47215795/16d02b23-24c6-4b56-86b2-359705235d50

2024-07-12 23:16 UTC, JatinAgrawal94 approved these changes
Changes work as expected. Good work.

https://github.com/user-attachments/assets/f6574d3d-5de8-4269-91a8-ea29bd847e7b

2024-07-13 01:43 UTC, kdaga81 approved these changes
<img width="286" alt="image" src="https://github.com/user-attachments/assets/0930e29b-d93f-4c0e-8991-2027551b5891">

Getting the localhost popup with the required error message

2024-07-13 04:13 UTC, sahithidhulipala9 approved these changes
Tested the PR & the prompt says that password cannot be less than 2 characters
![Screenshot (113)](https://github.com/user-attachments/assets/773097fe-782b-451a-8323-cc5205428cf1)

2024-07-13 07:51 UTC, aaryaneil requested changes
I encountered an issue while testing the PR and the code failed to compile as the RoleInfoModal.jsx does not match with the one in the src folder.
<img width="1552" alt="Screenshot 2024-07-13 at 2 48 59 AM" src="https://github.com/user-attachments/assets/6085e9a7-f30a-46f7-acf3-1ee1ec1dc6cd">

2024-07-17 22:53 UTC, DiyaWadhwani commented
> I encountered an issue while testing this PR: the application failed to compile due to a case sensitivity error with the import statement for `RoleInfoModal`. The file on disk is named `roleInfoModal.jsx`, but the import statement in `routes.js` is using a different casing. I updated the import statement in `routes.js` to match the exact case of the file name on disk (`import RoleInfoCollections from '/components/UserProfile/EditableModal/roleInfoModal'`), but I still encountered the same issue.
> 
> Before: <img alt="image" width="960" src="https://private-user-images.githubusercontent.com/123037122/347627642-d7b893c5-2c80-4d37-b7f0-99abab110a14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNTY5NTAsIm5iZiI6MTcyMTI1NjY1MCwicGF0aCI6Ii8xMjMwMzcxMjIvMzQ3NjI3NjQyLWQ3Yjg5M2M1LTJjODAtNGQzNy1iN2YwLTk5YWJhYjExMGExNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QyMjUwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTIyM2QzZGNmZGFmMGNjNjNhOTE2ZTIxNWNmYTAzZGJhNzVlYTc3NjRiYzc2ZjdiYWNmZmQzYWUzNmY2YmI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iaKkcqQ3SDxlhtc5XyLHdl1Ts6KLqNL33YdcVNCozt0">
> 
> After: ![image](https://private-user-images.githubusercontent.com/123037122/347627950-181ea97c-9d01-44df-9a65-a84356b83408.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNTY5NTAsIm5iZiI6MTcyMTI1NjY1MCwicGF0aCI6Ii8xMjMwMzcxMjIvMzQ3NjI3OTUwLTE4MWVhOTdjLTlkMDEtNDRkZi05YTY1LWE4NDM1NmI4MzQwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QyMjUwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjM4ZTFlNjkwMzNlNjBlOTA4MmVjMThmMzVkNjJjNTVjMjQ3NzgzODA1ZTIzOTY4NzI4YmJhYTU2OTQ5ZjIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MxURWcyvUkTGGV18gDB_VqISMZmOECE5QwSzzNFaj9s)

Hi, this issue has been resolved and was an error being caused due to the latest dev branch changes.

2024-07-21 12:51 UTC, aaryaneil approved these changes
Tested the PR and when using a single letter for the last name an popup error is displayed.
Also a suggestion when the job title is missing the error says "Path jobTitle.0 is required" which seems a little odd. I know the PR isn't for that but still thought I'd mention it.
<img width="1532" alt="Screenshot 2024-07-21 at 7 47 57 AM" src="https://github.com/user-attachments/assets/cbaf7aca-36b3-4bf6-80c8-4ffe9f0f8b4e">

<img width="1532" alt="Screenshot 2024-07-21 at 7 48 17 AM" src="https://github.com/user-attachments/assets/97df9d34-d617-492f-8e5c-27c63e80676d">

2024-07-26 15:54 UTC, Pranay-ai requested changes
Hi @DiyaWadhwani,

The recent changes are working as expected overall, but I've noticed a few bugs.

When I initially set the last name with just an initial, an alert is triggered.
If I then immediately change the last name to the required minimum of 2 letters, an error message still appears, even though the changes are saved.
To improve this, it would be better to disable the save button when the entered last name is only one letter, preventing the alert from being triggered in the first place.


Thank you!

https://github.com/user-attachments/assets/980017b7-7b39-4e80-aa98-ae74604034af

2024-08-02 07:07 UTC, jayyy-s commented
I ran into the same issue with RoleInfoModal. However, after changing the file name, I was able to replicate the behavior and confirm that your changes work correctly.

![image](https://github.com/user-attachments/assets/3760e540-6196-4d15-960a-d1836df96ce4)

2024-08-15 06:55 UTC, Parth-tech approved these changes
Hey Diya,

The PR works as intended and the codebase looks good too. Great job done.

`Image Reference:`
<img width="1440" alt="Screenshot 2024-08-14 at 11 31 33 PM" src="https://github.com/user-attachments/assets/4cf1791e-2e74-44f3-89f7-9bd6c14add9b">
<img width="1440" alt="Screenshot 2024-08-14 at 11 31 49 PM" src="https://github.com/user-attachments/assets/053b8f4f-bae3-4b26-a72e-dbc04a3112f7">

2024-08-16 18:58 UTC, SnelPatare approved these changes
I tested the PR. It is working well. I changed the RoleInfoModal.jsx file name manually. 

![image](https://github.com/user-attachments/assets/4d67b743-4d99-408f-9982-3a5d0ac0fc2c)

2024-08-16 19:43 UTC, SMitta11 requested changes
While testing this PR I am getting error :Cannot find file: 'RoleInfoModal.jsx' does not match the corresponding name on disk:'./src/components/UserProfile/EditableModal/roleInfoModal.jsx'.
So I checked routes.js and in this file name is RoleInfoModal whereas the actual file is roleInfoModal.jsx
Attaching screenshot of error:
![PR 2440](https://github.com/user-attachments/assets/40d06a4f-8838-4e5c-89bf-3b7d37f09eb8)

2024-08-17 17:00 UTC, AnkitLall requested changes
I have tested the feature according to the instructions in the PR and identified a few issues:

1. When running the application, the following error occurs: "Cannot find file: 'RoleInfoModal.jsx' does not match the corresponding name on disk: './src/components/UserProfile/EditableModal/roleInfoModal.jsx'." This issue arises because the file is named `roleInfoModal` but is referenced as `RoleInfoModal` in routes.js and FormattedReport.js. To ensure consistency, the file name should be updated to `RoleInfoModal`.

2. The feature generally works as expected, however, after changing the name and attempting to save it again, the error modal reappears.

3. Additionally, the error is being displayed both in a modal and through an "alert" message. For a better user experience, it would be better to display the error only within the modal.


https://github.com/user-attachments/assets/9427aaf7-a1b4-40d4-9fee-96bf286318ec

2024-08-17 21:42 UTC, adityasure9 approved these changes
I tested the PR and found that the specific error message for the last name field works as intended when the last name is set to a single character. 

![image](https://github.com/user-attachments/assets/59a40ee8-fe85-4adf-8be0-877b6aaed2df)

2024-08-30 22:30 UTC, oliviahyw requested changes
I met the naming error first. After fixing the naming issue, it worked as expected. 
<img width="993" alt="Screenshot 2024-08-30 at 5 27 05 PM" src="https://github.com/user-attachments/assets/684e5b66-1c8b-47b9-8417-0143316eb27a">
<img width="637" alt="Screenshot 2024-08-30 at 5 28 16 PM" src="https://github.com/user-attachments/assets/1cfa5455-33cf-4b2d-8621-f4787e8efe53">

2024-08-31 19:06 UTC, merged