Nahiayn_New Dark Mode Button
OneCommunityGlobal/HighestGoodNetworkApp pull request #2470
Opened 2024-07-20 00:19 UTC by Nahiyan-16

# Description
Created a brand new dark mode button with hover effects

## Related PRS (if any):
This frontend PR is related to the dev backend PR.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to dashboard→ "Welcome, User Name" -> Check if the dark mode toggle is working properly

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/f32790f8-7f9e-4ec1-8fda-7a0cd0d96f0d

2024-07-20 00:35 UTC, kdaga81 approved these changes, later dismissed
<img width="280" alt="image" src="https://github.com/user-attachments/assets/2262dfc8-9241-412d-a186-315dcee2165a">
<img width="250" alt="image" src="https://github.com/user-attachments/assets/a080942d-04b6-441d-afcb-054a6d66a7f3">

This looks awesome! Good work!

2024-07-20 01:26 UTC, SrikanthChowdary495 submitted a review, later dismissed
I have tested this PR. It is working in both Darkmode & lightmode is working.

2024-07-20 02:05 UTC, kabraambika requested changes
I reviewed the feature on PR is working as intended but I noticed that if I click before the animation finishes, the image appears to get stuck on the text. Please see the attached video for reference.

https://github.com/user-attachments/assets/f8b3ec2d-aea9-4b1f-a3a2-7d54b9923ffe

2024-07-20 03:38 UTC, Parth-tech approved these changes, later dismissed
Hey Nahiayan,
The PR works as intended but as @kabraambika highlighted try dealing with the warning.
Approving the PR as the required functionality is met.
<img width="1440" alt="Screenshot 2024-07-19 at 8 28 03 PM" src="https://github.com/user-attachments/assets/8aeeca8b-48ca-46c4-b2d4-2335c198c420">

2024-07-20 08:45 UTC, Chetan0606 approved these changes
Verified as per the provided steps, It looks good.
![Screenshot (314)](https://github.com/user-attachments/assets/33bfd2f5-f978-4299-ba12-6ca33bb599fd)

2024-07-20 16:51 UTC, angelalalacheng submitted a review, later dismissed
Hi, 
I use the latest development backend branch and your frontend branch to test. When the mouse hover on button, the animation works good. And I also test the mobile device and it all works without animation.

https://www.loom.com/share/3a1defb61fa644f7bb876fd9213ef5c4?sid=a94e7699-729c-40a8-b143-1115813a427f

<img width="771" alt="Screenshot 2024-07-20 at 9 49 26 AM" src="https://github.com/user-attachments/assets/ca0d8faa-3388-4954-8d74-cbd683297189">

2024-07-20 18:21 UTC, one-community commented
Thank you all, merging!

2024-07-20 18:22 UTC, merged

2024-07-20 19:06 UTC, souravwalke commented
I tested the feature and found a small UI issue when toggling from Dark mode to Light mode. The text that should display as "Light Mode" does not appear as it gets masked by the background color. I've attached a screenshot for you to look over.

![image](https://github.com/user-attachments/assets/538747b8-8a47-4c9c-a71d-48d3199f41bc)

https://www.loom.com/share/9136e2bda48d4c42851bf19b9fccce38?sid=e34f7dce-5b45-48c4-9f13-181a88f9c024

2024-07-21 02:23 UTC, pavanswaroopl reviewed
Great work,

Have some observations, light mode text doesn't appear at times, simulation is upload below.

https://github.com/user-attachments/assets/44316764-1526-4e1c-8a09-92c9d7d59663

<img width="1440" alt="Screenshot 2024-07-20 at 9 19 58 PM" src="https://github.com/user-attachments/assets/ca0c09e6-aeed-44ae-be06-95762d4d6761">

2024-07-22 01:21 UTC, kabraambika commented on src/components/Header/DarkMode.css
> +  justify-content: start;
Thanks for resolving in new changeset 05143d20db8ee0676472113d77a4e8f8dcce6788.

2024-07-22 02:33 UTC, kabraambika reviewed
The compilation warnings have been addressed. However, there are still two issues to resolve:

- The "Light mode" text is not visible when dark mode is enabled as mentioned by @souravwalke and @pavanswaroopl  
- If the button is clicked before the animation completes, the icon becomes stuck on the text