Lin pagination UI members table fix
OneCommunityGlobal/HighestGoodNetworkApp pull request #2476
Opened 2024-07-20 15:52 UTC by linkhanthtel

# Description
<img width="796" alt="Screenshot 2024-07-20 at 11 39 33 PM" src="https://github.com/user-attachments/assets/fb249b82-b45b-4e34-b8b5-1451348df41b">

## Related PRS (if any):
This frontend PR is related to the #2201 frontend PR.
…

## Main changes explained:
1. Fixed UI for handling overlap of pagination and table values
2. Fixed CSS styling for smaller width screen
…

## How to test:
1. check into current branch
2. do npm install and npm run start:local to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. Go to Reports -> Projects -> Any project with 7 or more members
6. Make Screen Smaller
7. Check that pagination doesn't overlaps with table values on different screen size
...

## Screenshots or videos of changes:
Before
<img width="1438" alt="Screenshot 2024-07-20 at 11 46 44 PM" src="https://github.com/user-attachments/assets/c2427d4f-48e0-48d3-9476-190872359211">

After
<img width="1440" alt="Screenshot 2024-07-20 at 11 35 39 PM" src="https://github.com/user-attachments/assets/37ed138b-7378-41d6-b171-b95fa88798a9">

## Note:

2024-07-21 08:55 UTC, aaryaneil approved these changes
Tested the PR and the overlap is not present. 
Also tested for smaller screen size and the changes work as expected.
 ![Screenshot 2024-07-21 at 3 53 06 AM](https://github.com/user-attachments/assets/842b3e99-6af3-4036-bb92-d70bc983088e)

2024-07-24 19:01 UTC, souravwalke commented
Changes in the PR working as expected. Found no issues.

https://www.loom.com/share/dba5e5882cab453eba4450da2adaf090?sid=ebbdddc0-027f-44bf-bbe8-f659ed8ce0d6

2024-07-25 18:06 UTC, beblicarl commented
The UI looks as expected. Great work

![image](https://github.com/user-attachments/assets/1541d776-44c4-43ff-ab3b-3d4fb8bee9e3)

2024-07-25 18:08 UTC, beblicarl approved these changes

2024-07-25 20:59 UTC, Jingyii800 approved these changes
I tested this PR. The members section looks good for more than 7 members. No overlap. Great job!
![image](https://github.com/user-attachments/assets/785a038b-96ab-463c-b4ed-edf0c85769fe)

2024-07-26 17:16 UTC, arunsrao9 commented
I have tested as per the instructions and changes in the PR are working as expected. Found no issues.

<img width="1440" alt="Screenshot 2024-07-26 at 10 15 06 AM" src="https://github.com/user-attachments/assets/cfe8ecc6-253a-4b4c-976a-951b4bae2a6a">
<img width="1440" alt="Screenshot 2024-07-26 at 10 14 58 AM" src="https://github.com/user-attachments/assets/2866fe16-d999-4801-b25e-d1fb227d38c6">
<img width="1440" alt="Screenshot 2024-07-26 at 10 14 46 AM" src="https://github.com/user-attachments/assets/dff0cd9b-e627-41d9-9278-fce39ccfa4ff">

2024-07-26 18:28 UTC, SrikanthChowdary495 approved these changes
I have tested this PR. For project members above 7 or more. The pagination is working as expected for different screen sizes. Attaching a video for reference. 

https://github.com/user-attachments/assets/e90ca3e8-946d-4dd0-ba8e-7b86968b44a4

2024-07-26 19:03 UTC, SaiLavanya1 reviewed
I have tested the pagination UI in the Members table on various screen sizes. The changes you implemented to fix the overlap issue are working correctly. The pagination UI now properly adjusts without overlapping the last member when the screen size is smaller. The CSS styling for smaller width screens has been effectively applied, ensuring a consistent and responsive design.
https://www.loom.com/share/124c9d7d166b4f25b7487310df13e789

2024-07-26 19:26 UTC, JatinAgrawal94 approved these changes
Changes work as expected.

https://github.com/user-attachments/assets/c0f25309-857c-4f1b-ba29-ec8afe9bb354

2024-07-26 19:43 UTC, Chetan0606 approved these changes
Followed the instructions and everything looks good. Here's my observation video.


https://github.com/user-attachments/assets/400a17e3-51ca-492e-b27b-556ec5900294

2024-07-26 21:49 UTC, kabraambika requested changes
There seems to be an issue with pagination as some members are missing:

In the active checkbox, I see 10 members displayed:
Page 1
<img width="313" alt="image" src="https://github.com/user-attachments/assets/76086221-f8db-44e6-8cd0-eb146c98c6cc">

Page 2
<img width="307" alt="image" src="https://github.com/user-attachments/assets/c18e9078-d6cd-444a-ad14-c80ac58a9fee">

_**However, in the All-time view, which should show 12 members, only 10 are visible:**_

<img width="318" alt="image" src="https://github.com/user-attachments/assets/963f8a19-301c-40fa-94c2-cb05119fbc1e">
<img width="315" alt="image" src="https://github.com/user-attachments/assets/8763883a-88bf-4046-814a-48dc1d82f6ee">
 
Could you please investigate this discrepancy?

2024-07-26 22:44 UTC, vishavk1992 requested changes
Hi , I tried to test this PR but i am not able to start local host it gives error. I attached the screenshots for your reference. 
![PR-2476](https://github.com/user-attachments/assets/72d48759-b390-4841-95a6-11ce4c53dd0e)

2024-07-27 04:09 UTC, ishan-miglani requested changes
Hi, I have verified the changes in this PR. The members table pagination doesn't overlaps with table values on different screen sizes. 
But for a few projects the pagination doesn't show all the all-time members. Please see attached video. For the first project 2 additional inactive members are correctly added to the table on clicking the all-time filter but for the second one they are not added to the table.

https://github.com/user-attachments/assets/f2644fb0-305e-4d56-b560-6adc59bad6b6

2024-07-27 20:15 UTC, Pranay-ai reviewed
The Changes are Working as Expected
![image](https://github.com/user-attachments/assets/000c59c2-0a9c-4538-84ba-0e87954e82a8)
![image](https://github.com/user-attachments/assets/be142c3b-b2f1-4a5b-a777-6f7215238a39)
Thank You.

2024-08-03 01:48 UTC, ReinaT5678 reviewed
Hi, I'm getting an error when I try to run the program:

<img width="961" alt="Screenshot 2024-08-02 at 6 48 06 PM" src="https://github.com/user-attachments/assets/81e62981-fede-461b-abdc-7ec274f935bf">

2024-08-10 20:30 UTC, adityasure9 approved these changes
Hi @linkhanthtel,

The pagination UI fix works well. I tested the members table with various screen sizes, and the pagination controls no longer overlap with the table values. The CSS adjustments handle smaller widths effectively, and everything looks clean and functional.

![1](https://github.com/user-attachments/assets/cae36e24-0c9f-487c-ac55-f5e589d3622f)

I also tested on both very narrow and wide screens, and the UI remains consistent across different viewports. Great job on addressing this issue!

![3](https://github.com/user-attachments/assets/404c9c28-ce8b-4796-943b-dd9b0ab1b0d3)

2024-08-16 19:02 UTC, preethamdnr approved these changes
Hello Lin,
Tested the PR in both the modes, and there is no overlap. 
<img width="878" alt="image" src="https://github.com/user-attachments/assets/cf9db245-33f2-4881-b3aa-5574b74ba143">
![image](https://github.com/user-attachments/assets/a89cdb80-73d0-4f0a-9090-82658f7e04f3)

2024-08-18 04:02 UTC, AnkitLall approved these changes
I have tested the feature, following the instructions in the PR, and it works as expected. Please refer the screenshots attached below.

<img width="1512" alt="Screen Shot 2024-08-18 at 12 01 56 AM" src="https://github.com/user-attachments/assets/22c17a7f-61d7-41a1-a4c9-be6ced0d0d7f">
<img width="1512" alt="Screen Shot 2024-08-18 at 12 02 06 AM" src="https://github.com/user-attachments/assets/c752e980-7314-4cb3-bdcc-24badeeab0a1">

2024-09-07 16:01 UTC, swaroop-2007 requested changes
@linkhanthtel 
I’ve reviewed your PR, and the layout looks good with no overlap on smaller screen sizes. However, I noticed that with 72 total contributors (70 active), the view only displays the active contributors, not all 72. I’m not sure if this falls within the scope of this PR, but I’ve attached a screenshot for reference.

![Screenshot (362)](https://github.com/user-attachments/assets/324104b2-b0b3-43db-add3-30d690e1d387)

2024-09-08 02:36 UTC, FayeLV commented
Hi,
Great job! I tested the PR, and the overlap issue is resolved. I also tested it on smaller screen sizes, and the changes work as expected.
![PR 2525](https://github.com/user-attachments/assets/2899e123-39bb-479b-a015-6d88cc59cbac)
![Snipaste_2024-09-07_21-32-35](https://github.com/user-attachments/assets/07dabd28-e1b2-4878-a7f9-a257d3b71d01)
![Snipaste_2024-09-07_21-32-55](https://github.com/user-attachments/assets/2081de12-36ca-47b3-b680-f1cbf5b01bfc)

2024-09-09 22:08 UTC, strallia approved these changes
I verify that the pagination does not overlap the table values at various browser widths. Great work! 

https://github.com/user-attachments/assets/2ab63684-dd1c-42e1-8c7a-19cd2b5df24d

I am also not having issues with the number of users displayed in the Active and All-Time views that others reported earlier.

https://github.com/user-attachments/assets/b4cdeb5b-af17-4b46-b055-f30c3c59e8e7

2024-09-10 19:19 UTC, AJAYINAVOLU approved these changes
Changes are working as expected.

<img width="949" alt="image" src="https://github.com/user-attachments/assets/4c067420-b6fd-411c-ac1c-3464aed66203">

Thank You

2024-09-12 20:19 UTC, crystallow1168 approved these changes
Hi @linkhanthtel,

Changes are working as expected. Verified that there's no overlap of pagination and table values. 

<img width="1222" alt="image" src="https://github.com/user-attachments/assets/4ff61eb8-921c-4307-8f31-1d06b0d2ac06">
<img width="1403" alt="image" src="https://github.com/user-attachments/assets/3da0ef32-1065-43e0-8606-31fb80d63b0d">

2024-09-15 01:29 UTC, Shreyav2000 approved these changes
Tested the changes, and everything works as expected. UI looks good on smaller screens.

https://github.com/user-attachments/assets/a8c1c318-9d68-43c7-a7e5-8d853404d6b3

2024-09-18 22:50 UTC, ashayk9 approved these changes
I tried the functionality in both dark mode and light mode. There is no overlap.
![Screenshot 2024-09-18 at 3 48 13 PM](https://github.com/user-attachments/assets/066f6047-334d-4226-b55c-b78e7c909d46)
![Screenshot 2024-09-18 at 3 48 25 PM](https://github.com/user-attachments/assets/2f8f6711-4b96-42a2-a249-52b0f9e60eb9)

2024-09-21 20:36 UTC, nishitag5 approved these changes
The changes are working as expected.
![image](https://github.com/user-attachments/assets/7301727d-0308-48bc-b1fb-1983478bde36)

2024-09-22 05:27 UTC, lcohen730 approved these changes
Looks good at smaller screen sizes. Pagination does not overlap with table.
![Screenshot 2024-09-22 at 01 26 13](https://github.com/user-attachments/assets/5fe820f9-b5a3-40c6-bedd-368c886fe86f)

2024-09-27 00:39 UTC, nevatiarishabh approved these changes
I have tested this PR. The PR is working as expected for the functionality to be tested.

<img width="1440" alt="Screenshot 2024-09-26 at 5 35 45 PM" src="https://github.com/user-attachments/assets/cac9604d-67d8-4fde-9412-664a84fac71e">
<img width="500" alt="Screenshot 2024-09-26 at 5 36 13 PM" src="https://github.com/user-attachments/assets/66f019f8-7178-4f0f-9ae0-9fec623de39a">

2024-09-27 02:02 UTC, geetamatkar commented
Hi @linkhanthtel ,
Tested this PR and it is working as expected. There is no overlap in different screen sizes.

<img width="1022" alt="PR2476" src="https://github.com/user-attachments/assets/728dd759-246e-4b24-9543-c016977a46fd">
<img width="738" alt="PR2476-1" src="https://github.com/user-attachments/assets/3bb33a8d-738f-467d-8193-85988fef7b31">

2024-09-29 05:11 UTC, Muzammil603 approved these changes
![image](https://github.com/user-attachments/assets/cad1dfc2-2c3f-4eb1-b8a7-06f55cadbd4e)
![image](https://github.com/user-attachments/assets/c2a4b50f-7a92-4ccc-bf0a-a5f79761f00a)
working as expected

2024-10-06 04:24 UTC, khushijain03 approved these changes
Hi @linkhanthtel ,

The changes are working as expected.

<img width="810" alt="Screenshot 2024-10-06 at 12 22 00 AM" src="https://github.com/user-attachments/assets/bb6e2ee4-3a58-4684-9ddd-307638d78d36">


<img width="690" alt="Screenshot 2024-10-06 at 12 22 22 AM" src="https://github.com/user-attachments/assets/765735a9-b3e6-4a96-b446-e81c795f988c">

2024-10-07 23:01 UTC, pallavithorat commented
I tested this PR, and it is functioning as expected with no overlap across various screen sizes.
<img width="1470" alt="PR1#2476" src="https://github.com/user-attachments/assets/e04cd7d7-63dc-435c-a466-001de9eb00bb">
<img width="1470" alt="PR2#2476" src="https://github.com/user-attachments/assets/f2b8a840-8713-43f8-9b4d-e95d0500891c">
<img width="1470" alt="PR3#2476" src="https://github.com/user-attachments/assets/e05cd773-b115-4456-bd1e-9c44c8d7c5e8">

2024-10-24 20:41 UTC, bhavya17prakash approved these changes
Working as expected!
<img width="654" alt="PR 2476" src="https://github.com/user-attachments/assets/a4373681-f66c-49f0-8e41-a0848bd061e7">

2024-10-27 01:41 UTC, zhiminV approved these changes
I have checked that the pagination work as expected if member over 7 peoples, and  work in different screen size.

![Screenshot 2024-10-26 at 6 39 20 PM](https://github.com/user-attachments/assets/391bf5f9-edd6-4e0b-840b-f55891a0f571)
![Screenshot 2024-10-26 at 6 38 52 PM](https://github.com/user-attachments/assets/0f01611e-083a-44f9-b5dd-17dfee33c521)

2024-10-27 04:55 UTC, VMD281 commented
I reviewed this PR and it works properly! 
<img width="1655" alt="PR#2476_1" src="https://github.com/user-attachments/assets/f553ffb1-ca35-4ea4-8b90-9681d8bfa9b6">

2024-10-31 17:41 UTC, humera314 commented
This PR addresses a compilation issue that is currently preventing the application from running successfully.
![image](https://github.com/user-attachments/assets/b9880404-e393-4ae2-b410-e653fc914c3c)

2024-11-02 21:45 UTC, ajitp4292 approved these changes
The Pagination of members table in Project reports works as expected.
<img width="1507" alt="Screenshot 2024-11-02 at 5 43 22 PM" src="https://github.com/user-attachments/assets/c2bebb56-014c-43c0-b746-041f857946b0">

2024-11-06 22:40 UTC, SupriyaSudini approved these changes
I have tested the PR and confirmed that the pagination displays correctly without any overlap, even on smaller screens.

![image](https://github.com/user-attachments/assets/88457e1b-d580-4e35-bf22-0c1dfce09f1b)

![image](https://github.com/user-attachments/assets/9ce9bf2c-a331-4728-83ab-9a2721cd5c85)

![image](https://github.com/user-attachments/assets/6b1529f2-cc18-4b69-abea-90c69d28bcdc)

2024-11-09 06:42 UTC, audreydieuanh approved these changes
Nothing overlaps when I reduce my screen size.

![Screenshot 2024-11-09 at 12 38 48 AM](https://github.com/user-attachments/assets/88c512ea-76e1-4ee9-a0a6-a8bb1bb6051d)

2024-11-10 01:27 UTC, AshritaCherlapally approved these changes
Code changes of this PR is working as expected. The Members table does not overlap for projects with more than 7 members.

https://github.com/user-attachments/assets/ec953e9e-e428-42b2-bc8f-cb1a47f89419

2025-01-17 20:34 UTC, honglinchen0524 requested changes
The overlap of pagination and table values issue is fixed! 

However, I noticed that the members list won't appear instantly when I first select the project. It will only appear when I adjust the screen width multiple times, see video. (I tried this several times, and it behaves like that every time I click into a project with members). I am not sure if it is my browser issue or a UI/backend glitch, do you mind look into that?  

Also, I think the Pie Charts component's pagination is off, see video. Please try to fix that.

https://github.com/user-attachments/assets/73dbe709-79ae-4c7b-93dc-771a554d5e07

2025-02-28 02:49 UTC, TanviAnantula commented
The pagination UI fix works well and prevents overlap with table values across different screen sizes with a responsive layout.

2025-03-11 17:40 UTC, closed without merging