NandiniYelmela_fix_project_report_UI_issues
OneCommunityGlobal/HighestGoodNetworkApp pull request #2480
Opened 2024-07-20 23:55 UTC by nyelmela

# Description
Please include the exact bug/functionality description and a summary of the changes/ related issues. Please also include any other relevant motivation and context:
Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ task→…
6. verify function “A” (feel free to include screenshot here)
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2024-07-27 02:50 UTC, JatinAgrawal94 approved these changes
Changes work as expected. Good work.

https://github.com/user-attachments/assets/6906d0a7-467b-46b0-a546-cb8b29967cb1

2024-07-27 08:08 UTC, aaryaneil approved these changes
Tested the PR and the changes work as expected and as mentioned in the PR.

https://github.com/user-attachments/assets/f38ae7d8-3fb3-4075-8005-fae4aea893a0

2024-07-27 19:14 UTC, Pranay-ai approved these changes
https://github.com/user-attachments/assets/c663cc56-367d-4c09-b6eb-a78941c1efed

hey @nyelmela ,
Reviewed the PR working as Expected.
Thank You

2024-08-01 20:06 UTC, manikittu810 submitted a review, later dismissed
Hello @nyelmela 
All the mentioned are working as expected.

https://github.com/user-attachments/assets/9964b8dc-cc34-49ce-b33e-10987ef8b62d

Thanks

2024-09-10 19:14 UTC, AJAYINAVOLU submitted a review, later dismissed
Changes are working as expected.
<img width="937" alt="PR 2480" src="https://github.com/user-attachments/assets/28fe9958-894f-470f-b70b-a0b9d74501f3">
<img width="656" alt="PR 2480-1" src="https://github.com/user-attachments/assets/fbbeff6d-d2cd-428c-a23b-a54c24b75532">
<img width="608" alt="PR 2480-2" src="https://github.com/user-attachments/assets/4d8d35fb-a063-40fb-94f6-29d6212b1321">
<img width="374" alt="PR 2480-3" src="https://github.com/user-attachments/assets/b7b935bb-9b59-448e-a59b-5e487a7c39ff">

Thank You

2024-09-13 19:07 UTC, vishavk1992 submitted a review, later dismissed
I have tested this PR and UI works as expected for both mode light and dark.


https://github.com/user-attachments/assets/193f280d-627f-420f-99fd-6f8d3ca51194

2024-11-09 06:26 UTC, audreydieuanh requested changes
There are compile errors from the syntax errors in the file TasksDetail.jsx
<img width="1512" alt="Screenshot 2024-11-09 at 12 18 38 AM" src="https://github.com/user-attachments/assets/ea2294a6-14a5-4e3c-a489-b318122b0be5">

2025-01-05 07:05 UTC, nikhilgiri0226 commented
This Pull request is no longer needed and the relevant code in merged in PR #2970

2025-01-05 07:05 UTC, closed without merging