Kyo TimeLogger for BMdashboard
OneCommunityGlobal/HighestGoodNetworkApp pull request #2494
Opened 2024-07-24 02:37 UTC by alla0810

# Description
Implementing "Time Logger" Function for bmdashboard.
http://localhost:3000/bmdashboard/timelog

## Related PRS (if any):
This PR should be tested along with [Backend 1041
](https://github.com/OneCommunityGlobal/HGNRest/pull/1041)

## Main changes explained:
This PR is for implementing the followings:

URL: “/bmdashboard/timelog”

By selecting a specific project, the manager can view the users assigned to the project.
The top bar shows the name of the user. The color may change according to the user’s role. For example, light blue for volunteers, orange for core team, light green for managers and mentors, and red for owner.
The “start”, “stop” or “clear” buttons are the same as the buttons used for time log in the phase one system.
A select dropdown for the manager to monitor. The value here will be the default/pre-select value passed to the time log form to save. 

![image](https://github.com/user-attachments/assets/ff4b48ad-ad61-4e9c-b62e-7797405d55b5)

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to `http://localhost:3000/bmdashboard/timelog`, you may need to login again.
6. select a project to test
7. test start/pause/stop/clear time log for each member

## Screenshots or videos of changes:

![image](https://github.com/user-attachments/assets/8f430184-0554-4260-9d94-f32fe1af3ef9)

https://github.com/user-attachments/assets/d654b9e5-0a59-4177-8492-74678cbcdec3

## Function implemented by now:
1. retrieve project and member information from server to display member card
2. Stop/Pause/Stop/Clear time log
3. Set card color according to member role

## Functions to be implemented further
1. retrieve task name to display on the member's card
    --> may need to think about separate signaling to retrieve task information because of database fetch latency
2. update time log information to the database
3. some cosmetic improvement

2024-07-25 18:25 UTC, Pranay-ai requested changes
Hey @alla0810  When i try to select a Project from the dropdown menu it turns out to be a blank page I have attached the Logfile kindly verify it.
[localhost-timelog.log](https://github.com/user-attachments/files/16382293/localhost-timelog.log)
Thank You.
Guda Pranay Netha

2024-07-26 02:29 UTC, SrikanthChowdary495 reviewed
I have tested this PR. I have followed the steps. But when I am selecting Project. I am facing this 404 error. I have attached the screen shot. Please check if I am missing anything. 
![groupcheck](https://github.com/user-attachments/assets/376ec4a2-6e2a-407b-af9c-76914eec427c)

2024-07-26 23:07 UTC, JatinAgrawal94 approved these changes
Changes work as expected. Good work.

https://github.com/user-attachments/assets/faaca0e5-82c2-4525-acf3-5b61a392d1c1

2024-07-27 09:10 UTC, aaryaneil reviewed
The GET request for the users returns a 404 error. I have attached the screenshot for your reference.
<img width="1440" alt="Screenshot 2024-07-27 at 4 09 33 AM" src="https://github.com/user-attachments/assets/1a33196d-4c49-4ecb-8e78-ca73a797c1a3">

2024-07-27 09:22 UTC, aaryaneil approved these changes
Tested the PR and the changes work as expected and I am able to view/start/stop/clear timelogs.

https://github.com/user-attachments/assets/32a0cf49-209d-4490-b9bd-960260d30500

2024-08-02 00:23 UTC, Gmon-k commented
I am getting 404 error while testing it, below is the screenshot for it
<img width="1024" alt="2494" src="https://github.com/user-attachments/assets/bcaeb660-2c82-4c6e-bc70-993ae49c2192">

2025-03-21 20:59 UTC, sri0606 commented
Updated PR here #3299

2025-03-21 20:59 UTC, closed without merging