Peizhou_fix the assigning blue square with future date issue
OneCommunityGlobal/HighestGoodNetworkApp pull request #2496
Opened 2024-07-24 09:13 UTC by ZhangPeizhou

# Description
![image](https://github.com/user-attachments/assets/597d1761-27bb-43fc-86cd-5f1caea69103)

## Related PRS (if any):
This frontend PR is not related to any backend PR, please just check in to the development branch.

## Main changes explained:
- Fix the issue of being able to assign the blue square with a future date.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to a user's profile, assign a blue square with a future date
6. an alert message should occur, saying "WARNING: Cannot Assign Blue Square with a Future Date", and the blue square should not be added

## Screenshots or videos of changes:

2024-07-24 18:44 UTC, Chetan0606 approved these changes
Verified the PR as per the description and everything looks good

![image](https://github.com/user-attachments/assets/8aaf9f39-7794-4017-82fe-bf02fec9ebf5)
![image](https://github.com/user-attachments/assets/2144b04a-fed5-4fb5-859c-6310f94aed79)

2024-07-24 19:27 UTC, Shadhrush5 submitted a review, later dismissed
Hi, I have reviewed PR #2496 . I followed the instructions while executing the test as mentioned. The functionality works as stated. Thank you for the great work. I have approved the same. The below image depicts my testing.

<img width="560" alt="Screenshot 2024-07-24 at 12 07 13 PM" src="https://github.com/user-attachments/assets/c1dd15f9-3f58-4dfa-bbaa-d2dd455321a1">

2024-07-25 04:48 UTC, SrikanthChowdary495 submitted a review, later dismissed
I have tested this PR. followed the steps. I have tried to add a future date. I got alert message that occurs, saying "WARNING: Cannot Assign Blue Square with
![date](https://github.com/user-attachments/assets/12008d46-4106-461b-8dd8-7d5814de3f5b)
 a Future Date", and the blue square should not be added

2024-07-25 06:35 UTC, nikethaanand commented
The PR Works as expected, not able to assign a future date. On selecting a future date there is an error message that comes up.

https://github.com/user-attachments/assets/b724243d-172e-4376-849e-11a27e0fd410

2024-07-25 18:09 UTC, vishavk1992 submitted a review, later dismissed
I have tested this PR and i am not able to assign future date to blue square. It works  as expected. 
![pr-2496](https://github.com/user-attachments/assets/7ebab0d2-8b91-4786-98fb-1a1203b78364)
![PR-2496-1](https://github.com/user-attachments/assets/ab07dc58-1529-451f-b1e4-4f578777fda5)

2024-07-25 18:53 UTC, souravwalke commented
Tested the changes in the PR and it's working as expected. 

A quick suggestion instead of using the default alert message you can try using a predefined react component library like "react-hot-toast" to beautify your alert messages as per the UI. Looks cleaner than the default one.

https://www.loom.com/share/87483ce09b574e23a019244afc236100?sid=6ec31788-6e2e-41f9-bc06-75fed0510642

2024-07-25 20:26 UTC, Jingyii800 approved these changes
It works well! I logged in as an owner account and I cannot assign a blue square for a user at a future date. Please see the image below.
![image](https://github.com/user-attachments/assets/fc1f9ce2-73df-46a3-a088-513e26c5b059)

2024-07-26 09:33 UTC, Annezhang673 approved these changes
Works as expected and there are no bugs present. When I login as admin and pick a user to assign a blue square for a future date, I meet with an error message. 
<img width="1170" alt="PR2496" src="https://github.com/user-attachments/assets/79cfca5d-d1ec-46f5-81bf-9da94b421b8e">

2024-07-26 17:10 UTC, arunsrao9 commented
Verified the PR as per the description and everything looks good

<img width="1440" alt="Screenshot 2024-07-26 at 10 09 38 AM" src="https://github.com/user-attachments/assets/16276f0a-4b2e-4c5d-82ef-bccecc0b4f41">

2024-07-26 18:46 UTC, JatinAgrawal94 approved these changes
Feature works as expected. Good Work.
https://github.com/user-attachments/assets/1c7deed4-e1d3-45a2-a3c0-632f057aa65f

2024-07-26 18:48 UTC, SaiLavanya1 submitted a review, later dismissed
I have tested the functionality as described. The fix successfully prevents blue squares from being assigned with a future date. When attempting to assign a blue square with a future date, an appropriate warning message is displayed: "WARNING: Cannot Assign Blue Square with a Future Date," and the blue square is not added. This ensures that only valid dates can be used for assigning blue squares, addressing the issue effectively.
<img width="1470" alt="Screenshot 2024-07-26 at 11 46 46 AM" src="https://github.com/user-attachments/assets/618c5d94-e367-4858-a113-789ad48643e4">

2024-07-26 20:31 UTC, kabraambika submitted a review, later dismissed
**Observation on Valid Date Handling:**

**Current Behavior**: In the case of an invalid date, a new blue square is created.

**Expected Behavior**: In the case of an invalid date, a new blue square should not be created.

**Steps to Recreate the Issue:**

- Ensure the user currently has only one blue badge.
- Add a new blue square.
- Choose a valid date, such as a past or today's date.
- Customize your comment for the reason of the blue badge.
- Remove the date in the date field, returning it to "MM/DD/YYYY".
- Click on submit.
- Observe that a new blue square is created and now profile has 2 blue squares.

Please refer to the GIF below to see the steps for recreating the issue:
![PRComment-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/98637b55-84b6-484b-9d8b-08564a2c96e8)

2024-07-27 03:42 UTC, ishan-miglani requested changes
Hi, I have tested the changes in this PR. It shows an alert for a future date correctly.
I had some questions
- Why is a seperate alert message that opens in a different modal needed here. Will a error message below the date picker not suffice and look better visually ?
- For an empty date I am able to press Submit and the blue square is visible on the profile until a refresh and it then updates. Is this expected behaviour ?



https://github.com/user-attachments/assets/c69d3ccc-f86a-48d0-8f0c-ad78e72f72d2

2024-07-27 04:58 UTC, vijay10pk submitted a review, later dismissed
All the changes are working as expected.
<img width="717" alt="Screenshot 2024-07-27 at 12 57 27 AM" src="https://github.com/user-attachments/assets/bab2bef7-f419-4c3d-ae45-3483b7894a89">

2024-07-27 04:59 UTC, Parth-tech submitted a review, later dismissed
Hey Peizhou,
The PR works as intended, great job.
<img width="1440" alt="Screenshot 2024-07-26 at 9 58 23 PM" src="https://github.com/user-attachments/assets/ff8e10d0-77d7-43f8-b150-32ecc1f5661a">
<img width="1440" alt="Screenshot 2024-07-26 at 9 58 29 PM" src="https://github.com/user-attachments/assets/85b4a062-b7d7-4462-8882-e141bdf59d71">

2024-07-27 09:31 UTC, aaryaneil submitted a review, later dismissed
Tested the PR and the changes work as described and the error message pops up when a future date is set for a blue square.
<img width="1440" alt="Screenshot 2024-07-27 at 4 29 05 AM" src="https://github.com/user-attachments/assets/7450c22a-594e-4f80-a71f-028c304d959b">

2024-07-28 00:02 UTC, ReinaT5678 approved these changes
Ran the steps in the instructions and everything seems to work fine!

<img width="1114" alt="Screenshot 2024-07-27 at 5 01 57 PM" src="https://github.com/user-attachments/assets/a951424d-e021-4f55-999d-3c663fd6cd67">

<img width="1113" alt="Screenshot 2024-07-27 at 5 02 10 PM" src="https://github.com/user-attachments/assets/aa4a9e8b-477f-413a-b6a7-2bcb3cff8f66">

2024-07-31 22:05 UTC, varunreddy03 requested changes
The PR is working as intended for not being able to add blue squares for a future date (both light & dark mode), but it fails to address the problem of being able to add blue square for an invalid date, it pops up a message saying invalid date but a blue square is created even for that invalid date. I have attached the image of that below.

 
![PR 2496_5](https://github.com/user-attachments/assets/7240ccb8-54a9-473f-ba86-dc699e69d359)

A suggestion from my side, Instead of using system alert you can add the error message by performing JS validations and embed into the frontend, So that even when the user's system is in light mode it does not conflict the dark mode in HGN App.

Below is the screenshot of HGN App when it is in Dark mode but due to my browser is in light mode that made alert also in light mode and it conflicts with the dark mode of HGN App.

![PR 2496_2](https://github.com/user-attachments/assets/fe9a2188-b0ba-4d31-ad3e-cfff7a3f1833)

2024-08-03 16:28 UTC, Pranay-ai approved these changes
Hey @ZhangPeizhou 
The review is working as expected please find the screenshot for reference
![image](https://github.com/user-attachments/assets/20f1b6f7-3886-40b4-9f4a-eddfac6c2274)
Thank You.

2024-08-04 04:37 UTC, ZhangPeizhou commented
> JS validations and embed into the frontend, So that even when the user's system is in light mode it does not conflict the dark mo

Hello, thank you for your review! This issue is solved, please have a look. Thanks!

2024-08-04 04:38 UTC, ZhangPeizhou commented
> Hi, I have tested the changes in this PR. It shows an alert for a future date correctly. I had some questions
> 
> * Why is a seperate alert message that opens in a different modal needed here. Will a error message below the date picker not suffice and look better visually ?
> * For an empty date I am able to press Submit and the blue square is visible on the profile until a refresh and it then updates. Is this expected behaviour ?
> 
>  Screen.Recording.2024-07-26.at.11.33.19.PM.mov

Hello, thank you for your reply! The empty-date issue is now solved, please have a look, thanks!

2024-08-04 05:27 UTC, merged