added total members count in members popup
OneCommunityGlobal/HighestGoodNetworkApp pull request #2506
Opened 2024-07-26 16:27 UTC by Sarath-3119

# Description
 (PRIORITY HIGH) Jae: Add active/inactive numbers by teams on team page
Other Links>Teams
I’d like to easily see on this page the number of active and inactive team members in each team
If you take this one, please DM me your best ideas for showing this, so I can choose before you code it

## Related PRS (if any):
Check out the development branch in the backend.

…

## Main changes explained:
-The Teams page only has the teams and their status if it is active or not and Members icon which opens a pop-up with team members. 
- In the team members popup, I returned the number of active members in that team.

…

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in as an admin user
5. go to dashboard ->other links → Teams and Click on the Members icon
6. verify if you are able to see if the total team members number is displayed or not.
7. Check the responsiveness of the page. 
8. Go to user management pause any user that is present in any team, and check if the team members count is updating accordingly.

## Screenshots or videos of changes:

https://www.loom.com/share/1df421b4a36e40bea6b0d5521100462c

2024-07-26 21:42 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/de1334fc-2568-4c17-a1bf-d0ba95fd94c5

2024-07-27 02:16 UTC, kdaga81 approved these changes
<img width="536" alt="image" src="https://github.com/user-attachments/assets/7c905f90-404a-44f1-8b4c-779e716d388c">

I checked everything and working as expected!

2024-07-27 04:43 UTC, vijay10pk requested changes
All the changes are working as expected.
![Uploading Screenshot 2024-07-27 at 12.
<img width="805" alt="Screenshot 2024-07-27 at 12 40 26 AM" src="https://github.com/user-attachments/assets/f6ab90ba-697d-467b-b77d-a6d15b08a431">
<img width="1425" alt="Screenshot 2024-07-27 at 12 39 55 AM" src="https://github.com/user-attachments/assets/92695398-9ad1-4be2-a1fb-e1340d951378">
<img width="800" alt="Screenshot 2024-07-27 at 12 39 12 AM" src="https://github.com/user-attachments/assets/b00a5928-e262-4591-ad3f-df4623f31ab0">
40.51 AM.png…]()

UI Bug: for screen size below 992px the members modal is not responsive. refer the below screenshot for reference.
<img width="817" alt="Screenshot 2024-07-27 at 12 38 11 AM" src="https://github.com/user-attachments/assets/be182d99-9130-4aa6-a770-e5eec3d19a6c">

If this is not comes under the scope of this requirement let me know I will approve the changes.

2024-07-27 06:57 UTC, nikethaanand commented
All the changes are working as expected after pausing and resuming an users access.

https://github.com/user-attachments/assets/051a8368-28b8-4c63-bb10-e934da319c7a

2024-07-27 16:46 UTC, Pranay-ai reviewed
Hey @Sarath-3119 
I have Tested the PR 
![image](https://github.com/user-attachments/assets/af057dd3-c213-4610-9c63-0eda716ede82)
Works Fine, but i had to refresh the page again in order to update the active Member Count.
Thank You.

2024-07-27 18:11 UTC, jinxyou approved these changes
The function of total members count works as expected
![Screenshot 2024-07-27 121043](https://github.com/user-attachments/assets/f38d8779-ef1e-4d46-9a33-44547a5f30b0)

2024-07-28 04:58 UTC, Gauravmg6 approved these changes
Members count is updating according to pausing/resuming of the user. Page is responsive.


https://github.com/user-attachments/assets/2f63e256-dbf4-4f59-84e6-e7d059b725b0

2024-08-01 02:01 UTC, Gmon-k commented
I have reviewed the PR from my side and Below are the result:
1)the total team members number is displayed
2)page is responsiveness  
3) team members count is updating accordingly, if they are paused

Below is the screenshot of it
<img width="1024" alt="2506" src="https://github.com/user-attachments/assets/7192fdb2-788d-4bfc-afc9-da5e58092dd1">

2024-08-01 17:43 UTC, manikittu810 commented
Hey @Sarath-3119 
Working as mentioned.
Below are the observations :
Displayed total active members
When paused a user , decrement in count of active users reflected
when resumed , users count back to normal.
Everything worked fine.
Here is the video attached

https://github.com/user-attachments/assets/5ff20e44-01f8-46a3-b8bb-5178e79203e7

2024-08-01 18:15 UTC, manikittu810 approved these changes
Hey @Sarath-3119 
Working as mentioned.
Below are the observations :
Displayed total active members
When paused a user , decrement in count of active users reflected
when resumed , users count back to normal.
Everything worked fine.
Here is the video attached


Uploading Screen Recording 2024-08-01 at 10.36.40 AM.mov…

2024-08-11 03:59 UTC, aaryaneil approved these changes
Tested the PR and the changes work as expected.
<img width="1412" alt="Screenshot 2024-08-01 at 8 23 38 PM" src="https://github.com/user-attachments/assets/b8cfe7ad-1726-4fac-ab56-339d43f5d908">
<img width="1412" alt="Screenshot 2024-08-01 at 8 24 01 PM" src="https://github.com/user-attachments/assets/e8685064-a26b-4217-9f45-ee37bdf140c5">
<img width="1412" alt="Screenshot 2024-08-01 at 8 24 15 PM" src="https://github.com/user-attachments/assets/40beb01d-3a96-47e5-9f69-668779c3ad3a">

2024-08-22 20:40 UTC, preethamdnr approved these changes
Hello Sarath,
This PR is working as expected.

![image](https://github.com/user-attachments/assets/dde5c0cf-79cf-4559-9917-9863ab825245)
![image](https://github.com/user-attachments/assets/bb42f333-0df9-47f1-8255-cd45c0893a98)
![image](https://github.com/user-attachments/assets/2a98750b-0178-4f94-bf37-3fa95f12e5da)

2024-09-10 18:47 UTC, AJAYINAVOLU approved these changes
Changes are working as expected.

<img width="954" alt="image" src="https://github.com/user-attachments/assets/2f5c0ecb-db9a-4223-9c65-7f38f90cbec8">

Thank You

2024-09-13 15:27 UTC, one-community requested changes
1. Please show number of active members on the Teams overview page too. Do it as a bubble to the right of the name.
2. On the details page, show the number of active (green number) AND inactive users (red number) in this format: Members (17): 10 / 7

2025-02-22 04:45 UTC, closed without merging