update rehireable status if response is 200
OneCommunityGlobal/HighestGoodNetworkApp pull request #2514
Opened 2024-07-28 09:16 UTC by ImzIssa

# Description
 Fix Rehireable status is updated in the frontend regardless of the response status 
![Screenshot (492)](https://github.com/user-attachments/assets/3963d48c-f869-43a8-8f07-b1e469176c4d)

## Related PRS (if any):
This frontend PR is related to the [#PR1046](https://github.com/OneCommunityGlobal/HGNRest/pull/1046) PR.

## Main changes explained:
- Updated updateRehireableStatus function in actions/userManagement.js
- Update userProfile.js to display error if backend doesn't return 200 status when updating rehireable status

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user/ user with Change Rehireable Status permission
5. go to dashboard→ User Management → search for the protected accounts
'[jae@onecommunityglobal.org](mailto:jae@onecommunityglobal.org), '[one.community@me.com](mailto:one.community@me.com)', '[jsabol@me.com](mailto:jsabol@me.com)', '[devadmin@hgn.net](mailto:devadmin@hgn.net)' , and access their profile.
6. verify you can't update the Rehireable status of any of the protected accounts.
7. You could also add your email to the list of protected emails in the backend via editing the src\utilities\constants.js

## Screenshots or videos of changes:
![Screenshot (493)](https://github.com/user-attachments/assets/9f35cce8-4409-4eb0-9bf3-82a2a35648dc)

## Note:
Include the information the reviewers need to know.

2024-07-30 23:05 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.
![Screenshot (163)](https://github.com/user-attachments/assets/738e3ca6-cc13-405d-8240-4f02b7b421ad)

2024-07-31 03:25 UTC, vijay10pk approved these changes
Changes are working as expected.
<img width="1427" alt="image" src="https://github.com/user-attachments/assets/626c9de3-6538-45a7-ae9c-2016093fe852">

2024-08-01 00:17 UTC, Pranay-ai approved these changes
Hey @ImzIssa ,
I have tested the PR and is working as expected 

Uploading HGN APP - Rehirable.mp4…

Thank You.

2024-08-02 05:27 UTC, JatinAgrawal94 approved these changes
Changes work as expected. Good work.

https://github.com/user-attachments/assets/aa08e934-9fd4-4f62-ae35-efc2abad1367

2024-08-03 23:36 UTC, Gauravmg6 approved these changes
It is working fine as expected.

![Screenshot 2024-08-03 193452](https://github.com/user-attachments/assets/601e995f-cf28-4bb3-a525-abb59a911720)

2024-08-04 03:52 UTC, Annezhang673 approved these changes
Function works as expected. Can't change the protected user's rehireable status with admin account. 
<img width="1286" alt="PR2514" src="https://github.com/user-attachments/assets/1c1fcbf1-d458-40a0-b856-6e228a7410ab">

2024-08-06 22:20 UTC, Gmon-k commented
I have tested the PR and it is working as expected.

![Uploading 2514.png…]()

2024-08-07 05:43 UTC, varunreddy03 approved these changes
I have tested this PR by checking into both frontend and backend PR and it is working as intended for changing the re-hirable status for the protected accounts it is working as intended in both dark and light mode.

Also I have added one of my emails into the constants.js file and tested it out for that account and it is working as intended

I have also checked for my other accounts without protected access and I was able to check the Re-hirable status checkbox.

![PR 2514_1](https://github.com/user-attachments/assets/fb3b9580-96a4-41bb-915a-8056cfc7352a)
![PR 2514_2](https://github.com/user-attachments/assets/eed759a2-0aaa-42be-b530-1ddba35d8f2a)
![PR 2514_3](https://github.com/user-attachments/assets/6deebdbe-569e-45fd-affa-e7cf2d1d1ece)

2024-08-07 18:20 UTC, vishavk1992 approved these changes
I have tested this PR with backend PR-1046 and verified that i couldn't update the Rehireable status of any of the protected accounts.

![Screenshot 2024-08-07 141737](https://github.com/user-attachments/assets/92e48d4c-8788-41c1-b05a-f61d357fb9f5)
![Screenshot 2024-08-07 141745](https://github.com/user-attachments/assets/2efd29a0-941c-4003-b5ed-7c810bcac5c7)
![Screenshot 2024-08-07 141818](https://github.com/user-attachments/assets/d8348cd9-5823-4bfe-a46e-d9ae265709fe)

2024-08-24 23:00 UTC, SMitta11 approved these changes
I tested this and tried to change the status of these 4 protected accounts '[jae@onecommunityglobal.org](mailto:jae@onecommunityglobal.org), '[one.community@me.com](mailto:one.community@me.com)', '[jsabol@me.com](mailto:jsabol@me.com)', '[devadmin@hgn.net](mailto:devadmin@hgn.net)' but could not change their rehire-able status.So changes work as expected.
Screenshots for your reference:
![1](https://github.com/user-attachments/assets/b9fc62a7-587a-4d5a-8b5c-db100ff2b640)
![2](https://github.com/user-attachments/assets/79a28129-76af-4d9c-9dc3-baefc2666a39)
![3](https://github.com/user-attachments/assets/832ed851-beb5-42bd-aa0f-61b9f44b921c)
![4](https://github.com/user-attachments/assets/12f047c6-e245-4eb3-8a0f-4597d512ae0f)
![5](https://github.com/user-attachments/assets/e4444cd0-bc39-4fe6-88f0-c1a461526baf)

2024-08-28 19:21 UTC, manikittu810 approved these changes
Hello @ImzIssa 
Everything is working as mentioned.
![Screenshot 2024-08-28 at 12 21 09 PM](https://github.com/user-attachments/assets/fa63c178-8737-46f0-9412-b27789aa518c)

Thankyou.

2024-08-31 23:35 UTC, sri0606 reviewed
Hello @ImzIssa , I have tried to test the changes you made but ran into some issues.

* The main issue "Rehirable status updated in frontend regardless of the response status" still persists for me.
* I am able to edit rehirable status of protected accounts on frontend although I get error an backend.
* I am checked into the correct branch on both frontend and backend, `Imran_Fix_Rehireable_status`
* I tried clearing cache, site data too.

I believe this might just be on my end, but not sure what's going wrong. Any help would be appreciated!

Please refer to the video below:

https://github.com/user-attachments/assets/4eb222e1-3aac-4fb2-85db-b5c6c04cc0de


![PR2514](https://github.com/user-attachments/assets/8781f47a-4d57-4d20-9093-c68ed1e785ec)

2024-09-05 16:17 UTC, AJAYINAVOLU requested changes
Hi @ImzIssa, I am facing the issue as @sri0606. I am able to edit the rehireable status of protected accounts on the frontend and I get an error on the backend. 

<img width="947" alt="PR 2514" src="https://github.com/user-attachments/assets/3746a657-4947-4698-926d-140ed9e6e17e">
<img width="719" alt="PR 2514-1" src="https://github.com/user-attachments/assets/85d6fc79-e691-4e93-8365-fc9321de0ed2">

2024-09-14 02:19 UTC, Saniya98 approved these changes
Changes are working as expected 
![image](https://github.com/user-attachments/assets/89e853ba-d139-4750-99d8-38fa916b2611)

2024-09-14 15:04 UTC, sud306 commented
Hello,
I reviewed this PR along with PR1046 and I was able to change the status.
Please find the attached screenshots.

![6 PR1046_PR2514_1](https://github.com/user-attachments/assets/b253eb23-6647-4512-a281-491633315911)

![6 PR1046_PR2514_2](https://github.com/user-attachments/assets/c1fc0c58-940c-4f4d-b368-9665f45f3cfa)
![6 PR1046_PR2514_3](https://github.com/user-attachments/assets/8a53b819-0252-4ce3-9482-a4b3c665e892)

2024-09-15 02:23 UTC, panchalvatneu approved these changes
I was able to test this PR successfully, one can't change protected account's rehire-able status

![Screenshot (51)](https://github.com/user-attachments/assets/1d869572-fc50-4728-bc87-b290ce4b7006)
![Screenshot 2024-09-14 192146](https://github.com/user-attachments/assets/9c82cecb-6fd5-4482-ac9f-a98d999b8b24)

2024-10-25 08:50 UTC, samarth9201 approved these changes
Working as expected.
![image](https://github.com/user-attachments/assets/8c6323e2-1222-4bbc-845b-7186fa676a21)

2024-12-12 00:07 UTC, pallavithorat commented
I have tested the PR and it works as expected, Can't change the protected user's rehireable status.
<img width="1470" alt="Screenshot 2024-12-11 at 4 05 06 PM" src="https://github.com/user-attachments/assets/65dabf79-ca3c-4d21-b3f2-d5781ca2949f" />

2024-12-22 02:39 UTC, ShraddhaShahari reviewed
I have tested the PR and it works as expected, please find below attached screenshot.

<img width="806" alt="Screenshot 2024-12-21 at 6 37 13 PM" src="https://github.com/user-attachments/assets/004ad92c-8a9d-4c21-b575-8e34c1ab725b" />

2025-02-07 23:07 UTC, Srichand-Medagani reviewed
I have reviewed this PR and it works as expected. I am not able to change the Rehireable status for any of the accounts mentioned. This works both light and dark mode.
<img width="442" alt="image" src="https://github.com/user-attachments/assets/b60fdf51-46c7-4414-b06a-de18c6fc3e93" />
<img width="446" alt="image" src="https://github.com/user-attachments/assets/138f46b0-ab43-4ce8-9d62-d36fbb3ff778" />

2025-04-17 22:52 UTC, closed without merging