Added the redirection part to the current user
OneCommunityGlobal/HighestGoodNetworkApp pull request #2538
Opened 2024-08-04 20:12 UTC by Chetan0606

# Description
Users are unable to navigate back to the main dashboard after viewing another user's profile. 
![image](https://github.com/user-attachments/assets/c4648475-9fde-4b8a-86a3-9adda3ef04a6)

## Related PRS (if any):
This frontend PR is related to the dev backend.
…

## Main changes explained:
- Added the navigation logic to Header.jsx

## How to test:
1. check into the current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner/admin user
5. Go to dashboard→Leaderboard Section→ Click on red/green dot before the username→Click Welcome, {Username}→Click view profile→Click on X on the yellow bar→Click ok
6. verify if you are navigated to your dashboard
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/13ffda49-f610-49f8-b4c2-268203b3a123

2024-08-04 23:56 UTC, kabraambika requested changes
I have reviewed this frontend PR and suggested changes.

2024-08-04 23:56 UTC, kabraambika commented on src/components/Header/Header.jsx
> +    window.location.href = `/dashboard/${userId}`;
**Suggestion for code improvement**: Using window.location.href reloads the entire application, which can be inefficient. The useHistory hook from React Router is better suited for this case as it enables navigation without a full reload. 

logged-in user ID should not visible in the URL and Url should be '/dashboard' which maintains consistency throughout the application.

2024-08-05 16:29 UTC, kabraambika approved these changes
I have reviewed the changes and it's working fine now. Good work!

2024-08-05 16:30 UTC, kabraambika commented on src/components/Header/Header.jsx
> +    window.location.href = `/dashboard/${userId}`;
Resolving the conversation as this is fixed in changeset 201ad4f1abf550ff2669fe79c1cb7466e7afe291

2024-08-05 21:40 UTC, manikittu810 approved these changes
Hello @Chetan0606 
Followed the mentioned steps and everything is workin as mentioned.  Below is the screen recording.

https://github.com/user-attachments/assets/27022924-7a10-43a1-baf8-852d723712c2


Thank you.

2024-08-06 16:12 UTC, SrikanthChowdary495 approved these changes
Everything working as expected. Great Work! 

https://github.com/user-attachments/assets/f825d3b6-fd4e-4f83-8481-7e2ef2e7073e

2024-08-06 18:49 UTC, Pranay-ai approved these changes
Hey @Chetan0606 
The PR is Working as Expected 

https://github.com/user-attachments/assets/585a8200-8111-4dcd-a458-d21796bc8eea

Thank You.

2024-08-07 02:21 UTC, vijay10pk approved these changes
This fix is working as expected.
https://www.loom.com/share/ece3ae5146ad42b8a85d5d394483c012?sid=3b24eabd-c8c3-46c8-9575-3a72d71707f7

2024-08-07 21:14 UTC, DiyaWadhwani approved these changes
Hi Chetan,
Went through your changes. All looks good and works as expected.
Thank you for your time with this. I have dropped a working video of the testing below.

https://github.com/user-attachments/assets/ccf42ea5-625a-4ff2-9e28-1f394b1cfaeb

2024-08-08 11:12 UTC, cgomezhub reviewed
Hey Chetan!

I see you've implemented useHistory to redirect the button to /dashboard. That's good. However, I don't see a difference between a personal dashboard and a simple dashboard, except for the yellow window.

![Screenshot 2024-08-08 070734](https://github.com/user-attachments/assets/a86a72b6-60a8-4741-a23b-fdcfcb27c828)


![Screenshot 2024-08-08 070804](https://github.com/user-attachments/assets/756ede38-2b02-40c6-85fd-b4eda14ae5e6)

2024-08-08 16:58 UTC, Logeshwari-Renu approved these changes
I have tested the PR and verified the redirection to current user from selected user. The functionality work fine. Great work!
![2538_1](https://github.com/user-attachments/assets/47772f72-024d-43ee-8908-ab5ad4a9dd19)
![2538_2](https://github.com/user-attachments/assets/b38397e0-6aab-4102-817d-7928fcb04526)

2024-08-09 20:40 UTC, vishavk1992 approved these changes
i have tested this PR and it works as expected, good work


https://github.com/user-attachments/assets/11f14034-b9e6-4f69-b4e0-3bffc2f1bf33

2024-08-10 19:41 UTC, wang9hu approved these changes
Work as intended!

https://github.com/user-attachments/assets/1d08477c-00c5-4e9c-9c24-a235375db05a

2024-08-12 03:23 UTC, aaryaneil approved these changes
Tested the PR and the changes work as expected and the navigation works as described. 

https://github.com/user-attachments/assets/975838dc-f103-46c6-9e1e-cbbcb55465ad

2024-08-12 21:39 UTC, one-community commented
Thank you all, merging!

2024-08-12 21:39 UTC, merged