Peizhou_Fix Add New Project Category & Ability to Change Category
OneCommunityGlobal/HighestGoodNetworkApp pull request #2561
Opened 2024-08-12 10:13 UTC by ZhangPeizhou

# Description
![Capture](https://github.com/user-attachments/assets/1725d15c-e489-4b78-9f30-f579eae5ff5c)

## Related PRS (if any):
This frontend PR is not related to any backend PR, please just check in to the development branch.

## Main changes explained:
- Fix the issue of the category becoming "Unspecified" when creating new projects.
- Fix the issue of not being able to change the category of existing projects.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Other Link→ Projects
6. create a project with a specified category, and the project will be shown with the specific category. It may take one minute or two.
7. change the category of an existing project, and check in the database. That project's category will be changed. You can also check by refreshing the page and find the project you just changed, see if its category changed.

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/07b2d49f-cf65-47fb-804c-39af37d8e19c

2024-08-14 20:29 UTC, Aishwarya0898 approved these changes
Hi @ZhangPeizhou 
The PR is working as expected, here is the video for reference.


https://github.com/user-attachments/assets/6f8b437d-c255-47e0-ba4c-2649a0f27344

2024-08-15 19:28 UTC, vishavk1992 approved these changes
I have tested this PR and everything working as expected. 

![Screenshot 2024-08-15 152719](https://github.com/user-attachments/assets/87bf9feb-4d15-47b2-b47d-4dbd9c104d95)
![Screenshot 2024-08-15 152736](https://github.com/user-attachments/assets/ee62483f-eb30-4ebb-85de-82eb054ee10e)

2024-08-15 19:59 UTC, Pranay-ai approved these changes
The PR is working as expected, new project created is rendered in the list later.
Thank you.
![image](https://github.com/user-attachments/assets/4d80288a-61d8-4934-8ad0-3cc250918333)

2024-08-17 05:51 UTC, JatinAgrawal94 submitted a review, later dismissed
When I try to add a new project it gives me an error. Please check the video for reference.

https://github.com/user-attachments/assets/5cbaa446-22ed-4206-b282-41f99e05ef3a

2024-08-18 05:24 UTC, Gauravmg6 approved these changes
Everything works as expected.
![Screenshot 2024-08-18 012331](https://github.com/user-attachments/assets/eaf3b8c0-7497-422a-babd-63adb63a1681)

2024-08-19 04:37 UTC, Lemonnycodes approved these changes
Hi,

Tested the PR and verified that creating a new project with a specified category displays the project under the correct category after a short delay of few mins. 

Screenshots:

Create New Project with Category:
![PR 2561](https://github.com/user-attachments/assets/612db4b5-dc19-4f0e-9afe-dc0544ec1e57)
Changed Category reflected:
![PR 2561 (2)](https://github.com/user-attachments/assets/bf492202-207d-431e-9673-910e9d8a385a)

2024-08-20 21:57 UTC, SnelPatare approved these changes
Tested PR on both modes (light, dark). Working fine for me. 
Please find below Screenshots

![image](https://github.com/user-attachments/assets/bc038175-e2db-4628-bbd7-f20489593dde)

![image](https://github.com/user-attachments/assets/25caf8cd-5c0e-466b-b8ea-b20d4bffb7e6)

2024-08-22 23:14 UTC, vishnupriyaatheti requested changes
@ZhangPeizhou I have reviewed your changes. Below are my observations:

issue: When I try to create new project on the page and click the '+' button , I can see the loading sign even after 10min. If I refresh the page manually then I can see the project adding on the page. Otherwise it shows me as loading on the UI.

The other scenario of category change is working as expected, Also the code changes seems good.

![PR #2561 new project creation loading](https://github.com/user-attachments/assets/eb09594e-5d73-4860-b986-aff4cefcc7a4)
![PR #2561 after category change](https://github.com/user-attachments/assets/feaf2396-1128-4102-b104-895d37c55e29)
![PR #2561 new project creation](https://github.com/user-attachments/assets/6f51cae0-e011-4228-a3a1-1bf396987209)

2024-08-23 05:21 UTC, Parth-tech approved these changes
Hi Peizhou,
The PR meets the required functionality and the codebase looks great too. I was able to create a new project. Also change the category and after each page reload, the new category assigned was displayed, hence the system is persistent.

Great job done.

`Image References:`
<img width="1440" alt="Screenshot 2024-08-22 at 10 17 04 PM" src="https://github.com/user-attachments/assets/11c3e608-20f8-44c6-b5a6-0b2d21da3e95">
<img width="1440" alt="Screenshot 2024-08-22 at 10 17 22 PM" src="https://github.com/user-attachments/assets/38a8866c-f9dc-46c3-9b1d-a78c80ddb4e6">
<img width="1440" alt="Screenshot 2024-08-22 at 10 17 51 PM" src="https://github.com/user-attachments/assets/9e57ac6c-4361-43df-b0f5-951cc1cb5cf2">
<img width="1440" alt="Screenshot 2024-08-22 at 10 18 07 PM" src="https://github.com/user-attachments/assets/c8353563-537d-45dd-af3c-99c1726e782c">

2024-08-30 18:33 UTC, sri0606 approved these changes
Hello @ZhangPeizhou , I have reviewed the changes, and everything works as expected. Refer to the video below:

https://github.com/user-attachments/assets/42421686-33b1-40af-8ebd-cbf20ad8deb9

2024-08-31 01:04 UTC, vedantg24 approved these changes
I tested this PR, and the changes are working as expected.

https://github.com/user-attachments/assets/a87dc122-48b1-40bb-9356-2d02681e9941

2024-09-04 21:51 UTC, strallia requested changes
### Tested all functionalities and they work as expected:
- Creating a new project displays with correct category.
<img width="1195" alt="image" src="https://github.com/user-attachments/assets/b93e6a48-1284-4105-ae9c-7d025e1d263e">
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/b9857316-78c0-484e-bc5b-19ed1a750489">

- Changing the category is reflected in the database and upon page refresh.
<img width="1177" alt="image" src="https://github.com/user-attachments/assets/57505e05-8ed7-4d59-aa19-265ee1c36099">

### Issues (These may call for separate PRs):
- After adding a new project, the loading icon kept running for even more than 5 minutes of waiting. When I refreshed the page, the loading icon went away and the new project is shown in the list, meaning it was added to the database. I expected the loading icon to close out automatically once successfully added to the database without me having to refresh manually.
- In Safari, the design of the `select` tag for selecting the category is inconsistent with how it looks on Chrome.
<img width="1392" alt="Screenshot 2024-09-04 at 2 45 41 PM" src="https://github.com/user-attachments/assets/fcedde58-b7ff-4a31-83f2-a1466f136722">

2024-09-05 19:04 UTC, ashayk9 approved these changes
I tested this PR, and the changes are working as expected.
![Screenshot 2024-09-04 at 8 40 14 PM](https://github.com/user-attachments/assets/11156734-96fe-4eff-baa0-9177f6595760)
![Screenshot 2024-09-04 at 8 40 54 PM](https://github.com/user-attachments/assets/25e806f9-0da2-4e00-8181-401c59faa83a)
![Screenshot 2024-09-04 at 8 42 12 PM](https://github.com/user-attachments/assets/aefe93f8-b475-4e51-b3f7-b60d63009098)

2024-09-07 00:54 UTC, crystallow1168 approved these changes
Hi @ZhangPeizhou

PR is working as expected! 

Observation: The loader spinner seems to take a long time. I refreshed the page after a few seconds, and I see the updated changes. (Refer to images below)

![image](https://github.com/user-attachments/assets/5f9b3986-bbb3-4ee4-a893-45ac41e6d9a1)
Successfully created a project with a category assigned

![image](https://github.com/user-attachments/assets/e26cc495-6208-4a3a-8969-08b1a71fa382)
Successfully changed project's category from Food to Economics

2024-09-07 19:29 UTC, AJAYINAVOLU approved these changes
Changes are working as expected.

<img width="941" alt="PR 2561" src="https://github.com/user-attachments/assets/970c225b-69b7-4a7e-8162-65ccefbced6a">
<img width="938" alt="PR 2561-1" src="https://github.com/user-attachments/assets/0eaf69c0-cf74-4e8c-875f-159f87a3905b">

Thank You

2024-09-11 21:22 UTC, SFA23SCM35V commented
I have tested this PR, and everything is working as expected.
![PR #2561](https://github.com/user-attachments/assets/8467d1e4-88ed-4491-892d-7b1dcd304def)

2024-09-12 05:26 UTC, SFA23SCM35V approved these changes
![pr1](https://github.com/user-attachments/assets/183dffe0-e4b9-4944-a2fb-0557a6318a9a)

2024-09-13 15:17 UTC, one-community commented
Thank you all, merging!

2024-09-13 15:17 UTC, merged