Reina delete own time
OneCommunityGlobal/HighestGoodNetworkApp pull request #2566
Opened 2024-08-13 17:55 UTC by ReinaT5678

# Description
This is a continuation of PR#2087

"This PR enables the user with the Delete Time Entry (Own) permission to be able to delete it's own any time entry via their dashboard."

## Related PRS (if any):
This frontend PR is related to the dev backend PR.
…

## Main changes explained:
- Fixed a few bugs in PR2087. 
- Added some conditional logic to a few files to enable own permissions.
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Other Links -> Permissions Management -> Manage User Permissions -> Choose a USER without Delete Time Entry (Own) permission under Timelog Management -> click on Add -> Submit
6. Make sure USER doesn't have DELETE_TIME_ENTRY_OTHERS Permission
7. Verify that the user who was given permission is now able to see the delete button in any of time entry log on the dashboard and is able to delete it.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/d6e66ebe-d709-46e5-8171-a77379f85fa6

2024-08-13 18:44 UTC, Pranay-ai approved these changes
Hey @ReinaT5678  The Pr is Working as expected please find the attached Screenshots
Before Assigning Permission
![image](https://github.com/user-attachments/assets/dcd2e067-4bdd-4409-b7b1-afe8c582b3e3)
After adding the Permission
![image](https://github.com/user-attachments/assets/b0f86d8d-0e88-46a0-98ea-bbedee3a3ebc)
Thank You.

2024-08-13 21:46 UTC, vishavk1992 requested changes
I have tested this PR and i am able to assign user permission from my Owner account but i am not able to add the intangible time entry to test this PR . Please check 

![Screenshot 2024-08-13 170530](https://github.com/user-attachments/assets/bc84072a-aa9b-4770-9b78-2908706e21fa)
![Screenshot 2024-08-13 173716](https://github.com/user-attachments/assets/14f63654-d06f-48bf-b6ae-61a9f119ecc1)

2024-08-14 02:19 UTC, nikhilpittala16 submitted a review, later dismissed
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/1f085f34-1f70-4bcb-a744-035c020be169

2024-08-14 02:45 UTC, vijay10pk submitted a review, later dismissed
The changes are working as expected.
<img width="1426" alt="Screenshot 2024-08-13 at 10 45 15 PM" src="https://github.com/user-attachments/assets/3cde318c-f95c-4786-8c87-22dcf086839d">
<img width="715" alt="Screenshot 2024-08-13 at 10 19 34 PM" src="https://github.com/user-attachments/assets/889c09a2-429a-49b1-9d12-b8503a5a8bb7">

2024-08-14 06:46 UTC, Aishwarya0898 approved these changes
Hi @ReinaT5678 
The PR is working as expected, Here is the reference.

https://github.com/user-attachments/assets/a28ffe11-fea3-415c-a062-03105d75757f

2024-08-15 18:57 UTC, vishavk1992 submitted a review, later dismissed
I have tested this PR again and now it works as expected . I am able to see the delete button in any of time entry log on the dashboard and  able to delete it.

![Screenshot 2024-08-15 145448](https://github.com/user-attachments/assets/fce5f63d-3574-485e-b673-5d5f67356614)
![Screenshot 2024-08-15 145458](https://github.com/user-attachments/assets/9f026d92-a3fc-4e51-8046-06a7275b2794)

2024-08-17 05:30 UTC, JatinAgrawal94 submitted a review, later dismissed
Changes work as expected. 

https://github.com/user-attachments/assets/9436e398-b9bf-4e0b-b3ce-bbecf7f4d8de

2024-08-18 05:11 UTC, Gauravmg6 approved these changes
After adding the permission to my volunteer account, I can see the delete option under time entry.
![Screenshot 2024-08-18 011011](https://github.com/user-attachments/assets/9ad562c4-6dfa-4f3d-96fd-f4c5ed9a97e6)

2024-08-25 00:26 UTC, Vigneshwar-Muriki approved these changes
Tested this PR and its working as expected.

https://github.com/user-attachments/assets/18c1b2e6-1c01-4eb8-995a-8a90e2eaeca6

2024-08-29 23:46 UTC, SnelPatare approved these changes
Changes are working as expected. I created a task with no timelog permission. Assigned permission to delete timelog (own). I was able to see delete icon on timelog  (volunteer profile) and was able to delete the timelog. 

Please find screenshots below. 
![image](https://github.com/user-attachments/assets/1a3c517a-c9a9-458b-bff1-61ff67c65f12)

![image](https://github.com/user-attachments/assets/45c12718-8493-49c3-808c-c3148f7eb647)

2024-08-31 07:07 UTC, sri0606 approved these changes
Hey @ReinaT5678 , I followed the steps you mentioned and tested the functionality of deleting own time and everything worked as expected and I can see a delete button:

**After giving permission:**


![Screenshot 2024-08-30 235832](https://github.com/user-attachments/assets/677b2036-ea77-4d23-bd2f-e9e5a3088e82)

2024-09-06 22:47 UTC, AJAYINAVOLU approved these changes
Changes are working as expected.

Before granting permission:
<img width="941" alt="PR 2566" src="https://github.com/user-attachments/assets/f1d92384-df8f-4817-ac95-d6add30a4d6b">

After granting permission:
<img width="943" alt="PR 2566-1" src="https://github.com/user-attachments/assets/53bd153f-8f84-4a91-a6c7-3cb99e539e8a">

Thank You

2024-09-17 00:57 UTC, crystallow1168 approved these changes
Hi @ReinaT5678,

Changes are working as expected 👍🏻! Below are my findings:


https://github.com/user-attachments/assets/e2458980-976a-46c0-b9e8-5bd54d9a0857



✅ After adding "Delete Time Entry (Own)" to a user, the delete option/logo is now visible to the user
✅ Successfully delete a time entry 

Observation: The new permission setting does not seemed to work after refreshing the page. The user assigned with new permission will need to log out and log in again to see the delete option. (Ignore this observation if this is the expected behavior)

2024-12-22 02:22 UTC, ShraddhaShahari reviewed
I have tested the PR and is working as expected. Added screenshots before and after assigning permissions to user.

Screenshot before assigning the "time delete" permission
<img width="1714" alt="Screenshot 2024-12-21 at 6 16 13 PM" src="https://github.com/user-attachments/assets/ff7388c6-afc7-4c0a-8aa0-7240d33304c4" />

Assigned the "time delete" permission successfully.
<img width="1675" alt="Screenshot 2024-12-21 at 6 17 03 PM" src="https://github.com/user-attachments/assets/2d218d88-66bd-4ea4-88cf-8b790ab95b96" />

Screenshot after assigning the "time delete" permission
<img width="1716" alt="Screenshot 2024-12-21 at 6 18 12 PM" src="https://github.com/user-attachments/assets/6f426865-b645-4915-b268-0158be9847c6" />

2025-01-10 20:58 UTC, one-community commented
Thank you all, merging!

2025-01-10 20:58 UTC, merged