Fixing "Send Emails" visibility for Volunteers with 'Other Links' access and adding a new Send Emails Permission.
OneCommunityGlobal/HighestGoodNetworkApp pull request #2572
Opened 2024-08-15 19:58 UTC by Shadhrush5

# Description
<img width="744" alt="Screenshot 2024-08-15 at 12 35 01 PM" src="https://github.com/user-attachments/assets/709dce23-625c-43f4-b329-956a1c656081">
<img width="1728" alt="Screenshot 2024-08-15 at 12 41 17 PM" src="https://github.com/user-attachments/assets/1c8169a2-5d9d-47ec-930d-4f2a7da7899d">

## Related PRS (if any):
This frontend PR is related to the development backend.
…

## Main changes explained:
1. Added a new permission for access to 'Send Mails'.
2. Added a new route called 'Announcements' and 'Send Mails' permission comes under this.
3. Gave 'Owner' the new permission by default. For the rest it can be added.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. Give the 'add Roles' permission to any Volunteer.
6. log on as that volunteer who has the permission.
7. go to dashboard→ Other links
8. You will not see 'Send Mails' anymore
9. log as admin/owner user
5. Give the 'Send Emails' permission to the Volunteer.
6. log on as that volunteer who has the permission.
7. go to dashboard→ Other links
8. You will now see 'Send Mails' and click on the same to verify the right page opens.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/8e03c11b-0f10-4974-b45f-e9bfd240ff01

https://github.com/user-attachments/assets/feb97799-7994-4a4a-bf3c-2042fa407b38

## Note:

2024-08-15 23:25 UTC, Pranay-ai submitted a review, later dismissed
Hey @Shadhrush5 
I have tested the PR by following the steps and its working as expected 
![image](https://github.com/user-attachments/assets/f8f55d01-cd70-4dec-861e-a19722c7467c)

Thank You

2024-08-16 01:16 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.
![Screenshot (169)](https://github.com/user-attachments/assets/06c0634b-5890-481d-a787-9a4d067a5e15)
![Screenshot (170)](https://github.com/user-attachments/assets/6f5e482b-07cb-4223-9d03-e8d19976b6e6)

2024-08-16 02:55 UTC, Lemonnycodes commented
Hi,

The PR Works as described. 
 Both the "Send Mails" and "Add Roles" permissions are functioning correctly. When these permissions are assigned to a volunteer, the corresponding options appear under "Other Links" on the dashboard. The permissions are applied as expected, and the UI behaves as intended. No issues were encountered during testing.
 
Screenshots:
![PR (1) 2572](https://github.com/user-attachments/assets/4b9cecea-63a3-477d-9c12-2f1b7fd41193)
![PR (2) 2572](https://github.com/user-attachments/assets/b77df8ea-37ad-4a78-945e-19c4d012f0c8)

2024-08-16 20:54 UTC, vishavk1992 submitted a review, later dismissed
I have tested this PR and i gave permission to my volunteer account to send email. and it successfully display on my volunteer account. 

![Screenshot 2024-08-16 165332](https://github.com/user-attachments/assets/62bc273a-2fcf-449c-bf74-787e44c34651)
![Screenshot 2024-08-16 165348](https://github.com/user-attachments/assets/76a38f76-9ff6-482f-8966-13c4a65876fd)

2024-08-17 00:34 UTC, AnkitLall approved these changes
I have tested the feature, following the instructions in the PR, and it works as expected. I’ve attached a video recording of the testing process.


https://github.com/user-attachments/assets/1e99cd8b-59e0-4253-98f2-8f2d6da5d39c

2024-08-17 05:05 UTC, JatinAgrawal94 submitted a review, later dismissed
Everything works as expected.

https://github.com/user-attachments/assets/62b038ba-9094-4e9f-9673-6197c5a24395

2024-08-17 05:39 UTC, Aishwarya0898 approved these changes
Hi @Shadhrush5 
The PR is working as expected. Here is the screenshot for reference.


https://github.com/user-attachments/assets/68b39c84-a829-47cc-8963-66afcb312bec

2024-08-17 06:46 UTC, SMitta11 approved these changes
I login as admin first and gave volunteer user permission to send emails and then login as volunteer and can see the send email.
It is working as expected.
Screenshots:
![Screen Shot 2024-08-17 at 1 42 57 AM](https://github.com/user-attachments/assets/c6796ee2-2909-4899-a97f-cc6e873116c2)

![Screen Shot 2024-08-17 at 1 44 58 AM](https://github.com/user-attachments/assets/71026188-ee6f-46aa-b4d8-1be9a89f4fd9)

2024-08-17 20:33 UTC, adityasure9 approved these changes
I have tested the PR following the provided steps, and it works as expected. The 'Send Mails' permission is correctly applied, and the UI behaves as intended when permissions are assigned to a volunteer. Everything functions as described. Great work!

![image](https://github.com/user-attachments/assets/47d35ce0-fd2d-46b2-a911-5886b53b05a2)

2024-08-17 20:49 UTC, nathanah requested changes
Everthing looks good here, but this PR needs a backend equivalent to reject API requests when users don't have the relevant permission. The relevant functions seem to be `sendEmail` and `sendEmailToAll` in `emailController.js`. Also please add this permission to the [permissions spreadsheet](https://docs.google.com/spreadsheets/d/1TfiJY9OLDZuyP2UgF0C1wI9tOSLKbS9MiJFH6n1Dsao/edit?gid=0#gid=0).

2024-08-18 04:26 UTC, Gauravmg6 approved these changes
Everything works well!

![Screenshot 2024-08-18 002559](https://github.com/user-attachments/assets/230100cf-3211-49a2-a3f8-2b0129a67f4c)

2024-08-22 02:25 UTC, Parth-tech approved these changes
Hi Shadrush,

The PR works correctly. Once the volunteer is assigned the sendEmail permission, user is able to see that option and navigate to the page too.

`Image References:`


<img width="608" alt="Screenshot 2024-08-21 at 7 21 48 PM" src="https://github.com/user-attachments/assets/1bb0cad3-e852-42f4-ad23-660da001bf8f">
<img width="1440" alt="Screenshot 2024-08-21 at 7 19 50 PM" src="https://github.com/user-attachments/assets/c36c72e9-f3ac-4a72-911f-ce8e487c1962">
<img width="606" alt="Screenshot 2024-08-21 at 7 21 55 PM" src="https://github.com/user-attachments/assets/dfad71c8-6602-47e5-b58f-9d9358dba98f">
<img width="1439" alt="Screenshot 2024-08-21 at 7 22 19 PM" src="https://github.com/user-attachments/assets/6fd7e588-2a45-457c-be0f-c669833118f4">
<img width="1438" alt="Screenshot 2024-08-21 at 7 23 00 PM" src="https://github.com/user-attachments/assets/da4b5a37-33bd-4dd9-b160-6bbc4ecb78a6">

2024-08-22 18:56 UTC, skaush21 submitted a review, later dismissed
Retested the 'Send Emails' function, everything works as intended. Implemented code looks good. Tested using backend [PR 1082](https://github.com/OneCommunityGlobal/HGNRest/pull/1082/files)

2024-08-22 21:13 UTC, vishavk1992 reviewed
I approved this PR .

2024-08-22 21:20 UTC, nikhilpittala16 submitted a review, later dismissed
I have retested the PR and everything works as expected.

2024-08-23 05:34 UTC, SMitta11 approved these changes
Initially volunteer account could not see send email and when I gave permission of 'send email' to volunteer and log on as that volunteer who has the permission then send email was visible and the correct page opens up on clicking.
Screenshots:
![Screen Shot 2024-08-23 at 12 13 52 AM](https://github.com/user-attachments/assets/a68809cd-4e31-4f4d-a2ed-213d97fd5539)
![Screen Shot 2024-08-23 at 12 07 29 AM](https://github.com/user-attachments/assets/dbff4f89-e816-400d-9dd8-667595b7a20a)
![Screen Shot 2024-08-23 at 12 15 36 AM](https://github.com/user-attachments/assets/2914bec1-db39-4afd-ade3-b2db3c2b2e17)
![Screen Shot 2024-08-23 at 12 15 46 AM](https://github.com/user-attachments/assets/44c8fc20-80d5-46b7-9e83-1e3d2f980f54)

2024-08-23 23:01 UTC, AJAYINAVOLU reviewed
Changes are working as expected.

![2572-1](https://github.com/user-attachments/assets/0438e99a-290e-420b-8832-a783353f77b1)


Thank You

2024-08-28 18:49 UTC, manikittu810 submitted a review, later dismissed
Hello @Shadhrush5 
I have followed the mentioned steps. Everything is working as mentioned.

https://github.com/user-attachments/assets/c5ccc0fd-ad0c-4ecd-8016-0ecd17e7d5ca

Thank you.

2024-08-30 19:42 UTC, sri0606 approved these changes
Hello @Shadhrush5 , 
I have reviewed the changes. 

Test notes:
* At first, **Other Links** option was not visible on the volunteer account.
* Then, I gave the same account "Send Emails" permission.
* Now, the **Other Links** option is visible and the dropdown menu has "Send emails" option and onClick, navigates to correct page.

![Screenshot 2024-08-30 123523](https://github.com/user-attachments/assets/c2d11bfa-717b-463f-95b9-6fa1bb183547)
![Screenshot 2024-08-30 123803](https://github.com/user-attachments/assets/d4d3b42f-2e05-4c39-a390-3da043b33010)

2024-08-30 22:19 UTC, Shadhrush5 commented
> Everthing looks good here, but this PR needs a backend equivalent to reject API requests when users don't have the relevant permission. The relevant functions seem to be `sendEmail` and `sendEmailToAll` in `emailController.js`. Also please add this permission to the [permissions spreadsheet](https://docs.google.com/spreadsheets/d/1TfiJY9OLDZuyP2UgF0C1wI9tOSLKbS9MiJFH6n1Dsao/edit?gid=0#gid=0).

Changes addressed and the backend PR is approved by the commenter as well.

2024-08-31 20:54 UTC, nathanah commented on src/components/Header/Header.jsx
> +  const canAccessSendEmails = props.hasPermission('sendEmails', !isAuthUser);
```suggestion
  const canAccessSendEmails = props.hasPermission('sendEmails');
```
hasPermission only accepts one argument, right?

2024-08-31 21:00 UTC, nathanah approved these changes

2024-09-01 19:31 UTC, one-community commented
Thank you all, merging!

2024-09-01 19:31 UTC, merged