Aaryaneil unit test weekly summary options
OneCommunityGlobal/HighestGoodNetworkApp pull request #2576
Opened 2024-08-16 18:40 UTC by aaryaneil

# Description
Unit test for `src/components/UserProfile/AddNewUserProfile/WeeklySummaryOptions.jsx`

## Main changes explained:
Added test cases to check for the following
- should not error out due to no tests
- test render summary options
- test handle user profile called on change
- test default value set to required
- test correct value attributes
- test value changes when different option selected
- test render without default value
- test accessibility attributes

## How to test:
1. check into current branch
2. do `npm install`
3. do `npm test VolunteeringTimeTab.test.js`

2024-08-17 04:44 UTC, JatinAgrawal94 requested changes
Error: No Tests Found. Please refer to screenshot.
<img width="1216" alt="Screenshot 2024-08-16 at 9 43 16 PM" src="https://github.com/user-attachments/assets/3f9243f9-74a3-4cc6-b97d-9bbe8daa9e50">

2024-08-18 00:57 UTC, AnkitLall requested changes
I have tested the feature, following the instructions in the PR, and it failed with error. Please refer the screenshots attached below.

<img width="1040" alt="Aaryaneil unit test WeeklySummaryOptions #2576" src="https://github.com/user-attachments/assets/bacaffef-f043-4ce3-8f2e-6c41b98fb7b7">

2024-08-18 03:19 UTC, jinxyou approved these changes
![image](https://github.com/user-attachments/assets/951ba166-5ca2-48c2-9ff6-d073696a3c3f)
The test cannot be found in this branch. Please check if you have all the things in the right place.

2024-08-18 03:21 UTC, jinxyou requested changes
The test cannot be found in this branch. Please check if you have all the things in the right place.
![Screenshot 2024-08-17 211855](https://github.com/user-attachments/assets/774e3b29-c102-4ae6-a96b-2cf48faf4653)

2024-08-18 04:03 UTC, Gauravmg6 requested changes
The test cases are failing. Please check the issue.

![Screenshot 2024-08-18 000242](https://github.com/user-attachments/assets/efe793c2-259b-441a-9770-8f463be3a58a)

2024-08-19 01:37 UTC, Vigneshwar-Muriki approved these changes
Tested this PR and the test failed. Below is the screenshot.

![Screenshot 2024-08-18 213622](https://github.com/user-attachments/assets/ce906783-cbc4-4749-9b7e-8fe13d59a6a4)

2024-08-21 09:04 UTC, beblicarl requested changes
![image](https://github.com/user-attachments/assets/157495bc-5b85-4b3a-8176-a72b0988c087)

2024-08-21 21:00 UTC, nikhilpittala16 requested changes
Error: No tests found. please check the issue
![Screenshot (174)](https://github.com/user-attachments/assets/caef3b03-e4ad-4989-885c-b23262e43029)

2024-08-23 11:42 UTC, aaryaneil commented
Can you test it again with the new instructions?
@JatinAgrawal94 @AnkitLall @jinxyou @Gauravmg6 @Vigneshwar-Muriki @beblicarl @nikhilpittala16

2024-08-23 22:48 UTC, AJAYINAVOLU approved these changes
All test cases are passing without any errors.

![2576-1](https://github.com/user-attachments/assets/410ad70f-ec73-498a-86df-df5a6494b413)


Thank You

2024-08-25 00:02 UTC, Vigneshwar-Muriki requested changes
Tested this PR and some test cases are failing.

2024-09-10 02:54 UTC, ishangoel17 reviewed
All test cases are passing. Below is the screenshot for reference:
![Capture2576](https://github.com/user-attachments/assets/0695853a-32a8-43b4-9c3b-5279ae4fa94b)

2024-09-12 21:42 UTC, RishithaMamidala approved these changes
@aaryaneil 
Tested this PR, and it passes all the test cases.
<img width="672" alt="PR 2576" src="https://github.com/user-attachments/assets/f61bc32f-4534-42dc-a832-e49e67793cd6">

2024-09-26 16:28 UTC, slidracoon72 approved these changes
#2576
@aaryaneil
I have tested this PR, and it successfully passes all test cases.

![PR 2576](https://github.com/user-attachments/assets/8d328cb4-ac5b-4ba3-95df-43de1bba887b)

2024-09-29 00:21 UTC, Watchdog00 reviewed
I have completed the testing and got the expected results. Good job!
<img width="925" alt="#2576" src="https://github.com/user-attachments/assets/b8f765fd-7bc5-46bd-b6b2-ae083c7e200f">

2024-10-03 03:55 UTC, ziyanw52 approved these changes
I have test this PR and all the test cases passed.
![721727927698_ pic_hd](https://github.com/user-attachments/assets/5efeb756-4259-4599-b3f6-34fcbf935444)

2024-10-15 03:26 UTC, navya9989 commented
HI @aaryaneil 
I have tested this PR# 2576 and This passes all the test cases, here is the reference below. Great work!
![2576# PR](https://github.com/user-attachments/assets/d5188be7-5ca0-4f3c-8d62-986c56fd81f0)

2024-10-20 23:07 UTC, navya9989 approved these changes

2024-10-23 02:29 UTC, SatyashanthiT commented
All test cases, including rendering summary options, handling user profile changes, and checking default value and accessibility attributes, passed successfully. Everything is functioning as expected.

<img width="801" alt="image" src="https://github.com/user-attachments/assets/7eb90763-2d01-43a5-95e3-e76bb7849fb4">

2025-04-02 02:41 UTC, closed without merging