bug fix
OneCommunityGlobal/HighestGoodNetworkApp pull request #2583
Opened 2024-08-17 02:29 UTC by suaniii

# Description
![Fix USER MANAGEMENT PAGE UI issues](https://github.com/user-attachments/assets/c713474d-d64d-4e6c-8c36-4fbe45d1a328)

## Related PRS (if any):
For backend use development branch

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links→ User Management
6. Verify that there is spacing to the right of the show button.
7. Ensure the search input size is appropriate at screen widths around 641px and 491px.
8. Check that there is proper spacing and left alignment between top items at 375px.
9. Verify that the user table font size reduces after 750px to minimize side scrolling.
10. Confirm that the setup invitation history modal uses a bordered table and includes placeholders in Email input.
11. Ensure that the placeholder text is fully visible in the Setup New User modal at 375px.
12. Verify that the reset password modal does not have excessive space beneath the labels.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/2fec4875-bdcc-4de9-ba57-bac8fd675234

2024-08-17 04:00 UTC, JatinAgrawal94 requested changes
There is no space between two rows of buttons as shown in below images, rest everything described works.

-----
Reply:
Thank you for the feedback! The lack of space between the two rows of buttons is intentional. If any adjustments are needed in the future, we can revisit this, but for now, this is how it's supposed to look.

<img width="1512" alt="Screenshot 2024-08-16 at 8 59 10 PM" src="https://github.com/user-attachments/assets/df6ccd5a-0a2b-4601-ab96-b39d1597914d">
<img width="1512" alt="Screenshot 2024-08-16 at 8 59 18 PM" src="https://github.com/user-attachments/assets/50ce42c1-9324-4d51-a0a9-dfca4f89e801">

2024-08-17 13:59 UTC, manikittu810 submitted a review, later dismissed
Hello @suaniii , I have gone through every step mentioned and everything is working as mentioned in the description.
<img width="1470" alt="Screenshot 2024-08-17 at 6 57 56 AM" src="https://github.com/user-attachments/assets/ca33b01d-5a26-40d3-a646-13ccc53beaa1">

<img width="1470" alt="Screenshot 2024-08-17 at 6 47 19 AM" src="https://github.com/user-attachments/assets/9961dc69-6f07-4458-9421-65ad278c871a">

<img width="1470" alt="Screenshot 2024-08-17 at 6 46 42 AM" src="https://github.com/user-attachments/assets/4616cf2d-1f4d-4716-8a23-e3e69485e5a5">


<img width="1470" alt="Screenshot 2024-08-17 at 6 46 30 AM" src="https://github.com/user-attachments/assets/8ac3aadb-8a26-4e63-bb2b-3cd9253916f9">
Thank you.

2024-08-17 20:44 UTC, kdaga81 reviewed
![image](https://github.com/user-attachments/assets/9986f2de-a8b8-4a59-a417-82a83f7d4efb)

We can add some margin between the buttons. Rest everything working as expected!

2024-08-31 17:07 UTC, Pranay-ai submitted a review, later dismissed
Hey @suaniii 
The PR is working as expected but they are few issues with it in mobile view
![image](https://github.com/user-attachments/assets/0efadee1-3869-4a57-a042-4ccddde84c07)
The Search and show Inputs are not aligned .
Thank You.

2024-09-04 03:39 UTC, FayeLV commented
Hi, 
Great job! Overall, all functionalities and styles are working as expected, and the design adapts well across different screen sizes:
Button Spacing: The spacing to the right of the "Show" button is correct, keeping the layout tidy.
Input Size: The search input size is appropriate at 641px and 491px, matching the page's style.
Alignment and Spacing: Proper spacing and alignment are maintained at 375px screen width.
Font Scaling: The font size in the user table reduces correctly below 750px, minimizing side scrolling.
Modal Design:
Setup Invitation History Modal: Uses a bordered table, and Email input includes placeholders, meeting design standards.
Setup New User Modal: Placeholder text is fully visible at 375px, ensuring good visual appearance.
Modal Layout: The reset password modal manages spacing under labels well, with no excessive gaps.
![Snipaste_2024-09-03_22-21-20](https://github.com/user-attachments/assets/cf387bc1-dece-4793-9bea-3bb095e9ca89)
![Snipaste_2024-09-03_22-29-12](https://github.com/user-attachments/assets/345a8576-41f6-438c-b5dd-8d4e0dae86de)
![Snipaste_2024-09-03_22-30-47](https://github.com/user-attachments/assets/8f40d42a-b2a2-4da3-bd14-6e6922e9b669)
![Snipaste_2024-09-03_22-31-47](https://github.com/user-attachments/assets/2fda45f9-0a9a-443a-bf68-0116fceff1a7)

2024-09-04 17:01 UTC, sri0606 approved these changes
Hey @suaniii , I have reviewed your PR and tested the UI changes. Everything looks good and as expected.

![Screenshot 2024-09-04 095252](https://github.com/user-attachments/assets/b404f359-77af-41a2-b693-a7f4884d3267)
![Screenshot 2024-09-04 095423](https://github.com/user-attachments/assets/9713010b-33f3-4c9e-8cf3-204ac78fa128)
![Screenshot 2024-09-04 095652](https://github.com/user-attachments/assets/48b560df-7fd3-4580-ac78-86eff2e09980)
![Screenshot 2024-09-04 095720](https://github.com/user-attachments/assets/97b8963b-5ac4-49be-b18a-2828ece133d6)

2024-09-04 19:26 UTC, SnelPatare reviewed
I have tested the changes and everything is working as expected. Please details below
Verify that there is spacing to the right of the show button. - Working as expected
Ensure the search input size is appropriate at screen widths around 641px and 491px. - Working as expected
Check that there is proper spacing and left alignment between top items at 375px. - "Send Setup link" and "Create new user" buttons are overlapping. Needs to improve
Verify that the user table font size reduces after 750px to minimize side scrolling. - Working as expected
Ensure that the placeholder text is fully visible in the Setup New User modal at 375px. - Working as expected
Verify that the reset password modal does not have excessive space beneath the labels. - Working as expected

Please find images below. 
![image](https://github.com/user-attachments/assets/1e9a3f8f-d33f-4b51-b467-dde59412e960)

![image](https://github.com/user-attachments/assets/f5dda5da-5269-443e-9d85-9374117a0c0b)

![image](https://github.com/user-attachments/assets/58206157-c094-435d-9f66-beaff0398583)

![image](https://github.com/user-attachments/assets/2e148ebc-e423-4755-bd59-e440faa797a9)

![image](https://github.com/user-attachments/assets/a37f7d10-0c74-4de8-a64b-1995edfe9dba)

![image](https://github.com/user-attachments/assets/3f84b793-c3f0-4c94-a60b-ded136834bff)

2024-09-04 20:43 UTC, strallia submitted a review, later dismissed
I've tested the functionalities and they work as expected.

These are other issues I found:
-  In Safari, the `select` inputs do not have consistent design with the other inputs and are misaligned.
<img width="1217" alt="Screenshot 2024-09-04 at 1 16 23 PM" src="https://github.com/user-attachments/assets/800b2d37-17cb-42e7-a28c-e93b2ffca9d7">

- At 375px width, design-wise I think there could be more spacing between the top items so the buttons and inputs aren’t touching.
<img width="501" alt="Screenshot 2024-09-04 at 1 22 19 PM" src="https://github.com/user-attachments/assets/8d7588a6-daf8-4016-88ff-94d41effed2f">

- In the Setup Invitation History modal, it would make more sense to have the Email placeholder be “Enter Email” instead of “Your Email” since it’s a list of other people’s emails.

2024-09-06 05:01 UTC, Jingyii800 submitted a review, later dismissed
I have tested this function and it works as expected. While shrinking the page under 600 px width, all button and search box display in a good format.

https://github.com/user-attachments/assets/7c63d79c-0869-432a-9d98-c840368c10e9

2024-09-06 07:29 UTC, sud306 commented
Hi,
I have reviewed the PR and everything looks as expected.
![2  PR2583_1](https://github.com/user-attachments/assets/729d2f3a-5989-4b8b-9d44-efbe79ef28a8)
![2  PR2583_2](https://github.com/user-attachments/assets/e9958f70-e80a-47a9-a835-a1182df503d1)
![2  PR2583_3](https://github.com/user-attachments/assets/d5602ae3-4442-45a5-ba53-110c6b34401e)
![2  PR2583_4](https://github.com/user-attachments/assets/625da5b2-3620-48af-92d5-bfee33a13d4d)
![2  PR2583_5](https://github.com/user-attachments/assets/1a73ce6a-6331-44fd-ac0a-222edbe8a442)

2024-09-06 21:54 UTC, yashwanth170 submitted a review, later dismissed
Everything works as expected!
![mobile_view_1](https://github.com/user-attachments/assets/648ab828-59f0-4142-98c2-12175ea7094d)
![mobile_view_2](https://github.com/user-attachments/assets/a1e504c3-562c-41f8-9598-f89966afaa3f)
![mobile_view_3](https://github.com/user-attachments/assets/90335a0d-320a-46fc-a0ff-d255714cc2bf)

2024-09-06 22:33 UTC, AJAYINAVOLU submitted a review, later dismissed
Changes are working as expected.

<img width="511" alt="PR 2583" src="https://github.com/user-attachments/assets/49c88845-a960-4c89-adc6-9079a0ff5130">
<img width="524" alt="PR 2583-1" src="https://github.com/user-attachments/assets/7a0eeddc-0488-417e-adb1-5418a9bfd395">

Thank You

2024-09-07 00:13 UTC, crystallow1168 submitted a review, later dismissed
Hi @suaniii 

Everything is working as expected and here are my findings: 

✅ Verify that there is spacing to the right of the show button.
✅ Ensure the search input size is appropriate at screen widths around 641px and 491px.
<img width="902" alt="image" src="https://github.com/user-attachments/assets/1c9a3ee0-113f-49ed-ac6e-5001684168c8">

---

✅ Check that there is proper spacing and left alignment between top items at 375px.
<img width="373" alt="image" src="https://github.com/user-attachments/assets/475c0e15-3273-45f9-8983-6948e6fb9912">

Suggestion: Add top/bottom margin to prevent the elements from appearing cramped.
![image](https://github.com/user-attachments/assets/3f1435f0-58d4-4c93-adcc-95f2c23537d3)

---

✅ Verify that the user table font size reduces after 750px to minimize side scrolling.
Confirm that the setup invitation history modal uses a bordered table and includes placeholders in Email input.
<img width="1142" alt="image" src="https://github.com/user-attachments/assets/14f77c62-7823-4a99-9cee-562fff02fecd">

---

✅ Ensure that the placeholder text is fully visible in the Setup New User modal at 375px.

https://github.com/user-attachments/assets/72836672-6fba-414f-87ff-50d4b63c1d19

---

✅ Verify that the reset password modal does not have excessive space beneath the labels.
<img width="386" alt="image" src="https://github.com/user-attachments/assets/dda8de2d-e19a-453f-9424-137d11aadce1">

2024-09-07 02:16 UTC, swaroop-2007 approved these changes

2024-09-07 02:23 UTC, swaroop-2007 commented
Hey, @suaniii 
I reviewed your work and went through it in detail. Everything works well. Thank you! 
![Screenshot (345)](https://github.com/user-attachments/assets/cd3c3ce9-6318-4885-859e-e40413553568)
![Screenshot (346)](https://github.com/user-attachments/assets/5f32090c-2ac0-4281-ae11-a2a244e547f3)
![Screenshot (347)](https://github.com/user-attachments/assets/9ff58bdd-ed64-4a18-87b1-559eb00cd9d7)
![Screenshot (348)](https://github.com/user-attachments/assets/b4f15256-2cab-4411-8136-d7604c14a307)
![Screenshot (349)](https://github.com/user-attachments/assets/a70a7ca2-2645-4d0d-8436-176415c93954)
![Screenshot (350)](https://github.com/user-attachments/assets/6713a2f4-e988-40de-8e16-30b306c9150b)
![Screenshot (351)](https://github.com/user-attachments/assets/f484f010-9a6c-4e51-86df-3a760db16121)

2024-09-07 10:32 UTC, Parth-tech requested changes
Hey Yili,
Your work is working correctly. But I found that between screen size 770px and 991px the labels `Weekly Committed Hours` and `Weekly Summary Options` overflow. If that could be resolved in this PR itself, it would be great.

Image Reference for error:
<img width="1440" alt="Screenshot 2024-09-07 at 3 28 17 AM" src="https://github.com/user-attachments/assets/76ec4c73-65cd-4e81-b0f9-85d0c6df884f">

Correctly Working UI reference images:
<img width="1440" alt="Screenshot 2024-09-07 at 3 27 25 AM" src="https://github.com/user-attachments/assets/580720ec-27bc-4074-b16d-86ed758727e6">
<img width="1440" alt="Screenshot 2024-09-07 at 3 27 33 AM" src="https://github.com/user-attachments/assets/35bcb77b-d565-4147-b899-c2cfb30497d1">
<img width="1440" alt="Screenshot 2024-09-07 at 3 27 41 AM" src="https://github.com/user-attachments/assets/6364b5c3-644d-4980-887e-6bd17f6aa645">
<img width="1440" alt="Screenshot 2024-09-07 at 3 27 52 AM" src="https://github.com/user-attachments/assets/481d5156-2d68-417b-be5e-8872934143bc">
<img width="1440" alt="Screenshot 2024-09-07 at 3 27 57 AM" src="https://github.com/user-attachments/assets/4d2a753c-28a5-4abc-ac94-4bd0a50dc317">
<img width="1440" alt="Screenshot 2024-09-07 at 3 28 04 AM" src="https://github.com/user-attachments/assets/cabd7f31-be17-41da-b0d0-f8a566d377b6">

2024-09-07 21:04 UTC, vedantg24 approved these changes
Tested the PR, and the changes are working as expected.

-There is spacing to the right of the show button.
-The search input size is appropriate at screen widths around 641px and 491px.
![Screenshot 2024-09-07](https://github.com/user-attachments/assets/dee5dab2-3173-4d12-bae9-b453d89e6064)
![Screenshot 2024-09-07](https://github.com/user-attachments/assets/e5bdcba8-580a-4a37-98f7-9a429568bc9b)

-There is proper spacing and left alignment between top items at 375px.
![Screenshot 2024-09-07](https://github.com/user-attachments/assets/07517b87-68fd-438f-9f11-3601631bc2d9)

-The user table font size reduces after 750px.
![Screenshot 2024-09-07](https://github.com/user-attachments/assets/7d75e7ee-402e-4a23-b0c8-fd8c15785372)
![Screenshot 2024-09-07](https://github.com/user-attachments/assets/5ee686cc-d4a8-4c5c-bcfc-5e1bf0630826)

-The setup invitation history modal uses a bordered table and includes placeholders in Email input.
![Screenshot 2024-09-07](https://github.com/user-attachments/assets/e5ff222c-f144-454c-ad18-d387cb4790a0)

-The placeholder text is visible in the Setup New User modal at 375px.
![Screenshot 2024-09-07](https://github.com/user-attachments/assets/4fa3cbb4-b1d7-4d5d-b2fc-adffecef4667)

-The reset password modal does not have excessive space beneath the labels.
![Screenshot 2024-09-07](https://github.com/user-attachments/assets/5cc5807a-ca2f-4f96-85be-d18350ba274b)

2024-09-07 23:17 UTC, vishnupriyaatheti approved these changes
@suaniii I have Verified the PR and changes are working as expected.
![FE PR 2583 reset password](https://github.com/user-attachments/assets/fbb8ab17-7490-43c6-8352-8ee3df52babd)
![FE PR 2583 user table veification](https://github.com/user-attachments/assets/66defd40-38a5-42d9-bc31-88941b5dd6ed)
![FE PR 2583 create new user](https://github.com/user-attachments/assets/643687df-ebdb-46bf-a508-809d9c70272e)

2024-09-09 20:11 UTC, ashayk9 approved these changes
I have tested the pr, verified the following changes and everything is functioning as expected:
1.	Spacing: There is adequate spacing to the right of the "Show" button.
2.	Search Input Size: The search input size is appropriate at screen widths of 641px and 491px.
3.	Top Items Alignment: Proper spacing and left alignment between top items are maintained at 375px.
4.	User Table Font Size: The font size in the user table reduces after 750px
5.	Setup Invitation History Modal: The modal uses a bordered table and includes placeholders in the Email input field.
6.	Setup New User Modal: The placeholder text is fully visible at 375px.
7.	Reset Password Modal: There is no excessive space beneath the labels.
I have uploaded a screenshot to confirm these changes.

![Screenshot 2024-09-09 at 11 27 20 AM](https://github.com/user-attachments/assets/196c8f2e-35c3-42d2-8617-be4f3f7a2534)
![Screenshot 2024-09-09 at 11 28 04 AM](https://github.com/user-attachments/assets/410b0f28-04a7-4ebf-b324-1b76f9233717)
![Screenshot 2024-09-09 at 11 28 37 AM](https://github.com/user-attachments/assets/87f42912-5e1f-4e4e-bb34-216b8a0dc6e8)
![Screenshot 2024-09-09 at 11 30 03 AM](https://github.com/user-attachments/assets/9b35a57b-b85b-4625-83a4-c86fa3142319)
![Screenshot 2024-09-09 at 11 30 15 AM](https://github.com/user-attachments/assets/549d3620-76c1-450a-880f-a824ecd0be5c)
![Screenshot 2024-09-09 at 11 32 30 AM](https://github.com/user-attachments/assets/e4c16076-9d3e-4a2e-9697-c4caf8269f20)
![Screenshot 2024-09-09 at 11 34 12 AM](https://github.com/user-attachments/assets/c44654a5-affd-41f7-a4eb-c587fb3a6caa)
![Screenshot 2024-09-09 at 11 36 03 AM](https://github.com/user-attachments/assets/83d52afb-87cf-47ea-82e9-4e2432c01083)

2024-09-10 04:51 UTC, saurabhshetty29 commented
Suggest adding a margin for tabs that wrap to the second line and changing the color of the 'Search' and 'Show' tabs for better visibility. Everything else looks good!
<img width="956" alt="Screenshot 2024-09-09 at 9 45 16 PM" src="https://github.com/user-attachments/assets/13494a75-858d-4e94-a6e8-dcc58220f79f">
<img width="716" alt="Screenshot 2024-09-09 at 9 47 17 PM" src="https://github.com/user-attachments/assets/2246f254-77b3-464f-bc60-4b55d44943b0">

2024-09-11 20:38 UTC, SFA23SCM35V commented
I have tested the PR and confirmed that the following changes are functioning as expected:

- **Spacing:** Adequate spacing is provided to the right of the "Show" button.
- **Search Input Size:** The search input size is appropriate for screen widths of 641px and 491px.
- **Top Items Alignment:** Proper spacing and left alignment between top items are maintained at 375px.
- **User Table Font Size:** The font size in the user table decreases appropriately after 750px.
- **Invitation History Modal Setup:** The modal uses a bordered table, and placeholders are present in the Email input field.
- **New User Modal Setup:** The placeholder text is fully visible at 375px.
- **Reset Password Modal:** There is no excessive space beneath the labels.

I have also uploaded a screenshot to confirm these changes.
![PR #2583](https://github.com/user-attachments/assets/aae85096-7463-4a20-addf-65559cad5eda)

2024-09-12 05:24 UTC, SFA23SCM35V approved these changes
![pr](https://github.com/user-attachments/assets/843156bf-6c92-41be-ad7b-9a59858f0a66)

2024-09-14 02:00 UTC, Abhinav-Ankur786 submitted a review, later dismissed
It is getting resized and it works as per PR
<img width="492" alt="Screenshot 2024-09-13 at 9 59 32 PM" src="https://github.com/user-attachments/assets/5adb7c12-2608-491a-b793-78ddcaabdd89">

2024-09-14 02:23 UTC, Shreyav2000 submitted a review, later dismissed
Tested the changes, and everything works as expected.

Spacing, alignment, and font size adjustments are perfect across various screen widths.
Modals, placeholders, and table borders display correctly.
Great job on the UI fixes!

https://github.com/user-attachments/assets/7da41d61-e29c-4a12-a89a-89a673fb2002

2024-09-14 02:37 UTC, geetamatkar commented
Hi @suaniii ,
I tested this PR and everything is working as expected. 
 - Search input size is appropriate at screen widths around 641px and 491px.
- There is proper spacing and left alignment between top items at 375px.
- User table font size reduces after 750px to minimize side scrolling.
- Setup invitation history modal uses a bordered table and includes placeholders in Email input.
- Placeholder text is fully visible in the Setup New User modal at 375px.
- Reset password modal does not have excessive space beneath the labels.

I have one suggestion, if there is proper margin spacings between all buttons under user management, it will look better.

<img width="906" alt="PR2583-1" src="https://github.com/user-attachments/assets/1c28863c-a981-43cd-bdbb-cbb73e77e2fe">
<img width="898" alt="PR2583-2" src="https://github.com/user-attachments/assets/e3a01129-e949-437c-bd30-65ba1bb4ae0c">
<img width="1176" alt="PR2583-3" src="https://github.com/user-attachments/assets/18fa6afd-be37-4db8-b779-a6e6990e5798">
<img width="966" alt="PR2583-4" src="https://github.com/user-attachments/assets/74290f7c-da22-46d5-8e77-c271155a4419">

2024-09-14 21:16 UTC, nishitag5 submitted a review, later dismissed
The changes work as described.

https://github.com/user-attachments/assets/a3d891b4-3936-41b0-b15a-43c35be63c33

2024-09-21 19:34 UTC, saurabhshetty29 commented
I tested this PR and everything is working as expected.

https://github.com/user-attachments/assets/a31520bc-1994-454b-a303-cde30b92ddf2

2024-09-22 04:43 UTC, lcohen730 submitted a review, later dismissed
All requirements work and look as expected.

Spacing to the right of show button:
![Screenshot 2024-09-22 at 00 13 24](https://github.com/user-attachments/assets/af0a6fca-7b71-4f78-b211-fbc739686275)

Search input size at screen widths 641px and 491px:
![Screenshot 2024-09-22 at 00 35 06](https://github.com/user-attachments/assets/757ae99e-a8a2-4008-96d1-1b1ef38dfa9d)

Spacing and left alignment of top items at 375px AND space beneath the labels in reset password modal:
![Screenshot 2024-09-22 at 00 37 04](https://github.com/user-attachments/assets/2bbf0cb8-723d-4a36-bd4e-2ba7739989a7)

User table font size reduces after 750px:

https://github.com/user-attachments/assets/e02b9b43-bf8b-4897-8a4b-e5c7d14cdc8e

Setup invitation history modal:
![Screenshot 2024-09-22 at 00 19 44](https://github.com/user-attachments/assets/ac967141-ca82-4432-9d77-897388f8ba54)

Placeholder text in Setup New User modal at 375px:

https://github.com/user-attachments/assets/9c12faf6-d7d5-4aee-b7f5-70c0733f2009

2024-09-23 18:31 UTC, ashmita123 submitted a review, later dismissed
Tested PR #2583. UI changes on the User Management Page work as expected. 


https://github.com/user-attachments/assets/2060b052-a787-4060-ac5b-fcc1cd09057f

2024-09-25 21:15 UTC, nevatiarishabh approved these changes
Everything is working as expected. Looks good to me.

Spacing to the right of the show button.
Search input size is appropriate at screen widths around 641px and 491px.
![Screenshot 2024-09-25 at 2 01 01 PM](https://github.com/user-attachments/assets/bee27ad3-b436-43b8-96e1-fedfbccdc61f)
![Screenshot 2024-09-25 at 2 00 12 PM](https://github.com/user-attachments/assets/60dc5ae3-0757-4ac8-a903-7bfcdf552f53)

There is proper spacing and left alignment between top items at 375px.
![Screenshot 2024-09-25 at 2 02 42 PM](https://github.com/user-attachments/assets/3359fd35-6514-4369-82d3-3ce76db37a58)

The user table font size reduces after 750px to minimize side scrolling.
![Screenshot 2024-09-25 at 2 04 29 PM](https://github.com/user-attachments/assets/c6b0bb72-18ba-46f7-9468-43985caa9e9e)
![Screenshot 2024-09-25 at 2 06 50 PM](https://github.com/user-attachments/assets/4b56bf99-6bb1-461c-b6b5-afabe203fb6d)

The setup invitation history modal uses a bordered table and includes placeholders in Email input.
![Screenshot 2024-09-25 at 2 10 38 PM](https://github.com/user-attachments/assets/62092033-a195-4117-a4bd-f79262fad196)

The placeholder text is fully visible in the Setup New User modal at 375px.
![Screenshot 2024-09-25 at 2 12 36 PM](https://github.com/user-attachments/assets/e6e25870-760f-4f25-97af-5b45e1585c5c)

The reset password modal does not have excessive space beneath the labels.
![Screenshot 2024-09-25 at 2 13 43 PM](https://github.com/user-attachments/assets/b08cf9c9-d89c-4e4d-9c68-d39dd1fd478c)

2024-09-26 23:28 UTC, mrinalini-raghavendran19 approved these changes
Hello!

These changes look good to me!

Here are some screenshots from testing the changes in narrower screen sizes.

<img width="1470" alt="Screenshot 2024-09-26 at 4 25 57 PM" src="https://github.com/user-attachments/assets/5ce93b3a-7f3a-4acf-b1c9-145309e53cfd">
<img width="506" alt="Screenshot 2024-09-26 at 4 26 26 PM" src="https://github.com/user-attachments/assets/6db5424f-455e-4262-a86b-988cb4df7485">
<img width="506" alt="Screenshot 2024-09-26 at 4 26 54 PM" src="https://github.com/user-attachments/assets/b69dea87-a872-4074-ba62-8b4461470fdf">
<img width="506" alt="Screenshot 2024-09-26 at 4 27 01 PM" src="https://github.com/user-attachments/assets/5ea5103c-1c3c-4c79-9f2c-532ef08ba64a">

I think having gaps between the buttons in narrower screens would make it look less compressed and more spaced out for better ui.

2024-09-29 06:06 UTC, Muzammil603 approved these changes
![image](https://github.com/user-attachments/assets/e3c6e948-29a7-440d-96e3-4e88b2037161)
![image](https://github.com/user-attachments/assets/4d3a3d71-ddfe-49d5-b148-48cf9ff3d221)
![image](https://github.com/user-attachments/assets/eb3889ea-a033-4b1a-8bc3-b15da8bf5901)
working as expected

2024-10-03 05:47 UTC, ziyanw52 requested changes
Hi Yili, when I test the UI at a 504px width, I found the search function isn't displaying perfectly.  I'm unable to scroll to the right to type the name properly. Please see the second screenshot for reference.
![781727934095_ pic_hd](https://github.com/user-attachments/assets/8fa203a6-aca2-40ed-935c-9dc622aba9ac)
![771727934070_ pic_hd](https://github.com/user-attachments/assets/148fb876-a74b-44d4-bbe9-ec9b16fffbcd)

2024-10-05 06:28 UTC, javid679 commented
Hey, 
Everything is working fine as intended. but the text is not aligned in the center of the boxes, apart from that everything is working fine. Great work !

1. Text is alinged at 750px  as intended, as i said, text should have been centered.

![Screenshot (26)](https://github.com/user-attachments/assets/1918ab1e-7c8b-46ad-9fa6-0ad67582a6cd)

2. There is proper spacing and left alignment between top items at 375px.

![Screenshot (27)](https://github.com/user-attachments/assets/0567e034-7f49-4e9f-a320-6dfb47a91511)

3. The search input size is appropriate at screen widths around 641px and 491px

![Screenshot (28)](https://github.com/user-attachments/assets/89a47b4c-0755-4ad6-8dee-b7c0eba327df)
 
4. The reset password modal does not have excessive space beneath the labels
![Screenshot (31)](https://github.com/user-attachments/assets/20cef6dc-dbb7-480e-8273-c3018a3a7f1e)

5 .The setup invitation history modal uses a bordered table and includes placeholders in Email input.
![Screenshot (29)](https://github.com/user-attachments/assets/2600c199-d885-405c-b443-9ee2df0cb686)

6. The placeholder text is fully visible in the Setup New User modal at 375px
![Screenshot (30)](https://github.com/user-attachments/assets/c81e71ed-c842-4365-a35e-801a1b09299f)

2024-10-08 08:37 UTC, neeharikakoniki approved these changes
The adjustments for responsive design on the User Management page work well across various screen sizes, improving layout and readability. I tested each specified screen width, and all elements, including spacing, font size, and modals, displayed correctly without any issues.

![image](https://github.com/user-attachments/assets/939dabd4-d988-46bf-bab3-44f58633d22a)
![image](https://github.com/user-attachments/assets/95c4032c-7572-46b8-95df-af91d6eb6f90)

2024-10-18 06:54 UTC, Anoushka21 requested changes
Tested out with admin account.
**Spacing between buttons is still an issue, they are kind of joined, will need to fix!** 
Alignment and spacing on top items is okay.
User table font size also reducing!
Bordered table, spacing and placeholder text visibility is working!
![image](https://github.com/user-attachments/assets/7f68c835-32bb-4ef2-ba9f-e28c69df1272)

----

Reply
Thank you for the feedback. This is how it's supposed to look.

2024-10-19 19:38 UTC, bhavya17prakash requested changes
The spacing and alignment are not working as expected. **Needs to be fixed!!**
<img width="359" alt="PR 2583" src="https://github.com/user-attachments/assets/d6d798f5-4aa7-4a47-81b8-a2f8a3fe16ff">

2024-10-27 01:21 UTC, zhiminV requested changes
I login as admin user, and I have checked the following features:

1. there is spacing to the right of the show button.
2. search input size is appropriate
3. Check that there is proper spacing and left alignment between top items at 375px.
4. 750px can scrolling screen
5.  setup invitation history, Setup New User, and reset password modal work expected.

Suggestions: Spacing between buttons could be improve,  there is some overlapping

https://github.com/user-attachments/assets/0c456e0a-e1e6-45d0-9858-8c759e9c1a51

![IMG_0986](https://github.com/user-attachments/assets/a1352e85-f881-4219-8cb5-b06a7c314623)
![IMG_0987](https://github.com/user-attachments/assets/1468652e-78a4-4162-ab12-8a01a5a5b651)

2024-10-27 02:35 UTC, Rupa2400 submitted a review, later dismissed
I tested the recent changes, and most things look good. Here’s what I found:

Spacing to the right of the "Show" button – working.
Search input adjusts well around 641px and 491px – no issues.
Spacing and alignment at 375px – slight overlap with "Send Setup Link" and "Create New User" buttons.
User table font size decreases after 750px, which helps reduce side-scrolling – all good.
Placeholder text in the "Setup New User" modal is visible at 375px – no problems.
Reset password modal doesn’t have extra space under the labels – looks good.

https://github.com/user-attachments/assets/36127d65-7029-44c2-8966-0309a8e77e27

2024-10-31 19:55 UTC, humera314 commented
Show does not have space near the search.  Works fine for search input size is appropriate at screen widths around 641px and 491px.

![image](https://github.com/user-attachments/assets/42b0c637-1dee-4d8c-9ba0-d8c0d26b77ad)

there is proper spacing and left alignment between top items at 375px.
![image](https://github.com/user-attachments/assets/8217c3bc-e85e-4309-b5f1-7e1f8895325d)

user table font size reduces after 750px to minimize side scrolling.
![image](https://github.com/user-attachments/assets/2fd75358-593d-4e27-8417-08919e2bdb99)

everything alings perfectly
![image](https://github.com/user-attachments/assets/d89d7161-12f9-48e0-a100-00c2d05c9734)
![image](https://github.com/user-attachments/assets/86f73b09-0e07-489d-b393-e98c657c55e0) ![image](https://github.com/user-attachments/assets/8cfffbeb-37c1-470f-8695-4019058d6329)

2024-11-02 20:54 UTC, SupriyaSudini requested changes
I have reviewed the changes and everything is working fine and has been approved. However, I noticed there is no space to the right of the "Show" button. Could this be adjusted?

![image](https://github.com/user-attachments/assets/60bbd8b8-aae5-41eb-ab0b-0772e8659d70)

The search input size is appropriate to the screen width 641px and 491px

![image](https://github.com/user-attachments/assets/2d889f13-58f1-4e8f-bd01-aecdf298923f)

![image](https://github.com/user-attachments/assets/6aa259c1-b3c0-460f-ba9f-f4dc999a444a)

At 375px, lack of space between the rows and for smaller screens from 819px
![image](https://github.com/user-attachments/assets/e24ea637-720e-4dda-bf64-7cf4986cd062)

Setup invitation modal history uses the table and has input placeholder for email
![image](https://github.com/user-attachments/assets/94b8cbf8-c486-4093-b090-2c03226e4426)

![image](https://github.com/user-attachments/assets/36686541-58bd-4f92-98b0-fd0431555b5f)

Reset password button does not have excessive space beneath the labels
![image](https://github.com/user-attachments/assets/da091387-a065-48fe-997f-0cb5e63b316c)

2024-11-05 18:23 UTC, AshritaCherlapally submitted a review, later dismissed
Code changes works as expected. As a suggestion, there can be margin space between the search and show buttons. Rest everything works as expected.

https://github.com/user-attachments/assets/50d64680-ae33-457d-8368-8919ca58ca58

2024-11-09 07:56 UTC, suaniii commented
> Code changes works as expected. As a suggestion, there can be margin space between the search and show buttons. Rest everything works as expected.
> 
>  PR.2583.mov

Added space, please review again

2024-11-09 07:56 UTC, suaniii commented
> I have reviewed the changes and everything is working fine and has been approved. However, I noticed there is no space to the right of the "Show" button. Could this be adjusted?
> 
> ![image](https://private-user-images.githubusercontent.com/95210394/382507689-60bbd8b8-aae5-41eb-ab0b-0772e8659d70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii85NTIxMDM5NC8zODI1MDc2ODktNjBiYmQ4YjgtYWFlNS00MWViLWFiMGItMDc3MmU4NjU5ZDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMWIxZjRiN2UyYWU0YWM2ZjQ1YjU5NzA2NzcxNGEyMTM5OGY1NTAxNWUzNjIzZWJmN2U5NzlmZWQ2YzE5YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RxwqG4NJTzta-IouAdcNc9078Hq23Z2ZAnBjwvYvvzQ)
> 
> The search input size is appropriate to the screen width 641px and 491px
> 
> ![image](https://private-user-images.githubusercontent.com/95210394/382507713-2d889f13-58f1-4e8f-bd01-aecdf298923f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii85NTIxMDM5NC8zODI1MDc3MTMtMmQ4ODlmMTMtNThmMS00ZThmLWJkMDEtYWVjZGYyOTg5MjNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NzE4NDY3NDEzZTk3ODY0ZGEzYzI3ODExMzJjNjUzZGZmZjJlNDgwY2RmYWU4OWIzNzRlODFlNjUwYTgyOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E8Ve__lcoQdF-LIsXXUHjxzwQCO_lS4n9OMSDLlAc5o)
> 
> ![image](https://private-user-images.githubusercontent.com/95210394/382507718-6aa259c1-b3c0-460f-ba9f-f4dc999a444a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii85NTIxMDM5NC8zODI1MDc3MTgtNmFhMjU5YzEtYjNjMC00NjBmLWJhOWYtZjRkYzk5OWE0NDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZTdkNTBmM2FmODVkNzQ1ZWY1ZTI4M2I1MDkzMTZlYmY1YWVhYmExNjkyOGM4YzZkNDQ5Yzk5ZjU0NmNkMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4l6P0uze50MXf9lYw8L7R8EL109ASE9L7C7Th-wLAvk)
> 
> At 375px, lack of space between the rows and for smaller screens from 819px ![image](https://private-user-images.githubusercontent.com/95210394/382507737-e24ea637-720e-4dda-bf64-7cf4986cd062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii85NTIxMDM5NC8zODI1MDc3MzctZTI0ZWE2MzctNzIwZS00ZGRhLWJmNjQtN2NmNDk4NmNkMDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NGU2NDlhODY3NjYyYjJmNzhkYmU1ODlkMTQyYmIxYzY3YmEwODc1MWQyZTlhNTYwMjIyYjUyZTI5YWU0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fHC4JX9tQ3VlypdtnzEf4pkcbeWNNWLfZzmyIXduYfg)
> 
> Setup invitation modal history uses the table and has input placeholder for email ![image](https://private-user-images.githubusercontent.com/95210394/382507765-94b8cbf8-c486-4093-b090-2c03226e4426.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii85NTIxMDM5NC8zODI1MDc3NjUtOTRiOGNiZjgtYzQ4Ni00MDkzLWIwOTAtMmMwMzIyNmU0NDI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyODdlMDlhYzc5NGQwYjczNTE3ZmY5NWYzMTUxYTdiZThhOGI3Nzg1NzUzYmM2ZjA1NDcxMjBlNWIzNDNlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LHKkHfo0UObmF467bR0KRoyI95fcTbVQ66lFTO_gOM4)
> 
> ![image](https://private-user-images.githubusercontent.com/95210394/382507775-36686541-58bd-4f92-98b0-fd0431555b5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii85NTIxMDM5NC8zODI1MDc3NzUtMzY2ODY1NDEtNThiZC00ZjkyLTk4YjAtZmQwNDMxNTU1YjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4Y2E4Njg1NTVhN2QxODQ3ZjZlYjE5YWUzMTJjMzA5NjZkOWIyZGE5MmM1ZWNmMWY4Yzk4MTA5ZDA3YzE0MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LTBG4_FmKveE7Nt53Ncpwrm9I3XN7X7O2A68QSt9SMg)
> 
> Reset password button does not have excessive space beneath the labels ![image](https://private-user-images.githubusercontent.com/95210394/382507796-da091387-a065-48fe-997f-0cb5e63b316c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii85NTIxMDM5NC8zODI1MDc3OTYtZGEwOTEzODctYTA2NS00OGZlLTk5N2YtMGNiNWU2M2IzMTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNTFhOTdjMThkYjgxZGU3ZmVkODhhNmI2MjUzMTgwMmU1MDlmNTlkZmM3MDAxYmM5ZjBmNjI1YTU1YmQzODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6wPsm5Nvidgui3cRwvaFqbY-EbhtdQoGC6GG8Kxa8tg)

Added space, please review again

2024-11-09 07:57 UTC, suaniii commented
> Code changes works as expected. As a suggestion, there can be margin space between the search and show buttons. Rest everything works as expected.
> 
>  PR.2583.mov

Added space, please review again.

2024-11-09 07:58 UTC, suaniii commented
> I have reviewed the changes and everything is working fine and has been approved. However, I noticed there is no space to the right of the "Show" button. Could this be adjusted?
> 
> ![image](https://private-user-images.githubusercontent.com/95210394/382507689-60bbd8b8-aae5-41eb-ab0b-0772e8659d70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii85NTIxMDM5NC8zODI1MDc2ODktNjBiYmQ4YjgtYWFlNS00MWViLWFiMGItMDc3MmU4NjU5ZDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMWIxZjRiN2UyYWU0YWM2ZjQ1YjU5NzA2NzcxNGEyMTM5OGY1NTAxNWUzNjIzZWJmN2U5NzlmZWQ2YzE5YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RxwqG4NJTzta-IouAdcNc9078Hq23Z2ZAnBjwvYvvzQ)
> 
> The search input size is appropriate to the screen width 641px and 491px
> 
> ![image](https://private-user-images.githubusercontent.com/95210394/382507713-2d889f13-58f1-4e8f-bd01-aecdf298923f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii85NTIxMDM5NC8zODI1MDc3MTMtMmQ4ODlmMTMtNThmMS00ZThmLWJkMDEtYWVjZGYyOTg5MjNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NzE4NDY3NDEzZTk3ODY0ZGEzYzI3ODExMzJjNjUzZGZmZjJlNDgwY2RmYWU4OWIzNzRlODFlNjUwYTgyOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E8Ve__lcoQdF-LIsXXUHjxzwQCO_lS4n9OMSDLlAc5o)
> 
> ![image](https://private-user-images.githubusercontent.com/95210394/382507718-6aa259c1-b3c0-460f-ba9f-f4dc999a444a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii85NTIxMDM5NC8zODI1MDc3MTgtNmFhMjU5YzEtYjNjMC00NjBmLWJhOWYtZjRkYzk5OWE0NDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZTdkNTBmM2FmODVkNzQ1ZWY1ZTI4M2I1MDkzMTZlYmY1YWVhYmExNjkyOGM4YzZkNDQ5Yzk5ZjU0NmNkMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4l6P0uze50MXf9lYw8L7R8EL109ASE9L7C7Th-wLAvk)
> 
> At 375px, lack of space between the rows and for smaller screens from 819px ![image](https://private-user-images.githubusercontent.com/95210394/382507737-e24ea637-720e-4dda-bf64-7cf4986cd062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii85NTIxMDM5NC8zODI1MDc3MzctZTI0ZWE2MzctNzIwZS00ZGRhLWJmNjQtN2NmNDk4NmNkMDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NGU2NDlhODY3NjYyYjJmNzhkYmU1ODlkMTQyYmIxYzY3YmEwODc1MWQyZTlhNTYwMjIyYjUyZTI5YWU0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fHC4JX9tQ3VlypdtnzEf4pkcbeWNNWLfZzmyIXduYfg)
> 
> Setup invitation modal history uses the table and has input placeholder for email ![image](https://private-user-images.githubusercontent.com/95210394/382507765-94b8cbf8-c486-4093-b090-2c03226e4426.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii85NTIxMDM5NC8zODI1MDc3NjUtOTRiOGNiZjgtYzQ4Ni00MDkzLWIwOTAtMmMwMzIyNmU0NDI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyODdlMDlhYzc5NGQwYjczNTE3ZmY5NWYzMTUxYTdiZThhOGI3Nzg1NzUzYmM2ZjA1NDcxMjBlNWIzNDNlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LHKkHfo0UObmF467bR0KRoyI95fcTbVQ66lFTO_gOM4)
> 
> ![image](https://private-user-images.githubusercontent.com/95210394/382507775-36686541-58bd-4f92-98b0-fd0431555b5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii85NTIxMDM5NC8zODI1MDc3NzUtMzY2ODY1NDEtNThiZC00ZjkyLTk4YjAtZmQwNDMxNTU1YjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4Y2E4Njg1NTVhN2QxODQ3ZjZlYjE5YWUzMTJjMzA5NjZkOWIyZGE5MmM1ZWNmMWY4Yzk4MTA5ZDA3YzE0MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LTBG4_FmKveE7Nt53Ncpwrm9I3XN7X7O2A68QSt9SMg)
> 
> Reset password button does not have excessive space beneath the labels ![image](https://private-user-images.githubusercontent.com/95210394/382507796-da091387-a065-48fe-997f-0cb5e63b316c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii85NTIxMDM5NC8zODI1MDc3OTYtZGEwOTEzODctYTA2NS00OGZlLTk5N2YtMGNiNWU2M2IzMTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNTFhOTdjMThkYjgxZGU3ZmVkODhhNmI2MjUzMTgwMmU1MDlmNTlkZmM3MDAxYmM5ZjBmNjI1YTU1YmQzODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6wPsm5Nvidgui3cRwvaFqbY-EbhtdQoGC6GG8Kxa8tg)

Added space, please review again.

2024-11-09 07:58 UTC, suaniii commented
> Show does not have space near the search. Works fine for search input size is appropriate at screen widths around 641px and 491px.
> 
> ![image](https://private-user-images.githubusercontent.com/69070883/382090444-42b0c637-1dee-4d8c-9ba0-d8c0d26b77ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii82OTA3MDg4My8zODIwOTA0NDQtNDJiMGM2MzctMWRlZS00ZDhjLTliYTAtZDhjMGQyNmI3N2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MWY0OTVmZTJhYTg1MTg1ZGFmNzFkYzkxYzM0ZGMyMzY0MDhkYjZkZjg5NmRkMDE1ZGRmZjk3OGM0MTM0NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6x0GIqnYGMX6nYxKOBe6qzQXAsUHV9SqpT4-PhP4-bI)
> 
> there is proper spacing and left alignment between top items at 375px. ![image](https://private-user-images.githubusercontent.com/69070883/382092136-8217c3bc-e85e-4309-b5f1-7e1f8895325d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii82OTA3MDg4My8zODIwOTIxMzYtODIxN2MzYmMtZTg1ZS00MzA5LWI1ZjEtN2UxZjg4OTUzMjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZmVhNjExMDQ3MTZlNTBmNmY5OTRhZWViMTI3OWQ0OGJjMjEyZWMzMmRkM2YxZjYyYzI3ODAwYzNlMDk4ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GrWVyINYIezpLdY4pp16go0hHMMGnL7c2e6u840MKoM)
> 
> user table font size reduces after 750px to minimize side scrolling. ![image](https://private-user-images.githubusercontent.com/69070883/382093202-2fd75358-593d-4e27-8417-08919e2bdb99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii82OTA3MDg4My8zODIwOTMyMDItMmZkNzUzNTgtNTkzZC00ZTI3LTg0MTctMDg5MTllMmJkYjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZmI2OWFhYzJmMDhlZDUxNDhiNzYwYjIyMDhjZmE4YjUxYmI1YWM4ODJiYmY5YjU4MjRiMDZjMGZjMWQ4NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gm_s8hF2KYe5pt4GxyL-Izt365bn292NSMUC79n9XJE)
> 
> everything alings perfectly ![image](https://private-user-images.githubusercontent.com/69070883/382095464-d89d7161-12f9-48e0-a100-00c2d05c9734.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii82OTA3MDg4My8zODIwOTU0NjQtZDg5ZDcxNjEtMTJmOS00OGUwLWExMDAtMDBjMmQwNWM5NzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZTE3NGRmYzk0ZDFjODEyNmZjMjg0ODdlYjRkZjdhNjc1ODA3MzVlNDZjMTA0YWQxYjczZjgyOTNkNTE5ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dwYFcNw0TfWFktzgYtHGyHZLMhI5TZkDNP7FrCkbVa4) ![image](https://private-user-images.githubusercontent.com/69070883/382095828-86f73b09-0e07-489d-b393-e98c657c55e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii82OTA3MDg4My8zODIwOTU4MjgtODZmNzNiMDktMGUwNy00ODlkLWIzOTMtZTk4YzY1N2M1NWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMDBjMDQzNzM4NDdmZTFlYTlhNDg4MDA5ZTZhZDA0NTJmZWI3ZjcxMzA3YWE4OWQzNjgyYjkzYzdiOWM0N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A1zNGYeIl16ei1q90YLfs5IDsreMl1NeMoICubTlRsk) ![image](https://private-user-images.githubusercontent.com/69070883/382096524-8cfffbeb-37c1-470f-8695-4019058d6329.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzkxNzUsIm5iZiI6MTczMTEzODg3NSwicGF0aCI6Ii82OTA3MDg4My8zODIwOTY1MjQtOGNmZmZiZWItMzdjMS00NzBmLTg2OTUtNDAxOTA1OGQ2MzI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NDY5N2Q0OTkxNjQ3NDA1ZDVlNjFiYzdkZWM4NTNkMjZiZmUwNjU5OTM4YTUwMTNhN2M1MTA0ZTU2YTJiYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R_7X3FNHtS46YnI5Rza2CrF6H5Ir-6nPns0L6wVb6tM)

Added space, please review again.

2024-11-09 07:59 UTC, suaniii commented
> zhiminV

Added space, please review again.

2025-01-17 21:11 UTC, honglinchen0524 approved these changes
Great work! All features work as intended.

https://github.com/user-attachments/assets/bb211543-09d7-4e64-bc30-936bc01da301

2025-02-08 05:13 UTC, bhavya17prakash submitted a review, later dismissed
Reviewed Changes. Works as Expected.

https://github.com/user-attachments/assets/2128e9e4-8479-42b6-802b-1247be43eedd

2025-03-16 01:53 UTC, HarideepValiveru commented
Reviewed PR. The code is well-organized and covers a lot of functionality like managing users, permissions, modals, and UI updates. It works as expected

2025-03-29 23:53 UTC, myeeli commented
I have checked out the PR. Although all the functionalities are working as expected , while clicking on reset password i could see the field names are displayed twice, as you can see in the last picture. Also, i could see some display statements and warnings are getting displayed in the console when navigated to the user management screen. 

<img width="297" alt="PR 2583 - 1" src="https://github.com/user-attachments/assets/af53ac04-175e-4d09-aeea-14a58465023a" />
<img width="293" alt="PR 2583 - 2" src="https://github.com/user-attachments/assets/7768177e-22c7-4063-802a-a7e74bb9d81a" />
<img width="556" alt="PR 2583 - 3" src="https://github.com/user-attachments/assets/6906a677-cc94-4a94-aa4c-a38d4e889a82" />
<img width="300" alt="PR 2583 - 4" src="https://github.com/user-attachments/assets/fad93504-833d-4f0c-a57c-64ac99804e01" />
<img width="949" alt="PR 2583 - 5" src="https://github.com/user-attachments/assets/e7d0eb15-3ad1-432b-8dcd-a9b006acd95f" />
<img width="945" alt="PR 2583 - 6" src="https://github.com/user-attachments/assets/9a79a52f-d2c5-48bc-9fa8-a30ce39f536d" />

2025-03-30 20:50 UTC, myeeli reviewed
I have checked out the PR. Although all the functionalities are working as expected , while clicking on reset password i could see the field names are displayed twice, as you can see in the last picture. Also, i could see some display statements and warnings are getting displayed in the console when navigated to the user management screen. 

<img width="297" alt="PR 2583 - 1" src="https://github.com/user-attachments/assets/af53ac04-175e-4d09-aeea-14a58465023a" />
<img width="293" alt="PR 2583 - 2" src="https://github.com/user-attachments/assets/7768177e-22c7-4063-802a-a7e74bb9d81a" />
<img width="556" alt="PR 2583 - 3" src="https://github.com/user-attachments/assets/6906a677-cc94-4a94-aa4c-a38d4e889a82" />
<img width="300" alt="PR 2583 - 4" src="https://github.com/user-attachments/assets/fad93504-833d-4f0c-a57c-64ac99804e01" />
<img width="949" alt="PR 2583 - 5" src="https://github.com/user-attachments/assets/e7d0eb15-3ad1-432b-8dcd-a9b006acd95f" />
<img width="945" alt="PR 2583 - 6" src="https://github.com/user-attachments/assets/9a79a52f-d2c5-48bc-9fa8-a30ce39f536d" />

2025-04-05 04:31 UTC, suaniii commented
> I have checked out the PR. Although all the functionalities are working as expected , while clicking on reset password i could see the field names are displayed twice, as you can see in the last picture. Also, i could see some display statements and warnings are getting displayed in the console when navigated to the user management screen.

Thanks for the feedback. My changes focused solely on the UI fixes described in the ticket, and the duplicate field names and console warnings appear to be pre-existing issues outside my scope.

2025-04-09 03:16 UTC, merged