Diya Export All Badges to PDF Fix
OneCommunityGlobal/HighestGoodNetworkApp pull request #2604
Opened 2024-08-22 23:59 UTC by DiyaWadhwani

# Description
Export All Badges to PDF exports only old assigned badges and not any newly created and assigned badge.
User Profile > Select Featured > Export All Badges to PDF does not work as expected.

## Related PRS (if any):
N/A

## Main changes explained:
Added a fallback image if the image of the badge cannot load which fails the conversion of that badge to be added to the PDF

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to view profile → select featured → export all badges to PDF
6. verify that all badges get added to the PDF
7. create new badges, assign them to a user and verify if required.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/100e25b4-f91e-43e3-9d84-7dc57649c1de

2024-08-23 07:47 UTC, manikittu810 approved these changes
Hello @DiyaWadhwani 
I have verified the changes , they are working as mentioned.

![Uploading Screenshot 2024-08-23 at 12.46.06 AM.png…]()

Thank you.

2024-08-23 18:45 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/7871b967-4f84-4eb0-9885-cd8a5673c0f0

2024-08-23 21:35 UTC, AJAYINAVOLU approved these changes
Changes are working as expected.

![2604-1](https://github.com/user-attachments/assets/bf797bb4-0be0-44a2-8b5e-aceee2dbe204)


Thank you

2024-08-23 22:30 UTC, jinxyou approved these changes
The function looks good. 
![Screenshot 2024-08-23 162858](https://github.com/user-attachments/assets/76aee125-37ed-43e7-bfbc-ff775fd1fa61)
![Screenshot 2024-08-23 162917](https://github.com/user-attachments/assets/26b276de-fc33-4c1d-8586-377024aea6b7)

2024-08-24 02:56 UTC, kdaga81 requested changes
![image](https://github.com/user-attachments/assets/5c2916c5-f6c5-45a8-863e-05f1237407bf)

Changes are working as expected when there are badges. However, if we don't have any badge and clicking on "Export all badges to pdf", it's not giving any WARNING/ERROR message.

2024-08-25 06:25 UTC, Gauravmg6 approved these changes
Everything works as expected.
![Screenshot 2024-08-25 022435](https://github.com/user-attachments/assets/89083192-c0c5-4452-922a-90919e841505)

2024-08-26 02:48 UTC, Saniya98 approved these changes
Changes are working as  expected
![2604-1](https://github.com/user-attachments/assets/faafe650-0890-485b-a24a-ea2dd0a6fe68)

2024-08-30 01:04 UTC, JatinAgrawal94 approved these changes
Changes work as expected. Good work.

https://github.com/user-attachments/assets/926965c5-69a6-40d9-91ef-ac9861b124a8

2024-08-30 17:25 UTC, preethamdnr approved these changes
Hello Diya,
I have reviewed this PR and is working as expected.

https://github.com/user-attachments/assets/9fa64094-319f-4d50-ac52-430c4cf4731e

2024-08-30 17:55 UTC, gowthamdongari approved these changes
Hello Diya,
I have reviewed this PR and working as expected.


https://github.com/user-attachments/assets/fb7d683b-abb1-4d77-aadd-8a406103ffec

2024-08-30 19:51 UTC, Pranay-ai approved these changes
Hey @DiyaWadhwani 
I have reviewed the PR, the changes are working as expected.
![image](https://github.com/user-attachments/assets/9644bf05-a735-439d-9c1e-f59b6d40610c)
![image](https://github.com/user-attachments/assets/5ac9a128-8985-467b-ad8d-16eac58e9ad4)

Thank You

2024-08-31 19:09 UTC, merged