Nahiyan_Optimized dashboard for mobile view
OneCommunityGlobal/HighestGoodNetworkApp pull request #2614
Opened 2024-08-24 17:10 UTC by Nahiyan-16

# Description
ALL THE RED LINES FIXED
![Screenshot 2024-08-24 130520](https://github.com/user-attachments/assets/e19af1f7-7e7f-42cc-ba7f-71c30a1d986c)

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- Aligned dashboard components when 991px and below
- Created new dropdown for days sector when below 768px.
- Aligned Tracking/Hide button to the right

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard
6. verify dashboard components are aligned when 991px and below
7. verify that days selector displays correctly when 768px and below
8. verify that Tracking/Hide button is aligned to the right.
9. verify these new features works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:
![Screenshot 2024-08-24 115005](https://github.com/user-attachments/assets/41e5c924-6e67-4c77-9e87-432b65ad5fe4)
![Screenshot 2024-08-24 130151](https://github.com/user-attachments/assets/ce7bb29a-054a-433d-b813-1e5295063bc6)

2024-08-24 17:48 UTC, Parth-tech submitted a review, later dismissed
Hey Nahiyan,
The UI works well at varying screen sizes and in both light and dark mode.
Great job done.

`Image references:`

<img width="689" alt="Screenshot 2024-08-24 at 10 47 10 AM" src="https://github.com/user-attachments/assets/08dbfab2-17da-48c4-93d4-4e6668044acf">
<img width="845" alt="Screenshot 2024-08-24 at 10 42 16 AM" src="https://github.com/user-attachments/assets/1af031bc-fcdf-445a-b1c6-9144df9e302f">

2024-08-24 19:33 UTC, Pranay-ai approved these changes
Hey @Nahiyan-16 
The PR is Working as expected please find the related screenshots.
![image](https://github.com/user-attachments/assets/97198636-ce09-47f4-bcf7-c138068c69a7)
![image](https://github.com/user-attachments/assets/4b4c2d52-05f5-4340-820b-50034d937621)
![image](https://github.com/user-attachments/assets/6e2c1ff5-3ecd-47de-8727-688567df1221)
Thank You.

2024-08-24 19:51 UTC, kdaga81 requested changes
![image](https://github.com/user-attachments/assets/01f32432-af88-434c-9b44-b6a066fffbd2)

The date selector's dropdown is displayed in the middle. Please check the image for reference.

2024-08-24 20:24 UTC, SnelPatare approved these changes
Working as expected!!

![image](https://github.com/user-attachments/assets/df6d51d4-5aac-4d95-a4f2-46a1f2a1c9cd)

![image](https://github.com/user-attachments/assets/1e2cd135-8a23-49b1-b72f-5210ddbccb4a)

2024-08-24 22:26 UTC, manikittu810 submitted a review, later dismissed
Hello @Nahiyan-16 
The changes are working as mentioned 
<img width="947" alt="Screenshot 2024-08-24 at 3 25 56 PM" src="https://github.com/user-attachments/assets/5dc3c9dc-bf18-448b-9797-37d7d361814b">
Thank you.

2024-08-25 03:00 UTC, oliviahyw requested changes
Hi @Nahiyan-16 I have tested this PR. The date selector is not working as expected. Please check the screenshot attached.
![PR2614](https://github.com/user-attachments/assets/a17a4dfa-61e0-4c76-be8b-658e693194f5)

2024-08-26 21:39 UTC, vishnupriyaatheti approved these changes
@Nahiyan-16 I have reviewed your PR as per the given 5 points  in redlines. All changes are working fine and below are my observations:
1) Badges, weekly summary.....etc seems to be in same width at given px.
ii) Weekly summary checkbox is getting displayed at given 544px
iii) days icon: Displaying as expected.
iv) Tracking button check: till 768px it shows at fixed position right, Above 768px it is floats to the middle.
v) from 345px it the title "View time .." going to second line. At 375px it looks as expected.
iv) Search button is working as expected.
![FE PR 2614(i) above 991px check](https://github.com/user-attachments/assets/b1f146c7-ffdd-4fda-9494-eeb996ee5e00)
![FE PR 2614(i) check](https://github.com/user-attachments/assets/7a6ae626-419a-4cf3-8aa2-b4b7ec08782d)
![FE PR 2614(ii) weekly checkbox check below 544px](https://github.com/user-attachments/assets/0f42ee00-a7d1-453f-ad36-71058432896d)
![FE PR 2614(iii) below 480px check](https://github.com/user-attachments/assets/fb4264b3-9a31-4371-89e5-2db86d49bb1f)
![FE PR 2614(iv) above 544px at 768px](https://github.com/user-attachments/assets/8f987433-ae1b-4c31-b2b2-8ec5058c3eb9)
![FE PR 2614(iv) above 544px tracking button check](https://github.com/user-attachments/assets/cd78e4ac-2482-46d1-9b51-fe1fa49ceb8a)
![FE PR 2614(iv) below 544px tracking button check](https://github.com/user-attachments/assets/3f369fba-0234-4582-805e-1385897ac985)
![FE PR 2614(v) at 345px search button check](https://github.com/user-attachments/assets/33c300bf-0404-4f74-b955-c6e8385aaa16)
![FE PR 2614(v) at 375px search button check](https://github.com/user-attachments/assets/f6ac8aa6-2210-4ab7-b5c6-99acd525aa3c)

2024-08-27 20:49 UTC, FayeLV commented
Hello @Nahiyan-16
The changes are working as shown in the screenshots.

![Snipaste_2024-08-27_15-34-34](https://github.com/user-attachments/assets/8af17bed-a139-4b7d-b24c-e64522faad6e)
![Snipaste_2024-08-27_15-35-50](https://github.com/user-attachments/assets/93a47b5f-54e6-41d1-ab4e-3722f89ff87e)
![Snipaste_2024-08-27_15-36-58](https://github.com/user-attachments/assets/b4d6fa0a-ff4f-4089-a397-a009a2c335fb)

2024-08-27 21:29 UTC, preethamdnr approved these changes
Hello Nahiyan,
This PR is working as expected in both the modes with varying dimensions.
<img width="221" alt="image" src="https://github.com/user-attachments/assets/a53bd7e1-29d1-4d80-891e-59bb74a63346">
![image](https://github.com/user-attachments/assets/71ff5570-e1c1-4272-8e80-4d1932891367)

2024-08-27 23:32 UTC, FayeLV approved these changes

2024-08-29 02:19 UTC, yashwanth170 approved these changes
Hey @Nahiyan-16
The PR is Working as expected. I have tested responsiveness for various dimensions and its working as expected. 
![Days](https://github.com/user-attachments/assets/bc1d23b4-5a6b-40ac-94a5-40dcbb640065)

2024-08-29 03:55 UTC, JatinAgrawal94 submitted a review, later dismissed
Changes work as expected. Good work.
<img width="1506" alt="Screenshot 2024-08-28 at 8 54 05 PM" src="https://github.com/user-attachments/assets/fecdd046-ec23-433f-8296-4ae8835e45ea">
<img width="1501" alt="Screenshot 2024-08-28 at 8 54 49 PM" src="https://github.com/user-attachments/assets/4448e9de-0e44-47be-8192-1dd1a52dafa3">

2024-08-30 01:42 UTC, crystallow1168 commented on src/components/TeamMemberTasks/TeamMemberTasks.jsx
> +                  {days} {days === "1" ? "day" : "days"}
What do you think about DRYing up this code block? We seem to use this line more than once (line 601 and 630).

2024-08-30 03:24 UTC, crystallow1168 commented
Hello @Nahiyan-16,
I have reviewed your PR, I noticed a couple of things:

- ❗️ Dashboard components are not aligned when screen is 991px and below


https://github.com/user-attachments/assets/0823111f-ff9e-4238-8b3a-bd82f0d612d3



- ✅ Dropdown for days sector is displayed when screen is below 768px. 
  - ❗️The dropdown day selector seems to float in the middle. 
![image](https://github.com/user-attachments/assets/586cf5ca-7b47-4657-968b-32f331754157)


- ✅ Tracking/Hide button is aligned to the right.

https://github.com/user-attachments/assets/1245fc88-8519-4b34-a033-d7853ff9cc7b

2024-08-30 03:25 UTC, crystallow1168 requested changes
Hello @Nahiyan-16,
I have reviewed your PR, I noticed a couple of things:

- ❗️ Dashboard components are not aligned when screen is 991px and below


https://github.com/user-attachments/assets/0823111f-ff9e-4238-8b3a-bd82f0d612d3



- ✅ Dropdown for days sector is displayed when screen is below 768px. 
  - ❗️The dropdown day selector seems to float in the middle. 
![image](https://github.com/user-attachments/assets/586cf5ca-7b47-4657-968b-32f331754157)


- ✅ Tracking/Hide button is aligned to the right.

https://github.com/user-attachments/assets/1245fc88-8519-4b34-a033-d7853ff9cc7b

2024-08-30 18:00 UTC, gowthamdongari approved these changes
Hello,
I have reviewed this PR and working as expected.
![image](https://github.com/user-attachments/assets/06076545-140e-4712-9b53-dac1b1ab98c8)

2024-08-30 20:39 UTC, vishavk1992 submitted a review, later dismissed
I have tested this PR and it works as expected for mobile view.

![Screenshot 2024-08-30 162937](https://github.com/user-attachments/assets/13295f2d-cd63-4323-a9ea-3e6fb873651b)

2024-09-04 03:12 UTC, vedantg24 approved these changes
Tested the PR, and the changes are working as expected. At 375px, the title "Viewing time entries from..” looks as expected, but below that, it goes to the second line
![Screenshot 2024-09-03](https://github.com/user-attachments/assets/20480a63-7407-4e57-a9ad-f0faaa5399ca)
![Screenshot 2024-09-03](https://github.com/user-attachments/assets/517c843c-adc6-4383-91b7-c61c981ea724)
![Screenshot 2024-09-03](https://github.com/user-attachments/assets/7b7382e4-70fe-4443-a841-472c8ac5ed07)
![Screenshot 2024-09-03](https://github.com/user-attachments/assets/ea1b3716-0ef3-479a-9a1c-e59a3796a5f6)
![Screenshot 2024-09-03](https://github.com/user-attachments/assets/20116414-b067-44d3-9ff3-79c5219146e6)

2024-09-06 19:59 UTC, AJAYINAVOLU approved these changes
Changes are working as expected.

<img width="511" alt="image" src="https://github.com/user-attachments/assets/e532e097-1f4c-4d32-961a-f75a051509d3">

Thank you

2024-09-07 00:32 UTC, Sudershhh reviewed
The functionalities work as expected however thre might be one minor pixel issue with the days alignment. the days dropdown only seem to work below 767px. Let me know if you can recreate this.

2024-09-07 17:47 UTC, merged