Peterson implement improvements in team code input
OneCommunityGlobal/HighestGoodNetworkApp pull request #2621
Opened 2024-08-26 18:21 UTC by peterson337

# Description
This pull request has been opened to implement the auto-save feature in the team code input.

## Related PRS (if any):
None

## Main changes explained:
Three components (AutoCompleteTeamCode.jsx, UserTeamsTable.jsx and UserProfile.jsx) have been modified to implement the auto-save.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Log in as an administrator or owner.
5. go to view profile→ Teams
6. After the team code has 5, 6, or 7 characters, the team will be automatically saved. If a new code is entered, it will be saved, and the autocomplete will be updated

## Screenshots or videos of changes:
![Peterson_implement_improvements_in_team_code_input](https://github.com/user-attachments/assets/4cb359d4-355a-42cb-b752-d399c3ebb4d5)

## Note:
None.

2024-08-27 01:27 UTC, Vigneshwar-Muriki approved these changes
Tested this PR and its working as expected. Got a toast notification after updating the team code.

https://github.com/user-attachments/assets/7699e9af-a4e0-4c1d-8f56-5c2a75642475

2024-08-27 19:30 UTC, manikittu810 approved these changes
Hello @peterson337 
Everything is working as mentioned.
<img width="1470" alt="Screenshot 2024-08-27 at 12 27 57 PM" src="https://github.com/user-attachments/assets/b3b7bf99-ee76-453d-b07e-99d3182ccce3">
<img width="1470" alt="Screenshot 2024-08-27 at 12 28 15 PM" src="https://github.com/user-attachments/assets/ca5da24d-2f03-4c83-b26d-f3cad2c50e9d">

Thank you.

2024-08-29 02:46 UTC, JatinAgrawal94 submitted a review, later dismissed
Changes work as expected. Good work.

https://github.com/user-attachments/assets/4453794c-1da7-4e8f-acef-47e7cdf8047d

2024-08-30 00:14 UTC, Jingyii800 submitted a review, later dismissed
I have tested this function and it worked as expected. 

https://github.com/user-attachments/assets/3856d408-535b-418b-a429-fb3882e8836f

2024-08-30 20:13 UTC, Pranay-ai requested changes
Hey @peterson337 
I have reviewed the PR But i have couple of Issues
The Team code is not being checked if it's a valid Code 
Too many Toast Notifications  For Each Char Added and Deleted


https://github.com/user-attachments/assets/8cc50fb4-0b89-4a77-b00e-1e9330460094

2024-08-31 04:30 UTC, jinxyou submitted a review, later dismissed
![Screenshot 2024-08-30 212909](https://github.com/user-attachments/assets/b48eda95-1f6b-4c3a-8e93-54b97e27e592)
The function works fine. Great work!

2024-09-01 03:24 UTC, CillianRen submitted a review, later dismissed
https://github.com/user-attachments/assets/507b08fa-96e2-460a-b5a7-2020a29f3581

it works perfectly for me.

2024-09-05 21:47 UTC, sri0606 requested changes
Hey @peterson337 , I have reviewed the changes you made and found some issues:

* When I enter a character and choose an option from dropdown, I get the correct toaster message. But when I clear the team code to enter another, I get another toaster message saying "Team code updated"
* If I enter a invalid team code with enough characters, I get "Team code updated".
* It crashes/lags sometimes as you can see in video below. I had to refresh.


https://github.com/user-attachments/assets/3b56cc84-b9b6-4055-9e77-b7b80426b82c

2024-09-26 17:54 UTC, sri0606 requested changes
Hey @peterson337 , I have reviewed the changes you made. Although the team code doesn't update when I clear the input, there are still some issues:

* Invalid team codes are still being updated.
* And it crashes a lot whenever I get a dropdown with loading sign in it. Sometimes, refreshing doesn't work either. It directly opens the same dropdown. And once its loaded, nothing is clickable.

Please refer to video below:

https://github.com/user-attachments/assets/31e67389-3b17-46c9-85b0-d3520342d521

2025-01-29 03:40 UTC, one-community commented
Thank you all, merging!

2025-01-29 03:40 UTC, merged