Adding a spinner to the leader board component to indicate loading/reloading.
OneCommunityGlobal/HighestGoodNetworkApp pull request #2624
Opened 2024-08-27 19:03 UTC by Shadhrush5

# Description
<img width="819" alt="Screenshot 2024-08-27 at 11 45 07 AM" src="https://github.com/user-attachments/assets/8ee9d87a-6f84-4a19-b5c9-ea914576fe82">
<img width="733" alt="Screenshot 2024-08-27 at 11 48 08 AM" src="https://github.com/user-attachments/assets/a1ee7f6c-fa3f-40a0-b52e-c88c22f4c8b3">

## Related PRS (if any):
This frontend PR is related to the development backend.
…

## Main changes explained:
I have added a spinner to be visible whenever the data displayed on the leaderboard is loading or reloading. 

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Leaderboard→ Click Dot By Name of team member
6. When viewing another user’s dashboard, you should see the leaderboard with a loading symbol as it takes too long to load the data.
7.  Click on the 'x' at the end of the the yellow bar above to exit the dashboard, you should see the leaderboard with a loading symbol as it takes too long to load the data.

## Screenshots or videos of changes:
Before
https://github.com/user-attachments/assets/10193b0c-2df9-4f4d-9fa6-a11ae9371b1d

After
https://github.com/user-attachments/assets/ce8f574a-bae3-4b66-852d-0f90948ed6ed

## Note:

2024-08-27 19:21 UTC, manikittu810 approved these changes
Hello @Shadhrush5 
Everything is working as mentioned.


https://github.com/user-attachments/assets/ce50e1f4-8d45-440f-a10e-af323b878b00

Thank you.

2024-08-27 21:34 UTC, vishnupriyaatheti requested changes
@Shadhrush5 
I have reviewed your changes, in considering three scenarios
1) While loading of the page or page refresh
	expected : spinner should be seen for loading leaderboard dashboard
	actual: spinner is coming
2) While navigating to other dashboard's view: 
	Here are my observations:
		There seems a lag, when I click on ok button the dialog box still 
presents without closing, Also the 'Team Member Tasks' on the left side behaves wierdly, 
First it displays nothing, later it showed up some members data and then it showed the member 
data of whom which I clicked to view the dashboard. Here also spinner is coming before loading of data.
3) After exiting from member dashboard's view:
  Here the spinner is coming before loading of Leaderboard component. But again the team member tasks on the left side is still
showing up the exited member task details. The data is not refreshing even after coming from other
members dashboard view.

On a whole the showing up of spinner while loading the data is working as expected
as per the story but above the my observations as per testing, please check and let
me know.

https://github.com/user-attachments/assets/af559941-ae41-4a6a-912f-683a45a74775

2024-08-27 21:58 UTC, Shadhrush5 commented
> @Shadhrush5 I have reviewed your changes, in considering three scenarios
> 
> 1. While loading of the page or page refresh
>    expected : spinner should be seen for loading leaderboard dashboard
>    actual: spinner is coming
> 2. While navigating to other dashboard's view:
>    Here are my observations:
>    There seems a lag, when I click on ok button the dialog box still
>    presents without closing, Also the 'Team Member Tasks' on the left side behaves wierdly,
>    First it displays nothing, later it showed up some members data and then it showed the member
>    data of whom which I clicked to view the dashboard. Here also spinner is coming before loading of data.
> 3. After exiting from member dashboard's view:
>    Here the spinner is coming before loading of Leaderboard component. But again the team member tasks on the left side is still
>    showing up the exited member task details. The data is not refreshing even after coming from other
>    members dashboard view.
> 
> On a whole the showing up of spinner while loading the data is working as expected as per the story but above the my observations as per testing, please check and let me know.
> 
>  FE.PR.2624.1.mp4

Hi @vishnupriyaatheti, Thank you for reviewing. The issues you mentioned do exist, but are out of the scope of this PR. Please do check the Bug doc to see if these are reported. If not, please report the same. Thank you once again.

2024-08-27 22:35 UTC, RishithaMamidala submitted a review, later dismissed
@Shadhrush5 
The spinner component works as described.


https://github.com/user-attachments/assets/32ee05d5-50e7-48c5-a09d-22d037e16c21

2024-08-27 22:45 UTC, SnelPatare submitted a review, later dismissed
Changes are working fine. Please find image below

![image](https://github.com/user-attachments/assets/62fd711b-4ee9-4656-8439-0980953b0877)

2024-08-28 20:43 UTC, vishavk1992 submitted a review, later dismissed
i have tested this PR and spinner working on leaderboard component to indicate loading and reloading. 



https://github.com/user-attachments/assets/995213b1-a898-4658-b88c-dbeeb7db05d7

2024-08-28 21:02 UTC, Jingyii800 submitted a review, later dismissed
I have tested this function. Logging in as an admin account, when clicking on the button before member's name, the page is reloading with a spinner. Great job!
![image](https://github.com/user-attachments/assets/2c9974f2-a53f-4215-9ccb-fb0719714793)

2024-08-29 01:05 UTC, crystallow1168 commented
https://github.com/user-attachments/assets/532b3a58-0b4b-4977-b8d5-c09370b0bed8

Hi @Shadhrush5,
I have tested the PR changes on the Admin user dashboard and while viewing another team member's dashboard. In both cases, the loading spinner is displayed correctly while waiting for the list of members to be fetched and when clicking on the reload button. Great job!

2024-08-29 01:09 UTC, crystallow1168 approved these changes

2024-08-29 01:49 UTC, yashwanth170 submitted a review, later dismissed
As @vishnupriyaatheti mentioned, there seems to be a lag, but I believe that isn't covered under this PR.  Other than that everything is working as expected. 
![Screenshot (3)](https://github.com/user-attachments/assets/5f62bb43-b42f-46c3-accf-a5df61f71001)

2024-08-29 02:17 UTC, JatinAgrawal94 submitted a review, later dismissed
Changes work as expected.
<img width="1506" alt="Screenshot 2024-08-28 at 7 16 19 PM" src="https://github.com/user-attachments/assets/f21d6d10-28b7-4bf8-afa3-2bff1f759b78">

2024-08-29 12:07 UTC, beblicarl commented
this functionality works as intended

[screencast-localhost_3000-2024.08.29-12_05_50.webm](https://github.com/user-attachments/assets/2332e314-f52b-4857-96dd-8c1a8fee89ba)

2024-08-29 12:08 UTC, beblicarl submitted a review, later dismissed

2024-08-29 19:06 UTC, vishnupriyaatheti approved these changes
If reported bugs are of out of scope, then the changes are looking are good. Thankyou

2024-08-29 19:07 UTC, vishnupriyaatheti approved these changes

2024-08-29 19:30 UTC, ddshah878 submitted a review, later dismissed
I’ve tested the changes, and the spinner is functioning properly.


https://github.com/user-attachments/assets/52e49175-4b9f-4a21-a7b5-10d0a03654cd

2024-08-30 00:59 UTC, Parth-tech submitted a review, later dismissed
Hey Shadrush,
The Spinner component works well, on page refresh, leaderboard reload and also while viewing other user's dashboard. Great job.


`Image Reference:`
<img width="1440" alt="Screenshot 2024-08-29 at 5 53 35 PM" src="https://github.com/user-attachments/assets/9f7d6067-3009-4901-bd53-954de3faf661">
<img width="1440" alt="Screenshot 2024-08-29 at 5 57 28 PM" src="https://github.com/user-attachments/assets/8151bec6-dd7e-4f45-89df-177ebdbd0b61">

2024-08-30 00:59 UTC, oliviahyw approved these changes
I have tested this PR an it's working as expected.
<img width="1344" alt="Screenshot 2024-08-29 at 7 57 15 PM" src="https://github.com/user-attachments/assets/eb71b137-3d5f-49b9-b682-539ed2b8c20c">

2024-08-30 01:14 UTC, FayeLV commented
Hi,

The Spinner component is functioning perfectly. It works smoothly on page refresh, leaderboard reloads, and when viewing other users' dashboards. Great job!
![Snipaste_2024-08-28_23-23-54](https://github.com/user-attachments/assets/1496c6b3-4e61-4127-a259-e40274d00d31)
![Snipaste_2024-08-29_19-37-12](https://github.com/user-attachments/assets/873bd88a-a8ff-46d2-a3ed-4258298e9b75)
![Snipaste_2024-08-29_19-56-49](https://github.com/user-attachments/assets/caed1c5c-5c67-4806-a04b-21915d8f7012)

2024-08-30 01:14 UTC, FayeLV approved these changes

2024-08-30 06:43 UTC, vedantg24 submitted a review, later dismissed
The spinner works perfectly fine when viewing another user’s dashboard, when exiting their dashboard, when refreshing the leaderboard, and also when the page reloads.

https://github.com/user-attachments/assets/92279258-c606-430e-b9de-18a023ca9e1a

2024-08-30 15:29 UTC, preethamdnr approved these changes
Hello Shadhrush,

I have checked the PR, and it is working as expected.
<img width="890" alt="image" src="https://github.com/user-attachments/assets/0bad0dcd-cbd2-416e-a2ba-9a2e26fce923">

2024-08-30 17:07 UTC, gowthamdongari approved these changes
Hello Shadhrush,
I have checked this PR and it is working as expected.

https://github.com/user-attachments/assets/0844f631-b877-487d-b905-012ddbbe5d22

2024-08-30 19:23 UTC, Pranay-ai submitted a review, later dismissed
Hey @Shadhrush5 
The PR is working as expected, please find the screenshots for reference
![image](https://github.com/user-attachments/assets/2a9278eb-3d6c-455c-8568-dc15dbab2b69)

2024-08-31 21:51 UTC, KurtisIvey requested changes
Love it! Well done on the visual aspect. However, there is inline styling that you integrated into this rather than just using bootstrap or creating a dedicated style sheet. 

git rid of the inline styling in lines:
347, 381, 382, 383, 454,455, 456, 457, 478, 479 (assignStarDotColors can stay), 483, 484, 485, 486, 495, 496,  497, 498, 499, 559, 576. There could be more, but there's 500+ lines of code in this, so I wouldn't be surprised if I missed something

Any conditional styling based on other variables can stay. There were quite a bit, so I may have missed some. Once these are corrected I'll look over it again to confirm the inline styling is gone.

2024-09-03 03:18 UTC, Shreyav2000 approved these changes
The spinner works as intended.

2024-09-03 03:28 UTC, Shreyav2000 approved these changes
The spinner works as intended after loading someone's leaderboard and whilst trying to reload the whole leaderboard on the admin dashboard as an owner. 

Uploading 361939241-ce8f574a-bae3-4b66-852d-0f90948ed6ed.mov…

2024-09-06 19:21 UTC, AJAYINAVOLU approved these changes
Changes are working as expected.

<img width="947" alt="image" src="https://github.com/user-attachments/assets/48f6b60c-6030-4880-b70b-17981e721163">

Thank You

2024-09-07 03:40 UTC, mohangadde1 submitted a review, later dismissed
![image](https://github.com/user-attachments/assets/a7ea1840-9cef-4a71-9ff0-fea78303116b)
spinner is working as expected while loading.

2024-09-08 05:44 UTC, Gauravmg6 approved these changes
It is working as expected.
![Screenshot 2024-09-08 014401](https://github.com/user-attachments/assets/e0abec4e-64d6-4fef-9c42-73a441a7f4ef)

2024-09-14 17:15 UTC, KurtisIvey commented
Hi Shadhrush, would love to get this rereviewed once the inline styling issues are addressed. I'll keep monitoring this in the meanwhile.

2024-09-15 23:54 UTC, Shadhrush5 commented
> Hi Shadhrush, would love to get this rereviewed once the inline styling issues are addressed. I'll keep monitoring this in the meanwhile.

Hi @KurtisIvey, thank you for your comments. I did not add all those inline styling as a part of this commit and only the spinner styling which was inline has been changed since I added that. Thank you.

2024-09-19 00:47 UTC, Abhinav-Ankur786 approved these changes
This is working fine as it spins when page is refreshed as well when searching for different team
<img width="1512" alt="PR - #2624" src="https://github.com/user-attachments/assets/c3b5540b-5625-4182-a563-7a29eb8fd0cd">

2024-09-20 21:53 UTC, KurtisIvey commented
> Hi @KurtisIvey, thank you for your comments. I did not add all those inline styling as a part of this commit and only the spinner styling which was inline has been changed since I added that. Thank you.

It did seem like you modified every one of those according to your commit history under your "G" commit. I would suggest not modifying the code block the same way next time, so we can track changes. Please be sure to follow the commit guidelines next time as well as "G" isn't very descriptive 

Seems like we'll just be moving forward past the inline styles. Once the new merge conflict is cleared up, I'll go ahead and rereview.

2024-09-27 03:40 UTC, nishitag5 submitted a review, later dismissed
Everything is working as expected. I have attached the recording below.

https://github.com/user-attachments/assets/d42c71b4-0c71-465b-afe4-0ce69585e7a8

2024-10-11 22:56 UTC, geetamatkar commented
Hi @Shadhrush5 ,
Tested this PR and it is working as expected. 

<img width="1255" alt="PR2624-1" src="https://github.com/user-attachments/assets/4edcb3b4-071e-438a-9727-437a329c969b">
<img width="1262" alt="PR2624-2" src="https://github.com/user-attachments/assets/104affe5-698b-4e8e-a5a5-3db240a3dbcb">
<img width="1409" alt="PR2624-3" src="https://github.com/user-attachments/assets/1b9c771d-2d56-4a93-8153-aaf1fe447b52">
<img width="1244" alt="PR2624-4" src="https://github.com/user-attachments/assets/5d6fae43-400c-442c-b179-47f6c91781d0">

2025-03-14 05:28 UTC, closed without merging