Peterson implement improvements in the my team filter
OneCommunityGlobal/HighestGoodNetworkApp pull request #2638
Opened 2024-09-02 17:07 UTC by peterson337

# Description
This pull request has been opened to improve the filter of the team in the dashboard section and Leaderboard table.

## Related PRS (if any):
None

## Main changes explained:
The Leaderboard component have been modified to improve the filter of the team in the dashboard section and Leaderboard table.

## How to test:
1. check into current branch
2. do npm install, git pull and ... to run this PR locally
3. Clear site data/cache
4. Log in as an administrator or owner.
5. go to dashboard
6. Check if the tables 'Leaderboard' and 'Team Member Tasks' are filtered simultaneously; the filter features should be easy to use. Check if the member numbers are displayed correctly in the header of the 'Leaderboard' table after the table is filtered.

## Screenshots or videos of changes:
![Peterson_implement_improvements_in_the_My_Team_filter](https://github.com/user-attachments/assets/ac4f947c-b666-468b-a1f0-8dcb46b9b67e)

## Note:
None

2024-09-06 04:36 UTC, Jingyii800 requested changes
Hi, I have tested this feature. Although the leaderboard and tasks can both display the filtered team at the same time, the leaderboard will jump back to original view in one second. Please see more details in my video.

https://github.com/user-attachments/assets/527ddb34-8cd2-497d-acbc-faf7e89d1f11

2024-09-06 18:40 UTC, AJAYINAVOLU requested changes
Changes are working as expected. But the leaderboard is changing back to show all after a couple of seconds.

<img width="942" alt="PR 2638" src="https://github.com/user-attachments/assets/26f51d4a-82f7-490e-b7cf-5b03cc2be150">
<img width="945" alt="PR 2638-1" src="https://github.com/user-attachments/assets/8b7c7876-e908-4dfd-addb-798e86ac8760">

Thank You

2024-09-12 16:53 UTC, peterson337 commented
> Changes are working as expected. But the leaderboard is changing back to show all after a couple of seconds.
> 
> <img alt="PR 2638" width="942" src="https://private-user-images.githubusercontent.com/120858167/365273011-26f51d4a-82f7-490e-b7cf-5b03cc2be150.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTk5NzcsIm5iZiI6MTcyNjE1OTY3NywicGF0aCI6Ii8xMjA4NTgxNjcvMzY1MjczMDExLTI2ZjUxZDRhLTgyZjctNDkwZS1iN2NmLTViMDNjYzJiZTE1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxNjQ3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWVlMTc2MmI2MmFlMjU5ZDU0ZjZmN2ZmMTE5NzhiZDc3N2UzOTBiMzdkYTJiNjA5OTMwNTYzM2IyNDc2NDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KdpWHDG08oHhwaWG1PwtpOpHuBDGiWVb7cjFdOZFASw"> <img alt="PR 2638-1" width="945" src="https://private-user-images.githubusercontent.com/120858167/365273015-8b7c7876-e908-4dfd-addb-798e86ac8760.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTk5NzcsIm5iZiI6MTcyNjE1OTY3NywicGF0aCI6Ii8xMjA4NTgxNjcvMzY1MjczMDE1LThiN2M3ODc2LWU5MDgtNGRmZC1hZGRiLTc5OGU4NmFjODc2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxNjQ3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Mjk2NWRiZTI3ZGZlOTAzN2QxMTM5N2IyMWQ2NzYxNGYyNmIzNmRmNmMyMmIzMDExMTI2MTI0MDFjYTU3YmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-6f-K15nx7w_U27PepDiS3IgzQ5vLwfzyW5LzLf8_dc">
> Thank You


Hello [@AJAYINAVOLU](https://github.com/AJAYINAVOLU), I hope this message finds you well. I saw your review on my PR and I made changes in my code. I would greatly appreciate it if you could take another look at my pull request when you have a moment. Don't forget to use git pull in your terminal.

2024-09-12 22:25 UTC, peterson337 commented
> Hi, I have tested this feature. Although the leaderboard and tasks can both display the filtered team at the same time, the leaderboard will jump back to original view in one second. Please see more details in my video.
> 
>  bandicam.2024-09-05.21-31-12-538.mp4

Hello [Jingyii800](https://github.com/Jingyii800), I hope this message finds you well. I saw your review on my PR and I made changes in my code. I would greatly appreciate it if you could take another look at my pull request when you have a moment. Don't forget to use git pull in your terminal.

2024-09-18 20:02 UTC, AJAYINAVOLU approved these changes
Changes are working as expected.

<img width="954" alt="image" src="https://github.com/user-attachments/assets/daa8f825-ea0f-441c-a02d-e22872cac0e8">

Thank You

2024-09-18 21:30 UTC, Jingyii800 approved these changes
Hi I have reviewed this feature again. Now it works well, while filtering the team on Leaderboard, the task tabs also changes correspondingly. Great job!

Uploading 9月18日.mp4…

2025-06-07 16:24 UTC, dipti95 commented
Hi @honglinchen0524 I’ve debugged the PR and found that its changes are already present in the development branch. There was another PR ([PR #2858](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2858)) with the same developer and title that has already been merged. Therefore, we can go ahead and close PR #2638.
<img width="949" alt="Screenshot 2025-06-07 at 12 20 36 PM" src="https://github.com/user-attachments/assets/4e8c2495-f489-4382-9da7-6b32691b250b" />

2025-07-14 21:15 UTC, closed without merging