Vijay Anand - Hotfix for assign badge button and search field bug on entering space
OneCommunityGlobal/HighestGoodNetworkApp pull request #2639
Opened 2024-09-02 17:35 UTC by vijay10pk

# Description
 
![Screenshot 2024-09-02 at 1 27 25 PM](https://github.com/user-attachments/assets/eca11c52-57f6-4152-86c6-4d57cf5676b0)

**Issues**
Assign badge Button:
![Screenshot 2024-09-02 at 1 26 51 PM](https://github.com/user-attachments/assets/ebcef734-1ace-4711-890f-ffe51f0d2a71)

Search Field:
![Screenshot 2024-09-02 at 1 27 31 PM](https://github.com/user-attachments/assets/a8390b15-839a-4c72-bf29-f47c4cd8de41)

## Related PRS (if any):
To test this frontend PR you need to check out the development branch for the backend.
…

## Main changes explained:
- Refactored the code to remove any unnecessary space in the beginning and trailing of the search input.
- Refactored the code so that the "Assign Badge" button will be enabled only when a user is selected.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Other Links→ Badge Management → Badge Assignment(Tab)
6. verify if the user can see the search result even if you enter space at the beginning or trailing of the name when entered in search field.
7. verify if the "Assign Badge" button is enabled only when a user name is selected from the search result.

## Screenshots or videos of changes:
https://www.loom.com/share/d21ba9e1c97c419ab512b8b5b8f2468f?sid=a000250c-97c0-4c5c-8f4f-f3e24658c242

## Note:
This changes are related only to badge assignment component

2024-09-03 13:51 UTC, agryash commented
This PR works as expected.

From what I noticed these are the two changes you made:
1. Trimming fullName to use trimmedName
2. Disabling the button if no selectedUserId is present

My suggestion would be to include error handling for the fullName field. If the fullName field gets passed something else other than a string, it might error out.

2024-09-03 13:51 UTC, agryash commented on src/components/Badge/AssignBadge.jsx
> +    const trimmedName = fullName.trim(); // Trim any leading/trailing spaces
Add error handling for fullName

2024-09-04 05:30 UTC, manikittu810 submitted a review, later dismissed
Hello @vijay10pk 
Followed steps in the description. Everything is working as mentioned.
<img width="1470" alt="Screenshot 2024-09-03 at 10 26 52 PM" src="https://github.com/user-attachments/assets/2117098e-09b7-4a6f-9442-aea56a85806a">

Thank you.

2024-09-04 22:12 UTC, Vigneshwar-Muriki submitted a review, later dismissed
Tested this PR and its working as expected.


https://github.com/user-attachments/assets/afc1ce8f-8d22-4a1e-84d4-58408f176110

2024-09-05 05:03 UTC, RishithaMamidala requested changes
@vijay10pk 
The "Assign Badge" button is initially disabled, but when you search for a name and then clear the input, the button remains enabled even with no name present.
Chcek below video for walkthrough.

https://github.com/user-attachments/assets/f5cdd068-7901-47df-b713-61b5899f1154

2024-09-05 14:33 UTC, beblicarl requested changes
The search field works perfectly. However, the assign badge appears even when there is nothing in the search field

![image](https://github.com/user-attachments/assets/2e6cd21b-9484-443f-aae2-11450e5e512e)

![image](https://github.com/user-attachments/assets/fa12d0d1-e46b-4a6f-b7f8-67f56af2284d)

2024-09-06 00:22 UTC, CillianRen submitted a review, later dismissed
![image](https://github.com/user-attachments/assets/0924093d-6b2a-4919-9de7-e46632d77e0e)
Worked as expected. Good job.

2024-09-06 02:29 UTC, one-community commented
Thank you all, merging!

2024-09-06 02:29 UTC, merged

2024-09-06 02:34 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/d59c2d4d-90c5-4e53-b3ad-cab56939683d