ambika fix tasks contributed section of people reports page
OneCommunityGlobal/HighestGoodNetworkApp pull request #2651
Opened 2024-09-07 05:10 UTC by kabraambika

# Description
![image](https://github.com/user-attachments/assets/084de909-8b72-44fc-9b6a-271d07d02141)

Here’s [a video about all this](https://www.loom.com/share/981c7dde2feb4219883e83b6b6d3bc9e)
* Overlapping of the column names in the header of the "Tasks contributed" table.
* Overlapping columns "Priority" with "Status".

Fixes # (bug list priority high)

## Related PRS (if any):
- Continued after PR #2005
- To test this frontend PR you need to checkout the development branch of backend PR.

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ task→…
6. verify function “A” (feel free to include screenshot here)
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2024-09-07 18:09 UTC, panchalvatneu approved these changes
Great work, columns do not overlap anymore 
![image](https://github.com/user-attachments/assets/29b9b148-5b9b-4eed-8bc1-3738c71766ca)

2024-09-07 18:17 UTC, AJAYINAVOLU submitted a review, later dismissed
Changes are working as expected.

<img width="959" alt="image" src="https://github.com/user-attachments/assets/0c2644f8-bac6-47df-b607-603e7e935b89">

Thank You

2024-09-07 21:41 UTC, CillianRen approved these changes
![image](https://github.com/user-attachments/assets/27e7c1f4-16b8-4ddd-be53-0da8704a1591)
works great!

2024-09-08 01:21 UTC, sam19981 approved these changes
I tested the fix for the overlapping "Priority" and "Status" columns in the "Tasks Contributed" table header, and it’s working fine now. The columns are no longer overlapping.
<img width="1439" alt="Screenshot 2024-09-07 at 8 16 53 PM" src="https://github.com/user-attachments/assets/c6f4d814-dc91-4b5d-bed3-33a11080eb4a">
<img width="1431" alt="Screenshot 2024-09-07 at 8 16 38 PM" src="https://github.com/user-attachments/assets/271fec34-753f-44d7-8d6e-5bbaaec69fc8">
<img width="1438" alt="Screenshot 2024-09-07 at 8 15 58 PM" src="https://github.com/user-attachments/assets/0b7a5bcf-72f6-47d6-87e7-b8f040e7bf4d">

2024-09-10 16:33 UTC, kabraambika commented
Hello @ddshah878 , Thanks for the feedback, it's fixed now. 
![image](https://github.com/user-attachments/assets/2d5de68e-ee9c-4d6c-a6e5-46bd3099efd2)

2024-09-12 18:36 UTC, ddshah878 approved these changes
Changes are working as expected. Nice job @kabraambika!

![image](https://github.com/user-attachments/assets/ec6490b1-5429-48f6-b102-51a5f66ca5d7)

2024-09-12 23:59 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.
![Screenshot (198)](https://github.com/user-attachments/assets/cb120e58-45e2-492c-8c92-81214828587f)

2024-09-14 02:28 UTC, ArtemisNyx3 approved these changes
There is no overlap in either light or dark mode, and the content displays correctly across various viewport sizes. Everything looks great!

![image](https://github.com/user-attachments/assets/fd3a5917-0208-48f3-b4d5-72ec94fa33d2)
![image](https://github.com/user-attachments/assets/3366ff18-50c4-491e-863b-2d24ddb2e290)
![image](https://github.com/user-attachments/assets/7a8c83a7-3c34-44a8-9e55-6654c0ba92d4)
![image](https://github.com/user-attachments/assets/c02090f1-7782-4c31-a23e-95245bf6c379)

2024-09-14 14:02 UTC, sud306 commented
Hello,
I tested this PR and it's working as expected. The logo looks correct.
![3 PR2651_1](https://github.com/user-attachments/assets/464e0198-a770-4e27-a790-a284aa78193c)
![3 PR2651_2](https://github.com/user-attachments/assets/7f348fe0-79e2-4fb4-9468-8c8c059bea3c)

2024-09-14 18:41 UTC, saurabhshetty29 commented
The content adjusts seamlessly for both light and dark modes without any overlap, and it renders correctly across all screen sizes. Looks solid!
<img width="1267" alt="Screenshot 2024-09-14 at 11 39 09 AM" src="https://github.com/user-attachments/assets/145eace5-bba4-4355-a099-4132b688b0eb">
<img width="902" alt="Screenshot 2024-09-14 at 11 39 28 AM" src="https://github.com/user-attachments/assets/a0eada5c-22e3-4e89-87e9-5c68f1385589">

2024-09-14 19:13 UTC, ashayk9 approved these changes
The content looks good in both light and dark modes without overlapping, and it displays correctly on all screen sizes.
![Screenshot 2024-09-14 at 12 09 28 PM](https://github.com/user-attachments/assets/e639f2e5-459d-42c3-b8a2-57535e4b2d95)
![Screenshot 2024-09-14 at 12 10 15 PM](https://github.com/user-attachments/assets/87ce3fe8-83a3-488f-bc8e-a56ea57f1e4b)

2024-09-14 21:00 UTC, mohangadde1 approved these changes
![image](https://github.com/user-attachments/assets/602239f2-ade2-4225-a8ec-a6b139582d72)
![image](https://github.com/user-attachments/assets/59ba52ea-b5ac-4ae2-8e6b-ad12a16c26c8)
The content is displayed properly across different viewport sizes, with no overlap in either light or dark mode.

2024-09-16 20:10 UTC, strallia requested changes
These changes are working as expected:
- No overlapping of header text and table columns

Issues:
- In dark mode, in mobile view, the table uses the light mode theme. I expect it to have the same dark mode color theme as when viewed at larger browser widths.

https://github.com/user-attachments/assets/6949c4cf-2e6e-43e5-b160-8f0e0662718d

2024-09-16 22:36 UTC, kabraambika commented
Hello @strallia ,
Thank you for reviewing this PR. The issue you've mentioned is beyond the scope of this PR. However, I made temporary adjustments to the view to test its compatibility with the current dark theme, as shown below:
![image](https://github.com/user-attachments/assets/01403fb9-878d-47aa-b3d4-af28bced5a70)

After these changes, I believe the color theme for the dark mode view, as displayed above, won't work well since the cards are blending into the background. Therefore, I suggest keeping it as it is for now. Please feel free to share your thoughts.

2024-09-17 02:45 UTC, swaroop-2007 approved these changes
@kabraambika,
I tested this PR and everything works as expected. There are no overlapping columns in both dark and light modes and it works for mobile view as well. 

![Screenshot (418)](https://github.com/user-attachments/assets/cec4a213-5771-49fb-8bd7-a4e1fb3cef63)
![Screenshot (417)](https://github.com/user-attachments/assets/f40c9972-7240-4f3a-a776-132b5bb650c0)

2024-09-17 03:26 UTC, SFA23SCM35V approved these changes
I tested the PR by checking out the branch `ambika-fix-tasks-contributed-people-reports`, running it locally after installing dependencies, clearing site data, logging in as an admin, and verifying that the task contributed section's table columns were properly aligned across different viewport sizes and functioned correctly in dark mode.
![1](https://github.com/user-attachments/assets/c9a554d8-29ed-40cd-abc9-fbcdda803eea)
![2](https://github.com/user-attachments/assets/f6844ae7-e683-4cc2-8b9e-16cdfccbd0f4)
![3](https://github.com/user-attachments/assets/0282df11-0340-4b36-b29e-0325a7c1eb7a)

2024-09-17 05:06 UTC, strallia approved these changes
@kabraambika I agree the issue is out of the scope of this PR and that the dark color theme does make the individual cards harder to see, so I am approving this PR as it is.

2024-09-18 23:48 UTC, one-community commented
Thank you all, merging!

2024-09-18 23:48 UTC, merged