Adding z-index to button
OneCommunityGlobal/HighestGoodNetworkApp pull request #2681
Opened 2024-09-16 16:36 UTC by kdaga81

# Description
The issue is related to the UI of the "Assign Team" button in the User Profile, where it intermittently responds to clicks.
Fixes # Increased the z-index of the "Assign Team" button to ensure it appears above overlapping elements, resolving an intermittent clickability issue.

## Related PRS (if any):
This frontend PR is related to the Development backend PR.

## Main changes explained:
- Update TeamAndProjects.css to add z-index

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Profile → Teams → Check "Assign Team" button click
6. verify it in different resolutions.
7. verify if this works in [dark mode]

## Screenshots or videos of changes:
Before: 

https://github.com/user-attachments/assets/29ff9358-b827-4e09-a9da-dd3f10503577

After: Button clicking working as expected

2024-09-16 19:35 UTC, strallia approved these changes
Changes are working as expected:
- No flickering of cursor on hover
- Button responds wherever it is clicked
- Works in dark/light mode and at different browser widths

https://github.com/user-attachments/assets/a02a1523-5a50-4e58-a2b2-3ddbb0469ce9

2024-09-17 00:45 UTC, geetamatkar commented
Hi @kdaga81 ,
Tested this PR. Checked 'Assign Team' button in different resolutions and in dark mode. It is working fine.

<img width="1002" alt="PR2681" src="https://github.com/user-attachments/assets/f8adbb86-2e26-4996-9cd0-e37ebd48f103">

2024-09-17 02:13 UTC, swaroop-2007 requested changes
@kdaga81,
I tested this PR, and everything works as expected in both dark and light mode. 
![Screenshot (415)](https://github.com/user-attachments/assets/b904e8b8-4ec1-49db-8d2d-a6a5055f161f)
![Screenshot (414)](https://github.com/user-attachments/assets/41330735-42cc-4421-a1c9-e05e8ad2ff7a)
![Screenshot (416)](https://github.com/user-attachments/assets/1cfe475a-820e-4906-a710-ac4997f9634a)

For smaller resolutions, when I hover on the Assign Team button, I don't get the text 'This team code should only used by admin/owner, and has nothing to do with the team data model'. I am not sure if this lies in the scope of the PR, but can be taken care of for better user experience. Thanks.

2024-09-17 03:28 UTC, RishithaMamidala approved these changes
@kdaga81 
The assign team button works correctly and tool tip works except in the smaller resolutions.
![PR 2681](https://github.com/user-attachments/assets/b211e826-1cde-4e95-abb8-7bfbbc8aeda9)

2024-09-17 20:26 UTC, vishavk1992 approved these changes
I have tested this PR and works as expected.


https://github.com/user-attachments/assets/c5163c1f-c195-4f9d-acac-009703300b8b

2024-09-18 02:38 UTC, vijay10pk approved these changes
The UI changes are working as expected.
<img width="1427" alt="Screenshot 2024-09-17 at 10 37 28 PM" src="https://github.com/user-attachments/assets/18be6bcd-ffa3-4aaf-a063-8d694df212ad">

2024-09-18 05:00 UTC, ashayk9 approved these changes
The changes are working as expected, with no flickering of the cursor on hover. the functionality is consistent across both dark and light modes, and it adapts smoothly to different browser widths.
![Screenshot 2024-09-17 at 9 58 50 PM](https://github.com/user-attachments/assets/3f263458-d0f1-4bf3-a202-2b888d53c01d)
![Screenshot 2024-09-17 at 9 59 06 PM](https://github.com/user-attachments/assets/c20b59c3-231b-47eb-b4a4-9df8ad662d3b)

2024-09-19 00:45 UTC, chu-ziyu approved these changes
I tested this PR and changes worked as expected in both light mode and dark mode:
1. Text shows when hover on the button
2. Good response when button was clicked
![keshav_fix_button_ui_01](https://github.com/user-attachments/assets/6b1f6149-ab9f-4ea1-b484-a0fed45302a8)
![keshav_fix_button_ui_02](https://github.com/user-attachments/assets/1a07e795-57bf-4b1b-b306-8eadb5ca1996)
![keshav_fix_button_ui_03](https://github.com/user-attachments/assets/646ce1ba-d7cb-4cb4-9dcc-70cb2cce415d)
![keshav_fix_button_ui_04](https://github.com/user-attachments/assets/3c6774f5-ca4b-4ea0-b159-81f1ab234ddf)

2024-09-19 00:58 UTC, one-community commented
Thank you all, merging!  

Logging your issue as a new bug Swaroop, thank you

2024-09-19 00:58 UTC, merged