Initial commit to global volunteer map
OneCommunityGlobal/HighestGoodNetworkApp pull request #2706
Opened 2024-09-21 03:45 UTC by Vigneshwar-Muriki

# Description
This React component displays a heat map of user locations using react-leaflet and fetches data via axios, managing state with useReducer. A heat layer is added to the map, and visibility is toggled with notifications using react-toastify.

## Related PRS (if any):
No related PRs. To Test this PR checkout development backend
…

## Main changes explained:
- Created a global volunteer map which displays active volunteers.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Reports→ Total Org Summary -> Click the first accordion which displays active volunteers in the map.
6. verify this new feature works in dark mode(https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2024-09-21 17:43 UTC, panchalvatneu approved these changes
Active volunteer status shows well and the same in both dark and light mode, good work!

![image](https://github.com/user-attachments/assets/e1ec8907-2535-472d-b8f4-674d74a889b3)
![image](https://github.com/user-attachments/assets/2a2a4349-6a0d-4ea2-9309-7eb9a18f3f85)

2024-09-25 05:02 UTC, saurabhshetty29 commented
The active volunteer status is clearly visible and consistent in both dark and light modes.
<img width="1390" alt="Screenshot 2024-09-24 at 10 01 35 PM" src="https://github.com/user-attachments/assets/35b1f9e1-fe3e-4114-a00f-02e564e546d0">

2024-09-25 17:58 UTC, SFA23SCM35V requested changes
Request failed with status code: 404
![PR2706](https://github.com/user-attachments/assets/f7d1c059-f852-4774-9c9a-5e21650fb8ee)

2024-09-25 19:24 UTC, mrinalini-raghavendran19 submitted a review, later dismissed
Looks great! Very cool feature!

Works in both dark and light mode:

<img width="1449" alt="Screenshot 2024-09-25 at 12 16 04 PM" src="https://github.com/user-attachments/assets/b829e73d-c552-4060-ba21-26f2a1af8b91">

<img width="1470" alt="Screenshot 2024-09-25 at 12 16 29 PM" src="https://github.com/user-attachments/assets/fe00ef2f-4d94-4268-a3a3-fc36b8ecea19">

2024-09-25 20:26 UTC, nevatiarishabh approved these changes
Looks good to me. Everything is working as expected. Active volunteers map is displayed in both light and dark mode.

![Screenshot 2024-09-25 at 1 23 46 PM](https://github.com/user-attachments/assets/139e7c7d-fcd7-4434-93af-5b0e230cbc31)
![Screenshot 2024-09-25 at 1 24 13 PM](https://github.com/user-attachments/assets/50d543e6-f4f0-4f4f-82fa-c2f830ebc58f)

2024-09-26 13:55 UTC, ashmita123 submitted a review, later dismissed
Tested PR #2706 and confirmed that the active volunteer map works as expected. The feature displays correctly in both light and dark modes, and the active volunteer status is visible.

<img width="1432" alt="Screenshot 2024-09-26 at 9 53 33 AM" src="https://github.com/user-attachments/assets/01089e19-c319-4a47-bdab-3ecc5ec47568">
<img width="1432" alt="Screenshot 2024-09-26 at 9 53 48 AM" src="https://github.com/user-attachments/assets/c2a2a312-7c6d-41b2-a949-5bbc8959df4c">

2024-09-26 16:54 UTC, beblicarl commented
this feature works correctly in both light and dark modes

![image](https://github.com/user-attachments/assets/7a84794e-eff7-46f9-bdba-d06f2fe5acbc)

2024-09-26 16:55 UTC, beblicarl approved these changes

2024-09-26 22:59 UTC, Dk-21 reviewed
PR 2706
@Vigneshwar-Muriki 
Tested the code changes and Working As Expected.

<img width="1463" alt="PR 2706 (2)" src="https://github.com/user-attachments/assets/f2d48e5b-1bfc-4ba5-831d-3a72f90dfbb7">
<img width="1484" alt="PR 2706(1)" src="https://github.com/user-attachments/assets/2a694548-1b3a-4a79-8ce1-055ffb2cf642">

2024-09-26 22:59 UTC, Dk-21 approved these changes

2024-09-27 01:28 UTC, ziyanw52 submitted a review, later dismissed
This feature works smoothly in both light mode and dark mode.
![1](https://github.com/user-attachments/assets/a60acea4-4c36-425b-a594-16920de04379)
![2](https://github.com/user-attachments/assets/92ae0c5c-9731-4460-bcf6-bbda2016cb7d)

2024-09-27 11:45 UTC, neeharikakoniki reviewed
It shows a request failed error
![image](https://github.com/user-attachments/assets/13489c1a-47c7-4bd3-ac75-d52869aa8cd6)

2024-09-27 21:29 UTC, lcohen730 submitted a review, later dismissed
Active volunteer heat map appears as expected in light and dark modes.


https://github.com/user-attachments/assets/f6c60098-5f71-45fe-8db5-c6398b775411

2024-09-27 23:46 UTC, khushijain03 approved these changes
Hi, @Vigneshwar-Muriki ,
Tested the PR and confirmed that the active volunteer map is working as expected. The feature works in both light and dark modes. 
<img width="1459" alt="Screenshot 2024-09-27 at 7 43 02 PM" src="https://github.com/user-attachments/assets/392d1fe3-227a-438b-a083-717c54780488">


<img width="1437" alt="Screenshot 2024-09-27 at 7 43 41 PM" src="https://github.com/user-attachments/assets/7cdb1728-1c0f-4980-90d3-e522347beb44">

2024-09-29 04:00 UTC, Muzammil603 approved these changes
![image](https://github.com/user-attachments/assets/c2747895-aa53-4919-83c0-c76286419389)
working as expected

2024-10-03 12:09 UTC, Vincent-space reviewed
It failed to run on my machine.

2024-10-04 09:00 UTC, javid679 commented
Hi,
Tested the PR and can confirm that the active volunteer map is working as expected. The feature works in both light and dark modes. Below are the screenshots for your reference. Good Job !

### Light Mode
![Screenshot (18)](https://github.com/user-attachments/assets/1bc0c1eb-0d4a-42cd-af87-52a202e01773)

### Dark Mode
![Screenshot (19)](https://github.com/user-attachments/assets/0faa2fcb-52fe-48ec-8368-39071b480804)

2024-10-04 21:59 UTC, nikhilgiri0226 approved these changes
The active volunteer status was visible and as expected present in the first accodian under volunteer status in both dark and light modes.
<img width="915" alt="Screenshot_2706_Dark" src="https://github.com/user-attachments/assets/97d2317b-655d-4a07-9b3b-1015d6e25c20">
<img width="917" alt="Screenshot_2706_Normal" src="https://github.com/user-attachments/assets/63ccc63e-e6b1-44de-a3d9-42db61b9740e">

2024-10-06 02:16 UTC, khushijain03 approved these changes
Hi, @Vigneshwar-Muriki ,
Tested the PR and confirmed that the active volunteer map is working as expected. The feature works in both light and dark modes. 

<img width="1459" alt="Screenshot 2024-09-27 at 7 43 02 PM" src="https://github.com/user-attachments/assets/392d1fe3-227a-438b-a083-717c54780488">


<img width="1437" alt="Screenshot 2024-09-27 at 7 43 41 PM" src="https://github.com/user-attachments/assets/7cdb1728-1c0f-4980-90d3-e522347beb44">

2024-10-10 23:07 UTC, pallavithorat commented
It looks great to me. Everything is working as expected, and the active volunteers map is properly displayed in both light and dark mode.

<img width="1470" alt="PR#2706" src="https://github.com/user-attachments/assets/5f0e3277-772d-4070-bd62-8e21ed6f5446">
<img width="1470" alt="PR1#2706" src="https://github.com/user-attachments/assets/e01f29be-2c0d-4def-8f6f-757710313551">

2024-10-15 18:25 UTC, AshishNags approved these changes
Approving this PR, Active volunteer status map shows as expected.
![Screenshot 2024-10-15 132236](https://github.com/user-attachments/assets/aa113bdc-d7da-4106-9f73-243014381279)

2024-10-19 21:00 UTC, bhavya17prakash approved these changes
Verified global Volunteer map working as intended in dark mode.
<img width="821" alt="PR 2706" src="https://github.com/user-attachments/assets/f80edb9d-05fe-4069-b7cd-cfd9c812628b">

2024-10-20 01:41 UTC, zhiminV approved these changes
Volunteer Status map works well  in both dark and light mode.
![Screenshot 2024-10-19 at 6 39 53 PM](https://github.com/user-attachments/assets/3b9c7d4b-560e-48c7-afe2-e8c412117fb7)
![Screenshot 2024-10-19 at 6 40 08 PM](https://github.com/user-attachments/assets/4b28251d-21e1-4f70-b548-f017b211a1c9)

2025-01-18 03:47 UTC, honglinchen0524 approved these changes
Great work! The volunteer status display exactly as description .
![image](https://github.com/user-attachments/assets/ccdcdd39-8cbd-4877-bd8a-36b579f08296)
![image](https://github.com/user-attachments/assets/1bc81c58-d428-4d6c-ae3f-4d378ae935c9)

2025-03-28 17:20 UTC, closed without merging