Vedant Fix assign team button hover at smaller resolutions
OneCommunityGlobal/HighestGoodNetworkApp pull request #2708
Opened 2024-09-21 19:55 UTC by vedantg24

# Description
Fixed assign team button hover at smaller resolutions

![Screenshot 2024-09-18 at 8 03 23 PM](https://github.com/user-attachments/assets/254c7547-0bda-435a-9bd0-ad6c864b6d63)

## Related PRS (if any):
This frontend PR is related to the development backend PR.
…

## Main changes explained:
Updated `UserTeamsTable.jsx` and added the tooltip for the assign team button at smaller resolutions
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner/admin user
5. go to dashboard→ View Profile → Teams → Check "Assign Team" button
6. verify that the message "This team code should only used by admin/owner, and has nothing to do with the team data mode" pops up in different resolutions
 
## Screenshots or videos of changes:

https://github.com/user-attachments/assets/82753eec-4b2d-4c5a-937c-29a08a302485

2024-09-21 22:36 UTC, panchalvatneu requested changes
![image](https://github.com/user-attachments/assets/349601ea-b338-4fc5-964f-54ad3280e563)
![image](https://github.com/user-attachments/assets/eb0ea3f1-1272-48f2-a3fc-e7f2f49077db)
![image](https://github.com/user-attachments/assets/05e7bedc-811c-4d23-896e-e292952a7f27)
The message appears, and in different sizes. There is a copy editing error however; it should read: "The team should only **be** used by admin/owner, and has nothing to do with the team data model."

2024-09-25 21:36 UTC, tharunaa-1 commented
when you hover over team the pop up comes as expected.

![image](https://github.com/user-attachments/assets/74b0024c-d5b8-4415-9dd9-ac67bb42ae8f)

2024-09-26 13:44 UTC, ashmita123 reviewed
Tested PR #2708 in both light and dark modes. The "Assign Team" button tooltip appears correctly at smaller resolutions. 


https://github.com/user-attachments/assets/2bae6b9f-d4e3-4be3-8df2-9aad9a0c8074

2024-09-26 16:37 UTC, beblicarl commented
this functionality works as intended and the code is great

![image](https://github.com/user-attachments/assets/5c7d47e4-7cd5-4b00-abcf-09273005b71d)

2024-09-26 16:38 UTC, beblicarl submitted a review, later dismissed

2024-09-26 21:21 UTC, Dk-21 approved these changes
### PR 2708
@vedantg24 
Tested the changes and Its working Expected.

https://github.com/user-attachments/assets/7ffb8ec4-8c2a-485f-88ee-e67f13443e50

2024-09-28 12:52 UTC, Vincent-space approved these changes
Hi, everything works well as mentioned.
<img width="1282" alt="image" src="https://github.com/user-attachments/assets/f957b410-d455-4d0b-b626-1279cd212dee">

2024-09-28 16:59 UTC, aaryaneil approved these changes
Tested the PR and the hover functionality works as expected for different resolutions
<img width="1440" alt="Screenshot 2024-09-28 at 9 56 25 AM" src="https://github.com/user-attachments/assets/3236494d-05ee-486a-9bec-624fd55cd5e0">
<img width="1051" alt="Screenshot 2024-09-28 at 9 58 39 AM" src="https://github.com/user-attachments/assets/a7a48746-c5f2-41ba-8a40-9dc6813b5667">

2024-09-29 01:27 UTC, khushijain03 submitted a review, later dismissed
Hi @vedantg24, 

Tested the PR and the functionality works as expected for different resolutions. 

<img width="845" alt="Screenshot 2024-09-28 at 9 23 26 PM" src="https://github.com/user-attachments/assets/38cfb3b8-a538-46a5-90cb-448df5cebea8">


<img width="581" alt="Screenshot 2024-09-28 at 9 24 06 PM" src="https://github.com/user-attachments/assets/ef237891-32ef-4a5d-a570-7414820a2cd8">

2024-09-29 04:06 UTC, Muzammil603 approved these changes
![image](https://github.com/user-attachments/assets/eb691cfb-4182-47dd-9ec4-6a69b8f512da)
![image](https://github.com/user-attachments/assets/28cc473b-7b05-4e1d-8daf-c448a86f81e5)
working as expected

2024-09-29 18:23 UTC, Gauravmg6 approved these changes
It is working well as expected.
![Screenshot 2024-09-29 142310](https://github.com/user-attachments/assets/0f6486dc-0e60-4e6d-afc6-b2ec67d8539d)

2024-10-01 18:20 UTC, mrinalini-raghavendran19 submitted a review, later dismissed
Looks good to me!

The Ui changes work as expected. Here are screenshots of the App in light and dark mode displaying the working of the feature:

<img width="1470" alt="Screenshot 2024-10-01 at 11 17 38 AM" src="https://github.com/user-attachments/assets/9d5b3503-a50a-447a-92af-a7714a3256dd">

<img width="493" alt="Screenshot 2024-10-01 at 11 18 04 AM" src="https://github.com/user-attachments/assets/de02c48d-5f0d-4eb6-b5ad-15663a74e7fe">

<img width="1470" alt="Screenshot 2024-10-01 at 11 18 31 AM" src="https://github.com/user-attachments/assets/2adc412b-658b-45e7-a388-d9d64e4ba89d">

<img width="503" alt="Screenshot 2024-10-01 at 11 18 46 AM" src="https://github.com/user-attachments/assets/ff90b903-1aea-43c8-bab2-248081b86e7b">

2024-10-04 00:06 UTC, pallavithorat commented
Hi, It is working as expected.
<img width="1470" alt="PR Review #2708" src="https://github.com/user-attachments/assets/9a5521f1-4e00-4525-84d2-b0711ad623b5">

2024-10-04 02:24 UTC, ishangoel17 reviewed
Verified the PR and the changes are working as expected. The team button is visible as expected on hovering. Below are the screenshots for reference:
![Capture2708_1](https://github.com/user-attachments/assets/980fd06e-7117-4582-9045-185e0e43d09e)
![Capture2708_2](https://github.com/user-attachments/assets/23f8a576-beac-48fb-bfe1-dfa837867175)

2024-10-04 08:36 UTC, javid679 commented
Verified the PR and the changes are working as expected. Below are the screenshots for the reference.


![image](https://github.com/user-attachments/assets/77d8d595-2b9d-4555-b61c-3c7d87d9c80a)

2024-10-04 21:31 UTC, nikhilgiri0226 submitted a review, later dismissed
The tooltip was working as expected in both mobile and desktop screen sizes.
![Screenshot_2708_Desktop](https://github.com/user-attachments/assets/2fba3918-3d9c-49f4-8b87-f1bf062885f8)
![Screenshot_2708_Mobile](https://github.com/user-attachments/assets/a77470e0-5d0c-4e98-9997-d6caea86962f)

2024-10-05 00:52 UTC, nikhilpittala16 submitted a review, later dismissed
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/2639e01b-3998-4cbf-9257-469fb92c391a

2024-10-07 17:53 UTC, AshishNags submitted a review, later dismissed
Tested the PR, the message appears correctly when hovered in different resolution.

![Screenshot 2024-10-07 124817](https://github.com/user-attachments/assets/77f25ad2-6557-4115-9519-d5879c86c319)
![Screenshot 2024-10-07 124859](https://github.com/user-attachments/assets/8fd7ff7b-a3b8-49e5-b889-4bd22fe32326)

2024-10-11 20:47 UTC, geetamatkar commented
Tested this PR and it is working as expected.

<img width="810" alt="PR2708" src="https://github.com/user-attachments/assets/f35e54e5-8595-40ac-b0b5-6471de2e0fad">
<img width="948" alt="PR2708-1" src="https://github.com/user-attachments/assets/f67346a9-4ae5-4522-ae71-7f7705135677">

2024-10-18 00:19 UTC, NK3101 approved these changes
Tested the PR, the tooltip is working as expected.

https://github.com/user-attachments/assets/27d4cd12-a163-4336-899a-eabfd97a4ef2

2024-10-18 05:06 UTC, Anoushka21 submitted a review, later dismissed
Tested on smaller resolutions. 

https://github.com/user-attachments/assets/6f9da9be-8ee5-4579-9df6-68da0bc207ea

The pop up looks good!

2024-10-18 05:37 UTC, lng2020 reviewed
I think CI failure is due to there already being a button with `teamCodeAssign` as an ID.

2024-10-19 01:28 UTC, VMD281 commented
Hi, I reviewed this PR and the assign team button hover works properly at smaller resolution as well. 
<img width="1357" alt="PR#2708_1" src="https://github.com/user-attachments/assets/c4e1d049-c735-4112-b178-567dde78354c">
<img width="813" alt="PR#2708_2" src="https://github.com/user-attachments/assets/e856d25c-54e7-4200-bde3-5fc3700da946">

2024-10-19 19:10 UTC, bhavya17prakash approved these changes
The assign team button hover is working as expected at smaller resolutions. Please find the screen recording of testing attached.

https://github.com/user-attachments/assets/c2c784cc-32fd-4ac8-852b-e7b1505a502b

2024-10-20 01:29 UTC, zhiminV approved these changes
I have checked the feature and it work as expected
![Screenshot 2024-10-19 at 6 26 25 PM](https://github.com/user-attachments/assets/83e04334-d5fd-4883-ba1d-4c4014f9456a)

2024-11-02 22:23 UTC, sheetalmangate commented
Changes are working locally. only having suggestion if message "This team code should only.."  is define as constant instead.

![PR2708_testing](https://github.com/user-attachments/assets/dc022f17-d1e3-4b4b-98f4-993e34fa8c08)

2024-11-06 18:28 UTC, AshritaCherlapally submitted a review, later dismissed
This code is working as expected. Assign Team button is working as per the changes at smaller resolutions.

https://github.com/user-attachments/assets/c6731cfb-6430-486d-8da6-a5508d90604c

2024-11-10 03:51 UTC, anandsesha approved these changes
Tested this PR and the resolution changes to the Teams section work as expected and the tooltip for the assign team button at smaller resolutions. The members modal displays correctly. Codbase looks clean. Screenshots attached.

![Screenshot (1131)](https://github.com/user-attachments/assets/1b5b2ab8-9277-4616-8c3b-d5494f3aeeff)
![Screenshot (1130)](https://github.com/user-attachments/assets/504bae82-3272-450e-85b1-8f2523db08e6)
![Screenshot (1128)](https://github.com/user-attachments/assets/5269795c-907f-4d4a-9917-aba89020c500)
![Screenshot (1127)](https://github.com/user-attachments/assets/0e308392-b644-4680-9e62-876cd5810494)
![Screenshot (1126)](https://github.com/user-attachments/assets/74256642-b0c6-4134-b5a9-49201632544d)

2025-01-12 04:28 UTC, one-community commented
Thank you all, merging!

2025-01-12 04:28 UTC, merged