Jatin get profile images from website
OneCommunityGlobal/HighestGoodNetworkApp pull request #2714
Opened 2024-09-22 21:42 UTC by JatinAgrawal94

# Description
<img width="733" alt="Screenshot 2024-09-08 at 1 41 52 PM" src="https://github.com/user-attachments/assets/8d53733f-5842-4077-8503-073a5fcc413d">

## Related PRS (if any):
This frontend PR is related to the [#1116](https://github.com/OneCommunityGlobal/HGNRest/pull/1116/) backend PR.

## Main changes explained:
- Added `confirmRemoveModal.js` to `components/UserProfileModal`.
- Added `suggestedProfileModal.js` to `components/UserProfileModal`.
- Made Changes to `UserProfileModal.css` and `UserProfile.jsx` files.
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to UserProfile Page.
6. If you have a profile on the onecommunity website, you should either have a profile image(if it was empty before) else you should see a `suggested Profile Image` button to display all the images that match your name.

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/3d410ea4-7923-4c9e-aa14-22d5e3e8b87f

2024-09-26 19:40 UTC, Dk-21 submitted a review, later dismissed
PR-2714
@JatinAgrawal94 
I tested the changes in the code.
I Can't see any of My photo or Suggested Profile Image Button to Display the images that match my name.

Suggestion : Also, We have to manually Enter the name otherwise it leads to the blank page. The name retrieval can be optimized to automatic retrieval from the User profile.

Thank You
<img width="1369" alt="PR-2714(1)" src="https://github.com/user-attachments/assets/0937907e-7a3c-4461-814c-6a93f01216cc">

2024-09-26 19:46 UTC, JatinAgrawal94 commented
> @JatinAgrawal94 I tested the changes in the code. I Can't see any of My photo or Suggested Profile Image Button to Display the images that match my name.
> 
> Thank You <img alt="PR-2714(1)" width="1369" src="https://private-user-images.githubusercontent.com/78248369/371292728-0937907e-7a3c-4461-814c-6a93f01216cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczODAwNTYsIm5iZiI6MTcyNzM3OTc1NiwicGF0aCI6Ii83ODI0ODM2OS8zNzEyOTI3MjgtMDkzNzkwN2UtN2EzYy00NDYxLTgxNGMtNmE5M2YwMTIxNmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE5NDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NzMwOGIwZTYwYmM4YjA0NzFiYmJkZTgxMWU3MGQ1YTg5NTMyNzk5YmRlODEzZDM5MjcyMGZkYzA2YTFlMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AUUyJToNFx6tL3K1cPFvGnBFZ4AZNZd_193ZAj4MI6A">

Hello Denish,
Do you have your bio posted on https://www.onecommunityglobal.org/team ? If yes, Only then your profile image would be changed and you will be able to see suggested Images button.
If you have any other questions, Please let me know.

2024-10-07 14:37 UTC, Ankuriboh reviewed
Looks good, but I am not sure if the remove avatar feature is needed.

2024-10-07 21:32 UTC, mrinalini-raghavendran19 reviewed
Hey Jatin,

I tried testing this PR, with the suggestion from one of your comments asking you to use your name for testing but it doesn't seem to work for me.

Are there any other things I need to look into before testing this PR?

<img width="1469" alt="Screenshot 2024-10-07 at 2 30 33 PM" src="https://github.com/user-attachments/assets/7072f32f-80fd-486a-bd2d-f5255052fc88">

2024-10-24 02:18 UTC, Rui-Liu-github reviewed
Hi, I reviewed an PR #2714 @JatinAgrawal94 .  I pulled the latest version to my local environment to check the fix. I'm not sure if others are experiencing the same issue, but the profile page couldn't be loaded, and errors were displayed in the browser. 

https://github.com/user-attachments/assets/1aae2aba-8f85-41a4-88ce-1c109ffd005f

2024-10-24 02:37 UTC, Rui-Liu-github requested changes
I reviewed the PR #2714 just now and try again, but still couldn't be loaded for the profile page. 

![image](https://github.com/user-attachments/assets/d3ee44c1-99da-49f2-99d9-2ce1952c6ea4)

2024-10-24 07:54 UTC, samarth9201 commented
I reviewd the PR. When trying to change the profile image, it displays the message "Please click on "Save changes" to save the changes you have made.", however I cannot click the button.

![Screenshot (111)](https://github.com/user-attachments/assets/87c6c207-0624-4368-8f59-42f8457554b6)

2024-10-26 06:48 UTC, sheetalmangate commented on src/components/UserProfile/UserProfile.jsx
> +      console.log(newUserProfile.profilePic)
Please remove console.log()

2024-10-26 07:24 UTC, sheetalmangate commented on src/components/UserProfile/UserProfile.jsx
> +                userProfile?.profilePic==null ||
instead of == use ===

2024-10-26 07:31 UTC, sheetalmangate commented
Code changes are looking good only having few suggestions.
1) Remove console.log for printing profile image
2) for comparison use === instead of ==

Could not test it locally.

2024-10-26 07:33 UTC, sheetalmangate submitted a review, later dismissed
Approving the code only need  below modification
1) Removing console.log()

2024-11-01 21:02 UTC, humera314 commented
I attempted to navigate to the User Profile page but encountered an error that prevented access.

![image](https://github.com/user-attachments/assets/6e8c1884-edf4-4f10-b1e6-46c6c7dc7f5a) ![image](https://github.com/user-attachments/assets/d83aae75-a6a8-4925-af17-42e56b261ba0)

2024-11-02 19:54 UTC, ajitp4292 reviewed
User Profile page is not accessible.
<img width="1181" alt="Screenshot 2024-11-02 at 3 53 24 PM" src="https://github.com/user-attachments/assets/206ce004-243e-4fad-89ab-b9a621487248">

2024-11-02 21:18 UTC, JatinAgrawal94 commented
> I reviewd the PR. When trying to change the profile image, it displays the message "Please click on "Save changes" to save the changes you have made.", however I cannot click the button.
> 
> ![Screenshot (111)](https://private-user-images.githubusercontent.com/50882280/379671479-87c6c207-0624-4368-8f59-42f8457554b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1ODI1NDksIm5iZiI6MTczMDU4MjI0OSwicGF0aCI6Ii81MDg4MjI4MC8zNzk2NzE0NzktODdjNmMyMDctMDYyNC00MzY4LThmNTktNDJmODQ1NzU1NGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDIxMTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkOWFmZTc3MjYzOTk5YjZmNDAzZmZmODdmN2YwMDE5MjRlZGE4MDA5ZDg5OGQ1YjdkMDNkY2M5ODZiMmVjYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.auzjFZUWc06jkWpiy2J_CyjX_Z2a7ZK7SO-51Tm1iYM)

The save button is present at the bottom of the page.

2024-11-02 21:19 UTC, JatinAgrawal94 commented
> User Profile page is not accessible. <img alt="Screenshot 2024-11-02 at 3 53 24 PM" width="1181" src="https://private-user-images.githubusercontent.com/114351189/382503215-206ce004-243e-4fad-89ab-b9a621487248.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1ODI1NTAsIm5iZiI6MTczMDU4MjI1MCwicGF0aCI6Ii8xMTQzNTExODkvMzgyNTAzMjE1LTIwNmNlMDA0LTI0M2UtNGZhZC04OWFiLWI5YTYyMTQ4NzI0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQyMTE3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjEzOTA3MDA2YzRhYWUzODE2N2NlNDBkYjg2ODdhNTk5YThmZjcwMDRhODRiZmM4NzdlMTEzMmIwOTdhMTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OVewxlY3TcoBv-TwCoRPstGXxQZp5-xxhPgoFtA3ixY">

Please clone the repository again and review. I have made significant changes to for that issue.

2024-11-02 23:19 UTC, Rupa2400 submitted a review, later dismissed
I reviewed PR #2714 from @JatinAgrawal94 and pulled the latest version into my local environment to test the fix. However, when I tried loading the profile page, it wouldn't display, and I ran into errors in the browser. I'm not sure if anyone else is experiencing the same issue.

<img width="959" alt="PR_2714" src="https://github.com/user-attachments/assets/c5a79006-a60b-4447-860e-36a37c199a03">

2024-11-03 00:13 UTC, audreydieuanh submitted a review, later dismissed
The profile page isn't loading, and the console shows an error: TypeError: undefined is not an object (evaluating 'suggestedProfilePics.map'). I suspect this is happening in the file src/components/UserProfile/UserProfileModal/suggestedProfileModal.js, where the code attempts to use the .map() method on suggestedProfilePics, which is currently undefined.

![test3](https://github.com/user-attachments/assets/66cbc743-037c-4726-861b-b8421d6fea52)

2024-11-03 00:27 UTC, JatinAgrawal94 commented
> The profile page isn't loading, and the console shows an error: TypeError: undefined is not an object (evaluating 'suggestedProfilePics.map'). I suspect this is happening in the file src/components/UserProfile/UserProfileModal/suggestedProfileModal.js, where the code attempts to use the .map() method on suggestedProfilePics, which is currently undefined.
> 
> ![test3](https://private-user-images.githubusercontent.com/127930337/382514988-66cbc743-037c-4726-861b-b8421d6fea52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTM0NzEsIm5iZiI6MTczMDU5MzE3MSwicGF0aCI6Ii8xMjc5MzAzMzcvMzgyNTE0OTg4LTY2Y2JjNzQzLTAzN2MtNDcyNi04NjFiLWI4NDIxZDZmZWE1Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2YxZTMzYTA5ZmIwYWY2ODEyN2FmNjJjYWFmZTIzZTU4M2ZhZDA0ZWY1ODExMGFiYTBjZmY1Zjk3ZWU2ZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c0X8zGXjsfbNkDPNM3Qb9JSbOHZNg8ppK_ZyWO8FAMQ) [ ![test3](https://private-user-images.githubusercontent.com/127930337/382514988-66cbc743-037c-4726-861b-b8421d6fea52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTM0NzEsIm5iZiI6MTczMDU5MzE3MSwicGF0aCI6Ii8xMjc5MzAzMzcvMzgyNTE0OTg4LTY2Y2JjNzQzLTAzN2MtNDcyNi04NjFiLWI4NDIxZDZmZWE1Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2YxZTMzYTA5ZmIwYWY2ODEyN2FmNjJjYWFmZTIzZTU4M2ZhZDA0ZWY1ODExMGFiYTBjZmY1Zjk3ZWU2ZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c0X8zGXjsfbNkDPNM3Qb9JSbOHZNg8ppK_ZyWO8FAMQ) ](https://private-user-images.githubusercontent.com/127930337/382514988-66cbc743-037c-4726-861b-b8421d6fea52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTM0NzEsIm5iZiI6MTczMDU5MzE3MSwicGF0aCI6Ii8xMjc5MzAzMzcvMzgyNTE0OTg4LTY2Y2JjNzQzLTAzN2MtNDcyNi04NjFiLWI4NDIxZDZmZWE1Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2YxZTMzYTA5ZmIwYWY2ODEyN2FmNjJjYWFmZTIzZTU4M2ZhZDA0ZWY1ODExMGFiYTBjZmY1Zjk3ZWU2ZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c0X8zGXjsfbNkDPNM3Qb9JSbOHZNg8ppK_ZyWO8FAMQ) [ ](https://private-user-images.githubusercontent.com/127930337/382514988-66cbc743-037c-4726-861b-b8421d6fea52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTM0NzEsIm5iZiI6MTczMDU5MzE3MSwicGF0aCI6Ii8xMjc5MzAzMzcvMzgyNTE0OTg4LTY2Y2JjNzQzLTAzN2MtNDcyNi04NjFiLWI4NDIxZDZmZWE1Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2YxZTMzYTA5ZmIwYWY2ODEyN2FmNjJjYWFmZTIzZTU4M2ZhZDA0ZWY1ODExMGFiYTBjZmY1Zjk3ZWU2ZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c0X8zGXjsfbNkDPNM3Qb9JSbOHZNg8ppK_ZyWO8FAMQ)

Can you please upload the complete video for reference , starting from making required changes to the code.

2024-11-03 00:30 UTC, audreydieuanh commented
> > The profile page isn't loading, and the console shows an error: TypeError: undefined is not an object (evaluating 'suggestedProfilePics.map'). I suspect this is happening in the file src/components/UserProfile/UserProfileModal/suggestedProfileModal.js, where the code attempts to use the .map() method on suggestedProfilePics, which is currently undefined.
> > ![test3](https://private-user-images.githubusercontent.com/127930337/382514988-66cbc743-037c-4726-861b-b8421d6fea52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTM0NzEsIm5iZiI6MTczMDU5MzE3MSwicGF0aCI6Ii8xMjc5MzAzMzcvMzgyNTE0OTg4LTY2Y2JjNzQzLTAzN2MtNDcyNi04NjFiLWI4NDIxZDZmZWE1Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2YxZTMzYTA5ZmIwYWY2ODEyN2FmNjJjYWFmZTIzZTU4M2ZhZDA0ZWY1ODExMGFiYTBjZmY1Zjk3ZWU2ZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c0X8zGXjsfbNkDPNM3Qb9JSbOHZNg8ppK_ZyWO8FAMQ)
> >       
> >         [
> >           
> >             ![test3](https://private-user-images.githubusercontent.com/127930337/382514988-66cbc743-037c-4726-861b-b8421d6fea52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTM0NzEsIm5iZiI6MTczMDU5MzE3MSwicGF0aCI6Ii8xMjc5MzAzMzcvMzgyNTE0OTg4LTY2Y2JjNzQzLTAzN2MtNDcyNi04NjFiLWI4NDIxZDZmZWE1Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2YxZTMzYTA5ZmIwYWY2ODEyN2FmNjJjYWFmZTIzZTU4M2ZhZDA0ZWY1ODExMGFiYTBjZmY1Zjk3ZWU2ZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c0X8zGXjsfbNkDPNM3Qb9JSbOHZNg8ppK_ZyWO8FAMQ)
> >           
> >         ](https://private-user-images.githubusercontent.com/127930337/382514988-66cbc743-037c-4726-861b-b8421d6fea52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTM0NzEsIm5iZiI6MTczMDU5MzE3MSwicGF0aCI6Ii8xMjc5MzAzMzcvMzgyNTE0OTg4LTY2Y2JjNzQzLTAzN2MtNDcyNi04NjFiLWI4NDIxZDZmZWE1Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2YxZTMzYTA5ZmIwYWY2ODEyN2FmNjJjYWFmZTIzZTU4M2ZhZDA0ZWY1ODExMGFiYTBjZmY1Zjk3ZWU2ZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c0X8zGXjsfbNkDPNM3Qb9JSbOHZNg8ppK_ZyWO8FAMQ)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/127930337/382514988-66cbc743-037c-4726-861b-b8421d6fea52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTM0NzEsIm5iZiI6MTczMDU5MzE3MSwicGF0aCI6Ii8xMjc5MzAzMzcvMzgyNTE0OTg4LTY2Y2JjNzQzLTAzN2MtNDcyNi04NjFiLWI4NDIxZDZmZWE1Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2YxZTMzYTA5ZmIwYWY2ODEyN2FmNjJjYWFmZTIzZTU4M2ZhZDA0ZWY1ODExMGFiYTBjZmY1Zjk3ZWU2ZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c0X8zGXjsfbNkDPNM3Qb9JSbOHZNg8ppK_ZyWO8FAMQ)
> >         
> >        [ ![test3](https://private-user-images.githubusercontent.com/127930337/382514988-66cbc743-037c-4726-861b-b8421d6fea52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTM0NzEsIm5iZiI6MTczMDU5MzE3MSwicGF0aCI6Ii8xMjc5MzAzMzcvMzgyNTE0OTg4LTY2Y2JjNzQzLTAzN2MtNDcyNi04NjFiLWI4NDIxZDZmZWE1Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2YxZTMzYTA5ZmIwYWY2ODEyN2FmNjJjYWFmZTIzZTU4M2ZhZDA0ZWY1ODExMGFiYTBjZmY1Zjk3ZWU2ZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c0X8zGXjsfbNkDPNM3Qb9JSbOHZNg8ppK_ZyWO8FAMQ) ](https://private-user-images.githubusercontent.com/127930337/382514988-66cbc743-037c-4726-861b-b8421d6fea52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTM0NzEsIm5iZiI6MTczMDU5MzE3MSwicGF0aCI6Ii8xMjc5MzAzMzcvMzgyNTE0OTg4LTY2Y2JjNzQzLTAzN2MtNDcyNi04NjFiLWI4NDIxZDZmZWE1Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2YxZTMzYTA5ZmIwYWY2ODEyN2FmNjJjYWFmZTIzZTU4M2ZhZDA0ZWY1ODExMGFiYTBjZmY1Zjk3ZWU2ZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c0X8zGXjsfbNkDPNM3Qb9JSbOHZNg8ppK_ZyWO8FAMQ)
> >       
> >         [
> >           
> >             ![test3](https://private-user-images.githubusercontent.com/127930337/382514988-66cbc743-037c-4726-861b-b8421d6fea52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTM0NzEsIm5iZiI6MTczMDU5MzE3MSwicGF0aCI6Ii8xMjc5MzAzMzcvMzgyNTE0OTg4LTY2Y2JjNzQzLTAzN2MtNDcyNi04NjFiLWI4NDIxZDZmZWE1Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2YxZTMzYTA5ZmIwYWY2ODEyN2FmNjJjYWFmZTIzZTU4M2ZhZDA0ZWY1ODExMGFiYTBjZmY1Zjk3ZWU2ZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c0X8zGXjsfbNkDPNM3Qb9JSbOHZNg8ppK_ZyWO8FAMQ)
> >           
> >         ](https://private-user-images.githubusercontent.com/127930337/382514988-66cbc743-037c-4726-861b-b8421d6fea52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTM0NzEsIm5iZiI6MTczMDU5MzE3MSwicGF0aCI6Ii8xMjc5MzAzMzcvMzgyNTE0OTg4LTY2Y2JjNzQzLTAzN2MtNDcyNi04NjFiLWI4NDIxZDZmZWE1Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2YxZTMzYTA5ZmIwYWY2ODEyN2FmNjJjYWFmZTIzZTU4M2ZhZDA0ZWY1ODExMGFiYTBjZmY1Zjk3ZWU2ZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c0X8zGXjsfbNkDPNM3Qb9JSbOHZNg8ppK_ZyWO8FAMQ)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/127930337/382514988-66cbc743-037c-4726-861b-b8421d6fea52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTM0NzEsIm5iZiI6MTczMDU5MzE3MSwicGF0aCI6Ii8xMjc5MzAzMzcvMzgyNTE0OTg4LTY2Y2JjNzQzLTAzN2MtNDcyNi04NjFiLWI4NDIxZDZmZWE1Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZ [...]

2024-12-12 05:54 UTC, Shreyav2000 requested changes
Hi Jatin,

I reviewed this PR along with the related backend PR and followed the instructions you provided. I updated the server.js file by adding the following lines:

```
[const { getProfileImagesFromWebsite } = require('./helpers/userHelper');
getProfileImagesFromWebsite();]

```

After restarting the server and reloading the page (while testing by changing the name to yours), I couldn’t see any image. I’ve attached a video for your reference.

Additionally, the suggested image feature doesn’t seem to fetch relevant suggestions based on the name entered. Instead, it displays the same three images regardless of the name input.

Refer to the video below:
https://github.com/user-attachments/assets/75a81b13-7d38-489c-90ea-38212f48fbf3

2024-12-13 06:37 UTC, nishitag5 requested changes
Hi Jatin,

I reviewed this PR along with the related backend PR and followed your instructions and recordring. After restarting the server and reloading the page (while testing by changing the from one community teams page), the image is not fetched from the website immediately but I can see the changes reflecting after some time.
As it is a corn job. Is there any schedule for the job to run due to which it is delayed?
I have attached the recording and screenshots below:



https://github.com/user-attachments/assets/37bbb58a-898c-4128-a8c9-a97dd1114160
![image](https://github.com/user-attachments/assets/14bd4cce-0f11-44f8-9acb-80bc36ef24d5)

2024-12-14 06:16 UTC, nishitag5 approved these changes
HI Jatin,
After taking your changes and following the steps mentioned, I changed the name in the user profile to match with the team member's name available on the One Community website. Then I restarted the server and waited for 5-7 minutes to refresh the profile page. On refreshing the page, I am able to see the profile image based on the user name given in the profile page. 
The changes are working as expected. Please find the recording below:

https://github.com/user-attachments/assets/60b5623c-5ba1-4aee-acbf-6b8551d5225c

2024-12-21 05:08 UTC, Shreyav2000 approved these changes
Hi Jatin,

I reviewed your PR again and I'm ready to approve these changes, as everything is working correctly now. Initially, I thought the changes (particularly the profile image being fetched from the One Community website) would reflect immediately, but I see now that it takes a couple of minutes.

2025-01-12 04:20 UTC, Sheehan20 reviewed
Hi @JatinAgrawal94, great work on implementing the profile image fetching feature! Here are my observations:

1. Feature Highlights:
- Added ability to fetch profile images from the One Community website
- Implemented modal for suggested profile images
- Created confirmation modal for image removal
- Enhanced user profile image management

2. Key Components Added:
- `suggestedProfileModal.js`: Modal for displaying suggested profile images
- `confirmRemoveModal.js`: Modal for confirming profile image removal
- Updated `UserProfile.jsx` to support new image selection and removal workflows

3. Notable Technical Implementations:
- Added endpoints for profile image management
- Implemented image conversion to base64
- Added toast notifications for image updates
- Graceful handling of profile image scenarios

4. Observations & Suggestions:
- The feature seems to have a slight delay in image fetching (as noted by reviewers)
- Recommended adding error handling for image conversion
- Consider adding loading states during image fetch/update

5. Testing Recommendations:
- Verify image fetching works across different user profiles
- Test edge cases like no suggested images
- Ensure smooth cross-browser compatibility

Overall, this is a solid implementation that enhances user profile customization. Great job on the detailed implementation!

2025-01-16 23:15 UTC, honglinchen0524 reviewed
The profile page isn't loading for some reason. Here is the video (including the code I added following the backend PR instructions):

https://github.com/user-attachments/assets/bc9ab55d-2361-4770-b80a-0b4573cea596

2025-01-21 16:29 UTC, jeyanthi-sm commented
Logged in and navigated to 'View Profile'.
Received the following warning:
'It was not possible to retrieve the team codes. Please try again by clicking the icon inside the input auto-complete.'
This was followed by a blank screen.

See the attached video for more details.

https://github.com/user-attachments/assets/d4e4c50f-cfc7-4fdd-9d45-8ab47ba94bd2

2025-01-24 21:03 UTC, JatinAgrawal94 commented
> The profile page isn't loading for some reason. Here is the video (including the code I added following the backend PR instructions):
> 
>  PR2714.mp4

The user profile page, has been working fine for me. I have tried doing that in firefox, Chrome, Safari. 
Please try again and let me know if the issue still persists.

2025-01-24 21:04 UTC, JatinAgrawal94 commented
> Logged in and navigated to 'View Profile'. Received the following warning: 'It was not possible to retrieve the team codes. Please try again by clicking the icon inside the input auto-complete.' This was followed by a blank screen.
> 
> See the attached video for more details.
> 
>  PR-2714.mp4

The userprofile screen seems to be working fine for me. I have tried that on chrome, safari and firefox. Please try again and let me know if the issue still persists.

2025-01-24 23:45 UTC, one-community commented
Thank you all, merging!

2025-01-24 23:45 UTC, merged