Aditya-Added-testing-for-PermisssionsManagement
OneCommunityGlobal/HighestGoodNetworkApp pull request #2729
Opened 2024-09-27 23:54 UTC by adityasure9

# Description
This pull request introduces unit testing for the `PermissionsManagement` component in the application. It covers test cases for various functionalities, including handling permissions, updating user roles, and ensuring proper UI rendering in different scenarios.

## Main changes explained:
- Added unit tests to `PermissionsManagement` to ensure that the permission settings are handled correctly.
- Mocked API calls and Redux store to simulate different user roles and permissions.
- Verified that the UI renders correctly when different permission levels are applied.
- Added error boundary tests to ensure graceful failure handling.

## How to test:
1. Check out the current branch.
2. Run `npm install` to ensure all necessary dependencies are installed.
3. Run the following command to execute the test suite: npm test PermissionsManagement.test.js

## Screenshots or videos of changes:

![image](https://github.com/user-attachments/assets/69dc7be3-c847-440f-b165-d76b4e83bacb)

## Note:
Please make sure to run the tests with npm test and verify that all test cases pass successfully. If there are any dependencies or environment-specific configurations needed for these tests, make sure they are set up beforehand.

2024-09-28 00:57 UTC, ziyanw52 approved these changes
I execute the test suite and all of them passed.
![521727485062_ pic_hd](https://github.com/user-attachments/assets/9e6aafbe-0049-4717-a8f8-70598f423bc0)

2024-09-28 02:20 UTC, nikhilpittala16 approved these changes
I have tested the PR and all the test cases have passed.
![Screenshot (210)](https://github.com/user-attachments/assets/3475258a-3d16-447d-b27e-64476f955b34)

2024-09-28 04:51 UTC, jinxyou approved these changes
All test cases have passed.  
![image](https://github.com/user-attachments/assets/43a3231f-c1db-473c-b53d-e651edd3993b)

2024-09-28 17:14 UTC, Dk-21 approved these changes
PR 2729
@adityasure9 
Tested the test file and all test cases passed.
<img width="701" alt="PR 2729" src="https://github.com/user-attachments/assets/acd42094-77d4-47e8-a887-c4d05cdece5a">

2024-09-28 23:32 UTC, ishangoel17 reviewed
All test cases are passing, however observed few console errors. Below is the screenshot for reference:
![Capture2729](https://github.com/user-attachments/assets/06fe406e-4b0c-461d-a693-ef43ba22d4dd)

2024-09-29 04:53 UTC, aaryaneil reviewed
Thanks for the edits! It seems only comments were updated and the file was moved. Could you check for any required functional changes?

2024-09-29 06:38 UTC, mianmiantea2019 commented
All test cases are passing, however observed few console errors. 

![image](https://github.com/user-attachments/assets/d5e8c427-132e-40f4-93e9-051946f74ab1)
![image](https://github.com/user-attachments/assets/833521a5-f816-4e30-89fd-7cccab54cf24)

2024-09-29 07:03 UTC, nathanah requested changes

2024-09-29 07:03 UTC, nathanah commented on src/components/PermissionsManagement/__tests__/PermissionsManagement.test.js
> +        expect(screen.queryByRole('Button', { name: /add new role/i })).not.toBeInTheDocument();
This should probably test that the button appears only when the user has the "Add Roles" (Key = `postRole`) permission. Are you testing for multiple roles? There's a useful function in `MockStates` for creating auths for testing specific permissions `createAuthMocks()`.

2024-10-02 17:52 UTC, slidracoon72 approved these changes
#2729
@[adityasure9](https://github.com/adityasure9) 
Verified the unit test file, and all test cases successfully passed.

![2729](https://github.com/user-attachments/assets/8c7aac9f-07d9-4acd-bb58-a7b83c338304)

2024-10-03 13:38 UTC, Vincent-space approved these changes
Hi, all test cases passed

2024-10-04 10:41 UTC, beblicarl requested changes
All tests passed however there are a lot of errors in the console

![image](https://github.com/user-attachments/assets/8d5617f8-8e7c-4613-a909-3892cba1939e)

2024-10-11 02:27 UTC, vijay10pk requested changes
All the test cases passed but there are errors in the console. refer below screenshot.
<img width="899" alt="Screenshot 2024-10-10 at 10 26 39 PM" src="https://github.com/user-attachments/assets/7b8ec533-b837-42a3-aa02-45c7de6314c2">
<img width="908" alt="Screenshot 2024-10-10 at 10 26 30 PM" src="https://github.com/user-attachments/assets/08c00f22-414a-4016-91eb-59185d16e775">

2024-10-12 00:57 UTC, SatyashanthiT commented
I reviewed and tested this PR, focusing on the new unit tests for the PermissionsManagement component. The tests effectively cover various scenarios, including role updates, API handling, and UI rendering with different permissions. All test cases passed, confirming the component's functionality works as intended.
<img width="705" alt="image" src="https://github.com/user-attachments/assets/cf35f846-8253-4bb3-ba21-b93adce1c34a">

2024-10-24 16:40 UTC, ajitp4292 approved these changes
Permission Management test case runs as expected.
<img width="992" alt="Screenshot 2024-10-24 at 12 38 46 PM" src="https://github.com/user-attachments/assets/bc9408bf-f8a6-4601-80b1-144c4b4facd3">

2024-10-26 20:25 UTC, SharadhaS24 approved these changes
All the testcases are passing successfully.

<img width="468" alt="image" src="https://github.com/user-attachments/assets/d01d132e-299d-4281-826c-312278142580">

2024-10-26 22:13 UTC, Muhideenthegreat approved these changes
Verification:

All of the test case in the unit testing for the PermissionsManagement component in the application works.

<img width="923" alt="Screenshot 2024-10-26 at 6 12 03 PM" src="https://github.com/user-attachments/assets/fde53f43-188a-4b78-8f2d-025c716ba361">

2024-11-02 00:53 UTC, samarth9201 approved these changes
All the test cases passed. There are some errors logged which need to be fixed.

![Screenshot 2024-11-01 175226](https://github.com/user-attachments/assets/16370f7d-a0e2-4d73-b020-2efceb8bc26a)

2025-02-18 16:49 UTC, closed without merging