Aditya-Added-Unit-Testing-for-UpdatePassword
OneCommunityGlobal/HighestGoodNetworkApp pull request #2732
Opened 2024-09-28 03:00 UTC by adityasure9

# Description
This PR introduces unit tests for the `UpdatePassword` component. The purpose is to ensure the functionality around updating passwords, including input validation, error handling, and correct API interaction behavior, works as intended. This PR addresses:

## Main changes explained:
- **Created** `UpdatePassword.test.jsx` to introduce unit tests for the `UpdatePassword` component.
- **Mock** API responses using `msw` to simulate server interactions for the password update requests.
- **Added** validation tests for input fields including empty states, invalid formats, and mismatched passwords.
- **Introduced** tests for server errors, loading state on submit, and successful password update handling.
- **Included** dark mode test for UI consistency across themes.

## How to test:
1. Check into the current branch.
2. Run `npm install` to install dependencies.
3. Run `npm test UpdatePassword.test.jsx` to execute the unit tests..

## Screenshots or videos of changes:
![image](https://github.com/user-attachments/assets/b70b59be-f113-40ba-aa71-9db99bd6644d)

2024-09-28 04:14 UTC, geetamatkar commented
Hi @adityasure9 ,
Tested this PR and I'm getting this error.

<img width="1001" alt="pr2732" src="https://github.com/user-attachments/assets/3bc4db96-4c06-4c54-b97c-7b242f6ff1b2">

2024-09-28 04:32 UTC, jinxyou approved these changes
![image](https://github.com/user-attachments/assets/c8f7891d-23f5-479d-86f7-057557413f9c)
All test cases have passed

2024-09-28 23:19 UTC, ishangoel17 reviewed
Tested this PR and I'm getting this error. Below is the screenshot for reference:
![Capture2732](https://github.com/user-attachments/assets/9eff2e80-6185-4de8-a3d8-78ff7b74194d)

2024-09-29 04:32 UTC, ptrpengdev commented
LTGM. Should fix how to test section from `npm test UpdatePassword.test.jsx` to `npm test UpdatePassword.test.js`

![image](https://github.com/user-attachments/assets/b57fbd4c-2401-483b-924a-1899681b032c)

2024-09-29 04:32 UTC, ptrpengdev approved these changes

2024-09-29 04:44 UTC, aaryaneil reviewed
Thanks for the PR! It looks like the changes are mostly comment edits. Could you review and make any necessary functional changes?

2024-09-29 06:34 UTC, mianmiantea2019 commented
All tests pass.

![image](https://github.com/user-attachments/assets/af47c517-cca1-4051-8237-20dee869e583)

2024-10-02 18:48 UTC, tharunaa-1 commented
All the test cases has been passed

![image](https://github.com/user-attachments/assets/ca1bcb48-280b-4ab6-a727-55135e55801d)

2024-10-03 18:46 UTC, nikhilpittala16 approved these changes
I have tested the PR and all the test cases have passed.
![Screenshot (220)](https://github.com/user-attachments/assets/d56e7348-e299-4ce5-9822-5131c8295288)

2024-10-04 10:58 UTC, beblicarl requested changes
All tests passed however there are errors in the console

![image](https://github.com/user-attachments/assets/ee0e869f-6151-4881-88ce-5cdbf95cd110)

![image](https://github.com/user-attachments/assets/a9f374e2-daf7-4c30-8a3f-e7d725bd24e7)

2024-10-06 05:03 UTC, ziyanw52 approved these changes
All the test cases passed successfully.
![1001728191010_ pic_hd](https://github.com/user-attachments/assets/b4c844c6-2280-41f4-a5f4-2b661c76f919)

2024-10-06 06:34 UTC, mianmiantea2019 commented
All the test cases passed successfully.

![image](https://github.com/user-attachments/assets/0a902393-66be-46e6-9d55-088192aa591f)

2024-10-11 02:21 UTC, vijay10pk approved these changes
All the test case passed.
<img width="916" alt="image" src="https://github.com/user-attachments/assets/6cbdcdf1-8a71-40e7-8d2c-ea135075b8d6">

2024-10-12 00:54 UTC, SatyashanthiT commented
I reviewed and tested this PR. The unit tests for the UpdatePassword component ran as expected, covering validation, API interaction, and error handling scenarios. The functionality works as intended.
<img width="651" alt="image" src="https://github.com/user-attachments/assets/35dfa134-025c-4595-9441-288364f2e569">

2024-10-19 16:18 UTC, SharadhaS24 approved these changes
All the test cases are passing for update password component.

<img width="468" alt="image" src="https://github.com/user-attachments/assets/0a900c97-b9d1-42a4-983c-6ac55044822f">

2024-10-26 22:08 UTC, Muhideenthegreat approved these changes
Verification:

All of the test case in this unit testing, for the update password component, passes and works as expected.

<img width="933" alt="Screenshot 2024-10-26 at 6 05 53 PM" src="https://github.com/user-attachments/assets/13b8e013-8e55-4666-a33b-891468eb7b63">

2025-01-18 01:35 UTC, vishavk1992 approved these changes
I have tested this PR and all test cases passed successfully!!

2025-02-18 16:50 UTC, closed without merging