Cillian: Fix archived project list functionality
OneCommunityGlobal/HighestGoodNetworkApp pull request #2748
Opened 2024-10-04 23:46 UTC by CillianRen

**Description**
This PR fixes the issue related to the archived project list not displaying correctly in the allProjectsReducer. It addresses the bug where the incorrect data was being displayed and improves the functionality for handling archived projects.
Fixes # 
![image](https://github.com/user-attachments/assets/91cc7f41-ecfe-4956-a1b7-4a845b7c8714)
https://drive.google.com/file/d/15B5PBBbiHo_SvCMeLu9W_KckjAjY17PM/view?usp=sharing

…

## Main changes explained:
Updated allProjectsReducer.js to fix issues with archived project list rendering and ensure proper handling of project data.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. Navigate to: Other Links → Projects. Attempt to archive a project and verify that the archive functionality is working as expected.
6. Verify that this new feature works in [dark mode]
## Screenshots or videos of changes:

https://github.com/user-attachments/assets/31ab67ff-56c9-479e-9a85-c1f002af8f9b

2024-10-05 01:35 UTC, SatyashanthiT commented
After following the provided steps and testing the updated feature, the archived projects now display and function as expected. I have confirmed that the bug fix improves the rendering and handling of archived project data.

https://github.com/user-attachments/assets/bb07e82d-c15c-4349-b6ee-8d7074c48d1e

2024-10-10 21:50 UTC, nikhilpittala16 submitted a review, later dismissed
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/f1f678fa-22de-4a20-815f-569ee3909dec

2024-10-11 21:30 UTC, tharunaa-1 commented
works as expected!


https://github.com/user-attachments/assets/d5decf24-fcc9-4ff1-9eb1-9625e197e878

2024-10-12 05:12 UTC, khushijain03 approved these changes
Hi @CillianRen , the PR works as expected. It takes a bit time to load after clicking the confirm button, other than that, it works well.


https://github.com/user-attachments/assets/b88dda3c-0157-4b28-961a-44feff2982b6

2024-10-12 07:15 UTC, lng2020 commented on src/reducers/allProjectsReducer.js
> +      index = allProjects.projects.findIndex(project => project._id === updatedProject._id);
just a nit. 
```
projects = allProjects.projects.map(project =>
  project._id === undatedProject._id ? updatedProject : project
);

return updateState({ projects, status });
```

2024-10-12 07:15 UTC, lng2020 commented on .vscode/settings.json
accidentally added?

2024-10-12 07:33 UTC, Jingyii800 submitted a review, later dismissed
I have tested this feature and it worked as expected.

https://github.com/user-attachments/assets/fde519d1-2ac4-499c-b3d1-f681bb761ba7

2024-10-13 02:30 UTC, javid679 commented
Hey the updates to the PR are on the point, Good job, below is the video for your reference:


https://github.com/user-attachments/assets/2c3daca9-2cb4-45a3-ad2e-36256de9e631

2024-10-14 22:00 UTC, AshishNags submitted a review, later dismissed
Approving this PR, archive function working as expected.
![Screenshot 2024-10-14 165702](https://github.com/user-attachments/assets/a80e806c-0e8f-40a6-b11b-388e8c15a802)
![Screenshot 2024-10-14 165821](https://github.com/user-attachments/assets/f10bb7c0-e1bf-43a2-a3fa-38673b198c13)

2024-10-16 18:09 UTC, aaryaneil submitted a review, later dismissed
Tested the PR and the changes works as expected.

https://github.com/user-attachments/assets/9cdf101c-dc26-4266-872c-d5f746388b29

2024-10-16 23:19 UTC, SharadhaS24 submitted a review, later dismissed
Confirmed the project archive functionality removes archived projects from the list, working correctly in both light and dark modes.



https://github.com/user-attachments/assets/d8bde092-8f63-4d43-98d9-a007442ae247

2024-10-17 06:41 UTC, NK3101 submitted a review, later dismissed
I have tested the PR and everything works as expected in both light and dark modes.

https://github.com/user-attachments/assets/3216a72e-498c-4699-b42c-f38efabd1c2e

2024-10-18 05:27 UTC, Anoushka21 reviewed
The archive functionality works fine. But do we need the settings.json file? 

https://github.com/user-attachments/assets/ae97310a-bf4d-44d0-a31a-c94495ca6156

2024-10-19 00:32 UTC, VMD281 commented
Hi, I reviewed this PR and the archive property works perfectly
<img width="1459" alt="PR#2748_1" src="https://github.com/user-attachments/assets/9344f017-4148-4db0-86d8-1cf9f32764af">
<img width="1459" alt="PR#2748_2" src="https://github.com/user-attachments/assets/8fafbf21-bedc-45f8-997a-3217ed075499">
<img width="1459" alt="PR#2748" src="https://github.com/user-attachments/assets/685ad9f3-b22c-4473-9dcf-be8f11082f97">
! I have pasted the screenshots below:

2024-10-19 01:05 UTC, bhavya17prakash submitted a review, later dismissed
I have tested the functionality in dark mode and it's working as intended. Please find the screen recording attached

https://github.com/user-attachments/assets/08aa5fa9-d338-41f9-ba1d-4d433f2ea459

2024-10-19 04:21 UTC, zhiminV approved these changes
I have check this feature in dark mode, 
1. create my test project: 
<img width="1256" alt="Screenshot 2024-10-18 at 9 17 42 PM" src="https://github.com/user-attachments/assets/1856ec97-3188-4280-96ed-63e947d245f3">
<img width="1252" alt="Screenshot 2024-10-18 at 9 18 09 PM" src="https://github.com/user-attachments/assets/0d570911-de99-4c06-9450-f898f06455d1">
2. Confirm Archive
<img width="1239" alt="Screenshot 2024-10-18 at 9 18 18 PM" src="https://github.com/user-attachments/assets/6f26d52c-0851-4c91-bc6c-4b8fb248aea8">
3. my test project not show,  work as expected!
<img width="1243" alt="Screenshot 2024-10-18 at 9 18 40 PM" src="https://github.com/user-attachments/assets/56d530f0-6da3-4b71-9b17-16ae6dd64a03">

2024-10-20 00:23 UTC, shashankhv submitted a review, later dismissed
Tested archive functionality for projects, and it works as expected. Verified it also works in dark mode.

[Cillian-PR.webm](https://github.com/user-attachments/assets/c1573bae-44a0-4967-b414-cbbba83c6003)

2024-10-20 02:05 UTC, lng2020 requested changes
The vscode settings.json should be removed in my opinion.

2024-10-20 02:06 UTC, KurtisIvey approved these changes
![Screenshot 2024-10-19 at 9 04 07 PM](https://github.com/user-attachments/assets/286d2b60-4a08-47cb-bd0c-869248bd27d2)


Archive functionality now refreshes. Dark mode works as well. I don't know where to find archived projects, but you've met the goal of the pull request. Good job! minimal code changes as well which I like

2024-10-20 02:12 UTC, KurtisIvey commented on .vscode/settings.json
I agree. It has to go

2024-10-23 19:15 UTC, Rui-Liu-github reviewed
Hi, I pulled the latest version to my local and reviewed the PR #2748 @CillianRen. the feature of archived project list functionality works as expected. Normal and Dark mode works well. But when I clicked the confirm button in the new window to archive the project, nothing happened for about 5-12 seconds. After this delay, the verification window disappeared. I think the user experience should be improved in the future.I tried several times and not sure if anyone else has this experience.

https://github.com/user-attachments/assets/7be34e26-923b-46c2-8533-9d4132e43ed4

![image](https://github.com/user-attachments/assets/fa11f137-d1d0-40d2-bca2-22f28406c635)
![image](https://github.com/user-attachments/assets/0b7612db-ecab-4d5d-850c-8501824acd03)
![image](https://github.com/user-attachments/assets/a3d893c2-3cb0-431c-8b6f-ff7594219772)

2024-10-24 07:43 UTC, samarth9201 submitted a review, later dismissed
I have verified that th PR work as expected. However, I noticed that it takes significantly long time to load the page again, which should not happen.

2024-10-26 15:30 UTC, RachanaZha commented
I have tested the PR. After clicking the confirm button , it takes a few seconds for the popup to disappear and the project archive changes to reflect. The changes are working perfectly fine and as expected, however the response time after clicking the confirm button is a bit long.

https://github.com/user-attachments/assets/3433d87b-3949-4f7b-b4ef-4a61890d390f

2024-10-26 15:48 UTC, RachanaZha submitted a review, later dismissed

2024-11-06 18:42 UTC, AshritaCherlapally reviewed
I have created a Test project and tried archiving it, the Archive functionality works as expected, but the response time after clicking on Confirm button is way too long. User experience can be better. Except that everything looks great.

https://github.com/user-attachments/assets/853ba46f-15ee-4ccc-be14-9b1cf3ee23fc

2024-12-20 21:42 UTC, CillianRen commented
> The vscode settings.json should be removed in my opinion.

Thank you for the suggestion! I’ve already deleted the vscode/settings.json file in this PR. Please let me know if there’s anything else that needs to be addressed.

2024-12-20 21:43 UTC, CillianRen commented
> just noticed the .vscode/settings.json change.
> 
> We don't have that in the codebase, and it does look like a personal setting.
> 
> I'm fine with the rest of the code though.
> 
> ![Screenshot 2024-10-19 at 9 04 07 PM](https://private-user-images.githubusercontent.com/19482363/378139213-286d2b60-4a08-47cb-bd0c-869248bd27d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MzEyMTMsIm5iZiI6MTczNDczMDkxMywicGF0aCI6Ii8xOTQ4MjM2My8zNzgxMzkyMTMtMjg2ZDJiNjAtNGEwOC00N2NiLWJkMGMtODY5MjQ4YmQyN2QyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDIxNDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZmI5ZDBhZDFhZWVjYmY5NDJhOTQ0MWUxZTQ2MTQwYmYwNWYzMTZlMDhkM2JlZThlZjZjMTVmYzk5YmM5YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3WLWImoa1K7cqVAC3mvZvC-7kgTWXuLiYrtBNnAxxxU)
> 
> Archive functionality now refreshes. Dark mode works as well. I don't know where to find archived projects, but you've met the goal of the pull request.

Thank you for the suggestion! I’ve already deleted the vscode/settings.json file in this PR. Please let me know if there’s anything else that needs to be addressed.

2024-12-21 04:37 UTC, lng2020 commented
But the fixing part is also removed? Now the diff says nothing has changed. Probably because of the merge operation.

2024-12-21 04:44 UTC, CillianRen commented
> But the fixing part is also removed? Now the diff says nothing has changed. Probably because of the merge operation.

![image](https://github.com/user-attachments/assets/98ee7f48-3235-482d-b2c5-14b5318cc934)

My changes from the previous commit are still included in the merge, so it doesn't matter.

2024-12-21 06:36 UTC, lng2020 reviewed
but now this PR's files change is nothing.

2024-12-21 07:04 UTC, CillianRen commented
> but now this PR's files change is nothing.

The file changes are displayed based on the commits I made earlier, showing only the differences between the merged version and the updates I made to the feature. Which means it include the corrected code.

2024-12-21 07:13 UTC, lng2020 commented
This is the current change https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2748/files. Your first commit fe518cf26d9e39b785c63d75506886e7168a91c0 fixed the code and added the vscode file. The second commit 9f0101c6bcae9f15d3b5ec665f4705a047cdf925 deleted the vscode file. The latest commit 963c6342cb985833232cc329a4a4ba5d2489b892 reverted the code fix.

2024-12-21 07:21 UTC, CillianRen commented
> This is the current change https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2748/files. Your first commit [fe518cf](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/fe518cf26d9e39b785c63d75506886e7168a91c0) fixed the code and added the vscode file. The second commit [9f0101c](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/9f0101c6bcae9f15d3b5ec665f4705a047cdf925) deleted the vscode file. The latest commit [963c634](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/963c6342cb985833232cc329a4a4ba5d2489b892) reverted the code fix. The current change of this PR is ![image](https://private-user-images.githubusercontent.com/70063547/397911300-e21b28b7-463e-4055-8b65-dccd67b39300.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NjU3MzksIm5iZiI6MTczNDc2NTQzOSwicGF0aCI6Ii83MDA2MzU0Ny8zOTc5MTEzMDAtZTIxYjI4YjctNDYzZS00MDU1LThiNjUtZGNjZDY3YjM5MzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA3MTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYjNlZmUwYTc3ODhkMzRhMjUxMDRhYzhhZGM5NDg5OTIzN2U5YjM2ZGQ3M2RlYzkwMDBkZWI0MTE1OTEyNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZoPa9g85cJqCgrX7uNLfs2q1e0kwPPuITyPCPTFW-WA)

Please check the third commit to see if the changes I made to AllprojectReducers in the first commit are still present in the third commit. Just go click into the third commit and looking for lane 42 to see if it’s updatedproject_id or not.

2024-12-21 07:52 UTC, lng2020 commented
> Please check the third commit to see if the changes I made to AllprojectReducers in the first commit are still present in the third commit. 

Commits are separated. If this PR merges, all of your three commits will be merged. So we only need to inspect the file changes by combining three commits, which is https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2748/files.

2025-01-04 20:36 UTC, closed without merging