Haoyue fix team code data on profile page
OneCommunityGlobal/HighestGoodNetworkApp pull request #2751
Opened 2024-10-05 03:55 UTC by oliviahyw

# Description
<img width="758" alt="Screenshot 2024-10-04 at 10 49 18 PM" src="https://github.com/user-attachments/assets/1ba55baa-d373-4081-ac47-ff1bafb14295">

## Related PRS (if any):

## Main changes explained:
- Changed the options in "Team Code" field on profile page to the active team code data from the weekly summary report page.
- Added team code to redux so that it can be accessed through the entire app.
- When the team code has been updated on the weekly summary report page, the according title on the profile page will display as red.
- Also added the error styling for the team code field.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to user profile → Add a New Title
6. verify the current team code
7. go to weekly summary report → modify the team code
8. go to user profile → verify the styling of title div and team code field in the edit modal

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/3e651bec-1035-43cc-843f-643aa75785ee

2024-10-12 06:51 UTC, Jingyii800 requested changes
After replacing the team code in weekly summary reports and back to the profile page. The edit button exists but when I want to update the team code, it displays "invalid team code error". Please check more details in my video.

https://github.com/user-attachments/assets/c444895d-5ab5-42c1-9303-fb8e04e306ad

https://github.com/user-attachments/assets/46df9118-9387-4336-8849-b5d67a94924e

2024-10-17 17:27 UTC, AshishNags approved these changes
Approving this PR, Functionality working as expected.
![Screenshot 2024-10-17 121736](https://github.com/user-attachments/assets/b46339d5-4b24-41fb-92e6-3ca9973d849a)
![Screenshot 2024-10-17 121859](https://github.com/user-attachments/assets/fe519ba1-b8d0-4885-ab3f-04b62463968f)
![Screenshot 2024-10-17 122420](https://github.com/user-attachments/assets/20787904-b629-45ae-839c-746d16ae8267)

![Screenshot 2024-10-17 122545](https://github.com/user-attachments/assets/ac295e54-5fd6-492c-8423-3c9785dd01b0)

2024-10-19 00:20 UTC, VMD281 commented
Hi, I reviewed this PR and the alignment looks good! I have pasted the screenshots below:
<img width="421" alt="PR#2751_1" src="https://github.com/user-attachments/assets/a2deecc9-bf68-4baa-8a06-bcba18f927a3">
<img width="578" alt="PR#2751_2" src="https://github.com/user-attachments/assets/97a4b4ea-17e1-4773-87c5-fa9476ddd1e0">
<img width="578" alt="PR#2751_3" src="https://github.com/user-attachments/assets/7c8065a6-3756-4d03-b06e-837cde9a390c">
<img width="578" alt="PR#2751_4" src="https://github.com/user-attachments/assets/261e92d7-db6c-4bd2-aaaf-182a727870f7">
<img width="578" alt="PR#2751_5" src="https://github.com/user-attachments/assets/2d637ff4-fb52-40db-ba54-4e27480d2704">

2024-10-23 11:28 UTC, samarth9201 approved these changes
Verified the functionality of the PR. LGTM!

![image](https://github.com/user-attachments/assets/10a1bdad-a49e-41e2-8198-acf0f4081ec3)

2024-10-23 21:05 UTC, bhavya17prakash submitted a review, later dismissed
Verified the functionality is working as intended
<img width="644" alt="PR 2751" src="https://github.com/user-attachments/assets/8c84ff2a-98e4-4798-8319-89f8c624c9af">

2024-10-24 00:48 UTC, Rui-Liu-github approved these changes
Hi, I reviewed PR #2751. I pulled the latest version to my local and checked the fixed function. The function works as expected. I modified the team code from AB-XYZ to A-XYZ, then went to the profile. The styling of the title div and the team code field in the edit modal, appeared as red. 
![ReviewPR_#2751_1](https://github.com/user-attachments/assets/5c6e89f7-a51e-4c1a-a2c5-9d597472542a)
![ReviewPR_#2751_2](https://github.com/user-attachments/assets/cd610707-2c9f-4c1b-9aa0-59962b119dea)
![ReviewPR_#2751_3](https://github.com/user-attachments/assets/3f2a376f-fc95-4f9b-919f-bd07e3b8c09b)
![ReviewPR_#2751_4](https://github.com/user-attachments/assets/d3a08a3c-4286-4a59-a24d-8f4add87b264)
![ReviewPR_#2751_5](https://github.com/user-attachments/assets/ba4fe6fd-278a-4358-a424-c8142164cc29)
![ReviewPR_#2751_6](https://github.com/user-attachments/assets/4fb2baae-c22a-4d31-b20a-92dd9dd1d5ac)

2024-10-26 20:48 UTC, zhiminV submitted a review, later dismissed
I have checked this function works as expected. I changed the team code from a-bbb to AbbAbb, it work after I changed and I back to the profile, the new team code also showed in the dropdown list.
![Screenshot 2024-10-26 at 1 40 54 PM](https://github.com/user-attachments/assets/9d42fe1c-c271-4bdd-b75a-1f5f87174caf)
![Screenshot 2024-10-26 at 1 39 22 PM](https://github.com/user-attachments/assets/6bd5fd24-867e-48fb-8dec-e81ff93382d1)
![Screenshot 2024-10-26 at 1 41 01 PM](https://github.com/user-attachments/assets/eb25bbde-bad0-467a-bd3b-65d042a86fb0)
![Screenshot 2024-10-26 at 1 43 57 PM](https://github.com/user-attachments/assets/2d533bfc-aebd-46ef-b10a-f4d6a3194ce5)

2024-11-02 19:22 UTC, AshritaCherlapally requested changes
I have tested this code, I have changed the team code from B-TES to B-tesss in the weekly summary report section. The code is updated successfully. But when i am trying to update the code in profile section, i cannot see the EDIT button to update the existing team code. But it is working fine when i am trying to create a new title with changed code B-tesss, i can see the changed code in the dropdown list.

<img width="1440" alt="Screenshot 2024-11-02 at 3 12 29 PM" src="https://github.com/user-attachments/assets/a37d9e1b-580b-4823-843d-33f712f70b63">
<img width="1440" alt="Screenshot 2024-11-02 at 3 12 44 PM" src="https://github.com/user-attachments/assets/a35eba09-439e-41f6-afc1-4ef325f2de60">
<img width="1440" alt="Screenshot 2024-11-02 at 3 18 18 PM" src="https://github.com/user-attachments/assets/2fb0dd84-df65-4d14-8c11-f78a329ea2df">

2024-11-02 20:49 UTC, ajitp4292 approved these changes
I have checked the functionality works as expected. I changed the team code from T-est to T-est1, it work after I changed and I back to the profile, the new team code also showed in the
<img width="1507" alt="Screenshot 2024-11-02 at 4 40 35 PM" src="https://github.com/user-attachments/assets/af464d71-a50a-4c8c-a939-77053dc722f6">
<img width="1512" alt="Screenshot 2024-11-02 at 4 44 52 PM" src="https://github.com/user-attachments/assets/d03e9a07-4acb-4f16-9509-6cfb82124ffe">
 list.

2024-11-02 21:32 UTC, sheetalmangate commented
Could not test this PR locally.  after checkout to branch "haoyue-team-code-data" its giving below error while starting a project.

![PR2751_testing_error](https://github.com/user-attachments/assets/8caec602-b4bc-4551-ac00-565bb5f4f2f5)

2024-11-03 00:05 UTC, sheetalmangate submitted a review, later dismissed
Tested this PR locally. its is working as expected so approving it 

![PR2751_testing1](https://github.com/user-attachments/assets/37c8ff56-82ed-49cc-99a1-5dda358fbc2d)

2024-11-05 00:50 UTC, SupriyaSudini requested changes
I have tested this PR and confirmed that the team code has been replaced. However, the edit button is missing in the profile section, and the replaced team code is visible when creating a new title.

![image](https://github.com/user-attachments/assets/a9dde8ee-ed4e-4a96-8bc5-87085b10377f)

![image](https://github.com/user-attachments/assets/60490bc4-90ff-4c7e-8a78-85c342f716ef)

![image](https://github.com/user-attachments/assets/1dca648f-4301-4ee0-b263-fae80de6cd9e)

![image](https://github.com/user-attachments/assets/9cc16437-4d08-42c0-be24-c71b538afabb)

2024-11-08 23:38 UTC, Muhideenthegreat approved these changes
Verification:

- Functionality works as expected, only active team codes are in yellow

<img width="1440" alt="Screenshot 2024-11-08 at 6 34 39 PM" src="https://github.com/user-attachments/assets/e194b201-3078-4af1-9280-7309bf6358d7">
<img width="1440" alt="Screenshot 2024-11-08 at 6 35 38 PM" src="https://github.com/user-attachments/assets/ddbbfecf-33f6-4c6f-82c7-16d66b371642">
<img width="1440" alt="Screenshot 2024-11-08 at 6 36 26 PM" src="https://github.com/user-attachments/assets/835baa48-8701-4a0b-b005-debf38a7fb1d">

2025-01-04 03:51 UTC, oliviahyw commented
> After replacing the team code in weekly summary reports and back to the profile page. The edit button exists but when I want to update the team code, it displays "invalid team code error". Please check more details in my video.
> 
>  bandicam.2024-10-11.23-46-27-568.mp4 
>  bandicam.2024-10-11.23-43-40-636.mp4

Hi @Jingyii800, I’ve tested this issue multiple times but haven’t been able to replicate the bug. Could you please clear your browser cache and double-check if the issue still persists? Let me know if you encounter it again. Thank you!

2025-01-26 01:59 UTC, honglinchen0524 reviewed
The icon turns from yellow to red after modifying the team code in the weekly summary. However, is it normal that I am not able to see myself in the weekly summary page when the icon is yellow?

https://github.com/user-attachments/assets/33f3a48f-a3fd-411e-b523-6b42d0d20e50

2025-02-04 00:12 UTC, AshritaCherlapally reviewed
Hi I have tried test this PR, however when i am trying to submit the updated team code, it is throwing an error and is not letting me to submit further.


https://github.com/user-attachments/assets/4713b3ed-d2c3-4f9e-885e-0914bf553650

2025-02-17 02:35 UTC, oliviahyw commented
> Hi I have tried test this PR, however when i am trying to submit the updated team code, it is throwing an error and is not letting me to submit further.
> 
>  Screen.Recording.2025-02-03.at.5.10.12.PM.mov

Please pull the latest code from backend branch and test it again. Thanks.

2025-02-17 02:36 UTC, oliviahyw commented
> I have tested this PR and confirmed that the team code has been replaced. However, the edit button is missing in the profile section, and the replaced team code is visible when creating a new title.
> 
> ![image](https://private-user-images.githubusercontent.com/95210394/382966628-a9dde8ee-ed4e-4a96-8bc5-87085b10377f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk3NTk4NzAsIm5iZiI6MTczOTc1OTU3MCwicGF0aCI6Ii85NTIxMDM5NC8zODI5NjY2MjgtYTlkZGU4ZWUtZWQ0ZS00YTk2LThiYzUtODcwODViMTAzNzdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE3VDAyMzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMWNjMTVmZDk0ZDRjMGFkMTQ1ZGNmZDgzNDViOTRmMzUwNGY1YzU5ODdhZjdjNjY2MmUwNjdhZjZmYzgzY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QAGaJYp1Bflg_o5VyuxpJrvUWjMnvgis8axzX37McDs)
> 
> ![image](https://private-user-images.githubusercontent.com/95210394/382966652-60490bc4-90ff-4c7e-8a78-85c342f716ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk3NTk4NzAsIm5iZiI6MTczOTc1OTU3MCwicGF0aCI6Ii85NTIxMDM5NC8zODI5NjY2NTItNjA0OTBiYzQtOTBmZi00YzdlLThhNzgtODVjMzQyZjcxNmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE3VDAyMzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYzFlNDMxMjAwNjUxZDRmM2U4Njk5MDRkMDY1YjY4MzUzZDlhOTVmY2QwOGFlYjUxMWMzOGE3NGY3NTc3NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PtDt3P7_llwatIk5ZmA-nlYjpmSoW3J00cVShD5oVgA)
> 
> ![image](https://private-user-images.githubusercontent.com/95210394/382966681-1dca648f-4301-4ee0-b263-fae80de6cd9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk3NTk4NzAsIm5iZiI6MTczOTc1OTU3MCwicGF0aCI6Ii85NTIxMDM5NC8zODI5NjY2ODEtMWRjYTY0OGYtNDMwMS00ZWUwLWIyNjMtZmFlODBkZTZjZDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE3VDAyMzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYTBiMmY5Y2EzMGE5MzQyNTc1NWQ0YjY5NjU2NjBhYTQ0ODM5NTMzZjA0ZjRiZmNjZmIzZGQyZTQ1ODEzYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OY7Fweb0NtoT2FvzcBh34bKvQfJhCSS-UHOh6ZXI0ks)
> 
> ![image](https://private-user-images.githubusercontent.com/95210394/382966732-9cc16437-4d08-42c0-be24-c71b538afabb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk3NTk4NzAsIm5iZiI6MTczOTc1OTU3MCwicGF0aCI6Ii85NTIxMDM5NC8zODI5NjY3MzItOWNjMTY0MzctNGQwOC00MmMwLWJlMjQtYzcxYjUzOGFmYWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE3VDAyMzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZmQzM2YzMGNkZTc0ZjY3OWY2MmNhZTYwYjgyNzJmNmZlYjEwZTE4ZmM5Nzg2YWFhOTc3NTJjZGNjZjk2NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pRcViTrNsJ_WE9qTBzzYDuFzBMQkIIFJzqSvJlJbXVM)

Please pull the latest code from backend branch and test it again. Thanks.

2025-02-20 14:20 UTC, AshritaCherlapally commented
@oliviahyw I have pulled the latest code and tested this PR, it is now working as expected. Changed the team code from ABABA to Ababa. The team code is updated successfully, the functionality is working as expected. Great Job!


https://github.com/user-attachments/assets/0bcf9037-d474-4618-8a07-2616a05d0712

2025-02-20 16:30 UTC, AshritaCherlapally approved these changes

2025-02-21 00:48 UTC, one-community commented
Thank you all, merging!

2025-02-21 00:48 UTC, merged