Add title with info icon to Teams page
OneCommunityGlobal/HighestGoodNetworkApp pull request #2760
Opened 2024-10-06 08:46 UTC by deepthikannan

# Description
![image](https://github.com/user-attachments/assets/e4c3eddc-770d-4ee4-bee0-5c4484dbda16)

…

## Main changes explained:
- Updated Teams page JSX: Added the Teams title and an EditableInfoModal with the info icon next to it.
- Updated Teams page CSS: Commented out the background: gray; rule in the .teams__overview--top class to remove the grey background affecting the Total Teams and Active Teams buttons for a cleaner layout.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ other links→ teams→…
6. verify The Teams title and the info icon are displayed correctly

## Screenshots or videos of changes:
![image](https://github.com/user-attachments/assets/3a79ee92-786c-4726-b189-a37f78c8d917)

2024-10-08 05:24 UTC, shivansh-nathani commented
I can see the teams title added and have check for responsiveness of the page and it works as expected.
<img width="764" alt="Screenshot 2024-10-07 at 9 39 20 PM" src="https://github.com/user-attachments/assets/af6d6e28-39b9-4a04-a669-8e7b335a3553">

I had a quick question regarding the contents of the modal that pops up after clicking the i icon (Should it display the text as shown in image below or do we need to update that?)

<img width="917" alt="Screenshot 2024-10-07 at 9 42 16 PM" src="https://github.com/user-attachments/assets/a27ed765-f861-44a2-a67b-6e71687342ca">

2024-10-08 05:26 UTC, shivansh-nathani commented
I have checked the PR and the title is present and I have also checked the website for responsiveness and it is working as expected.
<img width="764" alt="Screenshot 2024-10-07 at 9 39 20 PM" src="https://github.com/user-attachments/assets/7bb6566a-cf41-45c5-8774-7b5bb0626dda">
I have a question regarding the modal contents when which opens up when i is clicked - should the content remain as shown in the image below or is it to be updated?
<img width="917" alt="Screenshot 2024-10-07 at 9 42 16 PM" src="https://github.com/user-attachments/assets/157d6789-fc4a-4f4d-a219-e54de725623a">

2024-10-08 05:35 UTC, shivansh-nathani requested changes
I have checked the changes and I am able to view the Teams title and I have also check for responsiveness and things look good.
<img width="764" alt="Screenshot 2024-10-07 at 9 39 20 PM" src="https://github.com/user-attachments/assets/5aa9013e-9afc-4698-91e7-8a4cf31c0925">
I have a question on contents of the modal when i is clicked - do we also need to update it?
<img width="917" alt="Screenshot 2024-10-07 at 9 42 16 PM" src="https://github.com/user-attachments/assets/25a6a5e3-4bfe-4212-8d73-d2fd81949de8">

2024-10-09 15:35 UTC, Ankuriboh commented
Works as described, UI and edit announcement functionalities also work.

2024-10-09 15:35 UTC, Ankuriboh approved these changes
Please ignore this approval, see below:

2024-10-09 15:53 UTC, Ankuriboh requested changes
UI and edit announcement functionalities work after fixing the problem in role props.

As also mentioned by @shivansh-nathani, there wasn't any button on the modal to indicate the message content could be edited or updated. I only knew that it was editable 
It would be better if we add an explicit button below the modal to show that it is actually editable. That's out of scope for this PR but fixing it could definitely a huge plus.

2024-10-09 15:53 UTC, Ankuriboh commented on src/components/Teams/Teams.jsx
> +                  role={this.props.state.userProfile.role}
Should be `this.props.state?.auth?.user?.role`.

2024-10-10 20:50 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/f2e8fbf8-7bd6-4e00-a4e8-c325f78237a9

2024-10-11 21:15 UTC, tharunaa-1 commented
The message pops up as expected!

![image](https://github.com/user-attachments/assets/2293b3ac-e532-4c13-bf33-af789d04c25a)

2024-10-12 01:01 UTC, slidracoon72 approved these changes
#2760 
@deepthikannan 
I have verified that the "Teams" title is displayed along with the "i" icon in both light and dark mode.

![PR 2760 1](https://github.com/user-attachments/assets/ccdc7c6b-6dd2-4040-affe-88c473710fc3)
![PR 2760 2](https://github.com/user-attachments/assets/24b9820b-6cec-4566-a04c-587efcdf6734)

2024-10-12 21:14 UTC, ishangoel17 reviewed
Verified the PR and the changes are working as expected. Below is the screenshot for reference:
![Capture2760](https://github.com/user-attachments/assets/4566cd35-f9ce-41bb-9abb-9896fe7af79f)

2024-10-16 19:59 UTC, aaryaneil submitted a review, later dismissed
Tested the PR and the teams i icon works as expected for both light and dark mode.

https://github.com/user-attachments/assets/93fca159-df1b-4c0e-9f6b-29787845689c

2024-10-24 22:22 UTC, CodewithKoushica requested changes
The changes in this PR generally work well, and the new "Teams" title and info icon are displayed correctly. However, I noticed an issue on the smaller screen size. The buttons near this section become partially hidden which affects usability.

Suggestion: Please adjust the layout for smaller screen sizes (like iPhone 12) to ensure that all elements, including the buttons, remain visible and accessible. Other than that, everything looks good!

<img width="1186" alt="Screenshot 2024-10-24 at 5 18 55 PM" src="https://github.com/user-attachments/assets/4466c50c-07c0-49bf-871c-1dbbef007bd3">

2024-10-25 19:14 UTC, Muhideenthegreat requested changes
Validation:

I confirm that the header was added to the page, with an info icon. 

Suggested Improvements:

- The search functionality can be standardized into a single, clear input field
- The page can be made more responsive, as it seems cramped on mobile devices
- The use of a clear color hierarchy for action buttons might be beneficial

<img width="1440" alt="Screenshot 2024-10-25 at 3 03 25 PM" src="https://github.com/user-attachments/assets/98a23e0b-7505-44ce-aba8-208379bb585a">
<img width="1440" alt="Screenshot 2024-10-25 at 3 03 39 PM" src="https://github.com/user-attachments/assets/7c4054b3-abed-4f09-bf02-8aecd7c67dab">
<img width="889" alt="Screenshot 2024-10-25 at 3 04 49 PM" src="https://github.com/user-attachments/assets/346be845-0261-4beb-8476-1dcf9e9046a4">

2024-10-26 19:20 UTC, SharadhaS24 approved these changes
Tested the PR and verified that the team names are displayed correctly along with the team icon.

<img width="468" alt="image" src="https://github.com/user-attachments/assets/732ec190-55c5-4543-a4ec-90f83467490d">
<img width="468" alt="image" src="https://github.com/user-attachments/assets/88a5c248-9e74-41fb-b90c-d92d19c410bd">

2024-11-02 00:35 UTC, samarth9201 approved these changes
LGTM!
![Screenshot 2024-11-01 173451](https://github.com/user-attachments/assets/ad59bc88-1f89-486f-8d28-b28371d9bca5)
![Screenshot 2024-11-01 173458](https://github.com/user-attachments/assets/9e3ab8df-314f-4d0a-bd65-c3cdf01f6f24)

2024-11-03 00:00 UTC, ajitp4292 approved these changes
Icon Works as expected
<img width="763" alt="Screenshot 2024-11-02 at 7 59 52 PM" src="https://github.com/user-attachments/assets/ddfaf738-1695-4667-9bc7-99984640c8ab">

2024-11-06 06:48 UTC, deepthikannan commented
Hi @Muhideenthegreat @shivansh-nathani @CodewithKoushica , the requested changes have been made.
The changes related to the information in the i icon, the option of editing the information is only accessible in the owner account which will be later reflected in the admin and other accounts. Kindly please verify by making any test changes. 

The changes related to the responsiveness of the page is fixed as separate PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2838 kindly please refer and verify

2024-11-06 21:13 UTC, hqzhu0913 approved these changes
The team icon works as expected.
<img width="1552" alt="Screenshot 2024-11-06 at 1 11 34 PM" src="https://github.com/user-attachments/assets/279dc2ce-ba8d-4b13-985a-55614da4ee7d">

2024-11-06 23:52 UTC, CodewithKoushica approved these changes
Page responsiveness remains unchanged, but I’m looking forward to seeing improvements in the new PR [#2838](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2838). Other than that, everything else is working well for me.
<img width="1440" alt="Screenshot 2024-11-06 at 5 51 56 PM" src="https://github.com/user-attachments/assets/d98492b0-4647-432e-86d6-b11ee63a5c45">

2024-11-15 04:32 UTC, merged