code committed after fixing the project report formatting of member t…
OneCommunityGlobal/HighestGoodNetworkApp pull request #2782
Opened 2024-10-12 11:39 UTC by nikhilgiri0226

…ables

# Description
Fixed Project Report formatting of members.
The column names were not aligned with the listed data
Fixes # (medium)

## Related PRS (if any):
This frontend PR is not related to any specific backend PR.
…

## Main changes explained:
Update file HighestGoodNetworkApp\src\components\Reports\ProjectMemberTable\ProjectMemberTable.css
Changed the CSS attributes to properly align the table headers with the columns in different screen sizes.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. Reports → Reports → Projects → Choose Project
6. The column names should be aligned with the listed data.
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

Issue

https://github.com/user-attachments/assets/1eb0d5c3-4c5c-43cc-8830-0fb9bc9fd420

Fix
https://github.com/user-attachments/assets/a0d7d82f-930a-41d1-893e-137a129f25ff

2024-10-12 22:27 UTC, anirudhsk2107 reviewed
There is no proper alignment  in the members table

<img width="1170" alt="Screen Shot 2024-10-12 at 6 27 27 PM" src="https://github.com/user-attachments/assets/15ae08a9-4bb6-4a1c-b407-c4e2633d26a0">

2024-10-13 11:09 UTC, aaryaneil approved these changes
Tested the PR and the Active ID is properly aligned.
<img width="1440" alt="Screenshot 2024-10-13 at 4 08 51 AM" src="https://github.com/user-attachments/assets/c180ba4e-aee5-490f-9a7b-6dbdff82257c">

2024-10-14 21:28 UTC, AshishNags approved these changes
Approving this PR, the column name and its data are aligned properly.

![Screenshot 2024-10-14 162515](https://github.com/user-attachments/assets/9d86c340-a320-4b8e-af27-8f41a12928e1)

2024-10-15 02:51 UTC, lucy-xfl approved these changes
![image](https://github.com/user-attachments/assets/4c3fd991-5970-4e8c-8009-043acfcb9933)
Works well in different kind of window size.

2024-10-15 14:16 UTC, Ankuriboh requested changes
Simple CSS fix for the element, but why don't we just use actual `tr` element for the table?

2024-10-16 02:17 UTC, ShreyaLaheri commented
Hi, I have tested the PR in dark mode and light mode - the column names didn't show up aligned on my screen
![image](https://github.com/user-attachments/assets/e3f9b176-7533-4831-9069-ecb2dffb31e8)
![image](https://github.com/user-attachments/assets/b9b04f4b-7798-4711-987d-7f98764faf53)

2024-10-16 19:35 UTC, SharadhaS24 approved these changes
Tested the PR on various responsive web pages, and the columns are properly aligned with the data in the table.

<img width="468" alt="image" src="https://github.com/user-attachments/assets/15cb4f7d-3610-4d6a-93c5-e826b9a8cd91">

<img width="468" alt="image" src="https://github.com/user-attachments/assets/0bfbb111-270c-4f79-ae02-7a1bb492778c">

The columns in the table are perfectly aligned, including in dark mode.

<img width="468" alt="image" src="https://github.com/user-attachments/assets/2b19a8b7-dde4-4794-a840-6b5357b412ca">

2024-10-16 23:33 UTC, NK3101 approved these changes
I have tested the PR in both dark mode and light mode, the columns and names are aligned properly. I also verified the alignment while resizing the screen, and everything remains properly aligned.
<img width="1447" alt="Screenshot 2024-10-16 at 6 55 35 PM" src="https://github.com/user-attachments/assets/1867dabe-4daf-4025-88b0-b4e5a84fb8d9">
<img width="1400" alt="Screenshot 2024-10-16 at 7 20 16 PM" src="https://github.com/user-attachments/assets/b5cd1c91-29f8-4708-afcf-ff20452688a7">

2024-10-17 19:17 UTC, Anoushka21 commented
Tested out with different screen sizes- column names and data is aligned.
![size1](https://github.com/user-attachments/assets/ce7337e9-89e5-472f-b7bf-5f5703ceda94)
![size2](https://github.com/user-attachments/assets/61831b7d-9c56-4b6c-a489-f9d60b608ecd)
![size3](https://github.com/user-attachments/assets/c7585213-a948-4ce5-8b2d-5538d2ae98ff)
![size5](https://github.com/user-attachments/assets/0deb7379-d014-4f1d-8989-e2aff507e50c)
](https://github.com/user-attachments/assets/afb7c781-1517-40f8-a435-01a3c98eb9d8)

2024-10-17 19:18 UTC, Anoushka21 approved these changes

2024-10-17 23:27 UTC, pallavithorat commented
I reviewed the PR in both dark and light modes, ensuring that the columns and names are accurately aligned. Additionally, I tested the layout by resizing the screen, verifying that the alignment remains consistent and properly adjusted throughout

<img width="1470" alt="Screenshot 2024-10-17 at 4 18 10 PM" src="https://github.com/user-attachments/assets/b08ead9a-511e-4b10-8db3-4acb35e5c7f6">
<img width="609" alt="Screenshot 2024-10-17 at 4 21 07 PM" src="https://github.com/user-attachments/assets/3d695eaf-e597-4c59-b048-a1546c079b21">
<img width="602" alt="Screenshot 2024-10-17 at 4 21 46 PM" src="https://github.com/user-attachments/assets/50a97f67-e249-4288-8e5f-81210dc860d3">
<img width="1461" alt="Screenshot 2024-10-17 at 4 24 32 PM" src="https://github.com/user-attachments/assets/4a30b216-eba4-4744-a9e0-9e1716ad70e3">

2024-10-18 02:55 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/e6732805-1cbb-4748-8bc5-4944d424c1e2

2024-10-18 04:24 UTC, lng2020 approved these changes
![Screenshot_20241017_232447](https://github.com/user-attachments/assets/fcd3e065-2f78-488e-8bb5-fc7e370c641f)
LGTM

2024-10-18 21:37 UTC, shashankhv approved these changes
Tested the fix thoroughly and recorded a video demonstrating the results. Verified that the changes work correctly in both light and dark modes, as well as across responsive screen sizes. Everything is functioning as expected without issues. Approving the PR. 

[Nikhil-fix-PR.webm](https://github.com/user-attachments/assets/19698e9a-e287-455f-84d5-44015565efda)

2024-10-18 23:39 UTC, VMD281 commented
Hi, I reviewed this PR and the alignment looks good! I have pasted the screenshots below:
<img width="1229" alt="PR#2782_1" src="https://github.com/user-attachments/assets/5e626092-0a7f-490d-83bf-cfe9fe253d49">
<img width="1229" alt="PR#2782_2" src="https://github.com/user-attachments/assets/6e53e9cd-5dfc-4c54-954a-28413eef4cb2">

2024-10-19 02:34 UTC, Jingyii800 approved these changes
I have tested this feature, now the name of columns and columns are aligned well.
![image](https://github.com/user-attachments/assets/174f24f5-45f5-466a-a381-0ae94ec2a411)

2024-10-19 02:40 UTC, javid679 commented
Hi, 
I reviewed this PR and the alignment looks good! I have pasted the screenshots below:

![Screenshot (48)](https://github.com/user-attachments/assets/9ee5ad63-2a1f-40a2-be21-cc0d7989fdab)

2024-10-19 03:38 UTC, zhiminV approved these changes
I have reviewed the feature in dark mode,  and column names  aligned with the listed data.
<img width="1284" alt="Screenshot 2024-10-18 at 8 37 03 PM" src="https://github.com/user-attachments/assets/34d1ac2f-b14a-495e-821b-8d2abe1d4e18">

2024-10-19 08:43 UTC, javid679 approved these changes
Hi, 
I reviewed this PR and the alignment looks good! I have pasted the screenshots below:

![Screenshot (48)](https://github.com/user-attachments/assets/9ee5ad63-2a1f-40a2-be21-cc0d7989fdab)

2024-10-19 20:28 UTC, bhavya17prakash approved these changes
Verified the column names are aligned with the listed data.
<img width="882" alt="PR 2782" src="https://github.com/user-attachments/assets/e8d48467-28b3-41ca-b7f6-2eb2d4e9d4c8">

2024-10-20 06:02 UTC, Rupa2400 reviewed
Hi, I have tested the PR - the formatting does not appear to be correctly fixed, as the headers and data columns are still misaligned.

<img width="900" alt="format_table_3" src="https://github.com/user-attachments/assets/641e212f-f4bf-4354-a83b-c178d8700263">
<img width="907" alt="format_table_2" src="https://github.com/user-attachments/assets/4976e0f2-8380-4401-b536-d57e4d51faec">
<img width="898" alt="format_table" src="https://github.com/user-attachments/assets/b33c8ab5-f17f-4c39-839c-463d18aca7e9">

2024-10-21 03:33 UTC, one-community commented
Thank you all, merging!

2024-10-21 03:33 UTC, merged