Swathi Fix resources dot centering on Tasks pages
OneCommunityGlobal/HighestGoodNetworkApp pull request #2789
Opened 2024-10-16 04:51 UTC by Lemonnycodes

# Description
This PR addresses the issue of misaligned initials inside resource dots and improves the layout when there are multiple resources in the task table. The initials inside the resource circles are now correctly centered both vertically and horizontally.

## Related PRS (if any):
This frontend PR is related to the development backend PR.

## Main changes explained:
- Updated the CSS file to center the initials in the resource dots using display: flex, justify-content: center, and align-items: center.
- Applied text-align: center and vertical-align: middle to table cells to align text and icons centrally.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Other Links>Projects>Click WBS Icon>Choose WBS>Edit
6. Verify that the initials in resource circles are properly centered.
7. Add multiple resources (5 or more) to a task and verify that they display correctly without overlap and can be horizontally scrolled if necessary.
8. Verify this feature works in dark mode

## Screenshots or videos of changes:
Before : 
![image](https://github.com/user-attachments/assets/6ca5a78d-ef06-44c1-b918-1b62e475d1b0)
After : 
![full view](https://github.com/user-attachments/assets/3bce69a6-377c-4711-8679-c946732b8058)
![10+ resources](https://github.com/user-attachments/assets/88674779-b883-4000-8491-7e2d903b0a15)

2024-10-16 08:27 UTC, lucy-xfl approved these changes
flex works well in dark and light mode.
![WeChatdc4e596b417774654a777a7d030b4fa9](https://github.com/user-attachments/a
![WeChat95d61072b6e4cb3817071a0d28925b85](https://github.com/user-attachments/assets/84bf6ee4-5a1e-42a6-a5e3-303433456635)
ssets/dee352cd-a9e0-432d-ba64-61e2b315ede4)

2024-10-18 03:21 UTC, nikhilpittala16 submitted a review, later dismissed
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/e3fe6a21-37f2-44ba-a720-477f2876723a

2024-10-18 06:31 UTC, SharadhaS24 submitted a review, later dismissed
Validated the addition of multiple resource types (1, 5, or more) in both light and dark modes, ensuring consistent performance and correct functionality. Its centered and aligned properly.

<img width="468" alt="image" src="https://github.com/user-attachments/assets/92e59175-b2b5-41ef-8129-1664a3460a95">

<img width="468" alt="image" src="https://github.com/user-attachments/assets/80b1a5cd-cab8-41d3-802e-19f8c376eb8e">

<img width="468" alt="image" src="https://github.com/user-attachments/assets/35e5b0d2-3536-4b4e-8db5-360557700024">

2024-10-18 08:25 UTC, Anoushka21 commented
Tested in both modes. Aligned and working well.

https://github.com/user-attachments/assets/792c0971-52fe-402a-90d7-3b3e3b675df8

2024-10-18 08:25 UTC, Anoushka21 approved these changes

2024-10-18 21:09 UTC, pallavithorat commented
I have verified the PR by ensuring that the initials in the resource circles are properly centered, and multiple resources display correctly with horizontal scrolling, without overlap. The feature also works seamlessly in dark mode.
<img width="1470" alt="PR#2789" src="https://github.com/user-attachments/assets/1159f714-ccd8-4189-ad3e-c2b81c50fcb3">

2024-10-19 00:17 UTC, NK3101 approved these changes
Tested the PR in both light and dark modes. Working as expected.

<img width="1470" alt="#2789" src="https://github.com/user-attachments/assets/eeab21ef-00bd-4fab-9371-d5f83b46157e">
<img width="1470" alt="#2789-2" src="https://github.com/user-attachments/assets/6a9a43b6-7a6f-45cd-a7d7-d0bd32ce37f5">

2024-10-19 04:22 UTC, shashankhv approved these changes
Verified initials centering, resource display, and tested in dark mode. Works as expected.
[swathi-PR.webm](https://github.com/user-attachments/assets/a3fa334a-a236-42cb-acb4-93badbd479ef)

2024-10-23 22:49 UTC, CodewithKoushica requested changes
The changes in this PR work well, and the initials in the resource dots are correctly centered. However, I noticed that the UI makes a noticeable jump when expanding and collapsing the resource section. It would improve the user experience if this transition could be made smoother, possibly by adding a CSS transition effect. Other than that, the fix looks great!


https://github.com/user-attachments/assets/28a3c155-2a2a-436d-bbe6-7e817b263db2

2024-10-26 05:51 UTC, nikhilgiri0226 approved these changes
I have tested the PR. Everything works as expected. The resources icons with initials were aligned properly inside the column horizontally. I have tested it in different screen sizes.


https://github.com/user-attachments/assets/f24c12f7-c0ba-4939-bd26-2d16b9b0c92b

2024-10-26 06:28 UTC, zhiminV submitted a review, later dismissed
I have tested that the initials in resource circles are properly centered.
and 5 or more resources display correctly without overlap and can be horizontally. And I also verify this feature works in dark mode.
<img width="1157" alt="Screenshot 2024-10-25 at 11 25 35 PM" src="https://github.com/user-attachments/assets/21f6a24c-dfa1-4a61-a544-40632ea6405d">
<img width="1322" alt="Screenshot 2024-10-25 at 11 20 19 PM" src="https://github.com/user-attachments/assets/1e777f22-9378-4622-b96a-072fd9ba1159">

<img width="1157" alt="Screenshot 2024-10-25 at 11 26 16 PM" src="https://github.com/user-attachments/assets/fac3b115-7182-443c-9658-4557671f3738">

2024-10-26 10:10 UTC, Anoushka21 approved these changes

2024-10-26 18:46 UTC, varun-elango submitted a review, later dismissed
The code changes look good and the functionality is working as expected. The initials are properly centered and multiple resources are displayed correctly without any overlap. Verified in dark mode as well.
![PR2789_1](https://github.com/user-attachments/assets/855fe94f-b18c-4ad7-87fe-d7c369410d8e)
![PR2789_2](https://github.com/user-attachments/assets/53310f07-579f-4d8f-b42c-3c16b73a0257)
![PR2789_3](https://github.com/user-attachments/assets/83940c9d-9465-48da-935e-7981adb9370f)

2024-10-26 18:50 UTC, bhavya17prakash approved these changes
Working as intended in dark mode as well
<img width="716" alt="PR 2789" src="https://github.com/user-attachments/assets/908566f3-136a-4bc8-b903-b60c230be8bb">

2024-10-26 20:55 UTC, Rupa2400 approved these changes
Tested the PR in both light and dark modes. The PR is working as expected.

<img width="959" alt="PR_2789_1" src="https://github.com/user-attachments/assets/8d95c738-2c5e-4a01-a9ea-0f59d34b7421">

<img width="959" alt="PR_2789_2" src="https://github.com/user-attachments/assets/b0b13366-5c99-4d1d-8e7a-ecf3023746e8">

<img width="959" alt="PR_2789_3" src="https://github.com/user-attachments/assets/c4947399-ec96-43b7-85bc-69dca626d394">

2024-10-26 22:33 UTC, sheetalmangate commented on src/components/Projects/WBS/WBSDetail/wbs.css
> +  vertical-align: middle; /* Centers the text vertically */
Comments for CSS classes are not required. they are self explanatory

2024-10-26 22:39 UTC, sheetalmangate commented
CSS changes working as per requirement stated. UI changes looks good, just having small suggestion
1)  comments for CSS classes are not required they are self explanatory.

Approving this PR

![PR2789_testing](https://github.com/user-attachments/assets/6c4a2c99-d6f4-4620-bf52-0d61d63c50f7)

2024-10-26 22:42 UTC, sheetalmangate approved these changes

2024-10-26 22:43 UTC, sheetalmangate submitted a review, later dismissed

2024-10-30 00:18 UTC, samarth9201 submitted a review, later dismissed
Reviewed the PR Working as expected.
![image](https://github.com/user-attachments/assets/cdc913b8-fe4a-4ade-93a2-b94d80f9ac82)

2024-10-30 02:40 UTC, anirudhsk2107 submitted a review, later dismissed
Changes are working in light mode and dark mode

![Screen Shot 2024-10-29 at 10 36 55 PM](https://github.com/user-attachments/assets/ce541933-cf5f-4266-9399-b0d07c4c7255)
![Screen Shot 2024-10-29 at 10 36 47 PM](https://github.com/user-attachments/assets/bb54beb2-6296-42e5-a762-af2de8121b8d)

2024-10-31 07:14 UTC, Rui-Liu-github approved these changes
I reviewed PR #2789 by pulling the latest version from Swathi. The fixed CSS styling works as expected, with the resources dot positioned at the center.

![image](https://github.com/user-attachments/assets/1bcc7adc-8fc5-4609-bb0a-7d255bdecc71)
![image](https://github.com/user-attachments/assets/370dcb08-d94b-4bf4-a068-cebb2483e2fb)

2024-11-01 01:46 UTC, SupriyaSudini approved these changes
I have verified that the initials in the resource circles are properly centered and tested adding multiple resources (5 or more) to a task to ensure they display correctly without overlap, with horizontal scrolling available when needed.

![image](https://github.com/user-attachments/assets/0f0396d0-2378-41e1-a737-1b8eed60d131)

![image](https://github.com/user-attachments/assets/f6e4c5aa-9f74-4c98-b57b-e88ec9f4e6a7)

![image](https://github.com/user-attachments/assets/cb3d2ec3-ee78-4883-8d0f-0b3f066fdffa)

2024-11-02 16:09 UTC, AshritaCherlapally approved these changes
This code is working as expected, when creating task with adding resources, the resources are aligned on center as expected

https://github.com/user-attachments/assets/8163e20e-655a-4580-bec0-daaad8d49ac8

2024-11-03 02:21 UTC, audreydieuanh submitted a review, later dismissed
It works correctly both in light and dark mode and with 5+ resources.
<img width="1512" alt="Screenshot 2024-11-02 at 9 17 55 PM" src="https://github.com/user-attachments/assets/acb8eab4-584d-4366-b01e-1e8d6c867354">
<img width="1512" alt="Screenshot 2024-11-02 at 9 18 03 PM" src="https://github.com/user-attachments/assets/eca512df-c9fa-45c5-a013-393a889aef88">

2024-11-05 21:39 UTC, hqzhu0913 reviewed
The resources tags center as expected. 
But I find a problem with limited resources selections. I am not sure if I didn't test it correctly. But these are not problem of your UI change. Comment me if you see the problem as well.
<img width="1552" alt="Screenshot 2024-11-05 at 1 31 37 PM" src="https://github.com/user-attachments/assets/8b05d845-346c-47d8-9a51-74bee9e6ff25">


<img width="1552" alt="Screenshot 2024-11-05 at 1 31 05 PM" src="https://github.com/user-attachments/assets/36709691-58e6-4b38-a3bd-c5b9096c5cff">

2024-11-07 19:10 UTC, humera314 commented
I ran the tests on this feature, and it’s working perfectly across all specified conditions, including dark mode.
![image](https://github.com/user-attachments/assets/c33c92d6-5b53-45c1-8d5c-0b70f585f4b6)
![image](https://github.com/user-attachments/assets/d86b3a75-ab79-4601-839b-c1c34698dd16)

2024-11-24 05:13 UTC, SS-Reddys approved these changes
Changes are working as expected

![image](https://github.com/user-attachments/assets/3b3d04a3-73c8-475b-b38a-3cff9fbee1e7)

![image](https://github.com/user-attachments/assets/45648ad1-b1b7-411f-b794-832bad3a5986)

2024-11-27 00:49 UTC, one-community commented
Thank you all, merging!

2024-11-27 00:49 UTC, merged