Ambika fix reports teams calendar cropping issue
OneCommunityGlobal/HighestGoodNetworkApp pull request #2796
Opened 2024-10-17 00:52 UTC by kabraambika

# Description
![image](https://github.com/user-attachments/assets/65b16303-bc01-4a43-a920-de1b1d0d9e64)

Fixes # (bug list priority low)

## Related PRS (if any):
To test this frontend PR you need to checkout the development branch of backend.

## Main changes explained:
- Update ReportBlock.css file by removing overflow hidden from wrapper class

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Reports→ Reports→Teams->choose any team name -> scroll at the bottom
6. verify that the calendars for 'Created After' and 'Modified After' appear not to be cropped
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:
After implementation:
![image](https://github.com/user-attachments/assets/40672543-52d4-47e7-9140-4db2b97f2821)
![image](https://github.com/user-attachments/assets/7b2fec78-ca40-4a64-a837-2dcf10a8d6e8)

## Note:

The list of members is not visible in this section because PR #2468 includes a comment that disables the code responsible for displaying the members list.

2024-10-17 07:06 UTC, shivansh-nathani submitted a review, later dismissed
I have tested the changes and the date picker is not hidden and is visible as expected.
<img width="1432" alt="Screenshot 2024-10-17 at 12 05 20 AM" src="https://github.com/user-attachments/assets/32eab3bd-42fb-4ac9-bdc5-e1487607b14c">
<img width="1427" alt="Screenshot 2024-10-17 at 12 05 33 AM" src="https://github.com/user-attachments/assets/bba772f4-4626-4daf-83b3-507055a22637">

2024-10-17 19:00 UTC, shashankhv submitted a review, later dismissed
Tested the removal of overflow: hidden from .report-block-wrapper and .report-block-wrapper-dark, and confirmed it resolves the layout issue without causing any visual or functional side effects. Verified on multiple browsers and all content remains within bounds as expected. Looks good to approve!


![HGN APP · 1 25pm · 10-17](https://github.com/user-attachments/assets/fb31afc4-de58-48a8-9226-0eaf34f8b0c6)


![HGN APP](https://github.com/user-attachments/assets/3048dd55-f918-467a-a555-e89749a836f3)

2024-10-18 02:19 UTC, nikhilpittala16 submitted a review, later dismissed
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/c70dacf6-f639-4d5e-a33a-ef9a0b58318f

2024-10-18 04:35 UTC, Anoushka21 submitted a review, later dismissed
Tested in light and dark mode. Everything looks good!
![Screenshot 2024-10-17 213405](https://github.com/user-attachments/assets/c94a8bb9-ef60-48e4-8ec0-bb9c91ec9cd7)
![Screenshot 2024-10-17 213325](https://github.com/user-attachments/assets/ddf79954-1c79-4c5c-a883-aebdef4dac28)

2024-10-18 04:50 UTC, lng2020 submitted a review, later dismissed

2024-10-18 05:31 UTC, lucy-xfl submitted a review, later dismissed
![WeChat7979e1d9336c7ebd67e14ec51e14231f](https://github.com/user-attachments/assets/68cac97b-12f1-4373-bd05-d8cb05c21b9c)
Seems a little strange in dark mode

2024-10-18 06:51 UTC, SharadhaS24 requested changes
The calendar dates from my end still appears to be cropped in both light and dark mode.

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/290fe0a0-53f2-4ae8-9c44-f34194b4d53a">

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/16cc050e-69de-4d8d-926e-f95497ab15d6">

2024-10-18 23:27 UTC, NK3101 submitted a review, later dismissed
Tested the PR, everything works as expected.
<img width="1227" alt="#2796-2" src="https://github.com/user-attachments/assets/428f53de-70d8-4db9-a4ed-4908f3564bf8">
<img width="1227" alt="#2796" src="https://github.com/user-attachments/assets/62f53aa0-cb8b-472f-bd57-9fb45a9f8e99">

2024-10-19 02:31 UTC, Jingyii800 submitted a review, later dismissed
I have tested this feature, it works well. Now the calendar in "created after" and "modified after" will not be cropped.

![Screenshot 2024-10-18 193022](https://github.com/user-attachments/assets/1fa231c7-2bee-4bd2-9fe8-579dcffd17d9)
![Screenshot 2024-10-18 193019](https://github.com/user-attachments/assets/eec65e96-7d76-4d78-a942-9169dda35822)

2024-10-19 02:53 UTC, javid679 commented
Hi Ambika, I have tested this PR and it is working as intended.

Created after:
![Screenshot (49)](https://github.com/user-attachments/assets/25ea6ce1-d294-44c4-a981-33758d915c95)

Modified After: 
![Screenshot (50)](https://github.com/user-attachments/assets/d845169c-b6f5-474c-81f5-98ba6786b0a7)

2024-10-19 03:26 UTC, zhiminV approved these changes
I have test the feature in dark mode, everything work as expected.
<img width="1198" alt="Screenshot 2024-10-18 at 8 23 00 PM" src="https://github.com/user-attachments/assets/3a7be1fa-64e9-4a4f-a062-cb41eff0d1c3">
<img width="1211" alt="Screenshot 2024-10-18 at 8 23 11 PM" src="https://github.com/user-attachments/assets/09b0cad4-4feb-48ae-9c1f-36bd4fb8f0f4">

2024-10-19 08:42 UTC, javid679 approved these changes
Hi Ambika, I have tested this PR and it is working as intended.

Created after:
![Screenshot (49)](https://github.com/user-attachments/assets/25ea6ce1-d294-44c4-a981-33758d915c95)

Modified After: 
![Screenshot (50)](https://github.com/user-attachments/assets/d845169c-b6f5-474c-81f5-98ba6786b0a7)

2024-10-19 20:20 UTC, bhavya17prakash submitted a review, later dismissed
Verified both in light and dark mode, calendars are not cropped

https://github.com/user-attachments/assets/297d7099-97d3-4ff9-8ac9-3b85fc71eac4

2024-10-20 03:06 UTC, sheetalmangate commented
Code changes are working properly in both mode.

2024-10-20 03:30 UTC, Rupa2400 approved these changes
I've tested the issue. The calendar component displays correctly without clipping and the date picker is fully visible. 

<img width="362" alt="calendar cropping" src="https://github.com/user-attachments/assets/4c7a4157-6f49-4722-8880-d972fa3260a6">
<img width="356" alt="image" src="https://github.com/user-attachments/assets/724dd015-5b74-4644-8323-458b94fcfc5d">

2024-10-20 04:03 UTC, nikhilgiri0226 submitted a review, later dismissed
Tested the PR, and I confirm that the layout of date block for created and modified in both dark and normal mode was properly visible and didn't cropped. Everything works as expected.

<img width="821" alt="Screenshot_2796_Created_Dark" src="https://github.com/user-attachments/assets/0198fbee-2281-40a6-b8ee-c3cdb6e54e0d">
<img width="620" alt="Screenshot_2796_Created_Normal" src="https://github.com/user-attachments/assets/0efe29a4-d056-4f4e-a604-77fcacf3f3ce">
<img width="749" alt="Screenshot_2796_modified_Dark" src="https://github.com/user-attachments/assets/77ba78fa-76e6-48da-8d75-5785f91b2d42">
<img width="752" alt="Screenshot_2796_modified_Normal" src="https://github.com/user-attachments/assets/d523e164-b4b3-4b5a-816d-0a09a0d82acb">

2024-10-20 05:49 UTC, RashmiKY98 commented
Tested the PR with different teams and different browsers. Also, after selecting the date, tried to modify it. The calendar was shown and no issues were found. 

![Screenshot 2024-10-20 004529](https://github.com/user-attachments/assets/96fcc04d-1bfe-4aab-a9ff-2a89603fcd11)
![Screenshot 2024-10-20 004334](https://github.com/user-attachments/assets/ebd3d9e8-69c0-4403-850c-f6c46a2a3de2)

2024-10-20 10:01 UTC, kabraambika commented
Hello @lucy-xfl and @SharadhaS24 , Thanks for sharing the feedback, the screenshot issue mentioned in your comments is fixed now. Can you review the changes now ?

2024-10-21 22:06 UTC, hqzhu0913 approved these changes
I test the function in dark mode, work as expected. No date cropped.
![full2](https://github.com/user-attachments/assets/96fbb7ca-ed39-4afe-9f8a-1bb9a58f37dd)
![full](https://github.com/user-attachments/assets/0d38bb52-cb07-4189-b264-eae56718346d)

2024-10-21 23:58 UTC, samarth9201 commented
Tested this PR. Calendar is not Cropped in Light as well as Dark Mode
![Screenshot (88)](https://github.com/user-attachments/assets/9be171cb-1a42-4cda-a5a7-7d090c5f22db)
![Screenshot (89)](https://github.com/user-attachments/assets/71bf77ce-b63f-46d2-b863-557a2d45eaae)
![Screenshot (90)](https://github.com/user-attachments/assets/5fa15cb4-f45b-4d45-8721-bdcedf27d99a)
![Screenshot (91)](https://github.com/user-attachments/assets/3181b0de-3641-4163-be78-c6b0ac704f03)

2024-10-22 14:31 UTC, CodewithKoushica approved these changes
The fix resolves the cropping issue for the date inputs, and the functionality seems to be working well overall.

However, I encountered a couple of issues during testing:

- The date picker allows selecting past or future dates without restrictions. Please review the logic to ensure only valid date ranges are selectable.
<img width="1440" alt="Screenshot 2024-10-22 at 9 23 03 AM" src="https://github.com/user-attachments/assets/e78a7688-742e-40bd-95ff-969dd36864b5">

- When the screen size is reduced, the UI shifts unexpectedly. It would be helpful to address this to improve the layout's responsiveness.

https://github.com/user-attachments/assets/82314152-7609-4cd7-85de-2617f01b2897

2024-10-22 17:16 UTC, AshishNags approved these changes
Approving this PR, calendar is not cropping, working as expected.
![Screenshot 2024-10-22 121416](https://github.com/user-attachments/assets/9698dc1a-5eb3-4885-9b81-0042b3cae5bc)
![Screenshot 2024-10-22 121427](https://github.com/user-attachments/assets/4a40f603-4d57-48c7-947e-7aa2e5df3b99)

2024-10-23 00:23 UTC, Rui-Liu-github reviewed
Hi, I reviewed PR #2796 @kabraambika. I agree with your update that modifies the ReportBlock.css file by removing overflow hidden from the wrapper class. However, I found a new problem when I refreshed my browser again. This issue disappears when I log out or navigate to another page and then return back. I recorded a screen video for this new problem. 

https://github.com/user-attachments/assets/d3437d32-6ba8-4248-ac23-be3f618804fe

2024-10-23 00:35 UTC, Rui-Liu-github requested changes
I reviewed PR #2796. a problem when I refreshed my browser again. This issue disappears when I log out or navigate to another page and then return back. I uploaded a video on my last comment.

![image](https://github.com/user-attachments/assets/60c9cdad-378e-4d33-b869-abd6290ebd16)

2024-10-23 04:47 UTC, kabraambika commented
Hi @Rui-Liu-github , I have included additional changes in my PR. I would recommend testing the PR by pulling the latest version of this branch, rather than applying manual half changes to your own repository. The issue you mentioned has also been addressed in my PR, so I'm marking your comment as stale.

2024-10-23 05:27 UTC, Rui-Liu-github commented
> the

Hi @kabraambika, Sorry for that, and thank you for your reply! I tested the PR by pulling the latest version just now, and it worked as expected. I made the last comment because the update just deleted the "overflow: hidden" and recently had another 2 people review for the same problem above. I will test using latest version in the future. Thanks again.

2024-10-24 19:21 UTC, slidracoon72 approved these changes
#2796 
@kabraambika 
I've confirmed the calendar isn't cropped in the "Create After" and "Modified After" inputs for both light and dark mode.
![Screenshot 2024-10-24 at 3 15 21 PM](https://github.com/user-attachments/assets/15611d9d-cb09-41a6-96cb-e3e3eb028050)
![Screenshot 2024-10-24 at 3 15 10 PM](https://github.com/user-attachments/assets/ffc72d17-6018-40b6-b988-e5ace6a40eae)

2024-10-26 00:04 UTC, SatyashanthiT commented
I reviewed this pr, focusing on the calendar cropping fix in the Reports section. The changes worked as expected, and the layout displayed correctly in both regular and dark modes.

https://github.com/user-attachments/assets/b6bdce0d-e463-4510-bdfe-46b50d10e157

2024-10-26 19:36 UTC, VMD281 commented
I reviewed this PR, focusing on the calendar cropping fix in the Reports section. It works fine!
<img width="1690" alt="PR#2796_2" src="https://github.com/user-attachments/assets/0da139fd-c239-41db-87a5-0363fa80bdb2">

2024-10-30 22:52 UTC, humera314 commented
I reviewed the PR and tested the calendar component with all specified cases, including desktop view, zoom levels, dark and light mode. The component performs as expected across these scenarios.
Finding
It working perfectly on both dark and light mode but difficult to interact with the full calendar interface on Mobile screens (if its important and not skipping mobile).

![WhatsApp Image 2024-10-30 at 3 47 59 PM](https://github.com/user-attachments/assets/a21cc2cb-cff4-4dba-ac42-f5ce88b36886)

![WhatsApp Image 2024-10-30 at 3 49 04 PM](https://github.com/user-attachments/assets/7444ed9c-c8ce-4fb0-95fa-a31cf7e7bd6c)

![WhatsApp Image 2024-10-30 at 3 49 36 PM](https://github.com/user-attachments/assets/aee1d326-96e9-41a8-bf08-fe3db385a02b)

2024-11-01 00:42 UTC, SupriyaSudini reviewed
I logged in as an admin, opened the reports, selected a team, and tested the "Created After" calendar display. It appears visually correct and functions as expected.

But a suggestion regarding the variation in the height of the calendar.

![image](https://github.com/user-attachments/assets/aae56854-5b6a-4a12-944d-996995b9f04c)

I can see that it is overlapping both the "Created After" headline and the text placeholder above.

![image](https://github.com/user-attachments/assets/d21e8075-c5d7-48bc-a910-3bb9919eeca3)

 
The placeholder is visible here
I notice that the display changes when switching the month in the "Modified After" section.
 
![image](https://github.com/user-attachments/assets/4c010558-b72c-4d08-96bf-c885321f4d2e)

The display is overlapping the "Modified After" heading
 
![image](https://github.com/user-attachments/assets/abb2499b-b00b-429c-9846-bded9ace36a9)

 
The display is currently hiding the "Modified After" heading.
![image](https://github.com/user-attachments/assets/f78b6852-931f-47cf-88be-7c6ae71c8c02)

I suggest making the display constant (without changing the height) regardless of the month. The same applies to "Created After" and "Modified After" sections. Consistently showing or hiding the headings would result in a more visually appealing calendar with fixed width and height.

2024-11-02 16:41 UTC, AshritaCherlapally approved these changes
Changes in the code works as expected. It works well in both light and dark modes.

<img width="1440" alt="PR#2796_1" src="https://github.com/user-attachments/assets/d61b843d-8a04-459c-8f74-1cce3f7840db">
<img width="1440" alt="PR#2796_2" src="https://github.com/user-attachments/assets/02bdc581-8ccd-492d-8b07-ac6e71965106">

2024-11-02 23:56 UTC, anandsesha approved these changes
Tested this PR and the changes work as expected. The date calender is visible and even in the dark mode which was reported earlier. Codebase looks clean. Screenshots attached.
![PR 2796 Calender](https://github.com/user-attachments/assets/3ed27e88-9056-4956-b9f7-0b3e94dcb972)
![PR 2796 Dark mode](https://github.com/user-attachments/assets/bb9cebfc-f895-4c4f-8f1a-097227ce8f93)
![PR 2796](https://github.com/user-attachments/assets/8a10eb37-fe96-4a44-8c65-82ab5803cc90)
![Screenshot (1118)](https://github.com/user-attachments/assets/07be4007-0337-452c-a02d-dcd51dc9aa29)

2024-11-19 06:15 UTC, merged