Snehal fix user id dashboard
OneCommunityGlobal/HighestGoodNetworkApp pull request #2801
Opened 2024-10-18 04:31 UTC by SnelPatare

# Description
Fix user ID workaround bug for dashboard display:
Bug: The Add Time Entry button on the Dashboard displays the wrong user name after viewing another person’s profile.
The Badges section also shows wrong profile data after viewing another person’s profile.

## Related PRS (if any):
To test this frontend PR you need to checkout the development branch in backend.

## Main changes explained:
Changes in Dashboard.jsx file 

## How to test:
Test 1:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as Owner user -> Login into Owner's  Dashboard
5. Leaderboard -> click on red/green circular button of another user -> This will display <another user> viewing dashboard. 
6. Popup to view another user dashboard -> Click in "OK"
7. Check the name on summary bar, Badges and "Add time .." button name.
8. View yellow bar "You are currently viewing header for .. " Click on "X" to exit form the another user viewing dashboard page.
9. Popup to exit the another user view dashboard -> "OK"
10. This will send to current user viewing page. Check the summary name, badges and Yellow button "Add time" name.

Test 2: 
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as Owner user -> Login into Owner's  Dashboard
5. Click on any user from leaders board -> Land to userprofile of selected user (http://localhost:3000/userprofile/<another_userid>)
6. Change the URL to ( http://localhost:3000/dashboard/<another_userid> )
7. Check the name on summary bar, Badges and "Add time .." button name. (Should be another user details)

## Screenshots or videos of changes:
Test 1: 
https://github.com/user-attachments/assets/9c84e392-211f-4615-adce-3669c0faf89e

Test 2:
https://github.com/user-attachments/assets/32f843ca-5690-4541-bc63-16a2e41742ac

2024-10-18 05:18 UTC, lucy-xfl submitted a review, later dismissed
![WeChat7209fbad77ef70cd3545985731acffa4](https://github.com/user-attachments/assets/447b8697-74ff-4344-8e47-8117eee84373)
double function tests passed. We can use double way to check other's dashboard.

2024-10-19 04:13 UTC, CodewithKoushica requested changes
Hello Snehal,
I went through the code and tested the changes in Safari, Google Chrome and Firefox. The changes you mentioned works well for me.

Test verifying video:
https://github.com/user-attachments/assets/7619bd44-5161-4c43-815b-f56779a37a0a

Issue #1:
In Test1, while viewing the activity of other user why does the profile name change ( Welcome, ${original user} -> changes to Welcome, ${name of viewing user}. I believe it has to be the same even while viewing other user's activity.

<img width="1440" alt="Screenshot 2024-10-18 at 11 12 40 PM" src="https://github.com/user-attachments/assets/f878d3cd-5289-499d-a36e-8cffe0860e6a">

2024-10-19 04:57 UTC, SnelPatare commented
> Hello Snehal, I went through the code and tested the changes in Safari, Google Chrome and Firefox. The changes you mentioned works well for me.
> 
> Test verifying video: https://github.com/user-attachments/assets/7619bd44-5161-4c43-815b-f56779a37a0a
> 
> Issue #1: In Test1, while viewing the activity of other user why does the profile name change ( Welcome, ${original user} -> changes to Welcome, ${name of viewing user}. I believe it has to be the same even while viewing other user's activity.
> 
> <img alt="Screenshot 2024-10-18 at 11 12 40 PM" width="1440" src="https://private-user-images.githubusercontent.com/184954416/378048621-f878d3cd-5289-499d-a36e-8cffe0860e6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMTM5ODQsIm5iZiI6MTcyOTMxMzY4NCwicGF0aCI6Ii8xODQ5NTQ0MTYvMzc4MDQ4NjIxLWY4NzhkM2NkLTUyODktNDk5ZC1hMzZlLThjZmZlMDg2MGU2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQwNDU0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmU2ZTliNzk0NGQ5NmEyNzhjNmY2MGMyMjk0ZWJkM2M1YTE5NzE3NTk5OGM5OWIwZDQ3OGRmZmViZGIwM2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OWLV0mszClbD7_LG7bdhNYSI_wFt27OsX4Pt7grz7e8">

This is what is expected from the changes. When we view another user's page dashboard needs to show another user's details on dashboard summary.

2024-10-19 05:27 UTC, CodewithKoushica commented
> > Hello Snehal, I went through the code and tested the changes in Safari, Google Chrome and Firefox. The changes you mentioned works well for me.
> > Test verifying video: https://github.com/user-attachments/assets/7619bd44-5161-4c43-815b-f56779a37a0a
> > Issue #1: In Test1, while viewing the activity of other user why does the profile name change ( Welcome, ${original user} -> changes to Welcome, ${name of viewing user}. I believe it has to be the same even while viewing other user's activity.
> > <img alt="Screenshot 2024-10-18 at 11 12 40 PM" width="1440" src="https://private-user-images.githubusercontent.com/184954416/378048621-f878d3cd-5289-499d-a36e-8cffe0860e6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMTM5ODQsIm5iZiI6MTcyOTMxMzY4NCwicGF0aCI6Ii8xODQ5NTQ0MTYvMzc4MDQ4NjIxLWY4NzhkM2NkLTUyODktNDk5ZC1hMzZlLThjZmZlMDg2MGU2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQwNDU0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmU2ZTliNzk0NGQ5NmEyNzhjNmY2MGMyMjk0ZWJkM2M1YTE5NzE3NTk5OGM5OWIwZDQ3OGRmZmViZGIwM2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OWLV0mszClbD7_LG7bdhNYSI_wFt27OsX4Pt7grz7e8">
> 
> Hi Koushika, Thanks for reviewing PR This is what is expected from the changes. When we view another user's page dashboard needs to show another user's details on dashboard summary and timelog.

Oh Great Then! Thank you for the clarification.. Apart from this everything works well.

2024-10-19 05:28 UTC, CodewithKoushica submitted a review, later dismissed

2024-10-20 04:30 UTC, abdel-lall submitted a review, later dismissed
LGTM. good job
![Screenshot 2024-10-19 232755](https://github.com/user-attachments/assets/f05c555b-9a02-4752-8bf6-4dcb088ec7df)

2024-10-24 10:35 UTC, samarth9201 submitted a review, later dismissed
Verified the PR. LGTM!

![Screenshot (119)](https://github.com/user-attachments/assets/ee9069d1-6ad7-4332-bc9c-30970713e820)
![Screenshot (120)](https://github.com/user-attachments/assets/e0df0fac-6cd7-4b37-af8d-0f7275b84405)
![Screenshot (121)](https://github.com/user-attachments/assets/9494b5ac-fde8-4856-a49d-6a91c6aa7318)

2024-10-25 04:36 UTC, Rui-Liu-github approved these changes
Hi， I reviewed an PR #2801 by pulling the latest version from Snehal branch. I checked the other user dashboard according to the instructions, summary name, badges and Yellow button "Add time" name...all of then works as expected. Good job. 

![image](https://github.com/user-attachments/assets/e77d05cc-d54c-4553-909e-2d499d6c63b2)
![image](https://github.com/user-attachments/assets/aa5f0c0f-24a3-496c-b716-e5e6a7d89e74)
![image](https://github.com/user-attachments/assets/7c52040d-13c9-46c0-b56e-338ba3f41cd7)
![image](https://github.com/user-attachments/assets/073414cc-8214-4504-92b7-e501c17c7792)
![image](https://github.com/user-attachments/assets/c928bb74-074a-45f3-8afa-61fc01d5edf3)

2024-10-26 18:56 UTC, VMD281 commented
Hi, I reviewed this issue and checked the name on the summary bar, Badges, and "Add time .." button name. Everything is working fine!
<img width="1669" alt="PR#2801_1" src="https://github.com/user-attachments/assets/1e031aa4-4911-4f54-8f72-3f8cb3bb5cc5">
<img width="1669" alt="PR#2801_2" src="https://github.com/user-attachments/assets/d886f1e3-da9c-4355-82e9-eb0ff5d80452">
<img width="1669" alt="PR#2801_3" src="https://github.com/user-attachments/assets/6dcb68f3-c9b9-4dd1-96d1-ce1f589746ad">

2024-10-26 20:32 UTC, Rupa2400 submitted a review, later dismissed
I reviewed PR #2801 by pulling the latest version from the Snehal_fix_userID_dashboard branch. I checked the other user dashboard according to the instructions, verifying the summary name, badges, and the "Add Time" button in yellow—all of which function as expected. Nice work!


https://github.com/user-attachments/assets/ffbc9879-0a14-452b-98c5-9426bcfb35a5


<img width="959" alt="PR_2801" src="https://github.com/user-attachments/assets/2dccac07-697c-46d3-88c6-3f6fc95b37b1">
<img width="959" alt="PR_2801" src="https://github.com/user-attachments/assets/55a20de4-e678-484c-9070-9ec88a2af58e">

2024-10-27 01:41 UTC, varun-elango submitted a review, later dismissed
The code changes look good and is working as expected. The correct user name is displayed on the Summary bar, Badges and Add Time Entry button on the dashboard after viewing another person's profile. 
![PR2801_1](https://github.com/user-attachments/assets/37cf491f-bfab-4672-aea0-3a4f64a5eec5)
![PR2801_2](https://github.com/user-attachments/assets/c376c996-85bb-48ee-8c70-b6ae25b8affd)
![PR2801_3](https://github.com/user-attachments/assets/499e0c97-5abd-49f4-9b6c-681f09fd66d8)

2024-10-27 06:04 UTC, sheetalmangate commented
While testing this PR locally I found the issue below. 

![PR2801_error](https://github.com/user-attachments/assets/167f0a42-9b46-40cd-aba8-4a978f624b5f)

Steps to reproduce
1) Click on red/green button to open another person’s profile.
2) After opening profile click on Task Badge.
3) it will keep header for another person but showing "Activity for {Logged in user's name}

2024-11-02 04:20 UTC, Jingyii800 submitted a review, later dismissed
I have tested this feature and it worked as expected. When viewing other's dashboard, the badges, add time entry and other tabs in summary display correct name. 

https://github.com/user-attachments/assets/0972aa31-7ac6-4d42-95d9-691c8ec3e0cb

2024-11-23 00:23 UTC, CodewithKoushica commented
Everything works as expected.
<img width="1440" alt="Screenshot 2024-11-22 at 6 23 19 PM" src="https://github.com/user-attachments/assets/a45c9524-77bd-423f-9292-45115eb3a889">

2024-11-23 00:23 UTC, CodewithKoushica approved these changes

2024-11-23 03:29 UTC, Jingyii800 submitted a review, later dismissed
The feature worked as expected. 

https://github.com/user-attachments/assets/62d55bb5-23e2-4aa9-a711-c789c088fd26

2024-11-23 03:58 UTC, lucy-xfl approved these changes
![image](https://github.com/user-attachments/assets/4eb5f4af-14bd-4dc2-88b2-d251bd11e9a3)
<img width="391" alt="image" src="https://github.com/user-attachments/assets/e77ba694-1715-4e7c-b25e-56a043d55f02">
have test the two functions, both of them work well

2025-01-24 01:10 UTC, one-community commented
Thank you all, merging!

2025-01-24 01:11 UTC, merged