made changes to the timer reset problem in the WBSItem.jsx file
OneCommunityGlobal/HighestGoodNetworkApp pull request #2807
Opened 2024-10-21 17:18 UTC by mrinalini-raghavendran19

# Description

<img width="733" alt="Screenshot 2024-10-21 at 10 38 06 PM" src="https://github.com/user-attachments/assets/c3c37153-438a-42f7-90e7-8c6656e1076f">

Fixes # (bug list priority low)
(PRIORITY LOW) Tatyana

## Related PRS (if any):
NA
…

## Main changes explained:

1) Made a change to WBSItem.jsx in src/components/Projects/WBS/WBSItem/WBSItem.js
2) Changed the line of code -  <a href={`/wbs/tasks/${props.wbsId}/${props.projectId}/${props.name}`} className={darkMode ? 'text-azure' : ''}>{props.name}</a> 
to - <Link to={`/wbs/tasks/${props.wbsId}/${props.projectId}/${props.name}`} className={darkMode ? 'text-azure' : ''}>{props.name}</Link> to prevent a page reload and reset timer

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/ owner user
5. go to dashboard→ Start Timer -> Go to Projects -> Click on the WBS for a project -> Click on a task 
6. verify Page doesn't reload and timer reset because of this

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/f744aca8-2ea1-4cb2-98c8-614af7bc0c5b

## Note:
-

2024-10-22 00:21 UTC, samarth9201 submitted a review, later dismissed
Verified the Functionality of the changes. The timer does not reset after clicking on tasks.

![Screenshot (92)](https://github.com/user-attachments/assets/c6519322-b778-445d-93fa-ef4fe94e3c34)

2024-10-22 00:21 UTC, samarth9201 commented on src/components/Projects/WBS/WBSItem/WBSItem.jsx
> +         {/* <a href={`/wbs/tasks/${props.wbsId}/${props.projectId}/${props.name}`} className={darkMode ? 'text-azure' : ''}>{props.name}</a>  */}
Remove the Comment

2024-10-22 14:02 UTC, CodewithKoushica submitted a review, later dismissed
The changes work well, and the flow behaves as expected.
<img width="1436" alt="Screenshot 2024-10-22 at 8 58 42 AM" src="https://github.com/user-attachments/assets/e18a7d87-cb9c-4d84-82bb-bd3a072e10ab">


### Suggestion:
It would be helpful to add comments in key areas of the code for documentation purposes. This will make it easier for others (and future you) to understand the logic and maintain the code.

This will improve code readability and assist with long-term maintenance.

2024-10-22 18:05 UTC, Ankuriboh requested changes
Simple fix, code-wise should be ready to merge. However, please note that the element indention doesn't match code level. Also, you have added some unnecessary comments to the code. Please kindly fix before merging.

2024-10-25 00:44 UTC, anji-annavarapu approved these changes
https://github.com/user-attachments/assets/b9edb050-32a7-4704-9225-3b1f66a4fc1d

Reloading works as expected. He also made the correction as mentioned in the conversation.

2024-10-25 00:48 UTC, nikhilgiri0226 reviewed
I have tested this PR. The timer didn't paused. Everything works as expected.

Dark mode
![image](https://github.com/user-attachments/assets/08165c6a-ec61-4454-8c2a-8cad5cef4d6a)

Normal mode
![image](https://github.com/user-attachments/assets/68d15a45-e57f-466f-a1b7-40f97726cadd)

2024-10-25 04:04 UTC, NK3101 approved these changes
Tested the PR, changes work as expected.
<img width="1470" alt="Screenshot 2024-10-25 at 12 04 24 AM" src="https://github.com/user-attachments/assets/66cf3228-8bfb-4e76-8fa6-7d13382c802d">

2024-10-25 23:06 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/60b3d4dd-c7cd-47ac-a5fe-b87489dd3dd0

2024-10-26 11:19 UTC, Anoushka21 approved these changes
The timer doesn't reset and page doesn't reload when editing task in wbs. Working well in both light and dark mode.

https://github.com/user-attachments/assets/5028be9d-9d12-405b-9b04-49e585c0870b

2024-10-26 19:36 UTC, shashankhv submitted a review, later dismissed
Confirmed that navigating through tasks doesn’t reload the page or reset the timer. Functionality works as expected.

[2807.webm](https://github.com/user-attachments/assets/2c9b5808-2f17-4b95-971a-1f9e55edacfd)

2024-11-02 04:32 UTC, Jingyii800 approved these changes
I have tested this feature and it works well. The timer won't reset when clicking on WBS.

https://github.com/user-attachments/assets/00e0d8ee-9f9e-4c72-8d3c-b078ba437ed2

2024-11-02 16:25 UTC, jinxyou submitted a review, later dismissed
The timer is working correctly and it doesn't stop. Great job
![Screenshot 2024-11-02 092520](https://github.com/user-attachments/assets/fa829849-8351-411a-adad-ac14125a906d)
![Screenshot 2024-11-02 092531](https://github.com/user-attachments/assets/67ab8841-377c-45d9-8541-d2861342b024)

2024-11-03 02:51 UTC, varun-elango submitted a review, later dismissed
The change works as expected. The page does not reload and the timer is not reset.
![PR2807_1](https://github.com/user-attachments/assets/e14cc323-f06b-4cf7-abef-abed5efe6c78)
![PR2807_2](https://github.com/user-attachments/assets/9eab6d1b-4d03-459a-9778-521f22d98824)

2024-11-03 05:53 UTC, hqzhu0913 approved these changes
No time reset or reloading problem. Works as expected.
https://www.loom.com/share/91355e2c89a542479c58dbeb8b47c9a2?sid=d8c9255c-c09a-4836-a36d-78a1c6733e69

2024-11-08 03:45 UTC, vijay10pk approved these changes
Everything works as expected.
<img width="1425" alt="image" src="https://github.com/user-attachments/assets/13ad3e51-d573-4030-a031-09575881e645">

2024-11-09 20:04 UTC, KurtisIvey commented
Hi there, I noticed there was a merge conflict on this. I'd love to get this moved to final review asap once you clear up the merge conflict as you've got a lot of approvals on this

2025-01-24 01:12 UTC, one-community commented
Thank you all, merging!

2025-01-24 01:13 UTC, merged