Rishitha user management lint fix
OneCommunityGlobal/HighestGoodNetworkApp pull request #2810
Opened 2024-10-23 23:09 UTC by RishithaMamidala

# Description
Lint fix for the UserManagemnet Component

## Main changes explained:
All the files in src/component/UserManagement/** have been checked and all lint and prettier fixes have been made.

## How to test:
1. check into current branch
2. do npm install and ... to run this PR locally
3. log as admin user
4. Verify if the application mainly user management works as expected (Same as development branch)
5. Also check tests, npm run test

2024-10-25 22:58 UTC, nikhilpittala16 submitted a review, later dismissed
I have tested the PR and everything works as expected.
![Screenshot (230)](https://github.com/user-attachments/assets/342b47d9-bba5-4d14-a633-8eb6fc1a3e5f)
![Screenshot (231)](https://github.com/user-attachments/assets/b066db12-b510-45df-bea3-a4d739f1f321)

2024-10-25 23:45 UTC, EvianTan commented
Thanks for your efforts! Please resolve those conflicts and DM me on Slack, I'll merge it as soon as I can, or it will have conflicts again..

2024-10-26 04:44 UTC, anirudhsk2107 submitted a review, later dismissed
Everything is working as expected 

![Screen Shot 2024-10-26 at 12 40 15 AM](https://github.com/user-attachments/assets/a4ef2931-57a4-45c3-96ae-e148b5efc728)
<img width="422" alt="Screen Shot 2024-10-26 at 12 44 57 AM" src="https://github.com/user-attachments/assets/a2801e3b-5712-436b-b606-8608d3c9f238">

2024-10-26 11:29 UTC, Anoushka21 approved these changes
Working as expected. No linting errors and the code is now cleaner.
![image](https://github.com/user-attachments/assets/626e2688-61d9-446b-b756-d5307104b0ed)

2024-10-27 01:06 UTC, ShreyaLaheri commented
Attached ss of what user management looks like. Not all the tests passed.
![image](https://github.com/user-attachments/assets/a8aab58f-234d-4d6c-8c7e-409140b6e7aa)
![image](https://github.com/user-attachments/assets/14c23a48-ede0-4030-9c8c-3e721278b917)

2024-10-29 23:05 UTC, samarth9201 approved these changes
Working as Expected.

![image](https://github.com/user-attachments/assets/21d15b9b-34e9-4876-9e5a-f2828cb696fb)

2024-10-30 04:14 UTC, Rui-Liu-github approved these changes
Hi, I reviewed PR #2810 by pulling the latest version branch from Rishi. I checked the user management and ran test, all mentioned feature and test works as expected. 
![image](https://github.com/user-attachments/assets/764a7338-0c93-4d95-be90-8953aaaab6a0)
![image](https://github.com/user-attachments/assets/9fbdcca4-2730-44f0-ab91-d75616103141)

2024-10-30 23:34 UTC, humera314 commented
Works Perfectly as Expected

![image](https://github.com/user-attachments/assets/87d4f8ac-79ae-4a22-926f-3d48144095ec)

![image](https://github.com/user-attachments/assets/6f5c797b-306b-4219-a841-832c8c93756c)

2024-10-31 03:20 UTC, SupriyaSudini reviewed
I have tested the user management functionality and verified that it works the same as in the development environment.

![image](https://github.com/user-attachments/assets/7acb22c1-5d51-4aae-9b98-6243a9fd6313)

User management in dev
![image](https://github.com/user-attachments/assets/afbdcfa9-95a7-4fb4-a88f-b6d1d4c3fd32)

I ran the test cases, and while some passed successfully, others were skipped.
Please look at the skipped test cases based on the priority
![image](https://github.com/user-attachments/assets/18cf5b47-865c-427b-95ce-c5a6391d4321)

2024-10-31 20:25 UTC, CodewithKoushica requested changes
I tested this PR and there are few failed test cases. Please take a look at it.
<img width="1159" alt="Screenshot 2024-10-31 at 3 22 38 PM" src="https://github.com/user-attachments/assets/8afdbf1b-c982-4747-8bf0-64990e08d841">

2024-11-01 23:51 UTC, EvianTan commented
No new issues was introduced by this PR and passed all the lint and unit tests. I'll approve and merge this PR.
![image](https://github.com/user-attachments/assets/eac7864d-d3d0-4e73-b6e7-c5c7952ca075)
![image](https://github.com/user-attachments/assets/29c279cf-334b-450a-bea0-c8f9c418d019)

2024-11-01 23:51 UTC, EvianTan approved these changes

2024-11-01 23:51 UTC, merged

2024-11-02 06:51 UTC, sheetalmangate commented on src/components/UserManagement/ActiveCell.test.js
> +// import React from 'react';
Please remove commented code.

2024-11-02 07:12 UTC, sheetalmangate commented on src/components/UserManagement/NewUserPopup.jsx
> +  const confirmAction = () => {
Remove function with no body.

2024-11-02 07:20 UTC, sheetalmangate commented on src/components/UserManagement/NewUserPopup.jsx
Remove functions that do not have body.

2024-11-02 07:34 UTC, sheetalmangate commented on src/components/UserManagement/ResetPasswordPopup.jsx
Please remove commented code

2024-11-02 15:05 UTC, sheetalmangate commented
While checking functionality "Bulk Update" functionality on user management is not working. for regenerating issue
1) log in as owner 
2) Click on edit icon from header and then click on save icon.

https://github.com/user-attachments/assets/d5f2594e-4738-426b-b2c9-dd3e373eb2a7