Start date bug fix
OneCommunityGlobal/HighestGoodNetworkApp pull request #2812
Opened 2024-10-24 02:32 UTC by anirudhsk2107

# Description
1. Navigate to  Other Links → Projects → WBS → Click on WBS name → Add Task
Bug: When the End Date is set earlier than the Start Date, the error message 'Due Date must be greater than Start Date' appears for both fields, but it should only appear for the End Date. 
![Screen Shot 2024-10-23 at 9 28 17 PM](https://github.com/user-attachments/assets/103b7852-819f-498c-85dc-4d3df1b770c1)

2. Navigate to  Other Links → Projects → WBS → Click on WBS name → Task Edit → Edit
Bug: When the Start Date and End Date are corrected in the Update Task modal (with the Start Date set earlier than the End Date), error messages are still displayed for both dates. 
![Screen Shot 2024-10-23 at 9 29 10 PM](https://github.com/user-attachments/assets/2377c045-c464-45a4-8504-36848b164df5)

3. Navigate to  Other Links → Projects → WBS → Click on WBS name → Task Edit → Edit
Bug: When the End Date is updated to a date earlier than the Start Date, I was able to save the incorrect updates despite the error messages being displayed.
![Screen Shot 2024-10-23 at 9 30 33 PM](https://github.com/user-attachments/assets/f9fe2c58-e4b1-467b-b977-f1d8259cdbb7)

4. Navigate to  Other Links → Projects → WBS → Click on WBS name → Task Edit → Edit
Bug: When opening a task for editing with incorrectly set dates(see image above), the End Date appears as unspecified (the default date is shown in the End Date field in the image below).
The format of the Start Date does not match the format of the End Date in the Edit Task modal.
![Screen Shot 2024-10-23 at 9 31 11 PM](https://github.com/user-attachments/assets/ede36336-fe07-45ae-862e-19a6aa16ad9d)

## Related PRS (if any):
Not related to any backend PRs

## Main changes explained:
- Added error message validation in EditTaskModal.jsx for Start Date and End Date, ensuring users input correct date values.
- Fixed error messages persisting on closing or minimizing the modal by resetting state and clearing errors using the useEffect hook.
- Fixed the format issue for start date when clicking on "Edit"

## How to test:
1. Check into current branch
2. Do npm install and run this PR locally
3. Clear site data/cache
4. Log as owner/admin user
5. Go to dashboard→ Projects → WBS -> Select Task
6. Edit any task (Add a new one if no tasks are available) 
7. Check if the edit allows the start date to be more than the end date. 

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/1bee4613-03a7-48fe-9a41-3a2390428e1e

## Note:
The add task page can be navigated to here in [this video](https://www.loom.com/share/8bc672c323b64955aac4bce46c3794aa?sid=b05f5604-87cb-4ca1-80b8-49bd823893ee)
This PR is related to front end [PR 2335](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2335). Same bugs were fixed in the Add Task modal.

2024-10-24 22:10 UTC, CodewithKoushica requested changes
The changes in this PR work smoothly, and all the reported bugs related to the Start Date and End Date validation have been resolved. I tested various edge cases, including incorrect date ranges, boundary dates, and reopening the modal without submitting, and everything functions as expected. The UI behaves consistently, and error messages clear properly after corrections.

**Minor issues:
- I noticed that the date picker becomes partially hidden, making it difficult to use. It would be great if this could be adjusted for better visibility.
- Additionally, there's an unnecessary white space added after the DOM to hold the Date Picker, which affects the layout. **

<img width="1438" alt="Screenshot 2024-10-24 at 5 08 16 PM" src="https://github.com/user-attachments/assets/9c2cbb4d-998a-4b7b-b04e-6308118ff270">
<img width="1440" alt="Screenshot 2024-10-24 at 5 08 32 PM" src="https://github.com/user-attachments/assets/2e84c7cb-2b80-4a08-9107-3156e00cef4b">


Overall, great work! Just this small fix, and it’ll be perfect.

2024-10-25 00:04 UTC, anji-annavarapu commented
As @CodewithKoushica mentioned, the date picker is hidden in edit option, but everything else is fine.

2024-10-25 00:10 UTC, nikhilgiri0226 approved these changes
I have reviewed this PR and everything works as expected. 

1.) I was able to input correct date values at the first time while creating a task and while editing as well.

2.) Error messages were not visible once the start and end date validation is fulfilled.

3.) The format issue for start date when clicking on "Edit" is fixed.

The date picker position could be adjusted for better visibility and the added extra space at the bottom can be ignored. It could be placed on the top to avoid adding the extra space. Kindly refer the images below.

![image](https://github.com/user-attachments/assets/c5923147-3d0b-48b8-8bfb-a001e02e67cc)

![image](https://github.com/user-attachments/assets/4b5eeeab-45fe-4dba-a9de-f4e6c0f81b22)

![image](https://github.com/user-attachments/assets/f25e93b1-9abd-431b-b023-b411daf4e48e)

2024-10-25 08:31 UTC, samarth9201 approved these changes
Verified the changes, LGTM
![Screenshot (126)](https://github.com/user-attachments/assets/67652d52-08be-4647-a802-2325111642ac)
![Screenshot (127)](https://github.com/user-attachments/assets/98ea5de3-265d-4787-9c87-0c7601c5ab84)
![Screenshot (128)](https://github.com/user-attachments/assets/7bc402b1-fa18-40cb-a6aa-09289a33a0e2)

2024-10-25 14:52 UTC, linkhanthtel reviewed
It's showing error for incorrect input dates as expected. Nice work! But, one thing, it would be much better if the date picker position is adjusted. 

<img width="1144" alt="#2812" src="https://github.com/user-attachments/assets/8a6612f3-b6bf-41c2-b551-bc2160298117">

<img width="1141" alt="#2812 (2)" src="https://github.com/user-attachments/assets/7d51d2ea-2f19-4cca-a2a2-a5cc0e7a25e0">

2024-10-25 18:18 UTC, Muhideenthegreat reviewed
Verified:

- Successfully fixed the validation logic for start/end dates
- Error messages now appear correctly only for the problematic field
- Date format consistency is now maintained across the UI
- Prevented saving of invalid date combinations
- Clean implementation of the fixes

Suggested Improvement:

While the functionality works perfectly, I noticed one UX consideration: The container size for the Edit Task modal feels a bit constrained, especially when the calendar is open. Consider increasing the modal width/height to fully accommodate the calendar widget without overlap, improve accessibility on smaller devices/screens, provide more comfortable spacing for the form elements

The current size works, but a slightly larger container would enhance the user experience, especially for mobile users.

<img width="1440" alt="Screenshot 2024-10-25 at 1 59 29 PM" src="https://github.com/user-attachments/assets/adff6482-107d-42d7-aa66-fb7a1637c5ae">
<img width="1440" alt="Screenshot 2024-10-25 at 1 59 47 PM" src="https://github.com/user-attachments/assets/2532414d-2d2c-4020-bbec-dbe50b921de3">
<img width="1440" alt="Screenshot 2024-10-25 at 2 01 50 PM" src="https://github.com/user-attachments/assets/c62cae1b-3146-4d77-81ee-02dba639522e">

2024-10-25 19:27 UTC, hqzhu0913 requested changes
Hi,
Everything works as explained. But just like @CodewithKoushica mentioned, in the edit mode, there is date cropped issue.
<img width="1427" alt="Screenshot 2024-10-25 at 12 21 10 PM" src="https://github.com/user-attachments/assets/553687ea-70c0-48d3-9267-657d91d33fe0">
<img width="1426" alt="Screenshot 2024-10-25 at 12 26 57 PM" src="https://github.com/user-attachments/assets/9c86e699-cf87-49c0-9b67-43132643e0fc">
<img width="1431" alt="Screenshot 2024-10-25 at 12 21 39 PM" src="https://github.com/user-attachments/assets/4467dc66-eb54-4eeb-b829-eca89b905f82">

2024-10-25 22:47 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/fbfc6aec-c944-45f0-9901-abd6dc36e29f

2024-10-25 23:56 UTC, NK3101 approved these changes
Tested the PR,  everything works as expected.

<img width="1470" alt="Screenshot 2024-10-25 at 7 52 39 PM" src="https://github.com/user-attachments/assets/b360171e-c1be-43ea-938a-5e04ef0d51a5">
<img width="1470" alt="Screenshot 2024-10-25 at 7 51 56 PM" src="https://github.com/user-attachments/assets/68ae2ae7-fd61-4fd8-9603-5d82e40517f6">

2024-10-26 01:25 UTC, ajitp4292 approved these changes
Error messages functionality working has expected
<img width="1423" alt="Screenshot 2024-10-25 at 9 22 27 PM" src="https://github.com/user-attachments/assets/bf823c9a-7c02-4fe6-a4c0-e5d33cc39811">

2024-10-26 11:38 UTC, Anoushka21 approved these changes
Bugs are fixed. Shows a validation error only when due date is less than start date.
Like everyone mentioned, we can improve on the date picker position so it appears more clearly for better UI

https://github.com/user-attachments/assets/9f72904a-d742-4458-a19d-68f0c8c4c887

2024-10-27 02:49 UTC, ShreyaLaheri commented
Tested the PR in both dark and light mode. Works well
Just one suggestion - in the dark mode, is it possible to change the color of the error message?
![image](https://github.com/user-attachments/assets/8cd2ae91-3188-47cf-9f7d-7433eadddec7)

2025-07-01 00:02 UTC, closed without merging