Sai Preetham implements logic for search display
OneCommunityGlobal/HighestGoodNetworkApp pull request #2816
Opened 2024-10-25 16:13 UTC by preethamdnr

# Description
<img width="445" alt="image" src="https://github.com/user-attachments/assets/69b25ed7-7546-49f3-aaab-343bf1717fa0">

## Related PRS (if any):
To test this PR, please ensure you are checked out to the latest development branch on the backend.
…

## Main changes explained:
Updated the Team Reports page to display search results with dark mode support, checkbox selection logic, and improved user interaction for team details.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user who has permissions to see reports and teams.
5. go to dashboard→ Reports→ Reports→ Teams
6. Select any of the the team and it navigates to its team stats page scroll down to the end of the page where you can see a search bar with "search team name"
7. Verify Search Functionality: Type a specific team name in the search bar. Check that the page correctly filters and displays only the teams that match the entered name.
8. Check Team Stats Display: Select a team by clicking its checkbox. Ensure that the detailed stats for that selected team are displayed correctly on the screen.
9. Observe Behavior in Both Modes: Test the above steps in both light and dark modes to confirm that the search functionality and stats display work consistently across different themes.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/78062483-578e-4dc0-b902-6fd6b1a5c624

2024-10-25 20:38 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/1b5ba9ce-264c-4953-a3cb-e247c74c33c3

2024-10-25 20:53 UTC, CodewithKoushica submitted a review, later dismissed
The updates in this PR work well, and the new features—search, selection, and dark mode—are functional and responsive. However, I noticed a usability issue with team visibility on the Teams Reports page:

Currently, only the first five team names are displayed, which may lead users to believe there are no more teams available. It would be helpful to add an indicator, like a “View More” button or scrollbar, to clarify that additional teams are accessible beyond the initial display.

Overall, everything else looks great—just this small adjustment for a clearer user experience would be helpful!

<img width="1440" alt="Screenshot 2024-10-25 at 2 45 00 PM" src="https://github.com/user-attachments/assets/120ae5ec-7483-45b1-805c-ef3240748763">

2024-10-25 21:40 UTC, vishavk1992 submitted a review, later dismissed
I have tested this PR work well, and the new features search, selection, and dark mode are functional and responsive.
![Screenshot 2024-10-25 173825](https://github.com/user-attachments/assets/38bead2c-666f-4bb0-86fa-ba14a559a167)

2024-10-25 21:51 UTC, hqzhu0913 requested changes
The search function works as expected in both light and dark mode. But search function only shows 5 items. Need indicator to View more to tell users know there are more listed items. And if select the team, the UI changed. The whole width becomes wider. 
<img width="1552" alt="Screenshot 2024-10-25 at 2 51 00 PM" src="https://github.com/user-attachments/assets/b2491654-4090-4b91-9df3-489c1d190302">
<img width="1552" alt="Screenshot 2024-10-25 at 2 51 11 PM" src="https://github.com/user-attachments/assets/60063cfb-fdb5-4d00-8ade-2f271bafeda3">

2024-10-25 23:38 UTC, NK3101 approved these changes
Tested the PR, search, select features are functional and responsive in both light and dark modes.

https://github.com/user-attachments/assets/14613401-2531-44ff-9854-e4a7f80d9cac

2024-10-26 00:31 UTC, samarth9201 submitted a review, later dismissed
Works as expected, LGTM!

![Screenshot (131)](https://github.com/user-attachments/assets/3271c120-bca8-4964-a2aa-9311feb31d40)
![Screenshot (132)](https://github.com/user-attachments/assets/1e8c1260-9a54-4e59-99e6-99361d124c36)
![Screenshot (133)](https://github.com/user-attachments/assets/30c6c2ed-03ea-461d-b270-dfb01617d031)

2024-10-26 11:49 UTC, Anoushka21 submitted a review, later dismissed
Changes working as intended. Search functionality and select functionality working. I tested in both modes using admin role.

https://github.com/user-attachments/assets/61c35c39-3cf9-426b-908c-9e290c02c4a9

2024-10-27 02:59 UTC, ShreyaLaheri commented
Everything works as expected
![image](https://github.com/user-attachments/assets/20e9e886-0ce2-4caa-8f8c-c1308b24ca5e)
![image](https://github.com/user-attachments/assets/5b5b117a-23f7-4509-815f-5186d01efa76)
![image](https://github.com/user-attachments/assets/e84d104e-582d-4921-9b81-83d77c8a08c3)

2024-11-01 18:53 UTC, SharadhaS24 approved these changes
The search functionality and stats display work well across different themes, providing relevant search results each time.

<img width="468" alt="image" src="https://github.com/user-attachments/assets/949ebbcc-3309-4199-8f12-2a3462e87a55">
<img width="468" alt="image" src="https://github.com/user-attachments/assets/2d889975-520e-42c9-a68d-bca61f1eb11a">

2024-11-02 18:40 UTC, anji-annavarapu requested changes
<img width="960" alt="Screenshot 2024-11-02 133714" src="https://github.com/user-attachments/assets/decb36ee-4c1d-45a8-9611-c505b23b32db">

The date picker is hidden in this picture. Feel free to refer to this picture. Additionally, when I try to clear the date in the picker, it does not clear. Please correct this issue.

2024-11-02 21:58 UTC, ajitp4292 requested changes
The Search functionality of team names works as excepted, but date picker does not display the dates, is this normal?
<img width="1512" alt="Screenshot 2024-11-02 at 5 51 58 PM" src="https://github.com/user-attachments/assets/5312d44f-a56b-46e6-bb9e-2886e1f527ea">
<img width="1453" alt="Screenshot 2024-11-02 at 5 54 20 PM" src="https://github.com/user-attachments/assets/1020166a-59c0-41ee-81d2-9b9b27cf64fb">

2024-11-04 01:49 UTC, aaryaneil requested changes
The changes work as expected but I suggest you add a scrolling view in it so that multiple teams can be displayed and not just the top 5.

https://github.com/user-attachments/assets/c82e3955-8907-4a08-b2f7-b8e20dd7899e

2024-11-20 00:35 UTC, preethamdnr commented
Hello all,

I have addressed your change requests and made the necessary updates to allow viewing more than 5 rows by adding vertical scroll functionality. The table now displays more than 5 rows at a time, with additional rows accessible via scrolling. Please review and let me know if any further changes are needed.

Thank You!

https://github.com/user-attachments/assets/f6e30983-b765-4485-922f-9eb380003393

2024-11-20 22:29 UTC, hqzhu0913 approved these changes
The search function works as expected. And no more 5 items limited. Great Job.

2025-07-04 16:51 UTC, Deekshith010905 commented
![image](https://github.com/user-attachments/assets/b589f78b-aaa5-477c-9a41-1a9238126a7a)
The TeamReport page is working as expected after taking over from Preetham. The team name search, date filters, and active/inactive checkboxes now function correctly and update the table in real time. All team details are displayed properly, and the "See" button works. React errors have been resolved, the console is clean, and the UI remains stable and responsive with full functionality.

2025-07-13 03:06 UTC, Babu-kota approved these changes
I have tested this PR work well, and the new features search, selection, and dark mode are functional and responsive.

https://github.com/user-attachments/assets/2ce0c3cf-7377-4ef2-8a68-5c09b6b4c6f8

2025-09-01 04:09 UTC, one-community commented
Thank you all, merging!

2025-09-01 04:09 UTC, merged

2025-11-07 18:57 UTC, ManeeshBuddha21 commented
Reviewed and tested this as part of PR #4273 
Functionality confirmed working correctly ,  search triggers on click, clear button resets as expected.