Swathi Add a button to display paused tasks on the top of the table.
OneCommunityGlobal/HighestGoodNetworkApp pull request #2817
Opened 2024-10-26 02:38 UTC by Lemonnycodes

# Description
This PR introduces a button to display paused tasks at the top of the table in the tasks view. 

## Related PRS (if any):
This frontend PR is related to the development backend 

## Main changes explained:

- Add button to task view: Added a button in the task UI to filter and display paused tasks.
- Update filter logic in file: Updated the filter function in the tasks component to handle paused tasks status.
- Modify styling and layout: Adjusted styling and layout to maintain consistency and ensure the button aligns with the existing UI.

## How to test:

-  Check into current branch
- Run npm install to ensure dependencies are up-to-date.
- Clear your browser’s site data and cache to avoid any stored data conflicts.
- Log in as an admin user.
- Navigate to Other Links>Projects>Click WBS Icon>Choose WBS>Add Task
- Add or Edit a new task and set its status to "Paused".
- Click the new "Paused" button and verify that only paused tasks are displayed.
- Confirm that the feature functions correctly in both light and dark mode.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/950f4f38-decf-4011-9096-dd76994748ed

![image](https://github.com/user-attachments/assets/f61902af-e2ad-4e47-be40-26ff273ed01e)

2024-10-26 03:39 UTC, shashankhv approved these changes
Tested ‘Paused’ status, verified button displays only paused tasks in both dark and light modes and screen sizes. Approving PR

[swathi-pr-2.webm](https://github.com/user-attachments/assets/51565320-77c6-4fe4-9d97-749c8a32500c)

2024-10-26 11:55 UTC, samarth9201 approved these changes
Verified that only paused tasks are displayed.

![Screenshot (179)](https://github.com/user-attachments/assets/3c0e713b-a82e-40f9-a505-b8eb5108194f)
![Screenshot (180)](https://github.com/user-attachments/assets/af57a110-ff41-4fc9-baae-bf1b0ba94082)

2024-10-26 11:56 UTC, Anoushka21 approved these changes
Hey! The button works as intended. Shows only paused tasks. And working well in both light and dark modes.

https://github.com/user-attachments/assets/09af46a8-5bd3-48b4-b005-a053c9003cbf

2024-10-26 17:10 UTC, Muhideenthegreat approved these changes

2024-10-26 17:11 UTC, Muhideenthegreat approved these changes
Verification

The pause button works as expected and only displays paused task

2024-10-26 19:51 UTC, Rupa2400 approved these changes
The "Paused" button functions as expected, displaying only tasks with a "Paused" status. The feature performs smoothly in both light and dark modes.

<img width="959" alt="PR_2817_1" src="https://github.com/user-attachments/assets/4ab4ca0f-7b11-4b6b-ad65-e2b050a504bf">

<img width="959" alt="PR_2817_2" src="https://github.com/user-attachments/assets/791330c3-8d14-4236-b871-29bb04fd701d">

<img width="959" alt="PR_2817_3" src="https://github.com/user-attachments/assets/04838cdb-c7fb-42e1-a7b7-db4e3cba77af">

2024-10-26 19:57 UTC, zhiminV approved these changes
I have checked that displaying paused tasks work for light and dark mode.
![Screenshot 2024-10-26 at 12 55 31 PM](https://github.com/user-attachments/assets/bb264454-6205-450f-82c1-e1949cc83d9f)
![Screenshot 2024-10-26 at 12 55 37 PM](https://github.com/user-attachments/assets/560e63b8-b42d-4661-8558-3aff9bb78a6e)
![Screenshot 2024-10-26 at 12 55 47 PM](https://github.com/user-attachments/assets/e125bac3-0496-4935-a9c2-0c6cdade95fd)

2024-10-26 21:25 UTC, SMitta11 approved these changes
It works both in light and dark mode as expected.
Screenshots:
![Screen Shot 2024-10-26 at 4 22 03 PM](https://github.com/user-attachments/assets/2c7843e1-6801-4824-8402-c2a12ed408cb)
![Screen Shot 2024-10-26 at 4 23 31 PM](https://github.com/user-attachments/assets/290d851e-c9c9-45c0-910c-f1d0bf2740be)

2024-10-27 00:52 UTC, ShreyaLaheri commented
Added a few tasks, put one of them on paused state.  After filtering to show only paused state, it worked as expected
![image](https://github.com/user-attachments/assets/c4bf6d5e-157b-4b49-927c-f65a7fd5e591)
![image](https://github.com/user-attachments/assets/3425d655-dfa3-4ae2-9e1f-ff151b6529d8)

![image](https://github.com/user-attachments/assets/169a33c2-5692-4e66-96ce-19408068cfa1)
![image](https://github.com/user-attachments/assets/3dc58401-491f-4e35-aed1-2f92d1c4edb2)

2024-10-27 02:36 UTC, varun-elango approved these changes
The code changes look good and it is working as expected. The paused button filters and shows only paused tasks. The styling and layout of the button aligns with the existing UI in both light and dark mode. But the color of the button could be changed as it is right next to active having the same color.
![PR2817_1](https://github.com/user-attachments/assets/814a10ac-0436-4c5f-bff6-7f45b79181d4)
![PR2817_2](https://github.com/user-attachments/assets/0f1bbbfe-4b11-4b59-b734-34bc8a251b82)
![PR2817_3](https://github.com/user-attachments/assets/3012dc36-4f8e-4754-8b78-55905a1cc53d)

2024-10-27 03:40 UTC, mianmiantea2019 commented
The code  is working as expected.


https://github.com/user-attachments/assets/3cf18144-60e9-454e-8a3e-f7a0c60becb7

2024-10-28 21:21 UTC, AshritaCherlapally commented
The code changes looks perfect and is working as expected. I have tested it by creating a active task and pause task in WBS. The status tab shows both active and paused tasks, also when filtered with Pause tasks it is working fine by filtering only the paused tasks. It is working in dark mode as well.


https://github.com/user-attachments/assets/0ef139fd-33e3-4206-8c16-bf3642bfa9aa

2024-10-28 21:23 UTC, AshritaCherlapally approved these changes
The code changes looks perfect and is working as expected. I have tested it by creating a active task and pause task in WBS. The status tab shows both active and paused tasks, also when filtered with Pause tasks it is working fine by filtering only the paused tasks. It is working in dark mode as well.

2024-10-30 03:36 UTC, nikhilgiri0226 approved these changes
I have reviewed this PR and confirms that the pause button works as expected. Only tasks which are paused are visible when I clicked on paused button and reset when I clicked on All or Active button. This worked fine in both light and dark mode. Kindly, refer the video below.


https://github.com/user-attachments/assets/af11494f-3636-4b41-b79c-e01f2737073d

2024-10-30 03:50 UTC, Rui-Liu-github approved these changes
Hi, I reviewed the PR #2817 by pulling the latest version branch from Swathi. I added a task, edited its status to paused, and then clicked the paused button. The paused list displayed correctly. It works as mentioned.

https://github.com/user-attachments/assets/3a1ebab6-ce29-4399-98e6-62c836020eaf

2024-10-30 14:22 UTC, CodewithKoushica requested changes
I noticed that when a main task is set to 'Paused,' it appears correctly in the paused task section. However, if a sub-task or a sub-sub-task is paused, it doesn’t display in the paused section. Just wanted to confirm if this behavior is intentional or if paused sub-tasks and sub-sub-tasks should also be included in the paused section? 

Thanks!


https://github.com/user-attachments/assets/dcee197b-a203-474f-90be-c46036ede470

2024-10-30 14:44 UTC, SupriyaSudini approved these changes
I've tested the changes and confirmed that the pause button correctly filters out only paused tasks in both light and dark modes. Everything works as expected.

![image](https://github.com/user-attachments/assets/e9457ba9-cf3d-4758-ac34-386abe079bf4)

![image](https://github.com/user-attachments/assets/d1b65d48-0b92-40bf-9fd7-d48347339552)

![image](https://github.com/user-attachments/assets/0444c51f-0134-4d07-9771-b019c09dc6c9)

2024-11-01 20:28 UTC, sheetalmangate approved these changes
Code looks good and it is functioning as expected on my local. 
I have one suggestion : instead of displaying  "**Update Success!**" after editing it would be better to use more formal message like "Updated Successfully" or "Update successful".

Approving this PR.

![PR2817_update_msg_1](https://github.com/user-attachments/assets/e302ca2a-072d-41ae-9da5-f11b10f119de)

2024-11-02 10:32 UTC, aaryaneil approved these changes
Tested the PR and the pause button functionality works as expected for both light and dark mode.

https://github.com/user-attachments/assets/e3822520-e5f0-4762-9935-5cd2f29c4da2

2024-11-02 20:27 UTC, ajitp4292 approved these changes
Reviewed the PR, the task of project are paused and paused task button works as expected.
<img width="1504" alt="Screenshot 2024-11-02 at 4 23 44 PM" src="https://github.com/user-attachments/assets/543b0173-c38b-43b6-9188-f8544f65abd7">
<img width="1507" alt="Screenshot 2024-11-02 at 4 24 13 PM" src="https://github.com/user-attachments/assets/d922fe45-9bb3-4fb3-b33e-dbc273e1cfc5">

2024-11-02 23:45 UTC, audreydieuanh approved these changes
The paused button functions correctly in all scenarios: when adding a new paused task, changing a non-paused task to paused, switching a paused task to non-paused, and in both dark and light mode.

![test2](https://github.com/user-attachments/assets/34c77cea-0b54-4735-8c48-882754119aab)

2024-11-03 00:00 UTC, anandsesha approved these changes
The feature works as intended. Added and edited tasks in both owner and vol user and paused task to check filtered list and it works as expected. Also in dark mode as well. Codebase looks clean. Good work. Screenshots attached.
![Screenshot (1111)](https://github.com/user-attachments/assets/2368e550-a315-424b-8682-6df89254be89)
![Screenshot (1112)](https://github.com/user-attachments/assets/e18db985-e107-4291-a6aa-1a44d59af98d)
![Screenshot (1113)](https://github.com/user-attachments/assets/b3ed23e5-cc18-4351-a1a1-a7d1b3e61eed)
![Screenshot (1114)](https://github.com/user-attachments/assets/5c5db508-edaa-4ecf-8d8b-d52fc8dbe568)

2024-11-07 23:29 UTC, nikhilpittala16 approved these changes
I have tested the PR and all the test cases have passed.

https://github.com/user-attachments/assets/d143b69e-5c85-42ea-8ace-cc0e1a0fec9a

2024-11-11 21:06 UTC, one-community commented
Thank you all, merging!

2024-11-11 21:06 UTC, merged