Yili - Clicking active button cause the page to freeze
OneCommunityGlobal/HighestGoodNetworkApp pull request #2823
Opened 2024-10-27 05:02 UTC by suaniii

# Description
![ Clicking active button cause the page to freeze](https://github.com/user-attachments/assets/44b02622-a849-404c-8800-8e4485532303)

## Related PRS (if any):
For backend use development branch

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner/ admin user
5. go to dashboard→ Reports→ Reports →People
6. Hover over any green dot or grey dot within the "Active" section
7. Confirm that the cursor remains as an arrow (not a clickable pointer), aligning with the behavior on the "Project" and "Teams" pages.
8. Click Test: Click on any green dot or grey dot.
9. Confirm that the page does not freeze and remains responsive.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/a6e107f1-02a6-445b-a245-d05138b16b1a

2024-10-29 02:54 UTC, vijay10pk submitted a review, later dismissed
Changes are working as expected.

https://github.com/user-attachments/assets/e5be7589-280f-43ba-9a19-1100e2a6efbc

2024-10-29 15:07 UTC, CodewithKoushica requested changes
Everything works as expected! One thing to consider: is the onStatusChange functionality necessary here? Please let me know your thoughts.

https://github.com/user-attachments/assets/d59d2c67-02f3-4bea-93e7-b909a82457c7

2024-10-29 20:29 UTC, suaniii commented
> Everything works as expected! One thing to consider: is the onStatusChange functionality necessary here? Please let me know your thoughts.
> 
>  Screen.Recording.2024-10-29.at.10.04.11.AM.mov

Thank you for the feedback! I don’t believe the onStatusChange functionality is necessary in this context. Firstly, the active status on this page is determined by the "Start Date" and "End Date" fields, so there's no need for manual status changes. Secondly, this is a Reports page, not a User Management page, making onStatusChange redundant here. We already have the status change functionality implemented in the User Management page (as shown in the image), where it’s more appropriate and relevant.

![Screen Shot 2024-10-29 at 1 22 28 PM](https://github.com/user-attachments/assets/60925ecd-c314-4bc8-8315-cb9376421087)

2024-10-29 22:42 UTC, samarth9201 submitted a review, later dismissed
Changes working as expected.

![Screenshot 2024-10-29 154031](https://github.com/user-attachments/assets/d15d6691-974b-4bf5-871a-e5f8162639ec)
![Screenshot 2024-10-29 154040](https://github.com/user-attachments/assets/3232069e-8f5d-4f9a-b9b8-0f520d5c77c5)

2024-10-29 22:42 UTC, samarth9201 commented on src/components/Reports/PeopleTable.js
> +  function onStatusClick(person, isActive) {
I agree, should be removed

2024-10-30 03:34 UTC, CodewithKoushica commented
> > Everything works as expected! One thing to consider: is the onStatusChange functionality necessary here? Please let me know your thoughts.
> > Screen.Recording.2024-10-29.at.10.04.11.AM.mov
> 
> Thank you for the feedback! I don’t believe the onStatusChange functionality is necessary in this context. Firstly, the active status on this page is determined by the "Start Date" and "End Date" fields, so there's no need for manual status changes. Secondly, this is a Reports page, not a User Management page, making onStatusChange redundant here. We already have the status change functionality implemented in the User Management page (as shown in the image), where it’s more appropriate and relevant.
> 
> ![Screen Shot 2024-10-29 at 1 22 28 PM](https://private-user-images.githubusercontent.com/113208952/381296156-60925ecd-c314-4bc8-8315-cb9376421087.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTkzNDQsIm5iZiI6MTczMDI1OTA0NCwicGF0aCI6Ii8xMTMyMDg5NTIvMzgxMjk2MTU2LTYwOTI1ZWNkLWMzMTQtNGJjOC04MzE1LWNiOTM3NjQyMTA4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQwMzMwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzFjZDY1YjYyYmE4YjZlZjFhYWJkMTRhOTEwZDhlNjk2NTQyZGRjYWJkMTVkZGFmYjg5MjNlOWVkODc3ZjE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vh2Ad-6s6o2F5HZeCz9NdqSWxBMaM8T_Ty0bEa_IO5g)

Thank you for clarifying! That makes complete sense—if the active status is fully controlled by the "Start Date" and "End Date" fields here, then onStatusChange does seem unnecessary. Could you please remove the onStatusChange functionality from this page?

@suaniii  Thanks again for the thoughtful explanation!

2024-10-30 03:45 UTC, anirudhsk2107 submitted a review, later dismissed
The changes are working properly 

![Screen Shot 2024-10-29 at 11 45 35 PM](https://github.com/user-attachments/assets/e754ea36-7ed9-4b90-a5d9-96b79fb409b2)

2024-10-30 06:39 UTC, hqzhu0913 requested changes
Function works as expected. And like others mentioned, onStatusClick is not used anyway and status should not be clickable.
<img width="1552" alt="Screenshot 2024-10-29 at 11 23 02 PM" src="https://github.com/user-attachments/assets/935de949-7ad5-4f69-b480-3a8346699a2c">
<img width="1552" alt="Screenshot 2024-10-29 at 11 39 12 PM" src="https://github.com/user-attachments/assets/6c8e4177-bed6-4d57-a9d2-5c2731ea6bfc">

2024-10-31 13:34 UTC, beblicarl commented
This functionality works as intended and the code is great

[6ebd4b8b-681e-460f-9702-c5f894d1508a.webm](https://github.com/user-attachments/assets/3c1f2c07-66cc-42e4-ae43-19776cccdb20)

2024-10-31 13:37 UTC, beblicarl approved these changes

2024-11-02 04:15 UTC, nikhilgiri0226 submitted a review, later dismissed
Hi Yili,

I have reviewed the PR and screen was not freeze after clicking the green/grey dot. There was one slight UI related concern. When I clicked on the People table, the table seems to be very wide and table for teams and projects were as expected. I tested this in edge, chrome and I saw this behavior in both browser. Maybe this is at my end only so I am not suggesting any changes because other reviewers were not facing the same issue. So, approving this change.

Kindly find the video below for reference.


https://github.com/user-attachments/assets/f6c50a9f-dfcd-4ad9-b2b4-7aa2c714b657

2024-11-02 04:46 UTC, Jingyii800 submitted a review, later dismissed
The feature worked well. The page doesn't freeze when clicking on the active button. But the total layout for People looks weird on my screen.

https://github.com/user-attachments/assets/dc15d764-2d9a-4411-a7d4-073c558e04d7

2024-11-03 00:03 UTC, ajitp4292 approved these changes
Page does not freeze, works has expected.
<img width="812" alt="Screenshot 2024-11-02 at 8 01 57 PM" src="https://github.com/user-attachments/assets/6ae34a15-bebf-4a43-81de-1bc80520c314">

2024-11-03 00:32 UTC, varun-elango reviewed
It is working as expected. The green/grey dots are not clickable and the page does not freeze. I do agree with others that the onStatusClick function is not needed. And the page is rendered improperly and I had to zoom out a lot to see the green dots. But that is not in scope of this PR.
![PR2823_1](https://github.com/user-attachments/assets/203cb9dc-98bd-47c8-bf9a-52c557db4ae1)
![PR2823_2](https://github.com/user-attachments/assets/a1b93ec0-6711-4452-8182-c4a587f0fd12)

2024-11-03 10:11 UTC, suaniii commented
Edited. Please check it again.
Thanks for the comments.

2024-11-04 16:54 UTC, CodewithKoushica commented
Everything is working as expected. Thank you for considering my request for the change.
Approving the PR.

2024-11-04 17:04 UTC, CodewithKoushica approved these changes

2024-11-05 06:47 UTC, hqzhu0913 reviewed
Hi, I test all people, team and project's active button. They are not clickable and work as expected.

Just one thing, I am not sure if this is my problem. The people table overflow in the test. 

https://www.loom.com/share/cd11220c176646c6bdee3babce564e25?sid=ef1eeb43-6a3e-45b7-87f6-25f33e0fa4de

2024-11-07 21:12 UTC, Muhideenthegreat approved these changes
Verification:

- Page no longer freezes upon click of the dots and cursor remains as an arrow over the dots as well. Bug fixed ! 

<img width="1440" alt="Screenshot 2024-11-07 at 4 07 34 PM" src="https://github.com/user-attachments/assets/8c45ba9f-baa0-45b9-88b9-2437e0c9a03c">

2024-11-08 00:07 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/b8261222-d9b5-4b5c-b0e0-40fc2a31175a

2024-11-20 22:20 UTC, hqzhu0913 approved these changes
It works as expected. And no more clickable function.

2024-11-25 23:52 UTC, one-community commented
Thank you all, merging!

2024-11-25 23:52 UTC, merged