Rishitha material approval process
OneCommunityGlobal/HighestGoodNetworkApp pull request #2827
Opened 2024-10-30 19:32 UTC by RishithaMamidala

# Description
Implement Approval/Rejection process for the material purchase request.

## Related PRS (if any):
This frontend PR is related to the #1138 backend PR.
To test this frontend PR you need to checkout the #1138 backend PR.
…

## Main changes explained:
- Updated src/actions/bmdashboard/materialsActions.js 
- Updated src/components/BMDashboard/ItemList/ItemsTable.jsx to send purchace records correctly
- Updated src/components/BMDashboard/ItemList/RecordsModal.css to add styling to approve and reject buttons
- Updated src/components/BMDashboard/ItemList/RecordsModal.jsx to add approve and reject buttons and handling the buttons
- Updated src/constants/bmdashboard/materialsConstants.js
- Updated src/reducers/bmdashboard/materialsReducer.js
- Updated src/utils/URL.js to add backend endpoint
…

## How to test:
1. check into current branch and check into #1138 backend PR
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. Navigate to http://localhost:3000/bmdashboard and log in as an admin again.
6. Go to http://localhost:3000/bmdashboard/materials
7. Click on the View button under the purchases section to open the request details.
8. For each purchase request, verify that the Approve and Reject buttons are present and functional.
9. Click on the Approve button and ensure the request status updates correctly to "Approved".
10. Click on the Reject button and ensure the request status updates correctly to "Rejected".
11. Confirm that the total purchase count is updated accordingly with each action.
12. Ensure that the Approve and Reject buttons are disabled for requests that have already been approved or rejected.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/4bb32645-6c76-47bd-8d36-07a7556a36a3

## Note:
This is a phase 2 functionality.

2024-10-31 09:02 UTC, samarth9201 approved these changes
I can see the Approve and Reject buttons, but they don't seem to work.

![Screenshot 2024-10-29 173644](https://github.com/user-attachments/assets/6196e28b-4e29-4a21-8142-af12cb2a3882)
![Screenshot 2024-10-29 173701](https://github.com/user-attachments/assets/bd74c51e-73ad-49bf-8aa7-4884522e6cee)
![Screenshot 2024-10-31 015510](https://github.com/user-attachments/assets/76f38735-2559-47b2-9ced-eae351b0880d)
![Screenshot 2024-10-31 020115](https://github.com/user-attachments/assets/c108aec3-480d-4b87-ac61-d689cb8da194)
![Screenshot 2024-10-31 020121](https://github.com/user-attachments/assets/e0d717fa-3889-477a-b07b-e4bea55d6473)

2024-10-31 17:50 UTC, RishithaMamidala commented
Hi @samarth9201 
For this PR, please ensure you're checking out both the main PR and backend PR #1138. Confirm that you’ve switched to the backend #1138 PR branch as well.

2024-10-31 20:18 UTC, CodewithKoushica requested changes
Thanks for adding the approval/rejection buttons! Noticed that while the buttons appear, the call to update status fails, so requests aren’t actually approved or rejected( I have the right backend branch in my local). Could you check the backend connection and add error handling for failed calls?

https://github.com/user-attachments/assets/92e7f70f-4fee-4d78-bd0e-43c5f6097688

2024-11-01 06:06 UTC, hqzhu0913 approved these changes
Approve and remove functions work as expected. Great Job.
<img width="1552" alt="Screenshot 2024-10-31 at 10 52 01 PM" src="https://github.com/user-attachments/assets/339c54ec-61d8-4857-ae58-f365a35c4dc8">
<img width="1552" alt="Screenshot 2024-10-31 at 10 51 43 PM" src="https://github.com/user-attachments/assets/01ee6581-9a46-42be-b8ba-a7036eb39d86">

2024-11-03 02:05 UTC, RashmiKY98 commented
The functionality is working as expected. Tested with Microsoft Edge and Firefox. Also verified that the changes reflect in the count of purchase record without refreshing. No issues found.
![Screenshot 2024-11-02 205348](https://github.com/user-attachments/assets/cd156d43-5669-451b-8d86-bff489063436)
![Screenshot 2024-11-02 205714](https://github.com/user-attachments/assets/de2a06a6-a4df-4cf4-9501-1808a55f223d)
![Screenshot 2024-11-02 205741](https://github.com/user-attachments/assets/f70b41b8-98d5-4b25-853a-ade2abc7d120)

2024-11-03 06:30 UTC, aaryaneil approved these changes
The PR worked as described and the approve and reject button work. Just a suggestion that you can hide the button once they are clicked instead of greying them out.
<img width="1440" alt="Screenshot 2024-11-02 at 11 28 31 PM" src="https://github.com/user-attachments/assets/d9e35614-5aa6-4d22-900c-878a114dcb20">

2024-11-06 22:44 UTC, anirudhsk2107 requested changes
Got the same issue as @CodewithKoushica 
Checked out the correct backend branch as well an still got the issue 
<img width="1680" alt="Screen Shot 2024-11-06 at 5 45 20 PM" src="https://github.com/user-attachments/assets/7c4f1839-358e-48bc-9a79-de3e7a7e5577">

2024-11-11 18:13 UTC, CodewithKoushica approved these changes
Working fine now. Thank you for implementing this change.
<img width="1440" alt="Screenshot 2024-11-11 at 12 11 51 PM" src="https://github.com/user-attachments/assets/193a664e-2fe7-49f5-b8a2-2c5d6b5df751">
<img width="1440" alt="Screenshot 2024-11-11 at 12 12 00 PM" src="https://github.com/user-attachments/assets/d9428975-9580-4303-a805-9dece0f9240c">

2024-11-11 19:23 UTC, anirudhsk2107 approved these changes
The changes worked 
<img width="1128" alt="Screen Shot 2024-11-11 at 2 19 47 PM" src="https://github.com/user-attachments/assets/32c3b9e4-19b6-46f5-9dc0-31dc4b72c23e">
<img width="387" alt="Screen Shot 2024-11-09 at 11 42 28 AM" src="https://github.com/user-attachments/assets/c12ae403-d239-4bcc-8636-4d3cb2f610a7">

<img width="336" alt="Screen Shot 2024-11-11 at 2 19 54 PM" src="https://github.com/user-attachments/assets/d94fbb87-9c29-453d-b5dd-e17903592c5c">

2024-12-21 03:33 UTC, mashpotato9 commented
function worked as expected, successfully obtain the response with both options
<img width="1392" alt="Screenshot 2024-12-20 at 10 30 45 PM" src="https://github.com/user-attachments/assets/a250bfdf-cf50-495d-8abd-274abb55d1d5" />
<img width="1392" alt="Screenshot 2024-12-20 at 10 30 40 PM" src="https://github.com/user-attachments/assets/76848858-1929-432d-90ff-913699d8a8de" />

2025-02-09 19:54 UTC, merged