Sriram fix view of others dashboard
OneCommunityGlobal/HighestGoodNetworkApp pull request #2833
Opened 2024-11-02 00:06 UTC by sri0606

# Description
![image](https://github.com/user-attachments/assets/64e77ec6-dea9-49fb-8a1c-be52337a8f26)

## Related PRS (if any):
Backend development PR
…

## Main changes explained:
- Modified Header component to update correctly when viewing other user's dashboard
- Updated logic dashboard component to pass correct user's details to child components
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Leaderboard → Click dot by a person’s name
6. verify that correct details are displayed
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2024-11-06 22:15 UTC, anirudhsk2107 submitted a review, later dismissed
The changes are working properly. 
Tested for both light as well as dark mode. 

<img width="1650" alt="Screen Shot 2024-11-06 at 5 15 13 PM" src="https://github.com/user-attachments/assets/efee1718-cff6-4166-bd4b-195db36aaded">
<img width="1664" alt="Screen Shot 2024-11-06 at 5 14 14 PM" src="https://github.com/user-attachments/assets/f3c66ebd-23fc-4e93-ba37-4bbc17d57f6a">
<img width="1663" alt="Screen Shot 2024-11-06 at 5 13 33 PM" src="https://github.com/user-attachments/assets/b44a0a62-b0fd-42ce-ae88-5d6a9a58e308">
<img width="1664" alt="Screen Shot 2024-11-06 at 5 12 04 PM" src="https://github.com/user-attachments/assets/f6c02d49-2954-4dd6-80b3-bcb50417f94e">

2024-11-23 00:53 UTC, nikhilpittala16 submitted a review, later dismissed
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/77c37642-3b0b-4f8c-bd85-2a3882917541

2024-11-29 22:00 UTC, ppsahu commented
I have tried to review this PR, however I am getting errors of login for all the 3 accounts. It is not allowing me to enter the dashboard. If you have any fix, please me know. Below are the screenshots for reference.

<img width="1469" alt="Screenshot 2024-11-29 at 1 58 42 PM" src="https://github.com/user-attachments/assets/84d491ce-9017-411d-be8f-21d8f1ab9536">

2024-12-01 02:47 UTC, ppsahu commented
Update from my side. I have tested this PR review, and all the changes as said are working properly. 

![Screenshot 2024-11-30 at 6 45 53 PM](https://github.com/user-attachments/assets/c1d518d0-5e7e-4706-8026-695d16427575)
![Screenshot 2024-11-30 at 6 45 18 PM](https://github.com/user-attachments/assets/44a53b85-12c4-4ad5-8c38-06aed528854d)

2024-12-07 08:13 UTC, SammanBaidya submitted a review, later dismissed
I have reviewed and tested the PR, and the changes are functioning as expected. Both light and dark modes were checked, and everything works smoothly. Please refer to the images for further details.

![PR 2 1#2833](https://github.com/user-attachments/assets/654dd112-609e-4534-adf9-8b95bbc8890f)
![PR2 2 #2833](https://github.com/user-attachments/assets/3e09a9b8-ff8c-4352-bf2a-5f5eadd9bda7)

2024-12-08 02:09 UTC, ShraddhaShahari reviewed
I have reviewed and tested the PR, and the changes are functioning as expected. Both light and dark modes are working as expected and everything works smoothly. Please refer to the screenshots attached.
<img width="1695" alt="Screenshot1- PR2833" src="https://github.com/user-attachments/assets/b0a9f29f-79a4-4d6e-97bd-fd3b42a3ebcb">

<img width="1700" alt="Screenshot2- PR2833" src="https://github.com/user-attachments/assets/66630027-d2d6-4131-9000-822e8860a582">

2024-12-12 23:29 UTC, pallavithorat commented
I have reviewed and tested the PR, and the changes are working as intended. I verified both light and dark modes, and everything functions as expected.
<img width="1470" alt="Screenshot 2024-12-12 at 3 27 28 PM" src="https://github.com/user-attachments/assets/1c3b8234-4933-40aa-ab1b-5b8a686f45c4" />

2025-01-12 04:13 UTC, Sheehan20 reviewed
**Reviewed the view of others dashboard fix.**

Tested functionalities:
1. Access control:
   - Admin/Owner can view others' dashboards
   - Volunteer users correctly restricted
   - Permission checks working

2. Dashboard navigation:
   - Leaderboard dots navigation working
   - Profile to Dashboard navigation shows correct info
   - Display state persists correctly

3. UI Elements:
   - Proper display in both light/dark modes
   - Header updates correctly in viewing mode

Issue found:
- There are merge conflicts in:
  - Header.jsx
  - Leaderboard.jsx
  - TeamMemberTask.jsx

The functionality works as expected but merge conflicts need to be resolved before merging.

2025-01-26 01:13 UTC, honglinchen0524 requested changes
I was able to view other's dashboard using owner's account, but not able to view other's dashboard using admin account.
![image](https://github.com/user-attachments/assets/70f52d07-bd73-4b35-ae3f-6be27150d4f2)

2025-01-26 01:13 UTC, honglinchen0524 commented on src/components/LeaderBoard/Leaderboard.jsx
> +    if (displayUserRole !== 'Owner' && displayUserRole !== 'Admin') {
I think the issue might be here, it should be Administrator instead of Admin.

2025-02-05 19:58 UTC, mikelambo7 approved these changes
Verified that this PR works as expected in both light and dark mode
<img width="1428" alt="Screenshot 2025-02-05 at 2 57 23 PM" src="https://github.com/user-attachments/assets/d8382afa-1bce-48dc-966b-8ad6129ca774" />
<img width="1427" alt="Screenshot 2025-02-05 at 2 56 20 PM" src="https://github.com/user-attachments/assets/37fce963-e99c-4191-b8e1-d9a0b33625de" />

2025-02-05 22:23 UTC, sri0606 commented on src/components/LeaderBoard/Leaderboard.jsx
> +    if (displayUserRole !== 'Owner' && displayUserRole !== 'Admin') {
Yes you are right! It should be `Administrator`.

2025-02-11 23:23 UTC, yany960 approved these changes
Works as expected.
<img width="1980" alt="image" src="https://github.com/user-attachments/assets/0f4d51f5-6763-462c-a648-45a8664f1020" />

2025-03-15 03:47 UTC, HarideepValiveru commented
Reviewed PR. The code is really well done with cool features like tracking tasks and showing progress clearly. It’s easy to use, and the dark mode is a nice touch. Overall the code works as expected.

2025-04-14 20:28 UTC, closed without merging