Deepthi fixed the earned dates at 1025px and below
OneCommunityGlobal/HighestGoodNetworkApp pull request #2842
Opened 2024-11-06 10:48 UTC by deepthikannan

# Description
Below 1025px, the column or option for earned dates is unavailable
 

## Related PRS (if any):
This frontend PR is related to the #2617 
…

## Main changes explained:
- BadgeReport.jsx: Conditional rendering for the "Earned Dates" field in both tablet and desktop views, dropdown for "Earned Dates" in tablet view, and added Options column header for tablet view.
- BadgeReport.css: Media query to toggle between .tablet and .desktop views, column width adjustments for tablet view, dark mode adjustments for tablet header, and dropdown menu styling.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user/ owner user
5. go to dashboard→ view profile→ featured badges→ select featured
6. verify the earned dates column or option is available at 1025px and below

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/792a7686-06c8-4b21-a5d9-c79472d7506b

2024-11-06 19:16 UTC, humera314 requested changes
I can not see the table title of "Earned Date" below 1025px.
![image](https://github.com/user-attachments/assets/f2f8b0ca-0e11-46be-a9a8-4282045563ba)

2024-11-07 03:17 UTC, Muhideenthegreat submitted a review, later dismissed
The earned date columns' header is missing for smaller dimensions. Also the rows can be designed to be more flexible and responsive to fit the width of the screen.

<img width="889" alt="Screenshot 2024-11-06 at 10 12 58 PM" src="https://github.com/user-attachments/assets/5bb6e4ed-de69-42d6-8be5-254d859f4395">

2024-11-07 03:54 UTC, Muhideenthegreat commented
@deepthikannan it works this this way! The load time for the responsiveness still needs to be addressed

2025-01-17 02:07 UTC, one-community commented
Thank you all, merging!

2025-01-17 02:07 UTC, merged