Nikita-Fix-the-incomplete-Members-list-when-the-ALL-TIME-button-is-selected
OneCommunityGlobal/HighestGoodNetworkApp pull request #2854
Opened 2024-11-09 08:33 UTC by ArtemisNyx3

# Description
![image](https://github.com/user-attachments/assets/e4a286f7-c106-4585-8e5d-7fff312b52eb)

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Reports→ Reports→ Projects→ _Select a project_
6. go a few user profiles and add the project selected above
7. All the users who actively are assigned to the project are in active tab
8. delete the project for some users - these users should not be in active tan but should still be in all time tab

## Screenshots or videos of changes:

2024-11-09 14:20 UTC, aaryaneil requested changes
Tested the PR, but when I add a new member, they are added to the all-time tab even before I remove them. Otherwise, all the functionalities work.

https://github.com/user-attachments/assets/a6deda05-0bec-4fc2-a075-517cd570d1e1

2024-11-10 04:21 UTC, anji-annavarapu requested changes
When I assign a member to a project, it works fine. However, when I try to delete a user, they still appear as an active member in the project list.
<img width="807" alt="Screenshot 2024-11-09 221805" src="https://github.com/user-attachments/assets/e6e40f10-e19c-48b6-b018-d5799f1ab0bf">

2024-11-15 04:25 UTC, manikittu810 approved these changes, later dismissed
Hello @ArtemisNyx3 
Everything is working as mentioned.
<img width="1146" alt="Screenshot 2024-11-14 at 8 11 29 PM" src="https://github.com/user-attachments/assets/ec59b536-047a-4441-8983-fe39a5e5831e">


<img width="1454" alt="Screenshot 2024-11-14 at 8 24 08 PM" src="https://github.com/user-attachments/assets/154830d6-ba6a-471f-bf8a-d7cdd7e6fe49">
<img width="1733" alt="Screenshot 2024-11-14 at 8 07 36 PM" src="https://github.com/user-attachments/assets/ce4636c2-544b-496e-92ad-2f81e119364d">
Thank you.

2024-11-23 18:57 UTC, ArtemisNyx3 commented
> Tested the PR, but when I add a new member, they are added to the all-time tab even before I remove them. Otherwise, all the functionalities work.
> Screen.Recording.2024-11-09.at.6.16.42.AM.mov

This is the expected behaviour, since all-time is all users who were added from the beginning

2024-11-23 19:03 UTC, ArtemisNyx3 commented
> When I assign a member to a project, it works fine. However, when I try to delete a user, they still appear as an active member in the project list. <img alt="Screenshot 2024-11-09 221805" width="807" src="https://private-user-images.githubusercontent.com/156052129/384658242-e6e40f10-e19c-48b6-b018-d5799f1ab0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODE2MjAsIm5iZiI6MTczMjM4MTMyMCwicGF0aCI6Ii8xNTYwNTIxMjkvMzg0NjU4MjQyLWU2ZTQwZjEwLWUxOWMtNDhiNi1iMDE4LWQ1Nzk5ZjFhYjBiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxNzAyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmRiMjI4NWNiNWUxN2QzMDE1YzA0ZGU4MGIwZTNjMzQzNzZlZGI1MjYwNTRhODgyODRjZTEzNThmMDZjMGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b5sGg6z_0sX8H-QyDd-YqsbguNjfccxEccM2UdzqpkE">

i was not able to replicate the error its running fine on my end 
can i get a video showing the bug please

thanks

2024-12-14 21:16 UTC, ShraddhaShahari reviewed
Tested the PR, and all the functionalities works as expected.
Please find attached screenshots for the reference.
<img width="1537" alt="Screenshot 2024-12-14 at 1 14 25 PM" src="https://github.com/user-attachments/assets/ed1163c3-abc1-4ad3-951a-e65d0f2fd9c4" />
<img width="1667" alt="Screenshot 2024-12-14 at 1 13 07 PM" src="https://github.com/user-attachments/assets/e6ca1d52-5a54-48a3-b84a-1a83efedd94d" />

2025-02-07 00:20 UTC, yany960 approved these changes, later dismissed
Tested successfully—users assigned to the project are correctly shown in the active tab, and after removing the project for some users, they no longer appear in the active tab but remain in the all-time tab. The functionality works as expected.
![image](https://github.com/user-attachments/assets/d5abd32d-efca-4de4-afa7-bbecc9b4c1d1)

2026-05-18 05:00 UTC, closed without merging

2026-05-18 05:00 UTC, one-community commented
Replaced by this PR: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/5225