Yili - Gives the user permission to Reset and/or Change the password of any user
OneCommunityGlobal/HighestGoodNetworkApp pull request #2860
Opened 2024-11-12 20:57 UTC by suaniii

# Description
![Gives the user permission to Reset and:or Change the password of any user but Owner:Admin classes](https://github.com/user-attachments/assets/3ea766df-0511-41bb-be72-7719e68eb876)

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to Other Links -> Permissions Management -> Manage User Permissions -> Choose a volunteer user -> add Reset / Change Password (Others) -> click on "save changes"
6. verify that the user who was given the permission is now able to see the reset password button and reset another volunteer user's password.(make sure to reset your own account for testing) 

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/b3993606-c514-4249-a5b6-295ab4eb817a

![1](https://github.com/user-attachments/assets/943e1f43-ffc1-41e3-9c6e-a0796742393b)
![2](https://github.com/user-attachments/assets/f8c03652-b0be-4c5d-802d-0e2b01de7e59)
![3](https://github.com/user-attachments/assets/6970b9fc-ad8f-4fca-a4ce-75ba49822a90)

2024-11-15 03:18 UTC, manikittu810 submitted a review, later dismissed
Hello @suaniii 
Everything is working as mentioned.
Thank you.
<img width="1636" alt="Screenshot 2024-11-14 at 6 28 01 PM" src="https://github.com/user-attachments/assets/cbcc4e2d-b4a2-4233-a149-e17e5d8dae15">
<img width="1597" alt="Screenshot 2024-11-14 at 6 29 33 PM" src="https://github.com/user-attachments/assets/5b0ac732-d046-402e-8e7d-0e400aa3051c">

2024-11-17 04:15 UTC, audreydieuanh approved these changes
My volunteer account was able to see the reset button after I changed the permission with my admin test account.

![test17](https://github.com/user-attachments/assets/283f5717-29e1-4ea1-ba23-ceb5e11d08e8)

2024-11-18 02:26 UTC, anji-annavarapu approved these changes
https://github.com/user-attachments/assets/7aca6169-528c-407a-96bf-e84a44c8f0e0

its working all expected.

2025-01-17 22:14 UTC, srikanthpusthem approved these changes
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/4834ecc9-3f48-4871-8fa5-7a618a9089bc" />
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/514d585b-8180-4cff-a46d-1c9a839514bd" />
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/a2baf646-20df-4ecf-8892-b4da4b1069b8" />
working as expected

2025-01-18 04:26 UTC, honglinchen0524 approved these changes
Great work! I was able to give permission to reset password. Video below:

https://github.com/user-attachments/assets/fb478019-f24f-4f90-aeaf-12b9980d35df

2025-01-24 02:53 UTC, lycan10 commented
<img width="1512" alt="Screenshot 2025-01-23 at 9 51 47 PM" src="https://github.com/user-attachments/assets/a3153a2d-b598-4cc2-8c49-3c69d9ee0fae" />

Hi, unfortunately, I cannot find the option to reset password.

2025-02-06 07:03 UTC, yany960 approved these changes
Tested successfully—assigned permissions correctly enable the user to see and use the reset password button. The functionality works as expected.
![WeChatc7a3af584accbc1185e7e3421fcb6c7c](https://github.com/user-attachments/assets/37d41869-b6b0-404c-a3e8-c4a643505db2)

2025-02-08 14:26 UTC, Peter-Nie2003 submitted a review, later dismissed
The function work as expected, Well done!


https://github.com/user-attachments/assets/a25dad95-59e8-4768-8776-0ded6656898d

2025-02-19 09:44 UTC, AurHubertMax approved these changes
The permission to reset/change password of a user functions as expected. Gave permission to my volunteer 1 account to change password of any user, verified to see that the button to reset the password of my volunteer 2 account is available. Changed the account's password to a new password, and verified that the changes were in effect by logging into my volunteer 2 account with the new password.

https://github.com/user-attachments/assets/c4e142ae-d2e3-4407-860a-76be10098ec9

2025-03-16 02:11 UTC, HarideepValiveru commented
Reviewed PR. The code looks really good and shows a lot of effort in organizing everything. It takes care of managing user profiles, teams, permissions, and other tasks well. The tabs and modals are really cool features.

2025-04-02 18:44 UTC, karnati007 submitted a review, later dismissed
Tested the Reset / Change Password (Others) permission in Other Links → Permissions Management → Manage User Permissions as an owner user. Added the permission to a volunteer user, saved changes, and confirmed that the user could see the reset password button and successfully reset another volunteer user's password. Also tested by resetting my own account. Cleared site data and cache before testing. Everything is working as expected.
![YiliPR2](https://github.com/user-attachments/assets/068dd416-b632-4668-86b3-cc983a8fc36f)
![YiliPR](https://github.com/user-attachments/assets/dcaf23c2-0ec6-4de9-8e86-da90e5772927)

2025-04-02 22:17 UTC, nathanah requested changes
Should consolidate update and reset password permissions.

2025-04-02 22:17 UTC, nathanah commented on src/components/UserProfile/UserProfile.jsx
> +      setCanResetPassword(response.data.permissions.frontPermissions.includes('resetPassword'));
```suggestion
      const canResetPassword = props.hasPermission('resetPassword');
```
`hasPermission()` checks both role and individual permissions. The current way only checks individual permissions. Doesn't need to be a state obj because it won't change after being set.

2025-04-02 22:17 UTC, nathanah commented on src/components/UserProfile/UserProfile.jsx
> +              {(canUpdatePassword && canEdit && !isUserSelf || canResetPassword) && (
Doesn't `updatePassword` already do what `resetPassword` should do?

2025-04-02 22:17 UTC, nathanah commented on src/components/PermissionsManagement/PermissionsConst.js
> +        key: 'resetPassword',
I think the `updatePassword` permission was already mostly set up, but not included in `PermissionsConst.js`. Should be fixing/replacing `updatePassword` instead of adding a new permission of `resetPassword` on top of it.

2025-04-05 09:46 UTC, suaniii commented on src/components/UserProfile/UserProfile.jsx
> +              {(canUpdatePassword && canEdit && !isUserSelf || canResetPassword) && (
Fixed, `canUpdatePassword` is now being used for this.

2025-04-05 09:48 UTC, suaniii commented on src/components/PermissionsManagement/PermissionsConst.js
> +        key: 'resetPassword',
I've removed resetPassword from both BE and FE, and `updatePassword` is doing the job now.

2025-04-05 09:55 UTC, suaniii commented on src/components/UserProfile/UserProfile.jsx
> +      setCanResetPassword(response.data.permissions.frontPermissions.includes('resetPassword'));
Changed to use `updatePassword` permission instead.

2025-04-05 23:16 UTC, nathanah requested changes

2025-04-05 23:16 UTC, nathanah commented on src/components/UserManagement/UserTableData.jsx
Still has reset and update

2025-04-05 23:16 UTC, nathanah commented on src/components/UserProfile/UserProfile.jsx
> +  const [canUpdatePassword, setCanUpdatePassword] = useState(props.hasPermission('updatePassword'));
```suggestion
```

2025-04-05 23:16 UTC, nathanah commented on src/components/UserProfile/UserProfile.jsx
> +      setCanUpdatePassword(response.data.permissions.frontPermissions.includes('updatePassword'));
```suggestion
```

2025-04-05 23:16 UTC, nathanah commented on src/components/UserProfile/UserProfile.jsx
> -  const canUpdatePassword = props.hasPermission('updatePassword');
This is how it should be done. `canUpdatePassword` doesn't need to be a state object and should always be set to `props.hasPermission('updatePassword')`.

2025-04-09 07:17 UTC, suaniii commented on src/components/UserProfile/UserProfile.jsx
> -  const canUpdatePassword = props.hasPermission('updatePassword');
Reverted my changes, now it's using `hasPermission()`

2025-04-09 07:17 UTC, suaniii commented on src/components/UserProfile/UserProfile.jsx
> +      setCanUpdatePassword(response.data.permissions.frontPermissions.includes('updatePassword'));
Removed this, use `hasPermissions()` instead.

2025-04-09 07:17 UTC, suaniii commented on src/components/UserProfile/UserProfile.jsx
> +  const [canUpdatePassword, setCanUpdatePassword] = useState(props.hasPermission('updatePassword'));
Removed this, use `hasPermissions()` instead.

2025-04-12 02:27 UTC, nathanah approved these changes
LGTM

2025-04-13 05:11 UTC, one-community commented
Thank you all, merging!

2025-04-13 05:11 UTC, merged