Created branch to delete members from the project
OneCommunityGlobal/HighestGoodNetworkApp pull request #2862
Opened 2024-11-13 00:49 UTC by SnelPatare

# Description
(PRIORITY HIGH) Jae: Create way to remove members from Projects>Members pages (WIP Snehal)
Other Links → Projects → Click on Members icon
I’d like a way to remove a member from a project. It should work just like the way we remove a WBS using Other Links → Projects → Click on WBS icon → “-” (see below)
Be sure this fully removes the person from the project but checking their Profile>Projects page and seeing it is gone there too

## Related PRS (if any):
To test this frontend PR you need to checkout the development branch in backend.

## Main changes explained:
Changes in Members.jsx and Member.jsx files

## How to test:
1.check into current branch
2. npm install and ... to run this PR locally
3. Clear site data/cache
4. login as Owner user -> Login into Owner's Dashboard
5. Select Other Links on top left of dashbaord -> Projects
6. Select members icon on any project with members. -> This will show project member list table. 
7. Open the user profile of the listed member. Check if the select projects exist in member's userprofile.
8. Come back to project member list. Check if the delete button exists for each member
9. Delete the member. Confirm it on the popup text. 
11. Crosscheck in deleted members userprofile page if the project still exist or not. 
12. Once the project member is deleted. userprofile of the member should not have project listed in its project tab. (Cross verification)

## Screenshots or videos of changes:
/home/snehalc/HGN/Photos/Week 11/video1084193701.mp4

2024-12-14 20:56 UTC, ShraddhaShahari approved these changes
Tested this PR and the given scenario is working fine as per the expectation, If we delete any project from user's profile then that username is removed from the project's members list. Also attached screenshots for the reference. 
<img width="1066" alt="Screenshot 2024-12-14 at 12 40 08 PM" src="https://github.com/user-attachments/assets/ae78ab50-8318-4ad5-b83d-a40b70c8879f" />

<img width="1087" alt="Screenshot 2024-12-14 at 12 43 36 PM" src="https://github.com/user-attachments/assets/2585c390-b78e-4b02-bb2d-cc8439bec01b" />
<img width="1472" alt="Screenshot 2024-12-14 at 12 49 59 PM" src="https://github.com/user-attachments/assets/b3297766-3519-4231-ba5d-726efb1802c9" />

2025-01-17 22:35 UTC, Maddila-Anjali commented
Works as mentioned. I initially added a test user and tried. The project exists in the bio section. Later when I deleted the person from the project it automatically gets removed from their dashboard projects section. Attached are the screenshots.
<img width="1297" alt="Screenshot 2025-01-17 at 4 32 51 PM" src="https://github.com/user-attachments/assets/c6a81b68-3eaf-4cb2-a5b1-ff0a1770e7df" />
<img width="1437" alt="Screenshot 2025-01-17 at 4 33 55 PM" src="https://github.com/user-attachments/assets/3788876b-368b-46da-84e2-5444005b1532" />

2025-01-17 23:18 UTC, Maddila-Anjali approved these changes

2025-01-18 22:01 UTC, Eveye2023 requested changes
The functions works well.  Just some little issues.

2025-01-18 22:01 UTC, Eveye2023 commented on src/components/Projects/Members/Member/Member.jsx
> +import { connect, useSelector } from 'react-redux';
This `useSelector` is not in use.

2025-01-21 00:58 UTC, lycan10 commented on src/components/Projects/Members/Member/Member.jsx
> +            onClick={e =>
Out of curiosity, why are the props not destructured?

2025-01-21 00:58 UTC, lycan10 commented on src/components/Projects/Members/Member/Member.jsx
>    const canUnassignUserInProject = props.hasPermission('unassignUserInProject');
Since hasPermission is already imported, why is it still being accessed via props?

2025-01-21 23:14 UTC, SnelPatare commented on src/components/Projects/Members/Member/Member.jsx
> +        <td className="members__unassign">
Hi Eve, The canUnassignUserInProject checks if the member exists or not. I deleted the condition because if the member is not at  all present it will be impossible to add that member in projects. So, I felt it was not in use. Secondly the canUnassignUserInProject will take a huge amount of time to search and check if member exists or not. So I directly preferred to delete the member in project

2025-01-21 23:15 UTC, SnelPatare commented on src/components/Projects/Members/Member/Member.jsx
>    const canUnassignUserInProject = props.hasPermission('unassignUserInProject');
This changes are not included in my commit

2025-01-21 23:22 UTC, SnelPatare commented on src/components/Projects/Members/Member/Member.jsx
> +            onClick={e =>
Hi, Since the prop is infrequently used I wanted to keep it simple and precise

2025-01-21 23:26 UTC, SnelPatare commented on src/components/Projects/Members/Members.jsx
> +                  <th scope="col" id="members__name">
Thank you for noticing, Made changes.

2025-01-21 23:26 UTC, SnelPatare commented on src/components/Projects/Members/Member/Member.jsx
> +import { connect, useSelector } from 'react-redux';
Thank you, made changes

2025-01-22 00:51 UTC, Eveye2023 approved these changes
Everything works well for me.

2025-01-22 22:17 UTC, ShraddhaShahari approved these changes
Reviewed this PR, and everything looks good.

2025-01-22 22:32 UTC, lycan10 approved these changes
I have tested the changes and they work as expected.

2025-01-24 15:27 UTC, vinayv-456 reviewed
The functionality is as expected but please clarrify my above doubt.
![image](https://github.com/user-attachments/assets/0a9bd09c-ad09-4c44-8d8d-f3f0ef7c3540)
![image](https://github.com/user-attachments/assets/9522cc43-af96-402e-8ced-dad0a2f314e9)

2025-01-24 15:27 UTC, vinayv-456 commented on src/components/Projects/Members/Member/Member.jsx
> +        <td className="members__unassign">
Hi SnelPatare, from what i understood from the code is that "canUnassignUserInProject" is looking for the user's permission if they can unassign or not. and unassign permission was not added to permission list of owner.
I feel you might need to add permission for unassigning project, so that the button is vissible.

2025-01-24 21:30 UTC, honglinchen0524 requested changes
Functionalities including: creating a project, adding members into a project, and removing members from the project works perfectly, and was able to reflect in both owner and member accounts. But there is a small issue (See video): when I was testing the "+All" button functionality when adding members to a project, I encountered significant UI performance issues. I see in your code: assignAll() uses Promise.all() to execute all assignment requests at once. Your current implementation fires multiple simultaneous API calls to assign all unassigned users to project, which overwhelm both the client and server when dealing with large user lists. 

I assume there's likely no practical use case where a project would need every single user assigned to it, so I recommend removing this bulk assignment functionality entirely to prevent the issues. However, if this feature must be retained, it should be refactored to process users in smaller batches  to prevent server overload.

https://github.com/user-attachments/assets/037ca56a-1f40-4114-a235-b45808a5e58f

2025-01-24 22:23 UTC, SnelPatare commented
Hi honglinchen0524, 
Thank you for reviewing my changes. I tried to recreate issue you faced in my system. But, I am not facing any of such issue in mine. Please find below video for reference. 

https://github.com/user-attachments/assets/a111e75e-c7e5-4ec6-81da-437c33901506

2025-01-24 23:20 UTC, honglinchen0524 approved these changes
I was able to remove a member from a project by clicking: Other Links → Projects → Click on WBS icon → “-” 
I also checked their profile and verified the person no longer is in the project.

2025-01-25 01:29 UTC, ziddigsm approved these changes
The functionality of deleting members from project works as expected and there are no performance issues.

https://github.com/user-attachments/assets/f27a0c35-68a0-4634-938c-58c017b86a0a

2025-01-25 06:57 UTC, one-community commented
Thank you all, merging!

2025-01-25 06:57 UTC, merged