fix projects active filter
OneCommunityGlobal/HighestGoodNetworkApp pull request #2865
Opened 2024-11-13 22:10 UTC by RishithaMamidala

# Description
 (PRIORITY TBD) Jinxiong: The Projects page “Active” filter does not work correctly (WIP Rishitha)
Other Links>Projects>Active filter
Select Active or Inactive.
None of the records are displayed. It should displayed the filtered result.

## Related PRS (if any):
This frontend PR is related to the development backend PR.

## Main changes explained:
- Updated src/components/Projects/Projects.jsx for the filter to work
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Other Links>Projects>Active filter
6. confirm if the active filter is working correctly

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/8eb33d69-5dec-4dca-8f52-a39c08c9ec59

2024-11-14 16:27 UTC, vijay10pk submitted a review, later dismissed
Changes are working as expected.
https://vijay-anand-pandian.neetorecord.com/watch/6360875c-0d4c-497e-b2cb-e7920ad04502

2024-11-15 00:07 UTC, SatyashanthiT commented
Working as expected. Great work.

https://github.com/user-attachments/assets/4c859fd1-7fc9-4795-ba83-1a0a85321aab

2024-11-15 07:11 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/b74a5fa6-5aa0-4827-bace-160db4c3ecda

2024-11-17 03:21 UTC, audreydieuanh approved these changes
The active filler is working correctly.

![test14](https://github.com/user-attachments/assets/1595f6a9-88ad-4034-858c-c74387ef10ed)

2024-11-17 06:11 UTC, RashmiKY98 approved these changes
Tested the functionality by changing the screen size, flipping between light and dark mode. No issue found.
![Screenshot 2024-11-17 000957](https://github.com/user-attachments/assets/dfafe810-c54b-4980-80e4-d0244e4d600e)
![Screenshot 2024-11-17 001033](https://github.com/user-attachments/assets/6334ba25-17b8-47e5-96b1-0fc080e5e87b)
![Screenshot 2024-11-17 001013](https://github.com/user-attachments/assets/487b3ae7-e8e0-4ad6-87a6-719a9289b278)

2024-11-17 06:31 UTC, abdel-lall submitted a review, later dismissed
LGTM. good job!

![Screenshot 2024-11-17 003020](https://github.com/user-attachments/assets/8a40dc48-7d58-4217-886a-86dace9943cc)

2024-11-17 06:37 UTC, anji-annavarapu approved these changes
https://github.com/user-attachments/assets/ce5f61f1-9b98-4203-8704-316a9f8d8556

Filter working fine as expected

2024-11-20 19:29 UTC, anirudhsk2107 approved these changes
The filter is working as expected. 
Tested for light and dark mode both. 
<img width="1657" alt="Screen Shot 2024-11-20 at 2 25 36 PM" src="https://github.com/user-attachments/assets/300142fb-3c55-480d-b89c-797af1fe4b97">
<img width="1649" alt="Screen Shot 2024-11-20 at 2 25 26 PM" src="https://github.com/user-attachments/assets/8283a125-56da-4028-baa2-c42cd31e14d2">
<img width="1650" alt="Screen Shot 2024-11-20 at 2 25 18 PM" src="https://github.com/user-attachments/assets/b3a05324-344a-431c-a2bf-4ef7ec36e1d8">

2024-11-23 04:17 UTC, SS-Reddys approved these changes
Changes are working as expected for both active and inactive in active filter.

![image](https://github.com/user-attachments/assets/a779d58b-2580-4c78-bc37-b16a3d3df963)


![image](https://github.com/user-attachments/assets/71e26e4a-edc4-4f8d-b009-1b2a65b0c2ac)

2024-11-29 22:13 UTC, ppsahu commented
I have tried to review this PR, however I am getting login issue for all the 3 accounts. If you have any fixes please let me know. It is happening for any branch I checkout. Please check the screenshot for reference.

<img width="1469" alt="Screenshot 2024-11-29 at 2 09 21 PM" src="https://github.com/user-attachments/assets/49d8bd03-01bb-4179-8cb5-fde36c15aad3">

2024-12-01 03:29 UTC, ppsahu commented
Update from my side: I have got my account issue resolved.

I have tested this PR and all the changes are working as expected. Below are the screenshots for reference.

![Screenshot 2024-11-30 at 7 28 45 PM](https://github.com/user-attachments/assets/8780d518-5a80-45d8-aa83-ccb76b6d1374)
![Screenshot 2024-11-30 at 7 28 39 PM](https://github.com/user-attachments/assets/ee388d43-c16c-4777-b200-18592b502b36)

2024-12-07 23:53 UTC, KurtisIvey commented
Hi there, I noticed this has a merge conflict on it. We'd love to get it moved to final review and merged asap once this merge conflict is resolved. Thank you for your hard work

2024-12-12 15:49 UTC, FayeLV commented
Hi, great job! The filter is working perfectly as expected.

https://github.com/user-attachments/assets/12c96d45-a3f3-4044-a555-0d79ce661b6e

2024-12-13 01:37 UTC, Lakshan-K approved these changes
The functionality works as expected. I tested the Active filter, and it correctly displays the filtered results. Great job on resolving this issue and ensuring the feature works seamlessly!
<img width="1440" alt="PR#2865" src="https://github.com/user-attachments/assets/1ce6c63a-aa35-4dfe-bcc8-25a5a8b6b721" />

2025-01-18 06:57 UTC, honglinchen0524 requested changes
Great job, the active filter works as intended! However, currently the project list renders all projects at once, which might impact performance as the number of projects grows. I recommend adding a paginated container for the project list and implement page navigation to help users view projects.


https://github.com/user-attachments/assets/410821e0-87b4-4763-a1b6-c2e134dae485

2025-01-23 04:55 UTC, RishithaMamidala commented
> Great job, the active filter works as intended! However, currently the project list renders all projects at once, which might impact performance as the number of projects grows. I recommend adding a paginated container for the project list and implement page navigation to help users view projects.
> 
>  PR2865.mp4

@honglinchen0524 
That is a great sugesstion, however it is out of scope for this PR.

2025-01-24 17:00 UTC, vinayv-456 approved these changes
Verified, Work as expected.
![image](https://github.com/user-attachments/assets/508bdbbc-2d9d-4ced-88c7-81c2d7fa4aa2)

2025-01-31 00:59 UTC, ziddigsm approved these changes
The filters are working as expected.


https://github.com/user-attachments/assets/fba70637-72f6-4bba-99bc-5af5f8c38058

2025-02-05 19:31 UTC, mikelambo7 approved these changes
Confirmed that the active filter is working as expected

https://github.com/user-attachments/assets/207b2158-af4b-463c-9bf6-3ef7462a9419

2025-02-09 03:05 UTC, vivshar commented
This worked as expected for both dark and light mode, and while page performance can be improved, its out of scope of this pr.

https://github.com/user-attachments/assets/2500fd6f-c8e6-4e53-bcb2-e6796b0b7e56


![image](https://github.com/user-attachments/assets/87597355-0bcc-4cd4-b4cd-8b163e46dfe1)

2025-02-09 06:41 UTC, merged