Ashish_Fix_Rehireable_Status
OneCommunityGlobal/HighestGoodNetworkApp pull request #2866
Opened 2024-11-13 23:20 UTC by AshishNags

# Description
Fix Rehireable status is updated in the frontend regardless of the response status
![image](https://github.com/user-attachments/assets/728f38f3-1815-4c9b-850a-6aeaf36f5ff5)

## Related PRS (if any):
This PR is related to the backend PR https://github.com/OneCommunityGlobal/HGNRest/pull/1148.
…

## Main changes explained:
- Updated updateRehireableStatus function in actions/userManagement.js
- Update userProfile.js to display error if backend doesn't return 200 status when updating rehireable status
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user/ user with Change Rehireable Status permission
5. go to dashboard→ User Management → search for the protected accounts
'[jae@onecommunityglobal.org], '[one.community@me.com]', '[jsabol@me.com]', '[devadmin@hgn.net]' , and access their profile.
6. verify you can't update the Rehireable status of any of the protected accounts.

## Screenshots or videos of changes:
Video in the link:
https://www.loom.com/share/1fc5f26e99ba44828e7cd7151b1453d5?sid=6d1fc2c9-4f35-4e3a-874b-711ee5d6c57f

![Screenshot 2024-11-08 224731](https://github.com/user-attachments/assets/58f241c4-7e58-4c79-85d9-4d33388cb9f9)

2024-11-15 02:06 UTC, manikittu810 approved these changes
Hello @AshishNags 
Everything is working as mentioned.
Thank you.
<img width="1920" alt="Screenshot 2024-11-14 at 6 04 53 PM (2)" src="https://github.com/user-attachments/assets/35e3a30e-a816-40c0-8fe4-840b9f2c4289">

2024-11-15 07:23 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/c20b8c30-108b-49f0-a2b2-f5f8fdcb8268

2024-11-17 05:46 UTC, RashmiKY98 requested changes
I was able to flip the status. Hence requesting changes.
I have ensured that the code has been pulled from the same repository and all the codebase is up to date. I had logged in as a admin user to test the feature.
![Screenshot 2024-11-16 234236](https://github.com/user-attachments/assets/037e986e-e979-4574-a3b4-84cba6ea2917)
![image](https://github.com/user-attachments/assets/6c94d123-2546-4867-b874-493643756574)

2024-11-17 06:10 UTC, anji-annavarapu approved these changes
https://github.com/user-attachments/assets/a2129e50-9061-4bc2-af51-cde110249b39

tested this pr its working as expected

2024-11-19 19:34 UTC, AshishNags commented
> I was able to flip the status. Hence requesting changes. I have ensured that the code has been pulled from the same repository and all the codebase is up to date. I had logged in as a admin user to test the feature. ![Screenshot 2024-11-16 234236](https://private-user-images.githubusercontent.com/118213564/386923048-037e986e-e979-4574-a3b4-84cba6ea2917.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNDUxMjUsIm5iZiI6MTczMjA0NDgyNSwicGF0aCI6Ii8xMTgyMTM1NjQvMzg2OTIzMDQ4LTAzN2U5ODZlLWU5NzktNDU3NC1hM2I0LTg0Y2JhNmVhMjkxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxOTMzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2ZmNWU5NjFjYzQwYmUzODg0MTFjNzU0YTM1MmI1ODE3NzhkM2YxMTc2ZDExNzM0NmQwNjk3MTI5ZjgwMjc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RAhf4f0klO4SPtBuy65kJBo-9nEtO1qN9d3jxi-BM8Y) ![image](https://private-user-images.githubusercontent.com/118213564/386923055-6c94d123-2546-4867-b874-493643756574.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNDUxMjUsIm5iZiI6MTczMjA0NDgyNSwicGF0aCI6Ii8xMTgyMTM1NjQvMzg2OTIzMDU1LTZjOTRkMTIzLTI1NDYtNDg2Ny1iODc0LTQ5MzY0Mzc1NjU3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxOTMzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjMwMTYzNTBmYmFmM2I3MmVkNjczZDVlOTcyNzg1NGM0MTdiZTM2YjdhNDAzNWFlNWZiOWRmZTliYzEzODE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jGuT7ZmqZFP9001koR76Akz8m6kH7gayqg-iXAfXGN8)

2024-11-19 19:49 UTC, AshishNags commented
> I was able to flip the status. Hence requesting changes. I have ensured that the code has been pulled from the same repository and all the codebase is up to date. I had logged in as a admin user to test the feature. ![Screenshot 2024-11-16 234236](https://private-user-images.githubusercontent.com/118213564/386923048-037e986e-e979-4574-a3b4-84cba6ea2917.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNDU0NjAsIm5iZiI6MTczMjA0NTE2MCwicGF0aCI6Ii8xMTgyMTM1NjQvMzg2OTIzMDQ4LTAzN2U5ODZlLWU5NzktNDU3NC1hM2I0LTg0Y2JhNmVhMjkxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxOTM5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODQ3MDU4MjkxZDY4NjQ2ZTY4ZjU5NmVhNzkzMTNhYzNkNTE5ZDVkMDA5MTk2Njg5NDU1ODU4MWE2ZTY1MmU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qKa6QcKOCGhniBerswa5_1c_LE2T2ayZI3JmLh4yT_g) ![image](https://private-user-images.githubusercontent.com/118213564/386923055-6c94d123-2546-4867-b874-493643756574.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNDU0NjAsIm5iZiI6MTczMjA0NTE2MCwicGF0aCI6Ii8xMTgyMTM1NjQvMzg2OTIzMDU1LTZjOTRkMTIzLTI1NDYtNDg2Ny1iODc0LTQ5MzY0Mzc1NjU3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxOTM5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDUxOTZiM2JiNmI4MGE3ZjgzZjc5NzI5NGFlYjZmNDQwMWI4MGQwMTQzYzIyOGRmYzk0YjQ0NTk0MTZkY2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.F2ij4WOr8juvms-Z_K2PRZkY7g4ElHuvFjqRFRKJrIo)

Hello @RashmiKY98 ,
I just want to confirm if you have followed the steps in the backend, this PR is related to the backend PR mentioned above, if you have followed those steps and still facing the same issue please reply to this comment, i will look into it.
Thank you.

2024-11-20 19:51 UTC, anirudhsk2107 approved these changes
The changes were working as expected 

<img width="1627" alt="Screen Shot 2024-11-20 at 2 52 38 PM" src="https://github.com/user-attachments/assets/8d6788bc-191a-4c58-a6d7-1b07e1e80cca">

2024-12-14 02:02 UTC, one-community commented
Thank you all, merging!

2024-12-14 02:02 UTC, merged