Yashwanth individual permission change show
OneCommunityGlobal/HighestGoodNetworkApp pull request #2868
Opened 2024-11-14 01:13 UTC by yashwanth170

# Description
The permission change log table only logs changes made to role, so I have added additional features to log permission changes made to individual account. Now the table shows latest logs of changes made to both individual and role

## Related PRS (if any):
This frontend PR is related to the #1149 backend PR.
To test this frontend PR you need to checkout the #1149 Backend PR.
…

## Main changes explained:
- When changes are made to indvidual or user, the function calls endpoint POST_USER_PERMISSION_CHANGE_LOGS to post changes made to permissions
- Created new endpoint GET_USER_PERMISSION_CHANGE_LOGS to fetch changes made to both individual and role

## How to test:
1. check into current branch, and check into backend branch Yashwanth_individual_permission_change_show_backend
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links → Permission Management → Make changes to a role or individual and verify that the table updates accordingly

## Screenshots or videos of changes:

## Note:
Test it across different user types, and let me know if I missed any expected conventions or if you have any other suggestions.

2024-11-15 01:55 UTC, manikittu810 reviewed
Hello @yashwanth170 
 I have tested this , and it is displaying the text Loading for a long time instead of a table and I hjave also tried using clearing the cache.
<img width="1913" alt="Screenshot 2024-11-14 at 5 52 42 PM" src="https://github.com/user-attachments/assets/84fef54f-4f99-4c5d-85d8-05fe1aff0565">

Thank you.

2024-11-15 16:03 UTC, yashwanth170 commented
> Hello @yashwanth170 I have tested this , and it is displaying the text Loading for a long time instead of a table and I hjave also tried using clearing the cache. <img alt="Screenshot 2024-11-14 at 5 52 42 PM" width="1913" src="https://private-user-images.githubusercontent.com/58840319/386426634-84fef54f-4f99-4c5d-85d8-05fe1aff0565.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2ODY2OTUsIm5iZiI6MTczMTY4NjM5NSwicGF0aCI6Ii81ODg0MDMxOS8zODY0MjY2MzQtODRmZWY1NGYtNGY5OS00YzVkLTg1ZDgtMDVmZTFhZmYwNTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDE1NTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhODVjZjBkZGRhMmI3YzJiMjU0ZWMxMThmMzA2OTUwYjRiNjc3ZTJmM2JiODRlYWU5ZjFlMDVhZTY0N2YzMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.de_OzLRlrBWN6WQKKnCIEOS1WElkUH0q8EDV5T4mEGA">
> 
> Thank you.

Hello,
Did you checkout the backend branch as well?

2024-11-16 03:10 UTC, nathanah requested changes
Most of this logic should be on the backend. The only frontend changes required should be accommodating the new info in the `permissionChangeLogTable`.

2024-11-16 03:10 UTC, nathanah commented on src/components/PermissionsManagement/UserPermissionsPopUp.jsx
> +          logPermissionChanges(logPermissionChangesUrl, permissionChangeLog);
```suggestion
```
This is not atomic. This request could fail after the permission change request succeeds, so it wouldn't show up in the history. If a dev wanted to test updating permissions manually with something like Postman, they could avoid also logging  those changes which could cause confusion or potential problems.
Logging permission changes should be part of the same API call as updating the user's permissions.

2024-11-16 03:10 UTC, nathanah commented on src/utils/URL.js
> +  POST_USER_PERMISSION_CHANGE_LOGS: `${APIEndpoint}/logPermissionChanges`,
```suggestion
```

2024-11-16 03:10 UTC, nathanah commented on src/components/PermissionsManagement/UserPermissionsPopUp.jsx
> +
```suggestion
```
This logic should be on the backend and part of the same API call as the update itself.

2024-11-16 03:10 UTC, nathanah commented on src/components/PermissionsManagement/UserPermissionsPopUp.jsx
> +    const logPermissionChangesUrl = ENDPOINTS.POST_USER_PERMISSION_CHANGE_LOGS;
```suggestion
```

2024-11-16 03:10 UTC, nathanah commented on src/components/PermissionsManagement/UserPermissionsPopUp.jsx
> +
```suggestion
```

2024-11-16 03:10 UTC, nathanah commented on src/components/PermissionsManagement/PermissionsManagement.jsx
> +        <PermissionChangeLogTable changeLogs={changeLogs} darkMode={darkMode} />
removing reverse?

2024-11-16 06:45 UTC, audreydieuanh requested changes
The table doesn't show, and I have done git checkout for backend PR #1149.
![test11](https://github.com/user-attachments/assets/e3edbccd-c0e9-48c8-a3c8-1cd411005d0d)

2024-12-21 07:36 UTC, nathanah requested changes
Not sure if this should be on the front-end or during logging on the back-end, but individuals should be labeled as "INDIVIDUAL: <Name>" according to instruction C. in your screenshot. Everything else looks good.
![image](https://github.com/user-attachments/assets/093a6717-c8d2-483b-8d85-4c2d4b62f77a)

2024-12-21 07:38 UTC, nathanah commented
> The table doesn't show, and I have done git checkout for backend PR #1149. ![test11](https://private-user-

You have to be logged into an Owner account to see the table.

2024-12-27 22:57 UTC, nathanah approved these changes

2024-12-29 04:01 UTC, one-community commented
Thank you all, merging!

2024-12-29 04:01 UTC, merged