Fix deactivation date logic and ensure proper behavior
OneCommunityGlobal/HighestGoodNetworkApp pull request #2869
Opened 2024-11-15 00:14 UTC by CillianRen

### **Description**
Fixes the issue where the deactivation date on the profile page is incorrectly displayed as "Invalid date" when the green button is clicked to deactivate an account. Now, the deactivation date will correctly show the last day the user logged time.

### **Fixes:**

Bug priority: Medium
Related task: "Fix deactivation date not showing when the green button is clicked on the profile page."
Main Changes Explained
Updated the logic for fetching and displaying the deactivation date:
Integrated a backend call to retrieve the last logged time for the user.
Ensured the End Date field displays the correct last logged time when the account is deactivated.
Adjusted fallback behavior:
If no logged time is available, the End Date will now default to the account creation date.
Verified display functionality in both light mode and dark mode.
**### How to Test**
Switch to this branch: Cillian_fix_deactivation_date_bug.
Run the project locally:
Clear browser cache and site data to ensure no stale data interferes with testing.
Steps to Test: a. Log in as an admin user. b. Navigate to the profile page of a user. c. Click the green button to deactivate the account. d. Verify that the End Date field correctly displays the last day the user logged time. e. Reactivate the account, then deactivate again to ensure consistency. f. Test this functionality in dark mode to ensure proper visibility.

**### Screenshots/Videos of Changes**
Include screenshots or a link to a video showing the following:
![image](https://github.com/user-attachments/assets/52a9f542-effd-4111-9474-5e72c76945f4)

The End Date correctly displaying the last logged time in both light and dark modes.
**### Notes**
This PR addresses the issue in the frontend; ensure the backend endpoint /time-entries returns accurate data for the user's last logged time.
The End Date logic falls back to the account creation date (createdDate) if no logged time is found.

2024-11-17 03:05 UTC, audreydieuanh approved these changes
The end date displayed correctly both in light mode and dark mode, even though I had to refresh the page after I changed.

![test134](https://github.com/user-attachments/assets/14f62bbd-c788-40f7-85bd-2e5bd4362ca3)

2024-11-17 05:18 UTC, anji-annavarapu requested changes
<img width="850" alt="Screenshot 2024-11-16 231010" src="https://github.com/user-attachments/assets/ceb93673-2b32-4b1f-89dc-ce4ec6f48698">
<img width="852" alt="Screenshot 2024-11-16 231032" src="https://github.com/user-attachments/assets/3598e2b2-00fd-40c5-af97-1e1a355a235f">
<img width="960" alt="Screenshot 2024-11-16 231143" src="https://github.com/user-attachments/assets/d699b9ff-b4b6-42a4-882f-446ede6a4bdd">

It shows the end date correctly, but after refreshing the page (instead of immediately clicking the green button), the format with time is not displayed.
correct me if I am wrong

2024-11-17 05:25 UTC, RashmiKY98 requested changes
Tested the feature to ensure correct deactivation date is provided. Reversed the changes to ensure other functionalities are not affected. The changes are reflected only after refreshing the screen. This is an inconsistency. Hence requesting changes.
![Screenshot 2024-11-16 231747](https://github.com/user-attachments/assets/2490686a-1a65-4898-a9c2-23ae5cc6cf6c)
![Screenshot 2024-11-16 231801](https://github.com/user-attachments/assets/676781c8-afbb-4fa4-ac28-90bcb38565bb)
![Screenshot 2024-11-16 231809](https://github.com/user-attachments/assets/b81d35d2-8b11-4ca8-b0db-8854fa63b239)
![Screenshot 2024-11-16 231832](https://github.com/user-attachments/assets/d3563f12-2e5b-4587-910a-1e5c05e7c5b2)
![Screenshot 2024-11-16 231851](https://github.com/user-attachments/assets/396b7ba0-2f64-40e3-aebb-a480b4063e46)
![Screenshot 2024-11-16 231908](https://github.com/user-attachments/assets/6504fd57-4371-4351-b4df-db6a015812a3)

2024-11-20 20:25 UTC, anirudhsk2107 requested changes
I set the final date and after refreshing it shows it correctly. 
But if i pause the user then it resets the final date and then when i make the active again then the final date shows NA
Hence requesting changes

<img width="660" alt="Screen Shot 2024-11-20 at 3 23 06 PM" src="https://github.com/user-attachments/assets/7844e1c2-63fc-4514-a79c-baf99ce23f67">
<img width="741" alt="Screen Shot 2024-11-20 at 3 22 51 PM" src="https://github.com/user-attachments/assets/f1351163-014c-4a32-9d1f-7fd67936620a">
<img width="542" alt="Screen Shot 2024-11-20 at 3 22 44 PM" src="https://github.com/user-attachments/assets/e7e58d00-1605-437b-896e-708f33af2492">
<img width="697" alt="Screen Shot 2024-11-20 at 3 22 32 PM" src="https://github.com/user-attachments/assets/357fb2ea-069a-4c6e-8f9b-00207437f5bc">
<img width="683" alt="Screen Shot 2024-11-20 at 3 22 01 PM" src="https://github.com/user-attachments/assets/0614755c-b4d3-49f2-87fe-56edd27d919d">

2024-12-20 21:38 UTC, CillianRen commented
> I set the final date and after refreshing it shows it correctly. But if i pause the user then it resets the final date and then when i make the active again then the final date shows NA Hence requesting changes
> 
> <img alt="Screen Shot 2024-11-20 at 3 23 06 PM" width="660" src="https://private-user-images.githubusercontent.com/114316759/388253056-7844e1c2-63fc-4514-a79c-baf99ce23f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MzA4OTMsIm5iZiI6MTczNDczMDU5MywicGF0aCI6Ii8xMTQzMTY3NTkvMzg4MjUzMDU2LTc4NDRlMWMyLTYzZmMtNDUxNC1hNzljLWJhZjk5Y2UyM2Y2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQyMTM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWM4MWI1M2FjNWNiMDRjYzEzNWFiZjIxMTM2ZGVhYmZkZWE1ZjRiOWUwNWNhYjI5MjIwYWM0ZWY3MmI0MWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6WilUmfCi94tNcWks9QnFG9iStraPEd_YGt0-gVTBzg"> <img alt="Screen Shot 2024-11-20 at 3 22 51 PM" width="741" src="https://private-user-images.githubusercontent.com/114316759/388253057-f1351163-014c-4a32-9d1f-7fd67936620a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MzA4OTMsIm5iZiI6MTczNDczMDU5MywicGF0aCI6Ii8xMTQzMTY3NTkvMzg4MjUzMDU3LWYxMzUxMTYzLTAxNGMtNGEzMi05ZDFmLTdmZDY3OTM2NjIwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQyMTM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWI2M2M0NzFkOWUxMzVjOGE2MDhhNzk3YWU4YzI3NmQwZDFkZThmZmRhYjg1OWQ4NGE4YTQwMzhjZTJhN2M2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qYT3mD6y7YvsgELBi6YU5zV7_hCWyhL-myY5ou9pCHQ"> <img alt="Screen Shot 2024-11-20 at 3 22 44 PM" width="542" src="https://private-user-images.githubusercontent.com/114316759/388253058-e7e58d00-1605-437b-896e-708f33af2492.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MzA4OTMsIm5iZiI6MTczNDczMDU5MywicGF0aCI6Ii8xMTQzMTY3NTkvMzg4MjUzMDU4LWU3ZTU4ZDAwLTE2MDUtNDM3Yi04OTZlLTcwOGYzM2FmMjQ5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQyMTM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWZmYjY1MmRiM2ZlNmNmZDAxZmQzZGQyOTJhNDY0ZTAxN2Q1Nzk0ODU4MGRjZWZjM2Y5NDYwMzk3MTU5ZWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hYpKWQw6BaRHglDgqt-SSQQYKBnKeLbG3WO10e92XDI"> <img alt="Screen Shot 2024-11-20 at 3 22 32 PM" width="697" src="https://private-user-images.githubusercontent.com/114316759/388253060-357fb2ea-069a-4c6e-8f9b-00207437f5bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MzA4OTMsIm5iZiI6MTczNDczMDU5MywicGF0aCI6Ii8xMTQzMTY3NTkvMzg4MjUzMDYwLTM1N2ZiMmVhLTA2OWEtNGM2ZS04ZjliLTAwMjA3NDM3ZjViYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQyMTM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDVhMzM5MzgyZGZhZWQzOTlhMmI1NmY4MDAyN2RkZmRiN2U2M2Q3ZGZkZDgxMWM4OTUzNGE0M2Y1MGE1M2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bBJ7-rXPI3EAL851GOGXOZP8eofLS2fldio3rGWXoL0"> <img alt="Screen Shot 2024-11-20 at 3 22 01 PM" width="683" src="https://private-user-images.githubusercontent.com/114316759/388253065-0614755c-b4d3-49f2-87fe-56edd27d919d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MzA4OTMsIm5iZiI6MTczNDczMDU5MywicGF0aCI6Ii8xMTQzMTY3NTkvMzg4MjUzMDY1LTA2MTQ3NTVjLWI0ZDMtNDlmMi04N2ZlLTU2ZWRkMjdkOTE5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQyMTM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDg1NGYwNjY4ZDdiNzNjZTgxMTk1ZWUxOTk1MTU4YjM2MTZiYjM0MGI4ZDcwNjBkM2FlODZhZmZiZGQ5OGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lYfH7XVvLuocbEphDhd7GdYRhNR2KAFqvh7OuE0hiw8">

2024-12-20 21:40 UTC, CillianRen commented
> I set the final date and after refreshing it shows it correctly. But if i pause the user then it resets the final date and then when i make the active again then the final date shows NA Hence requesting changes
> 
> <img alt="Screen Shot 2024-11-20 at 3 23 06 PM" width="660" src="https://private-user-images.githubusercontent.com/114316759/388253056-7844e1c2-63fc-4514-a79c-baf99ce23f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MzA4OTMsIm5iZiI6MTczNDczMDU5MywicGF0aCI6Ii8xMTQzMTY3NTkvMzg4MjUzMDU2LTc4NDRlMWMyLTYzZmMtNDUxNC1hNzljLWJhZjk5Y2UyM2Y2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQyMTM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWM4MWI1M2FjNWNiMDRjYzEzNWFiZjIxMTM2ZGVhYmZkZWE1ZjRiOWUwNWNhYjI5MjIwYWM0ZWY3MmI0MWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6WilUmfCi94tNcWks9QnFG9iStraPEd_YGt0-gVTBzg"> <img alt="Screen Shot 2024-11-20 at 3 22 51 PM" width="741" src="https://private-user-images.githubusercontent.com/114316759/388253057-f1351163-014c-4a32-9d1f-7fd67936620a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MzA4OTMsIm5iZiI6MTczNDczMDU5MywicGF0aCI6Ii8xMTQzMTY3NTkvMzg4MjUzMDU3LWYxMzUxMTYzLTAxNGMtNGEzMi05ZDFmLTdmZDY3OTM2NjIwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQyMTM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWI2M2M0NzFkOWUxMzVjOGE2MDhhNzk3YWU4YzI3NmQwZDFkZThmZmRhYjg1OWQ4NGE4YTQwMzhjZTJhN2M2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qYT3mD6y7YvsgELBi6YU5zV7_hCWyhL-myY5ou9pCHQ"> <img alt="Screen Shot 2024-11-20 at 3 22 44 PM" width="542" src="https://private-user-images.githubusercontent.com/114316759/388253058-e7e58d00-1605-437b-896e-708f33af2492.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MzA4OTMsIm5iZiI6MTczNDczMDU5MywicGF0aCI6Ii8xMTQzMTY3NTkvMzg4MjUzMDU4LWU3ZTU4ZDAwLTE2MDUtNDM3Yi04OTZlLTcwOGYzM2FmMjQ5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQyMTM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWZmYjY1MmRiM2ZlNmNmZDAxZmQzZGQyOTJhNDY0ZTAxN2Q1Nzk0ODU4MGRjZWZjM2Y5NDYwMzk3MTU5ZWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hYpKWQw6BaRHglDgqt-SSQQYKBnKeLbG3WO10e92XDI"> <img alt="Screen Shot 2024-11-20 at 3 22 32 PM" width="697" src="https://private-user-images.githubusercontent.com/114316759/388253060-357fb2ea-069a-4c6e-8f9b-00207437f5bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MzA4OTMsIm5iZiI6MTczNDczMDU5MywicGF0aCI6Ii8xMTQzMTY3NTkvMzg4MjUzMDYwLTM1N2ZiMmVhLTA2OWEtNGM2ZS04ZjliLTAwMjA3NDM3ZjViYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQyMTM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDVhMzM5MzgyZGZhZWQzOTlhMmI1NmY4MDAyN2RkZmRiN2U2M2Q3ZGZkZDgxMWM4OTUzNGE0M2Y1MGE1M2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bBJ7-rXPI3EAL851GOGXOZP8eofLS2fldio3rGWXoL0"> <img alt="Screen Shot 2024-11-20 at 3 22 01 PM" width="683" src="https://private-user-images.githubusercontent.com/114316759/388253065-0614755c-b4d3-49f2-87fe-56edd27d919d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MzA4OTMsIm5iZiI6MTczNDczMDU5MywicGF0aCI6Ii8xMTQzMTY3NTkvMzg4MjUzMDY1LTA2MTQ3NTVjLWI0ZDMtNDlmMi04N2ZlLTU2ZWRkMjdkOTE5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQyMTM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDg1NGYwNjY4ZDdiNzNjZTgxMTk1ZWUxOTk1MTU4YjM2MTZiYjM0MGI4ZDcwNjBkM2FlODZhZmZiZGQ5OGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lYfH7XVvLuocbEphDhd7GdYRhNR2KAFqvh7OuE0hiw8">

Thank you for the review! I’d like to clarify that my changes are focused solely on fixing the issue with the green button for deactivating an account, ensuring that the deactivation date displays correctly.

The "Set Final Day" functionality falls outside the scope of this PR. I believe that issue is being addressed in another PR by someone else. If needed, I’m happy to coordinate with the team to ensure no conflicts.

Let me know if further clarification is needed!

2025-01-04 20:47 UTC, closed without merging