Vijay Anand - Add unit test for timeEntriesReducer file
OneCommunityGlobal/HighestGoodNetworkApp pull request #2871
Opened 2024-11-15 04:09 UTC by vijay10pk

# Description
Unit tests for timeEntriesReducer.

## Related PRS (if any):
No related PRs.

## Main changes explained:
- Added a new test file timeEntriesReducer.test.js to ensure the timeEntriesReducer functions as expected.
- The list of test cases for timeEntriesReducer includes:
  - Returns the initial state when no action type is provided
  - Handles GET_TIME_ENTRIES_WEEK by updating the specified week with the provided payload
  - Handles GET_TIME_ENTRIES_PERIOD by updating the period with the provided payload
  - Handles ADD_TIME_ENTRY by adding a new entry to the specified week
  - Returns the current state for unknown action types

## How to test:
1. Check out the current branch.
2. Run npm install if necessary and npm test timeEntriesReducer.test.js.
3. Confirm all test cases pass without errors.

## Screenshots or videos of changes:
<img width="904" alt="image" src="https://github.com/user-attachments/assets/7f4a5acb-476f-476b-9e39-54e03a15769d">

## Note:
Include the information the reviewers need to know.

2024-11-15 05:04 UTC, nikhilpittala16 approved these changes
I have tested the PR and all the test cases have passed.
![Screenshot (238)](https://github.com/user-attachments/assets/d819dc45-820b-45fb-b024-8c003a47a3f0)

2024-11-15 22:26 UTC, SatyashanthiT commented
Tested and validated the unit tests for timeEntriesReducer in PR #2871. Verified that all test cases passed, ensuring the reducer handles scenarios

<img width="773" alt="image" src="https://github.com/user-attachments/assets/4567de0f-bd53-44c9-94ad-1c23148ea88b">

2024-11-16 05:48 UTC, linkhanthtel approved these changes
All test cases passed as expected. Nice Work!

<img width="1042" alt="#2871" src="https://github.com/user-attachments/assets/43cc2aa4-34a8-4bb2-9643-86c28bec2379">

2024-11-16 18:36 UTC, aaryaneil approved these changes
Tested the PR and all the test cases passed.
<img width="1140" alt="Screenshot 2024-11-16 at 10 36 24 AM" src="https://github.com/user-attachments/assets/d5e31f8e-2a9d-4dda-af03-46b57bfa0295">

2024-11-17 02:57 UTC, audreydieuanh requested changes
The test failed when I tested it.

![test13](https://github.com/user-attachments/assets/f5383985-f3ae-4a5e-b8bd-44567faae904)

2024-11-17 04:55 UTC, anji-annavarapu approved these changes
<img width="441" alt="Screenshot 2024-11-09 230153" src="https://github.com/user-attachments/assets/a859754f-b782-464e-93c4-d0a763467349">

All test cases passed successfully

2024-11-17 04:58 UTC, RashmiKY98 approved these changes
Verified that the test cases cover edge scenarios. No issues found. All the test cases passed.
![Screenshot 2024-11-16 225703](https://github.com/user-attachments/assets/5a3bdf51-86c7-440f-9c22-121f1dd26c33)

2024-11-20 00:00 UTC, anirudhsk2107 approved these changes
All tests have passed 

<img width="490" alt="Screen Shot 2024-11-19 at 7 01 33 PM" src="https://github.com/user-attachments/assets/edc89005-cfef-4a18-8335-a598d37340bf">

2024-11-22 09:14 UTC, beblicarl commented
All tests passed successfully

![image](https://github.com/user-attachments/assets/21c4026a-8d16-4261-870e-383d7e8a4366)

2024-11-22 09:15 UTC, beblicarl approved these changes

2024-12-28 17:41 UTC, neha3010 approved these changes
Tested the PR. All the test cases passed.
<img width="562" alt="Screenshot 2024-12-28 at 12 40 51 PM" src="https://github.com/user-attachments/assets/b7eb3a36-b522-4aec-bb87-b154d3779601" />

2025-03-16 23:35 UTC, one-community commented
Thank you all, merging!

2025-03-16 23:35 UTC, merged