Sheetal M - Add unit test for managingTeamsReducer
OneCommunityGlobal/HighestGoodNetworkApp pull request #2876
Opened 2024-11-17 03:27 UTC by sheetalmangate

# Description
Unit test for managingTeamsReducer

## Related PRS (if any):
No related PRs

## Main changes explained:
- Added a new file under reducers/tests called managingTeamsReducer.test.js
- The list of test cases for managingTeamsReducer
  - return the initial state when no action is specified
  - handles FETCH_PROJECTS_START action by returning status 200
  - handles RECEIVE_TEAMS action by returning status 200
  - handles FETCH_TEAMS_ERROR by returning fetching=false

## How to test:
1. Checkout the current branch
2. Run npm test managingTeamsReducer.test.js
3. Verify all test cases pass without any errors

## Screenshots or videos of changes:
![manging-teams-reducer-test](https://github.com/user-attachments/assets/a4a7ca09-9df5-4934-969d-67edb60748bc)

2024-11-17 07:26 UTC, mianmiantea2019 commented
All tests passed, good work 
![image](https://github.com/user-attachments/assets/bb392bfc-3045-4e38-891d-989050b85bc7)

2024-11-19 23:13 UTC, SatyashanthiT commented
Tested the managingTeamsReducer unit tests, and all cases passed without any issues. Everything is working as expected.

<img width="706" alt="image" src="https://github.com/user-attachments/assets/396c0301-3fa2-4eb9-9a9e-4c2ef35b1dbf">

2024-11-19 23:48 UTC, anirudhsk2107 approved these changes
All tests have passed 

<img width="507" alt="Screen Shot 2024-11-19 at 6 49 05 PM" src="https://github.com/user-attachments/assets/cd944eb4-b558-4203-91ef-ca7b42e6a572">

2024-11-20 02:58 UTC, vijay10pk approved these changes
All the test cases passed.
<img width="771" alt="image" src="https://github.com/user-attachments/assets/35f13fe3-3bbd-433c-ad14-905ee37a2f30">

2024-11-22 01:48 UTC, nikhilpittala16 approved these changes
I have tested the PR and all the test cases have passed.
![Screenshot (245)](https://github.com/user-attachments/assets/a526b3c1-cc59-498a-bd90-da0f6dc0bca7)

2024-11-22 09:30 UTC, beblicarl requested changes
All tests passed however there were errors in the console

![image](https://github.com/user-attachments/assets/5902a8a7-ff7f-4b25-852d-20a8347eb57a)

2024-11-24 06:50 UTC, RashmiKY98 approved these changes
Tested all the test cases. Reviewed the code changes. No issues found.
![image](https://github.com/user-attachments/assets/f4e2fcc6-6eaf-4b48-aace-59f9acf73ff8)

2024-12-28 22:53 UTC, neha3010 requested changes
Reviewed the PR. The test cases passed. But there's a console error. 
<img width="569" alt="Screenshot 2024-12-28 at 5 53 47 PM" src="https://github.com/user-attachments/assets/2d4c6eb0-f048-4c99-a341-886edb3f84ef" />

2025-05-17 23:25 UTC, sheetalmangate commented
> All tests passed however there were errors in the console
> 
> ![image](https://private-user-images.githubusercontent.com/68056104/388880700-5902a8a7-ff7f-4b25-852d-20a8347eb57a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDc1MjQwMzQsIm5iZiI6MTc0NzUyMzczNCwicGF0aCI6Ii82ODA1NjEwNC8zODg4ODA3MDAtNTkwMmE4YTctZmY3Zi00YjI1LTg1MmQtMjBhODM0N2ViNTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTE3VDIzMTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlY2E1NjU3YjdiNzYyYjI2OTRjMDBkZDgyNzM2ZDVjZTI0Y2EwZWExNzNiOWI2YzQxZWQ3YWJiYzZkNDg2NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._Xj-iTLMFUp2cUh4WTEhZD_YfL3uYtrlgQEeHIBmA0o)

I have committed the changes required to fix the console.log output shown in image.

2025-05-18 01:32 UTC, sheetalmangate commented
> I have committed the changes required to fix the console.log output shown in image.

2025-05-18 01:33 UTC, sheetalmangate commented
> Reviewed the PR. The test cases passed. But there's a console error. <img alt="Screenshot 2024-12-28 at 5 53 47 PM" width="569" src="https://private-user-images.githubusercontent.com/44228494/399128657-2d4c6eb0-f048-4c99-a341-886edb3f84ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDc1MzIyMDUsIm5iZiI6MTc0NzUzMTkwNSwicGF0aCI6Ii80NDIyODQ5NC8zOTkxMjg2NTctMmQ0YzZlYjAtZjA0OC00Yzk5LWEzNDEtODg2ZWRiM2Y4NGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTE4VDAxMzE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMDhkMDdkMDU4MmNkNDA1ODBhY2EyOWNhNzhhMWExYjRjODg3OGIzMTU3NGRjNjE2M2EyNWNkZDViYzAyNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2v6JVsS3uEFuZpZYX9gyAusCPzrHKbbMDl00MUDP4UU">

I have committed the changes required to fix the console.log output shown in image.

2025-05-20 23:55 UTC, one-community commented
Thank you all, merging!

2025-05-20 23:55 UTC, merged