huijie - schedule meeting bell notification
OneCommunityGlobal/HighestGoodNetworkApp pull request #2878
Opened 2024-11-17 06:49 UTC by metaphor987

# Description
![task](https://github.com/user-attachments/assets/b2324cb4-6c78-455a-bd97-2882cb1555a9)

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.

## Main changes explained:
1. Implement a new page for administrators, core team members, managers, mentors, and owners to schedule meetings with other members.
2. Implement Redux actions and reducer functions to retrieve scheduled meeting information and create modals for meeting notifications. As a result, when a user enters the app, notifications for their upcoming meetings will be displayed.

## Known bugs:
The bell does not ring for the first meeting notification displayed but rings for subsequent ones. This happens because browsers block the autoplay of audio or video until the user interacts with the page (e.g., by clicking or tapping). A possible solution could be to display a preview notification for the upcoming meeting, prompting the user to click a button on the page, which would then allow the bell to ring for future notifications.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Other Links→ Schedule Meetings
6. verify that an admin/owner user can fill in the information in the scheduling form. After clicking the "Submit" button, a message should display the details of the meeting the user has just scheduled.
7. Log in as one of the recipients of the scheduled meeting. If the meeting is scheduled within 3 days from the current date, the recipient should see notifications for the meetings they need to attend after logging in. After clicking the "Cancel" button, the current notification should no longer be displayed. Notifications for other meetings, if available, should then be shown.

## Screenshots or videos of changes:
![schedule meeting page](https://github.com/user-attachments/assets/313e8598-512f-457e-8562-22c96b5d070f)
![notification page](https://github.com/user-attachments/assets/58aa6847-fbdc-4be4-8fba-286a6fb3d675)

2024-11-29 22:33 UTC, ppsahu commented
I tried to review this PR, I am not able to load the login page, below is the screenshot for reference.

<img width="1469" alt="Screenshot 2024-11-29 at 2 32 07 PM" src="https://github.com/user-attachments/assets/e6a37a8b-5928-4a0e-ac23-e7b73aa93280">

2024-11-30 20:39 UTC, metaphor987 commented
Hi @ppsahu Thank you for reviewing. Could you please clear the localStorage and other site data/cache in the developer tools as shown here, and then test again? This may reinitialize Redux and include the updates.
<img width="1427" alt="Screenshot 2024-11-30 at 12 32 26 PM" src="https://github.com/user-attachments/assets/96b1a950-0c87-4662-9b29-450d575f4b0f">

2024-11-30 21:31 UTC, ppsahu commented
Hi @metaphor987 I cleared the local storage as you said, I was able to load the landing page, however, I am not able to login through any of the accounts. If you know of any fi
![Screenshot 2024-11-30 at 1 29 39 PM](https://github.com/user-attachments/assets/2feadd76-64ec-45ef-986c-0719bdd4e456)
x, please let me know. Below is the screenshot for reference.

2024-12-01 02:21 UTC, metaphor987 commented
Hi @ppsahu, 
Thank you for reviewing! I couldn’t reproduce this error on my side. I’ve just updated the PR to include the latest changes in Dev. Could you please test it again and check the console log for details about the "unexpected error" toast message? I appreciate your help!

2024-12-01 02:32 UTC, ppsahu commented
Hi @metaphor987 I got my account issue solved and I have tested this PR. I was able to schedule the meeting through dev account and added me as the recipient. However, I could not see any notification into my recipient account. Below are the screenshots for reference.

![Screenshot 2024-11-30 at 6 23 32 PM](https://github.com/user-attachments/assets/bb0a281a-cbf0-459e-8a28-1063bebdd2a2)
![Screenshot 2024-11-30 at 6 23 46 PM](https://github.com/user-attachments/assets/42348584-6a51-4cd7-8a6f-3fd3bf90bd91)
![Screenshot 2024-11-30 at 6 30 32 PM](https://github.com/user-attachments/assets/76390a5e-4626-411f-a5c4-de7efc3153c5)

2024-12-01 03:30 UTC, metaphor987 commented
Hi @ppsahu,

Thank you for testing! I think this meeting wasn't successfully saved to the database despite the confirmation message, as I cannot find this meeting record in the dev database. Could you please provide the frontend console log while attempting to save the scheduled meeting? Additionally, if the backend logs any error messages, could you take screenshots of them? Thank you!

I have also used my accounts to schedule two meetings for your recipient account, which you can check to see if any notifications are displayed.

2024-12-01 03:50 UTC, ppsahu commented
Hi @metaphor987 I still cannot see the notification on my account for the meeting. As per requested here is the screenshot for frontend console log. No error messages on the backend console log. Let me know if anything else is needed.
![Screenshot 2024-11-30 at 7 44 05 PM](https://github.com/user-attachments/assets/3370349c-63ea-4655-befd-82800e292684)

2024-12-01 04:33 UTC, metaphor987 commented
Hi @ppsahu,

Thank you for sending! Is it possible for you to get the HTTP response message in dev tool like this? So that I would know why there's a 404 error
<img width="1430" alt="3" src="https://github.com/user-attachments/assets/fced914d-28cb-469d-9039-26ebb2970c36">
<img width="1428" alt="1" src="https://github.com/user-attachments/assets/15a3eb41-a004-4ca4-8cc6-b673f17b08f9">

Additionally, may I confirm that you are on the latest version of both frontend and backend(#1154)? Thank you again for your assistance!

2024-12-01 04:42 UTC, ppsahu commented
Here you go..

![Screenshot 2024-11-30 at 8 37 42 PM](https://github.com/user-attachments/assets/a537d44f-2061-4268-9853-6df1bce94e34)
![Screenshot 2024-11-30 at 8 37 30 PM](https://github.com/user-attachments/assets/6e3ee6a4-eac2-4f05-866f-69ed01af16d1)

2024-12-01 05:13 UTC, metaphor987 commented
Hi @ppsahu, thanks for sending! May I confirm that you are on the latest version of the backend(https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1154)?

2024-12-01 05:20 UTC, ppsahu commented
Hi @metaphor987  I just rechecked again and found out that I was not on the latest branch in backend. I checked out and now it works fine for me. Apologies from my side. Below are the screenshots for reference.

![Screenshot 2024-11-30 at 9 18 34 PM](https://github.com/user-attachments/assets/35163562-f5c7-4d08-9494-d4f8e6dbdeba)
![Screenshot 2024-11-30 at 9 17 47 PM](https://github.com/user-attachments/assets/0ff152e9-ef6f-4128-ba41-4bf8ec26ff0b)

2024-12-01 05:26 UTC, metaphor987 commented
@ppsahu No worries, I have also modified the backend PR today and forgot to mention that. Thank you for your help on testing and sending the screenshots!

2024-12-22 02:52 UTC, mashpotato9 commented
I’ve tested this pr, and everything worked as expected. I received notifications for meetings within three days, but not for any meetings beyond that.
<img width="1248" alt="Screenshot 2024-12-21 at 9 51 49 PM" src="https://github.com/user-attachments/assets/4d11a2d5-1596-4774-9b2c-4b1560a30546" />
<img width="1119" alt="Screenshot 2024-12-21 at 9 52 01 PM" src="https://github.com/user-attachments/assets/308f1539-dbf8-4b8f-a4db-52bf9eb79723" />

2025-01-01 02:04 UTC, kobakvantrishvili requested changes
I left the same review on the backend PR.

I am having trouble selecting participants to schedule the meeting with. it's not letting me select the participant even if I type in the full name, therefore I am unable to test whether or not the notification is sent out. I'm not sure why this is happening. If I double click it selects the person and then quickly deselects him, when clicking once nothing happens. I tried this out in multiple browsers and in private mode and this front end issue still persists.

<img width="1198" alt="bug1" src="https://github.com/user-attachments/assets/c9cb9b95-9fa5-4244-85e3-231a5f0bef5b" />

2025-01-18 16:15 UTC, Sheehan20 reviewed
Critical Issues:

Participant Selection Bug:


Cannot select participants in scheduling form as reported by @kobakvantrishvili
Selection is immediately deselecting - this needs to be fixed before merge

Suggested Improvements:

Error Handling:


Add form validation as noted in known issues
Improve error message display for failed meeting saves
Add error boundaries for notification components


Performance & UX:


Consider throttling bell notifications to prevent audio overlap
Add loading states during API calls
Consider using a toast library for ephemeral notifications


Browser Compatibility:


Document autoplay audio limitations for bell notifications
Consider alternative notification approaches for browsers blocking autoplay


Code Structure:


Move notification logic from Header to separate component
Consider using React Query for data fetching
Add prop types for component props

The core functionality works when tested by multiple reviewers, but the participant selection bug must be fixed before merging.

2025-01-29 12:07 UTC, jeyanthi-sm requested changes
I want to refer to a backend pull request in this frontend PR, so I am using the following link: [Commented Here](https://github.com/OneCommunityGlobal/HGNRest/pull/1154#issuecomment-2603907987)

2025-02-19 19:38 UTC, AurHubertMax approved these changes
Meeting bell notification works as expected. Admin and Owner accounts can edit all parts of the meeting details. Participants will receive the bell notification as well. 
However, I found that when the participant has another notification they have not closed out yet, it will disable the meeting notification from coming through. This might be a slight oversight which is out of the scope of this implementation. 

https://github.com/user-attachments/assets/02eb555b-e93d-4cf3-b918-142be5fc06fa

2025-03-01 23:20 UTC, SSP24SCM16G approved these changes
UI functions well and allows smooth scheduling of meetings. The ability to add multiple participants at once is working as expected. However, there are a couple of issues that need attention. The form currently submits successfully even when no details are entered, which indicates a need for validation on the frontend. Additionally, the notes section displays text wrapped in <p> tags instead of rendering it as plain text, which affects readability. Addressing these issues will enhance the user experience and ensure proper data handling.
 
<img width="1470" alt="Screenshot 2025-03-01 at 17 02 40" src="https://github.com/user-attachments/assets/5adfcb3f-002c-4412-80d4-27a311c860c3" />
<img width="1470" alt="Screenshot 2025-03-01 at 17 07 44" src="https://github.com/user-attachments/assets/55a5f130-8172-44e6-81ba-f49fd98d73a1" />

2025-03-09 00:47 UTC, rishwa344 requested changes
The UI for the scheduling the meeting is working as expected but I am not able to see any notifications on the participant's dashboard.

<img width="597" alt="Screenshot 2025-03-08 at 4 34 15 PM" src="https://github.com/user-attachments/assets/e41579b2-7157-4074-ad30-0246ac05b549" />
And also i am getting this error while i click on the bell icon on the dashboard.
<img width="1440" alt="Screenshot 2025-03-08 at 4 38 21 PM" src="https://github.com/user-attachments/assets/39b50c91-c0f6-4c76-a4b8-f2d1698ff5d5" />

2025-03-16 05:44 UTC, kkkaiaa commented
PR reviewed. There are several issues occur during the testing. I'm unable to add any participants even if I input the full name. And here is the error message. 
And when I log in again, I do not receive the reminder. Probably because of failing to add the participants.
<img width="277" alt="截屏2025-03-16 上午1 43 36" src="https://github.com/user-attachments/assets/6c16ea18-031b-454b-85c8-eaf77d7acd74" />
<img width="772" alt="截屏2025-03-16 上午1 34 26" src="https://github.com/user-attachments/assets/50ee92ad-27af-41c2-ab81-1f22832bca31" />
<img width="723" alt="截屏2025-03-16 上午1 37 26" src="https://github.com/user-attachments/assets/7f5f4220-d77f-44c3-9a0f-e7dfce4ddc58" />

2025-03-29 03:27 UTC, humemah commented
Tested the meeting scheduling UI but couldn't select a participant.The form submits even when no participant is selected, which shouldn't happen.
![image](https://github.com/user-attachments/assets/6b945012-8183-4037-bd60-1909c104ed9b)

2026-02-01 02:54 UTC, rohanrastogi311 requested changes
Hi Huijie, 

Launch Error due to incorrect node version. 14 instead of 20. 

<img width="1728" height="265" alt="Image" src="https://github.com/user-attachments/assets/a9f00b91-a43c-47cd-9b26-81a4a6370868" />

2026-07-26 04:05 UTC, merged