Sheetal M - Add unit test for monthlyDashboardDataReducer.js
OneCommunityGlobal/HighestGoodNetworkApp pull request #2893
Opened 2024-11-24 03:38 UTC by sheetalmangate

# Description
Unit test for managingTeamsReducer

## Related PRS (if any):
No related PRs

## Main changes explained:
 - Added a new file under reducers/tests called monthlyDashboardDataReducer.test.js
 - The list of test cases for monthlyDashboardDataReducer
   - return the default value for monthly dashboard data  when no action is specified
   - handles GET_MONTHLY_DASHBOARD_DATA action by returning payload  

## How to test:
1. Checkout the current branch
2. Run npm test managingTeamsReducer.test.js
3. Verify all test cases pass without any errors

## Screenshots or videos of changes:
![monthlyDashboardDataReducer-testsuite](https://github.com/user-attachments/assets/10b680c1-e638-4c47-912e-91501c539117)

2024-11-24 05:28 UTC, RashmiKY98 approved these changes
Tested and verified that the test cases are valid and covers the scenarios.
![Screenshot 2024-11-23 232743](https://github.com/user-attachments/assets/aa6b9077-81fc-44ca-8566-3156200870d1)

2024-11-24 07:09 UTC, mianmiantea2019 commented
All test passed, good work

![image](https://github.com/user-attachments/assets/e1188cb2-58ab-4b07-8f2c-dfa56f5e24fb)

2024-11-28 01:44 UTC, SatyashanthiT commented
Tested the monthlyDashboardDataReducer unit tests. Verified scenarios including default value handling and payload return for the GET_MONTHLY_DASHBOARD_DATA action.

<img width="807" alt="image" src="https://github.com/user-attachments/assets/252cf5a0-0736-4d5a-9c75-d18871f83d33">

2024-11-29 11:56 UTC, beblicarl commented
All tests passed successfully and the code is great

![image](https://github.com/user-attachments/assets/461edb65-9143-4019-a4db-d10dd399986f)

2024-11-29 11:56 UTC, beblicarl approved these changes

2024-11-29 20:42 UTC, nikhilpittala16 submitted a review, later dismissed
I have tested the PR and all the test cases have passed.
![Screenshot (251)](https://github.com/user-attachments/assets/3d7a4dfe-ddf9-4f3f-99d9-550d2b0ef07e)

2024-12-04 15:39 UTC, anirudhsk2107 submitted a review, later dismissed
All test cases passed
<img width="617" alt="Screen Shot 2024-12-03 at 9 26 13 PM" src="https://github.com/user-attachments/assets/63ea55b4-0d68-4987-8a6b-c0b7650bb58b">

2024-12-29 03:41 UTC, neha3010 approved these changes
Reviewed the PR. All the test cases passed.
<img width="554" alt="Screenshot 2024-12-28 at 10 39 36 PM" src="https://github.com/user-attachments/assets/968b5833-6631-4f28-a8a0-e7f4008b42ec" />

2025-01-11 21:37 UTC, KurtisIvey requested changes
This pull request is almost there, but it’s missing a test for when the reducer starts with no initial state, which is important for how Redux sets up the default state. Adding this test will help make sure the reducer works perfectly right from the start.

Therefore, you will need to create a test that handles an undefined initial state. Once you've done so, you'll have my approval on this one.

2025-01-25 22:32 UTC, KurtisIvey approved these changes
Well done. You've got that one test added in there, so you've got my approval on this one. Thank you for implementing that change. All tests continued to pass as well


<img width="633" alt="image" src="https://github.com/user-attachments/assets/91dba8fd-02da-4cc0-9e10-06fbc2f11094" />

2025-05-12 03:25 UTC, one-community commented
Thank you all, merging!

2025-05-12 03:25 UTC, merged