Nanguan Add test for CreateNewBadgePopup.jsx
OneCommunityGlobal/HighestGoodNetworkApp pull request #2894
Opened 2024-11-24 03:59 UTC by lng2020

# Description
Add unit test for CreateNewBadgePopup.jsx

## Main changes explained:
Added a new file under reducers/tests called CreateNewBadgePopup.test.js
Test the following scenarios:
1. Rendering the component without crashing.
2. Updating the state when the badge name input changes.
3. Updating the state when the image URL input changes.
4. Updating the state when the description input changes.
5. Updating the state when the ranking input changes.
6. Updating the state when the badge type select changes.

## How to test:
1. Checkout the current branch
2. Run npm test CreateNewBadgePopup.test.js
3. Verify all test cases pass without any errors

## Screenshots or videos of changes:
![Screenshot_20241123_230009](https://github.com/user-attachments/assets/8bbb4c70-65c2-4d9f-ade9-3775684af4bf)

2024-11-24 05:22 UTC, RashmiKY98 approved these changes
Verified the test case and ensure that the test cases run and covers boundary scenario.
![Screenshot 2024-11-23 232107](https://github.com/user-attachments/assets/2dfc8da6-5b4f-4acb-8a8c-7a15ea4443a8)

2024-11-24 07:07 UTC, mianmiantea2019 commented
All tests passed, good work! 

![image](https://github.com/user-attachments/assets/f9ed60c5-61ee-4696-8891-7acfd7a77eae)

2024-11-28 01:42 UTC, SatyashanthiT commented
Tested the CreateNewBadgePopup component unit tests. Verified all scenarios, including input updates for badge name, image URL, description, ranking, and badge type.

<img width="766" alt="image" src="https://github.com/user-attachments/assets/95135fac-56e5-4ded-a43c-c936548f70ad">

2024-11-29 12:02 UTC, beblicarl approved these changes

2024-11-29 20:48 UTC, nikhilpittala16 submitted a review, later dismissed
I have tested the PR and all the test cases have passed.
![Screenshot (252)](https://github.com/user-attachments/assets/1c16647b-5c54-4e0d-a86f-3dca2c012793)

2024-11-30 08:58 UTC, jinxyou approved these changes
The test cases passed. Great job
![Screenshot 2024-11-30 005746](https://github.com/user-attachments/assets/c0707e36-8a08-4236-a387-fc81c348694a)

2024-12-01 07:01 UTC, mianmiantea2019 commented
All tests passed successfully 

![image](https://github.com/user-attachments/assets/c1109eca-2219-4b80-b000-e652fd7e6859)

2024-12-04 02:21 UTC, anirudhsk2107 approved these changes
All test cases are working 
<img width="663" alt="Screen Shot 2024-12-03 at 9 20 57 PM" src="https://github.com/user-attachments/assets/c6061479-b03c-4487-98f0-70ead0584c0a">

2024-12-15 04:13 UTC, Lakshan-K approved these changes
I tested the functionality described in this PR, and it works as expected.

All test cases in CreateNewBadgePopup.test.js passed successfully without any errors.

Verified that the component renders without crashing and the state updates correctly for all scenarios, including:
Badge name input changes.
Image URL input changes.
Description input changes.
Ranking input changes.
Badge type selection changes.

Great work on adding comprehensive unit tests for this component!

<img width="457" alt="PR#2894" src="https://github.com/user-attachments/assets/06d0c699-1f5b-4f19-a0ea-032867aa37c2" />

2024-12-21 19:47 UTC, neha3010 submitted a review, later dismissed
All the test cases passed. 
<img width="560" alt="Screenshot 2024-12-21 at 2 46 17 PM" src="https://github.com/user-attachments/assets/fddf4324-dbcc-40dd-a581-d73c0985e0a8" />

2024-12-28 16:05 UTC, KurtisIvey requested changes
Hi there, you've done great work so far on this test file, but I'm going to request changes for the following reasons.

1. Render Verification:
Add assertions for all key elements (e.g., input fields, dropdowns, buttons) to ensure they render correctly. Verifying just the "create" button alone isn't adequate

2. Conditional Logic:
Test visibility of fields that appear or change based on the selected badge type (e.g., showTotalHrs, showWeeks).

3. Button State:
Verify the "Create" button is enabled or disabled based on input validity.

4. Form Submission:
Mock the createNewBadge function and verify it is called with the correct data on form submission.

Once these tests are modified/added you'll have my approval.

2025-01-09 10:50 UTC, lng2020 commented
replace by #3027

2025-01-09 10:50 UTC, closed without merging