Vijay Anand - Unit test notificationReducer file
OneCommunityGlobal/HighestGoodNetworkApp pull request #2903
Opened 2024-11-27 04:15 UTC by vijay10pk

# Description
Added unit tests for the notificationReducer.

## Related PRS (if any):
No related PRs.

## Main changes explained:

- Added a new test file notificationReducer.test.js under the __tests__ directory.
- Test cases include:
- Returns the initial state when no state is provided.
  - Handles FETCH_USER_NOTIFICATIONS_REQUEST by setting loading to true and clearing error.
  - Handles FETCH_USER_NOTIFICATIONS_SUCCESS by populating the notifications array and setting loading to false.
  - Handles FETCH_USER_NOTIFICATIONS_FAILURE by updating the error field with the provided error message.
  - Handles FETCH_UNREAD_USER_NOTIFICATIONS_SUCCESS by updating the unreadNotifications array.
  - Handles MARK_NOTIFICATION_AS_READ_SUCCESS by removing the specified notification from the unreadNotifications array.
  - Handles RESET_ERROR by clearing the error field.

## How to test:

1. Check out the current branch.
2. Run npm install if necessary.
3. Execute npm test notificationReducer.test.js.
4. Verify that all test cases pass without any errors.

## Screenshots or videos of changes:
<img width="1014" alt="Screenshot 2024-11-26 at 11 08 44 PM" src="https://github.com/user-attachments/assets/de12f567-1046-47d0-89eb-ee67a8f292b1">

## Note:
Include the information the reviewers need to know.

2024-11-28 01:35 UTC, SatyashanthiT commented
I have reviewed and tested the unit tests for the notificationReducer. All scenarios, including initial state handling, success, and failure actions, were thoroughly validated, and all test cases passed successfully. 
<img width="776" alt="image" src="https://github.com/user-attachments/assets/b9b7c5f2-50bb-44fe-9652-c0d9951a8fcf">

2024-11-29 12:14 UTC, beblicarl commented
All tests passed successfully and the code is great

![image](https://github.com/user-attachments/assets/2b17fd4c-c906-4215-b15b-67a54b93cf59)

2024-11-29 12:14 UTC, beblicarl approved these changes

2024-11-29 20:55 UTC, nikhilpittala16 submitted a review, later dismissed
I have tested the PR and all the test cases have passed.
![Screenshot (254)](https://github.com/user-attachments/assets/285127eb-70f2-4687-bebd-ce9726be8739)

2024-11-30 08:49 UTC, jinxyou approved these changes
All test cases passed. Looks good to me.
![Screenshot 2024-11-30 004934](https://github.com/user-attachments/assets/d1df208d-ebd6-4959-8f60-8eeb62a5b871)

2024-11-30 11:16 UTC, linkhanthtel submitted a review, later dismissed
All test cases passed as expected! Nice work!

<img width="1158" alt="PR #2903" src="https://github.com/user-attachments/assets/11d82639-770f-42c3-8289-345c41a054e0">

2024-12-01 05:06 UTC, RashmiKY98 approved these changes
Tested the test cases. No issues found. The test cases covered the mentioned scenarios. 
![image](https://github.com/user-attachments/assets/92407de1-d7f4-4302-972f-41ef83c5f6ca)

2024-12-01 06:57 UTC, mianmiantea2019 commented
All test cases passed as expected! Nice work!

![image](https://github.com/user-attachments/assets/ffd9ef4c-7f2b-4335-a712-83ed06b6a5b5)

2024-12-03 22:36 UTC, pallavithorat commented
I have reviewed the PR, and all test cases have been successfully passed.
<img width="848" alt="PR#2903" src="https://github.com/user-attachments/assets/8e6eaf8b-c56a-455f-8586-5cfb3524e5e9">

2024-12-05 19:29 UTC, anirudhsk2107 approved these changes
All tests have passed 

![Screenshot 2024-12-05 142824](https://github.com/user-attachments/assets/4ef5dc6b-9f62-4101-9d5e-8cf6b9d351f1)

2024-12-06 07:01 UTC, NazaninHashemian approved these changes
I ran the tests (npm test notificationReducer.test.js) locally, and all 7 cases passed successfully.
![3](https://github.com/user-attachments/assets/bab6d2c1-48b6-479a-b7ef-cb8a0ed0dd9d)
![1](https://github.com/user-attachments/assets/deeddbbd-3c15-4be3-8353-ee63f914786f)
![2](https://github.com/user-attachments/assets/02595c9b-47af-4830-bef1-e9ac3731291b)

2024-12-19 19:30 UTC, neha3010 submitted a review, later dismissed
All the test cases passed.
<img width="570" alt="Screenshot 2024-12-19 at 2 28 48 PM" src="https://github.com/user-attachments/assets/71b42869-b28f-45c8-810f-8d5878364c89" />

2024-12-21 03:42 UTC, khushijain03 submitted a review, later dismissed
All the test cases have passed the PR works as described.

<img width="860" alt="Screenshot 2024-12-20 at 10 41 18 PM" src="https://github.com/user-attachments/assets/1c8e5fc0-264e-4abd-b3b1-d2a87ab0c602" />

2025-01-18 19:16 UTC, KurtisIvey approved these changes
great test file as usual. Fantastic work. great coverage and tests everything that should be tested on a base level

![image](https://github.com/user-attachments/assets/6d3792a1-3e27-4ade-a750-5f6cb04d8d7a)

2025-01-18 19:22 UTC, KurtisIvey requested changes
Just noticed the commented out cases. We don't appear to have those in the reducer, so I'm going to request changes to get those deleted out of the test file as they don't exist in the reducer.

2025-03-16 02:07 UTC, vijay10pk commented
> Just checking back in on this one as there has been no activity from you on it, but you've been initiating new pull requests.
@KurtisIvey,
removed the extra test cases. Please review and approve.
![Screenshot 2025-03-15 at 10 06 27 PM](https://github.com/user-attachments/assets/ea3abc75-d9c5-443f-927a-8a2a0c958d8f)

2025-03-17 02:52 UTC, one-community commented
Thank you all, merging!

2025-03-17 02:52 UTC, merged