Ramakrishna Fix refresh function when deleting and making people inactive
OneCommunityGlobal/HighestGoodNetworkApp pull request #2907
Opened 2024-11-28 20:36 UTC by Ramaruva

# Description
![image](https://github.com/user-attachments/assets/70bc88aa-f630-412c-a114-f1d856f50ee9)

Or Implements # (WBS) 

## Related PRS (if any):
Please use latest backend development branch to test this PR
…

## Main changes explained:
- Moved code in componentDidMount to separate reusable method so that we get latest userprofile date whenever necessary in UserManagement.jsx
- Updated the DropDownSearchBox.jsx and usersTeamsTable.jsx to fix some warnings which is not related to this fix

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user or any another user who has permission to visit the user management and add/delete users
5. go to dashboard→ other links -> user Management 
6. create couple of dummy users for this PR testing purpose
7.Now, try deleting those users and observe that the user data disappears from the table view without requiring a page refresh.
8. Now, try activating or deactivating any user and observe that the active/inactive color changes without requiring a page refresh.

2024-11-29 22:21 UTC, nikhilpittala16 submitted a review, later dismissed
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/7a3126c4-7c21-4559-a96e-9d4729d3a908

2024-12-08 01:08 UTC, Jingyii800 approved these changes
I tested this feature and it worked as expected. The deleted/inactivated result can be displayed real-time without refreshing. But it needs to wait several more seconds.

https://github.com/user-attachments/assets/d6920f9c-74fb-4e17-a2a9-ffcc2059cf68

2024-12-08 01:45 UTC, Lakshan-K submitted a review, later dismissed
The functionality works as expected! When a user is deleted, the data is removed from the table without needing a manual refresh, which is great. However, I noticed a slight delay in the deletion process. The delay is long enough that it might prompt someone to want to refresh the page. If there’s a way to optimize or speed up the deletion process, it would improve the user experience. Overall, excellent work on ensuring the feature functions correctly! 🎉


https://github.com/user-attachments/assets/6c5151ba-31ed-4cad-bad7-143f5799cb03

2024-12-12 00:31 UTC, pallavithorat commented
During testing, confirmed that user deletion functionality works as expected, with users being removed from the table view without page refresh. However, encountered an "unexpected error" when attempting to activate/deactivate users
<img width="1470" alt="Screenshot 2024-12-11 at 4 25 31 PM" src="https://github.com/user-attachments/assets/0844f478-3ec4-48a8-84fe-618cc4ed097e" />
<img width="1470" alt="Screenshot 2024-12-11 at 4 26 22 PM" src="https://github.com/user-attachments/assets/8f205d93-611f-4b67-8d90-74982eb4d8b6" />
<img width="1470" alt="Screenshot 2024-12-11 at 4 27 22 PM" src="https://github.com/user-attachments/assets/9da5e390-aaa2-4e9c-91ff-3193b3945b4d" />

2024-12-14 21:30 UTC, ShraddhaShahari reviewed
Tested this PR and everything is working as expected.
Please check the screenshots attached for reference.
<img width="1708" alt="Screenshot 2024-12-14 at 1 26 42 PM" src="https://github.com/user-attachments/assets/3448205a-6524-4968-9858-b10225e586b5" />
<img width="1699" alt="Screenshot 2024-12-14 at 1 27 46 PM" src="https://github.com/user-attachments/assets/11080dbc-58ee-4277-9b46-3f48b6561b23" />
<img width="1709" alt="Screenshot 2024-12-14 at 1 27 29 PM" src="https://github.com/user-attachments/assets/8944a820-6393-4d1e-925f-edbeb28a06b9" />

2024-12-17 18:39 UTC, anirudhsk2107 reviewed
The functionality works as expected but the only things is that the change in status or deleting a user reflects after some time without refresh. It does not happen immediately after we perform the action  

![Screenshot 2024-12-17 133822](https://github.com/user-attachments/assets/949b882e-812d-406b-9f27-2d918c8a5a58)

2025-02-01 22:37 UTC, vinayv-456 requested changes
These are already fixed in this [PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/3028/)

[repeated PR]
I feel these changes are not required, most of the changes are parallely maintaing the state updations locally instead of using the redux state(updated from APIs)

this can be simple fixed by checking if there is difference in allUserProfiles by comparing with redux state. and triger the componentDidUpdate as done in the above PR mentioned.
const userProfilesChanged = prevProps.state.allUserProfiles.userProfiles !== this.props.state.allUserProfiles.userProfiles;

2025-02-10 15:27 UTC, Peter-Nie2003 approved these changes
The code work as what description expected. Well done!

https://github.com/user-attachments/assets/9cac2e97-7a64-4573-b45c-7e0072e49be8

2025-02-13 21:17 UTC, Ramaruva commented
> These are already fixed in this [PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/3028/)
> 
> [repeated PR] I feel these changes are not required, most of the changes are parallely maintaing the state updations locally instead of using the redux state(updated from APIs)
> 
> this can be simple fixed by checking if there is difference in allUserProfiles by comparing with redux state. and triger the componentDidUpdate as done in the above PR mentioned. const userProfilesChanged = prevProps.state.allUserProfiles.userProfiles !== this.props.state.allUserProfiles.userProfiles;

Hi @vinayv-456 
I haven't introduced any local state in the component. Instead, I added an async function to the existing flow because, whenever a user deletes or deactivates another user, two API calls are made immediately: the first for the update (PUT request) and the second for fetching the latest data (GET request). Previously, without using `async`, the GET request would run in parallel, retrieving the Redux state with outdated data. By making the function asynchronous, I ensure that the latest data is fetched from the Redux state before proceeding.

2025-02-14 00:57 UTC, vinayv-456 commented on src/components/UserManagement/UserManagement.jsx
> +    this.getFilteredData(
Hi @Ramaruva, this is what i mean about having duplicate state running which would be out of sync with the redux store. this is already been during "updateUserStatus" action, also please refer the PR i mentioned just refetching the userprofiles by comparing the userprofiles will fix all these issues.

2025-02-17 21:37 UTC, AurHubertMax approved these changes
Feature works as expected. I created 2 new users with volunteer and manager role and filled in the sections randomly. Setting the user's active/inactive status updates it dynamically, and stores the status after refresh. Deleting the user is also displayed dynamically, and persists after page refresh as well.

https://github.com/user-attachments/assets/bc64f5ac-55d4-4426-b39b-f98c86b6a2de

2025-02-18 20:51 UTC, Ramaruva commented on src/components/UserManagement/UserManagement.jsx
> +    this.getFilteredData(
Hi
Yes, I have reviewed the PR. It appears that we cannot directly compare two objects using:
const userProfilesChanged = prevProps.state.allUserProfiles.userProfiles !== this.props.state.allUserProfiles.userProfiles;
Even if the data remains the same, object references may differ, leading to unexpected results. To address this, I attempted to update the userProfiles data within the component itself.
![image](https://github.com/user-attachments/assets/5fcd15fc-c019-4aa8-98a8-1ab9e0999879)

2025-02-19 00:21 UTC, vinayv-456 commented on src/components/UserManagement/UserManagement.jsx
> +    this.getFilteredData(
@Ramaruva , there would be no need to have any code changes, code at development would update the list after user inactive and delete operations or any userprofiles updations.

2025-02-19 20:07 UTC, Ramaruva commented on src/components/UserManagement/UserManagement.jsx
> +    this.getFilteredData(
Got it

2025-03-17 01:32 UTC, vasavi-139 approved these changes
Functionality works as expected. 

https://github.com/user-attachments/assets/d0ea766e-01e5-475f-ac37-dd8027bb31a1

2025-03-29 21:17 UTC, myeeli approved these changes
I have checked out the current PR, created a new user, and tested inactivating the user. I could see the status change immediately. Similarly, I deleted the user, and it was removed without needing to refresh the page.

<img width="950" alt="PR 2907 - 1" src="https://github.com/user-attachments/assets/2efd9a1e-58cf-4be6-88ed-e83d02a8739f" />
<img width="948" alt="PR 2907 - 2" src="https://github.com/user-attachments/assets/fac55e76-62e2-4c2d-9c9e-881d8e51772c" />
<img width="899" alt="PR 2907 - 3" src="https://github.com/user-attachments/assets/7800b5c6-c570-4d94-886d-012781d28ad8" />

2025-07-13 02:40 UTC, Babu-kota approved these changes
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/901ff146-ae27-49ce-9a56-9d564a15ccb5

2025-09-28 22:53 UTC, closed without merging