Start/End date format, validation bug & date picker overflow issue fix
OneCommunityGlobal/HighestGoodNetworkApp pull request #2915
Opened 2024-12-03 21:15 UTC by anirudhsk2107

# Description
1. Navigate to  Other Links → Projects → WBS → Click on WBS name → Add Task
Bug: When the End Date is set earlier than the Start Date, the error message 'Due Date must be greater than Start Date' appears for both fields, but it should only appear for the End Date. 
![Start_Date_Bug_Fix_1](https://github.com/user-attachments/assets/01c01413-85e8-43e5-a61a-5373a294052b)

2. Navigate to  Other Links → Projects → WBS → Click on WBS name → Task Edit → Edit
Bug: When the Start Date and End Date are corrected in the Update Task modal (with the Start Date set earlier than the End Date), error messages are still displayed for both dates. 
![Start_Date_Bug_Fix_2](https://github.com/user-attachments/assets/25a91376-8a5d-495d-ba25-5d39cd9305d6)

3. Navigate to  Other Links → Projects → WBS → Click on WBS name → Task Edit → Edit
Bug: When the End Date is updated to a date earlier than the Start Date, I was able to save the incorrect updates despite the error messages being displayed.
![Start_Date_Bug_Fix_3](https://github.com/user-attachments/assets/43a8643c-256a-47d2-8986-3fc44ca87c17)

4. Navigate to  Other Links → Projects → WBS → Click on WBS name → Task Edit → Edit
Bug: When opening a task for editing with incorrectly set dates(see image above), the End Date appears as unspecified (the default date is shown in the End Date field in the image below).
The format of the Start Date does not match the format of the End Date in the Edit Task modal.
![Start_Date_Bug_Fix_4](https://github.com/user-attachments/assets/8f980ce9-52f4-4b17-adfd-979a1dc301c0)

5. Also Fixed the appearance for the date picker in the modal. 
In the same page, while opening the date picker there used to be additional space added to the modal. 

## Related PRS (if any):
Preciously [PR 2812](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2812) was raised for the same bugs. Due to issues in merge conflict, raising a new PR with the updated fix.

## Main changes explained:
- Added error message validation in EditTaskModal.jsx for Start Date and End Date, ensuring users input correct date values.
- Fixed error messages persisting on closing or minimizing the modal by resetting state and clearing errors using the useEffect hook.
- Fixed the format issue for start date when clicking on "Edit"
- Date picker appearance adjusted. The white space is no longer added to the modal.

## How to test:
1. Check into current branch
2. Do npm install and run this PR locally
3. Clear site data/cache
4. Log as owner/admin user
5. Go to dashboard→ Projects → WBS -> Select Task
6. Edit any task (Add a new one if no tasks are available) 
7. Check if the edit allows the start date to be more than the end date. 

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/037c866b-1eb2-4884-957c-830f69eb532d

## Note:
The add task page can be navigated to here in [this video](https://www.loom.com/share/8bc672c323b64955aac4bce46c3794aa?sid=b05f5604-87cb-4ca1-80b8-49bd823893ee)
This PR is related to front end [PR 2335](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2335). Same bugs were fixed in the Add Task modal.

2024-12-04 07:34 UTC, ppsahu commented
I have tested this PR and all the changes are working as expected. I noticed one minor difference, when the pop up window appears after clicking edit, at the bottom there is a slight UI change in the Endstate section, like the white border changes to transparent. I did not see that in the video above that was put in the description. Otherwise, everything is good. Below is the screen recording for reference. I hope it helps.

https://github.com/user-attachments/assets/a66dfdee-39cd-4034-afaa-449cee57114b

2024-12-05 22:58 UTC, nikhilpittala16 approved these changes
I  have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/2afcbd58-5689-4777-b91a-bf489b41f0b9

2024-12-06 23:28 UTC, ShraddhaShahari reviewed
I have tested this PR and all the changes are working as expected. Below is the screenshot for reference.

<img width="539" alt="Screenshot 2024-12-06 at 3 19 08 PM" src="https://github.com/user-attachments/assets/377b9751-569b-4cb8-86a3-1f1276fbf9f6">
<img width="588" alt="Screenshot 2024-12-06 at 3 21 03 PM" src="https://github.com/user-attachments/assets/3ef0b2a8-f3a2-4c78-b203-faabb312b2b9">

2024-12-07 07:29 UTC, SammanBaidya approved these changes
The changes have been reviewed and tested successfully. Everything is working as expected, and I did not encounter any appearance issues, which appear to have been fixed. I have uploaded a short video of the testing process along with screenshots for reference

[Review2.webm](https://github.com/user-attachments/assets/41a45ad9-e508-4596-b74d-8aabf913dd76)
![PR#2925](https://github.com/user-attachments/assets/5b8cea0b-2829-4b28-9e0d-7cb0fefa6cfc)
![PR1 2 #2925](https://github.com/user-attachments/assets/49dadebe-6bea-4ae2-8b9a-49c349062ab9)
![PR1 3 #2925](https://github.com/user-attachments/assets/da14f9bf-9d14-4bdd-a8fd-5738c592140a)

2024-12-07 22:40 UTC, FayeLV commented
All fixes functioned as expected. Date validation, error handling, and UI improvements were successfully implemented and verified. No additional issues were found during testing.


![Snipaste_2024-12-07_16-36-37](https://github.com/user-attachments/assets/ddd6432f-2458-4739-a2aa-da9da1a5fe49)

2024-12-08 00:57 UTC, Jingyii800 approved these changes
Hi, I have tested this feature and it worked as expected. In "adding new task" or "editing task", it does not allow the start date to be more than the end date and the error message displays correctly, and cannot update/save the changes without correct date.

https://github.com/user-attachments/assets/9fdc3207-946e-4786-8b34-055909cf21ef

2024-12-08 03:17 UTC, Lakshan-K requested changes
The functionality works as expected in most cases, but I noticed an issue when entering a start date that's after the end date (e.g., Dec 8 as start date and Dec 7 as end date). Initially, the error message "Due date must be greater than end date" appears, and the task can't be updated. However, if I change the start date to a valid date like Jan 8, keeping the end date as Dec 7, I am then able to update the task with a start date that's still after the end date.

This behavior needs to be fixed, as the validation should consistently prevent a start date that’s after the end date.

https://github.com/user-attachments/assets/6bdfd777-a8a2-42f5-88a5-3069e3c9d4d6

2024-12-11 00:40 UTC, anirudhsk2107 commented
Hi @Lakshan-K,

Thank you for pointing out the error. I have pushed a fix for it
Please try again

2024-12-11 23:42 UTC, pallavithorat commented
I have reviewed PR and all changes are working as expected.
<img width="1470" alt="Screenshot 2024-12-11 at 3 35 31 PM" src="https://github.com/user-attachments/assets/6cfbe3e4-c285-400d-af6c-8cab63dabf57" />
<img width="1470" alt="Screenshot 2024-12-11 at 3 35 57 PM" src="https://github.com/user-attachments/assets/02ee3e7e-8bc9-4933-8596-c0d94a7ba019" />

2024-12-13 03:59 UTC, CodewithKoushica requested changes
I tried with start date in the year 2025 and end date in the year 2024, it doesn't throw any error message it accepts the range and allows to update it.
Please check for this issue. 

https://github.com/user-attachments/assets/5b358597-0f95-4079-9fef-274a1ff77072

2024-12-16 21:04 UTC, anirudhsk2107 commented
@CodewithKoushica 

I had pushed a fix for it. Can you please fetch the latest code and try again

2024-12-24 21:29 UTC, Lakshan-K approved these changes

2024-12-29 05:54 UTC, neha3010 requested changes
Reviewed the PR. There's one issue I noticed. When the start date is in Dec and end in Jan next year its saying the end date should be greater than the start date. 
I'm attaching the screen recording for reference.

https://github.com/user-attachments/assets/5ffcaaa7-636a-4280-9197-a7654116c1f8

2025-01-26 00:54 UTC, honglinchen0524 submitted a review, later dismissed
There is an issue with cross-year date comparisons. When setting a start date in any date in a year and an end date in any date of the following year, it raises  the "Due Date must be greater than Start Date" error. 
I think it's because your current implementation does string comparisons of dates ( "2023-12-31" > "2024-01-01") rather than comparing actual Date objects. Try do that instead.

![image](https://github.com/user-attachments/assets/10a37879-49ad-411f-8730-ff3b359bbd85)

2025-02-05 18:16 UTC, mikelambo7 approved these changes
Tested and verified that the changes work as expected

https://github.com/user-attachments/assets/360e217a-957c-4503-8c3c-8a4e1b82f0b4

2025-02-06 06:07 UTC, yany960 submitted a review, later dismissed
Everything else works as expected, but an issue occurs when the start date and end date span across different years.
<img width="490" alt="image" src="https://github.com/user-attachments/assets/0708b2b9-e7ef-4537-b221-8b44f6909a77" />

2025-02-08 07:44 UTC, vivshar commented
Fix for dates within same year work fine but  cross year comparison doesnt seem to work properly. Attached video

https://github.com/user-attachments/assets/72fe4310-e724-4993-9c69-a324b0e35bef

2025-02-19 18:32 UTC, AurHubertMax requested changes
The fix works as expected when the dates are in the same year, but behaves incorrectly when the start date and end date have different years. 
For example, setting start date at x/x/25 and the end date at x/x/26 will trigger the `setEndDateError` to true. 
I think it's because the dates are being compared as a `string` type, instead of a `Date` type, which could be compared incorrectly.

https://github.com/user-attachments/assets/00ce58dc-545f-44f1-9b4b-34ed2559ffd9

2025-03-29 21:34 UTC, myeeli approved these changes
I have reviewed the PR and the date selection is working as expected.

<img width="311" alt="PR 2915" src="https://github.com/user-attachments/assets/c4c935a3-c974-4ca0-8a37-89ec99a910a5" />

2025-06-29 14:14 UTC, Venk-rgb requested changes
Tested the PR in the frontend. Changes do not work as expected. Adding screen recording of the same. Please check!

Uploading Screen Recording 2025-06-29 at 10.11.27 AM.mov…

2025-06-30 22:01 UTC, Saicharan1505 approved these changes
Tested PR-2915. All date validation bugs in Add/Edit Task modals are resolved. Error messages now behave correctly, invalid inputs are blocked, date formats are consistent, and the date picker UI no longer causes layout issues. Everything is working as expected.

![2915 #1](https://github.com/user-attachments/assets/a83a8ced-69c9-4951-9b12-1ee82d3efb00)
![2915 #2](https://github.com/user-attachments/assets/8bd1eaa5-08c8-4a69-a964-0d0bf45dc03f)
![2915 #3](https://github.com/user-attachments/assets/883b59b6-0111-4829-a560-c0b83ce6d4f9)

2025-07-01 00:02 UTC, one-community commented
Thank you all, merging!

2025-07-01 00:02 UTC, merged

2025-07-10 20:05 UTC, sphurthy commented
Changes work as expected, it does not allow the start date to be after end date. Good work!
<img width="1346" height="625" alt="image" src="https://github.com/user-attachments/assets/f2fb1150-6fc8-41d2-aef3-c5821c4964f1" />

2025-07-10 23:09 UTC, sphurthy reviewed
Changes work as expected, it does not allow the start date to be after end date. Good work!
<img width="1346" height="625" alt="image" src="https://github.com/user-attachments/assets/7abdd799-c672-49e8-a3b9-1dde75d3b1ad" />