Rahul - Added Frontend Files For The HGN Form
OneCommunityGlobal/HighestGoodNetworkApp pull request #2922
Opened 2024-12-05 21:32 UTC by slidracoon72

# Description
![Screenshot 2024-12-05 at 3 45 29 PM](https://github.com/user-attachments/assets/0350e21a-3388-4b49-8430-48b1d9b866fe)

This PR contains the frontend code for the HGN Form application, designed to help developers assess their skill sets across various parameters, promoting collaboration by enabling them to offer or seek assistance from others. The PR focuses on the React.js-based frontend of the form application, which includes six pages. The implementation is demonstrated in the video below. This form mimics the Google Form [HGN Development Team Questionnaire](https://forms.gle/GCnqZdNvTpMbs4TT9). The Figma designs for this application can be found [here](https://www.figma.com/design/TweXhwOF7tipvogbiZqMLi/OneCommunityGlobal?node-id=0-1).

## Related PR
This frontend PR is related to the backend PR [#1164](https://github.com/OneCommunityGlobal/HGNRest/pull/1164).
Before starting this application, make sure to run the backend. Follow the [link](https://github.com/OneCommunityGlobal/HGNRest/pull/1164) for instructions on how to start the backend.

## Main features explained
- Developed Frontend Form Pages 1 to 6 as per the Figma designs.
- Implemented functionality for the Owner to edit the form questions.
- Enabled Users to edit previously answered questions by using the "Back" or "Edit Response" buttons on Page 5.
- Ensured the form is responsive, incorporating auto-scrolling and smooth page transitions.
- Added validation and checks for the respective form fields.
- Implemented a progress bar to track the user's form completion.
- Utilized React Context to preserve form state across pages, allowing users to edit their responses.
- Implemented smart selection for Availability and Preferences fields, including grouping consecutive times.
- Organized the form data collected across pages before sending it to the backend.

## How to test
Before starting this application, make sure to run the backend. Follow the [link](https://github.com/OneCommunityGlobal/HGNRest/pull/1164) for instructions on how to start the backend. You can also check out this [video](https://www.loom.com/share/e8a28ca8345a4938b8348a208311adb1?sid=e8405e40-d4aa-4c2a-9c05-a1c4b8af2d0c) for starting the backend. Currently, the Owner mode is set to true in the code to allow everyone to test the "edit questions" feature.
1. Switch to the current branch using: `git checkout Rahul-HGN-Form`
2. Navigate to the directory with: `cd src/components/HGNForm/frontend`
3. Install the required dependencies by running: `npm install`
4. Start the application by running: `npm start`
5. Complete the form and check the output in your browser's console.
6. Verify that the features mentioned above are functioning as expected.
7. Watch the video below to see how the form works.

## Video Demo of the HGN Form
https://www.loom.com/share/47aafbd487724dad8f6000a9f6342982?sid=a2151be0-5708-4d86-b35a-25b6da6bf3b8

2024-12-06 05:47 UTC, NazaninHashemian reviewed
In general, the form is functioning as expected. However, I encountered an issue on Pages 2 and 3 where most of the questions were missing, and only the answers were displayed. Additionally, attempting to edit those pages resulted in an error due to the empty questions.

I've attached screenshots of all the pages for reference. It seems these issues could be related to backend authentication not being set up correctly.
![0](https://github.com/user-attachments/assets/c638aecb-f6a3-42f7-808e-e16c4f3d1972)
![1](https://github.com/user-attachments/assets/7f2aad3c-a0cf-4396-a71d-2b473ffe744c)
![2](https://github.com/user-attachments/assets/03810c68-0163-4d30-a9f5-4f484eef50de)
![3](https://github.com/user-attachments/assets/9c449c17-d1d2-464e-8902-938cf67bff86)
![4](https://github.com/user-attachments/assets/0f6e7dd1-4972-42ec-908b-210267545559)
![5](https://github.com/user-attachments/assets/460322f5-36d3-4eb0-ade0-87dc6df26101)
![6](https://github.com/user-attachments/assets/8208e673-92c8-4fc7-932c-ff710ef72f9d)
![7](https://github.com/user-attachments/assets/c2377f6c-2833-4830-a059-cb64e1050710)
![8](https://github.com/user-attachments/assets/1e519f3f-42c4-4c98-bd9f-3d88f3e78507)

2024-12-06 15:13 UTC, slidracoon72 commented
> 

Hi @NazaninHashemian,

To view and edit the questions in this form, you need to start the backend and set up the database first. Please refer to the [linked PR](https://github.com/OneCommunityGlobal/HGNRest/pull/1164) and watch this [video](https://www.loom.com/share/e8a28ca8345a4938b8348a208311adb1?sid=e8405e40-d4aa-4c2a-9c05-a1c4b8af2d0c) for instructions on setting up the backend and database to test the frontend functionality of the application.

2024-12-14 01:52 UTC, ShraddhaShahari submitted a review, later dismissed
The form is functioning as expected, attempted to edit those pages its working as expected, also was able to edit the response.

I've attached screenshots of all the pages for reference. 

<img width="1715" alt="Screenshot 2024-12-13 at 5 28 16 PM" src="https://github.com/user-attachments/assets/e593d88f-f2af-40d6-8b0d-c69e81a69e44" />
<img width="1128" alt="Screenshot 2024-12-13 at 5 28 36 PM" src="https://github.com/user-attachments/assets/aea6a3d7-c787-492c-8eb4-97d3bd40b889" />
<img width="1390" alt="Screenshot 2024-12-13 at 5 38 42 PM" src="https://github.com/user-attachments/assets/d021edb0-5279-4a80-a55b-f5ff650e4d2d" />
<img width="1608" alt="Screenshot 2024-12-13 at 5 38 59 PM" src="https://github.com/user-attachments/assets/6b8abf7c-ee42-47d6-a0ce-52921e55328a" />
<img width="1714" alt="Screenshot 2024-12-13 at 5 44 20 PM" src="https://github.com/user-attachments/assets/95b777d5-7e22-41e6-ad27-e4a773f58925" />

2024-12-19 03:19 UTC, mashpotato9 commented
form worked as expect, I was able to change the questions and save them. All of the answers were saved with console log on the last page

2025-01-12 04:12 UTC, Sheehan20 reviewed
**Good implementation of allTimeEntriesReducer tests!**

Test coverage efficiently covers essential scenarios:
- Initial state handling
- GET_ALL_TIME_ENTRIES action processing
- Unknown action handling

The test cases are concise and well-structured, following testing best practices. All tests pass successfully.

2025-02-13 03:57 UTC, jaissica requested changes
The form is functioning as expected. I was able to edit the questions, select options without issues, and view my responses in the console. I've attached a recording of the working page.
However, there are some styling tweaks needed, along with a few missing simple components based on the provided [Figma design](https://www.figma.com/design/TweXhwOF7tipvogbiZqMLi/OneCommunityGlobal?node-id=0-1&p=f&t=9trITwlGsVKUwEUi-0). I've included an [Excel file](https://docs.google.com/spreadsheets/d/1HjNq82ZA9mlKRs3t_A3Ahk8M_HgpJfQbVaenOmB8rXY/edit?gid=0#gid=0) detailing the sections, component style differences, and a comparison of the expected vs. current design.

https://github.com/user-attachments/assets/1f7fdc11-1ce1-4cb5-bf46-21881c1f89fa

Please feel free to reach out if you have any questions regarding my review.

2025-03-04 23:37 UTC, slidracoon72 commented
Before finishing my internship, I had developed a standalone application for the HGN Form that needed to be merged into the main application, and I had submitted a proposal for this in the bugs document. Now, Jatin Agrawal has taken over this task and has completed the integration of the form into the main application, building upon my code from PR 2922 and making the necessary modifications. As a result, my PR 2922 should not be merged, as it only contains the outdated base code, whereas Jatin's PR 3070 includes my work along with the required changes and full integration into the main application. This is the one that should be merged.

2025-03-04 23:37 UTC, closed without merging