Samarth B Job CC feature
OneCommunityGlobal/HighestGoodNetworkApp pull request #2924
Opened 2024-12-05 23:21 UTC by samarth9201

# Description
Create a UI for an Owner to add to the CC options for specific posting categories, jobs, and/or ALL positions - Create a modal or management dashboard for the owner to view and manage the CC lists.
Should show whomever is on this list
Make it so that the CC list checks to make sure the person is active, and removes them from the list if they aren’t
Have CC functionality to add other people to CC so people who are hiring for a particular position can get a CC of the application details
Allow the owner to assign CC permissions: At the category level (example all ads under “Software Engineer”), For individual ads within a category (example only Front-End Engineer ads).

## Related PRS (if any):
This frontend PR is related to the [#1165](https://github.com/OneCommunityGlobal/HGNRest/pull/1165) backend PR.
…

## How to test:
1. check into current branch and follow backend PR instructions
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to Dashboard
6. "Edit Job Application Email CC" button should be visible below "Blue Square Email CC" button
7. Clicking the button should redirect you to /job-notification-dashboard
8. Verify Adding Emails to Particular job posting as well as addcing CC to each category work.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/30915b7a-afcb-4d60-98b0-3c01b8ccef29

2024-12-29 03:09 UTC, mashpotato9 submitted a review, later dismissed
I've reviewed this pr and all functionalities worked as expected.
<img width="1243" alt="Screenshot 2024-12-28 at 10 08 05 PM" src="https://github.com/user-attachments/assets/4a2c5326-92ea-42ee-a914-cc35183c9ba9" />
<img width="1249" alt="Screenshot 2024-12-28 at 10 09 02 PM" src="https://github.com/user-attachments/assets/655556be-9407-43ed-9ea0-321722a6f82e" />

2025-02-15 02:03 UTC, Srichand-Medagani approved these changes
I have reviewed this PR and it works fine. I was able to manage the CCs for all the categories. 

https://github.com/user-attachments/assets/05617d10-d43f-48e3-bd40-41e01ee3164d

2025-02-19 01:09 UTC, AurHubertMax requested changes
I tested each category by adding it to everyone in the category, as well as adding and removing a CC one at a time. When adding email CCs to specific categories, the feature works as expected. However, when adding email CCs to all categories, it produced a 400 server error as seen below at 2:50 in the video.

https://github.com/user-attachments/assets/093f4a76-51fb-4e22-850a-59f5043ad22a

Server error 4 (bad request) error message:
![z PR 2924 proof 2](https://github.com/user-attachments/assets/fafd5acd-29d8-42d5-8f8c-72b096834452)
00

2025-03-10 18:18 UTC, one-community commented
Thank you all, merging!

2025-03-10 18:19 UTC, merged