Mohan - Fix project inactive button
OneCommunityGlobal/HighestGoodNetworkApp pull request #2934
Opened 2024-12-08 05:20 UTC by mohangadde1

# Description
![image](https://github.com/user-attachments/assets/4edf65df-39e0-432d-a573-fabcc58f20e2)

Fixes # (bug list priority high/medium/low x.y.z)
Fixes the project inactive button,
Fixes a bug in all project reducer
Fixes Active/Inactive status filter  in project

## Related PRS (if any):
This frontend PR is related to the ... backend PR.

…

## Main changes explained:
fixes in projects.jsx and allprojectsreducer.js

…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ other links→ projects → Archive
6. verify function of Inactive Button, also verify the Active/Inactive filter

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/b24fb0ab-129f-4b3b-a215-7e7bb6958e17
![image](https://github.com/user-attachments/assets/972b418f-c26c-460f-bb2a-e07983e1f9e2)

![image](https://github.com/user-attachments/assets/7b32df02-3982-43be-95db-43d0127b4ef8)

2024-12-13 08:42 UTC, beblicarl requested changes, later dismissed
This functionality works as intended and the code is great. However, I suggest that when the "InActive" filter is applied, the heading up there should change to "InActive" instead of remaining as "Active"

![image](https://github.com/user-attachments/assets/376b08a4-303e-41cb-8d6b-a132c4c5f489)

![image](https://github.com/user-attachments/assets/402774f7-5ea1-48ed-b80a-2f48d3a2683b)

![image](https://github.com/user-attachments/assets/76b83172-ee96-4b56-b3de-4d4a736b46c5)

2024-12-13 22:17 UTC, nikhilpittala16 submitted a review, later dismissed
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/f0739830-9025-4278-9f14-f9cecd7b4d18

2024-12-14 05:38 UTC, jinxyou approved these changes, later dismissed
![Screenshot 2024-12-13 213504](https://github.com/user-attachments/assets/b0ee6a49-d33c-4198-b683-5433fa046c1b)
![Screenshot 2024-12-13 213512](https://github.com/user-attachments/assets/e9241d6c-b269-47ed-a15c-a1190f8acda7)

This is working well. Good job!

2024-12-14 15:43 UTC, anirudhsk2107 reviewed
The changes are working as expected 
![Screenshot 2024-12-14 104200](https://github.com/user-attachments/assets/ef4fd7b1-f36b-4baf-aa88-327228645978)
![Screenshot 2024-12-14 104207](https://github.com/user-attachments/assets/63bb8924-7ea7-499b-8d4c-544c8e3fcb9b)
![Screenshot 2024-12-14 104212](https://github.com/user-attachments/assets/165f675f-6762-49e8-92ed-3a049ab639ad)
![Screenshot 2024-12-14 104212](https://github.com/user-attachments/assets/e44afc40-586b-4a9c-95cf-af22badc7b3d)

2024-12-14 15:44 UTC, anirudhsk2107 submitted a review, later dismissed

2024-12-14 17:44 UTC, SammanBaidya approved these changes, later dismissed
Reviewed and tested the changes. It's working as intended. Well implemented. 


![R6](https://github.com/user-attachments/assets/f74a719b-e1b6-4ad1-9016-916022d8b54d)
![R5](https://github.com/user-attachments/assets/53d5f680-804d-44cc-afda-e371fb55189d)

2024-12-15 06:54 UTC, beblicarl approved these changes, later dismissed

2024-12-15 07:20 UTC, RashmiKY98 commented
I am unable to access the Projects page. Unsure if this is because of lack of permissions. Please find below the error screenshot. I request you to look into the issue. If this is because of the lack of permission, then a proper pop up/ error message would be helpful! 
![Screenshot 2024-12-14 231707](https://github.com/user-attachments/assets/7e0e81fe-7e97-4456-aad2-0a37b93e04e8)

2024-12-21 15:57 UTC, neha3010 approved these changes, later dismissed
Tested all the functionalities mentioned. Everything is working as expected.

<img width="1433" alt="Screenshot 2024-12-21 at 10 53 57 AM" src="https://github.com/user-attachments/assets/27eb9125-a126-427d-b88c-083794e97854" />
<img width="1436" alt="Screenshot 2024-12-21 at 10 54 13 AM" src="https://github.com/user-attachments/assets/8df0669c-9873-4275-9ca9-935f1ba8a16a" />
<img width="1436" alt="Screenshot 2024-12-21 at 10 54 38 AM" src="https://github.com/user-attachments/assets/fc52a609-9f25-4ce9-b889-4cf8594fdd3d" />

2024-12-28 22:25 UTC, mashpotato9 commented
Everything worked as expected. 
<img width="1392" alt="Screenshot 2024-12-28 at 5 22 14 PM" src="https://github.com/user-attachments/assets/2c356746-bdd5-48c5-b9b1-b533e3bb28d3" />
<img width="1221" alt="Screenshot 2024-12-28 at 5 22 31 PM" src="https://github.com/user-attachments/assets/be60e1dd-adeb-45fc-8bfb-fa1938fa21c3" />

I would second this suggestion
> when the "InActive" filter is applied, the heading up there should change to "InActive" instead of remaining as "Active"

2025-01-18 07:16 UTC, honglinchen0524 requested changes, later dismissed
Currently, if you "Archive --> Confirm" a project, it will active a project, but also reset the  Category to Unspecified. See video:

https://github.com/user-attachments/assets/adb7123e-6022-419b-8316-522a5042d4cf

2025-01-30 15:32 UTC, ziddigsm approved these changes, later dismissed
The bug fixes are resolved and no issue with the PR.


https://github.com/user-attachments/assets/fde14172-dafe-486c-aedc-3941e7ef1b2a

2025-02-04 20:30 UTC, mikelambo7 approved these changes, later dismissed
Verified that functionality works as expected. 

https://github.com/user-attachments/assets/1b0c5967-6025-43cd-a114-7e77b6de56f9



I noticed that after clicking the 'Set Inactive' button, there is a delay of a few seconds before the effect takes place. This might cause confusion for users who might think the action hasn't been registered. 

I suggest you consider adding a visual indicator (e.g., showing a 'Processing...' message) while the action is being processed. This would give users immediate feedback and make it clear that their input is being handled.

2025-02-06 00:28 UTC, yany960 submitted a review, later dismissed
Tested the related functionality, and it works as expected.
![WeChat9e38ec78efb8fcbcd2ed796bcccddf8f](https://github.com/user-attachments/assets/eaa8768e-f684-4b53-89b9-00dfa5e5a4d3)
![WeChat32b161b3d33e70d854064ea4586be493](https://github.com/user-attachments/assets/651da2ea-fb69-44c6-9856-360d85e64621)

2025-02-08 08:32 UTC, vivshar commented
Worked as expected, though there were few delays, first with process finishing and then active/inactive count changing, something like a spinner could be used to show process completion .
https://github.com/user-attachments/assets/595925f3-09dc-4097-9e83-6ecc824c3923

2025-02-09 06:40 UTC, k1guo submitted a review, later dismissed
<img width="1006" alt="#2934" src="https://github.com/user-attachments/assets/a93f9cb9-3a83-4ab9-a5e4-957737f7aea3" />
I review the code and test the app. It works as expect. Thank you!

2025-02-20 22:51 UTC, AurHubertMax submitted a review, later dismissed
Setting projects to active and inactive works as expected, does not need to refresh page to see changes anymore. Filters still work as well. 

https://github.com/user-attachments/assets/75237c32-f541-4256-af2c-6fa9fb8e16b7

2025-03-09 04:46 UTC, SravyaKotra commented
This update fixes project inactivity issues by improving the archive button’s functionality and refining state management. The refactored permission checks enhance maintainability. Optimizing useEffect dependencies can prevent unnecessary renders. Adding unit tests for category/status updates would further strengthen reliability.

2025-03-12 06:49 UTC, koushi1906 commented
Have reviewed the code and functionality is working as expected.

<img width="1364" alt="Screenshot 2025-03-12 at 1 47 46 AM" src="https://github.com/user-attachments/assets/1d27efc5-6985-4bb4-80bb-8b75df9b62af" />

2025-03-15 05:28 UTC, HSP24SCM69K submitted a review, later dismissed
Functionality works as expected. The Inactive Button now correctly toggles project status, and the Active/Inactive filter properly updates project visibility in the Archive section. No errors were found, and the changes integrate seamlessly with the existing functionality. 
<img width="1470" alt="Screenshot 2025-03-15 at 00 26 25" src="https://github.com/user-attachments/assets/b377bb29-52ee-44c2-8821-5694107058fb" />
<img width="1470" alt="Screenshot 2025-03-15 at 00 26 41" src="https://github.com/user-attachments/assets/8eeb7c2a-5fb1-481a-8e75-3c7d0b970e82" />
<img width="1470" alt="Screenshot 2025-03-15 at 00 26 55" src="https://github.com/user-attachments/assets/083235b9-f736-4edf-a825-345d04a97936" />

2025-04-01 20:45 UTC, karnati007 submitted a review, later dismissed
Tested the  Inactive button functionality in Dashboard → Other Links → Projects → Archive as an admin user. Verified that projects are correctly marked as inactive when the button is clicked. Additionally, tested the Active/Inactive filter, confirming that it accurately filters projects based on their status. Cleared site data and cache before testing to ensure no caching issues. The feature is working as intended.
![MohanPR](https://github.com/user-attachments/assets/e5d097f8-b5fa-4596-8d9d-6d1b09871014)

2025-04-03 22:09 UTC, myeeli submitted a review, later dismissed
I have checked out the latest code and i was able to inactive a project and can filter the data based on active / inactive filter . The changes are working as expected.

<img width="736" alt="PR 2934 1" src="https://github.com/user-attachments/assets/ff7b4cb8-98a2-4047-aa41-b49a6ecd172f" />

2025-08-17 01:18 UTC, SallaguntaRaahul commented
I have verified front-end PR #3613and its related PR #2934, the functions are working as expected.
<img width="840" height="822" alt="Screenshot 2025-08-16 at 9 13 32 PM" src="https://github.com/user-attachments/assets/5c422e6a-19e8-4101-9a12-1e355ec37315" />
<img width="840" height="822" alt="Screenshot 2025-08-16 at 9 17 42 PM" src="https://github.com/user-attachments/assets/b578e4bc-9c50-4f1d-87ae-e10038c503b2" />

2026-03-31 02:22 UTC, one-community commented
Redone with this PR: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/3613

2026-03-31 02:22 UTC, closed without merging