Rishitha Add title column in User Management
OneCommunityGlobal/HighestGoodNetworkApp pull request #2942
Opened 2024-12-12 08:54 UTC by RishithaMamidala

# Description
(PRIORITY MEDIUM) JAE: Add “Title” column and reduce “Role” column on User Management page
Admin Login → Other Links → User Management

## Related PRS (if any):
This frontend PR is related to the #1175 backend PR.
To test this frontend PR you need to checkout the #1175 backend PR.

## Main changes explained:
- Update src/components/UserManagement/UserManagement.jsx for including title column
- Update src/components/UserManagement/UserTableData.jsx for including title data
- Update src/components/UserManagement/UserTableHeader.jsx to add title in table header
- Update src/reducers/allUserProfilesReducer.js to include title in props
- Update src/components/UserManagement/UserTableSearchHeader.jsx to add search functionality for title
- Update src/components/UserManagement/__tests__/UserTableSearchHeader.test.js to have correct number of columns.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to otherslinks -> user management
6. Ensure that the table includes a "Title" column and validate that the data within this column is accurate 
7. Verify that the search functionality for the "Title" column operates correctly

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/a45d7596-0f4a-428d-bd06-3d7150713e93

2024-12-13 02:54 UTC, Lakshan-K requested changes
I reviewed this PR, but there seems to be an issue with the User Management page. The table is empty, and no users are displayed. Additionally, when I manually create a user, it doesn’t appear in the list.

Please investigate this to ensure that:

1) Existing users are properly fetched and displayed.
2) Newly created users are added to the list.

Thank you!

<img width="1440" alt="PR#2942" src="https://github.com/user-attachments/assets/622c66a9-208a-4624-9565-2803e47ae647" />

2024-12-15 06:54 UTC, RashmiKY98 requested changes
No users are displayed in the user management page. However, the title filter has been added. I request you to look into the issue.
![image](https://github.com/user-attachments/assets/5c952204-2db7-424c-aa3f-eb8e655ff672)

2024-12-19 16:57 UTC, neha3010 commented
<img width="1421" alt="Screenshot 2024-12-19 at 11 53 28 AM" src="https://github.com/user-attachments/assets/bce58ce9-4dac-487f-ad8c-0d2d920446f2" />
<img width="1419" alt="Screenshot 2024-12-19 at 11 54 17 AM" src="https://github.com/user-attachments/assets/f9c46133-a22b-4d73-9417-9224e9627c43" />

The table includes the "Job Title" column. But no users are getting displayed in the table. 
When I tried to add new user, I'm getting an error message.

2024-12-19 17:07 UTC, neha3010 reviewed
The table includes the "Job Title" column. But no users are getting displayed in the table.
When I tried to add new user, I'm getting an error message.
<img width="1421" alt="Screenshot 2024-12-19 at 11 53 28 AM" src="https://github.com/user-attachments/assets/e6902ce0-4da9-48d1-8d7e-8417fb175137" />
<img width="1419" alt="Screenshot 2024-12-19 at 11 54 17 AM" src="https://github.com/user-attachments/assets/ec55eb12-a56a-4aab-9c97-da718bea16ca" />

2024-12-21 21:38 UTC, mashpotato9 commented
I've tested this pr and was able to retrieve data by searching with job title filter
<img width="1392" alt="Screenshot 2024-12-21 at 4 37 04 PM" src="https://github.com/user-attachments/assets/cafe7c11-0add-45e0-94b5-b9a4b73b10e3" />

2024-12-22 06:03 UTC, RishithaMamidala commented
@Lakshan-K , @RashmiKY98 , @neha3010 
As I cannot recreate the issue,
Can you please confirm that you are checking out 1175 backend PR and are use npm run build command before starting the backend?

2024-12-23 23:05 UTC, neha3010 requested changes
Reviewed the PR. The "Job Title" is visible but its not displaying the users. I did checkout the 1175 backend PR.
<img width="1375" alt="Screenshot 2024-12-23 at 6 03 43 PM" src="https://github.com/user-attachments/assets/f12d6135-8d90-44b5-b5aa-c33ec74b4921" />

2025-02-09 20:01 UTC, closed without merging