Samarth B - Fixed Linting component/Teams
OneCommunityGlobal/HighestGoodNetworkApp pull request #2947
Opened 2024-12-13 15:32 UTC by samarth9201

# Description
Fixed Linting errors in src/components/TeamMemberTasks/**

## Related PRS (if any):
This frontend PR is not related to backend PR.

## How to test:
1. check into current branch
2. do npm install and ... to run this PR locally
3. Clear site data/cache
4. log as any user
5. The App should work as normal
6. Run npm run test to make sure all tests are passing.
7. Run npm run lint tp check linting

2024-12-14 16:08 UTC, anirudhsk2107 approved these changes
All changes are working properly. The tests have passed as well 
![Screenshot 2024-12-14 110330](https://github.com/user-attachments/assets/758bcff6-2820-442a-8f07-489094044feb)
![Screenshot 2024-12-14 110033](https://github.com/user-attachments/assets/51c08924-04b8-449e-9e51-3a27145cc51b)

2024-12-15 04:21 UTC, Lakshan-K requested changes
I ran the app to verify if it functions normally, but it does not. When trying to log in, an error occurs with the message: "Unexpected error".

Please look into this issue and resolve it. Thank you!

<img width="1058" alt="Screenshot 2024-12-14 at 11 17 52 PM" src="https://github.com/user-attachments/assets/33fbeb3e-604c-4c1a-b7b8-061188ef0266" />

2024-12-15 04:30 UTC, Lakshan-K requested changes
I ran the tests as instructed, and here are the results:

Test Suites: 1 failed, 214 passed, 215 total.
Tests: 1 failed, 34 skipped, 1445 passed, 1480 total.
Snapshots: 2 passed, 2 total.
Time Taken: 72.128 seconds.
The majority of the test cases passed successfully, but one test case failed. The failure needs to be investigated and resolved. Additionally, there are 34 skipped tests which might need a review to ensure they are intentionally skipped.

<img width="457" alt="PR#2947" src="https://github.com/user-attachments/assets/1f1bd827-b21b-494d-85a2-b982c9590c80" />

2024-12-15 05:51 UTC, RashmiKY98 requested changes
One test case failed and 217 passed. Request you to please look into the issue.
![image](https://github.com/user-attachments/assets/bfd8bfd1-179d-4e95-86e1-8afaf95efad1)

2025-02-10 18:41 UTC, mikelambo7 requested changes
Some test cases are failing. I've attached a screenshotsbelow
<img width="949" alt="Screenshot 2025-02-10 at 1 40 04 PM" src="https://github.com/user-attachments/assets/a2a5e8d6-0f44-4962-8f93-1a81ab19885c" />

2025-02-20 22:35 UTC, AurHubertMax submitted a review, later dismissed
Test cases passed, lint produced no errors.

![z PR 2947 proof 1](https://github.com/user-attachments/assets/ef3b1225-7877-4ae0-989e-e764df7ca00e)

2025-03-16 03:47 UTC, EvianTan commented
Works great with no errors, merging now. 
![image](https://github.com/user-attachments/assets/23f7836a-0df6-44b7-b90b-c4d3714c0e4d)

2025-03-16 03:48 UTC, EvianTan approved these changes

2025-03-16 03:48 UTC, merged