Samarth B - Lint Fix TeamLocations
OneCommunityGlobal/HighestGoodNetworkApp pull request #2948
Opened 2024-12-13 21:11 UTC by samarth9201

# Description
Fixed Linting errors in src/components/TeamMemberTasks/**

## Related PRS (if any):
This frontend PR is not related to backend PR.

## How to test:
1. check into current branch
2. do npm install and ... to run this PR locally
3. Clear site data/cache
4. log as any user
5. The App should work as normal
6. Run npm run test to make sure all tests are passing.
7. Run npm run lint tp check linting

2024-12-14 16:14 UTC, anirudhsk2107 approved these changes
The app is working and all test cases have passed 

![Screenshot 2024-12-14 111042](https://github.com/user-attachments/assets/f2fa8518-bed8-4899-a9d6-dc5ee18cbb17)
![Screenshot 2024-12-14 111329](https://github.com/user-attachments/assets/bb5f65cb-3e45-4966-b01f-5902add4ff75)
![Screenshot 2024-12-14 111338](https://github.com/user-attachments/assets/4079b6ec-31c5-457a-b0e4-27c34805f13e)

2024-12-15 06:31 UTC, RashmiKY98 approved these changes
Ensured that the linting fixes provided do not affect the software by running unit test cases. Reviewed the unit test cases. No issues found. Good work!
![image](https://github.com/user-attachments/assets/1eee33b8-deef-4733-918f-feca77d8b836)

2024-12-21 19:04 UTC, neha3010 submitted a review, later dismissed
Everything is working as expected. And all the test cases passed.
<img width="565" alt="Screenshot 2024-12-21 at 1 58 03 PM" src="https://github.com/user-attachments/assets/60f824f5-8b4c-47ac-8c82-7035d5b9ef55" />

2025-02-10 18:50 UTC, mikelambo7 requested changes
Some tests are failing
<img width="1018" alt="Screenshot 2025-02-10 at 1 49 52 PM" src="https://github.com/user-attachments/assets/cb98306c-52db-4b3a-bdaf-e2b9da08e967" />

2025-03-16 04:42 UTC, EvianTan commented
Looks good to me. 
![image](https://github.com/user-attachments/assets/73e29d22-edea-4edf-b1bf-4d3e0eebd55f)

2025-03-16 04:47 UTC, merged