Peterson implement improvements in 404 page
OneCommunityGlobal/HighestGoodNetworkApp pull request #2962
Opened 2024-12-18 23:02 UTC by peterson337

# Description
This pull request has been opened to implement an error page after the user uses a link to redirect to a page that does not exist.

## Related PRS (if any):
None

## Main changes explained:
Six components have been modified to implement the page of error.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Log in as any user.
4. Go to a URL that does not exist, e.g., http://localhost:3000/project
5. If the user is logged in, two links should appear on the error page: the first redirects to the dashboard, and the second also redirects to the same route but should open the modal for suggestions and development.
6. If the user is not logged in, a link should appear on the error page that redirects to the login page.

## Screenshots or videos of changes:
![Peterson_implement_Default_Error_Page_to_be_created_and_redirected_to](https://github.com/user-attachments/assets/9c1bfb10-7524-44f5-8655-630937430265)

## Note:
None

2024-12-26 22:09 UTC, ManasaViswanadhapalli approved these changes
I have tested and it is working as expected.
https://www.loom.com/share/60f61fdcc6494e72ad54e9763ba9619f?sid=ce7d563a-dbbc-4617-90a3-9747ac3bd93b

2024-12-28 22:02 UTC, mashpotato9 submitted a review, later dismissed
I've reviewed this pr and everything worked as expected
<img width="1078" alt="Screenshot 2024-12-28 at 5 01 12 PM" src="https://github.com/user-attachments/assets/558f504c-6573-4b92-99b7-575c3ce1913f" />
<img width="968" alt="Screenshot 2024-12-28 at 5 01 32 PM" src="https://github.com/user-attachments/assets/808a1b55-3101-44c1-86c9-718523cb427f" />

2025-01-23 21:55 UTC, vinayv-456 submitted a review, later dismissed
Reviewed code changes. "page not found" page is updated as mentioned
![image](https://github.com/user-attachments/assets/4788789f-b1e0-42c2-9a15-5c55f00995b2)

2025-01-25 23:29 UTC, honglinchen0524 requested changes
The error pages only shows up if the first path segment is invalid. If the first path segment is valid, it does not takes me to the error page(see first video). 
Also it does not work for profile page(see second video).

https://github.com/user-attachments/assets/cc7e2b90-57c8-42d0-b424-aaf866420212


https://github.com/user-attachments/assets/3695ae80-f85e-428a-891a-17c72b6e5ebe

2025-01-31 23:22 UTC, vivshar commented
Fix works well when the 404 page is reached, however routes may need to be looked at as dashboard and timelog screens do not redirect to 404 page but teamlocations works.

https://github.com/user-attachments/assets/3bda75d3-ed38-43f8-8eee-d9f9c3d13f1d


https://github.com/user-attachments/assets/b61821c6-aa1d-444f-804f-5e414915e9f5

2025-02-08 01:48 UTC, Peter-Nie2003 approved these changes
The web work as expected, great job!

https://github.com/user-attachments/assets/c24ebab3-d66b-44df-bf39-b6f77ee6cbd3

2025-02-09 06:26 UTC, k1guo reviewed
<img width="1265" alt="#2922" src="https://github.com/user-attachments/assets/a0389b05-3430-4884-8171-9a6a50f0ae80" />
I reviewed the code, it works as expected! thank you.

2025-02-20 22:25 UTC, AurHubertMax approved these changes
Tested page where user is not logged in, along with volunteer, admin, and owner accounts. Page not found works as expected. Links in the page not found page also works as expected.

https://github.com/user-attachments/assets/1849169b-fd15-44d7-88ba-0d1a6673f4da

2025-02-23 02:57 UTC, SSP24SCM16G requested changes
Issue: While http://localhost:3000/dashboard and http://localhost:3000/kjwhdg work as expected, http://localhost:3000/dashboard/wjhsdgc is also accessible, which is incorrect. sometimes image is not displayed. 
Suggestion: Ensure proper route handling so that undefined subroutes under /dashboard return the correct error response instead of loading.
https://drive.google.com/file/d/1G-3OzDHtUiXPFS0kAORf-YujrLF3pKDD/view?usp=sharing 


Uploading 2962.mov…

2025-02-23 03:36 UTC, rohith1667 requested changes
The feature works well as stated when user is logged in shows two links and when logged out shows only one link. There is a problem tough when checking a  new non existing path the website is still loading instead of throwing an error. That should be checked properly!
<img width="1438" alt="Screenshot 2025-02-22 at 9 26 13 PM" src="https://github.com/user-attachments/assets/6e552fb0-3c8f-4aad-9712-8ddf24ad00fc" />
<img width="1431" alt="Screenshot 2025-02-22 at 9 26 48 PM" src="https://github.com/user-attachments/assets/1845992d-2949-4073-a7e5-04785bede6f6" />
<img width="1418" alt="Screenshot 2025-02-22 at 9 31 10 PM" src="https://github.com/user-attachments/assets/8518034a-7275-4c14-998e-bd9dd77490cb" />

2025-03-02 04:12 UTC, koushi1906 commented
I've tested the pull request, and the functionality is working as expected—logged-in users see two links, while logged-out users see only one.

However, I found an issue where the display image doesn't load correctly when there are multiple path separators (/) in the URL.

Additionally, when a user submits a report, the modal opens as expected, and the URL updates to http://localhost:3000/dashboard?openModalReport. However, even after closing the modal or submitting the report, if the page is reloaded, the modal opens again. This seems to be due to the query parameter still being present in the URL after the modal is closed.

<img width="1345" alt="Screenshot 2025-03-01 at 9 58 45 PM" src="https://github.com/user-attachments/assets/38ed3d4c-fbda-41bd-b467-1124b0dbb478" />

<img width="1363" alt="Screenshot 2025-03-01 at 9 59 11 PM" src="https://github.com/user-attachments/assets/458294e1-5296-418a-94f5-ded904e3e8d2" />

2025-03-08 20:50 UTC, HSP24SCM69K approved these changes
Reviewed and tested the 404 Error Page improvements for both logged-in and logged-out users.

Functionality: All redirects are working as expected, with logged-in users correctly seeing options for the dashboard and suggestion modal, while logged-out users are redirected to the login page.
UI & User Experience: The design is clean, intuitive, and responsive, ensuring smooth navigation.
Performance: No errors were encountered, and all features function as intended.
<img width="1464" alt="Screenshot 2025-03-08 at 14 41 02" src="https://github.com/user-attachments/assets/ec457869-d897-4f03-a01d-a1e356e9cac5" />
<img width="1455" alt="Screenshot 2025-03-08 at 14 41 12" src="https://github.com/user-attachments/assets/8c1c7b44-5b87-4331-bda5-fff86dd50ec8" />

2025-03-28 21:14 UTC, myeeli approved these changes
I have checked out the current PR and can confirm that the "Page Not Found" message is displayed correctly when the user is logged in and logged out, in both light mode and dark mode. Hence approving the PR.

<img width="955" alt="PR 2962 - 1" src="https://github.com/user-attachments/assets/f40ab27e-2bac-4393-bb23-87f2c437ce0a" />
<img width="956" alt="PR 2962 - 2" src="https://github.com/user-attachments/assets/f5b42350-60f0-4f5c-a6cd-688a0efc2077" />
<img width="950" alt="PR 2962 - 3" src="https://github.com/user-attachments/assets/ebdfdf43-b60c-4569-a960-452600f088ff" />
<img width="947" alt="PR 2962 - 4" src="https://github.com/user-attachments/assets/3482a483-c61a-419e-b53e-3438f3e707c5" />

2025-04-03 07:17 UTC, linh2020 approved these changes
I have checked out the PR branch, installed dependencies, and cleared the cache. I logged in as both a regular and admin user and verified the error page behavior for non-existent routes. Everything works as expected — the 404 page displays the correct links based on login state, renders correctly in both light and dark modes, and no console errors appear. I also tested nested routes and verified that the modal behaves as expected.

![2025-04-03 00_11_41-Login and 1 more page - Your Microsoft Edge - Microsoft​ Edge](https://github.com/user-attachments/assets/efaaed2f-4ed9-4824-bbbc-0d0da5009d9d)

![2025-04-03 00_12_00-HGN APP and 1 more page - Your Microsoft Edge - Microsoft​ Edge](https://github.com/user-attachments/assets/b93753aa-a719-42ea-8103-c0cd2c07c40a)

![2025-04-03 00_13_25-Dashboard - Linh Admin and 1 more page - Your Microsoft Edge - Microsoft​ Edge](https://github.com/user-attachments/assets/9846f5f8-69fa-44fa-8d3f-004cddd5b8d3)

![2025-04-03 00_13_40-HGN APP and 1 more page - Your Microsoft Edge - Microsoft​ Edge](https://github.com/user-attachments/assets/079e04e9-9c0f-4aff-9538-26bed8c8a6cb)

![2025-04-03 00_14_07-Login and 1 more page - Your Microsoft Edge - Microsoft​ Edge](https://github.com/user-attachments/assets/213e0dae-855a-4f34-9a1f-7a124b6bafd6)

![2025-04-03 00_14_12-HGN APP and 1 more page - Your Microsoft Edge - Microsoft​ Edge](https://github.com/user-attachments/assets/e64f654f-e1b5-4897-a3cb-e1e3d653b44d)

2025-04-03 11:35 UTC, closed without merging