Task dashboard
OneCommunityGlobal/HighestGoodNetworkApp pull request #558
Opened 2022-11-13 04:10 UTC by Programmingrelated1999

![after task deletion](https://user-images.githubusercontent.com/83194014/201505278-23d7c985-1643-4f5c-9e01-bbe929529e70.PNG)
This is a PR for Task Deletion Dashboard. The new features are: 

* There will be additional section in Task: Status
* The Status is for admin and creator positions and will have delete the task button
* If the delete task button is clicked, the task will be deleted from database.

I have added new Status section and delete button in Team Member Task component. Moreover, I have added the delete request from frontend in the reducer file in Team Member Task folder. 

Below are screenshots of the delete button.
![before task deletion](https://user-images.githubusercontent.com/83194014/201504779-cc88f4a0-1ae6-488a-bcd8-9ba822eefb14.PNG)
![task delete button clicked](https://user-images.githubusercontent.com/83194014/201504761-f31a6619-4c91-4cbe-8bb2-8ddeb59cbd8c.PNG)

2022-11-16 00:31 UTC, EvianTan commented
Hi @Programmingrelated1999 ,

Awesome job! 
Finally figured out this PR is only for "create ability for admin/owner users to delete tasks from dashboard", so I updated our actions list as below to be more accurate. I split your action 2.3.8 from 2.3.5 as two tasks.
<img width="525" alt="image" src="https://user-images.githubusercontent.com/5071040/202049732-eaa91009-4d4e-491c-8dbe-e6daa34e486c.png">

✅ Verified changes:
1. Added a new column on dashboard task tab called "Status"
2. Only admin/owner can see the "Delete" buttons for tasks
3. Tasks can be totally removed from dashboard/WBS page and database

💡 Things can be improved:
1. The little red cross remove sign
For the consistency of signs in our app, it's always better to pick one from [this library](https://fontawesome.com/v4/icons/). You can also find that from our codes, most of the signs are start with "fa ...", that's because they both from this same library. Try to use this [remove](https://fontawesome.com/v4/icon/times) sign instead. Also here is a [link](https://www.freecodecamp.org/news/how-to-add-font-awesome-icons-to-your-buttons/) for use font awesome icon in button
2. Alignment of the task table header and data
<img width="772" alt="image" src="https://user-images.githubusercontent.com/5071040/202053602-447b67fd-78bf-41c1-a9d5-3aa982bfbfe0.png">

❓ Question:
Just curious about this PR, why it shows so many unrelated commits?? I hit this things once, but didn't know how did I trigger that 🥲

2022-11-16 22:09 UTC, EvianTan commented
Oh btw, for naming working branch, it's better to use something like "Yourfirstname-the_feature_you_are_working". Like this branch could be "Kaung-create_task_deletion_on_dashboard". It will be quick for others and yourself to find the branch from tons of branches, and the more meaningful branch name can give others more info on the first glance.

2022-12-04 01:08 UTC, one-community commented
Following up on this, does it still need to be reviewed and integrated?

2022-12-06 00:00 UTC, EvianTan commented
> Following up on this, does it still need to be reviewed and integrated?

Yes it still need to reviewed. I'm reviewing it now.

2022-12-18 00:32 UTC, Red4lpha commented
I cannot accept this PR, I don't think this branch was properly updated with development branch when it was being worked on. My changes to WBS task action menu got removed and it now that function is completely broken:
![Week11-PR-brokenFeature](https://user-images.githubusercontent.com/25683957/208271330-601e459c-057f-410e-b4a2-acc0f7146fb8.png)

This leads me to believe other developers recent changes have been possibly broken as well
Furthermore, the red X for is not align well with it's column and does not seemingly work. Where's the buttons to delete it? and the popup message only works half the time.
![Week11-PRBrokenFeature2](https://user-images.githubusercontent.com/25683957/208271411-43bc0e26-3495-429e-90f5-fd5d2785df8b.png)

2022-12-18 00:34 UTC, Red4lpha commented on src/components/Projects/WBS/WBSDetail/Task/Task.jsx
> -
Why was my feature deletion? Was this properly updated with the development branch before PR?

2022-12-18 13:20 UTC, pedroelton commented
> I cannot accept this PR, I don't think this branch was properly updated with development branch when it was being worked on. My changes to WBS task action menu got removed and it now that function is completely broken: ![Week11-PR-brokenFeature](https://user-images.githubusercontent.com/25683957/208271330-601e459c-057f-410e-b4a2-acc0f7146fb8.png)
> 
> This leads me to believe other developers recent changes have been possibly broken as well Furthermore, the red X for is not align well with it's column and does not seemingly work. Where's the buttons to delete it? and the popup message only works half the time. ![Week11-PRBrokenFeature2](https://user-images.githubusercontent.com/25683957/208271411-43bc0e26-3495-429e-90f5-fd5d2785df8b.png)



> I cannot accept this PR, I don't think this branch was properly updated with development branch when it was being worked on. My changes to WBS task action menu got removed and it now that function is completely broken: ![Week11-PR-brokenFeature](https://user-images.githubusercontent.com/25683957/208271330-601e459c-057f-410e-b4a2-acc0f7146fb8.png)
> 
> This leads me to believe other developers recent changes have been possibly broken as well Furthermore, the red X for is not align well with it's column and does not seemingly work. Where's the buttons to delete it? and the popup message only works half the time. ![Week11-PRBrokenFeature2](https://user-images.githubusercontent.com/25683957/208271411-43bc0e26-3495-429e-90f5-fd5d2785df8b.png)

I had a look here, and someone doubled this line by mistake.
Around line 567 it was supposed to be like this:
```
          </tr>
        </>
      ) : null}
    </>
```

And it was like this:
```
          </tr>
          ) : null}
        </>
      ) : null}
    </>
```

2022-12-20 00:36 UTC, EvianTan requested changes

2022-12-20 00:42 UTC, EvianTan commented
Hey @Programmingrelated1999 ,

1. Please don't include the formatting/ESLint/Prettier changes in this PR since it is a functionality change one, and it would be really hard for people to review the actual code changes you made. 
2. Like Kevin mentioned, his feature works well on Main/Dev but totally broken on this branch. Please fetch the latest Dev code and make sure you don't break any existing functionalities. We don't want to introduce bug again in such a hard time.

2023-02-14 13:55 UTC, Filipe-Oliv commented
Is this PR still being reviewed?

2023-02-14 23:30 UTC, one-community commented
This one needs to be taken over and wrapped up by someone else.

2023-02-17 13:37 UTC, Filipe-Oliv commented
Working on it

2023-02-18 14:01 UTC, Filipe-Oliv commented
The WBS task action menu that was removed and the function was stopped is working again. Could you chech it, please?

Before:
![02-18-2023 (1)](https://user-images.githubusercontent.com/114119668/219869809-c58f983d-c429-4c53-8c09-8e0e5a776192.png)

After:

[02-18-2023 (2).webm](https://user-images.githubusercontent.com/114119668/219869816-7fd58584-e5b3-45de-acc1-80681fe4ffb1.webm)

That's all for now. On Monday I'll keep working on it.

2023-02-18 14:57 UTC, PrabhjotSembhi commented
@Filipe-Oliv Let me know once it's ready to review. Thanks

2023-02-28 12:15 UTC, closed without merging