Alan view weekly summaries button
OneCommunityGlobal/HighestGoodNetworkApp pull request #593
Opened 2022-12-11 04:29 UTC by LeeSingChanYau

Implemented a way for people on the same team (especially managers of a team) to access the weekly summaries of their fellow team members. They shouldn’t have access to the entire summaries report, just the summaries of people on their team. Created a dropdown select input form to select from all the team members of the current user.

2022-12-12 16:57 UTC, ShaunSully88 commented
Looks like there is a conflict with the new code entered, around line 79-80. Can you double check on your end and then submit again?

2022-12-17 06:05 UTC, LeeSingChanYau commented
Resolved conflicts and made some changes. Updated the positioning of the "Team Weekly Summaries" button to the top.

2022-12-17 20:00 UTC, one-community commented
Branch still says it has conflicts... is that something you can fix Alan or should I ask Yiyun?

2022-12-17 20:43 UTC, LeeSingChanYau commented
Its fixed now. Please review.

2022-12-17 20:45 UTC, one-community commented
Excellent, thank you

2022-12-18 00:56 UTC, KaixiangGU commented on src/components/UserProfile/UserProfile.jsx
>                  />
I'm a little bit confused here. What's the purpose of removing `userTasks` and `updateTask` props here and also removing related functions? I can't see my task list in the projects tab when I test this branch.

2022-12-18 00:56 UTC, KaixiangGU commented on src/components/UserProfile/UserProfile.jsx
> +        setSubmittedSummary(true);
I checked the bug list. It requires displaying past three week's summaries. Please check it out.
![summary](https://user-images.githubusercontent.com/98206107/208271898-e173c04f-9c00-470d-ab5d-83c5ee3e0733.JPG)

2022-12-18 00:56 UTC, KaixiangGU commented on src/components/UserProfile/UserProfile.jsx
> +              {/* <BlueSquareLayout
Don't forget to uncomment BlueSquareLayout. Otherwise blue squares will not display once your PR gets merged.

2023-02-08 05:12 UTC, Theophileaseh requested changes
Hi @LeeSingChanYau 

CHANGES REQUESTED ♻️
Great work on implementing the project requirements ✔️
Linter is failing ❌
Can you please ensure the linter is passing
Cheers and happy coding 💻

2023-02-17 02:48 UTC, LeeSingChanYau commented
@Theophileaseh I can fix the lint problems. Please tell me what command you ran. I don't think its a good idea if I push lint fixes in this PR, because If I do I could mess up other stuff since there are more than a hundred errors on userProfile.jsx.

2023-02-17 03:10 UTC, LeeSingChanYau commented
@Theophileaseh please check again, I made some changes. @one-community I made the button smaller as requested.

https://user-images.githubusercontent.com/67836976/219539925-e5c21510-9ba5-4944-b27a-79fbb8f82e8e.mov


https://user-images.githubusercontent.com/67836976/219539962-ec76173c-7b63-449f-8205-47c1e521aeeb.mov

2023-02-17 03:55 UTC, tingedudu8 commented
Hi @LeeSingChanYau,
The "Team Weekly Summaries" button displays the team members' past three weeks summaries successfully. But I think it is better to clear the result after collapsing the summaries, when the button is clicked again, the three summaries should not be there.
Also, when I tried to make some changes to the user profile, the whole app crushed.
https://user-images.githubusercontent.com/70128933/219544731-8ddc4541-19d0-45b8-be62-b89a786f9b43.mov

2023-02-17 04:33 UTC, LeeSingChanYau commented
Hey @tingedudu8, thanks for the catch. I made some changes two solved the two issues you mentioned. Deleted showSaveWarning that was causing the app to crash after updating.

2023-02-18 15:02 UTC, PrabhjotSembhi commented
> Hi @LeeSingChanYau
> 
> CHANGES REQUESTED ♻️
> 
> * Great work on implementing the project requirements ✔️
> * Linter is failing ❌
> 
> Can you please ensure the linter is passing Cheers and happy coding 💻

@Theophileaseh Can you please check if your requested changes are made?

2023-02-19 06:24 UTC, NyahJ commented
Hi @LeeSingChanYau,

A small compile error arises, could you pls take a look? 
I believe it will work if you delete one of the "FormGroup" imported, thanks!

![截屏2023-02-18 下午10 21 23](https://user-images.githubusercontent.com/77643813/219932570-22c3c955-f1b8-4657-91d2-e6fa50f3d4e5.png)

2023-02-23 06:30 UTC, suigunfjc commented
Hi @LeeSingChanYau , I tested the button and it works correctly. When I clicked the button it displays the latest three weeks' summaries and clicking it again will collapse the summaries. Didn't find any bugs and I think you did a great job! Though currently, the button seems too big compared with the icons next to it. Also, the user name in the first row does not match with other rows.

https://user-images.githubusercontent.com/94319381/220834954-9d964be1-60e0-4edf-aea6-d6255028a59b.mp4

2023-02-23 18:11 UTC, kamtoeddy requested changes
Hi @LeeSingChanYau,

I tested the feature and it works as intended and here are some screenshots I took:

![Screenshot (510)](https://user-images.githubusercontent.com/65472478/220992209-19ee32ef-38dc-4a64-9746-4a54210f9351.png)

![Screenshot (511)](https://user-images.githubusercontent.com/65472478/220992220-ed62ebfe-9aa5-426c-a5dc-eec6830cf164.png)

The screenshots show that "Eddy Test", the test user I used could only see their summaries + those of "Ember Test" because they belong to the same team "Eddy's test team". 

Great job! but I have commented on a few changes in the codebase I think you should go over.  Thank you.

2023-02-23 23:23 UTC, LeeSingChanYau commented on src/components/SummaryBar/SummaryBar.jsx
> +      <Container fluid className={matchUser ? 'px-lg-0 bg--bar' : 'px-lg-0 bg--bar disabled-bar'}>
Sorry about that must have been the auto formatting.

2023-02-23 23:29 UTC, LeeSingChanYau commented on src/components/Projects/WBS/WBSDetail/Task/Task.jsx
> +                      <DropdownToggle caret caret color="primary" size="sm">
@kamtoeddy Thanks for the catch, please review again.

2023-02-24 16:20 UTC, kamtoeddy submitted a review, later dismissed
All good. Thanks again

2023-02-24 22:22 UTC, one-community commented
Thank you all. Moved to final review stage.

2023-02-25 13:54 UTC, rauleffting requested changes
Hi @LeeSingChanYau. Your PR was tested and everything is working quite well, as you can see below:

![test](https://user-images.githubusercontent.com/29555732/221360656-46992baa-c648-4a31-9ea7-aebfadf3e223.png)

However, there are some comments in the code that must be deleted before we merge. May you do this? I've marked all of them to help you.

Thank you very much!

2023-02-25 13:54 UTC, rauleffting commented on src/components/UserProfile/UserProfile.jsx
> +          // setIsValid={setIsValid(true)}
To delete.

2023-02-25 13:54 UTC, rauleffting commented on src/components/UserProfile/UserProfile.jsx
> +        // setIsValid(false)
To delete.

2023-02-25 13:54 UTC, rauleffting commented on src/components/UserProfile/UserProfile.jsx
> +        // setIsValid(false)
To delete.

2023-02-25 13:54 UTC, rauleffting commented on src/components/UserProfile/UserProfile.jsx
> +        // ];
To delete.

2023-02-25 13:54 UTC, rauleffting commented on src/components/UserProfile/UserProfile.jsx
> +  // const [isValid, setIsValid] = useState(true)
To delete.

2023-02-25 13:54 UTC, rauleffting commented on src/components/UserProfile/UserProfile.jsx
> +// import { ENDPOINTS } from 'utils/URL';
To delete.

2023-02-25 13:54 UTC, rauleffting commented on src/components/Projects/WBS/WBSDetail/Task/Task.jsx
>        controllerToggle = false;
To delete.

2023-02-25 14:50 UTC, vanelnw commented
Hi @LeeSingChanYau. I tested this PR and everything works well. Great work!


https://user-images.githubusercontent.com/38879488/221363245-8d8556f2-8873-47bb-a44d-f52b78136adf.mp4

2023-02-26 00:38 UTC, ayush0904 commented
Hey @LeeSingChanYau, I tested the PR and it looks good to me. Excellent work...

However, can you please review this, might be I am wrong.
I have selected Locke Lamora's Summaries. In the Team Weekly Summaries : The summary for the last week is showing Null. However when I go to the dashboard of Locke Lamora, I can see a symmary for the last week. 

<img width="789" alt="Screen Shot 2023-02-25 at 4 35 12 PM" src="https://user-images.githubusercontent.com/15180550/221386027-99830449-9d96-498f-8092-4f2898ac6122.png">
<img width="790" alt="Screen Shot 2023-02-25 at 4 35 23 PM" src="https://user-images.githubusercontent.com/15180550/221386030-38025bfb-f5cc-4301-9199-0b71fc5ed3d5.png">

2023-02-27 18:41 UTC, vitorsaa2k commented
Hello @LeeSingChanYau,

The feature seems to be working fine. There's just one problem, the highlighted text in the image should be displaying an apostrophe, but is showing a HTML code: "&apos".
![image](https://user-images.githubusercontent.com/17365161/221652718-b893986e-cfd6-4cc3-974d-0119cc0e91ae.png)

2023-02-27 21:20 UTC, one-community commented
Good catch Vitor!

2023-03-03 03:29 UTC, dkamghem commented
Weekly summaries look great. It seems different than what others have commented i am guessing they have been an update. I have the following:
![Screen Shot 2023-03-02 at 9 27 28 PM (2)](https://user-images.githubusercontent.com/83235086/222624333-70d08e9a-b17a-48d3-9eb2-a08e0f86e46c.png)

2023-03-03 21:08 UTC, NataliaCavicchioli submitted a review, later dismissed

2023-03-18 04:58 UTC, LeeSingChanYau commented
@vitorsaa2k Resolved conflicts and made changes. This feature is in the UserProfile page and not in the dashboard. Please review when you can.

2023-03-20 14:36 UTC, NataliaCavicchioli reviewed
Hey Alan, I tested your PR and it is working as intended, good job!

There are a few minor issues, for example, when I click on a user, it opens like this "ViewingNatalia Test-Volunteer&apos s summary." 

It would look much better with a space between Viewing and the user's name, and "&apos " replaced by an apostrophe.

https://user-images.githubusercontent.com/103126226/226373033-1a43ccaf-a786-47af-a8c8-ac0e236c190f.mp4

2023-03-20 16:16 UTC, vitorsaa2k commented
> @vitorsaa2k Resolved conflicts and made changes. This feature is in the UserProfile page and not in the dashboard. Please review when you can.

Now it's working as intended. Good job!

![image](https://user-images.githubusercontent.com/17365161/226402420-327dbbd4-c5f6-4445-8944-fabd2713a3ca.png)

2023-03-24 23:21 UTC, LeeSingChanYau commented
Hey @NataliaCavicchioli, can you make sure to pull the changes?
This is what I have for your summaries:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/67836976/227660459-a37af281-4611-4c4f-aa6b-4d251e0f138e.png">

2023-03-26 02:07 UTC, KaixiangGU commented on src/components/UserProfile/UserProfile.jsx
> -import React, { useState, useEffect, useRef } from 'react';
Hey Alan, I checked your most recent commit, may be you deleted this line accidentally.
I checked functionalities with added this line back. Everything works fine.

2023-03-27 01:46 UTC, closed without merging

2023-03-27 01:46 UTC, one-community commented
Closed and replaced by this PR: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/740