Alan fix total summaries
OneCommunityGlobal/HighestGoodNetworkApp pull request #622
Opened 2022-12-25 02:22 UTC by LeeSingChanYau

Fix for Weekly summaries view for volunteers is missing last week (see below), so we’ll have 4 tabs instead of 3 from now on. Also, the “total submitted” is not accurate. Please add another tab showing the end date for last week.

2023-01-02 18:51 UTC, rauleffting commented
@LeeSingChanYau I ran your PR locally, but the 'last week' tab is still missing.  It's missing not just for volunteers, but for all account types as well.

Here is a screenshot:
![Screen Shot 2023-01-02 at 15 36 08](https://user-images.githubusercontent.com/29555732/210269434-2540df07-273c-486c-856d-92360b8c36f2.png)

2023-01-07 04:17 UTC, LeeSingChanYau commented
Hey Raul, thanks for catching that. I made a change please review again and tell if it looks good.

2023-01-07 15:16 UTC, rauleffting commented
Hi @LeeSingChanYau ! Thank you very much for taking a look. I've tested again and I found a new error. Now, it's possible to see the tabs, but when I add a new tangible or intangible time, it doesn't appear on 'Current Week Timelog' .

Here is a video:

Uploading Screen Recording 2023-01-07 at 12.03.22.mov…

2023-01-07 15:19 UTC, rauleffting commented
Hi @LeeSingChanYau ! Thank you very much for taking a look. I've tested again and I found a new error. Now, it's possible to see the tabs, but when I add a new tangible or intangible time, it doesn't appear on 'Current Week Timelog' .

Here is a video:

https://user-images.githubusercontent.com/29555732/211157843-c48bb2eb-5b1b-430d-b015-5682ace391af.mov

2023-01-07 22:06 UTC, LeeSingChanYau commented
Hi @rauleffting, yes you are right that is not behaving correctly. But I think that is the Timelog component. In this PR I am working on the WeeklySummary Component

2023-01-07 22:08 UTC, LeeSingChanYau commented
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/67836976/211172066-8db9eb4f-99bf-4a9e-a016-abd1005fa2f7.png">

Maybe you can add this to the bugs google doc.

2023-01-07 22:09 UTC, LeeSingChanYau commented
> <img alt="image" width="1065" src="https://user-images.githubusercontent.com/67836976/211172066-8db9eb4f-99bf-4a9e-a016-abd1005fa2f7.png">
> 
> Maybe you can add this to the bugs google doc.

As you can see above they are two different components.

2023-01-07 22:42 UTC, one-community commented
> 

It should have 4 tabs, not 3 too. So still missing "2 Weeks Ago" tab.

2023-01-08 05:16 UTC, LeeSingChanYau commented
ok I can do that, but I'm not sure how to access to the summary before 2 weeks ago.

2023-01-08 19:45 UTC, one-community commented
Are they not stored in the database? Maybe see if Yiyun can help you.

2023-01-13 05:25 UTC, one-community commented
Following up on this

2023-01-14 14:59 UTC, rauleffting commented
> > <img alt="image" width="1065" src="https://user-images.githubusercontent.com/67836976/211172066-8db9eb4f-99bf-4a9e-a016-abd1005fa2f7.png">
> > Maybe you can add this to the bugs google doc.
> 
> As you can see above they are two different components.

2023-01-14 15:05 UTC, rauleffting commented
@LeeSingChanYau You are right and I was wrong about the component. I'll take a look at your new changes. 

p.s: Sorry, I closed it by mistake.

2023-01-14 15:36 UTC, rauleffting commented
Hi, @LeeSingChanYau! I tested your PR. As you can see in the video below, the weekly summaries are showing as expected. However, there are two things that must be fixed:
1. the fourth tab is showing the wrong date because '3 weeks ago' wasn't at first January. I also think that the tab title is supposed to be 'Three weeks ago'. Please, correct me if I'm wrong.
2. the second thing is that when a new weekly summary is added, the page freezes and it's necessary to reload.

https://user-images.githubusercontent.com/29555732/212479909-ce137d7a-1533-46d6-b5ca-e38614f50d23.mov

Here are the errors that the console shows when clicking on save:

![Screen Shot 2023-01-14 at 12 33 51](https://user-images.githubusercontent.com/29555732/212479986-0865986a-161f-490a-bad8-53e844180400.png)

Thank you!

2023-01-15 04:41 UTC, LeeSingChanYau commented
Hello @rauleffting, yes as I said in slack the weeklySummaries are not loading correctly since the first of january in the dev branch. Things are working fine in the main branch, but in the dev the 3 summaries are displaying the due dates for this week.
<img width="1920" alt="Screenshot 2023-01-14 at 8 40 30 PM" src="https://user-images.githubusercontent.com/67836976/212523232-2f79aa29-5591-48f7-8571-80e6a5dcaa79.png">

2023-01-15 04:43 UTC, LeeSingChanYau commented
Also as of right now we cant really show the last 4 summaries because the database only stores the last 3, so unless we merge a new pr that stores 4 summaries this will still be happening.

2023-01-15 16:59 UTC, one-community commented
Please create that PR for a 4th summary

2023-01-16 15:21 UTC, rauleffting commented
> Hello @rauleffting, yes as I said in slack the weeklySummaries are not loading correctly since the first of january in the dev branch. Things are working fine in the main branch, but in the dev the 3 summaries are displaying the due dates for this week. <img alt="Screenshot 2023-01-14 at 8 40 30 PM" width="1920" src="https://user-images.githubusercontent.com/67836976/212523232-2f79aa29-5591-48f7-8571-80e6a5dcaa79.png">

Ok. But we need to be sure that this error would not affect the main branch if PR is merged. 

Please, change the variables' names to the same name used in the UX. So the code can be more readable. 

Thank you very much!

2023-01-21 08:36 UTC, LeeSingChanYau commented
Hi @rauleffting, please review when you can. I made some changes.

2023-01-21 15:48 UTC, rauleffting commented
> Hi @rauleffting, please review when you can. I made some changes.

Hi @LeeSingChanYau. I tested your PR again and it's still freezing when a summary is submitted:

https://user-images.githubusercontent.com/29555732/213874902-dbb6b43b-2a6e-4ce7-877d-dbbc01b121cf.mov

Please, change the variables summaryBeforeLast for summaryTwoWeeksAgo, like the UX:

![Screen Shot 2023-01-21 at 12 47 33](https://user-images.githubusercontent.com/29555732/213874913-d7ad8678-1b7c-42cf-b5b6-1afac4278794.png)

Thank you very much!

2023-01-21 16:24 UTC, RafaelCastilhoCastro commented
Hi @LeeSingChanYau,
I also tested the PR and this is the result.
![image](https://user-images.githubusercontent.com/65736872/213876404-1571446a-ebf8-4817-8a85-d9b166688911.png)

The screen is algo freezing after submitting a new weekly summary.

2023-01-21 16:26 UTC, LeeSingChanYau commented
Hello @rauleffting, yes you are correct nothing refreshes when we save a summary that is not for the current. But if you submit a summary for the current week, it should refresh like the video I shared below.

2023-01-21 16:44 UTC, LeeSingChanYau commented
Thanks for catching that. That was happening because somehow I did not pass the setSubmittedSummary as prop. Please review again. Thanks again!

2023-01-21 17:24 UTC, PrabhjotSembhi commented
Hey, I have checked it. When We add a summary we can add the last 3 weeks. But I am not sure about the date. 
If the third date shows the week's ending date the week it's ok. 

![image](https://user-images.githubusercontent.com/82662768/213878911-e9a87bbc-7460-4c14-91a5-5db210659d4c.png)

and in the Admin role week, summary reports it's not showing the 3rd-week reports. 

![image](https://user-images.githubusercontent.com/82662768/213879113-acd29375-137e-495f-9678-ef0ab49af9f7.png)

maybe you can do this later.

2023-01-21 17:33 UTC, PrabhjotSembhi requested changes
Hey, I have checked it. When We add a summary we can add the last 3 weeks. But I am not sure about the date. 
If the third date shows the week's ending date the week it's ok. 

![image](https://user-images.githubusercontent.com/82662768/213878911-e9a87bbc-7460-4c14-91a5-5db210659d4c.png)

and in the Admin role week, summary reports it's not showing 3rd-week reports. 

![image](https://user-images.githubusercontent.com/82662768/213879113-acd29375-137e-495f-9678-ef0ab49af9f7.png)

2023-01-24 16:20 UTC, rauleffting commented
Hi @LeeSingChanYau, I tested your PR again. Now, the page isn't freezing anymore. However, the Three Weeks Ago tab is still not displaying the right date. I also think that it should be called Three Weeks Ago, following the pattern of the other tabs.

![Screen Shot 2023-01-24 at 13 14 48](https://user-images.githubusercontent.com/29555732/214348348-a79aacc2-ed73-4b96-8b20-dec3f4728f89.png)

Thank you very much! Thanks to change the variable's name!

2023-01-24 17:47 UTC, RafaelCastilhoCastro commented
Hi @LeeSingChanYau,
I performed new tests and all features seems to be working as intended. Tks.

2023-01-25 09:01 UTC, PrabhjotSembhi reviewed
In the Admin view, we are not using dates to represent weeks. 
In the volunteer tab, we are using the date in the last tab. we make it consistent, that will be better and easy to understand

2023-01-25 09:01 UTC, PrabhjotSembhi approved these changes

2023-01-25 18:09 UTC, rauleffting commented
Hi @PrabhjotSembhi. Why did you approve it? It's displaying the wrong date in the last tab. Thanks.

2023-01-30 16:18 UTC, rauleffting commented
The date remains incorrect. Cannot be approved. Thank you all.

2023-02-02 04:31 UTC, LeeSingChanYau commented
@rauleffting please review now, I made some changes.

2023-02-02 04:31 UTC, LeeSingChanYau commented
This is what I am getting now after saving the last three summaries.
<img width="1512" alt="Screenshot 2023-02-02 at 12 29 43 PM" src="https://user-images.githubusercontent.com/67836976/216232096-7d854249-6f86-411b-a20f-b8eb2469bb94.png">
<img width="1512" alt="Screenshot 2023-02-02 at 12 29 04 PM" src="https://user-images.githubusercontent.com/67836976/216232112-9bc00496-1498-43ab-b51d-6acd7e685d48.png">
<img width="1512" alt="Screenshot 2023-02-02 at 12 28 55 PM" src="https://user-images.githubusercontent.com/67836976/216232119-0a8d1927-7fe0-4794-bd5a-f3de9070a3e4.png">

2023-02-02 16:13 UTC, rauleffting approved these changes
Hi @LeeSingChanYau! I tested your changes. Everything worked quite well, as you can see in the video below:

https://user-images.githubusercontent.com/29555732/216379228-a6bdce09-6456-467e-adea-b68346b602f7.mp4

2023-02-02 16:17 UTC, rauleffting commented on src/components/WeeklySummary/WeeklySummary.jsx
> +      // (weeklySummaries && weeklySummaries[1] && weeklySummaries[1].dueDate) ||
Please, delete these comments.

2023-02-02 16:20 UTC, rauleffting commented
Hi @LeeSingChanYau. Thank you very much. As you can see in the video below, your changes worked quite well:

https://user-images.githubusercontent.com/29555732/216380957-482aac0f-20a0-4e7e-8dfd-a325c8bdb6f6.mp4

2023-02-02 16:21 UTC, rauleffting requested changes

2023-02-02 16:21 UTC, rauleffting commented on src/components/WeeklySummary/WeeklySummary.jsx
> +      // (weeklySummaries && weeklySummaries[1] && weeklySummaries[1].dueDate) ||
Please, @LeeSingChanYau, delete these comments. Thereafter, I'm going to approve your PR! Thank you!

2023-02-02 16:21 UTC, rauleffting commented on src/components/WeeklySummary/WeeklySummary.jsx
> +      // (weeklySummaries && weeklySummaries[2] && weeklySummaries[2].dueDate) ||
Please, @LeeSingChanYau, delete these comments. Thereafter, I'm going to approve your PR! Thank you!

2023-02-02 16:21 UTC, rauleffting commented on src/components/WeeklySummary/WeeklySummary.jsx
> +      // (weeklySummaries && weeklySummaries[3] && weeklySummaries[3].dueDate) ||
Please, @LeeSingChanYau, delete these comments. Thereafter, I'm going to approve your PR! Thank you!

2023-02-08 18:46 UTC, RafaelCastilhoCastro commented
Hi @LeeSingChanYau,
I tested the PR again. No more freezing screen after submiting a summary. I did submit summaries to Current Week, Last Week, Two Weeks ago and Three Weeks Ago with all account roles with no issues.

The "Total submitted" is not working though. My admin account shows a total of 6 summaries submited, but it doesn't add to it when submitting new ones. It keeps to 0 on all my other accounts.

![image](https://user-images.githubusercontent.com/65736872/217616698-9ea5a3ac-0b5a-4416-aa6b-cbb8f1a648b5.png)

Thanks.

2023-02-08 22:17 UTC, one-community commented
Good catch Rafael! Please fix that Alan.

2023-02-09 14:15 UTC, Filipe-Oliv commented
Hi @LeeSingChanYau 

Same question as Rafael. The "Total submitted: 0" is not working.

![week 03 - 02-09-23 (#622)](https://user-images.githubusercontent.com/114119668/217837072-f5d959db-fcd1-4e57-a8a9-93ee901df3c5.png)

2023-02-17 09:49 UTC, PrabhjotSembhi reviewed
As others are saying  Total submitted count is not getting updated. 
I have added comments in the code with potential issues. pleas have a look

2023-02-17 09:49 UTC, PrabhjotSembhi commented on src/components/Dashboard/Dashboard.jsx
> +        setCount={setCount}
I think here you want to use 
`  setCount={weeklySummariesCount}`

correct me if i am wrong

2023-02-23 19:37 UTC, NyahJ commented
Hi @LeeSingChanYau,

Most of the issues mentioned above are fixed, the features you changed went well with different accounts.
About the "Total submitted: 0", I also reading your codes and have the same view with PrabhjotSembhi, could you pls try it when you get a chance? Thanks!

![截屏2023-02-23 上午11 23 34](https://user-images.githubusercontent.com/77643813/221012007-f8b02a3d-a222-48d9-a9df-1b9f7631f549.png)

2023-02-28 19:42 UTC, dkamghem commented
In my case, i only have three tabs. i am not sure if it is what it is intended to be.
![Screen Shot 2023-02-28 at 1 41 17 PM (2)](https://user-images.githubusercontent.com/83235086/221961435-202fef47-4193-4e1e-b840-d265eca9bbd5.png)

2023-02-28 19:51 UTC, RafaelCastilhoCastro commented
Hi @dkamghem,
The UI on your image seems strange on some elements. Can you please make sure you are on the right branchs and has them update/installed (`git pull`/`npm i`) and double check your results? Thank you.

2023-03-01 15:17 UTC, Lunaliar commented
Hey @LeeSingChanYau, Seems to be working for me! Great job!
![Screenshot from 2023-03-01 10-14-56](https://user-images.githubusercontent.com/98275089/222182178-2b8a488b-1fed-4755-afa0-0032ec04b41e.png)

2023-03-01 16:24 UTC, Lunaliar commented
Hey @LeeSingChanYau, I checked out your changes, the tabs are working great and I'm able to write and view summaries from those weeks, however, the total submitted is still at 0, I tried following the code and debugging to see why its only showing at 0 but I keep losing track of it.
![Screenshot from 2023-03-01 10-39-35](https://user-images.githubusercontent.com/98275089/222200439-2b4f11b8-ec6c-4be6-b1c0-1f736990127a.png)
![Screenshot from 2023-03-01 10-39-50](https://user-images.githubusercontent.com/98275089/222200450-5090c465-50b2-474b-89d0-390b6287e6ec.png)

2023-03-04 23:35 UTC, ayush0904 commented
Hey @LeeSingChanYau, Total Submitted is always showing as 0. It is not getting updated. Please see to it. Thank you

<img width="843" alt="Screen Shot 2023-03-04 at 3 32 17 PM" src="https://user-images.githubusercontent.com/15180550/222933429-0ccd54b7-4f0d-4cd5-8a2b-e0203dfdcbff.png">

2023-03-10 23:45 UTC, EvianTan commented
Close it due to I raised #707

2023-03-10 23:45 UTC, closed without merging