Jae: Auto refresh/Check time and date when logging intangible time
OneCommunityGlobal/HighestGoodNetworkApp pull request #632
Opened 2022-12-31 20:21 UTC by RJBornToWin

Bug description: Right now if someone has a poor internet connection and leaves the app open for a day and goes to log intangible time, the time will be logged using the date for the last time they were active in the app. I’d like the app to check/auto-refresh the time and date to make sure it is accurate when logging this intangible time.

Fix: Validate add time form upon submission and show corresponding error message. Admin can add submission for any date. Other users cannot. So the fix is limited to users other than admin. Any user can edit already entered form. So the fix is limited only to add. If incorrect date is populated and user tries to submit it, "Invalid date. Please refresh the page." is displayed as error message on the form.

Test cases:
1. Admin can add intangible time log for any date
2. User can add intangible time log only for current date (Need to access the app around 11.55 PM and leave it for 5 minutes), and try to add intangible time entry at 12.01 and see if incorrect date is populated. If incorrect then error message should be shown)

2023-01-01 02:30 UTC, one-community commented
Wonderful! Thank you for putting PR raised by the bug on the bugs doc too. Please also always include the PR # and link. See how I did this there for this one as an example.

2023-01-04 21:51 UTC, ShaunSully88 approved these changes
Thanks a lot RJ, this is actually really helpful. Good to know I close in some areas, and grateful to learn the rest from you. Really appreciate the help on this, thank you!

2023-01-06 00:48 UTC, EvianTan commented on src/components/Badge/Badge.jsx
>      console.log('This is userId', userId);
No functional changes in this file.

2023-01-08 04:51 UTC, RajasriJanaki commented on src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
> +      else if (currentUserRole !== 'Owner' && !edit && today.diff(date, 'days') != 0) {
In the code “Administrator” role is mentioned as owner. So I have checked only owner. Please correct me if I am wrong. Thanks.

2023-01-08 04:51 UTC, RJBornToWin commented on src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
> +      else if (currentUserRole !== 'Owner' && !edit && today.diff(date, 'days') != 0) {
In the code “Administrator” role is mentioned as owner. So I have checked only owner. Please correct me if I am wrong. Thanks.

2023-02-02 20:06 UTC, RJBornToWin commented on src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
> +      else if (currentUserRole !== 'Owner' && !edit && today.diff(date, 'days') != 0) {
With the recent changes, Administrator role is handled as "Administrator" in the code. Updating the code to accommodate the same.

2023-02-14 14:27 UTC, rauleffting requested changes
Hi @RJBornToWin. Good job! The functionality is perfect, as you can see below:

https://user-images.githubusercontent.com/29555732/218766438-9bb069a2-fcff-4e67-a1e6-04949c09c76d.mp4

However, we still need to delete those debug outputs. Then, I'm going to approve! Thank you very much!

2023-02-14 14:27 UTC, rauleffting commented on src/components/Badge/Badge.jsx
> +      // console.log('userProfileBadgeCollectionId', props.userProfile._id);
I think we can delete these debug outputs.

2023-02-14 14:27 UTC, rauleffting commented on src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
> +    // console.log('submitting');
Here as well.

2023-02-16 18:39 UTC, PrabhjotSembhi reviewed
I am still able to add an intangible entry for the previous day. When time is @00:01 or more in the form it still  shows 16 Feb ( Previous date ) 
![image](https://user-images.githubusercontent.com/82662768/219457403-1711d23f-d68b-4e56-9fc3-97d901433846.png)



https://user-images.githubusercontent.com/82662768/219457611-d0aca459-e7d2-49a5-9b7d-3126669d864c.mp4

Please check video

2023-02-25 03:24 UTC, NyahJ commented
Hi @RJBornToWin,

All your changes worked well, for the Admin and user accounts, they all worked as expected as you mentioned in the description. Thanks!

<img width="1432" alt="截屏2023-02-24 下午7 22 44" src="https://user-images.githubusercontent.com/77643813/221333730-28c5f2a9-a4dd-42ca-ac69-b5bfdb9f5544.png">
<img width="1333" alt="截屏2023-02-24 下午7 19 45" src="https://user-images.githubusercontent.com/77643813/221333731-3c093ea6-f981-45bd-a489-3a9763e835d7.png">

2023-02-28 02:59 UTC, tingedudu8 approved these changes
Hi @RJBornToWin, I tested your PR and the feature works properly for both volunteer and admin role. Thanks!
https://user-images.githubusercontent.com/70128933/221741991-3b9a797b-5a0e-4443-b797-2f1b6f49e140.mov

2023-03-08 18:07 UTC, rauleffting approved these changes
Hi @RJBornToWin. Changes worked perfectly. 

Approved!


https://user-images.githubusercontent.com/29555732/223794604-4d00556d-e387-4e17-b966-c59c7d58daa1.mp4

2023-03-08 18:12 UTC, merged