fix make intangible hours editable
OneCommunityGlobal/HighestGoodNetworkApp pull request #635
Opened 2023-01-03 23:31 UTC by KaixiangGU

This PR is about making intangible hours editable.
User -> View Profile -> Volunteering Times
![BUG](https://user-images.githubusercontent.com/98206107/210458406-edeec260-5ee1-4d7a-b5af-f153d7c22424.JPG)

✔️ How to test this PR:
1. Login with an admin account, manually edit intangible hours and save changes.
2. Submit a new intangible time entry to see if intangible hours keep adding.
3. Change intangible entry to tangible entry and vice versa to see if intangible hours will increase/decrease accurately.

2023-01-04 15:40 UTC, rauleffting requested changes
I reviewed your code. Think it worked quite well on changing intangible hours, both in the profile: 

![ss2](https://user-images.githubusercontent.com/29555732/210591188-ab2c9c94-d482-4e77-8d53-092a94f19864.png)

And in the dashboard:

![ss1](https://user-images.githubusercontent.com/29555732/210592586-021563d1-7a15-43b6-a95a-8d561340f159.png)

However, it's showing an error alert when saving changes. It seems not affecting the functionalities, but I think this is not supposed to appear:

![ss3](https://user-images.githubusercontent.com/29555732/210591851-3858985d-182e-48d8-82d6-4a6a90c52c60.png)

I imagine this is a [backend](https://github.com/OneCommunityGlobal/HGNRest/pull/267) issue.

Once this small error is corrected, I believe we can approve the front and back PRs.

Thank you very much!

2023-01-05 19:42 UTC, KaixiangGU commented
Hi @rauleffting, thanks for your review.
This error bug actually not related to my PR, it happened couple weeks ago, and it has already been fixed when I was working on intangible hours.
And my working branch was not the latest branch, that's why you saw this bug in my PR. To make sure this bug will not show up when my PR gets merged, I just pulled the latest changes from FE and BE, and everything works fine, hours can be edited without any errors.

2023-01-06 14:53 UTC, rauleffting commented
@KaixiangGU Thanks to take a look. Now, the alert and error are no longer appearing. However, the 'intangible hours' field isn't getting updated anymore: 

https://user-images.githubusercontent.com/29555732/211036463-3a909a03-bcb0-4cca-bab4-a934376dcecd.mov

2023-01-06 15:09 UTC, rauleffting commented
Hi @KaixiangGU. I tested here. The error is still occurring. After the first test, I also did a pull in front and back to test again and the error remains. Can you take a look? Thank you very much!

2023-01-07 00:40 UTC, rauleffting approved these changes
After pulled the development branch, it worked perfectly!

2023-01-13 15:46 UTC, rauleffting commented
I've tested again and I found something. I followed your test list steps. Items 1 and 2 worked well, but Item 3 didn't. When changing tangible to intangible and vice versa at the 'Current Week Timelog', the value didn't update at the profile.

https://user-images.githubusercontent.com/29555732/212360724-ce6f649d-8569-4daf-99c8-3b098675cfea.mov

2023-01-15 00:30 UTC, KaixiangGU commented
@rauleffting Hey, it should work now, please check it out. Thank you!

2023-01-16 15:11 UTC, rauleffting commented
@KaixiangGU thank you very much! Your changes worked, as you can see below:

https://user-images.githubusercontent.com/29555732/212709740-da578398-ba46-4350-9559-edfd58aa1494.mov

however, as you saw at the end of the video, there's one other thing. When deleting the intangible/tangible time, the time doesn't change on the profile page. I'm not sure if it's related to your PR. So please correct me if I'm wrong.

Thank you very much!

2023-01-17 18:32 UTC, KaixiangGU commented
Sure I can fix that! Thanks for the catch.

2023-01-17 20:29 UTC, KaixiangGU commented
@rauleffting It should work now! Check it out!

2023-01-18 15:09 UTC, rauleffting submitted a review, later dismissed
Your changes worked perfectly! I didn't see anything strange in your code as well. I'm going to approve it! Thank you very much!

2023-01-25 06:36 UTC, RJBornToWin requested changes
I see following issues while testing:
1. I am able to enter negative values using the down step button on the field. Upon save it doesn't get saved but shows success message instead

<img width="600" alt="Screen Shot 2023-01-24 at 10 21 25 PM" src="https://user-images.githubusercontent.com/16258136/214496505-017def5a-63db-4a04-a159-08de89ff8840.png">

2. On initial load, on development branch, my intangible hours was 1hr. But on your branch it shows empty box which is a major issue. Upon entering new value and saving stores only the new value. Old value just vanishes. This causes data integrity issues and will leave the application in data loss state.

On dev:
<img width="600" alt="Screen Shot 2023-01-24 at 10 22 24 PM" src="https://user-images.githubusercontent.com/16258136/214496458-2a7f1cfc-e9a3-4780-928a-0cdf07b08bac.png">

But empty in your branch: Refer (1st) image.




NOTE: Upon save I still get error alert which i assume is a different problem irrespective of this PR.
<img width="600" alt="Screen Shot 2023-01-24 at 10 26 09 PM" src="https://user-images.githubusercontent.com/16258136/214496355-45ff7221-d010-4590-9d38-343c9f2635c3.png">

2023-01-27 04:28 UTC, KaixiangGU commented
Hi @RJBornToWin Thanks for the review.

1. Sure, I will fix that negative number issue.

2. For old data, here is the problem. If you check current code base, I mean FE development branch. The way how to calculate intangible hours is that get all the time entries data, and sum up hours of all the intangible time entries. It actually didn't have any data stored in the database but it works in the past because intangible hours is not allowed to edit. 

But if it needs to be editable, I have to create an intangible hours property in the database and keep track of it when users make any changes. So, if this branch get merged, intangible hours will be start from 0.

Currently, I cannot think of any ways to keep old data and also make intangible hours editable. If you have any idea, please let me know! Thank you!

@one-community Hi Jae, do you really need keep all the old data of intangible hours? Or you okay with reset it from zero when it gets merged?

2023-01-27 22:33 UTC, one-community commented
I'm ok if we lose the old intangible hours data.

2023-01-28 18:47 UTC, RJBornToWin commented
@one-community : If you do not need the old intangible entry, how about removing the field ? We can add intangible entries from the user profile anyways.

2023-01-28 20:04 UTC, one-community commented
I don't need the old intangible entry data because I have it all tracked on a spreadsheet, going back 10 years, for the entire management team. So I can manually enter it and then I want this to properly update it.

2023-01-29 00:45 UTC, KaixiangGU commented
Hi @RJBornToWin , I made new changes as requested, I updated the description at the top of the page. Please check it out, thank you!

2023-02-02 17:27 UTC, RafaelCastilhoCastro commented
Hi @KaixiangGU,
I tested the PR and both tangible and intangible fields are editable. The numbers are properly centered too.
I found some issues though:

1. Add intangible time -> access user profile -> change intangible hours to 0 -> Dashboard -> click checkbox tangible OR delete intangible time entry -> user profile -> Got negative intangible time.
I'm not sure if this is a bug since the fields will be editable, but I think its worth mentioning so it doesn't become a problem in the future.
![1](https://user-images.githubusercontent.com/65736872/216395845-699720aa-716d-446e-9dc3-48f76949efd1.jpg)

2. The fields are accepting multiple zeros. It isn't causing problems with the data when saving according to my tests. I think it might be a good idea to fix it though.
![2](https://user-images.githubusercontent.com/65736872/216397182-7f5fbb54-e3c4-4815-b07e-4f6deccf5691.jpg)

3. The fields are accepting a large number of caracters before and after the decimal "."
![3](https://user-images.githubusercontent.com/65736872/216397534-1b0d28c9-ecce-4eb0-bad1-2b8b60fd7dfe.jpg)

Thanks.

2023-02-02 18:37 UTC, KaixiangGU commented
Thank you @RafaelCastilhoCastro 
I'll take a closer look at #1 and #3.

For #2, I tried to solve this leading zeros issue in this PR. But cannot come up with a proper solution. If you have any idea about this, please let me know!

2023-02-03 00:00 UTC, tingedudu8 commented
Hi @KaixiangGU, I pulled both FE and BE and tested, but I found that I cannot make any change to Intangible time, is there something wrong with Intangible data? Thanks!

https://user-images.githubusercontent.com/70128933/216478195-2a111094-5ef2-4e12-aed5-71e7224468e5.mov

2023-02-03 01:53 UTC, KaixiangGU commented
Hi @tingedudu8, It should work, Rafasel just tested it. From your video, it looks like BE is not running properly, I put BE link at the top of the page, please double check you're using the right PR. If there are any related errors on your console, please take a screenshot would be even better. Thank you!

2023-02-04 10:07 UTC, PrabhjotSembhi commented
@KaixiangGU Hey, I am not seeing option to edit intangible hours
 
![PR 635 ](https://user-images.githubusercontent.com/82662768/216761239-61284f70-1c05-41d5-8c05-c1d256f9b964.jpg)

2023-02-08 21:25 UTC, Filipe-Oliv commented
HI @KaixiangGU 

1 - when I added the intangible hours in the volunteering times tab, an error popup appeared as shown in the image;

![week 03 - 02-08-23 (6)](https://user-images.githubusercontent.com/114119668/217654346-0ba2439b-8274-4d7c-a4f7-d2d98027c4b8.png)
 
2 - when I returned to the main page, the box for the current week remained reset;

3 - when I added the main intangible time, the task was added to the task box and timalog, but the current week box kept with zero;

4 - when I returned to the volunteering times in the profile, there was an addition to the manual time added in the main with the time manually added in the volunteering times.

[week 03 - 02-08-23 (5).webm](https://user-images.githubusercontent.com/114119668/217651519-58bf07fe-f662-4e39-bce3-b927745dce1c.webm)

2023-02-16 19:31 UTC, PrabhjotSembhi reviewed
it's not working correctly when I check the box to switch intangible to tangible Time is not get updated. Please watch video 

https://user-images.githubusercontent.com/82662768/219467957-dd823194-98f2-45b6-becd-32536d9946bd.mp4

2023-02-17 16:58 UTC, Lunaliar commented
I wasn't able to adjust the intangible time on other users' profiles as well as the current controlled profile. It seems like the form is not updating to the BE but Im not entirely sure. I really like the layout and formatting designs for this, however.
Here are some pics of my attempts to adjust the intangible time.
![Screenshot from 2023-02-17 11-01-28](https://user-images.githubusercontent.com/98275089/219713893-02cbc1ce-5091-46b7-ae84-0ad9c46b3d30.png)
![Screenshot from 2023-02-17 11-01-42](https://user-images.githubusercontent.com/98275089/219713928-762e6791-7a6a-4fc5-b72e-4f77be9a3429.png)


Seeing some functional components instead of class-based ones was really nice, I really like how you write your variables. I do have a few housekeeping things that may need a little attention.

In DeleteModal.jsx there are a few console.log functions on lines 23 & 28

In TimeEntry.jsx there is an unused variable on line 11 

In TimeEntryForm.jsx 
1) . There is an unused variable on line 24
2). There are 2 console.log functions on lines 397 and 444

In VolunteeringTimeTab.jsx there is a console.log function on line 198

2023-02-17 17:37 UTC, vitorsaa2k commented
Im able to edit to intangible hours, but, there are a few problems:

1. I still get the error alert.
2. I can "accidentaly" make the intangible hours turn to a negative number.

https://user-images.githubusercontent.com/17365161/219722938-9771a1aa-30d6-4297-9953-30a195937059.mp4

As showed in the video:
1. I have created an intangible hours entry of 2hours
2. Edited the intangible hours on the profile to 0
3. When marking the intangible hours as tangible, the intangible hours on the profile turns into a negative number

2023-02-18 18:37 UTC, KaixiangGU commented
@Lunaliar Thanks for the code check. I will delete those unused variables and console.logs.

2023-02-18 18:39 UTC, KaixiangGU commented
Hi, @vitorsaa2k 
1. You don't have to worry about that error alert, that has been already fixed in the development branch.
2. I'm still working on the negative issue. I will push new commit when I fixed that.

2023-02-19 02:52 UTC, suigunfjc reviewed
Hi @KaixiangGU, I tested checking and unchecking the intangible timelog and the profile updated the intangible time correctly. Except for the error popup when saving the change, everything else looks pretty good to me.

https://user-images.githubusercontent.com/94319381/219909531-cf48cc95-a177-4b25-be46-efd4704cf935.mp4

2023-02-24 01:47 UTC, NyahJ commented
Hi @KaixiangGU,

Follow your tesing suggestions:
First off, I got to manually edit intangible hours and save the change. Then, any new added intangible time entry was added. Last, it increased and decreased accurately for converting between tangible entry and intangible entry.
Since you mentioned the popup window is fixed, everything looks good from my side:) Thank you!
![截屏2023-02-23 下午5 46 51](https://user-images.githubusercontent.com/77643813/221071937-3733c318-9a00-45de-a3ea-bb29c63fd0e4.png)

2023-02-24 14:10 UTC, harlleybastos commented
@KaixiangGU I just tested here and it works but have one error, but once you already said on others comments that is already fixed on development, is okay !

https://user-images.githubusercontent.com/37200778/221199090-0d541220-ffb8-40d3-b454-59e050f38205.mp4

2023-03-03 03:36 UTC, dkamghem commented
I am able to modify tangible time from 5 hours to 10 hours. 
![Screen Shot 2023-03-02 at 9 34 22 PM (2)](https://user-images.githubusercontent.com/83235086/222625217-f9d2b7e0-b7cf-4dc6-8197-415c0c511226.png)
![Screen Shot 2023-03-02 at 9 34 43 PM (2)](https://user-images.githubusercontent.com/83235086/222625227-431f8984-d426-4af5-90a0-269f61a23485.png)

2023-03-03 14:39 UTC, Lunaliar commented
Hey, @KaixiangGU  I came back to this PR to debug my previous errors and was able to edit intangible hrs.
![prior](https://user-images.githubusercontent.com/98275089/222748645-61c6bc67-cb30-4bb1-bb24-aebf6e49e9eb.png)
![post](https://user-images.githubusercontent.com/98275089/222748685-b84d433d-3118-4ea9-ae1c-43c24e95827f.png)

2023-03-11 21:21 UTC, KaixiangGU commented
Updated on 3/11
Prevent negative hours when edit time logs. Any negative hours will turn into zero.

2023-03-13 12:43 UTC, Filipe-Oliv commented
Hi @KaixiangGU 

I managed to add and save negative hours and when I returned to the main my weekly hours goal also became negative.

![(2)](https://user-images.githubusercontent.com/114119668/224704677-2408999b-0272-412f-8cd5-4f60f96938d3.png)

![(3)](https://user-images.githubusercontent.com/114119668/224704684-cac211f1-5d76-494d-8241-997a64d11f01.png)

2023-03-15 15:44 UTC, rauleffting requested changes
Hi @KaixiangGU.

I've tested your PR and I was able to change the number inside the intangible time input. However, this is not affecting intangible time in other places, like the leaderboard. Is this supposed to behave like that?


https://user-images.githubusercontent.com/29555732/225363243-8ca0342f-e840-4166-9945-505390fda254.mp4


Still, you must have to delete some debug outputs. I've marked them for you.

Thank you very much!

2023-03-15 15:44 UTC, rauleffting commented on src/components/Timelog/DeleteModal.jsx
> +      console.log(category);
Here too.

2023-03-15 15:44 UTC, rauleffting commented on src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
> +  console.log(hoursByCategory);
Here too.

2023-03-23 04:57 UTC, KaixiangGU commented
@one-community Hi Jae, I think Raul just pointed out a good question. (Please check his video above)

If I manually edit the intangible hours, do I need also to change the number in effort bar under weekly timelog tabs? 

For the leaderboard, it only displays tangible hours, right? Editing intangible hours will not affect the leaderboard.

2023-03-23 21:26 UTC, one-community commented
> If I manually edit the intangible hours, do I need also to change the number in effort bar under weekly timelog tabs?

No, that bar is only for the current week and should only show time logged via that page

> For the leaderboard, it only displays tangible hours, right? Editing intangible hours will not affect the leaderboard.

It shows only tangible as the bar but intangible are included in the number on the right... editing these numbers from the Profile page though should not affect that.

2023-03-27 21:18 UTC, rauleffting approved these changes
Hi, @KaixiangGU. I've tested your PR and it worked perfectly.

https://user-images.githubusercontent.com/29555732/228068576-0d2c380f-2584-4e0a-bf81-928dbf37f68d.mp4

I verified that you also made the changes that I requested.

Thank you very much! Approved!

2023-04-02 04:12 UTC, one-community commented
Thanks everyone! Meeeeeeeerrrrrrgggggggiiiiinggggggggg! 👍

2023-04-02 04:12 UTC, merged