Added new tab to Timelog component. Displaying the last three summari…
OneCommunityGlobal/HighestGoodNetworkApp pull request #639
Opened 2023-01-06 21:06 UTC by LeeSingChanYau

It was requested that we have a new tab in the Timelog Component in the dashboard to display the last three summaries of the current user we are seeing. This PR adds a new tab to the timelog and also displays the last three summaries. I tested this and it is displaying the last three summaries of the userProfile object that is returned, but I encountered a problem. The last three summaries I am getting are all of the current week (8th of January 2023 deadline), I tried different accounts and I see the same problem. 
Files changed:
- Timelog.jsx
- Dashboard.jsx
- SummaryBar.jsx
Filex created:
-WeeklySummaries.jsx

2023-02-03 15:14 UTC, rauleffting commented
Hi @LeeSingChanYau. I think there might be a problem in that part of the code. Probably on loading the HTML elements as a string:

![211335428-2cd6311c-dfee-4aaa-bb74-6c3fe4c09ab7](https://user-images.githubusercontent.com/29555732/216638620-06feab42-8f14-46f8-98d2-12343aa54178.png)

Could you take a look? I think it's very simple to fix. Thanks!

2023-02-18 07:07 UTC, agujjar2206 commented
I believe these are the last three summaries of the userProfile object.
<img width="1440" alt="639-1" src="https://user-images.githubusercontent.com/94432002/219846723-ae54b2ca-3602-4563-ad56-404f4dccc8fe.png">

2023-02-19 03:15 UTC, suigunfjc commented
Can't open the dashborad page, there is an error in `<WeeklySummaries>` component.
![Screenshot 2023-02-18 191326](https://user-images.githubusercontent.com/94319381/219910168-f8ad7396-5941-4e85-ac62-d73d1b9422f0.png)

2023-02-19 03:43 UTC, suigunfjc submitted a review, later dismissed
Hi @LeeSingChanYau , please address my comment on WeeklySummaries.jsx, that is causing me not able to launch the branch.

2023-02-19 03:43 UTC, suigunfjc commented on src/components/Timelog/WeeklySummaries.jsx
> +      {userProfile.weeklySummaries[1].summary ? (
For a user don't have any summary, the length of `userProfile.weeklySummaries` is 1 and line 16&26 will cause a crash.

2023-02-19 05:53 UTC, NyahJ commented
Hi  @LeeSingChanYau,

After using different testing accounts, the result on my side went well greatly:
 
<img width="1426" alt="截屏2023-02-18 下午9 48 30" src="https://user-images.githubusercontent.com/77643813/219931416-52379431-b5d0-4bd7-99a2-5d4a193cedf0.png">

<img width="1430" alt="截屏2023-02-18 下午9 49 01" src="https://user-images.githubusercontent.com/77643813/219931411-5ccb7632-8611-49a8-b126-088123bfce7c.png">

A tiny advice on the font of the last 3 summaries, it would be better to be smaller and consistent with the page :)

2023-02-23 20:38 UTC, tingedudu8 requested changes
Hi @LeeSingChanYau, I tested your PR and the weekly summaries are not properly displayed. Please check your rendering part of code.
<img width="1777" alt="PR639" src="https://user-images.githubusercontent.com/70128933/221024652-141e3779-fe25-4b51-836d-788b0563fc12.png">

2023-02-25 13:19 UTC, vitorsaa2k requested changes
Hi @LeeSingChanYau,

It worked in some parts but not in others.
![image](https://user-images.githubusercontent.com/17365161/221358862-105e7e9c-e8c0-4d99-8e85-0d4f4c25cd54.png)

- The rendering of the summaries seems to not be working well.
- Also, would be good if the title that separate the date of the summaries was more visable, Maybe changing the color or adding something around the make obvius that it is a title

2023-03-04 22:15 UTC, ayush0904 commented
Hi @LeeSingChanYau Please see the below image.
The HTML tags are also getting printed along with the text.
<img width="771" alt="Screen Shot 2023-03-04 at 2 14 10 PM" src="https://user-images.githubusercontent.com/15180550/222931006-31aacdc7-d2af-48d1-ae7a-3b257bfd5bf8.png">

2023-03-07 23:46 UTC, mpavithr commented
Hi, as other reviewers have noted above, I am also facing the same issue with the tags being printed.
<img width="491" alt="pr639_1" src="https://user-images.githubusercontent.com/42751267/223581383-56751c42-9f03-421d-9f48-000d38c4ca94.PNG">

2023-03-25 03:24 UTC, LeeSingChanYau commented
@vitorsaa2k @mpavithr @ayush0904 Hello guys, thank you for your feedback. Please pull the changes, and review again. You shouldn't see the html tags anymore. Thanks!

2023-04-10 18:40 UTC, vitorsaa2k approved these changes
Working as intended.
![image](https://user-images.githubusercontent.com/17365161/230970003-c0b91964-ecbb-476b-929e-db212e9ffd2e.png)

2023-04-10 18:49 UTC, one-community commented
Excellent, thank you everyone. Moving to final review.

2023-04-11 14:59 UTC, rauleffting approved these changes
Hi, @LeeSingChanYau. It worked perfectly.

![image](https://user-images.githubusercontent.com/29555732/231203910-4ccc1436-00d1-4732-84b9-f6b7a9006c34.png)

Thank you!

2023-04-11 15:05 UTC, merged