Raul fix header menu displaying behind content on small screens
OneCommunityGlobal/HighestGoodNetworkApp pull request #676
Opened 2023-02-06 19:15 UTC by rauleffting

# Description
(HEADER COMPONENT - PRIORITY LOW) 

> (PRIORITY LOW) Raul: (WIP Raul) Header menu displays behind content when opened. How to test:
> a. Use a smartphone or a tablet. Must be something with a small screen. You can also decrease browser window size.
> b. Then, open the menu clicking on the header burguer(top right). 

## Mainly changes explained:
In Header.jsx, was added a 'z-index: 10' to the Navbar, so it cannot be overlapped by page content on small screens anymore.

## How to test:
1. git checkout raul_fix_menu_displaying_behind_content
2. npm install
3. npm run start:local
4. log in with any user
5. Verify if the header menu is being overlapped by content on small screens after clicking on the dropdown button (you can test it by changing the resolutions with the inspection resource on Chrome). The proper resolutions to test are **between 425px and 991 px**.

### Here are two videos to help you:

1. Dropdown behavior (BEFORE):

https://user-images.githubusercontent.com/29555732/217062841-a1253109-7349-485d-970e-fbc522d16f12.mp4

2. Dropdown behavior (AFTER):

https://user-images.githubusercontent.com/29555732/217063827-cbb6c176-8e16-40cb-a5a5-3c18994e9a27.mp4

2023-02-06 22:38 UTC, Filipe-Oliv commented
Hi @rauleffting 

Working well.

![week 03 - 02-06-23 (1)](https://user-images.githubusercontent.com/114119668/217102566-25db8ccd-e5b6-44f8-9551-e632b3ff61dc.png)

2023-02-07 01:03 UTC, NyahJ commented
Hi @rauleffting,

Works well, thanks for your efforts!

https://user-images.githubusercontent.com/77643813/217121472-dd8867cb-bf06-418e-a084-091b95dea150.mp4

2023-02-07 06:58 UTC, tingedudu8 commented
Hi @rauleffting, I tested by different resolutions and they all worked well. However, I do see some warnings in console. I guess they are BE problems, do you know why I met these problems? Thanks!
<img width="1779" alt="Screen Shot 2023-02-07 at 12 58 05 AM" src="https://user-images.githubusercontent.com/70128933/217170796-07156523-c054-4a58-b2fd-21c71da32795.png">

<img width="1783" alt="Screen Shot 2023-02-07 at 12 57 44 AM" src="https://user-images.githubusercontent.com/70128933/217170811-0207b503-4d42-49d9-bee1-4e6a1add91e1.png">

2023-02-07 16:21 UTC, rauleffting commented
Hi, @tingedudu8! No problem. Those issues already were y in the application. They are not related to this PR. Thank you for your concern!

2023-02-07 21:04 UTC, rauleffting commented
Please, guys! If you review and everything works, approve it.

2023-02-07 21:14 UTC, Filipe-Oliv approved these changes

2023-02-07 23:26 UTC, AnishPandita commented
Hello @rauleffting I tested your PR and it works well. The menu overlaps the content behind correctly and does not overfill on smaller screen sizes. Tested on multiple smaller screens.
<img width="1436" alt="Screenshot 2023-02-07 at 3 23 45 PM" src="https://user-images.githubusercontent.com/111321945/217389808-70602dea-763c-4233-9443-19ef58e13513.png">
<img width="1440" alt="Screenshot 2023-02-07 at 3 22 52 PM" src="https://user-images.githubusercontent.com/111321945/217389820-0e4789bd-c2fe-40f7-936d-56ed2db6a12e.png">

2023-02-08 04:06 UTC, KaixiangGU requested changes
Hey @rauleffting 
It works when the menu is not expanded, but if you click one of those collapse menus you can see the badge number on the dashboard is overlapping the menu. See the picture below.
![review_FE_PR#676_1](https://user-images.githubusercontent.com/98206107/217430768-59fc687d-21af-4391-a486-c676bd21517a.JPG)
![review_FE_PR#676_2](https://user-images.githubusercontent.com/98206107/217430832-485f10cb-7256-4942-b5d6-c93e74a66d51.JPG)

2023-02-08 14:51 UTC, rauleffting commented
Hi @KaixiangGU. Please, review again!.

2023-02-08 18:26 UTC, KaixiangGU commented
@rauleffting Works well, thank you!

2023-02-08 18:27 UTC, KaixiangGU approved these changes
Reviewed, all good!

2023-02-08 21:38 UTC, merged