validate input at forgot password page
OneCommunityGlobal/HighestGoodNetworkApp pull request #677
Opened 2023-02-11 03:08 UTC by juneluo

### Description
**Fixes bug priority low 3 of LOGIN COMPONENT: Fix missing validation for email in the “forgot password” page**
a) The validation for email is missing in the “forgot password” page. Invalid email is accepted.
b) “Please enter your full name” appears if the submit button is clicked without first and last name. 
     But providing the values, doesn’t remove the error even after clicking submit.

### Mainly changes explained:
It will check whether the input matches the schema and show alert if not during the entering process and after clicking submit button.
<img width="589" alt="img" src="https://user-images.githubusercontent.com/9314962/218235923-dbc5d2d1-0757-420c-b0b0-c37e5ca6eb90.png">

### How to test:
check into current branch
do npm install and ... to run this PR locally
Login page --> forgot password link --> enter invalid email/ leave name empty -->enter valid email address and full name

2023-02-11 08:29 UTC, Theophileaseh approved these changes
## Approved

Hi @juneluo 

Great work. 🎉 
The app works perfectly fine and the validations work as expected. ✔️ 

https://user-images.githubusercontent.com/51954313/218248303-176c9c43-bc68-4275-97da-ea51279622d8.mp4

2023-02-11 08:30 UTC, Theophileaseh approved these changes
## Approved

Hi @juneluo 

Great work. 🎉 
The app works perfectly fine and the validations work as expected. ✔️ 

https://user-images.githubusercontent.com/51954313/218248303-176c9c43-bc68-4275-97da-ea51279622d8.mp4

2023-02-11 14:43 UTC, Filipe-Oliv approved these changes

2023-02-11 14:48 UTC, Jorge-Nerd reviewed
It seems to me that it is working very well

2023-02-11 14:53 UTC, Filipe-Oliv commented
Hi @juneluo 

I tested your PR and it's working correctly.

[week 03 - 02-11-23 (#677).webm](https://user-images.githubusercontent.com/114119668/218263940-0ebfa2c6-f05e-4086-a9eb-a2a413f7e344.webm)

2023-02-11 21:30 UTC, AnishPandita commented
Hello @juneluo I tested your PR #677 and It seems to be working great. I had a quick question even though there is a check to ensure the text boxes are not empty but the user can still put in blank spaces as names. Should there be a check that there is atleast one character entered?
<img width="1440" alt="Screenshot 2023-02-11 at 12 34 38 PM" src="https://user-images.githubusercontent.com/111321945/218280193-b5952bd3-bf74-448e-af1e-3daee3b29334.png">
<img width="1440" alt="Screenshot 2023-02-11 at 12 35 50 PM" src="https://user-images.githubusercontent.com/111321945/218280197-76b95b6a-c027-40d1-8a52-2fc27db6977b.png">
<img width="1440" alt="Screenshot 2023-02-11 at 12 36 02 PM" src="https://user-images.githubusercontent.com/111321945/218280202-e84f3b38-81ba-4d0d-80dd-de19534e7af6.png">

2023-02-12 02:40 UTC, RJBornToWin requested changes
Good work here by using joi, combining multiple states into single user object.

I have 1 suggestion and 1 problem.
1. Problem: 
   a. Email without dot (.) is accepted

 <img width="400" alt="Screen Shot 2023-02-11 at 6 11 43 PM" src="https://user-images.githubusercontent.com/16258136/218289633-1e5fd041-0479-4568-adf0-8fc349444640.png">

   b. Also on consequent changes, adding space bar to email adds "dot" (.)

https://user-images.githubusercontent.com/16258136/218289766-8494bcc2-7d05-4ff1-aaf7-90a96671a592.mov

   c. Instead of variable name being exposed or shown, please change it to descriptive words. 
       Eg: firstName to be changed as "First Name"

3. Suggestion:
Instead of validating on user entering the details, i suggest to check it on submit button click. 
Jae can take a call if this is okay or the behavior you have added is okay. @one-community  
https://user-images.githubusercontent.com/16258136/218289808-a74b9d3f-d123-4cc7-9823-4a827a7310d1.mov

2023-02-13 08:36 UTC, Gukal7 commented
Hi @juneluo, I have also tested your code and it works like required. But like @RJBornToWin noticed that the email is accepted without a dot (.). Also I believe the prompt should be like plain english "First Name" is not allowed to empty instead of like a coding variable "firstName".


<img width="668" alt="Screenshot 2023-02-13 at 2 01 10 PM" src="https://user-images.githubusercontent.com/30505274/218408610-0e20ed21-11a6-4a1f-ad05-24ce94bb0797.png">

2023-02-13 17:23 UTC, RafaelCastilhoCastro commented
Hi @juneluo,
I tested your PR and your proposed changes are working as intended.
I tried to replicate the issue pointed out by @RJBornToWin where two spaces create a dot but it didn't happen with me.
Besides that, I observed the same results on other issues reported: email being accepted without ".sufix" and variables name on the alert messages.
Thanks

2023-02-13 22:57 UTC, vitorsaa2k commented on src/components/Login/ForgotPassword.jsx
> +    var vaildateResult = {};
there's a misspelling on the "validateResult" variable, which is being spelled as "vaildateResult"

2023-02-13 23:22 UTC, tingedudu8 reviewed
Hi @juneluo, I tested your PR and all the proposed changes mentioned above worked as intented. But still the email accepted special symbols that should not appear, like "&#!", please take a look, thanks!

https://user-images.githubusercontent.com/70128933/218597201-efdf33a2-7513-45a1-912d-f01e1ae03593.mp4

2023-02-14 00:27 UTC, RJBornToWin approved these changes
Works as intended.

2023-02-14 05:05 UTC, merged

2023-02-14 13:27 UTC, Filipe-Oliv commented
First and last name popups are in inverted fields.

![02-14-2023 (1)](https://user-images.githubusercontent.com/114119668/218751213-515d9e30-d21f-4df5-824f-11e5aaf3c037.png)

2023-02-14 23:59 UTC, one-community commented
Wow, yes good catch Filipe! 

Please raise the PR fix soon and PM me with it @juneluo so I can just merge it without a bunch of reviews.