Set Task tab as default after login
OneCommunityGlobal/HighestGoodNetworkApp pull request #686
Opened 2023-02-23 20:48 UTC by RafaelCastilhoCastro

# Fixes PROJECTS/TASKS/WBS COMPONENT (BUG #14 PRIORITY LOW)

This PR intends to set the Tasks tab as default when acessing the Dashboard. So the Task tab should automatically open after the login and when returning to Dashboard after navigating the App. This is suposed to happen to all account roles except a volunteer account with **no** task wbs assign to it. Volunteer accounts **with wbs tasks** should have Tasks tab as default too.

## Related PR's
This frontend PR is related to the old [#535](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/535) frontend PR. I took over to completed it but there were too many conflicts to be safely merged so raising a new PR was safer.

## How to test:
Keep backend on development
check into this PR on frontent
run `git pull` and `npm install`
log as different account roles and test if with all of them (except volunteer with no WBS) the Tasks tab is shown first.
Assign a **WBS task** to a volunteer account and test if the Task tab is being displayed first.

![image](https://user-images.githubusercontent.com/65736872/221022404-84ba38d0-85c6-48bc-87a1-2dc4e8183714.png)

## Note:
Please observe that it's necessary to have a **WBS task** assigned to it not just a Project. If you're not sure how to do it, please check video below.

https://user-images.githubusercontent.com/65736872/221026449-4a37f61e-a1e8-4099-9cc8-e963ceb947f7.mp4

2023-02-24 04:17 UTC, agujjar2206 commented
Hello @RafaelCastilhoCastro, I have tested the PR and it works as expected.

1. Admin account displays "Tasks" tab as default:
<img width="1439" alt="686-1" src="https://user-images.githubusercontent.com/94432002/221090349-cbd7b58e-f022-49ad-9f75-c11383b0a5b0.png">

2. Volunteer account without WBS task does not display "Tasks" tab as default:
<img width="1439" alt="686-2" src="https://user-images.githubusercontent.com/94432002/221090437-17034abe-1501-4758-819a-752fb18cb910.png">

3. Volunteer account with WBS task displays "Tasks" tab as default:
<img width="1438" alt="686-3" src="https://user-images.githubusercontent.com/94432002/221090559-13291f29-8f71-4a9c-8ba1-488b57e80e18.png">

Thanks.

2023-02-24 04:19 UTC, agujjar2206 submitted a review, later dismissed

2023-02-24 04:20 UTC, vanelnw submitted a review, later dismissed
Hi @RafaelCastilhoCastro 
Great Job, i tested this PR and its works as expected
-Frist i login with a volunteer without task assign  then the Task tab wasn't set

https://user-images.githubusercontent.com/38879488/221090489-74855a24-f64d-453d-9386-673feb4c1702.mp4

- Next i assign tasks to that volunteer user and login again then the task tab was set be default

https://user-images.githubusercontent.com/38879488/221090701-44e3ce36-c4c9-4954-a8c0-4e59d14ad40b.mp4

- I also login with another account and it's work well

2023-02-24 06:42 UTC, angelinatr15 commented
Hi @RafaelCastilhoCastro, 

I tested this PR and it displayed the task bar as default for every login except the volunteer-no-task as expected. I assigned each account with a WBS task except the volunteer-no-task account. I logged in to each account and clicked around to different tabs then returned to the dashboard to see if it would still render the task tab as default. This was the case for every account except the volunteer-no-task which was also to be expected. I started logging into the accounts in the following order: admin, role-master, mentor, manager, testing, volunteer, volunteer-no-task, and core-team. 

https://user-images.githubusercontent.com/97488347/221109285-f0379f6b-f330-45c3-8a73-8035b5c70bf1.mov

2023-02-24 06:50 UTC, angelinatr15 submitted a review, later dismissed

2023-02-24 08:14 UTC, AnishPandita commented
Hi, I tested the PR and its working as intended. When the user is admin, the task tab is default. When user is volunteer but has a WBS task, task tab is default. When user is volunteer but has no WBS task, current week timelog is default. 
<img width="1440" alt="Screenshot 2023-02-24 at 12 06 41 AM" src="https://user-images.githubusercontent.com/111321945/221127014-42b35dbd-2585-4b1c-80ed-72ec1362e65f.png">
<img width="1440" alt="Screenshot 2023-02-24 at 12 07 29 AM" src="https://user-images.githubusercontent.com/111321945/221127061-b26c511d-13b3-4339-824e-fb2b96adc164.png">
<img width="1440" alt="Screenshot 2023-02-24 at 12 08 58 AM" src="https://user-images.githubusercontent.com/111321945/221127074-d3d5996c-3b42-4c6c-ac8a-a9f02c6825e8.png">

2023-02-24 19:41 UTC, kamtoeddy submitted a review, later dismissed
Hi @RafaelCastilhoCastro,

Tested and everything works plus the code is ok
![Screenshot (515)](https://user-images.githubusercontent.com/65472478/221275445-769689ed-c74a-4fb0-9106-9f56774b4579.png)
![Screenshot (516)](https://user-images.githubusercontent.com/65472478/221275472-61cc98eb-8316-400c-9eb5-5113a05bee72.png)
![Screenshot (517)](https://user-images.githubusercontent.com/65472478/221275525-13802ae4-1ef5-455f-8c3e-bf6f1a9ee7cc.png)
![Screenshot (518)](https://user-images.githubusercontent.com/65472478/221275557-dd36480c-9dc7-4125-a316-c0409f4445da.png)

2023-02-24 21:57 UTC, suigunfjc reviewed
Hi @RafaelCastilhoCastro , I tested the PR by logging in with three different roles as Admin, Manager and Volunteer. The task tab was displayed as expected for Admin and Manager. For the volunteer, it showed as default after I assigned it a task. Well done! 
![Screenshot 2023-02-24 133636](https://user-images.githubusercontent.com/94319381/221300366-e365ef3f-abcc-4b76-aa0b-b836acf4b671.png)
![Screenshot 2023-02-24 133827](https://user-images.githubusercontent.com/94319381/221300367-0a91b974-5f2a-44e4-a2c8-4bf04e1cd7d0.png)
![Screenshot 2023-02-24 133933](https://user-images.githubusercontent.com/94319381/221300368-493a83ef-f551-433d-9a69-08b317e9b7d0.png)
Though there is one thing I am concerned about, in your PR there is also an update about `deleteSelectedTask` and marking tasks as done. I think there will be a conflict with #684.

2023-02-24 22:52 UTC, one-community commented
Excellent job everyone, thank you. Rafael, resolve the merge conflicts and I'll move this one to final review.

2023-02-25 01:22 UTC, NyahJ commented
Hi @RafaelCastilhoCastro , 

Good work! I followed your video to test for different 2 accounts, they all worked as intended.

![截屏2023-02-24 下午1 48 03](https://user-images.githubusercontent.com/77643813/221328188-0caa4d02-003b-4652-87c4-ddd8951e4817.png)
![截屏2023-02-24 下午1 49 30](https://user-images.githubusercontent.com/77643813/221328190-23a906c8-b258-4afe-99da-872f57334bf7.png)
![截屏2023-02-24 下午5 20 42](https://user-images.githubusercontent.com/77643813/221328193-59c5a248-aed3-43da-a816-20a46779c884.png)

2023-02-25 01:25 UTC, NyahJ submitted a review, later dismissed
Already left comments and test result, so I am just gonna approve this.

2023-02-25 01:43 UTC, crystalsong2021 commented
I tested out the functionality and it works as expected like you mention in the PR. Nice work @RafaelCastilhoCastro 
https://user-images.githubusercontent.com/18197013/221329193-87bd3e59-0d0f-4be9-99a6-2d3a042ec94c.mov

2023-02-25 02:26 UTC, anant2047 commented
I tested the PR. It works as expected. Sharing the homepage when you login for admin, volunteer without WBS, and then assigning WBS to volunteer and opening again.
<img width="812" alt="Screen Shot 2023-02-24 at 5 42 23 PM" src="https://user-images.githubusercontent.com/97596031/221331377-0d02244d-9fd0-4d4a-95a7-7b0d4e535174.png">
<img width="935" alt="Screen Shot 2023-02-24 at 6 06 40 PM" src="https://user-images.githubusercontent.com/97596031/221331388-67346b20-d90f-408f-88c7-2ac05d243841.png">
<img width="896" alt="Screen Shot 2023-02-24 at 6 23 59 PM" src="https://user-images.githubusercontent.com/97596031/221331396-94193ad6-057c-4bdd-9780-7e8251434ffd.png">

2023-02-25 02:29 UTC, anant2047 submitted a review, later dismissed
I gave minor comments. Please fix them and functionally wise it's good. Bravo!

2023-02-25 02:36 UTC, tingedudu8 commented
Hi @RafaelCastilhoCastro, I noticed that if I assigned the task to a volunteer then deleted it, the default page should not be the task tab right? However, the task tab still open automatically after returning to the dashboard.

https://user-images.githubusercontent.com/70128933/221331936-c09b88d9-12c9-4c19-895c-cdc34383ea11.mov

2023-02-25 10:44 UTC, vitorsaa2k commented
Great PR @RafaelCastilhoCastro! I tested using the following steps:

1. WBS assigned to a user doesn't make the task tab as default
2. Assining a task to the same user and opening the dashboard again makes the task tab as default
3. Deleting the task assigned to the user doesn't make the task tab as default
4. In an admin account the task tab will always be the default tab

https://user-images.githubusercontent.com/17365161/221352558-3703c3fc-6e9c-4d0f-ac4e-46083cfad20c.mp4

2023-02-25 10:44 UTC, vitorsaa2k submitted a review, later dismissed

2023-02-25 15:07 UTC, rauleffting requested changes
Hi @RafaelCastilhoCastro. Your PR was tested and everything is working quite well, as you can see below:


https://user-images.githubusercontent.com/29555732/221364276-0e5df195-78ea-49f0-ad10-1de635097a60.mp4


However, there is one debug output line in your code that must be deleted. Can you do this? Thereafter, I'm going to approve it!

Good job! Thank you very much!

2023-02-25 15:07 UTC, rauleffting commented on src/components/TeamMemberTasks/TeamMemberTasks.jsx
> +          console.log('task before', task.task)
To delete.

2023-02-25 20:30 UTC, RafaelCastilhoCastro commented on src/components/TeamMemberTasks/TeamMemberTasks.jsx
> +          console.log('task before', task.task)
Removed, thanks.

2023-02-25 23:36 UTC, Jorge-Nerd commented
Hi @RafaelCastilhoCastro seems to me to be working correctly
![image](https://user-images.githubusercontent.com/77848827/221384033-e453b397-a014-43b8-b673-7d2a3cee8acb.png)
and appears the new project in the volunteer project
![image](https://user-images.githubusercontent.com/77848827/221384068-54c211af-6a15-4a8f-b1b2-8e7e6258741f.png)
In the branch development does not appears  task as a default
![image](https://user-images.githubusercontent.com/77848827/221384431-d7a7018b-081a-44ab-ae96-f2163c018222.png)

2023-02-25 23:58 UTC, mpavithr commented
Hi, everything seems right and it seems to be working correctly from my end.
Dev admin has task as default
<img width="726" alt="raphael_pr1" src="https://user-images.githubusercontent.com/42751267/221385042-a4089885-4556-4214-9d7d-7c14d7294af5.PNG">
Volunteer with no tasks does not have task as default
<img width="569" alt="raphael_pr2" src="https://user-images.githubusercontent.com/42751267/221385045-39ef0c10-de35-4962-8804-4a2109e3133d.PNG">
Volunteer with tasks have it as default
<img width="763" alt="raphael_pr3" src="https://user-images.githubusercontent.com/42751267/221385051-49629fea-4ad5-4559-aec7-bac44d984536.PNG">

2023-02-27 13:51 UTC, rauleffting approved these changes
Tested and approved!

2023-02-27 15:34 UTC, merged