Lucas user hours set to zero
OneCommunityGlobal/HighestGoodNetworkApp pull request #727
Opened 2023-03-21 15:14 UTC by Lucas-E

This PR solves (PRIORITY LOW) Jae: Special Situation - User Hours Set to Zero

### PLEASE USE THE PROPER BACKEND ([#298](https://github.com/OneCommunityGlobal/HGNRest/pull/298)) SO THE PR CAN WORK PROPERLY

<hr>

### Main changes

Now, Mentor users and users with zero hours are not displayed on the leaderboard and do not add to the HGN totals. Mentor users can only be seen by themselves and Owners, Administrators and Core Teams on the Leaderboard. Also, Mentor users and users with zero hours can see the members on their respective teams.

<hr>

### How to test

- Checkout the current branch on both frontend and backend provided on Slack and on this PR
- npm install (on the backend)
- npm run build (on the backend)
- npm run start (on the backend)
- npm install (on the frontend)
- npm start:local (on the frontend)
- Login as various roles and check the users that appear on the Leaderboard (Mentors and zero hour users should see themselves and team members, Owners, Administrators and Core Team members should be able to see all users, including zero hour users and Mentor users. Other role's users should not see Mentor users and zero hour users)
- Change some user's hours to zero and role to Mentor and check if the the count on HGN Totals changes.

2023-03-21 17:47 UTC, nicollext reviewed
Tested all cases and it is working as expected. 

I just have one doubt, about this case:
    //if the user is not an administrator, nor owner, nor mentor, and also not a core team, it will only see the people from the same team, no zero hour members and not mentor members

When logged as a Volunteer or Manager I can see the Mentor that is at my team. Is this the expected? 
![lucas_user_hours_set_to_zero_Volunteer2](https://user-images.githubusercontent.com/101591708/226689357-818032ed-eb10-4832-82cf-6226cd70b053.PNG)
![lucas_user_hours_set_to_zero_Manager](https://user-images.githubusercontent.com/101591708/226694072-74e4370a-403a-4792-97ea-5edb6c14a87b.PNG)

For other roles it is working as expected. 

1. Administrator, Owner and Core Team are  able to see all users, including zero hour users and Mentor users.

https://user-images.githubusercontent.com/101591708/226692519-385ac921-38cf-45b0-8c70-1a950104cad8.MP4

https://user-images.githubusercontent.com/101591708/226692594-fb93dcee-3d6f-41d2-adcc-ff1387e4adfb.MP4

https://user-images.githubusercontent.com/101591708/226692583-231eedc0-6bb9-46cd-a1be-ac24c7d29d29.MP4

2. Mentors and zero hour users can see themselves and team members. Other role's users should not see Mentor users and zero hour users.

![lucas_user_hours_set_to_zero_Mentor](https://user-images.githubusercontent.com/101591708/226694368-905fcf94-1b4a-4d9b-8457-c228f83f5f3d.PNG)

![lucas_user_hours_set_to_zero_Volunteer2](https://user-images.githubusercontent.com/101591708/226694329-6ee47fb5-622c-49d8-981f-d50a23d3f0d3.PNG)

3. Mentor users and users with zero hours do not add to the HGN totals.

https://user-images.githubusercontent.com/101591708/226696799-61ac7e20-b6e3-4883-a879-c58f786a2e9c.MP4

2023-03-21 18:39 UTC, Lucas-E commented
> Tested all cases and it is working as expected.
> 
> I just have one doubt, about this case: //if the user is not an administrator, nor owner, nor mentor, and also not a core team, it will only see the people from the same team, no zero hour members and not mentor members
> 
> When logged as a Volunteer or Manager I can see the Mentor that is at my team. Is this the expected? ![lucas_user_hours_set_to_zero_Volunteer2](https://user-images.githubusercontent.com/101591708/226689357-818032ed-eb10-4832-82cf-6226cd70b053.PNG) ![lucas_user_hours_set_to_zero_Manager](https://user-images.githubusercontent.com/101591708/226694072-74e4370a-403a-4792-97ea-5edb6c14a87b.PNG)
> 
> For other roles it is working as expected.
> 
> 1. Administrator, Owner and Core Team are  able to see all users, including zero hour users and Mentor users.
> 
> 2. Mentors and zero hour users can see themselves and team members. Other role's users should not see Mentor users and zero hour users.
> 
> ![lucas_user_hours_set_to_zero_Mentor](https://user-images.githubusercontent.com/101591708/226694368-905fcf94-1b4a-4d9b-8457-c228f83f5f3d.PNG)
> 
> ![lucas_user_hours_set_to_zero_Volunteer2](https://user-images.githubusercontent.com/101591708/226694329-6ee47fb5-622c-49d8-981f-d50a23d3f0d3.PNG)
> 
> 3. Mentor users and users with zero hours do not add to the HGN totals.

Hey Nicolle, thanks for the review! Could you please dm me a console print with the expanded array in it on slack?

2023-03-21 18:44 UTC, nicollext commented
> > Tested all cases and it is working as expected.
> > I just have one doubt, about this case: //if the user is not an administrator, nor owner, nor mentor, and also not a core team, it will only see the people from the same team, no zero hour members and not mentor members
> > When logged as a Volunteer or Manager I can see the Mentor that is at my team. Is this the expected? ![lucas_user_hours_set_to_zero_Volunteer2](https://user-images.githubusercontent.com/101591708/226689357-818032ed-eb10-4832-82cf-6226cd70b053.PNG) ![lucas_user_hours_set_to_zero_Manager](https://user-images.githubusercontent.com/101591708/226694072-74e4370a-403a-4792-97ea-5edb6c14a87b.PNG)
> > For other roles it is working as expected.
> > 
> > 1. Administrator, Owner and Core Team are  able to see all users, including zero hour users and Mentor users.
> > 2. Mentors and zero hour users can see themselves and team members. Other role's users should not see Mentor users and zero hour users.
> > 
> > ![lucas_user_hours_set_to_zero_Mentor](https://user-images.githubusercontent.com/101591708/226694368-905fcf94-1b4a-4d9b-8457-c228f83f5f3d.PNG)
> > ![lucas_user_hours_set_to_zero_Volunteer2](https://user-images.githubusercontent.com/101591708/226694329-6ee47fb5-622c-49d8-981f-d50a23d3f0d3.PNG)
> > 
> > 3. Mentor users and users with zero hours do not add to the HGN totals.
> 
> Hey Nicolle, thanks for the review! Could you please dm me a console print with the expanded array in it on slack?

Of course ;)

2023-03-21 19:05 UTC, nicollext approved these changes

2023-03-25 16:54 UTC, kangjay88 submitted a review, later dismissed
Hi @Lucas-E , I have tested this PR with all roles except 'Owner', and it is working as intended. Nice code implementation, here are my examples:
Volunteer: 
![PR727-1](https://user-images.githubusercontent.com/108297706/227730833-c9a01c7c-7fb3-48a6-a2e3-cab1ee8c0acd.JPG)
Manager:
![PR727-2](https://user-images.githubusercontent.com/108297706/227730845-6faaee92-80c9-4ce6-8932-656e69c5d8aa.JPG)
CoreTeam:
https://user-images.githubusercontent.com/108297706/227730855-42046f81-b891-423d-9b88-9ac5c0d71305.mp4
Admin:
https://user-images.githubusercontent.com/108297706/227730923-5b4df2a8-4939-433a-89e3-666ee17559c6.mp4
Mentor:
![PR727-5](https://user-images.githubusercontent.com/108297706/227730938-b012a2f2-9e30-4985-a3a9-e898bb62ab22.JPG)

2023-03-28 19:33 UTC, vitorsaa2k reviewed
Tested with Admin, Core Team, Owner and Volunteer, all cases works as intended, user with the Mentor role can not be seem by volunteer users but the other roles can. Mentor can not be seem by another Mentor. Zero hour users can be seem by Admin or Owners user, but the other roles can't.

2023-04-01 21:32 UTC, Lucas-E commented
@one-community

2023-04-01 22:26 UTC, one-community commented
Excellent, thank you everyone. Moving this pair to final review.

2023-04-05 15:51 UTC, rauleffting requested changes
Hi, Lucas. Your PR is perfect and worked as expected. However, you still need to delete a debug output that was left. 

https://user-images.githubusercontent.com/29555732/230135008-0192ae98-917a-43b3-9e36-a695282778ff.mp4

Thank you very much!

2023-04-13 02:54 UTC, Elisaudo approved these changes
Hi, Lucas, I tested all cases and it is working as expected.

1)Owners, Administrators and Core Team members should be able to see all users, including zero hour users and Mentor users.

[PR#727 PR#298 Video 1.webm](https://user-images.githubusercontent.com/64317219/231634894-914599fd-99cc-4e4d-9b8c-51306883a4ad.webm)

2)	Mentor users can only be seen by themselves and Owners, Administrators and Core Teams on the Leaderboard. 

![PR#727 PR#298 - Mentor users can only be seen by themselves](https://user-images.githubusercontent.com/64317219/231635324-d9cf5243-2e3f-412b-a95e-38007a4def20.png)

![PR#727 PR#298 - Mentor users can only be seen by themselves 2](https://user-images.githubusercontent.com/64317219/231635331-c963c882-0f89-454b-82ac-25a0bd01ecfa.png)

3)	Mentor users and users with zero hours are not displayed on the leaderboard and do not add to the HGN totals. Other role's users should not see Mentor users and zero hour users. (manager, volunteer)

![PR#727 PR#298 - Other role's cannot see Mentor users and zero hour users](https://user-images.githubusercontent.com/64317219/231635691-a111ab70-4496-46ec-be9d-3bac5e1f4ca0.png)

4)	Mentor users and users with zero hours can see the members on their respective teams.

![PR#727 PR#298 - Mentor users and users with zero hours can see team members 1](https://user-images.githubusercontent.com/64317219/231636730-9e04fd8a-3a05-472d-b813-fa8d1a267cca.png)



![PR#727 PR#298 - Mentor users and users with zero hours can see team members 2](https://user-images.githubusercontent.com/64317219/231636867-af689f19-7499-4143-ac2b-537f3f6d9c3e.png)



![PR#727 PR#298 - Elisaudo Team - team members](https://user-images.githubusercontent.com/64317219/231636197-da3b9497-c51e-408b-8425-fb4bc0c6fa57.png)

2023-04-13 17:37 UTC, Lucas-E commented on src/components/LeaderBoard/LeaderBoard.container.jsx
> +  console.log(leaderBoardData)
Done

2023-04-14 18:15 UTC, rauleffting approved these changes
Hi, @Lucas-E. It worked perfectly.

![pic](https://user-images.githubusercontent.com/29555732/232124739-8f00ced3-d5e2-4b34-bc83-8cf495aa74b7.png)

Approved!

2023-04-14 18:28 UTC, merged

2023-04-29 21:49 UTC, one-community commented
Excellent job on this!