Jinchao block the alert when changing user status at userProfile page
OneCommunityGlobal/HighestGoodNetworkApp pull request #730
Opened 2023-03-22 05:30 UTC by suigunfjc

# Description
Fix bug: When clicking the green/grey dot on the userProfile page to change the user status, the saving change alert will incorrectly show up.

## Mainly changes explained:
Update setActiveInactive function.
Rather than first setting userprofile and then calling `updateUserStatus`, the new function directly calls the `updateUserStatus` function with new user data, and then sets `shouldRefresh` to true. In this case, the `userProfile` and `originalUserProfile` will both get updated after updating the database, which will block the alert.

## How to test:

1. Log in as an admin user
2. Go to a user's profile and click the green/grey dot to active and inactive the user
![image](https://user-images.githubusercontent.com/94319381/226809618-8279d604-47ac-4e22-a7e5-44b3d635be98.png)

3. Check if the saving change alert is blocked.

## Note:
When clicking the dot very fast, the status may not be changed after clicking the OK button. Click the dot again will change the status correctly. I tried to reduce the bug occurrence by `await updateUserStatus` but I'm not sure about it. Please give me some suggestions, thanks!

2023-03-22 18:23 UTC, Lucas-E approved these changes
Hey Jinchao, just reviewed your PR and everything works as intended! Great job!

![Captura de tela de 2023-03-22 15-22-24](https://user-images.githubusercontent.com/92558269/227001127-55a9b954-b5ba-4396-ba4f-ce305442fd13.png)
![Captura de tela de 2023-03-22 15-22-21](https://user-images.githubusercontent.com/92558269/227001132-4c7e3ae3-66cf-4b74-b1c0-3c4cc5804f43.png)
![Captura de tela de 2023-03-22 15-22-11](https://user-images.githubusercontent.com/92558269/227001135-d1010b51-5392-41ce-9351-427bed3f32b6.png)

2023-03-22 21:56 UTC, nicollext requested changes
Hi @suigunfjc, I have tested it and noticed that the status is not updating properly when clicked too quickly. 

https://user-images.githubusercontent.com/101591708/227047276-1bf1b4e1-36e9-4f39-bbad-7e1e0265912d.MP4

2023-03-23 07:17 UTC, AnishPandita commented
Hi @suigunfjc I tested your PR and as suggested by @nicollext there seems to be some issue when i click immediately again after updating it once. Its not being reflected properly.

https://user-images.githubusercontent.com/111321945/227130770-78ba61ad-89c0-49ef-81e3-388e2e71a12d.mov

2023-03-23 07:45 UTC, suigunfjc commented
@AnishPandita @nicollext bug resolved, please test again, thanks!

2023-03-24 00:35 UTC, AriaYu927 commented
Hi @suigunfjc , I've tested the functionality and it works perfect. Great job!

https://user-images.githubusercontent.com/94303659/227394126-f0532027-0f53-4111-a943-c2490dc70e9b.mp4

2023-03-24 20:35 UTC, one-community commented
Thank you all, moving to final review

2023-03-25 22:07 UTC, Jorge-Nerd commented
Hello @suigunfjc  the PR seems to work properly 
![Pull#730](https://user-images.githubusercontent.com/77848827/227744611-a83b89d4-f7db-47d7-8c39-dd16210bdc2a.JPG)
![Pull#730_2](https://user-images.githubusercontent.com/77848827/227744617-c882c7fa-29ca-4609-b401-0c7270653f89.JPG)

2023-03-31 22:10 UTC, EvianTan approved these changes
Beautiful implementation. Thank you!

2023-04-01 00:14 UTC, merged