Fix user modal overflow and horizontal scrollbar
OneCommunityGlobal/HighestGoodNetworkApp pull request #784
Opened 2023-04-20 22:07 UTC by ypan710

# Description
(PRIORITY LOW) Kaixiang:  Remove the horizontal scroll bar on Dev and Main 
Confirmed by at least 2 people but Jae can’t see it on either site using his computer. 
![Screen Shot 2023-04-17 at 10 29 41 PM](https://user-images.githubusercontent.com/46613683/232680499-c56b5735-7920-40be-9242-d24320e45edb.png)

## Mainly changes explained:
Hid horizontal scrollbar and reduced user modal (dropdown menu under "Welcome, XXX") overflow on dev and main. Related PR: [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/778](url)

## How to test:
1. check into current branch
2. do `npm run start:local` to run this PR locally
3. inspect dashboard and other pages in the application to verify that the horizontal scroll bar has been removed and user modal dropdown menu is no longer overflowing.

## Screenshots

![Screen Shot 2023-04-20 at 2 42 55 PM](https://user-images.githubusercontent.com/46613683/233495384-e1987936-fec5-4198-9fb3-2cd3648444b4.png)
![Screen Shot 2023-04-20 at 2 43 58 PM](https://user-images.githubusercontent.com/46613683/233495396-6e3e0865-0042-49fa-aee0-b32c38bcdf78.png)
![Screen Shot 2023-04-20 at 2 46 04 PM](https://user-images.githubusercontent.com/46613683/233495413-c7661acb-f499-476f-a932-4f919921d4e8.png)

2023-04-20 22:33 UTC, one-community commented
What's the difference between this and this? https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/778

2023-04-20 22:34 UTC, one-community commented
Oh, I see, this is my request from over there. Excellent, thank you!

2023-04-21 00:21 UTC, AnishPandita commented
Hi @ypan710 I tested your PR and I dont see a horizontal scroll. The the user modal dropdown still seems to be overflowing and partially cut at the right end. 
<img width="1439" alt="Screenshot 2023-04-20 at 5 08 51 PM" src="https://user-images.githubusercontent.com/111321945/233512599-038f4c8a-37c5-4661-b2cb-e469b6c304d7.png">
<img width="1437" alt="Screenshot 2023-04-20 at 5 09 01 PM" src="https://user-images.githubusercontent.com/111321945/233512592-4b6e5537-060b-499d-9c85-f19eadefab63.png">

2023-04-21 04:28 UTC, ypan710 commented
> Hi @ypan710 I tested your PR and I dont see a horizontal scroll. The the user modal dropdown still seems to be overflowing and partially cut at the right end. <img alt="Screenshot 2023-04-20 at 5 08 51 PM" width="1439" src="https://user-images.githubusercontent.com/111321945/233512599-038f4c8a-37c5-4661-b2cb-e469b6c304d7.png"> <img alt="Screenshot 2023-04-20 at 5 09 01 PM" width="1437" src="https://user-images.githubusercontent.com/111321945/233512592-4b6e5537-060b-499d-9c85-f19eadefab63.png">

Could you please inspect the dropdown-menu.show class to ensure the transform property has been set as follows:
![Screen Shot 2023-04-20 at 9 22 16 PM](https://user-images.githubusercontent.com/46613683/233540626-5953e105-f9df-4d61-a7a7-c7f1c7ca2b3e.png)

2023-04-21 04:35 UTC, abdel-lall reviewed
The horizontal scroll bar has been successfully removed. The drop down menu is not fully displayed though.

![PR784](https://user-images.githubusercontent.com/49083865/233541546-a4bf37a6-7add-48b9-ac59-d474f3e27ba8.png)

2023-04-21 06:05 UTC, ypan710 commented
> The horizontal scroll bar has been successfully removed. The drop down menu is not fully displayed though.
> 
> ![PR784](https://user-images.githubusercontent.com/49083865/233541546-a4bf37a6-7add-48b9-ac59-d474f3e27ba8.png)

Could you please inspect the dropdown-menu.show class to ensure the transform property has been set as follows:
![Screen Shot 2023-04-20 at 9 22 16 PM](https://user-images.githubusercontent.com/46613683/233540626-5953e105-f9df-4d61-a7a7-c7f1c7ca2b3e.png)

2023-04-21 16:16 UTC, NataliaCavicchioli commented
Hey @ypan710, we no longer have the scroll bar! This is good.

The dropdown is also not overflowing anymore, but when the page has a vertical scroll bar, it cuts part of the dropdown. I've included screenshots below to make it clear.

Without the vertical scroll bar: 
![image](https://user-images.githubusercontent.com/103126226/233684562-698a9af8-d41e-4dca-8b05-a77aaf3162af.png)

With the vertical scroll bar:
![image](https://user-images.githubusercontent.com/103126226/233684663-e78171a8-7263-4fac-82d6-41cdb594a5c5.png)

I believe it is excellent, as it doesn't cut part of the buttons or any necessary information. Good job!

2023-04-21 16:18 UTC, NataliaCavicchioli commented
Hey @ypan710, we no longer have the scroll bar! This is good.

The dropdown is also not overflowing anymore, but when the page has a vertical scroll bar, it cuts part of the dropdown. I've included screenshots below to make it clear.

Without the vertical scroll bar: 
![image](https://user-images.githubusercontent.com/103126226/233685703-9dd0299f-bc8f-4f7a-855e-54993e13e5dc.png)

With the vertical scroll bar:
![image](https://user-images.githubusercontent.com/103126226/233685659-1dc420e9-9256-4f0a-afda-c96c45fd2da1.png)

I believe it is excellent, as it doesn't cut part of the buttons or any necessary information. Good job!

2023-04-21 16:19 UTC, NataliaCavicchioli submitted a review, later dismissed

2023-04-24 22:41 UTC, Vishvesh-Sheoran commented on src/App.css
1. It might be worth considering removing the use of !important, as it can make it difficult to override styles in the future.

2. Instead of using absolute positioning and setting the width and height of .newProfilePic to 0, it might be better to use display:none to hide the element.

3. The use of inline styles (e.g. padding-top: 7px) can make it difficult to maintain and update the code. It might be better to move these styles to a separate CSS class and apply it to the relevant elements.

4. Using more descriptive class names (e.g. .bg-medium-blue instead of .bg-super) can make the code more readable and easier to maintain.

Code:

html {
  overflow-x: hidden;
}

body, #root {
  height: 100%;
}

.text-center {
  text-align: center;
}

.new-profile-pic {
  visibility: hidden;
  width: 0;
  height: 0;
  padding-top: 7px;
  padding-right: 2px;
  position: absolute;
  right: 0;
  top: 0;
}

.infringement {
  color: blue;
}

.profile-pic {
  height: 180px;
  width: 180px;
}

.accordion-toggle:after {
  font-family: 'FontAwesome';
  content: '\f054';
  float: right;
}

.accordion-toggle.collapsed:after {
  content: '\f078';
}

.btn-primary {
  background-color: black;
  border: black;
}

.hgn-leaderboard {
  background-color: black;
}

.bg-blue {
  background-color: #0000cd;
}

.bg-purple {
  background-color: #990099;
}

.bg-pink {
  background-color: #cc3366;
}

.bg-orange {
  background-color: #ffa500;
}

.bg-green {
  background-color: #c9d6c6;
}

.bg-red {
  background-color: #ff3300;
}

.dropdown-menu.show {
  transform: translate3d(-26px, 40px, 0px);
}

2023-04-27 18:50 UTC, vitorsaa2k requested changes
The position of another dropdowns has been affected, please, fix that.

![image](https://user-images.githubusercontent.com/17365161/234962603-9cac5733-0e13-49a3-bb51-57ca5b2c5933.png)

2023-04-28 00:43 UTC, ypan710 commented
> The position of another dropdowns has been affected, please, fix that.
> 
> ![image](https://user-images.githubusercontent.com/17365161/234962603-9cac5733-0e13-49a3-bb51-57ca5b2c5933.png)

I will take a look. Thanks.

2023-05-01 01:25 UTC, alexander-huerta reviewed
Hi @ypan710 

The horizontal scroll bar has been successfully removed. Nice work!


However there are 3 concerns I would like to address, (2 were previously described by others). 

1. The `Task and Timelogs` card and the `Badges` cards are no longer aligned. Please see the screenshots below for clarity. 
2. The user drop down menu is not fully displayed-- being cut off on the right side.
3. I also was able to recreate the issue Vitor brought up- when logged in as an admin, the position of the `Other Links ` drop down is off.


![cards_aligned](https://user-images.githubusercontent.com/59572783/235386995-22c5f4c0-b2d0-4660-8398-3d9e86c1ab5a.png)
![cards_unaligned](https://user-images.githubusercontent.com/59572783/235386996-e2471eda-1d79-4597-ba90-244d91ac4566.png)

2023-05-02 16:42 UTC, ypan710 commented
> The position of another dropdowns has been affected, please, fix that.
> 
> ![image](https://user-images.githubusercontent.com/17365161/234962603-9cac5733-0e13-49a3-bb51-57ca5b2c5933.png)

@vitorsaa2k I've fixed what you mentioned. Please see screenshots.

2023-05-02 16:45 UTC, ypan710 commented
> Hi @ypan710
> 
> The horizontal scroll bar has been successfully removed. Nice work!
> 
> However there are 3 concerns I would like to address, (2 were previously described by others).
> 
> 1. The `Task and Timelogs` card and the `Badges` cards are no longer aligned. Please see the screenshots below for clarity.
> 2. The user drop down menu is not fully displayed-- being cut off on the right side.
> 3. I also was able to recreate the issue Vitor brought up- when logged in as an admin, the position of the `Other Links ` drop down is off.
> 
> ![cards_aligned](https://user-images.githubusercontent.com/59572783/235386995-22c5f4c0-b2d0-4660-8398-3d9e86c1ab5a.png) ![cards_unaligned](https://user-images.githubusercontent.com/59572783/235386996-e2471eda-1d79-4597-ba90-244d91ac4566.png)

@alexander-huerta I've not made any changes to the `Task and Timelogs` card and the `Badges` in the files. I've tested both frontend and backend branches in development and they have not been aligned.

2023-05-02 19:44 UTC, vitorsaa2k approved these changes
So much better, thank you!

![image](https://user-images.githubusercontent.com/17365161/235769226-71391f43-d1b4-46f4-8db4-a80fb4304b5e.png)

2023-05-02 21:55 UTC, one-community commented
Thank you everyone, merging.

2023-05-02 21:55 UTC, merged