(PRIORITY MEDIUM) Jae: Add GDoc Link to Weekly Summaries Reports
OneCommunityGlobal/HighestGoodNetworkApp pull request #786
Opened 2023-04-21 05:49 UTC by angelinatr15

1. [this icon](https://www.uplabs.com/posts/google-go-android-icon) and a link to that Google Doc for each person who has one
2. Put the icon/link to the right of their name Navigate as an Admin to Reports → Weekly Summaries Reports: I’d like the app to check for a Google Doc link on their profile (one is added for almost every person when they are added to the system) and insert 
3. On that icon, please also be sure that I can command (mac)/control (PC) + Click to open that in a new tab. It should happen automatically if it is a linked icon, but please double-check to be sure.
4. If no Google Doc is present for the user, it should instead cause a popup that says: “Uh oh, no Google Doc is present for this user! Please contact an Admin to find out why.”

### **Main Changes Explained:**

1. add google doc icon image
2. add  google doc styling in WeeklySummariesReport.css
3. add functions to FormattedReport.jsx [mainly google doc link and toast message was added]

### **How to Test:**

1. check out this branch and the backend branch that is related to this PR as well. (see link below)
2. Navigate as an Admin to Reports → Weekly Summaries Reports
3. Select the google doc icon located next to each user profile name. 
4. If they have a google doc link then a new window will open and the google doc link will appear. 
5. If they do not have a google doc link then a pop-up will appear. 

### **Additional Notes:**
This branch needs the backend branch:
https://github.com/OneCommunityGlobal/HGNRest/pull/329

2023-04-21 15:19 UTC, abdel-lall reviewed
Works as intended. just a little typo on the toast message.
 'Uh oh, no Google Doc is **NOT** present for this user! Please contact an Admin to find out why'
![PR786](https://user-images.githubusercontent.com/49083865/233673793-a9c1e3f4-f1ad-43c1-a157-5feb68a362ce.png)

2023-04-21 20:57 UTC, one-community commented
Text looks good to me. Adding "not" would be a double since "no" is already earlier in the sentence. Please add a period at the end though.

2023-04-22 00:01 UTC, johny4437 commented
Hi @angelinatr15 I am trying to run your frontend PR locally, but looks like  is broking the app, I tried first time and did not worked, then I deleted the branch locally and tried again and still broken for me.  Tested the development branch and it is working fine.
![Captura de Tela (341)](https://user-images.githubusercontent.com/39320057/233750553-8669aa5d-d1a3-4ed1-97ff-e50b9a69a9a3.png)

2023-04-22 01:40 UTC, KaixiangGU commented
Work as expected, great job!

2023-04-24 18:29 UTC, AuroraLovesWhales reviewed
Hi Angelina. I have tested your PR and it is working as expected. The popup message appears when a user does not have a link. 
![image](https://user-images.githubusercontent.com/44281916/234082652-d1c53169-4722-43cb-b192-3c99227c4b54.png)

However, I created a new user and provided the Google doc link during account registration, but the popup message still shows up and says there's no link provided. I'm not sure if I'm doing it wrong?

2023-04-26 02:45 UTC, AnishPandita commented
Hi, I tested your PR and its working as intended. The error message is shown correctly when we click google icon and no link is present.
<img width="1440" alt="Screenshot 2023-04-25 at 7 43 32 PM" src="https://user-images.githubusercontent.com/111321945/234453313-29cf089a-83f2-4668-98d3-7a51442e0d00.png">

2023-04-26 05:10 UTC, Vishvesh-Sheoran commented on src/components/WeeklySummariesReport/FormattedReport.jsx
Here are a few suggestions to improve the code:

1. Instead of using the spread operator and the Set object to remove duplicates from the 'emails' array, you can use the 'filter' and 'indexOf' methods like this:

_const emails = summaries.filter(summary => summary.email).map(summary => summary.email);
const uniqueEmails = emails.filter((email, index, self) => self.indexOf(email) === index);_

This way, we can avoid creating unnecessary intermediate arrays.

2. The 'alphabetize' function can be simplified using destructuring and a template literal like this:

_const alphabetize = summaries => {
  return summaries.sort((a, b) => {
    const { firstName: aFirst, lastName: aLast } = a;
    const { firstName: bFirst, lastName: bLast } = b;
    return `${aFirst} ${aLast}`.localeCompare(`${bFirst} ${bLast}`);
  });
};_

3. The 'getGoogleDocLink' function can be made more concise using the find method and optional chaining like this:

_const alphabetize = summaries => {
  return summaries.sort((a, b) => {
    const { firstName: aFirst, lastName: aLast } = a;
    const { firstName: bFirst, lastName: bLast } = b;
    return `${aFirst} ${aLast}`.localeCompare(`${bFirst} ${bLast}`);
  });
};_

4. In the 'handleGoogleDocClick' function, we can use the optional chaining operator to simplify the check for the presence of the 'googleDocLink' like this:

_const handleGoogleDocClick = googleDocLink => {
  const toastGoogleLinkDoesNotExist = 'toast-on-click';
  if (googleDocLink?.Link) {
    window.open(googleDocLink.Link);
  } else {
    toast.error(
      'Uh oh, no Google Doc is present for this user! Please contact an Admin to find out why',
      {
        toastId: toastGoogleLinkDoesNotExist,
        pauseOnFocusLoss: false,
        autoClose: 3000,
      },
    );
  }
};_

5. In the JSX code, you can use the 'className' attribute instead of the 'style' attribute to apply CSS styles. For example:

_<p className={summary.weeklySummariesCount === 8 ? 'blue' : ''}>
  <b>Total Valid Weekly Summaries:</b>{' '}
  {summary.weeklySummariesCount || 'No valid submissions yet!'}
</p>_

6. Instead of using the 'React.Fragment' syntax ('<>...</>'), we can use the shorthand syntax ('<></>') to create an empty JSX fragment.



7. Finally, we can consider breaking down the component into smaller, more focused components to improve reusability and maintainability. For example, you can extract the logic for displaying the user's name and profile link into a separate component, like this:

_const UserName = ({ firstName, lastName, id }) => {
  return (
    <Link to={`/userProfile/${id}`} title="View Profile">
      {firstName} {lastName}
    </Link>
  );
};_

2023-04-27 23:22 UTC, angelinatr15 commented
> Hi Angelina. I have tested your PR and it is working as expected. The popup message appears when a user does not have a link. ![image](https://user-images.githubusercontent.com/44281916/234082652-d1c53169-4722-43cb-b192-3c99227c4b54.png)
> 
> However, I created a new user and provided the Google doc link during account registration, but the popup message still shows up and says there's no link provided. I'm not sure if I'm doing it wrong?

Hi @AuroraLovesWhales, can you test this PR again? I did not encounter the popup message after creating a new user with a google doc link. Please be sure to check out the back end as well as the front end to test this PR. Thanks!

2023-04-28 18:24 UTC, vitorsaa2k requested changes
There should have a google doc field on the User Profile page as well. But I'm not sure if it should be implemented with this PR. I'm gonna wait for @one-community's response, and if not, I'll approve this PR as the functionality is working great.

2023-04-29 23:43 UTC, GKD890 approved these changes
Hi Angelina,

It works as intended on my local environment and code is easy to read. Screenshot should be the same for this one, so not provide here.

Also I tried to reproduce the problem @AuroraLovesWhales met, at least it works on my computer. The Google Doc link that I insert when creating account can be detect and open through the icon.

2023-04-30 00:38 UTC, nicollext approved these changes

2023-04-30 00:40 UTC, one-community commented
> There should have a google doc field on the User Profile page as well. But I'm not sure if it should be implemented with this PR. I'm gonna wait for @one-community's response, and if not, I'll approve this PR as the functionality is working great.

There's one there, it's above the blue squares

2023-04-30 00:41 UTC, one-community commented
Thank you everyone, Vitor from the leadership team approved this, so merging it.

2023-04-30 00:42 UTC, merged

2023-04-30 00:48 UTC, nicollext approved these changes
Tested and works as intended! Also created a new user and the link opens correctly. Great job! 

https://user-images.githubusercontent.com/101591708/235330188-59a3deed-123d-45e4-8297-680884ccd1ed.MP4