Fix button to save visibibility edit for manager role
OneCommunityGlobal/HighestGoodNetworkApp pull request #792
Opened 2023-04-25 23:57 UTC by ypan710

# Description
![Screen Shot 2023-04-20 at 4 35 02 PM](https://user-images.githubusercontent.com/46613683/233508084-7930fdb7-1135-471a-a499-4af1d445aff0.png)

## Mainly changes explained:
Under manager role, created "Save Changes" button to save the changes of visible/invisible toggle button. I merely created a new branch in this PR to solve the same problem and addressed issues in comments in related PR: [PR#785](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/785).

## How to test:
1. check into current branch
2. do `npm run start:local` to run this PR locally
3. login as manager role, under "Welcome, XXX" -> View Profile -> Teams, inspect presence of "Save Changes" button and toggle "visible/invisible" and click on "Save Changes" button to verify ability to save the changes.

## Screenshots
![Screen Shot 2023-04-25 at 11 55 39 AM](https://user-images.githubusercontent.com/46613683/234430726-baf7442d-5150-4203-967a-5508b03b9221.png)
![Screen Shot 2023-04-25 at 11 56 21 AM](https://user-images.githubusercontent.com/46613683/234430729-a4e0faa3-98b8-4ce9-8846-7d44809b4a9b.png)

![Screen Shot 2023-04-25 at 11 56 30 AM](https://user-images.githubusercontent.com/46613683/234430733-fe61533d-71cb-4301-bd87-acaeea63ade7.png)
![Screen Shot 2023-04-25 at 11 56 51 AM](https://user-images.githubusercontent.com/46613683/234430734-acb3e2f4-8461-480a-96f5-bc346a31643d.png)

2023-04-26 01:45 UTC, AuroraLovesWhales approved these changes
Hi Yongjian! I have tested your PR and it is working as expected. I have tried to log out and log back in as manager as well, and the change is being saved. Great work!

Before:
Set visibility to "invisible" and no option to save the change.
https://user-images.githubusercontent.com/44281916/234442845-97d7e5e0-0644-4a8d-b904-352b1e8a85da.mov

After:
A "Save Changes" button is available. Set visibility to "invisible", click on "Save Changes", and now the change can be saved.
https://user-images.githubusercontent.com/44281916/234444508-5b968a90-9d56-4697-a4d4-c9e53a37234a.mov

2023-04-26 05:40 UTC, Vishvesh-Sheoran commented on src/components/UserProfile/UserProfile.jsx
A possible improvement to make the code more concise and readable is to extract the conditions and expressions that are repeated into separate variables or functions. For example:


"const canSaveChanges =
  canEdit &&
  (activeTab === '1' || activeTab === '3' ||
    hasPermission(requestorRole, 'editUserProfile', roles, userPermissions));
const isFormValid = formValid.firstName && formValid.lastName && formValid.email;
const hasChanges = !isProfileEqual || !isTasksEqual || !isTeamsEqual || !isProjectsEqual;

return (
  <>
    {canSaveChanges && (
      <>
        <SaveButton
          className="mr-1 btn-bottom"
          handleSubmit={handleSubmit}
          disabled={!isFormValid || !hasChanges}
          userProfile={userProfile}
        />
        {activeTab !== '3' && (
          <span
            onClick={() => {
              setUserProfile(originalUserProfile);
              setTasks(originalTasks);
              setTeams(originalTeams);
            }}
            className="btn btn-outline-danger mr-1 btn-bottom"
          >
            Cancel
          </span>
        )}
      </>
    )}
    <Button outline onClick={loadUserProfile}>Load User Profile</Button>
  </>
); "


This code uses descriptive variable names to make the conditions and expressions more self-explanatory, and reduces duplication by extracting them into separate variables or functions. It also simplifies the '_disabled_' prop of the '_SaveButton_' component by combining the conditions into a single expression. Finally, it replaces the string '_"Load User Profile"_' with the actual function '_loadUserProfile_' in the '_onClick_' prop of the Button component.

2023-04-26 23:02 UTC, abdel-lall approved these changes
Works as intended. Nice job!

![PR792](https://user-images.githubusercontent.com/49083865/234720843-70c05b5b-4a1b-479f-b770-9ae87f4442bd.png)

2023-04-27 02:34 UTC, one-community commented
Reminder to start PRs with your name

2023-04-28 18:01 UTC, vitorsaa2k requested changes
While testing your PR, I've noticed that I'm not able to edit the role of users with the Volunteer/Core Team/Manager/Mentor roles. You didn't made any change about the functionality on the code, but somehow your PR is affecting it.

https://user-images.githubusercontent.com/17365161/235220440-3b19d6b2-6227-4f11-b8ef-eedd3c42b186.mp4

2023-04-28 21:56 UTC, ypan710 commented
> While testing your PR, I've noticed that I'm not able to edit the role of users with the Volunteer/Core Team/Manager/Mentor roles. You didn't made any change about the functionality on the code, but somehow your PR is affecting it.
> 
>  Desktop.2023.04.28.-.14.57.33.01.mp4

How should I diagnose what is happening?

2023-04-29 05:37 UTC, one-community commented
Watched your video Vitor and those other classes shouldn't be able to edit the the roles - only Admin and Owner classes should be able to edit them. That ability was mistakenly granted to all roles and has been fixed with another PR. So I think what's happening there is you are changing from and Admin and then you (correctly) lose that editing ability as soon as you save. 

Correct me if my interpretation of your video is incorrect. If it's correct though, go ahead and approve this and I'll merge it.

2023-04-29 22:13 UTC, one-community commented
Why is there this PR about this too: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/785

2023-04-30 00:50 UTC, GKD890 commented
Hi Yongjian, 
the visibility and `save changes` button works as expected, thanks for the work.

<img width="1077" alt="PR_Frontend#792" src="https://user-images.githubusercontent.com/57503876/235330171-b599805d-151e-4b75-9b89-cf4746ac8881.png">

2023-05-03 16:10 UTC, vitorsaa2k commented
> 

@one-community The oppositte is happening, when I'm using an Owner/Admin account I can't edit the role of accounts which have the Volunteer/Core Team/Manager/Mentor role.

2023-05-05 01:43 UTC, wang9hu approved these changes
The 'Save Changes' does work as intended. Great job, @ypan710 !
![Screenshot 2023-05-04 184050](https://user-images.githubusercontent.com/77769556/236362307-82852a24-fabe-4788-9f18-2ccc3d60f794.png)
![Screenshot 2023-05-04 184158](https://user-images.githubusercontent.com/77769556/236362308-adb785ac-4dd7-4b0e-a1b2-661e8f312a5c.png)

2023-05-05 03:36 UTC, EdwinLauM approved these changes
Hi Yongjian,

Works as intended. The save changes button appears in the Teams tab. Toggling it between visible/invisible and saving the changes works as well! Good job!

https://user-images.githubusercontent.com/42288987/236372718-61cefc63-0ebb-4474-801a-e3a30f7069b6.mov

2023-05-19 02:55 UTC, AnishPandita commented
Hi @ypan710 I tested your PR and can attest that the save changes option is working as intended.
<img width="1440" alt="Screenshot 2023-05-18 at 7 51 43 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/842b0bc6-8b88-404d-b8cf-e8b170e9c3d7">

2023-05-19 20:55 UTC, one-community commented
Thank you all, merging.

2023-05-19 20:55 UTC, merged