Lucas fix notification icon
OneCommunityGlobal/HighestGoodNetworkApp pull request #802
Opened 2023-05-05 14:26 UTC by Lucas-E

This PR is due: (PRIORITY MEDIUM) Jae: Fix red bell icon, the red bell should go away after you see the changes that have been made. (WIP - Lucas)
Dashboard → Tasks Tab → click Red Bell by task
The red bell should go away after you see the changes that have been made. It should only go away for the person who has seen those changes, NOT everyone. 
Please check this function for other bugs too. 
Is the bell showing up:

- With any kind of change?
- If changes are made from the Projects page?
- From edit option accessed from the Tasks Tab?
- Any other fringe cases you can think of

<hr>

### MAIN CHANGES

- if one or more users have a task and it changes, the red bell will appear for every user under that task
- only users in the task can mark the notification as read
- if a user mark the notification as read, the notification will go away only for the user that read, but not for the other users
- a notification will only go away once the user mark it as read
- when viewing another user's dashboard, you should not be able to mark a notification as read

<hr>

### How to test

- checkout this branch
- npm install
- npm run start:local
- create a task and add resources
- check the main changes

2023-05-05 18:14 UTC, GKD890 commented
Hi Lucas,
I've been working on it, but finding a issue that when a user is in dashboard page, the page will keeping sending request to `/userProfile?members=` domain. After compared, I found it doesn't appear in current `development` branch, so I believe it's in this PR. 
Could it be the `useEffect()` you added to file `src/components/TeamMemberTasks/TeamMemberTasks.jsx` from line 53 to line 57?

Here's the link: [record](https://www.dropbox.com/s/iqwd9ewqk8zvf4d/Frontend_PR%23802_BugReport.mov?dl=0)

2023-05-05 19:06 UTC, alexander-huerta approved these changes
After testing the changes I can confirm that: 

1. Clicking the Red Bell Icon and Marking as Read, will make the icon disappear for that user and NOT for any other user(s). 
2. There is not an option to Mark another user’s Icon as Read. 


**Before Fix** 
[802_recreate_bug.webm](https://user-images.githubusercontent.com/59572783/236547372-1865a8b3-fc37-43c6-a58e-ffe76331e554.webm)
 
**After Fix**
[802_fix.webm](https://user-images.githubusercontent.com/59572783/236547443-26c51e26-611b-4ba9-b545-a3d9e537730f.webm)

You can read more on my testing methodology in this [doc](https://docs.google.com/document/d/1p7c1OpZVdYqZa-xlAxPy9EHrvKU8r8f18Fk74xEDL0g/edit)

2023-05-05 20:15 UTC, Lucas-E commented
> Hi Lucas, I've been working on it, but finding a issue that when a user is in dashboard page, the page will keep sending request to `/userProfile?members=` domain. After compared, I found it doesn't appear in current `development` branch, so I believe it's in this PR. Could it be the `useEffect()` you added to file `src/components/TeamMemberTasks/TeamMemberTasks.jsx` from line 53 to line 57?
> 
> Here's the link: [record](https://www.dropbox.com/s/iqwd9ewqk8zvf4d/Frontend_PR%23802_BugReport.mov?dl=0)

Reviewed and indeed it was the useEffect. I've already removed it. Please test it again, thanks!

2023-05-06 00:09 UTC, abdel-lall approved these changes
works as intended. good job!

![PR802(1)](https://user-images.githubusercontent.com/49083865/236587316-568821e0-2ca6-442b-b161-ee6b883e987b.png)

![PR802(2)](https://user-images.githubusercontent.com/49083865/236587323-3dd4cce2-3bf4-4e11-937d-8b50bdcce1bc.png)

![PR802(3)](https://user-images.githubusercontent.com/49083865/236587328-54b5a6eb-c7a9-40b3-88ef-837cb20eb0b2.png)

2023-05-06 06:33 UTC, Vishvesh-Sheoran commented on src/actions/task.js
Leaving a comment here that is produced by chatGPT because it explains what the added code does (so anyone who reads this comment in the future understands it here):

The newly added code is using the _axios.delete()_ method to make a _DELETE HTTP_ request to a specified endpoint _DELETE_TASK_NOTIFICATION_BY_USER_ID_ with two parameters _taskId_ and _userId_. This endpoint is probably used to delete a specific task notification that is associated with a particular user. The response from the server is logged to the console using _console.log(res)_.

The commented-out code appears to be the old code that was replaced. It is still there for reference, and it probably deletes a task notification using an endpoint that takes in a _taskNotificationId_ parameter.

2023-05-06 18:30 UTC, GKD890 commented
Hi, tested the code after changed. It works as expected, the red bell will disappear once been `mark as read` and seems the result can be shown properly to other members in the same tea
<img width="618" alt="Frontend_PR#802-feedback" src="https://user-images.githubusercontent.com/57503876/236641037-091cba5f-0ef1-4e64-b3ae-c494a144d9fa.png">
m.

2023-05-06 23:10 UTC, wang9hu commented
Hi, Lucas
I tested the code and it does work as expected. 
One thing that I notice is that the page will do a full page refresh and I wonder if this process could be optimized. 
Overall, great job!!

https://user-images.githubusercontent.com/77769556/236649813-4787e8e7-e861-4358-b9d4-eeb0801a0b0c.mp4

2023-05-06 23:51 UTC, Sneha1b approved these changes
Nice Job! Works as intended

https://user-images.githubusercontent.com/29037428/236650865-706cdc6e-e55a-4410-9a1d-03721b18764c.mov

2023-05-07 16:58 UTC, one-community commented
> Hi, Lucas I tested the code and it does work as expected. One thing that I notice is that the page will do a full page refresh and I wonder if this process could be optimized. Overall, great job!!
> 
>  frontend.802.and.backend.343.mp4

I've requested optimization like that for deleting tasks here and would like to see that for this function too. Would you like to take that on Lucas as your next bug, or should I leave it to whomever optimizes deleting, so they can do it all at once... or would you like to add that optimization for this and deleting tasks?

2023-05-09 18:44 UTC, one-community commented
Thank you all, moving to final review.

2023-05-09 21:11 UTC, one-community commented
Super, thank you. Will do on Slack.

2023-05-11 01:15 UTC, AuroraLovesWhales approved these changes
Hi Lucas! I have tested your PR and it works as expected. Great job!

I changed the task urgency from Primary to Secondary, and it worked as expected. The red bell reappeared under the task. And only the user in the task can mark the notification as read. And the notification will go away only for the user that read, but not for the other users:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/d0a6ee2f-bc96-4391-a73b-8a4afc5cf4cb

2023-05-11 03:19 UTC, EdwinLauM submitted a review, later dismissed
Works as intended! When marked as read the bell notification disappears!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/0e6715f9-fd6c-41fb-a923-abd613498028

2023-05-12 22:18 UTC, EvianTan approved these changes

2023-05-14 00:07 UTC, wang9hu requested changes

2023-05-14 00:07 UTC, wang9hu commented on src/components/TeamMemberTasks/TeamMemberTask.jsx
This is a quick fix: `timeLogOpen`, `<EffortBar>` and <TimeEntry>` are not defined in this file.

2023-05-14 03:20 UTC, GKD890 commented
Hi @Lucas-E , seems I met a problem that the red bell won't go away by itself even after it's refresh once clicked `mark as read` . It goes away after I manually refresh the page (thus total 2 refresh). But it won't affect other member's read status based on what I tested.

A video [link](https://www.dropbox.com/s/5wea309qxgge277/Frontend_PR%23802_problem.mov?dl=0), I've tested this problem and confirm it is reproducible on my computer.

2023-05-14 05:02 UTC, drewlong314 commented
When a user clicks the red bell and then selects mark as read, it removes the red bell for only that user. Any other user that has that task will still have the red bell but not be able to select mark as read.
<img width="711" alt="Screen Shot 2023-05-13 at 11 59 08 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78223925/119fb6e7-bb7a-4bd9-ba76-c11d635d9c3c">
<img width="724" alt="Screen Shot 2023-05-13 at 11 59 25 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78223925/76b6d06b-95e8-4f9f-9142-b8468f0c209e">

2023-05-14 06:00 UTC, EdwinLauM reviewed
Hello Lucas! I am running into a similar problem to _place name_ as well . In my case, whenever I click the bell it seems like the backend server is crashing. In the video, it also shows that it didn't refresh and the bell still remains there

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/f67d92fa-8757-465b-8784-b8a2177169a4

2023-05-14 06:01 UTC, yoyoweiii reviewed
Work as intended. Good work @Lucas-E 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60588210/c6bd5dbf-1850-4172-b31f-0f26d8463d67

2023-05-15 06:02 UTC, Lucas-E commented on src/components/TeamMemberTasks/TeamMemberTask.jsx
Solved

2023-05-18 17:22 UTC, eduhorta commented
Hi @Lucas-E!
I could not replicate the feature.
Can you please check if I'm missing something?

Testing using:
Backend PR# 343 - Commit - 88ec31323102aa1af29d690dad6c513768663c29
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/0b269da3-f30c-4b35-b282-3a69b3eb3096)

Frontend PR#802 - Commit - 201c45c83f32d6472f400f61fa3a029092e1f4a3
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/ab0f0cee-20e6-49a6-9c7d-666bc91ba846)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/3a6864d0-4922-44bd-a523-b50bda208f4d

2023-05-23 03:43 UTC, 20chen-7 approved these changes
Awesome! The rerender issues has been resolved and everything look great!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/25cce42b-6fa8-4c02-a46e-34989e2fd839

2023-05-25 01:59 UTC, NidaZaki reviewed
Tried to the test the PR, but not able to test the fix for it. The red bell icon still appears even if I refresh the page after clicking the "Mark As Read" button. Not sure if I'm testing this functionality correctly or if this is intentional?
Please refer the video below
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/32549172/8124e52f-4f88-4a42-9f90-63a7c00c4d8e

2023-05-25 20:33 UTC, OAkinbode reviewed
Hi. I am not able to replicate a successful test. I am noticing a missing "confirm" button at the bottom of the changes pop-up page: 
<img width="1440" alt="Screenshot 2023-05-25 at 2 29 27 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/485e4265-3219-4037-b17a-f7726d9a65ee">

Please check out the video below to see what I did: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/421dc2fc-bdd2-4649-9f6d-ff4bca13588c

Also, see my terminal. I am checkout both on the back and frontend: 
<img width="458" alt="Backend prompt" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/87710c00-c7f4-47b2-9fe2-f0906ac16869">
<img width="540" alt="Frontend prompt" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/9e5ba97d-fdcf-42b3-bb56-1c7b918f9a69">

Not sure if I am doing something wrong.

2023-05-25 23:45 UTC, one-community commented
Is that confirm button still missing? We had another button disappear due to PR 762. I reverted that right after your review here and it came back, so someone please confirm for me if it is there or not.

2023-05-26 17:56 UTC, OAkinbode commented
> Is that confirm button still missing? We had another button disappear due to PR 762. I reverted that right after your review here and it came back, so someone please confirm for me if it is there or not.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/f962e5df-da22-429a-ab89-9fdce5f51588

Hi, The button is still missing.

2023-05-26 19:04 UTC, OAkinbode commented
> Is that confirm button still missing? We had another button disappear due to PR 762. I reverted that right after your review here and it came back, so someone please confirm for me if it is there or not.

I think I found the problem. The button only shows up if the admin is visiting his own account to tick a task as completed. I created a task for myself and tested the feature with that. The question then becomes, should an admin be able to tick a task complete for all or for just themselves?


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/d133da5e-26d1-4316-ac4a-4fcd2d4491d8

2023-05-27 04:26 UTC, one-community commented
> I think I found the problem. The button only shows up if the admin is visiting his own account to tick a task as completed. I created a task for myself and tested the feature with that. The question then becomes, should an admin be able to tick a task complete for all or for just themselves?

That looks correct then. Nobody should be able to "Mark as Read" for anyone else, only for themselves.

2023-06-01 16:59 UTC, papiasharmin approved these changes
Hi @Lucas-E, the mark as read button is still missing. And on create task modal, for resources input, only few members name are available. Can not find my name as admin or volunteer to assign the task.
![noconfirmbtn](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86232710/0dabcaf3-6079-4ee7-9e00-14db74ba1b49)
![task](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86232710/eac9f018-ca61-4476-8fcd-09c6c9066c4d)

2023-06-01 17:21 UTC, papiasharmin requested changes
Hi @Lucas-E, the mark as read button is still missing. And on create task modal, for resources input, only few members name are available. Can not find my name as admin or volunteer to assign the task.
![noconfirmbtn](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86232710/0dabcaf3-6079-4ee7-9e00-14db74ba1b49)
![task](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86232710/eac9f018-ca61-4476-8fcd-09c6c9066c4d)

2023-06-09 00:29 UTC, nathanah approved these changes
Just some small formatting suggestions, but everything seems to work as intended.

2023-06-09 00:29 UTC, nathanah commented on src/utils/URL.js
> +
```suggestion
  DELETE_TASK_NOTIFICATION_BY_USER_ID: (taskId, userId) =>
  `${APIEndpoint}/tasknotification/${userId}/${taskId}`,
```

2023-06-09 00:29 UTC, nathanah commented on src/components/TeamMemberTasks/TeamMemberTask.jsx
> +                                    })
```suggestion
                                    const taskNotificationId = task.taskNotifications.filter(
                                      taskNotification => taskNotification.userId === user.personId
                                    )
```
Slightly cleaner.

2023-06-12 23:41 UTC, Lucas-E commented
> Hi @Lucas-E, the mark as read button is still missing. And on create task modal, for resources input, only few members name are available. Can not find my name as admin or volunteer to assign the task. ![noconfirmbtn](https://user-images.githubusercontent.com/86232710/242672138-0dabcaf3-6079-4ee7-9e00-14db74ba1b49.jpg) ![task](https://user-images.githubusercontent.com/86232710/242672185-eac9f018-ca61-4476-8fcd-09c6c9066c4d.jpg)

The button for the notification to be dismissed will only appear for the user whose have the notification, owners and administrators cannot dismiss other user's notifications.

2023-06-13 05:48 UTC, wang9hu approved these changes

2023-06-13 06:27 UTC, wang9hu commented
Things are working as intended. Great Job! Only some console.log need to be removed.

2023-06-14 00:03 UTC, Lucas-E commented
Thank you everyone! Moving to final review!

2023-06-17 02:31 UTC, juneluo commented
Test result:
The red bell appears for anyone within the task, and it will goes away when a user marks it as read (only for the user themselves but not others even viewing others' dashboard). Changes made to the task will bring back the red bell notification.
It works as intended, good job!
However, as the review mentioned above, a few lines of `console.log` should be removed.

2023-06-17 03:07 UTC, juneluo approved these changes

2023-06-17 04:21 UTC, AuroraLovesWhales approved these changes
Hi @Lucas-E. I have tested this PR again and everything is working as intended. Great job!

- if one or more users have a task and it changes, the red bell will appear for every user under that task
- only users in the task can mark the notification as read
- if a user mark the notification as read, the notification will go away only for the user that read, but not for the other users
- a notification will only go away once the user mark it as read

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/877f263c-54a7-438a-82a0-dc6b22c5af2b

- when viewing another user's dashboard, you should not be able to mark a notification as read

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/4271ec95-a561-484c-9af2-ff9a150ca1ab

2023-06-17 23:21 UTC, merged