Xiao Create Shadow Consistency for the Dashboard
OneCommunityGlobal/HighestGoodNetworkApp pull request #862
Opened 2023-05-30 01:03 UTC by AuroraLovesWhales

# Description
(PRIORITY LOW) Jae: Create Shadow Consistency for the Dashboard
a. Please add the shadow shown below to the rest of the buttons on that page: 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/181981a4-c6f6-4858-a9bb-65d53975da93)
b. Definitely these two areas, but any other areas on this page you think they would look good too: 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/600bad49-31d8-41e4-af77-0c6fca8a9031)

## Main changes explained:
Added style={{ boxShadow: '2px 2px 4px 1px lightgray', }} to "Add Intangible Time Entry" button, "Badge Report" button, and "CountDownTimer" box. Also added some padding between the three icons next to "Tasks and Timelogs" to make it look better.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log in as any user and verify that the changes have been made

## Screenshots or videos of changes:
After:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/3b0251f9-e840-4772-ac01-f1fac6509425)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/7a89d33a-84ca-419a-a8f9-aa331eb3dd36)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/c95e24b4-63e8-4c0c-853c-44ed422cd306)

## Note:
This is an easy PR to test. The only changes are made to the UI. If you have any other suggestions for improvement, please let me know.

2023-05-30 03:01 UTC, one-community commented
Looks good!

2023-05-30 03:32 UTC, Cirakuze commented on package-lock.json
What is this diff from? Is it relevant to the feature changes of this PR?

2023-05-30 03:45 UTC, Cirakuze requested changes
This PR does not include any changes to the packages, but includes a package-lock.json diff. Unless the package-lock.json diff is intentional and this PR is missing the accompanying package version diffs, please remove it from this PR.

The three boxShadow styles in this PR seem to be identical. If the intention is for them to always be the same, please explore ways to allow this style to be reusable and scalable, allowing a dev in the future to touch just one part of the code to apply the changes to everywhere this specific style is used.

2023-05-30 03:59 UTC, one-community commented
> The three boxShadow styles in this PR seem to be identical. If the intention is for them to always be the same, please explore ways to allow this style to be reusable and scalable, allowing a dev in the future to touch just one part of the code to apply the changes to everywhere this specific style is used.

Great suggestion! Let me know how much time to add for doing this Xiao, setting it up so everything throughout the app with  these shadows can be adjusted with one code change. Then look at all the other pages and see where this can be applied there too... include all the Admin-level pages. So this is a pretty big task because it will touch all pages.

2023-05-30 04:41 UTC, AuroraLovesWhales commented
> > The three boxShadow styles in this PR seem to be identical. If the intention is for them to always be the same, please explore ways to allow this style to be reusable and scalable, allowing a dev in the future to touch just one part of the code to apply the changes to everywhere this specific style is used.
> 
> Great suggestion! Let me know how much time to add for doing this Xiao, setting it up so everything throughout the app with these shadows can be adjusted with one code change. Then look at all the other pages and see where this can be applied there too... include all the Admin-level pages. So this is a pretty big task because it will touch all pages.

Thank you for the advice! I will apply these suggestions. I will probably need 3 more hours to do it.

2023-05-30 17:03 UTC, 20chen-7 reviewed
Looks great! The shadow is like intended. I agree with the [Cirakuze](https://github.com/Cirakuze), there are three duplicating style.
![Screenshot 2023-05-30 at 11 02 23 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/d409cf00-0a33-4343-976d-4ca1f0a9b5f1)
![Screenshot 2023-05-30 at 11 02 19 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/6c230141-09c4-4977-8703-6b3c6c98104c)

2023-05-30 18:17 UTC, NidaZaki reviewed
This PR works as intended, and I agree with @Cirakuze
![PR#862](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/32549172/7fb14ae2-cccd-4c87-994a-a6241fd17d23)

2023-05-30 20:43 UTC, AuroraLovesWhales commented
I have manually deleted package-lock.json from github, but now all checks have failed. Does anyone know how to resolve this? Thank you!

I have added a styles.js file to make the boxShadow style reusable. Here are other places throughout the app I have applied the style too. Please let me know if there are any suggestions or areas for improvement. 

Weekly Summaries Reports
![Pasted Graphic 3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/60cf789d-ee35-43f8-87ee-9c58a8eadb23)

Badge Report Popup
![Pasted Graphic 4](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/7300422b-d1ba-4ed2-9680-2f70db3878c8)
![Pasted Graphic 12](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/e1feb305-111c-4a4d-99bb-89fd7d09e064)

Badge Management
![Pasted Graphic 5](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/d8eee337-946d-4b27-979f-d488b1a35584)
![Pasted Graphic 6](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/390aed37-8aca-49d1-9d5a-d882004e4169)

Profile
![Pasted Graphic 13](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/b0c03770-f4b5-474b-97a7-baab35fdca23)

Weekly Summaries
![Pasted Graphic 8](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/c1297425-f181-44db-b729-ff0a113b2f68)

Permission Management
![Pasted Graphic 10](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/6151c640-4b06-4856-8420-e895f605a3f8)

WBSTasks
![Pasted Graphic 11](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/bbb7b893-ebd6-460c-a40a-1053edde5058)

2023-05-31 03:11 UTC, one-community commented
> I will probably need 3 more hours to do it.

Excellent, added 4 hours to where you are now, to include any other requests here.

2023-05-31 05:30 UTC, lchua2314 requested changes
Hi @AuroraLovesWhales I've tried to solve the package-lock.json issue, but I couldn't find a solution. I looked online and people say to not ever delete package-lock.json, but to instead fix conflicts with package.json then run "npm install". Not sure how much that can help you, but I felt like I should inform you of that. 

Also, I requested a small change of some code. It's probably due to the linter.

I tested the changes and everything works as intended, however, I cannot approve your PR until the package-lock.json and my requested change gets fixed.

Weekly Summaries Reports
![1 Weekly Summaries Reports](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46981223/33301a86-a378-4756-ad67-0d1a0a6a70ef)

Badge Report Popup
![2 Badge Report Popup](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46981223/a22bcbc8-98fc-4a44-a302-0a2a450e2e25)
![3 Badge Report Popup](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46981223/eb976699-928f-4087-af90-60a2f1f5009c)

Badge Management
![4 Badge Management](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46981223/49660059-e823-4efe-b1ae-613543498c1a)
![5 Badge Management](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46981223/5fe648fc-7050-4130-9f81-0fb43d77da1c)

Profile
![6 Profile](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46981223/8c44c8a4-39f9-490d-84e7-7910f51937e5)

Weekly Summaries
![7 Weekly Summaries](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46981223/d716b8f0-8057-4e62-ac90-4dee86ea4047)

WBSTasks
![8 WBSTasks](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46981223/a2081aea-37d6-49cc-a919-c693be740b65)

2023-05-31 05:30 UTC, lchua2314 commented on src/components/Timelog/Timelog.jsx
> +                              Add Intangible Time Entry{' '}
```suggestion
                              Add Intangible Time Entry
```
This is probably the caused by the linter.

2023-05-31 16:17 UTC, OAkinbode reviewed
Hi, 

Nice job. I think the solution is pretty elegant. 

<img width="1440" alt="PR 862 working fine" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/5d42c96a-cb9d-4902-8c01-c0381fa1ec12">

2023-05-31 20:30 UTC, AuroraLovesWhales commented
> Hello @AuroraLovesWhales, I also once committed changes in package.json file and deleting it manually, the checks failed. So I pushed again my previous changes, this time, excluding package.json file from my commit. Or you can read this blog from medium https://blog.devgenius.io/how-to-remove-modified-or-changed-files-from-a-git-pull-request-a7769e3c58da.
> 
> Those shadows looks great, I am not sure but are you also planning to do this on reports -> reports -> choose people -> peoplereport page there are two button on below. and also a buttons in bottom of the view profile page. lastly on other links -> popup management page buttons

Hi @papiasharmin. Thank you so much for your feedback! I have raised another PR because I am still unable to solve the issue, and I have taken your advice to add the style to the three areas you pointed out. Please refer to [PR864](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/864) to see the changes. Thank you again!

2023-06-01 23:40 UTC, OAkinbode reviewed
Just for information. This is how the shadows look In dark mode (from PR 842). I added the styling to one of the larger components in that PR and I think they look good as well. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/b3498abb-125b-4649-8706-d786f870c75d

2023-06-03 08:00 UTC, yufeiStella reviewed
It works well now. Great job!
<img width="1331" alt="Screen Shot 2023-06-03 at 02 56 28" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/1afe18d4-ae08-41fd-8ef9-994e3481b3e6">
<img width="240" alt="Screen Shot 2023-06-03 at 02 55 53" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/8d60042d-3905-4cb8-a9bf-1fab39badb9d">

2023-06-29 00:11 UTC, closed without merging