Natalia make reports look good on phone
OneCommunityGlobal/HighestGoodNetworkApp pull request #865
Opened 2023-06-01 19:15 UTC by NataliaCavicchioli

### Description
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103126226/842e2aee-dbda-4dcd-a89b-797384713aef)

### Main changes explained
To fix responsiveness on the reports page, and every subsequent page. 

### How to test
1. check into current branch
2. `npm install` 
3. `npm run start:local` to run this PR locally
5. log in as Admin/Owner, go to Reports → Reports
6. verify if all the pages are responsive. 
- Click the Projects/People/Teams buttons, and click at least one item from each table.

### Note
- Please test for Mobile 375px minimum screen size. 
- The graphs are with overflow: scroll for mobiles, for now, this was the best solution to not lose any data.

### Screenshots of changes:
Before:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103126226/e04daf22-87d1-4a57-b5e7-5b8c94d1d58b)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103126226/dce6bd50-5ee5-477a-a9f4-2d872c9d10b7)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103126226/786bad51-0cb7-45d6-b4c5-d88f4225f2d3)

After:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103126226/754a6bed-8348-46e1-a15d-29c0f22c4319)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103126226/db353d85-9f2c-41cd-b5f0-43f8ad8ee451)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103126226/d39225ad-f535-42fc-a270-d0b1d7d9d9e2)

2023-06-01 21:07 UTC, stevenpaalz requested changes
Nice work on this Natalia!

A few notes/recommendations:
I am unable to open the reports page from a safari browser. This may be the issue that resulted in this task being created in the first place.  The reports page in safari opens a blank white page, regardless of screen size.

On chrome:
The category selector is too large for a 375px screen. For screens this size, recommend reducing this in size so that it isn't scrollable, or maybe stacking the categories vertically rather than horizontally. 

<img width="316" alt="Screenshot 2023-06-01 at 4 41 31 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121642083/5866946e-ddea-4540-9bc6-1370e8e00545">

The tasks table looks a bit odd at 375px. Recommend reducing font size in this chart. Additionally, it may be beneficial to center align the blue buttons shown below and make them the same width.

<img width="287" alt="Screenshot 2023-06-01 at 4 46 49 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121642083/bd199651-1aeb-49fb-893f-6ed4af6b2e26">

In the weekly committed hours area after clicking an individual's name, the spacing of the text is not aligned. See image below.

<img width="319" alt="Screenshot 2023-06-01 at 4 47 49 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121642083/11fd2986-bedb-4ad6-9108-1b02765e9fe3">

2023-06-01 22:44 UTC, 20chen-7 requested changes
Everything looks great!! only some tiny issues, like the task contents layout, and the size of the 'team',' group', and 'project' is a little larger.
<img width="1440" alt="Screenshot 2023-06-01 at 4 39 27 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/80103348-d24f-4789-814c-6d1cf6d96e93">

<img width="1440" alt="Screenshot 2023-06-01 at 4 32 29 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/7dd53ab8-e151-4849-9d47-22a7bde47327">
 great!

2023-06-01 23:32 UTC, NidaZaki reviewed
Tested this PR and the changes look good. But came across some issues:
1. Some misalignment of the contents : 
![PR#865](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/32549172/b0c24c34-f868-486c-98f1-9d78958fda4c)
2. Misalignment in this section as well:
![PR#865-1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/32549172/85ecf4ab-dfb6-4667-972f-24aeaad46f77)
3. The "Team" section is not equal to other sections
![PR#865-2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/32549172/f6dc6d5b-8867-4705-a66b-e684048898b3)

2023-06-01 23:45 UTC, nathanah requested changes
Some widths have hidden overflow of text for ReportBlocks.
701px to around 1000px
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/23086054/80918f86-bee7-43ec-9e06-200859ceee90)

2023-06-01 23:48 UTC, AnishPandita commented
Hi @NataliaCavicchioli I tested your updates and it seems great apart from some minor hiccups. As pointed by others the alignment of elements seems bit off at some places. Also as pointed by @stevenpaalz the reports page on safari is blank regardless of size.
<img width="1440" alt="Screenshot 2023-06-01 at 4 24 25 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/e0328f71-405d-46c6-be79-f780f54e54eb">

<img width="380" alt="Screenshot 2023-06-01 at 4 25 46 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/64102138-c53f-403e-b7c0-8536b7e0ef05">
<img width="541" alt="Screenshot 2023-06-01 at 4 40 27 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/c938143b-b48b-4ddb-8d92-675553885de3">

2023-06-02 10:15 UTC, papiasharmin requested changes
Hello @NataliaCavicchioli, really great work. Along with the issues mentioned by others, I found this issues
On peoplereport page after opening graph
![1200pxafteropengraph](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86232710/c03caa86-e56d-4d62-9eae-2cb54a64623f)
Onteamreport page calender is cutting off
![teamreportpagecalander](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86232710/27b37e7a-f0fe-4d3f-9c74-515af582aeef)

2023-06-02 16:50 UTC, eduhorta commented
Hi, @NataliaCavicchioli!
Here are my observations:

Vertical scroll bar on small devices - cards carrousel - after clicking on any card
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/7354b563-15c2-4b28-9046-d303278a19ee)

Different card sizes
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/06b7fe16-8fc4-4dc5-91eb-e788d4391f1d)

When clicking on people card
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/af51045a-0efd-4c95-9481-f2fb7841cd77)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/40bce5d6-3839-4f81-ae3a-07a500f3d461)

Team card:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/1de69e87-31cd-42c8-bc51-17231fa742c9)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/a62923ad-351f-44f3-a486-32761a30e150)

Projects
Name alignment
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/5a6acecb-7cfe-45d7-90a3-1b8543470fe2)

People's report
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/e8683f9c-644b-46b2-b06f-974b4468b313)

2023-06-02 17:44 UTC, OAkinbode reviewed
Well done Natalia. I checked out the functionalities that you mentioned. They all worked. I did see some squashing of the elements like below. Whether or not anything should be done about those is another question altogether. 
<img width="1440" alt="Mobile view Galaxy s8 PR 865" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/3596ea1c-36e5-42f9-a170-fdc17cd82ebb">

I tested with different phone types from Apple and Samsung and it looks good in my option. See below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/d5eadde3-ddce-4f85-ad8b-4ad3014f094a

2023-06-04 00:03 UTC, yufeiStella commented
Well done! I thoroughly checked the entire app and everything is working well, even in edge cases:

<img width="494" alt="Screen Shot 2023-06-03 at 18 59 17" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/602da7b0-6f72-48ca-acbf-9e48f20fefd0">
<img width="699" alt="Screen Shot 2023-06-03 at 18 59 59" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/8a3eeee7-dff1-479b-bc2f-fc5e7ba7713f">
<img width="578" alt="Screen Shot 2023-06-03 at 19 01 03" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/1727f8ef-3a74-4026-a7e6-9e670ab9c196">
<img width="441" alt="Screen Shot 2023-06-03 at 19 01 40" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/c3a99073-74c7-43bd-af01-3e0d4dcd52cf">

2023-06-16 18:46 UTC, leonzh2k requested changes
Few things that others have probably already mentioned:

This section in the profile page looks weird.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/b4f5060c-4284-4deb-a123-1c8f9713b046)

On a project page, maybe the names could be aligned?
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/302475d3-989d-4423-a596-63231dc7c244)

On a specific team page, when selecting a team to see the visualization of hours worked we get this (doesn't look very good):
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/43af71d9-58a1-4ec4-889e-163cf1b2bcf1)

2023-06-22 21:18 UTC, cvtqx requested changes
Great job on making the pages responsive! There is so much to take into consideration. Here are a few things that I noticed or would like  to suggest to make it look better:

1. Fix horizontal alignment in table rows:

![People-alignment off](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/3f2bd854-a22f-4db3-9ed0-d259bf9eba8c)

2. In Teams the pop up modal is cut off by the parent container if it has too much content in it:
![Teams - pop-up modal cuts off if its too big](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/800cbe58-be3c-49e4-aee3-cbf7f8990696)

3. Center 'Loading' paragraph:

![loading not centered](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/ddbf5628-fbe6-4352-b9f5-d61109fbbb32)

4.Suggestion - to make all input fields the same width 

![Suggestion - input fields need to be the same width](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/2ad6d672-a03d-40da-bd9e-b5591b581c26)

2023-07-08 17:00 UTC, Jiangwei-shi commented
Test as iPhone 12Pro
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/ca198146-023f-428e-933b-14b8173ac42c)
I think the "person Name" should be in the middle of the space, and "More" doesn't have to be around a square.
![屏幕截图 2023-07-08 125647](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/9cfb0769-8270-4070-b5c3-7a2917efa914)
others work as indeed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/cb39bab7-46db-44c8-b46d-56b0dbb4ad8a)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/b540b795-1608-4043-9d43-5ea92645ce2a)

2023-07-08 20:07 UTC, yaow62023 reviewed
I tested the report page in both portrait and landscape states. In both states, the same function and layout as described by the author are realized. People in the portrait mode will display the more button, but in the landscape mode, the start and end dates will be displayed directly. Need to confirm with the author whether the feature works correctly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/e310a13d-d465-4147-99fe-5bf3f2e1c311


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/50b92105-b124-48a0-ab86-2482e774dad0

2023-07-10 13:35 UTC, HectorAgudelo reviewed
the page is responsive, but you got to work on the spacing of some element. For instance between the user info box and the boxes displaying hours and blue squares info. Also, there is a lot of uncentered elements that should be aligned correctly for a smoother view when changing screen sizes.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/8996d87a-b475-4030-9ee0-714e5cdbf239

2023-08-27 00:51 UTC, Shubhu0 commented
The page works as intended and is responsive.

2023-09-28 02:57 UTC, Shubhu0 commented
Hi @NataliaCavicchioli The page is responsive and all the previously raised issues look to have been fixed. It looks good! Good job! Tested the functionality of the page for both iPhone and Samsung, and it worked well.

But i will say, i loaded the page first on Firefox, and it did not show anything and gave me a blank white page for reports. But worked on Edge and Chrome. 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/61e8d9ed-e119-4aa7-b67a-24362d3862a0)

One thing i did notice is that the table names for people and projects arent aligned with the serial number column.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/451397a9-71ba-4ec8-9cdb-b0a1c25da3bd)

2023-09-30 23:04 UTC, one-community commented
Woah... this is super old and got lost in the shuffle somehow. She's been off the team for months, so I need someone to take this over and finish it.

2025-04-16 23:35 UTC, closed without merging