Jinchao add weekly summary indicator on leaderboard for admin users
OneCommunityGlobal/HighestGoodNetworkApp pull request #880
Opened 2023-06-04 01:46 UTC by suigunfjc

# Description
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/94319381/d6622996-7e86-473a-918b-b7dd2f6d1be2)

This PR adds a green √ next to the green/red dot/star on leaderboard for users who have submitted their weekly summaries of this week.

## Related PRS (if any):
Invisibility update PR: #859 
This frontend PR is related to the [#383](https://github.com/OneCommunityGlobal/HGNRest/pull/383) backend PR, please test these two PRs together.

## Main changes explained:
- Moved `onClick={() => dashboardToggle(item)}` from outside `<td>` to inside `<div>` that wrapped the dot/star.
- Added a flex div to hold the weekly summary indicator and the state dot/star, which will keep the dot/star on left for admin user and in center for non-admin user.
- Added the green check mark.

## How to test:
1. check into current branch on both HGNRest and HGNApp
2. do `npm run build` and `npm start` on HGNRest
3. log as Owner/Admin/Core Team user and check if there are green marks for users that have submitted their weekly summary:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94319381/22f120e9-b64e-4171-80f7-21fcdb98ad90)
4. log as non-admin user, check if there is no green check marks and the position of dot is in the center.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94319381/14dcd2f9-46ce-46bd-ba92-b2847ebb2349)
5. submit the weekly summary, log as Owner/Admin/Core Team user to check if the indicator works as expected.

2023-06-04 02:11 UTC, EdwinLauM requested changes
Code looks good and works as intended! As a suggestion, I think it would look nicer to move the red dot of the status to align with the stars and dots.

<img width="785" alt="PR #880" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/d5efcc11-772b-4606-be52-4bc9f795d219">

2023-06-04 17:40 UTC, KurtisIvey submitted a review, later dismissed
Changes function as described. No errors either. Maintains centering on all resolutions. Verified with tester volunteer account. I also agree about the HGN Totals red button, but I know that would have little impact functionality wise. It seems to be perfectly centered when logged in as volunteer. However, with admin login it isn't. 

Image attached verifying functionality as admin:
![pr880check](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/86d20f02-8e1f-41f6-a78f-7e15a9097a92)

imaged attached verifying functionality as volunteer:
![verify](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/a5f97bf1-3c81-418f-8e71-be740858ffa1)

2023-06-05 17:56 UTC, 20chen-7 reviewed
The function is intended. Also, I agree with [EdwinLauM](https://github.com/EdwinLauM)'s opinion, the alighment issues.
Login as a volunteer:
<img width="498" alt="Screenshot 2023-06-05 at 11 01 00 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/255ee08d-cf0b-40fe-a85d-5175bc5a157c">
Login as adminr:
<img width="516" alt="Screenshot 2023-06-05 at 11 53 42 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/51a41625-7cc6-4e37-8b30-7f9e18179e5e">

2023-06-06 12:16 UTC, eduhorta reviewed
Hi, @suigunfjc!
The feature works as intended, nice job! 👍

Preview:
![Screenshot 2023-06-06 09-11-23](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/dae90c3e-b183-400b-b881-de56fa68ba52)

As mentioned by other members, how about align the top red dot of the status with the other dots/stars?

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/1a152088-5561-4f86-971e-b6e95e7a14a2)


![Screenshot 2023-06-06 09-13-06](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/ce007bb8-aa4a-41fb-a770-1c994b3ff219)

2023-06-06 18:22 UTC, stevenpaalz approved these changes
This feature works as intended. Although see other reviewers note on aligning top red dot with the rest of the column.

![Screenshot 2023-06-06 at 2 21 03 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121642083/0ac03ea1-1aef-4cc8-964b-ceabbdbc3f1a)

2023-06-08 22:11 UTC, bienzguoa reviewed
Works as intended! Please see other reviewers note on aligning top red dot with the rest of the column.
Logged as owner:
<img width="807" alt="Screenshot 2023-06-08 at 4 52 14 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/17773115-2dea-4ebd-890b-d939878763a1">
logged as volunteer:

<img width="680" alt="Screenshot 2023-06-08 at 4 53 13 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/8d79f8c6-4f6c-4a94-b2da-e0fd5943c46b">
submitted :
<img width="981" alt="Screenshot 2023-06-08 at 4 58 45 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/5dbfbe85-7cb5-446f-becb-caf11fba4057">
then logged as owner:
<img width="638" alt="Screenshot 2023-06-08 at 4 59 52 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/90479231-d492-4c14-8be7-9cc6c9f45ca8">

2023-06-09 04:19 UTC, suigunfjc commented
Hi @EdwinLauM , thank you for pointing this out. My concern here is that the first line is actually never gonna have the check mark as other lines so I didn't change the position of the dot for the first line. I would like to hear opinion from Jae @one-community

2023-06-09 20:16 UTC, cvtqx requested changes
Implemented changes work as described.

1. When logged in as volunteer, red dots are centered:
![Volunteer - red dots centered](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/341122bf-6577-4406-8452-f4177cbf029b)

2. After submitting weekly summary on a volunteer account and then logging back in as Admin, I can see a  green checkmark next to the corresponding record. 
![Admin-GreenCheckMarkDisplayed](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/777c14ce-e8ba-46e6-9232-ac97ba1c558e)

Agreed that the top red dot will look better if aligned with the other dots in the list

2023-06-09 20:34 UTC, mahamakhan commented
The features work perfectly fine but the red dot of HGN Totals needs to be aligned.

<img width="397" alt="image"
<img width="1031" alt="Screenshot 2023-06-09 132933" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/a27d22f0-5dec-486a-bb3e-014cdf25c44b">
 src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/b3778ed8-f63f-4b62-8974-bb506a07b34b">

2023-06-09 20:37 UTC, mahamakhan submitted a review, later dismissed
The features work perfectly fine but the red dot of HGN Totals needs to be aligned.

<img width="397" alt="image"
 src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/b3778ed8-f63f-4b62-8974-bb506a07b34b">
<img width="1031" alt="Screenshot 2023-06-09 132933" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/a27d22f0-5dec-486a-bb3e-014cdf25c44b">

2023-06-09 22:23 UTC, OAkinbode reviewed
Well done. The code works as intended barring the changes others have indicated. 
<img width="1440" alt="PR 880 and 383 working" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/41f66822-e3f0-425c-a6b5-ae8e1040caff">

2023-06-10 02:34 UTC, yufeiStella submitted a review, later dismissed
Good job! It works as intended.
Log in as admin:
<img width="723" alt="Screen Shot 2023-06-09 at 21 32 02" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/89e9f9d6-6e27-48f6-a18f-46c4e181b849">
Log in as the volunteer:
<img width="608" alt="Screen Shot 2023-06-09 at 21 30 46" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/1b5742b9-165b-41b6-8e0c-5ba887d0b4e8">

2023-06-10 07:11 UTC, one-community commented
> Hi @EdwinLauM , thank you for pointing this out. My concern here is that the first line is actually never gonna have the check mark as other lines so I didn't change the position of the dot for the first line. I would like to hear opinion from Jae @one-community

Good point and catch! Please remove the dot for that line, it doesn't serve a purpose.

2023-06-11 00:07 UTC, rachnapandya commented
Except for the improvements others have suggested, the code operates as intended. Good Work.
Log in as a Volunteer.
![volunteer_login](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/b803ddaf-bafc-4f5d-ac4e-2e51ba226d00)

Log in as an admin.
![admin_login](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/754717c8-e47b-495d-bcd9-cdafbb495522)

2023-06-14 15:14 UTC, Chuehleo submitted a review, later dismissed
Everything works as intended. Good job!
Log in as admin:
![Screenshot 2023-06-14 075006](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/7dbc2d9d-90e3-49fc-babb-04639854b0f0)
Log in as volunteer:
![Screenshot 2023-06-14 074837](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/6ca415d0-25d2-4b0f-a453-e28915d47b29)

2023-06-15 05:19 UTC, suigunfjc commented
Hi guys @bienzguoa @20chen-7 @OAkinbode @eduhorta @EdwinLauM @cvtqx @KurtisIvey @mahamakhan @yufeiStella @stevenpaalz @Chuehleo. The latest change was maded to remove the status dot in the first line based on Jae's requirement. 

Also, this PR recover the invisibility state icon in #859, which was affected by the revert commits during the new timer setup (around 2 weeks ago). 

Please test this PR again and remember to pull the latest commit on [BE](https://github.com/OneCommunityGlobal/HGNRest/pull/383) which gets it merged with the latest development branch. Thank you!

Btw, if you have PRs merged during the new timer setup, please check them on the Dev to make sure they weren't mistakely reverted.

2023-06-15 12:45 UTC, eduhorta requested changes
Hi @suigunfjc!
As mentioned by @EdwinLauM and @one-community, the dot for that line wasn't adding up.

The only issue I see is the vertical of HGN Total Members

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/0d5e3b2b-8cb9-453b-9749-c097b88fde7b)

Once you fix this, please tag me or send me a message on Slack so I can approve.

Nice job! 👍

2023-06-15 12:45 UTC, eduhorta commented on src/components/LeaderBoard/Leaderboard.jsx
>                <th scope="row">{organizationData.name}</th>
Add className="align-middle"

`<th className="align-middle" scope="row">{organizationData.name}</th>`

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/0a84f4e8-e933-48d4-b8c1-b9f1aedf5d07)

2023-06-16 06:27 UTC, suigunfjc commented
Hi @eduhorta, this bug is actually confusing because even with a dev branch in local, the align issue exists: 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94319381/40f8c71b-bfbf-4d95-9dcc-a009f68d6d67)
While this issue doesn't exist in our dev app:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94319381/81a3b2ca-8f33-4d69-9e34-f06c5d40fe42)
So I think the bug is out of this PR's scope and may relate to some css conflicts when you run the app locally.

2023-06-16 16:25 UTC, eduhorta approved these changes
Hey, @suigunfjc!

I think you are right. This behaviour is outside of the scope of this PR.

Everything is working as intended here! Nice job! 👍

2023-06-27 22:10 UTC, KaixiangGU commented
Work as intended. GJ!
<img width="1185" alt="Screenshot 2023-06-27 at 3 07 24 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98206107/50c630b7-b9be-48c8-8f91-49395094c1d7">

2023-06-27 22:11 UTC, KaixiangGU approved these changes

2023-06-28 02:54 UTC, merged