AddTaskModal & EditTaskModal - Table overflowing Modal css updates for the bug fix
OneCommunityGlobal/HighestGoodNetworkApp pull request #883
Opened 2023-06-06 03:27 UTC by NidaZaki

# Description
The AddTaskModal and EditTaskModal have their input fields overflow the size of the modal when the page is opened/refreshed with developer tools open
Fixes # (bug list priority low)
Added media query on `wbs.css` which should enforce a fixed table layout when the window size changes on a responsive layout triggered by developer tools. 

## Main changes explained:
- Added media query on `wbs.css` between 200px and 1496px that applies the css rule `table-layout: fixed`

## How to test:
1. check into current branch
2. log as admin user
3. Open Developer Tools
4. Refresh the page
5.  Other Links > Projects > WBS > select an item > Add Task/Edit Task (any of them)
6. Please Verify that the fields inside the modal DO NOT overflow the width of the modal.

## Screenshots or videos of changes:
### Before:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/32549172/7b7785eb-a2f8-4ac6-b36f-e6133c8dfa8f)

### After
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/32549172/7f99acbf-39e8-4631-afef-c95231b10af0)

2023-06-06 05:14 UTC, AnishPandita commented
Hey @NidaZaki I tested your PR and the add/edit task modal does not overflow when developer tools are open.
<img width="1440" alt="Screenshot 2023-06-05 at 10 14 12 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/9dd7b7a2-357f-4084-b480-31e1b23fb544">

2023-06-06 05:15 UTC, AnishPandita approved these changes

2023-06-06 17:38 UTC, OAkinbode reviewed
Nice work. It seems like it works fine. 
<img width="1440" alt="New task PR883" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/f16c0890-78aa-43ae-a9b0-fa4fbd3474c2">

2023-06-06 18:16 UTC, stevenpaalz submitted a review, later dismissed
I am able to confirm that this bug is fixed across varying window widths. Nice work!

![Screenshot 2023-06-06 at 2 14 52 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121642083/77b8a51f-4af9-4fb2-bdc8-f98cc7473d38)

2023-06-06 18:46 UTC, leonzh2k requested changes
Looks good when adding a task:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/72c353bf-8519-4ff3-8f36-19acd76ba97c)
Looks good when editing a task:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/50865201-eba6-4ec6-8cff-1967a06bf43d)

So the functionality looks good. There's just the issue of code formatting. Not sure why the formatting is changed in `OwnerMessage.css` and `TableFilter.css` as I don't think they're relevant to the modals. For the other files, maybe the reformatting should be addressed in a separate PR?

2023-06-06 18:46 UTC, leonzh2k commented on src/components/OwnerMessage/OwnerMessage.css
What's the reasoning behind this code style change?  As far as I know this component isn't used in the modals you changed (correct me if I'm wrong). Also, I'm not sure if this conforms to the code style either (Prettier detects code style issues).

2023-06-06 18:46 UTC, leonzh2k commented on src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
Prettier detects code style issues in this file

2023-06-06 18:46 UTC, leonzh2k commented on src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
Prettier detects code style issues in this file

2023-06-06 18:46 UTC, leonzh2k commented on src/components/Projects/WBS/WBSDetail/wbs.css
Prettier detects code style issues in this file

2023-06-06 18:46 UTC, leonzh2k commented on src/components/Reports/TableFilter/TableFilter.css
What's the reasoning behind this code style change? As far as I know this component isn't used in the modals you changed (correct me if I'm wrong). Also, I'm not sure if this conforms to the code style either (Prettier detects code style issues).

2023-06-06 20:01 UTC, nathanah approved these changes
This fixes the issue I was having. Thank you.

2023-06-07 01:04 UTC, NidaZaki commented on src/components/Projects/WBS/WBSDetail/wbs.css
Made commits to address these styling issues

2023-06-07 01:31 UTC, NidaZaki commented on src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
What's the command to test code style issues? This was automatically added by the linter. So I guess that's what it likes. Surprising it is now complaining about code style issues. Probably some part of the configuration is corrupted and is working against itself.

2023-06-07 17:58 UTC, leonzh2k commented on src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
It should be something like `npx prettier --check path_to_file`. Did you use this to check for problems?

2023-06-07 18:31 UTC, 20chen-7 approved these changes
Everything looks good no matter add Task or edit Task.
Varying window's width:
<img width="1236" alt="Screenshot 2023-06-07 at 12 29 52 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/d844e669-686e-4b96-b6d6-4eaba6a36283">
<img width="1216" alt="Screenshot 2023-06-07 at 12 28 44 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/c94dbffe-8afd-4eea-97b3-d9c6a4e7206a">
Edit Task:
<img width="1220" alt="Screenshot 2023-06-07 at 12 30 18 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/0c3ae1ed-2904-496b-a359-26b66c985f60">

2023-06-07 20:16 UTC, leonzh2k commented on src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
Your latest commit to this file has fixed all Prettier issues, at least for me.

2023-06-07 20:25 UTC, NidaZaki commented on src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/32549172/fbd1617d-6c4d-43f1-8163-532274394913)
On Ctrl + S command on VSCode, the styling formatting changes were added automatically. Later I used `npx prettier` command and that worked. Thanks for the feedback and help.

2023-06-07 20:26 UTC, NidaZaki commented on src/components/Reports/TableFilter/TableFilter.css
Updated the lint fixes

2023-06-07 20:37 UTC, leonzh2k approved these changes
Okay, looks there are no more formatting issues.

2023-06-08 03:45 UTC, nathanah approved these changes
Looks good

2023-06-08 20:44 UTC, 20chen-7 approved these changes
Looks good!

2023-06-09 14:29 UTC, NidaZaki commented
> Hi, @NidaZaki!
> 
> I'm having the same issue as in PR #891. Failed to compile the timer. Probably because of the revert.
> 
> ![image](https://user-images.githubusercontent.com/105796041/244710076-c4dfb192-c5d2-42ff-9724-4b4eb9a4012c.png)

Hi, Did you try doing npm install after pulling down this branch? If not, try doing npm install both in the FE and BE.

2023-06-09 18:39 UTC, cvtqx approved these changes
When dev tools are open, the table fields do not overflow the width of the table. The table looks neat no matter the screen size. Nicely done!

![Screen Shot 2023-06-09 at 2 33 50 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/a5de2a1a-f307-431b-aeb0-7483badc164a)

2023-06-09 22:15 UTC, Lucas-E commented
Thank you everyone, moving this to final review!

2023-06-10 08:26 UTC, bienzguoa approved these changes
Looks good! The fields inside the modal do not overflow the width of the modal.
<img width="1202" alt="Screenshot 2023-06-10 at 3 20 03 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/28ea8497-0cbc-4c2e-8dc7-fb9cab78967f">
<img width="1175" alt="Screenshot 2023-06-10 at 3 20 36 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/24062072-3978-4fa6-a938-f92587649d1a">

2023-06-10 19:41 UTC, EdwinLauM approved these changes
Code changes look good and works as intended! Good job! 

<img width="1678" alt="Screen Shot 2023-06-10 at 12 39 02 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/7b5081c9-9acb-42ca-84d0-6e25675cc431">

2023-06-12 00:50 UTC, merged