Alex- Add Current Prompt modal to Weekly Summary and a copy prompt function
OneCommunityGlobal/HighestGoodNetworkApp pull request #890
Opened 2023-06-07 18:08 UTC by alexander-huerta

# Description
This PR adds a modal that contains the most current AI prompt that users should be using with their text completion editor of choice, to edit their weekly summary Upon entering the modal, there is a button that allows the user to copy the prompt to their clipboard.

## Related PRS (if any):
This PR adds to progress made in PR [868](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/868) on the Weekly Summary component. 

Future plans for the Weekly Summary Component include:

next week
1. Add the Current Prompt as a value in the database 
 note: the `currentPrompt` variable on line 15 of `CurrentPromptModal.jsx` is a temporary placeholder
2. Allow owners to easily edit the Current Prompt value--  and have changes be reflected instantly for all users.

this month

3. Integrate AI into the editor and have the option to auto generate a summary based on a users tangible time logs from current week  

## Main changes explained:
- Created a modal  to display the current AI prompt 
- Added a Button to trigger this modal to open, and placed it in the weekly summary component, under the text form
  - Added a more info modal to this button (this was not in the requirements and may be unnecessary. I would appreciate opinions) 
- Added a copy button in the current prompt modal to copy the current prompt

## How to test:
1. Start backed-(HGNRest repository) from the development branch by running npm run build then npm  start
2. From this repository, check into current branch and run npm run start local
3. Log as any user (more than one ideally)
4. Follow the process you normally would to add a weekly summary 
5. Test the changes and functionality explained above 

## Screenshots or videos of changes:
![btn](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59572783/ccf7f518-4a37-4cd6-82ad-b6992735da02)

![info_modal](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59572783/f54f32bb-c3f6-4050-bc38-b4a24b0c2a67)

![2023-06-07_14-04](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59572783/22d7a4ee-e366-43d7-b990-a5dd3db29ab1)

2023-06-07 18:24 UTC, 20chen-7 submitted a review, later dismissed
Code and function look great!
<img width="590" alt="Screenshot 2023-06-07 at 12 23 30 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/1358882f-9700-49e0-b868-7f0013e2db74">
<img width="706" alt="Screenshot 2023-06-07 at 12 23 24 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/45e36f46-a06e-488f-bb23-49bf1140fc72">

2023-06-07 20:59 UTC, stevenpaalz submitted a review, later dismissed
This feature is working as intended. Nice work! Tested from admin, volunteer, and manager accounts.

Note: Please reach out to me regarding future functionality of integrating chat-gpt prompt directly into the modal via OpenAI API. I recently did this for another application I am working on.

<img width="915" alt="Screenshot 2023-06-07 at 4 56 36 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121642083/65d69d22-9428-4d64-93cc-97701e788678">
<img width="786" alt="Screenshot 2023-06-07 at 4 53 26 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121642083/abddea34-5e32-4b07-95fb-a73484cd161b">

2023-06-07 21:06 UTC, nathanah submitted a review, later dismissed
Not sure if the button would be better above the text box, but it appears to work as intended.
example:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/23086054/19d801e4-2f82-49d0-b97f-cee46f790386)

2023-06-08 04:59 UTC, one-community commented
> Not sure if the button would be better above the text box, but it appears to work as intended.
> example:

Yes, that's where I envisioned this too. Please move it there and change the text to say "View and Copy Current AI Prompt"

2023-06-08 12:17 UTC, eduhorta submitted a review, later dismissed
Hi, @alexander-huerta!
The feature is working as intended! Nice job! 👍👍
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/b3c34152-836e-407d-b4c9-7d7b1999ffe7)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/6a368fd8-1da1-4ae1-898d-adf03e76ffdc)

2023-06-08 15:42 UTC, cvtqx approved these changes
The new modal looks great and is copied to clipboard as described. Great job!

Button with a tooltip:

![Screen Shot 2023-06-08 at 11 33 56 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/ac353371-a08d-4d23-a957-fdab2561da8b)

Modal after 'copy' button is clicked:

![Screen Shot 2023-06-08 at 11 34 29 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/47f6e95e-ad02-4224-91b4-83a6bc92d46d)

2023-06-08 18:30 UTC, AuroraLovesWhales submitted a review, later dismissed
Hi @alexander-huerta! I have reviewed your PR and everything works as intended. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/f97f68ab-9825-4ad1-84b0-58e05aad96da

2023-06-09 02:31 UTC, AnishPandita commented
Hi @alexander-huerta I tested the PR and its working as intended. Tested via different users as well. The prompt modal and copy functionally is great.
<img width="806" alt="Screenshot 2023-06-08 at 7 28 33 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/6bb7c093-3337-4525-bf27-9fdd137beba0">
<img width="1440" alt="Screenshot 2023-06-08 at 7 28 47 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/8d422bbf-b8a2-41a5-8e8b-664924bb57e7">

2023-06-09 03:49 UTC, NidaZaki submitted a review, later dismissed
Works as intended! Nice work! The button and the modal including the tooltip
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/32549172/193ca79b-4ed3-41f3-998f-04fd03ff0d41)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/32549172/1688f1c7-f842-4710-a7a0-7f3fd9be7caa)

2023-06-09 20:23 UTC, leonzh2k submitted a review, later dismissed
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/48083084-ad33-4e51-9f0a-954e44606ebc)
Info popup works:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/628033a4-468d-4943-b137-87edf286e49c)
Modal works;
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/0538fd89-dd49-4430-a579-9f3f82a5d28c)

Copying works:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/5b19e397-13ab-4c1f-867d-56ca5a6598ed)

2023-06-09 20:57 UTC, Lucas-E commented
Thank you everyone, moving this to final review!

2023-06-10 01:09 UTC, alexander-huerta commented
Thanks all! Final adjustments have been made. 
@one-community @Lucas-E 

1. Button moved above the form box and to the right
2. Button Text updated 

![890_adjustments](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59572783/37051aa4-15a3-4876-8a6f-1858a28f5145)

2023-06-10 07:07 UTC, one-community commented
> Thanks all! Final adjustments have been made. @one-community @Lucas-E
> 
> 1. Button moved above the form box and to the right
> 2. Button Text updated

Looks great, thank you!

2023-06-10 07:30 UTC, bienzguoa approved these changes
Works as intended! 
<img width="846" alt="Screenshot 2023-06-10 at 2 23 32 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/a3cdd73e-d113-4d6d-b00c-9b1abfd83deb">
<img width="1011" alt="Screenshot 2023-06-10 at 2 26 29 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/14ceffad-22c2-44af-8197-ff970f455f42">
<img width="1084" alt="Screenshot 2023-06-10 at 2 26 54 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/3356ff77-87f7-4a6f-8b60-32f39e64a214">

2023-06-10 18:31 UTC, KaixiangGU commented
It works well! Good job!

2023-06-10 19:51 UTC, EdwinLauM approved these changes
Works as intended! Good job! 

<img width="955" alt="Screen Shot 2023-06-10 at 12 48 46 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/37168b8c-33d1-42bd-afe5-cf682c4d98cd">

<img width="1108" alt="Screen Shot 2023-06-10 at 12 48 53 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/63b91290-49d8-4fdd-a9cd-bfebefdfcbd2">

2023-06-10 21:36 UTC, nathanah requested changes

2023-06-10 21:36 UTC, nathanah commented on src/components/WeeklySummary/WeeklySummary.css
> +  justify-content: space-between;
```suggestion
  justify-content: space-between;
  margin-right: 0;
```
Last thing so the button lines up with the editor, but everything looks good other than that.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/23086054/39d6713d-a034-4749-bf86-08449eb45c1f)

2023-06-12 02:59 UTC, nathanah approved these changes

2023-06-12 23:27 UTC, merged