Yongjian - Create back to top button on index page
OneCommunityGlobal/HighestGoodNetworkApp pull request #910
Opened 2023-06-13 19:23 UTC by ypan710

# Description
![Screen Shot 2023-06-13 at 12 04 41 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46613683/222be96f-108b-4f5f-b086-23293e82e6b2)

## Main changes explained:
Check for error states for invalid email and/or password whenever users submit credentials to login.

## How to test:
1. check into current branch
2. do `npm run start:local`
3. login using correct email but incorrect password and verify "Invalid email and/ or password." message pop ups every time.
4. login using incorrect email and incorrect password and verify "Invalid email and/ or password." message pop ups every time.

## Screenshots:
![Screen Shot 2023-06-13 at 12 00 42 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46613683/8423564d-5ea2-4a1f-a285-15a25701c3b4)
![Screen Shot 2023-06-13 at 12 01 04 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46613683/fa37b163-fa66-4a74-85c3-b152a112ccc1)
![Screen Shot 2023-06-13 at 12 02 07 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46613683/f00e83aa-66f0-47b8-882c-4c5903ecf0c0)
![Screen Shot 2023-06-13 at 12 02 14 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46613683/f4705366-ebde-4d71-88aa-2cbf65eb2341)
![Screen Shot 2023-06-13 at 12 02 35 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46613683/df8ac8ad-bc6b-43d3-b29f-561f7bab84da)

2023-06-13 20:10 UTC, leonzh2k requested changes
Functionality works. Minor code changes requested.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/60fd89fd-9a0d-49d8-bc19-f79063155017

2023-06-13 21:06 UTC, ypan710 commented on src/components/common/Form/Form.jsx
what code style issues?

2023-06-13 21:07 UTC, ypan710 commented on src/components/common/Form/Form.jsx
> Prettier reports code style issues with this file

what code style issues?

2023-06-13 21:10 UTC, leonzh2k commented on src/components/common/Form/Form.jsx
When I run `npx prettier --check src/components/common/Form/Form.jsx` it detects code style issues

2023-06-13 21:44 UTC, stevenpaalz submitted a review, later dismissed
This appears to work as intended. Be sure to remove console.log statement before merging.

![Screenshot 2023-06-13 at 5 42 26 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121642083/606dbeaa-3bf0-4a25-9422-0703f12c7fde)

2023-06-14 04:02 UTC, AnishPandita commented
Hi @ypan710, I tested the PR and the login feature does the login check as intended. I tried all the possibilities as suggested by you and it worked well.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/18618209-b527-4c5c-b2e8-b478800c1d66

2023-06-14 05:40 UTC, rachnapandya commented
It is working well @ypan710. Good work

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/ae7ddf76-bc8f-4d99-b957-4753b1a22619

2023-06-14 12:56 UTC, eduhorta reviewed
Hi, @ypan710!
Great job! 👏
It is working as intended.
As mentioned by @stevenpaalz, just remove the console.log so we can approve.

![Screenshot 2023-06-14 09-52-55](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/f9a26dde-3aa8-4edd-b6ca-593ea9eb1227)

2023-06-14 23:12 UTC, OAkinbode reviewed
Hello Yongjian, nice work. I however observed some peculiar behavior and I am not sure if it is part of the scope of this PR or not. I mutilated my email address when trying to log in and not only didn't I get errors, I was allowed through to the dashboard. 

Here I am removing "m" from the end of my email. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/130272b9-9bda-4d78-8360-48135f3b74d3

I am here removing the first few letters of my email address before logging with the correct password.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/a07f7fa9-5c5f-416e-b567-633909342fcf

I tried doing this with some of my other accounts (admin and volunteer) and yes, as long as the password is correct, it lets them through.

2023-06-14 23:37 UTC, mahamakhan commented
Works as mentioned.


<img width="334" alt="Screenshot 2023-06-14 163451" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/2a89c131-2f23-42fa-ba3d-79351afd4479">
<img width="304" alt="Screenshot 2023-06-14 163513" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/d96f98a3-afc2-40ab-ad7c-50d366548574">

2023-06-14 23:37 UTC, mahamakhan approved these changes
Works as mentioned.


<img width="334" alt="Screenshot 2023-06-14 163451" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/2a89c131-2f23-42fa-ba3d-79351afd4479">
<img width="304" alt="Screenshot 2023-06-14 163513" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/d96f98a3-afc2-40ab-ad7c-50d366548574">

2023-06-15 04:39 UTC, bienzguoa reviewed
It works as you mentioned, but I also encounter the same as OAkinbode said:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/2d8071d7-826e-406b-a3c1-b26c1e6dc5e9

2023-06-15 17:45 UTC, ypan710 commented on src/components/common/Form/Form.jsx
I turned off prettier because I've found that whenever I tried to save while working in this project, some of the existing codes in some files got removed in VS code.

2023-06-15 17:48 UTC, ypan710 commented on src/components/common/Form/Form.jsx
> +    console.log("submit")
Removed in new commit

2023-06-15 17:49 UTC, ypan710 commented
> Hello Yongjian, nice work. I however observed some peculiar behavior and I am not sure if it is part of the scope of this PR or not. I mutilated my email address when trying to log in and not only didn't I get errors, I was allowed through to the dashboard.
> 
> Here I am removing "m" from the end of my email.
> 
>  PR.910.issues2.mov 
> I am here removing the first few letters of my email address before logging with the correct password.
> 
>  PR.910.issues1.mov 
> I tried doing this with some of my other accounts (admin and volunteer) and yes, as long as the password is correct, it lets them through.

@OAkinbode I believe that is beyond the scope of this PR. You can raise the issue on the bug list. Thanks.

2023-06-15 17:50 UTC, ypan710 commented
> It works as you mentioned, but I also encounter the same as OAkinbode said:
> 
>  Screen.Recording.2023-06-14.at.11.36.36.PM.mov

@bienzguoa I believe that is beyond the scope of this PR. You can raise the issue on the bug list. Thanks.

2023-06-16 04:44 UTC, yufeiStella commented
Good job! I tested it, and everything is fine.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/598447a2-ddcc-4a0a-8b6e-982bc5b06556

2023-06-16 10:07 UTC, papiasharmin requested changes
Hello, @ypan710, everything is working as intended, great work. just one small suggestion, it will be nice if the password is wrong, the notification should appear bottom of password input. so user will be sure, the password is wrong not the email

2023-06-16 13:14 UTC, EdwinLauM approved these changes
Works as intended! Approving this since it looks like the suggestions from the other members are out of the scope of this PR.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/d0d04c20-4a7d-42ec-b01a-c8790407a71e

2023-06-16 15:01 UTC, papiasharmin commented
> > Hello, @ypan710, everything is working as intended, great work. just one small suggestion, it will be nice if the password is wrong, the notification should appear bottom of password input. so user will be sure, the password is wrong not the email
> 
> For security purposes, I'm not too sure if letting the user know whether the password or email is wrong is ideal. if an outside user is trying different emails and ends up correctly guessing an email they will now be able to narrow the possibilities to only guessing the password. What do you think @one-community?

Okay, Sorry I did not know that.

2023-06-16 15:02 UTC, papiasharmin approved these changes
Working as intended.

2023-06-16 16:15 UTC, cvtqx approved these changes
Works as described.

The alert pops up every time when logging in with incorrect email and password, logging in with either incorrect email or password:

![Screen Shot 2023-06-16 at 11 58 14 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/c4491fea-f67e-44d6-a8d9-eba79e5a145c)

Agree with others that it does let you log in if you type gmail.c or gmail.co at the end, but that's out of this PR scope.

2023-06-16 16:23 UTC, eduhorta approved these changes
It works as intended! Great job! 👍

2023-06-16 16:25 UTC, KurtisIvey approved these changes
functions as it should, passes all tests, and the code is cleaned up. Good job

![pr910](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/4c434dc9-237f-495b-a2f9-17a60b9cdfcd)

2023-06-16 18:04 UTC, leonzh2k approved these changes

2023-06-17 23:03 UTC, one-community commented
Thank you everyone, merging!

2023-06-17 23:03 UTC, merged