Lucile_bug_rehireable_reports
OneCommunityGlobal/HighestGoodNetworkApp pull request #914
Opened 2023-06-15 23:59 UTC by LucileTech

# Description
The End date is sent to backend in the right format. After this PR was merged due to a bug issue, I had to manage the date in the front : 
https://github.com/OneCommunityGlobal/HGNRest/pull/405/files

###Description
9. (PRIORITY MEDIUM) Jae: Add work confirmation improvements to People Report (WIP Lucile)
Admin or Owner login → Reports → Reports → People → Choose
Remove “hours logged this week” section: If a user is INACTIVE (has an end date), then the “Hours Logged This Week” square should not show. Center the remaining ones.
Please also add the User’s Title under their name.
Please also add a “Rehireable” section under their name that can be clicked as Yes or No

11. (PRIORITY LOW): In smaller view widths (<=1200px), the tops of the report blocks are cut off. (WIP Lucile)

###Related PR
To test this frontend PR you need to checkout the  #405 backend PR.
https://github.com/OneCommunityGlobal/HGNRest/pull/405
do "npm install" and "npm run build" and "npm start" to run this PR locally

###Mainly changes explained:
1 - Was added a new set State in setRehireable in PeapleReport

###Before (sorry for my slow connexion)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111132148/e92b0a4c-9f38-4129-963b-645cdada4b9d

###After (sorry for my slow connexion)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111132148/ae80a0ca-568f-454f-93f5-adfaa0bd0eef

###How to test:
Git checkout Lucile_add_work_confirmation_improvements_to_people_report in the frontend
do npm install and npm run start:local to run this PR locally

Git checkout Lucile_End_Date_Issue
do npm install and npm run build and npm start

Admin or Owner login → Reports → Reports → People → Choose someone with an end date 
You should not see "hours logged this week" section
You should see the User’s Title under their name
You should be able to checkout and checkout the rehireable check box on the right.
The chosen check should remain even if the page is refreshed.
The tops of the report blocks should not be cut off in smaller views

Admin or Owner login → Reports → Reports → People → Choose someone without an end date 
You should see "hours logged this week" section
You should see the User’s Title under their name
You should not see the rehireable checkbox
The tops of the report blocks should not be cut off in smaller views

2023-06-16 05:10 UTC, yufeiStella commented
Hi @LucileTech, I have checked both users with and without an end date, and they have different views as you described. Also, the Rehireable checkbox can be changed and it persists even after reloading.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/1f2210b1-32f3-483f-8155-9950434bc912

2023-06-16 06:26 UTC, bienzguoa approved these changes
Hi,
Good job! I tested using owner account, it works as described. Someone's title is blank, but I think it's because not set in their profile.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/02862781-8302-4f9d-845e-5dce3e41fae3

2023-06-16 08:12 UTC, Chuehleo approved these changes
Everthing work as intended, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/4aa07650-a0b3-4bff-999b-04255f78fbe3

2023-06-16 09:53 UTC, papiasharmin approved these changes
Everything is working as intended. great work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86232710/ae9df6dc-d681-4293-9bcb-87261d20401e

2023-06-16 13:03 UTC, EdwinLauM approved these changes
Works as intended! Good job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/1dfb0085-dc70-4940-81b3-9e360be8558c

2023-06-16 14:20 UTC, cvtqx approved these changes
The changes work as described and the tops of report blocks remain visible in smaller widths.

[Screen Recording 2023-06-16 at 10.08.05 AM.mov.zip](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/files/11771203/Screen.Recording.2023-06-16.at.10.08.05.AM.mov.zip)

2023-06-16 18:21 UTC, eduhorta approved these changes
Hi, @LucileTech!

Everything is working as intended! Great job! 👍

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/4484f26d-2bd5-4414-b2f4-bfa5707bad72

2023-06-16 19:07 UTC, OAkinbode reviewed
Hello Lucile, 

The PR seems to work fine. Well done. 
![Uploading PR 911 working.png…]()

2023-06-16 20:50 UTC, stevenpaalz approved these changes
All functionality tested and appears to be working as intended. Good work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121642083/0099571c-139c-4851-b6ec-4be06b213bba

2023-06-17 03:12 UTC, suigunfjc requested changes
Hi @LucileTech , I reviewed your #836 , [#362](https://github.com/OneCommunityGlobal/HGNRest/pull/362) and this PR. 

I understand the reason behind adding the `new Date(...` line and modifying the endDate in this PR. In the original `putUserController`, the `endDate` needs to be in the 'YYYY-MM-DD' format to pass the `yearMonthDayDateValidator(req.body.endDate)` condition. However, when updating the `isRehireable`, the `endDate` is sent as a timestamp string like `2023-06-21T00:00:00.000Z`, which results a N/A in endDate after update.

To address this issue, I propose creating a new function in `userProfileController` specifically for updating a single field. This approach is preferable because the `putUserProfile` should be used solely for COMPLETE updates of the userProfile, where the provided object replaces the target userProfile entirely. However, in this case, the `this.props.userProfile` you provided (line 155 in PeopleReport.jsx) is incomplete and lacks some fields such as `isVisible`(You can check this field under userProfile->Teams->Visibility). Updating `isRehireable` would unintentionally set `isVisible` to false. 

This bug also happens when updating `bioStatus` in this Page, which also calls `putUserProfile` function with a incomplete userProfile. Hence, implementing a separate function in userProfileController for updating individual fields would be a more suitable solution:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94319381/c4b61f39-f9cc-4712-a5d5-156f5945b6eb)


Please let me know your thoughts on this approach.

2023-06-22 03:42 UTC, AnishPandita commented
Hey @LucileTech I tested the PR and it works well. Good job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/e5ff599b-7995-421e-87a7-75f8ce43527a

2023-06-25 04:49 UTC, rachnapandya commented
Works as intended!
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/3a997e52-5c55-49f2-bc53-d1133b64a331)

2023-06-26 16:18 UTC, closed without merging