update the readme files
OneCommunityGlobal/HighestGoodNetworkApp pull request #915
Opened 2023-06-16 22:44 UTC by EvianTan

# Description
Due to the dated Readme file, I plan to update it and also create "good" documentation in the near future

## Related PRS (if any):
None

## Main changes explained:
Update the markdown file and upload images

## How to test:
just see the view of README file

## Screenshots or videos of changes:

2023-06-16 23:38 UTC, bienzguoa reviewed
Hi,
It looks good! Are the contents of Roadmap, License and acknowledgement still in updating?

2023-06-17 00:57 UTC, yufeiStella reviewed
The readme file is looking good so far!

2023-06-17 07:09 UTC, mahamakhan approved these changes
The readme looks good.

2023-06-17 14:56 UTC, KurtisIvey requested changes
I think in line 85 it may be better to mention that there's a preferred node version. Lots of people run into the gyp issue.

1. Node v12.5(v14.17.6 preferred) or higher installed on your machine.

2023-06-17 14:56 UTC, KurtisIvey requested changes
I think in line 85 it may be better to mention that there's a preferred node version. Lots of people run into the gyp issue.

1. Node v12.5(v14.17.6 preferred) or higher installed on your machine.

2023-06-17 21:43 UTC, leonzh2k reviewed
Are you intending for this new README to be a place where new volunteers can learn how to get the app running? If so, I think the google doc does a better job currently (mentions what to put in `.env` file, etc.

2023-06-17 21:43 UTC, leonzh2k commented on README.md
> +1. Join One Community as a member
Would be helpful to include a link to the volunteer application here

2023-06-20 16:03 UTC, eduhorta commented
Not sure if this is outside of the scope of the PR, but, there was a comment on instructions for running the app regarding Apple M1 incompatibility made by @stevenpaalz that could be useful aswell.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/007297a7-c885-47e3-b51f-4f54516e09ed)

2023-06-21 16:00 UTC, cvtqx commented
Looks good so far!

2023-06-22 13:15 UTC, Chuehleo approved these changes
The readme file looks pretty good!

2023-06-23 21:16 UTC, wang9hu approved these changes
Looks a lot more professional, and I agree with @leonzh2k, this can be where it starts, and gradually transfer from google doc.

2023-06-25 00:38 UTC, rachnapandya commented
the readme file is looking great so far with a good format.

2023-07-07 00:16 UTC, BaileyM96 requested changes
This README is looking great so far! I think there could be a change that can help out a new volunteer.

## Issue

1.  I think the Installation needs more to get the new volunteer set up correctly and get their user accounts going.

## Fix

1.Have the volunteer application in the contact section and tell the user to fill out the application so they can have google doc link to get correctly set up

2023-07-07 01:44 UTC, one-community commented
> ## Fix
> 1.Have the volunteer application in the contact section and tell the user to fill out the application so they can have google doc link to get correctly set up

What if we just linked to our website application, so they are always linking to the most current information

2023-07-07 03:28 UTC, BaileyM96 commented
> 

Yeah we can do that so we can keep track who is working on the repos and the google docs set up has really good documentation on getting set up

2023-07-08 20:33 UTC, HectorAgudelo approved these changes
looks good so far.

2023-07-24 17:04 UTC, eduvarjaor approved these changes
The readme file looks awesome!

2023-07-24 18:07 UTC, yurisokolovicz approved these changes
The README.md looks good. It contains everything we need to get in touch and start volunteering.

2023-07-28 20:40 UTC, Indujaks approved these changes
The Readme looks great!

2023-08-03 04:16 UTC, ThapeloMasasa approved these changes
The readme is well written and looks good

2023-08-05 01:47 UTC, merged