Leon fix bravo text in badge section of user profile
OneCommunityGlobal/HighestGoodNetworkApp pull request #925
Opened 2023-06-20 20:26 UTC by leonzh2k

# Description
- Currently, when viewing a user profile, the badge text was the same regardless of whether you are viewing your own profile or other people's profiles. For example it says “you’ve earned X badges” even when you are not looking at your own profile which doesn't make sense. 
- Currently, the logic for displaying the badge text does not take into account whether the number of badges earned is singular or plural. So if you've earned 1 badge, it says "you've earned 1 badges" which doesn't make sense.

## Main changes explained:
- Pass a new prop `isUserSelf` to the Badges component to determine whether the profile being viewed is your own or someone else's and add new logic to display the text accordingly
- Add new logic to display "badge" or "badges" based on how many badges the user has earned.

## How to test:
1. check into current branch via `git checkout -b leon_fix_bravo_text_in_badge_section origin/leon_fix_bravo_text_in_badge_section`
2. do `npm install` and `npm run start:local` to start the frontend
3. checkout the development branch on the backend, do `npm install`, `npm run build`, and `npm run start` to start the backend
4. login as any user role
5. Go to your own profile and verify it says "Bravo! You've earned..."
6. Go to somebody else's profile and verify it says "Bravo! This person has earned..."
7. Go to a user profile with a number of badges != 1 and verify it says "badges"
8. Go to a user profile with 1 badge and verify it says "badge"
9. Run Prettier on the changed files with `npx prettier --check ${path_to_file}` to confirm that they follow code style

## Screenshots or videos of changes:
Before (Assuming I am not logged in as user "AI test"): 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/1e3d1cde-0d86-4d22-829c-d30e0adafb7a)

After (Assuming I am not logged in as user "AI test"): 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/8f2c66c4-5cc4-49aa-be67-12e7ac754635)

2023-06-21 03:27 UTC, one-community commented
Is there a reason this has "do not review" on it Leon? 

Also, did you comment on the Doc with your times for this? I don't have it in the HGN as your task.

2023-06-21 03:33 UTC, leonzh2k commented
@one-community Yes, I did comment my times for it on the doc, and I remember that you commented that you added it as a task. The task should be in the HGN as I was able to log time towards it:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/c39a6eaf-a533-4a29-bcd1-adba295a21e6)

I labeled it as "do not review" as I was planning to write a unit test for it and so considered it not ready for review yet.

2023-06-21 04:33 UTC, one-community commented
My tasks tab wasn't refreshed, I see it now. Thank you! 

Thanks for the DNR explanation too!

2023-06-23 22:03 UTC, yufeiStella commented
It works as intended! 1 => 'badge', not 1 =>'badges'
<img width="780" alt="Screen Shot 2023-06-23 at 16 57 06" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/49901d32-c6a2-47a9-83b7-f86884a84a3a">
<img width="843" alt="Screen Shot 2023-06-23 at 16 57 49" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/57b54fce-7afc-44a4-b8c9-cae4b115463f">
<img width="798" alt="Screen Shot 2023-06-23 at 17 00 32" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/14dc4d72-d73e-465d-a826-791fee084101">

2023-06-24 19:19 UTC, jonathancarpena requested changes
@leonzh2k Good job! 👍 Everything works like you described!

I would suggest to update the text to say: 

- "You have no badges." 
- "This user has no badges."

I think saying Bravo! you have 0 badges isn't something someone should "Bravo" too. 😅

User w/ 0 badges
![925 (1)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/e493df87-68ea-495f-aeaf-bf01d055bf43)

User w/ more than 1 badge
![925 (2)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/c16e81eb-3782-4606-bf74-55dca441d161)

User w/ only 1 badge
![925 (3)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/9ba6ae59-64ca-4337-9cd3-596ed94b35d3)

2023-06-25 04:27 UTC, rachnapandya commented
I think it's just me. Any advice?
![badge](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/119a9d9e-2caa-4e7c-b9cf-af1059aaf109)

2023-06-26 01:25 UTC, one-community commented
> I would suggest to update the text to say:
> 
> * "You have no badges."
> * "This user has no badges."

Yes, please add this. Also, if just 1 badge, it shouldn't say "earned 1 badges" with an "s"

2023-06-26 01:27 UTC, one-community commented
> I think it's just me. Any advice?

Not sure what you are referring to here. Please make clearer your intent/question with your comments.

2023-06-26 22:25 UTC, leonzh2k commented
@jonathancarpena Thanks for the feedback, I agree and have made the suggested changes.

2023-06-26 22:33 UTC, leonzh2k commented
@rachnapandya I'm assuming the problem you're having is that the text is wrong when viewing another person's profile. Are you still getting this problem?

2023-06-27 00:42 UTC, jonathancarpena approved these changes
@leonzh2k Great job! No more Bravo to 0 badges. 👍 All the changes are working like you intended.

User with No Badges
![925 (1)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/ef6f6ae6-0a62-4d78-9430-0c4c1d5fda41)

Other user with No Badges
![925 (4)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/0f276d8e-d721-4501-bf6a-186540497ca7)


User with More than 1 Badge
![925 (2)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/9b5754fa-1ff8-4363-b269-f22ac32946fb)

User with 1 Badge
![925 (3)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/dc6d54d6-ccdf-40bc-a880-a380d3aedf3a)

2023-06-27 12:45 UTC, beblicarl submitted a review, later dismissed

2023-06-27 13:46 UTC, KurtisIvey submitted a review, later dismissed
Functions as intended
![pr925 works on other ppl account](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/6751ef52-10e7-4f01-aad7-bb0889737a5a)
![pr925 works on own profile](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/d30a2c0c-ef9d-4227-b7fc-5453d6b2a0ec)

Since this isn't exactly in the scope, I went ahead and approved.
May have found an additional bug though as the dashboard doesn't seem to be updating unless the user logs out and logs back in. 
![pr925 badges section dashboard fail](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/13f7249e-72f2-4f02-b3de-fb8b25245c88)

2023-06-28 11:48 UTC, Lucas-E commented
Thank you everyone! Moving this to final review!

2023-06-28 16:52 UTC, cvtqx approved these changes
Works well and finally I am not congratulated on having 0 badges :)

My account 0 badges:
<img width="577" alt="Screen Shot 2023-06-28 at 12 46 34 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/b42ef636-224c-4d3b-bab8-5b087b82b875">

My account 1 badge:
<img width="736" alt="Screen Shot 2023-06-28 at 12 38 10 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/acb9bea0-5fc3-47af-926f-01f21d72667a">

My account many badges:
<img width="577" alt="Screen Shot 2023-06-28 at 12 46 55 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/9b962d9a-4cb1-469b-85c9-4dbe29e52899">

Someone else's account 0 badges:

<img width="736" alt="Screen Shot 2023-06-28 at 12 40 06 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/64a35393-d5cc-48e3-a57a-baae505d0e83">

Someone else's account 1 badge:
<img width="736" alt="Screen Shot 2023-06-28 at 12 40 41 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/c0caf466-1782-44a3-9b7b-a553c72d117a">

Someone else's account many badges:

<img width="736" alt="Screen Shot 2023-06-28 at 12 39 36 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/400467a7-eaf9-43e5-8e96-677c8908cd5d">

2023-06-28 16:57 UTC, cvtqx commented
One suggestion: when we check someone else's account do we want to see the word Bravo there (i.e. Bravo! this person has earned 1 badge) ? Perhaps just a statement - this person has earned this many badges - would make more sense?

2023-06-28 23:26 UTC, one-community commented
> One suggestion: when we check someone else's account do we want to see the word Bravo there (i.e. Bravo! this person has earned 1 badge) ? Perhaps just a statement - this person has earned this many badges - would make more sense?

I'd like to keep this as it is. Our messages are intentionally informal to support a more friendly corporate culture.

2023-06-29 22:13 UTC, Aishwaryak01 reviewed
@leonzh2k  Went through the code files and have the below comments : 
1. Why is the file name Badges. test. jsx? Is this the correct naming convention? Where is this file used?
2. Can you add some comment lines in code files to make it more understandable?
The code logic in other files looks good to me.

2023-06-30 18:49 UTC, leonzh2k commented
@Aishwaryak01 
1. `Badges.test.jsx` is a test file, so it's not used in the application. The naming convention is just what Jest expects.
2. What specific lines of code would you recommend I comment on? Did you find any specific part to be confusing?

2023-06-30 21:27 UTC, Aishwaryak01 commented
> @Aishwaryak01
> 
> 1. `Badges.test.jsx` is a test file, so it's not used in the application. The naming convention is just what Jest expects.
> 2. What specific lines of code would you recommend I comment on? Did you find any specific part to be confusing?

@leonzh2k 
1. If it is a test file do we need to commit it with this change?
2. I want you to comment on the code that you added in all files as it is a standard practice for developers.I understood it but it helps to make it more readable for everyone.

2023-06-30 22:31 UTC, leonzh2k commented
@Aishwaryak01 Okay, I added some comments.

2023-07-02 02:56 UTC, Aishwaryak01 approved these changes
I can see that only one comment is added to the code. Otherwise, the code looks good to me logically. Hence approving it.

2023-07-02 16:22 UTC, merged