Jianjun - only owner can deactivate another owner
OneCommunityGlobal/HighestGoodNetworkApp pull request #926
Opened 2023-06-21 00:27 UTC by juneluo

# Description
**(PRIORITY HIGH) Make Admins so they can MAKE ACTIVATE inactive Owner accounts**
Admin login → User Management → Click gray dot
This should ONLY allow an Admin to make an Owner active (click gray dot), they should not be able to deactivate an Owner (click green dot)
This is needed in the event of some odd bug like the one above, or if an Owner somehow accidentally deactivated themselves or another Owner, then that other Owner could have an Admin reactivate them. 

## Main changes explained:
- Add a conditional check that any user that is not an owner (for example, admin) cannot deactivate an owner account.
- Anyone with 'changeUserStatus' permission (for example, admin) can activate an inactive user including an owner.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to dashboard→ Other links -> User Management -> Click gray dot (of an owner) ALERT-> Click green dot (of an owner) CAN CHANGE
5. go to an active owner user profile page -> Click green dot ALERT
6. go to an inactive owner user profile page -> Click gray dot CAN CHANGE

## Screenshots or videos of changes:
Login as an admin:
In the user management page:
<img width="886" alt="1" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/9314962/0ec4d910-95b8-412d-ae8f-fba4d9eb18ab">
<img width="906" alt="2" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/9314962/8774e2d8-a8a9-4814-abdc-3e7239b7781a">
In another user's profile page:
<img width="656" alt="3" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/9314962/6ec2b163-6e7e-477d-9364-3bb82c06f485">

2023-06-21 04:21 UTC, cone-7 commented on src/components/UserManagement/UserManagement.jsx
> +    if (user.role === 'Owner' && user.isActive && authRole !== 'Owner') {
Can this validation occur in another table/form?? maybe it's a good idea to create a function for this.

2023-06-21 09:27 UTC, Chuehleo approved these changes
Everything work as intended, great job!
![Screenshot 2023-06-21 022645](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/24fd5e3b-fc0b-484f-8730-0bb2e7d3e401)
![Screenshot 2023-06-21 022606](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/e8db7a68-2a18-42ae-b38a-eb7dcce12ca7)
![Screenshot 2023-06-21 022536](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/b4089da2-a71e-4032-ae67-9d554a252bfc)

2023-06-21 15:12 UTC, KurtisIvey submitted a review, later dismissed
Works as intended. Great job!

received alert when trying to deactivate active owner:
![pr926 works with active owner](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/87f15017-a422-4106-aa22-f8b3e546f16a)

was able to change status with inactive owner:
![pr926 works with inactive owner](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/a08ce72d-8d0f-416a-9470-f4c93c8f117b)

2023-06-21 19:34 UTC, jonathancarpena approved these changes
Good job @juneluo 👍 Everything is working like you intended. When I try to deactivate an active owner I get an alert. Also I was able to change the status of an inactive owner

![#926 (1)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/81583972-5099-4ae9-ba77-c52b3e771939)
![#926 (2)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/c717e83c-edf7-4324-91d0-fb4ff7c08a18)
![#926 (3)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/339d5542-795f-4e79-81ce-5f8b0359a7e8)
![#926 (4)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/0f9f2ea3-ac8b-4a43-88ec-78dd54f53b99)

2023-06-21 23:29 UTC, EdwinLauM requested changes
Works as intended! Good job! 

Admin on Active Owner Account:

<img width="1680" alt="Screen Shot 2023-06-21 at 7 21 49 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/03a648d3-7519-48e1-864f-7a1e137b3951">

Admin on Inactive Owner Account:

<img width="1680" alt="Screen Shot 2023-06-21 at 7 21 34 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/ce1e16ad-e86c-41a9-a729-3f68fc013dd3">

I do agree with @cone-7 suggestion. Since you're using the same validation check in the `UserManagement` and `UserProfile` components maybe we can move it into a separate function and import it?

2023-06-22 03:29 UTC, juneluo commented
@cone-7 @EdwinLauM Thanks for the suggestion. I can wrap it in a separate function as following:
```
const newValidateFunction = (user, authRole)=>{
    if (user.role === 'Owner' && user.isActive && authRole !== 'Owner') {
        alert('You are not authorized to deactivate an owner.');
        return true;
    }else{
        return false;
    }
```
and then I shall import the function in both UserManagement and UserProfile component file, pass the parameters to the function and check the value it returned. Take one as example:
```
import newValidateFunction from '../../utils/permissions';

onActiveInactiveClick = user => {
    ......
    if (newValidateFunction(user, authRole)){
        return;
    }
    ......
}
```
I am not sure if it is better to make it this way since the validation itself is simple and intuitive. I will update it if you think that will be helpful to improve the code readability. Or please let me know if there is a better way.

2023-06-22 17:53 UTC, cone-7 commented
@juneluo I agree with you that the validation itself is simple and intuitive, but having a function we can use it in different components/files.

And I think it would be better just to return a boolean value:

```
const newValidateFunction = (user, authRole)=> {
    return user.role === 'Owner' && user.isActive && authRole !== 'Owner';
}
```
and then

import newValidateFunction from '../../utils/permissions';

```
onActiveInactiveClick = user => {
    ......
    if (newValidateFunction(user, authRole)){
        alert('You are not authorized to deactivate an owner.');
        return;
    }
    ......
}
```

2023-06-22 23:08 UTC, yufeiStella commented
Hi @juneluo, it works perfectly! After spending some time figuring out how to deactivate the owner account itself, I find the admin can reactivate the owner account. Also, the admin cannot deactivate an active owner account.

<img width="974" alt="Screen Shot 2023-06-22 at 17 46 42" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/56edeb72-bc75-4cee-9efb-2e0406b82a36">
<img width="1003" alt="Screen Shot 2023-06-22 at 18 05 09" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/2f31c36f-f456-42c6-9ba5-15af310328a0">

2023-06-24 05:26 UTC, rachnapandya commented
Works as intended.
![owner](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/07b405c1-e526-4d14-bfb1-ce0ba0c14673)

2023-06-25 23:58 UTC, juneluo commented
@EdwinLauM Please check the update, thank you.

2023-06-26 03:37 UTC, EdwinLauM approved these changes
Works as intended! Good job! Thanks for addressing the suggestions @juneluo!

Activating an Owner Account: 

<img width="1678" alt="Screen Shot 2023-06-25 at 11 34 47 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/97d2ed3d-9584-49fa-84c5-c96c0c38c771">

Deactivating a Owner Account: 
<img width="1340" alt="Screen Shot 2023-06-25 at 11 32 26 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/a961e81d-f0bb-4586-9196-71e1857eb0e8">

2023-06-26 05:17 UTC, merged