Abdel deadline follow up tracking solution
OneCommunityGlobal/HighestGoodNetworkApp pull request #935
Opened 2023-06-23 01:41 UTC by abdel-lall

# Description
1.	#### $\textcolor{red}{\textsf{(PRIORITY HIGH) Jae:}}$  Create way for me to track people I’ve followed up with about deadlines 

-  On the Tasks tab, I’d like a little box I can click on and off. I’m thinking the best location is to the right of the time numbers below. This is because it is related to those numbers and I want it super easy to scroll the whole tasks list and see who needs a followup or not.
- It should be visible and usable by every class but Volunteers. Any class checking the box will change its appearance for all others that can see it. This is so everyone knows if a person has been followed up with yet.
- It should have mouseover text that says, “This box is used to track follow ups. Clicking it means you’ve checked in with a person that they are on track to meet their deadline.”
- I’d like the box to be Red outline with light pink filler when a person is at 50% of their task deadline, again at 75% of their task deadline, and again when they are at 90% of their task deadline. This is to make it clear that it needs to be checked/the person needs to be followed up with. Once checked, the box should change back to normal but with a check in it. 
- I’d like the box to reset/auto-clear the check within the box when a person reaches 75% and 90%, so the box is ready/needs to be checked again. This is so I can track when I’ve followed up with people and also know when/if my managers are following up with people.
- I’d like an “i” icon for information that explains all of the information above.
- I’d also like mouseover text that will be different for the box at each level 
      **A -**. 0-50%: Check this box once you’ve checked in for the first time with this team member to make sure they are clear on their task.
      **B -**. 0-50%: Check this box once you’ve checked in for the first time with this team member to make sure they are clear on their task.
      **C -**. Your team member’s task should be at least 75% complete! Check this box once you’ve confirmed they are on track to meet their deadline. Request additional time be added to their task if it is needed.
      **D -**. Your team member’s task should be almost complete! Check this box once you’ve confirmed they are on track to meet their deadline. Request additional time be added to their task if it is needed.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/1862b0c7-1064-4291-bfee-dc1cb8f05b48)

## Related PRS (if any):

- This frontend PR is related to the #XXX backend PR.

## Main changes explained:

- Update TeamMemberTask file Add handleCheckboxFollowUp and followUpMouseoverText
- Update TeamMemberTasks file Add handleFollowUp.
- Update TeamMemberTasks/task file Add setFollowUp and checkWhoNeedsFollowUp.
- Update TeamMemberTasks/reducer file Add SET_FOLLOWED_UP.

## How to test:

- check into the current branch.
- do `npm run start:local` to run this PR locally.
- Create a task and assign it to a user. 
- Test for the requirements in the description.

## Test:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/9866e33f-6de4-4c81-99e2-779ee6fd178b

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/0971f0cb-3a03-492e-9621-f6f0b08184fb

## Note:
To observe the changes on the checkbox after adding time to a user, do a hard refresh:
Windows/Linux: Ctrl + F5
Mac: Command + Shift + R

2023-06-23 16:47 UTC, cvtqx approved these changes, later dismissed
Checked this PR in Admin, manager and owner accounts. All display this functionality which seems to work as intended.

1. Info modal over i:

![info modal](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/90e3ed1a-ef49-4c3a-9f16-b84a80051499)

2. Task is 50% complete:

![50%complete](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/7bf7c1b7-5390-4892-a75b-b2ebdeb90aba)

3. Task is 75% complete:

![75%complete](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/52ea063c-40fc-4dc3-afcb-41f4f6c77dd8)

4. Task is 90% complete:
![90%complete](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/ddd875f2-e07b-4c96-b1a8-e9ad4d598938)

The checkbox, once checked, is reset to pink and unchecked when a new breakpoint is achieved. It is not reset until the 50%,  75% and 90% are achieved. 

We would need to fix the alignment in admin view in a separate PR perhaps:
![alignment](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/c1f4400a-8f05-48d6-8b3a-db9a3bc5d74b)

2023-06-23 23:48 UTC, mahamakhan submitted a review, later dismissed
Checked from admin and volunteer account. Looks fine. 


<img width="566" alt="Screenshot 2023-06-23 163958" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/def4fa71-eb89-4db0-bf72-b3e45442fc26">
<img width="481" alt="Screenshot 2023-06-23 164026" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/262ae708-0600-4ece-b33d-5398733e1891">
<img width="511" alt="Screenshot 2023-06-23 162625" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/52a2ff9a-3fe9-41f4-90d0-999028c61e1a">

2023-06-24 05:58 UTC, rachnapandya commented
The feature is working well.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/1b947e54-4205-4e26-8f52-88164eb16666)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/50e83cd0-ee81-4046-b974-08970259dfc0)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/4040d57a-113f-4c08-bfea-58f7d834c4be)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/f86116f3-4a8f-44bc-8056-de416a05677f)

2023-06-24 18:00 UTC, jonathancarpena requested changes
@abdel-lall I notice this issue after adding intangible time to a task. After switching the intangible time to tangible, the task progress would not update. I'm not sure if this was intended. 

Test Bug:
1. Log **Intangible Time** to task
2. Update the task from **Intangible** to **Tangible**
3. Check if progress was added after changing time to tangible

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/14873538-b73d-4139-9abd-38ff4261fbc6

2023-06-25 23:49 UTC, one-community commented
> @abdel-lall I notice this issue after adding intangible time to a task. After switching the intangible time to tangible, the task progress would not update. I'm not sure if this was intended.
> 
> Test Bug:
> 
> 1. Log **Intangible Time** to task
> 2. Update the task from **Intangible** to **Tangible**
> 3. Check if progress was added after changing time to tangible

Great catch! This is outside the scope of this PR, please post it to the Bugs Doc and comment on it so I can approve it.

2023-06-26 00:05 UTC, abdel-lall commented
@jonathancarpena Well spotted! However, this particular issue falls beyond the scope of the pull request.
![1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/3821c49d-9e3b-4704-a5a5-f110dcc0bf15)
![2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/6c072c67-e710-42bb-9a3b-8fc387200b21)
![3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/ec763cee-ee17-4886-b943-a1d344a06ea6)

2023-07-05 15:31 UTC, beblicarl commented
This functionality works as intended

![test-5](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/e0b82b2d-71b0-4d1c-93c8-f9a4916c5601)

![test-6](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/9a347fef-d7d3-4ef0-b326-e684770e9b49)

![test-7](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/7dea854d-6a15-4dc9-ad81-206269ca224f)

![test-8](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/7dd140ae-d282-45a4-8275-1d3c52df9873)

2023-07-07 17:11 UTC, xaanders approved these changes, later dismissed
I've tested the PR. Works as intended 

- icon explains the functionality 
<img width="947" alt="i" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/b4a75be9-ea92-4468-8cfa-8a48bf184a78">

- hover on the checkbox shows track follow up text, text depends on the task progress

- if progress less 50% checkbox remains unchecked(green). 
<img width="583" alt="before50" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/2f7ed53c-6c17-47ea-b267-b8173b04c72c">

- after achieving 50%, 75% and 90% it requires follow up(though checkbox gets unchecked if it was checked before the breakpoint) 
<img width="720" alt="breakpoints" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/c7965bb4-9e7c-4998-b2b3-0c972d12c419">

- if followed up then checkbox is checked until next breakpoint
<img width="594" alt="checked" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/7c2df83a-a57d-4bdc-ae72-c61112fe1bf1">


- stays checked when reach 100% and gets unchecked after reaching 75%
<img width="574" alt="100and75" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/60f6b6d3-11d6-46e6-9049-c2df42f38fda">

- volunteers see the progress without checkbox
<img width="594" alt="volunteer" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/80e759ce-5bb7-4c8e-9761-f2fa9967f3e0">

2023-07-07 22:54 UTC, igorrochadasilva commented
This functionality works as intended. = ) 

- icon explains the functionality
![info-modal-over](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/c026eec4-f54c-4125-9491-5c306b1e1362)

- Initial checkbox
![initial-checkbox](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/445323ea-3cc3-4861-9202-6a06cfdb2d23)

- Volunteer can't see the checkbox
![volunteer-cant-see-checkbox](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/6ff936a1-25d6-4965-b2d5-37480ff02fcc)


- The checkbox clicked 0%
![checkbox-checked-0%](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/76da8d42-8672-4ed9-bc29-f5d113285784)

- The checkbox after 50% progress
![after-50%-progress](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/567492dc-e15b-48ca-b833-088240800d87)

- The checkbox after 50%, when clicked turned green
![after-50%-clicked-became-green](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/66048d71-e6cb-43b8-a2f0-cb4652e50a3f)

- The checkbox after 75% progress
![after-75%-progress](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/25cc2fba-082b-40f1-ab68-880b18836fd4)

- The checkbox after 75%, when clicked turned green
![after-75%-clicked-became-green](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/d8726762-bf3b-4016-9267-8453a69bd11b)

- The checkbox after 90% progress
![after-90%-progress](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/dbcdf35c-6e70-4668-8bf2-233c463615cf)

- The checkbox after 90%, when clicked turned green
![after-90%-clicked-became-green](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/f8f1f0ee-e67c-4260-ae42-70fbec724e2c)

2023-07-15 06:47 UTC, ramyaram2092 reviewed
The functionality works as expected . 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/8cfa5d2f-c4b1-41ca-b70e-89daa22b8829)

2023-07-16 01:36 UTC, Jiangwei-shi commented
icon explains the functionality
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/d4ce63c4-67d4-4259-ad8d-906960ad83fd)
After finishing 50%
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/c9da444b-a1c0-4a3c-b9ab-c975bf4ed7be)
checked
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/d1dbff06-486f-4001-8ab5-1e7af37a8970)
After finishing 75%
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/870d4f7e-be9c-434f-a3ed-38d2306e8644)
checked
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/d08dfe83-212d-4b1e-b569-bcf6b88ce0a6)
After finishing 90%
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/4bc7aa8d-aa23-4c90-9808-b8c8c60865fc)
checked
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/528012de-c564-4089-bf91-fcabbc564306)

2023-07-21 08:32 UTC, DavidC0126 reviewed
Hi @abdel-lall, I tested the PR and did not encounter any issue, good work!

-  When the cursor is on  the "i" icon, it will show the explaination.
<img width="1677" alt="theIicon" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/43a2b68f-31c6-495b-b005-6a580554eb0a">

-  In the Initial state, the checked box is green and no check on it.
<img width="882" alt="InitialState" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/744e30c5-1919-43d2-8180-f4b9b3a4f768">


- The functionality works fine in 50%, more than 75%, and over 90% progresses.

<img width="882" alt="progresses_admin" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/dbef1242-5ad6-4e80-b2e5-58af97fea592">

- Volunteer users cannot see the checked box, but are able to see the progresses.

<img width="882" alt="volunteerUser" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/54aa3499-f070-4c72-98e5-b3fc0af9f296">

2023-07-21 18:18 UTC, iTvX commented
Checked both admin and owner accounts, and everything works as described. However, I'm experiencing significant lag, and sometimes nothing appears. In such cases, I have to use my mouse to hover over another icon, and then it will reset.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/c3cf0cdd-1ea0-4d84-8250-62b7403ac593

2023-07-30 00:50 UTC, zuhang2000 reviewed
Hi I test this PR by following your instructions on checking out both front-end and back-end branch. The overall functionality is working great. One thing is that I'm experiencing extreme high lag when doing this test(it's just that it took a really long time to load the dashboard and all those pop up message). Another thing is that the time can become negative if I edit and delete some of my time log of that task.

Here are my test details. Firstly, the "i" is showing correctly when I move mouse onto it.
<img width="1136" alt="Screen Shot 2023-07-29 at 5 02 07 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/52b62261-c189-4659-9fd6-4b5405562bae">

Then, I test all the cases, including when the task progress is below 50%, above 50% but lower than 75%, above 75% but lower than 90%, and at 95%. I check the box whenever it passes the required threshold. It turns out that it can work as expected. When reaching 75% and 90%, the checked box got cleared automatically. 

When I move my mouse onto the checkbox, the message also changed accordingly. The color is also changing according to the progress bar. 



<img width="839" alt="Screen Shot 2023-07-29 at 5 28 40 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/11ff9686-1bfa-4ffe-9619-6e6a29301892">
<img width="1168" alt="Screen Shot 2023-07-29 at 5 30 07 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/54a651d6-d910-4853-96fe-675a3299d065">
In these screenshots, you may see that the box gets automatically cleared when it reaches the threshold.
<img width="1173" alt="Screen Shot 2023-07-29 at 5 31 42 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/398cbaaf-9035-4a9a-9a50-51173047cd0c">
<img width="1171" alt="Screen Shot 2023-07-29 at 5 33 04 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/33e3d24b-1bf2-43b4-bf5d-26d1a0cae3d4">

However, I do notice that it's getting strange behaviors if I edit and delete my timelog. It can become negative number. In this case, I must submit more hours of time log in order to compensate this negative time. As you can see in the following screenshots. In order to do the test, I even have to submit a lot more hours. I can also see a lot of negative time records in the "Tasks" list. 
<img width="787" alt="Screen Shot 2023-07-29 at 5 24 13 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/290211c8-8053-4004-8dcf-8193ec827811">
<img width="796" alt="Screen Shot 2023-07-29 at 5 33 49 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/62fb6338-cd5f-4bf6-9869-b8954c2f5b08">

2023-08-03 23:25 UTC, ThapeloMasasa reviewed
works well as can be seen below.. I do not know why the X symbol is not there though

<img width="903" alt="Screenshot 2023-08-03 at 3 56 50 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/9d16db9d-bf1f-46d1-9385-cde43b72e957">


<img width="343" alt="Screenshot 2023-08-03 at 4 04 57 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/35a314a3-1cd0-428c-a706-bbf18c4b028c">
Tested the feature 
<img width="318" alt="Screenshot 2023-08-03 at 4 05 06 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/009dac67-2a85-4cac-b1fb-aa755d723539">


<img width="342" alt="Screenshot 2023-08-03 at 4 06 20 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/6605889a-b2a3-4395-8ae1-75e7b4dc240c">

<img width="339" alt="Screenshot 2023-08-03 at 4 12 36 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/a11a4b90-6045-4078-ad16-cff5f8ac6b6d">

2023-08-06 04:41 UTC, winghojackyli approved these changes
Hi @abdel-lall , I've tested the PR and it works great. The 50%, 75% and 90% checkpoints have been tested. Besides, I tried using volunteer and it cannot see the checkbox as intended. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/7354567b-9967-4d4f-b1b9-fc79f1793bd4

2023-08-16 22:29 UTC, veronicacheng2 approved these changes
Hi @abdel-lall, I have tested the PR. The functionality is good but the tasks container is a bit too small and some of the content cannot be shown (the 'i' icon). Other than that, the tracking function works perfectly.

### Green checkbox initially
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/36c51fcb-455b-41a5-becc-1ff4a8e8691b)

### Red checkbox when reaching over 50%
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/3612447d-0ada-49b0-bc8a-27e381898c8b)

### Checking the box turns it green
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/0700afa9-1593-4601-8586-a6622657b851)

### Red checkbox when reaching over 75%
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/9c5168f9-cb2d-49ec-919a-7002f9514239)

### Checking the box turns it green
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/29f57c99-6093-4548-af94-9a9e946160d5)

2023-08-22 22:56 UTC, yunshan111 submitted a review, later dismissed
Tested this PR, LTGM.

2023-08-23 04:03 UTC, one-community commented
Looking good everyone, keep those reviews and feedback coming. This one is super important!

2023-09-21 22:24 UTC, Shiwani99 requested changes
Hi,
I tried to test your PR but when I start the frontend and backend it crashes after login. I'm attaching the screenshot of what is happening in my end. 

<img width="1429" alt="Screenshot 2023-09-21 at 6 18 10 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/f9000087-6118-445d-863b-da03d8d3df6c">

2023-09-28 21:12 UTC, Shubhu0 commented
Tested this PR. Feature working as intended. Can see the icons and all Info icon displays the information as well! And checking the box works but is slow and takes about 2-4 seconds each time to register, but does work and checking the box makes it turn green.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/2076b25b-cb05-40bf-ab48-e2da16e71e4f)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/000ac732-ed22-414d-8568-13ecfd177306)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/e17e9c73-0c2a-4d1d-9096-ea0df25286a4)

2023-10-11 22:02 UTC, StrawberryCalpico requested changes
Hi I tested your PR, however the page will freeze and crash.
<img width="1137" alt="Screenshot 2023-10-11 at 6 02 38 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/4d90ec9a-ba2e-4a33-b7c6-f28130c3afe9">

2023-10-28 06:43 UTC, malikjahanzaib requested changes
Hi @abdel-lall, I tried running this PR locally but it seems to be unresponsive. I am getting a lot of console and BE server errors as well. Refer to my screenshots. Thank you.

Screenshots:

<img width="960" alt="Screenshot 2023-10-27 234037" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/8621d65a-8f94-4500-adf0-bdfd16766e3c">


<img width="960" alt="Screenshot 2023-10-27 233441" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/10042941-149d-4259-b50b-7821586b3f19">

<img width="960" alt="Screenshot 2023-10-27 233503" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/acfd62d6-0905-4528-ad73-c7478960f3a8">

2023-11-17 18:53 UTC, Changhao3220K reviewed
Hi @abdel-lall 
all the functions seems work fine for me on local environment using admin and volunteer.
<img width="1357" alt="Screenshot 2023-11-17 at 1 35 44 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104778270/328e606d-6cd1-45ff-8494-6e00ad6d0c94">
and the infor icon works fine
<img width="1021" alt="Screenshot 2023-11-17 at 1 49 29 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104778270/8411b93c-e9b5-47b3-80fd-7ded46472292">
One thing I am not sure is that when creating new user it will throw me error and stop me from creating new users, is this an issue or should I use the dev site to create user?
<img width="1297" alt="Screenshot 2023-11-17 at 1 03 59 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104778270/a0139c70-ca04-4a03-afce-90c0ae3cc32f">

2023-11-17 22:21 UTC, Shuhua-L requested changes
Hi @abdel-lall, I was able to create a task and assign it to myself. However, when I logged in as a user who had been assigned a task, consistent errors popped up when loading the task, both on the Dashboard page and the TimeLog page. Could you provide some guidance here?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/f339bda9-50de-4ffa-b49c-ca27dec3b71a

2023-11-18 16:08 UTC, ptrpengdev commented
Hi @abdel-lall, I was able to test some of the functionalities but failed to test with the volunteer role since the Task API failed. 

Env Setup:
Frontend Branch: A[bdel_deadline_follow_up_tracking_solution](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/935)
Backend Branch:  [Abdel_deadline_follow_up_tracking_solution](https://github.com/OneCommunityGlobal/hgnrest/pull/419)

Issue:
Failed to load tasks with the volunteer role.

Step To Reproduce:
Log in with the **volunteer** account: 
  - testtesterpp@gmail.com; password: Hgn@dev2023

Go to Dashboard -> Tasks tab 
   - Team Member Tasks list never finish rendering
   - **Failed API endpoint** with **error** QueryExceededMemoryLimitNoDiskUseAllowed: http://localhost:4500/api/user/6556211f46f10d58d8d9b567/teams/tasks )

Screenshot:
<img width="1019" alt="failedToLoadTasksVolunteer" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/26ae4f5d-4f77-467a-b5d3-8a05a3aba4fa">

<hr/>
For the Admin role, I was able to test the functionalities:

Icon tooltip **(Sucess)**
Check and uncheck the box **(Sucess)**

Screenshot:
<img width="658" alt="buttonCheckedAdmin" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/8a283095-7755-446c-a3fd-407f38d0fc57">
<img width="760" alt="iIconWorksAdmin" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/beecabcc-1553-4910-a94d-294f15a4275d">

2023-11-18 21:34 UTC, palakgosalia commented
Hey, I tried testing your PR but the tasks tab wouldn't load. Attached is the screenshot of the error. Hope it helps. Thank you

Env Setup:
Frontend Branch: Ahttps://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/935
Backend Branch: https://github.com/OneCommunityGlobal/hgnrest/pull/419

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/4ad4fb98-34a1-4a82-93f5-5c8bd847d523)

2023-11-18 22:41 UTC, kavya151 commented
Hi @abdel-lall, I tried to run this PR on my computer locally, and whenever I open the website, the page becomes unresponsive. I've made several attempts, but I consistently encounter the same issue with the webpage freezing.  I didn't face similar problems with other PRs
<img width="1440" alt="Screenshot 2023-11-18 at 3 40 25 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/92babdc0-71f6-4300-8a54-bba8deb3b964">

2023-12-01 23:25 UTC, sucheta90 approved these changes, later dismissed
@abdel-lall Tested in local as Admin, looks like the app works as intended. Well done.
![PR#935_PR#419](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/97bc0639-f494-43f6-946f-a156594e98da)

2023-12-22 07:15 UTC, Alforoan requested changes
All the functionalities seem to work on my end except for volunteer not being able to manipulate the checkbox. As you can see, as a volunteer, I was able to click on the checkbox. Also the checkmark doesn't seem to be right in the center.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/1041023e-1ef2-4a47-aff5-90cf3982e7c1

2023-12-23 06:42 UTC, abdel-lall commented
@Alforoan Hey, I've fixed the issues. When you have a moment, could you please test it again

2023-12-31 01:56 UTC, Alforoan requested changes
I keep getting infinite loading error for my tasks and am unable to see any of my tasks.

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/81e9ffdb-8063-4808-9ed2-2fe84a57091c)

2024-01-01 06:12 UTC, one-community commented
> I keep getting infinite loading error for my tasks and am unable to see any of my tasks.

Thank you for your review. This is not related to this PR, it's something else. See the coding problems channel.

2024-01-13 22:29 UTC, Haoxiang310 commented
I've tested your PR with owner role. I created a new project and assigned a new user to this project. The page of assigning user to the project looks wierd as after I searched and added the new user, the search result disappear after a few second and I cannot delete the user that I just assigned. Also, after entering the WBS page, I cannot see the user I just assigned, thus cannot create a new task. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/135764868/9a3564a2-e2a1-4e81-8c25-9c3142291157

By the way, could you please include the process of creating a task into the PR? Thank you!

2024-01-15 04:59 UTC, one-community commented
> I've tested your PR with owner role. I created a new project and assigned a new user to this project. The page of assigning user to the project looks wierd as after I searched and added the new user, the search result disappear after a few second and I cannot delete the user that I just assigned. Also, after entering the WBS page, I cannot see the user I just assigned, thus cannot create a new task.
> 
>  PR7-.935.mov 
> By the way, could you please include the process of creating a task into the PR? Thank you!

Excellent find, please log this as a new bug on the bugs doc and comment on it for my review.

2024-01-15 05:00 UTC, one-community commented
I also added how to input a task to the description here

2024-01-16 01:15 UTC, pshereen requested changes
After switching to the branch, "Abdel_deadline_follow_up_tracking_solution", tasks are not loading both in the admin dashboard and volunteer dashboard.
<img width="504" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/35d10e5c-070a-44f2-a0bb-4f636b801a51">

But the tasks are loading in the dashboard if I switch to development branch.
<img width="519" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/a0c5afbf-c9c2-42ea-9863-b4d512917f72">

2024-01-19 06:05 UTC, pshereen reviewed
Tasks are not loading in the dashboard.

2024-01-20 02:21 UTC, yuhuimin1996 commented
Hi, I've tested this PR with my owner role, and I met the same problems as @Haoxiang310. After I created a new project and add a volunteer user into it, the user suddenly disappear. And when I click the WBS and try to add assign task, I can't find any buttons or anything like you show in your instructions to create a task. 
Please see more details in the video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108281570/bbec9a48-06c2-4e69-9fbb-c8d6a118646a

2024-01-20 07:20 UTC, Sophie-lei requested changes
I just tested this FE and #419 BE. I met the problem. After I logged in owner role, I could not find other users in the Team Member Tasks. Thus, I can not assign a task to a user. and the console has shown the error as below. It might related to problems in BE #419. 
<img width="1439" alt="Screenshot 2024-01-20 at 15 03 20" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/b032ef7d-ecc4-408a-a9d0-87fdb74fbfcd">

2024-01-21 06:24 UTC, galgalinidhi commented
The Tasks don't load for me either. I cleared the browser data and logged in/out a couple of times but the problem persists. 

<img width="1436" alt="Screenshot 2024-01-20 at 10 22 51 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/e2309b95-60df-440e-b1a5-b95e092b79e5">

2024-01-22 20:41 UTC, X1aoZhang99 requested changes
Hi Abdel,

I'm also experiencing difficulties with loading the tasks.

![Screenshot 2024-01-22 at 15 37 30](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/92f9260a-bc3a-4a10-b4fa-460d99ff8b85)

2024-01-23 03:34 UTC, Renanluizssx reviewed
Hi @abdel-lall, i tested your application i noticed some errors, when i checked in some box, it didn't checked, but some of boxes are checked and the message was showed to me very well.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/5df6408e-bda4-4269-af0a-fb76f3cc9eb5

2024-01-23 03:34 UTC, Renanluizssx commented on src/components/TeamMemberTasks/style.css
> +  /* margin-right: 5px; */
you could delete this comment

2024-02-08 22:31 UTC, SRamen1999 reviewed
After testing this PR with the BE #419 I'm experiencing difficulties with loading the tasks. I also tested this PR with the current development BE and the task seem to load properly. I think something might be wrong with the BE #419

<img width="1722" alt="Screen Shot 2024-02-08 at 5 29 20 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/d52f2127-3643-45fb-aa67-a07998b45102">

2024-02-09 19:56 UTC, SaiDeepak-NEU reviewed
Hello Abdel,

I have tested the changes like mentioned in the PR but din't get the intented results, I don't know if I am doing something wrong or not but here are my findings.
1. I logged in as an admin and navigated to projects and then to wbs of a project and selected a wbs and added a task and assigned a volunteer to that task.
2.  Then I logged in as that volunteer but  in the tasks tab of the dashboard I am not able to see any team member names. The part is not loading at all. I see a blank white space. I tried different things, adding a new task, or editing an already existing task  with more than 3 members assigned to it, but nothing worked. Take a look at the ss of my page
![Screenshot (76)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114311909/e4f51d9c-2d7b-4d37-a560-87998492a3be)
Please take a look or suggest if I am doing anything wrong in here!
Thank you

2024-02-14 20:51 UTC, XiaohanMeng reviewed
Hi Abdel, I tested with my Owner and Volunteer account, the same problem appears as @yuhuimin1996  mentioned. There's no button after I create a new task and try to assign it. Also, in the Owner role, the leaderboard and team member tasks don't show member names, which prevents me from following the guidance by clicking the checkbox. Please see them in the video.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/ad6f63eb-aa3b-4925-97f9-117c7865f68c

2024-02-18 00:54 UTC, brandta-1 reviewed
# Review
Successfully created a new task for a user in a project as an Admin. When returning to that user's dashboard, the tasks could not load. The error is pictured below, and was a result of the API route ```http://localhost:4500/api/user/65d0f8a1cf23bb6228fa9d32/teams/tasks``` which was called in ```src/actions/task.js```. See [backend review](https://github.com/OneCommunityGlobal/HGNRest/pull/419#pullrequestreview-1887059088) for details on server side.

# Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/ee16d8d0-ea59-41d1-8421-250b89312d10

![01_task_in_mongoDB](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/efede1d5-6794-47a6-ac0c-6ed11fae3659)

![02_dashboard_task_error](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/e6152a8d-e60d-4a7b-9ac4-200683d67ea6)

2024-02-18 04:08 UTC, nnamdixobi commented
Everything seems to be working okay except for the fact that I was not able to add a user to an existing task like specified in your instructions on how to test

2024-02-27 00:40 UTC, skaush21 reviewed
Could not check task feature do to Team members Task not loading.
* logged in using owner account
* waited for page to load, Team members tasks did not load
* console has errors 
* took a look at the code, was unable to determine what was causing the issue. 
<img width="902" alt="task members not loading" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/4023fdae-3b32-4430-af65-407e66a5840c">

<img width="761" alt="console errors" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/c3962d96-46b0-4b15-9d8d-7cc326833069">

2024-02-28 07:19 UTC, ClemarNunes reviewed
The dashboard does not return tasks.

![foi](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/115e8fad-f42b-4700-b5b7-87a44aed55bf)

2024-03-01 15:58 UTC, MALAV1308 requested changes
Hello , I have tested your PR as per your description. I have created task and assign to the team member but it does not appear in admin account. Something is wrong there from the backend. Need to address this before merging.
![#935](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61341363/1bd91c32-2b56-4094-afe3-505d0edfc464)

2024-03-25 22:39 UTC, hetvi11110 requested changes
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/6183a65e-f74e-4c75-b40d-ce74c8ac098d

2024-03-30 03:06 UTC, abdel-lall commented
@hetvi11110 the 404 error suggests that the route to api/followup does not exist. It's probably because the backend was not built prior to testing. please make sure to run `npm run build` in the backend after switching to the branch

2024-04-01 17:35 UTC, hetvi11110 approved these changes, later dismissed
@abdel-lall  I have reviewed it again and, it is working fine. Good work!

2024-04-04 02:26 UTC, abdel-lall commented
@hetvi11110 The checkbox doesn't turn red when it's unchecked. Instead, it turns red when users need a follow-up.

![Screenshot 2024-04-03 212145](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/80419297-2fc0-4a1c-8845-421fc19f8150)

2024-04-04 05:48 UTC, Shiwani99 submitted a review, later dismissed
Hi,
I reviewed your PR again. it works as expected. I tested for task at 50%, 75%, 90% deadline and the box changed to a different color when these times were recorded. When I checked on the box, it turned to green color. Tooltip also works fine. Great work!

before ticking on the box:
<img width="724" alt="Screenshot 2024-04-04 at 1 27 05 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/f456a8f8-51c9-4031-b5c7-7aa9cfe90897">

after ticking on the box:
<img width="711" alt="Screenshot 2024-04-04 at 1 27 57 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/8a730d8f-213f-4f3f-965c-439f01d59860">

2024-04-04 20:03 UTC, kylepham requested changes
PR works as intended. 50%, 75%, and 90% progress breakpoints did trigger the checkbox to be unchecked and displayed in red color. 
![Screenshot 2024-04-04 at 2 48 26 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/21591d02-6c68-48f6-ad08-fdd74e937f91)
![Screenshot 2024-04-04 at 2 51 21 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/86548a75-0e6e-4eb2-bdea-6b68635aaa5e)
![Screenshot 2024-04-04 at 2 53 45 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/5cdecad8-3b90-41e7-be31-3000395d265b)
![Screenshot 2024-04-04 at 2 56 13 PM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/bf41fdb1-b519-4a03-800e-8ce0531d2302)

2024-04-06 01:20 UTC, abdel-lall commented
@kylepham Thank you for the feedback! I've incorporated your suggestion please check it out when you get a chance.

2024-04-07 19:53 UTC, kylepham submitted a review, later dismissed
Changes look good to me. Nice work 😄 

<img width="681" alt="Screenshot 2024-04-07 at 3 05 13 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/7ad9c692-221d-44b1-ab12-3ca8f69a38f6">

2024-04-09 15:44 UTC, ptrpengdev commented
Hi @abdel-lall

I tested the latest code in this PR. All cases passed except the case - uncheck task with progress > 75% and checkbox should turn red.

<img width="1446" alt="PR_935_Review3" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/1f36952f-094f-4796-a570-9d7502ccc38b">

In the video, I said 50% but I meant > 75%.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/c554b0e3-6bed-4c19-9ad1-580069fa9a80

2024-04-10 19:42 UTC, MQChen211 commented
Hi, I tested your PR with the volunteer, admin, and mentor accounts, and it works as intended.

<img width="1231" alt="截屏2024-04-10 15 40 21" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/0ae63d5a-0e33-4a53-9ade-71642be2338a">
<img width="1233" alt="截屏2024-04-10 15 39 09" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/7c8a4e88-5963-468d-b000-cdfc037d84aa">
<img width="1227" alt="截屏2024-04-10 15 35 48" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40895011/c5ca986c-feb3-4d17-8752-deb2d038003c">

2024-04-11 22:51 UTC, abdel-lall commented
Hi @ptrpengdev When a task is assigned to multiple users, the checkbox should turn red for all of them once any of them adds enough tangible time to hit one of the thresholds (50%,75%,90%). That means we need to follow up with all the users working on the task.
I tested it again, and it's working fine for me. Just make sure you hit one of the thresholds when adding time. Thanks!
at 75% and 90%
![Screenshot 2024-04-11 173312](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/076e5eca-ee28-44da-8a5c-1cb78f79786a)

![Screenshot 2024-04-11 173627](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/da60fea2-6a1e-4b6e-89c6-e0fe48caa685)

Please test it again when you get a chance. Thank you.

2024-04-20 06:40 UTC, one-community commented
Thank you all, merging!

2024-04-20 06:40 UTC, merged