Add seeSummaryIndicator and seeVisibilityIcon permissions to both rol…
OneCommunityGlobal/HighestGoodNetworkApp pull request #982
Opened 2023-07-08 21:35 UTC by suigunfjc

# Description
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94319381/af4fda89-02d3-4d9b-a662-32344c3268a9)

This PR creates the permissions for seeing weekly summary indicator #880 and visibility icon #859. Now owner can assign these two permissions to user or role to let them view the indicators and icons.

## Main changes explained:
- Create two permissions in `RolePermissions.jsx` and `UserRoleTab.jsx` for both role permissions and user permissions list.
- Replace boolean 'isAdmin' with `hasSummaryIndicatorPermission` and `hasVisibilityIconPermission` in `Leaderboard.jsx`

## How to test:
1. check into current branch
2. log in as owner user (if you don't have one, use my account first and create your own. jinchaoowner@gmail.com password:Ff12345678)
3. Other links->permissions management -> any role. Check if there are two new permissions at the bottom of the role permission list
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94319381/c21bd4e1-682d-4f5e-8154-21d003305368)
4. Assign/unassign these permissions seperately to different roles, check if they are working as intended(don't forget to click save after you make changes):
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94319381/9c2a5e81-ef92-45d2-90cb-6d13729a131d)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94319381/c3331cc1-4337-4f28-aee6-b42904b941c0)
5. Unassign permissions to all roles, then go to Other links->permissions management -> Manage user permissions, check if there are new permissions at the bottom of the permission list.
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94319381/7738a281-4fdd-4202-868e-31090a650830)
6. Assign permissions to one user and log in as that user to check if it works as expected.

## Note:
After changing the permission on roles, it may take more time to reload the page since it changes the `state` of the page.

2023-07-10 00:51 UTC, tdkent submitted a review, later dismissed
Local testing confirms

- Selectable options `See Summary Indicator` and `See Visibility Icon` have been added as the last items of the **Manage User Permissions** form.
- Activating these options adds corresponding icon to the applicable users in the **Leaderboards** list on the Dashboard.
- Icons are visible to all roles when their permissions are active (could not confirm visibility icon for Volunteer role)

Nice work!

Testing Video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/3aafafd3-d659-460c-bdae-1aa24aa9a7a7

2023-07-10 04:41 UTC, luisarevalo21 commented
Hello [suigunfjc](https://github.com/suigunfjc)

I reviewed you PR and found the following:

- Was able to view the new permission at the bottom via my own owner account
- Was able to toggle the permissions and and assign it to each of the roles in the system
- Provided the permission to both Admin and Volunteers accounts.
- Logged into the Admin account and can view each of the icons for weekly summary submission and visibility icon.
- Logged into Volunteer account, however, couldn't retrieve the dashboard. Unsure if that is part of the volunteers permissions. 
- I also removed the permission from both the role and the account and was reverted back to normal.

Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/db99d5e9-b7ed-4052-ace3-58c6141b77a4

<img width="1705" alt="Screenshot 2023-07-09 at 9 36 51 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/5618ec78-a191-4802-a33d-888b67d010b4">

2023-07-10 05:29 UTC, AaronPersaud submitted a review, later dismissed
Good evening, I've tested it and it looks good!

<b>Before adding permissions </b>

![before](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/d2c60ea8-65f7-4da8-b188-b2c551da5e72)

<b> Adding permissions and logging back in</b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/e003b780-6303-4691-b7d7-d49e663d81ee

- verified two new permissions appear at the bottom of permissions list
- applying permissions shows corresponding icon on leaderboard

2023-07-11 23:56 UTC, freecode23 commented
Works smoothly. Tested for with and without those two permissions for : admin, volunteer, mentor, manager, and core team roles

2023-07-12 00:28 UTC, BaileyM96 submitted a review, later dismissed
Good evening @suigunfjc I tested your changes and everything works fine.

## Video Walkthrough

[Manage Permissions.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/221dec8a-dbe4-49b7-9e3d-08fa148fb07b)

2023-07-12 10:32 UTC, beblicarl commented
I can confirm that this functionality works and the code looks good 

[screencast-hgnapplication_react_beta.surge.sh-2023.07.12-10_30_24.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/fe1b47d7-ede3-465d-ad62-c93dd2c2ffd2)

2023-07-12 10:33 UTC, beblicarl submitted a review, later dismissed

2023-07-13 08:09 UTC, Jiangwei-shi commented
two new permissions appear at the bottom of the permissions list: yes
applying permissions shows the corresponding icon on the leaderboard: yes
works as indeed. good job!

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/43604039-2063-4fc0-b78c-828edaedae2b)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/3171165b-78d9-40a2-96d9-b2c8eec0f8af)

2023-07-14 02:01 UTC, freecode23 submitted a review, later dismissed

2023-07-14 06:34 UTC, iTvX requested changes
The code looks good, but on my side, it doesn't work at all.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/8d85fb33-f4c2-43da-ab46-93d9c2c8fb68

I followed the instructions, created an owner account first, and then used that owner account to change the permissions of my other account. However, after switching to that account, I couldn't see any icon indicating that I have those two permissions.

Next, I switched back to the owner account and checked my test account again. I could see that the permissions had already been added to my test account.

Finally, I tried changing my browser, but the permissions icon still didn't appear.

2023-07-14 18:35 UTC, bienzguoa commented
Good job! It works as intended! 
For owners:
<img width="745" alt="Screenshot 2023-07-15 at 2 25 40 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/f34d7c57-af66-4d6f-93d7-074f237ec030">
<img width="636" alt="Screenshot 2023-07-15 at 2 30 22 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/c94709c8-2d79-459b-a24e-d8bc07c69039">
delete these two permissions:
<img width="632" alt="Screenshot 2023-07-15 at 2 31 00 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/6a1f077b-2780-4d16-b06b-f9332c3f8724">
For admins:
<img width="812" alt="Screenshot 2023-07-15 at 2 32 33 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/ea5545c8-2223-49de-9908-f3ee84bc68c6">
<img width="639" alt="Screenshot 2023-07-15 at 2 32 59 AM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/8b05ee0d-e410-44ef-85c9-0cb21950fd54">

2023-07-14 18:36 UTC, bienzguoa submitted a review, later dismissed
Code looks clear and workable.

2023-07-15 01:24 UTC, one-community commented
Needs branch conflicts fixed and the change request addressed and we can move this to final review.

2023-07-15 01:27 UTC, one-community commented
> The code looks good, but on my side, it doesn't work at all.

This video is blank... just need the branch conflicts resolved and we'll move to final review.

2023-07-15 01:36 UTC, iTvX commented
> > The code looks good, but on my side, it doesn't work at all.
> 
> This video is blank... just need the branch conflicts resolved and we'll move to final review.

On my side, the video is fine though. Could you please download it? I think it might be h265 or others issue. I will change record tool though.

2023-07-15 01:48 UTC, iTvX approved these changes

2023-07-15 19:36 UTC, iTvX commented on src/components/LeaderBoard/Leaderboard.jsx
> +                    hasSummaryIndicatorPermission && item.hasSummary &&
the variables hasSummaryIndicatorPermission and hasVisibilityIconPermission are used multiple times. To improve code readability and maintainability, I suggest considering grouping the definitions and uses of these variables together or using more descriptive variable names.

2023-07-18 03:17 UTC, Lucas-E commented
@suigunfjc Great job! Please resolve the conflicts so I can mot this PR to final review! Please DM me on Slack when you do it!

2023-07-19 15:24 UTC, xaanders submitted a review, later dismissed
Hi! You've done good job. Everything works with manager, volunteer and admin users
![1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/afc33234-e1e6-4121-bba4-ab2d9f7df1dc)

- Manager:
![2](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/47588a99-7dda-4053-b60f-b4af17e29926)
![3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/960110d3-fb3c-4e3a-8dd2-701b1cefb7b0)

- With admin user:
![4](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/9b0d0b7b-b43d-47a4-b2ec-3112c9393d5c)
![4 1](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/03b15444-2d5a-4306-a77d-fc55b0133301)

- And volunteer:
![5](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/a270e23a-2b93-4372-ac9b-2c6783225cc1)

2023-07-24 17:52 UTC, eduvarjaor submitted a review, later dismissed
Everything working as intended. Great job!

2023-07-24 19:52 UTC, Shreyj14 commented
the PR works as intended. I was able to see the visibility icon when given the permission

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/5c55a047-8334-4282-877f-c68ecfcfee96

2023-07-24 19:52 UTC, Shreyj14 submitted a review, later dismissed

2023-07-25 18:35 UTC, EdwinLauM approved these changes
Hey Jinchao! Changes work as intended! Good job! Please resolve branch conflicts as well

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/78256c9f-71f3-4c62-9c06-9c8acc78c29e

2023-07-25 18:46 UTC, yurisokolovicz submitted a review, later dismissed
Hi @suigunfjc,

I have reviewed the PR, and it does what was intended. Using the owner account, I was able to see the two new permissions at the bottom of the "Manage User Permissions" page. Subsequently, when I logged in as an ADM account without these two permissions, their respective icons did not appear. Finally, after logging in again with the owner account and setting the "See Summary Indicator" and "See Visibility Icon" for my admin account, I was able to see these icons as an administrator.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/5afd7da7-e6c1-42d5-947e-2cbb5e2687c7

2023-07-28 19:36 UTC, Indujaks approved these changes
Tested changes, works as expected, can add both permissions!
<img width="937" alt="Screenshot 2023-07-28 at 12 35 11 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/11251850/eed0c245-b872-4bcb-9fa2-455366b20f10">

2023-07-29 15:59 UTC, one-community commented
Thank you all, will merge as soon as branch conflicts are resolved.

2023-08-05 20:02 UTC, suigunfjc commented
@one-community conflicts resolved

2023-08-07 00:13 UTC, merged