Leo Add ability to create a team from the “Add Team” option of User Management
OneCommunityGlobal/HighestGoodNetworkApp pull request #997
Opened 2023-07-12 09:04 UTC by Chuehleo

# Description
![Screenshot 2023-07-12 001931](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/df43efea-6405-4641-b02f-5e96eaed2101)
…
## Related PRS (if any):
This frontend PR is related to [#453](https://github.com/OneCommunityGlobal/HGNRest/pull/453) backend PR
…

## Main changes explained:
- Update AddTeamPopup.jsx for including new "create new team" button
- Able to create a new team in the add team popup
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. Admin/Owner Login → Other Links → User Management → Create New User → Assign Team 
5. Check if the create new team button is able to create a new team and add team immediately

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/78fb1346-b78d-406d-b387-56e77b42e5ec

## Note:
Include the information the reviewers need to know.

2023-07-12 12:35 UTC, beblicarl submitted a review, later dismissed

2023-07-12 23:06 UTC, tdkent requested changes, later dismissed
Local testing of the PR branch confirms 

- a **Create New Team** input has been added to the **Add Team** popup form in User Management > Create New User.
- using the input successfully creates a new team, which is added to the Teams list.
- the new user can subsequently be added to the team in the same **Add Team** form.

Issues encountered which may be worth addressing:

- the **Create New Team** functionality does not appear to have been added to the Permissions Management page, though as noted in the description this may require a separate PR to implement.
- The **Add Team** form styles might be updated to make the "add team" and "create team" functions easier to differentiate (ie divide the form into separate sections with "Add To Team" and "Create New Team" headers).
- Adding a new team is confirmed via an alert that must be manually cleared by the user. This might be improved with a toast alert or text alert that appears in the form itself.
- The **Add Team** form styling becomes strange between 768-992px screen widths (see below).


<img width="575" alt="997-add-team" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/82e52e32-72bb-458c-8f94-65c2707b069f">

Testing Video:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/03d6b2e8-fcd2-4bce-9557-735e7999bfc8

2023-07-13 01:09 UTC, AnishPandita commented
Hi @Chuehleo I tested the PR and although the main functionality works well. There was a issue regarding duplicate name entries. Also I agree with @tdkent suggestion about making the add team success popup a toast or alert. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/72215468-db5a-487d-8915-a5d80639491c

Here you can add same name again creating duplicate entries for same teams.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/86259f56-d28d-4be9-ba22-90c4971d9cb4

2023-07-13 01:11 UTC, BaileyM96 requested changes
Hello @Chuehleo I tested your Add Team Modal and everything works great!

## Issues

The only issue/question I have is that when on "Add Team" modal the confirm input field is kind of confusing I was not sure what I was supposed to do with that for a few seconds. Maybe we can make it where the confirm button is just located next to the cancel button.

## Screenshots
After creating the team for the user
<img width="1665" alt="PR #997 Add Team to creating user" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/ad6391b4-2273-47b9-8d9e-f50f0a0fad45">

The UI issue
<img width="804" alt="PR #997 Issue" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/eae5c144-7b7f-4f9b-abd1-a83c5888de03">

2023-07-13 05:33 UTC, iTvX commented
Work as described.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/a68e6667-225c-4948-974d-97a3f6c9b7e0

 duplicate name entries have some issue like others said. I also have one more suggestion, When I first entered this interface, my initial instinct was to type a team name into the first line. However, it prompted me with an error message that read, "Hey, You need to pick a team first!". I believe this error message isn't suitable. In my opinion, the correct error message should be, "This team isn't found, you need to create a team first."

2023-07-13 05:36 UTC, iTvX requested changes
Work as described.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/24f45cde-0600-4b49-80c0-cf17d8457349



However, duplicate name entries have some issue like others said.

I also have one more suggestion, When I first entered this interface, my initial instinct was to type a team name into the first line. However, it prompted me with an error message that read, "Hey, You need to pick a team first!". I believe this error message isn't suitable. In my opinion, the correct error message should be, "This team isn't found, you need to create a team first."

2023-07-14 00:42 UTC, ramyaram2092 reviewed
Hello @Chuehleo : The functionality works as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/5d9966d8-21f8-4911-8c25-f5b61e095ea6

I have few suggestions for the UI though in addition to the suggestions given by others .

-  When the user clicks on the Assign Team , the Assign Team pop up shows up
Existing UI
![image]
(https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/1f75ef13-3f68-4057-9bd4-91b2ec60f8df)

Proposed UI : 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/4ba46910-1abe-43e7-9623-a7cbb2bdfc96)

Followed by the following UI based on the choices the user gives
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/1ca0a783-cb34-4cbd-9e32-da5b9eedefa6)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/5174bd70-a245-49b7-979e-766cd0a2006f)

2023-07-14 01:47 UTC, freecode23 commented
Agree with everyone on the UI issue. But otherwise the code works fine.
I tried logging in as user with the team assigned and it works.

For the UI, I'm thinking of this:
<img width="919" alt="Screenshot 2023-07-13 at 9 44 35 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67333705/e1294226-dfe2-420d-b6a8-37bac99c259b">

but this would mean that we need to add the logic in the backend if team does not exist yet, then create it before assigning

2023-07-14 04:32 UTC, luisarevalo21 requested changes
Hello @Chuehleo,

I tested your PR and works as intended great job! 

As others have pointed out theres a few UI change that can make the app much better.
A few I suggest are: 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/62eac0f0-32cb-499f-8ee8-950ffa75e471

- First the searching for a team should have text inside with "search for team" instead of being blank. Could be a separate PR 
- Next if the search team had a text an a new team is create, the text inside of the search team input should be set to "" have placeholder text of "search for team" (text can be something else just used this as an example).' See video for example

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/b2b611f2-9871-4589-9256-b2070d2e7742

- When a team is created a pop up should appear saying "team was successfully created" 
- When confirming the user to a team the modal should should disappear or a popup message saying "member added to team dismiss modal to continue." (text can be something else just used this as an example).

2023-07-14 05:45 UTC, AaronPersaud requested changes
Hi, I've tested and it looks good!

<b>Creating new team from "Create New User" Modal</b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/2bb5e5ef-72f9-4998-a6c4-fba2829e04cb

- can create new team
- can add user to existing team
- error thrown when trying to add to team that doesn't exist

However, I have a few suggestions.

1.) Users can create a team with a name that's already in use. This seems like a bad idea as the only way to differentiate between same named teams is their ID but I don't believe the user has access to that. Add an error popup that is displayed when a user clicks "Create New Team" with an already existing team name. See my comment for line 40.

2.) When a user tries to add a team that the user is already part of, the error "Hey, You need to pick a team first!" pops up which doesn't make sense for this scenario. You can probably fix this by adding lines 45-47 back and possibly changing the condition logic.

3.) Generally, dropdowns have a functionality that allow you to navigate through the options using the up and down arrow keys. You would need to add `onKeyUp` and `onKeyDown` attributes to the input component that change the selected value.

The last suggestion is just a personal suggestion, and it seems that the dropdown was already there before this ticket so it probably be done in a separate issue.

Another suggestion I thought of that fixes both 2.) and 3.) is disabling the "Confirm" button until the team is a valid team name (exists & not already added).

2023-07-14 05:45 UTC, AaronPersaud commented on src/components/UserProfile/TeamsAndProjects/AddTeamPopup.jsx
> -          {!isValidTeam && selectedTeam && (
Why was this block removed? (45-47) I feel like this message is necessary if the user chooses a team that the person is already assigned to.

2023-07-14 05:45 UTC, AaronPersaud commented on src/components/UserProfile/TeamsAndProjects/AddTeamPopup.jsx
> +  const onCreateTeam = async () => {
You should probably add another case in this function to check if there already exists a team with the given name.

2023-07-14 05:45 UTC, AaronPersaud commented on src/components/UserProfile/TeamsAndProjects/AddTeamPopup.jsx
> +  const [isValidNewTeam, onNewTeamValidation] = useState(true);
What is the point of this variable? Every time it is called its value is just getting modified, but is not used anywhere.

2023-07-14 05:45 UTC, AaronPersaud commented on src/components/UserProfile/TeamsAndProjects/AddTeamPopup.jsx
> +    onNewTeamValidation(true);
(Line 23) This setter gets called every time the new team name changes i.e each time a letter is typed. This seems costly and redundant, and unnecessary as its not being used for anything. You can probably remove it.

2023-07-14 06:17 UTC, siddharthmohite submitted a review, later dismissed
The functionality works as expected. But as others have pointed out it is confusing for a first-time user to understand it. The UI Suggestion given by @ramyaram2092 is amazing!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37925823/d61fb58f-d76d-4c3b-8455-971de04e7b88

2023-07-14 08:15 UTC, Jiangwei-shi commented
I tested your PR and works as intended great job!
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/86822956-41ba-44ce-9b9d-230d303a8acc)
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/4c8fcec5-b466-4049-87d8-50948a6181e6)

2023-07-14 19:09 UTC, HectorAgudelo approved these changes, later dismissed
The app was tested following the instructions on the PR, and it performs as expected. it works while creating an user, and also when the user is already created.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/26faeef0-a21b-4f3a-92ab-1156a48d721c

2023-07-15 04:42 UTC, shiva2096 submitted a review, later dismissed
The app was tested following the instructions on the PR and It performs as expected. 
UI suggestion above from the team looks better, but this also works fine.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/1957e72c-7ee9-457b-ac9a-9e674d95a901

2023-07-17 04:35 UTC, one-community commented
> I also have one more suggestion, When I first entered this interface, my initial instinct was to type a team name into the first line. However, it prompted me with an error message that read, "Hey, You need to pick a team first!". I believe this error message isn't suitable. In my opinion, the correct error message should be, "This team isn't found, you need to create a team first."

Yes, this message needs to be updated. 

1. "Hey, You need to pick a team first!" should show if they click "Confirm" without typing anything. 
2. If they type something that does not exist, please have it say, "Oops, this team doesn't exist! Create it if you want it."

2023-07-19 03:51 UTC, mahamakhan submitted a review, later dismissed
The mentioned function works fine with new and existing users from the admin user.

2023-07-19 10:46 UTC, igorrochadasilva commented
Hi @Chuehleo !
I hope you are well =D

I tested your PR and works as intended great job!

![997_01_create-team](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/57a0aba1-0888-419a-ac96-a30c72283281)
![997_02_team-created](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/fed0ee77-b655-4fbc-8d86-3d3fca9ae350)
![997_03_team-added](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/df338302-c75d-4142-ab82-4ebe7f54ee1c)

2023-07-20 18:34 UTC, sxiong5 submitted a review, later dismissed
Hey, I tested your changes, and they worked as intended.

<img width="1512" alt="Screenshot 2023-07-20 at 14 26 36" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/71919809-fd28-405f-b858-a3d40dae42a0">
<img width="1512" alt="Screenshot 2023-07-20 at 14 26 45" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/93be2e2b-3f47-4796-a84e-82311c6d2b8d">
<img width="1512" alt="Screenshot 2023-07-20 at 14 26 51" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/e022fd1c-a581-41e6-9336-a51631c1ece3">

# Suggestion
(Just a suggestion to improve the UI)
The operation, for now, is a little bit complicated, and the UI might be confusing.
The following is a component demo from MUI. We could learn from it since we have the same requirements.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/598d2e4d-e041-4de0-a60e-7b8194d36e46

2023-07-20 23:31 UTC, DavidC0126 commented
Hi @Chuehleo I tested your PR and everything works as intended. I am able to create a new team or assign to an existing team immediately. I also agree with the UI suggestions in this post. Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/c7101b12-b865-4f8c-b022-4d4654149e67

<img width="1677" alt="pr453" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/f77ea6c0-e0ac-4ae7-9ab0-2be6d824b532">

2023-07-21 03:55 UTC, ramyaram2092 commented
Hello @Chuehleo  could you check my comment in the backend PR  453?

2023-07-21 05:37 UTC, Shreyj14 commented
Hi @Chuehleo 

I tested this PR which is a dependency for #453 in the backend, it works as intended, and I was able to create the team. I can see that certain changes have been implemented which were part of the suggestions from the comments above. The changes I noticed which look good are -
1) When confirm is clicked without picking a team it displays the message "Hey, you need to pick a team first"
2) If a team exists it throws a message alerting that the team already exists.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/b6a3a250-6171-40b9-8a37-0aab0b680d72

2023-07-21 19:23 UTC, ramyaram2092 submitted a review, later dismissed
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/e9e3a4bd-f3ad-4944-964c-c3b19a274ab8

Works well. All the suggestions and feed back has been addressed 👍 

Testing Video

2023-07-22 23:49 UTC, vemanamadhu requested changes
Hello Leo,

Good job on creating the UI and the flow for creating a team while creating a user.
I have a couple of suggestions. 
I created a new team for the user but then I got confused for a second on what to do. 

I had a couple of suggestions about the flow of things
1. I was very confused about what to do after creating a team. I then realized that we had to go and add the team that we created back to the add-to team prompt. This flow in my opinion is not optimal for user experience. I feel like we need to revisit this flow.
Suggestions on different flows
- Once we create a team it auto-assigns the newly created team to the user
- We can remove the create new team prompt and incorporate that into the add-to-team prompt. If the team name we are typing doesn't exist we can show the create new team link in the drop down itself. We can do something like shown in the screenshot below.
- 
![PR # 997 review_suggestions](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13665284/f47e290f-bdb3-4944-a9d9-a2aa81464a2b)

2. I feel like the new team was created successfully and the team already exists message should show up in the pop-up and not on the side of the screen. It can be missed if you have a big screen you are viewing the app on.

Please let me know what you think. Apart from that everything seems to be working as expected. Good job

2023-07-24 02:38 UTC, one-community commented
> * Once we create a team it auto-assigns the newly created team to the user
> * We can remove the create new team prompt and incorporate that into the add-to-team prompt. If the team name we are typing doesn't exist we can show the create new team link in the drop down itself. We can do something like shown in the screenshot below.
> 
> ![PR # 997 review_suggestions](https://user-images.githubusercontent.com/13665284/255354876-f47e290f-bdb3-4944-a9d9-a2aa81464a2b.png)
> 
> 2. I feel like the new team was created successfully and the team already exists message should show up in the pop-up and not on the side of the screen. It can be missed if you have a big screen you are viewing the app on.

These are great suggestions, please integrate them

2023-07-24 06:59 UTC, Chuehleo commented
> These are great suggestions, please integrate them

No problem. I'll start working on integrating these suggestions.

2023-07-24 07:09 UTC, Chuehleo commented
> Hello Leo,
> 
> Good job on creating the UI and the flow for creating a team while creating a user. I have a couple of suggestions. I created a new team for the user but then I got confused for a second on what to do.
> 
> I had a couple of suggestions about the flow of things
> 
> 1. I was very confused about what to do after creating a team. I then realized that we had to go and add the team that we created back to the add-to team prompt. This flow in my opinion is not optimal for user experience. I feel like we need to revisit this flow.
>    Suggestions on different flows
> 
> * Once we create a team it auto-assigns the newly created team to the user
> * We can remove the create new team prompt and incorporate that into the add-to-team prompt. If the team name we are typing doesn't exist we can show the create new team link in the drop down itself. We can do something like shown in the screenshot below.
> 
> ![PR # 997 review_suggestions](https://user-images.githubusercontent.com/13665284/255354876-f47e290f-bdb3-4944-a9d9-a2aa81464a2b.png)
> 
> 2. I feel like the new team was created successfully and the team already exists message should show up in the pop-up and not on the side of the screen. It can be missed if you have a big screen you are viewing the app on.
> 
> Please let me know what you think. Apart from that everything seems to be working as expected. Good job

For the suggestion create new team prompt and incorporate that into the add-to-team prompt, do you mean that the drop down list including the create new team link should be able to pop the create new team modal up when the user click it?

2023-07-24 23:36 UTC, vemanamadhu commented
> So what I was thinking was:
There can be one prompt called Add Team.
When we search for a team --> A "create new team ->" option shows up in the drop-down. It can become active if a team with the same name doesn't exist.

So once we click on the "create new team ->" in the dropdown -- the backend process to create a new team can be triggered. Once the team gets created --> We can get a notification saying "Team created successfully".

And then there can be a confirm and cancel button at the bottom which confirms that we have assigned a team.

2023-07-25 17:49 UTC, eduvarjaor approved these changes, later dismissed
Hi @Chuehleo 

I tested this PR and everything works as intended. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/21b56847-ebb2-425d-8c5f-55b5abb1fa98

2023-07-27 04:53 UTC, AaronPersaud approved these changes, later dismissed
Hi, I've tested it again and you've addressed all my requests! Everything looks good!

1.) You cannot create duplicate team names anymore

<b>Creating team with a name that exists</b>

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/553a4512-7c0c-4660-a78c-08d2a5cc2d06)

2.) No incorrect error when trying to add to a team that user is already a part of 

<b>Adding to team new user is already on</b>

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/1a9d5ebf-4f93-42ed-9a8d-5354d55a84bd)

- no message appears at all if you attempt this, but this is a very specific edge case where the toast isn't super necessary

3.) Outside of scope of the PR (`onKeyUp` and `onKeyDown` for dropdown)

Great job!

2023-07-27 23:58 UTC, Indujaks approved these changes, later dismissed
Tested Changes, Works as Expected!
<img width="929" alt="Screenshot 2023-07-27 at 4 57 12 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/11251850/929386fc-407b-48d7-8aec-b9bd02bd98d5">

2023-07-28 16:33 UTC, yaow62023 approved these changes, later dismissed
After testing this PR, I found that the functionalities mentioned in the description are working as expected. However, I have a couple of suggestions:
1. After creating a team, is it possible to automatically join the team? This would eliminate the need for a second step to assign oneself to the team.
2. Shouldn't team names be unique? In the video, I was able to create multiple teams with the same name and join them. This could potentially lead to conflicts in the future.

Feature test video:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/146370da-1978-4d75-a6f4-5bbaa0b466e3

Video for add to team which same name:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/838942ac-10a4-4f0e-b49b-5d82c9f1f923

2023-07-29 00:58 UTC, zuhang2000 approved these changes, later dismissed
I have tested both the front-end and back-end. The functionality are working as expected.

More specifically, I did the test on "Create New Team" and "Add to a Team". I created several new teams with different format of team name and try to see whether it can successfully detect all kinds of duplicate team name. It works as expected and it would disallow creating a team with the same name as an existing team.

Also as @one-community suggested previously, I think those suggestions would make this feature even better. 

But I do notice many people suggest about adding the user to the team once the team is created. I think it's gonna be a problem if the admin account is creating a new user and at the same time also creating a new team. Which person should be added to this new team? The new user or the admin or both of them? I think more considerations should be made on how to handle this case. But if creating a new team elsewhere, adding the user to the new team once the team is created would be a great feature.

<img width="1099" alt="Screen Shot 2023-07-28 at 5 17 49 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/5f48c66e-6c61-449d-8705-85ab96770cf4">
<img width="1162" alt="Screen Shot 2023-07-28 at 5 24 55 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/facb0ce3-ab5f-44a1-b5fa-d2af9e227454">

In this picture, I'm trying to add the person who is already in the team to the team again. It is great that the error pops up which does not allow me to do so. It's just gonna be better if the error message could be "The person is already in the team". I think it would be confusing in the case that if there are a lot of people in the team, it would be hard to figure out whether I made the name wrong or the person is already in the team. This is only my suggestion. All the functionality is working as expected. 
<img width="957" alt="Screen Shot 2023-07-28 at 5 28 29 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/8d60f03c-39b7-4cb8-ad70-0dad00dc4a5f">

Good job!

2023-07-30 03:10 UTC, mahamakhan approved these changes, later dismissed
Tested the functionality and was able to create a team and add it successfully. 

<img width="350" alt="image" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/a978c347-c060-4c4e-9935-f2beb74bb2c5">
<img width="368" alt="Screenshot 2023-07-29 200615" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/bf7827fd-aa28-49f0-a9f5-4d5059a47b31">
<img width="386" alt="Screenshot 2023-07-29 200519" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/65e33c58-d536-481f-8f74-4d36e5668d0e">
<img width="347" alt="Screenshot 2023-07-29 200714" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/c1b5bf33-aa0c-470c-963b-eb8251d3e4f6">

2023-08-01 04:59 UTC, ThapeloMasasa approved these changes, later dismissed
The functionality works as intended and the changes made to the code are great

<img width="738" alt="Screenshot 2023-07-31 at 9 45 44 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/a953f177-12d4-469f-ae30-075322442799">

<img width="622" alt="Screenshot 2023-07-31 at 9 46 04 PM" src="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/7824527d-56b2-4b78-be79-1e29ed9499d2">

2023-08-04 05:22 UTC, winghojackyli approved these changes, later dismissed
Hello @Chuehleo , I can create team and add the new user into the new created team while creating user. It works well with the backend https://github.com/OneCommunityGlobal/HGNRest/pull/453


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/fb2f9b4a-5004-4db5-ac30-99c295a620d5

2023-08-15 17:52 UTC, veronicacheng2 commented
Hi @Chuehleo, I tried testing the PR but 'Create New Team' input and button do not show up. 

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/a830d4be-98ee-4908-a78b-6debb42b870a)

2023-08-15 18:06 UTC, Chuehleo commented
> Hi @Chuehleo, I tried testing the PR but 'Create New Team' input and button do not show up.
> 
> ![image](https://user-images.githubusercontent.com/95119686/260794210-a830d4be-98ee-4908-a78b-6debb42b870a.png)

Hi @veronicacheng2 , I have change the code to what @vemanamadhu had requested, so there won't be a create new team button, just simply type the team you want to create and the dropdown list will allow you to create it if it doesn't exist. The video is also provided in the description of this PR.

2023-08-15 18:38 UTC, veronicacheng2 approved these changes
> > Hi @Chuehleo, I tried testing the PR but 'Create New Team' input and button do not show up.
> > ![image](https://user-images.githubusercontent.com/95119686/260794210-a830d4be-98ee-4908-a78b-6debb42b870a.png)
> 
> Hi @veronicacheng2 , I have change the code to what @vemanamadhu had requested, so there won't be a create new team button, just simply type the team you want to create and the dropdown list will allow you to create it if it doesn't exist. The video is also provided in the description of this PR.

Hi @Chuehleo, thank you for your prompt reply. I have tested again according to the new instructions. Everything works perfectly.

 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/b6f2d9bf-858d-48ff-841b-8f145c4ef48b

2023-08-18 18:32 UTC, harshidad approved these changes, later dismissed
This code working as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/f03921fa-5c85-4053-acbe-341c23fe70e9

2023-08-19 20:13 UTC, winghojackyli approved these changes
Hi @Chuehleo , I've tested this updated PR and it works as intended. The new create team method works well with the UI. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/73fef416-7f71-4e04-9c7f-8e2bd65d03f5

2023-08-25 01:17 UTC, Jiyuanxia commented
Hi @Chuehleo, I have reviewed your pull request and tested it. It works as you intended. Well done!

![Screenshot 2023-08-24 211604](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/6f8a5f4d-5065-470a-9085-a0d868ed26ca)
![Screenshot 2023-08-24 211617](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92963742/3090fee8-5c18-495d-870d-056aa57f0f4e)

2023-08-26 19:39 UTC, yunshan111 approved these changes, later dismissed
Tested this PR, LGTM!

2023-08-27 00:55 UTC, Shubhu0 commented
Reviewed the PR and all its changes, works as intended

2023-08-27 01:05 UTC, Shubhu0 commented
Reviewed this PR. Working as intended. Great job!!

2023-09-03 03:44 UTC, zuhang2000 submitted a review, later dismissed
Hi Leo! I'm following up on my previous review on your PR. This PR now works as expected! This functionality and new feature is good. Here below is my recording on the test.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/7147f0d9-dd27-486c-bf1c-0a71ad9f87b2

2023-09-05 04:25 UTC, one-community commented
Be sure to pull the latest code so these formatting issues that have already been fixed are included: 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/18335122/856824ae-657a-4e66-9f7a-825b35db6383)

If there were a way to add that "Create" button elegantly to the right of the word "Teams", that would be nice too. If keeping it below, please change label to "Create Team" and make it the same size as the "Assign Team" button

2023-09-07 19:12 UTC, Chuehleo commented
> Be sure to pull the latest code so these formatting issues that have already been fixed are included: ![image](https://user-images.githubusercontent.com/18335122/265584665-856824ae-657a-4e66-9f7a-825b35db6383.png)
> 
> If there were a way to add that "Create" button elegantly to the right of the word "Teams", that would be nice too. If keeping it below, please change label to "Create Team" and make it the same size as the "Assign Team" button
Do you mean the "Create" button of the create user modal or the one after I click the "Assign Team" button. For the lastest code, there is only a dropdown option to create the team so there won't be be a "Create" button.
![Screenshot 2023-09-07 121127](https://github.com/OneComm
![KYnmEF13](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/924064a0-fd9e-48a7-955c-f0edb6554b1e)
unityGlobal/HighestGoodNetworkApp/assets/122568562/ac42011d-0c09-4a34-ba26-eceb17765920)

2023-09-15 22:04 UTC, Shiwani99 submitted a review, later dismissed
Hi,
Great work. I tested your PR and it works as expected. I am attaching a screen recording of how it looks in my end.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/6732eaa5-0a80-4088-9c5e-6960fa273c23

2023-09-16 02:45 UTC, wantingxu7 approved these changes, later dismissed
Hi,
I've tested and it works as intended. Please find in the recording below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/2b2764cb-9372-4973-8e17-934c9d06f7e5

2023-09-28 02:06 UTC, Shubhu0 commented
Hi @Chuehleo, I have reviewed your pull request and tested it and it works as you intended. Well done!

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/dc42a18c-5a8d-4e4f-908d-82680d26f5b1)

2023-10-01 00:17 UTC, RheaWu1212 commented
'create new team' not displayed 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/2d064adc-2b89-4746-acf8-7ceaa3e258e0

2023-10-07 19:01 UTC, JeffLi117 approved these changes, later dismissed
Changes work as intended. 

When the text within the search bar does not directly match a team name, there is an option to "Create new team" with said name (testing997 team was created already, I took this screenshot after I had tested everything else): 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/0e672ca5-cf60-45e6-803e-673e919ec5b5)

Successfully created a team (with respective toast):
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/2d5e4087-7a04-46d7-85a0-14de6b1b01e7)

Successfully assigned the newly created team to my new user:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/29b0074a-0396-4741-94bf-50fcbda4053d)

Double checking that my new team is in the system and the new user is also listed within said team:
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/e602d497-7cfc-425c-87b7-ebd16721f6a9)

Great job!

2023-10-09 21:21 UTC, yi-lin-1234 submitted a review, later dismissed
Hi, I tested this PR with #453, and it works as intended. Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/f1bab9a8-3fa3-401e-8731-924d415e3330

2023-10-11 19:56 UTC, StrawberryCalpico submitted a review, later dismissed
Hi I tested this PR, it worked perfectly, Good job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/ab49a025-ad43-4c27-9704-b2849dc40f02

2023-10-21 09:37 UTC, malikjahanzaib approved these changes
Hi @Chuehleo, I tested this PR locally and it works great. I was able to create a new team from the user creation popup and verified the team existed in the "Teams" tab. Great job!!!

Test Rec:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/69814dbd-f39f-42b5-b867-76b88f0cfa41

2023-10-26 00:08 UTC, kavya151 commented
Hi @Chuehleo I have tested this PR locally and it works great. I was able to create new team and also the created team exists in the team and doesn't allow creating duplicate teams.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/35066222-9d31-43e8-b879-29f1a06ea18d

2023-10-26 00:13 UTC, kavya151 commented
Hi @Chuehleo . I have tested this PR locally and it allows me to successfully create  new team and also the created team is visible in the teams.

Uploading Screen Recording 2023-10-25 at 5.12.02 PM.mov…

2023-10-27 15:39 UTC, emunkh404 commented
Hi, I tested your work, Great job!
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/e2db7b01-4a72-469e-bd6e-520f7b23b980)

2023-10-27 17:45 UTC, kavya151 commented
Thank you

On Fri, Oct 27, 2023, 8:39 AM emunkh404 ***@***.***> wrote:

> Hi, I tested your work, Great job!
> [image: image]
> <https://user-images.githubusercontent.com/145945063/278691913-e2db7b01-4a72-469e-bd6e-520f7b23b980.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/997#issuecomment-1783126898>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOX2ECPMFQRN35NSGFDKMFLYBPIU5AVCNFSM6AAAAAA2HFLOVOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBTGEZDMOBZHA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-11-30 21:52 UTC, navneeeth requested changes
Hey @Chuehleo! The functionality works as expected and the team creation happens hassle-free and the user can be added to the newly created team as verified from the Teams page. Good implementation!

## Test Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/70ab7fe6-805b-4084-8983-160cb39689bc


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/64e394b5-c36f-411d-99bd-b86dee4ad336

## Issue
However, right after the team is created, there is an issue with clicking on 'Confirm' which does not recognize the recently created team until it is searched again as shown here: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/8d4d7748-8a6b-4dc1-a187-d475399023ea

Please fix this such that after team creation, the 'Confirm' functionality works without having to search again for the team name. Thank you!

2023-12-04 07:25 UTC, navneeeth approved these changes
Hello, @Chuehleo! Great job on addressing the issue! The functionality works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/d45c6afd-d48a-42f6-b01e-8fc036f98691

2023-12-05 01:01 UTC, one-community commented
Thank you all, merging!

2023-12-05 01:01 UTC, merged